var searchData=
[
  ['a_20configuration_20file_0',['a Configuration File',['../index.html#configuration-via-a-configuration-file',1,'Configuration via a Configuration File'],['../index.html#default-name-of-a-configuration-file',1,'Default Name of a Configuration File']]],
  ['a_20la_20node_20js_20express_1',['Highlevel WEB-API a&apos;la Node.JS-Express',['../index.html#highlevel-web-api-ala-nodejs-express',1,'']]],
  ['a_20sdk_2',['Choose and Download a SDK',['../index.html#choose-and-download-a-sdk',1,'']]],
  ['all_20configuration_20items_3',['List of all Configuration Items',['../index.html#list-of-all-configuration-items',1,'']]],
  ['all_20constructors_20of_20socketclient_20classes_4',['All Constructors of &lt;span class=&quot;tt&quot;&gt;SocketClient&lt;/span&gt; Classes',['../index.html#all-constructors-of-socketclient-classes',1,'']]],
  ['all_20constructors_20of_20socketserver_20classes_5',['All Constructors of &lt;span class=&quot;tt&quot;&gt;SocketServer&lt;/span&gt; Classes',['../index.html#all-constructors-of-socketserver-classes',1,'']]],
  ['already_20existing_20instances_6',['Attaching the Callbacks to already existing Instances',['../index.html#attaching-the-callbacks-to-already-existing-instances',1,'']]],
  ['an_20application_7',['Using More Than One Instance in an Application',['../index.html#using-more-than-one-instance-in-an-application',1,'']]],
  ['an_20echo_20application_8',['An &quot;Echo&quot; Application',['../index.html#an-echo-application',1,'']]],
  ['anatomy_20of_20the_20command_20line_20interface_9',['Anatomy of the Command Line Interface',['../index.html#anatomy-of-the-command-line-interface',1,'']]],
  ['and_20client_10',['Main Applications for Server and Client',['../index.html#main-applications-for-server-and-client',1,'']]],
  ['and_20client_20information_20host_20name_20ip_20port_20ssl_20tls_20information_11',['Extract Server and Client Information (host name, IP, port, SSL/TLS information)',['../index.html#extract-server-and-client-information-host-name-ip-port-ssltls-information',1,'']]],
  ['and_20dependencies_12',['and Dependencies',['../index.html#requirements-and-dependencies',1,'Requirements and Dependencies'],['../index.html#requirements-and-dependencies-1',1,'Requirements and Dependencies']]],
  ['and_20download_20a_20sdk_13',['Choose and Download a SDK',['../index.html#choose-and-download-a-sdk',1,'']]],
  ['and_20echoclient_14',['CMakeLists.txt file for Building and Installing our &lt;em&gt;echoserver&lt;/em&gt; and &lt;em&gt;echoclient&lt;/em&gt;',['../index.html#cmakeliststxt-file-for-building-and-installing-our-echoserver-and-echoclient',1,'']]],
  ['and_20features_15',['Design Decisions and Features',['../index.html#design-decisions-and-features',1,'']]],
  ['and_20hardware_16',['Supported Systems and Hardware',['../index.html#supported-systems-and-hardware',1,'']]],
  ['and_20http_20client_20api_17',['Basic HTTP-Server and HTTP-Client API',['../index.html#basic-http-server-and-http-client-api',1,'']]],
  ['and_20installing_20our_20echoserver_20and_20echoclient_18',['CMakeLists.txt file for Building and Installing our &lt;em&gt;echoserver&lt;/em&gt; and &lt;em&gt;echoclient&lt;/em&gt;',['../index.html#cmakeliststxt-file-for-building-and-installing-our-echoserver-and-echoclient',1,'']]],
  ['and_20ipv6_20socketserver_19',['Specific &lt;em&gt;socket&lt;/em&gt; Options for IPv4 and IPv6 &lt;em&gt;SocketServer&lt;/em&gt;',['../index.html#specific-socket-options-for-ipv4-and-ipv6-socketserver',1,'']]],
  ['and_20its_20dependencies_20',['Install the SNode.C Package and its Dependencies',['../index.html#install-the-snodec-package-and-its-dependencies',1,'']]],
  ['and_20mqtt_20client_20api_21',['Basic MQTT-Server and MQTT-Client API',['../index.html#basic-mqtt-server-and-mqtt-client-api',1,'']]],
  ['and_20socketclient_22',['Specific &lt;em&gt;socket&lt;/em&gt; Options for IPv6 &lt;em&gt;SocketServer&lt;/em&gt; and &lt;em&gt;SocketClient&lt;/em&gt;',['../index.html#specific-socket-options-for-ipv6-socketserver-and-socketclient',1,'']]],
  ['and_20socketclient_20classes_23',['and SocketClient Classes',['../index.html#common-aspects-of-socketserver-and-socketclient-classes',1,'Common Aspects of &lt;span class=&quot;tt&quot;&gt;SocketServer&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;SocketClient&lt;/span&gt; Classes'],['../index.html#constructors-of-socketserver-and-socketclient-classes',1,'Constructors of &lt;span class=&quot;tt&quot;&gt;SocketServer&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;SocketClient&lt;/span&gt; Classes'],['../index.html#existing-socketserver-and-socketclient-classes',1,'Existing &lt;span class=&quot;tt&quot;&gt;SocketServer&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;SocketClient&lt;/span&gt; Classes']]],
  ['and_20socketclient_20instances_24',['and SocketClient Instances',['../index.html#socketserver-and-socketclient-instances',1,'&lt;span class=&quot;tt&quot;&gt;SocketServer&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;SocketClient&lt;/span&gt; Instances'],['../index.html#common-socket-options-for-socketserver-and-socketclient-instances',1,'Common &lt;em&gt;socket&lt;/em&gt; Options for &lt;em&gt;SocketServer&lt;/em&gt; and &lt;em&gt;SocketClient&lt;/em&gt; Instances']]],
  ['api_25',['API',['../index.html#basic-http-server-and-http-client-api',1,'Basic HTTP-Server and HTTP-Client API'],['../index.html#basic-mqtt-server-and-mqtt-client-api',1,'Basic MQTT-Server and MQTT-Client API'],['../index.html#configuration-using-the-c-api',1,'Configuration using the C++ API']]],
  ['api_20a_20la_20node_20js_20express_26',['Highlevel WEB-API a&apos;la Node.JS-Express',['../index.html#highlevel-web-api-ala-nodejs-express',1,'']]],
  ['apis_27',['Application Leyer Protocols APIs',['../index.html#application-leyer-protocols-apis',1,'']]],
  ['application_28',['Application',['../index.html#an-echo-application',1,'An &quot;Echo&quot; Application'],['../index.html#echo-client-main-application',1,'Echo-Client Main Application'],['../index.html#echo-server-main-application',1,'Echo-Server Main Application'],['../index.html#using-more-than-one-instance-in-an-application',1,'Using More Than One Instance in an Application']]],
  ['application_20configuration_29',['Application Configuration',['../index.html#application-configuration',1,'']]],
  ['application_20layer_30',['Application Layer',['../index.html#application-layer',1,'']]],
  ['application_20leyer_20protocols_20apis_31',['Application Leyer Protocols APIs',['../index.html#application-leyer-protocols-apis',1,'']]],
  ['applications_32',['Example Applications',['../index.html#example-applications',1,'']]],
  ['applications_20for_20server_20and_20client_33',['Main Applications for Server and Client',['../index.html#main-applications-for-server-and-client',1,'']]],
  ['architecture_34',['Fundamental Architecture',['../index.html#fundamental-architecture',1,'']]],
  ['arm_35',['Installation on Debian Style Systems (x86-64, Arm)',['../index.html#installation-on-debian-style-systems-x86-64-arm',1,'']]],
  ['aspects_20of_20socketserver_20and_20socketclient_20classes_36',['Common Aspects of &lt;span class=&quot;tt&quot;&gt;SocketServer&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;SocketClient&lt;/span&gt; Classes',['../index.html#common-aspects-of-socketserver-and-socketclient-classes',1,'']]],
  ['attaching_20the_20callbacks_20during_20instance_20creation_37',['Attaching the Callbacks during Instance Creation',['../index.html#attaching-the-callbacks-during-instance-creation',1,'']]],
  ['attaching_20the_20callbacks_20to_20already_20existing_20instances_38',['Attaching the Callbacks to already existing Instances',['../index.html#attaching-the-callbacks-to-already-existing-instances',1,'']]]
];
