var searchData=
[
  ['main_20application_0',['Main Application',['../index.html#echo-client-main-application',1,'Echo-Client Main Application'],['../index.html#echo-server-main-application',1,'Echo-Server Main Application']]],
  ['main_20applications_20for_20server_20and_20client_1',['Main Applications for Server and Client',['../index.html#main-applications-for-server-and-client',1,'']]],
  ['mandatory_2',['Mandatory',['../index.html#mandatory',1,'Mandatory'],['../index.html#mandatory-1',1,'Mandatory']]],
  ['mariadb_3',['MariaDB',['../index.html#mariadb',1,'']]],
  ['methods_4',['Methods',['../index.html#bluetooth-l2cap-specific-connect-methods',1,'Bluetooth L2CAP specific &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Methods'],['../index.html#bluetooth-l2cap-specific-listen-methods',1,'Bluetooth L2CAP specific &lt;span class=&quot;tt&quot;&gt;listen()&lt;/span&gt; Methods'],['../index.html#bluetooth-rfcomm-specific-connect-methods',1,'Bluetooth RFCOMM specific &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Methods'],['../index.html#bluetooth-rfcomm-specific-listen-methods',1,'Bluetooth RFCOMM specific &lt;span class=&quot;tt&quot;&gt;listen()&lt;/span&gt; Methods'],['../index.html#common-connect-methods',1,'Common &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Methods'],['../index.html#common-listen-methods',1,'Common &lt;span class=&quot;tt&quot;&gt;listen()&lt;/span&gt; Methods'],['../index.html#connect-methods',1,'Connect Methods'],['../index.html#ipv4-specific-connect-methods',1,'IPv4 specific &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Methods'],['../index.html#ipv4-specific-listen-methods',1,'IPv4 specific &lt;span class=&quot;tt&quot;&gt;listen()&lt;/span&gt; Methods'],['../index.html#ipv6-specific-connect-methods',1,'IPv6 specific &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Methods'],['../index.html#ipv6-specific-listen-methods',1,'IPv6 specific &lt;span class=&quot;tt&quot;&gt;listen()&lt;/span&gt; Methods'],['../index.html#listen-methods',1,'Listen Methods'],['../index.html#most-important-common-socketconnection-methods',1,'Most Important common &lt;span class=&quot;tt&quot;&gt;SocketConnection&lt;/span&gt; Methods'],['../index.html#unix-domain-socket-specific-connect-methods',1,'Unix Domain Socket specific &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Methods'],['../index.html#unix-domain-socket-specific-listen-methods',1,'Unix Domain Socket specific &lt;span class=&quot;tt&quot;&gt;listen()&lt;/span&gt; Methods']]],
  ['methods_20when_20no_20configuration_20file_20exists_5',['Methods when no Configuration File exists',['../index.html#using-the-parameterless-connect-methods-when-no-configuration-file-exists',1,'Using the Parameterless &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Methods when no Configuration File exists'],['../index.html#using-the-parameterless-listen-methods-when-no-configuration-file-exists',1,'Using the Parameterless &lt;span class=&quot;tt&quot;&gt;listen()&lt;/span&gt; Methods when no Configuration File exists']]],
  ['minimum_20required_20compiler_20versions_6',['Minimum required Compiler Versions',['../index.html#minimum-required-compiler-versions',1,'']]],
  ['more_20than_20one_20instance_20in_20an_20application_7',['Using More Than One Instance in an Application',['../index.html#using-more-than-one-instance-in-an-application',1,'']]],
  ['most_20important_20common_20socketconnection_20methods_8',['Most Important common &lt;span class=&quot;tt&quot;&gt;SocketConnection&lt;/span&gt; Methods',['../index.html#most-important-common-socketconnection-methods',1,'']]],
  ['mqtt_20client_20api_9',['Basic MQTT-Server and MQTT-Client API',['../index.html#basic-mqtt-server-and-mqtt-client-api',1,'']]],
  ['mqtt_20over_20websocket_10',['MQTT Over WebSocket',['../index.html#mqtt-over-websocket',1,'']]],
  ['mqtt_20server_20and_20mqtt_20client_20api_11',['Basic MQTT-Server and MQTT-Client API',['../index.html#basic-mqtt-server-and-mqtt-client-api',1,'']]]
];
