SNode.C: core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args > Class Template Reference
core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args > Class Template Reference
#include <SocketServer.h>
Classes
struct Context
Public Types
using SocketConnection = typename SocketAcceptor::SocketConnection
using SocketAddress = typename SocketAcceptor::SocketAddress
using Config = typename SocketAcceptor::Config
Public Types inherited from core::socket::Socket< SocketAcceptorT::Config >
using Config
Public Member Functions
SocketServer (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, Args &&... args)
SocketServer (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, Args &&... args)
SocketServer (const std::string &name, Args &&... args)
SocketServer (Args &&... args)
const SocketServer & listen (const std::function< void(const SocketAddress &, core::socket::State)> &onStatus) const
const SocketServer & listen (const SocketAddress &localAddress, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus) const
const SocketServer & listen (const SocketAddress &localAddress, int backlog, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus) const
std::function< void(SocketConnection *)> & getOnConnect () const
const SocketServer & setOnConnect (const std::function< void(SocketConnection *)> &onConnect, bool initialize=false) const
std::function< void(SocketConnection *)> & getOnConnected () const
const SocketServer & setOnConnected (const std::function< void(SocketConnection *)> &onConnected, bool initialize=false) const
std::function< void(SocketConnection *)> & getOnDisconnect () const
SocketServer & setOnDisconnect (const std::function< void(SocketConnection *)> &onDisconnect, bool initialize=false)
std::function< void(const std::shared_ptr< AutoConnectControl > &)> & getOnAutoConnectControl ()
const SocketServer & setOnAutoConnectControl (const std::function< void(const std::shared_ptr< AutoConnectControl > &)> &onAutoConnectControl, bool initialize=false) const
std::function< void(core::eventreceiver::AcceptEventReceiver *)> & getOnInitState () const
const SocketServer & setOnInitState (const std::function< void(core::eventreceiver::AcceptEventReceiver *)> &onInitState, bool initialize=false) const
std::shared_ptr< SocketContextFactory > getSocketContextFactory () const
Public Member Functions inherited from core::socket::Socket< SocketAcceptorT::Config >
Socket (const std::string &name)
virtual ~Socket ()
Config & getConfig () const
Private Types
using SocketAcceptor = SocketAcceptorT
using SocketContextFactory = SocketContextFactoryT
using Super = core::socket::Socket<typename SocketAcceptor::Config>
Private Member Functions
SocketServer (const std::shared_ptr< Config > &config, const std::shared_ptr< SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> onConnect, const std::function< void(SocketConnection *)> onConnected, const std::function< void(SocketConnection *)> onDisconnect)
SocketServer (const std::shared_ptr< Config > &config, const std::shared_ptr< Context > &sharedContext)
const SocketServer & realListen (const std::function< void(const SocketAddress &, core::socket::State)> &onStatus, unsigned int tries, double retryTimeoutScale) const
Private Attributes
std::shared_ptr< Context > sharedContext
Additional Inherited Members
Protected Member Functions inherited from core::socket::Socket< SocketAcceptorT::Config >
Socket & operator= (const Socket &)=default
Protected Attributes inherited from core::socket::Socket< SocketAcceptorT::Config >
const std::shared_ptr< Config > config
Detailed Description
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args>
requires std::is_base_of_v<core::eventreceiver::AcceptEventReceiver, SocketAcceptorT> && std::is_base_of_v<core::socket::stream::SocketContextFactory, SocketContextFactoryT>
class core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >
Definition at line 68 of file SocketServer.h.
Member Typedef Documentation
Config
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> using core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Config = typename SocketAcceptor::Config
Definition at line 78 of file SocketServer.h.
SocketAcceptor
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> using core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::SocketAcceptor = SocketAcceptorT private
Definition at line 70 of file SocketServer.h.
SocketAddress
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> using core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::SocketAddress = typename SocketAcceptor::SocketAddress
Definition at line 77 of file SocketServer.h.
SocketConnection
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> using core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::SocketConnection = typename SocketAcceptor::SocketConnection
Definition at line 76 of file SocketServer.h.
SocketContextFactory
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> using core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::SocketContextFactory = SocketContextFactoryT private
Definition at line 71 of file SocketServer.h.
Super
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> using core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Super = core::socket::Socket<typename SocketAcceptor::Config> private
Definition at line 73 of file SocketServer.h.
Constructor & Destructor Documentation
SocketServer() [1/6]
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::SocketServer (const std::shared_ptr< Config > & config, const std::shared_ptr< SocketContextFactory > & socketContextFactory, const std::function< void(SocketConnection *)> onConnect, const std::function< void(SocketConnection *)> onConnected, const std::function< void(SocketConnection *)> onDisconnect) inline private
Definition at line 107 of file SocketServer.h.
            : Super(config)
            , sharedContext(std::make_shared<Context>(socketContextFactory, onConnect, onConnected, onDisconnect)) {
        }
References sharedContext.
SocketServer() [2/6]
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::SocketServer (const std::shared_ptr< Config > & config, const std::shared_ptr< Context > & sharedContext) inline private
Definition at line 116 of file SocketServer.h.
            : Super(config)
            , sharedContext(sharedContext) {
        }
References sharedContext.
SocketServer() [3/6]
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::SocketServer (const std::string & name, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, Args &&... args) inline
Definition at line 122 of file SocketServer.h.
            : Super(name)
            , sharedContext(std::make_shared<Context>(
                  std::make_shared<SocketContextFactory>(std::forward<Args>(args)...),
                  [onConnect](SocketConnection* socketConnection) { // onConnect
                      LOG(DEBUG) << socketConnection->getConnectionName() << ": OnConnect";
                      LOG(DEBUG) << "  Local: " << socketConnection->getLocalAddress().toString();
                      LOG(DEBUG) << "   Peer: " << socketConnection->getRemoteAddress().toString();
                      if (onConnect) {
                          onConnect(socketConnection);
                      }
                  },
                  [onConnected](SocketConnection* socketConnection) { // onConnected
                      LOG(DEBUG) << socketConnection->getConnectionName() << ": OnConnected";
                      LOG(DEBUG) << "  Local: " << socketConnection->getLocalAddress().toString();
                      LOG(DEBUG) << "   Peer: " << socketConnection->getRemoteAddress().toString();
                      if (onConnected) {
                          onConnected(socketConnection);
                      }
                  },
                  [onDisconnect](SocketConnection* socketConnection) { // onDisconnect
                      LOG(DEBUG) << socketConnection->getConnectionName() << ": OnDisconnect";
                      LOG(DEBUG) << "            Local: " << socketConnection->getLocalAddress().toString();
                      LOG(DEBUG) << "             Peer: " << socketConnection->getRemoteAddress().toString();
                      LOG(DEBUG) << "     Online Since: " << socketConnection->getOnlineSince();
                      LOG(DEBUG) << "  Online Duration: " << socketConnection->getOnlineDuration();
                      LOG(DEBUG) << "     Total Queued: " << socketConnection->getTotalQueued();
                      LOG(DEBUG) << "       Total Sent: " << socketConnection->getTotalSent();
                      LOG(DEBUG) << "      Write Delta: " << socketConnection->getTotalQueued() - socketConnection->getTotalSent();
                      LOG(DEBUG) << "       Total Read: " << socketConnection->getTotalRead();
                      LOG(DEBUG) << "  Total Processed: " << socketConnection->getTotalProcessed();
                      LOG(DEBUG) << "       Read Delta: " << socketConnection->getTotalRead() - socketConnection->getTotalProcessed();
                      if (onDisconnect) {
                          onDisconnect(socketConnection);
                      }
                  })) {
        }
References sharedContext.
SocketServer() [4/6]
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::SocketServer (const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, Args &&... args) inline
Definition at line 172 of file SocketServer.h.
            : SocketServer("", onConnect, onConnected, onDisconnect, std::forward<Args>(args)...) {
        }
SocketServer() [5/6]
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::SocketServer (const std::string & name, Args &&... args) inline
Definition at line 179 of file SocketServer.h.
            : SocketServer(name, {}, {}, {}, std::forward<Args>(args)...) {
        }
SocketServer() [6/6]
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::SocketServer (Args &&... args) inline explicit
Definition at line 183 of file SocketServer.h.
            : SocketServer("", std::forward<Args>(args)...) {
        }
Member Function Documentation
getOnAutoConnectControl()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::function< void(const std::shared_ptr< AutoConnectControl > &)> & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::getOnAutoConnectControl () inline
Definition at line 317 of file SocketServer.h.
{
            return sharedContext->onAutoConnectControl;
        }
References sharedContext.
getOnConnect()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::function< void(SocketConnection *)> & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::getOnConnect () const inline
Definition at line 274 of file SocketServer.h.
{
            return sharedContext->onConnect;
        }
References sharedContext.
getOnConnected()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::function< void(SocketConnection *)> & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::getOnConnected () const inline
Definition at line 288 of file SocketServer.h.
{
            return sharedContext->onConnected;
        }
References sharedContext.
getOnDisconnect()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::function< void(SocketConnection *)> & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::getOnDisconnect () const inline
Definition at line 302 of file SocketServer.h.
{
            return sharedContext->onDisconnect;
        }
References sharedContext.
getOnInitState()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::function< void(core::eventreceiver::AcceptEventReceiver *)> & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::getOnInitState () const inline
Definition at line 340 of file SocketServer.h.
{
            return sharedContext->onInitState;
        }
References sharedContext.
getSocketContextFactory()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::shared_ptr< SocketContextFactory > core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::getSocketContextFactory () const inline
Definition at line 356 of file SocketServer.h.
{
            return sharedContext->socketContextFactory;
        }
References sharedContext.
listen() [1/3]
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> const SocketServer & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::listen (const SocketAddress & localAddress, const std::function< void(const SocketAddress &, core::socket::State)> & onStatus) const inline
Definition at line 259 of file SocketServer.h.
{
            Super::config->Local::setSocketAddress(localAddress);
            return listen(onStatus);
        }
listen() [2/3]
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> const SocketServer & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::listen (const SocketAddress & localAddress, int backlog, const std::function< void(const SocketAddress &, core::socket::State)> & onStatus) const inline
Definition at line 266 of file SocketServer.h.
{
            Super::config->Local::setBacklog(backlog);
            return listen(localAddress, onStatus);
        }
listen() [3/3]
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> const SocketServer & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::listen (const std::function< void(const SocketAddress &, core::socket::State)> & onStatus) const inline
Definition at line 255 of file SocketServer.h.
{
            return realListen(onStatus, 0, 1);
        }
References realListen().
Referenced by main(), express::legacy::in6::Server(), express::legacy::in::Server(), express::legacy::rc::Server(), express::legacy::un::Server(), express::tls::in6::Server(), express::tls::in::Server(), express::tls::rc::Server(), and express::tls::un::Server().
realListen()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> const SocketServer & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::realListen (const std::function< void(const SocketAddress &, core::socket::State)> & onStatus, unsigned int tries, double retryTimeoutScale) const inline private
Definition at line 188 of file SocketServer.h.
{
            core::EventReceiver::atNextTick(
                [config = this->config, sharedContext = this->sharedContext, onStatus, tries, retryTimeoutScale] {
                    LOG(DEBUG) << config->getInstanceName() << ": Initiating listen";
                    if (core::SNodeC::state() == core::State::RUNNING || core::SNodeC::state() == core::State::INITIALIZED) {
                        auto autoConnectControl = sharedContext->autoConnectControl;
                        if (!autoConnectControl) {
                            autoConnectControl = std::make_shared<AutoConnectControl>();
                            sharedContext->autoConnectControl = autoConnectControl;
                            if (sharedContext->onAutoConnectControl) {
                                sharedContext->onAutoConnectControl(autoConnectControl);
                            }
                        }
                        new SocketAcceptor(
                            sharedContext->socketContextFactory,
                            sharedContext->onConnect,
                            sharedContext->onConnected,
                            sharedContext->onDisconnect,
                            sharedContext->onInitState,
                            [config, sharedContext, autoConnectControl, onStatus, tries, retryTimeoutScale](
                                const SocketAddress& socketAddress, core::socket::State state) {
                                const bool retryFlag = (state & core::socket::State::NO_RETRY) == 0;
                                state &= ~core::socket::State::NO_RETRY;
                                onStatus(socketAddress, state);
                                if (retryFlag && config->getRetry() // Shall we potentially retry? In case are the ...
                                    && autoConnectControl->isRetryEnabled() &&
                                    (config->getRetryTries() == 0 ||
                                     tries < config->getRetryTries()) // ... limits not reached and has an ...
                                    && (state == core::socket::State::ERROR ||
                                        (state == core::socket::State::FATAL && config->getRetryOnFatal()))) { // error occurred?
                                    double relativeRetryTimeout =
                                        config->getRetryLimit() > 0
                                            ? std::min<double>(config->getRetryTimeout() * retryTimeoutScale, config->getRetryLimit())
                                            : config->getRetryTimeout() * retryTimeoutScale;
                                    relativeRetryTimeout -= utils::Random::getInRange(-config->getRetryJitter(), config->getRetryJitter()) *
                                                            relativeRetryTimeout / 100.;
                                    LOG(INFO) << config->getInstanceName() << ": Retry listen in " << relativeRetryTimeout << " seconds";
                                    autoConnectControl->armRetryTimer(
                                        relativeRetryTimeout,
                                        [config, sharedContext, autoConnectControl, /*generation,*/ onStatus, tries, retryTimeoutScale]() {
                                            if (!autoConnectControl->isRetryEnabled()) {
                                                return;
                                            }
                                            if (config->getRetry()) {
                                                SocketServer(config, sharedContext)
                                                    .realListen(onStatus, tries + 1, retryTimeoutScale * config->getRetryBase());
                                            } else {
                                                LOG(INFO) << config->getInstanceName() << ": Retry listen disabled during wait";
                                            }
                                        });
                                }
                            },
                            config);
                    }
                });
            return *this;
        }
References core::EventReceiver::atNextTick(), core::socket::State::ERROR, core::socket::State::FATAL, utils::Random::getInRange(), core::INITIALIZED, core::socket::State::NO_RETRY, core::socket::State::operator&(), core::socket::State::operator&=(), core::socket::State::operator==(), realListen(), core::RUNNING, and core::SNodeC::state().
Referenced by listen(), and realListen().
setOnAutoConnectControl()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> const SocketServer & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::setOnAutoConnectControl (const std::function< void(const std::shared_ptr< AutoConnectControl > &)> & onAutoConnectControl, bool initialize = false) const inline
Definition at line 322 of file SocketServer.h.
{
            sharedContext->onAutoConnectControl = initialize ? onAutoConnectControl
                                                             : [oldOnAutoConnectControl = sharedContext->onAutoConnectControl,
                                                                onAutoConnectControl](const std::shared_ptr<AutoConnectControl>& control) {
                                                                   oldOnAutoConnectControl(control);
                                                                   onAutoConnectControl(control);
                                                               };
            if (sharedContext->autoConnectControl && onAutoConnectControl) {
                core::EventReceiver::atNextTick([sharedContext = this->sharedContext, onAutoConnectControl] {
                    onAutoConnectControl(sharedContext->autoConnectControl);
                });
            }
            return *this;
        }
References core::EventReceiver::atNextTick(), and sharedContext.
setOnConnect()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> const SocketServer & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::setOnConnect (const std::function< void(SocketConnection *)> & onConnect, bool initialize = false) const inline
Definition at line 278 of file SocketServer.h.
{
            sharedContext->onConnect =
                initialize ? onConnect : [oldOnConnect = sharedContext->onConnect, onConnect](SocketConnection* socketConnection) {
                    oldOnConnect(socketConnection);
                    onConnect(socketConnection);
                };
            return *this;
        }
References sharedContext.
setOnConnected()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> const SocketServer & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::setOnConnected (const std::function< void(SocketConnection *)> & onConnected, bool initialize = false) const inline
Definition at line 292 of file SocketServer.h.
{
            sharedContext->onConnected =
                initialize ? onConnected : [oldOnConnected = sharedContext->onConnected, onConnected](SocketConnection* socketConnection) {
                    oldOnConnected(socketConnection);
                    onConnected(socketConnection);
                };
            return *this;
        }
References sharedContext.
setOnDisconnect()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> SocketServer & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::setOnDisconnect (const std::function< void(SocketConnection *)> & onDisconnect, bool initialize = false) inline
Definition at line 306 of file SocketServer.h.
{
            sharedContext->onDisconnect =
                initialize ? onDisconnect
                           : [oldOnDisconnect = sharedContext->onDisconnect, onDisconnect](SocketConnection* socketConnection) {
                                 oldOnDisconnect(socketConnection);
                                 onDisconnect(socketConnection);
                             };
            return *this;
        }
References sharedContext.
setOnInitState()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> const SocketServer & core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::setOnInitState (const std::function< void(core::eventreceiver::AcceptEventReceiver *)> & onInitState, bool initialize = false) const inline
Definition at line 344 of file SocketServer.h.
{
            sharedContext->onInitState = initialize ? onInitState
                                                    : [oldOnInitState = sharedContext->onInitState,
                                                       onInitState](core::eventreceiver::AcceptEventReceiver* descriptorEventReceiver) {
                                                          oldOnInitState(descriptorEventReceiver);
                                                          onInitState(descriptorEventReceiver);
                                                      };
            return *this;
        }
References sharedContext.
Referenced by main().
Member Data Documentation
sharedContext
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::shared_ptr<Context> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::sharedContext private
Definition at line 361 of file SocketServer.h.
Referenced by getOnAutoConnectControl(), getOnConnect(), getOnConnected(), getOnDisconnect(), getOnInitState(), getSocketContextFactory(), setOnAutoConnectControl(), setOnConnect(), setOnConnected(), setOnDisconnect(), setOnInitState(), SocketServer(), SocketServer(), and SocketServer().
The documentation for this class was generated from the following file:
core/socket/stream/SocketServer.h