SNode.C: iot::mqtt::packets::Connack Class Reference
iot::mqtt::packets::Connack Class Reference
#include <Connack.h>
Public Member Functions
Connack ()
Connack (uint8_t returncode, uint8_t acknowledgeFlags)
uint8_t getAcknowledgeFlags () const
uint8_t getReturnCode () const
bool getSessionPresent () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type, const std::string &name)
ControlPacket (const ControlPacket &)=default
ControlPacket (ControlPacket &&)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
ControlPacket & operator= (ControlPacket &&)=default
std::vector< char > serialize () const
const std::string & getName () const
Protected Attributes
iot::mqtt::types::UInt8 acknowledgeFlags
iot::mqtt::types::UInt8 returnCode
bool sessionPresent = false
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t flags = 0
Private Member Functions
std::vector< char > serializeVP () const override
Additional Inherited Members
Protected Member Functions inherited from iot::mqtt::ControlPacket
uint8_t getType () const
uint8_t getFlags () const
Detailed Description
Definition at line 66 of file Connack.h.
Constructor & Destructor Documentation
Connack() [1/2]
iot::mqtt::packets::Connack::Connack ()
Definition at line 53 of file Connack.cpp.
        : iot::mqtt::ControlPacket(MQTT_CONNACK, "CONNACK") {
    }
References iot::mqtt::ControlPacket::ControlPacket().
Referenced by Connack().
Connack() [2/2]
iot::mqtt::packets::Connack::Connack (uint8_t returncode, uint8_t acknowledgeFlags)
Definition at line 57 of file Connack.cpp.
        : Connack() {
        this->returnCode = returncode;
        this->acknowledgeFlags = acknowledgeFlags;
    }
References acknowledgeFlags, Connack(), iot::mqtt::types::UInt8::operator=(), and returnCode.
Referenced by iot::mqtt::server::Mqtt::sendConnack().
Member Function Documentation
getAcknowledgeFlags()
uint8_t iot::mqtt::packets::Connack::getAcknowledgeFlags () const
Definition at line 72 of file Connack.cpp.
{
        return acknowledgeFlags;
    }
References acknowledgeFlags.
Referenced by iot::mqtt::client::Mqtt::_onConnack().
getReturnCode()
uint8_t iot::mqtt::packets::Connack::getReturnCode () const
Definition at line 76 of file Connack.cpp.
{
        return returnCode;
    }
References returnCode.
Referenced by iot::mqtt::client::Mqtt::_onConnack().
getSessionPresent()
bool iot::mqtt::packets::Connack::getSessionPresent () const
Definition at line 80 of file Connack.cpp.
{
        return sessionPresent;
    }
References sessionPresent.
Referenced by iot::mqtt::client::Mqtt::_onConnack().
serializeVP()
std::vector< char > iot::mqtt::packets::Connack::serializeVP () const override private virtual
Implements iot::mqtt::ControlPacket.
Definition at line 63 of file Connack.cpp.
{
        std::vector<char> packet(acknowledgeFlags.serialize());
        std::vector<char> tmpVector = returnCode.serialize();
        packet.insert(packet.end(), tmpVector.begin(), tmpVector.end());
        return packet;
    }
References acknowledgeFlags, returnCode, and iot::mqtt::types::TypeBase< ValueTypeT >::serialize().
Member Data Documentation
acknowledgeFlags
iot::mqtt::types::UInt8 iot::mqtt::packets::Connack::acknowledgeFlags protected
Definition at line 81 of file Connack.h.
Referenced by Connack(), iot::mqtt::client::packets::Connack::deserializeVP(), getAcknowledgeFlags(), and serializeVP().
returnCode
iot::mqtt::types::UInt8 iot::mqtt::packets::Connack::returnCode protected
Definition at line 82 of file Connack.h.
Referenced by Connack(), iot::mqtt::client::packets::Connack::deserializeVP(), getReturnCode(), and serializeVP().
sessionPresent
bool iot::mqtt::packets::Connack::sessionPresent = false protected
Definition at line 84 of file Connack.h.
Referenced by iot::mqtt::client::packets::Connack::deserializeVP(), and getSessionPresent().
The documentation for this class was generated from the following files:
iot/mqtt/packets/Connack.h
iot/mqtt/packets/Connack.cpp