SNode.C: iot::mqtt::server::Mqtt Class Reference
iot::mqtt::server::Mqtt Class Reference
#include <Mqtt.h>
Public Types
using Super = iot::mqtt::Mqtt
Public Member Functions
Mqtt (const std::shared_ptr< iot::mqtt::server::broker::Broker > &broker)
~Mqtt () override
void sendConnack (uint8_t returnCode, uint8_t flags) const
void sendSuback (uint16_t packetIdentifier, std::list< uint8_t > &returnCodes) const
void sendUnsuback (uint16_t packetIdentifier) const
void sendPingresp () const
std::string getProtocol () const
uint8_t getLevel () const
uint8_t getConnectFlags () const
uint16_t getKeepAlive () const
std::string getClientId () const
std::string getWillTopic () const
std::string getWillMessage () const
std::string getUsername () const
std::string getPassword () const
bool getUsernameFlag () const
bool getPasswordFlag () const
bool getWillRetain () const
uint8_t getWillQoS () const
bool getWillFlag () const
bool getCleanSession () const
void setMqttContext (MqttContext *mqttContext)
virtual void onConnected ()
std::size_t onProcess ()
virtual void onDisconnected ()
core::socket::stream::SocketConnection * getSocketConnection ()
void sendPublish (const std::string &topic, const std::string &message, uint8_t qoS, bool retain)
Static Public Member Functions
static std::string dataToHexString (const std::vector< char > &data)
static std::string stringToHexString (const std::string data)
Protected Member Functions
void sendPuback (uint16_t packetIdentifier) const
void sendPubrec (uint16_t packetIdentifier) const
void sendPubrel (uint16_t packetIdentifier) const
void sendPubcomp (uint16_t packetIdentifier) const
virtual void onPublish (const iot::mqtt::packets::Publish &publish)
virtual void onPuback (const iot::mqtt::packets::Puback &puback)
virtual void onPubrec (const iot::mqtt::packets::Pubrec &pubrec)
virtual void onPubrel (const iot::mqtt::packets::Pubrel &pubrel)
virtual void onPubcomp (const iot::mqtt::packets::Pubcomp &pubcomp)
bool _onPublish (const iot::mqtt::packets::Publish &publish)
void _onPuback (const iot::mqtt::packets::Puback &puback)
void _onPubrec (const iot::mqtt::packets::Pubrec &pubrec)
void _onPubrel (const iot::mqtt::packets::Pubrel &pubrel)
void _onPubcomp (const iot::mqtt::packets::Pubcomp &pubcomp)
uint16_t getPacketIdentifier ()
void send (const iot::mqtt::ControlPacket &controlPacket) const
void printVP (const iot::mqtt::ControlPacket &packet)
Static Protected Member Functions
static void printFixedHeader (const iot::mqtt::FixedHeader &fixedHeader)
Protected Attributes
std::string protocol
uint8_t level = 0
uint8_t connectFlags = 0
uint16_t keepAlive = 0
std::string willTopic
std::string willMessage
std::string username
std::string password
bool usernameFlag = false
bool passwordFlag = false
bool willRetain = false
uint8_t willQoS = 0
bool willFlag = false
bool cleanSession = false
std::shared_ptr< iot::mqtt::server::broker::Broker > broker
std::string clientId
MqttContext * mqttContext = nullptr
Private Member Functions
iot::mqtt::ControlPacketDeserializer * createControlPacketDeserializer (iot::mqtt::FixedHeader &fixedHeader) final
void deliverPacket (iot::mqtt::ControlPacketDeserializer *controlPacketDeserializer) override
void onExit (int sig) override
void initSession (const utils::Timeval &keepAlive)
void releaseSession ()
virtual void onConnect (const iot::mqtt::packets::Connect &connect)
virtual void onSubscribe (const iot::mqtt::packets::Subscribe &subscribe)
virtual void onUnsubscribe (const iot::mqtt::packets::Unsubscribe &unsubscribe)
virtual void onPingreq (const iot::mqtt::packets::Pingreq &pingreq)
virtual void onDisconnect (const iot::mqtt::packets::Disconnect &disconnect)
void _onConnect (const iot::mqtt::server::packets::Connect &connect)
void _onPublish (const iot::mqtt::server::packets::Publish &publish)
void _onSubscribe (const iot::mqtt::server::packets::Subscribe &subscribe)
void _onUnsubscribe (const iot::mqtt::server::packets::Unsubscribe &unsubscribe)
void _onPingreq (const iot::mqtt::server::packets::Pingreq &pingreq)
void _onDisconnect (const iot::mqtt::server::packets::Disconnect &disconnect)
void initSession (Session *session, const utils::Timeval &keepAlive)
void send (const std::vector< char > &data) const
Private Attributes
iot::mqtt::FixedHeader fixedHeader
iot::mqtt::ControlPacketDeserializer * controlPacketDeserializer = nullptr
uint16_t _packetIdentifier = 0
core::timer::Timer keepAliveTimer
int state = 0
Session * session = nullptr
Friends
class iot::mqtt::server::packets::Connect
class iot::mqtt::server::packets::Subscribe
class iot::mqtt::server::packets::Unsubscribe
class iot::mqtt::server::packets::Pingreq
class iot::mqtt::server::packets::Disconnect
class iot::mqtt::server::packets::Publish
class iot::mqtt::server::packets::Pubcomp
class iot::mqtt::server::packets::Pubrec
class iot::mqtt::server::packets::Puback
class iot::mqtt::server::packets::Pubrel
Detailed Description
Definition at line 68 of file Mqtt.h.
Member Typedef Documentation
Super
using iot::mqtt::server::Mqtt::Super = iot::mqtt::Mqtt
Definition at line 70 of file Mqtt.h.
Constructor & Destructor Documentation
Mqtt()
iot::mqtt::server::Mqtt::Mqtt (const std::shared_ptr< iot::mqtt::server::broker::Broker > & broker) explicit
Definition at line 50 of file Mqtt.cpp.
        : broker(broker) {
    }
~Mqtt()
iot::mqtt::server::Mqtt::~Mqtt () override virtual
Reimplemented from iot::mqtt::Mqtt.
Definition at line 54 of file Mqtt.cpp.
                {
        releaseSession();
        if (willFlag) {
            broker->publish(willTopic, willMessage, willQoS, willRetain);
        }
    }
References iot::mqtt::server::broker::Broker::publish(), releaseSession(), willFlag, willMessage, willQoS, willRetain, and willTopic.
Member Function Documentation
_onConnect()
void iot::mqtt::server::Mqtt::_onConnect (const iot::mqtt::server::packets::Connect & connect) private
Definition at line 185 of file Mqtt.cpp.
{
        LOG(DEBUG) << "  Protocol: " << connect.getProtocol();
        LOG(DEBUG) << "  Version: " << static_cast<uint16_t>(connect.getLevel());
        LOG(DEBUG) << "  ConnectFlags: 0x" << std::hex << std::setfill('0') << std::setw(2)
                   << static_cast<uint16_t>(connect.getConnectFlags()) << std::dec << std::setw(0);
        LOG(DEBUG) << "  KeepAlive: " << connect.getKeepAlive();
        LOG(DEBUG) << "  ClientID: " << connect.getClientId();
        LOG(DEBUG) << "  CleanSession: " << connect.getCleanSession();
        if (connect.getWillFlag()) {
            LOG(DEBUG) << "  WillTopic: " << connect.getWillTopic();
            LOG(DEBUG) << "  WillMessage: " << connect.getWillMessage();
            LOG(DEBUG) << "  WillQoS: " << static_cast<uint16_t>(connect.getWillQoS());
            LOG(DEBUG) << "  WillRetain: " << connect.getWillRetain();
        }
        if (connect.getUsernameFlag()) {
            LOG(DEBUG) << "  Username: " << connect.getUsername();
        }
        if (connect.getPasswordFlag()) {
            LOG(DEBUG) << "  Password: " << connect.getPassword();
        }
        if (connect.getProtocol() != "MQTT") {
            LOG(DEBUG) << "  Wrong Protocol: " << connect.getProtocol();
            mqttContext->end(true);
        } else if (connect.getLevel() != MQTT_VERSION_3_1_1) {
            LOG(DEBUG) << "  Wrong Protocol Level: " << MQTT_VERSION_3_1_1 << " != " << connect.getLevel();
            sendConnack(MQTT_CONNACK_UNACEPTABLEVERSION, MQTT_SESSION_NEW);
            mqttContext->end(true);
        } else if (connect.isFakedClientId() && !connect.getCleanSession()) {
            LOG(DEBUG) << "  Resume session but no ClientId present";
            sendConnack(MQTT_CONNACK_IDENTIFIERREJECTED, MQTT_SESSION_NEW);
            mqttContext->end(true);
        } else {
            // V-Header
            protocol = connect.getProtocol();
            level = connect.getLevel();
            connectFlags = connect.getConnectFlags();
            keepAlive = connect.getKeepAlive();
            // Payload
            clientId = connect.getClientId();
            willTopic = connect.getWillTopic();
            willMessage = connect.getWillMessage();
            username = connect.getUsername();
            password = connect.getPassword();
            // Derived from flags
            usernameFlag = connect.getUsernameFlag();
            passwordFlag = connect.getPasswordFlag();
            willRetain = connect.getWillRetain();
            willQoS = connect.getWillQoS();
            willFlag = connect.getWillFlag();
            cleanSession = connect.getCleanSession();
            initSession(1.5 * keepAlive);
            onConnect(connect);
        }
    }
References cleanSession, iot::mqtt::Mqtt::clientId, connectFlags, iot::mqtt::MqttContext::end(), iot::mqtt::packets::Connect::getCleanSession(), iot::mqtt::packets::Connect::getClientId(), iot::mqtt::packets::Connect::getConnectFlags(), iot::mqtt::packets::Connect::getKeepAlive(), iot::mqtt::packets::Connect::getLevel(), iot::mqtt::packets::Connect::getPassword(), iot::mqtt::packets::Connect::getPasswordFlag(), iot::mqtt::packets::Connect::getProtocol(), iot::mqtt::packets::Connect::getUsername(), iot::mqtt::packets::Connect::getUsernameFlag(), iot::mqtt::packets::Connect::getWillFlag(), iot::mqtt::packets::Connect::getWillMessage(), iot::mqtt::packets::Connect::getWillQoS(), iot::mqtt::packets::Connect::getWillRetain(), iot::mqtt::packets::Connect::getWillTopic(), initSession(), iot::mqtt::server::packets::Connect::isFakedClientId(), keepAlive, level, iot::mqtt::Mqtt::mqttContext, onConnect(), password, passwordFlag, protocol, sendConnack(), username, usernameFlag, willFlag, willMessage, willQoS, willRetain, and willTopic.
Referenced by iot::mqtt::server::packets::Connect::deliverPacket().
_onDisconnect()
void iot::mqtt::server::Mqtt::_onDisconnect (const iot::mqtt::server::packets::Disconnect & disconnect) private
Definition at line 306 of file Mqtt.cpp.
{
        willFlag = false;
        onDisconnect(disconnect);
        releaseSession();
        mqttContext->end();
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::Mqtt::mqttContext, onDisconnect(), releaseSession(), and willFlag.
Referenced by iot::mqtt::server::packets::Disconnect::deliverPacket().
_onPingreq()
void iot::mqtt::server::Mqtt::_onPingreq (const iot::mqtt::server::packets::Pingreq & pingreq) private
Definition at line 300 of file Mqtt.cpp.
{
        sendPingresp();
        onPingreq(pingreq);
    }
References onPingreq(), and sendPingresp().
Referenced by iot::mqtt::server::packets::Pingreq::deliverPacket().
_onPuback()
void iot::mqtt::Mqtt::_onPuback (const iot::mqtt::packets::Puback & puback) protected inherited
Definition at line 265 of file Mqtt.cpp.
{
        if (puback.getPacketIdentifier() == 0) {
            LOG(DEBUG) << "  PackageIdentifier missing";
            mqttContext->end(true);
        } else {
            LOG(DEBUG) << "  PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4) << puback.getPacketIdentifier();
        }
        onPuback(puback);
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::packets::Puback::getPacketIdentifier(), iot::mqtt::Mqtt::mqttContext, and iot::mqtt::Mqtt::onPuback().
Referenced by iot::mqtt::client::packets::Puback::deliverPacket(), and iot::mqtt::server::packets::Puback::deliverPacket().
_onPubcomp()
void iot::mqtt::Mqtt::_onPubcomp (const iot::mqtt::packets::Pubcomp & pubcomp) protected inherited
Definition at line 307 of file Mqtt.cpp.
{
        if (pubcomp.getPacketIdentifier() == 0) {
            LOG(DEBUG) << "  PackageIdentifier missing";
            mqttContext->end(true);
        } else {
            LOG(DEBUG) << "  PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4) << pubcomp.getPacketIdentifier();
            session->publishMap.erase(pubcomp.getPacketIdentifier());
            session->pubrelPacketIdentifierSet.erase(pubcomp.getPacketIdentifier());
        }
        onPubcomp(pubcomp);
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::packets::Pubcomp::getPacketIdentifier(), iot::mqtt::Mqtt::mqttContext, iot::mqtt::Mqtt::onPubcomp(), iot::mqtt::Session::publishMap, iot::mqtt::Session::pubrelPacketIdentifierSet, and iot::mqtt::Mqtt::session.
Referenced by iot::mqtt::client::packets::Pubcomp::deliverPacket(), and iot::mqtt::server::packets::Pubcomp::deliverPacket().
_onPublish() [1/2]
bool iot::mqtt::Mqtt::_onPublish (const iot::mqtt::packets::Publish & publish) protected inherited
Definition at line 225 of file Mqtt.cpp.
{
        bool deliver = true;
        LOG(DEBUG) << "  Topic: " << publish.getTopic();
        LOG(DEBUG) << "  Message:\n" << stringToHexString(publish.getMessage());
        LOG(DEBUG) << "  QoS: " << static_cast<uint16_t>(publish.getQoS());
        LOG(DEBUG) << "  PacketIdentifier: " << publish.getPacketIdentifier();
        LOG(DEBUG) << "  DUP: " << publish.getDup();
        LOG(DEBUG) << "  Retain: " << publish.getRetain();
        if (publish.getQoS() > 2) {
            LOG(DEBUG) << "  Received invalid QoS: " << publish.getQoS();
            mqttContext->end(true);
            deliver = false;
        } else if (publish.getPacketIdentifier() == 0 && publish.getQoS() > 0) {
            LOG(DEBUG) << "  Received QoS > 0 but no PackageIdentifier present";
            mqttContext->end(true);
            deliver = false;
        } else {
            switch (publish.getQoS()) {
                case 1:
                    sendPuback(publish.getPacketIdentifier());
                    break;
                case 2:
                    sendPubrec(publish.getPacketIdentifier());
                    if (session->publishPacketIdentifierSet.contains(publish.getPacketIdentifier())) {
                        deliver = false;
                    } else {
                        session->publishPacketIdentifierSet.insert(publish.getPacketIdentifier());
                    }
                    break;
            }
        }
        return deliver;
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::packets::Publish::getDup(), iot::mqtt::packets::Publish::getMessage(), iot::mqtt::packets::Publish::getPacketIdentifier(), iot::mqtt::packets::Publish::getQoS(), iot::mqtt::packets::Publish::getRetain(), iot::mqtt::packets::Publish::getTopic(), iot::mqtt::Mqtt::mqttContext, iot::mqtt::Session::publishPacketIdentifierSet, iot::mqtt::Mqtt::sendPuback(), iot::mqtt::Mqtt::sendPubrec(), iot::mqtt::Mqtt::session, and iot::mqtt::Mqtt::stringToHexString().
Referenced by iot::mqtt::client::Mqtt::_onPublish(), and _onPublish().
_onPublish() [2/2]
void iot::mqtt::server::Mqtt::_onPublish (const iot::mqtt::server::packets::Publish & publish) private
Definition at line 248 of file Mqtt.cpp.
{
        if (Super::_onPublish(publish)) {
            broker->publish(publish.getTopic(), publish.getMessage(), publish.getQoS(), publish.getRetain());
            onPublish(publish);
        }
    }
References iot::mqtt::Mqtt::_onPublish(), iot::mqtt::packets::Publish::getMessage(), iot::mqtt::packets::Publish::getQoS(), iot::mqtt::packets::Publish::getRetain(), iot::mqtt::packets::Publish::getTopic(), iot::mqtt::Mqtt::onPublish(), and iot::mqtt::server::broker::Broker::publish().
Referenced by iot::mqtt::server::packets::Publish::deliverPacket().
_onPubrec()
void iot::mqtt::Mqtt::_onPubrec (const iot::mqtt::packets::Pubrec & pubrec) protected inherited
Definition at line 276 of file Mqtt.cpp.
{
        if (pubrec.getPacketIdentifier() == 0) {
            LOG(DEBUG) << "  PackageIdentifier missing";
            mqttContext->end(true);
        } else {
            LOG(DEBUG) << "  PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4) << pubrec.getPacketIdentifier();
            session->publishMap.erase(pubrec.getPacketIdentifier());
            session->pubrelPacketIdentifierSet.insert(pubrec.getPacketIdentifier());
            sendPubrel(pubrec.getPacketIdentifier());
        }
        onPubrec(pubrec);
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::packets::Pubrec::getPacketIdentifier(), iot::mqtt::Mqtt::mqttContext, iot::mqtt::Mqtt::onPubrec(), iot::mqtt::Session::publishMap, iot::mqtt::Session::pubrelPacketIdentifierSet, iot::mqtt::Mqtt::sendPubrel(), and iot::mqtt::Mqtt::session.
Referenced by iot::mqtt::client::packets::Pubrec::deliverPacket(), and iot::mqtt::server::packets::Pubrec::deliverPacket().
_onPubrel()
void iot::mqtt::Mqtt::_onPubrel (const iot::mqtt::packets::Pubrel & pubrel) protected inherited
Definition at line 292 of file Mqtt.cpp.
{
        if (pubrel.getPacketIdentifier() == 0) {
            LOG(DEBUG) << "  PackageIdentifier missing";
            mqttContext->end(true);
        } else {
            LOG(DEBUG) << "  PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4) << pubrel.getPacketIdentifier();
            session->publishPacketIdentifierSet.erase(pubrel.getPacketIdentifier());
            sendPubcomp(pubrel.getPacketIdentifier());
        }
        onPubrel(pubrel);
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::packets::Pubrel::getPacketIdentifier(), iot::mqtt::Mqtt::mqttContext, iot::mqtt::Mqtt::onPubrel(), iot::mqtt::Session::publishPacketIdentifierSet, iot::mqtt::Mqtt::sendPubcomp(), and iot::mqtt::Mqtt::session.
Referenced by iot::mqtt::client::packets::Pubrel::deliverPacket(), and iot::mqtt::server::packets::Pubrel::deliverPacket().
_onSubscribe()
void iot::mqtt::server::Mqtt::_onSubscribe (const iot::mqtt::server::packets::Subscribe & subscribe) private
Definition at line 256 of file Mqtt.cpp.
{
        if (subscribe.getPacketIdentifier() == 0) {
            LOG(DEBUG) << "  PackageIdentifier missing";
            mqttContext->end(true);
        } else {
            LOG(DEBUG) << "  PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4) << subscribe.getPacketIdentifier();
            for (const iot::mqtt::Topic& topic : subscribe.getTopics()) {
                LOG(DEBUG) << "  Topic filter: '" << topic.getName() << "', QoS: " << static_cast<uint16_t>(topic.getQoS());
            }
            std::list<uint8_t> returnCodes;
            for (const iot::mqtt::Topic& topic : subscribe.getTopics()) {
                uint8_t returnCode = broker->subscribe(clientId, topic.getName(), topic.getQoS());
                returnCodes.push_back(returnCode);
            }
            sendSuback(subscribe.getPacketIdentifier(), returnCodes);
            onSubscribe(subscribe);
        }
    }
References iot::mqtt::Mqtt::clientId, iot::mqtt::MqttContext::end(), iot::mqtt::Topic::getName(), iot::mqtt::packets::Subscribe::getPacketIdentifier(), iot::mqtt::Topic::getQoS(), iot::mqtt::packets::Subscribe::getTopics(), iot::mqtt::Mqtt::mqttContext, onSubscribe(), sendSuback(), and iot::mqtt::server::broker::Broker::subscribe().
Referenced by iot::mqtt::server::packets::Subscribe::deliverPacket().
_onUnsubscribe()
void iot::mqtt::server::Mqtt::_onUnsubscribe (const iot::mqtt::server::packets::Unsubscribe & unsubscribe) private
Definition at line 279 of file Mqtt.cpp.
{
        if (unsubscribe.getPacketIdentifier() == 0) {
            LOG(DEBUG) << "  PackageIdentifier missing";
            mqttContext->end(true);
        } else {
            LOG(DEBUG) << "  PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4) << unsubscribe.getPacketIdentifier();
            for (const std::string& topic : unsubscribe.getTopics()) {
                LOG(DEBUG) << "  Topic: " << topic;
            }
            for (const std::string& topic : unsubscribe.getTopics()) {
                broker->unsubscribe(clientId, topic);
            }
            sendUnsuback(unsubscribe.getPacketIdentifier());
            onUnsubscribe(unsubscribe);
        }
    }
References iot::mqtt::Mqtt::clientId, iot::mqtt::MqttContext::end(), iot::mqtt::packets::Unsubscribe::getPacketIdentifier(), iot::mqtt::packets::Unsubscribe::getTopics(), iot::mqtt::Mqtt::mqttContext, onUnsubscribe(), sendUnsuback(), and iot::mqtt::server::broker::Broker::unsubscribe().
Referenced by iot::mqtt::server::packets::Unsubscribe::deliverPacket().
createControlPacketDeserializer()
iot::mqtt::ControlPacketDeserializer * iot::mqtt::server::Mqtt::createControlPacketDeserializer (iot::mqtt::FixedHeader & fixedHeader) final private virtual
Implements iot::mqtt::Mqtt.
Definition at line 67 of file Mqtt.cpp.
{
        iot::mqtt::ControlPacketDeserializer* controlPacketDeserializer = nullptr;
        switch (fixedHeader.getType()) {
            case MQTT_CONNECT:
                controlPacketDeserializer =
                    new iot::mqtt::server::packets::Connect(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_PUBLISH:
                controlPacketDeserializer =
                    new iot::mqtt::server::packets::Publish(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_PUBACK:
                controlPacketDeserializer =
                    new iot::mqtt::server::packets::Puback(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_PUBREC:
                controlPacketDeserializer =
                    new iot::mqtt::server::packets::Pubrec(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_PUBREL:
                controlPacketDeserializer =
                    new iot::mqtt::server::packets::Pubrel(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_PUBCOMP:
                controlPacketDeserializer =
                    new iot::mqtt::server::packets::Pubcomp(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_SUBSCRIBE:
                controlPacketDeserializer =
                    new iot::mqtt::server::packets::Subscribe(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_UNSUBSCRIBE:
                controlPacketDeserializer =
                    new iot::mqtt::server::packets::Unsubscribe(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_PINGREQ:
                controlPacketDeserializer =
                    new iot::mqtt::server::packets::Pingreq(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_DISCONNECT:
                controlPacketDeserializer =
                    new iot::mqtt::server::packets::Disconnect(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            default:
                controlPacketDeserializer = nullptr;
                break;
        }
        return controlPacketDeserializer;
    }
References iot::mqtt::server::packets::Connect::Connect(), iot::mqtt::server::packets::Disconnect::Disconnect(), iot::mqtt::FixedHeader::getFlags(), iot::mqtt::FixedHeader::getRemainingLength(), iot::mqtt::FixedHeader::getType(), iot::mqtt::server::packets::Pingreq::Pingreq(), iot::mqtt::server::packets::Puback::Puback(), iot::mqtt::server::packets::Pubcomp::Pubcomp(), iot::mqtt::server::packets::Publish::Publish(), iot::mqtt::server::packets::Pubrec::Pubrec(), iot::mqtt::server::packets::Pubrel::Pubrel(), iot::mqtt::server::packets::Subscribe::Subscribe(), and iot::mqtt::server::packets::Unsubscribe::Unsubscribe().
dataToHexString()
std::string iot::mqtt::Mqtt::dataToHexString (const std::vector< char > & data) static inherited
Definition at line 339 of file Mqtt.cpp.
{
        std::stringstream ss;
        ss << "                                               ";
        unsigned long i = 0;
        for (char ch : data) {
            if (i != 0 && i % 8 == 0 && i != data.size()) {
                ss << std::endl;
                ss << "                                               ";
            }
            ++i;
            ss << "0x" << std::hex << std::setfill('0') << std::setw(2) << static_cast<uint16_t>(static_cast<uint8_t>(ch))
               << " "; // << " | ";
        }
        return ss.str();
    }
Referenced by iot::mqtt::Mqtt::printFixedHeader(), iot::mqtt::Mqtt::printVP(), iot::mqtt::Mqtt::send(), and iot::mqtt::Mqtt::stringToHexString().
deliverPacket()
void iot::mqtt::server::Mqtt::deliverPacket (iot::mqtt::ControlPacketDeserializer * controlPacketDeserializer) override private virtual
Implements iot::mqtt::Mqtt.
Definition at line 119 of file Mqtt.cpp.
{
        static_cast<iot::mqtt::server::ControlPacketDeserializer*>(controlPacketDeserializer)->deliverPacket(this);
    }
References iot::mqtt::server::ControlPacketDeserializer::deliverPacket().
getCleanSession()
bool iot::mqtt::server::Mqtt::getCleanSession () const
Definition at line 388 of file Mqtt.cpp.
{
        return cleanSession;
    }
References cleanSession.
getClientId()
std::string iot::mqtt::server::Mqtt::getClientId () const
Definition at line 348 of file Mqtt.cpp.
{
        return clientId;
    }
References iot::mqtt::Mqtt::clientId.
getConnectFlags()
uint8_t iot::mqtt::server::Mqtt::getConnectFlags () const
Definition at line 340 of file Mqtt.cpp.
{
        return connectFlags;
    }
References connectFlags.
getKeepAlive()
uint16_t iot::mqtt::server::Mqtt::getKeepAlive () const
Definition at line 344 of file Mqtt.cpp.
{
        return keepAlive;
    }
References keepAlive.
getLevel()
uint8_t iot::mqtt::server::Mqtt::getLevel () const
Definition at line 336 of file Mqtt.cpp.
{
        return level;
    }
References level.
getPacketIdentifier()
uint16_t iot::mqtt::Mqtt::getPacketIdentifier () protected inherited
Definition at line 362 of file Mqtt.cpp.
{
        ++_packetIdentifier;
        if (_packetIdentifier == 0) {
            ++_packetIdentifier;
        }
        return _packetIdentifier;
    }
References iot::mqtt::Mqtt::_packetIdentifier.
Referenced by iot::mqtt::Mqtt::sendPublish(), iot::mqtt::client::Mqtt::sendSubscribe(), and iot::mqtt::client::Mqtt::sendUnsubscribe().
getPassword()
std::string iot::mqtt::server::Mqtt::getPassword () const
Definition at line 364 of file Mqtt.cpp.
{
        return password;
    }
References password.
getPasswordFlag()
bool iot::mqtt::server::Mqtt::getPasswordFlag () const
Definition at line 372 of file Mqtt.cpp.
{
        return passwordFlag;
    }
References passwordFlag.
getProtocol()
std::string iot::mqtt::server::Mqtt::getProtocol () const
Definition at line 332 of file Mqtt.cpp.
{
        return protocol;
    }
References protocol.
getSocketConnection()
core::socket::stream::SocketConnection * iot::mqtt::Mqtt::getSocketConnection () inherited
Definition at line 138 of file Mqtt.cpp.
{
        return mqttContext->getSocketConnection();
    }
References iot::mqtt::MqttContext::getSocketConnection(), and iot::mqtt::Mqtt::mqttContext.
Referenced by iot::mqtt::Mqtt::initSession().
getUsername()
std::string iot::mqtt::server::Mqtt::getUsername () const
Definition at line 360 of file Mqtt.cpp.
{
        return username;
    }
References username.
getUsernameFlag()
bool iot::mqtt::server::Mqtt::getUsernameFlag () const
Definition at line 368 of file Mqtt.cpp.
{
        return usernameFlag;
    }
References usernameFlag.
getWillFlag()
bool iot::mqtt::server::Mqtt::getWillFlag () const
Definition at line 384 of file Mqtt.cpp.
{
        return willFlag;
    }
References willFlag.
getWillMessage()
std::string iot::mqtt::server::Mqtt::getWillMessage () const
Definition at line 356 of file Mqtt.cpp.
{
        return willMessage;
    }
References willMessage.
getWillQoS()
uint8_t iot::mqtt::server::Mqtt::getWillQoS () const
Definition at line 380 of file Mqtt.cpp.
{
        return willQoS;
    }
References willQoS.
getWillRetain()
bool iot::mqtt::server::Mqtt::getWillRetain () const
Definition at line 376 of file Mqtt.cpp.
{
        return willRetain;
    }
References willRetain.
getWillTopic()
std::string iot::mqtt::server::Mqtt::getWillTopic () const
Definition at line 352 of file Mqtt.cpp.
{
        return willTopic;
    }
References willTopic.
initSession() [1/2]
void iot::mqtt::server::Mqtt::initSession (const utils::Timeval & keepAlive) private
Definition at line 123 of file Mqtt.cpp.
{
        if (broker->hasActiveSession(clientId)) {
            LOG(DEBUG) << "Existing session found for ClientId = " << clientId;
            LOG(DEBUG) << "  closing";
            sendConnack(MQTT_CONNACK_IDENTIFIERREJECTED, 0);
            mqttContext->end(true);
            willFlag = false;
        } else if (broker->hasRetainedSession(clientId)) {
            sendConnack(MQTT_CONNACK_ACCEPT, cleanSession ? MQTT_SESSION_NEW : MQTT_SESSION_PRESENT);
            LOG(DEBUG) << "Retained session found for ClientId = " << clientId;
            if (cleanSession) {
                LOG(DEBUG) << "  clean SessionId = " << this;
                broker->unsubscribe(clientId);
                initSession(broker->newSession(clientId, this), keepAlive);
            } else {
                LOG(DEBUG) << "  renew SessionId = " << this;
                initSession(broker->renewSession(clientId, this), keepAlive);
                broker->restartSession(clientId);
            }
        } else {
            sendConnack(MQTT_CONNACK_ACCEPT, MQTT_SESSION_NEW);
            LOG(DEBUG) << "No session found for ClientId = " << clientId;
            LOG(DEBUG) << "  new SessionId = " << this;
            initSession(broker->newSession(clientId, this), keepAlive);
        }
    }
References cleanSession, iot::mqtt::Mqtt::clientId, iot::mqtt::MqttContext::end(), iot::mqtt::server::broker::Broker::hasActiveSession(), iot::mqtt::server::broker::Broker::hasRetainedSession(), iot::mqtt::Mqtt::initSession(), iot::mqtt::Mqtt::mqttContext, iot::mqtt::server::broker::Broker::newSession(), iot::mqtt::server::broker::Broker::renewSession(), iot::mqtt::server::broker::Broker::restartSession(), sendConnack(), iot::mqtt::server::broker::Broker::unsubscribe(), and willFlag.
Referenced by _onConnect().
initSession() [2/2]
void iot::mqtt::Mqtt::initSession (Session * session, const utils::Timeval & keepAlive) private
Definition at line 73 of file Mqtt.cpp.
{
        this->session = session;
        for (auto& [packetIdentifier, publish] : session->publishMap) {
            LOG(DEBUG) << "PUBLISH Resend";
            send(publish);
        }
        for (uint16_t packetIdentifier : session->pubrelPacketIdentifierSet) {
            LOG(DEBUG) << "PUBREL Resend";
            send(iot::mqtt::packets::Pubrel(packetIdentifier));
        }
        if (keepAlive > 0) {
            keepAliveTimer = core::timer::Timer::singleshotTimer(
                [this, keepAlive]() -> void {
                    LOG(DEBUG) << "Keep-alive timer expired. Interval was: " << keepAlive;
                    mqttContext->close();
                },
                keepAlive);
            getSocketConnection()->setTimeout(0);
        }
    }
onConnect()
void iot::mqtt::server::Mqtt::onConnect (const iot::mqtt::packets::Connect & connect) private virtual
Definition at line 170 of file Mqtt.cpp.
{
    }
Referenced by _onConnect().
onConnected()
void iot::mqtt::Mqtt::onConnected () virtual inherited
Definition at line 63 of file Mqtt.cpp.
{
    }
Referenced by iot::mqtt::MqttContext::onConnected().
onDisconnect()
void iot::mqtt::server::Mqtt::onDisconnect (const iot::mqtt::packets::Disconnect & disconnect) private virtual
Definition at line 182 of file Mqtt.cpp.
{
    }
Referenced by _onDisconnect().
onDisconnected()
void iot::mqtt::Mqtt::onDisconnected () virtual inherited
Definition at line 131 of file Mqtt.cpp.
{
    }
Referenced by iot::mqtt::MqttContext::onDisconnected().
onExit()
void iot::mqtt::server::Mqtt::onExit (int sig) override private virtual
Reimplemented from iot::mqtt::Mqtt.
Definition at line 62 of file Mqtt.cpp.
{
        willFlag = false;
        Super::onExit(sig);
    }
References iot::mqtt::Mqtt::onExit(), and willFlag.
onPingreq()
void iot::mqtt::server::Mqtt::onPingreq (const iot::mqtt::packets::Pingreq & pingreq) private virtual
Definition at line 179 of file Mqtt.cpp.
{
    }
Referenced by _onPingreq().
onProcess()
std::size_t iot::mqtt::Mqtt::onProcess () inherited
Definition at line 66 of file Mqtt.cpp.
{
        std::size_t consumed = 0;
        switch (state) {
            case 0:
                consumed = fixedHeader.deserialize(mqttContext);
                if (!fixedHeader.isComplete()) {
                    break;
                } else if (fixedHeader.isError()) {
                    mqttContext->close();
                    break;
                } else {
                    printFixedHeader(fixedHeader);
                    controlPacketDeserializer = createControlPacketDeserializer(fixedHeader);
                    fixedHeader.reset();
                    if (controlPacketDeserializer == nullptr) {
                        LOG(DEBUG) << "Received packet-type is unavailable ... closing connection";
                        mqttContext->end(true);
                        break;
                    } else if (controlPacketDeserializer->isError()) {
                        LOG(DEBUG) << "Fixed header has error ... closing connection";
                        delete controlPacketDeserializer;
                        controlPacketDeserializer = nullptr;
                        mqttContext->end(true);
                        break;
                    }
                    state++;
                }
                [[fallthrough]];
            case 1:
                consumed += controlPacketDeserializer->deserialize(mqttContext);
                if (controlPacketDeserializer->isError()) {
                    LOG(DEBUG) << "Control packet has error ... closing connection";
                    mqttContext->end(true);
                    delete controlPacketDeserializer;
                    controlPacketDeserializer = nullptr;
                    state = 0;
                } else if (controlPacketDeserializer->isComplete()) {
                    deliverPacket(controlPacketDeserializer);
                    delete controlPacketDeserializer;
                    controlPacketDeserializer = nullptr;
                    state = 0;
                    keepAliveTimer.restart();
                }
                break;
        }
        return consumed;
    }
References iot::mqtt::FixedHeader::deserialize(), iot::mqtt::Mqtt::fixedHeader, iot::mqtt::Mqtt::mqttContext, and iot::mqtt::Mqtt::state.
Referenced by iot::mqtt::MqttContext::onData().
onPuback()
void iot::mqtt::Mqtt::onPuback (const iot::mqtt::packets::Puback & puback) protected virtual inherited
Definition at line 213 of file Mqtt.cpp.
{
    }
Referenced by iot::mqtt::Mqtt::_onPuback().
onPubcomp()
void iot::mqtt::Mqtt::onPubcomp (const iot::mqtt::packets::Pubcomp & pubcomp) protected virtual inherited
Definition at line 222 of file Mqtt.cpp.
{
    }
Referenced by iot::mqtt::Mqtt::_onPubcomp().
onPublish()
void iot::mqtt::Mqtt::onPublish (const iot::mqtt::packets::Publish & publish) protected virtual inherited
Definition at line 210 of file Mqtt.cpp.
{
    }
Referenced by iot::mqtt::client::Mqtt::_onPublish(), and _onPublish().
onPubrec()
void iot::mqtt::Mqtt::onPubrec (const iot::mqtt::packets::Pubrec & pubrec) protected virtual inherited
Definition at line 216 of file Mqtt.cpp.
{
    }
Referenced by iot::mqtt::Mqtt::_onPubrec().
onPubrel()
void iot::mqtt::Mqtt::onPubrel (const iot::mqtt::packets::Pubrel & pubrel) protected virtual inherited
Definition at line 219 of file Mqtt.cpp.
{
    }
Referenced by iot::mqtt::Mqtt::_onPubrel().
onSubscribe()
void iot::mqtt::server::Mqtt::onSubscribe (const iot::mqtt::packets::Subscribe & subscribe) private virtual
Definition at line 173 of file Mqtt.cpp.
{
    }
Referenced by _onSubscribe().
onUnsubscribe()
void iot::mqtt::server::Mqtt::onUnsubscribe (const iot::mqtt::packets::Unsubscribe & unsubscribe) private virtual
Definition at line 176 of file Mqtt.cpp.
{
    }
Referenced by _onUnsubscribe().
printFixedHeader()
void iot::mqtt::Mqtt::printFixedHeader (const iot::mqtt::FixedHeader & fixedHeader) static protected inherited
Definition at line 327 of file Mqtt.cpp.
{
        LOG(DEBUG) << "======================================================";
        LOG(TRACE) << "Received data (fixed header):\n" << dataToHexString(fixedHeader.serialize());
        LOG(DEBUG) << "Fixed Header: PacketType: 0x" << std::hex << std::setfill('0') << std::setw(2)
                   << static_cast<uint16_t>(fixedHeader.getType());
        LOG(DEBUG) << "              PacketFlags: 0x" << std::hex << std::setfill('0') << std::setw(2)
                   << static_cast<uint16_t>(fixedHeader.getFlags()) << std::dec;
        LOG(DEBUG) << "              RemainingLength: " << fixedHeader.getRemainingLength();
    }
References iot::mqtt::Mqtt::dataToHexString(), iot::mqtt::FixedHeader::getFlags(), iot::mqtt::FixedHeader::getRemainingLength(), iot::mqtt::FixedHeader::getType(), and iot::mqtt::FixedHeader::serialize().
printVP()
void iot::mqtt::Mqtt::printVP (const iot::mqtt::ControlPacket & packet) protected inherited
Definition at line 321 of file Mqtt.cpp.
{
        LOG(TRACE) << "Received data (full):\n" << dataToHexString(packet.serialize());
        LOG(INFO) << packet.getName() << " received: " << clientId;
    }
References iot::mqtt::Mqtt::clientId, iot::mqtt::Mqtt::dataToHexString(), iot::mqtt::ControlPacket::getName(), and iot::mqtt::ControlPacket::serialize().
Referenced by iot::mqtt::client::packets::Connack::deliverPacket(), iot::mqtt::client::packets::Pingresp::deliverPacket(), iot::mqtt::client::packets::Puback::deliverPacket(), iot::mqtt::client::packets::Pubcomp::deliverPacket(), iot::mqtt::client::packets::Publish::deliverPacket(), iot::mqtt::client::packets::Pubrec::deliverPacket(), iot::mqtt::client::packets::Pubrel::deliverPacket(), iot::mqtt::client::packets::Suback::deliverPacket(), iot::mqtt::client::packets::Unsuback::deliverPacket(), iot::mqtt::server::packets::Connect::deliverPacket(), iot::mqtt::server::packets::Disconnect::deliverPacket(), iot::mqtt::server::packets::Pingreq::deliverPacket(), iot::mqtt::server::packets::Puback::deliverPacket(), iot::mqtt::server::packets::Pubcomp::deliverPacket(), iot::mqtt::server::packets::Publish::deliverPacket(), iot::mqtt::server::packets::Pubrec::deliverPacket(), iot::mqtt::server::packets::Pubrel::deliverPacket(), iot::mqtt::server::packets::Subscribe::deliverPacket(), and iot::mqtt::server::packets::Unsubscribe::deliverPacket().
releaseSession()
void iot::mqtt::server::Mqtt::releaseSession () private
Definition at line 156 of file Mqtt.cpp.
{
        if (broker->isActiveSession(clientId, this)) {
            if (cleanSession) {
                LOG(DEBUG) << "Delete session for ClientId = " << clientId;
                LOG(DEBUG) << "  SessionId = " << this;
                broker->deleteSession(clientId);
            } else {
                LOG(DEBUG) << "Retain session for ClientId = " << clientId;
                LOG(DEBUG) << "  SessionId = " << this;
                broker->retainSession(clientId);
            }
        }
    }
References cleanSession, iot::mqtt::Mqtt::clientId, iot::mqtt::server::broker::Broker::deleteSession(), iot::mqtt::server::broker::Broker::isActiveSession(), and iot::mqtt::server::broker::Broker::retainSession().
Referenced by _onDisconnect(), and ~Mqtt().
send() [1/2]
void iot::mqtt::Mqtt::send (const iot::mqtt::ControlPacket & controlPacket) const protected inherited
Definition at line 169 of file Mqtt.cpp.
{
        LOG(DEBUG) << "======================================================";
        LOG(INFO) << controlPacket.getName() << " send: " << clientId;
        send(controlPacket.serialize());
    }
References iot::mqtt::Mqtt::clientId, iot::mqtt::ControlPacket::getName(), iot::mqtt::Mqtt::send(), and iot::mqtt::ControlPacket::serialize().
Referenced by iot::mqtt::Mqtt::initSession(), sendConnack(), iot::mqtt::client::Mqtt::sendConnect(), iot::mqtt::client::Mqtt::sendDisconnect(), iot::mqtt::client::Mqtt::sendPingreq(), sendPingresp(), iot::mqtt::Mqtt::sendPuback(), iot::mqtt::Mqtt::sendPubcomp(), iot::mqtt::Mqtt::sendPublish(), iot::mqtt::Mqtt::sendPubrec(), iot::mqtt::Mqtt::sendPubrel(), sendSuback(), iot::mqtt::client::Mqtt::sendSubscribe(), sendUnsuback(), and iot::mqtt::client::Mqtt::sendUnsubscribe().
send() [2/2]
void iot::mqtt::Mqtt::send (const std::vector< char > & data) const private inherited
Definition at line 176 of file Mqtt.cpp.
{
        LOG(TRACE) << "Send data:\n" << dataToHexString(data);
        mqttContext->send(data.data(), data.size());
    }
References iot::mqtt::Mqtt::dataToHexString(), iot::mqtt::Mqtt::mqttContext, and iot::mqtt::MqttContext::send().
Referenced by iot::mqtt::Mqtt::send().
sendConnack()
void iot::mqtt::server::Mqtt::sendConnack (uint8_t returnCode, uint8_t flags) const
Definition at line 316 of file Mqtt.cpp.
                                                                  { // Server
        send(iot::mqtt::packets::Connack(returnCode, flags));
    }
References iot::mqtt::packets::Connack::Connack(), and iot::mqtt::Mqtt::send().
Referenced by _onConnect(), and initSession().
sendPingresp()
void iot::mqtt::server::Mqtt::sendPingresp () const
Definition at line 328 of file Mqtt.cpp.
                                  { // Server
        send(iot::mqtt::packets::Pingresp());
    }
References iot::mqtt::packets::Pingresp::Pingresp(), and iot::mqtt::Mqtt::send().
Referenced by _onPingreq().
sendPuback()
void iot::mqtt::Mqtt::sendPuback (uint16_t packetIdentifier) const protected inherited
Definition at line 194 of file Mqtt.cpp.
                                                         { // Server & Client
        send(iot::mqtt::packets::Puback(packetIdentifier));
    }
References iot::mqtt::packets::Puback::Puback(), and iot::mqtt::Mqtt::send().
Referenced by iot::mqtt::Mqtt::_onPublish().
sendPubcomp()
void iot::mqtt::Mqtt::sendPubcomp (uint16_t packetIdentifier) const protected inherited
Definition at line 206 of file Mqtt.cpp.
                                                          { // Server & Client
        send(iot::mqtt::packets::Pubcomp(packetIdentifier));
    }
References iot::mqtt::packets::Pubcomp::Pubcomp(), and iot::mqtt::Mqtt::send().
Referenced by iot::mqtt::Mqtt::_onPubrel().
sendPublish()
void iot::mqtt::Mqtt::sendPublish (const std::string & topic, const std::string & message, uint8_t qoS, bool retain) inherited
Definition at line 182 of file Mqtt.cpp.
                                        { // Server & Client
        uint16_t pId = qoS != 0 ? getPacketIdentifier() : 0;
        send(iot::mqtt::packets::Publish(pId, topic, message, qoS, false, retain));
        if (qoS == 2) {
            session->publishMap.emplace(pId, iot::mqtt::packets::Publish(pId, topic, message, qoS, true, retain));
        }
    }
References iot::mqtt::Mqtt::getPacketIdentifier(), iot::mqtt::packets::Publish::Publish(), iot::mqtt::Session::publishMap, iot::mqtt::Mqtt::send(), and iot::mqtt::Mqtt::session.
Referenced by iot::mqtt::server::broker::Session::sendPublish().
sendPubrec()
void iot::mqtt::Mqtt::sendPubrec (uint16_t packetIdentifier) const protected inherited
Definition at line 198 of file Mqtt.cpp.
                                                         { // Server & Client
        send(iot::mqtt::packets::Pubrec(packetIdentifier));
    }
References iot::mqtt::packets::Pubrec::Pubrec(), and iot::mqtt::Mqtt::send().
Referenced by iot::mqtt::Mqtt::_onPublish().
sendPubrel()
void iot::mqtt::Mqtt::sendPubrel (uint16_t packetIdentifier) const protected inherited
Definition at line 202 of file Mqtt.cpp.
                                                         { // Server & Client
        send(iot::mqtt::packets::Pubrel(packetIdentifier));
    }
References iot::mqtt::packets::Pubrel::Pubrel(), and iot::mqtt::Mqtt::send().
Referenced by iot::mqtt::Mqtt::_onPubrec().
sendSuback()
void iot::mqtt::server::Mqtt::sendSuback (uint16_t packetIdentifier, std::list< uint8_t > & returnCodes) const
Definition at line 320 of file Mqtt.cpp.
                                                                                        { // Server
        send(iot::mqtt::packets::Suback(packetIdentifier, returnCodes));
    }
References iot::mqtt::Mqtt::send(), and iot::mqtt::packets::Suback::Suback().
Referenced by _onSubscribe().
sendUnsuback()
void iot::mqtt::server::Mqtt::sendUnsuback (uint16_t packetIdentifier) const
Definition at line 324 of file Mqtt.cpp.
                                                           { // Server
        send(iot::mqtt::packets::Unsuback(packetIdentifier));
    }
References iot::mqtt::Mqtt::send(), and iot::mqtt::packets::Unsuback::Unsuback().
Referenced by _onUnsubscribe().
setMqttContext()
void iot::mqtt::Mqtt::setMqttContext (MqttContext * mqttContext) inherited
Definition at line 59 of file Mqtt.cpp.
{
        this->mqttContext = mqttContext;
    }
References iot::mqtt::Mqtt::mqttContext.
Referenced by iot::mqtt::MqttContext::MqttContext().
stringToHexString()
std::string iot::mqtt::Mqtt::stringToHexString (const std::string data) static inherited
Definition at line 358 of file Mqtt.cpp.
{
        return dataToHexString(std::vector<char>(data.begin(), data.end()));
    }
References iot::mqtt::Mqtt::dataToHexString().
Referenced by iot::mqtt::Mqtt::_onPublish(), iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), iot::mqtt::server::broker::SubscribtionTree::TopicLevel::publish(), iot::mqtt::server::broker::RetainTree::TopicLevel::retain(), and iot::mqtt::server::broker::Session::sendPublish().
Friends And Related Symbol Documentation
iot::mqtt::server::packets::Connect
friend class iot::mqtt::server::packets::Connect friend
Definition at line 141 of file Mqtt.h.
iot::mqtt::server::packets::Disconnect
friend class iot::mqtt::server::packets::Disconnect friend
Definition at line 145 of file Mqtt.h.
iot::mqtt::server::packets::Pingreq
friend class iot::mqtt::server::packets::Pingreq friend
Definition at line 144 of file Mqtt.h.
iot::mqtt::server::packets::Puback
friend class iot::mqtt::server::packets::Puback friend
Definition at line 149 of file Mqtt.h.
iot::mqtt::server::packets::Pubcomp
friend class iot::mqtt::server::packets::Pubcomp friend
Definition at line 147 of file Mqtt.h.
iot::mqtt::server::packets::Publish
friend class iot::mqtt::server::packets::Publish friend
Definition at line 146 of file Mqtt.h.
iot::mqtt::server::packets::Pubrec
friend class iot::mqtt::server::packets::Pubrec friend
Definition at line 148 of file Mqtt.h.
iot::mqtt::server::packets::Pubrel
friend class iot::mqtt::server::packets::Pubrel friend
Definition at line 150 of file Mqtt.h.
iot::mqtt::server::packets::Subscribe
friend class iot::mqtt::server::packets::Subscribe friend
Definition at line 142 of file Mqtt.h.
iot::mqtt::server::packets::Unsubscribe
friend class iot::mqtt::server::packets::Unsubscribe friend
Definition at line 143 of file Mqtt.h.
Member Data Documentation
_packetIdentifier
uint16_t iot::mqtt::Mqtt::_packetIdentifier = 0 private inherited
Definition at line 117 of file Mqtt.h.
Referenced by iot::mqtt::Mqtt::getPacketIdentifier().
broker
std::shared_ptr<iot::mqtt::server::broker::Broker> iot::mqtt::server::Mqtt::broker protected
Definition at line 139 of file Mqtt.h.
cleanSession
bool iot::mqtt::server::Mqtt::cleanSession = false protected
Definition at line 137 of file Mqtt.h.
Referenced by _onConnect(), getCleanSession(), initSession(), and releaseSession().
clientId
std::string iot::mqtt::Mqtt::clientId protected inherited
Definition at line 111 of file Mqtt.h.
Referenced by _onConnect(), _onSubscribe(), _onUnsubscribe(), getClientId(), initSession(), iot::mqtt::Mqtt::Mqtt(), iot::mqtt::Mqtt::printVP(), releaseSession(), iot::mqtt::Mqtt::send(), and iot::mqtt::client::Mqtt::sendConnect().
connectFlags
uint8_t iot::mqtt::server::Mqtt::connectFlags = 0 protected
Definition at line 124 of file Mqtt.h.
Referenced by _onConnect(), and getConnectFlags().
controlPacketDeserializer
iot::mqtt::ControlPacketDeserializer* iot::mqtt::Mqtt::controlPacketDeserializer = nullptr private inherited
Definition at line 115 of file Mqtt.h.
Referenced by iot::mqtt::Mqtt::~Mqtt().
fixedHeader
iot::mqtt::FixedHeader iot::mqtt::Mqtt::fixedHeader private inherited
Definition at line 114 of file Mqtt.h.
Referenced by iot::mqtt::Mqtt::onProcess().
keepAlive
uint16_t iot::mqtt::server::Mqtt::keepAlive = 0 protected
Definition at line 125 of file Mqtt.h.
Referenced by _onConnect(), and getKeepAlive().
keepAliveTimer
core::timer::Timer iot::mqtt::Mqtt::keepAliveTimer private inherited
Definition at line 119 of file Mqtt.h.
Referenced by iot::mqtt::Mqtt::initSession(), and iot::mqtt::Mqtt::~Mqtt().
level
uint8_t iot::mqtt::server::Mqtt::level = 0 protected
Definition at line 123 of file Mqtt.h.
Referenced by _onConnect(), and getLevel().
mqttContext
MqttContext* iot::mqtt::Mqtt::mqttContext = nullptr protected inherited
Definition at line 126 of file Mqtt.h.
Referenced by iot::mqtt::client::Mqtt::_onConnack(), _onConnect(), _onDisconnect(), iot::mqtt::Mqtt::_onPuback(), iot::mqtt::Mqtt::_onPubcomp(), iot::mqtt::Mqtt::_onPublish(), iot::mqtt::Mqtt::_onPubrec(), iot::mqtt::Mqtt::_onPubrel(), iot::mqtt::client::Mqtt::_onSuback(), _onSubscribe(), iot::mqtt::client::Mqtt::_onUnsuback(), _onUnsubscribe(), iot::mqtt::Mqtt::getSocketConnection(), initSession(), iot::mqtt::Mqtt::initSession(), iot::mqtt::Mqtt::onProcess(), iot::mqtt::Mqtt::send(), and iot::mqtt::Mqtt::setMqttContext().
password
std::string iot::mqtt::server::Mqtt::password protected
Definition at line 130 of file Mqtt.h.
Referenced by _onConnect(), and getPassword().
passwordFlag
bool iot::mqtt::server::Mqtt::passwordFlag = false protected
Definition at line 133 of file Mqtt.h.
Referenced by _onConnect(), and getPasswordFlag().
protocol
std::string iot::mqtt::server::Mqtt::protocol protected
Definition at line 122 of file Mqtt.h.
Referenced by _onConnect(), and getProtocol().
session
Session* iot::mqtt::Mqtt::session = nullptr private inherited
Definition at line 123 of file Mqtt.h.
Referenced by iot::mqtt::Mqtt::_onPubcomp(), iot::mqtt::Mqtt::_onPublish(), iot::mqtt::Mqtt::_onPubrec(), iot::mqtt::Mqtt::_onPubrel(), iot::mqtt::Mqtt::initSession(), and iot::mqtt::Mqtt::sendPublish().
state
int iot::mqtt::Mqtt::state = 0 private inherited
Definition at line 121 of file Mqtt.h.
Referenced by iot::mqtt::Mqtt::onProcess().
username
std::string iot::mqtt::server::Mqtt::username protected
Definition at line 129 of file Mqtt.h.
Referenced by _onConnect(), and getUsername().
usernameFlag
bool iot::mqtt::server::Mqtt::usernameFlag = false protected
Definition at line 132 of file Mqtt.h.
Referenced by _onConnect(), and getUsernameFlag().
willFlag
bool iot::mqtt::server::Mqtt::willFlag = false protected
Definition at line 136 of file Mqtt.h.
Referenced by _onConnect(), _onDisconnect(), getWillFlag(), initSession(), onExit(), and ~Mqtt().
willMessage
std::string iot::mqtt::server::Mqtt::willMessage protected
Definition at line 128 of file Mqtt.h.
Referenced by _onConnect(), getWillMessage(), and ~Mqtt().
willQoS
uint8_t iot::mqtt::server::Mqtt::willQoS = 0 protected
Definition at line 135 of file Mqtt.h.
Referenced by _onConnect(), getWillQoS(), and ~Mqtt().
willRetain
bool iot::mqtt::server::Mqtt::willRetain = false protected
Definition at line 134 of file Mqtt.h.
Referenced by _onConnect(), getWillRetain(), and ~Mqtt().
willTopic
std::string iot::mqtt::server::Mqtt::willTopic protected
Definition at line 127 of file Mqtt.h.
Referenced by _onConnect(), getWillTopic(), and ~Mqtt().
The documentation for this class was generated from the following files:
iot/mqtt/server/Mqtt.h
iot/mqtt/server/Mqtt.cpp