snode.c: logger::Logger Class Reference
logger::Logger Class Reference
#include <Logger.h>
Public Member Functions
Logger ()=delete
~Logger ()=delete
Static Public Member Functions
static void init ()
static void setLogLevel (int level)
static void setVerboseLevel (int level)
static void logToFile (const std::string &logFile)
static void quiet ()
static void setCustomFormatSpec (const char *format, const el::FormatSpecifierValueResolver &resolver)
Static Protected Attributes
static el::Configurations conf
Detailed Description
Definition at line 39 of file Logger.h.
Constructor & Destructor Documentation
Logger()
logger::Logger::Logger () delete
~Logger()
logger::Logger::~Logger () delete
Member Function Documentation
init()
void logger::Logger::init () static
Definition at line 33 of file Logger.cpp.
                      {
        conf.setGlobally(el::ConfigurationType::Enabled, "true");
        conf.setGlobally(el::ConfigurationType::Format, "%datetime{%Y-%M-%d %H:%m:%s} %tick: %level %msg");
        conf.setGlobally(el::ConfigurationType::ToFile, "false");
        conf.setGlobally(el::ConfigurationType::ToStandardOutput, "true");
        conf.setGlobally(el::ConfigurationType::SubsecondPrecision, "2");
        conf.setGlobally(el::ConfigurationType::PerformanceTracking, "false");
        conf.setGlobally(el::ConfigurationType::MaxLogFileSize, "2097152");
        conf.setGlobally(el::ConfigurationType::LogFlushThreshold, "0");
        conf.set(el::Level::Verbose, el::ConfigurationType::Format, "%datetime{%Y-%M-%d %H:%m:%s} %tick: %msg");
        el::Loggers::addFlag(el::LoggingFlag::DisableApplicationAbortOnFatalLog);
        el::Loggers::addFlag(el::LoggingFlag::DisablePerformanceTrackingCheckpointComparison);
        el::Loggers::addFlag(el::LoggingFlag::ColoredTerminalOutput);
        el::Loggers::removeFlag(el::LoggingFlag::AllowVerboseIfModuleNotSpecified);
        el::Loggers::reconfigureLogger("default", conf);
        el::Logger* logger = el::Loggers::getLogger("default");
        std::string logFilename = logger->typedConfigurations()->filename(el::Level::Verbose).c_str();
        if (logFilename != "/dev/null") {
            conf.setGlobally(el::ConfigurationType::ToFile, "true");
            el::Loggers::reconfigureLogger("default", conf);
        }
    }
References conf.
Referenced by utils::Config::init().
logToFile()
void logger::Logger::logToFile (const std::string & logFile) static
Definition at line 108 of file Logger.cpp.
{
        conf.setGlobally(el::ConfigurationType::Filename, logFile);
        conf.setGlobally(el::ConfigurationType::ToFile, "true");
        el::Loggers::reconfigureLogger("default", conf);
    }
References conf.
Referenced by utils::Config::bootstrap().
quiet()
void logger::Logger::quiet () static
Definition at line 115 of file Logger.cpp.
                       {
        conf.setGlobally(el::ConfigurationType::ToStandardOutput, "false");
        el::Loggers::reconfigureLogger("default", conf);
    }
References conf.
Referenced by utils::Config::bootstrap(), and utils::Config::parse1().
setCustomFormatSpec()
void logger::Logger::setCustomFormatSpec (const char * format, const el::FormatSpecifierValueResolver & resolver) static
Definition at line 61 of file Logger.cpp.
{
        el::Helpers::installCustomFormatSpecifier(el::CustomFormatSpecifier(format, resolver));
    }
Referenced by core::EventLoop::init().
setLogLevel()
void logger::Logger::setLogLevel (int level) static
Definition at line 67 of file Logger.cpp.
{
        conf.set(el::Level::Trace, el::ConfigurationType::Enabled, "false");   // trace method/function calling
        conf.set(el::Level::Debug, el::ConfigurationType::Enabled, "false");   // typical assert messages - but we can go on
        conf.set(el::Level::Info, el::ConfigurationType::Enabled, "false");    // additional infos - what 's going on
        conf.set(el::Level::Warning, el::ConfigurationType::Enabled, "false"); // not that serious but mentioning
        conf.set(el::Level::Error, el::ConfigurationType::Enabled, "false");   // serious errors - but we can go on
        conf.set(el::Level::Fatal, el::ConfigurationType::Enabled, "false");   // asserts - stop - we can not go on
        switch (level) {
            case 6:
                conf.set(el::Level::Trace, el::ConfigurationType::Enabled, "true");
                [[fallthrough]];
            case 5:
                conf.set(el::Level::Debug, el::ConfigurationType::Enabled, "true");
                [[fallthrough]];
            case 4:
                conf.set(el::Level::Info, el::ConfigurationType::Enabled, "true");
                [[fallthrough]];
            case 3:
                conf.set(el::Level::Warning, el::ConfigurationType::Enabled, "true");
                [[fallthrough]];
            case 2:
                conf.set(el::Level::Error, el::ConfigurationType::Enabled, "true");
                [[fallthrough]];
            case 1:
                conf.set(el::Level::Fatal, el::ConfigurationType::Enabled, "true");
                [[fallthrough]];
            case 0:
                [[fallthrough]];
            default:;
        }
        el::Loggers::reconfigureLogger("default", conf);
    }
References conf.
Referenced by utils::Config::parse1().
setVerboseLevel()
void logger::Logger::setVerboseLevel (int level) static
Definition at line 102 of file Logger.cpp.
{
        if (level >= 0) {
            el::Loggers::setVerboseLevel(static_cast<el::base::type::VerboseLevel>(level));
        }
    }
Referenced by utils::Config::parse1().
Member Data Documentation
conf
el::Configurations logger::Logger::conf static protected
Definition at line 58 of file Logger.h.
Referenced by init(), logToFile(), quiet(), and setLogLevel().
The documentation for this class was generated from the following files:
log/Logger.h
log/Logger.cpp