SNode.C: database::mariadb::MariaDBConnection Class Reference
database::mariadb::MariaDBConnection Class Reference
#include <MariaDBConnection.h>
Public Member Functions
MariaDBConnection (MariaDBClient *mariaDBClient, const MariaDBConnectionDetails &connectionDetails)
MariaDBConnection (const MariaDBConnection &)=delete
~MariaDBConnection () override
MariaDBConnection & operator= (const MariaDBConnection &)=delete
MariaDBCommandSequence & execute_async (MariaDBCommandSequence &&commandSequence)
void execute_sync (MariaDBCommand *mariaDBCommand)
void commandStart (const utils::Timeval &currentTime)
void commandContinue (int status)
void commandCompleted ()
void unmanaged ()
Protected Member Functions
void checkStatus (int status)
void readEvent () override
void writeEvent () override
void outOfBandEvent () override
void readTimeout () override
void writeTimeout () override
void outOfBandTimeout () override
void unobservedEvent () override
Private Member Functions
void dispatchEvent () final
void timeoutEvent () final
int getRegisteredFd ()
void enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
virtual void terminate ()
void onEvent (const utils::Timeval &currentTime) final
virtual void onExit (int sig)
void triggered (const utils::Timeval &currentTime)
void setEnabled (const utils::Timeval &currentTime)
void setDisabled ()
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
int getRegisteredFd ()
void enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
void span ()
void relax ()
const std::string & getName () const
int getRegisteredFd ()
void enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
void span ()
void relax ()
const std::string & getName () const
Private Attributes
MariaDBClient * mariaDBClient
MYSQL * mysql
std::deque< MariaDBCommandSequence > commandSequenceQueue
MariaDBCommand * currentCommand = nullptr
bool connected = false
MariaDBCommandStartEvent commandStartEvent
DescriptorEventPublisher & descriptorEventPublisher
int observedFd = -1
bool enabled = false
bool suspended = false
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
int observationCounter = 0
Event event
Detailed Description
Definition at line 63 of file MariaDBConnection.h.
Constructor & Destructor Documentation
MariaDBConnection() [1/2]
database::mariadb::MariaDBConnection::MariaDBConnection (MariaDBClient * mariaDBClient, const MariaDBConnectionDetails & connectionDetails) explicit
Definition at line 40 of file MariaDBConnection.cpp.
        : ReadEventReceiver("MariaDBConnectionRead", core::DescriptorEventReceiver::TIMEOUT::DISABLE)
        , WriteEventReceiver("MariaDBConnectionWrite", core::DescriptorEventReceiver::TIMEOUT::DISABLE)
        , ExceptionalConditionEventReceiver("MariaDBConnectionExceptional", core::DescriptorEventReceiver::TIMEOUT::DISABLE)
        , mariaDBClient(mariaDBClient)
        , mysql(mysql_init(nullptr))
        , commandStartEvent("MariaDBCommandStartEvent", this) {
        mysql_options(mysql, MYSQL_OPT_NONBLOCK, nullptr);
        execute_async(std::move(MariaDBCommandSequence().execute_async(new database::mariadb::commands::async::MariaDBConnectCommand(
            connectionDetails,
            [this]() -> void {
                if (mysql_errno(mysql) == 0) {
                    int fd = mysql_get_socket(mysql);
                    LOG(DEBUG) << "Got valid descriptor: " << fd;
                    ReadEventReceiver::enable(fd);
                    WriteEventReceiver::enable(fd);
                    ExceptionalConditionEventReceiver::enable(fd);
                    ReadEventReceiver::suspend();
                    WriteEventReceiver::suspend();
                    ExceptionalConditionEventReceiver::suspend();
                    connected = true;
                } else {
                    LOG(WARNING) << "Got no valid descriptor: " << mysql_error(mysql) << ", " << mysql_errno(mysql);
                }
            },
            []() -> void {
                LOG(DEBUG) << "Connect success";
            },
            [](const std::string& errorString, unsigned int errorNumber) -> void {
                LOG(WARNING) << "Connect error: " << errorString << " : " << errorNumber;
            }))));
    }
References commandStartEvent, core::DescriptorEventReceiver::TIMEOUT::DISABLE, mariaDBClient, and MariaDBConnection().
Referenced by database::mariadb::MariaDBClient::execute_async(), database::mariadb::MariaDBClient::execute_sync(), and MariaDBConnection().
MariaDBConnection() [2/2]
database::mariadb::MariaDBConnection::MariaDBConnection (const MariaDBConnection &) delete
~MariaDBConnection()
database::mariadb::MariaDBConnection::~MariaDBConnection () override
Definition at line 78 of file MariaDBConnection.cpp.
{
        for (MariaDBCommandSequence& mariaDBCommandSequence : commandSequenceQueue) {
            for (MariaDBCommand* mariaDBCommand : mariaDBCommandSequence.sequence()) {
                if (core::SNodeC::state() == core::State::RUNNING && connected) {
                    mariaDBCommand->commandError(mysql_error(mysql), mysql_errno(mysql));
                }
                delete mariaDBCommand;
            }
        }
        if (mariaDBClient != nullptr) {
            mariaDBClient->connectionVanished();
        }
        mysql_close(mysql);
        mysql_library_end();
    }
References database::mariadb::MariaDBClient::connectionVanished(), and mariaDBClient.
Member Function Documentation
checkStatus()
void database::mariadb::MariaDBConnection::checkStatus (int status) protected
Definition at line 163 of file MariaDBConnection.cpp.
{
        if (connected) {
            if ((status & MYSQL_WAIT_READ) != 0) {
                if (ReadEventReceiver::isSuspended() && ReadEventReceiver::isEnabled()) {
                    ReadEventReceiver::resume();
                }
            } else if (!ReadEventReceiver::isSuspended()) {
                ReadEventReceiver::suspend();
            }
            if ((status & MYSQL_WAIT_WRITE) != 0) {
                if (WriteEventReceiver::isSuspended() && WriteEventReceiver::isEnabled()) {
                    WriteEventReceiver::resume();
                }
            } else if (!WriteEventReceiver::isSuspended()) {
                WriteEventReceiver::suspend();
            }
            if ((status & MYSQL_WAIT_EXCEPT) != 0) {
                if (ExceptionalConditionEventReceiver::isSuspended() && ExceptionalConditionEventReceiver::isEnabled()) {
                    ExceptionalConditionEventReceiver::resume();
                }
            } else if (!ExceptionalConditionEventReceiver::isSuspended()) {
                ExceptionalConditionEventReceiver::suspend();
            }
            if ((status & MYSQL_WAIT_TIMEOUT) != 0) {
                ReadEventReceiver::setTimeout(mysql_get_timeout_value(mysql));
                //                WriteEventReceiver::setTimeout(mysql_get_timeout_value(mysql));
                //                ExceptionalConditionEventReceiver::setTimeout(mysql_get_timeout_value(mysql));
            } else {
                ReadEventReceiver::setTimeout(core::DescriptorEventReceiver::TIMEOUT::DEFAULT);
                //                WriteEventReceiver::setTimeout(core::DescriptorEventReceiver::TIMEOUT::DEFAULT);
                //                ExceptionalConditionEventReceiver::setTimeout(core::DescriptorEventReceiver::TIMEOUT::DEFAULT);
            }
            if (status == 0) {
                if (mysql_errno(mysql) == 0) {
                    if (currentCommand->commandCompleted()) {
                        commandCompleted();
                    }
                } else {
                    currentCommand->commandError(mysql_error(mysql), mysql_errno(mysql));
                    commandCompleted();
                }
                commandStartEvent.span();
            }
        } else {
            currentCommand->commandError(mysql_error(mysql), mysql_errno(mysql));
            commandCompleted();
            delete this;
        }
    }
References commandCompleted(), database::mariadb::MariaDBCommand::commandCompleted(), commandStartEvent, connected, currentCommand, core::DescriptorEventReceiver::TIMEOUT::DEFAULT, core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setTimeout(), core::EventReceiver::span(), and core::DescriptorEventReceiver::suspend().
Referenced by commandContinue().
checkTimeout() [1/3]
void core::DescriptorEventReceiver::checkTimeout (const utils::Timeval & currentTime) inherited
Definition at line 159 of file DescriptorEventReceiver.cpp.
{
        if (maxInactivity > 0 && currentTime - lastTriggered >= maxInactivity) {
            timeoutEvent();
        }
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), utils::Timeval::operator>(), utils::Timeval::operator>=(), and core::DescriptorEventReceiver::timeoutEvent().
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents().
checkTimeout() [2/3]
void core::DescriptorEventReceiver::checkTimeout (const utils::Timeval & currentTime) inherited
Definition at line 159 of file DescriptorEventReceiver.cpp.
{
        if (maxInactivity > 0 && currentTime - lastTriggered >= maxInactivity) {
            timeoutEvent();
        }
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), utils::Timeval::operator>(), utils::Timeval::operator>=(), and core::DescriptorEventReceiver::timeoutEvent().
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents().
checkTimeout() [3/3]
void core::DescriptorEventReceiver::checkTimeout (const utils::Timeval & currentTime) inherited
Definition at line 159 of file DescriptorEventReceiver.cpp.
{
        if (maxInactivity > 0 && currentTime - lastTriggered >= maxInactivity) {
            timeoutEvent();
        }
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), utils::Timeval::operator>(), utils::Timeval::operator>=(), and core::DescriptorEventReceiver::timeoutEvent().
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents().
commandCompleted()
void database::mariadb::MariaDBConnection::commandCompleted ()
Definition at line 147 of file MariaDBConnection.cpp.
{
        LOG(DEBUG) << "Completed: " << currentCommand->commandInfo();
        commandSequenceQueue.front().commandCompleted();
        if (commandSequenceQueue.front().empty()) {
            commandSequenceQueue.pop_front();
        }
        delete currentCommand;
        currentCommand = nullptr;
    }
References database::mariadb::MariaDBCommand::commandInfo(), and currentCommand.
Referenced by checkStatus().
commandContinue()
void database::mariadb::MariaDBConnection::commandContinue (int status)
Definition at line 137 of file MariaDBConnection.cpp.
{
        if (currentCommand != nullptr) {
            checkStatus(currentCommand->commandContinue(status));
        } else if ((status & MYSQL_WAIT_READ) != 0 && commandSequenceQueue.empty()) {
            ReadEventReceiver::disable();
            WriteEventReceiver::disable();
            ExceptionalConditionEventReceiver::disable();
        }
    }
References checkStatus(), database::mariadb::MariaDBCommand::commandContinue(), currentCommand, and core::DescriptorEventReceiver::disable().
commandStart()
void database::mariadb::MariaDBConnection::commandStart (const utils::Timeval & currentTime)
Definition at line 120 of file MariaDBConnection.cpp.
{
        if (!commandSequenceQueue.empty()) {
            currentCommand = commandSequenceQueue.front().nextCommand();
            currentCommand->setMariaDBConnection(this);
            checkStatus(currentCommand->commandStart(mysql, currentTime));
        } else if (mariaDBClient != nullptr) {
            if (ReadEventReceiver::isSuspended() && ReadEventReceiver::isEnabled()) {
                ReadEventReceiver::resume();
            }
        } else {
            ReadEventReceiver::disable();
            WriteEventReceiver::disable();
            ExceptionalConditionEventReceiver::disable();
        }
    }
References currentCommand, core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::isSuspended(), mariaDBClient, core::DescriptorEventReceiver::resume(), and database::mariadb::MariaDBCommand::setMariaDBConnection().
Referenced by database::mariadb::MariaDBCommandStartEvent::onEvent().
destruct()
void core::EventReceiver::destruct () virtual inherited
Reimplemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, and database::mariadb::MariaDBCommandStartEvent.
Definition at line 31 of file EventReceiver.cpp.
{
        delete this;
    }
Referenced by core::EventMultiplexer::EventQueue::clear().
disable() [1/3]
void core::DescriptorEventReceiver::disable () inherited
Definition at line 67 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!isSuspended()) {
                suspend();
            }
            enabled = false;
            descriptorEventPublisher.disable(this);
        } else {
            LOG(TRACE) << "Double disable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::disable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::observedFd, and core::DescriptorEventReceiver::suspend().
Referenced by core::eventreceiver::AcceptEventReceiver::acceptTimeout(), commandContinue(), commandStart(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectEvent(), core::eventreceiver::ConnectEventReceiver::connectTimeout(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectTimeout(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::pipe::PipeSource::eof(), core::eventreceiver::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSink::readEvent(), core::eventreceiver::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::DescriptorEventReceiver::terminate(), core::socket::stream::SocketWriter< PhysicalSocketT >::terminate(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), core::pipe::PipeSource::writeEvent(), core::eventreceiver::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
disable() [2/3]
void core::DescriptorEventReceiver::disable () inherited
Definition at line 67 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!isSuspended()) {
                suspend();
            }
            enabled = false;
            descriptorEventPublisher.disable(this);
        } else {
            LOG(TRACE) << "Double disable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::disable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::observedFd, and core::DescriptorEventReceiver::suspend().
Referenced by core::eventreceiver::AcceptEventReceiver::acceptTimeout(), commandContinue(), commandStart(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectEvent(), core::eventreceiver::ConnectEventReceiver::connectTimeout(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectTimeout(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::pipe::PipeSource::eof(), core::eventreceiver::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSink::readEvent(), core::eventreceiver::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::DescriptorEventReceiver::terminate(), core::socket::stream::SocketWriter< PhysicalSocketT >::terminate(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), core::pipe::PipeSource::writeEvent(), core::eventreceiver::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
disable() [3/3]
void core::DescriptorEventReceiver::disable () inherited
Definition at line 67 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!isSuspended()) {
                suspend();
            }
            enabled = false;
            descriptorEventPublisher.disable(this);
        } else {
            LOG(TRACE) << "Double disable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::disable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::observedFd, and core::DescriptorEventReceiver::suspend().
Referenced by core::eventreceiver::AcceptEventReceiver::acceptTimeout(), commandContinue(), commandStart(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectEvent(), core::eventreceiver::ConnectEventReceiver::connectTimeout(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectTimeout(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::pipe::PipeSource::eof(), core::eventreceiver::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSink::readEvent(), core::eventreceiver::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::DescriptorEventReceiver::terminate(), core::socket::stream::SocketWriter< PhysicalSocketT >::terminate(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), core::pipe::PipeSource::writeEvent(), core::eventreceiver::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
dispatchEvent()
void core::eventreceiver::ReadEventReceiver::dispatchEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 41 of file ReadEventReceiver.cpp.
{
        readEvent();
    }
References core::eventreceiver::ReadEventReceiver::readEvent().
enable() [1/3]
void core::DescriptorEventReceiver::enable (int fd) inherited
Definition at line 50 of file DescriptorEventReceiver.cpp.
{
        if (!enabled) {
            observedFd = fd;
            enabled = true;
            descriptorEventPublisher.enable(this);
        } else {
            LOG(TRACE) << "Double enable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::enable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), and core::DescriptorEventReceiver::observedFd.
Referenced by core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >::connectTimeout(), core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
enable() [2/3]
void core::DescriptorEventReceiver::enable (int fd) inherited
Definition at line 50 of file DescriptorEventReceiver.cpp.
{
        if (!enabled) {
            observedFd = fd;
            enabled = true;
            descriptorEventPublisher.enable(this);
        } else {
            LOG(TRACE) << "Double enable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::enable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), and core::DescriptorEventReceiver::observedFd.
Referenced by core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >::connectTimeout(), core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
enable() [3/3]
void core::DescriptorEventReceiver::enable (int fd) inherited
Definition at line 50 of file DescriptorEventReceiver.cpp.
{
        if (!enabled) {
            observedFd = fd;
            enabled = true;
            descriptorEventPublisher.enable(this);
        } else {
            LOG(TRACE) << "Double enable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::enable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), and core::DescriptorEventReceiver::observedFd.
Referenced by core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >::connectTimeout(), core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
execute_async()
MariaDBCommandSequence & database::mariadb::MariaDBConnection::execute_async (MariaDBCommandSequence && commandSequence)
Definition at line 97 of file MariaDBConnection.cpp.
{
        if (currentCommand == nullptr && commandSequenceQueue.empty()) {
            commandStartEvent.span();
        }
        commandSequenceQueue.emplace_back(std::move(commandSequence));
        return commandSequenceQueue.back();
    }
References commandStartEvent, and core::EventReceiver::span().
Referenced by database::mariadb::MariaDBClient::execute_async().
execute_sync()
void database::mariadb::MariaDBConnection::execute_sync (MariaDBCommand * mariaDBCommand)
Definition at line 107 of file MariaDBConnection.cpp.
{
        mariaDBCommand->commandStart(mysql, utils::Timeval::currentTime());
        if (mysql_errno(mysql) == 0) {
            if (mariaDBCommand->commandCompleted()) {
            }
        } else {
            mariaDBCommand->commandError(mysql_error(mysql), mysql_errno(mysql));
        }
        delete mariaDBCommand;
    }
References database::mariadb::MariaDBCommand::commandCompleted().
Referenced by database::mariadb::MariaDBClient::execute_sync().
getName() [1/3]
const std::string & core::EventReceiver::getName () const inherited
Definition at line 43 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
getName() [2/3]
const std::string & core::EventReceiver::getName () const inherited
Definition at line 43 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
getName() [3/3]
const std::string & core::EventReceiver::getName () const inherited
Definition at line 43 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
getObservationCounter()
int core::Observer::getObservationCounter () inline inherited
Definition at line 55 of file DescriptorEventReceiver.h.
{
            return observationCounter;
        }
References core::Observer::observationCounter.
getRegisteredFd() [1/3]
int core::DescriptorEventReceiver::getRegisteredFd () inherited
Definition at line 46 of file DescriptorEventReceiver.cpp.
{
        return observedFd;
    }
References core::DescriptorEventReceiver::observedFd.
Referenced by core::DescriptorEventPublisher::enable(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::select::DescriptorEventPublisher::muxAdd(), core::poll::PollFdsManager::muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOff(), core::select::DescriptorEventPublisher::muxOff(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOn(), core::select::DescriptorEventPublisher::muxOn(), core::poll::PollFdsManager::muxOn(), core::pipe::PipeSink::readEvent(), core::pipe::PipeSource::writeEvent(), core::pipe::PipeSink::~PipeSink(), and core::pipe::PipeSource::~PipeSource().
getRegisteredFd() [2/3]
int core::DescriptorEventReceiver::getRegisteredFd () inherited
Definition at line 46 of file DescriptorEventReceiver.cpp.
{
        return observedFd;
    }
References core::DescriptorEventReceiver::observedFd.
Referenced by core::DescriptorEventPublisher::enable(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::select::DescriptorEventPublisher::muxAdd(), core::poll::PollFdsManager::muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOff(), core::select::DescriptorEventPublisher::muxOff(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOn(), core::select::DescriptorEventPublisher::muxOn(), core::poll::PollFdsManager::muxOn(), core::pipe::PipeSink::readEvent(), core::pipe::PipeSource::writeEvent(), core::pipe::PipeSink::~PipeSink(), and core::pipe::PipeSource::~PipeSource().
getRegisteredFd() [3/3]
int core::DescriptorEventReceiver::getRegisteredFd () inherited
Definition at line 46 of file DescriptorEventReceiver.cpp.
{
        return observedFd;
    }
References core::DescriptorEventReceiver::observedFd.
Referenced by core::DescriptorEventPublisher::enable(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::select::DescriptorEventPublisher::muxAdd(), core::poll::PollFdsManager::muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOff(), core::select::DescriptorEventPublisher::muxOff(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOn(), core::select::DescriptorEventPublisher::muxOn(), core::poll::PollFdsManager::muxOn(), core::pipe::PipeSink::readEvent(), core::pipe::PipeSource::writeEvent(), core::pipe::PipeSink::~PipeSink(), and core::pipe::PipeSource::~PipeSource().
getTimeout() [1/3]
utils::Timeval core::DescriptorEventReceiver::getTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 141 of file DescriptorEventReceiver.cpp.
{
        return maxInactivity > 0 ? currentTime > lastTriggered ? maxInactivity - (currentTime - lastTriggered) : 0 : TIMEOUT::MAX;
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::DescriptorEventPublisher::getNextTimeout().
getTimeout() [2/3]
utils::Timeval core::DescriptorEventReceiver::getTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 141 of file DescriptorEventReceiver.cpp.
{
        return maxInactivity > 0 ? currentTime > lastTriggered ? maxInactivity - (currentTime - lastTriggered) : 0 : TIMEOUT::MAX;
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::DescriptorEventPublisher::getNextTimeout().
getTimeout() [3/3]
utils::Timeval core::DescriptorEventReceiver::getTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 141 of file DescriptorEventReceiver.cpp.
{
        return maxInactivity > 0 ? currentTime > lastTriggered ? maxInactivity - (currentTime - lastTriggered) : 0 : TIMEOUT::MAX;
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::DescriptorEventPublisher::getNextTimeout().
isEnabled() [1/3]
bool core::DescriptorEventReceiver::isEnabled () const inherited
Definition at line 84 of file DescriptorEventReceiver.cpp.
{
        return enabled;
    }
References core::DescriptorEventReceiver::enabled.
Referenced by checkStatus(), commandStart(), core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >::connectTimeout(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), and core::DescriptorEventReceiver::terminate().
isEnabled() [2/3]
bool core::DescriptorEventReceiver::isEnabled () const inherited
Definition at line 84 of file DescriptorEventReceiver.cpp.
{
        return enabled;
    }
References core::DescriptorEventReceiver::enabled.
Referenced by checkStatus(), commandStart(), core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >::connectTimeout(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), and core::DescriptorEventReceiver::terminate().
isEnabled() [3/3]
bool core::DescriptorEventReceiver::isEnabled () const inherited
Definition at line 84 of file DescriptorEventReceiver.cpp.
{
        return enabled;
    }
References core::DescriptorEventReceiver::enabled.
Referenced by checkStatus(), commandStart(), core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >::connectTimeout(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), and core::DescriptorEventReceiver::terminate().
isObserved()
bool core::Observer::isObserved () inline inherited
Definition at line 43 of file DescriptorEventReceiver.h.
{
            return observationCounter > 0;
        }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
isSuspended() [1/3]
bool core::DescriptorEventReceiver::isSuspended () const inherited
Definition at line 121 of file DescriptorEventReceiver.cpp.
{
        return suspended;
    }
References core::DescriptorEventReceiver::suspended.
Referenced by checkStatus(), commandStart(), core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::pipe::PipeSource::send().
isSuspended() [2/3]
bool core::DescriptorEventReceiver::isSuspended () const inherited
Definition at line 121 of file DescriptorEventReceiver.cpp.
{
        return suspended;
    }
References core::DescriptorEventReceiver::suspended.
Referenced by checkStatus(), commandStart(), core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::pipe::PipeSource::send().
isSuspended() [3/3]
bool core::DescriptorEventReceiver::isSuspended () const inherited
Definition at line 121 of file DescriptorEventReceiver.cpp.
{
        return suspended;
    }
References core::DescriptorEventReceiver::suspended.
Referenced by checkStatus(), commandStart(), core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::pipe::PipeSource::send().
observed()
void core::Observer::observed () inline inherited
Definition at line 47 of file DescriptorEventReceiver.h.
{
            observationCounter++;
        }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setEnabled().
onEvent()
void core::DescriptorEventReceiver::onEvent (const utils::Timeval & currentTime) final private virtual inherited
Implements core::EventReceiver.
Definition at line 145 of file DescriptorEventReceiver.cpp.
{
        eventCounter++;
        triggered(currentTime);
        dispatchEvent();
    }
References core::DescriptorEventReceiver::dispatchEvent(), core::DescriptorEventReceiver::eventCounter, and core::DescriptorEventReceiver::triggered().
onExit()
void core::DescriptorEventReceiver::onExit (int sig) private virtual inherited
Definition at line 152 of file DescriptorEventReceiver.cpp.
{
    }
Referenced by core::DescriptorEventPublisher::sigExit().
operator=()
MariaDBConnection & database::mariadb::MariaDBConnection::operator= (const MariaDBConnection &) delete
outOfBandEvent()
void database::mariadb::MariaDBConnection::outOfBandEvent () override protected virtual
Implements core::eventreceiver::ExceptionalConditionEventReceiver.
Definition at line 225 of file MariaDBConnection.cpp.
{
        commandContinue(MYSQL_WAIT_EXCEPT);
    }
outOfBandTimeout()
void database::mariadb::MariaDBConnection::outOfBandTimeout () override protected virtual
Reimplemented from core::eventreceiver::ExceptionalConditionEventReceiver.
Definition at line 237 of file MariaDBConnection.cpp.
{
        commandContinue(MYSQL_WAIT_TIMEOUT);
    }
readEvent()
void database::mariadb::MariaDBConnection::readEvent () override protected virtual
Implements core::eventreceiver::ReadEventReceiver.
Definition at line 217 of file MariaDBConnection.cpp.
{
        commandContinue(MYSQL_WAIT_READ);
    }
readTimeout()
void database::mariadb::MariaDBConnection::readTimeout () override protected virtual
Reimplemented from core::eventreceiver::ReadEventReceiver.
Definition at line 229 of file MariaDBConnection.cpp.
{
        commandContinue(MYSQL_WAIT_TIMEOUT);
    }
relax() [1/3]
void core::EventReceiver::relax () inherited
Definition at line 39 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
relax() [2/3]
void core::EventReceiver::relax () inherited
Definition at line 39 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
relax() [3/3]
void core::EventReceiver::relax () inherited
Definition at line 39 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
resume() [1/3]
void core::DescriptorEventReceiver::resume () inherited
Definition at line 104 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (suspended) {
                suspended = false;
                lastTriggered = utils::Timeval::currentTime();
                if (isObserved()) {
                    descriptorEventPublisher.resume(this);
                }
            } else {
                LOG(TRACE) << "Double resume: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "Resume while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::Observer::isObserved(), core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::observedFd, utils::Timeval::operator=(), core::DescriptorEventPublisher::resume(), and core::DescriptorEventReceiver::suspended.
Referenced by checkStatus(), commandStart(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
resume() [2/3]
void core::DescriptorEventReceiver::resume () inherited
Definition at line 104 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (suspended) {
                suspended = false;
                lastTriggered = utils::Timeval::currentTime();
                if (isObserved()) {
                    descriptorEventPublisher.resume(this);
                }
            } else {
                LOG(TRACE) << "Double resume: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "Resume while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::Observer::isObserved(), core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::observedFd, utils::Timeval::operator=(), core::DescriptorEventPublisher::resume(), and core::DescriptorEventReceiver::suspended.
Referenced by checkStatus(), commandStart(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
resume() [3/3]
void core::DescriptorEventReceiver::resume () inherited
Definition at line 104 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (suspended) {
                suspended = false;
                lastTriggered = utils::Timeval::currentTime();
                if (isObserved()) {
                    descriptorEventPublisher.resume(this);
                }
            } else {
                LOG(TRACE) << "Double resume: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "Resume while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::Observer::isObserved(), core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::observedFd, utils::Timeval::operator=(), core::DescriptorEventPublisher::resume(), and core::DescriptorEventReceiver::suspended.
Referenced by checkStatus(), commandStart(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
setDisabled()
void core::DescriptorEventReceiver::setDisabled () private inherited
Definition at line 80 of file DescriptorEventReceiver.cpp.
{
        unObserved();
    }
References core::Observer::unObserved().
setEnabled()
void core::DescriptorEventReceiver::setEnabled (const utils::Timeval & currentTime) private inherited
Definition at line 61 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
        observed();
    }
References core::DescriptorEventReceiver::lastTriggered, core::Observer::observed(), and utils::Timeval::operator=().
Referenced by core::DescriptorEventPublisher::enable().
setTimeout() [1/3]
void core::DescriptorEventReceiver::setTimeout (const utils::Timeval & timeout) inherited
Definition at line 131 of file DescriptorEventReceiver.cpp.
{
        if (timeout == TIMEOUT::DEFAULT) {
            this->maxInactivity = initialTimeout;
        } else {
            this->maxInactivity = timeout;
        }
        triggered(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::TIMEOUT::DEFAULT, core::DescriptorEventReceiver::initialTimeout, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator=(), utils::Timeval::operator==(), and core::DescriptorEventReceiver::triggered().
Referenced by checkStatus(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::initConnectEvent(), core::socket::stream::SocketReader< PhysicalSocketT >::terminate(), and core::socket::stream::SocketWriter< PhysicalSocketT >::terminate().
setTimeout() [2/3]
void core::DescriptorEventReceiver::setTimeout (const utils::Timeval & timeout) inherited
Definition at line 131 of file DescriptorEventReceiver.cpp.
{
        if (timeout == TIMEOUT::DEFAULT) {
            this->maxInactivity = initialTimeout;
        } else {
            this->maxInactivity = timeout;
        }
        triggered(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::TIMEOUT::DEFAULT, core::DescriptorEventReceiver::initialTimeout, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator=(), utils::Timeval::operator==(), and core::DescriptorEventReceiver::triggered().
Referenced by checkStatus(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::initConnectEvent(), core::socket::stream::SocketReader< PhysicalSocketT >::terminate(), and core::socket::stream::SocketWriter< PhysicalSocketT >::terminate().
setTimeout() [3/3]
void core::DescriptorEventReceiver::setTimeout (const utils::Timeval & timeout) inherited
Definition at line 131 of file DescriptorEventReceiver.cpp.
{
        if (timeout == TIMEOUT::DEFAULT) {
            this->maxInactivity = initialTimeout;
        } else {
            this->maxInactivity = timeout;
        }
        triggered(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::TIMEOUT::DEFAULT, core::DescriptorEventReceiver::initialTimeout, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator=(), utils::Timeval::operator==(), and core::DescriptorEventReceiver::triggered().
Referenced by checkStatus(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::initConnectEvent(), core::socket::stream::SocketReader< PhysicalSocketT >::terminate(), and core::socket::stream::SocketWriter< PhysicalSocketT >::terminate().
span() [1/3]
void core::EventReceiver::span () inherited
Definition at line 35 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by checkStatus(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), execute_async(), core::file::FileReader::FileReader(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
span() [2/3]
void core::EventReceiver::span () inherited
Definition at line 35 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by checkStatus(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), execute_async(), core::file::FileReader::FileReader(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
span() [3/3]
void core::EventReceiver::span () inherited
Definition at line 35 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by checkStatus(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), execute_async(), core::file::FileReader::FileReader(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
suspend() [1/3]
void core::DescriptorEventReceiver::suspend () inherited
Definition at line 88 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!suspended) {
                suspended = true;
                if (isObserved()) {
                    descriptorEventPublisher.suspend(this);
                }
            } else {
                LOG(TRACE) << "Double suspend: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "Suspend while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::Observer::isObserved(), core::DescriptorEventReceiver::observedFd, core::DescriptorEventPublisher::suspend(), and core::DescriptorEventReceiver::suspended.
Referenced by checkStatus(), core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), and core::pipe::PipeSource::writeEvent().
suspend() [2/3]
void core::DescriptorEventReceiver::suspend () inherited
Definition at line 88 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!suspended) {
                suspended = true;
                if (isObserved()) {
                    descriptorEventPublisher.suspend(this);
                }
            } else {
                LOG(TRACE) << "Double suspend: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "Suspend while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::Observer::isObserved(), core::DescriptorEventReceiver::observedFd, core::DescriptorEventPublisher::suspend(), and core::DescriptorEventReceiver::suspended.
Referenced by checkStatus(), core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), and core::pipe::PipeSource::writeEvent().
suspend() [3/3]
void core::DescriptorEventReceiver::suspend () inherited
Definition at line 88 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!suspended) {
                suspended = true;
                if (isObserved()) {
                    descriptorEventPublisher.suspend(this);
                }
            } else {
                LOG(TRACE) << "Double suspend: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "Suspend while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::Observer::isObserved(), core::DescriptorEventReceiver::observedFd, core::DescriptorEventPublisher::suspend(), and core::DescriptorEventReceiver::suspended.
Referenced by checkStatus(), core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), and core::pipe::PipeSource::writeEvent().
terminate()
void core::DescriptorEventReceiver::terminate () virtual inherited
Reimplemented in core::socket::stream::SocketReader< PhysicalSocketT >, core::socket::stream::SocketWriter< PhysicalSocketT >, core::pipe::PipeSink, and core::pipe::PipeSource.
Definition at line 125 of file DescriptorEventReceiver.cpp.
{
        if (isEnabled()) {
            disable();
        }
    }
References core::DescriptorEventReceiver::disable(), and core::DescriptorEventReceiver::isEnabled().
Referenced by core::DescriptorEventPublisher::stop(), core::pipe::PipeSink::terminate(), and core::pipe::PipeSource::terminate().
timeoutEvent()
void core::eventreceiver::ReadEventReceiver::timeoutEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 45 of file ReadEventReceiver.cpp.
{
        readTimeout();
    }
References core::eventreceiver::ReadEventReceiver::readTimeout().
triggered()
void core::DescriptorEventReceiver::triggered (const utils::Timeval & currentTime) private inherited
Definition at line 155 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
    }
References core::DescriptorEventReceiver::lastTriggered, and utils::Timeval::operator=().
Referenced by core::DescriptorEventReceiver::onEvent(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::DescriptorEventReceiver::setTimeout().
unmanaged()
void database::mariadb::MariaDBConnection::unmanaged ()
Definition at line 159 of file MariaDBConnection.cpp.
{
        mariaDBClient = nullptr;
    }
References mariaDBClient.
Referenced by database::mariadb::MariaDBClient::~MariaDBClient().
unObserved()
void core::Observer::unObserved () inline inherited
Definition at line 51 of file DescriptorEventReceiver.h.
{
            observationCounter--;
        }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setDisabled().
unobservedEvent()
void database::mariadb::MariaDBConnection::unobservedEvent () override protected virtual
Implements core::Observer.
Definition at line 241 of file MariaDBConnection.cpp.
{
        delete this;
    }
writeEvent()
void database::mariadb::MariaDBConnection::writeEvent () override protected virtual
Implements core::eventreceiver::WriteEventReceiver.
Definition at line 221 of file MariaDBConnection.cpp.
{
        commandContinue(MYSQL_WAIT_WRITE);
    }
writeTimeout()
void database::mariadb::MariaDBConnection::writeTimeout () override protected virtual
Reimplemented from core::eventreceiver::WriteEventReceiver.
Definition at line 233 of file MariaDBConnection.cpp.
{
        commandContinue(MYSQL_WAIT_TIMEOUT);
    }
Member Data Documentation
commandSequenceQueue
std::deque<MariaDBCommandSequence> database::mariadb::MariaDBConnection::commandSequenceQueue private
Definition at line 101 of file MariaDBConnection.h.
commandStartEvent
MariaDBCommandStartEvent database::mariadb::MariaDBConnection::commandStartEvent private
Definition at line 106 of file MariaDBConnection.h.
Referenced by checkStatus(), execute_async(), and MariaDBConnection().
connected
bool database::mariadb::MariaDBConnection::connected = false private
Definition at line 104 of file MariaDBConnection.h.
Referenced by checkStatus().
currentCommand
MariaDBCommand* database::mariadb::MariaDBConnection::currentCommand = nullptr private
Definition at line 103 of file MariaDBConnection.h.
Referenced by checkStatus(), commandCompleted(), commandContinue(), and commandStart().
descriptorEventPublisher
DescriptorEventPublisher& core::DescriptorEventReceiver::descriptorEventPublisher private inherited
Definition at line 112 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
enabled
bool core::DescriptorEventReceiver::enabled = false private inherited
Definition at line 116 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
event
Event core::EventReceiver::event private inherited
Definition at line 54 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
eventCounter
int core::DescriptorEventReceiver::eventCounter = 0 private inherited
Definition at line 123 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::onEvent().
initialTimeout
const utils::Timeval core::DescriptorEventReceiver::initialTimeout private inherited
Definition at line 121 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), and core::DescriptorEventReceiver::setTimeout().
lastTriggered
utils::Timeval core::DescriptorEventReceiver::lastTriggered private inherited
Definition at line 119 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setEnabled(), and core::DescriptorEventReceiver::triggered().
mariaDBClient
MariaDBClient* database::mariadb::MariaDBConnection::mariaDBClient private
Definition at line 98 of file MariaDBConnection.h.
Referenced by commandStart(), MariaDBConnection(), unmanaged(), and ~MariaDBConnection().
maxInactivity
utils::Timeval core::DescriptorEventReceiver::maxInactivity private inherited
Definition at line 120 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::getTimeout(), and core::DescriptorEventReceiver::setTimeout().
mysql
MYSQL* database::mariadb::MariaDBConnection::mysql private
Definition at line 99 of file MariaDBConnection.h.
observationCounter
int core::Observer::observationCounter = 0 private inherited
Definition at line 62 of file DescriptorEventReceiver.h.
Referenced by core::Observer::getObservationCounter(), core::Observer::isObserved(), core::Observer::observed(), and core::Observer::unObserved().
observedFd
int core::DescriptorEventReceiver::observedFd = -1 private inherited
Definition at line 114 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
suspended
bool core::DescriptorEventReceiver::suspended = false private inherited
Definition at line 117 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
The documentation for this class was generated from the following files:
database/mariadb/MariaDBConnection.h
database/mariadb/MariaDBConnection.cpp