SNode.C: net::phy::PhysicalSocketOption Class Reference
net::phy::PhysicalSocketOption Class Reference
#include <PhysicalSocketOption.h>
Public Member Functions
PhysicalSocketOption ()=default
PhysicalSocketOption (int optLevel, int optName, int optValue)
PhysicalSocketOption (int optLevel, int optName, const std::string &optValue)
PhysicalSocketOption (int optLevel, int optName, const std::vector< char > &optValue)
int getOptLevel () const
int getOptName () const
const void * getOptValue () const
socklen_t getOptLen () const
Private Attributes
int optLevel = -1
int optName = -1
std::vector< char > optValue
Detailed Description
Definition at line 55 of file PhysicalSocketOption.h.
Constructor & Destructor Documentation
PhysicalSocketOption() [1/4]
net::phy::PhysicalSocketOption::PhysicalSocketOption () default
PhysicalSocketOption() [2/4]
net::phy::PhysicalSocketOption::PhysicalSocketOption (int optLevel, int optName, int optValue)
Definition at line 50 of file PhysicalSocketOption.cpp.
        : optLevel(optLevel)
        , optName(optName)
        , optValue(reinterpret_cast<char*>(&optValue), reinterpret_cast<char*>(&optValue) + sizeof(optValue)) {
    }
References optLevel, optName, and optValue.
Referenced by net::config::ConfigPhysicalSocket::addSocketOption(), and net::config::ConfigPhysicalSocket::addSocketOption().
PhysicalSocketOption() [3/4]
net::phy::PhysicalSocketOption::PhysicalSocketOption (int optLevel, int optName, const std::string & optValue)
Definition at line 56 of file PhysicalSocketOption.cpp.
        : optLevel(optLevel)
        , optName(optName)
        , optValue(optValue.begin(), optValue.end()) {
    }
References optLevel, optName, and optValue.
Referenced by net::config::ConfigPhysicalSocket::addSocketOption().
PhysicalSocketOption() [4/4]
net::phy::PhysicalSocketOption::PhysicalSocketOption (int optLevel, int optName, const std::vector< char > & optValue)
Definition at line 62 of file PhysicalSocketOption.cpp.
        : optLevel(optLevel)
        , optName(optName)
        , optValue(optValue) {
    }
References optLevel, optName, and optValue.
Referenced by net::config::ConfigPhysicalSocket::addSocketOption().
Member Function Documentation
getOptLen()
socklen_t net::phy::PhysicalSocketOption::getOptLen () const
Definition at line 80 of file PhysicalSocketOption.cpp.
{
        return static_cast<socklen_t>(optValue.size());
    }
References optValue.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open().
getOptLevel()
int net::phy::PhysicalSocketOption::getOptLevel () const
Definition at line 68 of file PhysicalSocketOption.cpp.
{
        return optLevel;
    }
References optLevel.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open().
getOptName()
int net::phy::PhysicalSocketOption::getOptName () const
Definition at line 72 of file PhysicalSocketOption.cpp.
{
        return optName;
    }
References optName.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open().
getOptValue()
const void * net::phy::PhysicalSocketOption::getOptValue () const
Definition at line 76 of file PhysicalSocketOption.cpp.
{
        return static_cast<const void*>(optValue.data());
    }
References optValue.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open().
Member Data Documentation
optLevel
int net::phy::PhysicalSocketOption::optLevel = -1 private
Definition at line 69 of file PhysicalSocketOption.h.
Referenced by getOptLevel(), PhysicalSocketOption(), PhysicalSocketOption(), and PhysicalSocketOption().
optName
int net::phy::PhysicalSocketOption::optName = -1 private
Definition at line 70 of file PhysicalSocketOption.h.
Referenced by getOptName(), PhysicalSocketOption(), PhysicalSocketOption(), and PhysicalSocketOption().
optValue
std::vector<char> net::phy::PhysicalSocketOption::optValue private
Definition at line 71 of file PhysicalSocketOption.h.
Referenced by getOptLen(), getOptValue(), PhysicalSocketOption(), PhysicalSocketOption(), and PhysicalSocketOption().
The documentation for this class was generated from the following files:
net/phy/PhysicalSocketOption.h
net/phy/PhysicalSocketOption.cpp