SNode.C: iot::mqtt_fast::packets::Connect Class Reference
iot::mqtt_fast::packets::Connect Class Reference
#include <Connect.h>
Public Member Functions
Connect (std::string clientId, std::string protocol="MQTT", uint8_t version=4, uint8_t flags=0, uint16_t keepAlive=0x003C)
Connect (iot::mqtt_fast::ControlPacketFactory &controlPacketFactory)
std::string getProtocol () const
uint8_t getLevel () const
uint8_t getFlags () const
uint16_t getKeepAlive () const
const std::string & getClientId () const
bool getUsernameFlag () const
bool getPasswordFlag () const
bool getWillRetain () const
uint8_t getWillQoS () const
bool getWillFlag () const
bool getCleanSession () const
const std::string & getWillTopic () const
const std::string & getWillMessage () const
const std::string & getUsername () const
const std::string & getPassword () const
uint8_t getType () const
uint8_t getReserved () const
uint64_t getRemainingLength () const
std::vector< char > getPacket ()
bool isError () const
Protected Member Functions
bool isError ()
std::vector< char > & getValue ()
uint8_t getInt8 ()
uint16_t getInt16 ()
uint32_t getInt32 ()
uint64_t getInt64 ()
uint32_t getIntV ()
std::string getString ()
std::string getStringRaw ()
std::list< uint8_t > getUint8ListRaw ()
void putInt8 (uint8_t value)
void putInt16 (uint16_t value)
void putInt32 (uint32_t value)
void putInt64 (uint64_t value)
void putIntV (uint32_t value)
void putString (const std::string &value)
void putStringRaw (const std::string &value)
void putUint8ListRaw (const std::list< uint8_t > &value)
Protected Attributes
bool error = false
Private Attributes
std::string protocol
uint8_t level = 0
uint8_t flags = 0
uint16_t keepAlive = 0
std::string clientId
std::string willTopic
std::string willMessage
std::string username
std::string password
bool usernameFlag = false
bool passwordFlag = false
bool willRetain = false
uint8_t willQoS = 0
bool willFlag = false
bool cleanSession = false
bool reserved = false
uint8_t type
iot::mqtt_fast::types::Binary data
Detailed Description
Definition at line 41 of file Connect.h.
Constructor & Destructor Documentation
Connect() [1/2]
iot::mqtt_fast::packets::Connect::Connect (std::string clientId, std::string protocol = "MQTT", uint8_t version = 4, uint8_t flags = 0, uint16_t keepAlive = 0x003C) explicit
Definition at line 27 of file Connect.cpp.
        : iot::mqtt_fast::ControlPacket(MQTT_CONNECT)
        , protocol(protocol)
        , level(version)
        , flags(flags)
        , keepAlive(keepAlive)
        , clientId(clientId) {
        // V-Header
        putString(this->protocol);
        putInt8(this->level);
        putInt8(this->flags);
        putInt16(this->keepAlive);
        // Payload
        putString(this->clientId);
    }
References clientId, iot::mqtt_fast::ControlPacket::ControlPacket(), flags, keepAlive, level, protocol, iot::mqtt_fast::ControlPacket::putInt16(), iot::mqtt_fast::ControlPacket::putInt8(), and iot::mqtt_fast::ControlPacket::putString().
Referenced by iot::mqtt_fast::SocketContext::sendConnect().
Connect() [2/2]
iot::mqtt_fast::packets::Connect::Connect (iot::mqtt_fast::ControlPacketFactory & controlPacketFactory) explicit
Definition at line 44 of file Connect.cpp.
        : iot::mqtt_fast::ControlPacket(controlPacketFactory) {
        // V-Header
        protocol = getString();
        level = getInt8();
        flags = getInt8();
        keepAlive = getInt16();
        usernameFlag = (flags & 0x80) != 0;
        passwordFlag = (flags & 0x40) != 0;
        willRetain = (flags & 0x20) != 0;
        willQoS = (flags & 0x18) >> 3;
        willFlag = (flags & 0x04) != 0;
        cleanSession = (flags & 0x02) != 0;
        reserved = (flags & 0x01) != 0;
        // Payload
        if (!isError()) {
            clientId = getString();
        } else {
            error = true;
        }
        if (!error && willFlag) {
            willTopic = getString();
            willMessage = getString();
        }
        if (!error && usernameFlag) {
            username = getString();
        }
        if (!error && passwordFlag) {
            password = getString();
        }
    }
References cleanSession, clientId, iot::mqtt_fast::ControlPacket::ControlPacket(), iot::mqtt_fast::ControlPacket::error, flags, iot::mqtt_fast::ControlPacket::getInt16(), iot::mqtt_fast::ControlPacket::getInt8(), iot::mqtt_fast::ControlPacket::getString(), iot::mqtt_fast::ControlPacket::isError(), keepAlive, level, password, passwordFlag, protocol, reserved, username, usernameFlag, willFlag, willMessage, willQoS, willRetain, and willTopic.
Referenced by iot::mqtt_fast::SocketContext::onReceivedFromPeer().
Member Function Documentation
getCleanSession()
bool iot::mqtt_fast::packets::Connect::getCleanSession () const
Definition at line 121 of file Connect.cpp.
{
        return cleanSession;
    }
References cleanSession.
getClientId()
const std::string & iot::mqtt_fast::packets::Connect::getClientId () const
Definition at line 97 of file Connect.cpp.
{
        return clientId;
    }
References clientId.
getFlags()
uint8_t iot::mqtt_fast::packets::Connect::getFlags () const
Definition at line 89 of file Connect.cpp.
{
        return flags;
    }
References flags.
getInt16()
uint16_t iot::mqtt_fast::ControlPacket::getInt16 () protected inherited
Definition at line 86 of file ControlPacket.cpp.
{
        return data.getInt16();
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::getInt16().
Referenced by Connect(), iot::mqtt_fast::packets::Puback::Puback(), iot::mqtt_fast::packets::Pubcomp::Pubcomp(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Pubrec::Pubrec(), iot::mqtt_fast::packets::Pubrel::Pubrel(), iot::mqtt_fast::packets::Suback::Suback(), iot::mqtt_fast::packets::Subscribe::Subscribe(), iot::mqtt_fast::packets::Unsuback::Unsuback(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
getInt32()
uint32_t iot::mqtt_fast::ControlPacket::getInt32 () protected inherited
Definition at line 90 of file ControlPacket.cpp.
{
        return data.getInt32();
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::getInt32().
getInt64()
uint64_t iot::mqtt_fast::ControlPacket::getInt64 () protected inherited
Definition at line 94 of file ControlPacket.cpp.
{
        return data.getInt64();
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::getInt64().
getInt8()
uint8_t iot::mqtt_fast::ControlPacket::getInt8 () protected inherited
Definition at line 82 of file ControlPacket.cpp.
{
        return data.getInt8();
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::getInt8().
Referenced by iot::mqtt_fast::packets::Connack::Connack(), Connect(), and iot::mqtt_fast::packets::Subscribe::Subscribe().
getIntV()
uint32_t iot::mqtt_fast::ControlPacket::getIntV () protected inherited
Definition at line 98 of file ControlPacket.cpp.
{
        return data.getIntV();
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::getIntV().
getKeepAlive()
uint16_t iot::mqtt_fast::packets::Connect::getKeepAlive () const
Definition at line 93 of file Connect.cpp.
{
        return keepAlive;
    }
References keepAlive.
getLevel()
uint8_t iot::mqtt_fast::packets::Connect::getLevel () const
Definition at line 85 of file Connect.cpp.
{
        return level;
    }
References level.
getPacket()
std::vector< char > iot::mqtt_fast::ControlPacket::getPacket () inherited
Definition at line 54 of file ControlPacket.cpp.
{
        std::vector<char> packet;
        packet.push_back(static_cast<char>((type << 0x04) | (reserved & 0x0F)));
        uint64_t remainingLength = data.getLength();
        do {
            uint8_t encodedByte = static_cast<uint8_t>(remainingLength % 0x80);
            remainingLength /= 0x80;
            if (remainingLength > 0) {
                encodedByte |= 0x80;
            }
            packet.push_back(static_cast<char>(encodedByte));
        } while (remainingLength > 0);
        packet.insert(packet.end(), data.getValue().begin(), data.getValue().end());
        return packet;
    }
References iot::mqtt_fast::ControlPacket::data, iot::mqtt_fast::types::Binary::getLength(), iot::mqtt_fast::types::Binary::getValue(), iot::mqtt_fast::ControlPacket::reserved, and iot::mqtt_fast::ControlPacket::type.
Referenced by iot::mqtt_fast::SocketContext::send(), and iot::mqtt_fast::SocketContext::send().
getPassword()
const std::string & iot::mqtt_fast::packets::Connect::getPassword () const
Definition at line 137 of file Connect.cpp.
{
        return password;
    }
References password.
getPasswordFlag()
bool iot::mqtt_fast::packets::Connect::getPasswordFlag () const
Definition at line 105 of file Connect.cpp.
{
        return passwordFlag;
    }
References passwordFlag.
getProtocol()
std::string iot::mqtt_fast::packets::Connect::getProtocol () const
Definition at line 81 of file Connect.cpp.
{
        return protocol;
    }
References protocol.
getRemainingLength()
uint64_t iot::mqtt_fast::ControlPacket::getRemainingLength () const inherited
Definition at line 50 of file ControlPacket.cpp.
{
        return data.getLength();
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::getLength().
getReserved()
uint8_t iot::mqtt_fast::ControlPacket::getReserved () const inherited
Definition at line 46 of file ControlPacket.cpp.
{
        return reserved;
    }
References iot::mqtt_fast::ControlPacket::reserved.
getString()
std::string iot::mqtt_fast::ControlPacket::getString () protected inherited
Definition at line 102 of file ControlPacket.cpp.
{
        return data.getString();
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::getString().
Referenced by Connect(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Subscribe::Subscribe(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
getStringRaw()
std::string iot::mqtt_fast::ControlPacket::getStringRaw () protected inherited
Definition at line 106 of file ControlPacket.cpp.
{
        return data.getStringRaw();
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::getStringRaw().
Referenced by iot::mqtt_fast::packets::Publish::Publish().
getType()
uint8_t iot::mqtt_fast::ControlPacket::getType () const inherited
Definition at line 42 of file ControlPacket.cpp.
{
        return type;
    }
References iot::mqtt_fast::ControlPacket::type.
getUint8ListRaw()
std::list< uint8_t > iot::mqtt_fast::ControlPacket::getUint8ListRaw () protected inherited
Definition at line 110 of file ControlPacket.cpp.
{
        return data.getUint8ListRaw();
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::getUint8ListRaw().
Referenced by iot::mqtt_fast::packets::Suback::Suback().
getUsername()
const std::string & iot::mqtt_fast::packets::Connect::getUsername () const
Definition at line 133 of file Connect.cpp.
{
        return username;
    }
References username.
getUsernameFlag()
bool iot::mqtt_fast::packets::Connect::getUsernameFlag () const
Definition at line 101 of file Connect.cpp.
{
        return usernameFlag;
    }
References usernameFlag.
getValue()
std::vector< char > & iot::mqtt_fast::ControlPacket::getValue () protected inherited
Definition at line 78 of file ControlPacket.cpp.
{
        return data.getValue();
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::getValue().
getWillFlag()
bool iot::mqtt_fast::packets::Connect::getWillFlag () const
Definition at line 117 of file Connect.cpp.
{
        return willFlag;
    }
References willFlag.
getWillMessage()
const std::string & iot::mqtt_fast::packets::Connect::getWillMessage () const
Definition at line 129 of file Connect.cpp.
{
        return willMessage;
    }
References willMessage.
getWillQoS()
uint8_t iot::mqtt_fast::packets::Connect::getWillQoS () const
Definition at line 113 of file Connect.cpp.
{
        return willQoS;
    }
References willQoS.
getWillRetain()
bool iot::mqtt_fast::packets::Connect::getWillRetain () const
Definition at line 109 of file Connect.cpp.
{
        return willRetain;
    }
References willRetain.
getWillTopic()
const std::string & iot::mqtt_fast::packets::Connect::getWillTopic () const
Definition at line 125 of file Connect.cpp.
{
        return willTopic;
    }
References willTopic.
isError() [1/2]
bool iot::mqtt_fast::ControlPacket::isError () protected inherited
Definition at line 146 of file ControlPacket.cpp.
{
        return data.isError();
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::TypeBase::isError().
Referenced by iot::mqtt_fast::packets::Connack::Connack(), Connect(), iot::mqtt_fast::packets::Disconnect::Disconnect(), iot::mqtt_fast::packets::Pingreq::Pingreq(), iot::mqtt_fast::packets::Pingresp::Pingresp(), iot::mqtt_fast::packets::Puback::Puback(), iot::mqtt_fast::packets::Pubcomp::Pubcomp(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Pubrec::Pubrec(), iot::mqtt_fast::packets::Pubrel::Pubrel(), iot::mqtt_fast::packets::Suback::Suback(), iot::mqtt_fast::packets::Subscribe::Subscribe(), iot::mqtt_fast::packets::Unsuback::Unsuback(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
isError() [2/2]
bool iot::mqtt_fast::ControlPacket::isError () const inherited
Definition at line 74 of file ControlPacket.cpp.
{
        return error;
    }
References iot::mqtt_fast::ControlPacket::error.
putInt16()
void iot::mqtt_fast::ControlPacket::putInt16 (uint16_t value) protected inherited
Definition at line 118 of file ControlPacket.cpp.
{
        data.putInt16(value);
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::putInt16().
Referenced by Connect(), iot::mqtt_fast::packets::Puback::Puback(), iot::mqtt_fast::packets::Pubcomp::Pubcomp(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Pubrec::Pubrec(), iot::mqtt_fast::packets::Pubrel::Pubrel(), iot::mqtt_fast::packets::Suback::Suback(), iot::mqtt_fast::packets::Subscribe::Subscribe(), iot::mqtt_fast::packets::Unsuback::Unsuback(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
putInt32()
void iot::mqtt_fast::ControlPacket::putInt32 (uint32_t value) protected inherited
Definition at line 122 of file ControlPacket.cpp.
{
        data.putInt32(value);
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::putInt32().
putInt64()
void iot::mqtt_fast::ControlPacket::putInt64 (uint64_t value) protected inherited
Definition at line 126 of file ControlPacket.cpp.
{
        data.putInt64(value);
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::putInt64().
putInt8()
void iot::mqtt_fast::ControlPacket::putInt8 (uint8_t value) protected inherited
Definition at line 114 of file ControlPacket.cpp.
{
        data.putInt8(value);
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::putInt8().
Referenced by iot::mqtt_fast::packets::Connack::Connack(), Connect(), and iot::mqtt_fast::packets::Subscribe::Subscribe().
putIntV()
void iot::mqtt_fast::ControlPacket::putIntV (uint32_t value) protected inherited
Definition at line 130 of file ControlPacket.cpp.
{
        data.putIntV(value);
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::putIntV().
putString()
void iot::mqtt_fast::ControlPacket::putString (const std::string & value) protected inherited
Definition at line 134 of file ControlPacket.cpp.
{
        data.putString(value);
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::putString().
Referenced by Connect(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Subscribe::Subscribe(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
putStringRaw()
void iot::mqtt_fast::ControlPacket::putStringRaw (const std::string & value) protected inherited
Definition at line 138 of file ControlPacket.cpp.
{
        data.putStringRaw(value);
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::putStringRaw().
Referenced by iot::mqtt_fast::packets::Publish::Publish().
putUint8ListRaw()
void iot::mqtt_fast::ControlPacket::putUint8ListRaw (const std::list< uint8_t > & value) protected inherited
Definition at line 142 of file ControlPacket.cpp.
{
        data.putUint8ListRaw(value);
    }
References iot::mqtt_fast::ControlPacket::data, and iot::mqtt_fast::types::Binary::putUint8ListRaw().
Referenced by iot::mqtt_fast::packets::Suback::Suback().
Member Data Documentation
cleanSession
bool iot::mqtt_fast::packets::Connect::cleanSession = false private
Definition at line 83 of file Connect.h.
Referenced by Connect(), and getCleanSession().
clientId
std::string iot::mqtt_fast::packets::Connect::clientId private
Definition at line 72 of file Connect.h.
Referenced by Connect(), Connect(), and getClientId().
data
iot::mqtt_fast::types::Binary iot::mqtt_fast::ControlPacket::data private inherited
Definition at line 84 of file ControlPacket.h.
Referenced by iot::mqtt_fast::ControlPacket::ControlPacket(), iot::mqtt_fast::ControlPacket::getInt16(), iot::mqtt_fast::ControlPacket::getInt32(), iot::mqtt_fast::ControlPacket::getInt64(), iot::mqtt_fast::ControlPacket::getInt8(), iot::mqtt_fast::ControlPacket::getIntV(), iot::mqtt_fast::ControlPacket::getPacket(), iot::mqtt_fast::ControlPacket::getRemainingLength(), iot::mqtt_fast::ControlPacket::getString(), iot::mqtt_fast::ControlPacket::getStringRaw(), iot::mqtt_fast::ControlPacket::getUint8ListRaw(), iot::mqtt_fast::ControlPacket::getValue(), iot::mqtt_fast::ControlPacket::isError(), iot::mqtt_fast::ControlPacket::putInt16(), iot::mqtt_fast::ControlPacket::putInt32(), iot::mqtt_fast::ControlPacket::putInt64(), iot::mqtt_fast::ControlPacket::putInt8(), iot::mqtt_fast::ControlPacket::putIntV(), iot::mqtt_fast::ControlPacket::putString(), iot::mqtt_fast::ControlPacket::putStringRaw(), and iot::mqtt_fast::ControlPacket::putUint8ListRaw().
error
bool iot::mqtt_fast::ControlPacket::error = false protected inherited
Definition at line 87 of file ControlPacket.h.
Referenced by iot::mqtt_fast::packets::Connack::Connack(), Connect(), iot::mqtt_fast::packets::Disconnect::Disconnect(), iot::mqtt_fast::ControlPacket::isError(), iot::mqtt_fast::packets::Pingreq::Pingreq(), iot::mqtt_fast::packets::Pingresp::Pingresp(), iot::mqtt_fast::packets::Puback::Puback(), iot::mqtt_fast::packets::Pubcomp::Pubcomp(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Pubrec::Pubrec(), iot::mqtt_fast::packets::Pubrel::Pubrel(), iot::mqtt_fast::packets::Suback::Suback(), iot::mqtt_fast::packets::Subscribe::Subscribe(), iot::mqtt_fast::packets::Unsuback::Unsuback(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
flags
uint8_t iot::mqtt_fast::packets::Connect::flags = 0 private
Definition at line 69 of file Connect.h.
Referenced by Connect(), Connect(), and getFlags().
keepAlive
uint16_t iot::mqtt_fast::packets::Connect::keepAlive = 0 private
Definition at line 70 of file Connect.h.
Referenced by Connect(), Connect(), and getKeepAlive().
level
uint8_t iot::mqtt_fast::packets::Connect::level = 0 private
Definition at line 68 of file Connect.h.
Referenced by Connect(), Connect(), and getLevel().
password
std::string iot::mqtt_fast::packets::Connect::password private
Definition at line 76 of file Connect.h.
Referenced by Connect(), and getPassword().
passwordFlag
bool iot::mqtt_fast::packets::Connect::passwordFlag = false private
Definition at line 79 of file Connect.h.
Referenced by Connect(), and getPasswordFlag().
protocol
std::string iot::mqtt_fast::packets::Connect::protocol private
Definition at line 67 of file Connect.h.
Referenced by Connect(), Connect(), and getProtocol().
reserved
bool iot::mqtt_fast::packets::Connect::reserved = false private
Definition at line 84 of file Connect.h.
Referenced by Connect().
type
uint8_t iot::mqtt_fast::ControlPacket::type private inherited
Definition at line 81 of file ControlPacket.h.
Referenced by iot::mqtt_fast::ControlPacket::ControlPacket(), iot::mqtt_fast::ControlPacket::ControlPacket(), iot::mqtt_fast::ControlPacket::getPacket(), and iot::mqtt_fast::ControlPacket::getType().
username
std::string iot::mqtt_fast::packets::Connect::username private
Definition at line 75 of file Connect.h.
Referenced by Connect(), and getUsername().
usernameFlag
bool iot::mqtt_fast::packets::Connect::usernameFlag = false private
Definition at line 78 of file Connect.h.
Referenced by Connect(), and getUsernameFlag().
willFlag
bool iot::mqtt_fast::packets::Connect::willFlag = false private
Definition at line 82 of file Connect.h.
Referenced by Connect(), and getWillFlag().
willMessage
std::string iot::mqtt_fast::packets::Connect::willMessage private
Definition at line 74 of file Connect.h.
Referenced by Connect(), and getWillMessage().
willQoS
uint8_t iot::mqtt_fast::packets::Connect::willQoS = 0 private
Definition at line 81 of file Connect.h.
Referenced by Connect(), and getWillQoS().
willRetain
bool iot::mqtt_fast::packets::Connect::willRetain = false private
Definition at line 80 of file Connect.h.
Referenced by Connect(), and getWillRetain().
willTopic
std::string iot::mqtt_fast::packets::Connect::willTopic private
Definition at line 73 of file Connect.h.
Referenced by Connect(), and getWillTopic().
The documentation for this class was generated from the following files:
iot/mqtt-fast/packets/Connect.h
iot/mqtt-fast/packets/Connect.cpp