SNode.C: iot::mqtt::server::broker::Message Class Reference
iot::mqtt::server::broker::Message Class Reference
#include <Message.h>
Public Member Functions
Message ()=default
Message (const std::string &originClientId, const std::string &topic, const std::string &message, uint8_t qoS, bool originRetain)
Message (const Message &message)=default
Message & operator= (const Message &)=default
const std::string & getOriginClientId () const
const std::string & getTopic () const
void setTopic (const std::string &topic)
const std::string & getMessage () const
void setMessage (const std::string &message)
uint8_t getQoS () const
void setQoS (uint8_t qoS)
bool getOriginRetain () const
nlohmann::json toJson () const
Message & fromJson (const nlohmann::json &json)
Private Attributes
std::string originClientId
std::string topic
std::string message
uint8_t qoS = 0
bool originRetain = false
Detailed Description
Definition at line 55 of file Message.h.
Constructor & Destructor Documentation
Message() [1/3]
iot::mqtt::server::broker::Message::Message () default
Referenced by iot::mqtt::server::broker::Session::fromJson(), and iot::mqtt::server::broker::RetainTree::TopicLevel::release().
Message() [2/3]
iot::mqtt::server::broker::Message::Message (const std::string & originClientId, const std::string & topic, const std::string & message, uint8_t qoS, bool originRetain)
Definition at line 53 of file Message.cpp.
        : originClientId(originClientId)
        , topic(topic)
        , message(message)
        , qoS(qoS)
        , originRetain(originRetain) {
    }
References message, originClientId, originRetain, qoS, and topic.
Referenced by iot::mqtt::server::broker::Broker::publish().
Message() [3/3]
iot::mqtt::server::broker::Message::Message (const Message & message) default
Member Function Documentation
fromJson()
Message & iot::mqtt::server::broker::Message::fromJson (const nlohmann::json & json)
Definition at line 105 of file Message.cpp.
{
        if (!json.empty()) {
            originClientId = json["origin_client_id"];
            topic = json["topic"];
            message = json["message"];
            qoS = json["qos"];
        }
        return *this;
    }
References message, originClientId, qoS, and topic.
Referenced by iot::mqtt::server::broker::RetainTree::TopicLevel::fromJson(), and iot::mqtt::server::broker::Session::fromJson().
getMessage()
const std::string & iot::mqtt::server::broker::Message::getMessage () const
Definition at line 74 of file Message.cpp.
{
        return message;
    }
References message.
Referenced by iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), iot::mqtt::server::broker::RetainTree::TopicLevel::getRetainTree(), iot::mqtt::server::broker::SubscribtionTree::TopicLevel::publish(), iot::mqtt::server::broker::RetainTree::TopicLevel::release(), iot::mqtt::server::broker::RetainTree::TopicLevel::retain(), iot::mqtt::server::broker::RetainTree::retain(), iot::mqtt::server::broker::Session::sendPublish(), and iot::mqtt::server::broker::RetainTree::TopicLevel::toJson().
getOriginClientId()
const std::string & iot::mqtt::server::broker::Message::getOriginClientId () const
Definition at line 62 of file Message.cpp.
{
        return originClientId;
    }
References originClientId.
Referenced by iot::mqtt::server::broker::Session::sendPublish().
getOriginRetain()
bool iot::mqtt::server::broker::Message::getOriginRetain () const
Definition at line 90 of file Message.cpp.
{
        return originRetain;
    }
References originRetain.
Referenced by iot::mqtt::server::broker::Session::sendPublish().
getQoS()
uint8_t iot::mqtt::server::broker::Message::getQoS () const
Definition at line 82 of file Message.cpp.
{
        return qoS;
    }
References qoS.
Referenced by iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), iot::mqtt::server::broker::Session::publishQueued(), iot::mqtt::server::broker::RetainTree::TopicLevel::retain(), and iot::mqtt::server::broker::Session::sendPublish().
getTopic()
const std::string & iot::mqtt::server::broker::Message::getTopic () const
Definition at line 66 of file Message.cpp.
{
        return topic;
    }
References topic.
Referenced by iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), iot::mqtt::server::broker::SubscribtionTree::publish(), iot::mqtt::server::broker::SubscribtionTree::TopicLevel::publish(), iot::mqtt::server::broker::RetainTree::TopicLevel::release(), iot::mqtt::server::broker::RetainTree::TopicLevel::retain(), iot::mqtt::server::broker::RetainTree::retain(), and iot::mqtt::server::broker::Session::sendPublish().
operator=()
Message & iot::mqtt::server::broker::Message::operator= (const Message &) default
Referenced by iot::mqtt::server::broker::RetainTree::TopicLevel::release(), and iot::mqtt::server::broker::RetainTree::TopicLevel::retain().
setMessage()
void iot::mqtt::server::broker::Message::setMessage (const std::string & message)
Definition at line 78 of file Message.cpp.
{
        this->message = message;
    }
References message.
setQoS()
void iot::mqtt::server::broker::Message::setQoS (uint8_t qoS)
Definition at line 86 of file Message.cpp.
{
        this->qoS = qoS;
    }
References qoS.
Referenced by iot::mqtt::server::broker::Session::sendPublish().
setTopic()
void iot::mqtt::server::broker::Message::setTopic (const std::string & topic)
Definition at line 70 of file Message.cpp.
{
        this->topic = topic;
    }
References topic.
toJson()
nlohmann::json iot::mqtt::server::broker::Message::toJson () const
Definition at line 94 of file Message.cpp.
{
        nlohmann::json json;
        json["origin_client_id"] = originClientId;
        json["topic"] = topic;
        json["message"] = message;
        json["qos"] = qoS;
        return json;
    }
References message, originClientId, qoS, and topic.
Referenced by iot::mqtt::server::broker::RetainTree::TopicLevel::toJson(), and iot::mqtt::server::broker::Session::toJson().
Member Data Documentation
message
std::string iot::mqtt::server::broker::Message::message private
Definition at line 82 of file Message.h.
Referenced by fromJson(), getMessage(), Message(), setMessage(), and toJson().
originClientId
std::string iot::mqtt::server::broker::Message::originClientId private
Definition at line 80 of file Message.h.
Referenced by fromJson(), getOriginClientId(), Message(), and toJson().
originRetain
bool iot::mqtt::server::broker::Message::originRetain = false private
Definition at line 84 of file Message.h.
Referenced by getOriginRetain(), and Message().
qoS
uint8_t iot::mqtt::server::broker::Message::qoS = 0 private
Definition at line 83 of file Message.h.
Referenced by fromJson(), getQoS(), Message(), setQoS(), and toJson().
topic
std::string iot::mqtt::server::broker::Message::topic private
Definition at line 81 of file Message.h.
Referenced by fromJson(), getTopic(), Message(), setTopic(), and toJson().
The documentation for this class was generated from the following files:
iot/mqtt/server/broker/Message.h
iot/mqtt/server/broker/Message.cpp