SNode.C: express::dispatcher::MiddlewareDispatcher Class Reference
express::dispatcher::MiddlewareDispatcher Class Reference
#include <MiddlewareDispatcher.h>
Public Member Functions
MiddlewareDispatcher (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, express::Next &)> &lambda)
Public Member Functions inherited from express::Dispatcher
Dispatcher (const Dispatcher &)=delete
Dispatcher & operator= (const Dispatcher &)=delete
Dispatcher ()=default
virtual ~Dispatcher ()
bool dispatchNext (Controller &controller, const std::string &parentMountPath)
Private Member Functions
bool dispatch (express::Controller &controller, const std::string &parentMountPath, const express::MountPoint &mountPoint) override
std::list< std::string > getRoutes (const std::string &parentMountPath, const MountPoint &mountPoint, bool strictRouting) const override
Private Attributes
const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, express::Next &)> lambda
std::regex regex
std::vector< std::string > names
Additional Inherited Members
Protected Attributes inherited from express::Dispatcher
std::shared_ptr< Route > nextRoute = nullptr
Detailed Description
Definition at line 65 of file MiddlewareDispatcher.h.
Constructor & Destructor Documentation
MiddlewareDispatcher()
express::dispatcher::MiddlewareDispatcher::MiddlewareDispatcher (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, express::Next &)> & lambda) explicit
Definition at line 68 of file MiddlewareDispatcher.cpp.
        : lambda(lambda) {
    }
References lambda.
Member Function Documentation
dispatch()
bool express::dispatcher::MiddlewareDispatcher::dispatch (express::Controller & controller, const std::string & parentMountPath, const express::MountPoint & mountPoint) override private virtual
Implements express::Dispatcher.
Definition at line 73 of file MiddlewareDispatcher.cpp.
{
        bool requestMatched = false;
        const std::string absoluteMountPath = parentMountPath + mountPoint.relativeMountPath;
        if ((controller.getFlags() & Controller::NEXT) == 0) {
            // Split mount & request into path + query
            std::string_view mountPath;
            std::string_view mountQueryString;
            splitPathAndQuery(absoluteMountPath, mountPath, mountQueryString);
            auto requiredQueryPairs = parseQuery(mountQueryString);
            std::string_view requestPath;
            std::string_view requestQueryString;
            splitPathAndQuery(controller.getRequest()->originalUrl, requestPath, requestQueryString);
            auto requestQueryPairs = parseQuery(requestQueryString);
            // Normalize single trailing slash if not strict
            if (!controller.getStrictRouting()) {
                mountPath = trimOneTrailingSlash(mountPath);
                requestPath = trimOneTrailingSlash(requestPath);
            }
            if (mountPath.empty()) {
                mountPath = "/";
            }
            // Middleware is **prefix** with boundary (Express: app.use)
            bool pathMatches = false;
            std::size_t consumedLength = 0;
            if (absoluteMountPath.find(':') != std::string::npos) {
                // Param mount: compile once, match once, fill params, and record matched prefix length
                if (regex.mark_count() == 0) {
                    if (regex.mark_count() == 0) {
                        LOG(TRACE) << "MiddlewarDispatchere: precompiled regex";
                        std::tie(regex, names) = compileParamRegex(mountPath,
                                                                   /*isPrefix*/ true,
                                                                   controller.getStrictRouting(),
                                                                   controller.getCaseInsensitiveRouting());
                    } else {
                        LOG(TRACE) << "MiddlewareDispatcher: using precompiled regex";
                    }
                }
                std::cmatch regexMatches;
                pathMatches = std::regex_search(requestPath.begin(), requestPath.end(), regexMatches, regex);
                if (pathMatches) {
                    // regexMatches[0] = full matched prefix starting at 0 (anchored by compile_param_regex)
                    consumedLength = static_cast<std::size_t>(regexMatches.length(0));
                    // fill named params
                    const std::size_t groups = !regexMatches.empty() ? (regexMatches.size() - 1) : 0;
                    const std::size_t n = std::min(names.size(), groups);
                    for (std::size_t i = 0; i < n; ++i) {
                        controller.getRequest()->params[names[i]] = regexMatches[i + 1].str();
                    }
                }
            } else {
                // Literal boundary prefix
                pathMatches = boundaryPrefix(requestPath, mountPath, controller.getCaseInsensitiveRouting());
                if (pathMatches) {
                    consumedLength = mountPath.size(); // IMPORTANT: literal consumes exactly its base length
                }
            }
            const bool queryMatches = querySupersetMatches(requestQueryPairs, requiredQueryPairs);
            requestMatched = (pathMatches && queryMatches);
            LOG(TRACE) << controller.getResponse()->getSocketContext()->getSocketConnection()->getConnectionName()
                       << " HTTP Express: middleware -> " << (requestMatched ? "MATCH" : "NO MATCH");
            LOG(TRACE) << "           RequestMethod: " << controller.getRequest()->method;
            LOG(TRACE) << "              RequestUrl: " << controller.getRequest()->url;
            LOG(TRACE) << "             RequestPath: " << controller.getRequest()->path;
            LOG(TRACE) << "       AbsoluteMountPath: " << absoluteMountPath;
            LOG(TRACE) << "           StrictRouting: " << controller.getStrictRouting();
            LOG(TRACE) << "  CaseInsensitiveRouting: " << controller.getCaseInsensitiveRouting();
            if (requestMatched) {
                // Compute remainder and temporarily **rewrite req.path**
                std::string_view remainderPath{};
                if (requestPath.size() > consumedLength) {
                    remainderPath = requestPath.substr(consumedLength);
                    if (!remainderPath.empty() && remainderPath.front() == '/') {
                        remainderPath.remove_prefix(1);
                    }
                }
                auto& req = *controller.getRequest();
                const std::string previousPathBackup = req.path;
                req.path = remainderPath.empty() ? "/" : ("/" + std::string(remainderPath));
                req.queries.insert(requestQueryPairs.begin(), requestQueryPairs.end());
                if (hasResult(absoluteMountPath)) {
                    setParams(absoluteMountPath, *controller.getRequest());
                }
                Next next(controller);
                lambda(controller.getRequest(), controller.getResponse(), next);
                // If next() was called synchronously continue current route-tree traversal
                if ((next.controller.getFlags() & express::Controller::NEXT) != 0) {
                    LOG(TRACE) << "Express: M - Next called - set to NO MATCH";
                    requestMatched = false;
                    controller = next.controller;
                }
                // Restore
                req.path = previousPathBackup;
            }
        } else {
            LOG(TRACE) << controller.getResponse()->getSocketContext()->getSocketConnection()->getConnectionName()
                       << " HTTP Express: middleware -> next(...) called";
            LOG(TRACE) << "           RequestMethod: " << controller.getRequest()->method;
            LOG(TRACE) << "              RequestUrl: " << controller.getRequest()->url;
            LOG(TRACE) << "             RequestPath: " << controller.getRequest()->path;
            LOG(TRACE) << "       AbsoluteMountPath: " << absoluteMountPath;
        }
        return requestMatched;
    }
References express::dispatcher::boundaryPrefix(), express::dispatcher::compileParamRegex(), express::Next::controller, express::Controller::getCaseInsensitiveRouting(), core::socket::stream::SocketConnection::getConnectionName(), express::Controller::getFlags(), express::Controller::getRequest(), express::Controller::getResponse(), core::socket::stream::SocketContext::getSocketConnection(), express::Response::getSocketContext(), express::Controller::getStrictRouting(), express::dispatcher::hasResult(), lambda, express::Request::method, names, express::Controller::NEXT, express::Next::Next(), express::Controller::operator=(), express::Request::originalUrl, express::dispatcher::parseQuery(), express::Request::path, express::Request::queries, express::dispatcher::querySupersetMatches(), express::MountPoint::relativeMountPath, express::dispatcher::setParams(), express::dispatcher::splitPathAndQuery(), express::dispatcher::trimOneTrailingSlash(), and express::Request::url.
getRoutes()
std::list< std::string > express::dispatcher::MiddlewareDispatcher::getRoutes (const std::string & parentMountPath, const MountPoint & mountPoint, bool strictRouting) const override private virtual
Implements express::Dispatcher.
Definition at line 192 of file MiddlewareDispatcher.cpp.
{
        std::list<std::string> routes{"M " + parentMountPath + mountPoint.relativeMountPath + (!strictRouting ? "*" : "")};
        routes.push_back("  " + mountPoint.method + " " + mountPoint.relativeMountPath);
        if (nextRoute) {
            routes.splice(routes.end(), nextRoute->getRoute(parentMountPath, strictRouting));
        }
        return routes;
    }
References express::Route::getRoute(), express::MountPoint::method, express::Dispatcher::nextRoute, and express::MountPoint::relativeMountPath.
Member Data Documentation
lambda
const std::function<void(const std::shared_ptr<Request>&, const std::shared_ptr<Response>&, express::Next&)> express::dispatcher::MiddlewareDispatcher::lambda private
Definition at line 75 of file MiddlewareDispatcher.h.
Referenced by dispatch(), and MiddlewareDispatcher().
names
std::vector<std::string> express::dispatcher::MiddlewareDispatcher::names private
Definition at line 78 of file MiddlewareDispatcher.h.
Referenced by dispatch().
regex
std::regex express::dispatcher::MiddlewareDispatcher::regex private
Definition at line 77 of file MiddlewareDispatcher.h.
The documentation for this class was generated from the following files:
express/dispatcher/MiddlewareDispatcher.h
express/dispatcher/MiddlewareDispatcher.cpp