SNode.C: core::eventreceiver::AcceptEventReceiver Class Reference
core::eventreceiver::AcceptEventReceiver Class Reference abstract
#include <AcceptEventReceiver.h>
Protected Member Functions
AcceptEventReceiver (const std::string &name, const utils::Timeval &timeout)
virtual void acceptTimeout ()
Protected Member Functions inherited from core::DescriptorEventReceiver
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
Protected Member Functions inherited from core::Observer
void observed ()
void unObserved ()
virtual void unobservedEvent ()=0
Observer ()=default
Observer (Observer &)=delete
Observer (Observer &&)=delete
virtual ~Observer ()
Protected Member Functions inherited from core::EventReceiver
virtual ~EventReceiver ()=default
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Private Member Functions
virtual void acceptEvent ()=0
void dispatchEvent () final
void timeoutEvent () final
void signalEvent (int signum) override
Additional Inherited Members
Public Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
int getRegisteredFd () const
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Static Public Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Static Protected Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Detailed Description
Definition at line 35 of file AcceptEventReceiver.h.
Constructor & Destructor Documentation
AcceptEventReceiver()
core::eventreceiver::AcceptEventReceiver::AcceptEventReceiver (const std::string & name, const utils::Timeval & timeout) protected
Definition at line 31 of file AcceptEventReceiver.cpp.
        : core::DescriptorEventReceiver(
              name + " Accept",
              core::EventLoop::instance().getEventMultiplexer().getDescriptorEventPublisher(core::EventMultiplexer::DISP_TYPE::RD),
              timeout) {
    }
References core::EventMultiplexer::getDescriptorEventPublisher(), core::EventLoop::getEventMultiplexer(), core::EventLoop::instance(), and core::EventMultiplexer::RD.
Member Function Documentation
acceptEvent()
virtual void core::eventreceiver::AcceptEventReceiver::acceptEvent () private pure virtual
Implemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >.
Referenced by dispatchEvent().
acceptTimeout()
void core::eventreceiver::AcceptEventReceiver::acceptTimeout () protected virtual
Definition at line 38 of file AcceptEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
Referenced by timeoutEvent().
dispatchEvent()
void core::eventreceiver::AcceptEventReceiver::dispatchEvent () final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 42 of file AcceptEventReceiver.cpp.
{
        acceptEvent();
    }
References acceptEvent().
signalEvent()
void core::eventreceiver::AcceptEventReceiver::signalEvent (int signum) override private virtual
Implements core::DescriptorEventReceiver.
Definition at line 50 of file AcceptEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
timeoutEvent()
void core::eventreceiver::AcceptEventReceiver::timeoutEvent () final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 46 of file AcceptEventReceiver.cpp.
{
        acceptTimeout();
    }
References acceptTimeout().
The documentation for this class was generated from the following files:
core/eventreceiver/AcceptEventReceiver.h
core/eventreceiver/AcceptEventReceiver.cpp