SNode.C: iot::mqtt::types::UInt16 Class Reference
iot::mqtt::types::UInt16 Class Reference
#include <UInt16.h>
Public Member Functions
UInt16 ()=default
UInt16 (const UInt16 &)=default
UInt16 (UInt16 &&) noexcept=default
UInt16 & operator= (const UInt16 &)=default
UInt16 & operator= (UInt16 &&) noexcept=default
~UInt16 () override
UInt16 & operator= (const uint16_t &newValue)
operator uint16_t () const
Public Member Functions inherited from iot::mqtt::types::TypeBase< uint16_t >
TypeBase (std::size_t size=sizeof(ValueType))
TypeBase (const TypeBase &)=default
TypeBase (TypeBase &&) noexcept=default
virtual ~TypeBase ()=default
TypeBase & operator= (const TypeBase &)=default
TypeBase & operator= (TypeBase &&) noexcept=default
virtual std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
virtual std::vector< char > serialize () const
void setSize (std::size_t size)
std::size_t size ()
bool isComplete () const
virtual void reset (std::size_t size=sizeof(ValueType))
Additional Inherited Members
Protected Types inherited from iot::mqtt::types::TypeBase< uint16_t >
using ValueType = uint16_t
Protected Attributes inherited from iot::mqtt::types::TypeBase< uint16_t >
std::vector< char > value
std::size_t length
std::size_t needed
bool complete
int state
Detailed Description
Definition at line 57 of file UInt16.h.
Constructor & Destructor Documentation
UInt16() [1/3]
iot::mqtt::types::UInt16::UInt16 () default
UInt16() [2/3]
iot::mqtt::types::UInt16::UInt16 (const UInt16 &) default
UInt16() [3/3]
iot::mqtt::types::UInt16::UInt16 (UInt16 &&) default noexcept
~UInt16()
iot::mqtt::types::UInt16::~UInt16 () override
Definition at line 55 of file UInt16.cpp.
                    {
    }
Member Function Documentation
operator uint16_t()
iot::mqtt::types::UInt16::operator uint16_t () const
Definition at line 64 of file UInt16.cpp.
{
        return be16toh(*reinterpret_cast<uint16_t*>(const_cast<char*>(value.data())));
    }
operator=() [1/3]
UInt16 & iot::mqtt::types::UInt16::operator= (const UInt16 &) default
operator=() [2/3]
UInt16 & iot::mqtt::types::UInt16::operator= (const uint16_t & newValue)
Definition at line 58 of file UInt16.cpp.
{
        *reinterpret_cast<uint16_t*>(value.data()) = htobe16(newValue);
        return *this;
    }
Referenced by iot::mqtt::packets::Connect::Connect(), iot::mqtt::types::String::operator=(), iot::mqtt::types::BinaryData::operator=(), iot::mqtt::packets::Puback::Puback(), iot::mqtt::packets::Pubcomp::Pubcomp(), iot::mqtt::packets::Publish::Publish(), iot::mqtt::packets::Pubrec::Pubrec(), iot::mqtt::packets::Pubrel::Pubrel(), iot::mqtt::types::String::String(), iot::mqtt::packets::Suback::Suback(), iot::mqtt::packets::Subscribe::Subscribe(), iot::mqtt::packets::Unsuback::Unsuback(), and iot::mqtt::packets::Unsubscribe::Unsubscribe().
operator=() [3/3]
UInt16 & iot::mqtt::types::UInt16::operator= (UInt16 &&) default noexcept
The documentation for this class was generated from the following files:
iot/mqtt/types/UInt16.h
iot/mqtt/types/UInt16.cpp