SNode.C: Option Class Reference
Option Class Reference
#include <CLI11.hpp>
Public Member Functions
Basic
Option (const Option &)=delete
Option & operator= (const Option &)=delete
std::size_t count () const
Count the total number of times an option was passed.
bool empty () const
True if the option was not passed.
operator bool () const
This bool operator returns true if any arguments were passed or the option callback is forced.
void clear ()
Clear the parsed results (mostly for testing)
Setting options
Option * expected (int value)
Set the number of expected arguments.
Option * expected (int value_min, int value_max)
Set the range of expected arguments.
Option * allow_extra_args (bool value=true)
bool get_allow_extra_args () const
Get the current value of allow extra args.
Option * trigger_on_parse (bool value=true)
Set the value of trigger_on_parse which specifies that the option callback should be triggered on every parse.
bool get_trigger_on_parse () const
The status of trigger on parse.
Option * force_callback (bool value=true)
Set the value of force_callback.
bool get_force_callback () const
The status of force_callback.
Option * run_callback_for_default (bool value=true)
bool get_run_callback_for_default () const
Get the current value of run_callback_for_default.
Option * check (Validator validator, const std::string &validator_name="")
Adds a Validator with a built in type name.
Option * check (std::function< std::string(const std::string &)> Validator, std::string Validator_description="", std::string Validator_name="")
Adds a Validator. Takes a const string& and returns an error message (empty if conversion/check is okay).
Option * transform (Validator Validator, const std::string &Validator_name="")
Adds a transforming Validator with a built in type name.
Option * transform (const std::function< std::string(std::string)> &func, std::string transform_description="", std::string transform_name="")
Adds a Validator-like function that can change result.
Option * each (const std::function< void(std::string)> &func)
Adds a user supplied function to run on each item passed in (communicate though lambda capture)
Validator * get_validator (const std::string &Validator_name="")
Get a named Validator.
Validator * get_validator (int index)
Get a Validator by index NOTE: this may not be the order of definition.
Option * needs (Option *opt)
Sets required options.
template<typename T = App>
Option * needs (std::string opt_name)
Can find a string if needed.
template<typename A , typename B , typename... ARG>
Option * needs (A opt, B opt1, ARG... args)
Any number supported, any mix of string and Opt.
bool remove_needs (Option *opt)
Remove needs link from an option. Returns true if the option really was in the needs list.
Option * excludes (Option *opt)
Sets excluded options.
template<typename T = App>
Option * excludes (std::string opt_name)
Can find a string if needed.
template<typename A , typename B , typename... ARG>
Option * excludes (A opt, B opt1, ARG... args)
Any number supported, any mix of string and Opt.
bool remove_excludes (Option *opt)
Remove needs link from an option. Returns true if the option really was in the needs list.
Option * envname (std::string name)
Sets environment variable to read if no option given.
template<typename T = App>
Option * ignore_case (bool value=true)
template<typename T = App>
Option * ignore_underscore (bool value=true)
Option * multi_option_policy (MultiOptionPolicy value=MultiOptionPolicy::Throw)
Take the last argument if given multiple times (or another policy)
Option * disable_flag_override (bool value=true)
Disable flag overrides values, e.g. –flag=is not allowed.
Accessors
int get_type_size () const
The number of arguments the option expects.
int get_type_size_min () const
The minimum number of arguments the option expects.
int get_type_size_max () const
The maximum number of arguments the option expects.
bool get_inject_separator () const
Return the inject_separator flag.
std::string get_envname () const
The environment variable associated to this value.
std::set< Option * > get_needs () const
The set of options needed.
std::set< Option * > get_excludes () const
The set of options excluded.
std::string get_default_str () const
The default value (for help printing)
callback_t get_callback () const
Get the callback function.
const std::vector< std::string > & get_lnames () const
Get the long names.
const std::vector< std::string > & get_snames () const
Get the short names.
const std::vector< std::string > & get_fnames () const
Get the flag names with specified default values.
const std::string & get_single_name () const
Get a single name for the option, first of lname, pname, sname, envname.
int get_expected () const
The number of times the option expects to be included.
int get_expected_min () const
The number of times the option expects to be included.
int get_expected_max () const
The max number of times the option expects to be included.
int get_items_expected_min () const
The total min number of expected string values to be used.
int get_items_expected_max () const
Get the maximum number of items expected to be returned and used for the callback.
int get_items_expected () const
The total min number of expected string values to be used.
bool get_positional () const
True if the argument can be given directly.
bool nonpositional () const
True if option has at least one non-positional name.
bool has_description () const
True if option has description.
const std::string & get_description () const
Get the description.
Option * description (std::string option_description)
Set the description.
Option * option_text (std::string text)
const std::string & get_option_text () const
Help tools
std::string get_name (bool positional=false, bool all_options=false) const
Gets a comma separated list of names. Will include / prefer the positional name if positional is true. If all_options is false, pick just the most descriptive name to show. Use get_name(true) to get the positional name (replaces get_pname)
Parser tools
void run_callback ()
Process the callback.
const std::string & matching_name (const Option &other) const
If options share any of the same names, find it.
bool operator== (const Option &other) const
If options share any of the same names, they are equal (not counting positional)
bool check_name (const std::string &name) const
Check a name. Requires "-" or "--" for short / long, supports positional name.
bool check_sname (std::string name) const
Requires "-" to be removed from string.
bool check_lname (std::string name) const
Requires "--" to be removed from string.
bool check_fname (std::string name) const
Requires "--" to be removed from string.
std::string get_flag_value (const std::string &name, std::string input_value) const
Option * add_result (std::string s)
Puts a result at the end.
Option * add_result (std::string s, int &results_added)
Puts a result at the end and get a count of the number of arguments actually added.
Option * add_result (std::vector< std::string > s)
Puts a result at the end.
const results_t & results () const
Get the current complete results set.
results_t reduced_results () const
Get a copy of the results.
template<typename T >
void results (T &output) const
Get the results as a specified type.
template<typename T >
T as () const
Return the results as the specified type.
bool get_callback_run () const
See if the callback has been run already.
Public Member Functions inherited from OptionBase< Option >
Option * group (const std::string &name)
Changes the group membership.
Option * required (bool value=true)
Set the option as required.
Option * mandatory (bool value=true)
Support Plumbum term.
Option * always_capture_default (bool value=true)
const std::string & get_group () const
Get the group of this option.
bool get_required () const
True if this is a required option.
bool get_ignore_case () const
The status of ignore case.
bool get_ignore_underscore () const
The status of ignore_underscore.
bool get_configurable () const
The status of configurable.
bool get_disable_flag_override () const
The status of configurable.
char get_delimiter () const
Get the current delimiter char.
bool get_always_capture_default () const
Return true if this will automatically capture the default value for help printing.
MultiOptionPolicy get_multi_option_policy () const
The status of the multi option policy.
Option * take_last ()
Set the multi option policy to take last.
Option * take_first ()
Set the multi option policy to take last.
Option * take_all ()
Set the multi option policy to take all arguments.
Option * join ()
Set the multi option policy to join.
Option * join (char delim)
Set the multi option policy to join with a specific delimiter.
Option * configurable (bool value=true)
Allow in a configuration file.
Option * delimiter (char value='\0')
Allow in a configuration file.
Protected Member Functions
Option (std::string option_name, std::string option_description, callback_t callback, App *parent)
Making an option by hand is not defined, it must be made by the App class.
Protected Member Functions inherited from OptionBase< Option >
void copy_to (T *other) const
Copy the contents to another similar class (one based on OptionBase)
Protected Attributes
Names
std::vector< std::string > snames_ {}
A list of the short names (-a) without the leading dashes.
std::vector< std::string > lnames_ {}
A list of the long names (--long) without the leading dashes.
std::vector< std::pair< std::string, std::string > > default_flag_values_ {}
std::vector< std::string > fnames_ {}
a list of flag names with specified default values;
std::string pname_ {}
A positional name.
std::string envname_ {}
If given, check the environment for this option.
std::string description_ {}
The description for help strings.
std::string default_str_ {}
A human readable default value, either manually set, captured, or captured by default.
std::string option_text_ {}
If given, replace the text that describes the option type and usage in the help text.
std::function< std::string()> type_name_
std::function< std::string()> default_function_ {}
Run this function to capture a default (ignore if empty)
Configuration
int type_size_max_ {1}
int type_size_min_ {1}
The minimum number of arguments an option should be expecting.
int expected_min_ {1}
The minimum number of expected values.
int expected_max_ {1}
The maximum number of expected values.
std::vector< Validator > validators_ {}
A list of Validators to run on each value parsed.
std::set< Option * > needs_ {}
A list of options that are required with this option.
std::set< Option * > excludes_ {}
A list of options that are excluded with this option.
Other
App * parent_ {nullptr}
link back up to the parent App for fallthrough
callback_t callback_ {}
Options store a callback to do all the work.
Protected Attributes inherited from OptionBase< Option >
std::string group_
The group membership.
bool required_
True if this is a required option.
bool ignore_case_
Ignore the case when matching (option, not value)
bool ignore_underscore_
Ignore underscores when matching (option, not value)
bool configurable_
Allow this option to be given in a configuration file.
bool disable_flag_override_
Disable overriding flag values with '=value'.
char delimiter_
Specify a delimiter character for vector arguments.
bool always_capture_default_
Automatically capture default value.
MultiOptionPolicy multi_option_policy_
Policy for handling multiple arguments beyond the expected Max.
Private Attributes
friend App
Parsing results
enum class option_state : char { parsing = 0 , validated = 2 , reduced = 4 , callback_run = 6 }
enumeration for the option state machine
results_t results_ {}
complete Results of parsing
results_t proc_results_ {}
results after reduction
option_state current_option_state_ {option_state::parsing}
Whether the callback has run (needed for INI parsing)
bool allow_extra_args_ {false}
Specify that extra args beyond type_size_max should be allowed.
bool flag_like_ {false}
Specify that the option should act like a flag vs regular option.
bool run_callback_for_default_ {false}
Control option to run the callback to set the default.
bool inject_separator_ {false}
flag indicating a separator needs to be injected after each argument call
bool trigger_on_result_ {false}
flag indicating that the option should trigger the validation and callback chain on each result when loaded
bool force_callback_ {false}
flag indicating that the option should force the callback regardless if any results present
Custom options
Option * type_name_fn (std::function< std::string()> typefun)
Set the type function to run when displayed on this option.
Option * type_name (std::string typeval)
Set a custom option typestring.
Option * type_size (int option_type_size)
Set a custom option size.
Option * type_size (int option_type_size_min, int option_type_size_max)
Set a custom option type size range.
void inject_separator (bool value=true)
Set the value of the separator injection flag.
Option * default_function (const std::function< std::string()> &func)
Set a capture function for the default. Mostly used by App.
Option * capture_default_str ()
Capture the default value from the original value (if it can be captured)
Option * default_str (std::string val)
Set the default value string representation (does not change the contained value)
template<typename X >
Option * default_val (const X &val)
std::string get_type_name () const
Get the full typename for this option.
void _validate_results (results_t &res) const
Run the results through the Validators.
void _reduce_results (results_t &out, const results_t &original) const
std::string _validate (std::string &result, int index) const
int _add_result (std::string &&result, std::vector< std::string > &res) const
Add a single result to the result set, taking into account delimiters.
Detailed Description
Definition at line 4948 of file CLI11.hpp.
Member Enumeration Documentation
option_state
enum class Option::option_state : char strong protected
enumeration for the option state machine
Enumerator
parsing
The option is currently collecting parsed results.
validated
the results have been validated
reduced
a subset of results has been generated
callback_run
the callback has been executed
Definition at line 5040 of file CLI11.hpp.
                                : char {
            parsing = 0,
            validated = 2,
            reduced = 4,
            callback_run = 6,
        };
Constructor & Destructor Documentation
Option() [1/2]
Option::Option (std::string option_name, std::string option_description, callback_t callback, App * parent) inline protected
Making an option by hand is not defined, it must be made by the App class.
Definition at line 5063 of file CLI11.hpp.
            : description_(std::move(option_description))
            , parent_(parent)
            , callback_(std::move(callback)) {
            std::tie(snames_, lnames_, pname_) = detail::get_names(detail::split_names(option_name));
        }
References description_, Option(), and parent_.
Referenced by Option().
Option() [2/2]
Option::Option (const Option &) delete
Member Function Documentation
_add_result()
int Option::_add_result (std::string && result, std::vector< std::string > & res) const inline private
Add a single result to the result set, taking into account delimiters.
Definition at line 6196 of file CLI11.hpp.
{
        int result_count = 0;
        if (allow_extra_args_ && !result.empty() && result.front() == '[' &&
            result.back() == ']') { // this is now a vector string likely from the default or user entry
            result.pop_back();
            for (auto& var : CLI::detail::split(result.substr(1), ',')) {
                if (!var.empty()) {
                    result_count += _add_result(std::move(var), res);
                }
            }
            return result_count;
        }
        if (delimiter_ == '\0') {
            res.push_back(std::move(result));
            ++result_count;
        } else {
            if ((result.find_first_of(delimiter_) != std::string::npos)) {
                for (const auto& var : CLI::detail::split(result, delimiter_)) {
                    if (!var.empty()) {
                        res.push_back(var);
                        ++result_count;
                    }
                }
            } else {
                res.push_back(std::move(result));
                ++result_count;
            }
        }
        return result_count;
    }
References allow_extra_args_.
_reduce_results()
void Option::_reduce_results (results_t & out, const results_t & original) const inline private
reduce the results in accordance with the MultiOptionPolicy
Parameters
[out] out results are assigned to res if there if they are different
Definition at line 6111 of file CLI11.hpp.
{
        // max num items expected or length of vector, always at least 1
        // Only valid for a trimming policy
        out.clear();
        // Operation depends on the policy setting
        switch (multi_option_policy_) {
            case MultiOptionPolicy::TakeAll:
                break;
            case MultiOptionPolicy::TakeLast: {
                // Allow multi-option sizes (including 0)
                std::size_t const trim_size =
                    std::min<std::size_t>(static_cast<std::size_t>(std::max<int>(get_items_expected_max(), 1)), original.size());
                if (original.size() != trim_size) {
                    out.assign(original.end() - static_cast<results_t::difference_type>(trim_size), original.end());
                }
            } break;
            case MultiOptionPolicy::TakeFirst: {
                std::size_t const trim_size =
                    std::min<std::size_t>(static_cast<std::size_t>(std::max<int>(get_items_expected_max(), 1)), original.size());
                if (original.size() != trim_size) {
                    out.assign(original.begin(), original.begin() + static_cast<results_t::difference_type>(trim_size));
                }
            } break;
            case MultiOptionPolicy::Join:
                if (results_.size() > 1) {
                    out.push_back(detail::join(original, std::string(1, (delimiter_ == '\0') ? '\n' : delimiter_)));
                }
                break;
            case MultiOptionPolicy::Sum:
                out.push_back(detail::sum_string_vector(original));
                break;
            case MultiOptionPolicy::Throw:
            default: {
                auto num_min = static_cast<std::size_t>(get_items_expected_min());
                auto num_max = static_cast<std::size_t>(get_items_expected_max());
                if (num_min == 0) {
                    num_min = 1;
                }
                if (num_max == 0) {
                    num_max = 1;
                }
                if (original.size() < num_min) {
                    throw ArgumentMismatch::AtLeast(get_name(), static_cast<int>(num_min), original.size());
                }
                if (original.size() > num_max) {
                    throw ArgumentMismatch::AtMost(get_name(), static_cast<int>(num_max), original.size());
                }
                break;
            }
        }
        // this check is to allow an empty vector in certain circumstances but not if expected is not zero.
        // {} is the indicator for an empty container
        if (out.empty()) {
            if (original.size() == 1 && original[0] == "{}" && get_items_expected_min() > 0) {
                out.push_back("{}");
                out.push_back("%%");
            }
        } else if (out.size() == 1 && out[0] == "{}" && get_items_expected_min() > 0) {
            out.push_back("%%");
        }
    }
_validate()
std::string Option::_validate (std::string & result, int index) const inline private
Definition at line 6174 of file CLI11.hpp.
{
        std::string err_msg;
        if (result.empty() && expected_min_ == 0) {
            // an empty with nothing expected is allowed
            return err_msg;
        }
        for (const auto& vali : validators_) {
            auto v = vali.get_application_index();
            if (v == -1 || v == index) {
                try {
                    err_msg = vali(result);
                } catch (const ValidationError& err) {
                    err_msg = err.what();
                }
                if (!err_msg.empty())
                    break;
            }
        }
        return err_msg;
    }
References expected_min_.
_validate_results()
void Option::_validate_results (results_t & res) const inline private
Run the results through the Validators.
Definition at line 6075 of file CLI11.hpp.
{
        // Run the Validators (can change the string)
        if (!validators_.empty()) {
            if (type_size_max_ > 1) { // in this context index refers to the index in the type
                int index = 0;
                if (get_items_expected_max() < static_cast<int>(res.size()) && multi_option_policy_ == CLI::MultiOptionPolicy::TakeLast) {
                    // create a negative index for the earliest ones
                    index = get_items_expected_max() - static_cast<int>(res.size());
                }
                for (std::string& result : res) {
                    if (detail::is_separator(result) && type_size_max_ != type_size_min_ && index >= 0) {
                        index = 0; // reset index for variable size chunks
                        continue;
                    }
                    auto err_msg = _validate(result, (index >= 0) ? (index % type_size_max_) : index);
                    if (!err_msg.empty())
                        throw ValidationError(get_name(), err_msg);
                    ++index;
                }
            } else {
                int index = 0;
                if (expected_max_ < static_cast<int>(res.size()) && multi_option_policy_ == CLI::MultiOptionPolicy::TakeLast) {
                    // create a negative index for the earliest ones
                    index = expected_max_ - static_cast<int>(res.size());
                }
                for (std::string& result : res) {
                    auto err_msg = _validate(result, index);
                    ++index;
                    if (!err_msg.empty())
                        throw ValidationError(get_name(), err_msg);
                }
            }
        }
    }
References type_size_max_.
add_result() [1/3]
Option * Option::add_result (std::string s) inline
Puts a result at the end.
Definition at line 5981 of file CLI11.hpp.
{
        _add_result(std::move(s), results_);
        current_option_state_ = option_state::parsing;
        return this;
    }
References current_option_state_, and parsing.
Referenced by default_val(), and run_callback().
add_result() [2/3]
Option * Option::add_result (std::string s, int & results_added) inline
Puts a result at the end and get a count of the number of arguments actually added.
Definition at line 5987 of file CLI11.hpp.
{
        results_added = _add_result(std::move(s), results_);
        current_option_state_ = option_state::parsing;
        return this;
    }
References current_option_state_, and parsing.
add_result() [3/3]
Option * Option::add_result (std::vector< std::string > s) inline
Puts a result at the end.
Definition at line 5993 of file CLI11.hpp.
{
        current_option_state_ = option_state::parsing;
        for (auto& str : s) {
            _add_result(std::move(str), results_);
        }
        return this;
    }
References current_option_state_, and parsing.
allow_extra_args()
Option * Option::allow_extra_args (bool value = true) inline
Set the value of allow_extra_args which allows extra value arguments on the flag or option to be included with each instance
Definition at line 5110 of file CLI11.hpp.
{
            allow_extra_args_ = value;
            return this;
        }
References allow_extra_args_.
Referenced by retire_option().
as()
template<typename T > T Option::as () const inline
Return the results as the specified type.
Definition at line 5495 of file CLI11.hpp.
{
            T output;
            results(output);
            return output;
        }
capture_default_str()
Option * Option::capture_default_str () inline
Capture the default value from the original value (if it can be captured)
Definition at line 5542 of file CLI11.hpp.
{
            if (default_function_) {
                default_str_ = default_function_();
            }
            return this;
        }
Referenced by net::config::ConfigTlsServer::addSniCert(), and net::config::ConfigTlsServer::addSniCerts().
check() [1/2]
Option * Option::check (std::function< std::string(const std::string &)> Validator, std::string Validator_description = "", std::string Validator_name = "") inline
Adds a Validator. Takes a const string& and returns an error message (empty if conversion/check is okay).
Definition at line 5666 of file CLI11.hpp.
{
        validators_.emplace_back(Validator, std::move(Validator_description), std::move(Validator_name));
        validators_.back().non_modifying();
        return this;
    }
check() [2/2]
Option * Option::check (Validator validator, const std::string & validator_name = "") inline
Adds a Validator with a built in type name.
Definition at line 5657 of file CLI11.hpp.
{
        validator.non_modifying();
        validators_.push_back(std::move(validator));
        if (!validator_name.empty())
            validators_.back().name(validator_name);
        return this;
    }
References Validator::non_modifying().
Referenced by deprecate_option().
check_fname()
bool Option::check_fname (std::string name) const inline
Requires "--" to be removed from string.
Definition at line 5433 of file CLI11.hpp.
{
            if (fnames_.empty()) {
                return false;
            }
            return (detail::find_member(std::move(name), fnames_, ignore_case_, ignore_underscore_) >= 0);
        }
check_lname()
bool Option::check_lname (std::string name) const inline
Requires "--" to be removed from string.
Definition at line 5428 of file CLI11.hpp.
{
            return (detail::find_member(std::move(name), lnames_, ignore_case_, ignore_underscore_) >= 0);
        }
Referenced by check_name().
check_name()
bool Option::check_name (const std::string & name) const inline
Check a name. Requires "-" or "--" for short / long, supports positional name.
Definition at line 5911 of file CLI11.hpp.
{
        if (name.length() > 2 && name[0] == '-' && name[1] == '-')
            return check_lname(name.substr(2));
        if (name.length() > 1 && name.front() == '-')
            return check_sname(name.substr(1));
        if (!pname_.empty()) {
            std::string local_pname = pname_;
            std::string local_name = name;
            if (ignore_underscore_) {
                local_pname = detail::remove_underscore(local_pname);
                local_name = detail::remove_underscore(local_name);
            }
            if (ignore_case_) {
                local_pname = detail::to_lower(local_pname);
                local_name = detail::to_lower(local_name);
            }
            if (local_name == local_pname) {
                return true;
            }
        }
        if (!envname_.empty()) {
            // this needs to be the original since envname_ shouldn't match on case insensitivity
            return (name == envname_);
        }
        return false;
    }
References check_lname(), check_sname(), envname_, pname_, CLI::detail::remove_underscore(), and CLI::detail::to_lower().
check_sname()
bool Option::check_sname (std::string name) const inline
Requires "-" to be removed from string.
Definition at line 5423 of file CLI11.hpp.
{
            return (detail::find_member(std::move(name), snames_, ignore_case_) >= 0);
        }
Referenced by check_name().
clear()
void Option::clear () inline
Clear the parsed results (mostly for testing)
Definition at line 5093 of file CLI11.hpp.
                     {
            results_.clear();
            current_option_state_ = option_state::parsing;
        }
References current_option_state_, and parsing.
Referenced by net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient(), net::config::ConfigPhysicalSocketServer::setAcceptsPerTick(), net::config::ConfigPhysicalSocketServer::setAcceptTimeout(), net::config::ConfigPhysicalSocketServer::setBacklog(), net::config::ConfigTls::setCaCert(), net::config::ConfigTls::setCaCertAcceptUnknown(), net::config::ConfigTls::setCaCertDir(), net::config::ConfigTls::setCaCertUseDefaultDir(), net::config::ConfigTls::setCert(), net::config::ConfigTls::setCertKey(), net::config::ConfigTls::setCertKeyPassword(), net::config::ConfigTls::setCipherList(), net::config::ConfigPhysicalSocketClient::setConnectTimeout(), net::config::ConfigInstance::setDisabled(), net::config::ConfigTlsServer::setForceSni(), net::config::ConfigTls::setInitTimeout(), net::config::ConfigTls::setNoCloseNotifyIsEOF(), net::config::ConfigConnection::setReadBlockSize(), net::config::ConfigConnection::setReadTimeout(), net::config::ConfigPhysicalSocketClient::setReconnect(), net::config::ConfigPhysicalSocketClient::setReconnectTime(), net::config::ConfigPhysicalSocket::setRetry(), net::config::ConfigPhysicalSocket::setRetryBase(), net::config::ConfigPhysicalSocket::setRetryJitter(), net::config::ConfigPhysicalSocket::setRetryLimit(), net::config::ConfigPhysicalSocket::setRetryOnFatal(), net::config::ConfigPhysicalSocket::setRetryTimeout(), net::config::ConfigPhysicalSocket::setRetryTries(), net::config::ConfigPhysicalSocket::setReuseAddress(), net::config::ConfigTls::setShutdownTimeout(), net::config::ConfigTlsClient::setSni(), net::config::ConfigTls::setSslOptions(), net::config::ConfigConnection::setTerminateTimeout(), net::config::ConfigConnection::setWriteBlockSize(), net::config::ConfigConnection::setWriteTimeout(), and App::version().
count()
std::size_t Option::count () const inline
Count the total number of times an option was passed.
Definition at line 5078 of file CLI11.hpp.
{
            return results_.size();
        }
Referenced by App::_process_config_file(), App::_process_help_flags(), and App::count().
default_function()
Option * Option::default_function (const std::function< std::string()> & func) inline
Set a capture function for the default. Mostly used by App.
Definition at line 5536 of file CLI11.hpp.
{
            default_function_ = func;
            return this;
        }
default_str()
Option * Option::default_str (std::string val) inline
Set the default value string representation (does not change the contained value)
Definition at line 5550 of file CLI11.hpp.
{
            default_str_ = std::move(val);
            return this;
        }
References default_str_.
Referenced by retire_option(), retire_option(), and App::set_config().
default_val()
template<typename X > Option * Option::default_val (const X & val) inline
Set the default value and validate the results and run the callback if appropriate to set the value into the bound value only available for types that can be converted to a string
Definition at line 5558 of file CLI11.hpp.
{
            std::string val_str = detail::to_string(val);
            auto old_option_state = current_option_state_;
            results_t old_results{std::move(results_)};
            results_.clear();
            try {
                add_result(val_str);
                // if trigger_on_result_ is set the callback already ran
                if (run_callback_for_default_ && !trigger_on_result_) {
                    run_callback(); // run callback sets the state, we need to reset it again
                    current_option_state_ = option_state::parsing;
                } else {
                    _validate_results(results_);
                    current_option_state_ = old_option_state;
                }
            } catch (const CLI::Error&) {
                // this should be done
                results_ = std::move(old_results);
                current_option_state_ = old_option_state;
                throw;
            }
            results_ = std::move(old_results);
            default_str_ = std::move(val_str);
            return this;
        }
References add_result(), current_option_state_, default_str_, parsing, run_callback(), run_callback_for_default_, and trigger_on_result_.
description()
Option * Option::description (std::string option_description) inline
Set the description.
Definition at line 5378 of file CLI11.hpp.
{
            description_ = std::move(option_description);
            return this;
        }
References description_.
Referenced by deprecate_option().
disable_flag_override()
Option * Option::disable_flag_override (bool value = true) inline
Disable flag overrides values, e.g. –flag=is not allowed.
Definition at line 5249 of file CLI11.hpp.
{
            disable_flag_override_ = value;
            return this;
        }
each()
Option * Option::each (const std::function< void(std::string)> & func) inline
Adds a user supplied function to run on each item passed in (communicate though lambda capture)
Definition at line 5693 of file CLI11.hpp.
{
        validators_.emplace_back(
            [func](std::string& inout) {
                func(inout);
                return std::string{};
            },
            std::string{});
        return this;
    }
empty()
bool Option::empty () const inline
True if the option was not passed.
Definition at line 5083 of file CLI11.hpp.
{
            return results_.empty();
        }
Referenced by App::_parse_single_config(), and operator bool().
envname()
Option * Option::envname (std::string name) inline
Sets environment variable to read if no option given.
Definition at line 5226 of file CLI11.hpp.
{
            envname_ = std::move(name);
            return this;
        }
References envname_.
excludes() [1/3]
template<typename A , typename B , typename... ARG> Option * Option::excludes (A opt, B opt1, ARG... args) inline
Any number supported, any mix of string and Opt.
Definition at line 5217 of file CLI11.hpp.
{
            excludes(opt);
            return excludes(opt1, args...);
        }
excludes() [2/3]
Option * Option::excludes (Option * opt) inline
Sets excluded options.
Definition at line 5733 of file CLI11.hpp.
{
        if (opt == this) {
            throw(IncorrectConstruction("and option cannot exclude itself"));
        }
        excludes_.insert(opt);
        // Help text should be symmetric - excluding a should exclude b
        opt->excludes_.insert(this);
        // Ignoring the insert return value, excluding twice is now allowed.
        // (Mostly to allow both directions to be excluded by user, even though the library does it for you.)
        return this;
    }
excludes() [3/3]
template<typename T = App> Option * Option::excludes (std::string opt_name) inline
Can find a string if needed.
Definition at line 5207 of file CLI11.hpp.
{
            auto opt = static_cast<T*>(parent_)->get_option_no_throw(opt_name);
            if (opt == nullptr) {
                throw IncorrectConstruction::MissingOption(opt_name);
            }
            return excludes(opt);
        }
References IncorrectConstruction::MissingOption(), and parent_.
expected() [1/2]
Option * Option::expected (int value) inline
Set the number of expected arguments.
Definition at line 5617 of file CLI11.hpp.
{
        if (value < 0) {
            expected_min_ = -value;
            if (expected_max_ < expected_min_) {
                expected_max_ = expected_min_;
            }
            allow_extra_args_ = true;
            flag_like_ = false;
        } else if (value == detail::expected_max_vector_size) {
            expected_min_ = 1;
            expected_max_ = detail::expected_max_vector_size;
            allow_extra_args_ = true;
            flag_like_ = false;
        } else {
            expected_min_ = value;
            expected_max_ = value;
            flag_like_ = (expected_min_ == 0);
        }
        return this;
    }
References allow_extra_args_, expected_max_, CLI::detail::expected_max_vector_size, expected_min_, and flag_like_.
Referenced by App::_add_flag_internal().
expected() [2/2]
Option * Option::expected (int value_min, int value_max) inline
Set the range of expected arguments.
Definition at line 5638 of file CLI11.hpp.
{
        if (value_min < 0) {
            value_min = -value_min;
        }
        if (value_max < 0) {
            value_max = detail::expected_max_vector_size;
        }
        if (value_max < value_min) {
            expected_min_ = value_max;
            expected_max_ = value_min;
        } else {
            expected_max_ = value_max;
            expected_min_ = value_min;
        }
        return this;
    }
References expected_max_, CLI::detail::expected_max_vector_size, and expected_min_.
Referenced by retire_option(), and retire_option().
force_callback()
Option * Option::force_callback (bool value = true) inline
Set the value of force_callback.
Definition at line 5129 of file CLI11.hpp.
{
            force_callback_ = value;
            return this;
        }
References force_callback_.
get_allow_extra_args()
bool Option::get_allow_extra_args () const inline
Get the current value of allow extra args.
Definition at line 5115 of file CLI11.hpp.
{
            return allow_extra_args_;
        }
References allow_extra_args_.
Referenced by retire_option().
get_callback()
callback_t Option::get_callback () const inline
Get the callback function.
Definition at line 5297 of file CLI11.hpp.
{
            return callback_;
        }
get_callback_run()
bool Option::get_callback_run () const inline
See if the callback has been run already.
Definition at line 5502 of file CLI11.hpp.
{
            return (current_option_state_ == option_state::callback_run);
        }
References callback_run, and current_option_state_.
get_default_str()
std::string Option::get_default_str () const inline
The default value (for help printing)
Definition at line 5292 of file CLI11.hpp.
{
            return default_str_;
        }
References default_str_.
Referenced by CLI::HelpFormatter::make_option_opts(), and Formatter::make_option_opts().
get_description()
const std::string & Option::get_description () const inline
Get the description.
Definition at line 5373 of file CLI11.hpp.
{
            return description_;
        }
References description_.
Referenced by App::App(), deprecate_option(), and Formatter::make_option_desc().
get_envname()
std::string Option::get_envname () const inline
The environment variable associated to this value.
Definition at line 5277 of file CLI11.hpp.
{
            return envname_;
        }
References envname_.
Referenced by CLI::HelpFormatter::make_option_opts(), and Formatter::make_option_opts().
get_excludes()
std::set< Option * > Option::get_excludes () const inline
The set of options excluded.
Definition at line 5287 of file CLI11.hpp.
{
            return excludes_;
        }
get_expected()
int Option::get_expected () const inline
The number of times the option expects to be included.
Definition at line 5329 of file CLI11.hpp.
{
            return expected_min_;
        }
References expected_min_.
Referenced by CLI::HelpFormatter::make_option_opts(), Formatter::make_option_opts(), and Formatter::make_option_usage().
get_expected_max()
int Option::get_expected_max () const inline
The max number of times the option expects to be included.
Definition at line 5338 of file CLI11.hpp.
{
            return expected_max_;
        }
References expected_max_.
Referenced by CLI::HelpFormatter::make_option_opts(), Formatter::make_option_opts(), Formatter::make_option_usage(), and retire_option().
get_expected_min()
int Option::get_expected_min () const inline
The number of times the option expects to be included.
Definition at line 5334 of file CLI11.hpp.
{
            return expected_min_;
        }
References expected_min_.
Referenced by App::_parse_single_config(), CLI::HelpFormatter::make_option_opts(), Formatter::make_option_opts(), and retire_option().
get_flag_value()
std::string Option::get_flag_value (const std::string & name, std::string input_value) const inline
Get the value that goes for a flag, nominally gets the default value but allows for overrides if not disabled
Definition at line 5939 of file CLI11.hpp.
{
        static const std::string trueString{"true"};
        static const std::string falseString{"false"};
        static const std::string emptyString{"{}"};
        // check for disable flag override_
        if (disable_flag_override_) {
            if (!((input_value.empty()) || (input_value == emptyString))) {
                auto default_ind = detail::find_member(name, fnames_, ignore_case_, ignore_underscore_);
                if (default_ind >= 0) {
                    // We can static cast this to std::size_t because it is more than 0 in this block
                    if (default_flag_values_[static_cast<std::size_t>(default_ind)].second != input_value) {
                        throw(ArgumentMismatch::FlagOverride(name));
                    }
                } else {
                    if (input_value != trueString) {
                        throw(ArgumentMismatch::FlagOverride(name));
                    }
                }
            }
        }
        auto ind = detail::find_member(name, fnames_, ignore_case_, ignore_underscore_);
        if ((input_value.empty()) || (input_value == emptyString)) {
            if (flag_like_) {
                return (ind < 0) ? trueString : default_flag_values_[static_cast<std::size_t>(ind)].second;
            }
            return (ind < 0) ? default_str_ : default_flag_values_[static_cast<std::size_t>(ind)].second;
        }
        if (ind < 0) {
            return input_value;
        }
        if (default_flag_values_[static_cast<std::size_t>(ind)].second == falseString) {
            try {
                auto val = detail::to_flag_value(input_value);
                return (val == 1) ? falseString : (val == (-1) ? trueString : std::to_string(-val));
            } catch (const std::invalid_argument&) {
                return input_value;
            }
        } else {
            return input_value;
        }
    }
References flag_like_, ArgumentMismatch::FlagOverride(), and detail::to_flag_value().
get_fnames()
const std::vector< std::string > & Option::get_fnames () const inline
Get the flag names with specified default values.
Definition at line 5312 of file CLI11.hpp.
{
            return fnames_;
        }
get_force_callback()
bool Option::get_force_callback () const inline
The status of force_callback.
Definition at line 5134 of file CLI11.hpp.
{
            return force_callback_;
        }
References force_callback_.
get_inject_separator()
bool Option::get_inject_separator () const inline
Return the inject_separator flag.
Definition at line 5272 of file CLI11.hpp.
{
            return inject_separator_;
        }
References inject_separator_.
get_items_expected()
int Option::get_items_expected () const inline
The total min number of expected string values to be used.
Definition at line 5353 of file CLI11.hpp.
{
            return get_items_expected_min();
        }
References get_items_expected_min().
get_items_expected_max()
int Option::get_items_expected_max () const inline
Get the maximum number of items expected to be returned and used for the callback.
Definition at line 5348 of file CLI11.hpp.
{
            int t = type_size_max_;
            return detail::checked_multiply(t, expected_max_) ? t : detail::expected_max_vector_size;
        }
References expected_max_, CLI::detail::expected_max_vector_size, and type_size_max_.
Referenced by App::_parse_single_config(), and CLI::HelpFormatter::make_option_opts().
get_items_expected_min()
int Option::get_items_expected_min () const inline
The total min number of expected string values to be used.
Definition at line 5343 of file CLI11.hpp.
{
            return type_size_min_ * expected_min_;
        }
References expected_min_, and type_size_min_.
Referenced by get_items_expected().
get_lnames()
const std::vector< std::string > & Option::get_lnames () const inline
Get the long names.
Definition at line 5302 of file CLI11.hpp.
{
            return lnames_;
        }
get_name()
std::string Option::get_name (bool positional = false, bool all_options = false) const inline
Gets a comma separated list of names. Will include / prefer the positional name if positional is true. If all_options is false, pick just the most descriptive name to show. Use get_name(true) to get the positional name (replaces get_pname)
The all list will never include a positional unless asked or that's the only name.
Parameters
positional Show the positional name
all_options Show every option
Definition at line 5813 of file CLI11.hpp.
{
        if (get_group().empty())
            return {}; // Hidden
        if (all_options) {
            std::vector<std::string> name_list;
            if ((positional && (!pname_.empty())) || (snames_.empty() && lnames_.empty())) {
                name_list.push_back(pname_);
            }
            if ((get_items_expected() == 0) && (!fnames_.empty())) {
                for (const std::string& sname : snames_) {
                    name_list.push_back("-" + sname);
                    if (check_fname(sname)) {
                        name_list.back() += "{" + get_flag_value(sname, "") + "}";
                    }
                }
                for (const std::string& lname : lnames_) {
                    name_list.push_back("--" + lname);
                    if (check_fname(lname)) {
                        name_list.back() += "{" + get_flag_value(lname, "") + "}";
                    }
                }
            } else {
                for (const std::string& sname : snames_)
                    name_list.push_back("-" + sname);
                for (const std::string& lname : lnames_)
                    name_list.push_back("--" + lname);
            }
            return detail::join(name_list);
        }
        // This returns the positional name no matter what
        if (positional)
            return pname_;
        // Prefer long name
        if (!lnames_.empty())
            return std::string(2, '-') + lnames_[0];
        // Or short name if no long name
        if (!snames_.empty())
            return std::string(1, '-') + snames_[0];
        // If positional is the only name, it's okay to use that
        return pname_;
    }
References pname_.
Referenced by App::_add_flag_internal(), App::_move_option(), App::App(), deprecate_option(), Formatter::make_option_name(), and retire_option().
get_needs()
std::set< Option * > Option::get_needs () const inline
The set of options needed.
Definition at line 5282 of file CLI11.hpp.
{
            return needs_;
        }
get_option_text()
const std::string & Option::get_option_text () const inline
Definition at line 5388 of file CLI11.hpp.
{
            return option_text_;
        }
References option_text_.
Referenced by CLI::HelpFormatter::make_option_opts(), and Formatter::make_option_opts().
get_positional()
bool Option::get_positional () const inline
True if the argument can be given directly.
Definition at line 5358 of file CLI11.hpp.
{
            return pname_.length() > 0;
        }
References pname_.
Referenced by App::_add_flag_internal().
get_run_callback_for_default()
bool Option::get_run_callback_for_default () const inline
Get the current value of run_callback_for_default.
Definition at line 5145 of file CLI11.hpp.
{
            return run_callback_for_default_;
        }
References run_callback_for_default_.
get_single_name()
const std::string & Option::get_single_name () const inline
Get a single name for the option, first of lname, pname, sname, envname.
Definition at line 5316 of file CLI11.hpp.
{
            if (!lnames_.empty()) {
                return lnames_[0];
            }
            if (!pname_.empty()) {
                return pname_;
            }
            if (!snames_.empty()) {
                return snames_[0];
            }
            return envname_;
        }
References envname_, and pname_.
get_snames()
const std::vector< std::string > & Option::get_snames () const inline
Get the short names.
Definition at line 5307 of file CLI11.hpp.
{
            return snames_;
        }
get_trigger_on_parse()
bool Option::get_trigger_on_parse () const inline
The status of trigger on parse.
Definition at line 5124 of file CLI11.hpp.
{
            return trigger_on_result_;
        }
References trigger_on_result_.
get_type_name()
std::string Option::get_type_name () const inline
Get the full typename for this option.
Definition at line 6062 of file CLI11.hpp.
{
        std::string full_type_name = type_name_();
        if (!validators_.empty()) {
            for (const auto& Validator : validators_) {
                std::string const vtype = Validator.get_description();
                if (!vtype.empty()) {
                    full_type_name += ":" + vtype;
                }
            }
        }
        return full_type_name;
    }
Referenced by CLI::HelpFormatter::make_option_opts(), and Formatter::make_option_opts().
get_type_size()
int Option::get_type_size () const inline
The number of arguments the option expects.
Definition at line 5258 of file CLI11.hpp.
{
            return type_size_min_;
        }
References type_size_min_.
Referenced by CLI::HelpFormatter::make_option_opts(), and Formatter::make_option_opts().
get_type_size_max()
int Option::get_type_size_max () const inline
The maximum number of arguments the option expects.
Definition at line 5267 of file CLI11.hpp.
{
            return type_size_max_;
        }
References type_size_max_.
Referenced by retire_option().
get_type_size_min()
int Option::get_type_size_min () const inline
The minimum number of arguments the option expects.
Definition at line 5263 of file CLI11.hpp.
{
            return type_size_min_;
        }
References type_size_min_.
Referenced by retire_option().
get_validator() [1/2]
Validator * Option::get_validator (const std::string & Validator_name = "") inline
Get a named Validator.
Definition at line 5703 of file CLI11.hpp.
{
        for (auto& Validator : validators_) {
            if (Validator_name == Validator.get_name()) {
                return &Validator;
            }
        }
        if ((Validator_name.empty()) && (!validators_.empty())) {
            return &(validators_.front());
        }
        throw OptionNotFound(std::string{"Validator "} + Validator_name + " Not Found");
    }
get_validator() [2/2]
Validator * Option::get_validator (int index) inline
Get a Validator by index NOTE: this may not be the order of definition.
Definition at line 5715 of file CLI11.hpp.
{
        // This is an signed int so that it is not equivalent to a pointer.
        if (index >= 0 && index < static_cast<int>(validators_.size())) {
            return &(validators_[static_cast<decltype(validators_)::size_type>(index)]);
        }
        throw OptionNotFound("Validator index is not valid");
    }
has_description()
bool Option::has_description () const inline
True if option has description.
Definition at line 5368 of file CLI11.hpp.
{
            return description_.length() > 0;
        }
References description_.
ignore_case()
template<typename T > Option * Option::ignore_case (bool value = true)
Ignore case
The template hides the fact that we don't have the definition of App yet. You are never expected to add an argument to the template here.
Definition at line 5759 of file CLI11.hpp.
{
        if (!ignore_case_ && value) {
            ignore_case_ = value;
            auto* parent = static_cast<T*>(parent_);
            for (const Option_p& opt : parent->options_) {
                if (opt.get() == this) {
                    continue;
                }
                const auto& omatch = opt->matching_name(*this);
                if (!omatch.empty()) {
                    ignore_case_ = false;
                    throw OptionAlreadyAdded("adding ignore case caused a name conflict with " + omatch);
                }
            }
        } else {
            ignore_case_ = value;
        }
        return this;
    }
References parent_.
ignore_underscore()
template<typename T > Option * Option::ignore_underscore (bool value = true)
Ignore underscores in the option names
The template hides the fact that we don't have the definition of App yet. You are never expected to add an argument to the template here.
Definition at line 5780 of file CLI11.hpp.
{
        if (!ignore_underscore_ && value) {
            ignore_underscore_ = value;
            auto* parent = static_cast<T*>(parent_);
            for (const Option_p& opt : parent->options_) {
                if (opt.get() == this) {
                    continue;
                }
                const auto& omatch = opt->matching_name(*this);
                if (!omatch.empty()) {
                    ignore_underscore_ = false;
                    throw OptionAlreadyAdded("adding ignore underscore caused a name conflict with " + omatch);
                }
            }
        } else {
            ignore_underscore_ = value;
        }
        return this;
    }
References parent_.
inject_separator()
void Option::inject_separator (bool value = true) inline
Set the value of the separator injection flag.
Definition at line 5531 of file CLI11.hpp.
{
            inject_separator_ = value;
        }
References inject_separator_.
matching_name()
const std::string & Option::matching_name (const Option & other) const inline
If options share any of the same names, find it.
Definition at line 5891 of file CLI11.hpp.
{
        static const std::string estring;
        for (const std::string& sname : snames_)
            if (other.check_sname(sname))
                return sname;
        for (const std::string& lname : lnames_)
            if (other.check_lname(lname))
                return lname;
        if (ignore_case_ || ignore_underscore_) { // We need to do the inverse, in case we are ignore_case or ignore underscore
            for (const std::string& sname : other.snames_)
                if (check_sname(sname))
                    return sname;
            for (const std::string& lname : other.lnames_)
                if (check_lname(lname))
                    return lname;
        }
        return estring;
    }
Referenced by operator==().
multi_option_policy()
Option * Option::multi_option_policy (MultiOptionPolicy value = MultiOptionPolicy::Throw) inline
Take the last argument if given multiple times (or another policy)
Definition at line 5800 of file CLI11.hpp.
{
        if (value != multi_option_policy_) {
            if (multi_option_policy_ == MultiOptionPolicy::Throw && expected_max_ == detail::expected_max_vector_size &&
                expected_min_ > 1) { // this bizarre condition is to maintain backwards compatibility
                                     // with the previous behavior of expected_ with vectors
                expected_max_ = expected_min_;
            }
            multi_option_policy_ = value;
            current_option_state_ = option_state::parsing;
        }
        return this;
    }
References current_option_state_, expected_max_, expected_min_, and parsing.
Referenced by App::_add_flag_internal().
needs() [1/3]
template<typename A , typename B , typename... ARG> Option * Option::needs (A opt, B opt1, ARG... args) inline
Any number supported, any mix of string and Opt.
Definition at line 5194 of file CLI11.hpp.
{
            needs(opt);
            return needs(opt1, args...); // NOLINT(readability-suspicious-call-argument)
        }
needs() [2/3]
Option * Option::needs (Option * opt) inline
Sets required options.
Definition at line 5175 of file CLI11.hpp.
{
            if (opt != this) {
                needs_.insert(opt);
            }
            return this;
        }
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient(), net::config::ConfigPhysicalSocketClient::setReconnect(), and net::config::ConfigPhysicalSocket::setRetry().
needs() [3/3]
template<typename T = App> Option * Option::needs (std::string opt_name) inline
Can find a string if needed.
Definition at line 5184 of file CLI11.hpp.
{
            auto opt = static_cast<T*>(parent_)->get_option_no_throw(opt_name);
            if (opt == nullptr) {
                throw IncorrectConstruction::MissingOption(opt_name);
            }
            return needs(opt);
        }
References IncorrectConstruction::MissingOption(), and parent_.
nonpositional()
bool Option::nonpositional () const inline
True if option has at least one non-positional name.
Definition at line 5363 of file CLI11.hpp.
{
            return (snames_.size() + lnames_.size()) > 0;
        }
operator bool()
Option::operator bool () const inline explicit
This bool operator returns true if any arguments were passed or the option callback is forced.
Definition at line 5088 of file CLI11.hpp.
{
            return !empty() || force_callback_;
        }
References empty(), and force_callback_.
operator=()
Option & Option::operator= (const Option &) delete
operator==()
bool Option::operator== (const Option & other) const inline
If options share any of the same names, they are equal (not counting positional)
Definition at line 5415 of file CLI11.hpp.
{
            return !matching_name(other).empty();
        }
References matching_name().
option_text()
Option * Option::option_text (std::string text) inline
Definition at line 5383 of file CLI11.hpp.
{
            option_text_ = std::move(text);
            return this;
        }
References option_text_.
reduced_results()
results_t Option::reduced_results () const inline
Get a copy of the results.
Definition at line 6001 of file CLI11.hpp.
{
        results_t res = proc_results_.empty() ? results_ : proc_results_;
        if (current_option_state_ < option_state::reduced) {
            if (current_option_state_ == option_state::parsing) {
                res = results_;
                _validate_results(res);
            }
            if (!res.empty()) {
                results_t extra;
                _reduce_results(extra, res);
                if (!extra.empty()) {
                    res = std::move(extra);
                }
            }
        }
        return res;
    }
References current_option_state_, parsing, and reduced.
remove_excludes()
bool Option::remove_excludes (Option * opt) inline
Remove needs link from an option. Returns true if the option really was in the needs list.
Definition at line 5748 of file CLI11.hpp.
{
        auto iterator = std::find(std::begin(excludes_), std::end(excludes_), opt);
        if (iterator == std::end(excludes_)) {
            return false;
        }
        excludes_.erase(iterator);
        return true;
    }
remove_needs()
bool Option::remove_needs (Option * opt) inline
Remove needs link from an option. Returns true if the option really was in the needs list.
Definition at line 5723 of file CLI11.hpp.
{
        auto iterator = std::find(std::begin(needs_), std::end(needs_), opt);
        if (iterator == std::end(needs_)) {
            return false;
        }
        needs_.erase(iterator);
        return true;
    }
Referenced by net::config::ConfigPhysicalSocketClient::setReconnect(), and net::config::ConfigPhysicalSocket::setRetry().
results() [1/2]
const results_t & Option::results () const inline
Get the current complete results set.
Definition at line 5454 of file CLI11.hpp.
{
            return results_;
        }
results() [2/2]
template<typename T > void Option::results (T & output) const inline
Get the results as a specified type.
Definition at line 5463 of file CLI11.hpp.
{
            bool retval = false;
            if (current_option_state_ >= option_state::reduced || (results_.size() == 1 && validators_.empty())) {
                const results_t& res = (proc_results_.empty()) ? results_ : proc_results_;
                retval = detail::lexical_conversion<T, T>(res, output);
            } else {
                results_t res;
                if (results_.empty()) {
                    if (!default_str_.empty()) {
                        // _add_results takes an rvalue only
                        _add_result(std::string(default_str_), res);
                        _validate_results(res);
                        results_t extra;
                        _reduce_results(extra, res);
                        if (!extra.empty()) {
                            res = std::move(extra);
                        }
                    } else {
                        res.emplace_back();
                    }
                } else {
                    res = reduced_results();
                }
                retval = detail::lexical_conversion<T, T>(res, output);
            }
            if (!retval) {
                throw ConversionError(get_name(), results_);
            }
        }
References default_str_.
run_callback()
void Option::run_callback () inline
Process the callback.
Definition at line 5865 of file CLI11.hpp.
{
        if (force_callback_ && results_.empty()) {
            add_result(default_str_);
        }
        if (current_option_state_ == option_state::parsing) {
            _validate_results(results_);
            current_option_state_ = option_state::validated;
        }
        if (current_option_state_ < option_state::reduced) {
            _reduce_results(proc_results_, results_);
            current_option_state_ = option_state::reduced;
        }
        if (current_option_state_ >= option_state::reduced) {
            current_option_state_ = option_state::callback_run;
            if (!(callback_)) {
                return;
            }
            const results_t& send_results = proc_results_.empty() ? results_ : proc_results_;
            bool const local_result = callback_(send_results);
            if (!local_result)
                throw ConversionError(get_name(), results_);
        }
    }
References add_result(), callback_run, current_option_state_, default_str_, parsing, reduced, and validated.
Referenced by App::_parse_single_config(), default_val(), and App::version().
run_callback_for_default()
Option * Option::run_callback_for_default (bool value = true) inline
Set the value of run_callback_for_default which controls whether the callback function should be called to set the default This is controlled automatically but could be manipulated by the user.
Definition at line 5140 of file CLI11.hpp.
{
            run_callback_for_default_ = value;
            return this;
        }
References run_callback_for_default_.
Referenced by App::add_option(), and App::add_option_no_stream().
transform() [1/2]
Option * Option::transform (const std::function< std::string(std::string)> & func, std::string transform_description = "", std::string transform_name = "") inline
Adds a Validator-like function that can change result.
Definition at line 5680 of file CLI11.hpp.
{
        validators_.insert(validators_.begin(),
                           Validator(
                               [func](std::string& val) {
                                   val = func(val);
                                   return std::string{};
                               },
                               std::move(transform_description),
                               std::move(transform_name)));
        return this;
    }
transform() [2/2]
Option * Option::transform (Validator Validator, const std::string & Validator_name = "") inline
Adds a transforming Validator with a built in type name.
Definition at line 5672 of file CLI11.hpp.
{
        validators_.insert(validators_.begin(), std::move(Validator));
        if (!Validator_name.empty())
            validators_.front().name(Validator_name);
        return this;
    }
trigger_on_parse()
Option * Option::trigger_on_parse (bool value = true) inline
Set the value of trigger_on_parse which specifies that the option callback should be triggered on every parse.
Definition at line 5119 of file CLI11.hpp.
{
            trigger_on_result_ = value;
            return this;
        }
References trigger_on_result_.
Referenced by net::config::ConfigInstance::ConfigInstance().
type_name()
Option * Option::type_name (std::string typeval) inline
Set a custom option typestring.
Definition at line 5517 of file CLI11.hpp.
{
            type_name_fn([typeval]() {
                return typeval;
            });
            return this;
        }
References type_name_fn().
Referenced by App::add_option(), App::add_option_function(), App::add_option_no_stream(), retire_option(), and retire_option().
type_name_fn()
Option * Option::type_name_fn (std::function< std::string()> typefun) inline
Set the type function to run when displayed on this option.
Definition at line 5511 of file CLI11.hpp.
{
            type_name_ = std::move(typefun);
            return this;
        }
Referenced by type_name().
type_size() [1/2]
Option * Option::type_size (int option_type_size) inline
Set a custom option size.
Definition at line 6019 of file CLI11.hpp.
{
        if (option_type_size < 0) {
            // this section is included for backwards compatibility
            type_size_max_ = -option_type_size;
            type_size_min_ = -option_type_size;
            expected_max_ = detail::expected_max_vector_size;
        } else {
            type_size_max_ = option_type_size;
            if (type_size_max_ < detail::expected_max_vector_size) {
                type_size_min_ = option_type_size;
            } else {
                inject_separator_ = true;
            }
            if (type_size_max_ == 0)
                required_ = false;
        }
        return this;
    }
References expected_max_, CLI::detail::expected_max_vector_size, inject_separator_, type_size_max_, and type_size_min_.
type_size() [2/2]
Option * Option::type_size (int option_type_size_min, int option_type_size_max) inline
Set a custom option type size range.
Definition at line 6038 of file CLI11.hpp.
{
        if (option_type_size_min < 0 || option_type_size_max < 0) {
            // this section is included for backwards compatibility
            expected_max_ = detail::expected_max_vector_size;
            option_type_size_min = (std::abs)(option_type_size_min);
            option_type_size_max = (std::abs)(option_type_size_max);
        }
        if (option_type_size_min > option_type_size_max) {
            type_size_max_ = option_type_size_min;
            type_size_min_ = option_type_size_max;
        } else {
            type_size_min_ = option_type_size_min;
            type_size_max_ = option_type_size_max;
        }
        if (type_size_max_ == 0) {
            required_ = false;
        }
        if (type_size_max_ >= detail::expected_max_vector_size) {
            inject_separator_ = true;
        }
        return this;
    }
References expected_max_, CLI::detail::expected_max_vector_size, inject_separator_, type_size_max_, and type_size_min_.
Referenced by retire_option().
Member Data Documentation
allow_extra_args_
bool Option::allow_extra_args_ {false} protected
Specify that extra args beyond type_size_max should be allowed.
Definition at line 5049 of file CLI11.hpp.
{false};
Referenced by _add_result(), allow_extra_args(), expected(), and get_allow_extra_args().
App
friend Option::App private
Definition at line 4949 of file CLI11.hpp.
callback_
callback_t Option::callback_ {} protected
Options store a callback to do all the work.
Definition at line 5029 of file CLI11.hpp.
{};
current_option_state_
option_state Option::current_option_state_ {option_state::parsing} protected
Whether the callback has run (needed for INI parsing)
Definition at line 5047 of file CLI11.hpp.
{option_state::parsing};
Referenced by add_result(), add_result(), add_result(), clear(), default_val(), get_callback_run(), multi_option_policy(), reduced_results(), and run_callback().
default_flag_values_
std::vector<std::pair<std::string, std::string> > Option::default_flag_values_ {} protected
A list of the flag names with the appropriate default value, the first part of the pair should be duplicates of what is in snames or lnames but will trigger a particular response on a flag
Definition at line 4963 of file CLI11.hpp.
{};
default_function_
std::function<std::string()> Option::default_function_ {} protected
Run this function to capture a default (ignore if empty)
Definition at line 4995 of file CLI11.hpp.
{};
default_str_
std::string Option::default_str_ {} protected
A human readable default value, either manually set, captured, or captured by default.
Definition at line 4982 of file CLI11.hpp.
{};
Referenced by default_str(), default_val(), get_default_str(), results(), and run_callback().
description_
std::string Option::description_ {} protected
The description for help strings.
Definition at line 4979 of file CLI11.hpp.
{};
Referenced by description(), get_description(), has_description(), and Option().
envname_
std::string Option::envname_ {} protected
If given, check the environment for this option.
Definition at line 4972 of file CLI11.hpp.
{};
Referenced by check_name(), envname(), get_envname(), and get_single_name().
excludes_
std::set<Option*> Option::excludes_ {} protected
A list of options that are excluded with this option.
Definition at line 5019 of file CLI11.hpp.
{};
expected_max_
int Option::expected_max_ {1} protected
The maximum number of expected values.
Definition at line 5010 of file CLI11.hpp.
{1};
Referenced by expected(), expected(), get_expected_max(), get_items_expected_max(), multi_option_policy(), type_size(), and type_size().
expected_min_
int Option::expected_min_ {1} protected
The minimum number of expected values.
Definition at line 5008 of file CLI11.hpp.
{1};
Referenced by _validate(), expected(), expected(), get_expected(), get_expected_min(), get_items_expected_min(), and multi_option_policy().
flag_like_
bool Option::flag_like_ {false} protected
Specify that the option should act like a flag vs regular option.
Definition at line 5051 of file CLI11.hpp.
{false};
Referenced by expected(), and get_flag_value().
fnames_
std::vector<std::string> Option::fnames_ {} protected
a list of flag names with specified default values;
Definition at line 4966 of file CLI11.hpp.
{};
force_callback_
bool Option::force_callback_ {false} protected
flag indicating that the option should force the callback regardless if any results present
Definition at line 5059 of file CLI11.hpp.
{false};
Referenced by force_callback(), get_force_callback(), and operator bool().
inject_separator_
bool Option::inject_separator_ {false} protected
flag indicating a separator needs to be injected after each argument call
Definition at line 5055 of file CLI11.hpp.
{false};
Referenced by get_inject_separator(), inject_separator(), type_size(), and type_size().
lnames_
std::vector<std::string> Option::lnames_ {} protected
A list of the long names (--long) without the leading dashes.
Definition at line 4959 of file CLI11.hpp.
{};
needs_
std::set<Option*> Option::needs_ {} protected
A list of options that are required with this option.
Definition at line 5016 of file CLI11.hpp.
{};
option_text_
std::string Option::option_text_ {} protected
If given, replace the text that describes the option type and usage in the help text.
Definition at line 4985 of file CLI11.hpp.
{};
Referenced by get_option_text(), and option_text().
parent_
App* Option::parent_ {nullptr} protected
link back up to the parent App for fallthrough
Definition at line 5026 of file CLI11.hpp.
{nullptr};
Referenced by excludes(), ignore_case(), ignore_underscore(), needs(), and Option().
pname_
std::string Option::pname_ {} protected
A positional name.
Definition at line 4969 of file CLI11.hpp.
{};
Referenced by check_name(), get_name(), get_positional(), and get_single_name().
proc_results_
results_t Option::proc_results_ {} protected
results after reduction
Definition at line 5038 of file CLI11.hpp.
{};
results_
results_t Option::results_ {} protected
complete Results of parsing
Definition at line 5036 of file CLI11.hpp.
{};
run_callback_for_default_
bool Option::run_callback_for_default_ {false} protected
Control option to run the callback to set the default.
Definition at line 5053 of file CLI11.hpp.
{false};
Referenced by default_val(), get_run_callback_for_default(), and run_callback_for_default().
snames_
std::vector<std::string> Option::snames_ {} protected
A list of the short names (-a) without the leading dashes.
Definition at line 4956 of file CLI11.hpp.
{};
trigger_on_result_
bool Option::trigger_on_result_ {false} protected
flag indicating that the option should trigger the validation and callback chain on each result when loaded
Definition at line 5057 of file CLI11.hpp.
{false};
Referenced by default_val(), get_trigger_on_parse(), and trigger_on_parse().
type_name_
std::function<std::string()> Option::type_name_ protected
Initial value:
{[]() {
            return std::string();
        }}
A human readable type value, set when App creates this
This is a lambda function so "types" can be dynamic, such as when a set prints its contents.
Definition at line 4990 of file CLI11.hpp.
                                           {[]() {
            return std::string();
        }};
type_size_max_
int Option::type_size_max_ {1} protected
The number of arguments that make up one option. max is the nominal type size, min is the minimum number of strings
Definition at line 5003 of file CLI11.hpp.
{1};
Referenced by _validate_results(), get_items_expected_max(), get_type_size_max(), type_size(), and type_size().
type_size_min_
int Option::type_size_min_ {1} protected
The minimum number of arguments an option should be expecting.
Definition at line 5005 of file CLI11.hpp.
{1};
Referenced by get_items_expected_min(), get_type_size(), get_type_size_min(), type_size(), and type_size().
validators_
std::vector<Validator> Option::validators_ {} protected
A list of Validators to run on each value parsed.
Definition at line 5013 of file CLI11.hpp.
{};
The documentation for this class was generated from the following file:
src/utils/CLI11.hpp