SNode.C: web::websocket::SubProtocol< SocketContextUpgradeT > Class Template Reference
web::websocket::SubProtocol< SocketContextUpgradeT > Class Template Reference abstract
#include <SubProtocol.h>
Public Member Functions
SubProtocol (SubProtocol &)=delete
SubProtocol (SubProtocol &&)=delete
SubProtocol & operator= (SubProtocol &)=delete
SubProtocol & operator= (SubProtocol &&)=delete
void sendMessage (const char *message, std::size_t messageLength) const
void sendMessage (const std::string &message) const
void sendMessageStart (const char *message, std::size_t messageLength) const
void sendMessageStart (const std::string &message) const
void sendMessageFrame (const char *message, std::size_t messageLength) const
void sendMessageFrame (const std::string &message) const
void sendMessageEnd (const char *message, std::size_t messageLength) const
void sendMessageEnd (const std::string &message) const
void sendPing (const char *reason=nullptr, std::size_t reasonLength=0) const
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
const std::string & getName ()
core::socket::stream::SocketConnection * getSocketConnection () const
std::size_t getPayloadTotalSent () const
std::size_t getPayloadTotalRead () const
std::string getOnlineSince () const
std::string getOnlineDuration () const
Protected Member Functions
SubProtocol (SubProtocolContext *subProtocolContext, const std::string &name, int pingInterval=60, int maxFlyingPings=3)
virtual ~SubProtocol ()
Protected Attributes
SubProtocolContext * subProtocolContext
Private Types
using SocketContextUpgrade = SocketContextUpgradeT
Private Member Functions
void attach ()
void detach ()
virtual void onConnected ()=0
virtual void onDisconnected ()=0
virtual bool onSignal (int sig)=0
virtual void onMessageStart (int opCode)=0
virtual void onMessageData (const char *chunk, std::size_t chunkLen)=0
virtual void onMessageEnd ()=0
virtual void onMessageError (uint16_t errnum)=0
virtual void onPongReceived ()
Private Attributes
const std::string name
core::timer::Timer pingTimer
int flyingPings = 0
Friends
template<typename SubProtocolT , typename RequestT , typename ResponseT >
class web::websocket::SocketContextUpgrade
Detailed Description
template<typename SocketContextUpgradeT>
class web::websocket::SubProtocol< SocketContextUpgradeT >
Definition at line 68 of file SubProtocol.h.
Member Typedef Documentation
SocketContextUpgrade
template<typename SocketContextUpgradeT > using web::websocket::SubProtocol< SocketContextUpgradeT >::SocketContextUpgrade = SocketContextUpgradeT private
Definition at line 77 of file SubProtocol.h.
Constructor & Destructor Documentation
SubProtocol() [1/3]
template<typename SocketContextUpgradeT > web::websocket::SubProtocol< SocketContextUpgradeT >::SubProtocol (SubProtocol< SocketContextUpgradeT > &) delete
SubProtocol() [2/3]
template<typename SocketContextUpgradeT > web::websocket::SubProtocol< SocketContextUpgradeT >::SubProtocol (SubProtocol< SocketContextUpgradeT > &&) delete
SubProtocol() [3/3]
template<typename SocketContextUpgrade > web::websocket::SubProtocol< SocketContextUpgrade >::SubProtocol (SubProtocolContext * subProtocolContext, const std::string & name, int pingInterval = 60, int maxFlyingPings = 3) protected
Definition at line 59 of file SubProtocol.hpp.
        : name(name)
        , subProtocolContext(subProtocolContext) {
        if (pingInterval > 0) {
            pingTimer = core::timer::Timer::intervalTimer(
                [this, maxFlyingPings](const std::function<void()>& stop) {
                    if (flyingPings < maxFlyingPings) {
                        sendPing();
                        flyingPings++;
                    } else {
                        LOG(WARNING) << this->subProtocolContext->getSocketConnection()->getConnectionName() << " Subprotocol '"
                                     << this->name << "': MaxFlyingPings exceeded - closing";
                        sendClose();
                        stop();
                    }
                },
                pingInterval);
        }
        getSocketConnection()->setTimeout(0);
    }
References web::websocket::SubProtocol< SocketContextUpgradeT >::flyingPings, core::socket::stream::SocketConnection::getConnectionName(), web::websocket::SubProtocolContext::getSocketConnection(), web::websocket::SubProtocol< SocketContextUpgradeT >::name, web::websocket::SubProtocol< SocketContextUpgradeT >::pingTimer, web::websocket::SubProtocol< SocketContextUpgradeT >::sendClose(), web::websocket::SubProtocol< SocketContextUpgradeT >::sendPing(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
Referenced by web::websocket::server::SubProtocol::SubProtocol().
~SubProtocol()
template<typename SocketContextUpgrade > web::websocket::SubProtocol< SocketContextUpgrade >::~SubProtocol () protected virtual
Reimplemented in web::websocket::client::SubProtocol, and web::websocket::server::SubProtocol.
Definition at line 86 of file SubProtocol.hpp.
{
        pingTimer.cancel();
    }
Member Function Documentation
attach()
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::attach () private
Definition at line 143 of file SubProtocol.hpp.
{
        LOG(DEBUG) << subProtocolContext->getSocketConnection()->getConnectionName() << " Subprotocol '" << name << "': attach";
        onConnected();
    }
References core::socket::stream::SocketConnection::getConnectionName(), web::websocket::SubProtocolContext::getSocketConnection(), web::websocket::SubProtocol< SocketContextUpgradeT >::name, web::websocket::SubProtocol< SocketContextUpgradeT >::onConnected(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
detach()
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::detach () private
Definition at line 150 of file SubProtocol.hpp.
{
        onDisconnected();
        LOG(DEBUG) << subProtocolContext->getSocketConnection()->getConnectionName() << " Subprotocol '" << name << "': detached";
        LOG(DEBUG) << "       Total Payload sent: " << getPayloadTotalSent();
        LOG(DEBUG) << "  Total Payload processed: " << getPayloadTotalRead();
    }
References core::socket::stream::SocketConnection::getConnectionName(), web::websocket::SubProtocol< SocketContextUpgradeT >::getPayloadTotalRead(), web::websocket::SubProtocol< SocketContextUpgradeT >::getPayloadTotalSent(), web::websocket::SubProtocolContext::getSocketConnection(), web::websocket::SubProtocol< SocketContextUpgradeT >::name, web::websocket::SubProtocol< SocketContextUpgradeT >::onDisconnected(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
getName()
template<typename SocketContextUpgrade > const std::string & web::websocket::SubProtocol< SocketContextUpgrade >::getName ()
Definition at line 167 of file SubProtocol.hpp.
{
        return name;
    }
References web::websocket::SubProtocol< SocketContextUpgradeT >::name.
Referenced by web::websocket::server::GroupsManager::subscribe().
getOnlineDuration()
template<typename SocketContextUpgrade > std::string web::websocket::SubProtocol< SocketContextUpgrade >::getOnlineDuration () const
Definition at line 192 of file SubProtocol.hpp.
{
        return subProtocolContext->getOnlineDuration();
    }
References web::websocket::SubProtocolContext::getOnlineDuration(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
getOnlineSince()
template<typename SocketContextUpgrade > std::string web::websocket::SubProtocol< SocketContextUpgrade >::getOnlineSince () const
Definition at line 187 of file SubProtocol.hpp.
{
        return subProtocolContext->getOnlineSince();
    }
References web::websocket::SubProtocolContext::getOnlineSince(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
getPayloadTotalRead()
template<typename SocketContextUpgrade > std::size_t web::websocket::SubProtocol< SocketContextUpgrade >::getPayloadTotalRead () const
Definition at line 182 of file SubProtocol.hpp.
{
        return subProtocolContext->getPayloadTotalRead();
    }
References web::websocket::SubProtocolContext::getPayloadTotalRead(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::detach().
getPayloadTotalSent()
template<typename SocketContextUpgrade > std::size_t web::websocket::SubProtocol< SocketContextUpgrade >::getPayloadTotalSent () const
Definition at line 177 of file SubProtocol.hpp.
{
        return subProtocolContext->getPayloadTotalSent();
    }
References web::websocket::SubProtocolContext::getPayloadTotalSent(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::detach().
getSocketConnection()
template<typename SocketContextUpgrade > core::socket::stream::SocketConnection * web::websocket::SubProtocol< SocketContextUpgrade >::getSocketConnection () const
Definition at line 172 of file SubProtocol.hpp.
{
        return subProtocolContext->getSocketConnection();
    }
References web::websocket::SubProtocolContext::getSocketConnection(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
onConnected()
template<typename SocketContextUpgradeT > virtual void web::websocket::SubProtocol< SocketContextUpgradeT >::onConnected () private pure virtual
Implemented in apps::websocket::subprotocol::echo::client::Echo, and apps::websocket::subprotocol::echo::server::Echo.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::attach().
onDisconnected()
template<typename SocketContextUpgradeT > virtual void web::websocket::SubProtocol< SocketContextUpgradeT >::onDisconnected () private pure virtual
Implemented in apps::websocket::subprotocol::echo::client::Echo, and apps::websocket::subprotocol::echo::server::Echo.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::detach().
onMessageData()
template<typename SocketContextUpgradeT > virtual void web::websocket::SubProtocol< SocketContextUpgradeT >::onMessageData (const char * chunk, std::size_t chunkLen) private pure virtual
Implemented in apps::websocket::subprotocol::echo::client::Echo, and apps::websocket::subprotocol::echo::server::Echo.
onMessageEnd()
template<typename SocketContextUpgradeT > virtual void web::websocket::SubProtocol< SocketContextUpgradeT >::onMessageEnd () private pure virtual
Implemented in apps::websocket::subprotocol::echo::client::Echo, and apps::websocket::subprotocol::echo::server::Echo.
onMessageError()
template<typename SocketContextUpgradeT > virtual void web::websocket::SubProtocol< SocketContextUpgradeT >::onMessageError (uint16_t errnum) private pure virtual
Implemented in apps::websocket::subprotocol::echo::client::Echo, and apps::websocket::subprotocol::echo::server::Echo.
onMessageStart()
template<typename SocketContextUpgradeT > virtual void web::websocket::SubProtocol< SocketContextUpgradeT >::onMessageStart (int opCode) private pure virtual
Implemented in apps::websocket::subprotocol::echo::client::Echo, and apps::websocket::subprotocol::echo::server::Echo.
onPongReceived()
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::onPongReceived () private virtual
Definition at line 160 of file SubProtocol.hpp.
{
        LOG(DEBUG) << subProtocolContext->getSocketConnection()->getConnectionName() << " Subprotocol '" << name << "': Pong received";
        flyingPings = 0;
    }
References web::websocket::SubProtocol< SocketContextUpgradeT >::flyingPings, core::socket::stream::SocketConnection::getConnectionName(), web::websocket::SubProtocolContext::getSocketConnection(), web::websocket::SubProtocol< SocketContextUpgradeT >::name, and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
onSignal()
template<typename SocketContextUpgradeT > virtual bool web::websocket::SubProtocol< SocketContextUpgradeT >::onSignal (int sig) private pure virtual
Implemented in apps::websocket::subprotocol::echo::client::Echo, and apps::websocket::subprotocol::echo::server::Echo.
operator=() [1/2]
template<typename SocketContextUpgradeT > SubProtocol & web::websocket::SubProtocol< SocketContextUpgradeT >::operator= (SubProtocol< SocketContextUpgradeT > &&) delete
operator=() [2/2]
template<typename SocketContextUpgradeT > SubProtocol & web::websocket::SubProtocol< SocketContextUpgradeT >::operator= (SubProtocol< SocketContextUpgradeT > &) delete
sendClose()
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::sendClose (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0)
Definition at line 138 of file SubProtocol.hpp.
{
        subProtocolContext->sendClose(statusCode, reason, reasonLength);
    }
References web::websocket::SubProtocolContext::sendClose(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
Referenced by apps::websocket::subprotocol::echo::client::Echo::onSignal(), apps::websocket::subprotocol::echo::server::Echo::onSignal(), and web::websocket::SubProtocol< SocketContextUpgradeT >::SubProtocol().
sendMessage() [1/2]
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::sendMessage (const char * message, std::size_t messageLength) const
Definition at line 91 of file SubProtocol.hpp.
{
        subProtocolContext->sendMessage(2, message, messageLength);
    }
Referenced by web::websocket::server::GroupsManager::sendBroadcast().
sendMessage() [2/2]
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::sendMessage (const std::string & message) const
Definition at line 96 of file SubProtocol.hpp.
{
        subProtocolContext->sendMessage(1, message.data(), message.length());
    }
References web::websocket::SubProtocolContext::sendMessage(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
Referenced by apps::websocket::subprotocol::echo::server::Echo::onConnected(), and web::websocket::server::GroupsManager::sendBroadcast().
sendMessageEnd() [1/2]
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::sendMessageEnd (const char * message, std::size_t messageLength) const
Definition at line 121 of file SubProtocol.hpp.
{
        subProtocolContext->sendMessageEnd(message, messageLength);
    }
References web::websocket::SubProtocolContext::sendMessageEnd(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
Referenced by web::websocket::server::GroupsManager::sendBroadcastEnd().
sendMessageEnd() [2/2]
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::sendMessageEnd (const std::string & message) const
Definition at line 126 of file SubProtocol.hpp.
{
        sendMessageEnd(message.data(), message.length());
    }
sendMessageFrame() [1/2]
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::sendMessageFrame (const char * message, std::size_t messageLength) const
Definition at line 111 of file SubProtocol.hpp.
{
        subProtocolContext->sendMessageFrame(message, messageLength);
    }
References web::websocket::SubProtocolContext::sendMessageFrame(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
Referenced by web::websocket::server::GroupsManager::sendBroadcastFrame().
sendMessageFrame() [2/2]
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::sendMessageFrame (const std::string & message) const
Definition at line 116 of file SubProtocol.hpp.
{
        sendMessageFrame(message.data(), message.length());
    }
sendMessageStart() [1/2]
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::sendMessageStart (const char * message, std::size_t messageLength) const
Definition at line 101 of file SubProtocol.hpp.
{
        subProtocolContext->sendMessageStart(2, message, messageLength);
    }
References web::websocket::SubProtocolContext::sendMessageStart(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
Referenced by web::websocket::server::GroupsManager::sendBroadcastStart().
sendMessageStart() [2/2]
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::sendMessageStart (const std::string & message) const
Definition at line 106 of file SubProtocol.hpp.
{
        subProtocolContext->sendMessageStart(1, message.data(), message.length());
    }
References web::websocket::SubProtocolContext::sendMessageStart(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
sendPing()
template<typename SocketContextUpgrade > void web::websocket::SubProtocol< SocketContextUpgrade >::sendPing (const char * reason = nullptr, std::size_t reasonLength = 0) const
Definition at line 131 of file SubProtocol.hpp.
{
        LOG(DEBUG) << subProtocolContext->getSocketConnection()->getConnectionName() << " Subprotocol '" << name << "': Ping sent";
        subProtocolContext->sendPing(reason, reasonLength);
    }
References core::socket::stream::SocketConnection::getConnectionName(), web::websocket::SubProtocolContext::getSocketConnection(), web::websocket::SubProtocol< SocketContextUpgradeT >::name, web::websocket::SubProtocolContext::sendPing(), and web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::SubProtocol().
Friends And Related Symbol Documentation
web::websocket::SocketContextUpgrade
template<typename SocketContextUpgradeT > template<typename SubProtocolT , typename RequestT , typename ResponseT > friend class web::websocket::SocketContextUpgrade friend
Definition at line 133 of file SubProtocol.h.
Member Data Documentation
flyingPings
template<typename SocketContextUpgradeT > int web::websocket::SubProtocol< SocketContextUpgradeT >::flyingPings = 0 private
Definition at line 130 of file SubProtocol.h.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::onPongReceived(), and web::websocket::SubProtocol< SocketContextUpgradeT >::SubProtocol().
name
template<typename SocketContextUpgradeT > const std::string web::websocket::SubProtocol< SocketContextUpgradeT >::name private
Definition at line 123 of file SubProtocol.h.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::attach(), web::websocket::SubProtocol< SocketContextUpgradeT >::detach(), web::websocket::SubProtocol< SocketContextUpgradeT >::getName(), web::websocket::SubProtocol< SocketContextUpgradeT >::onPongReceived(), web::websocket::SubProtocol< SocketContextUpgradeT >::sendPing(), and web::websocket::SubProtocol< SocketContextUpgradeT >::SubProtocol().
pingTimer
template<typename SocketContextUpgradeT > core::timer::Timer web::websocket::SubProtocol< SocketContextUpgradeT >::pingTimer private
Definition at line 129 of file SubProtocol.h.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::SubProtocol().
subProtocolContext
template<typename SocketContextUpgradeT > SubProtocolContext* web::websocket::SubProtocol< SocketContextUpgradeT >::subProtocolContext protected
Definition at line 126 of file SubProtocol.h.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::attach(), web::websocket::SubProtocol< SocketContextUpgradeT >::detach(), web::websocket::SubProtocol< SocketContextUpgradeT >::getOnlineDuration(), web::websocket::SubProtocol< SocketContextUpgradeT >::getOnlineSince(), web::websocket::SubProtocol< SocketContextUpgradeT >::getPayloadTotalRead(), web::websocket::SubProtocol< SocketContextUpgradeT >::getPayloadTotalSent(), web::websocket::SubProtocol< SocketContextUpgradeT >::getSocketConnection(), web::websocket::SubProtocol< SocketContextUpgradeT >::onPongReceived(), web::websocket::SubProtocol< SocketContextUpgradeT >::sendClose(), web::websocket::SubProtocol< SocketContextUpgradeT >::sendMessage(), web::websocket::SubProtocol< SocketContextUpgradeT >::sendMessageEnd(), web::websocket::SubProtocol< SocketContextUpgradeT >::sendMessageFrame(), web::websocket::SubProtocol< SocketContextUpgradeT >::sendMessageStart(), web::websocket::SubProtocol< SocketContextUpgradeT >::sendMessageStart(), web::websocket::SubProtocol< SocketContextUpgradeT >::sendPing(), and web::websocket::SubProtocol< SocketContextUpgradeT >::SubProtocol().
The documentation for this class was generated from the following files:
web/websocket/SubProtocol.h
web/websocket/SubProtocol.hpp