SNode.C: iot::mqtt::packets::Pubrel Class Reference
iot::mqtt::packets::Pubrel Class Reference
#include <Pubrel.h>
Public Member Functions
Pubrel ()
Pubrel (uint16_t packetIdentifier)
uint16_t getPacketIdentifier () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type, const std::string &name)
ControlPacket (const ControlPacket &)=default
ControlPacket (ControlPacket &&)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
ControlPacket & operator= (ControlPacket &&)=default
std::vector< char > serialize () const
const std::string & getName () const
Protected Attributes
iot::mqtt::types::UInt16 packetIdentifier
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t flags = 0
Private Member Functions
std::vector< char > serializeVP () const override
Additional Inherited Members
Protected Member Functions inherited from iot::mqtt::ControlPacket
uint8_t getType () const
uint8_t getFlags () const
Detailed Description
Definition at line 56 of file Pubrel.h.
Constructor & Destructor Documentation
Pubrel() [1/2]
iot::mqtt::packets::Pubrel::Pubrel ()
Definition at line 53 of file Pubrel.cpp.
        : iot::mqtt::ControlPacket(MQTT_PUBREL, "PUBREL") {
    }
References iot::mqtt::ControlPacket::ControlPacket().
Referenced by Pubrel().
Pubrel() [2/2]
iot::mqtt::packets::Pubrel::Pubrel (uint16_t packetIdentifier) explicit
Definition at line 57 of file Pubrel.cpp.
        : Pubrel() {
        this->packetIdentifier = packetIdentifier;
    }
References iot::mqtt::types::UInt16::operator=(), packetIdentifier, and Pubrel().
Referenced by iot::mqtt::Mqtt::initSession(), and iot::mqtt::Mqtt::sendPubrel().
Member Function Documentation
getPacketIdentifier()
uint16_t iot::mqtt::packets::Pubrel::getPacketIdentifier () const
Definition at line 66 of file Pubrel.cpp.
{
        return packetIdentifier;
    }
References packetIdentifier.
Referenced by iot::mqtt::Mqtt::_onPubrel().
serializeVP()
std::vector< char > iot::mqtt::packets::Pubrel::serializeVP () const override private virtual
Implements iot::mqtt::ControlPacket.
Definition at line 62 of file Pubrel.cpp.
{
        return std::vector<char>(packetIdentifier.serialize());
    }
References packetIdentifier, and iot::mqtt::types::TypeBase< ValueTypeT >::serialize().
Member Data Documentation
packetIdentifier
iot::mqtt::types::UInt16 iot::mqtt::packets::Pubrel::packetIdentifier protected
Definition at line 68 of file Pubrel.h.
Referenced by iot::mqtt::client::packets::Pubrel::deserializeVP(), iot::mqtt::server::packets::Pubrel::deserializeVP(), getPacketIdentifier(), Pubrel(), and serializeVP().
The documentation for this class was generated from the following files:
iot/mqtt/packets/Pubrel.h
iot/mqtt/packets/Pubrel.cpp