SNode.C: iot::mqtt::client::Mqtt Class Reference
iot::mqtt::client::Mqtt Class Reference
#include <Mqtt.h>
Public Types
using Super = iot::mqtt::Mqtt
Public Member Functions
Mqtt (const std::string &clientId)
~Mqtt () override
void sendConnect (uint16_t keepAlive, const std::string &clientId, bool cleanSession, const std::string &willTopic, const std::string &willMessage, uint8_t willQoS, bool willRetain, const std::string &username, const std::string &password, bool reflect)
void sendSubscribe (std::list< Topic > &topics)
void sendUnsubscribe (const std::list< std::string > &topics)
void sendPingreq () const
void sendDisconnect () const
virtual void onConnected ()
virtual void onDisconnected ()
core::socket::stream::SocketConnection * getSocketConnection ()
void sendPublish (const std::string &topic, const std::string &message, uint8_t qoS, bool retain)
void sendPuback (uint16_t packetIdentifier) const
void sendPubrec (uint16_t packetIdentifier) const
void sendPubrel (uint16_t packetIdentifier) const
void sendPubcomp (uint16_t packetIdentifier) const
Static Public Member Functions
static std::string dataToHexString (const std::vector< char > &data)
static std::string stringToHexString (const std::string &data)
Protected Member Functions
bool onSignal (int sig) override
void initSession (Session *session, utils::Timeval keepAlive)
virtual void onPublish (const iot::mqtt::packets::Publish &publish)
virtual void onPuback (const iot::mqtt::packets::Puback &puback)
virtual void onPubrec (const iot::mqtt::packets::Pubrec &pubrec)
virtual void onPubrel (const iot::mqtt::packets::Pubrel &pubrel)
virtual void onPubcomp (const iot::mqtt::packets::Pubcomp &pubcomp)
bool _onPublish (const iot::mqtt::packets::Publish &publish)
void _onPuback (const iot::mqtt::packets::Puback &puback)
void _onPubrec (const iot::mqtt::packets::Pubrec &pubrec)
void _onPubrel (const iot::mqtt::packets::Pubrel &pubrel)
void _onPubcomp (const iot::mqtt::packets::Pubcomp &pubcomp)
uint16_t getPacketIdentifier ()
void send (const iot::mqtt::ControlPacket &controlPacket) const
void printVP (const iot::mqtt::ControlPacket &packet) const
Static Protected Member Functions
static void printFixedHeader (const iot::mqtt::FixedHeader &fixedHeader)
Protected Attributes
std::string clientId
MqttContext * mqttContext = nullptr
Private Member Functions
iot::mqtt::ControlPacketDeserializer * createControlPacketDeserializer (iot::mqtt::FixedHeader &fixedHeader) final
void deliverPacket (iot::mqtt::ControlPacketDeserializer *controlPacketDeserializer) override
virtual void onConnack (const iot::mqtt::packets::Connack &connack)
virtual void onSuback (const iot::mqtt::packets::Suback &suback)
virtual void onUnsuback (const iot::mqtt::packets::Unsuback &unsuback)
virtual void onPingresp (const iot::mqtt::packets::Pingresp &pingresp)
void _onConnack (const iot::mqtt::client::packets::Connack &connack)
void _onPublish (const iot::mqtt::client::packets::Publish &publish)
void _onSuback (const iot::mqtt::client::packets::Suback &suback)
void _onUnsuback (const iot::mqtt::client::packets::Unsuback &unsuback)
void _onPingresp (const iot::mqtt::client::packets::Pingresp &pingresp)
std::size_t onReceivedFromPeer ()
void setMqttContext (MqttContext *mqttContext)
void send (const std::vector< char > &data) const
Private Attributes
uint16_t keepAlive = 0
std::string sessionStoreFileName
iot::mqtt::Session session
core::timer::Timer pingTimer
iot::mqtt::FixedHeader fixedHeader
iot::mqtt::ControlPacketDeserializer * controlPacketDeserializer = nullptr
uint16_t _packetIdentifier = 0
core::timer::Timer keepAliveTimer
int state = 0
Friends
class iot::mqtt::client::packets::Connack
class iot::mqtt::client::packets::Suback
class iot::mqtt::client::packets::Unsuback
class iot::mqtt::client::packets::Pingresp
class iot::mqtt::client::packets::Publish
class iot::mqtt::client::packets::Pubcomp
class iot::mqtt::client::packets::Pubrec
class iot::mqtt::client::packets::Puback
class iot::mqtt::client::packets::Pubrel
Detailed Description
Definition at line 62 of file Mqtt.h.
Member Typedef Documentation
Super
using iot::mqtt::client::Mqtt::Super = iot::mqtt::Mqtt
Definition at line 64 of file Mqtt.h.
Constructor & Destructor Documentation
Mqtt()
iot::mqtt::client::Mqtt::Mqtt (const std::string & clientId) explicit
Definition at line 57 of file Mqtt.cpp.
        : Super(clientId)
        , sessionStoreFileName((getenv("MQTT_SESSION_STORE") != nullptr) ? getenv("MQTT_SESSION_STORE") : "") { // NOLINT
        if (!sessionStoreFileName.empty()) {
            std::ifstream sessionStoreFile(sessionStoreFileName);
            if (sessionStoreFile.is_open()) {
                try {
                    nlohmann::json sessionStoreJson;
                    sessionStoreFile >> sessionStoreJson;
                    session.fromJson(sessionStoreJson);
                    LOG(DEBUG) << "MQTT Client:   ... Persistent session data loaded successfull";
                } catch (const nlohmann::json::exception&) {
                    LOG(DEBUG) << "MQTT Client:   ... Starting with empty session: Session store '" << sessionStoreFileName
                               << "' empty or corrupted";
                    session.clear();
                }
                sessionStoreFile.close();
                std::remove(sessionStoreFileName.data()); // NOLINT
                LOG(INFO) << "MQTT Client: Restoring saved session done";
            } else {
                PLOG(INFO) << "MQTT Client:   ... Could not read session store '" << sessionStoreFileName << "'";
            }
        } else {
            LOG(INFO) << "MQTT Client: Session not reloaded: Session store filename empty";
        }
    }
References iot::mqtt::Session::clear(), iot::mqtt::Session::fromJson(), iot::mqtt::Mqtt::Mqtt(), session, and sessionStoreFileName.
~Mqtt()
iot::mqtt::client::Mqtt::~Mqtt () override virtual
Reimplemented from iot::mqtt::Mqtt.
Definition at line 91 of file Mqtt.cpp.
                {
        if (!sessionStoreFileName.empty()) {
            const nlohmann::json sessionJson = session.toJson();
            std::ofstream sessionStoreFile(sessionStoreFileName);
            if (sessionStoreFile.is_open()) {
                if (!sessionJson.empty()) {
                    sessionStoreFile << sessionJson;
                }
                sessionStoreFile.close();
            } else {
                PLOG(DEBUG) << "MQTT Client: Could not write session store '" << sessionStoreFileName << "'";
            }
        } else {
            LOG(INFO) << "MQTT Client: Session not saved: Session store filename empty";
        }
        pingTimer.cancel();
    }
References core::Timer::cancel(), pingTimer, session, sessionStoreFileName, and iot::mqtt::Session::toJson().
Member Function Documentation
_onConnack()
void iot::mqtt::client::Mqtt::_onConnack (const iot::mqtt::client::packets::Connack & connack) private
Definition at line 172 of file Mqtt.cpp.
{
        LOG(DEBUG) << "MQTT Client:   Acknowledge Flag: " << static_cast<int>(connack.getAcknowledgeFlags());
        LOG(DEBUG) << "MQTT Client:   Return code: " << static_cast<int>(connack.getReturnCode());
        LOG(DEBUG) << "MQTT Client:   Session present: " << connack.getSessionPresent();
        if (connack.getReturnCode() != MQTT_CONNACK_ACCEPT) {
            LOG(DEBUG) << "MQTT Client:   Negative ack received";
        } else {
            initSession(&session, keepAlive);
            pingTimer = core::timer::Timer::intervalTimer(
                [this]() -> void {
                    sendPingreq();
                },
                keepAlive);
            onConnack(connack);
        }
    }
References iot::mqtt::packets::Connack::getAcknowledgeFlags(), iot::mqtt::packets::Connack::getReturnCode(), iot::mqtt::packets::Connack::getSessionPresent(), iot::mqtt::Mqtt::initSession(), core::timer::Timer::intervalTimer(), keepAlive, onConnack(), core::timer::Timer::operator=(), pingTimer, sendPingreq(), and session.
Referenced by iot::mqtt::client::packets::Connack::deliverPacket().
_onPingresp()
void iot::mqtt::client::Mqtt::_onPingresp (const iot::mqtt::client::packets::Pingresp & pingresp) private
Definition at line 236 of file Mqtt.cpp.
{
        onPingresp(pingresp);
    }
References onPingresp().
Referenced by iot::mqtt::client::packets::Pingresp::deliverPacket().
_onPuback()
void iot::mqtt::Mqtt::_onPuback (const iot::mqtt::packets::Puback & puback) protected inherited
Definition at line 270 of file Mqtt.cpp.
{
        if (puback.getPacketIdentifier() == 0) {
            LOG(DEBUG) << "MQTT:   PackageIdentifier missing";
            mqttContext->end(true);
        } else {
            LOG(DEBUG) << "MQTT:   PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4) << puback.getPacketIdentifier();
        }
        onPuback(puback);
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::packets::Puback::getPacketIdentifier(), iot::mqtt::Mqtt::mqttContext, and iot::mqtt::Mqtt::onPuback().
Referenced by iot::mqtt::client::packets::Puback::deliverPacket(), and iot::mqtt::server::packets::Puback::deliverPacket().
_onPubcomp()
void iot::mqtt::Mqtt::_onPubcomp (const iot::mqtt::packets::Pubcomp & pubcomp) protected inherited
Definition at line 312 of file Mqtt.cpp.
{
        if (pubcomp.getPacketIdentifier() == 0) {
            LOG(DEBUG) << "MQTT:   PackageIdentifier missing";
            mqttContext->end(true);
        } else {
            LOG(DEBUG) << "MQTT:   PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4) << pubcomp.getPacketIdentifier();
            session->publishMap.erase(pubcomp.getPacketIdentifier());
            session->pubrelPacketIdentifierSet.erase(pubcomp.getPacketIdentifier());
        }
        onPubcomp(pubcomp);
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::packets::Pubcomp::getPacketIdentifier(), iot::mqtt::Mqtt::mqttContext, iot::mqtt::Mqtt::onPubcomp(), iot::mqtt::Session::publishMap, iot::mqtt::Session::pubrelPacketIdentifierSet, and iot::mqtt::Mqtt::session.
Referenced by iot::mqtt::client::packets::Pubcomp::deliverPacket(), and iot::mqtt::server::packets::Pubcomp::deliverPacket().
_onPublish() [1/2]
void iot::mqtt::client::Mqtt::_onPublish (const iot::mqtt::client::packets::Publish & publish) private
Definition at line 192 of file Mqtt.cpp.
{
        if (Super::_onPublish(publish)) {
            onPublish(publish);
        }
    }
References iot::mqtt::Mqtt::_onPublish(), and iot::mqtt::Mqtt::onPublish().
Referenced by iot::mqtt::client::packets::Publish::deliverPacket().
_onPublish() [2/2]
bool iot::mqtt::Mqtt::_onPublish (const iot::mqtt::packets::Publish & publish) protected inherited
Definition at line 230 of file Mqtt.cpp.
{
        bool deliver = true;
        LOG(DEBUG) << "MQTT:   Topic: " << publish.getTopic();
        LOG(DEBUG) << "MQTT:   Message:\n" << stringToHexString(publish.getMessage());
        LOG(DEBUG) << "MQTT:   QoS: " << static_cast<uint16_t>(publish.getQoS());
        LOG(DEBUG) << "MQTT:   PacketIdentifier: " << publish.getPacketIdentifier();
        LOG(DEBUG) << "MQTT:   DUP: " << publish.getDup();
        LOG(DEBUG) << "MQTT:   Retain: " << publish.getRetain();
        if (publish.getQoS() > 2) {
            LOG(DEBUG) << "MQTT:   Received invalid QoS: " << publish.getQoS();
            mqttContext->end(true);
            deliver = false;
        } else if (publish.getPacketIdentifier() == 0 && publish.getQoS() > 0) {
            LOG(DEBUG) << "MQTT:   Received QoS > 0 but no PackageIdentifier present";
            mqttContext->end(true);
            deliver = false;
        } else {
            switch (publish.getQoS()) {
                case 1:
                    sendPuback(publish.getPacketIdentifier());
                    break;
                case 2:
                    sendPubrec(publish.getPacketIdentifier());
                    if (session->publishPacketIdentifierSet.contains(publish.getPacketIdentifier())) {
                        deliver = false;
                    } else {
                        session->publishPacketIdentifierSet.insert(publish.getPacketIdentifier());
                    }
                    break;
            }
        }
        return deliver;
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::packets::Publish::getDup(), iot::mqtt::packets::Publish::getMessage(), iot::mqtt::packets::Publish::getPacketIdentifier(), iot::mqtt::packets::Publish::getQoS(), iot::mqtt::packets::Publish::getRetain(), iot::mqtt::packets::Publish::getTopic(), iot::mqtt::Mqtt::mqttContext, iot::mqtt::Session::publishPacketIdentifierSet, iot::mqtt::Mqtt::sendPuback(), iot::mqtt::Mqtt::sendPubrec(), iot::mqtt::Mqtt::session, and iot::mqtt::Mqtt::stringToHexString().
Referenced by _onPublish(), and iot::mqtt::server::Mqtt::_onPublish().
_onPubrec()
void iot::mqtt::Mqtt::_onPubrec (const iot::mqtt::packets::Pubrec & pubrec) protected inherited
Definition at line 281 of file Mqtt.cpp.
{
        if (pubrec.getPacketIdentifier() == 0) {
            LOG(DEBUG) << "MQTT:   PackageIdentifier missing";
            mqttContext->end(true);
        } else {
            LOG(DEBUG) << "MQTT:   PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4) << pubrec.getPacketIdentifier();
            session->publishMap.erase(pubrec.getPacketIdentifier());
            session->pubrelPacketIdentifierSet.insert(pubrec.getPacketIdentifier());
            sendPubrel(pubrec.getPacketIdentifier());
        }
        onPubrec(pubrec);
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::packets::Pubrec::getPacketIdentifier(), iot::mqtt::Mqtt::mqttContext, iot::mqtt::Mqtt::onPubrec(), iot::mqtt::Session::publishMap, iot::mqtt::Session::pubrelPacketIdentifierSet, iot::mqtt::Mqtt::sendPubrel(), and iot::mqtt::Mqtt::session.
Referenced by iot::mqtt::client::packets::Pubrec::deliverPacket(), and iot::mqtt::server::packets::Pubrec::deliverPacket().
_onPubrel()
void iot::mqtt::Mqtt::_onPubrel (const iot::mqtt::packets::Pubrel & pubrel) protected inherited
Definition at line 297 of file Mqtt.cpp.
{
        if (pubrel.getPacketIdentifier() == 0) {
            LOG(DEBUG) << "MQTT:   PackageIdentifier missing";
            mqttContext->end(true);
        } else {
            LOG(DEBUG) << "MQTT:   PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4) << pubrel.getPacketIdentifier();
            session->publishPacketIdentifierSet.erase(pubrel.getPacketIdentifier());
            sendPubcomp(pubrel.getPacketIdentifier());
        }
        onPubrel(pubrel);
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::packets::Pubrel::getPacketIdentifier(), iot::mqtt::Mqtt::mqttContext, iot::mqtt::Mqtt::onPubrel(), iot::mqtt::Session::publishPacketIdentifierSet, iot::mqtt::Mqtt::sendPubcomp(), and iot::mqtt::Mqtt::session.
Referenced by iot::mqtt::client::packets::Pubrel::deliverPacket(), and iot::mqtt::server::packets::Pubrel::deliverPacket().
_onSuback()
void iot::mqtt::client::Mqtt::_onSuback (const iot::mqtt::client::packets::Suback & suback) private
Definition at line 198 of file Mqtt.cpp.
{
        if (suback.getPacketIdentifier() == 0) {
            LOG(DEBUG) << "MQTT Client:   PackageIdentifier missing";
            mqttContext->end(true);
        } else {
            LOG(DEBUG) << "MQTT Client:  PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4)
                       << suback.getPacketIdentifier();
            std::stringstream ss;
            std::list<uint8_t>::size_type i = 0;
            for (const uint8_t returnCode : suback.getReturnCodes()) {
                if (i != 0 && i % 8 == 0 && i != suback.getReturnCodes().size()) {
                    ss << std::endl;
                    ss << "                                                       ";
                }
                ++i;
                ss << "0x" << std::hex << std::setfill('0') << std::setw(2) << static_cast<uint16_t>(returnCode) << " "; // << " | ";
            }
            LOG(DEBUG) << "MQTT Client:  Return codes: " << ss.str();
            onSuback(suback);
        }
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::packets::Suback::getPacketIdentifier(), iot::mqtt::packets::Suback::getReturnCodes(), iot::mqtt::Mqtt::mqttContext, and onSuback().
Referenced by iot::mqtt::client::packets::Suback::deliverPacket().
_onUnsuback()
void iot::mqtt::client::Mqtt::_onUnsuback (const iot::mqtt::client::packets::Unsuback & unsuback) private
Definition at line 224 of file Mqtt.cpp.
{
        if (unsuback.getPacketIdentifier() == 0) {
            LOG(DEBUG) << "MQTT Client:PackageIdentifier missing";
            mqttContext->end(true);
        } else {
            LOG(DEBUG) << "MQTT Client:PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4)
                       << unsuback.getPacketIdentifier();
            onUnsuback(unsuback);
        }
    }
References iot::mqtt::MqttContext::end(), iot::mqtt::packets::Unsuback::getPacketIdentifier(), iot::mqtt::Mqtt::mqttContext, and onUnsuback().
Referenced by iot::mqtt::client::packets::Unsuback::deliverPacket().
createControlPacketDeserializer()
iot::mqtt::ControlPacketDeserializer * iot::mqtt::client::Mqtt::createControlPacketDeserializer (iot::mqtt::FixedHeader & fixedHeader) final private virtual
Implements iot::mqtt::Mqtt.
Definition at line 113 of file Mqtt.cpp.
{
        iot::mqtt::ControlPacketDeserializer* currentPacket = nullptr;
        switch (fixedHeader.getType()) {
            case MQTT_CONNACK:
                currentPacket = new iot::mqtt::client::packets::Connack(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_PUBLISH:
                currentPacket = new iot::mqtt::client::packets::Publish(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_PUBACK:
                currentPacket = new iot::mqtt::client::packets::Puback(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_PUBREC:
                currentPacket = new iot::mqtt::client::packets::Pubrec(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_PUBREL:
                currentPacket = new iot::mqtt::client::packets::Pubrel(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_PUBCOMP:
                currentPacket = new iot::mqtt::client::packets::Pubcomp(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_SUBACK:
                currentPacket = new iot::mqtt::client::packets::Suback(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_UNSUBACK:
                currentPacket = new iot::mqtt::client::packets::Unsuback(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            case MQTT_PINGRESP:
                currentPacket = new iot::mqtt::client::packets::Pingresp(fixedHeader.getRemainingLength(), fixedHeader.getFlags());
                break;
            default:
                currentPacket = nullptr;
                break;
        }
        return currentPacket;
    }
References iot::mqtt::client::packets::Connack::Connack(), iot::mqtt::FixedHeader::getFlags(), iot::mqtt::FixedHeader::getRemainingLength(), iot::mqtt::FixedHeader::getType(), iot::mqtt::client::packets::Pingresp::Pingresp(), iot::mqtt::client::packets::Puback::Puback(), iot::mqtt::client::packets::Pubcomp::Pubcomp(), iot::mqtt::client::packets::Publish::Publish(), iot::mqtt::client::packets::Pubrec::Pubrec(), iot::mqtt::client::packets::Pubrel::Pubrel(), iot::mqtt::client::packets::Suback::Suback(), and iot::mqtt::client::packets::Unsuback::Unsuback().
dataToHexString()
std::string iot::mqtt::Mqtt::dataToHexString (const std::vector< char > & data) static inherited
Definition at line 344 of file Mqtt.cpp.
{
        std::stringstream ss;
        ss << "                                               ";
        if (!data.empty()) {
            unsigned long i = 0;
            for (const char ch : data) {
                if (i != 0 && i % 8 == 0 && i != data.size()) {
                    ss << std::endl;
                    ss << "                                               ";
                }
                ++i;
                ss << "0x" << std::hex << std::setfill('0') << std::setw(2) << static_cast<uint16_t>(static_cast<uint8_t>(ch))
                   << " "; // << " | ";
            }
        } else {
            ss << "<EMPTY>";
        }
        return ss.str();
    }
Referenced by iot::mqtt::Mqtt::printFixedHeader(), iot::mqtt::Mqtt::printVP(), iot::mqtt::Mqtt::send(), and iot::mqtt::Mqtt::stringToHexString().
deliverPacket()
void iot::mqtt::client::Mqtt::deliverPacket (iot::mqtt::ControlPacketDeserializer * controlPacketDeserializer) override private virtual
Implements iot::mqtt::Mqtt.
Definition at line 152 of file Mqtt.cpp.
{
        static_cast<iot::mqtt::client::ControlPacketDeserializer*>(controlPacketDeserializer)->deliverPacket(this); // NOLINT
    }
References iot::mqtt::client::ControlPacketDeserializer::deliverPacket().
getPacketIdentifier()
uint16_t iot::mqtt::Mqtt::getPacketIdentifier () protected inherited
Definition at line 371 of file Mqtt.cpp.
{
        ++_packetIdentifier;
        if (_packetIdentifier == 0) {
            ++_packetIdentifier;
        }
        return _packetIdentifier;
    }
References iot::mqtt::Mqtt::_packetIdentifier.
Referenced by iot::mqtt::Mqtt::sendPublish(), sendSubscribe(), and sendUnsubscribe().
getSocketConnection()
core::socket::stream::SocketConnection * iot::mqtt::Mqtt::getSocketConnection () inherited
Definition at line 139 of file Mqtt.cpp.
{
        return mqttContext->getSocketConnection();
    }
References iot::mqtt::MqttContext::getSocketConnection(), and iot::mqtt::Mqtt::mqttContext.
Referenced by iot::mqtt::Mqtt::initSession().
initSession()
void iot::mqtt::Mqtt::initSession (Session * session, utils::Timeval keepAlive) protected inherited
Definition at line 143 of file Mqtt.cpp.
{
        this->session = session;
        for (const auto& [packetIdentifier, publish] : session->publishMap) {
            LOG(DEBUG) << "MQTT: PUBLISH Resend";
            send(publish);
        }
        for (const uint16_t packetIdentifier : session->pubrelPacketIdentifierSet) {
            LOG(DEBUG) << "MQTT: PUBREL Resend";
            send(iot::mqtt::packets::Pubrel(packetIdentifier));
        }
        if (keepAlive > 0) {
            keepAlive *= 1.5;
            LOG(TRACE) << "MQTT: Keep alive initialized with: " << keepAlive;
            keepAliveTimer = core::timer::Timer::singleshotTimer(
                [this, keepAlive]() -> void {
                    LOG(DEBUG) << "MQTT: Keep-alive timer expired. Interval was: " << keepAlive;
                    mqttContext->close();
                },
                keepAlive);
            getSocketConnection()->setTimeout(0);
        }
    }
References iot::mqtt::MqttContext::close(), iot::mqtt::Mqtt::getSocketConnection(), iot::mqtt::Mqtt::keepAliveTimer, iot::mqtt::Mqtt::mqttContext, utils::Timeval::operator*=(), core::timer::Timer::operator=(), utils::Timeval::operator>(), iot::mqtt::Session::publishMap, iot::mqtt::packets::Pubrel::Pubrel(), iot::mqtt::Session::pubrelPacketIdentifierSet, iot::mqtt::Mqtt::send(), iot::mqtt::Mqtt::session, core::socket::stream::SocketConnection::setTimeout(), and core::timer::Timer::singleshotTimer().
Referenced by _onConnack(), and iot::mqtt::server::Mqtt::initSession().
onConnack()
void iot::mqtt::client::Mqtt::onConnack (const iot::mqtt::packets::Connack & connack) private virtual
Definition at line 160 of file Mqtt.cpp.
{
    }
Referenced by _onConnack().
onConnected()
void iot::mqtt::Mqtt::onConnected () virtual inherited
Definition at line 64 of file Mqtt.cpp.
{
        LOG(INFO) << "MQTT: Connected";
    }
Referenced by iot::mqtt::MqttContext::onConnected().
onDisconnected()
void iot::mqtt::Mqtt::onDisconnected () virtual inherited
Definition at line 135 of file Mqtt.cpp.
{
        LOG(INFO) << "MQTT: Disconnected";
    }
Referenced by iot::mqtt::MqttContext::onDisconnected().
onPingresp()
void iot::mqtt::client::Mqtt::onPingresp (const iot::mqtt::packets::Pingresp & pingresp) private virtual
Definition at line 169 of file Mqtt.cpp.
{
    }
Referenced by _onPingresp().
onPuback()
void iot::mqtt::Mqtt::onPuback (const iot::mqtt::packets::Puback & puback) protected virtual inherited
Definition at line 218 of file Mqtt.cpp.
{
    }
Referenced by iot::mqtt::Mqtt::_onPuback().
onPubcomp()
void iot::mqtt::Mqtt::onPubcomp (const iot::mqtt::packets::Pubcomp & pubcomp) protected virtual inherited
Definition at line 227 of file Mqtt.cpp.
{
    }
Referenced by iot::mqtt::Mqtt::_onPubcomp().
onPublish()
void iot::mqtt::Mqtt::onPublish (const iot::mqtt::packets::Publish & publish) protected virtual inherited
Definition at line 215 of file Mqtt.cpp.
{
    }
Referenced by _onPublish(), and iot::mqtt::server::Mqtt::_onPublish().
onPubrec()
void iot::mqtt::Mqtt::onPubrec (const iot::mqtt::packets::Pubrec & pubrec) protected virtual inherited
Definition at line 221 of file Mqtt.cpp.
{
    }
Referenced by iot::mqtt::Mqtt::_onPubrec().
onPubrel()
void iot::mqtt::Mqtt::onPubrel (const iot::mqtt::packets::Pubrel & pubrel) protected virtual inherited
Definition at line 224 of file Mqtt.cpp.
{
    }
Referenced by iot::mqtt::Mqtt::_onPubrel().
onReceivedFromPeer()
std::size_t iot::mqtt::Mqtt::onReceivedFromPeer () private inherited
Definition at line 68 of file Mqtt.cpp.
{
        std::size_t consumed = 0;
        switch (state) {
            case 0:
                consumed = fixedHeader.deserialize(mqttContext);
                if (!fixedHeader.isComplete()) {
                    break;
                }
                if (fixedHeader.isError()) {
                    mqttContext->close();
                    break;
                }
                printFixedHeader(fixedHeader);
                controlPacketDeserializer = createControlPacketDeserializer(fixedHeader);
                fixedHeader.reset();
                if (controlPacketDeserializer == nullptr) {
                    LOG(DEBUG) << "MQTT: Received packet-type is unavailable ... closing connection";
                    mqttContext->end(true);
                    break;
                }
                if (controlPacketDeserializer->isError()) {
                    LOG(DEBUG) << "MQTT: Fixed header has error ... closing connection";
                    delete controlPacketDeserializer;
                    controlPacketDeserializer = nullptr;
                    mqttContext->end(true);
                    break;
                }
                state++;
                [[fallthrough]];
            case 1:
                consumed += controlPacketDeserializer->deserialize(mqttContext);
                if (controlPacketDeserializer->isError()) {
                    LOG(DEBUG) << "MQTT: Control packet has error ... closing connection";
                    mqttContext->end(true);
                    delete controlPacketDeserializer;
                    controlPacketDeserializer = nullptr;
                    state = 0;
                } else if (controlPacketDeserializer->isComplete()) {
                    deliverPacket(controlPacketDeserializer);
                    delete controlPacketDeserializer;
                    controlPacketDeserializer = nullptr;
                    state = 0;
                    keepAliveTimer.restart();
                }
                break;
        }
        return consumed;
    }
References iot::mqtt::MqttContext::close(), iot::mqtt::FixedHeader::deserialize(), iot::mqtt::Mqtt::fixedHeader, iot::mqtt::FixedHeader::isComplete(), iot::mqtt::FixedHeader::isError(), iot::mqtt::Mqtt::mqttContext, iot::mqtt::Mqtt::printFixedHeader(), and iot::mqtt::Mqtt::state.
Referenced by iot::mqtt::MqttContext::onReceivedFromPeer().
onSignal()
bool iot::mqtt::client::Mqtt::onSignal (int sig) override protected virtual
Implements iot::mqtt::Mqtt.
Definition at line 156 of file Mqtt.cpp.
{
        return false;
    }
onSuback()
void iot::mqtt::client::Mqtt::onSuback (const iot::mqtt::packets::Suback & suback) private virtual
Definition at line 163 of file Mqtt.cpp.
{
    }
Referenced by _onSuback().
onUnsuback()
void iot::mqtt::client::Mqtt::onUnsuback (const iot::mqtt::packets::Unsuback & unsuback) private virtual
Definition at line 166 of file Mqtt.cpp.
{
    }
Referenced by _onUnsuback().
printFixedHeader()
void iot::mqtt::Mqtt::printFixedHeader (const iot::mqtt::FixedHeader & fixedHeader) static protected inherited
Definition at line 332 of file Mqtt.cpp.
{
        LOG(DEBUG) << "MQTT: ======================================================";
        LOG(TRACE) << "MQTT: Received data (fixed header):\n" << dataToHexString(fixedHeader.serialize());
        LOG(DEBUG) << "MQTT: Fixed Header: PacketType: 0x" << std::hex << std::setfill('0') << std::setw(2)
                   << static_cast<uint16_t>(fixedHeader.getType()) << " (" << iot::mqtt::mqttPackageName[fixedHeader.getType()] << ")";
        LOG(DEBUG) << "MQTT:   PacketFlags: 0x" << std::hex << std::setfill('0') << std::setw(2)
                   << static_cast<uint16_t>(fixedHeader.getFlags()) << std::dec;
        LOG(DEBUG) << "MQTT:   RemainingLength: " << fixedHeader.getRemainingLength();
    }
References iot::mqtt::Mqtt::dataToHexString(), iot::mqtt::FixedHeader::getFlags(), iot::mqtt::FixedHeader::getRemainingLength(), iot::mqtt::FixedHeader::getType(), iot::mqtt::mqttPackageName, and iot::mqtt::FixedHeader::serialize().
Referenced by iot::mqtt::Mqtt::onReceivedFromPeer().
printVP()
void iot::mqtt::Mqtt::printVP (const iot::mqtt::ControlPacket & packet) const protected inherited
Definition at line 326 of file Mqtt.cpp.
{
        LOG(TRACE) << "MQTT: Received data (variable header and payload):\n" << dataToHexString(packet.serializeVP());
        LOG(INFO) << "MQTT: " << packet.getName() << " received: " << clientId;
    }
References iot::mqtt::Mqtt::clientId, iot::mqtt::Mqtt::dataToHexString(), iot::mqtt::ControlPacket::getName(), and iot::mqtt::ControlPacket::serializeVP().
Referenced by iot::mqtt::client::packets::Connack::deliverPacket(), iot::mqtt::client::packets::Pingresp::deliverPacket(), iot::mqtt::client::packets::Puback::deliverPacket(), iot::mqtt::client::packets::Pubcomp::deliverPacket(), iot::mqtt::client::packets::Publish::deliverPacket(), iot::mqtt::client::packets::Pubrec::deliverPacket(), iot::mqtt::client::packets::Pubrel::deliverPacket(), iot::mqtt::client::packets::Suback::deliverPacket(), iot::mqtt::client::packets::Unsuback::deliverPacket(), iot::mqtt::server::packets::Connect::deliverPacket(), iot::mqtt::server::packets::Disconnect::deliverPacket(), iot::mqtt::server::packets::Pingreq::deliverPacket(), iot::mqtt::server::packets::Puback::deliverPacket(), iot::mqtt::server::packets::Pubcomp::deliverPacket(), iot::mqtt::server::packets::Publish::deliverPacket(), iot::mqtt::server::packets::Pubrec::deliverPacket(), iot::mqtt::server::packets::Pubrel::deliverPacket(), iot::mqtt::server::packets::Subscribe::deliverPacket(), and iot::mqtt::server::packets::Unsubscribe::deliverPacket().
send() [1/2]
void iot::mqtt::Mqtt::send (const iot::mqtt::ControlPacket & controlPacket) const protected inherited
Definition at line 174 of file Mqtt.cpp.
{
        LOG(INFO) << "MQTT: " << controlPacket.getName() << " send: " << clientId;
        send(controlPacket.serialize());
    }
References iot::mqtt::Mqtt::clientId, iot::mqtt::ControlPacket::getName(), iot::mqtt::Mqtt::send(), and iot::mqtt::ControlPacket::serialize().
Referenced by iot::mqtt::Mqtt::initSession(), iot::mqtt::server::Mqtt::sendConnack(), sendConnect(), sendDisconnect(), sendPingreq(), iot::mqtt::server::Mqtt::sendPingresp(), iot::mqtt::Mqtt::sendPuback(), iot::mqtt::Mqtt::sendPubcomp(), iot::mqtt::Mqtt::sendPublish(), iot::mqtt::Mqtt::sendPubrec(), iot::mqtt::Mqtt::sendPubrel(), iot::mqtt::server::Mqtt::sendSuback(), sendSubscribe(), iot::mqtt::server::Mqtt::sendUnsuback(), and sendUnsubscribe().
send() [2/2]
void iot::mqtt::Mqtt::send (const std::vector< char > & data) const private inherited
Definition at line 180 of file Mqtt.cpp.
{
        LOG(TRACE) << "MQTT: Send data:\n" << dataToHexString(data);
        mqttContext->send(data.data(), data.size());
    }
References iot::mqtt::Mqtt::dataToHexString(), iot::mqtt::Mqtt::mqttContext, and iot::mqtt::MqttContext::send().
Referenced by iot::mqtt::Mqtt::send().
sendConnect()
void iot::mqtt::client::Mqtt::sendConnect (uint16_t keepAlive, const std::string & clientId, bool cleanSession, const std::string & willTopic, const std::string & willMessage, uint8_t willQoS, bool willRetain, const std::string & username, const std::string & password, bool reflect)
Definition at line 240 of file Mqtt.cpp.
                                         { // Client
        this->clientId = clientId;
        LOG(DEBUG) << "MQTT Client: CONNECT send: " << clientId;
        send(iot::mqtt::packets::Connect(
            clientId, keepAlive, cleanSession, willTopic, willMessage, willQoS, willRetain, username, password, reflect));
        this->keepAlive = keepAlive;
    }
References iot::mqtt::Mqtt::clientId, iot::mqtt::packets::Connect::Connect(), keepAlive, and iot::mqtt::Mqtt::send().
sendDisconnect()
void iot::mqtt::client::Mqtt::sendDisconnect () const
Definition at line 272 of file Mqtt.cpp.
                                    { // Client
        send(iot::mqtt::packets::Disconnect());
        mqttContext->end();
    }
References iot::mqtt::packets::Disconnect::Disconnect(), iot::mqtt::MqttContext::end(), iot::mqtt::Mqtt::mqttContext, and iot::mqtt::Mqtt::send().
sendPingreq()
void iot::mqtt::client::Mqtt::sendPingreq () const
Definition at line 268 of file Mqtt.cpp.
                                 { // Client
        send(iot::mqtt::packets::Pingreq());
    }
References iot::mqtt::packets::Pingreq::Pingreq(), and iot::mqtt::Mqtt::send().
Referenced by _onConnack().
sendPuback()
void iot::mqtt::Mqtt::sendPuback (uint16_t packetIdentifier) const inherited
Definition at line 199 of file Mqtt.cpp.
                                                         { // Server & Client
        send(iot::mqtt::packets::Puback(packetIdentifier));
    }
References iot::mqtt::packets::Puback::Puback(), and iot::mqtt::Mqtt::send().
Referenced by iot::mqtt::Mqtt::_onPublish().
sendPubcomp()
void iot::mqtt::Mqtt::sendPubcomp (uint16_t packetIdentifier) const inherited
Definition at line 211 of file Mqtt.cpp.
                                                          { // Server & Client
        send(iot::mqtt::packets::Pubcomp(packetIdentifier));
    }
References iot::mqtt::packets::Pubcomp::Pubcomp(), and iot::mqtt::Mqtt::send().
Referenced by iot::mqtt::Mqtt::_onPubrel().
sendPublish()
void iot::mqtt::Mqtt::sendPublish (const std::string & topic, const std::string & message, uint8_t qoS, bool retain) inherited
Definition at line 186 of file Mqtt.cpp.
                                        { // Server & Client
        uint16_t packageIdentifier = qoS != 0 ? getPacketIdentifier() : 0;
        send(iot::mqtt::packets::Publish(packageIdentifier, topic, message, qoS, false, retain));
        if (qoS == 2) {
            session->publishMap.emplace(packageIdentifier,
                                        iot::mqtt::packets::Publish(packageIdentifier, topic, message, qoS, true, retain));
        }
    }
References iot::mqtt::Mqtt::getPacketIdentifier(), iot::mqtt::packets::Publish::Publish(), iot::mqtt::Session::publishMap, iot::mqtt::Mqtt::send(), and iot::mqtt::Mqtt::session.
Referenced by iot::mqtt::server::broker::Session::sendPublish().
sendPubrec()
void iot::mqtt::Mqtt::sendPubrec (uint16_t packetIdentifier) const inherited
Definition at line 203 of file Mqtt.cpp.
                                                         { // Server & Client
        send(iot::mqtt::packets::Pubrec(packetIdentifier));
    }
References iot::mqtt::packets::Pubrec::Pubrec(), and iot::mqtt::Mqtt::send().
Referenced by iot::mqtt::Mqtt::_onPublish().
sendPubrel()
void iot::mqtt::Mqtt::sendPubrel (uint16_t packetIdentifier) const inherited
Definition at line 207 of file Mqtt.cpp.
                                                         { // Server & Client
        send(iot::mqtt::packets::Pubrel(packetIdentifier));
    }
References iot::mqtt::packets::Pubrel::Pubrel(), and iot::mqtt::Mqtt::send().
Referenced by iot::mqtt::Mqtt::_onPubrec().
sendSubscribe()
void iot::mqtt::client::Mqtt::sendSubscribe (std::list< Topic > & topics)
Definition at line 260 of file Mqtt.cpp.
                                                          { // Client
        send(iot::mqtt::packets::Subscribe(getPacketIdentifier(), topics));
    }
References iot::mqtt::Mqtt::getPacketIdentifier(), iot::mqtt::Mqtt::send(), and iot::mqtt::packets::Subscribe::Subscribe().
sendUnsubscribe()
void iot::mqtt::client::Mqtt::sendUnsubscribe (const std::list< std::string > & topics)
Definition at line 264 of file Mqtt.cpp.
                                                               { // Client
        send(iot::mqtt::packets::Unsubscribe(getPacketIdentifier(), topics));
    }
References iot::mqtt::Mqtt::getPacketIdentifier(), iot::mqtt::Mqtt::send(), and iot::mqtt::packets::Unsubscribe::Unsubscribe().
setMqttContext()
void iot::mqtt::Mqtt::setMqttContext (MqttContext * mqttContext) private inherited
Definition at line 60 of file Mqtt.cpp.
{
        this->mqttContext = mqttContext;
    }
References iot::mqtt::Mqtt::mqttContext.
Referenced by iot::mqtt::MqttContext::MqttContext().
stringToHexString()
std::string iot::mqtt::Mqtt::stringToHexString (const std::string & data) static inherited
Definition at line 367 of file Mqtt.cpp.
{
        return dataToHexString(std::vector<char>(data.begin(), data.end()));
    }
References iot::mqtt::Mqtt::dataToHexString().
Referenced by iot::mqtt::Mqtt::_onPublish(), iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), iot::mqtt::server::broker::SubscribtionTree::TopicLevel::publish(), iot::mqtt::server::broker::RetainTree::TopicLevel::retain(), and iot::mqtt::server::broker::Session::sendPublish().
Friends And Related Symbol Documentation
iot::mqtt::client::packets::Connack
friend class iot::mqtt::client::packets::Connack friend
Definition at line 105 of file Mqtt.h.
iot::mqtt::client::packets::Pingresp
friend class iot::mqtt::client::packets::Pingresp friend
Definition at line 108 of file Mqtt.h.
iot::mqtt::client::packets::Puback
friend class iot::mqtt::client::packets::Puback friend
Definition at line 112 of file Mqtt.h.
iot::mqtt::client::packets::Pubcomp
friend class iot::mqtt::client::packets::Pubcomp friend
Definition at line 110 of file Mqtt.h.
iot::mqtt::client::packets::Publish
friend class iot::mqtt::client::packets::Publish friend
Definition at line 109 of file Mqtt.h.
iot::mqtt::client::packets::Pubrec
friend class iot::mqtt::client::packets::Pubrec friend
Definition at line 111 of file Mqtt.h.
iot::mqtt::client::packets::Pubrel
friend class iot::mqtt::client::packets::Pubrel friend
Definition at line 113 of file Mqtt.h.
iot::mqtt::client::packets::Suback
friend class iot::mqtt::client::packets::Suback friend
Definition at line 106 of file Mqtt.h.
iot::mqtt::client::packets::Unsuback
friend class iot::mqtt::client::packets::Unsuback friend
Definition at line 107 of file Mqtt.h.
Member Data Documentation
_packetIdentifier
uint16_t iot::mqtt::Mqtt::_packetIdentifier = 0 private inherited
Definition at line 126 of file Mqtt.h.
Referenced by iot::mqtt::Mqtt::getPacketIdentifier().
clientId
std::string iot::mqtt::Mqtt::clientId protected inherited
Definition at line 120 of file Mqtt.h.
Referenced by iot::mqtt::server::Mqtt::_onConnect(), iot::mqtt::server::Mqtt::_onPublish(), iot::mqtt::server::Mqtt::_onSubscribe(), iot::mqtt::server::Mqtt::_onUnsubscribe(), iot::mqtt::server::Mqtt::getClientId(), iot::mqtt::server::Mqtt::initSession(), iot::mqtt::Mqtt::Mqtt(), iot::mqtt::Mqtt::printVP(), iot::mqtt::server::Mqtt::releaseSession(), iot::mqtt::Mqtt::send(), sendConnect(), and iot::mqtt::server::Mqtt::~Mqtt().
controlPacketDeserializer
iot::mqtt::ControlPacketDeserializer* iot::mqtt::Mqtt::controlPacketDeserializer = nullptr private inherited
Definition at line 124 of file Mqtt.h.
Referenced by iot::mqtt::Mqtt::~Mqtt().
fixedHeader
iot::mqtt::FixedHeader iot::mqtt::Mqtt::fixedHeader private inherited
Definition at line 123 of file Mqtt.h.
Referenced by iot::mqtt::Mqtt::onReceivedFromPeer().
keepAlive
uint16_t iot::mqtt::client::Mqtt::keepAlive = 0 private
Definition at line 116 of file Mqtt.h.
Referenced by _onConnack(), and sendConnect().
keepAliveTimer
core::timer::Timer iot::mqtt::Mqtt::keepAliveTimer private inherited
Definition at line 128 of file Mqtt.h.
Referenced by iot::mqtt::Mqtt::initSession(), and iot::mqtt::Mqtt::~Mqtt().
mqttContext
MqttContext* iot::mqtt::Mqtt::mqttContext = nullptr protected inherited
Definition at line 135 of file Mqtt.h.
Referenced by iot::mqtt::server::Mqtt::_onConnect(), iot::mqtt::Mqtt::_onPuback(), iot::mqtt::Mqtt::_onPubcomp(), iot::mqtt::Mqtt::_onPublish(), iot::mqtt::Mqtt::_onPubrec(), iot::mqtt::Mqtt::_onPubrel(), _onSuback(), iot::mqtt::server::Mqtt::_onSubscribe(), _onUnsuback(), iot::mqtt::server::Mqtt::_onUnsubscribe(), iot::mqtt::Mqtt::getSocketConnection(), iot::mqtt::Mqtt::initSession(), iot::mqtt::Mqtt::onReceivedFromPeer(), iot::mqtt::Mqtt::send(), sendDisconnect(), and iot::mqtt::Mqtt::setMqttContext().
pingTimer
core::timer::Timer iot::mqtt::client::Mqtt::pingTimer private
Definition at line 121 of file Mqtt.h.
Referenced by _onConnack(), and ~Mqtt().
session
iot::mqtt::Session iot::mqtt::client::Mqtt::session private
Definition at line 119 of file Mqtt.h.
Referenced by _onConnack(), Mqtt(), and ~Mqtt().
sessionStoreFileName
std::string iot::mqtt::client::Mqtt::sessionStoreFileName private
Definition at line 118 of file Mqtt.h.
Referenced by Mqtt(), and ~Mqtt().
state
int iot::mqtt::Mqtt::state = 0 private inherited
Definition at line 130 of file Mqtt.h.
Referenced by iot::mqtt::Mqtt::onReceivedFromPeer().
The documentation for this class was generated from the following files:
iot/mqtt/client/Mqtt.h
iot/mqtt/client/Mqtt.cpp