SNode.C: web::websocket::client::SubProtocolFactorySelector Class Reference
web::websocket::client::SubProtocolFactorySelector Class Reference
#include <SubProtocolFactorySelector.h>
Public Types
enum Role
using SubProtocolFactory = web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol >
Public Member Functions
SubProtocolFactorySelector (const SubProtocolFactorySelector &)=delete
SubProtocolFactorySelector & operator= (const SubProtocolFactorySelector &)=delete
~SubProtocolFactorySelector () override
SubProtocolFactory * select (const std::string &subProtocolName)
SubProtocolFactory * select (const std::string &subProtocolName, Role role)
void unload (SubProtocolFactory *subProtocolFactory)
Static Public Member Functions
static SubProtocolFactorySelector * instance ()
template<typename SubProtocolFactoryT >
static void link (const std::string &subProtocolName, SubProtocolFactoryT *(*getSubProtocolFactory)())
static void allowDlOpen ()
Protected Member Functions
void link (const std::string &subProtocolName, SubProtocolFactory *(*subProtocolFactory)())
Static Protected Member Functions
static SubProtocolFactory * load (const std::string &subProtocolName, const std::string &subProtocolLibraryFile, const std::string &subProtocolFactoryFunctionName)
Private Types
using Super = web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >
Private Member Functions
SubProtocolFactory * load (const std::string &subProtocolName) override
SubProtocolFactorySelector ()=default
Private Attributes
std::map< std::string, SubProtocolFactory * > subProtocolFactories
std::map< std::string, SubProtocolFactory *(*)()> linkedSubProtocolFactories
bool onlyLinked
Detailed Description
Definition at line 42 of file SubProtocolFactorySelector.h.
Member Typedef Documentation
SubProtocolFactory
using web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >::SubProtocolFactory = web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > inherited
Definition at line 44 of file SubProtocolFactorySelector.h.
Super
using web::websocket::client::SubProtocolFactorySelector::Super = web::websocket::SubProtocolFactorySelector<web::websocket::SubProtocolFactory<web::websocket::client::SubProtocol> > private
Definition at line 50 of file SubProtocolFactorySelector.h.
Member Enumeration Documentation
Role
enum web::websocket::SubProtocolFactorySelector::Role strong inherited
Definition at line 46 of file SubProtocolFactorySelector.h.
{ SERVER, CLIENT };
Constructor & Destructor Documentation
SubProtocolFactorySelector() [1/2]
web::websocket::client::SubProtocolFactorySelector::SubProtocolFactorySelector (const SubProtocolFactorySelector &) delete
~SubProtocolFactorySelector()
web::websocket::client::SubProtocolFactorySelector::~SubProtocolFactorySelector () override virtual
Reimplemented from web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >.
Definition at line 45 of file SubProtocolFactorySelector.cpp.
{
    }
SubProtocolFactorySelector() [2/2]
web::websocket::client::SubProtocolFactorySelector::SubProtocolFactorySelector () private default
Member Function Documentation
allowDlOpen()
void web::websocket::client::SubProtocolFactorySelector::allowDlOpen () static
Definition at line 48 of file SubProtocolFactorySelector.cpp.
{
        SubProtocolFactorySelector::instance()->Super::allowDlOpen();
    }
References web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::allowDlOpen(), and instance().
instance()
SubProtocolFactorySelector * web::websocket::client::SubProtocolFactorySelector::instance () static
Definition at line 39 of file SubProtocolFactorySelector.cpp.
{
        static SubProtocolFactorySelector subProtocolFactorySelector;
        return &subProtocolFactorySelector;
    }
Referenced by allowDlOpen(), link(), web::websocket::client::SocketContextUpgrade::loadSubProtocol(), and web::websocket::client::SocketContextUpgrade::~SocketContextUpgrade().
link() [1/2]
void web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >::link (const std::string & subProtocolName, SubProtocolFactory *(*)() subProtocolFactory) inline protected inherited
Definition at line 134 of file SubProtocolFactorySelector.h.
{
            onlyLinked = true;
            linkedSubProtocolFactories[subProtocolName] =
                reinterpret_cast<SubProtocolFactorySelector::SubProtocolFactory* (*) ()>(subProtocolFactory);
        }
link() [2/2]
template<typename SubProtocolFactoryT > static void web::websocket::client::SubProtocolFactorySelector::link (const std::string & subProtocolName, SubProtocolFactoryT *(*)() getSubProtocolFactory) inline static
Definition at line 58 of file SubProtocolFactorySelector.h.
{
            SubProtocolFactorySelector::instance()->Super::link(subProtocolName, getSubProtocolFactory);
        }
References instance().
load() [1/2]
SubProtocolFactorySelector::SubProtocolFactory * web::websocket::client::SubProtocolFactorySelector::load (const std::string & subProtocolName) override private virtual
Implements web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >.
Definition at line 52 of file SubProtocolFactorySelector.cpp.
{
        const std::string websocketSubprotocolLibraryFile = "libsnodec-websocket-" + subProtocolName + "-client.so." SOVERSION;
        const std::string websocketSubprotocolFunctionName = subProtocolName + "ClientSubProtocolFactory";
        std::string websocketSubprotocolInstallLibdir = WEBSOCKET_SUBPROTOCO_INSTALL_LIBDIR;
#if !defined(NDEBUG)
        if (const char* websocketSubprotocolInstallLibdirEnv = std::getenv("WEBSOCKET_SUBPROTOCOL_INSTALL_LIBDIR")) {
            LOG(WARNING) << "WebSocket: Overriding websocket subprotocol library dir";
            websocketSubprotocolInstallLibdir = std::string(websocketSubprotocolInstallLibdirEnv);
        }
#endif
        SubProtocolFactorySelector::SubProtocolFactory* subProtocolFactory = nullptr;
        if (std::filesystem::is_directory(websocketSubprotocolInstallLibdir + "/" + utils::Config::getApplicationName())) {
            subProtocolFactory = Super::load(subProtocolName,
                                             websocketSubprotocolInstallLibdir + "/" + utils::Config::getApplicationName() + "/" +
                                                 websocketSubprotocolLibraryFile,
                                             websocketSubprotocolFunctionName);
        } else {
            subProtocolFactory = Super::load(subProtocolName,
                                             websocketSubprotocolInstallLibdir + "/" + websocketSubprotocolLibraryFile,
                                             websocketSubprotocolFunctionName);
        }
        return subProtocolFactory;
    }
References utils::Config::getApplicationName(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load().
load() [2/2]
static SubProtocolFactory * web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >::load (const std::string & subProtocolName, const std::string & subProtocolLibraryFile, const std::string & subProtocolFactoryFunctionName) inline static protected inherited
Definition at line 54 of file SubProtocolFactorySelector.h.
{
            SubProtocolFactory* subProtocolFactory = nullptr;
            void* handle = core::DynamicLoader::dlOpen(subProtocolLibraryFile, RTLD_LAZY | RTLD_GLOBAL);
            if (handle != nullptr) {
                SubProtocolFactory* (*getSubProtocolFactory)() =
                    reinterpret_cast<SubProtocolFactory* (*) ()>(core::DynamicLoader::dlSym(handle, subProtocolFactoryFunctionName));
                if (getSubProtocolFactory != nullptr) {
                    subProtocolFactory = getSubProtocolFactory();
                    if (subProtocolFactory != nullptr) {
                        subProtocolFactory->setHandle(handle);
                        LOG(DEBUG) << "WebSocket: SubProtocolFactory created successfull: " << subProtocolName;
                    } else {
                        LOG(DEBUG) << "WebSocket: SubProtocolFactory not created: " << subProtocolName;
                        core::DynamicLoader::dlClose(handle);
                    }
                } else {
                    LOG(DEBUG) << "WebSocket: Optaining function \"" << subProtocolFactoryFunctionName
                               << "\" in plugin failed: " << core::DynamicLoader::dlError();
                    core::DynamicLoader::dlClose(handle);
                }
            }
            return subProtocolFactory;
        }
operator=()
SubProtocolFactorySelector & web::websocket::client::SubProtocolFactorySelector::operator= (const SubProtocolFactorySelector &) delete
select() [1/2]
SubProtocolFactory * web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >::select (const std::string & subProtocolName) inline inherited
Definition at line 84 of file SubProtocolFactorySelector.h.
{
            SubProtocolFactory* subProtocolFactory = nullptr;
            if (subProtocolFactories.contains(subProtocolName)) {
                subProtocolFactory = subProtocolFactories[subProtocolName];
            }
            return subProtocolFactory;
        }
select() [2/2]
SubProtocolFactory * web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >::select (const std::string & subProtocolName, Role role) inline inherited
Definition at line 94 of file SubProtocolFactorySelector.h.
{
            SubProtocolFactory* subProtocolFactory = select(subProtocolName);
            if (subProtocolFactory == nullptr) {
                if (linkedSubProtocolFactories.contains(subProtocolName)) {
                    SubProtocolFactory* (*plugin)() = linkedSubProtocolFactories[subProtocolName];
                    subProtocolFactory = plugin();
                } else if (!onlyLinked) {
                    subProtocolFactory = load(subProtocolName);
                }
                if (subProtocolFactory != nullptr) {
                    subProtocolFactories.insert({subProtocolName, subProtocolFactory});
                }
            }
            return subProtocolFactory;
        }
unload()
void web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >::unload (SubProtocolFactory * subProtocolFactory) inline inherited
Definition at line 113 of file SubProtocolFactorySelector.h.
{
            std::string name = subProtocolFactory->getName();
            if (subProtocolFactories.contains(name)) {
                subProtocolFactories.erase(name);
                void* handle = subProtocolFactory->getHandle();
                delete subProtocolFactory;
                if (handle != nullptr) {
                    core::DynamicLoader::dlCloseDelayed(handle);
                }
            }
        }
Member Data Documentation
linkedSubProtocolFactories
std::map<std::string, SubProtocolFactory* (*) ()> web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >::linkedSubProtocolFactories private inherited
Definition at line 142 of file SubProtocolFactorySelector.h.
onlyLinked
bool web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >::onlyLinked private inherited
Definition at line 144 of file SubProtocolFactorySelector.h.
subProtocolFactories
std::map<std::string, SubProtocolFactory*> web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >::subProtocolFactories private inherited
Definition at line 141 of file SubProtocolFactorySelector.h.
The documentation for this class was generated from the following files:
web/websocket/client/SubProtocolFactorySelector.h
web/websocket/client/SubProtocolFactorySelector.cpp