SNode.C: iot::mqtt::OnReceivedFromPeerEvent Class Reference
iot::mqtt::OnReceivedFromPeerEvent Class Reference
#include <SubProtocol.h>
Public Member Functions
OnReceivedFromPeerEvent (const std::function< void(const utils::Timeval &)> &onReceivedFromPeer)
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Private Member Functions
void onEvent (const utils::Timeval &currentTime) override
Private Attributes
std::function< void(const utils::Timeval &)> onReceivedFromPeer
Additional Inherited Members
Static Public Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Protected Member Functions inherited from core::EventReceiver
virtual ~EventReceiver ()=default
Detailed Description
Definition at line 72 of file SubProtocol.h.
Constructor & Destructor Documentation
OnReceivedFromPeerEvent()
iot::mqtt::OnReceivedFromPeerEvent::OnReceivedFromPeerEvent (const std::function< void(const utils::Timeval &)> & onReceivedFromPeer) explicit
Definition at line 50 of file SubProtocol.cpp.
        : core::EventReceiver("WS-OnData")
        , onReceivedFromPeer(onReceivedFromPeer) {
    }
References core::EventReceiver::EventReceiver(), and onReceivedFromPeer.
Member Function Documentation
onEvent()
void iot::mqtt::OnReceivedFromPeerEvent::onEvent (const utils::Timeval & currentTime) override private virtual
Implements core::EventReceiver.
Definition at line 55 of file SubProtocol.cpp.
{
        onReceivedFromPeer(currentTime);
    }
References onReceivedFromPeer.
Member Data Documentation
onReceivedFromPeer
std::function<void(const utils::Timeval&)> iot::mqtt::OnReceivedFromPeerEvent::onReceivedFromPeer private
Definition at line 79 of file SubProtocol.h.
Referenced by onEvent(), and OnReceivedFromPeerEvent().
The documentation for this class was generated from the following files:
iot/mqtt/SubProtocol.h
iot/mqtt/SubProtocol.cpp