SNode.C: net::phy::PhysicalSocket< SocketAddressT > Class Template Reference
net::phy::PhysicalSocket< SocketAddressT > Class Template Reference
#include <PhysicalSocket.h>
Public Types
enum Flags { NONE = 0 , NONBLOCK = SOCK_NONBLOCK , CLOEXIT = SOCK_CLOEXEC }
Public Member Functions
PhysicalSocket ()=delete
PhysicalSocket (PhysicalSocket &)=delete
PhysicalSocket & operator= (PhysicalSocket &)=delete
PhysicalSocket (const PhysicalSocket &)=delete
PhysicalSocket & operator= (const PhysicalSocket &)=delete
PhysicalSocket (int fd, const SocketAddress &bindAddress)
int open (const std::map< int, std::map< int, PhysicalSocketOption > > &socketOptionsMapMap, Flags flags)
int bind (SocketAddress &bindAddress)
bool isValid () const
int getSockError (int &cErrno) const
int getSockName (typename SocketAddress::SockAddr &localSockAddr, typename SocketAddress::SockLen &localSockAddrLen)
int getPeerName (typename SocketAddress::SockAddr &remoteSockAddr, typename SocketAddress::SockLen &remoteSockAddrLen)
const SocketAddress & getBindAddress () const
Public Member Functions inherited from core::Descriptor
Descriptor ()=delete
Descriptor (const Descriptor &d)=delete
Descriptor & operator= (int fd)
Descriptor & operator= (const Descriptor &descriptor)=delete
Descriptor & operator= (Descriptor &&descriptor) noexcept
int getFd () const
Protected Types
using SocketAddress = SocketAddressT
Protected Member Functions
PhysicalSocket (int domain, int type, int protocol)
PhysicalSocket (PhysicalSocket &&physicalSocket) noexcept=default
PhysicalSocket & operator= (PhysicalSocket &&) noexcept=default
~PhysicalSocket () override
Protected Member Functions inherited from core::Descriptor
Descriptor (int fd)
Descriptor (Descriptor &&descriptor) noexcept
virtual ~Descriptor ()
Protected Attributes
SocketAddress bindAddress
int domain = 0
int type = 0
int protocol = 0
Private Types
using Super = core::Descriptor
Private Member Functions
int setSockopt (int level, int optname, const void *optval, typename SocketAddress::SockLen optlen) const
int getSockopt (int level, int optname, void *optval, typename SocketAddress::SockLen *optlen) const
Detailed Description
template<typename SocketAddressT>
class net::phy::PhysicalSocket< SocketAddressT >
Definition at line 60 of file PhysicalSocket.h.
Member Typedef Documentation
SocketAddress
template<typename SocketAddressT > using net::phy::PhysicalSocket< SocketAddressT >::SocketAddress = SocketAddressT protected
Definition at line 68 of file PhysicalSocket.h.
Super
template<typename SocketAddressT > using net::phy::PhysicalSocket< SocketAddressT >::Super = core::Descriptor private
Definition at line 62 of file PhysicalSocket.h.
Member Enumeration Documentation
Flags
template<typename SocketAddressT > enum net::phy::PhysicalSocket::Flags
Enumerator
NONE
NONBLOCK
CLOEXIT
Definition at line 65 of file PhysicalSocket.h.
{ NONE = 0, NONBLOCK = SOCK_NONBLOCK, CLOEXIT = SOCK_CLOEXEC };
Constructor & Destructor Documentation
PhysicalSocket() [1/6]
template<typename SocketAddress > net::phy::PhysicalSocket< SocketAddress >::PhysicalSocket (int domain, int type, int protocol) protected
Definition at line 54 of file PhysicalSocket.hpp.
        : Descriptor(-1)
        , domain(domain)
        , type(type)
        , protocol(protocol) {
    }
References net::phy::PhysicalSocket< SocketAddressT >::domain, net::phy::PhysicalSocket< SocketAddressT >::protocol, and net::phy::PhysicalSocket< SocketAddressT >::type.
PhysicalSocket() [2/6]
template<typename SocketAddressT > net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket (PhysicalSocket< SocketAddressT > && physicalSocket) protected default noexcept
~PhysicalSocket()
template<typename SocketAddress > net::phy::PhysicalSocket< SocketAddress >::~PhysicalSocket () override protected
Definition at line 76 of file PhysicalSocket.hpp.
{
    }
PhysicalSocket() [3/6]
template<typename SocketAddressT > net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket () delete
PhysicalSocket() [4/6]
template<typename SocketAddressT > net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket (PhysicalSocket< SocketAddressT > &) delete
PhysicalSocket() [5/6]
template<typename SocketAddressT > net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket (const PhysicalSocket< SocketAddressT > &) delete
PhysicalSocket() [6/6]
template<typename SocketAddress > net::phy::PhysicalSocket< SocketAddress >::PhysicalSocket (int fd, const SocketAddress & bindAddress)
Definition at line 62 of file PhysicalSocket.hpp.
        : Descriptor(fd)
        , bindAddress(bindAddress) {
        typename SocketAddress::SockLen optLen = sizeof(domain);
        getSockopt(SOL_SOCKET, SO_DOMAIN, &domain, &optLen);
        optLen = sizeof(type);
        getSockopt(SOL_SOCKET, SO_TYPE, &type, &optLen);
        optLen = sizeof(protocol);
        getSockopt(SOL_SOCKET, SO_PROTOCOL, &protocol, &optLen);
    }
References net::phy::PhysicalSocket< SocketAddressT >::bindAddress, net::phy::PhysicalSocket< SocketAddressT >::domain, net::phy::PhysicalSocket< SocketAddressT >::getSockopt(), net::phy::PhysicalSocket< SocketAddressT >::protocol, and net::phy::PhysicalSocket< SocketAddressT >::type.
Member Function Documentation
bind()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::bind (SocketAddress & bindAddress)
Definition at line 106 of file PhysicalSocket.hpp.
{
        int ret = core::system::bind(core::Descriptor::getFd(), &bindAddress.getSockAddr(), bindAddress.getSockAddrLen());
        if (ret == 0) {
            this->bindAddress = bindAddress;
        }
        return ret;
    }
References core::system::bind(), net::phy::PhysicalSocket< SocketAddressT >::bindAddress, and core::Descriptor::getFd().
getBindAddress()
template<typename SocketAddress > const SocketAddress & net::phy::PhysicalSocket< SocketAddress >::getBindAddress () const
Definition at line 151 of file PhysicalSocket.hpp.
{
        return bindAddress;
    }
References net::phy::PhysicalSocket< SocketAddressT >::bindAddress.
getPeerName()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::getPeerName (typename SocketAddress::SockAddr & remoteSockAddr, typename SocketAddress::SockLen & remoteSockAddrLen)
Definition at line 145 of file PhysicalSocket.hpp.
{
        return core::system::getpeername(core::Descriptor::getFd(), reinterpret_cast<sockaddr*>(&remoteSockAddr), &remoteSockAddrLen);
    }
References core::Descriptor::getFd(), and core::system::getpeername().
getSockError()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::getSockError (int & cErrno) const
Definition at line 122 of file PhysicalSocket.hpp.
{
        typename SocketAddress::SockLen cErrnoLen = sizeof(cErrno);
        return getSockopt(SOL_SOCKET, SO_ERROR, &cErrno, &cErrnoLen);
    }
References net::phy::PhysicalSocket< SocketAddressT >::getSockopt().
getSockName()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::getSockName (typename SocketAddress::SockAddr & localSockAddr, typename SocketAddress::SockLen & localSockAddrLen)
Definition at line 139 of file PhysicalSocket.hpp.
{
        return core::system::getsockname(core::Descriptor::getFd(), reinterpret_cast<sockaddr*>(&localSockAddr), &localSockAddrLen);
    }
References core::Descriptor::getFd(), and core::system::getsockname().
getSockopt()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::getSockopt (int level, int optname, void * optval, typename SocketAddress::SockLen * optlen) const private
Definition at line 134 of file PhysicalSocket.hpp.
{
        return core::system::getsockopt(PhysicalSocket::getFd(), level, optname, optval, optlen);
    }
References core::Descriptor::getFd(), and core::system::getsockopt().
Referenced by net::phy::PhysicalSocket< SocketAddressT >::getSockError(), and net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket().
isValid()
template<typename SocketAddress > bool net::phy::PhysicalSocket< SocketAddress >::isValid () const
Definition at line 117 of file PhysicalSocket.hpp.
{
        return core::Descriptor::getFd() >= 0;
    }
References core::Descriptor::getFd().
open()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::open (const std::map< int, std::map< int, PhysicalSocketOption > > & socketOptionsMapMap, Flags flags)
Definition at line 80 of file PhysicalSocket.hpp.
{
        int ret = Super::operator=(core::system::socket(domain, type | flags, protocol)).getFd();
        if (ret >= 0) {
            for (const auto& [optLevel, socketOptionsMap] : socketOptionsMapMap) {
                for (const auto& [optName, socketOption] : socketOptionsMap) {
                    int setSockoptRet = setSockopt(
                        socketOption.getOptLevel(), socketOption.getOptName(), socketOption.getOptValue(), socketOption.getOptLen());
                    ret = (ret >= 0 && setSockoptRet < 0) ? setSockoptRet : ret;
                    if (ret < 0) {
                        break;
                    }
                }
                if (ret < 0) {
                    break;
                }
            }
        }
        return ret;
    }
References net::phy::PhysicalSocket< SocketAddressT >::domain, net::phy::PhysicalSocketOption::getOptLen(), net::phy::PhysicalSocketOption::getOptLevel(), net::phy::PhysicalSocketOption::getOptName(), net::phy::PhysicalSocketOption::getOptValue(), net::phy::PhysicalSocket< SocketAddressT >::protocol, net::phy::PhysicalSocket< SocketAddressT >::setSockopt(), core::system::socket(), and net::phy::PhysicalSocket< SocketAddressT >::type.
operator=() [1/3]
template<typename SocketAddressT > PhysicalSocket & net::phy::PhysicalSocket< SocketAddressT >::operator= (const PhysicalSocket< SocketAddressT > &) delete
operator=() [2/3]
template<typename SocketAddressT > PhysicalSocket & net::phy::PhysicalSocket< SocketAddressT >::operator= (PhysicalSocket< SocketAddressT > &&) protected default noexcept
operator=() [3/3]
template<typename SocketAddressT > PhysicalSocket & net::phy::PhysicalSocket< SocketAddressT >::operator= (PhysicalSocket< SocketAddressT > &) delete
setSockopt()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::setSockopt (int level, int optname, const void * optval, typename SocketAddress::SockLen optlen) const private
Definition at line 129 of file PhysicalSocket.hpp.
{
        return core::system::setsockopt(PhysicalSocket::getFd(), level, optname, optval, optlen);
    }
References core::Descriptor::getFd(), and core::system::setsockopt().
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open().
Member Data Documentation
bindAddress
template<typename SocketAddressT > SocketAddress net::phy::PhysicalSocket< SocketAddressT >::bindAddress protected
Definition at line 104 of file PhysicalSocket.h.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::bind(), net::phy::PhysicalSocket< SocketAddressT >::getBindAddress(), and net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket().
domain
template<typename SocketAddressT > int net::phy::PhysicalSocket< SocketAddressT >::domain = 0 protected
Definition at line 106 of file PhysicalSocket.h.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open(), net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket(), and net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket().
protocol
template<typename SocketAddressT > int net::phy::PhysicalSocket< SocketAddressT >::protocol = 0 protected
Definition at line 108 of file PhysicalSocket.h.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open(), net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket(), and net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket().
type
template<typename SocketAddressT > int net::phy::PhysicalSocket< SocketAddressT >::type = 0 protected
Definition at line 107 of file PhysicalSocket.h.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open(), net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket(), and net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket().
The documentation for this class was generated from the following files:
net/phy/PhysicalSocket.h
net/phy/PhysicalSocket.hpp