SNode.C: net::l2::config::ConfigAddress< ConfigAddressTypeT > Class Template Reference
net::l2::config::ConfigAddress< ConfigAddressTypeT > Class Template Reference
#include <ConfigAddress.h>
Public Member Functions
ConfigAddress & setSocketAddress (const SocketAddress &socketAddress)
ConfigAddress & setBtAddress (const std::string &btAddress)
std::string getBtAddress () const
ConfigAddress & setPsm (uint16_t psm)
uint16_t getPsm () const
void configurable (bool configurable=true) final
Public Member Functions inherited from net::config::ConfigSection
template<typename T>
ConfigSection (ConfigInstance *instance, T *sectionPtr, const std::string &group="Sections")
~ConfigSection () override
ConfigSection (const ConfigSection &)=delete
ConfigSection (ConfigSection &&)=delete
ConfigSection & operator= (const ConfigSection &)=delete
Public Member Functions inherited from utils::SubCommand
SubCommand (const SubCommand &)=delete
SubCommand (SubCommand &&)=delete
SubCommand & operator= (const SubCommand &)=delete
SubCommand & operator= (SubCommand &&)=delete
virtual ~SubCommand ()
std::string getName () const
std::string version () const
void parse (int argc, char *argv[])
CLI::Option * setConfig (const std::string &defaultConfigFile) const
CLI::Option * setLogFile (const std::string &defaultLogFile) const
CLI::Option * setVersionFlag (const std::string &version) const
bool hasParent () const
SubCommand * getParent ()
SubCommand * allowExtras (bool allow=true)
SubCommand * required (bool required=true, bool force=true)
SubCommand * required (SubCommand *subCommand, bool required=true)
SubCommand * required (CLI::Option *option, bool required=true)
SubCommand * needs (SubCommand *subCommand, bool needs=true)
SubCommand * disabled (SubCommand *subCommand, bool disabled=true)
SubCommand * setRequireCallback (const std::function< void(void)> &callback)
SubCommand * finalCallback (const std::function< void()> &finalCallback)
std::string configToStr () const
std::string help (const CLI::App *helpApp, const CLI::AppFormatMode &mode) const
template<typename NewSubCommand, typename... Args>
NewSubCommand * newSubCommand (Args &&... args)
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand ()
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand () const
CLI::Option * getOption (const std::string &name) const
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator) const
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Protected Member Functions
ConfigAddress (net::config::ConfigInstance *instance, const std::string &addressOptionName, const std::string &addressOptionDescription)
ConfigAddress & setBtAddressRequired (bool required=true)
ConfigAddress & setPsmRequired (bool required=true)
Protected Member Functions inherited from utils::SubCommand
SubCommand (SubCommand *parent, std::shared_ptr< utils::AppWithPtr > appWithPtr, const std::string &group, bool final)
template<typename ConcretSubCommand>
SubCommand (SubCommand *parent, ConcretSubCommand *concretSubCommand, const std::string &group, bool final=true)
SubCommand * description (const std::string &description)
SubCommand * footer (const std::string &footer)
template<typename ValueTypeT>
CLI::Option * setDefaultValue (CLI::Option *option, const ValueTypeT &value, bool clear=true) const
CLI::Option * setConfigurable (CLI::Option *option, bool configurable) const
Protected Attributes
CLI::Option * btAddressOpt = nullptr
CLI::Option * psmOpt = nullptr
Private Types
using Super = ConfigAddressTypeT<net::l2::SocketAddress>
Private Member Functions
SocketAddress * init () final
Additional Inherited Members
Static Public Member Functions inherited from utils::SubCommand
static CLI::App * getHelpTriggerApp ()
static CLI::App * getShowConfigTriggerApp ()
static CLI::App * getCommandlineTriggerApp ()
Static Public Attributes inherited from utils::SubCommand
static std::shared_ptr< CLI::Formatter > sectionFormatter = makeSectionFormatter()
Static Protected Attributes inherited from utils::SubCommand
static std::map< std::string, std::string > aliases
static CLI::App * helpTriggerApp = nullptr
static CLI::App * showConfigTriggerApp = nullptr
static CLI::App * commandlineTriggerApp = nullptr
Detailed Description
template<template< typename SocketAddressT > typename ConfigAddressTypeT>
class net::l2::config::ConfigAddress< ConfigAddressTypeT >
Definition at line 77 of file ConfigAddress.h.
Member Typedef Documentation
Super
template<template< typename SocketAddressT > typename ConfigAddressTypeT> using net::l2::config::ConfigAddress< ConfigAddressTypeT >::Super = ConfigAddressTypeT<net::l2::SocketAddress> private
Definition at line 81 of file ConfigAddress.h.
Constructor & Destructor Documentation
ConfigAddress()
template<template< typename SocketAddress > typename ConfigAddressType> net::l2::config::ConfigAddress< ConfigAddressType >::ConfigAddress (net::config::ConfigInstance * instance, const std::string & addressOptionName, const std::string & addressOptionDescription) protected
Definition at line 70 of file ConfigAddress.cpp.
        : ConfigSection(instance, this)
        , ConfigAddressType<net::l2::SocketAddress>(this) {
        btAddressOpt = addOption( //
            "--host",
            "Bluetooth address (format 01:23:45:67:89:AB)",
            "address",
            "00:00:00:00:00:00",
            CLI::Validator(
                [](std::string& s) -> std::string {
                    // Classic 48-bit Bluetooth/MAC style: "01:23:45:67:89:AB"
                    static const std::regex re(R"(^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$)");
                    if (std::regex_match(s, re)) {
                        return {}; // OK
                    }
                    return "Invalid Bluetooth address. Expected format like \"01:23:45:67:89:AB\" "
                           "(6 hex octets separated by ':').";
                },
                "BT_ADDR")
                .name("BT_ADDR"));
        psmOpt = addOption( //
            "--psm",
            "Protocol service multiplexer",
            "psm",
            "0",
            CLI::Range(std::numeric_limits<uint16_t>::min(), std::numeric_limits<uint16_t>::max()));
    }
Member Function Documentation
configurable()
template<template< typename SocketAddressT > typename ConfigAddressTypeT> void net::l2::config::ConfigAddress< ConfigAddressTypeT >::configurable (bool configurable = true) final
Definition at line 150 of file ConfigAddress.cpp.
{
        this->setConfigurable(btAddressOpt, configurable);
        this->setConfigurable(psmOpt, configurable);
    }
References btAddressOpt, and psmOpt.
getBtAddress()
template<template< typename SocketAddress > typename ConfigAddressType> std::string net::l2::config::ConfigAddress< ConfigAddressType >::getBtAddress () const
Definition at line 130 of file ConfigAddress.cpp.
{
        return btAddressOpt->as<std::string>();
    }
References btAddressOpt.
getPsm()
template<template< typename SocketAddress > typename ConfigAddressType> uint16_t net::l2::config::ConfigAddress< ConfigAddressType >::getPsm () const
Definition at line 145 of file ConfigAddress.cpp.
{
        return psmOpt->as<uint16_t>();
    }
References psmOpt.
init()
template<template< typename SocketAddress > typename ConfigAddressType> SocketAddress * net::l2::config::ConfigAddress< ConfigAddressType >::init () final private
Definition at line 104 of file ConfigAddress.cpp.
{
        SocketAddress* socketAddress = new SocketAddress(btAddressOpt->as<std::string>(), psmOpt->as<uint16_t>());
        socketAddress->init();
        return socketAddress;
    }
References btAddressOpt, net::l2::SocketAddress::init(), psmOpt, and net::l2::SocketAddress::SocketAddress().
setBtAddress()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::l2::config::ConfigAddress< ConfigAddressType >::setBtAddress (const std::string & btAddress)
Definition at line 120 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue(btAddressOpt, btAddress);
        required(btAddressOpt, false);
        return *this;
    }
References btAddressOpt.
Referenced by setSocketAddress().
setBtAddressRequired()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::l2::config::ConfigAddress< ConfigAddressType >::setBtAddressRequired (bool required = true) protected
Definition at line 156 of file ConfigAddress.cpp.
{
        this->required(btAddressOpt, required);
        return *this;
    }
References btAddressOpt.
Referenced by net::l2::stream::config::ConfigSocketClient::ConfigSocketClient().
setPsm()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::l2::config::ConfigAddress< ConfigAddressType >::setPsm (uint16_t psm)
Definition at line 135 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue(psmOpt, psm);
        required(psmOpt, false);
        return *this;
    }
References psmOpt.
Referenced by setSocketAddress().
setPsmRequired()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::l2::config::ConfigAddress< ConfigAddressType >::setPsmRequired (bool required = true) protected
Definition at line 163 of file ConfigAddress.cpp.
{
        this->required(psmOpt, required);
        return *this;
    }
References psmOpt.
Referenced by net::l2::stream::config::ConfigSocketClient::ConfigSocketClient(), and net::l2::stream::config::ConfigSocketServer::ConfigSocketServer().
setSocketAddress()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::l2::config::ConfigAddress< ConfigAddressType >::setSocketAddress (const SocketAddress & socketAddress)
Definition at line 112 of file ConfigAddress.cpp.
{
        setBtAddress(socketAddress.getBtAddress());
        setPsm(socketAddress.getPsm());
        return *this;
    }
References net::l2::SocketAddress::getBtAddress(), net::l2::SocketAddress::getPsm(), setBtAddress(), and setPsm().
Member Data Documentation
btAddressOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::l2::config::ConfigAddress< ConfigAddressTypeT >::btAddressOpt = nullptr protected
Definition at line 106 of file ConfigAddress.h.
Referenced by net::l2::config::ConfigAddressReverse< net::config::ConfigAddressReverse >::ConfigAddressReverse(), configurable(), getBtAddress(), init(), setBtAddress(), and setBtAddressRequired().
psmOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::l2::config::ConfigAddress< ConfigAddressTypeT >::psmOpt = nullptr protected
Definition at line 107 of file ConfigAddress.h.
Referenced by configurable(), getPsm(), init(), setPsm(), and setPsmRequired().
The documentation for this class was generated from the following files:
net/l2/config/ConfigAddress.h
net/l2/config/ConfigAddress.cpp