SNode.C: Validator Class Reference
Validator Class Reference
Some validators that are provided.
#include <CLI11.hpp>
Public Member Functions
Validator ()=default
Validator (std::string validator_desc)
Construct a Validator with just the description string.
Validator (std::function< std::string(std::string &)> op, std::string validator_desc, std::string validator_name="")
Construct Validator from basic information.
Validator & operation (std::function< std::string(std::string &)> op)
Set the Validator operation function.
std::string operator() (std::string &str) const
std::string operator() (const std::string &str) const
Validator & description (std::string validator_desc)
Specify the type string.
Validator description (std::string validator_desc) const
Specify the type string.
std::string get_description () const
Generate type description information for the Validator.
Validator & name (std::string validator_name)
Specify the type string.
Validator name (std::string validator_name) const
Specify the type string.
const std::string & get_name () const
Get the name of the Validator.
Validator & active (bool active_val=true)
Specify whether the Validator is active or not.
Validator active (bool active_val=true) const
Specify whether the Validator is active or not.
Validator & non_modifying (bool no_modify=true)
Specify whether the Validator can be modifying or not.
Validator & application_index (int app_index)
Specify the application index of a validator.
Validator application_index (int app_index) const
Specify the application index of a validator.
int get_application_index () const
Get the current value of the application index.
bool get_active () const
Get a boolean if the validator is active.
bool get_modifying () const
Get a boolean if the validator is allowed to modify the input returns true if it can modify the input.
Validator operator& (const Validator &other) const
Validator operator| (const Validator &other) const
Validator operator! () const
Create a validator that fails when a given validator succeeds.
Protected Member Functions
Validator (std::string validator_desc, std::function< std::string(std::string &)> func)
Protected Attributes
std::function< std::string()> desc_function_
This is the description function, if empty the description_ will be used.
std::function< std::string(std::string &)> func_
std::string name_ {}
The name for search purposes of the Validator.
int application_index_ = -1
A Validator will only apply to an indexed value (-1 is all elements)
bool active_ {true}
Enable for Validator to allow it to be disabled if need be.
bool non_modifying_ {false}
specify that a validator should not modify the input
Private Member Functions
void _merge_description (const Validator &val1, const Validator &val2, const std::string &merger)
Detailed Description
Some validators that are provided.
These are simple std::string(const std::string&) validators that are useful. They return a string if the validation fails. A custom struct is provided, as well, with the same user semantics, but with the ability to provide a new type name.
Definition at line 3327 of file CLI11.hpp.
Constructor & Destructor Documentation
Validator() [1/4]
Validator::Validator (std::string validator_desc, std::function< std::string(std::string &)> func) inline protected
Definition at line 3348 of file CLI11.hpp.
            : desc_function_([validator_desc]() {
                return validator_desc;
            })
            , func_(std::move(func)) {
        }
References Validator().
Referenced by Validator().
Validator() [2/4]
Validator::Validator () default
Validator() [3/4]
Validator::Validator (std::string validator_desc) inline explicit
Construct a Validator with just the description string.
Definition at line 3358 of file CLI11.hpp.
            : desc_function_([validator_desc]() {
                return validator_desc;
            }) {
        }
References Validator().
Referenced by Validator().
Validator() [4/4]
Validator::Validator (std::function< std::string(std::string &)> op, std::string validator_desc, std::string validator_name = "") inline
Construct Validator from basic information.
Definition at line 3364 of file CLI11.hpp.
            : desc_function_([validator_desc]() {
                return validator_desc;
            })
            , func_(std::move(op))
            , name_(std::move(validator_name)) {
        }
References Validator().
Referenced by Validator().
Member Function Documentation
_merge_description()
void Validator::_merge_description (const Validator & val1, const Validator & val2, const std::string & merger) inline private
Definition at line 4312 of file CLI11.hpp.
{
        const std::function<std::string()>& dfunc1 = val1.desc_function_;
        const std::function<std::string()>& dfunc2 = val2.desc_function_;
        desc_function_ = [=]() {
            std::string const f1 = dfunc1();
            std::string const f2 = dfunc2();
            if ((f1.empty()) || (f2.empty())) {
                return f1 + f2;
            }
            return std::string(1, '(') + f1 + ')' + merger + '(' + f2 + ')';
        };
    }
Referenced by operator&(), and operator|().
active() [1/2]
Validator & Validator::active (bool active_val = true) inline
Specify whether the Validator is active or not.
Definition at line 3420 of file CLI11.hpp.
{
            active_ = active_val;
            return *this;
        }
References active_.
active() [2/2]
Validator Validator::active (bool active_val = true) const inline
Specify whether the Validator is active or not.
Definition at line 3425 of file CLI11.hpp.
{
            Validator newval(*this);
            newval.active_ = active_val;
            return newval;
        }
References active_.
application_index() [1/2]
Validator & Validator::application_index (int app_index) inline
Specify the application index of a validator.
Definition at line 3437 of file CLI11.hpp.
{
            application_index_ = app_index;
            return *this;
        }
References application_index_.
Referenced by deprecate_option(), retire_option(), and retire_option().
application_index() [2/2]
Validator Validator::application_index (int app_index) const inline
Specify the application index of a validator.
Definition at line 3442 of file CLI11.hpp.
{
            Validator newval(*this);
            newval.application_index_ = app_index;
            return newval;
        }
References application_index_.
description() [1/2]
Validator & Validator::description (std::string validator_desc) inline
Specify the type string.
Definition at line 3388 of file CLI11.hpp.
{
            desc_function_ = [validator_desc]() {
                return validator_desc;
            };
            return *this;
        }
description() [2/2]
Validator Validator::description (std::string validator_desc) const inline
Specify the type string.
Definition at line 4238 of file CLI11.hpp.
{
        Validator newval(*this);
        newval.desc_function_ = [validator_desc]() {
            return validator_desc;
        };
        return newval;
    }
get_active()
bool Validator::get_active () const inline
Get a boolean if the validator is active.
Definition at line 3452 of file CLI11.hpp.
{
            return active_;
        }
References active_.
get_application_index()
int Validator::get_application_index () const inline
Get the current value of the application index.
Definition at line 3448 of file CLI11.hpp.
{
            return application_index_;
        }
References application_index_.
get_description()
std::string Validator::get_description () const inline
Generate type description information for the Validator.
Definition at line 3398 of file CLI11.hpp.
{
            if (active_) {
                return desc_function_();
            }
            return std::string{};
        }
References active_.
get_modifying()
bool Validator::get_modifying () const inline
Get a boolean if the validator is allowed to modify the input returns true if it can modify the input.
Definition at line 3457 of file CLI11.hpp.
{
            return !non_modifying_;
        }
References non_modifying_.
get_name()
const std::string & Validator::get_name () const inline
Get the name of the Validator.
Definition at line 3416 of file CLI11.hpp.
{
            return name_;
        }
References name_.
name() [1/2]
Validator & Validator::name (std::string validator_name) inline
Specify the type string.
Definition at line 3405 of file CLI11.hpp.
{
            name_ = std::move(validator_name);
            return *this;
        }
References name_.
name() [2/2]
Validator Validator::name (std::string validator_name) const inline
Specify the type string.
Definition at line 3410 of file CLI11.hpp.
{
            Validator newval(*this);
            newval.name_ = std::move(validator_name);
            return newval;
        }
References name_.
non_modifying()
Validator & Validator::non_modifying (bool no_modify = true) inline
Specify whether the Validator can be modifying or not.
Definition at line 3432 of file CLI11.hpp.
{
            non_modifying_ = no_modify;
            return *this;
        }
References non_modifying_.
Referenced by Option::check().
operation()
Validator & Validator::operation (std::function< std::string(std::string &)> op) inline
Set the Validator operation function.
Definition at line 3372 of file CLI11.hpp.
{
            func_ = std::move(op);
            return *this;
        }
operator!()
Validator Validator::operator! () const inline
Create a validator that fails when a given validator succeeds.
Definition at line 4290 of file CLI11.hpp.
{
        Validator newval;
        const std::function<std::string()>& dfunc1 = desc_function_;
        newval.desc_function_ = [dfunc1]() {
            auto str = dfunc1();
            return (!str.empty()) ? std::string("NOT ") + str : std::string{};
        };
        // Give references (will make a copy in lambda function)
        const std::function<std::string(std::string & res)>& f1 = func_;
        newval.func_ = [f1, dfunc1](std::string& test) -> std::string {
            std::string const s1 = f1(test);
            if (s1.empty()) {
                return std::string("check ") + dfunc1() + " succeeded improperly";
            }
            return std::string{};
        };
        newval.active_ = active_;
        newval.application_index_ = application_index_;
        return newval;
    }
References active_, and application_index_.
operator&()
Validator Validator::operator& (const Validator & other) const inline
Combining validators is a new validator. Type comes from left validator if function, otherwise only set if the same.
Definition at line 4246 of file CLI11.hpp.
{
        Validator newval;
        newval._merge_description(*this, other, " AND ");
        // Give references (will make a copy in lambda function)
        const std::function<std::string(std::string & filename)>& f1 = func_;
        const std::function<std::string(std::string & filename)>& f2 = other.func_;
        newval.func_ = [f1, f2](std::string& input) {
            std::string const s1 = f1(input);
            std::string const s2 = f2(input);
            if (!s1.empty() && !s2.empty())
                return std::string("(") + s1 + ") AND (" + s2 + ")";
            return s1 + s2;
        };
        newval.active_ = active_ && other.active_;
        newval.application_index_ = application_index_;
        return newval;
    }
References _merge_description(), active_, and application_index_.
operator()() [1/2]
std::string Validator::operator() (const std::string & str) const inline
This is the required operator for a Validator - provided to help users (CLI11 uses the member func directly)
Definition at line 3382 of file CLI11.hpp.
{
            std::string value = str;
            return (active_) ? func_(value) : std::string{};
        }
operator()() [2/2]
std::string Validator::operator() (std::string & str) const inline
This is the required operator for a Validator - provided to help users (CLI11 uses the member func directly)
Definition at line 4225 of file CLI11.hpp.
{
        std::string retstring;
        if (active_) {
            if (non_modifying_) {
                std::string value = str;
                retstring = func_(value);
            } else {
                retstring = func_(str);
            }
        }
        return retstring;
    }
References active_, and non_modifying_.
operator|()
Validator Validator::operator| (const Validator & other) const inline
Combining validators is a new validator. Type comes from left validator if function, otherwise only set if the same.
Definition at line 4268 of file CLI11.hpp.
{
        Validator newval;
        newval._merge_description(*this, other, " OR ");
        // Give references (will make a copy in lambda function)
        const std::function<std::string(std::string&)>& f1 = func_;
        const std::function<std::string(std::string&)>& f2 = other.func_;
        newval.func_ = [f1, f2](std::string& input) {
            std::string const s1 = f1(input);
            std::string const s2 = f2(input);
            if (s1.empty() || s2.empty())
                return std::string();
            return std::string("(") + s1 + ") OR (" + s2 + ")";
        };
        newval.active_ = active_ && other.active_;
        newval.application_index_ = application_index_;
        return newval;
    }
References _merge_description(), active_, and application_index_.
Member Data Documentation
active_
bool Validator::active_ {true} protected
Enable for Validator to allow it to be disabled if need be.
Definition at line 3344 of file CLI11.hpp.
{true};
Referenced by active(), active(), get_active(), get_description(), operator!(), operator&(), operator()(), and operator|().
application_index_
int Validator::application_index_ = -1 protected
A Validator will only apply to an indexed value (-1 is all elements)
Definition at line 3342 of file CLI11.hpp.
Referenced by application_index(), application_index(), get_application_index(), operator!(), operator&(), and operator|().
desc_function_
std::function<std::string()> Validator::desc_function_ protected
Initial value:
{[]() {
            return std::string{};
        }}
This is the description function, if empty the description_ will be used.
Definition at line 3330 of file CLI11.hpp.
                                               {[]() {
            return std::string{};
        }};
func_
std::function<std::string(std::string&)> Validator::func_ protected
Initial value:
{[](std::string&) {
            return std::string{};
        }}
This is the base function that is to be called. Returns a string error message if validation fails.
Definition at line 3336 of file CLI11.hpp.
                                                {[](std::string&) {
            return std::string{};
        }};
name_
std::string Validator::name_ {} protected
The name for search purposes of the Validator.
Definition at line 3340 of file CLI11.hpp.
{};
Referenced by get_name(), name(), and name().
non_modifying_
bool Validator::non_modifying_ {false} protected
specify that a validator should not modify the input
Definition at line 3346 of file CLI11.hpp.
{false};
Referenced by get_modifying(), non_modifying(), and operator()().
The documentation for this class was generated from the following file:
src/utils/CLI11.hpp