SNode.C: web::http::client::ConfigHTTP Class Reference
web::http::client::ConfigHTTP Class Reference
#include <ConfigHTTP.h>
Public Member Functions
ConfigHTTP (utils::SubCommand *parent)
~ConfigHTTP () override
ConfigHTTP (ConfigHTTP &)=delete
ConfigHTTP & operator= (ConfigHTTP &)=delete
ConfigHTTP (ConfigHTTP &&) noexcept=delete
ConfigHTTP & operator= (ConfigHTTP &&)=delete
ConfigHTTP & setHostHeader (const std::string &hostHeader)
std::string getHostHeader () const
ConfigHTTP & setPipelinedRequests (bool pipelinedRequests)
bool getPipelinedRequests () const
Public Member Functions inherited from utils::SubCommand
SubCommand (const SubCommand &)=delete
SubCommand (SubCommand &&)=delete
SubCommand & operator= (const SubCommand &)=delete
SubCommand & operator= (SubCommand &&)=delete
virtual ~SubCommand ()
std::string getName () const
std::string version () const
void parse (int argc, char *argv[])
CLI::Option * setConfig (const std::string &defaultConfigFile) const
CLI::Option * setLogFile (const std::string &defaultLogFile) const
CLI::Option * setVersionFlag (const std::string &version) const
bool hasParent () const
SubCommand * getParent ()
SubCommand * allowExtras (bool allow=true)
SubCommand * required (bool required=true, bool force=true)
SubCommand * required (SubCommand *subCommand, bool required=true)
SubCommand * required (CLI::Option *option, bool required=true)
SubCommand * needs (SubCommand *subCommand, bool needs=true)
SubCommand * disabled (SubCommand *subCommand, bool disabled=true)
SubCommand * setRequireCallback (const std::function< void(void)> &callback)
SubCommand * finalCallback (const std::function< void()> &finalCallback)
std::string configToStr () const
std::string help (const CLI::App *helpApp, const CLI::AppFormatMode &mode) const
template<typename NewSubCommand, typename... Args>
NewSubCommand * newSubCommand (Args &&... args)
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand ()
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand () const
CLI::Option * getOption (const std::string &name) const
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator) const
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Static Public Attributes
static constexpr std::string_view NAME {"http"}
static constexpr std::string_view DESCRIPTION {"HTTP behavior"}
Static Public Attributes inherited from utils::SubCommand
static std::shared_ptr< CLI::Formatter > sectionFormatter = makeSectionFormatter()
Private Attributes
CLI::Option * hostHeaderOpt = nullptr
CLI::Option * pipelinedRequestsOpt = nullptr
Additional Inherited Members
Static Public Member Functions inherited from utils::SubCommand
static CLI::App * getHelpTriggerApp ()
static CLI::App * getShowConfigTriggerApp ()
static CLI::App * getCommandlineTriggerApp ()
Protected Member Functions inherited from utils::SubCommand
SubCommand (SubCommand *parent, std::shared_ptr< utils::AppWithPtr > appWithPtr, const std::string &group, bool final)
template<typename ConcretSubCommand>
SubCommand (SubCommand *parent, ConcretSubCommand *concretSubCommand, const std::string &group, bool final=true)
SubCommand * description (const std::string &description)
SubCommand * footer (const std::string &footer)
template<typename ValueTypeT>
CLI::Option * setDefaultValue (CLI::Option *option, const ValueTypeT &value, bool clear=true) const
CLI::Option * setConfigurable (CLI::Option *option, bool configurable) const
Static Protected Attributes inherited from utils::SubCommand
static std::map< std::string, std::string > aliases
static CLI::App * helpTriggerApp = nullptr
static CLI::App * showConfigTriggerApp = nullptr
static CLI::App * commandlineTriggerApp = nullptr
Detailed Description
Definition at line 55 of file ConfigHTTP.h.
Constructor & Destructor Documentation
ConfigHTTP() [1/3]
web::http::client::ConfigHTTP::ConfigHTTP (utils::SubCommand * parent) explicit
Definition at line 53 of file ConfigHTTP.cpp.
        : utils::SubCommand(parent, this, "Applications") {
        hostHeaderOpt = addOption( //
            "--host",
            "HTTP request 'Host' header field",
            "hostname|IP",
            CLI::TypeValidator<std::string>());
        pipelinedRequestsOpt = addFlag( //
            "--pipelined-requests",
            "Pipelined requests",
            "bool",
            XSTR(HTTP_REQUEST_PIPELINED),
            CLI::IsMember({"true", "false"}));
    }
References utils::SubCommand::addFlag(), utils::SubCommand::addOption(), hostHeaderOpt, pipelinedRequestsOpt, and utils::SubCommand::SubCommand().
~ConfigHTTP()
web::http::client::ConfigHTTP::~ConfigHTTP () override
Definition at line 69 of file ConfigHTTP.cpp.
{
    }
ConfigHTTP() [2/3]
web::http::client::ConfigHTTP::ConfigHTTP (ConfigHTTP &) delete
ConfigHTTP() [3/3]
web::http::client::ConfigHTTP::ConfigHTTP (ConfigHTTP &&) delete noexcept
Member Function Documentation
getHostHeader()
std::string web::http::client::ConfigHTTP::getHostHeader () const
Definition at line 78 of file ConfigHTTP.cpp.
{
        return hostHeaderOpt->as<std::string>();
    }
References hostHeaderOpt.
Referenced by web::http::client::SocketContextFactory::create().
getPipelinedRequests()
bool web::http::client::ConfigHTTP::getPipelinedRequests () const
Definition at line 88 of file ConfigHTTP.cpp.
{
        return pipelinedRequestsOpt->as<bool>();
    }
References pipelinedRequestsOpt.
Referenced by web::http::client::SocketContextFactory::create().
operator=() [1/2]
ConfigHTTP & web::http::client::ConfigHTTP::operator= (ConfigHTTP &&) delete
operator=() [2/2]
ConfigHTTP & web::http::client::ConfigHTTP::operator= (ConfigHTTP &) delete
setHostHeader()
ConfigHTTP & web::http::client::ConfigHTTP::setHostHeader (const std::string & hostHeader)
Definition at line 72 of file ConfigHTTP.cpp.
{
        setDefaultValue(hostHeaderOpt, hostHeader);
        return *this;
    }
References hostHeaderOpt, and utils::SubCommand::setDefaultValue().
setPipelinedRequests()
ConfigHTTP & web::http::client::ConfigHTTP::setPipelinedRequests (bool pipelinedRequests)
Definition at line 82 of file ConfigHTTP.cpp.
{
        setDefaultValue(pipelinedRequestsOpt, pipelinedRequests ? "true" : "false");
        return *this;
    }
References pipelinedRequestsOpt, and utils::SubCommand::setDefaultValue().
Member Data Documentation
DESCRIPTION
std::string_view web::http::client::ConfigHTTP::DESCRIPTION {"HTTP behavior"} static constexpr
Definition at line 58 of file ConfigHTTP.h.
{"HTTP behavior"};
hostHeaderOpt
CLI::Option* web::http::client::ConfigHTTP::hostHeaderOpt = nullptr private
Definition at line 77 of file ConfigHTTP.h.
Referenced by ConfigHTTP(), getHostHeader(), and setHostHeader().
NAME
std::string_view web::http::client::ConfigHTTP::NAME {"http"} static constexpr
Definition at line 57 of file ConfigHTTP.h.
{"http"};
pipelinedRequestsOpt
CLI::Option* web::http::client::ConfigHTTP::pipelinedRequestsOpt = nullptr private
Definition at line 78 of file ConfigHTTP.h.
Referenced by ConfigHTTP(), getPipelinedRequests(), and setPipelinedRequests().
The documentation for this class was generated from the following files:
web/http/client/ConfigHTTP.h
web/http/client/ConfigHTTP.cpp