SNode.C: web::websocket::server::SubProtocol Class Reference
web::websocket::server::SubProtocol Class Reference abstract
#include <SubProtocol.h>
Public Member Functions
~SubProtocol () override
void subscribe (const std::string &group)
void sendBroadcast (const char *message, std::size_t messageLength, bool excludeSelf=false)
void sendBroadcast (const std::string &message, bool excludeSelf=false)
void sendBroadcastStart (const char *message, std::size_t messageLength, bool excludeSelf=false)
void sendBroadcastStart (const std::string &message, bool excludeSelf=false)
void sendBroadcastFrame (const char *message, std::size_t messageLength, bool excludeSelf=false)
void sendBroadcastFrame (const std::string &message, bool excludeSelf=false)
void sendBroadcastEnd (const char *message, std::size_t messageLength, bool excludeSelf=false)
void sendBroadcastEnd (const std::string &message, bool excludeSelf=false)
void forEachClient (const std::function< void(const SubProtocol *)> &sendToClient, bool excludeSelf=false)
void sendMessage (const char *message, std::size_t messageLength) const
void sendMessage (const std::string &message) const
void sendMessageStart (const char *message, std::size_t messageLength) const
void sendMessageStart (const std::string &message) const
void sendMessageFrame (const char *message, std::size_t messageLength) const
void sendMessageFrame (const std::string &message) const
void sendMessageEnd (const char *message, std::size_t messageLength) const
void sendMessageEnd (const std::string &message) const
void sendPing (const char *reason=nullptr, std::size_t reasonLength=0) const
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
const std::string & getName ()
core::socket::stream::SocketConnection * getSocketConnection ()
Protected Member Functions
SubProtocol (SubProtocolContext *subProtocolContext, const std::string &name, int pingInterval=0, int maxFlyingPings=3)
Protected Attributes
SubProtocolContext * subProtocolContext
Private Types
using Super = web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >
using SocketContextUpgrade = web::websocket::server::SocketContextUpgrade
Private Member Functions
virtual void onConnected ()=0
virtual void onDisconnected ()=0
virtual bool onSignal (int sig)=0
virtual void onMessageStart (int opCode)=0
virtual void onMessageData (const char *chunk, std::size_t chunkLen)=0
virtual void onMessageEnd ()=0
virtual void onMessageError (uint16_t errnum)=0
virtual void onPongReceived ()
Private Attributes
std::string group
const std::string name
core::timer::Timer pingTimer
int flyingPings
Friends
template<typename RequestT , typename ResponseT , typename SubProtocolT >
class web::websocket::SocketContextUpgrade
class GroupsManager
Detailed Description
Definition at line 41 of file SubProtocol.h.
Member Typedef Documentation
SocketContextUpgrade
using web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::SocketContextUpgrade = web::websocket::server::SocketContextUpgrade private inherited
Definition at line 53 of file SubProtocol.h.
Super
using web::websocket::server::SubProtocol::Super = web::websocket::SubProtocol<web::websocket::server::SocketContextUpgrade> private
Definition at line 43 of file SubProtocol.h.
Constructor & Destructor Documentation
SubProtocol()
web::websocket::server::SubProtocol::SubProtocol (SubProtocolContext * subProtocolContext, const std::string & name, int pingInterval = 0, int maxFlyingPings = 3) protected
Definition at line 31 of file SubProtocol.cpp.
        : Super(subProtocolContext, name, pingInterval, maxFlyingPings) {
        GroupsManager::instance()->subscribe(this);
    }
References web::websocket::server::GroupsManager::instance(), web::websocket::SubProtocol< SocketContextUpgradeT >::SubProtocol(), and web::websocket::server::GroupsManager::subscribe().
~SubProtocol()
web::websocket::server::SubProtocol::~SubProtocol () override virtual
Reimplemented from web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >.
Definition at line 36 of file SubProtocol.cpp.
{
        GroupsManager::instance()->unsubscribe(this);
    }
References web::websocket::server::GroupsManager::instance(), and web::websocket::server::GroupsManager::unsubscribe().
Member Function Documentation
forEachClient()
void web::websocket::server::SubProtocol::forEachClient (const std::function< void(const SubProtocol *)> & sendToClient, bool excludeSelf = false)
Definition at line 79 of file SubProtocol.cpp.
{
        GroupsManager::instance()->forEachClient(group, sendToClient, excludeSelf ? this : nullptr);
    }
References web::websocket::server::GroupsManager::forEachClient(), group, and web::websocket::server::GroupsManager::instance().
getName()
const std::string & web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::getName () inherited
Definition at line 87 of file SubProtocol.hpp.
{
        return name;
    }
getSocketConnection()
core::socket::stream::SocketConnection * web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::getSocketConnection () inherited
Definition at line 88 of file SubProtocol.hpp.
{
        return subProtocolContext->getSocketConnection();
    }
onConnected()
virtual void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::onConnected () private pure virtual inherited
onDisconnected()
virtual void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::onDisconnected () private pure virtual inherited
onMessageData()
virtual void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::onMessageData (const char * chunk, std::size_t chunkLen) private pure virtual inherited
onMessageEnd()
virtual void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::onMessageEnd () private pure virtual inherited
onMessageError()
virtual void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::onMessageError (uint16_t errnum) private pure virtual inherited
onMessageStart()
virtual void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::onMessageStart (int opCode) private pure virtual inherited
onPongReceived()
void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::onPongReceived () private virtual inherited
Definition at line 84 of file SubProtocol.hpp.
{
        LOG(INFO) << "WebSocket: Pong received";
        flyingPings = 0;
    }
onSignal()
virtual bool web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::onSignal (int sig) private pure virtual inherited
sendBroadcast() [1/2]
void web::websocket::server::SubProtocol::sendBroadcast (const char * message, std::size_t messageLength, bool excludeSelf = false)
Definition at line 51 of file SubProtocol.cpp.
{
        GroupsManager::instance()->sendBroadcast(group, message, messageLength, excludeSelf ? this : nullptr);
    }
References group, web::websocket::server::GroupsManager::instance(), and web::websocket::server::GroupsManager::sendBroadcast().
sendBroadcast() [2/2]
void web::websocket::server::SubProtocol::sendBroadcast (const std::string & message, bool excludeSelf = false)
Definition at line 47 of file SubProtocol.cpp.
{
        GroupsManager::instance()->sendBroadcast(group, message, excludeSelf ? this : nullptr);
    }
References group, web::websocket::server::GroupsManager::instance(), and web::websocket::server::GroupsManager::sendBroadcast().
sendBroadcastEnd() [1/2]
void web::websocket::server::SubProtocol::sendBroadcastEnd (const char * message, std::size_t messageLength, bool excludeSelf = false)
Definition at line 71 of file SubProtocol.cpp.
{
        GroupsManager::instance()->sendBroadcastEnd(group, message, messageLength, excludeSelf ? this : nullptr);
    }
References group, web::websocket::server::GroupsManager::instance(), and web::websocket::server::GroupsManager::sendBroadcastEnd().
sendBroadcastEnd() [2/2]
void web::websocket::server::SubProtocol::sendBroadcastEnd (const std::string & message, bool excludeSelf = false)
Definition at line 75 of file SubProtocol.cpp.
{
        GroupsManager::instance()->sendBroadcastEnd(group, message.data(), message.length(), excludeSelf ? this : nullptr);
    }
References group, web::websocket::server::GroupsManager::instance(), and web::websocket::server::GroupsManager::sendBroadcastEnd().
sendBroadcastFrame() [1/2]
void web::websocket::server::SubProtocol::sendBroadcastFrame (const char * message, std::size_t messageLength, bool excludeSelf = false)
Definition at line 63 of file SubProtocol.cpp.
{
        GroupsManager::instance()->sendBroadcastFrame(group, message, messageLength, excludeSelf ? this : nullptr);
    }
References group, web::websocket::server::GroupsManager::instance(), and web::websocket::server::GroupsManager::sendBroadcastFrame().
sendBroadcastFrame() [2/2]
void web::websocket::server::SubProtocol::sendBroadcastFrame (const std::string & message, bool excludeSelf = false)
Definition at line 67 of file SubProtocol.cpp.
{
        GroupsManager::instance()->sendBroadcastFrame(group, message.data(), message.length(), excludeSelf ? this : nullptr);
    }
References group, web::websocket::server::GroupsManager::instance(), and web::websocket::server::GroupsManager::sendBroadcastFrame().
sendBroadcastStart() [1/2]
void web::websocket::server::SubProtocol::sendBroadcastStart (const char * message, std::size_t messageLength, bool excludeSelf = false)
Definition at line 55 of file SubProtocol.cpp.
{
        GroupsManager::instance()->sendBroadcastStart(group, message, messageLength, excludeSelf ? this : nullptr);
    }
References group, web::websocket::server::GroupsManager::instance(), and web::websocket::server::GroupsManager::sendBroadcastStart().
sendBroadcastStart() [2/2]
void web::websocket::server::SubProtocol::sendBroadcastStart (const std::string & message, bool excludeSelf = false)
Definition at line 59 of file SubProtocol.cpp.
{
        GroupsManager::instance()->sendBroadcastStart(group, message, excludeSelf ? this : nullptr);
    }
References group, web::websocket::server::GroupsManager::instance(), and web::websocket::server::GroupsManager::sendBroadcastStart().
sendClose()
void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::sendClose (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0) inherited
Definition at line 70 of file SubProtocol.hpp.
{
        subProtocolContext->sendClose(statusCode, reason, reasonLength);
    }
sendMessage() [1/2]
void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::sendMessage (const char * message, std::size_t messageLength) const inherited
Definition at line 61 of file SubProtocol.hpp.
{
        subProtocolContext->sendMessage(2, message, messageLength);
    }
sendMessage() [2/2]
void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::sendMessage (const std::string & message) const inherited
Definition at line 62 of file SubProtocol.hpp.
{
        subProtocolContext->sendMessage(1, message.data(), message.length());
    }
sendMessageEnd() [1/2]
void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::sendMessageEnd (const char * message, std::size_t messageLength) const inherited
Definition at line 67 of file SubProtocol.hpp.
{
        subProtocolContext->sendMessageEnd(message, messageLength);
    }
sendMessageEnd() [2/2]
void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::sendMessageEnd (const std::string & message) const inherited
Definition at line 68 of file SubProtocol.hpp.
{
        sendMessageEnd(message.data(), message.length());
    }
sendMessageFrame() [1/2]
void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::sendMessageFrame (const char * message, std::size_t messageLength) const inherited
Definition at line 65 of file SubProtocol.hpp.
{
        subProtocolContext->sendMessageFrame(message, messageLength);
    }
sendMessageFrame() [2/2]
void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::sendMessageFrame (const std::string & message) const inherited
Definition at line 66 of file SubProtocol.hpp.
{
        sendMessageFrame(message.data(), message.length());
    }
sendMessageStart() [1/2]
void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::sendMessageStart (const char * message, std::size_t messageLength) const inherited
Definition at line 63 of file SubProtocol.hpp.
{
        subProtocolContext->sendMessageStart(2, message, messageLength);
    }
sendMessageStart() [2/2]
void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::sendMessageStart (const std::string & message) const inherited
Definition at line 64 of file SubProtocol.hpp.
{
        subProtocolContext->sendMessageStart(1, message.data(), message.length());
    }
sendPing()
void web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::sendPing (const char * reason = nullptr, std::size_t reasonLength = 0) const inherited
Definition at line 69 of file SubProtocol.hpp.
{
        subProtocolContext->sendPing(reason, reasonLength);
    }
subscribe()
void web::websocket::server::SubProtocol::subscribe (const std::string & group)
Definition at line 40 of file SubProtocol.cpp.
{
        GroupsManager::instance()->subscribe(this, group);
        // subscibe(group, this);
        // unsubscribe(this->group, this);
        // this->group = group;
    }
References web::websocket::server::GroupsManager::instance(), and web::websocket::server::GroupsManager::subscribe().
Friends And Related Symbol Documentation
GroupsManager
friend class GroupsManager friend
Definition at line 82 of file SubProtocol.h.
web::websocket::SocketContextUpgrade
template<typename RequestT , typename ResponseT , typename SubProtocolT > friend class web::websocket::SocketContextUpgrade friend
Definition at line 80 of file SubProtocol.h.
Member Data Documentation
flyingPings
int web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::flyingPings private inherited
Definition at line 98 of file SubProtocol.h.
group
std::string web::websocket::server::SubProtocol::group private
Definition at line 77 of file SubProtocol.h.
Referenced by forEachClient(), sendBroadcast(), sendBroadcast(), sendBroadcastEnd(), sendBroadcastEnd(), sendBroadcastFrame(), sendBroadcastFrame(), sendBroadcastStart(), sendBroadcastStart(), web::websocket::server::GroupsManager::subscribe(), and web::websocket::server::GroupsManager::unsubscribe().
name
const std::string web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::name private inherited
Definition at line 91 of file SubProtocol.h.
pingTimer
core::timer::Timer web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::pingTimer private inherited
Definition at line 97 of file SubProtocol.h.
subProtocolContext
SubProtocolContext* web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >::subProtocolContext protected inherited
Definition at line 94 of file SubProtocol.h.
The documentation for this class was generated from the following files:
web/websocket/server/SubProtocol.h
web/websocket/server/SubProtocol.cpp