SNode.C: net::config::ConfigTls Class Reference
net::config::ConfigTls Class Reference
#include <ConfigTls.h>
Public Member Functions
ConfigTls (ConfigInstance *instance)
ConfigTls & setInitTimeout (const utils::Timeval &newInitTimeout)
utils::Timeval getInitTimeout () const
ConfigTls & setShutdownTimeout (const utils::Timeval &newShutdownTimeout)
utils::Timeval getShutdownTimeout () const
ConfigTls & setCertChain (const std::string &newCertChain)
std::string getCertChain () const
ConfigTls & setCertKey (const std::string &newCertKey)
std::string getCertKey () const
ConfigTls & setCertKeyPassword (const std::string &newCertKeyPassword)
std::string getCertKeyPassword () const
ConfigTls & setCaCertFile (const std::string &newCaCertFile)
std::string getCaCertFile () const
ConfigTls & setCaCertDir (const std::string &newCaCertDir)
std::string getCaCertDir () const
ConfigTls & setUseDefaultCaCertDir (bool set=true)
bool getUseDefaultCaCertDir () const
ConfigTls & setCipherList (const std::string &newCipherList)
std::string getCipherList () const
ConfigTls & setSslTlsOptions (ssl_option_t newSslTlsOptions)
ssl_option_t getSslTlsOptions () const
Protected Member Functions
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
Protected Attributes
CLI::App * section = nullptr
Private Attributes
CLI::Option * certChainOpt = nullptr
CLI::Option * certKeyOpt = nullptr
CLI::Option * certKeyPasswordOpt = nullptr
CLI::Option * caCertFileOpt = nullptr
CLI::Option * caCertDirOpt = nullptr
CLI::Option * useDefaultCaCertDirOpt = nullptr
CLI::Option * cipherListOpt = nullptr
CLI::Option * tlsOptionsOpt = nullptr
CLI::Option * initTimeoutOpt = nullptr
CLI::Option * shutdownTimeoutOpt = nullptr
ConfigInstance * instance = nullptr
uint8_t requiredCount = 0
Detailed Description
Definition at line 45 of file ConfigTls.h.
Constructor & Destructor Documentation
ConfigTls()
net::config::ConfigTls::ConfigTls (ConfigInstance * instance) explicit
Definition at line 30 of file ConfigTls.cpp.
        : ConfigSection(instance, "tls", "Configuration of SSL/TLS behavior") {
        add_option(certChainOpt, //
                   "--cert-chain",
                   "Certificate chain file",
                   "filename:PEM-FILE",
                   "");
        add_option(certKeyOpt, //
                   "--cert-key",
                   "Certificate key file",
                   "filename:PEM-FILE",
                   "");
        add_option(certKeyPasswordOpt,
                   "--cert-key-password",
                   "Password for the certificate key file",
                   "password",
                   "",
                   CLI::TypeValidator<std::string>());
        add_option(caCertFileOpt, //
                   "--ca-cert-file",
                   "CA-certificate file",
                   "filename:PEM-FILE",
                   "");
        add_option(caCertDirOpt, //
                   "--ca-cert-dir",
                   "CA-certificate directory",
                   "directory:PEM-CONTAINER-DIR",
                   "");
        add_flag(useDefaultCaCertDirOpt,
                 "--ca-use-default-cert-dir{true}",
                 "Use default CA-certificate directory",
                 "bool",
                 "false",
                 CLI::IsMember({"true", "false"}));
        add_option(cipherListOpt, //
                   "--cipher-list",
                   "Cipher list (OpenSSL syntax)",
                   "cipher_list",
                   "",
                   CLI::TypeValidator<std::string>("CIPHER"));
        add_option(tlsOptionsOpt, //
                   "--tls-options",
                   "OR combined SSL/TLS options (OpenSSL values)",
                   "options",
                   0,
                   CLI::TypeValidator<ssl_option_t>());
        add_option(initTimeoutOpt, //
                   "--init-timeout",
                   "SSL/TLS initialization timeout in seconds",
                   "timeout",
                   TLS_INIT_TIMEOUT,
                   CLI::PositiveNumber);
        add_option(shutdownTimeoutOpt, //
                   "--shutdown-timeout",
                   "SSL/TLS shutdown timeout in seconds",
                   "timeout",
                   TLS_SHUTDOWN_TIMEOUT,
                   CLI::PositiveNumber);
    }
References net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_option(), net::config::ConfigSection::add_option(), caCertDirOpt, caCertFileOpt, certChainOpt, certKeyOpt, certKeyPasswordOpt, cipherListOpt, net::config::ConfigSection::ConfigSection(), tlsOptionsOpt, and useDefaultCaCertDirOpt.
Referenced by net::config::ConfigTlsClient::ConfigTlsClient(), and net::config::ConfigTlsServer::ConfigTlsServer().
Member Function Documentation
add_flag() [1/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 110 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag(name, description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [2/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 125 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [3/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 64 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [4/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 71 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [5/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_flag() [6/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag_function() [1/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) protected inherited
Definition at line 134 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [2/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 155 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), and net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient().
add_option() [1/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) protected inherited
Definition at line 79 of file ConfigSection.cpp.
{
        if (!instance->getInstanceName().empty() && !section->get_display_name().empty()) {
            section->disabled(false);
        }
        opt = section //
                  ->add_option(name, description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigInstance::getInstanceName(), net::config::ConfigSection::instance, and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [2/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 95 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [3/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 100 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [4/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 46 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [5/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 53 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [6/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
Referenced by ConfigTls().
add_option() [7/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
getCaCertDir()
std::string net::config::ConfigTls::getCaCertDir () const
Definition at line 155 of file ConfigTls.cpp.
{
        return caCertDirOpt->as<std::string>();
    }
References caCertDirOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getCaCertFile()
std::string net::config::ConfigTls::getCaCertFile () const
Definition at line 143 of file ConfigTls.cpp.
{
        return caCertFileOpt->as<std::string>();
    }
References caCertFileOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getCertChain()
std::string net::config::ConfigTls::getCertChain () const
Definition at line 107 of file ConfigTls.cpp.
{
        return certChainOpt->as<std::string>();
    }
References certChainOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getCertKey()
std::string net::config::ConfigTls::getCertKey () const
Definition at line 119 of file ConfigTls.cpp.
{
        return certKeyOpt->as<std::string>();
    }
References certKeyOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getCertKeyPassword()
std::string net::config::ConfigTls::getCertKeyPassword () const
Definition at line 131 of file ConfigTls.cpp.
{
        return certKeyPasswordOpt->as<std::string>();
    }
References certKeyPasswordOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getCipherList()
std::string net::config::ConfigTls::getCipherList () const
Definition at line 179 of file ConfigTls.cpp.
{
        return cipherListOpt->as<std::string>();
    }
References cipherListOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getInitTimeout()
utils::Timeval net::config::ConfigTls::getInitTimeout () const
Definition at line 203 of file ConfigTls.cpp.
{
        return initTimeoutOpt->as<utils::Timeval>();
    }
References initTimeoutOpt.
getShutdownTimeout()
utils::Timeval net::config::ConfigTls::getShutdownTimeout () const
Definition at line 215 of file ConfigTls.cpp.
{
        return shutdownTimeoutOpt //
            ->as<utils::Timeval>();
    }
References shutdownTimeoutOpt.
getSslTlsOptions()
ssl_option_t net::config::ConfigTls::getSslTlsOptions () const
Definition at line 191 of file ConfigTls.cpp.
{
        return tlsOptionsOpt->as<ssl_option_t>();
    }
References tlsOptionsOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getUseDefaultCaCertDir()
bool net::config::ConfigTls::getUseDefaultCaCertDir () const
Definition at line 167 of file ConfigTls.cpp.
{
        return useDefaultCaCertDirOpt->as<bool>();
    }
References useDefaultCaCertDirOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
required() [1/2]
bool net::config::ConfigSection::required () const protected inherited
Definition at line 75 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [2/2]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) protected inherited
Definition at line 58 of file ConfigSection.cpp.
{
        if (req != opt->get_required()) {
            if (req) {
                ++requiredCount;
                section->needs(opt);
                opt->default_str("");
            } else {
                --requiredCount;
                section->remove_needs(opt);
            }
            opt->required(req);
            instance->required(section, requiredCount > 0);
        }
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
setCaCertDir()
ConfigTls & net::config::ConfigTls::setCaCertDir (const std::string & newCaCertDir)
Definition at line 147 of file ConfigTls.cpp.
{
        caCertDirOpt //
            ->default_val(newCaCertDir)
            ->clear();
        return *this;
    }
References caCertDirOpt.
setCaCertFile()
ConfigTls & net::config::ConfigTls::setCaCertFile (const std::string & newCaCertFile)
Definition at line 135 of file ConfigTls.cpp.
{
        caCertFileOpt //
            ->default_val(newCaCertFile)
            ->clear();
        return *this;
    }
References caCertFileOpt.
setCertChain()
ConfigTls & net::config::ConfigTls::setCertChain (const std::string & newCertChain)
Definition at line 99 of file ConfigTls.cpp.
{
        certChainOpt //
            ->default_val(newCertChain)
            ->clear();
        return *this;
    }
References certChainOpt.
setCertKey()
ConfigTls & net::config::ConfigTls::setCertKey (const std::string & newCertKey)
Definition at line 111 of file ConfigTls.cpp.
{
        certKeyOpt //
            ->default_val(newCertKey)
            ->clear();
        return *this;
    }
References certKeyOpt.
setCertKeyPassword()
ConfigTls & net::config::ConfigTls::setCertKeyPassword (const std::string & newCertKeyPassword)
Definition at line 123 of file ConfigTls.cpp.
{
        certKeyPasswordOpt //
            ->default_val(newCertKeyPassword)
            ->clear();
        return *this;
    }
References certKeyPasswordOpt.
setCipherList()
ConfigTls & net::config::ConfigTls::setCipherList (const std::string & newCipherList)
Definition at line 171 of file ConfigTls.cpp.
{
        cipherListOpt //
            ->default_val(newCipherList)
            ->clear();
        return *this;
    }
References cipherListOpt.
setInitTimeout()
ConfigTls & net::config::ConfigTls::setInitTimeout (const utils::Timeval & newInitTimeout)
Definition at line 195 of file ConfigTls.cpp.
{
        initTimeoutOpt //
            ->default_val(newInitTimeout)
            ->clear();
        return *this;
    }
References initTimeoutOpt.
setShutdownTimeout()
ConfigTls & net::config::ConfigTls::setShutdownTimeout (const utils::Timeval & newShutdownTimeout)
Definition at line 207 of file ConfigTls.cpp.
{
        shutdownTimeoutOpt //
            ->default_val(newShutdownTimeout)
            ->clear();
        return *this;
    }
References shutdownTimeoutOpt.
setSslTlsOptions()
ConfigTls & net::config::ConfigTls::setSslTlsOptions (ssl_option_t newSslTlsOptions)
Definition at line 183 of file ConfigTls.cpp.
{
        tlsOptionsOpt //
            ->default_val(newSslTlsOptions)
            ->clear();
        return *this;
    }
References tlsOptionsOpt.
setUseDefaultCaCertDir()
ConfigTls & net::config::ConfigTls::setUseDefaultCaCertDir (bool set = true)
Definition at line 159 of file ConfigTls.cpp.
{
        useDefaultCaCertDirOpt //
            ->default_val(set ? "true" : "false")
            ->clear();
        return *this;
    }
References useDefaultCaCertDirOpt.
Member Data Documentation
caCertDirOpt
CLI::Option* net::config::ConfigTls::caCertDirOpt = nullptr private
Definition at line 84 of file ConfigTls.h.
Referenced by ConfigTls(), getCaCertDir(), and setCaCertDir().
caCertFileOpt
CLI::Option* net::config::ConfigTls::caCertFileOpt = nullptr private
Definition at line 83 of file ConfigTls.h.
Referenced by ConfigTls(), getCaCertFile(), and setCaCertFile().
certChainOpt
CLI::Option* net::config::ConfigTls::certChainOpt = nullptr private
Definition at line 80 of file ConfigTls.h.
Referenced by ConfigTls(), getCertChain(), and setCertChain().
certKeyOpt
CLI::Option* net::config::ConfigTls::certKeyOpt = nullptr private
Definition at line 81 of file ConfigTls.h.
Referenced by ConfigTls(), getCertKey(), and setCertKey().
certKeyPasswordOpt
CLI::Option* net::config::ConfigTls::certKeyPasswordOpt = nullptr private
Definition at line 82 of file ConfigTls.h.
Referenced by ConfigTls(), getCertKeyPassword(), and setCertKeyPassword().
cipherListOpt
CLI::Option* net::config::ConfigTls::cipherListOpt = nullptr private
Definition at line 86 of file ConfigTls.h.
Referenced by ConfigTls(), getCipherList(), and setCipherList().
initTimeoutOpt
CLI::Option* net::config::ConfigTls::initTimeoutOpt = nullptr private
Definition at line 88 of file ConfigTls.h.
Referenced by getInitTimeout(), and setInitTimeout().
instance
ConfigInstance* net::config::ConfigSection::instance = nullptr private inherited
Definition at line 121 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), and net::config::ConfigSection::required().
requiredCount
uint8_t net::config::ConfigSection::requiredCount = 0 private inherited
Definition at line 123 of file ConfigSection.h.
Referenced by net::config::ConfigSection::required(), and net::config::ConfigSection::required().
section
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 126 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
shutdownTimeoutOpt
CLI::Option* net::config::ConfigTls::shutdownTimeoutOpt = nullptr private
Definition at line 89 of file ConfigTls.h.
Referenced by getShutdownTimeout(), and setShutdownTimeout().
tlsOptionsOpt
CLI::Option* net::config::ConfigTls::tlsOptionsOpt = nullptr private
Definition at line 87 of file ConfigTls.h.
Referenced by ConfigTls(), getSslTlsOptions(), and setSslTlsOptions().
useDefaultCaCertDirOpt
CLI::Option* net::config::ConfigTls::useDefaultCaCertDirOpt = nullptr private
Definition at line 85 of file ConfigTls.h.
Referenced by ConfigTls(), getUseDefaultCaCertDir(), and setUseDefaultCaCertDir().
The documentation for this class was generated from the following files:
net/config/ConfigTls.h
net/config/ConfigTls.cpp