SNode.C: net::config::ConfigPhysicalSocketClient Class Reference
net::config::ConfigPhysicalSocketClient Class Reference
#include <ConfigPhysicalSocketClient.h>
Public Member Functions
ConfigPhysicalSocketClient & setReconnect (bool reconnect=true)
bool getReconnect () const
ConfigPhysicalSocketClient & setReconnectTime (double time)
double getReconnectTime () const
ConfigPhysicalSocketClient & setConnectTimeout (const utils::Timeval &connectTimeout)
utils::Timeval getConnectTimeout () const
Public Member Functions inherited from net::config::ConfigPhysicalSocket
const std::map< int, std::map< int, net::phy::PhysicalSocketOption > > & getSocketOptions () const
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, int optValue)
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, const std::string &optValue)
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, const std::vector< char > &optValue)
ConfigPhysicalSocket & removeSocketOption (int optLevel, int optName)
ConfigPhysicalSocket & setRetry (bool retry=true)
bool getRetry () const
ConfigPhysicalSocket & setRetryOnFatal (bool retry=true)
bool getRetryOnFatal () const
ConfigPhysicalSocket & setRetryTimeout (double sec)
double getRetryTimeout () const
ConfigPhysicalSocket & setRetryTries (unsigned int tries=0)
unsigned int getRetryTries () const
ConfigPhysicalSocket & setRetryBase (double base)
double getRetryBase () const
ConfigPhysicalSocket & setRetryLimit (unsigned int limit)
unsigned int getRetryLimit () const
ConfigPhysicalSocket & setRetryJitter (double percent)
double getRetryJitter () const
template<typename ConcretConfigPhysicalSocket>
ConfigPhysicalSocket (ConfigInstance *instance, ConcretConfigPhysicalSocket *section)
Public Member Functions inherited from net::config::ConfigSection
template<typename T>
ConfigSection (ConfigInstance *instance, T *sectionPtr, const std::string &group="Sections")
~ConfigSection () override
ConfigSection (const ConfigSection &)=delete
ConfigSection (ConfigSection &&)=delete
ConfigSection & operator= (const ConfigSection &)=delete
Public Member Functions inherited from utils::SubCommand
SubCommand (const SubCommand &)=delete
SubCommand (SubCommand &&)=delete
SubCommand & operator= (const SubCommand &)=delete
SubCommand & operator= (SubCommand &&)=delete
virtual ~SubCommand ()
std::string getName () const
std::string version () const
void parse (int argc, char *argv[])
CLI::Option * setConfig (const std::string &defaultConfigFile) const
CLI::Option * setLogFile (const std::string &defaultLogFile) const
CLI::Option * setVersionFlag (const std::string &version) const
bool hasParent () const
SubCommand * getParent ()
SubCommand * allowExtras (bool allow=true)
SubCommand * required (bool required=true, bool force=true)
SubCommand * required (SubCommand *subCommand, bool required=true)
SubCommand * required (CLI::Option *option, bool required=true)
SubCommand * needs (SubCommand *subCommand, bool needs=true)
SubCommand * disabled (SubCommand *subCommand, bool disabled=true)
SubCommand * setRequireCallback (const std::function< void(void)> &callback)
SubCommand * finalCallback (const std::function< void()> &finalCallback)
std::string configToStr () const
std::string help (const CLI::App *helpApp, const CLI::AppFormatMode &mode) const
template<typename NewSubCommand, typename... Args>
NewSubCommand * newSubCommand (Args &&... args)
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand ()
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand () const
CLI::Option * getOption (const std::string &name) const
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator) const
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Protected Member Functions
ConfigPhysicalSocketClient (ConfigInstance *instance)
~ConfigPhysicalSocketClient () override
Protected Member Functions inherited from net::config::ConfigPhysicalSocket
template<typename ConcretConfigPhysicalSocketT>
ConfigPhysicalSocket (ConfigInstance *instance, ConcretConfigPhysicalSocketT *section)
~ConfigPhysicalSocket () override
CLI::Option * addSocketOption (const std::string &name, int optLevel, int optName, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Protected Member Functions inherited from utils::SubCommand
SubCommand (SubCommand *parent, std::shared_ptr< utils::AppWithPtr > appWithPtr, const std::string &group, bool final)
template<typename ConcretSubCommand>
SubCommand (SubCommand *parent, ConcretSubCommand *concretSubCommand, const std::string &group, bool final=true)
SubCommand * description (const std::string &description)
SubCommand * footer (const std::string &footer)
template<typename ValueTypeT>
CLI::Option * setDefaultValue (CLI::Option *option, const ValueTypeT &value, bool clear=true) const
CLI::Option * setConfigurable (CLI::Option *option, bool configurable) const
Private Types
using Super = ConfigPhysicalSocket
Private Attributes
CLI::Option * reconnectOpt = nullptr
CLI::Option * reconnectTimeOpt = nullptr
CLI::Option * connectTimeoutOpt = nullptr
Additional Inherited Members
Static Public Member Functions inherited from utils::SubCommand
static CLI::App * getHelpTriggerApp ()
static CLI::App * getShowConfigTriggerApp ()
static CLI::App * getCommandlineTriggerApp ()
Static Public Attributes inherited from net::config::ConfigPhysicalSocket
static constexpr std::string_view NAME {"socket"}
static constexpr std::string_view DESCRIPTION {"Configuration of socket behavior"}
Static Public Attributes inherited from utils::SubCommand
static std::shared_ptr< CLI::Formatter > sectionFormatter = makeSectionFormatter()
Static Protected Attributes inherited from utils::SubCommand
static std::map< std::string, std::string > aliases
static CLI::App * helpTriggerApp = nullptr
static CLI::App * showConfigTriggerApp = nullptr
static CLI::App * commandlineTriggerApp = nullptr
Detailed Description
Definition at line 60 of file ConfigPhysicalSocketClient.h.
Member Typedef Documentation
Super
using net::config::ConfigPhysicalSocketClient::Super = ConfigPhysicalSocket private
Definition at line 62 of file ConfigPhysicalSocketClient.h.
Constructor & Destructor Documentation
ConfigPhysicalSocketClient()
net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient (ConfigInstance * instance) explicit protected
Definition at line 59 of file ConfigPhysicalSocketClient.cpp.
        : ConfigPhysicalSocket(instance, this) {
        reconnectOpt = addFlagFunction( //
            "--reconnect{true}",
            [this]() {
                if (!this->reconnectOpt->as<bool>()) {
                    this->reconnectTimeOpt->clear();
                }
            },
            "Auto-reconnection in the event of a connection interruption",
            "bool",
            XSTR(RECONNECT),
            CLI::IsMember({"true", "false"}));
        reconnectTimeOpt = addOption( //
            "--reconnect-time",
            "Duration after disconnect before reconnect",
            "sec",
            RECONNECT_TIME,
            CLI::NonNegativeNumber);
        reconnectTimeOpt->needs(reconnectOpt);
        connectTimeoutOpt = addOption( //
            "--connect-timeout",
            "Connect timeout",
            "timeout",
            CONNECT_TIMEOUT,
            CLI::NonNegativeNumber);
    }
References utils::SubCommand::addFlagFunction(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), connectTimeoutOpt, reconnectOpt, and reconnectTimeOpt.
~ConfigPhysicalSocketClient()
net::config::ConfigPhysicalSocketClient::~ConfigPhysicalSocketClient () override protected
Definition at line 89 of file ConfigPhysicalSocketClient.cpp.
{
    }
Member Function Documentation
getConnectTimeout()
utils::Timeval net::config::ConfigPhysicalSocketClient::getConnectTimeout () const
Definition at line 124 of file ConfigPhysicalSocketClient.cpp.
{
        return utils::Timeval(connectTimeoutOpt->as<double>());
    }
References connectTimeoutOpt, and utils::Timeval::Timeval().
getReconnect()
bool net::config::ConfigPhysicalSocketClient::getReconnect () const
Definition at line 104 of file ConfigPhysicalSocketClient.cpp.
{
        return reconnectOpt->as<bool>();
    }
References reconnectOpt.
getReconnectTime()
double net::config::ConfigPhysicalSocketClient::getReconnectTime () const
Definition at line 114 of file ConfigPhysicalSocketClient.cpp.
{
        return reconnectTimeOpt->as<double>();
    }
References reconnectTimeOpt.
setConnectTimeout()
ConfigPhysicalSocketClient & net::config::ConfigPhysicalSocketClient::setConnectTimeout (const utils::Timeval & connectTimeout)
Definition at line 118 of file ConfigPhysicalSocketClient.cpp.
{
        setDefaultValue(connectTimeoutOpt, connectTimeout);
        return *this;
    }
References connectTimeoutOpt, and utils::SubCommand::setDefaultValue().
setReconnect()
ConfigPhysicalSocketClient & net::config::ConfigPhysicalSocketClient::setReconnect (bool reconnect = true)
Definition at line 92 of file ConfigPhysicalSocketClient.cpp.
{
        setDefaultValue(reconnectOpt, reconnect ? "true" : "false");
        if (reconnect) {
            reconnectTimeOpt->remove_needs(reconnectOpt);
        } else {
            reconnectTimeOpt->needs(reconnectOpt);
        }
        return *this;
    }
References reconnectOpt, reconnectTimeOpt, and utils::SubCommand::setDefaultValue().
setReconnectTime()
ConfigPhysicalSocketClient & net::config::ConfigPhysicalSocketClient::setReconnectTime (double time)
Definition at line 108 of file ConfigPhysicalSocketClient.cpp.
{
        setDefaultValue(reconnectTimeOpt, time);
        return *this;
    }
References reconnectTimeOpt, and utils::SubCommand::setDefaultValue().
Member Data Documentation
connectTimeoutOpt
CLI::Option* net::config::ConfigPhysicalSocketClient::connectTimeoutOpt = nullptr private
Definition at line 83 of file ConfigPhysicalSocketClient.h.
Referenced by ConfigPhysicalSocketClient(), getConnectTimeout(), and setConnectTimeout().
reconnectOpt
CLI::Option* net::config::ConfigPhysicalSocketClient::reconnectOpt = nullptr private
Definition at line 80 of file ConfigPhysicalSocketClient.h.
Referenced by ConfigPhysicalSocketClient(), getReconnect(), and setReconnect().
reconnectTimeOpt
CLI::Option* net::config::ConfigPhysicalSocketClient::reconnectTimeOpt = nullptr private
Definition at line 81 of file ConfigPhysicalSocketClient.h.
Referenced by ConfigPhysicalSocketClient(), getReconnectTime(), setReconnect(), and setReconnectTime().
The documentation for this class was generated from the following files:
net/config/ConfigPhysicalSocketClient.h
net/config/ConfigPhysicalSocketClient.cpp