SNode.C: iot::mqtt_fast::ControlPacket Class Reference
iot::mqtt_fast::ControlPacket Class Reference
#include <ControlPacket.h>
Public Member Functions
ControlPacket (uint8_t type, uint8_t reserved=0)
ControlPacket (iot::mqtt_fast::ControlPacketFactory &controlPacketFactory)
ControlPacket (const ControlPacket &)=delete
ControlPacket (ControlPacket &&)=delete
ControlPacket & operator= (const ControlPacket &)=delete
ControlPacket & operator= (ControlPacket &&)=delete
uint8_t getType () const
uint8_t getReserved () const
uint64_t getRemainingLength () const
std::vector< char > getPacket ()
bool isError () const
Protected Member Functions
std::vector< char > & getValue ()
uint8_t getInt8 ()
uint16_t getInt16 ()
uint32_t getInt32 ()
uint64_t getInt64 ()
uint32_t getIntV ()
std::string getString ()
std::string getStringRaw ()
std::list< uint8_t > getUint8ListRaw ()
void putInt8 (uint8_t value)
void putInt16 (uint16_t value)
void putInt32 (uint32_t value)
void putInt64 (uint64_t value)
void putIntV (uint32_t value)
void putString (const std::string &value)
void putStringRaw (const std::string &value)
void putUint8ListRaw (const std::list< uint8_t > &value)
bool isError ()
Protected Attributes
bool error = false
Private Attributes
uint8_t type
uint8_t reserved
iot::mqtt_fast::types::Binary data
Detailed Description
Definition at line 62 of file ControlPacket.h.
Constructor & Destructor Documentation
ControlPacket() [1/4]
iot::mqtt_fast::ControlPacket::ControlPacket (uint8_t type, uint8_t reserved = 0) explicit
Definition at line 54 of file ControlPacket.cpp.
        : type(type)
        , reserved(reserved) {
    }
References reserved, and type.
Referenced by iot::mqtt_fast::packets::Connack::Connack(), iot::mqtt_fast::packets::Connect::Connect(), iot::mqtt_fast::packets::Disconnect::Disconnect(), iot::mqtt_fast::packets::Pingreq::Pingreq(), iot::mqtt_fast::packets::Pingresp::Pingresp(), iot::mqtt_fast::packets::Puback::Puback(), iot::mqtt_fast::packets::Pubcomp::Pubcomp(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Pubrec::Pubrec(), iot::mqtt_fast::packets::Pubrel::Pubrel(), iot::mqtt_fast::packets::Suback::Suback(), iot::mqtt_fast::packets::Subscribe::Subscribe(), iot::mqtt_fast::packets::Unsuback::Unsuback(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
ControlPacket() [2/4]
iot::mqtt_fast::ControlPacket::ControlPacket (iot::mqtt_fast::ControlPacketFactory & controlPacketFactory) explicit
Definition at line 59 of file ControlPacket.cpp.
        : type(controlPacketFactory.getPacketType())
        , reserved(controlPacketFactory.getPacketFlags())
        , data(std::move(controlPacketFactory.getPacket())) {
    }
References data, iot::mqtt_fast::ControlPacketFactory::getPacket(), iot::mqtt_fast::ControlPacketFactory::getPacketFlags(), iot::mqtt_fast::ControlPacketFactory::getPacketType(), reserved, and type.
Referenced by iot::mqtt_fast::packets::Connack::Connack(), iot::mqtt_fast::packets::Connect::Connect(), iot::mqtt_fast::packets::Disconnect::Disconnect(), iot::mqtt_fast::packets::Pingreq::Pingreq(), iot::mqtt_fast::packets::Pingresp::Pingresp(), iot::mqtt_fast::packets::Puback::Puback(), iot::mqtt_fast::packets::Pubcomp::Pubcomp(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Pubrec::Pubrec(), iot::mqtt_fast::packets::Pubrel::Pubrel(), iot::mqtt_fast::packets::Suback::Suback(), iot::mqtt_fast::packets::Subscribe::Subscribe(), iot::mqtt_fast::packets::Unsuback::Unsuback(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
ControlPacket() [3/4]
iot::mqtt_fast::ControlPacket::ControlPacket (const ControlPacket &) delete
ControlPacket() [4/4]
iot::mqtt_fast::ControlPacket::ControlPacket (ControlPacket &&) delete
Member Function Documentation
getInt16()
uint16_t iot::mqtt_fast::ControlPacket::getInt16 () protected
Definition at line 109 of file ControlPacket.cpp.
{
        return data.getInt16();
    }
References data, and iot::mqtt_fast::types::Binary::getInt16().
Referenced by iot::mqtt_fast::packets::Connect::Connect(), iot::mqtt_fast::packets::Puback::Puback(), iot::mqtt_fast::packets::Pubcomp::Pubcomp(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Pubrec::Pubrec(), iot::mqtt_fast::packets::Pubrel::Pubrel(), iot::mqtt_fast::packets::Suback::Suback(), iot::mqtt_fast::packets::Subscribe::Subscribe(), iot::mqtt_fast::packets::Unsuback::Unsuback(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
getInt32()
uint32_t iot::mqtt_fast::ControlPacket::getInt32 () protected
Definition at line 113 of file ControlPacket.cpp.
{
        return data.getInt32();
    }
References data, and iot::mqtt_fast::types::Binary::getInt32().
getInt64()
uint64_t iot::mqtt_fast::ControlPacket::getInt64 () protected
Definition at line 117 of file ControlPacket.cpp.
{
        return data.getInt64();
    }
References data, and iot::mqtt_fast::types::Binary::getInt64().
getInt8()
uint8_t iot::mqtt_fast::ControlPacket::getInt8 () protected
Definition at line 105 of file ControlPacket.cpp.
{
        return data.getInt8();
    }
References data, and iot::mqtt_fast::types::Binary::getInt8().
Referenced by iot::mqtt_fast::packets::Connack::Connack(), iot::mqtt_fast::packets::Connect::Connect(), and iot::mqtt_fast::packets::Subscribe::Subscribe().
getIntV()
uint32_t iot::mqtt_fast::ControlPacket::getIntV () protected
Definition at line 121 of file ControlPacket.cpp.
{
        return data.getIntV();
    }
References data, and iot::mqtt_fast::types::Binary::getIntV().
getPacket()
std::vector< char > iot::mqtt_fast::ControlPacket::getPacket ()
Definition at line 77 of file ControlPacket.cpp.
{
        std::vector<char> packet;
        packet.push_back(static_cast<char>((type << 0x04) | (reserved & 0x0F)));
        uint64_t remainingLength = data.getLength();
        do {
            uint8_t encodedByte = static_cast<uint8_t>(remainingLength % 0x80);
            remainingLength /= 0x80;
            if (remainingLength > 0) {
                encodedByte |= 0x80;
            }
            packet.push_back(static_cast<char>(encodedByte));
        } while (remainingLength > 0);
        packet.insert(packet.end(), data.getValue().begin(), data.getValue().end());
        return packet;
    }
References data, iot::mqtt_fast::types::Binary::getLength(), iot::mqtt_fast::types::Binary::getValue(), reserved, and type.
Referenced by iot::mqtt_fast::SocketContext::send(), and iot::mqtt_fast::SocketContext::send().
getRemainingLength()
uint64_t iot::mqtt_fast::ControlPacket::getRemainingLength () const
Definition at line 73 of file ControlPacket.cpp.
{
        return data.getLength();
    }
References data, and iot::mqtt_fast::types::Binary::getLength().
getReserved()
uint8_t iot::mqtt_fast::ControlPacket::getReserved () const
Definition at line 69 of file ControlPacket.cpp.
{
        return reserved;
    }
References reserved.
getString()
std::string iot::mqtt_fast::ControlPacket::getString () protected
Definition at line 125 of file ControlPacket.cpp.
{
        return data.getString();
    }
References data, and iot::mqtt_fast::types::Binary::getString().
Referenced by iot::mqtt_fast::packets::Connect::Connect(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Subscribe::Subscribe(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
getStringRaw()
std::string iot::mqtt_fast::ControlPacket::getStringRaw () protected
Definition at line 129 of file ControlPacket.cpp.
{
        return data.getStringRaw();
    }
References data, and iot::mqtt_fast::types::Binary::getStringRaw().
Referenced by iot::mqtt_fast::packets::Publish::Publish().
getType()
uint8_t iot::mqtt_fast::ControlPacket::getType () const
Definition at line 65 of file ControlPacket.cpp.
{
        return type;
    }
References type.
getUint8ListRaw()
std::list< uint8_t > iot::mqtt_fast::ControlPacket::getUint8ListRaw () protected
Definition at line 133 of file ControlPacket.cpp.
{
        return data.getUint8ListRaw();
    }
References data, and iot::mqtt_fast::types::Binary::getUint8ListRaw().
Referenced by iot::mqtt_fast::packets::Suback::Suback().
getValue()
std::vector< char > & iot::mqtt_fast::ControlPacket::getValue () protected
Definition at line 101 of file ControlPacket.cpp.
{
        return data.getValue();
    }
References data, and iot::mqtt_fast::types::Binary::getValue().
isError() [1/2]
bool iot::mqtt_fast::ControlPacket::isError () protected
Definition at line 169 of file ControlPacket.cpp.
{
        return data.isError();
    }
References data, and iot::mqtt_fast::types::TypeBase::isError().
Referenced by iot::mqtt_fast::packets::Connack::Connack(), iot::mqtt_fast::packets::Connect::Connect(), iot::mqtt_fast::packets::Disconnect::Disconnect(), iot::mqtt_fast::packets::Pingreq::Pingreq(), iot::mqtt_fast::packets::Pingresp::Pingresp(), iot::mqtt_fast::packets::Puback::Puback(), iot::mqtt_fast::packets::Pubcomp::Pubcomp(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Pubrec::Pubrec(), iot::mqtt_fast::packets::Pubrel::Pubrel(), iot::mqtt_fast::packets::Suback::Suback(), iot::mqtt_fast::packets::Subscribe::Subscribe(), iot::mqtt_fast::packets::Unsuback::Unsuback(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
isError() [2/2]
bool iot::mqtt_fast::ControlPacket::isError () const
Definition at line 97 of file ControlPacket.cpp.
{
        return error;
    }
References error.
operator=() [1/2]
ControlPacket & iot::mqtt_fast::ControlPacket::operator= (const ControlPacket &) delete
operator=() [2/2]
ControlPacket & iot::mqtt_fast::ControlPacket::operator= (ControlPacket &&) delete
putInt16()
void iot::mqtt_fast::ControlPacket::putInt16 (uint16_t value) protected
Definition at line 141 of file ControlPacket.cpp.
{
        data.putInt16(value);
    }
References data, and iot::mqtt_fast::types::Binary::putInt16().
Referenced by iot::mqtt_fast::packets::Connect::Connect(), iot::mqtt_fast::packets::Puback::Puback(), iot::mqtt_fast::packets::Pubcomp::Pubcomp(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Pubrec::Pubrec(), iot::mqtt_fast::packets::Pubrel::Pubrel(), iot::mqtt_fast::packets::Suback::Suback(), iot::mqtt_fast::packets::Subscribe::Subscribe(), iot::mqtt_fast::packets::Unsuback::Unsuback(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
putInt32()
void iot::mqtt_fast::ControlPacket::putInt32 (uint32_t value) protected
Definition at line 145 of file ControlPacket.cpp.
{
        data.putInt32(value);
    }
References data, and iot::mqtt_fast::types::Binary::putInt32().
putInt64()
void iot::mqtt_fast::ControlPacket::putInt64 (uint64_t value) protected
Definition at line 149 of file ControlPacket.cpp.
{
        data.putInt64(value);
    }
References data, and iot::mqtt_fast::types::Binary::putInt64().
putInt8()
void iot::mqtt_fast::ControlPacket::putInt8 (uint8_t value) protected
Definition at line 137 of file ControlPacket.cpp.
{
        data.putInt8(value);
    }
References data, and iot::mqtt_fast::types::Binary::putInt8().
Referenced by iot::mqtt_fast::packets::Connack::Connack(), iot::mqtt_fast::packets::Connect::Connect(), and iot::mqtt_fast::packets::Subscribe::Subscribe().
putIntV()
void iot::mqtt_fast::ControlPacket::putIntV (uint32_t value) protected
Definition at line 153 of file ControlPacket.cpp.
{
        data.putIntV(value);
    }
References data, and iot::mqtt_fast::types::Binary::putIntV().
putString()
void iot::mqtt_fast::ControlPacket::putString (const std::string & value) protected
Definition at line 157 of file ControlPacket.cpp.
{
        data.putString(value);
    }
References data, and iot::mqtt_fast::types::Binary::putString().
Referenced by iot::mqtt_fast::packets::Connect::Connect(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Subscribe::Subscribe(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
putStringRaw()
void iot::mqtt_fast::ControlPacket::putStringRaw (const std::string & value) protected
Definition at line 161 of file ControlPacket.cpp.
{
        data.putStringRaw(value);
    }
References data, and iot::mqtt_fast::types::Binary::putStringRaw().
Referenced by iot::mqtt_fast::packets::Publish::Publish().
putUint8ListRaw()
void iot::mqtt_fast::ControlPacket::putUint8ListRaw (const std::list< uint8_t > & value) protected
Definition at line 165 of file ControlPacket.cpp.
{
        data.putUint8ListRaw(value);
    }
References data, and iot::mqtt_fast::types::Binary::putUint8ListRaw().
Referenced by iot::mqtt_fast::packets::Suback::Suback().
Member Data Documentation
data
iot::mqtt_fast::types::Binary iot::mqtt_fast::ControlPacket::data private
Definition at line 107 of file ControlPacket.h.
Referenced by ControlPacket(), getInt16(), getInt32(), getInt64(), getInt8(), getIntV(), getPacket(), getRemainingLength(), getString(), getStringRaw(), getUint8ListRaw(), getValue(), isError(), putInt16(), putInt32(), putInt64(), putInt8(), putIntV(), putString(), putStringRaw(), and putUint8ListRaw().
error
bool iot::mqtt_fast::ControlPacket::error = false protected
Definition at line 110 of file ControlPacket.h.
Referenced by iot::mqtt_fast::packets::Connack::Connack(), iot::mqtt_fast::packets::Connect::Connect(), iot::mqtt_fast::packets::Disconnect::Disconnect(), isError(), iot::mqtt_fast::packets::Pingreq::Pingreq(), iot::mqtt_fast::packets::Pingresp::Pingresp(), iot::mqtt_fast::packets::Puback::Puback(), iot::mqtt_fast::packets::Pubcomp::Pubcomp(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Pubrec::Pubrec(), iot::mqtt_fast::packets::Pubrel::Pubrel(), iot::mqtt_fast::packets::Suback::Suback(), iot::mqtt_fast::packets::Subscribe::Subscribe(), iot::mqtt_fast::packets::Unsuback::Unsuback(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
reserved
uint8_t iot::mqtt_fast::ControlPacket::reserved private
Definition at line 105 of file ControlPacket.h.
Referenced by ControlPacket(), ControlPacket(), getPacket(), and getReserved().
type
uint8_t iot::mqtt_fast::ControlPacket::type private
Definition at line 104 of file ControlPacket.h.
Referenced by ControlPacket(), ControlPacket(), getPacket(), and getType().
The documentation for this class was generated from the following files:
iot/mqtt-fast/ControlPacket.h
iot/mqtt-fast/ControlPacket.cpp