SNode.C: core::socket::stream::legacy::SocketWriter Class Reference
core::socket::stream::legacy::SocketWriter Class Reference abstract
#include <SocketWriter.h>
Public Member Functions
int getRegisteredFd () const
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Static Public Member Functions
static void atNextTick (const std::function< void(void)> &callBack)
Protected Member Functions
void setBlockSize (std::size_t writeBlockSize)
void sendToPeer (const char *chunk, std::size_t chunkLen)
bool streamToPeer (core::pipe::Source *source)
void streamEof ()
void shutdownWrite (const std::function< void()> &onShutdown)
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
void observed ()
void unObserved ()
virtual void unobservedEvent ()=0
Protected Attributes
bool markShutdown = false
std::function< void()> onShutdown
std::vector< char > writePuffer
bool shutdownInProgress = false
Private Types
using Super = core::socket::stream::SocketWriter
Private Member Functions
ssize_t write (const char *chunk, std::size_t chunkLen) override
void writeEvent () final
void signalEvent (int sigNum) final
void doWrite ()
virtual bool onSignal (int sigNum)=0
virtual void doWriteShutdown (const std::function< void()> &onShutdown)=0
virtual void writeTimeout ()
void dispatchEvent () final
void timeoutEvent () final
void onEvent (const utils::Timeval &currentTime) final
void triggered (const utils::Timeval &currentTime)
void setEnabled (const utils::Timeval &currentTime)
void setDisabled ()
Private Attributes
std::function< void(int)> onStatus
core::pipe::Source * source = nullptr
std::size_t blockSize = 0
utils::Timeval terminateTimeout
DescriptorEventPublisher & descriptorEventPublisher
int observedFd = -1
bool enabled = false
bool suspended = false
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
int observationCounter = 0
Event event
Detailed Description
Definition at line 34 of file SocketWriter.h.
Member Typedef Documentation
Super
using core::socket::stream::legacy::SocketWriter::Super = core::socket::stream::SocketWriter private
Definition at line 36 of file SocketWriter.h.
Member Function Documentation
atNextTick()
void core::EventReceiver::atNextTick (const std::function< void(void)> & callBack) static inherited
Definition at line 28 of file EventReceiver.cpp.
{
        class NextTickEvent : public core::EventReceiver {
        public:
            explicit NextTickEvent(const std::function<void(void)>& callBack)
                : core::EventReceiver("RequestEvent")
                , callBack(callBack) {
            }
            void onEvent([[maybe_unused]] const utils::Timeval& currentTime) override {
                callBack();
                delete this;
            }
        private:
            std::function<void(void)> callBack;
        };
        (new NextTickEvent(callBack))->span();
    }
References core::EventReceiver::EventReceiver(), and core::EventReceiver::span().
Referenced by web::http::client::SocketContext::initiateRequest(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestDelivered(), web::http::client::SocketContext::responseDelivered(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), and core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector().
checkTimeout()
void core::DescriptorEventReceiver::checkTimeout (const utils::Timeval & currentTime) inherited
Definition at line 168 of file DescriptorEventReceiver.cpp.
{
        if (maxInactivity > 0 && currentTime - lastTriggered >= maxInactivity) {
            timeoutEvent();
        }
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), utils::Timeval::operator>(), utils::Timeval::operator>=(), and core::DescriptorEventReceiver::timeoutEvent().
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents().
destruct()
void core::EventReceiver::destruct () virtual inherited
Reimplemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, and database::mariadb::MariaDBCommandStartEvent.
Definition at line 53 of file EventReceiver.cpp.
{
        delete this;
    }
Referenced by core::EventMultiplexer::EventQueue::clear().
disable()
void core::DescriptorEventReceiver::disable () protected inherited
Definition at line 90 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            enabled = false;
            descriptorEventPublisher.disable(this);
            LOG(TRACE) << getName() << " (" << observedFd << "): Disabled";
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Double disable";
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::disable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), and core::DescriptorEventReceiver::observedFd.
Referenced by core::eventreceiver::AcceptEventReceiver::acceptTimeout(), database::mariadb::MariaDBConnection::commandContinue(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectEvent(), core::eventreceiver::ConnectEventReceiver::connectTimeout(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectTimeout(), core::DescriptorEventPublisher::disable(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::pipe::PipeSource::eof(), core::eventreceiver::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSink::readEvent(), core::eventreceiver::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::socket::stream::SocketWriter::signalEvent(), core::eventreceiver::AcceptEventReceiver::signalEvent(), core::eventreceiver::ConnectEventReceiver::signalEvent(), core::eventreceiver::ExceptionalConditionEventReceiver::signalEvent(), core::eventreceiver::ReadEventReceiver::signalEvent(), core::eventreceiver::WriteEventReceiver::signalEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), core::pipe::PipeSource::writeEvent(), core::eventreceiver::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
dispatchEvent()
void core::eventreceiver::WriteEventReceiver::dispatchEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 42 of file WriteEventReceiver.cpp.
{
        writeEvent();
    }
References core::eventreceiver::WriteEventReceiver::writeEvent().
doWrite()
void core::socket::stream::SocketWriter::doWrite () private inherited
Definition at line 57 of file SocketWriter.cpp.
{
        if (!writePuffer.empty()) {
            const std::size_t writeLen = (writePuffer.size() < blockSize) ? writePuffer.size() : blockSize;
            const ssize_t retWrite = write(writePuffer.data(), writeLen);
            if (retWrite > 0) {
                writePuffer.erase(writePuffer.begin(), writePuffer.begin() + retWrite);
                if (writePuffer.capacity() > writePuffer.size() * 2) {
                    writePuffer.shrink_to_fit();
                }
                if (!isSuspended()) {
                    suspend();
                }
                span();
            } else if ((errno == EAGAIN || errno == EWOULDBLOCK || errno == EINTR) && isSuspended()) {
                resume();
            } else {
                onStatus(errno);
                disable();
            }
        } else {
            if (!isSuspended()) {
                suspend();
            }
            if (markShutdown) {
                shutdownWrite(onShutdown);
            } else if (source != nullptr) {
                source->resume();
            }
        }
    }
References core::socket::stream::SocketWriter::blockSize, core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::isSuspended(), core::socket::stream::SocketWriter::markShutdown, core::socket::stream::SocketWriter::onShutdown, core::socket::stream::SocketWriter::onStatus, core::DescriptorEventReceiver::resume(), core::pipe::Source::resume(), core::socket::stream::SocketWriter::shutdownWrite(), core::socket::stream::SocketWriter::source, core::EventReceiver::span(), core::DescriptorEventReceiver::suspend(), core::socket::stream::SocketWriter::write(), and core::socket::stream::SocketWriter::writePuffer.
Referenced by core::socket::stream::SocketWriter::writeEvent().
doWriteShutdown()
virtual void core::socket::stream::SocketWriter::doWriteShutdown (const std::function< void()> & onShutdown) private pure virtual inherited
Referenced by core::socket::stream::SocketWriter::shutdownWrite().
enable()
bool core::DescriptorEventReceiver::enable (int fd) protected inherited
Definition at line 67 of file DescriptorEventReceiver.cpp.
{
        if (core::eventLoopState() != core::State::STOPPING) {
            if (!enabled) {
                observedFd = fd;
                enabled = true;
                descriptorEventPublisher.enable(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double enable";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Enable after signal";
        }
        return enabled;
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::enable(), core::DescriptorEventReceiver::enabled, core::eventLoopState(), core::EventReceiver::getName(), core::DescriptorEventReceiver::observedFd, and core::STOPPING.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::init(), core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 65 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::socket::stream::tls::SocketReader::read(), core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::SocketWriter::shutdownWrite(), core::socket::stream::SocketWriter::streamEof(), core::socket::stream::SocketWriter::streamToPeer(), core::DescriptorEventReceiver::suspend(), and core::socket::stream::tls::SocketWriter::write().
getRegisteredFd()
int core::DescriptorEventReceiver::getRegisteredFd () const inherited
Definition at line 63 of file DescriptorEventReceiver.cpp.
{
        return observedFd;
    }
References core::DescriptorEventReceiver::observedFd.
Referenced by core::DescriptorEventPublisher::enable(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::select::DescriptorEventPublisher::muxAdd(), core::poll::PollFdsManager::muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOff(), core::select::DescriptorEventPublisher::muxOff(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOn(), core::select::DescriptorEventPublisher::muxOn(), core::socket::stream::legacy::SocketReader::read(), core::pipe::PipeSink::readEvent(), write(), core::pipe::PipeSource::writeEvent(), core::pipe::PipeSink::~PipeSink(), and core::pipe::PipeSource::~PipeSource().
getTimeout()
utils::Timeval core::DescriptorEventReceiver::getTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 149 of file DescriptorEventReceiver.cpp.
{
        return maxInactivity > 0 ? currentTime > lastTriggered ? maxInactivity - (currentTime - lastTriggered) : 0 : TIMEOUT::MAX;
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::DescriptorEventPublisher::getNextTimeout().
isEnabled()
bool core::DescriptorEventReceiver::isEnabled () const inherited
Definition at line 104 of file DescriptorEventReceiver.cpp.
{
        return enabled;
    }
References core::DescriptorEventReceiver::enabled.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketWriter::sendToPeer(), and core::socket::stream::SocketWriter::streamToPeer().
isSuspended()
bool core::DescriptorEventReceiver::isSuspended () const inherited
Definition at line 135 of file DescriptorEventReceiver.cpp.
{
        return suspended;
    }
References core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::pipe::PipeSource::send().
observed()
void core::Observer::observed () protected inherited
Definition at line 38 of file DescriptorEventReceiver.cpp.
{
        observationCounter++;
    }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setEnabled().
onEvent()
void core::DescriptorEventReceiver::onEvent (const utils::Timeval & currentTime) final private virtual inherited
Implements core::EventReceiver.
Definition at line 153 of file DescriptorEventReceiver.cpp.
{
        eventCounter++;
        triggered(currentTime);
        dispatchEvent();
    }
References core::DescriptorEventReceiver::dispatchEvent(), core::DescriptorEventReceiver::eventCounter, and core::DescriptorEventReceiver::triggered().
onSignal()
virtual bool core::socket::stream::SocketWriter::onSignal (int sigNum) private pure virtual inherited
Referenced by core::socket::stream::SocketWriter::signalEvent().
relax()
void core::EventReceiver::relax () inherited
Definition at line 61 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
resume()
void core::DescriptorEventReceiver::resume () protected inherited
Definition at line 121 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (suspended) {
                suspended = false;
                lastTriggered = utils::Timeval::currentTime();
                descriptorEventPublisher.resume(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double resume";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Resume while not enabled";
        }
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::observedFd, utils::Timeval::operator=(), core::DescriptorEventPublisher::resume(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
sendToPeer()
void core::socket::stream::SocketWriter::sendToPeer (const char * chunk, std::size_t chunkLen) protected inherited
Definition at line 96 of file SocketWriter.cpp.
{
        if (!shutdownInProgress && !markShutdown) {
            if (isEnabled()) {
                if (writePuffer.empty()) {
                    resume();
                }
                writePuffer.insert(writePuffer.end(), chunk, chunk + chunkLen);
                if (source != nullptr && writePuffer.size() > 5 * blockSize) {
                    source->suspend();
                }
            } else {
                LOG(TRACE) << getName() << ": Send request while not enabled";
            }
        } else {
            LOG(TRACE) << getName() << ": Send request while shutdown in progress";
        }
    }
References core::socket::stream::SocketWriter::blockSize, core::EventReceiver::getName(), core::DescriptorEventReceiver::isEnabled(), core::socket::stream::SocketWriter::markShutdown, core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter::shutdownInProgress, core::socket::stream::SocketWriter::source, core::pipe::Source::suspend(), and core::socket::stream::SocketWriter::writePuffer.
setBlockSize()
void core::socket::stream::SocketWriter::setBlockSize (std::size_t writeBlockSize) protected inherited
Definition at line 92 of file SocketWriter.cpp.
{
        blockSize = writeBlockSize;
    }
References core::socket::stream::SocketWriter::blockSize.
setDisabled()
void core::DescriptorEventReceiver::setDisabled () private inherited
Definition at line 100 of file DescriptorEventReceiver.cpp.
{
        unObserved();
    }
References core::Observer::unObserved().
setEnabled()
void core::DescriptorEventReceiver::setEnabled (const utils::Timeval & currentTime) private inherited
Definition at line 84 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
        observed();
    }
References core::DescriptorEventReceiver::lastTriggered, core::Observer::observed(), and utils::Timeval::operator=().
Referenced by core::DescriptorEventPublisher::enable().
setTimeout()
void core::DescriptorEventReceiver::setTimeout (const utils::Timeval & timeout) inherited
Definition at line 139 of file DescriptorEventReceiver.cpp.
{
        if (timeout == TIMEOUT::DEFAULT) {
            this->maxInactivity = initialTimeout;
        } else {
            this->maxInactivity = timeout;
        }
        triggered(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::TIMEOUT::DEFAULT, core::DescriptorEventReceiver::initialTimeout, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator=(), utils::Timeval::operator==(), and core::DescriptorEventReceiver::triggered().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::init(), and core::socket::stream::SocketWriter::shutdownWrite().
shutdownWrite()
void core::socket::stream::SocketWriter::shutdownWrite (const std::function< void()> & onShutdown) protected inherited
Definition at line 145 of file SocketWriter.cpp.
{
        if (!shutdownInProgress) {
            SocketWriter::setTimeout(SocketWriter::terminateTimeout);
            SocketWriter::onShutdown = onShutdown;
            if (SocketWriter::writePuffer.empty()) {
                doWriteShutdown(onShutdown);
                shutdownInProgress = true;
            } else {
                SocketWriter::markShutdown = true;
                LOG(TRACE) << getName() << ": Delay shutdown due to queued data";
            }
        }
    }
References core::socket::stream::SocketWriter::doWriteShutdown(), core::EventReceiver::getName(), core::socket::stream::SocketWriter::markShutdown, core::socket::stream::SocketWriter::onShutdown, core::DescriptorEventReceiver::setTimeout(), core::socket::stream::SocketWriter::shutdownInProgress, core::socket::stream::SocketWriter::terminateTimeout, and core::socket::stream::SocketWriter::writePuffer.
Referenced by core::socket::stream::SocketWriter::doWrite(), and core::socket::stream::SocketWriter::signalEvent().
signalEvent()
void core::socket::stream::SocketWriter::signalEvent (int sigNum) final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 49 of file SocketWriter.cpp.
{
        if (onSignal(sigNum)) {
            shutdownWrite([this]() -> void {
                SocketWriter::disable();
            });
        }
    }
References core::DescriptorEventReceiver::disable(), core::socket::stream::SocketWriter::onSignal(), and core::socket::stream::SocketWriter::shutdownWrite().
span()
void core::EventReceiver::span () inherited
Definition at line 57 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by core::EventReceiver::atNextTick(), database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), core::file::FileReader::start(), core::file::FileReader::stop(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
streamEof()
void core::socket::stream::SocketWriter::streamEof () protected inherited
Definition at line 140 of file SocketWriter.cpp.
{
        LOG(TRACE) << getName() << ": Stream EOF";
        this->source = nullptr;
    }
References core::EventReceiver::getName(), and core::socket::stream::SocketWriter::source.
streamToPeer()
bool core::socket::stream::SocketWriter::streamToPeer (core::pipe::Source * source) protected inherited
Definition at line 116 of file SocketWriter.cpp.
{
        bool success = false;
        if (!shutdownInProgress && !markShutdown) {
            if (isEnabled()) {
                success = source != nullptr;
                if (success) {
                    LOG(TRACE) << getName() << ": Stream started";
                } else {
                    LOG(TRACE) << getName() << ": Stream source is nullptr";
                }
            } else {
                LOG(TRACE) << getName() << ": Stream request while not enabled";
            }
        } else {
            LOG(TRACE) << getName() << ": Stream request while shutdown in progress";
        }
        this->source = source;
        return success;
    }
References core::EventReceiver::getName(), core::DescriptorEventReceiver::isEnabled(), core::socket::stream::SocketWriter::markShutdown, core::socket::stream::SocketWriter::shutdownInProgress, and core::socket::stream::SocketWriter::source.
suspend()
void core::DescriptorEventReceiver::suspend () protected inherited
Definition at line 108 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!suspended) {
                suspended = true;
                descriptorEventPublisher.suspend(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double suspend";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Suspend while not enabled";
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::observedFd, core::DescriptorEventPublisher::suspend(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), and core::pipe::PipeSource::writeEvent().
timeoutEvent()
void core::eventreceiver::WriteEventReceiver::timeoutEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 46 of file WriteEventReceiver.cpp.
{
        writeTimeout();
    }
References core::eventreceiver::WriteEventReceiver::writeTimeout().
triggered()
void core::DescriptorEventReceiver::triggered (const utils::Timeval & currentTime) private inherited
Definition at line 164 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
    }
References core::DescriptorEventReceiver::lastTriggered, and utils::Timeval::operator=().
Referenced by core::DescriptorEventReceiver::onEvent(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::DescriptorEventReceiver::setTimeout().
unObserved()
void core::Observer::unObserved () protected inherited
Definition at line 42 of file DescriptorEventReceiver.cpp.
{
        observationCounter--;
        if (observationCounter == 0) {
            unobservedEvent();
        }
    }
References core::Observer::observationCounter, and core::Observer::unobservedEvent().
Referenced by core::DescriptorEventReceiver::setDisabled().
unobservedEvent()
virtual void core::Observer::unobservedEvent () protected pure virtual inherited
Implemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::tls::TLSHandshake, core::socket::stream::tls::TLSShutdown, core::pipe::PipeSink, core::pipe::PipeSource, and database::mariadb::MariaDBConnection.
Referenced by core::Observer::unObserved().
write()
ssize_t core::socket::stream::legacy::SocketWriter::write (const char * chunk, std::size_t chunkLen) override private virtual
Implements core::socket::stream::SocketWriter.
Definition at line 30 of file SocketWriter.cpp.
{
        return core::system::send(this->getRegisteredFd(), chunk, chunkLen, MSG_NOSIGNAL);
    }
References core::DescriptorEventReceiver::getRegisteredFd(), and core::system::send().
writeEvent()
void core::socket::stream::SocketWriter::writeEvent () final private virtual inherited
Implements core::eventreceiver::WriteEventReceiver.
Definition at line 45 of file SocketWriter.cpp.
{
        doWrite();
    }
References core::socket::stream::SocketWriter::doWrite().
writeTimeout()
void core::eventreceiver::WriteEventReceiver::writeTimeout () private virtual inherited
Reimplemented in core::socket::stream::tls::TLSHandshake, core::socket::stream::tls::TLSShutdown, and database::mariadb::MariaDBConnection.
Definition at line 38 of file WriteEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
Referenced by core::eventreceiver::WriteEventReceiver::timeoutEvent().
Member Data Documentation
blockSize
std::size_t core::socket::stream::SocketWriter::blockSize = 0 private inherited
Definition at line 90 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter::doWrite(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::SocketWriter::setBlockSize(), and core::socket::stream::SocketWriter::SocketWriter().
descriptorEventPublisher
DescriptorEventPublisher& core::DescriptorEventReceiver::descriptorEventPublisher private inherited
Definition at line 101 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
enabled
bool core::DescriptorEventReceiver::enabled = false private inherited
Definition at line 105 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
event
Event core::EventReceiver::event private inherited
Definition at line 65 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
eventCounter
int core::DescriptorEventReceiver::eventCounter = 0 private inherited
Definition at line 112 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::onEvent().
initialTimeout
const utils::Timeval core::DescriptorEventReceiver::initialTimeout private inherited
Definition at line 110 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), and core::DescriptorEventReceiver::setTimeout().
lastTriggered
utils::Timeval core::DescriptorEventReceiver::lastTriggered private inherited
Definition at line 108 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setEnabled(), and core::DescriptorEventReceiver::triggered().
markShutdown
bool core::socket::stream::SocketWriter::markShutdown = false protected inherited
Definition at line 75 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter::doWrite(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::SocketWriter::shutdownWrite(), and core::socket::stream::SocketWriter::streamToPeer().
maxInactivity
utils::Timeval core::DescriptorEventReceiver::maxInactivity private inherited
Definition at line 109 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::getTimeout(), and core::DescriptorEventReceiver::setTimeout().
observationCounter
int core::Observer::observationCounter = 0 private inherited
Definition at line 54 of file DescriptorEventReceiver.h.
Referenced by core::Observer::observed(), and core::Observer::unObserved().
observedFd
int core::DescriptorEventReceiver::observedFd = -1 private inherited
Definition at line 103 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
onShutdown
std::function<void()> core::socket::stream::SocketWriter::onShutdown protected inherited
Definition at line 81 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter::doWrite(), and core::socket::stream::SocketWriter::shutdownWrite().
onStatus
std::function<void(int)> core::socket::stream::SocketWriter::onStatus private inherited
Definition at line 78 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter::doWrite(), and core::socket::stream::SocketWriter::SocketWriter().
shutdownInProgress
bool core::socket::stream::SocketWriter::shutdownInProgress = false protected inherited
Definition at line 85 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::SocketWriter::shutdownWrite(), and core::socket::stream::SocketWriter::streamToPeer().
source
core::pipe::Source* core::socket::stream::SocketWriter::source = nullptr private inherited
Definition at line 88 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter::doWrite(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::SocketWriter::streamEof(), and core::socket::stream::SocketWriter::streamToPeer().
suspended
bool core::DescriptorEventReceiver::suspended = false private inherited
Definition at line 106 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
terminateTimeout
utils::Timeval core::socket::stream::SocketWriter::terminateTimeout private inherited
Definition at line 92 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter::shutdownWrite(), and core::socket::stream::SocketWriter::SocketWriter().
writePuffer
std::vector<char> core::socket::stream::SocketWriter::writePuffer protected inherited
Definition at line 83 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter::doWrite(), core::socket::stream::SocketWriter::sendToPeer(), and core::socket::stream::SocketWriter::shutdownWrite().
The documentation for this class was generated from the following files:
core/socket/stream/legacy/SocketWriter.h
core/socket/stream/legacy/SocketWriter.cpp