SNode.C: iot::mqtt_fast::types::Int_1 Class Reference
iot::mqtt_fast::types::Int_1 Class Reference
#include <Int_1.h>
Public Member Functions
Int_1 (core::socket::SocketContext *socketContext=nullptr)
std::size_t construct () override
uint8_t getValue ()
void reset () override
bool isCompleted ()
bool isError ()
Protected Member Functions
std::size_t read (char *buf, std::size_t count)
Protected Attributes
core::socket::SocketContext * socketContext
bool completed = false
bool error = false
Private Attributes
std::size_t length = 1
std::size_t needed = 1
char buffer [1]
Detailed Description
Definition at line 37 of file Int_1.h.
Constructor & Destructor Documentation
Int_1()
iot::mqtt_fast::types::Int_1::Int_1 (core::socket::SocketContext * socketContext = nullptr) explicit
Definition at line 27 of file Int_1.cpp.
        : iot::mqtt_fast::types::TypeBase(socketContext) {
    }
References iot::mqtt_fast::types::TypeBase::TypeBase().
Referenced by iot::mqtt_fast::ControlPacketFactory::ControlPacketFactory().
Member Function Documentation
construct()
std::size_t iot::mqtt_fast::types::Int_1::construct () override virtual
Implements iot::mqtt_fast::types::TypeBase.
Definition at line 31 of file Int_1.cpp.
{
        std::size_t consumed = read(buffer + length - needed, static_cast<std::size_t>(needed));
        needed -= consumed;
        completed = needed == 0;
        return consumed;
    }
References buffer, iot::mqtt_fast::types::TypeBase::completed, length, needed, and iot::mqtt_fast::types::TypeBase::read().
Referenced by iot::mqtt_fast::ControlPacketFactory::construct().
getValue()
uint8_t iot::mqtt_fast::types::Int_1::getValue ()
Definition at line 40 of file Int_1.cpp.
{
        return *reinterpret_cast<uint8_t*>(buffer);
    }
References buffer.
Referenced by iot::mqtt_fast::ControlPacketFactory::getPacketFlags(), and iot::mqtt_fast::ControlPacketFactory::getPacketType().
isCompleted()
bool iot::mqtt_fast::types::TypeBase::isCompleted () inherited
Definition at line 33 of file TypeBase.cpp.
{
        return completed;
    }
References iot::mqtt_fast::types::TypeBase::completed.
Referenced by iot::mqtt_fast::ControlPacketFactory::construct().
isError()
bool iot::mqtt_fast::types::TypeBase::isError () inherited
Definition at line 37 of file TypeBase.cpp.
{
        return error;
    }
References iot::mqtt_fast::types::TypeBase::error.
Referenced by iot::mqtt_fast::ControlPacketFactory::construct(), and iot::mqtt_fast::ControlPacket::isError().
read()
std::size_t iot::mqtt_fast::types::TypeBase::read (char * buf, std::size_t count) protected inherited
Definition at line 41 of file TypeBase.cpp.
{
        std::size_t ret = 0;
        ret = socketContext->readFromPeer(buf, count);
        return ret;
    }
References core::socket::SocketContext::readFromPeer(), and iot::mqtt_fast::types::TypeBase::socketContext.
Referenced by iot::mqtt_fast::types::Binary::construct(), construct(), and iot::mqtt_fast::types::Int_V::construct().
reset()
void iot::mqtt_fast::types::Int_1::reset () override virtual
Reimplemented from iot::mqtt_fast::types::TypeBase.
Definition at line 44 of file Int_1.cpp.
                      {
        length = 1;
        needed = 1;
        iot::mqtt_fast::types::TypeBase::reset();
    }
References length, needed, and iot::mqtt_fast::types::TypeBase::reset().
Referenced by iot::mqtt_fast::ControlPacketFactory::reset().
Member Data Documentation
buffer
char iot::mqtt_fast::types::Int_1::buffer[1] private
Definition at line 50 of file Int_1.h.
Referenced by construct(), and getValue().
completed
bool iot::mqtt_fast::types::TypeBase::completed = false protected inherited
Definition at line 57 of file TypeBase.h.
Referenced by iot::mqtt_fast::types::Binary::construct(), construct(), iot::mqtt_fast::types::Int_V::construct(), iot::mqtt_fast::types::Binary::getIntV(), iot::mqtt_fast::types::TypeBase::isCompleted(), and iot::mqtt_fast::types::TypeBase::reset().
error
bool iot::mqtt_fast::types::TypeBase::error = false protected inherited
Definition at line 58 of file TypeBase.h.
Referenced by iot::mqtt_fast::types::Int_V::construct(), iot::mqtt_fast::types::Binary::getInt16(), iot::mqtt_fast::types::Binary::getInt32(), iot::mqtt_fast::types::Binary::getInt64(), iot::mqtt_fast::types::Binary::getInt8(), iot::mqtt_fast::types::Binary::getIntV(), iot::mqtt_fast::types::Binary::getString(), iot::mqtt_fast::types::Binary::getStringRaw(), iot::mqtt_fast::types::Binary::getUint8ListRaw(), iot::mqtt_fast::types::TypeBase::isError(), and iot::mqtt_fast::types::TypeBase::reset().
length
std::size_t iot::mqtt_fast::types::Int_1::length = 1 private
Definition at line 48 of file Int_1.h.
Referenced by construct(), and reset().
needed
std::size_t iot::mqtt_fast::types::Int_1::needed = 1 private
Definition at line 49 of file Int_1.h.
Referenced by construct(), and reset().
socketContext
core::socket::SocketContext* iot::mqtt_fast::types::TypeBase::socketContext protected inherited
Definition at line 55 of file TypeBase.h.
Referenced by iot::mqtt_fast::types::TypeBase::read(), and iot::mqtt_fast::types::TypeBase::TypeBase().
The documentation for this class was generated from the following files:
iot/mqtt-fast/types/Int_1.h
iot/mqtt-fast/types/Int_1.cpp