SNode.C: core::multiplexer::select::FdSet Class Reference
core::multiplexer::select::FdSet Class Reference
#include <DescriptorEventPublisher.h>
Public Member Functions
FdSet ()
void set (int fd)
void clr (int fd)
int isSet (int fd) const
void zero ()
fd_set & get ()
Private Attributes
fd_set registered {}
fd_set active {}
Detailed Description
Definition at line 57 of file DescriptorEventPublisher.h.
Constructor & Destructor Documentation
FdSet()
core::multiplexer::select::FdSet::FdSet ()
Definition at line 55 of file DescriptorEventPublisher.cpp.
                 {
        zero();
    }
References zero().
Member Function Documentation
clr()
void core::multiplexer::select::FdSet::clr (int fd)
Definition at line 63 of file DescriptorEventPublisher.cpp.
{
        FD_CLR(fd, &registered);
        FD_CLR(fd, &active);
    }
References active, and registered.
Referenced by core::multiplexer::select::DescriptorEventPublisher::muxDel(), and core::multiplexer::select::DescriptorEventPublisher::muxOff().
get()
fd_set & core::multiplexer::select::FdSet::get ()
Definition at line 77 of file DescriptorEventPublisher.cpp.
                       {
        active = registered;
        return active;
    }
References active, and registered.
Referenced by core::multiplexer::select::EventMultiplexer::monitorDescriptors().
isSet()
int core::multiplexer::select::FdSet::isSet (int fd) const
Definition at line 68 of file DescriptorEventPublisher.cpp.
{
        return FD_ISSET(fd, &active);
    }
References active.
Referenced by core::multiplexer::select::DescriptorEventPublisher::spanActiveEvents().
set()
void core::multiplexer::select::FdSet::set (int fd)
Definition at line 59 of file DescriptorEventPublisher.cpp.
{
        FD_SET(fd, &registered);
    }
References registered.
Referenced by core::multiplexer::select::DescriptorEventPublisher::muxAdd(), and core::multiplexer::select::DescriptorEventPublisher::muxOn().
zero()
void core::multiplexer::select::FdSet::zero ()
Definition at line 72 of file DescriptorEventPublisher.cpp.
                     {
        FD_ZERO(&registered);
        FD_ZERO(&active);
    }
References active, and registered.
Referenced by FdSet().
Member Data Documentation
active
fd_set core::multiplexer::select::FdSet::active {} private
Definition at line 69 of file DescriptorEventPublisher.h.
{};
Referenced by clr(), get(), isSet(), and zero().
registered
fd_set core::multiplexer::select::FdSet::registered {} private
Definition at line 68 of file DescriptorEventPublisher.h.
{};
Referenced by clr(), get(), set(), and zero().
The documentation for this class was generated from the following files:
core/multiplexer/select/DescriptorEventPublisher.h
core/multiplexer/select/DescriptorEventPublisher.cpp