SNode.C: web::http::client::SocketContextUpgradeFactory Class Reference
web::http::client::SocketContextUpgradeFactory Class Reference abstract
#include <SocketContextUpgradeFactory.h>
Public Types
using Resquest = web::http::client::Request
using Reponse = web::http::client::Response
using Request = web::http::client::Request
using Response = web::http::client::Response
Public Member Functions
void checkRefCount () final
virtual std::string name ()=0
Static Public Member Functions
static void link (const std::string &upgradeContextName, SocketContextUpgradeFactory *(*linkedPlugin)())
Protected Member Functions
SocketContextUpgradeFactory ()
virtual void prepare (Request &request)=0
void prepare (Request &request, Response &response)
Protected Attributes
std::size_t refCount
Private Member Functions
virtual SocketContextUpgrade< Request, Response > * create (core::socket::stream::SocketConnection *socketConnection, Request *request, Response *response)=0
core::socket::stream::SocketContext * create (core::socket::stream::SocketConnection *socketConnection) final
void incRefCount ()
void decRefCount ()
Private Attributes
friend Request
friend Response
Request * request
Response * response
Friends
class SocketContextUpgradeFactorySelector
Detailed Description
Definition at line 38 of file SocketContextUpgradeFactory.h.
Member Typedef Documentation
Reponse
using web::http::client::SocketContextUpgradeFactory::Reponse = web::http::client::Response
Definition at line 42 of file SocketContextUpgradeFactory.h.
Request
using web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::Request = web::http::client::Request inherited
Definition at line 48 of file SocketContextUpgradeFactory.h.
Response
using web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::Response = web::http::client::Response inherited
Definition at line 49 of file SocketContextUpgradeFactory.h.
Resquest
using web::http::client::SocketContextUpgradeFactory::Resquest = web::http::client::Request
Definition at line 41 of file SocketContextUpgradeFactory.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactory()
web::http::client::SocketContextUpgradeFactory::SocketContextUpgradeFactory () protected
Definition at line 31 of file SocketContextUpgradeFactory.cpp.
{
    }
Member Function Documentation
checkRefCount()
void web::http::client::SocketContextUpgradeFactory::checkRefCount () final virtual
Implements web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >.
Definition at line 34 of file SocketContextUpgradeFactory.cpp.
{
        if (refCount == 0) {
            web::http::client::SocketContextUpgradeFactorySelector::instance()->unload(this);
        }
    }
References web::http::client::SocketContextUpgradeFactorySelector::instance(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::unload().
Referenced by web::websocket::client::SocketContextUpgradeFactory::create(), and web::http::client::Request::executeUpgrade().
create() [1/2]
core::socket::stream::SocketContext * web::http::SocketContextUpgradeFactory< Request, Response >::create (core::socket::stream::SocketConnection * socketConnection) final private virtual inherited
Implements core::socket::stream::SocketContextFactory.
Definition at line 66 of file SocketContextUpgradeFactory.hpp.
{
        return create(socketConnection, request, response);
    }
create() [2/2]
virtual SocketContextUpgrade< Request, Response > * web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::create (core::socket::stream::SocketConnection * socketConnection, Request * request, Response * response) private pure virtual inherited
Implemented in web::websocket::client::SocketContextUpgradeFactory.
decRefCount()
void web::http::SocketContextUpgradeFactory< Request, Response >::decRefCount () private inherited
Definition at line 69 of file SocketContextUpgradeFactory.hpp.
{
        --refCount;
        checkRefCount();
    }
incRefCount()
void web::http::SocketContextUpgradeFactory< Request, Response >::incRefCount () private inherited
Definition at line 68 of file SocketContextUpgradeFactory.hpp.
{
        ++refCount;
    }
link()
void web::http::client::SocketContextUpgradeFactory::link (const std::string & upgradeContextName, SocketContextUpgradeFactory *(*)() linkedPlugin) static
Definition at line 40 of file SocketContextUpgradeFactory.cpp.
{
        web::http::client::SocketContextUpgradeFactorySelector::instance()->link(upgradeContextName, linkedPlugin);
    }
References web::http::client::SocketContextUpgradeFactorySelector::instance(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::link().
Referenced by web::websocket::client::SocketContextUpgradeFactory::link().
name()
virtual std::string web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::name () pure virtual inherited
Implemented in web::websocket::client::SocketContextUpgradeFactory.
prepare() [1/2]
virtual void web::http::client::SocketContextUpgradeFactory::prepare (Request & request) protected pure virtual
Implemented in web::websocket::client::SocketContextUpgradeFactory.
Referenced by web::http::client::SocketContextUpgradeFactorySelector::select().
prepare() [2/2]
void web::http::SocketContextUpgradeFactory< Request, Response >::prepare (Request & request, Response & response) protected inherited
Definition at line 61 of file SocketContextUpgradeFactory.hpp.
{
        this->request = &request;
        this->response = &response;
    }
Friends And Related Symbol Documentation
SocketContextUpgradeFactorySelector
friend class SocketContextUpgradeFactorySelector friend
Definition at line 54 of file SocketContextUpgradeFactory.h.
Member Data Documentation
refCount
std::size_t web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::refCount protected inherited
Definition at line 59 of file SocketContextUpgradeFactory.h.
request
Request* web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::request private inherited
Definition at line 73 of file SocketContextUpgradeFactory.h.
Request
friend web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::Request private inherited
Definition at line 77 of file SocketContextUpgradeFactory.h.
response
Response* web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::response private inherited
Definition at line 74 of file SocketContextUpgradeFactory.h.
Response
friend web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::Response private inherited
Definition at line 76 of file SocketContextUpgradeFactory.h.
The documentation for this class was generated from the following files:
web/http/client/SocketContextUpgradeFactory.h
web/http/client/SocketContextUpgradeFactory.cpp