SNode.C: net::config::ConfigSection Class Reference
net::config::ConfigSection Class Reference
#include <ConfigSection.h>
Public Member Functions
template<typename T>
ConfigSection (ConfigInstance *instance, T *sectionPtr, const std::string &group="Sections")
virtual ~ConfigSection ()
ConfigSection (const ConfigSection &)=delete
ConfigSection (ConfigSection &&)=delete
ConfigSection & operator= (const ConfigSection &)=delete
ConfigSection & operator= (ConfigSection &&)=delete
CLI::Option * addOption (const std::string &name, const std::string &description)
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueTypeT>
CLI::Option * addOptionFunction (const std::string &name, const std::function< void(const std::string &)> &optionFunction, const std::string &description)
CLI::Option * addFlag (const std::string &name, const std::string &description)
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
CLI::Option * getOption (const std::string &name) const
void required (CLI::Option *opt, bool req=true)
void required (bool required=true)
bool getRequired () const
template<typename ValueType>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
Protected Member Functions
void setConfigurable (CLI::Option *option, bool configurable)
Protected Attributes
CLI::App * sectionSc = nullptr
Private Attributes
ConfigInstance * instance = nullptr
uint8_t requiredCount = 0
Detailed Description
Definition at line 65 of file ConfigSection.h.
Constructor & Destructor Documentation
ConfigSection() [1/3]
template<typename T> net::config::ConfigSection::ConfigSection (ConfigInstance * instance, T * sectionPtr, const std::string & group = "Sections")
Definition at line 99 of file ConfigSection.hpp.
        : instance(instance) {
        sectionSc = instance->newSection(net::config::Section(sectionPtr), group);
        sectionSc->description(std::string(T::description) + " for instance '" + instance->getInstanceName() + "'");
    }
References net::config::ConfigInstance::getInstanceName(), instance, net::config::ConfigInstance::newSection(), and sectionSc.
Referenced by net::config::ConfigConnection::ConfigConnection(), web::http::client::ConfigHTTP::ConfigHTTP(), net::config::ConfigLegacy::ConfigLegacy(), net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient(), net::config::ConfigPhysicalSocketServer::ConfigPhysicalSocketServer(), net::config::ConfigTlsClient::ConfigTlsClient(), net::config::ConfigTlsServer::ConfigTlsServer(), and section::ConfigWWW::ConfigWWW().
~ConfigSection()
net::config::ConfigSection::~ConfigSection () virtual
Definition at line 78 of file ConfigSection.cpp.
{
    }
ConfigSection() [2/3]
net::config::ConfigSection::ConfigSection (const ConfigSection &) delete
ConfigSection() [3/3]
net::config::ConfigSection::ConfigSection (ConfigSection &&) delete
Member Function Documentation
addFlag() [1/7]
CLI::Option * net::config::ConfigSection::addFlag (const std::string & name, const std::string & description)
Definition at line 139 of file ConfigSection.cpp.
{
        sectionSc->disabled(false);
        CLI::Option* opt = sectionSc //
                               ->add_flag(name, description);
        if (opt->get_configurable()) {
            opt->group(sectionSc->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References sectionSc.
Referenced by addFlag().
addFlag() [2/7]
CLI::Option * net::config::ConfigSection::addFlag (const std::string & name, const std::string & description, const std::string & typeName)
Definition at line 152 of file ConfigSection.cpp.
{
        return addFlag(name, description)->type_name(typeName);
    }
References addFlag().
Referenced by addFlag(), and addFlag().
addFlag() [3/7]
CLI::Option * net::config::ConfigSection::addFlag (const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator)
Definition at line 156 of file ConfigSection.cpp.
{
        return addFlag(name, description, typeName) //
            ->check(additionalValidator);
    }
References addFlag().
addFlag() [4/7]
template<typename ValueType> CLI::Option * net::config::ConfigSection::addFlag (const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue)
Definition at line 130 of file ConfigSection.hpp.
{
        return addFlag(name, description, typeName) //
            ->default_val(defaultValue);
    }
References addFlag().
addFlag() [5/7]
template<typename ValueType> CLI::Option * net::config::ConfigSection::addFlag (const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator)
Definition at line 136 of file ConfigSection.hpp.
{
        return addFlag(name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
addFlag() [6/7]
template<typename ValueTypeT> CLI::Option * net::config::ConfigSection::addFlag (const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue)
addFlag() [7/7]
template<typename ValueTypeT> CLI::Option * net::config::ConfigSection::addFlag (const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator)
Referenced by web::http::client::ConfigHTTP::ConfigHTTP(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
addFlagFunction() [1/2]
CLI::Option * net::config::ConfigSection::addFlagFunction (const std::string & name, const std::function< void()> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue)
Definition at line 164 of file ConfigSection.cpp.
{
        sectionSc->disabled(false);
        CLI::Option* opt = sectionSc //
                               ->add_flag_function(
                                   name,
                                   [callback](std::int64_t) {
                                       callback();
                                   },
                                   description)
                               ->default_val(defaultValue)
                               ->type_name(typeName)
                               ->take_last();
        if (opt->get_configurable()) {
            opt->group(sectionSc->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References sectionSc.
Referenced by addFlagFunction().
addFlagFunction() [2/2]
CLI::Option * net::config::ConfigSection::addFlagFunction (const std::string & name, const std::function< void()> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator)
Definition at line 188 of file ConfigSection.cpp.
{
        return addFlagFunction(name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References addFlagFunction().
Referenced by net::config::ConfigPhysicalSocket::addSocketOption(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), and net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient().
addOption() [1/7]
CLI::Option * net::config::ConfigSection::addOption (const std::string & name, const std::string & description)
Definition at line 111 of file ConfigSection.cpp.
{
        if (!instance->getInstanceName().empty() && !sectionSc->get_display_name().empty()) {
            sectionSc->disabled(false);
        }
        CLI::Option* opt = sectionSc //
                               ->add_option(name, description);
        if (opt->get_configurable()) {
            opt->group(sectionSc->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigInstance::getInstanceName(), instance, and sectionSc.
Referenced by addOption().
addOption() [2/7]
CLI::Option * net::config::ConfigSection::addOption (const std::string & name, const std::string & description, const std::string & typeName)
Definition at line 126 of file ConfigSection.cpp.
{
        return addOption(name, description) //
            ->type_name(typeName);
    }
References addOption().
Referenced by addOption(), addOption(), and web::http::client::ConfigHTTP::ConfigHTTP().
addOption() [3/7]
CLI::Option * net::config::ConfigSection::addOption (const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator)
Definition at line 131 of file ConfigSection.cpp.
{
        return addOption(name, description, typeName) //
            ->check(additionalValidator);
    }
References addOption().
addOption() [4/7]
template<typename ValueType> CLI::Option * net::config::ConfigSection::addOption (const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue)
Definition at line 107 of file ConfigSection.hpp.
{
        return addOption(name, description, typeName) //
            ->default_val(defaultValue);
    }
References addOption().
addOption() [5/7]
template<typename ValueType> CLI::Option * net::config::ConfigSection::addOption (const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator)
Definition at line 113 of file ConfigSection.hpp.
{
        return addOption(name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
addOption() [6/7]
template<typename ValueTypeT> CLI::Option * net::config::ConfigSection::addOption (const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue)
Referenced by net::config::ConfigTls::ConfigTls(), and section::ConfigWWW::ConfigWWW().
addOption() [7/7]
template<typename ValueTypeT> CLI::Option * net::config::ConfigSection::addOption (const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator)
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
addOptionFunction()
template<typename ValueTypeT> CLI::Option * net::config::ConfigSection::addOptionFunction (const std::string & name, const std::function< void(const std::string &)> & optionFunction, const std::string & description)
Definition at line 122 of file ConfigSection.hpp.
{
        return sectionSc->add_option_function<ValueTypeT>(name, optionFunction, description);
    };
References sectionSc.
getOption()
CLI::Option * net::config::ConfigSection::getOption (const std::string & name) const
Definition at line 198 of file ConfigSection.cpp.
{
        return sectionSc->get_option(name);
    }
References sectionSc.
Referenced by net::config::ConfigPhysicalSocket::addSocketOption().
getRequired()
bool net::config::ConfigSection::getRequired () const
Definition at line 102 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References requiredCount.
operator=() [1/2]
ConfigSection & net::config::ConfigSection::operator= (ConfigSection &&) delete
operator=() [2/2]
ConfigSection & net::config::ConfigSection::operator= (const ConfigSection &) delete
required() [1/2]
void net::config::ConfigSection::required (bool required = true)
Definition at line 98 of file ConfigSection.cpp.
{
        instance->required(sectionSc, required);
    }
References instance, net::config::ConfigInstance::required(), and sectionSc.
Referenced by required().
required() [2/2]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true)
Definition at line 81 of file ConfigSection.cpp.
{
        if (req != opt->get_required()) {
            if (req) {
                ++requiredCount;
                sectionSc->needs(opt);
                opt->default_str("");
            } else {
                --requiredCount;
                sectionSc->remove_needs(opt);
            }
            opt->required(req);
            required(requiredCount > 0);
        }
    }
References required(), requiredCount, and sectionSc.
Referenced by section::ConfigWWW::ConfigWWW(), and section::ConfigWWW::setHtmlRoot().
setConfigurable()
void net::config::ConfigSection::setConfigurable (CLI::Option * option, bool configurable) protected
Definition at line 106 of file ConfigSection.cpp.
{
        option->configurable(configurable);
        option->group(sectionSc->get_formatter()->get_label(configurable ? "Persistent Options" : "Nonpersistent Options"));
    }
References sectionSc.
Member Data Documentation
instance
ConfigInstance* net::config::ConfigSection::instance = nullptr private
Definition at line 149 of file ConfigSection.h.
Referenced by addOption(), ConfigSection(), and required().
requiredCount
uint8_t net::config::ConfigSection::requiredCount = 0 private
Definition at line 151 of file ConfigSection.h.
Referenced by getRequired(), and required().
sectionSc
CLI::App* net::config::ConfigSection::sectionSc = nullptr protected
Definition at line 146 of file ConfigSection.h.
Referenced by addFlag(), addFlagFunction(), addOption(), addOptionFunction(), ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), getOption(), required(), required(), and setConfigurable().
The documentation for this class was generated from the following files:
net/config/ConfigSection.h
net/config/ConfigSection.hpp
net/config/ConfigSection.cpp