snode.c: net::in6::SocketAddrInfo Class Reference
net::in6::SocketAddrInfo Class Reference
#include <SocketAddrInfo.h>
Public Member Functions
SocketAddrInfo ()=default
~SocketAddrInfo ()
int init (const std::string &node, const std::string &service, const addrinfo &hints)
bool useNext ()
const sockaddr * getSockAddr ()
Static Private Member Functions
static void logAddressInfo (const std::string &title, const addrinfo *addrInfo)
Private Attributes
struct addrinfo * addrInfo = nullptr
struct addrinfo * currentAddrInfo = nullptr
std::string node
std::string service
Detailed Description
Definition at line 32 of file SocketAddrInfo.h.
Constructor & Destructor Documentation
SocketAddrInfo()
net::in6::SocketAddrInfo::SocketAddrInfo () default
~SocketAddrInfo()
net::in6::SocketAddrInfo::~SocketAddrInfo ()
Definition at line 32 of file SocketAddrInfo.cpp.
{
        if (addrInfo != nullptr) {
            freeaddrinfo(addrInfo);
        }
    }
References addrInfo.
Member Function Documentation
getSockAddr()
const sockaddr * net::in6::SocketAddrInfo::getSockAddr ()
Definition at line 74 of file SocketAddrInfo.cpp.
{
        return currentAddrInfo != nullptr ? currentAddrInfo->ai_addr : nullptr;
    }
References currentAddrInfo.
init()
int net::in6::SocketAddrInfo::init (const std::string & node, const std::string & service, const addrinfo & hints)
Definition at line 38 of file SocketAddrInfo.cpp.
{
        int aiErrCode = 0;
        this->node = node;
        this->service = service;
        if (addrInfo != nullptr) {
            freeaddrinfo(addrInfo);
            addrInfo = nullptr;
        }
        if ((aiErrCode = core::system::getaddrinfo(node.c_str(), service.c_str(), &hints, &addrInfo)) == 0) {
            currentAddrInfo = addrInfo;
            SocketAddrInfo::logAddressInfo("Initialized AddressInfo", currentAddrInfo);
        }
        return aiErrCode;
    }
References addrInfo, currentAddrInfo, core::system::getaddrinfo(), logAddressInfo(), node, and service.
logAddressInfo()
void net::in6::SocketAddrInfo::logAddressInfo (const std::string & title, const addrinfo * addrInfo) static private
Definition at line 78 of file SocketAddrInfo.cpp.
{
        if (addrInfo != nullptr) {
            el::Logger* defaultLogger = el::Loggers::getLogger("default");
            static char hostBfr[NI_MAXHOST];
            static char servBfr[NI_MAXSERV];
            std::memset(hostBfr, 0, NI_MAXHOST);
            std::memset(servBfr, 0, NI_MAXSERV);
            getnameinfo(addrInfo->ai_addr,
                        addrInfo->ai_addrlen,
                        hostBfr,
                        sizeof(hostBfr),
                        servBfr,
                        sizeof(servBfr),
                        NI_NUMERICHOST | NI_NUMERICSERV);
            struct sockaddr_in* aiAddr = reinterpret_cast<sockaddr_in*>(addrInfo->ai_addr);
            std::string format = title + ":\n"
                                         "   ai_next      = %v\n"
                                         "   ai_flags     = %v\n"
                                         "   ai_family    = %v (PF_INET = %v, PF_INET6 = %v)\n"
                                         "   ai_socktype  = %v (SOCK_STREAM = %v, SOCK_DGRAM = %v)\n"
                                         "   ai_protocol  = %v (IPPROTO_TCP = %v, IPPROTO_UDP = %v)\n"
                                         "   ai_addrlen   = %v (sockaddr_in = %v, "
                                         "sockaddr_in6 = %v)\n"
                                         "   ai_addr      = sin_family:   %v (AF_INET = %v, "
                                         "AF_INET6 = %v)\n"
                                         "                  sin_addr:     %v\n"
                                         "                  sin_port:     %v";
            defaultLogger->trace(format.c_str(),
                                 addrInfo->ai_next,
                                 addrInfo->ai_flags,
                                 addrInfo->ai_family,
                                 PF_INET,
                                 PF_INET6,
                                 addrInfo->ai_socktype,
                                 SOCK_STREAM,
                                 SOCK_DGRAM,
                                 addrInfo->ai_protocol,
                                 IPPROTO_TCP,
                                 IPPROTO_UDP,
                                 addrInfo->ai_addrlen,
                                 sizeof(struct sockaddr_in),
                                 sizeof(struct sockaddr_in6),
                                 aiAddr->sin_family,
                                 AF_INET,
                                 AF_INET6,
                                 hostBfr,
                                 servBfr);
        }
    }
References addrInfo.
Referenced by init(), and useNext().
useNext()
bool net::in6::SocketAddrInfo::useNext ()
Definition at line 57 of file SocketAddrInfo.cpp.
{
        bool useNext = false;
        if (currentAddrInfo != nullptr && currentAddrInfo->ai_next != nullptr) {
            currentAddrInfo = currentAddrInfo->ai_next;
            useNext = true;
        } else {
            currentAddrInfo = addrInfo;
        }
        if (useNext) {
            SocketAddrInfo::logAddressInfo("Next potentially used AddressInfo", currentAddrInfo);
        }
        return useNext;
    }
References addrInfo, currentAddrInfo, logAddressInfo(), and useNext().
Referenced by useNext().
Member Data Documentation
addrInfo
struct addrinfo* net::in6::SocketAddrInfo::addrInfo = nullptr private
Definition at line 45 of file SocketAddrInfo.h.
Referenced by init(), logAddressInfo(), useNext(), and ~SocketAddrInfo().
currentAddrInfo
struct addrinfo* net::in6::SocketAddrInfo::currentAddrInfo = nullptr private
Definition at line 46 of file SocketAddrInfo.h.
Referenced by getSockAddr(), init(), and useNext().
node
std::string net::in6::SocketAddrInfo::node private
Definition at line 48 of file SocketAddrInfo.h.
Referenced by init().
service
std::string net::in6::SocketAddrInfo::service private
Definition at line 49 of file SocketAddrInfo.h.
Referenced by init().
The documentation for this class was generated from the following files:
net/in6/SocketAddrInfo.h
net/in6/SocketAddrInfo.cpp