SNode.C: web::websocket::server::SocketContextUpgradeFactory Class Reference
web::websocket::server::SocketContextUpgradeFactory Class Reference
#include <SocketContextUpgradeFactory.h>
Public Types
using Resquest = web::http::server::Request
using Reponse = web::http::server::Response
using Request = web::http::server::Request
using Response = web::http::server::Response
Public Member Functions
SocketContextUpgradeFactory ()=default
SocketContextUpgradeFactory (const SocketContextUpgradeFactory &)=delete
SocketContextUpgradeFactory & operator= (const SocketContextUpgradeFactory &)=delete
void checkRefCount () final
Static Public Member Functions
static void link ()
static void link (const std::string &upgradeContextName, SocketContextUpgradeFactory *(*linkedPlugin)())
Protected Member Functions
void prepare (Request &request, Response &response)
Protected Attributes
std::size_t refCount
Private Member Functions
std::string name () override
SocketContextUpgrade * create (core::socket::stream::SocketConnection *socketConnection, web::http::server::Request *request, web::http::server::Response *response) override
void incRefCount ()
void decRefCount ()
Private Attributes
friend Request
friend Response
Request * request
Response * response
Detailed Description
Definition at line 43 of file SocketContextUpgradeFactory.h.
Member Typedef Documentation
Reponse
using web::http::server::SocketContextUpgradeFactory::Reponse = web::http::server::Response inherited
Definition at line 42 of file SocketContextUpgradeFactory.h.
Request
using web::http::SocketContextUpgradeFactory< web::http::server::Request , web::http::server::Response >::Request = web::http::server::Request inherited
Definition at line 48 of file SocketContextUpgradeFactory.h.
Response
using web::http::SocketContextUpgradeFactory< web::http::server::Request , web::http::server::Response >::Response = web::http::server::Response inherited
Definition at line 49 of file SocketContextUpgradeFactory.h.
Resquest
using web::http::server::SocketContextUpgradeFactory::Resquest = web::http::server::Request inherited
Definition at line 41 of file SocketContextUpgradeFactory.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactory() [1/2]
web::websocket::server::SocketContextUpgradeFactory::SocketContextUpgradeFactory () default
Referenced by web::websocket::server::websocketServerContextUpgradeFactory().
SocketContextUpgradeFactory() [2/2]
web::websocket::server::SocketContextUpgradeFactory::SocketContextUpgradeFactory (const SocketContextUpgradeFactory &) delete
Member Function Documentation
checkRefCount()
void web::http::server::SocketContextUpgradeFactory::checkRefCount () final virtual inherited
Implements web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response >.
Definition at line 34 of file SocketContextUpgradeFactory.cpp.
{
        if (refCount == 0) {
            web::http::server::SocketContextUpgradeFactorySelector::instance()->unload(this);
        }
    }
References web::http::server::SocketContextUpgradeFactorySelector::instance(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::unload().
Referenced by create().
create()
SocketContextUpgrade * web::websocket::server::SocketContextUpgradeFactory::create (core::socket::stream::SocketConnection * socketConnection, web::http::server::Request * request, web::http::server::Response * response) override private virtual
Implements web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response >.
Definition at line 41 of file SocketContextUpgradeFactory.cpp.
{
        SocketContextUpgrade* socketContext = nullptr;
        if (request->get("Sec-WebSocket-Version") == "13") {
            std::string requestedSubProtocolNames = request->get("sec-websocket-protocol");
            std::list<std::string> subProtocolNamesList;
            do {
                std::string subProtocolName;
                std::tie(subProtocolName, requestedSubProtocolNames) = httputils::str_split(requestedSubProtocolNames, ',');
                httputils::str_trimm(subProtocolName);
                subProtocolNamesList.push_back(subProtocolName);
            } while (!requestedSubProtocolNames.empty());
            if (!subProtocolNamesList.empty()) {
                std::string selectedSubProtocolName;
                socketContext = new SocketContextUpgrade(socketConnection, this);
                selectedSubProtocolName = socketContext->loadSubProtocol(subProtocolNamesList);
                if (!selectedSubProtocolName.empty()) {
                    response->set("Upgrade", "websocket");
                    response->set("Connection", "Upgrade");
                    response->set("Sec-WebSocket-Protocol", selectedSubProtocolName);
                    response->set("Sec-WebSocket-Accept", base64::serverWebSocketKey(request->get("sec-websocket-key")));
                    response->status(101); // Switch Protocol
                } else {
                    delete socketContext;
                    socketContext = nullptr;
                    response->set("Connection", "close");
                    response->status(400);
                }
            } else {
                checkRefCount();
                response->set("Connection", "close");
                response->status(400);
            }
        } else {
            checkRefCount();
            response->set("Sec-WebSocket-Version", "13");
            response->set("Connection", "close");
            response->status(426);
        }
        return socketContext;
    }
References web::http::server::SocketContextUpgradeFactory::checkRefCount(), web::http::server::Request::get(), web::websocket::server::SocketContextUpgrade::loadSubProtocol(), base64::serverWebSocketKey(), web::http::server::Response::set(), web::websocket::server::SocketContextUpgrade::SocketContextUpgrade(), web::http::server::Response::status(), httputils::str_split(), and httputils::str_trimm().
decRefCount()
void web::http::SocketContextUpgradeFactory< Request, Response >::decRefCount () private inherited
Definition at line 69 of file SocketContextUpgradeFactory.hpp.
{
        --refCount;
        checkRefCount();
    }
incRefCount()
void web::http::SocketContextUpgradeFactory< Request, Response >::incRefCount () private inherited
Definition at line 68 of file SocketContextUpgradeFactory.hpp.
{
        ++refCount;
    }
link() [1/2]
void web::websocket::server::SocketContextUpgradeFactory::link () static
Definition at line 94 of file SocketContextUpgradeFactory.cpp.
{
        static bool linked = false;
        if (!linked) {
            web::http::server::SocketContextUpgradeFactory::link("websocket", websocketServerContextUpgradeFactory);
            linked = true;
        }
    }
References web::http::server::SocketContextUpgradeFactory::link(), and web::websocket::server::websocketServerContextUpgradeFactory().
link() [2/2]
void web::http::server::SocketContextUpgradeFactory::link (const std::string & upgradeContextName, SocketContextUpgradeFactory *(*)() linkedPlugin) static inherited
Definition at line 40 of file SocketContextUpgradeFactory.cpp.
{
        web::http::server::SocketContextUpgradeFactorySelector::instance()->link(upgradeContextName, linkedPlugin);
    }
References web::http::server::SocketContextUpgradeFactorySelector::instance(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::link().
Referenced by link().
name()
std::string web::websocket::server::SocketContextUpgradeFactory::name () override private virtual
Implements web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response >.
Definition at line 37 of file SocketContextUpgradeFactory.cpp.
{
        return "websocket";
    }
operator=()
SocketContextUpgradeFactory & web::websocket::server::SocketContextUpgradeFactory::operator= (const SocketContextUpgradeFactory &) delete
prepare()
void web::http::SocketContextUpgradeFactory< Request, Response >::prepare (Request & request, Response & response) protected inherited
Definition at line 61 of file SocketContextUpgradeFactory.hpp.
{
        this->request = &request;
        this->response = &response;
    }
Member Data Documentation
refCount
std::size_t web::http::SocketContextUpgradeFactory< web::http::server::Request , web::http::server::Response >::refCount protected inherited
Definition at line 59 of file SocketContextUpgradeFactory.h.
request
Request* web::http::SocketContextUpgradeFactory< web::http::server::Request , web::http::server::Response >::request private inherited
Definition at line 73 of file SocketContextUpgradeFactory.h.
Request
friend web::http::SocketContextUpgradeFactory< web::http::server::Request , web::http::server::Response >::Request private inherited
Definition at line 77 of file SocketContextUpgradeFactory.h.
response
Response* web::http::SocketContextUpgradeFactory< web::http::server::Request , web::http::server::Response >::response private inherited
Definition at line 74 of file SocketContextUpgradeFactory.h.
Response
friend web::http::SocketContextUpgradeFactory< web::http::server::Request , web::http::server::Response >::Response private inherited
Definition at line 76 of file SocketContextUpgradeFactory.h.
The documentation for this class was generated from the following files:
web/websocket/server/SocketContextUpgradeFactory.h
web/websocket/server/SocketContextUpgradeFactory.cpp