SNode.C: web::websocket::client::SocketContextUpgradeFactory Class Reference
web::websocket::client::SocketContextUpgradeFactory Class Reference
#include <SocketContextUpgradeFactory.h>
Public Types
using Resquest = web::http::client::Request
using Reponse = web::http::client::Response
using Request = web::http::client::Request
using Response = web::http::client::Response
Public Member Functions
SocketContextUpgradeFactory ()=default
SocketContextUpgradeFactory (const SocketContextUpgradeFactory &)=delete
SocketContextUpgradeFactory & operator= (const SocketContextUpgradeFactory &)=delete
void checkRefCount () final
Static Public Member Functions
static void link ()
static void link (const std::string &upgradeContextName, SocketContextUpgradeFactory *(*linkedPlugin)())
Protected Member Functions
void prepare (Request &request, Response &response)
Protected Attributes
std::size_t refCount
Private Member Functions
void prepare (web::http::client::Request &request) override
std::string name () override
SocketContextUpgrade * create (core::socket::stream::SocketConnection *socketConnection, web::http::client::Request *request, web::http::client::Response *response) override
void incRefCount ()
void decRefCount ()
Private Attributes
friend Request
friend Response
Request * request
Response * response
Detailed Description
Definition at line 43 of file SocketContextUpgradeFactory.h.
Member Typedef Documentation
Reponse
using web::http::client::SocketContextUpgradeFactory::Reponse = web::http::client::Response inherited
Definition at line 42 of file SocketContextUpgradeFactory.h.
Request
using web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::Request = web::http::client::Request inherited
Definition at line 48 of file SocketContextUpgradeFactory.h.
Response
using web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::Response = web::http::client::Response inherited
Definition at line 49 of file SocketContextUpgradeFactory.h.
Resquest
using web::http::client::SocketContextUpgradeFactory::Resquest = web::http::client::Request inherited
Definition at line 41 of file SocketContextUpgradeFactory.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactory() [1/2]
web::websocket::client::SocketContextUpgradeFactory::SocketContextUpgradeFactory () default
Referenced by web::websocket::client::websocketClientContextUpgradeFactory().
SocketContextUpgradeFactory() [2/2]
web::websocket::client::SocketContextUpgradeFactory::SocketContextUpgradeFactory (const SocketContextUpgradeFactory &) delete
Member Function Documentation
checkRefCount()
void web::http::client::SocketContextUpgradeFactory::checkRefCount () final virtual inherited
Implements web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >.
Definition at line 34 of file SocketContextUpgradeFactory.cpp.
{
        if (refCount == 0) {
            web::http::client::SocketContextUpgradeFactorySelector::instance()->unload(this);
        }
    }
References web::http::client::SocketContextUpgradeFactorySelector::instance(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::unload().
Referenced by create(), and web::http::client::Request::dispatchUpgrade().
create()
SocketContextUpgrade * web::websocket::client::SocketContextUpgradeFactory::create (core::socket::stream::SocketConnection * socketConnection, web::http::client::Request * request, web::http::client::Response * response) override private virtual
Implements web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >.
Definition at line 47 of file SocketContextUpgradeFactory.cpp.
{
        SocketContextUpgrade* socketContext = nullptr;
        if (response->get("sec-websocket-accept") == base64::serverWebSocketKey(request->header("Sec-WebSocket-Key"))) {
            const std::string subProtocolName = response->get("sec-websocket-protocol");
            socketContext = new SocketContextUpgrade(socketConnection, this);
            const std::string selectedSubProtocolName = socketContext->loadSubProtocol(subProtocolName);
            if (selectedSubProtocolName.empty()) {
                delete socketContext;
                socketContext = nullptr;
            }
        } else {
            checkRefCount();
        }
        return socketContext;
    }
References web::http::client::SocketContextUpgradeFactory::checkRefCount(), web::http::client::Response::get(), web::http::client::Request::header(), web::websocket::client::SocketContextUpgrade::loadSubProtocol(), base64::serverWebSocketKey(), and web::websocket::client::SocketContextUpgrade::SocketContextUpgrade().
decRefCount()
void web::http::SocketContextUpgradeFactory< Request, Response >::decRefCount () private inherited
Definition at line 69 of file SocketContextUpgradeFactory.hpp.
{
        --refCount;
        checkRefCount();
    }
incRefCount()
void web::http::SocketContextUpgradeFactory< Request, Response >::incRefCount () private inherited
Definition at line 68 of file SocketContextUpgradeFactory.hpp.
{
        ++refCount;
    }
link() [1/2]
void web::websocket::client::SocketContextUpgradeFactory::link () static
Definition at line 69 of file SocketContextUpgradeFactory.cpp.
{
        static bool linked = false;
        if (!linked) {
            web::http::client::SocketContextUpgradeFactory::link("websocket", websocketClientContextUpgradeFactory);
            linked = true;
        }
    }
References web::http::client::SocketContextUpgradeFactory::link(), and web::websocket::client::websocketClientContextUpgradeFactory().
link() [2/2]
void web::http::client::SocketContextUpgradeFactory::link (const std::string & upgradeContextName, SocketContextUpgradeFactory *(*)() linkedPlugin) static inherited
Definition at line 40 of file SocketContextUpgradeFactory.cpp.
{
        web::http::client::SocketContextUpgradeFactorySelector::instance()->link(upgradeContextName, linkedPlugin);
    }
References web::http::client::SocketContextUpgradeFactorySelector::instance(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::link().
Referenced by link().
name()
std::string web::websocket::client::SocketContextUpgradeFactory::name () override private virtual
Implements web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >.
Definition at line 43 of file SocketContextUpgradeFactory.cpp.
{
        return "websocket";
    }
operator=()
SocketContextUpgradeFactory & web::websocket::client::SocketContextUpgradeFactory::operator= (const SocketContextUpgradeFactory &) delete
prepare() [1/2]
void web::http::SocketContextUpgradeFactory< Request, Response >::prepare (Request & request, Response & response) protected inherited
Definition at line 61 of file SocketContextUpgradeFactory.hpp.
{
        this->request = &request;
        this->response = &response;
    }
prepare() [2/2]
void web::websocket::client::SocketContextUpgradeFactory::prepare (web::http::client::Request & request) override private virtual
Implements web::http::client::SocketContextUpgradeFactory.
Definition at line 35 of file SocketContextUpgradeFactory.cpp.
{
        unsigned char ebytes[16];
        getentropy(ebytes, 16);
        request.set("Sec-WebSocket-Key", base64::base64_encode(ebytes, 16));
        request.set("Sec-WebSocket-Version", "13");
    }
References base64::base64_encode(), and web::http::client::Request::set().
Member Data Documentation
refCount
std::size_t web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::refCount protected inherited
Definition at line 59 of file SocketContextUpgradeFactory.h.
request
Request* web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::request private inherited
Definition at line 73 of file SocketContextUpgradeFactory.h.
Request
friend web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::Request private inherited
Definition at line 77 of file SocketContextUpgradeFactory.h.
response
Response* web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::response private inherited
Definition at line 74 of file SocketContextUpgradeFactory.h.
Response
friend web::http::SocketContextUpgradeFactory< web::http::client::Request , web::http::client::Response >::Response private inherited
Definition at line 76 of file SocketContextUpgradeFactory.h.
The documentation for this class was generated from the following files:
web/websocket/client/SocketContextUpgradeFactory.h
web/websocket/client/SocketContextUpgradeFactory.cpp