SNode.C: utils::DaemonError Class Reference
utils::DaemonError Class Reference
#include <Daemon.h>
Public Member Functions
DaemonError (const std::string &errorMessage)
~DaemonError () override
Public Member Functions inherited from utils::DaemonFailure
DaemonFailure (const std::string &failureMessage)
~DaemonFailure () override
Detailed Description
Definition at line 62 of file Daemon.h.
Constructor & Destructor Documentation
DaemonError()
utils::DaemonError::DaemonError (const std::string & errorMessage) explicit
Definition at line 68 of file Daemon.cpp.
        : DaemonFailure(errorMessage + ": " + std::strerror(errno)) {
    }
References utils::DaemonFailure::DaemonFailure().
Referenced by utils::Daemon::startDaemon(), and utils::Daemon::stopDaemon().
~DaemonError()
utils::DaemonError::~DaemonError () override
Definition at line 72 of file Daemon.cpp.
{
    }
The documentation for this class was generated from the following files:
utils/Daemon.h
utils/Daemon.cpp