SNode.C: express::RootRoute Class Reference
express::RootRoute Class Reference
#include <RootRoute.h>
Public Member Functions
RootRoute ()=default
Route & use (const RootRoute &rootRoute) const
Route & use (const std::string &relativeMountPath, const RootRoute &rootRoute) const
Route & use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & use (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & use (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & all (const RootRoute &rootRoute) const
Route & all (const std::string &relativeMountPath, const RootRoute &rootRoute) const
Route & all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & all (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & all (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & get (const RootRoute &rootRoute) const
Route & get (const std::string &relativeMountPath, const RootRoute &rootRoute) const
Route & get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & get (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & get (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & put (const RootRoute &rootRoute) const
Route & put (const std::string &relativeMountPath, const RootRoute &rootRoute) const
Route & put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & put (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & put (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & post (const RootRoute &rootRoute) const
Route & post (const std::string &relativeMountPath, const RootRoute &rootRoute) const
Route & post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & post (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & post (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & del (const RootRoute &rootRoute) const
Route & del (const std::string &relativeMountPath, const RootRoute &rootRoute) const
Route & del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & del (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & del (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & connect (const RootRoute &rootRoute) const
Route & connect (const std::string &relativeMountPath, const RootRoute &rootRoute) const
Route & connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & connect (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & connect (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & options (const RootRoute &rootRoute) const
Route & options (const std::string &relativeMountPath, const RootRoute &rootRoute) const
Route & options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & options (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & options (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & trace (const RootRoute &rootRoute) const
Route & trace (const std::string &relativeMountPath, const RootRoute &rootRoute) const
Route & trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & trace (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & trace (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & patch (const RootRoute &rootRoute) const
Route & patch (const std::string &relativeMountPath, const RootRoute &rootRoute) const
Route & patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & patch (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & patch (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & head (const RootRoute &rootRoute) const
Route & head (const std::string &relativeMountPath, const RootRoute &rootRoute) const
Route & head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & head (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & head (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Public Attributes
bool strict = true
Protected Member Functions
void dispatch (Controller &&controller)
void dispatch (Controller &controller)
std::shared_ptr< dispatcher::RouterDispatcher > getDispatcher () const
std::list< Route > & routes () const
bool dispatch (Controller &controller, const std::string &parentMountPath)
bool dispatchNext (Controller &controller, const std::string &parentMountPath)
Private Attributes
MountPoint mountPoint
std::shared_ptr< Dispatcher > dispatcher
Friends
class Route
class Controller
template<typename Server >
class WebAppT
Detailed Description
Definition at line 60 of file RootRoute.h.
Constructor & Destructor Documentation
RootRoute()
express::RootRoute::RootRoute () default
Member Function Documentation
all() [1/8]
Route & express::RootRoute::all (const RootRoute & rootRoute) const
Definition at line 88 of file RootRoute.cpp.
all() [2/8]
Route & express::RootRoute::all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 88 of file RootRoute.cpp.
all() [3/8]
template<typename... Lambdas> Route & express::Route::all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 55 of file Route.hpp.
all() [4/8]
Route & express::RootRoute::all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 88 of file RootRoute.cpp.
all() [5/8]
template<typename... Lambdas> Route & express::Route::all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 55 of file Route.hpp.
all() [6/8]
Route & express::RootRoute::all (const std::string & relativeMountPath, const RootRoute & rootRoute) const
Definition at line 88 of file RootRoute.cpp.
all() [7/8]
Route & express::RootRoute::all (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 88 of file RootRoute.cpp.
all() [8/8]
Route & express::RootRoute::all (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 88 of file RootRoute.cpp.
connect() [1/8]
Route & express::RootRoute::connect (const RootRoute & rootRoute) const
Definition at line 93 of file RootRoute.cpp.
connect() [2/8]
Route & express::RootRoute::connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 93 of file RootRoute.cpp.
connect() [3/8]
template<typename... Lambdas> Route & express::Route::connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 60 of file Route.hpp.
connect() [4/8]
Route & express::RootRoute::connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 93 of file RootRoute.cpp.
connect() [5/8]
template<typename... Lambdas> Route & express::Route::connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 60 of file Route.hpp.
connect() [6/8]
Route & express::RootRoute::connect (const std::string & relativeMountPath, const RootRoute & rootRoute) const
Definition at line 93 of file RootRoute.cpp.
connect() [7/8]
Route & express::RootRoute::connect (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 93 of file RootRoute.cpp.
connect() [8/8]
Route & express::RootRoute::connect (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 93 of file RootRoute.cpp.
del() [1/8]
Route & express::RootRoute::del (const RootRoute & rootRoute) const
Definition at line 92 of file RootRoute.cpp.
del() [2/8]
Route & express::RootRoute::del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 92 of file RootRoute.cpp.
del() [3/8]
template<typename... Lambdas> Route & express::Route::del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 59 of file Route.hpp.
del() [4/8]
Route & express::RootRoute::del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 92 of file RootRoute.cpp.
del() [5/8]
template<typename... Lambdas> Route & express::Route::del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 59 of file Route.hpp.
del() [6/8]
Route & express::RootRoute::del (const std::string & relativeMountPath, const RootRoute & rootRoute) const
Definition at line 92 of file RootRoute.cpp.
del() [7/8]
Route & express::RootRoute::del (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 92 of file RootRoute.cpp.
del() [8/8]
Route & express::RootRoute::del (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 92 of file RootRoute.cpp.
dispatch() [1/3]
void express::RootRoute::dispatch (Controller && controller) protected
Definition at line 71 of file RootRoute.cpp.
{
        controller.setRootRoute(this);
        dispatch(controller);
    }
References dispatch(), and express::Controller::setRootRoute().
dispatch() [2/3]
void express::RootRoute::dispatch (Controller & controller) protected
Definition at line 77 of file RootRoute.cpp.
{
        if (!Route::dispatch(controller, "")) {
            if (strict) {
                controller.getResponse()->sendStatus(404);
            } else if (controller.laxRouting() && !Route::dispatch(controller, "")) {
                controller.getResponse()->sendStatus(404);
            }
        }
    }
References express::Route::dispatch(), express::Controller::getResponse(), express::Controller::laxRouting(), express::Response::sendStatus(), and strict.
Referenced by dispatch(), and express::Controller::next().
dispatch() [3/3]
bool express::Route::dispatch (Controller & controller, const std::string & parentMountPath) protected inherited
Definition at line 63 of file Route.cpp.
{
        controller.setCurrentRoute(this);
        bool dispatched = dispatcher->dispatch(controller, parentMountPath, mountPoint);
        if (!dispatched) { // TODO: only call if parent route matched
            dispatched = controller.dispatchNext(parentMountPath);
        }
        return dispatched;
    }
References express::Dispatcher::dispatch(), express::Route::dispatcher, express::Controller::dispatchNext(), express::Route::mountPoint, and express::Controller::setCurrentRoute().
Referenced by dispatch(), express::Route::dispatch(), express::dispatcher::RouterDispatcher::dispatch(), and express::Dispatcher::dispatchNext().
dispatchNext()
bool express::Route::dispatchNext (Controller & controller, const std::string & parentMountPath) protected inherited
Definition at line 75 of file Route.cpp.
{
        return dispatcher->dispatchNext(controller, parentMountPath);
    }
References express::Route::dispatcher, and express::Dispatcher::dispatchNext().
Referenced by express::Controller::dispatchNext().
get() [1/8]
Route & express::RootRoute::get (const RootRoute & rootRoute) const
Definition at line 89 of file RootRoute.cpp.
get() [2/8]
Route & express::RootRoute::get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 89 of file RootRoute.cpp.
get() [3/8]
template<typename... Lambdas> Route & express::Route::get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 56 of file Route.hpp.
get() [4/8]
Route & express::RootRoute::get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 89 of file RootRoute.cpp.
get() [5/8]
template<typename... Lambdas> Route & express::Route::get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 56 of file Route.hpp.
get() [6/8]
Route & express::RootRoute::get (const std::string & relativeMountPath, const RootRoute & rootRoute) const
Definition at line 89 of file RootRoute.cpp.
get() [7/8]
Route & express::RootRoute::get (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 89 of file RootRoute.cpp.
get() [8/8]
Route & express::RootRoute::get (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 89 of file RootRoute.cpp.
getDispatcher()
std::shared_ptr< dispatcher::RouterDispatcher > express::RootRoute::getDispatcher () const protected
Definition at line 63 of file RootRoute.cpp.
{
        return std::dynamic_pointer_cast<dispatcher::RouterDispatcher>(dispatcher);
    }
References express::Route::dispatcher.
head() [1/8]
Route & express::RootRoute::head (const RootRoute & rootRoute) const
Definition at line 97 of file RootRoute.cpp.
head() [2/8]
Route & express::RootRoute::head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 97 of file RootRoute.cpp.
head() [3/8]
template<typename... Lambdas> Route & express::Route::head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 64 of file Route.hpp.
head() [4/8]
Route & express::RootRoute::head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 97 of file RootRoute.cpp.
head() [5/8]
template<typename... Lambdas> Route & express::Route::head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 64 of file Route.hpp.
head() [6/8]
Route & express::RootRoute::head (const std::string & relativeMountPath, const RootRoute & rootRoute) const
Definition at line 97 of file RootRoute.cpp.
head() [7/8]
Route & express::RootRoute::head (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 97 of file RootRoute.cpp.
head() [8/8]
Route & express::RootRoute::head (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 97 of file RootRoute.cpp.
options() [1/8]
Route & express::RootRoute::options (const RootRoute & rootRoute) const
Definition at line 94 of file RootRoute.cpp.
options() [2/8]
Route & express::RootRoute::options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 94 of file RootRoute.cpp.
options() [3/8]
template<typename... Lambdas> Route & express::Route::options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 61 of file Route.hpp.
options() [4/8]
Route & express::RootRoute::options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 94 of file RootRoute.cpp.
options() [5/8]
template<typename... Lambdas> Route & express::Route::options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 61 of file Route.hpp.
options() [6/8]
Route & express::RootRoute::options (const std::string & relativeMountPath, const RootRoute & rootRoute) const
Definition at line 94 of file RootRoute.cpp.
options() [7/8]
Route & express::RootRoute::options (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 94 of file RootRoute.cpp.
options() [8/8]
Route & express::RootRoute::options (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 94 of file RootRoute.cpp.
patch() [1/8]
Route & express::RootRoute::patch (const RootRoute & rootRoute) const
Definition at line 96 of file RootRoute.cpp.
patch() [2/8]
Route & express::RootRoute::patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 96 of file RootRoute.cpp.
patch() [3/8]
template<typename... Lambdas> Route & express::Route::patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 63 of file Route.hpp.
patch() [4/8]
Route & express::RootRoute::patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 96 of file RootRoute.cpp.
patch() [5/8]
template<typename... Lambdas> Route & express::Route::patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 63 of file Route.hpp.
patch() [6/8]
Route & express::RootRoute::patch (const std::string & relativeMountPath, const RootRoute & rootRoute) const
Definition at line 96 of file RootRoute.cpp.
patch() [7/8]
Route & express::RootRoute::patch (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 96 of file RootRoute.cpp.
patch() [8/8]
Route & express::RootRoute::patch (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 96 of file RootRoute.cpp.
post() [1/8]
Route & express::RootRoute::post (const RootRoute & rootRoute) const
Definition at line 91 of file RootRoute.cpp.
post() [2/8]
Route & express::RootRoute::post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 91 of file RootRoute.cpp.
post() [3/8]
template<typename... Lambdas> Route & express::Route::post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 58 of file Route.hpp.
post() [4/8]
Route & express::RootRoute::post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 91 of file RootRoute.cpp.
post() [5/8]
template<typename... Lambdas> Route & express::Route::post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 58 of file Route.hpp.
post() [6/8]
Route & express::RootRoute::post (const std::string & relativeMountPath, const RootRoute & rootRoute) const
Definition at line 91 of file RootRoute.cpp.
post() [7/8]
Route & express::RootRoute::post (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 91 of file RootRoute.cpp.
post() [8/8]
Route & express::RootRoute::post (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 91 of file RootRoute.cpp.
put() [1/8]
Route & express::RootRoute::put (const RootRoute & rootRoute) const
Definition at line 90 of file RootRoute.cpp.
put() [2/8]
Route & express::RootRoute::put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 90 of file RootRoute.cpp.
put() [3/8]
template<typename... Lambdas> Route & express::Route::put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 57 of file Route.hpp.
put() [4/8]
Route & express::RootRoute::put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 90 of file RootRoute.cpp.
put() [5/8]
template<typename... Lambdas> Route & express::Route::put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 57 of file Route.hpp.
put() [6/8]
Route & express::RootRoute::put (const std::string & relativeMountPath, const RootRoute & rootRoute) const
Definition at line 90 of file RootRoute.cpp.
put() [7/8]
Route & express::RootRoute::put (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 90 of file RootRoute.cpp.
put() [8/8]
Route & express::RootRoute::put (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 90 of file RootRoute.cpp.
routes()
std::list< Route > & express::RootRoute::routes () const protected
Definition at line 67 of file RootRoute.cpp.
{
        return std::dynamic_pointer_cast<dispatcher::RouterDispatcher>(dispatcher)->getRoutes();
    }
References express::Route::dispatcher, and express::dispatcher::RouterDispatcher::getRoutes().
trace() [1/8]
Route & express::RootRoute::trace (const RootRoute & rootRoute) const
Definition at line 95 of file RootRoute.cpp.
trace() [2/8]
Route & express::RootRoute::trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 95 of file RootRoute.cpp.
trace() [3/8]
template<typename... Lambdas> Route & express::Route::trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 62 of file Route.hpp.
trace() [4/8]
Route & express::RootRoute::trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 95 of file RootRoute.cpp.
trace() [5/8]
template<typename... Lambdas> Route & express::Route::trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 62 of file Route.hpp.
trace() [6/8]
Route & express::RootRoute::trace (const std::string & relativeMountPath, const RootRoute & rootRoute) const
Definition at line 95 of file RootRoute.cpp.
trace() [7/8]
Route & express::RootRoute::trace (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 95 of file RootRoute.cpp.
trace() [8/8]
Route & express::RootRoute::trace (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 95 of file RootRoute.cpp.
use() [1/8]
Route & express::RootRoute::use (const RootRoute & rootRoute) const
Definition at line 87 of file RootRoute.cpp.
use() [2/8]
Route & express::RootRoute::use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 87 of file RootRoute.cpp.
use() [3/8]
template<typename... Lambdas> Route & express::Route::use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 54 of file Route.hpp.
use() [4/8]
Route & express::RootRoute::use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 87 of file RootRoute.cpp.
use() [5/8]
template<typename... Lambdas> Route & express::Route::use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 54 of file Route.hpp.
use() [6/8]
Route & express::RootRoute::use (const std::string & relativeMountPath, const RootRoute & rootRoute) const
Definition at line 87 of file RootRoute.cpp.
use() [7/8]
Route & express::RootRoute::use (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 87 of file RootRoute.cpp.
use() [8/8]
Route & express::RootRoute::use (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 87 of file RootRoute.cpp.
Friends And Related Symbol Documentation
Controller
friend class Controller friend
Definition at line 87 of file RootRoute.h.
Route
friend class Route friend
Definition at line 86 of file RootRoute.h.
WebAppT
template<typename Server > friend class WebAppT friend
Definition at line 90 of file RootRoute.h.
Member Data Documentation
dispatcher
std::shared_ptr<Dispatcher> express::Route::dispatcher private inherited
Definition at line 73 of file Route.h.
Referenced by express::Route::dispatch(), express::Route::dispatchNext(), getDispatcher(), express::Route::Route(), express::Route::Route(), and routes().
mountPoint
MountPoint express::Route::mountPoint private inherited
Definition at line 72 of file Route.h.
Referenced by express::Route::dispatch(), express::Route::Route(), and express::Route::Route().
strict
bool express::RootRoute::strict = true
Definition at line 84 of file RootRoute.h.
Referenced by dispatch(), and express::Router::laxRouting().
The documentation for this class was generated from the following files:
express/RootRoute.h
express/RootRoute.cpp