SNode.C: core::TimerEventPublisher Class Reference
core::TimerEventPublisher Class Reference
#include <TimerEventPublisher.h>
Classes
class timernode_lt
Public Member Functions
TimerEventPublisher ()=default
utils::Timeval getNextTimeout (const utils::Timeval &currentTime)
void spanActiveEvents (const utils::Timeval &currentTime)
void unobserveDisableEvents ()
void remove (TimerEventReceiver *timer)
void erase (TimerEventReceiver *timer)
void insert (TimerEventReceiver *timer)
bool empty ()
void stop ()
Private Attributes
std::set< TimerEventReceiver *, timernode_lt > timerList
std::list< TimerEventReceiver * > removedList
Detailed Description
Definition at line 60 of file TimerEventPublisher.h.
Constructor & Destructor Documentation
TimerEventPublisher()
core::TimerEventPublisher::TimerEventPublisher () default
Member Function Documentation
empty()
bool core::TimerEventPublisher::empty ()
Definition at line 98 of file TimerEventPublisher.cpp.
{
        return timerList.empty();
    }
References timerList.
Referenced by core::EventMultiplexer::waitForEvents().
erase()
void core::TimerEventPublisher::erase (TimerEventReceiver * timer)
Definition at line 90 of file TimerEventPublisher.cpp.
{
        timerList.erase(timer);
    }
References timerList.
Referenced by core::TimerEventReceiver::restart(), and core::TimerEventReceiver::update().
getNextTimeout()
utils::Timeval core::TimerEventPublisher::getNextTimeout (const utils::Timeval & currentTime)
Definition at line 55 of file TimerEventPublisher.cpp.
{
        utils::Timeval nextTimeout({LONG_MAX, 0});
        if (!timerList.empty()) {
            nextTimeout = (*(timerList.begin()))->getTimeoutRelative(currentTime);
        }
        return nextTimeout;
    }
References core::TimerEventReceiver::getTimeoutRelative(), utils::Timeval::operator=(), timerList, and utils::Timeval::Timeval().
Referenced by core::EventMultiplexer::getNextTimeout().
insert()
void core::TimerEventPublisher::insert (TimerEventReceiver * timer)
Definition at line 94 of file TimerEventPublisher.cpp.
{
        timerList.insert(timer);
    }
References timerList.
Referenced by core::TimerEventReceiver::enable(), core::TimerEventReceiver::restart(), and core::TimerEventReceiver::update().
remove()
void core::TimerEventPublisher::remove (TimerEventReceiver * timer)
Definition at line 83 of file TimerEventPublisher.cpp.
{
        if (std::find(timerList.begin(), timerList.end(), timer) != timerList.end() &&
            std::find(removedList.begin(), removedList.end(), timer) == removedList.end()) {
            removedList.push_back(timer);
        }
    }
References removedList, and timerList.
Referenced by core::TimerEventReceiver::cancel(), and stop().
spanActiveEvents()
void core::TimerEventPublisher::spanActiveEvents (const utils::Timeval & currentTime)
Definition at line 65 of file TimerEventPublisher.cpp.
{
        for (TimerEventReceiver* timerEventReceiver : timerList) {
            if (timerEventReceiver->getTimeoutAbsolut() <= currentTime) {
                timerEventReceiver->span();
            } else {
                break;
            }
        }
    }
References core::TimerEventReceiver::getTimeoutAbsolut(), utils::Timeval::operator<=(), core::EventReceiver::span(), and timerList.
Referenced by core::EventMultiplexer::spanActiveEvents().
stop()
void core::TimerEventPublisher::stop ()
Definition at line 102 of file TimerEventPublisher.cpp.
{
        for (TimerEventReceiver* timer : timerList) { // cppcheck-suppress constVariablePointer
            remove(timer);
        }
        unobserveDisableEvents();
    }
References remove(), timerList, and unobserveDisableEvents().
Referenced by core::EventMultiplexer::signal(), and core::EventMultiplexer::terminate().
unobserveDisableEvents()
void core::TimerEventPublisher::unobserveDisableEvents ()
Definition at line 75 of file TimerEventPublisher.cpp.
{
        for (TimerEventReceiver* timerEventReceiver : removedList) {
            timerList.erase(timerEventReceiver);
            timerEventReceiver->unobservedEvent();
        }
        removedList.clear();
    }
References removedList, timerList, and core::TimerEventReceiver::unobservedEvent().
Referenced by core::EventMultiplexer::releaseExpiredResources(), and stop().
Member Data Documentation
removedList
std::list<TimerEventReceiver*> core::TimerEventPublisher::removedList private
Definition at line 85 of file TimerEventPublisher.h.
Referenced by remove(), and unobserveDisableEvents().
timerList
std::set<TimerEventReceiver*, timernode_lt> core::TimerEventPublisher::timerList private
Definition at line 84 of file TimerEventPublisher.h.
Referenced by empty(), erase(), getNextTimeout(), insert(), remove(), spanActiveEvents(), stop(), and unobserveDisableEvents().
The documentation for this class was generated from the following files:
core/TimerEventPublisher.h
core/TimerEventPublisher.cpp