SNode.C: net::in::stream::config::ConfigSocketServer Class Reference
net::in::stream::config::ConfigSocketServer Class Reference
#include <ConfigSocketServer.h>
Public Member Functions
ConfigSocketServer & setReuseAddress (bool reuseAddress=true)
bool getReuseAddress () const
ConfigSocketServer & setReusePort (bool reusePort=true)
bool getReusePort () const
ConfigSocketServer & setDisableNagleAlgorithm (bool disableNagleAlgorithm=true)
bool getDisableNagleAlgorithm () const
Public Member Functions inherited from net::config::ConfigConnection
utils::Timeval getReadTimeout () const
ConfigConnection & setReadTimeout (const utils::Timeval &newReadTimeoutSet)
utils::Timeval getWriteTimeout () const
ConfigConnection & setWriteTimeout (const utils::Timeval &newWriteTimeoutSet)
std::size_t getReadBlockSize () const
ConfigConnection & setReadBlockSize (std::size_t newReadBlockSize)
std::size_t getWriteBlockSize () const
ConfigConnection & setWriteBlockSize (std::size_t newWriteBlockSize)
utils::Timeval getTerminateTimeout () const
ConfigConnection & setTerminateTimeout (const utils::Timeval &newTerminateTimeout)
Public Member Functions inherited from net::config::ConfigPhysicalSocketServer
ConfigPhysicalSocketServer & setBacklog (int newBacklog)
int getBacklog () const
ConfigPhysicalSocketServer & setAcceptsPerTick (int acceptsPerTickSet)
int getAcceptsPerTick () const
ConfigPhysicalSocketServer & setAcceptTimeout (const utils::Timeval &acceptTimeout)
utils::Timeval getAcceptTimeout () const
Public Member Functions inherited from net::config::ConfigPhysicalSocket
const std::map< int, std::map< int, net::phy::PhysicalSocketOption > > & getSocketOptions ()
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, int optValue)
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, const std::string &optValue)
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, const std::vector< char > &optValue)
ConfigPhysicalSocket & removeSocketOption (int optLevel, int optName)
ConfigPhysicalSocket & setRetry (bool retry=true)
bool getRetry () const
ConfigPhysicalSocket & setRetryOnFatal (bool retry=true)
bool getRetryOnFatal () const
ConfigPhysicalSocket & setRetryTimeout (double sec)
double getRetryTimeout () const
ConfigPhysicalSocket & setRetryTries (unsigned int tries=0)
unsigned int getRetryTries () const
ConfigPhysicalSocket & setRetryBase (double base)
double getRetryBase () const
ConfigPhysicalSocket & setRetryLimit (unsigned int limit)
unsigned int getRetryLimit () const
ConfigPhysicalSocket & setRetryJitter (double percent)
double getRetryJitter () const
Protected Member Functions
ConfigSocketServer (net::config::ConfigInstance *instance)
~ConfigSocketServer () override
Protected Member Functions inherited from net::config::stream::ConfigSocketServer< net::in::config::ConfigAddress, net::in::config::ConfigAddressReverse >
ConfigSocketServer (net::config::ConfigInstance *instance)
Protected Member Functions inherited from net::config::ConfigConnection
ConfigConnection (ConfigInstance *instance)
Protected Member Functions inherited from net::config::ConfigSection
ConfigSection (ConfigInstance *instance, const std::string &name, const std::string &description)
ConfigSection (const ConfigSection &)=delete
ConfigSection (ConfigSection &&)=delete
ConfigSection & operator= (const ConfigSection &)=delete
ConfigSection & operator= (ConfigSection &&)=delete
CLI::Option * addOption (const std::string &name, const std::string &description)
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
template<typename ValueType >
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
Protected Member Functions inherited from net::config::ConfigPhysicalSocketServer
ConfigPhysicalSocketServer (ConfigInstance *instance)
Protected Member Functions inherited from net::config::ConfigPhysicalSocket
ConfigPhysicalSocket (ConfigInstance *instance)
CLI::Option * addSocketOption (const std::string &name, int optLevel, int optName, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Private Attributes
CLI::Option * reuseAddressOpt = nullptr
CLI::Option * reusePortOpt = nullptr
CLI::Option * disableNagleAlgorithmOpt = nullptr
Additional Inherited Members
Public Types inherited from net::config::stream::ConfigSocketServer< net::in::config::ConfigAddress, net::in::config::ConfigAddressReverse >
using Local = net::in::config::ConfigAddress< net::config::ConfigAddressLocal >
using Remote = net::in::config::ConfigAddressReverse< net::config::ConfigAddressReverse >
Public Types inherited from net::config::ConfigConnection
using Connection = ConfigConnection
Public Types inherited from net::config::ConfigPhysicalSocketServer
using Socket = ConfigPhysicalSocketServer
Protected Attributes inherited from net::config::ConfigSection
CLI::App * section = nullptr
Detailed Description
Definition at line 62 of file ConfigSocketServer.h.
Constructor & Destructor Documentation
ConfigSocketServer()
net::in::stream::config::ConfigSocketServer::ConfigSocketServer (net::config::ConfigInstance * instance) explicit protected
Definition at line 78 of file ConfigSocketServer.cpp.
        : net::config::stream::ConfigSocketServer<net::in::config::ConfigAddress, net::in::config::ConfigAddressReverse>(instance) {
        net::in::config::ConfigAddress<net::config::ConfigAddressLocal>::setPortRequired();
        net::in::config::ConfigAddress<net::config::ConfigAddressLocal>::setAiFlags(AI_PASSIVE);
        net::in::config::ConfigAddress<net::config::ConfigAddressLocal>::setAiSockType(SOCK_STREAM);
        net::in::config::ConfigAddress<net::config::ConfigAddressLocal>::setAiProtocol(IPPROTO_TCP);
        reuseAddressOpt = net::config::ConfigPhysicalSocket::addSocketOption( //
            "--reuse-address{true}",
            SOL_SOCKET,
            SO_REUSEADDR,
            "Reuse socket address",
            "bool",
            XSTR(IN_REUSE_ADDRESS),
            CLI::IsMember({"true", "false"}));
        reusePortOpt = net::config::ConfigPhysicalSocket::addSocketOption( //
            "--reuse-port{true}",
            SOL_SOCKET,
            SO_REUSEPORT,
            "Reuse port number",
            "bool",
            XSTR(IN_REUSE_PORT),
            CLI::IsMember({"true", "false"}));
        disableNagleAlgorithmOpt = net::config::ConfigPhysicalSocket::addSocketOption( //
            "--disable-nagle-algorithm{true}",
            IPPROTO_TCP,
            TCP_NODELAY,
            "Turn of Nagle algorithm",
            "tristat",
            XSTR(IN_SERVER_DISABLE_NAGLE_ALGORITHM),
            CLI::IsMember({"true", "false", "default"}));
    }
References net::config::ConfigPhysicalSocket::addSocketOption(), net::config::stream::ConfigSocketServer< ConfigAddressLocalT, ConfigAddressRemoteT >::ConfigSocketServer(), disableNagleAlgorithmOpt, reuseAddressOpt, reusePortOpt, net::in::config::ConfigAddress< ConfigAddressTypeT >::setAiProtocol(), net::in::config::ConfigAddress< ConfigAddressTypeT >::setAiSockType(), and net::in::config::ConfigAddress< ConfigAddressTypeT >::setPortRequired().
~ConfigSocketServer()
net::in::stream::config::ConfigSocketServer::~ConfigSocketServer () override protected
Definition at line 113 of file ConfigSocketServer.cpp.
{
    }
Member Function Documentation
getDisableNagleAlgorithm()
bool net::in::stream::config::ConfigSocketServer::getDisableNagleAlgorithm () const
Definition at line 166 of file ConfigSocketServer.cpp.
{
        return disableNagleAlgorithmOpt->as<bool>();
    }
References disableNagleAlgorithmOpt.
getReuseAddress()
bool net::in::stream::config::ConfigSocketServer::getReuseAddress () const
Definition at line 130 of file ConfigSocketServer.cpp.
{
        return reuseAddressOpt->as<bool>();
    }
References reuseAddressOpt.
getReusePort()
bool net::in::stream::config::ConfigSocketServer::getReusePort () const
Definition at line 148 of file ConfigSocketServer.cpp.
{
        return reusePortOpt->as<bool>();
    }
References reusePortOpt.
setDisableNagleAlgorithm()
ConfigSocketServer & net::in::stream::config::ConfigSocketServer::setDisableNagleAlgorithm (bool disableNagleAlgorithm = true)
Definition at line 152 of file ConfigSocketServer.cpp.
{
        if (disableNagleAlgorithm) {
            addSocketOption(IPPROTO_TCP, TCP_NODELAY, 1);
        } else {
            addSocketOption(IPPROTO_TCP, TCP_NODELAY, 0);
        }
        disableNagleAlgorithmOpt //
            ->default_val(disableNagleAlgorithm ? "true" : "false")
            ->clear();
        return *this;
    }
References net::config::ConfigPhysicalSocket::addSocketOption(), and disableNagleAlgorithmOpt.
setReuseAddress()
ConfigSocketServer & net::in::stream::config::ConfigSocketServer::setReuseAddress (bool reuseAddress = true)
Definition at line 116 of file ConfigSocketServer.cpp.
{
        if (reuseAddress) {
            addSocketOption(SOL_SOCKET, SO_REUSEADDR, 1);
        } else {
            addSocketOption(SOL_SOCKET, SO_REUSEADDR, 0);
        }
        reuseAddressOpt //
            ->default_val(reuseAddress ? "true" : "false")
            ->clear();
        return *this;
    }
References net::config::ConfigPhysicalSocket::addSocketOption(), and reuseAddressOpt.
Referenced by main().
setReusePort()
ConfigSocketServer & net::in::stream::config::ConfigSocketServer::setReusePort (bool reusePort = true)
Definition at line 134 of file ConfigSocketServer.cpp.
{
        if (reusePort) {
            addSocketOption(SOL_SOCKET, SO_REUSEPORT, 1);
        } else {
            addSocketOption(SOL_SOCKET, SO_REUSEPORT, 0);
        }
        reusePortOpt //
            ->default_val(reusePort ? "true" : "false")
            ->clear();
        return *this;
    }
References net::config::ConfigPhysicalSocket::addSocketOption(), and reusePortOpt.
Member Data Documentation
disableNagleAlgorithmOpt
CLI::Option* net::in::stream::config::ConfigSocketServer::disableNagleAlgorithmOpt = nullptr private
Definition at line 82 of file ConfigSocketServer.h.
Referenced by ConfigSocketServer(), getDisableNagleAlgorithm(), and setDisableNagleAlgorithm().
reuseAddressOpt
CLI::Option* net::in::stream::config::ConfigSocketServer::reuseAddressOpt = nullptr private
Definition at line 80 of file ConfigSocketServer.h.
Referenced by ConfigSocketServer(), getReuseAddress(), and setReuseAddress().
reusePortOpt
CLI::Option* net::in::stream::config::ConfigSocketServer::reusePortOpt = nullptr private
Definition at line 81 of file ConfigSocketServer.h.
Referenced by ConfigSocketServer(), getReusePort(), and setReusePort().
The documentation for this class was generated from the following files:
net/in/stream/config/ConfigSocketServer.h
net/in/stream/config/ConfigSocketServer.cpp