SNode.C: core::DynamicLoader Class Reference
core::DynamicLoader Class Reference
#include <DynamicLoader.h>
Classes
struct Library
Public Member Functions
DynamicLoader ()=delete
~DynamicLoader ()=delete
Static Public Member Functions
static void * dlOpen (const std::string &libFile, int flags=RTLD_LOCAL|RTLD_LAZY)
static void dlCloseDelayed (void *handle)
static int dlClose (void *handle)
static const void * dlSym (void *handle, const std::string &symbol)
static const char * dlError ()
Static Private Member Functions
static std::string canonicalizePath (const std::string &libFile)
static int dlClose (Library &library)
static int realExecDlClose (const Library &library)
static void execDlCloseDeleyed ()
static void execDlCloseAll ()
Static Private Attributes
static std::map< std::string, Library > dlOpenedLibraries
static std::map< void *, std::string > dlOpenedLibrariesByHandle
static std::list< std::string > closeQueue
Friends
class EventLoop
class EventMultiplexer
Detailed Description
Definition at line 58 of file DynamicLoader.h.
Constructor & Destructor Documentation
DynamicLoader()
core::DynamicLoader::DynamicLoader () delete
~DynamicLoader()
core::DynamicLoader::~DynamicLoader () delete
Member Function Documentation
canonicalizePath()
std::string core::DynamicLoader::canonicalizePath (const std::string & libFile) static private
Definition at line 59 of file DynamicLoader.cpp.
{
        std::string result = libFile;
        try {
            const std::filesystem::path p(libFile);
            // Only try to resolve symlinks / normalize if the file actually exists.
            // Otherwise (e.g. "libfoo.so" to be found via ld search path), keep as-is.
            if (std::filesystem::exists(p)) {
                result = std::filesystem::canonical(p).string();
            }
        } catch (...) {
            // keep as-is
        }
        return result;
    }
Referenced by dlOpen().
dlClose() [1/2]
int core::DynamicLoader::dlClose (Library & library) static private
Definition at line 196 of file DynamicLoader.cpp.
{
        int ret = 0;
        ret = realExecDlClose(library);
        if (ret != 0) {
            LOG(TRACE) << "  dlClose: " << DynamicLoader::dlError();
        } else {
            LOG(TRACE) << "  dlClose: " << library.fileName << ": success";
        }
        return ret;
    }
References dlError(), core::DynamicLoader::Library::fileName, and realExecDlClose().
Referenced by dlClose(), execDlCloseAll(), and execDlCloseDeleyed().
dlClose() [2/2]
int core::DynamicLoader::dlClose (void * handle) static
Definition at line 145 of file DynamicLoader.cpp.
{
        int ret = 0;
        if (handle == nullptr) {
            LOG(TRACE) << "DynLoader: dlClose: handle is nullptr";
        } else {
            auto itHandle = dlOpenedLibrariesByHandle.find(handle);
            if (itHandle == dlOpenedLibrariesByHandle.end()) {
                LOG(TRACE) << "DynLoader: dlClose: " << handle << ": not opened using dlOpen";
            } else {
                auto itLib = dlOpenedLibraries.find(itHandle->second);
                if (itLib == dlOpenedLibraries.end()) {
                    LOG(TRACE) << "DynLoader: dlClose: internal error: handle known but library record missing";
                } else {
                    Library& lib = itLib->second;
                    if (lib.refCount > 0) {
                        --lib.refCount;
                    }
                    if (lib.refCount != 0) {
                        LOG(TRACE) << "DynLoader: dlClose: " << lib.fileName << ": still referenced (refCount=" << lib.refCount << ")";
                    } else {
                        lib.closePending = false;
                        ret = dlClose(lib);
                        dlOpenedLibrariesByHandle.erase(lib.handle);
                        dlOpenedLibraries.erase(itLib);
                    }
                }
            }
        }
        return ret;
    }
References core::DynamicLoader::Library::closePending, dlClose(), dlOpenedLibraries, dlOpenedLibrariesByHandle, core::DynamicLoader::Library::fileName, core::DynamicLoader::Library::handle, and core::DynamicLoader::Library::refCount.
Referenced by web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::load(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load().
dlCloseDelayed()
void core::DynamicLoader::dlCloseDelayed (void * handle) static
Definition at line 114 of file DynamicLoader.cpp.
{
        if (handle == nullptr) {
            LOG(TRACE) << "DynLoader: dlCloseDelayed: handle is nullptr";
        } else {
            auto itHandle = dlOpenedLibrariesByHandle.find(handle);
            if (itHandle == dlOpenedLibrariesByHandle.end()) {
                LOG(TRACE) << "DynLoader: dlCloseDelayed: " << handle << ": not opened using dlOpen";
            } else {
                auto itLib = dlOpenedLibraries.find(itHandle->second);
                if (itLib == dlOpenedLibraries.end()) {
                    LOG(TRACE) << "DynLoader: dlCloseDelayed: internal error: handle known but library record missing";
                } else {
                    Library& lib = itLib->second;
                    if (lib.refCount > 0) {
                        --lib.refCount;
                    }
                    if (lib.refCount == 0) {
                        lib.closePending = true;
                        closeQueue.push_back(lib.canonicalFileName);
                        LOG(TRACE) << "DynLoader: dlCloseDelayed: " << lib.fileName;
                    } else {
                        LOG(TRACE) << "DynLoader: dlCloseDelayed: " << lib.fileName << ": still referenced (refCount=" << lib.refCount
                                   << ")";
                    }
                }
            }
        }
    }
References core::DynamicLoader::Library::canonicalFileName, core::DynamicLoader::Library::closePending, closeQueue, dlOpenedLibraries, dlOpenedLibrariesByHandle, core::DynamicLoader::Library::fileName, and core::DynamicLoader::Library::refCount.
Referenced by web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::unload(), and web::websocket::SubProtocolFactorySelector< web::websocket::SubProtocolFactory< web::websocket::client::SubProtocol > >::unload().
dlError()
const char * core::DynamicLoader::dlError () static
Definition at line 186 of file DynamicLoader.cpp.
{
        const char* err = core::system::dlerror();
        return err;
    }
References core::system::dlerror().
Referenced by dlClose(), dlOpen(), web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::load(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load().
dlOpen()
void * core::DynamicLoader::dlOpen (const std::string & libFile, int flags = RTLD_LOCAL | RTLD_LAZY) static
Definition at line 76 of file DynamicLoader.cpp.
{
        void* handle = nullptr;
        const std::string canonicalFile = canonicalizePath(libFile);
        auto it = dlOpenedLibraries.find(canonicalFile);
        if (it != dlOpenedLibraries.end()) {
            Library& lib = it->second;
            ++lib.refCount;
            lib.closePending = false;
            LOG(TRACE) << "DynLoader: dlOpen: " << lib.fileName << ": already open (refCount=" << lib.refCount << ")";
            handle = lib.handle;
        } else {
            // Clear possible stale error
            (void) DynamicLoader::dlError();
            handle = core::system::dlopen(libFile.c_str(), flags);
            if (handle != nullptr) {
                Library lib;
                lib.fileName = libFile;
                lib.canonicalFileName = canonicalFile;
                lib.handle = handle;
                lib.refCount = 1;
                lib.closePending = false;
                dlOpenedLibraries.emplace(canonicalFile, lib);
                dlOpenedLibrariesByHandle.emplace(handle, canonicalFile);
                LOG(TRACE) << "DynLoader: dlOpen: " << libFile << ": success";
            } else {
                LOG(TRACE) << "DynLoader: dlOpen: " << libFile << ": " << DynamicLoader::dlError();
            }
        }
        return handle;
    }
References core::DynamicLoader::Library::canonicalFileName, canonicalizePath(), core::DynamicLoader::Library::closePending, dlError(), core::system::dlopen(), dlOpenedLibraries, dlOpenedLibrariesByHandle, core::DynamicLoader::Library::fileName, core::DynamicLoader::Library::handle, and core::DynamicLoader::Library::refCount.
Referenced by web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::load(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load().
dlSym()
const void * core::DynamicLoader::dlSym (void * handle, const std::string & symbol) static
Definition at line 181 of file DynamicLoader.cpp.
{
        const void* sym = core::system::dlsym(handle, symbol.c_str());
        return sym;
    }
References core::system::dlsym().
Referenced by web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::load(), and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::load().
execDlCloseAll()
void core::DynamicLoader::execDlCloseAll () static private
Definition at line 237 of file DynamicLoader.cpp.
{
        LOG(TRACE) << "DynLoader: execDlCloseAll";
        for (auto& [canonical, library] : dlOpenedLibraries) {
            (void) dlClose(library);
        }
        dlOpenedLibraries.clear();
        dlOpenedLibrariesByHandle.clear();
        closeQueue.clear();
        LOG(TRACE) << "DynLoader: execDlCloseAll done";
    }
References closeQueue, dlClose(), dlOpenedLibraries, and dlOpenedLibrariesByHandle.
Referenced by core::EventLoop::free().
execDlCloseDeleyed()
void core::DynamicLoader::execDlCloseDeleyed () static private
Definition at line 210 of file DynamicLoader.cpp.
{
        if (!closeQueue.empty()) {
            LOG(TRACE) << "DynLoader: execDlCloseDeleyed";
            for (const std::string& canonicalFile : closeQueue) {
                auto it = dlOpenedLibraries.find(canonicalFile);
                if (it == dlOpenedLibraries.end()) {
                    continue;
                }
                Library& lib = it->second;
                if (!lib.closePending || lib.refCount != 0) {
                    continue;
                }
                lib.closePending = false;
                (void) dlClose(lib);
                dlOpenedLibrariesByHandle.erase(lib.handle);
                dlOpenedLibraries.erase(it);
            }
            closeQueue.clear();
            LOG(TRACE) << "DynLoader: execDlCloseDeleyed done";
        }
    }
References core::DynamicLoader::Library::closePending, closeQueue, dlClose(), dlOpenedLibraries, dlOpenedLibrariesByHandle, core::DynamicLoader::Library::handle, and core::DynamicLoader::Library::refCount.
Referenced by core::EventMultiplexer::releaseExpiredResources().
realExecDlClose()
int core::DynamicLoader::realExecDlClose (const Library & library) static private
Definition at line 191 of file DynamicLoader.cpp.
{
        const int ret = core::system::dlclose(library.handle);
        return ret;
    }
References core::system::dlclose(), and core::DynamicLoader::Library::handle.
Referenced by dlClose().
Friends And Related Symbol Documentation
EventLoop
friend class EventLoop friend
Definition at line 90 of file DynamicLoader.h.
EventMultiplexer
friend class EventMultiplexer friend
Definition at line 91 of file DynamicLoader.h.
Member Data Documentation
closeQueue
std::list< std::string > core::DynamicLoader::closeQueue static private
Definition at line 88 of file DynamicLoader.h.
Referenced by dlCloseDelayed(), execDlCloseAll(), and execDlCloseDeleyed().
dlOpenedLibraries
std::map< std::string, DynamicLoader::Library > core::DynamicLoader::dlOpenedLibraries static private
Definition at line 86 of file DynamicLoader.h.
Referenced by dlClose(), dlCloseDelayed(), dlOpen(), execDlCloseAll(), and execDlCloseDeleyed().
dlOpenedLibrariesByHandle
std::map< void *, std::string > core::DynamicLoader::dlOpenedLibrariesByHandle static private
Definition at line 87 of file DynamicLoader.h.
Referenced by dlClose(), dlCloseDelayed(), dlOpen(), execDlCloseAll(), and execDlCloseDeleyed().
The documentation for this class was generated from the following files:
core/DynamicLoader.h
core/DynamicLoader.cpp