SNode.C: web::websocket::Transmitter Class Reference
web::websocket::Transmitter Class Reference
#include <Transmitter.h>
Public Member Functions
Transmitter ()=delete
Transmitter (const Transmitter &)=delete
Transmitter & operator= (const Transmitter &)=delete
virtual ~Transmitter ()
Protected Member Functions
Transmitter (core::socket::stream::SocketConnection *socketConnection, bool masking)
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
Protected Attributes
bool closeSent = false
Private Member Functions
void send (bool end, uint8_t opCode, const char *message, std::size_t messageLength)
void sendFrame (bool fin, uint8_t opCode, const char *payload, uint64_t payloadLength)
void sendFrameData (uint8_t data) const
void sendFrameData (uint16_t data) const
void sendFrameData (uint32_t data) const
void sendFrameData (uint64_t data) const
void sendFrameData (const char *frame, uint64_t frameLength) const
Private Attributes
std::random_device randomDevice
std::uniform_int_distribution< uint32_t > distribution {0, UINT32_MAX}
core::socket::stream::SocketConnection * socketConnection = nullptr
bool masking = false
Detailed Description
Definition at line 61 of file Transmitter.h.
Constructor & Destructor Documentation
Transmitter() [1/3]
web::websocket::Transmitter::Transmitter () delete
Transmitter() [2/3]
web::websocket::Transmitter::Transmitter (const Transmitter &) delete
~Transmitter()
web::websocket::Transmitter::~Transmitter () virtual
Definition at line 65 of file Transmitter.cpp.
{
    }
Transmitter() [3/3]
web::websocket::Transmitter::Transmitter (core::socket::stream::SocketConnection * socketConnection, bool masking) protected
Definition at line 60 of file Transmitter.cpp.
        : socketConnection(socketConnection)
        , masking(masking) {
    }
References masking, and socketConnection.
Referenced by web::websocket::SubProtocolContext::SubProtocolContext().
Member Function Documentation
operator=()
Transmitter & web::websocket::Transmitter::operator= (const Transmitter &) delete
send()
void web::websocket::Transmitter::send (bool end, uint8_t opCode, const char * message, std::size_t messageLength) private
Definition at line 84 of file Transmitter.cpp.
{
        std::size_t messageOffset = 0;
        do {
            const std::size_t sendFrameLength =
                (messageLength - messageOffset <= WSMAXFRAMEPAYLOADLENGTH) ? messageLength - messageOffset : WSMAXFRAMEPAYLOADLENGTH;
            const bool fin = (sendFrameLength == messageLength - messageOffset) && end;
            sendFrame(fin, opCode, message + messageOffset, sendFrameLength);
            messageOffset += sendFrameLength;
            opCode = 0; // continuation
        } while (messageLength - messageOffset > 0);
    }
References sendFrame(), and WSMAXFRAMEPAYLOADLENGTH.
Referenced by sendMessage(), sendMessageEnd(), sendMessageFrame(), and sendMessageStart().
sendFrame()
void web::websocket::Transmitter::sendFrame (bool fin, uint8_t opCode, const char * payload, uint64_t payloadLength) private
Definition at line 101 of file Transmitter.cpp.
{
        uint64_t length = 0;
        if (payloadLength < 126) {
            length = payloadLength;
        } else if (payloadLength < 0x10000) {
            length = 126;
        } else {
            length = 127;
        }
        char header[2];
        header[0] = static_cast<char>((fin ? 0b10000000 : 0) | opCode);
        header[1] = static_cast<char>((masking ? 0b10000000 : 0) | length);
        sendFrameData(header, 2);
        switch (length) {
            case 126:
                sendFrameData(static_cast<uint16_t>(payloadLength));
                break;
            case 127:
                sendFrameData(payloadLength);
                break;
        }
        union MaskingKey {
            uint32_t keyAsValue;
            char keyAsBytes[4];
        };
        MaskingKey maskingKeyAsArray = {.keyAsValue = distribution(randomDevice)};
        if (payloadLength > 0) {
            LOG(TRACE) << "WebSocket send: Frame data\n" << utils::hexDump(payload, payloadLength, 32, true);
        }
        if (masking) {
            sendFrameData(maskingKeyAsArray.keyAsBytes, 4);
            for (uint64_t i = 0; i < payloadLength; i++) {
                *(const_cast<char*>(payload) + i) = static_cast<char>(*(payload + i) ^ *(maskingKeyAsArray.keyAsBytes + i % 4));
            }
        }
        sendFrameData(payload, payloadLength);
        if (masking) {
            for (uint64_t i = 0; i < payloadLength; i++) {
                *(const_cast<char*>(payload) + i) = static_cast<char>(*(payload + i) ^ *(maskingKeyAsArray.keyAsBytes + i % 4));
            }
        }
    }
References distribution, utils::hexDump(), masking, randomDevice, sendFrameData(), sendFrameData(), and sendFrameData().
Referenced by send().
sendFrameData() [1/5]
void web::websocket::Transmitter::sendFrameData (const char * frame, uint64_t frameLength) const private
Definition at line 183 of file Transmitter.cpp.
{
        if (!closeSent) {
            uint64_t frameOffset = 0;
            do {
                std::size_t sendChunkLen =
                    (frameLength - frameOffset <= SIZE_MAX) ? static_cast<std::size_t>(frameLength - frameOffset) : SIZE_MAX;
                socketConnection->sendToPeer(frame + frameOffset, sendChunkLen);
                frameOffset += sendChunkLen;
            } while (frameLength - frameOffset > 0);
        }
    }
References closeSent, core::socket::stream::SocketConnection::sendToPeer(), and socketConnection.
Referenced by sendFrame(), sendFrameData(), sendFrameData(), sendFrameData(), and sendFrameData().
sendFrameData() [2/5]
void web::websocket::Transmitter::sendFrameData (uint16_t data) const private
Definition at line 162 of file Transmitter.cpp.
{
        if (!closeSent) {
            uint16_t sendData = htobe16(data);
            sendFrameData(reinterpret_cast<char*>(&sendData), sizeof(uint16_t));
        }
    }
References closeSent, and sendFrameData().
Referenced by sendFrame().
sendFrameData() [3/5]
void web::websocket::Transmitter::sendFrameData (uint32_t data) const private
Definition at line 169 of file Transmitter.cpp.
{
        if (!closeSent) {
            uint32_t sendData = htobe32(data);
            sendFrameData(reinterpret_cast<char*>(&sendData), sizeof(uint32_t));
        }
    }
References closeSent, and sendFrameData().
sendFrameData() [4/5]
void web::websocket::Transmitter::sendFrameData (uint64_t data) const private
Definition at line 176 of file Transmitter.cpp.
{
        if (!closeSent) {
            uint64_t sendData = htobe64(data);
            sendFrameData(reinterpret_cast<char*>(&sendData), sizeof(uint64_t));
        }
    }
References closeSent, and sendFrameData().
Referenced by sendFrame().
sendFrameData() [5/5]
void web::websocket::Transmitter::sendFrameData (uint8_t data) const private
Definition at line 156 of file Transmitter.cpp.
{
        if (!closeSent) {
            sendFrameData(reinterpret_cast<char*>(&data), sizeof(uint8_t));
        }
    }
References closeSent, and sendFrameData().
sendMessage()
void web::websocket::Transmitter::sendMessage (uint8_t opCode, const char * message, std::size_t messageLength) protected
Definition at line 68 of file Transmitter.cpp.
{
        send(true, opCode, message, messageLength);
    }
References send().
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendMessage().
sendMessageEnd()
void web::websocket::Transmitter::sendMessageEnd (const char * message, std::size_t messageLength) protected
Definition at line 80 of file Transmitter.cpp.
{
        send(true, 0, message, messageLength);
    }
References send().
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendMessageEnd().
sendMessageFrame()
void web::websocket::Transmitter::sendMessageFrame (const char * message, std::size_t messageLength) protected
Definition at line 76 of file Transmitter.cpp.
{
        send(false, 0, message, messageLength);
    }
References send().
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendMessageFrame().
sendMessageStart()
void web::websocket::Transmitter::sendMessageStart (uint8_t opCode, const char * message, std::size_t messageLength) protected
Definition at line 72 of file Transmitter.cpp.
{
        send(false, opCode, message, messageLength);
    }
References send().
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendMessageStart().
Member Data Documentation
closeSent
bool web::websocket::Transmitter::closeSent = false protected
Definition at line 98 of file Transmitter.h.
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageEnd(), sendFrameData(), sendFrameData(), sendFrameData(), sendFrameData(), and sendFrameData().
distribution
std::uniform_int_distribution<uint32_t> web::websocket::Transmitter::distribution {0, UINT32_MAX} private
Definition at line 91 of file Transmitter.h.
{0, UINT32_MAX};
Referenced by sendFrame().
masking
bool web::websocket::Transmitter::masking = false private
Definition at line 95 of file Transmitter.h.
Referenced by sendFrame(), and Transmitter().
randomDevice
std::random_device web::websocket::Transmitter::randomDevice private
Definition at line 90 of file Transmitter.h.
Referenced by sendFrame().
socketConnection
core::socket::stream::SocketConnection* web::websocket::Transmitter::socketConnection = nullptr private
Definition at line 93 of file Transmitter.h.
Referenced by sendFrameData(), and Transmitter().
The documentation for this class was generated from the following files:
web/websocket/Transmitter.h
web/websocket/Transmitter.cpp