SNode.C: web::http::Parser Class Reference
web::http::Parser Class Reference abstract
#include <Parser.h>
Public Member Functions
Parser (core::socket::stream::SocketContext *socketContext, const enum HTTPCompliance &compliance=HTTPCompliance::RFC2616|HTTPCompliance::RFC7230)
virtual ~Parser ()
std::size_t parse ()
void reset ()
Protected Types
enum struct HTTPCompliance : unsigned short {
RFC1945 = 0x01 << 0 , RFC2616 = 0x01 << 1 , RFC7230 = 0x01 << 2 , RFC7231 = 0x01 << 3 ,
RFC7232 = 0x01 << 4 , RFC7233 = 0x01 << 5 , RFC7234 = 0x01 << 6 , RFC7235 = 0x01 << 7 ,
RFC7540 = 0x01 << 8 , RFC7541 = 0x01 << 9
}
enum struct ParserState {
BEGIN , FIRSTLINE , HEADER , BODY ,
TRAILER , ERROR
}
Protected Member Functions
virtual void analyzeHeader ()
Protected Attributes
enum web::http::Parser::HTTPCompliance hTTPCompliance
ParserState parserState = ParserState::BEGIN
TransferEncoding transferEncoding = TransferEncoding::HTTP10
CiStringMap< std::string > headers
std::vector< char > content
int httpMajor = 0
int httpMinor = 0
std::list< web::http::ContentDecoder * > decoderQueue
core::socket::stream::SocketContext * socketContext = nullptr
std::string line
std::size_t contentLength = 0
std::size_t contentLengthRead = 0
Static Protected Attributes
static const std::regex httpVersionRegex
Private Member Functions
virtual void begin ()=0
virtual void parseStartLine (const std::string &line)=0
virtual void parseError (int code, const std::string &reason)=0
virtual void parsingFinished ()=0
std::size_t readStartLine ()
std::size_t readHeader ()
std::size_t readContent ()
std::size_t readTrailer ()
Private Attributes
web::http::decoder::Fields headerDecoder
std::set< std::string > trailerFieldsExpected
web::http::decoder::Fields trailerDecoder
Friends
enum HTTPCompliance operator| (const enum HTTPCompliance &c1, const enum HTTPCompliance &c2)
enum HTTPCompliance operator& (const enum HTTPCompliance &c1, const enum HTTPCompliance &c2)
Detailed Description
Definition at line 71 of file Parser.h.
Member Enumeration Documentation
HTTPCompliance
enum struct web::http::Parser::HTTPCompliance : unsigned short strong protected
Enumerator
RFC1945
RFC2616
RFC7230
RFC7231
RFC7232
RFC7233
RFC7234
RFC7235
RFC7540
RFC7541
Definition at line 73 of file Parser.h.
                                   : unsigned short {
            RFC1945 = 0x01 << 0, // HTTP 1.0
            RFC2616 = 0x01 << 1, // HTTP 1.1
            RFC7230 = 0x01 << 2, // Message Syntax and Routing
            RFC7231 = 0x01 << 3, // Semantics and Content
            RFC7232 = 0x01 << 4, // Conditional Requests
            RFC7233 = 0x01 << 5, // Range Requests
            RFC7234 = 0x01 << 6, // Caching
            RFC7235 = 0x01 << 7, // Authentication
            RFC7540 = 0x01 << 8, // HTTP 2.0
            RFC7541 = 0x01 << 9  // Header Compression
        } hTTPCompliance;
ParserState
enum struct web::http::Parser::ParserState strong protected
Enumerator
BEGIN
FIRSTLINE
HEADER
BODY
TRAILER
ERROR
Definition at line 98 of file Parser.h.
{ BEGIN, FIRSTLINE, HEADER, BODY, TRAILER, ERROR };
Constructor & Destructor Documentation
Parser()
web::http::Parser::Parser (core::socket::stream::SocketContext * socketContext, const enum HTTPCompliance & compliance = HTTPCompliance::RFC2616 | HTTPCompliance::RFC7230) explicit
Definition at line 63 of file Parser.cpp.
        : hTTPCompliance(compliance)
        , socketContext(socketContext)
        , headerDecoder(socketContext)
        , trailerDecoder(socketContext) {
    }
References web::http::decoder::Fields::Fields(), headerDecoder, socketContext, and trailerDecoder.
Referenced by web::http::server::RequestParser::RequestParser(), and web::http::client::ResponseParser::ResponseParser().
~Parser()
web::http::Parser::~Parser () virtual
Definition at line 70 of file Parser.cpp.
                    {
        reset();
    }
References reset().
Member Function Documentation
analyzeHeader()
void web::http::Parser::analyzeHeader () protected virtual
Reimplemented in web::http::client::ResponseParser, and web::http::server::RequestParser.
Definition at line 160 of file Parser.cpp.
{
        if (headers.contains("Content-Length")) {
            contentLength = std::stoul(headers["Content-Length"]);
            transferEncoding = TransferEncoding::Identity;
            decoderQueue.emplace_back(new web::http::decoder::Identity(socketContext, contentLength));
        }
        if (headers.contains("Transfer-Encoding")) {
            const std::string& encoding = headers["Transfer-Encoding"];
            if (web::http::ciContains(encoding, "chunked")) {
                transferEncoding = TransferEncoding::Chunked;
                decoderQueue.emplace_back(new web::http::decoder::Chunked(socketContext));
                if (headers.contains("Trailer")) {
                    std::string trailers = headers["Trailer"];
                    while (!trailers.empty()) {
                        std::string trailerField;
                        std::tie(trailerField, trailers) = httputils::str_split(trailers, ',');
                        httputils::str_trimm(trailerField);
                        trailerFieldsExpected.insert(trailerField);
                        trailerField.clear();
                    }
                    trailerDecoder.setFieldsExpected(trailerFieldsExpected);
                }
            }
            if (web::http::ciContains(encoding, "compressed")) {
                //  decoderQueue.emplace_back(new web::http::decoder::Compress(socketContext));
            }
            if (web::http::ciContains(encoding, "deflate")) {
                //  decoderQueue.emplace_back(new web::http::decoder::Deflate(socketContext));
            }
            if (web::http::ciContains(encoding, "gzip")) {
                //  decoderQueue.emplace_back(new web::http::decoder::GZip(socketContext));
            }
        }
        if (decoderQueue.empty()) {
            transferEncoding = TransferEncoding::HTTP10;
            decoderQueue.emplace_back(new web::http::decoder::HTTP10Response(socketContext));
        }
        if (headers.contains("Content-Encoding")) {
            const std::string& encoding = headers["Content-Encoding"];
            if (web::http::ciContains(encoding, "compressed")) {
                //  decoderQueue.emplace_back(new web::http::decoder::Compress(socketContext));
            }
            if (web::http::ciContains(encoding, "deflate")) {
                //  decoderQueue.emplace_back(new web::http::decoder::Deflate(socketContext));
            }
            if (web::http::ciContains(encoding, "gzip")) {
                //  decoderQueue.emplace_back(new web::http::decoder::GZip(socketContext));
            }
            if (web::http::ciContains(encoding, "br")) {
                //  decoderQueue.emplace_back(new web::http::decoder::Br(socketContext));
            }
        }
    }
References web::http::decoder::Chunked::Chunked(), web::http::Chunked, web::http::ciContains(), contentLength, decoderQueue, headers, web::http::HTTP10, web::http::decoder::HTTP10Response::HTTP10Response(), web::http::decoder::Identity::Identity(), web::http::Identity, web::http::decoder::Fields::setFieldsExpected(), socketContext, httputils::str_split(), httputils::str_trimm(), trailerDecoder, trailerFieldsExpected, and transferEncoding.
Referenced by web::http::client::ResponseParser::analyzeHeader(), web::http::server::RequestParser::analyzeHeader(), and readHeader().
begin()
virtual void web::http::Parser::begin () private pure virtual
Implemented in web::http::client::ResponseParser, and web::http::server::RequestParser.
Referenced by parse().
parse()
std::size_t web::http::Parser::parse ()
Definition at line 92 of file Parser.cpp.
{
        std::size_t ret = 0;
        std::size_t consumed = 0;
        do {
            switch (parserState) {
                case ParserState::BEGIN:
                    begin();
                    parserState = ParserState::FIRSTLINE;
                    [[fallthrough]];
                case ParserState::FIRSTLINE:
                    ret = readStartLine();
                    break;
                case ParserState::HEADER:
                    ret = readHeader();
                    break;
                case ParserState::BODY:
                    ret = readContent();
                    break;
                case ParserState::TRAILER:
                    ret = readTrailer();
                    break;
                case ParserState::ERROR:
                    break;
            }
            consumed += ret;
        } while (ret > 0 && parserState != ParserState::BEGIN && parserState != ParserState::ERROR);
        return consumed;
    }
References BEGIN, begin(), BODY, ERROR, FIRSTLINE, HEADER, parserState, readContent(), readHeader(), readStartLine(), readTrailer(), and TRAILER.
Referenced by apps::http::SimpleSocketProtocol::onReceivedFromPeer(), web::http::client::SocketContext::onReceivedFromPeer(), and web::http::server::SocketContext::onReceivedFromPeer().
parseError()
virtual void web::http::Parser::parseError (int code, const std::string & reason) private pure virtual
Implemented in web::http::client::ResponseParser, and web::http::server::RequestParser.
Referenced by readContent(), readHeader(), and readTrailer().
parseStartLine()
virtual void web::http::Parser::parseStartLine (const std::string & line) private pure virtual
Implemented in web::http::client::ResponseParser, and web::http::server::RequestParser.
Referenced by readStartLine().
parsingFinished()
virtual void web::http::Parser::parsingFinished () private pure virtual
Implemented in web::http::client::ResponseParser, and web::http::server::RequestParser.
Referenced by readContent(), and readTrailer().
readContent()
std::size_t web::http::Parser::readContent () private
Definition at line 219 of file Parser.cpp.
{
        ContentDecoder* contentDecoder = decoderQueue.front();
        const std::size_t consumed = contentDecoder->read();
        if (contentDecoder->isComplete()) {
            contentDecoder = decoderQueue.back();
            std::vector<char> chunk = contentDecoder->getContent();
            content.insert(content.end(), chunk.begin(), chunk.end());
            if (transferEncoding == TransferEncoding::Chunked && headers.contains("Trailer")) {
                parserState = Parser::ParserState::TRAILER;
            } else {
                parsingFinished();
            }
        } else if (contentDecoder->isError()) {
            parseError(400, "Wrong content encoding");
        }
        return consumed;
    }
References web::http::Chunked, content, decoderQueue, web::http::ContentDecoder::getContent(), headers, web::http::ContentDecoder::isComplete(), web::http::ContentDecoder::isError(), parseError(), parserState, parsingFinished(), web::http::ContentDecoder::read(), TRAILER, and transferEncoding.
Referenced by parse().
readHeader()
std::size_t web::http::Parser::readHeader () private
Definition at line 147 of file Parser.cpp.
{
        const std::size_t consumed = headerDecoder.read();
        if (headerDecoder.isError()) {
            parseError(headerDecoder.getErrorCode(), headerDecoder.getErrorReason());
        } else if (headerDecoder.isComplete()) {
            headers = std::move(headerDecoder.getHeader());
            analyzeHeader();
        }
        return consumed;
    }
References analyzeHeader(), web::http::decoder::Fields::getErrorCode(), web::http::decoder::Fields::getErrorReason(), web::http::decoder::Fields::getHeader(), headerDecoder, headers, web::http::decoder::Fields::isComplete(), web::http::decoder::Fields::isError(), parseError(), and web::http::decoder::Fields::read().
Referenced by parse().
readStartLine()
std::size_t web::http::Parser::readStartLine () private
Definition at line 123 of file Parser.cpp.
{
        std::size_t consumed = 0;
        std::size_t ret = 0;
        do {
            char ch = 0;
            ret = socketContext->readFromPeer(&ch, 1);
            if (ret > 0) {
                consumed += ret;
                if (ch == '\r' || ch == '\n') {
                    if (ch == '\n') {
                        parseStartLine(line);
                        line.clear();
                    }
                } else {
                    line += ch;
                }
            }
        } while (ret > 0 && parserState == ParserState::FIRSTLINE);
        return consumed;
    }
References FIRSTLINE, line, parserState, parseStartLine(), core::socket::stream::SocketContext::readFromPeer(), and socketContext.
Referenced by parse().
readTrailer()
std::size_t web::http::Parser::readTrailer () private
Definition at line 242 of file Parser.cpp.
{
        const std::size_t consumed = trailerDecoder.read();
        if (trailerDecoder.isError()) {
            parseError(trailerDecoder.getErrorCode(), trailerDecoder.getErrorReason());
        } else if (trailerDecoder.isComplete()) {
            web::http::CiStringMap<std::string>&& trailer = trailerDecoder.getHeader();
            headers.insert(trailer.begin(), trailer.end());
            parsingFinished();
        }
        return consumed;
    }
References web::http::decoder::Fields::getErrorCode(), web::http::decoder::Fields::getErrorReason(), web::http::decoder::Fields::getHeader(), headers, web::http::decoder::Fields::isComplete(), web::http::decoder::Fields::isError(), parseError(), parsingFinished(), web::http::decoder::Fields::read(), and trailerDecoder.
Referenced by parse().
reset()
void web::http::Parser::reset ()
Definition at line 74 of file Parser.cpp.
                       {
        parserState = ParserState::BEGIN;
        headers.clear();
        content.clear();
        httpMinor = 0;
        httpMajor = 0;
        line.clear();
        contentLength = 0;
        contentLengthRead = 0;
        for (ContentDecoder* contentDecoder : decoderQueue) {
            delete contentDecoder;
        }
        decoderQueue.clear();
        trailerFieldsExpected.clear();
    }
References BEGIN, content, contentLength, contentLengthRead, decoderQueue, headers, httpMajor, httpMinor, line, parserState, and trailerFieldsExpected.
Referenced by web::http::client::ResponseParser::parseError(), web::http::server::RequestParser::parseError(), web::http::client::ResponseParser::parsingFinished(), web::http::server::RequestParser::parsingFinished(), and ~Parser().
Friends And Related Symbol Documentation
operator&
enum HTTPCompliance operator& (const enum HTTPCompliance & c1, const enum HTTPCompliance & c2) friend
Definition at line 260 of file Parser.cpp.
{
        return static_cast<enum Parser::HTTPCompliance>(static_cast<unsigned short>(c1) & static_cast<unsigned short>(c2));
    }
operator|
enum HTTPCompliance operator| (const enum HTTPCompliance & c1, const enum HTTPCompliance & c2) friend
Definition at line 256 of file Parser.cpp.
{
        return static_cast<enum Parser::HTTPCompliance>(static_cast<unsigned short>(c1) | static_cast<unsigned short>(c2));
    }
Member Data Documentation
content
std::vector<char> web::http::Parser::content protected
Definition at line 120 of file Parser.h.
Referenced by web::http::client::ResponseParser::parsingFinished(), web::http::server::RequestParser::parsingFinished(), readContent(), and reset().
contentLength
std::size_t web::http::Parser::contentLength = 0 protected
Definition at line 143 of file Parser.h.
Referenced by analyzeHeader(), web::http::client::ResponseParser::analyzeHeader(), web::http::server::RequestParser::analyzeHeader(), and reset().
contentLengthRead
std::size_t web::http::Parser::contentLengthRead = 0 protected
Definition at line 144 of file Parser.h.
Referenced by reset().
decoderQueue
std::list<web::http::ContentDecoder*> web::http::Parser::decoderQueue protected
Definition at line 125 of file Parser.h.
Referenced by analyzeHeader(), web::http::client::ResponseParser::getResponse(), readContent(), and reset().
headerDecoder
web::http::decoder::Fields web::http::Parser::headerDecoder private
Definition at line 130 of file Parser.h.
Referenced by Parser(), and readHeader().
headers
CiStringMap<std::string> web::http::Parser::headers protected
Definition at line 119 of file Parser.h.
Referenced by analyzeHeader(), web::http::client::ResponseParser::analyzeHeader(), web::http::server::RequestParser::analyzeHeader(), web::http::client::ResponseParser::parsingFinished(), web::http::server::RequestParser::parsingFinished(), readContent(), readHeader(), readTrailer(), and reset().
hTTPCompliance
enum web::http::Parser::HTTPCompliance web::http::Parser::hTTPCompliance protected
httpMajor
int web::http::Parser::httpMajor = 0 protected
Definition at line 122 of file Parser.h.
Referenced by web::http::client::ResponseParser::parseStartLine(), web::http::server::RequestParser::parseStartLine(), web::http::client::ResponseParser::parsingFinished(), web::http::server::RequestParser::parsingFinished(), and reset().
httpMinor
int web::http::Parser::httpMinor = 0 protected
Definition at line 123 of file Parser.h.
Referenced by web::http::client::ResponseParser::parseStartLine(), web::http::server::RequestParser::parseStartLine(), web::http::client::ResponseParser::parsingFinished(), web::http::server::RequestParser::parsingFinished(), and reset().
httpVersionRegex
const std::regex web::http::Parser::httpVersionRegex static protected
Definition at line 104 of file Parser.h.
Referenced by web::http::client::ResponseParser::parseStartLine(), and web::http::server::RequestParser::parseStartLine().
line
std::string web::http::Parser::line protected
Definition at line 142 of file Parser.h.
Referenced by readStartLine(), and reset().
parserState
ParserState web::http::Parser::parserState = ParserState::BEGIN protected
Definition at line 100 of file Parser.h.
Referenced by web::http::client::ResponseParser::analyzeHeader(), web::http::server::RequestParser::analyzeHeader(), parse(), web::http::client::ResponseParser::parseError(), web::http::server::RequestParser::parseError(), web::http::client::ResponseParser::parseStartLine(), web::http::server::RequestParser::parseStartLine(), web::http::client::ResponseParser::parsingFinished(), web::http::server::RequestParser::parsingFinished(), readContent(), readStartLine(), and reset().
socketContext
core::socket::stream::SocketContext* web::http::Parser::socketContext = nullptr protected
Definition at line 127 of file Parser.h.
Referenced by analyzeHeader(), Parser(), and readStartLine().
trailerDecoder
web::http::decoder::Fields web::http::Parser::trailerDecoder private
Definition at line 133 of file Parser.h.
Referenced by analyzeHeader(), Parser(), and readTrailer().
trailerFieldsExpected
std::set<std::string> web::http::Parser::trailerFieldsExpected private
Definition at line 132 of file Parser.h.
Referenced by analyzeHeader(), and reset().
transferEncoding
TransferEncoding web::http::Parser::transferEncoding = TransferEncoding::HTTP10 protected
Definition at line 102 of file Parser.h.
Referenced by analyzeHeader(), web::http::client::ResponseParser::analyzeHeader(), web::http::server::RequestParser::analyzeHeader(), and readContent().
The documentation for this class was generated from the following files:
web/http/Parser.h
web/http/Parser.cpp