SNode.C: core::socket::stream::SocketConnection Class Reference
core::socket::stream::SocketConnection Class Reference abstract
#include <SocketConnection.h>
Public Member Functions
SocketConnection (int fd, const net::config::ConfigInstance *config)
SocketConnection (const SocketConnection &)=delete
virtual int getFd () const =0
void setSocketContext (SocketContext *socketContext)
virtual void sendToPeer (const char *chunk, std::size_t chunkLen)=0
void sendToPeer (const std::string &data)
void sentToPeer (const std::vector< uint8_t > &data)
void sentToPeer (const std::vector< char > &data)
virtual bool streamToPeer (core::pipe::Source *source)=0
virtual void streamEof ()=0
virtual std::size_t readFromPeer (char *chunk, std::size_t chunkLen)=0
virtual void shutdownRead ()=0
virtual void shutdownWrite (bool forceClose)=0
const std::string & getInstanceName () const
const std::string & getConnectionName () const
SocketContext * getSocketContext () const
virtual const core::socket::SocketAddress & getBindAddress () const =0
virtual const core::socket::SocketAddress & getLocalAddress () const =0
virtual const core::socket::SocketAddress & getRemoteAddress () const =0
virtual void close ()=0
virtual void setTimeout (const utils::Timeval &timeout)=0
virtual void setReadTimeout (const utils::Timeval &timeout)=0
virtual void setWriteTimeout (const utils::Timeval &timeout)=0
virtual std::size_t getTotalSent () const =0
virtual std::size_t getTotalQueued () const =0
virtual std::size_t getTotalRead () const =0
virtual std::size_t getTotalProcessed () const =0
std::string getOnlineSince () const
std::string getOnlineDuration () const
const net::config::ConfigInstance * getConfigInstance () const
Protected Member Functions
virtual ~SocketConnection ()
void setSocketContext (const std::shared_ptr< SocketContextFactory > &socketContextFactory)
Protected Attributes
core::socket::stream::SocketContext * socketContext = nullptr
core::socket::stream::SocketContext * newSocketContext = nullptr
std::string instanceName
std::string connectionName
std::chrono::time_point< std::chrono::system_clock > onlineSinceTimePoint
Static Private Member Functions
static std::string timePointToString (const std::chrono::time_point< std::chrono::system_clock > &timePoint)
static std::string durationToString (const std::chrono::time_point< std::chrono::system_clock > &bevore, const std::chrono::time_point< std::chrono::system_clock > &later=std::chrono::system_clock::now())
Private Attributes
const net::config::ConfigInstance * config
Friends
class core::socket::stream::SocketContext
Detailed Description
Definition at line 82 of file SocketConnection.h.
Constructor & Destructor Documentation
SocketConnection() [1/2]
core::socket::stream::SocketConnection::SocketConnection (int fd, const net::config::ConfigInstance * config)
Definition at line 62 of file SocketConnection.cpp.
        : instanceName(config->getInstanceName())
        , connectionName("[" + std::to_string(fd) + "]" + (!instanceName.empty() ? " " : "") + instanceName)
        , onlineSinceTimePoint(std::chrono::system_clock::now())
        , config(config) {
    }
References connectionName, net::config::ConfigInstance::getInstanceName(), instanceName, and onlineSinceTimePoint.
SocketConnection() [2/2]
core::socket::stream::SocketConnection::SocketConnection (const SocketConnection &) delete
~SocketConnection()
core::socket::stream::SocketConnection::~SocketConnection () protected virtual
Definition at line 69 of file SocketConnection.cpp.
{
    }
Member Function Documentation
close()
virtual void core::socket::stream::SocketConnection::close () pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by core::socket::stream::SocketContext::close(), and setSocketContext().
durationToString()
std::string core::socket::stream::SocketConnection::durationToString (const std::chrono::time_point< std::chrono::system_clock > & bevore, const std::chrono::time_point< std::chrono::system_clock > & later = std::chrono::system_clock::now()) static private
Definition at line 147 of file SocketConnection.cpp.
{
        using seconds_duration_type = std::chrono::duration<std::chrono::seconds::rep>::rep;
        const seconds_duration_type totalSeconds = std::chrono::duration_cast<std::chrono::seconds>(later - bevore).count();
        // Compute days, hours, minutes, and seconds
        const seconds_duration_type days = totalSeconds / 86400; // 86400 seconds in a day
        seconds_duration_type remainder = totalSeconds % 86400;
        const seconds_duration_type hours = remainder / 3600;
        remainder = remainder % 3600;
        const seconds_duration_type minutes = remainder / 60;
        const seconds_duration_type seconds = remainder % 60;
        // Format the components into a string using stringstream
        std::ostringstream oss;
        if (days > 0) {
            oss << days << " day" << (days == 1 ? "" : "s") << ", ";
        }
        oss << std::setw(2) << std::setfill('0') << hours << ":" << std::setw(2) << std::setfill('0') << minutes << ":" << std::setw(2)
            << std::setfill('0') << seconds;
        return oss.str();
    }
Referenced by getOnlineDuration().
getBindAddress()
virtual const core::socket::SocketAddress & core::socket::stream::SocketConnection::getBindAddress () const pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
getConfigInstance()
const net::config::ConfigInstance * core::socket::stream::SocketConnection::getConfigInstance () const
Definition at line 128 of file SocketConnection.cpp.
{
        return config;
    }
getConnectionName()
const std::string & core::socket::stream::SocketConnection::getConnectionName () const
Definition at line 112 of file SocketConnection.cpp.
{
        return connectionName;
    }
References connectionName.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::attach(), web::http::server::SocketContext::deliverRequest(), web::http::client::SocketContext::deliverResponse(), web::http::client::SocketContext::deliverResponseParseError(), core::socket::stream::SocketContext::detach(), web::websocket::SubProtocol< SocketContextUpgradeT >::detach(), express::dispatcher::ApplicationDispatcher::dispatch(), express::dispatcher::MiddlewareDispatcher::dispatch(), express::dispatcher::RouterDispatcher::dispatch(), web::http::client::MasterRequest::executeUpgrade(), web::http::client::SocketContext::initiateRequest(), main(), web::http::client::SocketContext::onConnected(), web::http::server::SocketContext::onConnected(), web::http::client::SocketContext::onDisconnected(), web::http::server::SocketContext::onDisconnected(), web::websocket::SubProtocol< SocketContextUpgradeT >::onPongReceived(), core::socket::stream::SocketContext::onReadError(), web::http::client::SocketContext::onSignal(), web::http::server::SocketContext::onSignal(), core::socket::stream::SocketContext::onWriteError(), web::http::client::SocketContext::requestCompleted(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestDelivered(), web::http::client::MasterRequest::requestEventSource(), web::http::client::SocketContext::requestPrepared(), web::http::server::SocketContext::responseCompleted(), web::http::client::SocketContext::responseStarted(), web::http::server::SocketContext::responseStarted(), web::websocket::SubProtocol< SocketContextUpgradeT >::sendPing(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::SocketConnectionT(), web::http::server::SocketContext::SocketContext(), express::middleware::StaticMiddleware::StaticMiddleware(), web::websocket::SubProtocol< SocketContextUpgradeT >::SubProtocol(), web::http::client::MasterRequest::upgrade(), web::http::client::Request::upgrade(), web::http::server::Response::upgrade(), express::middleware::VerboseRequest::VerboseRequest(), and web::http::client::SocketContext::~SocketContext().
getFd()
virtual int core::socket::stream::SocketConnection::getFd () const pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
getInstanceName()
const std::string & core::socket::stream::SocketConnection::getInstanceName () const
Definition at line 108 of file SocketConnection.cpp.
{
        return instanceName;
    }
References instanceName.
getLocalAddress()
virtual const core::socket::SocketAddress & core::socket::stream::SocketConnection::getLocalAddress () const pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
getOnlineDuration()
std::string core::socket::stream::SocketConnection::getOnlineDuration () const
Definition at line 124 of file SocketConnection.cpp.
{
        return durationToString(onlineSinceTimePoint);
    }
References durationToString(), and onlineSinceTimePoint.
getOnlineSince()
std::string core::socket::stream::SocketConnection::getOnlineSince () const
Definition at line 120 of file SocketConnection.cpp.
{
        return timePointToString(onlineSinceTimePoint);
    }
References onlineSinceTimePoint, and timePointToString().
getRemoteAddress()
virtual const core::socket::SocketAddress & core::socket::stream::SocketConnection::getRemoteAddress () const pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
getSocketContext()
SocketContext * core::socket::stream::SocketConnection::getSocketContext () const
Definition at line 116 of file SocketConnection.cpp.
{
        return socketContext;
    }
References socketContext.
getTotalProcessed()
virtual std::size_t core::socket::stream::SocketConnection::getTotalProcessed () const pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by core::socket::stream::SocketContext::attach(), and core::socket::stream::SocketContext::getTotalProcessed().
getTotalQueued()
virtual std::size_t core::socket::stream::SocketConnection::getTotalQueued () const pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by core::socket::stream::SocketContext::attach(), and core::socket::stream::SocketContext::getTotalQueued().
getTotalRead()
virtual std::size_t core::socket::stream::SocketConnection::getTotalRead () const pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by core::socket::stream::SocketContext::getTotalRead().
getTotalSent()
virtual std::size_t core::socket::stream::SocketConnection::getTotalSent () const pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by core::socket::stream::SocketContext::getTotalSent().
readFromPeer()
virtual std::size_t core::socket::stream::SocketConnection::readFromPeer (char * chunk, std::size_t chunkLen) pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by core::socket::stream::SocketContext::readFromPeer().
sendToPeer() [1/2]
virtual void core::socket::stream::SocketConnection::sendToPeer (const char * chunk, std::size_t chunkLen) pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >.
Referenced by sendToPeer(), core::socket::stream::SocketContext::sendToPeer(), sentToPeer(), and sentToPeer().
sendToPeer() [2/2]
void core::socket::stream::SocketConnection::sendToPeer (const std::string & data)
Definition at line 96 of file SocketConnection.cpp.
{
        sendToPeer(data.data(), data.size());
    }
References sendToPeer().
Referenced by tls::getClient(), and legacy::getLegacyClient().
sentToPeer() [1/2]
void core::socket::stream::SocketConnection::sentToPeer (const std::vector< char > & data)
Definition at line 104 of file SocketConnection.cpp.
{
        sendToPeer(data.data(), data.size());
    }
References sendToPeer().
sentToPeer() [2/2]
void core::socket::stream::SocketConnection::sentToPeer (const std::vector< uint8_t > & data)
Definition at line 100 of file SocketConnection.cpp.
{
        sendToPeer(reinterpret_cast<const char*>(data.data()), data.size());
    }
References sendToPeer().
setReadTimeout()
virtual void core::socket::stream::SocketConnection::setReadTimeout (const utils::Timeval & timeout) pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by web::http::server::SocketContext::responseStarted().
setSocketContext() [1/2]
void core::socket::stream::SocketConnection::setSocketContext (const std::shared_ptr< SocketContextFactory > & socketContextFactory) protected
Definition at line 72 of file SocketConnection.cpp.
{
        SocketContext* socketContext = socketContextFactory->create(this);
        if (socketContext != nullptr) {
            LOG(DEBUG) << connectionName << ": SocketContext created successful";
            setSocketContext(socketContext);
        } else {
            LOG(ERROR) << connectionName << ": SocketContext failed to create";
            close();
        }
    }
References close(), connectionName, core::socket::stream::SocketContextFactory::create(), and setSocketContext().
setSocketContext() [2/2]
void core::socket::stream::SocketConnection::setSocketContext (SocketContext * socketContext)
Definition at line 84 of file SocketConnection.cpp.
{
        if (this->socketContext == nullptr) {
            this->socketContext = socketContext;
            socketContext->attach();
        } else {
            LOG(DEBUG) << connectionName << " SocketContext: switch";
            newSocketContext = socketContext;
        }
    }
References core::socket::stream::SocketContext::attach(), connectionName, newSocketContext, and socketContext.
Referenced by setSocketContext(), web::http::client::Request::upgrade(), and web::http::server::Response::upgrade().
setTimeout()
virtual void core::socket::stream::SocketConnection::setTimeout (const utils::Timeval & timeout) pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by iot::mqtt::Mqtt::initSession(), and core::socket::stream::SocketContext::setTimeout().
setWriteTimeout()
virtual void core::socket::stream::SocketConnection::setWriteTimeout (const utils::Timeval & timeout) pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by web::http::client::SocketContext::setSseEventReceiver().
shutdownRead()
virtual void core::socket::stream::SocketConnection::shutdownRead () pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by core::socket::stream::SocketContext::shutdownRead().
shutdownWrite()
virtual void core::socket::stream::SocketConnection::shutdownWrite (bool forceClose) pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by core::socket::stream::SocketContext::shutdownWrite().
streamEof()
virtual void core::socket::stream::SocketConnection::streamEof () pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by core::socket::stream::SocketContext::streamEof().
streamToPeer()
virtual bool core::socket::stream::SocketConnection::streamToPeer (core::pipe::Source * source) pure virtual
Implemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalClientSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalServerSocket, Config >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, and core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >.
Referenced by core::socket::stream::SocketContext::streamToPeer().
timePointToString()
std::string core::socket::stream::SocketConnection::timePointToString (const std::chrono::time_point< std::chrono::system_clock > & timePoint) static private
Definition at line 132 of file SocketConnection.cpp.
{
        const std::time_t time = std::chrono::system_clock::to_time_t(timePoint);
        std::tm* tm_ptr = std::gmtime(&time);
        char buffer[100];
        std::string onlineSince = "Formatting error";
        // Format: "2025-02-02 14:30:00"
        if (std::strftime(buffer, sizeof(buffer), "%Y-%m-%d %H:%M:%S", tm_ptr) > 0) {
            onlineSince = std::string(buffer) + " UTC";
        }
        return onlineSince;
    }
Referenced by getOnlineSince().
Friends And Related Symbol Documentation
core::socket::stream::SocketContext
friend class core::socket::stream::SocketContext friend
Definition at line 154 of file SocketConnection.h.
Member Data Documentation
config
const net::config::ConfigInstance* core::socket::stream::SocketConnection::config private
Definition at line 152 of file SocketConnection.h.
connectionName
std::string core::socket::stream::SocketConnection::connectionName protected
Definition at line 147 of file SocketConnection.h.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::doWriteShutdown(), core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >::getConfig(), getConnectionName(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::onReceivedFromPeer(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::onSignal(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::readTimeout(), setSocketContext(), setSocketContext(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::shutdownRead(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::shutdownWrite(), SocketConnection(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::SocketConnectionT(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::unobservedEvent(), and core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::writeTimeout().
instanceName
std::string core::socket::stream::SocketConnection::instanceName protected
Definition at line 146 of file SocketConnection.h.
Referenced by getInstanceName(), and SocketConnection().
newSocketContext
core::socket::stream::SocketContext* core::socket::stream::SocketConnection::newSocketContext = nullptr protected
Definition at line 144 of file SocketConnection.h.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::onReceivedFromPeer(), and setSocketContext().
onlineSinceTimePoint
std::chrono::time_point<std::chrono::system_clock> core::socket::stream::SocketConnection::onlineSinceTimePoint protected
Definition at line 149 of file SocketConnection.h.
Referenced by getOnlineDuration(), getOnlineSince(), and SocketConnection().
socketContext
core::socket::stream::SocketContext* core::socket::stream::SocketConnection::socketContext = nullptr protected
Definition at line 143 of file SocketConnection.h.
Referenced by getSocketContext(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::onReadError(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::onReceivedFromPeer(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::onSignal(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::onWriteError(), setSocketContext(), and core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::unobservedEvent().
The documentation for this class was generated from the following files:
core/socket/stream/SocketConnection.h
core/socket/stream/SocketConnection.cpp