SNode.C: web::http::client::ResponseParser Class Reference
web::http::client::ResponseParser Class Reference
#include <ResponseParser.h>
Public Member Functions
ResponseParser (core::socket::stream::SocketContext *socketContext, const std::function< void(void)> &onStart, const std::function< void(std::string &, std::string &, std::string &)> &onResponse, const std::function< void(std::map< std::string, std::string > &, std::map< std::string, web::http::CookieOptions > &)> &onHeader, const std::function< void(std::vector< uint8_t > &)> &onContent, const std::function< void(ResponseParser &)> &onParsed, const std::function< void(int, const std::string &)> &onError)
void reset () override
std::size_t parse ()
Protected Types
enum struct HTTPCompliance : unsigned short {
RFC1945 = 0x01 << 0 , RFC2616 = 0x01 << 1 , RFC7230 = 0x01 << 2 , RFC7231 = 0x01 << 3 ,
RFC7232 = 0x01 << 4 , RFC7233 = 0x01 << 5 , RFC7234 = 0x01 << 6 , RFC7235 = 0x01 << 7 ,
RFC7540 = 0x01 << 8 , RFC7541 = 0x01 << 9
}
enum struct ParserState {
BEGIN , FIRSTLINE , HEADER , BODY ,
ERROR
}
Protected Attributes
enum web::http::Parser::HTTPCompliance hTTPCompliance
enum web::http::Parser::ParserState parserState = ParserState::BEGIN
std::size_t contentLength = 0
std::map< std::string, std::string > headers
std::vector< uint8_t > content
std::string httpVersion
int httpMajor = 0
int httpMinor = 0
Static Protected Attributes
static std::regex httpVersionRegex
Private Member Functions
void begin () override
enum Parser::ParserState parseStartLine (const std::string &line) override
enum Parser::ParserState parseHeader () override
enum Parser::ParserState parseContent (std::vector< uint8_t > &content) override
enum Parser::ParserState parsingError (int code, const std::string &reason) override
void parsingFinished ()
std::size_t readStartLine ()
std::size_t readHeaderLine ()
void splitHeaderLine (const std::string &line)
std::size_t readContent ()
Private Attributes
std::string statusCode
std::string reason
std::map< std::string, CookieOptions > cookies
std::function< void(void)> onStart
std::function< void(std::string &, std::string &, std::string &)> onResponse
std::function< void(std::map< std::string, std::string > &, std::map< std::string, web::http::CookieOptions > &)> onHeader
std::function< void(std::vector< uint8_t > &)> onContent
std::function< void(ResponseParser &)> onParsed
std::function< void(int, const std::string &)> onError
core::socket::stream::SocketContext * socketContext = nullptr
bool EOL {false}
std::string line
std::size_t contentRead = 0
Detailed Description
Definition at line 39 of file ResponseParser.h.
Member Enumeration Documentation
HTTPCompliance
enum struct web::http::Parser::HTTPCompliance : unsigned short strong protected inherited
Enumerator
RFC1945
RFC2616
RFC7230
RFC7231
RFC7232
RFC7233
RFC7234
RFC7235
RFC7540
RFC7541
Definition at line 45 of file Parser.h.
                                   : unsigned short {
            RFC1945 = 0x01 << 0, // HTTP 1.0
            RFC2616 = 0x01 << 1, // HTTP 1.1
            RFC7230 = 0x01 << 2, // Message Syntax and Routing
            RFC7231 = 0x01 << 3, // Semantics and Content
            RFC7232 = 0x01 << 4, // Conditional Requests
            RFC7233 = 0x01 << 5, // Range Requests
            RFC7234 = 0x01 << 6, // Caching
            RFC7235 = 0x01 << 7, // Authentication
            RFC7540 = 0x01 << 8, // HTTP 2.0
            RFC7541 = 0x01 << 9  // Header Compression
        } hTTPCompliance;
ParserState
enum struct web::http::Parser::ParserState strong protected inherited
Enumerator
BEGIN
FIRSTLINE
HEADER
BODY
ERROR
Definition at line 68 of file Parser.h.
{ BEGIN, FIRSTLINE, HEADER, BODY, ERROR } parserState = ParserState::BEGIN;
Constructor & Destructor Documentation
ResponseParser()
web::http::client::ResponseParser::ResponseParser (core::socket::stream::SocketContext * socketContext, const std::function< void(void)> & onStart, const std::function< void(std::string &, std::string &, std::string &)> & onResponse, const std::function< void(std::map< std::string, std::string > &, std::map< std::string, web::http::CookieOptions > &)> & onHeader, const std::function< void(std::vector< uint8_t > &)> & onContent, const std::function< void(ResponseParser &)> & onParsed, const std::function< void(int, const std::string &)> & onError)
Definition at line 41 of file ResponseParser.cpp.
        : Parser(socketContext)
        , onStart(onStart)
        , onResponse(onResponse)
        , onHeader(onHeader)
        , onContent(onContent)
        , onParsed(onParsed)
        , onError(onError) {
    }
References onContent, onError, onHeader, onParsed, onResponse, onStart, and web::http::Parser::Parser().
Member Function Documentation
begin()
void web::http::client::ResponseParser::begin () override private virtual
Implements web::http::Parser.
Definition at line 66 of file ResponseParser.cpp.
{
        onStart();
    }
References onStart.
parse()
std::size_t web::http::Parser::parse () inherited
Definition at line 49 of file Parser.cpp.
{
        std::size_t ret = 0;
        std::size_t consumed = 0;
        do {
            switch (parserState) {
                case ParserState::BEGIN:
                    reset();
                    begin();
                    parserState = ParserState::FIRSTLINE;
                    [[fallthrough]];
                case ParserState::FIRSTLINE:
                    ret = readStartLine();
                    break;
                case ParserState::HEADER:
                    ret = readHeaderLine();
                    break;
                case ParserState::BODY:
                    ret = readContent();
                    break;
                case ParserState::ERROR:
                    break;
            }
            consumed += ret;
        } while (ret > 0 && parserState != ParserState::BEGIN && parserState != ParserState::ERROR);
        return consumed;
    }
References web::http::Parser::BEGIN, web::http::Parser::begin(), web::http::Parser::BODY, web::http::Parser::ERROR, web::http::Parser::FIRSTLINE, web::http::Parser::HEADER, web::http::Parser::readContent(), web::http::Parser::readHeaderLine(), web::http::Parser::readStartLine(), and web::http::Parser::reset().
Referenced by web::http::client::SocketContext< RequestT, ResponseT >::onReceivedFromPeer(), and web::http::server::SocketContext< RequestT, ResponseT >::onReceivedFromPeer().
parseContent()
Parser::ParserState web::http::client::ResponseParser::parseContent (std::vector< uint8_t > & content) override private virtual
Implements web::http::Parser.
Definition at line 160 of file ResponseParser.cpp.
{
        onContent(content);
        parsingFinished();
        return ParserState::BEGIN;
    }
References web::http::Parser::BEGIN, onContent, and parsingFinished().
parseHeader()
enum Parser::ParserState web::http::client::ResponseParser::parseHeader () override private virtual
Implements web::http::Parser.
Definition at line 102 of file ResponseParser.cpp.
{
        for (const auto& [headerFieldName, headerFieldValue] : Parser::headers) {
            if (headerFieldName != "set-cookie") {
                if (headerFieldName == "content-length") {
                    Parser::contentLength = static_cast<std::size_t>(std::stoi(headerFieldValue));
                }
            } else {
                std::string cookiesLine = headerFieldValue;
                while (!cookiesLine.empty()) {
                    std::string cookieLine;
                    std::tie(cookieLine, cookiesLine) = httputils::str_split(cookiesLine, ',');
                    std::string cookieOptions;
                    std::string cookie;
                    std::tie(cookie, cookieOptions) = httputils::str_split(cookieLine, ';');
                    std::string cookieName;
                    std::string cookieValue;
                    std::tie(cookieName, cookieValue) = httputils::str_split(cookie, '=');
                    httputils::str_trimm(cookieName);
                    httputils::str_trimm(cookieValue);
                    std::map<std::string, CookieOptions>::iterator cookieElement;
                    bool inserted = false;
                    std::tie(cookieElement, inserted) = cookies.insert({cookieName, CookieOptions(cookieValue)});
                    while (!cookieOptions.empty()) {
                        std::string option;
                        std::tie(option, cookieOptions) = httputils::str_split(cookieOptions, ';');
                        std::string optionName;
                        std::string optionValue;
                        std::tie(optionName, optionValue) = httputils::str_split(option, '=');
                        httputils::str_trimm(optionName);
                        httputils::str_trimm(optionValue);
                        cookieElement->second.setOption(optionName, optionValue);
                    }
                }
            }
        }
        Parser::headers.erase("set-cookie");
        onHeader(Parser::headers, cookies);
        enum Parser::ParserState parserState = Parser::ParserState::BODY;
        if (contentLength == 0 && httpMinor == 1) {
            parsingFinished();
            parserState = ParserState::BEGIN;
        }
        return parserState;
    }
References web::http::Parser::BEGIN, web::http::Parser::BODY, web::http::Parser::contentLength, web::http::CookieOptions::CookieOptions(), cookies, web::http::Parser::headers, web::http::Parser::httpMinor, onHeader, parsingFinished(), web::http::CookieOptions::setOption(), httputils::str_split(), and httputils::str_trimm().
parseStartLine()
enum Parser::ParserState web::http::client::ResponseParser::parseStartLine (const std::string & line) override private virtual
Implements web::http::Parser.
Definition at line 70 of file ResponseParser.cpp.
{
        enum Parser::ParserState parserState = Parser::ParserState::HEADER;
        if (!line.empty()) {
            std::string remaining;
            std::tie(httpVersion, remaining) = httputils::str_split(line, ' ');
            std::smatch httpVersionMatch;
            if (!std::regex_match(httpVersion, httpVersionMatch, httpVersionRegex)) {
                parserState = parsingError(400, "Wrong protocol version");
            } else {
                httpMajor = std::stoi(httpVersionMatch.str(1));
                httpMinor = std::stoi(httpVersionMatch.str(2));
                std::tie(statusCode, reason) = httputils::str_split(remaining, ' ');
                if (StatusCode::contains(std::stoi(statusCode))) {
                    if (!reason.empty()) {
                        onResponse(httpVersion, statusCode, reason);
                    } else {
                        parserState = parsingError(400, "No reason phrase");
                    }
                } else {
                    parserState = parsingError(400, "Unknown status code");
                }
            }
        } else {
            parserState = parsingError(400, "Response line empty");
        }
        return parserState;
    }
References web::http::StatusCode::contains(), web::http::Parser::HEADER, web::http::Parser::httpMajor, web::http::Parser::httpMinor, web::http::Parser::httpVersion, web::http::Parser::httpVersionRegex, onResponse, reason, statusCode, and httputils::str_split().
parsingError()
enum Parser::ParserState web::http::client::ResponseParser::parsingError (int code, const std::string & reason) override private virtual
Implements web::http::Parser.
Definition at line 167 of file ResponseParser.cpp.
{
        onError(code, reason);
        return ParserState::ERROR;
    }
References web::http::Parser::ERROR, and onError.
parsingFinished()
void web::http::client::ResponseParser::parsingFinished () private
Definition at line 173 of file ResponseParser.cpp.
{
        onParsed(*this);
    }
References onParsed.
Referenced by parseContent(), and parseHeader().
readContent()
std::size_t web::http::Parser::readContent () private inherited
Definition at line 180 of file Parser.cpp.
{
        static char contentJunk[MAX_CONTENT_JUNK_LEN];
        std::size_t consumed = 0;
        if (httpMinor == 0 && contentLength == 0) {
            consumed = socketContext->readFromPeer(contentJunk, MAX_CONTENT_JUNK_LEN);
            std::size_t contentJunkLen = static_cast<std::size_t>(consumed);
            if (contentJunkLen > 0) {
                content.insert(content.end(), contentJunk, contentJunk + contentJunkLen);
            } else {
                parserState = parseContent(content);
            }
        } else if (httpMinor == 1) {
            std::size_t contentJunkLenLeft =
                (contentLength - contentRead < MAX_CONTENT_JUNK_LEN) ? contentLength - contentRead : MAX_CONTENT_JUNK_LEN;
            consumed = socketContext->readFromPeer(contentJunk, contentJunkLenLeft);
            std::size_t contentJunkLen = static_cast<std::size_t>(consumed);
            if (contentJunkLen > 0) {
                if (contentRead + contentJunkLen <= contentLength) {
                    content.insert(content.end(), contentJunk, contentJunk + contentJunkLen);
                    contentRead += contentJunkLen;
                    if (contentRead == contentLength) {
                        parserState = parseContent(content);
                    }
                } else {
                    parserState = parsingError(400, "Content to long");
                }
            }
        }
        return consumed;
    }
References web::http::Parser::content, web::http::Parser::contentLength, web::http::Parser::contentRead, web::http::Parser::httpMinor, core::socket::stream::SocketContext::readFromPeer(), and web::http::Parser::socketContext.
Referenced by web::http::Parser::parse().
readHeaderLine()
std::size_t web::http::Parser::readHeaderLine () private inherited
Definition at line 101 of file Parser.cpp.
{
        std::size_t consumed = 0;
        std::size_t ret = 0;
        do {
            char ch = 0;
            ret = socketContext->readFromPeer(&ch, 1);
            if (ret > 0) {
                if (ch == '\r' || ch == '\n') {
                    consumed++;
                    if (ch == '\n') {
                        if (EOL) {
                            splitHeaderLine(line);
                            line.clear();
                            if (parserState != ParserState::ERROR) {
                                parserState = parseHeader();
                            }
                            EOL = false;
                        } else if (line.empty()) {
                            if (parserState != ParserState::ERROR) {
                                parserState = parseHeader();
                            }
                        } else {
                            EOL = true;
                        }
                    }
                } else if (EOL) {
                    if (std::isblank(ch)) {
                        if ((hTTPCompliance & HTTPCompliance::RFC7230) == HTTPCompliance::RFC7230) {
                            parserState = parsingError(400, "Header Folding");
                        } else {
                            line += ch;
                            consumed++;
                        }
                    } else {
                        splitHeaderLine(line);
                        line.clear();
                        line += ch;
                        consumed++;
                    }
                    EOL = false;
                } else {
                    line += ch;
                    consumed++;
                }
            }
        } while (ret > 0 && parserState == ParserState::HEADER);
        return consumed;
    }
References web::http::Parser::EOL, web::http::Parser::ERROR, web::http::Parser::HEADER, web::http::Parser::line, web::http::operator&(), core::socket::stream::SocketContext::readFromPeer(), web::http::Parser::RFC7230, web::http::Parser::socketContext, and web::http::Parser::splitHeaderLine().
Referenced by web::http::Parser::parse().
readStartLine()
std::size_t web::http::Parser::readStartLine () private inherited
Definition at line 77 of file Parser.cpp.
{
        std::size_t consumed = 0;
        std::size_t ret = 0;
        do {
            char ch = 0;
            ret = socketContext->readFromPeer(&ch, 1);
            if (ret > 0) {
                consumed += ret;
                if (ch == '\r' || ch == '\n') {
                    if (ch == '\n') {
                        parserState = parseStartLine(line);
                        line.clear();
                    }
                } else {
                    line += ch;
                }
            }
        } while (ret > 0 && parserState == ParserState::FIRSTLINE);
        return consumed;
    }
References web::http::Parser::FIRSTLINE, web::http::Parser::line, core::socket::stream::SocketContext::readFromPeer(), and web::http::Parser::socketContext.
Referenced by web::http::Parser::parse().
reset()
void web::http::client::ResponseParser::reset () override virtual
Reimplemented from web::http::Parser.
Definition at line 58 of file ResponseParser.cpp.
{
        Parser::reset();
        httpVersion.clear();
        statusCode.clear();
        reason.clear();
        cookies.clear();
    }
References cookies, web::http::Parser::httpVersion, reason, web::http::Parser::reset(), and statusCode.
splitHeaderLine()
void web::http::Parser::splitHeaderLine (const std::string & line) private inherited
Definition at line 153 of file Parser.cpp.
{
        if (!line.empty()) {
            std::string headerFieldName;
            std::string headerFieldValue;
            std::tie(headerFieldName, headerFieldValue) = httputils::str_split(line, ':');
            if (headerFieldName.empty()) {
                parserState = parsingError(400, "Header-field empty");
            } else if (std::isblank(headerFieldName.back()) || std::isblank(headerFieldName.front())) {
                parserState = parsingError(400, "White space before or after header-field");
            } else if (headerFieldValue.empty()) {
                parserState = parsingError(400, "Header-value of field \"" + headerFieldName + "\" empty");
            } else {
                httputils::to_lower(headerFieldName);
                httputils::str_trimm(headerFieldValue);
                if (headers.find(headerFieldName) == headers.end()) {
                    headers.insert({headerFieldName, headerFieldValue});
                } else {
                    headers[headerFieldName] += "," + headerFieldValue;
                }
            }
        } else {
            parserState = parsingError(400, "Header-line empty");
        }
    }
References web::http::Parser::headers, httputils::str_split(), httputils::str_trimm(), and httputils::to_lower().
Referenced by web::http::Parser::readHeaderLine().
Member Data Documentation
content
std::vector<uint8_t> web::http::Parser::content protected inherited
Definition at line 84 of file Parser.h.
Referenced by web::http::Parser::readContent(), and web::http::Parser::reset().
contentLength
std::size_t web::http::Parser::contentLength = 0 protected inherited
Definition at line 82 of file Parser.h.
Referenced by parseHeader(), web::http::server::RequestParser::parseHeader(), web::http::Parser::readContent(), and web::http::Parser::reset().
contentRead
std::size_t web::http::Parser::contentRead = 0 private inherited
Definition at line 103 of file Parser.h.
Referenced by web::http::Parser::readContent(), and web::http::Parser::reset().
cookies
std::map<std::string, CookieOptions> web::http::client::ResponseParser::cookies private
Definition at line 65 of file ResponseParser.h.
Referenced by parseHeader(), and reset().
EOL
bool web::http::Parser::EOL {false} private inherited
Definition at line 99 of file Parser.h.
{false};
Referenced by web::http::Parser::readHeaderLine().
headers
std::map<std::string, std::string> web::http::Parser::headers protected inherited
Definition at line 83 of file Parser.h.
Referenced by parseHeader(), web::http::server::RequestParser::parseHeader(), web::http::Parser::reset(), and web::http::Parser::splitHeaderLine().
hTTPCompliance
enum web::http::Parser::HTTPCompliance web::http::Parser::hTTPCompliance protected inherited
httpMajor
int web::http::Parser::httpMajor = 0 protected inherited
Definition at line 87 of file Parser.h.
Referenced by parseStartLine(), web::http::server::RequestParser::parseStartLine(), and web::http::server::RequestParser::reset().
httpMinor
int web::http::Parser::httpMinor = 0 protected inherited
Definition at line 88 of file Parser.h.
Referenced by parseHeader(), web::http::server::RequestParser::parseHeader(), parseStartLine(), web::http::server::RequestParser::parseStartLine(), web::http::Parser::readContent(), and web::http::server::RequestParser::reset().
httpVersion
std::string web::http::Parser::httpVersion protected inherited
Definition at line 86 of file Parser.h.
Referenced by parseStartLine(), web::http::server::RequestParser::parseStartLine(), reset(), and web::http::server::RequestParser::reset().
httpVersionRegex
std::regex web::http::Parser::httpVersionRegex static protected inherited
Definition at line 69 of file Parser.h.
Referenced by parseStartLine(), and web::http::server::RequestParser::parseStartLine().
line
std::string web::http::Parser::line private inherited
Definition at line 102 of file Parser.h.
Referenced by web::http::Parser::readHeaderLine(), and web::http::Parser::readStartLine().
onContent
std::function<void(std::vector<uint8_t>&)> web::http::client::ResponseParser::onContent private
Definition at line 70 of file ResponseParser.h.
Referenced by parseContent(), and ResponseParser().
onError
std::function<void(int, const std::string&)> web::http::client::ResponseParser::onError private
Definition at line 72 of file ResponseParser.h.
Referenced by parsingError(), and ResponseParser().
onHeader
std::function<void(std::map<std::string, std::string>&, std::map<std::string, web::http::CookieOptions>&)> web::http::client::ResponseParser::onHeader private
Definition at line 69 of file ResponseParser.h.
Referenced by parseHeader(), and ResponseParser().
onParsed
std::function<void(ResponseParser&)> web::http::client::ResponseParser::onParsed private
Definition at line 71 of file ResponseParser.h.
Referenced by parsingFinished(), and ResponseParser().
onResponse
std::function<void(std::string&, std::string&, std::string&)> web::http::client::ResponseParser::onResponse private
Definition at line 68 of file ResponseParser.h.
Referenced by parseStartLine(), and ResponseParser().
onStart
std::function<void(void)> web::http::client::ResponseParser::onStart private
Definition at line 67 of file ResponseParser.h.
Referenced by begin(), and ResponseParser().
parserState
enum web::http::Parser::ParserState web::http::Parser::parserState = ParserState::BEGIN protected inherited
reason
std::string web::http::client::ResponseParser::reason private
Definition at line 64 of file ResponseParser.h.
Referenced by parseStartLine(), and reset().
socketContext
core::socket::stream::SocketContext* web::http::Parser::socketContext = nullptr private inherited
Definition at line 91 of file Parser.h.
Referenced by web::http::Parser::Parser(), web::http::Parser::readContent(), web::http::Parser::readHeaderLine(), and web::http::Parser::readStartLine().
statusCode
std::string web::http::client::ResponseParser::statusCode private
Definition at line 63 of file ResponseParser.h.
Referenced by parseStartLine(), and reset().
The documentation for this class was generated from the following files:
web/http/client/ResponseParser.h
web/http/client/ResponseParser.cpp