SNode.C: net::rc::SocketAddress Class Reference
net::rc::SocketAddress Class Reference final
#include <SocketAddress.h>
Public Types
using SockAddr = sockaddr_rc
using SockLen = socklen_t
Public Member Functions
SocketAddress ()
SocketAddress (const std::string &btAddress)
SocketAddress (uint8_t channel)
SocketAddress (const std::string &btAddress, uint8_t channel)
SocketAddress (const SockAddr &sockAddr, SockLen sockAddrLen)
SocketAddress & init ()
SocketAddress & setBtAddress (const std::string &btAddress)
std::string getBtAddress () const
SocketAddress & setChannel (uint8_t channel)
uint8_t getChannel () const
std::string toString (bool expanded=true) const override
const sockaddr & getSockAddr ()
const SockLen & getSockAddrLen () const
sa_family_t getAddressFamily () const
virtual bool useNext ()
Protected Attributes
SockAddr sockAddr
SockLen sockAddrLen
Private Types
using Super = net::SocketAddress< sockaddr_rc >
Private Attributes
std::string btAddress
uint8_t channel = 0
Detailed Description
Definition at line 38 of file SocketAddress.h.
Member Typedef Documentation
SockAddr
using net::SocketAddress< sockaddr_rc >::SockAddr = sockaddr_rc inherited
Definition at line 37 of file SocketAddress.h.
SockLen
using net::SocketAddress< sockaddr_rc >::SockLen = socklen_t inherited
Definition at line 38 of file SocketAddress.h.
Super
using net::rc::SocketAddress::Super = net::SocketAddress<sockaddr_rc> private
Definition at line 40 of file SocketAddress.h.
Constructor & Destructor Documentation
SocketAddress() [1/5]
net::rc::SocketAddress::SocketAddress ()
Definition at line 30 of file SocketAddress.cpp.
        : Super(AF_BLUETOOTH) {
    }
References net::SocketAddress< SockAddrT >::SocketAddress().
Referenced by SocketAddress(), SocketAddress(), and SocketAddress().
SocketAddress() [2/5]
net::rc::SocketAddress::SocketAddress (const std::string & btAddress) explicit
Definition at line 34 of file SocketAddress.cpp.
        : SocketAddress() {
        setBtAddress(btAddress);
    }
References setBtAddress(), and SocketAddress().
SocketAddress() [3/5]
net::rc::SocketAddress::SocketAddress (uint8_t channel) explicit
Definition at line 39 of file SocketAddress.cpp.
        : SocketAddress() {
        setChannel(channel);
    }
References setChannel(), and SocketAddress().
SocketAddress() [4/5]
net::rc::SocketAddress::SocketAddress (const std::string & btAddress, uint8_t channel)
Definition at line 44 of file SocketAddress.cpp.
        : SocketAddress() {
        setBtAddress(btAddress);
        setChannel(channel);
    }
References setBtAddress(), setChannel(), and SocketAddress().
Referenced by net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT, Args >::connect(), and net::rc::config::ConfigAddress< ConfigAddressTypeT >::init().
SocketAddress() [5/5]
net::rc::SocketAddress::SocketAddress (const SockAddr & sockAddr, SockLen sockAddrLen)
Definition at line 50 of file SocketAddress.cpp.
        : net::SocketAddress<SockAddr>(sockAddr, sockAddrLen) {
        channel = sockAddr.rc_channel;
        char btAddressC[15];
        ba2str(&sockAddr.rc_bdaddr, btAddressC);
        btAddress = btAddressC;
    }
References btAddress, channel, and net::SocketAddress< SockAddrT >::SocketAddress().
Member Function Documentation
getAddressFamily()
sa_family_t net::SocketAddress< SockAddr >::getAddressFamily () const inherited
Definition at line 51 of file SocketAddress.hpp.
{
        return reinterpret_cast<const sockaddr*>(&sockAddr)->sa_family;
    }
getBtAddress()
std::string net::rc::SocketAddress::getBtAddress () const
Definition at line 72 of file SocketAddress.cpp.
{
        return btAddress;
    }
References btAddress.
Referenced by net::rc::config::ConfigAddress< ConfigAddressTypeT >::setSocketAddress().
getChannel()
uint8_t net::rc::SocketAddress::getChannel () const
Definition at line 82 of file SocketAddress.cpp.
{
        return channel;
    }
References channel.
Referenced by net::rc::config::ConfigAddress< ConfigAddressTypeT >::setSocketAddress().
getSockAddr()
const sockaddr & net::SocketAddress< SockAddr >::getSockAddr () inherited
Definition at line 48 of file SocketAddress.hpp.
{
        return reinterpret_cast<const sockaddr&>(sockAddr);
    }
getSockAddrLen()
const SocketAddress< SockAddr >::SockLen & net::SocketAddress< SockAddr >::getSockAddrLen () const inherited
Definition at line 49 of file SocketAddress.hpp.
{
        return sockAddrLen;
    }
init()
SocketAddress & net::rc::SocketAddress::init ()
Definition at line 59 of file SocketAddress.cpp.
{
        sockAddr.rc_channel = channel;
        str2ba(btAddress.c_str(), &sockAddr.rc_bdaddr);
        return *this;
    }
References btAddress, and channel.
Referenced by net::rc::config::ConfigAddress< ConfigAddressTypeT >::init().
setBtAddress()
SocketAddress & net::rc::SocketAddress::setBtAddress (const std::string & btAddress)
Definition at line 66 of file SocketAddress.cpp.
{
        this->btAddress = btAddress;
        return *this;
    }
References btAddress.
Referenced by SocketAddress(), and SocketAddress().
setChannel()
SocketAddress & net::rc::SocketAddress::setChannel (uint8_t channel)
Definition at line 76 of file SocketAddress.cpp.
{
        this->channel = channel;
        return *this;
    }
References channel.
Referenced by SocketAddress(), and SocketAddress().
toString()
std::string net::rc::SocketAddress::toString (bool expanded = true) const override virtual
Implements core::socket::SocketAddress.
Definition at line 86 of file SocketAddress.cpp.
{
        return std::string(btAddress).append(":").append(std::to_string(channel));
    }
References btAddress, and channel.
useNext()
virtual bool core::socket::SocketAddress::useNext () inline virtual inherited
Reimplemented in net::in::SocketAddress, and net::in6::SocketAddress.
Definition at line 53 of file SocketAddress.h.
{
            return false;
        }
Member Data Documentation
btAddress
std::string net::rc::SocketAddress::btAddress private
Definition at line 60 of file SocketAddress.h.
Referenced by getBtAddress(), init(), setBtAddress(), SocketAddress(), and toString().
channel
uint8_t net::rc::SocketAddress::channel = 0 private
Definition at line 61 of file SocketAddress.h.
Referenced by getChannel(), init(), setChannel(), SocketAddress(), and toString().
sockAddr
SockAddr net::SocketAddress< sockaddr_rc >::sockAddr protected inherited
Definition at line 54 of file SocketAddress.h.
{};
sockAddrLen
SockLen net::SocketAddress< sockaddr_rc >::sockAddrLen protected inherited
Definition at line 55 of file SocketAddress.h.
The documentation for this class was generated from the following files:
net/rc/SocketAddress.h
net/rc/SocketAddress.cpp