SNode.C: core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT > Class Template Reference
core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT > Class Template Reference
#include <SocketAcceptor.h>
Public Types
using SocketAddress = typename Super::SocketAddress
using Config = typename Super::Config
using SocketConnection = typename Super::SocketConnection
Public Member Functions
SocketAcceptor (const std::shared_ptr< core::socket::stream::SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus, const std::shared_ptr< Config > &config)
~SocketAcceptor () override
Private Types
using Super = core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >
using PhysicalServerSocket = PhysicalSocketServerT
using SocketConnectionFactory = core::socket::stream::SocketConnectionFactory< PhysicalServerSocket, Config, SocketConnection >
Private Member Functions
void initAcceptEvent () final
SSL_CTX * getMasterSniCtx (const std::string &serverNameIndication)
SSL_CTX * getPoolSniCtx (const std::string &serverNameIndication)
SSL_CTX * getSniCtx (const std::string &serverNameIndication)
void acceptEvent () override
void destruct () final
void unobservedEvent () final
void onEvent (const utils::Timeval &currentTime) override
void span ()
void span ()
void relax ()
void relax ()
const std::string & getName () const
const std::string & getName () const
virtual void acceptTimeout ()
void dispatchEvent () final
void timeoutEvent () final
int getRegisteredFd ()
void enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
virtual void terminate ()
virtual void onExit (int sig)
void triggered (const utils::Timeval &currentTime)
void setEnabled (const utils::Timeval &currentTime)
void setDisabled ()
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
Static Private Member Functions
static int clientHelloCallback (SSL *ssl, int *al, void *arg)
Private Attributes
SSL_CTX * masterSslCtx = nullptr
std::set< std::string > masterSslCtxSans
std::map< std::string, SSL_CTX * > sniSslCtxs
bool forceSni = false
PhysicalServerSocket * physicalServerSocket
SocketAddress localAddress
std::shared_ptr< core::socket::stream::SocketContextFactory > socketContextFactory
std::function< void(SocketConnection *)> onConnect
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
std::function< void(const SocketAddress &, core::socket::State)> onStatus
std::shared_ptr< Config > config
Event event
DescriptorEventPublisher & descriptorEventPublisher
int observedFd = -1
bool enabled = false
bool suspended = false
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
int observationCounter = 0
Detailed Description
template<typename PhysicalSocketServerT, typename ConfigT>
class core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >
Definition at line 43 of file SocketAcceptor.h.
Member Typedef Documentation
Config
template<typename PhysicalSocketServerT , typename ConfigT > using core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::Config = typename Super::Config
Definition at line 50 of file SocketAcceptor.h.
PhysicalServerSocket
using core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >::PhysicalServerSocket = PhysicalSocketServerT private inherited
Definition at line 40 of file SocketAcceptor.h.
SocketAddress
template<typename PhysicalSocketServerT , typename ConfigT > using core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::SocketAddress = typename Super::SocketAddress
Definition at line 49 of file SocketAcceptor.h.
SocketConnection
template<typename PhysicalSocketServerT , typename ConfigT > using core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::SocketConnection = typename Super::SocketConnection
Definition at line 51 of file SocketAcceptor.h.
SocketConnectionFactory
using core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >::SocketConnectionFactory = core::socket::stream::SocketConnectionFactory<PhysicalServerSocket, Config, SocketConnection> private inherited
Definition at line 48 of file SocketAcceptor.h.
Super
template<typename PhysicalSocketServerT , typename ConfigT > using core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::Super = core::socket::stream::SocketAcceptor<PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection> private
Definition at line 46 of file SocketAcceptor.h.
Constructor & Destructor Documentation
SocketAcceptor()
template<typename PhysicalServerSocket , typename Config > core::socket::stream::tls::SocketAcceptor< PhysicalServerSocket, Config >::SocketAcceptor (const std::shared_ptr< core::socket::stream::SocketContextFactory > & socketContextFactory, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::function< void(const SocketAddress &, core::socket::State)> & onStatus, const std::shared_ptr< Config > & config)
Definition at line 36 of file SocketAcceptor.hpp.
        : Super(
              socketContextFactory,
              [onConnect, this](SocketConnection* socketConnection) -> void { // onConnect
                  socketConnection->startSSL(this->masterSslCtx, Super::config->getInitTimeout(), Super::config->getShutdownTimeout());
                  onConnect(socketConnection);
              },
              [socketContextFactory, onConnected, this](SocketConnection* socketConnection) -> void { // on Connected
                  SSL* ssl = socketConnection->getSSL();
                  if (ssl != nullptr) {
                      SSL_set_accept_state(ssl);
                      socketConnection->doSSLHandshake(
                          [socketContextFactory, onConnected, socketConnection, instanceName = this->config->getInstanceName()]()
                              -> void { // onSuccess
                              LOG(TRACE) << instanceName << ": SSL/TLS initial handshake success";
                              onConnected(socketConnection);
                              socketConnection->connected(socketContextFactory);
                          },
                          [socketConnection, instanceName = this->config->getInstanceName()]() -> void { // onTimeout
                              LOG(TRACE) << instanceName << ": SSL/TLS initial handshake timed out";
                              socketConnection->close();
                          },
                          [socketConnection, instanceName = this->config->getInstanceName()](int sslErr) -> void { // onStatus
                              ssl_log(instanceName + ": SSL/TLS initial handshake failed", sslErr);
                              socketConnection->close();
                          });
                  } else {
                      ssl_log_error(this->config->getInstanceName() + ": SSL/TLS initialization failed");
                      socketConnection->close();
                  }
              },
              [onDisconnect, instanceName = config->getInstanceName()](SocketConnection* socketConnection) -> void { // onDisconnect
                  LOG(TRACE) << instanceName << ": SSL/TLS connection destroyed";
                  socketConnection->stopSSL();
                  onDisconnect(socketConnection);
              },
              onStatus,
              config) {
    }
~SocketAcceptor()
template<typename PhysicalSocketServer , typename Config > core::socket::stream::tls::SocketAcceptor< PhysicalSocketServer, Config >::~SocketAcceptor () override
Definition at line 91 of file SocketAcceptor.hpp.
{
        if (masterSslCtx != nullptr) {
            ssl_ctx_free(masterSslCtx);
        }
        for (const auto& [domain, ctx] : sniSslCtxs) {
            if (ctx != nullptr) {
                ssl_ctx_free(ctx);
                std::for_each(sniSslCtxs.begin(), sniSslCtxs.end(), [sslCtx = ctx](auto& sniSslCtxsItem) -> void {
                    if (sniSslCtxsItem.second == sslCtx) {
                        sniSslCtxsItem.second = nullptr;
                    }
                });
            }
        }
    }
References core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::masterSslCtx, core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::sniSslCtxs, and core::socket::stream::tls::ssl_ctx_free().
Member Function Documentation
acceptEvent()
void core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::acceptEvent () override private virtual inherited
Implements core::eventreceiver::AcceptEventReceiver.
Definition at line 72 of file SocketAcceptor.hpp.
{
        int acceptsPerTick = config->getAcceptsPerTick();
        do {
            PhysicalServerSocket physicalClientSocket(physicalServerSocket->accept4(PhysicalServerSocket::Flags::NONBLOCK));
            if (physicalClientSocket.isValid()) {
                LOG(TRACE) << config->getInstanceName() << ": accept success '" << localAddress.toString() << "'";
                SocketConnectionFactory(onConnect, onConnected, onDisconnect).create(physicalClientSocket, config);
            } else if (errno != EINTR && errno != EAGAIN && errno != EWOULDBLOCK) {
                PLOG(TRACE) << config->getInstanceName() << ": accept failed '" << localAddress.toString() << "'";
            }
        } while (--acceptsPerTick > 0);
    }
acceptTimeout()
void core::eventreceiver::AcceptEventReceiver::acceptTimeout () private virtual inherited
Definition at line 37 of file AcceptEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
Referenced by core::eventreceiver::AcceptEventReceiver::timeoutEvent().
checkTimeout()
void core::DescriptorEventReceiver::checkTimeout (const utils::Timeval & currentTime) inherited
Definition at line 159 of file DescriptorEventReceiver.cpp.
{
        if (maxInactivity > 0 && currentTime - lastTriggered >= maxInactivity) {
            timeoutEvent();
        }
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), utils::Timeval::operator>(), utils::Timeval::operator>=(), and core::DescriptorEventReceiver::timeoutEvent().
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents().
clientHelloCallback()
template<typename PhysicalSocketServer , typename Config > int core::socket::stream::tls::SocketAcceptor< PhysicalSocketServer, Config >::clientHelloCallback (SSL * ssl, int * al, void * arg) static private
Definition at line 222 of file SocketAcceptor.hpp.
{
        int ret = SSL_CLIENT_HELLO_SUCCESS;
        SocketAcceptor* socketAcceptor = static_cast<SocketAcceptor*>(arg);
        std::string serverNameIndication = ssl_get_servername_from_client_hello(ssl);
        if (!serverNameIndication.empty()) {
            SSL_CTX* sniSslCtx = socketAcceptor->getSniCtx(serverNameIndication);
            if (sniSslCtx != nullptr) {
                LOG(TRACE) << socketAcceptor->config->getInstanceName() << ": Setting sni certificate for '" << serverNameIndication << "'";
                ssl_set_ssl_ctx(ssl, sniSslCtx);
            } else if (socketAcceptor->forceSni) {
                LOG(TRACE) << socketAcceptor->config->getInstanceName() << ": No sni certificate found for '" << serverNameIndication
                           << "' but forceSni set - terminating";
                ret = SSL_CLIENT_HELLO_ERROR;
                *al = SSL_AD_UNRECOGNIZED_NAME;
            } else {
                LOG(TRACE) << socketAcceptor->config->getInstanceName() << ": No sni certificate found for '" << serverNameIndication
                           << "' still using master certificate";
            }
        } else {
            LOG(TRACE) << socketAcceptor->config->getInstanceName() << ": No sni certificate set - the client did not request one";
        }
        return ret;
    }
References core::socket::stream::tls::ssl_get_servername_from_client_hello(), and core::socket::stream::tls::ssl_set_ssl_ctx().
Referenced by core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::initAcceptEvent().
destruct()
void core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::destruct () final protected virtual inherited
Reimplemented from core::EventReceiver.
Definition at line 75 of file SocketAcceptor.hpp.
{
        delete this;
    }
disable()
void core::DescriptorEventReceiver::disable () inherited
Definition at line 67 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!isSuspended()) {
                suspend();
            }
            enabled = false;
            descriptorEventPublisher.disable(this);
        } else {
            LOG(TRACE) << "Double disable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::disable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::observedFd, and core::DescriptorEventReceiver::suspend().
Referenced by core::eventreceiver::AcceptEventReceiver::acceptTimeout(), database::mariadb::MariaDBConnection::commandContinue(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectEvent(), core::eventreceiver::ConnectEventReceiver::connectTimeout(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectTimeout(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::pipe::PipeSource::eof(), core::eventreceiver::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSink::readEvent(), core::eventreceiver::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::DescriptorEventReceiver::terminate(), core::socket::stream::SocketWriter< PhysicalSocketT >::terminate(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), core::pipe::PipeSource::writeEvent(), core::eventreceiver::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
dispatchEvent()
void core::eventreceiver::AcceptEventReceiver::dispatchEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 41 of file AcceptEventReceiver.cpp.
{
        acceptEvent();
    }
References core::eventreceiver::AcceptEventReceiver::acceptEvent().
enable()
void core::DescriptorEventReceiver::enable (int fd) inherited
Definition at line 50 of file DescriptorEventReceiver.cpp.
{
        if (!enabled) {
            observedFd = fd;
            enabled = true;
            descriptorEventPublisher.enable(this);
        } else {
            LOG(TRACE) << "Double enable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::enable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), and core::DescriptorEventReceiver::observedFd.
Referenced by core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >::connectTimeout(), core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
getMasterSniCtx()
template<typename PhysicalSocketServer , typename Config > SSL_CTX * core::socket::stream::tls::SocketAcceptor< PhysicalSocketServer, Config >::getMasterSniCtx (const std::string & serverNameIndication) private
Definition at line 164 of file SocketAcceptor.hpp.
{
        SSL_CTX* sniSslCtx = nullptr;
        LOG(TRACE) << config->getInstanceName() << ": Search for sni='" << serverNameIndication << "' in master certificate";
        std::set<std::string>::iterator masterSniIt =
            std::find_if(masterSslCtxSans.begin(),
                         masterSslCtxSans.end(),
                         [&serverNameIndication, config = this->config](const std::string& sni) -> bool {
                             LOG(TRACE) << config->getInstanceName() << ":  .. " << sni.c_str();
                             return match(sni.c_str(), serverNameIndication.c_str());
                         });
        if (masterSniIt != masterSslCtxSans.end()) {
            LOG(TRACE) << config->getInstanceName() << ": found '" << *masterSniIt << "'";
            sniSslCtx = masterSslCtx;
        } else {
            LOG(TRACE) << config->getInstanceName() << ": not found";
        }
        return sniSslCtx;
    }
References core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::masterSslCtx, core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::masterSslCtxSans, and core::socket::stream::tls::match().
Referenced by core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::getSniCtx().
getName() [1/2]
const std::string & core::EventReceiver::getName () const inherited
Definition at line 43 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
getName() [2/2]
const std::string & core::EventReceiver::getName () const inherited
Definition at line 43 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
getObservationCounter()
int core::Observer::getObservationCounter () inline inherited
Definition at line 55 of file DescriptorEventReceiver.h.
{
            return observationCounter;
        }
References core::Observer::observationCounter.
getPoolSniCtx()
template<typename PhysicalSocketServer , typename Config > SSL_CTX * core::socket::stream::tls::SocketAcceptor< PhysicalSocketServer, Config >::getPoolSniCtx (const std::string & serverNameIndication) private
Definition at line 187 of file SocketAcceptor.hpp.
{
        SSL_CTX* sniCtx = nullptr;
        LOG(TRACE) << config->getInstanceName() << ": Search for sni='" << serverNameIndication << "' in sni certificates";
        std::map<std::string, SSL_CTX*>::iterator sniPairIt =
            std::find_if(sniSslCtxs.begin(),
                         sniSslCtxs.end(),
                         [&serverNameIndication, config = this->config](const std::pair<std::string, SSL_CTX*>& sniPair) -> bool {
                             LOG(TRACE) << config->getInstanceName() << ":  .. " << sniPair.first.c_str();
                             return match(sniPair.first.c_str(), serverNameIndication.c_str());
                         });
        if (sniPairIt != sniSslCtxs.end()) {
            LOG(TRACE) << config->getInstanceName() << ": found '" << sniPairIt->first << "'";
            sniCtx = sniPairIt->second;
        } else {
            LOG(TRACE) << config->getInstanceName() << ": not found";
        }
        return sniCtx;
    }
References core::socket::stream::tls::match(), and core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::sniSslCtxs.
Referenced by core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::getSniCtx().
getRegisteredFd()
int core::DescriptorEventReceiver::getRegisteredFd () inherited
Definition at line 46 of file DescriptorEventReceiver.cpp.
{
        return observedFd;
    }
References core::DescriptorEventReceiver::observedFd.
Referenced by core::DescriptorEventPublisher::enable(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::select::DescriptorEventPublisher::muxAdd(), core::poll::PollFdsManager::muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOff(), core::select::DescriptorEventPublisher::muxOff(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOn(), core::select::DescriptorEventPublisher::muxOn(), core::poll::PollFdsManager::muxOn(), core::pipe::PipeSink::readEvent(), core::pipe::PipeSource::writeEvent(), core::pipe::PipeSink::~PipeSink(), and core::pipe::PipeSource::~PipeSource().
getSniCtx()
template<typename PhysicalSocketServer , typename Config > SSL_CTX * core::socket::stream::tls::SocketAcceptor< PhysicalSocketServer, Config >::getSniCtx (const std::string & serverNameIndication) private
Definition at line 211 of file SocketAcceptor.hpp.
{
        SSL_CTX* sniSslCtx = getMasterSniCtx(serverNameIndication);
        if (sniSslCtx == nullptr) {
            sniSslCtx = getPoolSniCtx(serverNameIndication);
        }
        return sniSslCtx;
    }
References core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::getMasterSniCtx(), and core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::getPoolSniCtx().
getTimeout()
utils::Timeval core::DescriptorEventReceiver::getTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 141 of file DescriptorEventReceiver.cpp.
{
        return maxInactivity > 0 ? currentTime > lastTriggered ? maxInactivity - (currentTime - lastTriggered) : 0 : TIMEOUT::MAX;
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::DescriptorEventPublisher::getNextTimeout().
initAcceptEvent()
template<typename PhysicalSocketServer , typename Config > void core::socket::stream::tls::SocketAcceptor< PhysicalSocketServer, Config >::initAcceptEvent () final private virtual
Implements core::eventreceiver::InitAcceptEventReceiver.
Definition at line 110 of file SocketAcceptor.hpp.
{
        if (!config->getDisabled()) {
            masterSslCtx = ssl_ctx_new(config);
            if (masterSslCtx != nullptr) {
                masterSslCtxSans = ssl_get_sans(masterSslCtx);
                for (const std::string& san : masterSslCtxSans) {
                    LOG(TRACE) << config->getInstanceName() << ": SSL_CTX (M) for (san)'" << san << "' as master installed";
                }
                for (const auto& [domain, sniCertConf] : config->getSniCerts()) {
                    if (!sniCertConf.empty()) {
                        SSL_CTX* sniSslCtx = ssl_ctx_new(sniCertConf);
                        if (sniSslCtx != nullptr) {
                            if (!domain.empty()) {
                                if (sniSslCtxs.contains(domain)) {
                                    ssl_ctx_free(sniSslCtxs[domain]);
                                }
                                sniSslCtxs.insert_or_assign(domain, sniSslCtx);
                                LOG(TRACE) << config->getInstanceName() << ": SSL_CTX (E) sni for (dom)'" << domain
                                           << "' as server name indication (sni) installed";
                            }
                            for (const std::string& san : ssl_get_sans(sniSslCtx)) {
                                sniSslCtxs.insert({san, sniSslCtx});
                                LOG(TRACE) << config->getInstanceName() << ": SSL_CTX (S) sni for (san)'" << san
                                           << "' as server name indication (sni) installed";
                            }
                        } else {
                            LOG(TRACE) << config->getInstanceName() << ": Can not create SNI_SSL_CTX for domain '" << domain << "'";
                        }
                    }
                }
                forceSni = config->getForceSni();
                SSL_CTX_set_client_hello_cb(masterSslCtx, clientHelloCallback, this);
                Super::initAcceptEvent();
            } else {
                LOG(TRACE) << config->getInstanceName() << ": Master SSL/TLS certificate activation failed";
                Super::onStatus(Super::config->Local::getSocketAddress(), core::socket::STATE_ERROR);
                Super::destruct();
            }
        } else {
            Super::initAcceptEvent();
        }
    }
References core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::clientHelloCallback(), core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::forceSni, core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::masterSslCtx, core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::masterSslCtxSans, core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::sniSslCtxs, and core::socket::stream::tls::ssl_get_sans().
isEnabled()
bool core::DescriptorEventReceiver::isEnabled () const inherited
Definition at line 84 of file DescriptorEventReceiver.cpp.
{
        return enabled;
    }
References core::DescriptorEventReceiver::enabled.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >::connectTimeout(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), and core::DescriptorEventReceiver::terminate().
isObserved()
bool core::Observer::isObserved () inline inherited
Definition at line 43 of file DescriptorEventReceiver.h.
{
            return observationCounter > 0;
        }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
isSuspended()
bool core::DescriptorEventReceiver::isSuspended () const inherited
Definition at line 121 of file DescriptorEventReceiver.cpp.
{
        return suspended;
    }
References core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::pipe::PipeSource::send().
observed()
void core::Observer::observed () inline inherited
Definition at line 47 of file DescriptorEventReceiver.h.
{
            observationCounter++;
        }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setEnabled().
onEvent()
void core::eventreceiver::InitAcceptEventReceiver::onEvent (const utils::Timeval & currentTime) override private virtual inherited
Implements core::EventReceiver.
Definition at line 53 of file AcceptEventReceiver.cpp.
{
        initAcceptEvent();
    }
References core::eventreceiver::InitAcceptEventReceiver::initAcceptEvent().
onExit()
void core::DescriptorEventReceiver::onExit (int sig) private virtual inherited
Definition at line 152 of file DescriptorEventReceiver.cpp.
{
    }
Referenced by core::DescriptorEventPublisher::sigExit().
relax() [1/2]
void core::EventReceiver::relax () inherited
Definition at line 39 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
relax() [2/2]
void core::EventReceiver::relax () inherited
Definition at line 39 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
resume()
void core::DescriptorEventReceiver::resume () inherited
Definition at line 104 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (suspended) {
                suspended = false;
                lastTriggered = utils::Timeval::currentTime();
                if (isObserved()) {
                    descriptorEventPublisher.resume(this);
                }
            } else {
                LOG(TRACE) << "Double resume: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "Resume while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::Observer::isObserved(), core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::observedFd, utils::Timeval::operator=(), core::DescriptorEventPublisher::resume(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
setDisabled()
void core::DescriptorEventReceiver::setDisabled () private inherited
Definition at line 80 of file DescriptorEventReceiver.cpp.
{
        unObserved();
    }
References core::Observer::unObserved().
setEnabled()
void core::DescriptorEventReceiver::setEnabled (const utils::Timeval & currentTime) private inherited
Definition at line 61 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
        observed();
    }
References core::DescriptorEventReceiver::lastTriggered, core::Observer::observed(), and utils::Timeval::operator=().
Referenced by core::DescriptorEventPublisher::enable().
setTimeout()
void core::DescriptorEventReceiver::setTimeout (const utils::Timeval & timeout) inherited
Definition at line 131 of file DescriptorEventReceiver.cpp.
{
        if (timeout == TIMEOUT::DEFAULT) {
            this->maxInactivity = initialTimeout;
        } else {
            this->maxInactivity = timeout;
        }
        triggered(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::TIMEOUT::DEFAULT, core::DescriptorEventReceiver::initialTimeout, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator=(), utils::Timeval::operator==(), and core::DescriptorEventReceiver::triggered().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::initConnectEvent(), core::socket::stream::SocketReader< PhysicalSocketT >::terminate(), and core::socket::stream::SocketWriter< PhysicalSocketT >::terminate().
span() [1/2]
void core::EventReceiver::span () inherited
Definition at line 35 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::FileReader(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
span() [2/2]
void core::EventReceiver::span () inherited
Definition at line 35 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::FileReader(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
suspend()
void core::DescriptorEventReceiver::suspend () inherited
Definition at line 88 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!suspended) {
                suspended = true;
                if (isObserved()) {
                    descriptorEventPublisher.suspend(this);
                }
            } else {
                LOG(TRACE) << "Double suspend: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "Suspend while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::Observer::isObserved(), core::DescriptorEventReceiver::observedFd, core::DescriptorEventPublisher::suspend(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), and core::pipe::PipeSource::writeEvent().
terminate()
void core::DescriptorEventReceiver::terminate () virtual inherited
Reimplemented in core::socket::stream::SocketReader< PhysicalSocketT >, core::socket::stream::SocketWriter< PhysicalSocketT >, core::pipe::PipeSink, and core::pipe::PipeSource.
Definition at line 125 of file DescriptorEventReceiver.cpp.
{
        if (isEnabled()) {
            disable();
        }
    }
References core::DescriptorEventReceiver::disable(), and core::DescriptorEventReceiver::isEnabled().
Referenced by core::DescriptorEventPublisher::stop(), core::pipe::PipeSink::terminate(), and core::pipe::PipeSource::terminate().
timeoutEvent()
void core::eventreceiver::AcceptEventReceiver::timeoutEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 45 of file AcceptEventReceiver.cpp.
{
        acceptTimeout();
    }
References core::eventreceiver::AcceptEventReceiver::acceptTimeout().
triggered()
void core::DescriptorEventReceiver::triggered (const utils::Timeval & currentTime) private inherited
Definition at line 155 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
    }
References core::DescriptorEventReceiver::lastTriggered, and utils::Timeval::operator=().
Referenced by core::DescriptorEventReceiver::onEvent(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::DescriptorEventReceiver::setTimeout().
unObserved()
void core::Observer::unObserved () inline inherited
Definition at line 51 of file DescriptorEventReceiver.h.
{
            observationCounter--;
        }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setDisabled().
unobservedEvent()
void core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::unobservedEvent () final private virtual inherited
Implements core::Observer.
Definition at line 78 of file SocketAcceptor.hpp.
{
        destruct();
    }
Member Data Documentation
config
std::shared_ptr<Config> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >::config protected inherited
Definition at line 92 of file SocketAcceptor.h.
descriptorEventPublisher
DescriptorEventPublisher& core::DescriptorEventReceiver::descriptorEventPublisher private inherited
Definition at line 112 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
enabled
bool core::DescriptorEventReceiver::enabled = false private inherited
Definition at line 116 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
event
Event core::EventReceiver::event private inherited
Definition at line 54 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
eventCounter
int core::DescriptorEventReceiver::eventCounter = 0 private inherited
Definition at line 123 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::onEvent().
forceSni
template<typename PhysicalSocketServerT , typename ConfigT > bool core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::forceSni = false private
Definition at line 77 of file SocketAcceptor.h.
Referenced by core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::initAcceptEvent().
initialTimeout
const utils::Timeval core::DescriptorEventReceiver::initialTimeout private inherited
Definition at line 121 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), and core::DescriptorEventReceiver::setTimeout().
lastTriggered
utils::Timeval core::DescriptorEventReceiver::lastTriggered private inherited
Definition at line 119 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setEnabled(), and core::DescriptorEventReceiver::triggered().
localAddress
SocketAddress core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >::localAddress private inherited
Definition at line 81 of file SocketAcceptor.h.
masterSslCtx
template<typename PhysicalSocketServerT , typename ConfigT > SSL_CTX* core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::masterSslCtx = nullptr private
Definition at line 73 of file SocketAcceptor.h.
Referenced by core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::getMasterSniCtx(), core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::initAcceptEvent(), and core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::~SocketAcceptor().
masterSslCtxSans
template<typename PhysicalSocketServerT , typename ConfigT > std::set<std::string> core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::masterSslCtxSans private
Definition at line 74 of file SocketAcceptor.h.
Referenced by core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::getMasterSniCtx(), and core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::initAcceptEvent().
maxInactivity
utils::Timeval core::DescriptorEventReceiver::maxInactivity private inherited
Definition at line 120 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::getTimeout(), and core::DescriptorEventReceiver::setTimeout().
observationCounter
int core::Observer::observationCounter = 0 private inherited
Definition at line 62 of file DescriptorEventReceiver.h.
Referenced by core::Observer::getObservationCounter(), core::Observer::isObserved(), core::Observer::observed(), and core::Observer::unObserved().
observedFd
int core::DescriptorEventReceiver::observedFd = -1 private inherited
Definition at line 114 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
onConnect
std::function<void(SocketConnection*)> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >::onConnect protected inherited
Definition at line 86 of file SocketAcceptor.h.
onConnected
std::function<void(SocketConnection*)> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >::onConnected protected inherited
Definition at line 87 of file SocketAcceptor.h.
onDisconnect
std::function<void(SocketConnection*)> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >::onDisconnect protected inherited
Definition at line 88 of file SocketAcceptor.h.
onStatus
std::function<void(const SocketAddress&, core::socket::State)> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >::onStatus protected inherited
Definition at line 90 of file SocketAcceptor.h.
physicalServerSocket
PhysicalServerSocket* core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >::physicalServerSocket private inherited
Definition at line 80 of file SocketAcceptor.h.
sniSslCtxs
template<typename PhysicalSocketServerT , typename ConfigT > std::map<std::string, SSL_CTX*> core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::sniSslCtxs private
Definition at line 76 of file SocketAcceptor.h.
Referenced by core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::getPoolSniCtx(), core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::initAcceptEvent(), and core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::~SocketAcceptor().
socketContextFactory
std::shared_ptr<core::socket::stream::SocketContextFactory> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >::socketContextFactory protected inherited
Definition at line 84 of file SocketAcceptor.h.
suspended
bool core::DescriptorEventReceiver::suspended = false private inherited
Definition at line 117 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
The documentation for this class was generated from the following files:
core/socket/stream/tls/SocketAcceptor.h
core/socket/stream/tls/SocketAcceptor.hpp