SNode.C: express::middleware::BasicAuthentication Class Reference
express::middleware::BasicAuthentication Class Reference
#include <BasicAuthentication.h>
Public Member Functions
void laxRouting (bool strict=false)
Route & use (const Router &router) const
Route & use (const std::string &relativeMountPath, const Router &router) const
Route & use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & use (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & use (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & all (const Router &router) const
Route & all (const std::string &relativeMountPath, const Router &router) const
Route & all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & all (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & all (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & get (const Router &router) const
Route & get (const std::string &relativeMountPath, const Router &router) const
Route & get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & get (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & get (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & put (const Router &router) const
Route & put (const std::string &relativeMountPath, const Router &router) const
Route & put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & put (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & put (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & post (const Router &router) const
Route & post (const std::string &relativeMountPath, const Router &router) const
Route & post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & post (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & post (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & del (const Router &router) const
Route & del (const std::string &relativeMountPath, const Router &router) const
Route & del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & del (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & del (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & connect (const Router &router) const
Route & connect (const std::string &relativeMountPath, const Router &router) const
Route & connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & connect (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & connect (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & options (const Router &router) const
Route & options (const std::string &relativeMountPath, const Router &router) const
Route & options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & options (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & options (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & trace (const Router &router) const
Route & trace (const std::string &relativeMountPath, const Router &router) const
Route & trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & trace (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & trace (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & patch (const Router &router) const
Route & patch (const std::string &relativeMountPath, const Router &router) const
Route & patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & patch (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & patch (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & head (const Router &router) const
Route & head (const std::string &relativeMountPath, const Router &router) const
Route & head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & head (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
Route & head (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Protected Member Functions
BasicAuthentication (const std::string &userName, const std::string &password, const std::string &realm)
Static Protected Member Functions
static class BasicAuthentication & instance (const std::string &userName, const std::string &password, const std::string &realm)
Protected Attributes
std::shared_ptr< RootRoute > rootRoute = nullptr
Friends
class BasicAuthentication & BasicAuthentication (const std::string &userName, const std::string &password, const std::string &realm)
Detailed Description
Definition at line 35 of file BasicAuthentication.h.
Constructor & Destructor Documentation
BasicAuthentication()
express::middleware::BasicAuthentication::BasicAuthentication (const std::string & userName, const std::string & password, const std::string & realm) protected
Definition at line 36 of file BasicAuthentication.cpp.
{
        std::string userNamePassword = userName + ":" + password;
        const std::string credentials =
            base64::base64_encode(reinterpret_cast<unsigned char*>(userNamePassword.data()), userNamePassword.length());
        use([realm, credentials] MIDDLEWARE(req, res, next) {
            const std::string authCredentials = httputils::str_split(req->get("Authorization"), ' ').second;
            if (authCredentials == credentials) {
                next();
            } else {
                if (authCredentials.empty()) {
                    res->set("WWW-Authenticate", "Basic realm=\"" + realm + "\"");
                }
                res->sendStatus(401);
            }
        });
    }
References base64::base64_encode(), express::Request::get(), express::Next::operator()(), express::Response::sendStatus(), express::Response::set(), and httputils::str_split().
Referenced by instance().
Member Function Documentation
all() [1/10]
Route & express::Router::all (const Router & router) const inherited
Definition at line 63 of file Router.cpp.
all() [2/10]
Route & express::Router::all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 63 of file Router.cpp.
all() [3/10]
template<typename... Lambdas> Route & express::Router::all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 60 of file Router.hpp.
all() [4/10]
Route & express::Router::all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 63 of file Router.cpp.
all() [5/10]
template<typename... Lambdas> Route & express::Router::all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 60 of file Router.hpp.
all() [6/10]
Route & express::Router::all (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 63 of file Router.cpp.
all() [7/10]
Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 63 of file Router.cpp.
all() [8/10]
template<typename... Lambdas> Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 60 of file Router.hpp.
all() [9/10]
Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 63 of file Router.cpp.
all() [10/10]
template<typename... Lambdas> Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 60 of file Router.hpp.
connect() [1/10]
Route & express::Router::connect (const Router & router) const inherited
Definition at line 68 of file Router.cpp.
connect() [2/10]
Route & express::Router::connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 68 of file Router.cpp.
connect() [3/10]
template<typename... Lambdas> Route & express::Router::connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 65 of file Router.hpp.
connect() [4/10]
Route & express::Router::connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 68 of file Router.cpp.
connect() [5/10]
template<typename... Lambdas> Route & express::Router::connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 65 of file Router.hpp.
connect() [6/10]
Route & express::Router::connect (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 68 of file Router.cpp.
connect() [7/10]
Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 68 of file Router.cpp.
connect() [8/10]
template<typename... Lambdas> Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 65 of file Router.hpp.
connect() [9/10]
Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 68 of file Router.cpp.
connect() [10/10]
template<typename... Lambdas> Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 65 of file Router.hpp.
del() [1/10]
Route & express::Router::del (const Router & router) const inherited
Definition at line 67 of file Router.cpp.
del() [2/10]
Route & express::Router::del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 67 of file Router.cpp.
del() [3/10]
template<typename... Lambdas> Route & express::Router::del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 64 of file Router.hpp.
del() [4/10]
Route & express::Router::del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 67 of file Router.cpp.
del() [5/10]
template<typename... Lambdas> Route & express::Router::del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 64 of file Router.hpp.
del() [6/10]
Route & express::Router::del (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 67 of file Router.cpp.
del() [7/10]
Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 67 of file Router.cpp.
del() [8/10]
template<typename... Lambdas> Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 64 of file Router.hpp.
del() [9/10]
Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 67 of file Router.cpp.
del() [10/10]
template<typename... Lambdas> Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 64 of file Router.hpp.
get() [1/10]
Route & express::Router::get (const Router & router) const inherited
Definition at line 64 of file Router.cpp.
get() [2/10]
Route & express::Router::get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 64 of file Router.cpp.
get() [3/10]
template<typename... Lambdas> Route & express::Router::get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 61 of file Router.hpp.
get() [4/10]
Route & express::Router::get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 64 of file Router.cpp.
get() [5/10]
template<typename... Lambdas> Route & express::Router::get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 61 of file Router.hpp.
get() [6/10]
Route & express::Router::get (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 64 of file Router.cpp.
get() [7/10]
Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 64 of file Router.cpp.
get() [8/10]
template<typename... Lambdas> Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 61 of file Router.hpp.
get() [9/10]
Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 64 of file Router.cpp.
get() [10/10]
template<typename... Lambdas> Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 61 of file Router.hpp.
head() [1/10]
Route & express::Router::head (const Router & router) const inherited
Definition at line 72 of file Router.cpp.
head() [2/10]
Route & express::Router::head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 72 of file Router.cpp.
head() [3/10]
template<typename... Lambdas> Route & express::Router::head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 69 of file Router.hpp.
head() [4/10]
Route & express::Router::head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 72 of file Router.cpp.
head() [5/10]
template<typename... Lambdas> Route & express::Router::head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 69 of file Router.hpp.
head() [6/10]
Route & express::Router::head (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 72 of file Router.cpp.
head() [7/10]
Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 72 of file Router.cpp.
head() [8/10]
template<typename... Lambdas> Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 69 of file Router.hpp.
head() [9/10]
Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 72 of file Router.cpp.
head() [10/10]
template<typename... Lambdas> Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 69 of file Router.hpp.
instance()
class BasicAuthentication & express::middleware::BasicAuthentication::instance (const std::string & userName, const std::string & password, const std::string & realm) static protected
Definition at line 56 of file BasicAuthentication.cpp.
{
        // Keep the created authentication middleware alive
        static std::list<std::shared_ptr<class BasicAuthentication>> basicAuthentications;
        BasicAuthentication* basicAuthentication = new BasicAuthentication(userName, password, realm);
        basicAuthentications.push_back(std::shared_ptr<BasicAuthentication>(basicAuthentication));
        return *basicAuthentication;
    }
References BasicAuthentication().
Referenced by BasicAuthentication.
laxRouting()
void express::Router::laxRouting (bool strict = false) inherited
Definition at line 58 of file Router.cpp.
{
        rootRoute->strict = strict;
    }
References express::Router::rootRoute, and express::RootRoute::strict.
options() [1/10]
Route & express::Router::options (const Router & router) const inherited
Definition at line 69 of file Router.cpp.
options() [2/10]
Route & express::Router::options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 69 of file Router.cpp.
options() [3/10]
template<typename... Lambdas> Route & express::Router::options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 66 of file Router.hpp.
options() [4/10]
Route & express::Router::options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 69 of file Router.cpp.
options() [5/10]
template<typename... Lambdas> Route & express::Router::options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 66 of file Router.hpp.
options() [6/10]
Route & express::Router::options (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 69 of file Router.cpp.
options() [7/10]
Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 69 of file Router.cpp.
options() [8/10]
template<typename... Lambdas> Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 66 of file Router.hpp.
options() [9/10]
Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 69 of file Router.cpp.
options() [10/10]
template<typename... Lambdas> Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 66 of file Router.hpp.
patch() [1/10]
Route & express::Router::patch (const Router & router) const inherited
Definition at line 71 of file Router.cpp.
patch() [2/10]
Route & express::Router::patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 71 of file Router.cpp.
patch() [3/10]
template<typename... Lambdas> Route & express::Router::patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 68 of file Router.hpp.
patch() [4/10]
Route & express::Router::patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 71 of file Router.cpp.
patch() [5/10]
template<typename... Lambdas> Route & express::Router::patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 68 of file Router.hpp.
patch() [6/10]
Route & express::Router::patch (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 71 of file Router.cpp.
patch() [7/10]
Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 71 of file Router.cpp.
patch() [8/10]
template<typename... Lambdas> Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 68 of file Router.hpp.
patch() [9/10]
Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 71 of file Router.cpp.
patch() [10/10]
template<typename... Lambdas> Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 68 of file Router.hpp.
post() [1/10]
Route & express::Router::post (const Router & router) const inherited
Definition at line 66 of file Router.cpp.
post() [2/10]
Route & express::Router::post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 66 of file Router.cpp.
post() [3/10]
template<typename... Lambdas> Route & express::Router::post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 63 of file Router.hpp.
post() [4/10]
Route & express::Router::post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 66 of file Router.cpp.
post() [5/10]
template<typename... Lambdas> Route & express::Router::post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 63 of file Router.hpp.
post() [6/10]
Route & express::Router::post (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 66 of file Router.cpp.
post() [7/10]
Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 66 of file Router.cpp.
post() [8/10]
template<typename... Lambdas> Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 63 of file Router.hpp.
post() [9/10]
Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 66 of file Router.cpp.
post() [10/10]
template<typename... Lambdas> Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 63 of file Router.hpp.
put() [1/10]
Route & express::Router::put (const Router & router) const inherited
Definition at line 65 of file Router.cpp.
put() [2/10]
Route & express::Router::put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 65 of file Router.cpp.
put() [3/10]
template<typename... Lambdas> Route & express::Router::put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 62 of file Router.hpp.
put() [4/10]
Route & express::Router::put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 65 of file Router.cpp.
put() [5/10]
template<typename... Lambdas> Route & express::Router::put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 62 of file Router.hpp.
put() [6/10]
Route & express::Router::put (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 65 of file Router.cpp.
put() [7/10]
Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 65 of file Router.cpp.
put() [8/10]
template<typename... Lambdas> Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 62 of file Router.hpp.
put() [9/10]
Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 65 of file Router.cpp.
put() [10/10]
template<typename... Lambdas> Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 62 of file Router.hpp.
trace() [1/10]
Route & express::Router::trace (const Router & router) const inherited
Definition at line 70 of file Router.cpp.
trace() [2/10]
Route & express::Router::trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 70 of file Router.cpp.
trace() [3/10]
template<typename... Lambdas> Route & express::Router::trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 67 of file Router.hpp.
trace() [4/10]
Route & express::Router::trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 70 of file Router.cpp.
trace() [5/10]
template<typename... Lambdas> Route & express::Router::trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 67 of file Router.hpp.
trace() [6/10]
Route & express::Router::trace (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 70 of file Router.cpp.
trace() [7/10]
Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 70 of file Router.cpp.
trace() [8/10]
template<typename... Lambdas> Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 67 of file Router.hpp.
trace() [9/10]
Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 70 of file Router.cpp.
trace() [10/10]
template<typename... Lambdas> Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 67 of file Router.hpp.
use() [1/10]
Route & express::Router::use (const Router & router) const inherited
Definition at line 62 of file Router.cpp.
use() [2/10]
Route & express::Router::use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 62 of file Router.cpp.
use() [3/10]
template<typename... Lambdas> Route & express::Router::use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 59 of file Router.hpp.
use() [4/10]
Route & express::Router::use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 62 of file Router.cpp.
use() [5/10]
template<typename... Lambdas> Route & express::Router::use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 59 of file Router.hpp.
use() [6/10]
Route & express::Router::use (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 62 of file Router.cpp.
use() [7/10]
Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const inherited
Definition at line 62 of file Router.cpp.
use() [8/10]
template<typename... Lambdas> Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const inherited
Definition at line 59 of file Router.hpp.
use() [9/10]
Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const inherited
Definition at line 62 of file Router.cpp.
use() [10/10]
template<typename... Lambdas> Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const inherited
Definition at line 59 of file Router.hpp.
Friends And Related Symbol Documentation
BasicAuthentication
class BasicAuthentication & BasicAuthentication (const std::string & userName, const std::string & password, const std::string & realm) friend
Definition at line 66 of file BasicAuthentication.cpp.
{
        return BasicAuthentication::instance(userName, password, realm);
    }
References instance().
Member Data Documentation
rootRoute
std::shared_ptr<RootRoute> express::Router::rootRoute = nullptr protected inherited
Definition at line 99 of file Router.h.
Referenced by express::Router::laxRouting(), and express::Router::Router().
The documentation for this class was generated from the following files:
express/middleware/BasicAuthentication.h
express/middleware/BasicAuthentication.cpp