SNode.C: apps::websocket::subprotocol::echo::server::Echo Class Reference
apps::websocket::subprotocol::echo::server::Echo Class Reference
#include <Echo.h>
Public Member Functions
Echo (web::websocket::SubProtocolContext *socketContextUpgradeBase, const std::string &name)
Public Member Functions inherited from web::websocket::server::SubProtocol
~SubProtocol () override
void subscribe (const std::string &group)
void sendBroadcast (const char *message, std::size_t messageLength, bool excludeSelf=false)
void sendBroadcast (const std::string &message, bool excludeSelf=false)
void sendBroadcastStart (const char *message, std::size_t messageLength, bool excludeSelf=false)
void sendBroadcastStart (const std::string &message, bool excludeSelf=false)
void sendBroadcastFrame (const char *message, std::size_t messageLength, bool excludeSelf=false)
void sendBroadcastFrame (const std::string &message, bool excludeSelf=false)
void sendBroadcastEnd (const char *message, std::size_t messageLength, bool excludeSelf=false)
void sendBroadcastEnd (const std::string &message, bool excludeSelf=false)
void forEachClient (const std::function< void(const SubProtocol *)> &sendToClient, bool excludeSelf=false)
void sendMessage (const char *message, std::size_t messageLength) const
void sendMessage (const std::string &message) const
void sendMessageEnd (const char *message, std::size_t messageLength) const
void sendMessageEnd (const std::string &message) const
void sendMessageFrame (const char *message, std::size_t messageLength) const
void sendMessageFrame (const std::string &message) const
void sendMessageStart (const char *message, std::size_t messageLength) const
void sendMessageStart (const std::string &message) const
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
Public Member Functions inherited from web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >
SubProtocol (SubProtocol &)=delete
SubProtocol (SubProtocol &&)=delete
SubProtocol & operator= (SubProtocol &)=delete
SubProtocol & operator= (SubProtocol &&)=delete
void sendMessage (const char *message, std::size_t messageLength) const
void sendMessage (const std::string &message) const
void sendMessageStart (const char *message, std::size_t messageLength) const
void sendMessageStart (const std::string &message) const
void sendMessageFrame (const char *message, std::size_t messageLength) const
void sendMessageFrame (const std::string &message) const
void sendMessageEnd (const char *message, std::size_t messageLength) const
void sendMessageEnd (const std::string &message) const
void sendPing (const char *reason=nullptr, std::size_t reasonLength=0) const
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
const std::string & getName ()
core::socket::stream::SocketConnection * getSocketConnection () const
std::size_t getPayloadTotalSent () const
std::size_t getPayloadTotalRead () const
std::string getOnlineSince () const
std::string getOnlineDuration () const
Private Member Functions
void onConnected () override
void onMessageStart (int opCode) override
void onMessageData (const char *chunk, std::size_t chunkLen) override
void onMessageEnd () override
void onMessageError (uint16_t errnum) override
void onDisconnected () override
bool onSignal (int sig) override
Private Attributes
std::string data
Additional Inherited Members
Protected Member Functions inherited from web::websocket::server::SubProtocol
SubProtocol (SubProtocolContext *subProtocolContext, const std::string &name, int pingInterval=0, int maxFlyingPings=3)
Protected Member Functions inherited from web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >
SubProtocol (SubProtocolContext *subProtocolContext, const std::string &name, int pingInterval=60, int maxFlyingPings=3)
Protected Attributes inherited from web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >
SubProtocolContext * subProtocolContext
Detailed Description
Definition at line 61 of file Echo.h.
Constructor & Destructor Documentation
Echo()
apps::websocket::subprotocol::echo::server::Echo::Echo (web::websocket::SubProtocolContext * socketContextUpgradeBase, const std::string & name)
Definition at line 58 of file Echo.cpp.
        : web::websocket::server::SubProtocol(socketContextUpgradeBase, name, PING_INTERVAL, MAX_FLYING_PINGS) {
    }
References web::websocket::server::SubProtocol::SubProtocol().
Referenced by apps::websocket::subprotocol::echo::server::EchoFactory::create().
Member Function Documentation
onConnected()
void apps::websocket::subprotocol::echo::server::Echo::onConnected () override private virtual
Implements web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >.
Definition at line 62 of file Echo.cpp.
{
        VLOG(1) << "Echo connected";
    }
onDisconnected()
void apps::websocket::subprotocol::echo::server::Echo::onDisconnected () override private virtual
Implements web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >.
Definition at line 93 of file Echo.cpp.
{
        VLOG(1) << "Echo disconnected:";
    }
onMessageData()
void apps::websocket::subprotocol::echo::server::Echo::onMessageData (const char * chunk, std::size_t chunkLen) override private virtual
Implements web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >.
Definition at line 70 of file Echo.cpp.
{
        data += std::string(chunk, chunkLen);
        VLOG(2) << "Message Fragment: " << std::string(chunk, chunkLen);
    }
References data.
onMessageEnd()
void apps::websocket::subprotocol::echo::server::Echo::onMessageEnd () override private virtual
Implements web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >.
Definition at line 76 of file Echo.cpp.
{
        VLOG(1) << "Message Data: " << data;
        // Alternative
        // forEachClient([&data = this->data](SubProtocol* client) {
        //    client->sendMessage(data);
        // });
        sendBroadcast(data);
        data.clear();
    }
References data, and web::websocket::server::SubProtocol::sendBroadcast().
onMessageError()
void apps::websocket::subprotocol::echo::server::Echo::onMessageError (uint16_t errnum) override private virtual
Implements web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >.
Definition at line 89 of file Echo.cpp.
{
        VLOG(1) << "Message error: " << errnum;
    }
onMessageStart()
void apps::websocket::subprotocol::echo::server::Echo::onMessageStart (int opCode) override private virtual
Implements web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >.
Definition at line 66 of file Echo.cpp.
{
        VLOG(2) << "Message Start - OpCode: " << opCode;
    }
onSignal()
bool apps::websocket::subprotocol::echo::server::Echo::onSignal (int sig) override private virtual
Implements web::websocket::SubProtocol< web::websocket::server::SocketContextUpgrade >.
Definition at line 97 of file Echo.cpp.
{
        VLOG(1) << "SubProtocol 'echo' exit due to '" << strsignal(sig) << "' (SIG" << utils::system::sigabbrev_np(sig) << " = " << sig
                << ")";
        sendClose();
        return false;
    }
References web::websocket::SubProtocol< SocketContextUpgradeT >::sendClose(), and utils::system::sigabbrev_np().
Member Data Documentation
data
std::string apps::websocket::subprotocol::echo::server::Echo::data private
Definition at line 74 of file Echo.h.
Referenced by onMessageData(), and onMessageEnd().
The documentation for this class was generated from the following files:
apps/websocket/subprotocol/server/echo/Echo.h
apps/websocket/subprotocol/server/echo/Echo.cpp