SNode.C: SimpleSocketProtocol Class Reference
SimpleSocketProtocol Class Reference
Public Member Functions
SimpleSocketProtocol (core::socket::stream::SocketConnection *socketConnection)
~SimpleSocketProtocol () override
void onConnected () override
void onDisconnected () override
bool onSignal (int signum) override
std::size_t onReceivedFromPeer () override
void onWriteError (int errnum) override
void onReadError (int errnum) override
void sendToPeer (const char *junk, std::size_t junkLen) const final
void sendToPeer (const std::string &data) const
virtual void sendToPeer (const char *junk, std::size_t junkLen) const=0
void streamToPeer (core::pipe::Source *source) const final
std::size_t readFromPeer (char *junk, std::size_t junklen) const final
void setTimeout (const utils::Timeval &timeout) final
void shutdownRead ()
void shutdownWrite (bool forceClose=false)
void close () override
SocketConnection * getSocketConnection () const
virtual void switchSocketContext (SocketContext *newSocketContext)
Private Types
using Super = core::socket::SocketContext
Private Attributes
web::http::client::ResponseParser * responseParser
core::socket::stream::SocketConnection * socketConnection
Detailed Description
Definition at line 88 of file httplowlevelclient.cpp.
Member Typedef Documentation
Super
using core::socket::stream::SocketContext::Super = core::socket::SocketContext private inherited
Definition at line 48 of file SocketContext.h.
Constructor & Destructor Documentation
SimpleSocketProtocol()
SimpleSocketProtocol::SimpleSocketProtocol (core::socket::stream::SocketConnection * socketConnection) inline explicit
Definition at line 90 of file httplowlevelclient.cpp.
        : core::socket::stream::SocketContext(socketConnection) {
        responseParser = getResponseParser(this);
    }
References getResponseParser(), responseParser, and core::socket::stream::SocketContext::SocketContext().
Referenced by SimpleSocketProtocolFactory::create().
~SimpleSocketProtocol()
SimpleSocketProtocol::~SimpleSocketProtocol () override
Definition at line 126 of file httplowlevelclient.cpp.
{
    delete responseParser;
}
References responseParser.
Member Function Documentation
close()
void core::socket::stream::SocketContext::close () override virtual inherited
Implements core::socket::SocketContext.
Reimplemented in iot::mqtt::SocketContext.
Definition at line 58 of file SocketContext.cpp.
{
        socketConnection->close();
    }
References core::socket::stream::SocketConnection::close(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::server::RequestContextBase::close(), iot::mqtt::SocketContext::close(), web::http::client::Request::enqueue(), iot::mqtt_fast::SocketContext::onReceivedFromPeer(), web::http::client::Request::upgrade(), and web::http::client::Response::upgrade().
getSocketConnection()
SocketConnection * core::socket::stream::SocketContext::getSocketConnection () const inherited
Definition at line 38 of file SocketContext.cpp.
{
        return socketConnection;
    }
References core::socket::stream::SocketContext::socketConnection.
Referenced by iot::mqtt::SocketContext::getSocketConnection(), web::http::client::SocketContext< RequestT, ResponseT >::onConnected(), web::http::server::SocketContext< RequestT, ResponseT >::onConnected(), web::http::server::SocketContext< RequestT, ResponseT >::onDisconnected(), web::http::server::SocketContext< RequestT, ResponseT >::onSignal(), web::http::server::RequestContextBase::switchSocketContext(), and web::http::client::Response::upgrade().
onConnected()
void SimpleSocketProtocol::onConnected () inline override virtual
Implements core::socket::stream::SocketContext.
Definition at line 97 of file httplowlevelclient.cpp.
{
        VLOG(0) << "SimpleSocketProtocol connected";
    }
onDisconnected()
void SimpleSocketProtocol::onDisconnected () inline override virtual
Implements core::socket::stream::SocketContext.
Definition at line 100 of file httplowlevelclient.cpp.
{
        VLOG(0) << "SimpleSocketProtocol disconnected";
    }
onReadError()
void SimpleSocketProtocol::onReadError (int errnum) inline override virtual
Implements core::socket::SocketContext.
Definition at line 117 of file httplowlevelclient.cpp.
{
        core::socket::stream::SocketContext::onReadError(errnum);
        shutdownWrite();
    }
References core::socket::stream::SocketContext::onReadError(), and core::socket::stream::SocketContext::shutdownWrite().
onReceivedFromPeer()
std::size_t SimpleSocketProtocol::onReceivedFromPeer () inline override virtual
Implements core::socket::SocketContext.
Definition at line 108 of file httplowlevelclient.cpp.
{
        return responseParser->parse();
    }
References web::http::Parser::parse(), and responseParser.
onSignal()
bool SimpleSocketProtocol::onSignal (int signum) inline override virtual
Implements core::socket::SocketContext.
Definition at line 104 of file httplowlevelclient.cpp.
{
        return true;
    }
onWriteError()
void SimpleSocketProtocol::onWriteError (int errnum) inline override virtual
Implements core::socket::SocketContext.
Definition at line 112 of file httplowlevelclient.cpp.
{
        core::socket::stream::SocketContext::onWriteError(errnum);
        shutdownRead();
    }
References core::socket::stream::SocketContext::onWriteError(), and core::socket::stream::SocketContext::shutdownRead().
readFromPeer()
std::size_t core::socket::stream::SocketContext::readFromPeer (char * junk, std::size_t junklen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 50 of file SocketContext.cpp.
{
        return socketConnection->readFromPeer(junk, junklen);
    }
References core::socket::stream::SocketConnection::readFromPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by apps::echo::model::EchoSocketContext::onReceivedFromPeer(), web::http::Parser::readContent(), web::http::Parser::readHeaderLine(), web::http::Parser::readStartLine(), and iot::mqtt::SocketContext::recv().
sendToPeer() [1/3]
void core::socket::stream::SocketContext::sendToPeer (const char * junk, std::size_t junkLen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 42 of file SocketContext.cpp.
{
        socketConnection->sendToPeer(junk, junkLen);
    }
References core::socket::stream::SocketConnection::sendToPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::Request::enqueue(), apps::echo::model::EchoSocketContext::onReceivedFromPeer(), iot::mqtt::SocketContext::send(), iot::mqtt_fast::SocketContext::send(), and web::http::server::RequestContextBase::sendToPeer().
sendToPeer() [2/3]
virtual void core::socket::SocketContext::sendToPeer (const char * junk, std::size_t junkLen) const virtual inherited
Implements core::socket::SocketContext.
sendToPeer() [3/3]
void core::socket::SocketContext::sendToPeer (const std::string & data) const inherited
Definition at line 55 of file SocketContext.cpp.
{
        sendToPeer(data.data(), data.length());
    }
setTimeout()
void core::socket::stream::SocketContext::setTimeout (const utils::Timeval & timeout) final virtual inherited
Implements core::socket::SocketContext.
Definition at line 54 of file SocketContext.cpp.
{
        socketConnection->setTimeout(timeout);
    }
References core::socket::stream::SocketConnection::setTimeout(), and core::socket::stream::SocketContext::socketConnection.
shutdownRead()
void core::socket::stream::SocketContext::shutdownRead () inherited
Definition at line 62 of file SocketContext.cpp.
{
        socketConnection->shutdownRead();
    }
References core::socket::stream::SocketConnection::shutdownRead(), and core::socket::stream::SocketContext::socketConnection.
Referenced by onWriteError(), and core::socket::stream::SocketContext::onWriteError().
shutdownWrite()
void core::socket::stream::SocketContext::shutdownWrite (bool forceClose = false) inherited
Definition at line 66 of file SocketContext.cpp.
{
        socketConnection->shutdownWrite(forceClose);
    }
References core::socket::stream::SocketConnection::shutdownWrite(), and core::socket::stream::SocketContext::socketConnection.
Referenced by iot::mqtt::SocketContext::end(), onReadError(), core::socket::stream::SocketContext::onReadError(), web::http::server::SocketContext< RequestT, ResponseT >::requestParsed(), and web::http::server::SocketContext< RequestT, ResponseT >::sendToPeerCompleted().
streamToPeer()
void core::socket::stream::SocketContext::streamToPeer (core::pipe::Source * source) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 46 of file SocketContext.cpp.
{
        socketConnection->streamToPeer(source);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::streamToPeer().
Referenced by web::http::server::RequestContextBase::streamToPeer().
switchSocketContext()
void core::socket::stream::SocketContext::switchSocketContext (SocketContext * newSocketContext) virtual inherited
Definition at line 34 of file SocketContext.cpp.
{
        socketConnection->switchSocketContext(newSocketContext);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::switchSocketContext().
Referenced by web::http::server::RequestContextBase::sendToPeerCompleted(), and web::http::client::Response::upgrade().
Member Data Documentation
responseParser
web::http::client::ResponseParser* SimpleSocketProtocol::responseParser private
Definition at line 123 of file httplowlevelclient.cpp.
Referenced by onReceivedFromPeer(), SimpleSocketProtocol(), and ~SimpleSocketProtocol().
socketConnection
core::socket::stream::SocketConnection* core::socket::stream::SocketContext::socketConnection private inherited
Definition at line 77 of file SocketContext.h.
Referenced by core::socket::stream::SocketContext::close(), core::socket::stream::SocketContext::getSocketConnection(), core::socket::stream::SocketContext::readFromPeer(), core::socket::stream::SocketContext::sendToPeer(), core::socket::stream::SocketContext::setTimeout(), core::socket::stream::SocketContext::shutdownRead(), core::socket::stream::SocketContext::shutdownWrite(), core::socket::stream::SocketContext::SocketContext(), core::socket::stream::SocketContext::streamToPeer(), and core::socket::stream::SocketContext::switchSocketContext().
The documentation for this class was generated from the following file:
apps/http/httplowlevelclient.cpp