SNode.C: iot::mqtt::packets::Pubcomp Class Reference
iot::mqtt::packets::Pubcomp Class Reference
#include <Pubcomp.h>
Public Member Functions
Pubcomp ()
Pubcomp (uint16_t packetIdentifier)
uint16_t getPacketIdentifier () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type, const std::string &name)
ControlPacket (const ControlPacket &)=default
ControlPacket (ControlPacket &&)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
ControlPacket & operator= (ControlPacket &&)=default
std::vector< char > serialize () const
const std::string & getName () const
Protected Attributes
iot::mqtt::types::UInt16 packetIdentifier
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t flags = 0
Private Member Functions
std::vector< char > serializeVP () const override
Additional Inherited Members
Protected Member Functions inherited from iot::mqtt::ControlPacket
uint8_t getType () const
uint8_t getFlags () const
Detailed Description
Definition at line 56 of file Pubcomp.h.
Constructor & Destructor Documentation
Pubcomp() [1/2]
iot::mqtt::packets::Pubcomp::Pubcomp ()
Definition at line 53 of file Pubcomp.cpp.
        : iot::mqtt::ControlPacket(MQTT_PUBCOMP, "PUBCOMP") {
    }
References iot::mqtt::ControlPacket::ControlPacket().
Referenced by Pubcomp().
Pubcomp() [2/2]
iot::mqtt::packets::Pubcomp::Pubcomp (uint16_t packetIdentifier) explicit
Definition at line 57 of file Pubcomp.cpp.
        : Pubcomp() {
        this->packetIdentifier = packetIdentifier;
    }
References iot::mqtt::types::UInt16::operator=(), packetIdentifier, and Pubcomp().
Referenced by iot::mqtt::Mqtt::sendPubcomp().
Member Function Documentation
getPacketIdentifier()
uint16_t iot::mqtt::packets::Pubcomp::getPacketIdentifier () const
Definition at line 66 of file Pubcomp.cpp.
{
        return packetIdentifier;
    }
References packetIdentifier.
Referenced by iot::mqtt::Mqtt::_onPubcomp().
serializeVP()
std::vector< char > iot::mqtt::packets::Pubcomp::serializeVP () const override private virtual
Implements iot::mqtt::ControlPacket.
Definition at line 62 of file Pubcomp.cpp.
{
        return packetIdentifier.serialize();
    }
References packetIdentifier, and iot::mqtt::types::TypeBase< ValueTypeT >::serialize().
Member Data Documentation
packetIdentifier
iot::mqtt::types::UInt16 iot::mqtt::packets::Pubcomp::packetIdentifier protected
Definition at line 68 of file Pubcomp.h.
Referenced by iot::mqtt::client::packets::Pubcomp::deserializeVP(), iot::mqtt::server::packets::Pubcomp::deserializeVP(), getPacketIdentifier(), Pubcomp(), and serializeVP().
The documentation for this class was generated from the following files:
iot/mqtt/packets/Pubcomp.h
iot/mqtt/packets/Pubcomp.cpp