SNode.C: web::http::server::SocketContext< RequestT, ResponseT >::RequestContext Class Reference
web::http::server::SocketContext< RequestT, ResponseT >::RequestContext Class Reference
Public Member Functions
RequestContext (SocketContext *serverContext)
bool switchSocketContext (core::socket::stream::SocketContextFactory *socketContextUpgradeFactory)
void sendToPeer (const char *junk, std::size_t junkLen)
void streamToPeer (core::pipe::Source *source)
void sendToPeerCompleted ()
void close ()
Public Attributes
Request request
Response response
bool ready
int status
std::string reason
Private Attributes
web::http::SocketContext * socketContext = nullptr
core::socket::stream::SocketContext * socketContextUpgrade = nullptr
Detailed Description
template<typename RequestT, typename ResponseT>
class web::http::server::SocketContext< RequestT, ResponseT >::RequestContext
Definition at line 49 of file SocketContext.h.
Constructor & Destructor Documentation
RequestContext()
template<typename RequestT , typename ResponseT > web::http::server::SocketContext< RequestT, ResponseT >::RequestContext::RequestContext (SocketContext * serverContext) inline explicit
Definition at line 51 of file SocketContext.h.
                : RequestContextBase(serverContext)
                , response(this)
                , ready(false)
                , status(0) {
            }
References web::http::server::SocketContext< RequestT, ResponseT >::RequestContext::ready, web::http::server::SocketContext< RequestT, ResponseT >::RequestContext::response, and web::http::server::SocketContext< RequestT, ResponseT >::RequestContext::status.
Member Function Documentation
close()
void web::http::server::RequestContextBase::close () inherited
Definition at line 60 of file RequestContextBase.cpp.
{
        socketContext->close();
    }
References core::socket::stream::SocketContext::close(), and web::http::server::RequestContextBase::socketContext.
Referenced by web::http::server::Response::error(), and web::http::server::Response::sendToPeerCompleted().
sendToPeer()
void web::http::server::RequestContextBase::sendToPeer (const char * junk, std::size_t junkLen) inherited
Definition at line 44 of file RequestContextBase.cpp.
{
        socketContext->sendToPeer(junk, junkLen);
    }
References core::socket::stream::SocketContext::sendToPeer(), and web::http::server::RequestContextBase::socketContext.
Referenced by web::http::server::Response::sendResponse().
sendToPeerCompleted()
void web::http::server::RequestContextBase::sendToPeerCompleted () inherited
Definition at line 52 of file RequestContextBase.cpp.
{
        if (socketContextUpgrade != nullptr) {
            socketContext->switchSocketContext(socketContextUpgrade);
        }
        socketContext->sendToPeerCompleted();
    }
References web::http::SocketContext::sendToPeerCompleted(), web::http::server::RequestContextBase::socketContext, web::http::server::RequestContextBase::socketContextUpgrade, and core::socket::stream::SocketContext::switchSocketContext().
Referenced by web::http::server::Response::sendToPeerCompleted().
streamToPeer()
void web::http::server::RequestContextBase::streamToPeer (core::pipe::Source * source) inherited
Definition at line 48 of file RequestContextBase.cpp.
{
        socketContext->streamToPeer(source);
    }
References web::http::server::RequestContextBase::socketContext, and core::socket::stream::SocketContext::streamToPeer().
Referenced by web::http::server::Response::stream().
switchSocketContext()
bool web::http::server::RequestContextBase::switchSocketContext (core::socket::stream::SocketContextFactory * socketContextUpgradeFactory) inherited
Definition at line 38 of file RequestContextBase.cpp.
{
        socketContextUpgrade = socketContextUpgradeFactory->create(socketContext->getSocketConnection());
        return socketContextUpgrade != nullptr;
    }
References core::socket::stream::SocketContextFactory::create(), core::socket::stream::SocketContext::getSocketConnection(), web::http::server::RequestContextBase::socketContext, and web::http::server::RequestContextBase::socketContextUpgrade.
Referenced by web::http::server::Response::upgrade().
Member Data Documentation
ready
template<typename RequestT , typename ResponseT > bool web::http::server::SocketContext< RequestT, ResponseT >::RequestContext::ready
Definition at line 61 of file SocketContext.h.
Referenced by web::http::server::SocketContext< RequestT, ResponseT >::RequestContext::RequestContext().
reason
template<typename RequestT , typename ResponseT > std::string web::http::server::SocketContext< RequestT, ResponseT >::RequestContext::reason
Definition at line 64 of file SocketContext.h.
request
template<typename RequestT , typename ResponseT > Request web::http::server::SocketContext< RequestT, ResponseT >::RequestContext::request
Definition at line 58 of file SocketContext.h.
response
template<typename RequestT , typename ResponseT > Response web::http::server::SocketContext< RequestT, ResponseT >::RequestContext::response
Definition at line 59 of file SocketContext.h.
Referenced by web::http::server::SocketContext< RequestT, ResponseT >::RequestContext::RequestContext().
socketContext
web::http::SocketContext* web::http::server::RequestContextBase::socketContext = nullptr private inherited
Definition at line 62 of file RequestContextBase.h.
Referenced by web::http::server::RequestContextBase::close(), web::http::server::RequestContextBase::RequestContextBase(), web::http::server::RequestContextBase::sendToPeer(), web::http::server::RequestContextBase::sendToPeerCompleted(), web::http::server::RequestContextBase::streamToPeer(), and web::http::server::RequestContextBase::switchSocketContext().
socketContextUpgrade
core::socket::stream::SocketContext* web::http::server::RequestContextBase::socketContextUpgrade = nullptr private inherited
Definition at line 64 of file RequestContextBase.h.
Referenced by web::http::server::RequestContextBase::sendToPeerCompleted(), and web::http::server::RequestContextBase::switchSocketContext().
status
template<typename RequestT , typename ResponseT > int web::http::server::SocketContext< RequestT, ResponseT >::RequestContext::status
Definition at line 63 of file SocketContext.h.
Referenced by web::http::server::SocketContext< RequestT, ResponseT >::RequestContext::RequestContext().
The documentation for this class was generated from the following file:
web/http/server/SocketContext.h