SNode.C: core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT > Class Template Reference
core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT > Class Template Reference final
#include <SocketConnection.h>
Public Types
using SocketAddress = typename Super::SocketAddress
Public Member Functions
SocketConnection (PhysicalSocket &&physicalSocket, const std::function< void(SocketConnection *)> &onDisconnect, const std::shared_ptr< Config > &config)
SSL * getSSL () const
Public Member Functions inherited from core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >
void sendToPeer (const std::string &data)
SocketConnectionT ()=delete
int getFd () const final
void setTimeout (const utils::Timeval &timeout) final
void setReadTimeout (const utils::Timeval &timeout) final
void setWriteTimeout (const utils::Timeval &timeout) final
const SocketAddress & getBindAddress () const final
const SocketAddress & getLocalAddress () const final
const SocketAddress & getRemoteAddress () const final
std::size_t readFromPeer (char *chunk, std::size_t chunkLen) final
bool streamToPeer (core::pipe::Source *source) final
void streamEof () final
void shutdownRead () final
void shutdownWrite (bool forceClose) final
void close () final
Config & getConfig () const
std::size_t getTotalSent () const override
std::size_t getTotalQueued () const override
std::size_t getTotalRead () const override
std::size_t getTotalProcessed () const override
Public Member Functions inherited from core::socket::stream::SocketConnection
SocketConnection (int fd, const net::config::ConfigInstance *config)
SocketConnection (const SocketConnection &)=delete
void setSocketContext (SocketContext *socketContext)
virtual void sendToPeer (const char *chunk, std::size_t chunkLen)=0
void sendToPeer (const std::string &data)
void sentToPeer (const std::vector< uint8_t > &data)
void sentToPeer (const std::vector< char > &data)
const std::string & getInstanceName () const
const std::string & getConnectionName () const
SocketContext * getSocketContext () const
std::string getOnlineSince () const
std::string getOnlineDuration () const
const net::config::ConfigInstance * getConfigInstance () const
Private Types
using Super
using Config = ConfigT
using PhysicalSocket = PhysicalSocketT
using SocketReader = typename Super::SocketReader
using SocketWriter = typename Super::SocketWriter
Private Member Functions
SSL * startSSL (int fd, SSL_CTX *ctx)
void stopSSL ()
bool doSSLHandshake (const std::function< void()> &onSuccess, const std::function< void()> &onTimeout, const std::function< void(int)> &onStatus) final
void doSSLShutdown ()
void onReadShutdown () final
void doWriteShutdown (const std::function< void()> &onShutdown) final
Private Attributes
SSL * ssl = nullptr
utils::Timeval sslInitTimeout
utils::Timeval sslShutdownTimeout
bool closeNotifyIsEOF
Friends
template<typename PhysicalSocket, typename Config>
class SocketAcceptor
template<typename PhysicalSocket, typename Config>
class SocketConnector
Additional Inherited Members
Protected Types inherited from core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >
using Super
using Config
using PhysicalSocket
using SocketReader
using SocketWriter
using SocketAddress
Protected Member Functions inherited from core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >
~SocketConnectionT () override
void doWriteShutdown (const std::function< void()> &onShutdown) override
void onWriteError (int errnum)
void onReadError (int errnum)
Protected Member Functions inherited from core::socket::stream::SocketConnection
virtual ~SocketConnection ()
void setSocketContext (const std::shared_ptr< SocketContextFactory > &socketContextFactory)
Protected Member Functions inherited from core::socket::stream::SocketReader
SocketReader (const std::string &instanceName, const std::function< void(int)> &onStatus, const utils::Timeval &timeout, std::size_t blockSize, const utils::Timeval &terminateTimeout)
std::size_t getTotalRead () const
std::size_t getTotalProcessed () const
void setBlockSize (std::size_t readBlockSize)
std::size_t readFromPeer (char *chunk, std::size_t chunkLen)
void shutdownRead ()
SocketReader ()=delete
Protected Member Functions inherited from core::eventreceiver::ReadEventReceiver
ReadEventReceiver (const std::string &name, const utils::Timeval &timeout)
Protected Member Functions inherited from core::DescriptorEventReceiver
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
int getRegisteredFd () const
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Protected Member Functions inherited from core::Observer
void observed ()
void unObserved ()
Observer ()=default
Observer (Observer &)=delete
Observer (Observer &&)=delete
virtual ~Observer ()
Protected Member Functions inherited from core::EventReceiver
virtual ~EventReceiver ()=default
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Member Functions inherited from core::socket::stream::SocketWriter
SocketWriter (const std::string &instanceName, const std::function< void(int)> &onStatus, const utils::Timeval &timeout, std::size_t blockSize, const utils::Timeval &terminateTimeout)
std::size_t getTotalSent () const
std::size_t getTotalQueued () const
void setBlockSize (std::size_t writeBlockSize)
void sendToPeer (const char *chunk, std::size_t chunkLen)
bool streamToPeer (core::pipe::Source *source)
void streamEof ()
void shutdownWrite (const std::function< void()> &onShutdown)
SocketWriter ()=delete
Protected Member Functions inherited from core::eventreceiver::WriteEventReceiver
WriteEventReceiver (const std::string &name, const utils::Timeval &timeout)
Static Protected Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Protected Attributes inherited from core::socket::stream::SocketConnection
core::socket::stream::SocketContext * socketContext = nullptr
core::socket::stream::SocketContext * newSocketContext = nullptr
std::string instanceName
std::string connectionName
std::chrono::time_point< std::chrono::system_clock > onlineSinceTimePoint
Protected Attributes inherited from core::socket::stream::tls::SocketReader
SSL * ssl = nullptr
Protected Attributes inherited from core::socket::stream::SocketReader
utils::Timeval terminateTimeout
Protected Attributes inherited from core::socket::stream::tls::SocketWriter
SSL * ssl = nullptr
Protected Attributes inherited from core::socket::stream::SocketWriter
bool markShutdown = false
std::function< void()> onShutdown
std::vector< char > writePuffer
bool shutdownInProgress = false
utils::Timeval terminateTimeout
Detailed Description
template<typename PhysicalSocketT, typename ConfigT>
class core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT >
Definition at line 60 of file SocketConnection.h.
Member Typedef Documentation
Config
template<typename PhysicalSocketT, typename ConfigT> using core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT >::Config = ConfigT private
Definition at line 69 of file SocketConnection.h.
PhysicalSocket
template<typename PhysicalSocketT, typename ConfigT> using core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT >::PhysicalSocket = PhysicalSocketT private
Definition at line 70 of file SocketConnection.h.
SocketAddress
template<typename PhysicalSocketT, typename ConfigT> using core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT >::SocketAddress = typename Super::SocketAddress
Definition at line 75 of file SocketConnection.h.
SocketReader
template<typename PhysicalSocketT, typename ConfigT> using core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT >::SocketReader = typename Super::SocketReader private
Definition at line 71 of file SocketConnection.h.
SocketWriter
template<typename PhysicalSocketT, typename ConfigT> using core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT >::SocketWriter = typename Super::SocketWriter private
Definition at line 72 of file SocketConnection.h.
Super
template<typename PhysicalSocketT, typename ConfigT> using core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT >::Super private
Initial value:
 core::socket::stream::
            SocketConnectionT<PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT>
Definition at line 66 of file SocketConnection.h.
Constructor & Destructor Documentation
SocketConnection()
template<typename PhysicalSocket, typename Config> core::socket::stream::tls::SocketConnection< PhysicalSocket, Config >::SocketConnection (PhysicalSocket && physicalSocket, const std::function< void(SocketConnection< PhysicalSocketT, ConfigT > *)> & onDisconnect, const std::shared_ptr< Config > & config)
Definition at line 61 of file SocketConnection.hpp.
        : Super(
              std::move(physicalSocket),
              [onDisconnect, this]() {
                  onDisconnect(this);
              },
              config)
        , sslInitTimeout(config->getInitTimeout())
        , sslShutdownTimeout(config->getShutdownTimeout())
        , closeNotifyIsEOF(!config->getNoCloseNotifyIsEOF()) {
    }
Member Function Documentation
doSSLHandshake()
template<typename PhysicalSocket, typename Config> bool core::socket::stream::tls::SocketConnection< PhysicalSocket, Config >::doSSLHandshake (const std::function< void()> & onSuccess, const std::function< void()> & onTimeout, const std::function< void(int)> & onStatus) final private virtual
Implements core::socket::stream::tls::SocketReader.
Definition at line 113 of file SocketConnection.hpp.
{
        if (ssl != nullptr) {
            if (!SocketReader::isSuspended()) {
                SocketReader::suspend();
            }
            if (!SocketWriter::isSuspended()) {
                SocketWriter::suspend();
            }
            TLSHandshake::doHandshake(
                Super::getConnectionName(),
                ssl,
                [onSuccess, this]() { // onSuccess
                    SocketReader::span();
                    onSuccess();
                },
                [onTimeout]() { // onTimeout
                    onTimeout();
                },
                [onStatus](int sslErr) { // onStatus
                    onStatus(sslErr);
                },
                sslInitTimeout);
        }
        return ssl != nullptr;
    }
References core::socket::stream::tls::TLSHandshake::doHandshake(), ssl, and sslInitTimeout.
doSSLShutdown()
template<typename PhysicalSocket, typename Config> void core::socket::stream::tls::SocketConnection< PhysicalSocket, Config >::doSSLShutdown () private
Definition at line 144 of file SocketConnection.hpp.
{
        bool resumeSocketReader = false;
        bool resumeSocketWriter = false;
        if (!SocketReader::isSuspended()) {
            SocketReader::suspend();
            resumeSocketReader = true;
        }
        if (!SocketWriter::isSuspended()) {
            SocketWriter::suspend();
            resumeSocketWriter = true;
        }
        TLSShutdown::doShutdown(
            Super::getConnectionName(),
            ssl,
            [this, resumeSocketReader, resumeSocketWriter]() { // onSuccess
                if (resumeSocketReader) {
                    SocketReader::resume();
                }
                if (resumeSocketWriter) {
                    SocketWriter::resume();
                }
                if (SSL_get_shutdown(ssl) == (SSL_SENT_SHUTDOWN | SSL_RECEIVED_SHUTDOWN)) {
                    LOG(DEBUG) << Super::getConnectionName() << " SSL/TLS: Passive close_notify received and sent";
                } else {
                    LOG(DEBUG) << Super::getConnectionName() << " SSL/TLS: Active close_notify sent";
                }
            },
            [this, resumeSocketReader, resumeSocketWriter]() { // onTimeout
                if (resumeSocketReader) {
                    SocketReader::resume();
                }
                if (resumeSocketWriter) {
                    SocketWriter::resume();
                }
                LOG(ERROR) << Super::getConnectionName() << " SSL/TLS: Shutdown handshake timed out";
                Super::doWriteShutdown([this]() {
                    SocketConnection::close();
                });
            },
            [this, resumeSocketReader, resumeSocketWriter](int sslErr) { // onStatus
                if (resumeSocketReader) {
                    SocketReader::resume();
                }
                if (resumeSocketWriter) {
                    SocketWriter::resume();
                }
                ssl_log(Super::getConnectionName() + " SSL/TLS: Shutdown handshake failed", sslErr);
                Super::doWriteShutdown([this]() {
                    SocketConnection::close();
                });
            },
            sslShutdownTimeout);
    }
References core::socket::stream::tls::TLSShutdown::doShutdown(), ssl, and sslShutdownTimeout.
Referenced by doWriteShutdown(), and onReadShutdown().
doWriteShutdown()
template<typename PhysicalSocket, typename Config> void core::socket::stream::tls::SocketConnection< PhysicalSocket, Config >::doWriteShutdown (const std::function< void()> & onShutdown) final private virtual
Implements core::socket::stream::SocketWriter.
Definition at line 225 of file SocketConnection.hpp.
{
        if ((SSL_get_shutdown(ssl) & SSL_SENT_SHUTDOWN) == 0) {
            LOG(DEBUG) << Super::getConnectionName() << " SSL/TLS: Active send close_notify";
            doSSLShutdown();
        } else {
            Super::doWriteShutdown(onShutdown);
        }
    }
References doSSLShutdown(), and ssl.
getSSL()
template<typename PhysicalSocket, typename Config> SSL * core::socket::stream::tls::SocketConnection< PhysicalSocket, Config >::getSSL () const
Definition at line 76 of file SocketConnection.hpp.
{
        return ssl;
    }
References ssl.
Referenced by tls::getClient().
onReadShutdown()
template<typename PhysicalSocket, typename Config> void core::socket::stream::tls::SocketConnection< PhysicalSocket, Config >::onReadShutdown () final private virtual
Implements core::socket::stream::tls::SocketReader.
Definition at line 202 of file SocketConnection.hpp.
{
        if ((SSL_get_shutdown(ssl) & SSL_RECEIVED_SHUTDOWN) != 0) {
            if ((SSL_get_shutdown(ssl) & SSL_SENT_SHUTDOWN) != 0) {
                LOG(DEBUG) << Super::getConnectionName() << " SSL/TLS: Active close_notify sent and received";
                SocketWriter::shutdownInProgress = false;
                if (closeNotifyIsEOF) {
                    this->onReadError(0);
                }
            } else {
                LOG(DEBUG) << Super::getConnectionName() << " SSL/TLS: Passive close_notify received, answering with close_notify";
                doSSLShutdown();
            }
        } else {
            LOG(ERROR) << Super::getConnectionName() << " SSL/TLS: Unexpected EOF error";
            SocketWriter::shutdownInProgress = false;
            SSL_set_shutdown(ssl, SSL_SENT_SHUTDOWN | SSL_RECEIVED_SHUTDOWN);
        }
    }
References closeNotifyIsEOF, doSSLShutdown(), and ssl.
startSSL()
template<typename PhysicalSocket, typename Config> SSL * core::socket::stream::tls::SocketConnection< PhysicalSocket, Config >::startSSL (int fd, SSL_CTX * ctx) private
Definition at line 81 of file SocketConnection.hpp.
{
        if (ctx != nullptr) {
            ssl = SSL_new(ctx);
            if (ssl != nullptr) {
                SSL_set_ex_data(ssl, 0, const_cast<std::string*>(&Super::getConnectionName()));
                if (SSL_set_fd(ssl, fd) == 1) {
                    SocketReader::ssl = ssl;
                    SocketWriter::ssl = ssl;
                } else {
                    SSL_free(ssl);
                    ssl = nullptr;
                }
            }
        }
        return ssl;
    }
References ssl.
stopSSL()
template<typename PhysicalSocket, typename Config> void core::socket::stream::tls::SocketConnection< PhysicalSocket, Config >::stopSSL () private
Definition at line 102 of file SocketConnection.hpp.
{
        if (ssl != nullptr) {
            SSL_free(ssl);
            ssl = nullptr;
            SocketReader::ssl = nullptr;
            SocketWriter::ssl = nullptr;
        }
    }
References ssl.
Friends And Related Symbol Documentation
SocketAcceptor
template<typename PhysicalSocketT, typename ConfigT> template<typename PhysicalSocket, typename Config> friend class SocketAcceptor friend
Definition at line 105 of file SocketConnection.h.
SocketConnector
template<typename PhysicalSocketT, typename ConfigT> template<typename PhysicalSocket, typename Config> friend class SocketConnector friend
Definition at line 108 of file SocketConnection.h.
Member Data Documentation
closeNotifyIsEOF
template<typename PhysicalSocketT, typename ConfigT> bool core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT >::closeNotifyIsEOF private
Definition at line 102 of file SocketConnection.h.
Referenced by onReadShutdown().
ssl
template<typename PhysicalSocketT, typename ConfigT> SSL* core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT >::ssl = nullptr private
Definition at line 98 of file SocketConnection.h.
Referenced by doSSLHandshake(), doSSLShutdown(), doWriteShutdown(), getSSL(), onReadShutdown(), startSSL(), and stopSSL().
sslInitTimeout
template<typename PhysicalSocketT, typename ConfigT> utils::Timeval core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT >::sslInitTimeout private
Definition at line 100 of file SocketConnection.h.
Referenced by doSSLHandshake().
sslShutdownTimeout
template<typename PhysicalSocketT, typename ConfigT> utils::Timeval core::socket::stream::tls::SocketConnection< PhysicalSocketT, ConfigT >::sslShutdownTimeout private
Definition at line 101 of file SocketConnection.h.
Referenced by doSSLShutdown().
The documentation for this class was generated from the following files:
core/socket/stream/tls/SocketConnection.h
core/socket/stream/tls/SocketConnection.hpp