SNode.C: web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT > Class Template Reference
web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT > Class Template Reference abstract
#include <SocketContextUpgradeFactorySelector.h>
Public Types
using SocketContextUpgradeFactory = SocketContextUpgradeFactoryT
using Request = typename SocketContextUpgradeFactory::Request
using Response = typename SocketContextUpgradeFactory::Response
Public Member Functions
virtual SocketContextUpgradeFactory * select (Request &req, Response &res)=0
bool add (SocketContextUpgradeFactory *socketContextUpgradeFactory)
void link (const std::string &upgradeContextName, SocketContextUpgradeFactory *(*linkedPlugin)())
void allowDlOpen ()
void unload (SocketContextUpgradeFactory *socketContextUpgradeFactory)
Protected Types
using SocketContextUpgrade = web::http::SocketContextUpgrade< Request, Response >
Protected Member Functions
SocketContextUpgradeFactorySelector ()=default
virtual ~SocketContextUpgradeFactorySelector ()=default
SocketContextUpgradeFactory * select (const std::string &socketContextUpgradeName)
virtual SocketContextUpgradeFactory * load (const std::string &socketContextUpgradeName)=0
SocketContextUpgradeFactory * load (const std::string &socketContextUpgradeName, const std::string &socketContextUpgradeFactoryLibraryFile, const std::string &socketContextUpgradeFactoryFunctionName)
bool add (SocketContextUpgradeFactory *socketContextUpgradeFactory, void *handler)
Private Types
using SocketContextPlugin = SocketContextPlugin { SocketContextUpgradeFactory *socketContextUpgradeFactory
Private Attributes
void * handle = nullptr
std::map< std::string, SocketContextPlugin > socketContextUpgradePlugins
std::map< std::string, SocketContextUpgradeFactory *(*)()> linkedSocketContextUpgradePlugins
bool onlyLinked = false
Detailed Description
template<typename SocketContextUpgradeFactoryT>
class web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >
Definition at line 35 of file SocketContextUpgradeFactorySelector.h.
Member Typedef Documentation
Request
template<typename SocketContextUpgradeFactoryT > using web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::Request = typename SocketContextUpgradeFactory::Request
Definition at line 38 of file SocketContextUpgradeFactorySelector.h.
Response
template<typename SocketContextUpgradeFactoryT > using web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::Response = typename SocketContextUpgradeFactory::Response
Definition at line 39 of file SocketContextUpgradeFactorySelector.h.
SocketContextPlugin
template<typename SocketContextUpgradeFactoryT > using web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::SocketContextPlugin = SocketContextPlugin { SocketContextUpgradeFactory* socketContextUpgradeFactory private
Definition at line 48 of file SocketContextUpgradeFactorySelector.h.
SocketContextUpgrade
template<typename SocketContextUpgradeFactoryT > using web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::SocketContextUpgrade = web::http::SocketContextUpgrade<Request, Response> protected
Definition at line 42 of file SocketContextUpgradeFactorySelector.h.
SocketContextUpgradeFactory
template<typename SocketContextUpgradeFactoryT > using web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::SocketContextUpgradeFactory = SocketContextUpgradeFactoryT
Definition at line 37 of file SocketContextUpgradeFactorySelector.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactorySelector()
template<typename SocketContextUpgradeFactoryT > web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::SocketContextUpgradeFactorySelector () protected default
~SocketContextUpgradeFactorySelector()
template<typename SocketContextUpgradeFactoryT > virtual web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::~SocketContextUpgradeFactorySelector () protected virtual default
Member Function Documentation
add() [1/2]
template<typename SocketContextUpgradeFactory > bool web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::add (SocketContextUpgradeFactory * socketContextUpgradeFactory)
Definition at line 50 of file SocketContextUpgradeFactorySelector.hpp.
{
        return add(socketContextUpgradeFactory, nullptr);
    }
add() [2/2]
template<typename SocketContextUpgradeFactory > bool web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::add (SocketContextUpgradeFactory * socketContextUpgradeFactory, void * handler) protected
Definition at line 37 of file SocketContextUpgradeFactorySelector.hpp.
{
        bool success = false;
        if (socketContextUpgradeFactory != nullptr) {
            SocketContextPlugin socketContextPlugin = {.socketContextUpgradeFactory = socketContextUpgradeFactory, .handle = handle};
            std::tie(std::ignore, success) = socketContextUpgradePlugins.insert({socketContextUpgradeFactory->name(), socketContextPlugin});
        }
        return success;
    }
References web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::socketContextUpgradePlugins.
allowDlOpen()
template<typename SocketContextUpgradeFactory > void web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::allowDlOpen ()
Definition at line 55 of file SocketContextUpgradeFactorySelector.hpp.
{
        onlyLinked = false;
    }
link()
template<typename SocketContextUpgradeFactory > void web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::link (const std::string & upgradeContextName, SocketContextUpgradeFactory *(*)() linkedPlugin)
Definition at line 116 of file SocketContextUpgradeFactorySelector.hpp.
{
        if (!linkedSocketContextUpgradePlugins.contains(socketContextUpgradeName)) {
            linkedSocketContextUpgradePlugins[socketContextUpgradeName] = linkedPlugin;
        }
        onlyLinked = true;
    }
References web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::linkedSocketContextUpgradePlugins, and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::onlyLinked.
Referenced by web::http::client::SocketContextUpgradeFactory::link(), and web::http::server::SocketContextUpgradeFactory::link().
load() [1/2]
template<typename SocketContextUpgradeFactoryT > virtual SocketContextUpgradeFactory * web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::load (const std::string & socketContextUpgradeName) protected pure virtual
Implemented in web::http::client::SocketContextUpgradeFactorySelector, and web::http::server::SocketContextUpgradeFactorySelector.
load() [2/2]
template<typename SocketContextUpgradeFactory > SocketContextUpgradeFactory * web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::load (const std::string & socketContextUpgradeName, const std::string & socketContextUpgradeFactoryLibraryFile, const std::string & socketContextUpgradeFactoryFunctionName) protected
Definition at line 61 of file SocketContextUpgradeFactorySelector.hpp.
{
        SocketContextUpgradeFactory* socketContextUpgradeFactory = nullptr;
        void* handle = dlOpen(socketContextUpgradeFactoryLibraryFile, RTLD_LAZY | RTLD_GLOBAL);
        if (handle != nullptr) {
            SocketContextUpgradeFactory* (*getSocketContextUpgradeFactory)() = reinterpret_cast<SocketContextUpgradeFactory* (*) ()>(
                core::DynamicLoader::dlSym(handle, socketContextUpgradeFactoryFunctionName));
            if (getSocketContextUpgradeFactory != nullptr) {
                socketContextUpgradeFactory = getSocketContextUpgradeFactory();
                if (socketContextUpgradeFactory != nullptr) {
                    if (add(socketContextUpgradeFactory, handle)) {
                        LOG(DEBUG) << "SocketContextUpgradeFactory created successfull: " << socketContextUpgradeName;
                    } else {
                        LOG(DEBUG) << "UpgradeSocketContext already existing. Not using: " << socketContextUpgradeName;
                        delete socketContextUpgradeFactory;
                        socketContextUpgradeFactory = nullptr;
                        core::DynamicLoader::dlClose(handle);
                    }
                } else {
                    LOG(DEBUG) << "SocketContextUpgradeFactory not created: " << socketContextUpgradeName;
                    core::DynamicLoader::dlClose(handle);
                }
            } else {
                LOG(DEBUG) << "Optaining function \"" << socketContextUpgradeFactoryFunctionName
                           << "\" in plugin failed: " << core::DynamicLoader::dlError();
                core::DynamicLoader::dlClose(handle);
            }
        }
        return socketContextUpgradeFactory;
    }
Referenced by web::http::client::SocketContextUpgradeFactorySelector::load(), and web::http::server::SocketContextUpgradeFactorySelector::load().
select() [1/2]
template<typename SocketContextUpgradeFactory > SocketContextUpgradeFactory * web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::select (const std::string & socketContextUpgradeName) protected
Definition at line 100 of file SocketContextUpgradeFactorySelector.hpp.
{
        SocketContextUpgradeFactory* socketContextUpgradeFactory = nullptr;
        if (socketContextUpgradePlugins.contains(socketContextUpgradeName)) {
            socketContextUpgradeFactory = socketContextUpgradePlugins[socketContextUpgradeName].socketContextUpgradeFactory;
        } else if (linkedSocketContextUpgradePlugins.contains(socketContextUpgradeName)) {
            socketContextUpgradeFactory = linkedSocketContextUpgradePlugins[socketContextUpgradeName]();
            add(socketContextUpgradeFactory);
        } else if (!onlyLinked) {
            socketContextUpgradeFactory = load(socketContextUpgradeName);
        }
        return socketContextUpgradeFactory;
    }
References web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::linkedSocketContextUpgradePlugins, web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::onlyLinked, and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::socketContextUpgradePlugins.
Referenced by web::http::client::SocketContextUpgradeFactorySelector::select(), web::http::client::SocketContextUpgradeFactorySelector::select(), and web::http::server::SocketContextUpgradeFactorySelector::select().
select() [2/2]
template<typename SocketContextUpgradeFactoryT > virtual SocketContextUpgradeFactory * web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::select (Request & req, Response & res) pure virtual
unload()
template<typename SocketContextUpgradeFactory > void web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::unload (SocketContextUpgradeFactory * socketContextUpgradeFactory)
Definition at line 127 of file SocketContextUpgradeFactorySelector.hpp.
{
        std::string upgradeContextNames = socketContextUpgradeFactory->name();
        if (socketContextUpgradePlugins.contains(upgradeContextNames)) {
            SocketContextPlugin& socketContextPlugin = socketContextUpgradePlugins[upgradeContextNames];
            delete socketContextUpgradeFactory;
            if (socketContextPlugin.handle != nullptr) {
                core::DynamicLoader::dlCloseDelayed(socketContextPlugin.handle);
            }
            socketContextUpgradePlugins.erase(upgradeContextNames);
        }
    }
References core::DynamicLoader::dlCloseDelayed(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::socketContextUpgradePlugins.
Referenced by web::http::client::SocketContextUpgradeFactory::checkRefCount(), and web::http::server::SocketContextUpgradeFactory::checkRefCount().
Member Data Documentation
handle
template<typename SocketContextUpgradeFactoryT > void* web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::handle = nullptr private
Definition at line 50 of file SocketContextUpgradeFactorySelector.h.
linkedSocketContextUpgradePlugins
template<typename SocketContextUpgradeFactoryT > std::map<std::string, SocketContextUpgradeFactory* (*) ()> web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::linkedSocketContextUpgradePlugins private
Definition at line 77 of file SocketContextUpgradeFactorySelector.h.
Referenced by web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::link(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::select().
onlyLinked
template<typename SocketContextUpgradeFactoryT > bool web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::onlyLinked = false private
Definition at line 79 of file SocketContextUpgradeFactorySelector.h.
Referenced by web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::link(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::select().
socketContextUpgradePlugins
template<typename SocketContextUpgradeFactoryT > std::map<std::string, SocketContextPlugin> web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::socketContextUpgradePlugins private
Definition at line 76 of file SocketContextUpgradeFactorySelector.h.
Referenced by web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::add(), web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::select(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::unload().
The documentation for this class was generated from the following files:
web/http/SocketContextUpgradeFactorySelector.h
web/http/SocketContextUpgradeFactorySelector.hpp