SNode.C: iot::mqtt::types::UInt8 Class Reference
iot::mqtt::types::UInt8 Class Reference
#include <UInt8.h>
Public Member Functions
UInt8 ()=default
UInt8 (const UInt8 &)=default
UInt8 (UInt8 &&) noexcept=default
UInt8 & operator= (const UInt8 &)=default
UInt8 & operator= (UInt8 &&) noexcept=default
~UInt8 () override
UInt8 & operator= (const uint8_t &newValue)
operator uint8_t () const
Public Member Functions inherited from iot::mqtt::types::TypeBase< uint8_t >
TypeBase (std::size_t size=sizeof(ValueType))
TypeBase (const TypeBase &)=default
TypeBase (TypeBase &&) noexcept=default
virtual ~TypeBase ()=default
TypeBase & operator= (const TypeBase &)=default
TypeBase & operator= (TypeBase &&) noexcept=default
virtual std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
virtual std::vector< char > serialize () const
void setSize (std::size_t size)
std::size_t size ()
bool isComplete () const
virtual void reset (std::size_t size=sizeof(ValueType))
Additional Inherited Members
Protected Types inherited from iot::mqtt::types::TypeBase< uint8_t >
using ValueType = uint8_t
Protected Attributes inherited from iot::mqtt::types::TypeBase< uint8_t >
std::vector< char > value
std::size_t length
std::size_t needed
bool complete
int state
Detailed Description
Definition at line 57 of file UInt8.h.
Constructor & Destructor Documentation
UInt8() [1/3]
iot::mqtt::types::UInt8::UInt8 () default
UInt8() [2/3]
iot::mqtt::types::UInt8::UInt8 (const UInt8 &) default
UInt8() [3/3]
iot::mqtt::types::UInt8::UInt8 (UInt8 &&) default noexcept
~UInt8()
iot::mqtt::types::UInt8::~UInt8 () override
Definition at line 54 of file UInt8.cpp.
                  {
    }
Member Function Documentation
operator uint8_t()
iot::mqtt::types::UInt8::operator uint8_t () const
Definition at line 63 of file UInt8.cpp.
{
        return *reinterpret_cast<uint8_t*>(const_cast<char*>(value.data()));
    }
operator=() [1/3]
UInt8 & iot::mqtt::types::UInt8::operator= (const UInt8 &) default
operator=() [2/3]
UInt8 & iot::mqtt::types::UInt8::operator= (const uint8_t & newValue)
Definition at line 57 of file UInt8.cpp.
{
        *reinterpret_cast<uint8_t*>(value.data()) = newValue;
        return *this;
    }
Referenced by iot::mqtt::packets::Connack::Connack(), iot::mqtt::packets::Connect::Connect(), iot::mqtt::server::packets::Connect::deserializeVP(), and iot::mqtt::FixedHeader::FixedHeader().
operator=() [3/3]
UInt8 & iot::mqtt::types::UInt8::operator= (UInt8 &&) default noexcept
The documentation for this class was generated from the following files:
iot/mqtt/types/UInt8.h
iot/mqtt/types/UInt8.cpp