SNode.C: core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT > Class Template Reference
core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT > Class Template Reference abstract
#include <SocketAcceptor.h>
Public Member Functions
SocketAcceptor ()=delete
SocketAcceptor (SocketAcceptor &&)=delete
SocketAcceptor & operator= (const SocketAcceptor &)=delete
SocketAcceptor & operator= (SocketAcceptor &&)=delete
SocketAcceptor (const std::shared_ptr< core::socket::stream::SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus, const std::shared_ptr< Config > &config)
SocketAcceptor (const SocketAcceptor &socketAcceptor)
~SocketAcceptor () override
virtual void useNextSocketAddress ()=0
Protected Types
using Config = ConfigT
using SocketAddress = typename PhysicalServerSocket::SocketAddress
using SocketConnection = SocketConnectionT< PhysicalServerSocket >
Protected Member Functions
void initAcceptEvent () override
void destruct () final
void span ()
void relax ()
const std::string & getName () const
int getRegisteredFd () const
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
void observed ()
void unObserved ()
void span ()
void relax ()
const std::string & getName () const
Protected Attributes
std::shared_ptr< core::socket::stream::SocketContextFactory > socketContextFactory = nullptr
std::function< void(SocketConnection *)> onConnect
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
std::function< void(const SocketAddress &, core::socket::State)> onStatus = nullptr
std::shared_ptr< Config > config
Private Types
using PhysicalServerSocket = PhysicalSocketServerT
Private Member Functions
void acceptEvent () override
void unobservedEvent () final
void onEvent (const utils::Timeval &currentTime) override
virtual void acceptTimeout ()
void dispatchEvent () final
void timeoutEvent () final
void signalEvent (int signum) override
void onSignal (int signum)
void triggered (const utils::Timeval &currentTime)
void setEnabled (const utils::Timeval &currentTime)
void setDisabled ()
Private Attributes
PhysicalServerSocket physicalServerSocket
Event event
DescriptorEventPublisher & descriptorEventPublisher
int observedFd = -1
bool enabled = false
bool suspended = false
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
int observationCounter = 0
Detailed Description
template<typename PhysicalSocketServerT, typename ConfigT, template< typename PhysicalSocketServer > typename SocketConnectionT>
class core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >
Definition at line 37 of file SocketAcceptor.h.
Member Typedef Documentation
Config
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> using core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::Config = ConfigT protected
Definition at line 44 of file SocketAcceptor.h.
PhysicalServerSocket
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> using core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::PhysicalServerSocket = PhysicalSocketServerT private
Definition at line 41 of file SocketAcceptor.h.
SocketAddress
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> using core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAddress = typename PhysicalServerSocket::SocketAddress protected
Definition at line 45 of file SocketAcceptor.h.
SocketConnection
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> using core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketConnection = SocketConnectionT<PhysicalServerSocket> protected
Definition at line 46 of file SocketAcceptor.h.
Constructor & Destructor Documentation
SocketAcceptor() [1/4]
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor () delete
SocketAcceptor() [2/4]
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor (SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT > &&) delete
SocketAcceptor() [3/4]
template<typename PhysicalSocketServer , typename Config , template< typename PhysicalSocketServerT > typename SocketConnection> core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::SocketAcceptor (const std::shared_ptr< core::socket::stream::SocketContextFactory > & socketContextFactory, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::function< void(const SocketAddress &, core::socket::State)> & onStatus, const std::shared_ptr< Config > & config)
Definition at line 85 of file SocketAcceptor.hpp.
        : core::eventreceiver::InitAcceptEventReceiver("SocketAcceptor")
        , core::eventreceiver::AcceptEventReceiver("SocketAcceptor", 0)
        , socketContextFactory(socketContextFactory)
        , onConnect(onConnect)
        , onConnected(onConnected)
        , onDisconnect(onDisconnect)
        , onStatus(onStatus)
        , config(config) {
    }
References core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::config, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onConnect, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onConnected, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onDisconnect, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onStatus, and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::socketContextFactory.
SocketAcceptor() [4/4]
template<typename PhysicalSocketServer , typename Config , template< typename PhysicalSocketServerT > typename SocketConnection> core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::SocketAcceptor (const SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT > & socketAcceptor)
Definition at line 111 of file SocketAcceptor.hpp.
        : core::Observer(socketAcceptor)
        , core::eventreceiver::InitAcceptEventReceiver("SocketAcceptor")
        , core::eventreceiver::AcceptEventReceiver("SocketAcceptor", 0)
        , socketContextFactory(socketAcceptor.socketContextFactory)
        , onConnect(socketAcceptor.onConnect)
        , onConnected(socketAcceptor.onConnected)
        , onDisconnect(socketAcceptor.onDisconnect)
        , onStatus(socketAcceptor.onStatus)
        , config(socketAcceptor.config) {
    }
References core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::config, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onConnect, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onConnected, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onDisconnect, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onStatus, and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::socketContextFactory.
~SocketAcceptor()
template<typename PhysicalSocketServer , typename Config , template< typename PhysicalSocketServerT > typename SocketConnection> core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::~SocketAcceptor () override
Definition at line 127 of file SocketAcceptor.hpp.
{
    }
Member Function Documentation
acceptEvent()
template<typename PhysicalSocketServer , typename Config , template< typename PhysicalSocketServerT > typename SocketConnection> void core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::acceptEvent () override private virtual
Implements core::eventreceiver::AcceptEventReceiver.
Definition at line 214 of file SocketAcceptor.hpp.
{
        int acceptsPerTick = config->getAcceptsPerTick();
        do {
            PhysicalServerSocket connectedPhysicalSocket(physicalServerSocket.accept4(PhysicalServerSocket::Flags::NONBLOCK),
                                                         physicalServerSocket.getBindAddress());
            if (connectedPhysicalSocket.isValid()) {
                LOG(TRACE) << config->getInstanceName() << ": accept success '" << connectedPhysicalSocket.getBindAddress().toString()
                           << "'";
                SocketConnection* socketConnection =
                    new SocketConnection(config->getInstanceName(),
                                         std::move(connectedPhysicalSocket),
                                         onDisconnect,
                                         getLocalSocketAddress<SocketAddress>(connectedPhysicalSocket, config),
                                         getRemoteSocketAddress<SocketAddress>(connectedPhysicalSocket, config),
                                         config->getReadTimeout(),
                                         config->getWriteTimeout(),
                                         config->getReadBlockSize(),
                                         config->getWriteBlockSize(),
                                         config->getTerminateTimeout());
                onConnect(socketConnection);
                onConnected(socketConnection);
            } else if (errno != EINTR && errno != EAGAIN && errno != EWOULDBLOCK) {
                PLOG(TRACE) << config->getInstanceName() << ": accept failed '" << physicalServerSocket.getBindAddress().toString() << "'";
            }
        } while (--acceptsPerTick > 0);
    }
References core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::config, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onConnect, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onConnected, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onDisconnect, and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::physicalServerSocket.
acceptTimeout()
void core::eventreceiver::AcceptEventReceiver::acceptTimeout () private virtual inherited
Definition at line 38 of file AcceptEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
Referenced by core::eventreceiver::AcceptEventReceiver::timeoutEvent().
checkTimeout()
void core::DescriptorEventReceiver::checkTimeout (const utils::Timeval & currentTime) inherited
Definition at line 171 of file DescriptorEventReceiver.cpp.
{
        if (maxInactivity > 0 && currentTime - lastTriggered >= maxInactivity) {
            timeoutEvent();
        }
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), utils::Timeval::operator>(), utils::Timeval::operator>=(), and core::DescriptorEventReceiver::timeoutEvent().
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents().
destruct()
template<typename PhysicalSocketServer , typename Config , template< typename PhysicalSocketServerT > typename SocketConnection> void core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::destruct () final protected virtual
Reimplemented from core::EventReceiver.
Definition at line 251 of file SocketAcceptor.hpp.
{
        delete this;
    }
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent(), and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::unobservedEvent().
disable()
void core::DescriptorEventReceiver::disable () protected inherited
Definition at line 93 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            enabled = false;
            descriptorEventPublisher.disable(this);
            LOG(TRACE) << "EventReceiver: Disable: " << getName() << ": fd = " << observedFd;
        } else {
            LOG(TRACE) << "EventReceiver: Double disable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::disable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), and core::DescriptorEventReceiver::observedFd.
Referenced by core::eventreceiver::AcceptEventReceiver::acceptTimeout(), database::mariadb::MariaDBConnection::commandContinue(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectEvent(), core::eventreceiver::ConnectEventReceiver::connectTimeout(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectTimeout(), core::DescriptorEventPublisher::disable(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::pipe::PipeSource::eof(), core::eventreceiver::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSink::readEvent(), core::eventreceiver::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::socket::stream::SocketWriter::signalEvent(), core::eventreceiver::AcceptEventReceiver::signalEvent(), core::eventreceiver::ConnectEventReceiver::signalEvent(), core::eventreceiver::ExceptionalConditionEventReceiver::signalEvent(), core::eventreceiver::ReadEventReceiver::signalEvent(), core::eventreceiver::WriteEventReceiver::signalEvent(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), core::pipe::PipeSource::writeEvent(), core::eventreceiver::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
dispatchEvent()
void core::eventreceiver::AcceptEventReceiver::dispatchEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 42 of file AcceptEventReceiver.cpp.
{
        acceptEvent();
    }
References core::eventreceiver::AcceptEventReceiver::acceptEvent().
enable()
bool core::DescriptorEventReceiver::enable (int fd) protected inherited
Definition at line 70 of file DescriptorEventReceiver.cpp.
{
        if (core::eventLoopState() != core::State::STOPPING) {
            if (!enabled) {
                observedFd = fd;
                enabled = true;
                descriptorEventPublisher.enable(this);
            } else {
                LOG(TRACE) << "EventReceiver: Double enable: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "EventReceiver: Not enabled: Enable after signal";
        }
        return core::eventLoopState() != core::State::STOPPING;
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::enable(), core::DescriptorEventReceiver::enabled, core::eventLoopState(), core::EventReceiver::getName(), core::DescriptorEventReceiver::observedFd, and core::STOPPING.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::initConnectEvent(), core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
getName() [1/2]
const std::string & core::EventReceiver::getName () const inherited
Definition at line 44 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
getName() [2/2]
const std::string & core::EventReceiver::getName () const inherited
Definition at line 44 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
getRegisteredFd()
int core::DescriptorEventReceiver::getRegisteredFd () const inherited
Definition at line 66 of file DescriptorEventReceiver.cpp.
{
        return observedFd;
    }
References core::DescriptorEventReceiver::observedFd.
Referenced by core::DescriptorEventPublisher::enable(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::select::DescriptorEventPublisher::muxAdd(), core::poll::PollFdsManager::muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOff(), core::select::DescriptorEventPublisher::muxOff(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOn(), core::select::DescriptorEventPublisher::muxOn(), core::socket::stream::legacy::SocketReader::read(), core::pipe::PipeSink::readEvent(), core::socket::stream::legacy::SocketWriter::write(), core::pipe::PipeSource::writeEvent(), core::pipe::PipeSink::~PipeSink(), and core::pipe::PipeSource::~PipeSource().
getTimeout()
utils::Timeval core::DescriptorEventReceiver::getTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 152 of file DescriptorEventReceiver.cpp.
{
        return maxInactivity > 0 ? currentTime > lastTriggered ? maxInactivity - (currentTime - lastTriggered) : 0 : TIMEOUT::MAX;
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::DescriptorEventPublisher::getNextTimeout().
initAcceptEvent()
template<typename PhysicalSocketServer , typename Config , template< typename PhysicalSocketServerT > typename SocketConnection> void core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::initAcceptEvent () override protected virtual
Implements core::eventreceiver::InitAcceptEventReceiver.
Definition at line 131 of file SocketAcceptor.hpp.
{
        if (!config->getDisabled()) {
            try {
                LOG(TRACE) << config->getInstanceName() << ": starting";
                SocketAddress localAddress(config->Local::getSocketAddress());
                core::socket::State state = core::socket::STATE_OK;
                if (physicalServerSocket.open(config->getSocketOptions(), PhysicalServerSocket::Flags::NONBLOCK) < 0) {
                    switch (errno) {
                        case EMFILE:
                        case ENFILE:
                        case ENOBUFS:
                        case ENOMEM:
                            state = core::socket::STATE_ERROR;
                            PLOG(TRACE) << config->getInstanceName() << ": open '" << localAddress.toString() << "'";
                            break;
                        default:
                            state = core::socket::STATE_FATAL;
                            PLOG(TRACE) << config->getInstanceName() << ": open '" << localAddress.toString() << "'";
                            break;
                    }
                } else if (physicalServerSocket.bind(localAddress) < 0) {
                    switch (errno) {
                        case EADDRINUSE:
                            state = core::socket::STATE_ERROR;
                            PLOG(TRACE) << config->getInstanceName() << ": bind '" << localAddress.toString() << "'";
                            break;
                        default:
                            state = core::socket::STATE_FATAL;
                            PLOG(TRACE) << config->getInstanceName() << ": bind '" << localAddress.toString() << "'";
                            break;
                    }
                } else if (physicalServerSocket.listen(config->getBacklog()) < 0) {
                    switch (errno) {
                        case EADDRINUSE:
                            state = core::socket::STATE_ERROR;
                            PLOG(TRACE) << config->getInstanceName() << ": listen '" << localAddress.toString() << "'";
                            break;
                        default:
                            state = core::socket::STATE_FATAL;
                            PLOG(TRACE) << config->getInstanceName() << ": listen '" << localAddress.toString() << "'";
                            break;
                    }
                } else {
                    if (enable(physicalServerSocket.getFd())) {
                        LOG(TRACE) << config->getInstanceName() << ": listen '" << localAddress.toString() << "' success";
                    } else {
                        LOG(TRACE) << config->getInstanceName() << ": Error: not monitored by SNode.C";
                    }
                }
                if (localAddress.useNext()) {
                    LOG(TRACE) << config->getInstanceName() << ": using next SocketAddress '"
                               << config->Local::getSocketAddress().toString() << "'";
                    onStatus(localAddress, (state | core::socket::State::NO_RETRY));
                    useNextSocketAddress();
                } else {
                    onStatus(localAddress, state);
                }
            } catch (const typename SocketAddress::BadSocketAddress& badSocketAddress) {
                LOG(TRACE) << config->getInstanceName() << ": " << badSocketAddress.what();
                onStatus({}, core::socket::STATE(badSocketAddress.getState(), badSocketAddress.getErrnum(), badSocketAddress.what()));
            }
        } else {
            LOG(TRACE) << config->getInstanceName() << ": disabled";
            onStatus({}, core::socket::STATE_DISABLED);
        }
        if (isEnabled()) {
            core::eventreceiver::AcceptEventReceiver::setTimeout(config->getAcceptTimeout());
        } else {
            destruct();
        }
    }
References core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::config, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::destruct(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::isEnabled(), core::socket::State::NO_RETRY, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onStatus, core::socket::State::operator|(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::physicalServerSocket, core::DescriptorEventReceiver::setTimeout(), and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::useNextSocketAddress().
isEnabled()
bool core::DescriptorEventReceiver::isEnabled () const inherited
Definition at line 107 of file DescriptorEventReceiver.cpp.
{
        return enabled;
    }
References core::DescriptorEventReceiver::enabled.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::initConnectEvent(), and core::socket::stream::SocketWriter::sendToPeer().
isSuspended()
bool core::DescriptorEventReceiver::isSuspended () const inherited
Definition at line 138 of file DescriptorEventReceiver.cpp.
{
        return suspended;
    }
References core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::pipe::PipeSource::send().
observed()
void core::Observer::observed () protected inherited
Definition at line 41 of file DescriptorEventReceiver.cpp.
{
        observationCounter++;
    }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setEnabled().
onEvent()
void core::eventreceiver::InitAcceptEventReceiver::onEvent (const utils::Timeval & currentTime) override private virtual inherited
Implements core::EventReceiver.
Definition at line 59 of file AcceptEventReceiver.cpp.
{
        initAcceptEvent();
    }
References core::eventreceiver::InitAcceptEventReceiver::initAcceptEvent().
onSignal()
void core::DescriptorEventReceiver::onSignal (int signum) private inherited
Definition at line 163 of file DescriptorEventReceiver.cpp.
{
        signalEvent(signum);
    }
References core::DescriptorEventReceiver::signalEvent().
Referenced by core::DescriptorEventPublisher::signal().
operator=() [1/2]
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> SocketAcceptor & core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::operator= (const SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT > &) delete
operator=() [2/2]
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> SocketAcceptor & core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::operator= (SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT > &&) delete
relax() [1/2]
void core::EventReceiver::relax () inherited
Definition at line 40 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
relax() [2/2]
void core::EventReceiver::relax () inherited
Definition at line 40 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
resume()
void core::DescriptorEventReceiver::resume () protected inherited
Definition at line 124 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (suspended) {
                suspended = false;
                lastTriggered = utils::Timeval::currentTime();
                descriptorEventPublisher.resume(this);
            } else {
                LOG(TRACE) << "EventReceiver: Double resume: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "EventReceiver: Resume while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::observedFd, utils::Timeval::operator=(), core::DescriptorEventPublisher::resume(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
setDisabled()
void core::DescriptorEventReceiver::setDisabled () private inherited
Definition at line 103 of file DescriptorEventReceiver.cpp.
{
        unObserved();
    }
References core::Observer::unObserved().
setEnabled()
void core::DescriptorEventReceiver::setEnabled (const utils::Timeval & currentTime) private inherited
Definition at line 87 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
        observed();
    }
References core::DescriptorEventReceiver::lastTriggered, core::Observer::observed(), and utils::Timeval::operator=().
Referenced by core::DescriptorEventPublisher::enable().
setTimeout()
void core::DescriptorEventReceiver::setTimeout (const utils::Timeval & timeout) inherited
Definition at line 142 of file DescriptorEventReceiver.cpp.
{
        if (timeout == TIMEOUT::DEFAULT) {
            this->maxInactivity = initialTimeout;
        } else {
            this->maxInactivity = timeout;
        }
        triggered(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::TIMEOUT::DEFAULT, core::DescriptorEventReceiver::initialTimeout, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator=(), utils::Timeval::operator==(), and core::DescriptorEventReceiver::triggered().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::initConnectEvent(), and core::socket::stream::SocketWriter::shutdownWrite().
signalEvent()
void core::eventreceiver::AcceptEventReceiver::signalEvent (int signum) override private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 50 of file AcceptEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
span() [1/2]
void core::EventReceiver::span () inherited
Definition at line 36 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by TowerCalculator::calculate(), database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::FileReader(), core::eventreceiver::InitAcceptEventReceiver::InitAcceptEventReceiver(), core::eventreceiver::InitConnectEventReceiver::InitConnectEventReceiver(), TowerCalculator::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
span() [2/2]
void core::EventReceiver::span () inherited
Definition at line 36 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by TowerCalculator::calculate(), database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::FileReader(), core::eventreceiver::InitAcceptEventReceiver::InitAcceptEventReceiver(), core::eventreceiver::InitConnectEventReceiver::InitConnectEventReceiver(), TowerCalculator::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
suspend()
void core::DescriptorEventReceiver::suspend () protected inherited
Definition at line 111 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!suspended) {
                suspended = true;
                descriptorEventPublisher.suspend(this);
            } else {
                LOG(TRACE) << "EventReceiver: Double suspend: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "EventReceiver: Suspend while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::observedFd, core::DescriptorEventPublisher::suspend(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), and core::pipe::PipeSource::writeEvent().
timeoutEvent()
void core::eventreceiver::AcceptEventReceiver::timeoutEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 46 of file AcceptEventReceiver.cpp.
{
        acceptTimeout();
    }
References core::eventreceiver::AcceptEventReceiver::acceptTimeout().
triggered()
void core::DescriptorEventReceiver::triggered (const utils::Timeval & currentTime) private inherited
Definition at line 167 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
    }
References core::DescriptorEventReceiver::lastTriggered, and utils::Timeval::operator=().
Referenced by core::DescriptorEventReceiver::onEvent(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::DescriptorEventReceiver::setTimeout().
unObserved()
void core::Observer::unObserved () protected inherited
Definition at line 45 of file DescriptorEventReceiver.cpp.
{
        observationCounter--;
        if (observationCounter == 0) {
            unobservedEvent();
        }
    }
References core::Observer::observationCounter, and core::Observer::unobservedEvent().
Referenced by core::DescriptorEventReceiver::setDisabled().
unobservedEvent()
template<typename PhysicalSocketServer , typename Config , template< typename PhysicalSocketServerT > typename SocketConnection> void core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::unobservedEvent () final private virtual
Implements core::Observer.
Definition at line 246 of file SocketAcceptor.hpp.
{
        destruct();
    }
References core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::destruct().
useNextSocketAddress()
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> virtual void core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::useNextSocketAddress () pure virtual
Implemented in core::socket::stream::legacy::SocketAcceptor< PhysicalServerSocketT, ConfigT >, and core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent().
Member Data Documentation
config
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> std::shared_ptr<Config> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::config protected
Definition at line 91 of file SocketAcceptor.h.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::acceptEvent(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor().
descriptorEventPublisher
DescriptorEventPublisher& core::DescriptorEventReceiver::descriptorEventPublisher private inherited
Definition at line 104 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
enabled
bool core::DescriptorEventReceiver::enabled = false private inherited
Definition at line 108 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
event
Event core::EventReceiver::event private inherited
Definition at line 55 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
eventCounter
int core::DescriptorEventReceiver::eventCounter = 0 private inherited
Definition at line 115 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::onEvent().
initialTimeout
const utils::Timeval core::DescriptorEventReceiver::initialTimeout private inherited
Definition at line 113 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), and core::DescriptorEventReceiver::setTimeout().
lastTriggered
utils::Timeval core::DescriptorEventReceiver::lastTriggered private inherited
Definition at line 111 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setEnabled(), and core::DescriptorEventReceiver::triggered().
maxInactivity
utils::Timeval core::DescriptorEventReceiver::maxInactivity private inherited
Definition at line 112 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::getTimeout(), and core::DescriptorEventReceiver::setTimeout().
observationCounter
int core::Observer::observationCounter = 0 private inherited
Definition at line 53 of file DescriptorEventReceiver.h.
Referenced by core::Observer::observed(), and core::Observer::unObserved().
observedFd
int core::DescriptorEventReceiver::observedFd = -1 private inherited
Definition at line 106 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
onConnect
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> std::function<void(SocketConnection*)> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onConnect protected
Definition at line 85 of file SocketAcceptor.h.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::acceptEvent(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor().
onConnected
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> std::function<void(SocketConnection*)> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onConnected protected
Definition at line 86 of file SocketAcceptor.h.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::acceptEvent(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor().
onDisconnect
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> std::function<void(SocketConnection*)> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onDisconnect protected
Definition at line 87 of file SocketAcceptor.h.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::acceptEvent(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor().
onStatus
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> std::function<void(const SocketAddress&, core::socket::State)> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::onStatus = nullptr protected
Definition at line 89 of file SocketAcceptor.h.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor().
physicalServerSocket
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> PhysicalServerSocket core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::physicalServerSocket private
Definition at line 80 of file SocketAcceptor.h.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::acceptEvent(), and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent().
socketContextFactory
template<typename PhysicalSocketServerT , typename ConfigT , template< typename PhysicalSocketServer > typename SocketConnectionT> std::shared_ptr<core::socket::stream::SocketContextFactory> core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::socketContextFactory = nullptr protected
Definition at line 83 of file SocketAcceptor.h.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), and core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor().
suspended
bool core::DescriptorEventReceiver::suspended = false private inherited
Definition at line 109 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
The documentation for this class was generated from the following files:
core/socket/stream/SocketAcceptor.h
core/socket/stream/SocketAcceptor.hpp