SNode.C: core::timer::IntervalTimerStopable Class Reference
core::timer::IntervalTimerStopable Class Reference
#include <IntervalTimerStopable.h>
Public Member Functions
IntervalTimerStopable (const IntervalTimerStopable &)=delete
IntervalTimerStopable & operator= (const IntervalTimerStopable &timer)=delete
void restart ()
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Static Public Member Functions
static void atNextTick (const std::function< void(void)> &callBack)
Protected Member Functions
utils::Timeval getTimeoutAbsolut () const
utils::Timeval getTimeoutRelative (const utils::Timeval &currentTime) const
void enable ()
void update ()
void cancel ()
Private Member Functions
IntervalTimerStopable (const std::function< void(const std::function< void()> &stop)> &dispatcher, const utils::Timeval &timeout, const std::string &name="IntervalTimerStopable")
~IntervalTimerStopable () override=default
void dispatchEvent () final
void unobservedEvent () override
void onEvent (const utils::Timeval &currentTime) final
void setTimer (Timer *timer)
Private Attributes
std::function< void(const std::function< void()> &)> dispatcher = nullptr
TimerEventPublisher & timerEventPublisher
Timer * timer = nullptr
utils::Timeval absoluteTimeout
utils::Timeval delay
Event event
Friends
class Timer
Detailed Description
Definition at line 34 of file IntervalTimerStopable.h.
Constructor & Destructor Documentation
IntervalTimerStopable() [1/2]
core::timer::IntervalTimerStopable::IntervalTimerStopable (const IntervalTimerStopable &) delete
IntervalTimerStopable() [2/2]
core::timer::IntervalTimerStopable::IntervalTimerStopable (const std::function< void(const std::function< void()> &stop)> & dispatcher, const utils::Timeval & timeout, const std::string & name = "IntervalTimerStopable") private
Definition at line 28 of file IntervalTimerStopable.cpp.
        : core::TimerEventReceiver(name, timeout)
        , dispatcher(dispatcher) {
    }
References dispatcher, and core::TimerEventReceiver::TimerEventReceiver().
Referenced by core::timer::Timer::intervalTimer().
Member Function Documentation
atNextTick()
void core::EventReceiver::atNextTick (const std::function< void(void)> & callBack) static inherited
Definition at line 28 of file EventReceiver.cpp.
{
        class NextTickEvent : public core::EventReceiver {
        public:
            explicit NextTickEvent(const std::function<void(void)>& callBack)
                : core::EventReceiver("RequestEvent")
                , callBack(callBack) {
            }
            void onEvent([[maybe_unused]] const utils::Timeval& currentTime) override {
                callBack();
                delete this;
            }
        private:
            std::function<void(void)> callBack;
        };
        (new NextTickEvent(callBack))->span();
    }
References core::EventReceiver::EventReceiver(), and core::EventReceiver::span().
Referenced by web::http::client::SocketContext::dispatchNextRequest(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestSent(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), and core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector().
cancel()
void core::TimerEventReceiver::cancel () protected inherited
Definition at line 77 of file TimerEventReceiver.cpp.
{
        timerEventPublisher.remove(this);
    }
References core::TimerEventPublisher::remove(), and core::TimerEventReceiver::timerEventPublisher.
Referenced by core::Timer::cancel(), dispatchEvent(), and core::timer::SingleshotTimer::dispatchEvent().
destruct()
void core::EventReceiver::destruct () virtual inherited
Reimplemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, and database::mariadb::MariaDBCommandStartEvent.
Definition at line 53 of file EventReceiver.cpp.
{
        delete this;
    }
Referenced by core::EventMultiplexer::EventQueue::clear().
dispatchEvent()
void core::timer::IntervalTimerStopable::dispatchEvent () final private virtual
Implements core::TimerEventReceiver.
Definition at line 35 of file IntervalTimerStopable.cpp.
{
        update();
        dispatcher([this]() -> void {
            cancel();
        });
    }
References core::TimerEventReceiver::cancel(), dispatcher, and core::TimerEventReceiver::update().
enable()
void core::TimerEventReceiver::enable () protected inherited
Definition at line 62 of file TimerEventReceiver.cpp.
{
        if (core::eventLoopState() != core::State::STOPPING) {
            timerEventPublisher.insert(this);
        } else {
            LOG(TRACE) << "TimerEventReceiver - Enable after signal: Not enabled";
            delete this;
        }
    }
References core::eventLoopState(), core::TimerEventPublisher::insert(), core::STOPPING, and core::TimerEventReceiver::timerEventPublisher.
Referenced by core::Timer::Timer().
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 65 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::socket::stream::tls::SocketReader::read(), core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::SocketWriter::shutdownWrite(), core::socket::stream::SocketWriter::streamToPeer(), core::DescriptorEventReceiver::suspend(), and core::socket::stream::tls::SocketWriter::write().
getTimeoutAbsolut()
utils::Timeval core::TimerEventReceiver::getTimeoutAbsolut () const protected inherited
Definition at line 54 of file TimerEventReceiver.cpp.
{
        return absoluteTimeout;
    }
References core::TimerEventReceiver::absoluteTimeout.
Referenced by core::TimerEventReceiver::onEvent(), core::TimerEventPublisher::timernode_lt::operator()(), and core::TimerEventPublisher::spanActiveEvents().
getTimeoutRelative()
utils::Timeval core::TimerEventReceiver::getTimeoutRelative (const utils::Timeval & currentTime) const protected inherited
Definition at line 58 of file TimerEventReceiver.cpp.
{
        return absoluteTimeout > currentTime ? absoluteTimeout - currentTime : 0;
    }
References core::TimerEventReceiver::absoluteTimeout, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::TimerEventPublisher::getNextTimeout().
onEvent()
void core::TimerEventReceiver::onEvent (const utils::Timeval & currentTime) final private virtual inherited
Implements core::EventReceiver.
Definition at line 81 of file TimerEventReceiver.cpp.
{
        LOG(TRACE) << "TimerEventReceiver: Dispatch delta = " << (currentTime - getTimeoutAbsolut()).getMsd() << " ms";
        dispatchEvent();
    }
References core::TimerEventReceiver::dispatchEvent(), utils::Timeval::getMsd(), core::TimerEventReceiver::getTimeoutAbsolut(), and utils::Timeval::operator-().
operator=()
IntervalTimerStopable & core::timer::IntervalTimerStopable::operator= (const IntervalTimerStopable & timer) delete
relax()
void core::EventReceiver::relax () inherited
Definition at line 61 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
restart()
void core::TimerEventReceiver::restart () inherited
Definition at line 42 of file TimerEventReceiver.cpp.
{
        timerEventPublisher.erase(this);
        absoluteTimeout = utils::Timeval::currentTime() + delay;
        timerEventPublisher.insert(this);
    }
References core::TimerEventReceiver::absoluteTimeout, utils::Timeval::currentTime(), core::TimerEventReceiver::delay, core::TimerEventPublisher::erase(), core::TimerEventPublisher::insert(), utils::Timeval::operator+(), utils::Timeval::operator=(), and core::TimerEventReceiver::timerEventPublisher.
Referenced by core::Timer::restart().
setTimer()
void core::TimerEventReceiver::setTimer (Timer * timer) private inherited
Definition at line 87 of file TimerEventReceiver.cpp.
{
        this->timer = timer;
    }
References core::TimerEventReceiver::timer.
Referenced by core::Timer::operator=(), core::Timer::Timer(), core::Timer::Timer(), and core::Timer::~Timer().
span()
void core::EventReceiver::span () inherited
Definition at line 57 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by core::EventReceiver::atNextTick(), database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), core::file::FileReader::start(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
unobservedEvent()
void core::timer::IntervalTimerStopable::unobservedEvent () override private virtual
Implements core::TimerEventReceiver.
Definition at line 43 of file IntervalTimerStopable.cpp.
{
        delete this;
    }
update()
void core::TimerEventReceiver::update () protected inherited
Definition at line 71 of file TimerEventReceiver.cpp.
{
        timerEventPublisher.erase(this);
        absoluteTimeout += delay;
        timerEventPublisher.insert(this);
    }
References core::TimerEventReceiver::absoluteTimeout, core::TimerEventReceiver::delay, core::TimerEventPublisher::erase(), core::TimerEventPublisher::insert(), utils::Timeval::operator+=(), and core::TimerEventReceiver::timerEventPublisher.
Referenced by core::timer::IntervalTimer::dispatchEvent(), and dispatchEvent().
~IntervalTimerStopable()
core::timer::IntervalTimerStopable::~IntervalTimerStopable () override private default
Friends And Related Symbol Documentation
Timer
friend class Timer friend
Definition at line 52 of file IntervalTimerStopable.h.
Member Data Documentation
absoluteTimeout
utils::Timeval core::TimerEventReceiver::absoluteTimeout private inherited
Definition at line 70 of file TimerEventReceiver.h.
Referenced by core::TimerEventReceiver::getTimeoutAbsolut(), core::TimerEventReceiver::getTimeoutRelative(), core::TimerEventReceiver::restart(), core::TimerEventReceiver::TimerEventReceiver(), and core::TimerEventReceiver::update().
delay
utils::Timeval core::TimerEventReceiver::delay private inherited
Definition at line 71 of file TimerEventReceiver.h.
Referenced by core::TimerEventReceiver::restart(), core::TimerEventReceiver::TimerEventReceiver(), and core::TimerEventReceiver::update().
dispatcher
std::function<void(const std::function<void()>&)> core::timer::IntervalTimerStopable::dispatcher = nullptr private
Definition at line 50 of file IntervalTimerStopable.h.
Referenced by dispatchEvent(), and IntervalTimerStopable().
event
Event core::EventReceiver::event private inherited
Definition at line 59 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
timer
Timer* core::TimerEventReceiver::timer = nullptr private inherited
Definition at line 69 of file TimerEventReceiver.h.
Referenced by core::TimerEventReceiver::setTimer(), and core::TimerEventReceiver::~TimerEventReceiver().
timerEventPublisher
TimerEventPublisher& core::TimerEventReceiver::timerEventPublisher private inherited
Definition at line 67 of file TimerEventReceiver.h.
Referenced by core::TimerEventReceiver::cancel(), core::TimerEventReceiver::enable(), core::TimerEventReceiver::restart(), core::TimerEventReceiver::TimerEventReceiver(), and core::TimerEventReceiver::update().
The documentation for this class was generated from the following files:
core/timer/IntervalTimerStopable.h
core/timer/IntervalTimerStopable.cpp