SNode.C: web::http::server::RequestContextBase Class Reference
web::http::server::RequestContextBase Class Reference
#include <RequestContextBase.h>
Public Member Functions
RequestContextBase (web::http::SocketContext *socketContext)
virtual ~RequestContextBase ()
bool switchSocketContext (core::socket::stream::SocketContextFactory *socketContextUpgradeFactory)
void sendToPeer (const char *junk, std::size_t junkLen)
void streamToPeer (core::pipe::Source *source)
void sendToPeerCompleted ()
void close ()
Private Attributes
web::http::SocketContext * socketContext = nullptr
core::socket::stream::SocketContext * socketContextUpgrade = nullptr
Detailed Description
Definition at line 48 of file RequestContextBase.h.
Constructor & Destructor Documentation
RequestContextBase()
web::http::server::RequestContextBase::RequestContextBase (web::http::SocketContext * socketContext) explicit
Definition at line 31 of file RequestContextBase.cpp.
        : socketContext(socketContext) {
    }
References socketContext.
~RequestContextBase()
web::http::server::RequestContextBase::~RequestContextBase () virtual
Definition at line 35 of file RequestContextBase.cpp.
{
    }
Member Function Documentation
close()
void web::http::server::RequestContextBase::close ()
Definition at line 60 of file RequestContextBase.cpp.
{
        socketContext->close();
    }
References core::socket::stream::SocketContext::close(), and socketContext.
Referenced by web::http::server::Response::error(), and web::http::server::Response::sendToPeerCompleted().
sendToPeer()
void web::http::server::RequestContextBase::sendToPeer (const char * junk, std::size_t junkLen)
Definition at line 44 of file RequestContextBase.cpp.
{
        socketContext->sendToPeer(junk, junkLen);
    }
References core::socket::stream::SocketContext::sendToPeer(), and socketContext.
Referenced by web::http::server::Response::sendResponse().
sendToPeerCompleted()
void web::http::server::RequestContextBase::sendToPeerCompleted ()
Definition at line 52 of file RequestContextBase.cpp.
{
        if (socketContextUpgrade != nullptr) {
            socketContext->switchSocketContext(socketContextUpgrade);
        }
        socketContext->sendToPeerCompleted();
    }
References web::http::SocketContext::sendToPeerCompleted(), socketContext, socketContextUpgrade, and core::socket::stream::SocketContext::switchSocketContext().
Referenced by web::http::server::Response::sendToPeerCompleted().
streamToPeer()
void web::http::server::RequestContextBase::streamToPeer (core::pipe::Source * source)
Definition at line 48 of file RequestContextBase.cpp.
{
        socketContext->streamToPeer(source);
    }
References socketContext, and core::socket::stream::SocketContext::streamToPeer().
Referenced by web::http::server::Response::stream().
switchSocketContext()
bool web::http::server::RequestContextBase::switchSocketContext (core::socket::stream::SocketContextFactory * socketContextUpgradeFactory)
Definition at line 38 of file RequestContextBase.cpp.
{
        socketContextUpgrade = socketContextUpgradeFactory->create(socketContext->getSocketConnection());
        return socketContextUpgrade != nullptr;
    }
References core::socket::stream::SocketContextFactory::create(), core::socket::stream::SocketContext::getSocketConnection(), socketContext, and socketContextUpgrade.
Referenced by web::http::server::Response::upgrade().
Member Data Documentation
socketContext
web::http::SocketContext* web::http::server::RequestContextBase::socketContext = nullptr private
Definition at line 62 of file RequestContextBase.h.
Referenced by close(), RequestContextBase(), sendToPeer(), sendToPeerCompleted(), streamToPeer(), and switchSocketContext().
socketContextUpgrade
core::socket::stream::SocketContext* web::http::server::RequestContextBase::socketContextUpgrade = nullptr private
Definition at line 64 of file RequestContextBase.h.
Referenced by sendToPeerCompleted(), and switchSocketContext().
The documentation for this class was generated from the following files:
web/http/server/RequestContextBase.h
web/http/server/RequestContextBase.cpp