SNode.C: core::pipe::Sink Class Reference
core::pipe::Sink Class Reference abstract
#include <Sink.h>
Public Member Functions
Sink (Sink &)=delete
Sink & operator= (Sink &)=delete
Protected Member Functions
Sink ()=default
Sink (Sink &&) noexcept=default
Sink & operator= (Sink &&) noexcept=default
virtual ~Sink ()
bool isStreaming ()
void stop ()
Private Member Functions
void pipe (Source *source)
void streamData (const char *chunk, std::size_t chunkLen)
void streamEof ()
void streamError (int errnum)
void disconnect (const Source *source)
virtual void onSourceConnect (Source *source)=0
virtual void onSourceData (const char *chunk, std::size_t chunkLen)=0
virtual void onSourceEof ()=0
virtual void onSourceError (int errnum)=0
Private Attributes
Source * source = nullptr
Friends
class Source
Detailed Description
Definition at line 57 of file Sink.h.
Constructor & Destructor Documentation
Sink() [1/3]
core::pipe::Sink::Sink (Sink &) delete
Sink() [2/3]
core::pipe::Sink::Sink () protected default
Sink() [3/3]
core::pipe::Sink::Sink (Sink &&) protected default noexcept
~Sink()
core::pipe::Sink::~Sink () protected virtual
Definition at line 52 of file Sink.cpp.
                {
        if (source != nullptr) {
            source->disconnect(this);
        }
    }
References core::pipe::Source::disconnect(), and source.
Member Function Documentation
disconnect()
void core::pipe::Sink::disconnect (const Source * source) private
Definition at line 87 of file Sink.cpp.
{
        if (source == this->source) {
            this->source = nullptr;
        }
    }
References source.
Referenced by core::pipe::Source::disconnect(), and core::pipe::Source::~Source().
isStreaming()
bool core::pipe::Sink::isStreaming () protected
Definition at line 65 of file Sink.cpp.
{
        return source != nullptr;
    }
References source.
Referenced by web::http::client::MasterRequest::~MasterRequest(), and web::http::server::Response::~Response().
onSourceConnect()
virtual void core::pipe::Sink::onSourceConnect (Source * source) private pure virtual
Implemented in web::http::client::MasterRequest, and web::http::server::Response.
Referenced by pipe().
onSourceData()
virtual void core::pipe::Sink::onSourceData (const char * chunk, std::size_t chunkLen) private pure virtual
Implemented in web::http::client::MasterRequest, and web::http::server::Response.
Referenced by streamData().
onSourceEof()
virtual void core::pipe::Sink::onSourceEof () private pure virtual
Implemented in web::http::client::MasterRequest, and web::http::server::Response.
Referenced by streamEof().
onSourceError()
virtual void core::pipe::Sink::onSourceError (int errnum) private pure virtual
Implemented in web::http::client::MasterRequest, and web::http::server::Response.
Referenced by streamError().
operator=() [1/2]
Sink & core::pipe::Sink::operator= (Sink &&) protected default noexcept
operator=() [2/2]
Sink & core::pipe::Sink::operator= (Sink &) delete
pipe()
void core::pipe::Sink::pipe (Source * source) private
Definition at line 58 of file Sink.cpp.
{
        if (source->isOpen())
            this->source = source;
        onSourceConnect(source);
    }
References core::pipe::Source::isOpen(), onSourceConnect(), and source.
Referenced by core::pipe::Source::pipe().
stop()
void core::pipe::Sink::stop () protected
Definition at line 69 of file Sink.cpp.
                    {
        if (source != nullptr) {
            source->disconnect(this);
        }
    }
References core::pipe::Source::disconnect(), and source.
Referenced by web::http::server::Response::disconnect().
streamData()
void core::pipe::Sink::streamData (const char * chunk, std::size_t chunkLen) private
Definition at line 75 of file Sink.cpp.
{
        onSourceData(chunk, chunkLen);
    }
References onSourceData().
Referenced by core::pipe::Source::send().
streamEof()
void core::pipe::Sink::streamEof () private
Definition at line 79 of file Sink.cpp.
{
        onSourceEof();
    }
References onSourceEof().
Referenced by core::pipe::Source::eof().
streamError()
void core::pipe::Sink::streamError (int errnum) private
Definition at line 83 of file Sink.cpp.
{
        onSourceError(errnum);
    }
References onSourceError().
Referenced by core::pipe::Source::error().
Friends And Related Symbol Documentation
Source
friend class Source friend
Definition at line 92 of file Sink.h.
Member Data Documentation
source
Source* core::pipe::Sink::source = nullptr private
Definition at line 90 of file Sink.h.
Referenced by disconnect(), isStreaming(), pipe(), stop(), and ~Sink().
The documentation for this class was generated from the following files:
core/pipe/Sink.h
core/pipe/Sink.cpp