SNode.C: apps::echo::model::EchoSocketContext Class Reference
apps::echo::model::EchoSocketContext Class Reference
#include <EchoSocketContext.h>
Public Types
enum class Role { SERVER , CLIENT }
Public Member Functions
EchoSocketContext (core::socket::stream::SocketConnection *socketConnection, Role role)
void sendToPeer (const char *junk, std::size_t junkLen) const final
void sendToPeer (const std::string &data) const
virtual void sendToPeer (const char *junk, std::size_t junkLen) const=0
void streamToPeer (core::pipe::Source *source) const final
std::size_t readFromPeer (char *junk, std::size_t junklen) const final
void setTimeout (const utils::Timeval &timeout) final
void shutdownRead ()
void shutdownWrite (bool forceClose=false)
void close () override
SocketConnection * getSocketConnection () const
virtual void switchSocketContext (SocketContext *newSocketContext)
Protected Member Functions
void onWriteError (int errnum) override
void onReadError (int errnum) override
Private Types
using Super = core::socket::SocketContext
Private Member Functions
void onConnected () override
void onDisconnected () override
bool onSignal (int signum) override
std::size_t onReceivedFromPeer () override
Private Attributes
Role role
core::socket::stream::SocketConnection * socketConnection
Detailed Description
Definition at line 38 of file EchoSocketContext.h.
Member Typedef Documentation
Super
using core::socket::stream::SocketContext::Super = core::socket::SocketContext private inherited
Definition at line 48 of file SocketContext.h.
Member Enumeration Documentation
Role
enum class apps::echo::model::EchoSocketContext::Role strong
Enumerator
SERVER
CLIENT
Definition at line 40 of file EchoSocketContext.h.
{ SERVER, CLIENT };
Constructor & Destructor Documentation
EchoSocketContext()
apps::echo::model::EchoSocketContext::EchoSocketContext (core::socket::stream::SocketConnection * socketConnection, Role role) explicit
Definition at line 32 of file EchoSocketContext.cpp.
        : core::socket::stream::SocketContext(socketConnection)
        , role(role) {
    }
References role, and core::socket::stream::SocketContext::SocketContext().
Referenced by apps::echo::model::EchoServerSocketContextFactory::create(), and apps::echo::model::EchoClientSocketContextFactory::create().
Member Function Documentation
close()
void core::socket::stream::SocketContext::close () override virtual inherited
Implements core::socket::SocketContext.
Reimplemented in iot::mqtt::SocketContext.
Definition at line 58 of file SocketContext.cpp.
{
        socketConnection->close();
    }
References core::socket::stream::SocketConnection::close(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::server::RequestContextBase::close(), iot::mqtt::SocketContext::close(), web::http::client::Request::enqueue(), iot::mqtt_fast::SocketContext::onReceivedFromPeer(), web::http::client::Request::upgrade(), and web::http::client::Response::upgrade().
getSocketConnection()
SocketConnection * core::socket::stream::SocketContext::getSocketConnection () const inherited
Definition at line 38 of file SocketContext.cpp.
{
        return socketConnection;
    }
References core::socket::stream::SocketContext::socketConnection.
Referenced by iot::mqtt::SocketContext::getSocketConnection(), web::http::client::SocketContext< RequestT, ResponseT >::onConnected(), web::http::server::SocketContext< RequestT, ResponseT >::onConnected(), web::http::server::SocketContext< RequestT, ResponseT >::onDisconnected(), web::http::server::SocketContext< RequestT, ResponseT >::onSignal(), web::http::server::RequestContextBase::switchSocketContext(), and web::http::client::Response::upgrade().
onConnected()
void apps::echo::model::EchoSocketContext::onConnected () override private virtual
Implements core::socket::stream::SocketContext.
Definition at line 37 of file EchoSocketContext.cpp.
{
        VLOG(0) << "Echo connected";
        if (role == Role::CLIENT) {
            // sendToPeer("Hello peer! Nice to see you!!!");
        }
    }
References CLIENT, and role.
onDisconnected()
void apps::echo::model::EchoSocketContext::onDisconnected () override private virtual
Implements core::socket::stream::SocketContext.
Definition at line 45 of file EchoSocketContext.cpp.
{
        VLOG(0) << "Echo disconnected";
    }
onReadError()
void core::socket::stream::SocketContext::onReadError (int errnum) override protected virtual inherited
Implements core::socket::SocketContext.
Definition at line 74 of file SocketContext.cpp.
{
        shutdownWrite();
    }
References core::socket::stream::SocketContext::shutdownWrite().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReadError(), and SimpleSocketProtocol::onReadError().
onReceivedFromPeer()
std::size_t apps::echo::model::EchoSocketContext::onReceivedFromPeer () override private virtual
Implements core::socket::SocketContext.
Definition at line 53 of file EchoSocketContext.cpp.
{
        char junk[4096];
        const std::size_t junklen = readFromPeer(junk, 4096);
        if (junklen > 0) {
            VLOG(0) << "Data to reflect: " << std::string(junk, junklen);
            sendToPeer(junk, junklen);
        }
        return junklen;
    }
References core::socket::stream::SocketContext::readFromPeer(), and core::socket::stream::SocketContext::sendToPeer().
onSignal()
bool apps::echo::model::EchoSocketContext::onSignal (int signum) override private virtual
Implements core::socket::SocketContext.
Definition at line 49 of file EchoSocketContext.cpp.
{
        return true;
    }
onWriteError()
void core::socket::stream::SocketContext::onWriteError (int errnum) override protected virtual inherited
Implements core::socket::SocketContext.
Definition at line 70 of file SocketContext.cpp.
{
        shutdownRead();
    }
References core::socket::stream::SocketContext::shutdownRead().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onWriteError(), and SimpleSocketProtocol::onWriteError().
readFromPeer()
std::size_t core::socket::stream::SocketContext::readFromPeer (char * junk, std::size_t junklen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 50 of file SocketContext.cpp.
{
        return socketConnection->readFromPeer(junk, junklen);
    }
References core::socket::stream::SocketConnection::readFromPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by onReceivedFromPeer(), web::http::Parser::readContent(), web::http::Parser::readHeaderLine(), web::http::Parser::readStartLine(), and iot::mqtt::SocketContext::recv().
sendToPeer() [1/3]
void core::socket::stream::SocketContext::sendToPeer (const char * junk, std::size_t junkLen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 42 of file SocketContext.cpp.
{
        socketConnection->sendToPeer(junk, junkLen);
    }
References core::socket::stream::SocketConnection::sendToPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::Request::enqueue(), onReceivedFromPeer(), iot::mqtt::SocketContext::send(), iot::mqtt_fast::SocketContext::send(), and web::http::server::RequestContextBase::sendToPeer().
sendToPeer() [2/3]
virtual void core::socket::SocketContext::sendToPeer (const char * junk, std::size_t junkLen) const virtual inherited
Implements core::socket::SocketContext.
sendToPeer() [3/3]
void core::socket::SocketContext::sendToPeer (const std::string & data) const inherited
Definition at line 55 of file SocketContext.cpp.
{
        sendToPeer(data.data(), data.length());
    }
setTimeout()
void core::socket::stream::SocketContext::setTimeout (const utils::Timeval & timeout) final virtual inherited
Implements core::socket::SocketContext.
Definition at line 54 of file SocketContext.cpp.
{
        socketConnection->setTimeout(timeout);
    }
References core::socket::stream::SocketConnection::setTimeout(), and core::socket::stream::SocketContext::socketConnection.
shutdownRead()
void core::socket::stream::SocketContext::shutdownRead () inherited
Definition at line 62 of file SocketContext.cpp.
{
        socketConnection->shutdownRead();
    }
References core::socket::stream::SocketConnection::shutdownRead(), and core::socket::stream::SocketContext::socketConnection.
Referenced by SimpleSocketProtocol::onWriteError(), and core::socket::stream::SocketContext::onWriteError().
shutdownWrite()
void core::socket::stream::SocketContext::shutdownWrite (bool forceClose = false) inherited
Definition at line 66 of file SocketContext.cpp.
{
        socketConnection->shutdownWrite(forceClose);
    }
References core::socket::stream::SocketConnection::shutdownWrite(), and core::socket::stream::SocketContext::socketConnection.
Referenced by iot::mqtt::SocketContext::end(), SimpleSocketProtocol::onReadError(), core::socket::stream::SocketContext::onReadError(), web::http::server::SocketContext< RequestT, ResponseT >::requestParsed(), and web::http::server::SocketContext< RequestT, ResponseT >::sendToPeerCompleted().
streamToPeer()
void core::socket::stream::SocketContext::streamToPeer (core::pipe::Source * source) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 46 of file SocketContext.cpp.
{
        socketConnection->streamToPeer(source);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::streamToPeer().
Referenced by web::http::server::RequestContextBase::streamToPeer().
switchSocketContext()
void core::socket::stream::SocketContext::switchSocketContext (SocketContext * newSocketContext) virtual inherited
Definition at line 34 of file SocketContext.cpp.
{
        socketConnection->switchSocketContext(newSocketContext);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::switchSocketContext().
Referenced by web::http::server::RequestContextBase::sendToPeerCompleted(), and web::http::client::Response::upgrade().
Member Data Documentation
role
Role apps::echo::model::EchoSocketContext::role private
Definition at line 52 of file EchoSocketContext.h.
Referenced by EchoSocketContext(), and onConnected().
socketConnection
core::socket::stream::SocketConnection* core::socket::stream::SocketContext::socketConnection private inherited
Definition at line 77 of file SocketContext.h.
Referenced by core::socket::stream::SocketContext::close(), core::socket::stream::SocketContext::getSocketConnection(), core::socket::stream::SocketContext::readFromPeer(), core::socket::stream::SocketContext::sendToPeer(), core::socket::stream::SocketContext::setTimeout(), core::socket::stream::SocketContext::shutdownRead(), core::socket::stream::SocketContext::shutdownWrite(), core::socket::stream::SocketContext::SocketContext(), core::socket::stream::SocketContext::streamToPeer(), and core::socket::stream::SocketContext::switchSocketContext().
The documentation for this class was generated from the following files:
apps/echo/model/EchoSocketContext.h
apps/echo/model/EchoSocketContext.cpp