SNode.C: web::http::client::SocketContextUpgradeFactorySelector Class Reference
web::http::client::SocketContextUpgradeFactorySelector Class Reference
#include <SocketContextUpgradeFactorySelector.h>
Public Member Functions
SocketContextUpgradeFactory * select (const std::string &upgradeContextName, Request &req)
SocketContextUpgradeFactory * select (Request &req, Response &res) override
Public Member Functions inherited from web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >
virtual SocketContextUpgradeFactory * select (Request &req, Response &res)=0
bool add (SocketContextUpgradeFactory *socketContextUpgradeFactory)
void link (const std::string &upgradeContextName, SocketContextUpgradeFactory *(*linkedPlugin)())
void allowDlOpen ()
void unload (SocketContextUpgradeFactory *socketContextUpgradeFactory)
Static Public Member Functions
static SocketContextUpgradeFactorySelector * instance ()
Private Types
using Super = web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >
Private Member Functions
SocketContextUpgradeFactory * load (const std::string &socketContextUpgradeName) override
Additional Inherited Members
Public Types inherited from web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >
using SocketContextUpgradeFactory = SocketContextUpgradeFactory
using Request = typename SocketContextUpgradeFactory::Request
using Response = typename SocketContextUpgradeFactory::Response
Protected Types inherited from web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >
using SocketContextUpgrade = web::http::SocketContextUpgrade< Request, Response >
Protected Member Functions inherited from web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >
SocketContextUpgradeFactorySelector ()=default
virtual ~SocketContextUpgradeFactorySelector ()=default
SocketContextUpgradeFactory * select (const std::string &socketContextUpgradeName)
bool add (SocketContextUpgradeFactory *socketContextUpgradeFactory, void *handler)
SocketContextUpgradeFactory * load (const std::string &socketContextUpgradeName, const std::string &socketContextUpgradeFactoryLibraryFile, const std::string &socketContextUpgradeFactoryFunctionName)
Detailed Description
Definition at line 35 of file SocketContextUpgradeFactorySelector.h.
Member Typedef Documentation
Super
using web::http::client::SocketContextUpgradeFactorySelector::Super = web::http::SocketContextUpgradeFactorySelector<SocketContextUpgradeFactory> private
Definition at line 37 of file SocketContextUpgradeFactorySelector.h.
Member Function Documentation
instance()
SocketContextUpgradeFactorySelector * web::http::client::SocketContextUpgradeFactorySelector::instance () static
Definition at line 56 of file SocketContextUpgradeFactorySelector.cpp.
{
        static SocketContextUpgradeFactorySelector socketContextUpgradeFactorySelector;
        return &socketContextUpgradeFactorySelector;
    }
Referenced by web::http::client::SocketContextUpgradeFactory::checkRefCount(), web::http::client::SocketContextUpgradeFactory::link(), web::http::client::Request::upgrade(), and web::http::client::Response::upgrade().
load()
SocketContextUpgradeFactorySelector::SocketContextUpgradeFactory * web::http::client::SocketContextUpgradeFactorySelector::load (const std::string & socketContextUpgradeName) override private virtual
Implements web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >.
Definition at line 38 of file SocketContextUpgradeFactorySelector.cpp.
{
        std::string socketContextUpgradeFactoryLibraryFile = socketContextUpgradeName + "-client.so." SOVERSION;
        std::string socketContextUpgradeFactoryFunctionName = socketContextUpgradeName + "ClientContextUpgradeFactory";
        std::string httpUpgradeInstallLibdir = HTTP_UPGRADE_INSTALL_LIBDIR;
#if !defined(NDEBUG)
        if (const char* httpUpgradeInstallLibdirEnv = std::getenv("HTTP_UPGRADE_INSTALL_LIBDIR")) {
            LOG(WARNING) << "Overriding http upgrade library dir";
            httpUpgradeInstallLibdir = std::string(httpUpgradeInstallLibdirEnv);
        }
#endif
        return Super::load(socketContextUpgradeName,
                           httpUpgradeInstallLibdir + "/libsnodec-" + socketContextUpgradeFactoryLibraryFile,
                           socketContextUpgradeFactoryFunctionName);
    }
References web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::load().
select() [1/2]
SocketContextUpgradeFactory * web::http::client::SocketContextUpgradeFactorySelector::select (const std::string & upgradeContextName, Request & req)
Definition at line 62 of file SocketContextUpgradeFactorySelector.cpp.
{
        SocketContextUpgradeFactory* socketContextUpgradeFactory = select(upgradeContextName);
        if (socketContextUpgradeFactory != nullptr) {
            socketContextUpgradeFactory->prepare(req); // Fill in the missing header fields into the request object
        }
        return socketContextUpgradeFactory;
    }
References web::http::client::SocketContextUpgradeFactory::prepare(), and web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::select().
Referenced by web::http::client::Request::upgrade().
select() [2/2]
SocketContextUpgradeFactory * web::http::client::SocketContextUpgradeFactorySelector::select (Request & req, Response & res) override
Definition at line 72 of file SocketContextUpgradeFactorySelector.cpp.
{
        SocketContextUpgradeFactory* socketContextUpgradeFactory = nullptr;
        std::string upgradeContextName = res.header("upgrade");
        if (!upgradeContextName.empty()) {
            httputils::to_lower(upgradeContextName);
            socketContextUpgradeFactory = select(upgradeContextName);
            if (socketContextUpgradeFactory != nullptr) {
                socketContextUpgradeFactory->web::http::SocketContextUpgradeFactory<Request, Response>::prepare(
                    req, res); // Fill in the missing header fields into the request object
            }
        }
        return socketContextUpgradeFactory;
    }
References web::http::client::Response::header(), web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::prepare(), web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::select(), and httputils::to_lower().
Referenced by web::http::client::Response::upgrade().
The documentation for this class was generated from the following files:
web/http/client/SocketContextUpgradeFactorySelector.h
web/http/client/SocketContextUpgradeFactorySelector.cpp