SNode.C: core::multiplexer::select::EventMultiplexer Class Reference
core::multiplexer::select::EventMultiplexer Class Reference
#include <EventMultiplexer.h>
Public Member Functions
EventMultiplexer ()
~EventMultiplexer () override=default
Public Member Functions inherited from core::EventMultiplexer
EventMultiplexer (DescriptorEventPublisher *readDescriptorEventPublisher, DescriptorEventPublisher *writeDescriptorEventPublisher, DescriptorEventPublisher *exceptionDescriptorEventPublisher)
EventMultiplexer (const EventMultiplexer &)=delete
EventMultiplexer & operator= (const EventMultiplexer &)=delete
DescriptorEventPublisher & getDescriptorEventPublisher (DISP_TYPE dispType)
TimerEventPublisher & getTimerEventPublisher ()
void span (core::Event *event)
void relax (core::Event *event)
void signal (int sigNum)
void terminate ()
void clearEventQueue ()
TickStatus tick (const utils::Timeval &tickTimeOut, const sigset_t &sigMask)
Private Member Functions
int monitorDescriptors (utils::Timeval &tickTimeOut, const sigset_t &sigMask) override
void spanActiveEvents (int activeDescriptorCount) override
Private Attributes
FdSet fdSets [3]
Additional Inherited Members
Public Types inherited from core::EventMultiplexer
enum DISP_TYPE { RD = 0 , WR = 1 , EX = 2 }
Protected Member Functions inherited from core::EventMultiplexer
int maxFd ()
Protected Attributes inherited from core::EventMultiplexer
std::array< DescriptorEventPublisher *, 3 > descriptorEventPublishers
Detailed Description
Definition at line 34 of file EventMultiplexer.h.
Constructor & Destructor Documentation
EventMultiplexer()
core::multiplexer::select::EventMultiplexer::EventMultiplexer ()
Definition at line 41 of file EventMultiplexer.cpp.
        : core::EventMultiplexer(new core::multiplexer::select::DescriptorEventPublisher("READ", //
                                                                                         fdSets[core::EventMultiplexer::DISP_TYPE::RD]),
                                 new core::multiplexer::select::DescriptorEventPublisher("WRITE", //
                                                                                         fdSets[core::EventMultiplexer::DISP_TYPE::WR]),
                                 new core::multiplexer::select::DescriptorEventPublisher("EXCEPT", //
                                                                                         fdSets[core::EventMultiplexer::DISP_TYPE::EX])) {
        LOG(DEBUG) << "Core::multiplexer: select";
    }
References EventMultiplexer().
Referenced by EventMultiplexer().
~EventMultiplexer()
core::multiplexer::select::EventMultiplexer::~EventMultiplexer () override virtual default
Reimplemented from core::EventMultiplexer.
Member Function Documentation
monitorDescriptors()
int core::multiplexer::select::EventMultiplexer::monitorDescriptors (utils::Timeval & tickTimeOut, const sigset_t & sigMask) override private virtual
Implements core::EventMultiplexer.
Definition at line 51 of file EventMultiplexer.cpp.
{
        const timespec timeSpec = tickTimeOut.getTimespec();
        return core::system::pselect(maxFd() + 1,
                                     &fdSets[core::EventMultiplexer::DISP_TYPE::RD].get(),
                                     &fdSets[core::EventMultiplexer::DISP_TYPE::WR].get(),
                                     &fdSets[core::EventMultiplexer::DISP_TYPE::EX].get(),
                                     &timeSpec,
                                     &sigMask);
    }
References core::EventMultiplexer::EX, fdSets, core::multiplexer::select::FdSet::get(), utils::Timeval::getTimespec(), core::EventMultiplexer::maxFd(), core::system::pselect(), core::EventMultiplexer::RD, and core::EventMultiplexer::WR.
spanActiveEvents()
void core::multiplexer::select::EventMultiplexer::spanActiveEvents (int activeDescriptorCount) override private virtual
Implements core::EventMultiplexer.
Definition at line 62 of file EventMultiplexer.cpp.
{
        if (activeDescriptorCount > 0) {
            for (core::DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
                descriptorEventPublisher->spanActiveEvents();
            }
        }
    }
Member Data Documentation
fdSets
FdSet core::multiplexer::select::EventMultiplexer::fdSets[3] private
Definition at line 43 of file EventMultiplexer.h.
Referenced by monitorDescriptors().
The documentation for this class was generated from the following files:
src/core/multiplexer/select/EventMultiplexer.h
src/core/multiplexer/select/EventMultiplexer.cpp