SNode.C: net::rc::stream::config::ConfigSocketClient Class Reference
net::rc::stream::config::ConfigSocketClient Class Reference
#include <ConfigSocketClient.h>
Protected Member Functions
ConfigSocketClient (net::config::ConfigInstance *instance)
~ConfigSocketClient () override
Protected Member Functions inherited from net::config::stream::ConfigSocketClient< net::rc::config::ConfigAddress >
ConfigSocketClient (net::config::ConfigInstance *instance)
Protected Member Functions inherited from net::rc::config::ConfigAddress< net::config::ConfigAddressRemote >
ConfigAddress (net::config::ConfigInstance *instance, const std::string &addressOptionName, const std::string &addressOptionDescription)
ConfigAddress & setBtAddressRequired (bool required=true)
ConfigAddress & setChannelRequired (bool required=true)
Protected Member Functions inherited from net::config::ConfigAddress< net::rc::SocketAddress >
ConfigAddress (ConfigInstance *instance, const std::string &addressOptionName, const std::string &addressOptionDescription)
~ConfigAddress () override
Protected Member Functions inherited from net::config::ConfigAddressBase< net::rc::SocketAddress >
ConfigAddressBase (ConfigInstance *instance, const std::string &addressOptionName="", const std::string &addressOptionDescription="")
virtual ~ConfigAddressBase ()=default
Protected Member Functions inherited from net::config::ConfigSection
ConfigSection (ConfigInstance *instance, const std::string &name, const std::string &description)
ConfigSection (const ConfigSection &)=delete
ConfigSection (ConfigSection &&)=delete
ConfigSection & operator= (const ConfigSection &)=delete
ConfigSection & operator= (ConfigSection &&)=delete
CLI::Option * addOption (const std::string &name, const std::string &description)
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
template<typename ValueType>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
Protected Member Functions inherited from net::rc::config::ConfigAddress< net::config::ConfigAddressLocal >
ConfigAddress (net::config::ConfigInstance *instance, const std::string &addressOptionName, const std::string &addressOptionDescription)
ConfigAddress & setBtAddressRequired (bool required=true)
ConfigAddress & setChannelRequired (bool required=true)
Protected Member Functions inherited from net::config::ConfigConnection
ConfigConnection (ConfigInstance *instance)
Protected Member Functions inherited from net::config::ConfigPhysicalSocketClient
ConfigPhysicalSocketClient (ConfigInstance *instance)
Protected Member Functions inherited from net::config::ConfigPhysicalSocket
ConfigPhysicalSocket (ConfigInstance *instance)
CLI::Option * addSocketOption (const std::string &name, int optLevel, int optName, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Additional Inherited Members
Public Types inherited from net::config::stream::ConfigSocketClient< net::rc::config::ConfigAddress >
using Remote
using Local
Public Types inherited from net::config::ConfigConnection
using Connection = ConfigConnection
Public Types inherited from net::config::ConfigPhysicalSocketClient
using Socket = ConfigPhysicalSocketClient
Public Member Functions inherited from net::rc::config::ConfigAddress< net::config::ConfigAddressRemote >
ConfigAddress & setSocketAddress (const SocketAddress &socketAddress)
ConfigAddress & setBtAddress (const std::string &btAddress)
std::string getBtAddress () const
ConfigAddress & setChannel (uint8_t channel)
uint8_t getChannel () const
Public Member Functions inherited from net::config::ConfigAddress< net::rc::SocketAddress >
net::rc::SocketAddress getSocketAddress (const typename net::rc::SocketAddress::SockAddr &sockAddr, typename net::rc::SocketAddress::SockLen sockAddrLen)
void renew ()
Public Member Functions inherited from net::config::ConfigAddressBase< net::rc::SocketAddress >
net::rc::SocketAddress getSocketAddress (const typename net::rc::SocketAddress::SockAddr &sockAddr, typename net::rc::SocketAddress::SockLen sockAddrLen)
Public Member Functions inherited from net::rc::config::ConfigAddress< net::config::ConfigAddressLocal >
ConfigAddress & setSocketAddress (const SocketAddress &socketAddress)
ConfigAddress & setBtAddress (const std::string &btAddress)
std::string getBtAddress () const
ConfigAddress & setChannel (uint8_t channel)
uint8_t getChannel () const
Public Member Functions inherited from net::config::ConfigConnection
utils::Timeval getReadTimeout () const
ConfigConnection & setReadTimeout (const utils::Timeval &newReadTimeoutSet)
utils::Timeval getWriteTimeout () const
ConfigConnection & setWriteTimeout (const utils::Timeval &newWriteTimeoutSet)
std::size_t getReadBlockSize () const
ConfigConnection & setReadBlockSize (std::size_t newReadBlockSize)
std::size_t getWriteBlockSize () const
ConfigConnection & setWriteBlockSize (std::size_t newWriteBlockSize)
utils::Timeval getTerminateTimeout () const
ConfigConnection & setTerminateTimeout (const utils::Timeval &newTerminateTimeout)
Public Member Functions inherited from net::config::ConfigPhysicalSocketClient
ConfigPhysicalSocketClient & setReconnect (bool reconnect=true)
bool getReconnect () const
ConfigPhysicalSocketClient & setReconnectTime (double time)
double getReconnectTime () const
ConfigPhysicalSocketClient & setConnectTimeout (const utils::Timeval &connectTimeout)
utils::Timeval getConnectTimeout () const
Public Member Functions inherited from net::config::ConfigPhysicalSocket
const std::map< int, std::map< int, net::phy::PhysicalSocketOption > > & getSocketOptions ()
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, int optValue)
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, const std::string &optValue)
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, const std::vector< char > &optValue)
ConfigPhysicalSocket & removeSocketOption (int optLevel, int optName)
ConfigPhysicalSocket & setRetry (bool retry=true)
bool getRetry () const
ConfigPhysicalSocket & setRetryOnFatal (bool retry=true)
bool getRetryOnFatal () const
ConfigPhysicalSocket & setRetryTimeout (double sec)
double getRetryTimeout () const
ConfigPhysicalSocket & setRetryTries (unsigned int tries=0)
unsigned int getRetryTries () const
ConfigPhysicalSocket & setRetryBase (double base)
double getRetryBase () const
ConfigPhysicalSocket & setRetryLimit (unsigned int limit)
unsigned int getRetryLimit () const
ConfigPhysicalSocket & setRetryJitter (double percent)
double getRetryJitter () const
Protected Attributes inherited from net::rc::config::ConfigAddress< net::config::ConfigAddressRemote >
CLI::Option * btAddressOpt
CLI::Option * channelOpt
Protected Attributes inherited from net::config::ConfigSection
CLI::App * section = nullptr
Protected Attributes inherited from net::rc::config::ConfigAddress< net::config::ConfigAddressLocal >
CLI::Option * btAddressOpt
CLI::Option * channelOpt
Detailed Description
Definition at line 58 of file ConfigSocketClient.h.
Constructor & Destructor Documentation
ConfigSocketClient()
net::rc::stream::config::ConfigSocketClient::ConfigSocketClient (net::config::ConfigInstance * instance) explicit protected
Definition at line 69 of file ConfigSocketClient.cpp.
        : net::config::stream::ConfigSocketClient<net::rc::config::ConfigAddress>(instance) {
        net::rc::config::ConfigAddress<net::config::ConfigAddressRemote>::setBtAddressRequired();
        net::rc::config::ConfigAddress<net::config::ConfigAddressRemote>::setChannelRequired();
        net::rc::config::ConfigAddress<net::config::ConfigAddressRemote>::channelOpt //
            ->check(CLI::Range(1, 30));
        net::rc::config::ConfigAddress<net::config::ConfigAddressLocal>::channelOpt //
            ->default_val(0)
            ->check(CLI::Range(0, 30));
    }
References net::config::stream::ConfigSocketClient< ConfigAddressLocalT, ConfigAddressRemoteT >::ConfigSocketClient(), net::rc::config::ConfigAddress< ConfigAddressTypeT >::setBtAddressRequired(), and net::rc::config::ConfigAddress< ConfigAddressTypeT >::setChannelRequired().
~ConfigSocketClient()
net::rc::stream::config::ConfigSocketClient::~ConfigSocketClient () override protected
Definition at line 81 of file ConfigSocketClient.cpp.
{
    }
The documentation for this class was generated from the following files:
net/rc/stream/config/ConfigSocketClient.h
net/rc/stream/config/ConfigSocketClient.cpp