SNode.C: CallForVersion Class Reference
CallForVersion Class Reference
Errors
-v or –version on command line
#include <CLI11.hpp>
Public Member Functions
CallForVersion (std::string msg, ExitCodes exit_code)
CallForVersion (std::string msg, int exit_code)
CallForVersion ()
Public Member Functions inherited from Success
Success (std::string msg, ExitCodes exit_code)
Success (std::string msg, int exit_code)
Success ()
Public Member Functions inherited from ParseError
ParseError (std::string msg, ExitCodes exit_code)
ParseError (std::string msg, int exit_code)
Public Member Functions inherited from Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Protected Member Functions
CallForVersion (std::string ename, std::string msg, int exit_code)
CallForVersion (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from Success
Success (std::string ename, std::string msg, int exit_code)
Success (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from ParseError
ParseError (std::string ename, std::string msg, int exit_code)
ParseError (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
-v or –version on command line
Definition at line 1178 of file CLI11.hpp.
Constructor & Destructor Documentation
CallForVersion() [1/5]
CallForVersion::CallForVersion (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 1179 of file CLI11.hpp.
Referenced by App::set_version_flag().
CallForVersion() [2/5]
CallForVersion::CallForVersion (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 1179 of file CLI11.hpp.
CallForVersion() [3/5]
CallForVersion::CallForVersion (std::string msg, ExitCodes exit_code) inline
Definition at line 1179 of file CLI11.hpp.
CallForVersion() [4/5]
CallForVersion::CallForVersion (std::string msg, int exit_code) inline
Definition at line 1179 of file CLI11.hpp.
CallForVersion() [5/5]
CallForVersion::CallForVersion () inline
Definition at line 1180 of file CLI11.hpp.
            : CallForVersion("This should be caught in your main function, see examples", ExitCodes::Success) {
        }
References CallForVersion().
Referenced by CallForVersion().
The documentation for this class was generated from the following file:
src/utils/CLI11.hpp