SNode.C: core::eventreceiver::ConnectEventReceiver Class Reference
core::eventreceiver::ConnectEventReceiver Class Reference abstract
#include <ConnectEventReceiver.h>
Public Member Functions
int getRegisteredFd () const
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Static Public Member Functions
static void atNextTick (const std::function< void(void)> &callBack)
Protected Member Functions
ConnectEventReceiver (const std::string &name, const utils::Timeval &timeout)
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
void observed ()
void unObserved ()
virtual void unobservedEvent ()=0
Private Member Functions
virtual void connectEvent ()=0
virtual void connectTimeout ()
void dispatchEvent () final
void timeoutEvent () final
void signalEvent (int signum) override
void onEvent (const utils::Timeval &currentTime) final
void onSignal (int signum)
void triggered (const utils::Timeval &currentTime)
void setEnabled (const utils::Timeval &currentTime)
void setDisabled ()
Private Attributes
DescriptorEventPublisher & descriptorEventPublisher
int observedFd = -1
bool enabled = false
bool suspended = false
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
int observationCounter = 0
Event event
Detailed Description
Definition at line 35 of file ConnectEventReceiver.h.
Constructor & Destructor Documentation
ConnectEventReceiver()
core::eventreceiver::ConnectEventReceiver::ConnectEventReceiver (const std::string & name, const utils::Timeval & timeout) protected
Definition at line 31 of file ConnectEventReceiver.cpp.
        : core::DescriptorEventReceiver(
              name + " connect",
              core::EventLoop::instance().getEventMultiplexer().getDescriptorEventPublisher(core::EventMultiplexer::DISP_TYPE::WR),
              timeout) {
    }
References core::DescriptorEventReceiver::DescriptorEventReceiver(), core::EventMultiplexer::getDescriptorEventPublisher(), core::EventLoop::getEventMultiplexer(), core::EventLoop::instance(), and core::EventMultiplexer::WR.
Member Function Documentation
atNextTick()
void core::EventReceiver::atNextTick (const std::function< void(void)> & callBack) static inherited
Definition at line 28 of file EventReceiver.cpp.
{
        class NextTickEvent : public core::EventReceiver {
        public:
            explicit NextTickEvent(const std::function<void(void)>& callBack)
                : core::EventReceiver("RequestEvent")
                , callBack(callBack) {
            }
            void onEvent([[maybe_unused]] const utils::Timeval& currentTime) override {
                callBack();
                delete this;
            }
        private:
            std::function<void(void)> callBack;
        };
        (new NextTickEvent(callBack))->span();
    }
References core::EventReceiver::EventReceiver(), and core::EventReceiver::span().
Referenced by web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestSendError(), web::http::client::SocketContext::requestSent(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), and core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector().
checkTimeout()
void core::DescriptorEventReceiver::checkTimeout (const utils::Timeval & currentTime) inherited
Definition at line 171 of file DescriptorEventReceiver.cpp.
{
        if (maxInactivity > 0 && currentTime - lastTriggered >= maxInactivity) {
            timeoutEvent();
        }
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), utils::Timeval::operator>(), utils::Timeval::operator>=(), and core::DescriptorEventReceiver::timeoutEvent().
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents().
connectEvent()
virtual void core::eventreceiver::ConnectEventReceiver::connectEvent () private pure virtual
Implemented in core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, and core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >.
Referenced by dispatchEvent().
connectTimeout()
void core::eventreceiver::ConnectEventReceiver::connectTimeout () private virtual
Reimplemented in core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, and core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >.
Definition at line 38 of file ConnectEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
Referenced by timeoutEvent().
destruct()
void core::EventReceiver::destruct () virtual inherited
Reimplemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, and database::mariadb::MariaDBCommandStartEvent.
Definition at line 53 of file EventReceiver.cpp.
{
        delete this;
    }
Referenced by core::EventMultiplexer::EventQueue::clear().
disable()
void core::DescriptorEventReceiver::disable () protected inherited
Definition at line 93 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            enabled = false;
            descriptorEventPublisher.disable(this);
            LOG(TRACE) << getName() << " (" << observedFd << "): Disabled";
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Double disable";
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::disable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), and core::DescriptorEventReceiver::observedFd.
Referenced by core::eventreceiver::AcceptEventReceiver::acceptTimeout(), database::mariadb::MariaDBConnection::commandContinue(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectEvent(), connectTimeout(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectTimeout(), core::DescriptorEventPublisher::disable(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::pipe::PipeSource::eof(), core::eventreceiver::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSink::readEvent(), core::eventreceiver::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::socket::stream::SocketWriter::signalEvent(), core::eventreceiver::AcceptEventReceiver::signalEvent(), signalEvent(), core::eventreceiver::ExceptionalConditionEventReceiver::signalEvent(), core::eventreceiver::ReadEventReceiver::signalEvent(), core::eventreceiver::WriteEventReceiver::signalEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), core::pipe::PipeSource::writeEvent(), core::eventreceiver::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
dispatchEvent()
void core::eventreceiver::ConnectEventReceiver::dispatchEvent () final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 42 of file ConnectEventReceiver.cpp.
{
        connectEvent();
    }
References connectEvent().
enable()
bool core::DescriptorEventReceiver::enable (int fd) protected inherited
Definition at line 70 of file DescriptorEventReceiver.cpp.
{
        if (core::eventLoopState() != core::State::STOPPING) {
            if (!enabled) {
                observedFd = fd;
                enabled = true;
                descriptorEventPublisher.enable(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double enable";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Enable after signal";
        }
        return enabled;
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::enable(), core::DescriptorEventReceiver::enabled, core::eventLoopState(), core::EventReceiver::getName(), core::DescriptorEventReceiver::observedFd, and core::STOPPING.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::init(), core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 65 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::socket::stream::tls::SocketReader::read(), core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::SocketWriter::shutdownWrite(), core::socket::stream::SocketWriter::streamToPeer(), core::DescriptorEventReceiver::suspend(), and core::socket::stream::tls::SocketWriter::write().
getRegisteredFd()
int core::DescriptorEventReceiver::getRegisteredFd () const inherited
Definition at line 66 of file DescriptorEventReceiver.cpp.
{
        return observedFd;
    }
References core::DescriptorEventReceiver::observedFd.
Referenced by core::DescriptorEventPublisher::enable(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::select::DescriptorEventPublisher::muxAdd(), core::poll::PollFdsManager::muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOff(), core::select::DescriptorEventPublisher::muxOff(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOn(), core::select::DescriptorEventPublisher::muxOn(), core::socket::stream::legacy::SocketReader::read(), core::pipe::PipeSink::readEvent(), core::socket::stream::legacy::SocketWriter::write(), core::pipe::PipeSource::writeEvent(), core::pipe::PipeSink::~PipeSink(), and core::pipe::PipeSource::~PipeSource().
getTimeout()
utils::Timeval core::DescriptorEventReceiver::getTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 152 of file DescriptorEventReceiver.cpp.
{
        return maxInactivity > 0 ? currentTime > lastTriggered ? maxInactivity - (currentTime - lastTriggered) : 0 : TIMEOUT::MAX;
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::DescriptorEventPublisher::getNextTimeout().
isEnabled()
bool core::DescriptorEventReceiver::isEnabled () const inherited
Definition at line 107 of file DescriptorEventReceiver.cpp.
{
        return enabled;
    }
References core::DescriptorEventReceiver::enabled.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketWriter::sendToPeer(), and core::socket::stream::SocketWriter::streamToPeer().
isSuspended()
bool core::DescriptorEventReceiver::isSuspended () const inherited
Definition at line 138 of file DescriptorEventReceiver.cpp.
{
        return suspended;
    }
References core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::pipe::PipeSource::send().
observed()
void core::Observer::observed () protected inherited
Definition at line 41 of file DescriptorEventReceiver.cpp.
{
        observationCounter++;
    }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setEnabled().
onEvent()
void core::DescriptorEventReceiver::onEvent (const utils::Timeval & currentTime) final private virtual inherited
Implements core::EventReceiver.
Definition at line 156 of file DescriptorEventReceiver.cpp.
{
        eventCounter++;
        triggered(currentTime);
        dispatchEvent();
    }
References core::DescriptorEventReceiver::dispatchEvent(), core::DescriptorEventReceiver::eventCounter, and core::DescriptorEventReceiver::triggered().
onSignal()
void core::DescriptorEventReceiver::onSignal (int signum) private inherited
Definition at line 163 of file DescriptorEventReceiver.cpp.
{
        signalEvent(signum);
    }
References core::DescriptorEventReceiver::signalEvent().
Referenced by core::DescriptorEventPublisher::signal().
relax()
void core::EventReceiver::relax () inherited
Definition at line 61 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
resume()
void core::DescriptorEventReceiver::resume () protected inherited
Definition at line 124 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (suspended) {
                suspended = false;
                lastTriggered = utils::Timeval::currentTime();
                descriptorEventPublisher.resume(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double resume";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Resume while not enabled";
        }
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::observedFd, utils::Timeval::operator=(), core::DescriptorEventPublisher::resume(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
setDisabled()
void core::DescriptorEventReceiver::setDisabled () private inherited
Definition at line 103 of file DescriptorEventReceiver.cpp.
{
        unObserved();
    }
References core::Observer::unObserved().
setEnabled()
void core::DescriptorEventReceiver::setEnabled (const utils::Timeval & currentTime) private inherited
Definition at line 87 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
        observed();
    }
References core::DescriptorEventReceiver::lastTriggered, core::Observer::observed(), and utils::Timeval::operator=().
Referenced by core::DescriptorEventPublisher::enable().
setTimeout()
void core::DescriptorEventReceiver::setTimeout (const utils::Timeval & timeout) inherited
Definition at line 142 of file DescriptorEventReceiver.cpp.
{
        if (timeout == TIMEOUT::DEFAULT) {
            this->maxInactivity = initialTimeout;
        } else {
            this->maxInactivity = timeout;
        }
        triggered(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::TIMEOUT::DEFAULT, core::DescriptorEventReceiver::initialTimeout, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator=(), utils::Timeval::operator==(), and core::DescriptorEventReceiver::triggered().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::init(), and core::socket::stream::SocketWriter::shutdownWrite().
signalEvent()
void core::eventreceiver::ConnectEventReceiver::signalEvent (int signum) override private virtual
Implements core::DescriptorEventReceiver.
Definition at line 50 of file ConnectEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
span()
void core::EventReceiver::span () inherited
Definition at line 57 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by core::EventReceiver::atNextTick(), database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), core::file::FileReader::start(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
suspend()
void core::DescriptorEventReceiver::suspend () protected inherited
Definition at line 111 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!suspended) {
                suspended = true;
                descriptorEventPublisher.suspend(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double suspend";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Suspend while not enabled";
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::observedFd, core::DescriptorEventPublisher::suspend(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), and core::pipe::PipeSource::writeEvent().
timeoutEvent()
void core::eventreceiver::ConnectEventReceiver::timeoutEvent () final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 46 of file ConnectEventReceiver.cpp.
{
        connectTimeout();
    }
References connectTimeout().
triggered()
void core::DescriptorEventReceiver::triggered (const utils::Timeval & currentTime) private inherited
Definition at line 167 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
    }
References core::DescriptorEventReceiver::lastTriggered, and utils::Timeval::operator=().
Referenced by core::DescriptorEventReceiver::onEvent(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::DescriptorEventReceiver::setTimeout().
unObserved()
void core::Observer::unObserved () protected inherited
Definition at line 45 of file DescriptorEventReceiver.cpp.
{
        observationCounter--;
        if (observationCounter == 0) {
            unobservedEvent();
        }
    }
References core::Observer::observationCounter, and core::Observer::unobservedEvent().
Referenced by core::DescriptorEventReceiver::setDisabled().
unobservedEvent()
virtual void core::Observer::unobservedEvent () protected pure virtual inherited
Implemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::tls::TLSHandshake, core::socket::stream::tls::TLSShutdown, core::pipe::PipeSink, core::pipe::PipeSource, and database::mariadb::MariaDBConnection.
Referenced by core::Observer::unObserved().
Member Data Documentation
descriptorEventPublisher
DescriptorEventPublisher& core::DescriptorEventReceiver::descriptorEventPublisher private inherited
Definition at line 104 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
enabled
bool core::DescriptorEventReceiver::enabled = false private inherited
Definition at line 108 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
event
Event core::EventReceiver::event private inherited
Definition at line 59 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
eventCounter
int core::DescriptorEventReceiver::eventCounter = 0 private inherited
Definition at line 115 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::onEvent().
initialTimeout
const utils::Timeval core::DescriptorEventReceiver::initialTimeout private inherited
Definition at line 113 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), and core::DescriptorEventReceiver::setTimeout().
lastTriggered
utils::Timeval core::DescriptorEventReceiver::lastTriggered private inherited
Definition at line 111 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setEnabled(), and core::DescriptorEventReceiver::triggered().
maxInactivity
utils::Timeval core::DescriptorEventReceiver::maxInactivity private inherited
Definition at line 112 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::getTimeout(), and core::DescriptorEventReceiver::setTimeout().
observationCounter
int core::Observer::observationCounter = 0 private inherited
Definition at line 53 of file DescriptorEventReceiver.h.
Referenced by core::Observer::observed(), and core::Observer::unObserved().
observedFd
int core::DescriptorEventReceiver::observedFd = -1 private inherited
Definition at line 106 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
suspended
bool core::DescriptorEventReceiver::suspended = false private inherited
Definition at line 109 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
The documentation for this class was generated from the following files:
core/eventreceiver/ConnectEventReceiver.h
core/eventreceiver/ConnectEventReceiver.cpp