SNode.C: web::http::client::Request Class Reference
web::http::client::Request Class Reference
#include <Request.h>
Public Member Functions
Request (SocketContext *socketContext, const std::string &host)
Request (Request &)=delete
Request (Request &&) noexcept
Request & operator= (Request &)=delete
Request & operator= (Request &&) noexcept=delete
~Request () override
void setMasterRequest (const std::shared_ptr< Request > &masterRequest)
virtual void init ()
Request & host (const std::string &hostFieldValue)
Request & append (const std::string &field, const std::string &value)
Request & set (const std::string &field, const std::string &value, bool overwrite=true)
Request & set (const std::map< std::string, std::string > &headers, bool overwrite=true)
Request & type (const std::string &type)
Request & cookie (const std::string &name, const std::string &value)
Request & cookie (const std::map< std::string, std::string > &cookies)
Request & query (const std::string &key, const std::string &value)
Request & setTrailer (const std::string &field, const std::string &value, bool overwrite=true)
bool send (const char *chunk, std::size_t chunkLen, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError=responseParseError)
bool send (const std::string &chunk, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError=responseParseError)
bool upgrade (const std::string &url, const std::string &protocols, const std::function< void(const std::shared_ptr< Request > &, bool)> &onUpgradeInitiate, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, bool)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError=responseParseError)
bool sendFile (const std::string &file, const std::function< void(int errnum)> &onStatus, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError=responseParseError)
Request & sendHeader ()
Request & sendFragment (const char *chunk, std::size_t chunkLen)
Request & sendFragment (const std::string &data)
bool end (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError=responseParseError)
std::string header (const std::string &field)
const CiStringMap< std::string > & getQueries () const
const CiStringMap< std::string > & getHeaders () const
const CiStringMap< std::string > & getCookies () const
SocketContext * getSocketContext () const
Public Member Functions inherited from core::pipe::Sink
Sink (Sink &)=delete
Sink & operator= (Sink &)=delete
Static Public Member Functions
static void responseParseError (const std::shared_ptr< Request > &request, const std::string &message)
Public Attributes
std::string hostFieldValue
std::string method = "GET"
std::string url = "/"
int httpMajor = 1
int httpMinor = 1
Protected Attributes
CiStringMap< std::string > queries
CiStringMap< std::string > headers
CiStringMap< std::string > cookies
CiStringMap< std::string > trailer
Private Member Functions
bool initiate (const std::shared_ptr< Request > &request)
void upgrade (const std::shared_ptr< Response > &response, const std::function< void(const std::string &)> &status)
bool executeSendFile (const std::string &file, const std::function< void(int)> &onStatus)
bool executeUpgrade (const std::string &url, const std::string &protocols, const std::function< void(bool)> &onStatus)
bool executeEnd ()
bool executeSendHeader ()
bool executeSendFragment (const char *chunk, std::size_t chunkLen)
void requestPrepared ()
void requestDelivered ()
void deliverResponse (const std::shared_ptr< Request > &request, const std::shared_ptr< Response > &response)
void deliverResponseParseError (const std::shared_ptr< Request > &request, const std::string &message)
void onSourceConnect (core::pipe::Source *source) override
void onSourceData (const char *chunk, std::size_t chunkLen) override
void onSourceEof () override
void onSourceError (int errnum) override
Private Attributes
std::list< RequestCommand * > requestCommands
TransferEncoding transferEncoding = TransferEncoding::HTTP10
std::size_t contentLength = 0
std::size_t contentLengthSent = 0
ConnectionState connectionState = ConnectionState::Default
std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> onResponseReceived
std::function< void(const std::shared_ptr< Request > &request, const std::string &message)> onResponseParseError
std::weak_ptr< Request > masterRequest
web::http::client::SocketContext * socketContext
Friends
class commands::SendFileCommand
class commands::SendFragmentCommand
class commands::SendHeaderCommand
class commands::UpgradeCommand
class commands::EndCommand
class SocketContext
Additional Inherited Members
Protected Member Functions inherited from core::pipe::Sink
Sink ()=default
Sink (Sink &&) noexcept=default
Sink & operator= (Sink &&) noexcept=default
virtual ~Sink ()
bool isStreaming ()
void stop ()
Detailed Description
Definition at line 76 of file Request.h.
Constructor & Destructor Documentation
Request() [1/3]
web::http::client::Request::Request (SocketContext * socketContext, const std::string & host) explicit
Definition at line 75 of file Request.cpp.
        : hostFieldValue(host)
        , socketContext(socketContext) {
        this->host(hostFieldValue);
    }
References host(), hostFieldValue, and socketContext.
Request() [2/3]
web::http::client::Request::Request (Request &) explicit delete
Request() [3/3]
web::http::client::Request::Request (Request && request) explicit noexcept
Definition at line 81 of file Request.cpp.
        : hostFieldValue(request.hostFieldValue) // NOLINT
        , method(std::move(request.method))
        , url(std::move(request.url))
        , httpMajor(request.httpMajor)
        , httpMinor(request.httpMinor)
        , queries(std::move(request.queries))
        , headers(std::move(request.headers))
        , cookies(std::move(request.cookies))
        , trailer(std::move(request.trailer))
        , requestCommands(std::move(request.requestCommands))
        , transferEncoding(request.transferEncoding)
        , contentLength(request.contentLength)
        , contentLengthSent(request.contentLengthSent)
        , connectionState(request.connectionState)
        , onResponseReceived(std::move(request.onResponseReceived))
        , onResponseParseError(std::move(request.onResponseParseError))
        , masterRequest(request.masterRequest) // NOLINT
        , socketContext(request.socketContext) {
        request.init();
    }
References connectionState, contentLength, contentLengthSent, cookies, headers, hostFieldValue, httpMajor, httpMinor, init(), masterRequest, method, onResponseParseError, onResponseReceived, queries, requestCommands, socketContext, trailer, transferEncoding, and url.
~Request()
web::http::client::Request::~Request () override
Definition at line 103 of file Request.cpp.
                      {
        for (const RequestCommand* requestCommand : requestCommands) {
            delete requestCommand;
        }
        if (!masterRequest.expired() && Sink::isStreaming()) {
            socketContext->streamEof();
        }
    }
References core::pipe::Sink::isStreaming(), masterRequest, requestCommands, socketContext, and core::socket::stream::SocketContext::streamEof().
Member Function Documentation
append()
Request & web::http::client::Request::append (const std::string & field, const std::string & value)
Definition at line 147 of file Request.cpp.
{
        const std::map<std::string, std::string>::iterator it = headers.find(field);
        if (it != headers.end()) {
            set(field, it->second.append(", ").append(value));
        } else {
            set(field, value);
        }
        return *this;
    }
References headers, and set().
cookie() [1/2]
Request & web::http::client::Request::cookie (const std::map< std::string, std::string > & cookies)
Definition at line 225 of file Request.cpp.
{
        for (const auto& [name, value] : cookies) {
            cookie(name, value);
        }
        return *this;
    }
References cookie().
cookie() [2/2]
Request & web::http::client::Request::cookie (const std::string & name, const std::string & value)
Definition at line 219 of file Request.cpp.
{
        cookies.insert({name, value});
        return *this;
    }
References cookies.
Referenced by cookie().
deliverResponse()
void web::http::client::Request::deliverResponse (const std::shared_ptr< Request > & request, const std::shared_ptr< Response > & response) private
Definition at line 620 of file Request.cpp.
{
        onResponseReceived(request, response);
    }
References onResponseReceived.
Referenced by web::http::client::SocketContext::deliverResponse().
deliverResponseParseError()
void web::http::client::Request::deliverResponseParseError (const std::shared_ptr< Request > & request, const std::string & message) private
Definition at line 624 of file Request.cpp.
{
        onResponseParseError(request, message);
    }
References onResponseParseError.
Referenced by web::http::client::SocketContext::deliverResponseParseError().
end()
bool web::http::client::Request::end (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> & onResponseParseError = responseParseError)
Definition at line 431 of file Request.cpp.
{
        bool queued = true;
        if (!masterRequest.expired()) {
            this->onResponseReceived = onResponseReceived;
            this->onResponseParseError = onResponseParseError;
            sendHeader();
            requestCommands.push_back(new commands::EndCommand());
            requestPrepared();
        } else {
            queued = false;
        }
        return queued;
    }
References web::http::client::commands::EndCommand::EndCommand(), masterRequest, onResponseParseError, onResponseReceived, requestCommands, requestPrepared(), and sendHeader().
executeEnd()
bool web::http::client::Request::executeEnd () private
Definition at line 563 of file Request.cpp.
                             { // NOLINT
        return true;
    }
Referenced by web::http::client::commands::EndCommand::execute().
executeSendFile()
bool web::http::client::Request::executeSendFile (const std::string & file, const std::function< void(int)> & onStatus) private
Definition at line 476 of file Request.cpp.
{
        bool atomar = true;
        std::string absolutFileName = file;
        if (std::filesystem::exists(absolutFileName)) {
            std::error_code ec;
            absolutFileName = std::filesystem::canonical(absolutFileName);
            if (std::filesystem::is_regular_file(absolutFileName, ec) && !ec) {
                core::file::FileReader::open(absolutFileName)->pipe(this, [this, &atomar, &absolutFileName, &onStatus](int errnum) {
                    errno = errnum;
                    onStatus(errnum);
                    if (errnum == 0) {
                        if (httpMajor == 1) {
                            atomar = false;
                            set("Content-Type", web::http::MimeTypes::contentType(absolutFileName), false);
                            set("Last-Modified", httputils::file_mod_http_date(absolutFileName), false);
                            if (httpMinor == 1 && contentLength == 0) {
                                set("Transfer-Encoding", "chunked");
                            } else {
                                set("Content-Length", std::to_string(std::filesystem::file_size(absolutFileName) + contentLength));
                            }
                            executeSendHeader();
                        }
                    }
                });
            } else {
                errno = EINVAL;
                onStatus(errno);
            }
        } else {
            errno = ENOENT;
            onStatus(errno);
        }
        return atomar;
    }
References contentLength, web::http::MimeTypes::contentType(), executeSendHeader(), httputils::file_mod_http_date(), httpMajor, httpMinor, core::file::FileReader::open(), core::pipe::Source::pipe(), and set().
Referenced by web::http::client::commands::SendFileCommand::execute().
executeSendFragment()
bool web::http::client::Request::executeSendFragment (const char * chunk, std::size_t chunkLen) private
Definition at line 599 of file Request.cpp.
{
        if (transferEncoding == TransferEncoding::Chunked) {
            socketContext->sendToPeer(to_hex_str(chunkLen).append("\r\n"));
        }
        socketContext->sendToPeer(chunk, chunkLen);
        contentLengthSent += chunkLen;
        if (transferEncoding == TransferEncoding::Chunked) {
            socketContext->sendToPeer("\r\n");
            contentLength += chunkLen;
        }
        return true;
    }
References web::http::Chunked, contentLength, contentLengthSent, core::socket::stream::SocketContext::sendToPeer(), core::socket::SocketContext::sendToPeer(), socketContext, and transferEncoding.
Referenced by web::http::client::commands::SendFragmentCommand::execute(), onSourceData(), and requestDelivered().
executeSendHeader()
bool web::http::client::Request::executeSendHeader () private
Definition at line 567 of file Request.cpp.
{
        const std::string httpVersion = "HTTP/" + std::to_string(httpMajor) + "." + std::to_string(httpMinor);
        std::string queryString;
        if (!queries.empty()) {
            queryString += "?";
            for (auto& [key, value] : queries) {
                queryString += httputils::url_encode(key) + "=" + httputils::url_encode(value) + "&";
            }
            queryString.pop_back();
        }
        socketContext->sendToPeer(method + " " + url + queryString + " " + httpVersion + "\r\n");
        socketContext->sendToPeer("Date: " + httputils::to_http_date() + "\r\n");
        if (!headers.contains("Transfer-Encoding") && contentLength > 0) {
            set("Content-Length", std::to_string(contentLength));
        }
        for (const auto& [field, value] : headers) {
            socketContext->sendToPeer(std::string(field).append(":").append(value).append("\r\n"));
        }
        for (const auto& [name, value] : cookies) {
            socketContext->sendToPeer(std::string("Cookie:").append(name).append("=").append(value).append("\r\n"));
        }
        socketContext->sendToPeer("\r\n");
        return true;
    }
References contentLength, cookies, headers, httpMajor, httpMinor, method, queries, core::socket::SocketContext::sendToPeer(), set(), socketContext, httputils::to_http_date(), url, and httputils::url_encode().
Referenced by web::http::client::commands::SendHeaderCommand::execute(), executeSendFile(), and executeUpgrade().
executeUpgrade()
bool web::http::client::Request::executeUpgrade (const std::string & url, const std::string & protocols, const std::function< void(bool)> & onStatus) private
Definition at line 518 of file Request.cpp.
{
        const std::string connectionName = this->getSocketContext()->getSocketConnection()->getConnectionName();
        this->url = url;
        set("Connection", "Upgrade", true);
        set("Upgrade", protocols, true);
        web::http::client::SocketContextUpgradeFactory* socketContextUpgradeFactory =
            web::http::client::SocketContextUpgradeFactorySelector::instance()->select(protocols, *this);
        if (socketContextUpgradeFactory != nullptr) {
            LOG(DEBUG) << connectionName << " HTTP: "
                       << "SocketContextUpgradeFactory create success: " << socketContextUpgradeFactory->name();
            LOG(DEBUG) << connectionName << " HTTP: Initiating upgrade: " << method << " " << url
                       << " HTTP/" + std::to_string(httpMajor) + "." + std::to_string(httpMinor);
        } else {
            LOG(DEBUG) << connectionName << " HTTP: "
                       << "SocketContextUpgradeFactory create failed: " << protocols;
            LOG(DEBUG) << connectionName << " HTTP: Not initiating upgrade " << method << " " << url
                       << " HTTP/" + std::to_string(httpMajor) + "." + std::to_string(httpMinor);
        }
        LOG(DEBUG) << connectionName << " HTTP: Upgrade request:\n"
                   << httputils::toString(method,
                                          url,
                                          "HTTP/" + std::to_string(httpMajor) + "." + std::to_string(httpMinor),
                                          queries,
                                          headers,
                                          cookies,
                                          std::vector<char>());
        onStatus(socketContextUpgradeFactory != nullptr);
        if (socketContextUpgradeFactory != nullptr) {
            executeSendHeader();
            socketContextUpgradeFactory->checkRefCount();
        } else {
            socketContext->close();
        }
        return true;
    }
References web::http::client::SocketContextUpgradeFactory::checkRefCount(), core::socket::stream::SocketContext::close(), cookies, executeSendHeader(), core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), getSocketContext(), headers, httpMajor, httpMinor, web::http::client::SocketContextUpgradeFactorySelector::instance(), method, web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::name(), queries, web::http::client::SocketContextUpgradeFactorySelector::select(), set(), socketContext, httputils::toString(), and url.
Referenced by web::http::client::commands::UpgradeCommand::execute().
getCookies()
const web::http::CiStringMap< std::string > & web::http::client::Request::getCookies () const
Definition at line 690 of file Request.cpp.
{
        return cookies;
    }
References cookies.
getHeaders()
const web::http::CiStringMap< std::string > & web::http::client::Request::getHeaders () const
Definition at line 686 of file Request.cpp.
{
        return headers;
    }
References headers.
getQueries()
const web::http::CiStringMap< std::string > & web::http::client::Request::getQueries () const
Definition at line 682 of file Request.cpp.
{
        return queries;
    }
References queries.
getSocketContext()
SocketContext * web::http::client::Request::getSocketContext () const
Definition at line 694 of file Request.cpp.
{
        return socketContext;
    }
References socketContext.
Referenced by executeUpgrade(), main(), responseParseError(), and upgrade().
header()
std::string web::http::client::Request::header (const std::string & field)
Definition at line 678 of file Request.cpp.
{
        return headers.contains(field) ? headers[field] : "";
    }
References headers.
Referenced by web::websocket::client::SocketContextUpgradeFactory::create(), main(), web::http::client::SocketContext::requestPrepared(), upgrade(), and upgrade().
host()
Request & web::http::client::Request::host (const std::string & hostFieldValue)
Definition at line 141 of file Request.cpp.
{
        set("Host", hostFieldValue);
        return *this;
    }
References set().
Referenced by init(), and Request().
init()
void web::http::client::Request::init () virtual
Definition at line 117 of file Request.cpp.
                       {
        method = "GET";
        url = "/";
        httpMajor = 1;
        httpMinor = 1;
        queries.clear();
        headers.clear();
        cookies.clear();
        trailer.clear();
        for (const RequestCommand* requestCommand : requestCommands) {
            delete requestCommand;
        }
        requestCommands.clear();
        transferEncoding = TransferEncoding::HTTP10;
        contentLength = 0;
        contentLengthSent = 0;
        connectionState = ConnectionState::Default;
        onResponseReceived = nullptr;
        onResponseParseError = nullptr;
        this->host(hostFieldValue);
        set("X-Powered-By", "snode.c");
    }
References connectionState, contentLength, contentLengthSent, cookies, web::http::Default, headers, host(), hostFieldValue, web::http::HTTP10, httpMajor, httpMinor, method, onResponseParseError, onResponseReceived, queries, requestCommands, set(), trailer, transferEncoding, and url.
Referenced by Request(), and requestPrepared().
initiate()
bool web::http::client::Request::initiate (const std::shared_ptr< Request > & request) private
Definition at line 451 of file Request.cpp.
{
        bool error = false;
        bool atomar = true;
        for (RequestCommand* requestCommand : requestCommands) {
            if (!error) {
                const bool atomarCommand = requestCommand->execute(request);
                if (atomar) {
                    atomar = atomarCommand;
                }
                error = requestCommand->getError();
            }
            delete requestCommand;
        }
        requestCommands.clear();
        if (atomar && (!error || contentLengthSent != 0)) {
            requestDelivered();
        }
        return !error || contentLengthSent != 0;
    }
References contentLengthSent, web::http::client::RequestCommand::execute(), web::http::client::RequestCommand::getError(), requestCommands, and requestDelivered().
Referenced by web::http::client::SocketContext::initiateRequest().
onSourceConnect()
void web::http::client::Request::onSourceConnect (core::pipe::Source * source) override private virtual
Implements core::pipe::Sink.
Definition at line 645 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            if (socketContext->streamToPeer(source)) {
                source->start();
            }
        } else {
            source->stop();
        }
    }
References masterRequest, socketContext, core::pipe::Source::start(), core::pipe::Source::stop(), and core::socket::stream::SocketContext::streamToPeer().
onSourceData()
void web::http::client::Request::onSourceData (const char * chunk, std::size_t chunkLen) override private virtual
Implements core::pipe::Sink.
Definition at line 655 of file Request.cpp.
{
        executeSendFragment(chunk, chunkLen);
    }
References executeSendFragment().
onSourceEof()
void web::http::client::Request::onSourceEof () override private virtual
Implements core::pipe::Sink.
Definition at line 659 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            socketContext->streamEof();
            requestDelivered();
        }
    }
References masterRequest, requestDelivered(), socketContext, and core::socket::stream::SocketContext::streamEof().
onSourceError()
void web::http::client::Request::onSourceError (int errnum) override private virtual
Implements core::pipe::Sink.
Definition at line 667 of file Request.cpp.
{
        errno = errnum;
        if (!masterRequest.expired()) {
            socketContext->streamEof();
            socketContext->close();
            requestDelivered();
        }
    }
References core::socket::stream::SocketContext::close(), masterRequest, requestDelivered(), socketContext, and core::socket::stream::SocketContext::streamEof().
operator=() [1/2]
Request & web::http::client::Request::operator= (Request &&) delete noexcept
operator=() [2/2]
Request & web::http::client::Request::operator= (Request &) delete
query()
Request & web::http::client::Request::query (const std::string & key, const std::string & value)
Definition at line 233 of file Request.cpp.
{
        queries.insert({key, value});
        return *this;
    }
References queries.
requestDelivered()
void web::http::client::Request::requestDelivered () private
Definition at line 628 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            if (transferEncoding == TransferEncoding::Chunked) {
                executeSendFragment("", 0); // For transfer encoding chunked. Terminate the chunk sequence.
                if (!trailer.empty()) {
                    for (auto& [field, value] : trailer) {
                        socketContext->sendToPeer(std::string(field).append(":").append(value).append("\r\n"));
                    }
                    socketContext->sendToPeer("\r\n");
                }
            }
            socketContext->requestDelivered(std::move(*this), contentLengthSent == contentLength);
        }
    }
References web::http::Chunked, contentLength, contentLengthSent, executeSendFragment(), masterRequest, web::http::client::SocketContext::requestDelivered(), core::socket::SocketContext::sendToPeer(), socketContext, trailer, and transferEncoding.
Referenced by initiate(), onSourceEof(), and onSourceError().
requestPrepared()
void web::http::client::Request::requestPrepared () private
Definition at line 615 of file Request.cpp.
{
        socketContext->requestPrepared(std::move(*this));
        init();
    }
References init(), web::http::client::SocketContext::requestPrepared(), and socketContext.
Referenced by end(), send(), sendFile(), and upgrade().
responseParseError()
void web::http::client::Request::responseParseError (const std::shared_ptr< Request > & request, const std::string & message) static
Definition at line 258 of file Request.cpp.
{
        LOG(WARNING) << request->getSocketContext()->getSocketConnection()->getConnectionName()
                     << " HTTP: Response parse error: " << request->method << " " << request->url << " "
                     << "HTTP/" << request->httpMajor << "." << request->httpMinor << ": " << message;
    }
References core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), getSocketContext(), httpMajor, httpMinor, method, and url.
send() [1/2]
bool web::http::client::Request::send (const char * chunk, std::size_t chunkLen, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> & onResponseParseError = responseParseError)
Definition at line 264 of file Request.cpp.
{
        bool queued = true;
        if (!masterRequest.expired()) {
            this->onResponseReceived = onResponseReceived;
            this->onResponseParseError = onResponseParseError;
            if (chunkLen > 0) {
                set("Content-Type", "application/octet-stream", false);
            }
            sendHeader();
            sendFragment(chunk, chunkLen);
            requestCommands.push_back(new commands::EndCommand());
            requestPrepared();
        } else {
            queued = false;
        }
        return queued;
    }
References web::http::client::commands::EndCommand::EndCommand(), masterRequest, onResponseParseError, onResponseReceived, requestCommands, requestPrepared(), sendFragment(), sendHeader(), and set().
Referenced by send().
send() [2/2]
bool web::http::client::Request::send (const std::string & chunk, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> & onResponseParseError = responseParseError)
Definition at line 291 of file Request.cpp.
{
        if (!chunk.empty()) {
            set("Content-Type", "text/html; charset=utf-8", false);
        }
        return send(chunk.data(), chunk.size(), onResponseReceived, onResponseParseError);
    }
References send(), and set().
Referenced by main().
sendFile()
bool web::http::client::Request::sendFile (const std::string & file, const std::function< void(int errnum)> & onStatus, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> & onResponseParseError = responseParseError)
Definition at line 389 of file Request.cpp.
{
        bool queued = false;
        if (!masterRequest.expired()) {
            this->onResponseReceived = onResponseReceived;
            this->onResponseParseError = onResponseParseError;
            requestCommands.push_back(new commands::SendFileCommand(file, onStatus));
            requestPrepared();
            queued = true;
        }
        return queued;
    }
References masterRequest, onResponseParseError, onResponseReceived, requestCommands, requestPrepared(), and web::http::client::commands::SendFileCommand::SendFileCommand().
sendFragment() [1/2]
Request & web::http::client::Request::sendFragment (const char * chunk, std::size_t chunkLen)
Definition at line 417 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            contentLength += chunkLen;
            requestCommands.push_back(new commands::SendFragmentCommand(chunk, chunkLen));
        }
        return *this;
    }
References contentLength, masterRequest, requestCommands, and web::http::client::commands::SendFragmentCommand::SendFragmentCommand().
Referenced by send(), and sendFragment().
sendFragment() [2/2]
Request & web::http::client::Request::sendFragment (const std::string & data)
Definition at line 427 of file Request.cpp.
{
        return sendFragment(data.data(), data.size());
    }
References sendFragment().
sendHeader()
Request & web::http::client::Request::sendHeader ()
Definition at line 409 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            requestCommands.push_back(new commands::SendHeaderCommand());
        }
        return *this;
    }
References masterRequest, requestCommands, and web::http::client::commands::SendHeaderCommand::SendHeaderCommand().
Referenced by end(), and send().
set() [1/2]
Request & web::http::client::Request::set (const std::map< std::string, std::string > & headers, bool overwrite = true)
Definition at line 205 of file Request.cpp.
{
        for (const auto& [field, value] : headers) {
            set(field, value, overwrite);
        }
        return *this;
    }
References set().
set() [2/2]
Request & web::http::client::Request::set (const std::string & field, const std::string & value, bool overwrite = true)
Definition at line 159 of file Request.cpp.
{
        if (!value.empty()) {
            if (overwrite) {
                headers.insert_or_assign(field, value);
            } else {
                headers.insert({field, value});
            }
            if (web::http::ciEquals(field, "Connection")) {
                if (web::http::ciContains(headers[field], "close")) {
                    connectionState = ConnectionState::Close;
                } else if (web::http::ciContains(headers[field], "keep-alive")) {
                    connectionState = ConnectionState::Keep;
                }
            } else if (web::http::ciEquals(field, "Content-Length")) {
                contentLength = std::stoul(value);
                transferEncoding = TransferEncoding::Identity;
                headers.erase("Transfer-Encoding");
            } else if (web::http::ciEquals(field, "Transfer-Encoding")) {
                if (web::http::ciContains(headers[field], "chunked")) {
                    transferEncoding = TransferEncoding::Chunked;
                    headers.erase("Content-Length");
                }
                if (web::http::ciContains(headers[field], "compressed")) {
                }
                if (web::http::ciContains(headers[field], "deflate")) {
                }
                if (web::http::ciContains(headers[field], "gzip")) {
                }
            } else if (web::http::ciEquals(field, "Content-Encoding")) {
                if (web::http::ciContains(headers[field], "compressed")) {
                }
                if (web::http::ciContains(headers[field], "deflate")) {
                }
                if (web::http::ciContains(headers[field], "gzip")) {
                }
                if (web::http::ciContains(headers[field], "br")) {
                }
            }
        } else {
            headers.erase(field);
        }
        return *this;
    }
References web::http::Chunked, web::http::ciContains(), web::http::ciEquals(), web::http::Close, connectionState, contentLength, headers, web::http::Identity, web::http::Keep, and transferEncoding.
Referenced by append(), executeSendFile(), executeSendHeader(), executeUpgrade(), host(), init(), main(), web::websocket::client::SocketContextUpgradeFactory::prepare(), send(), send(), set(), and setTrailer().
setMasterRequest()
void web::http::client::Request::setMasterRequest (const std::shared_ptr< Request > & masterRequest)
Definition at line 113 of file Request.cpp.
{
        this->masterRequest = masterRequest;
    }
References masterRequest.
setTrailer()
Request & web::http::client::Request::setTrailer (const std::string & field, const std::string & value, bool overwrite = true)
Definition at line 239 of file Request.cpp.
{
        if (!value.empty()) {
            if (overwrite) {
                trailer.insert_or_assign(field, value);
            } else {
                trailer.insert({field, value});
            }
            if (!headers.contains("Trailer")) {
                set("Trailer", field);
            } else {
                headers["Trailer"].append("," + field);
            }
        } else {
            trailer.erase(field);
        }
        return *this;
    }
References headers, set(), and trailer.
type()
Request & web::http::client::Request::type (const std::string & type)
Definition at line 213 of file Request.cpp.
{
        headers.insert({"Content-Type", type});
        return *this;
    }
References headers.
Referenced by main().
upgrade() [1/2]
void web::http::client::Request::upgrade (const std::shared_ptr< Response > & response, const std::function< void(const std::string &)> & status) private
Definition at line 338 of file Request.cpp.
{
        const std::string connectionName = socketContext->getSocketConnection()->getConnectionName();
        std::string name;
        if (!masterRequest.expired()) {
            if (response != nullptr) {
                if (web::http::ciContains(response->get("connection"), "Upgrade")) {
                    SocketContextUpgradeFactory* socketContextUpgradeFactory =
                        SocketContextUpgradeFactorySelector::instance()->select(*this, *response);
                    if (socketContextUpgradeFactory != nullptr) {
                        name = socketContextUpgradeFactory->name();
                        LOG(DEBUG) << connectionName << " HTTP upgrade: SocketContextUpgradeFactory create success for: " << name;
                        core::socket::stream::SocketContext* socketContextUpgrade =
                            socketContextUpgradeFactory->create(socketContext->getSocketConnection());
                        if (socketContextUpgrade != nullptr) {
                            LOG(DEBUG) << connectionName << " HTTP upgrade: SocketContextUpgrade create success for: " << name;
                            socketContext->switchSocketContext(socketContextUpgrade);
                        } else {
                            LOG(DEBUG) << connectionName << " HTTP upgrade: SocketContextUpgrade create failed for: " << name;
                            socketContext->close();
                        }
                    } else {
                        LOG(DEBUG) << connectionName
                                   << " HTTP upgrade: SocketContextUpgradeFactory not supported by server: " << header("upgrade");
                        socketContext->close();
                    }
                } else {
                    LOG(DEBUG) << connectionName << " HTTP upgrade: No upgrade requested";
                    socketContext->close();
                }
            } else {
                LOG(ERROR) << connectionName << " HTTP upgrade: Response has gone away";
                socketContext->close();
            }
        } else {
            LOG(ERROR) << connectionName << " HTTP upgrade: Unexpected disconnect";
        }
        status(name);
    }
References web::http::ciContains(), core::socket::stream::SocketContext::close(), web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::create(), web::http::client::Response::get(), core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), header(), web::http::client::SocketContextUpgradeFactorySelector::instance(), masterRequest, web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::name(), web::http::client::SocketContextUpgradeFactorySelector::select(), socketContext, and core::socket::stream::SocketContext::switchSocketContext().
Referenced by upgrade().
upgrade() [2/2]
bool web::http::client::Request::upgrade (const std::string & url, const std::string & protocols, const std::function< void(const std::shared_ptr< Request > &, bool)> & onUpgradeInitiate, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, bool)> & onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> & onResponseParseError = responseParseError)
Definition at line 302 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            this->url = url;
            this->onResponseParseError = onResponseParseError;
            this->onResponseReceived = [onResponseReceived](const std::shared_ptr<Request>& req, const std::shared_ptr<Response>& res) {
                const std::string connectionName = req->getSocketContext()->getSocketConnection()->getConnectionName();
                LOG(DEBUG) << connectionName << " HTTP: Response to upgrade request: " << req->method << " " << req->url << " " << "HTTP/"
                           << req->httpMajor << "." << req->httpMinor << "\n"
                           << httputils::toString(res->httpVersion, res->statusCode, res->reason, res->headers, res->cookies, res->body);
                req->upgrade(res, [req, res, connectionName, &onResponseReceived](const std::string& name) {
                    LOG(DEBUG) << connectionName << " HTTP: Upgrade bootstrap " << (!name.empty() ? "success" : "failed");
                    LOG(DEBUG) << "      Protocol selected: " << name;
                    LOG(DEBUG) << "              requested: " << req->header("upgrade");
                    LOG(DEBUG) << "  Subprotocol  selected: " << res->get("Sec-WebSocket-Protocol");
                    LOG(DEBUG) << "              requested: " << req->header("Sec-WebSocket-Protocol");
                    onResponseReceived(req, res, !name.empty());
                });
            };
            requestCommands.push_back(new commands::UpgradeCommand(url, protocols, onUpgradeInitiate));
            requestPrepared();
        }
        return !masterRequest.expired();
    }
References web::http::client::Response::body, web::http::client::Response::cookies, web::http::client::Response::get(), core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), getSocketContext(), header(), web::http::client::Response::headers, httpMajor, httpMinor, web::http::client::Response::httpVersion, masterRequest, method, onResponseParseError, onResponseReceived, web::http::client::Response::reason, requestCommands, requestPrepared(), web::http::client::Response::statusCode, httputils::toString(), upgrade(), web::http::client::commands::UpgradeCommand::UpgradeCommand(), and url.
Referenced by main().
Friends And Related Symbol Documentation
commands::EndCommand
friend class commands::EndCommand friend
Definition at line 138 of file Request.h.
commands::SendFileCommand
friend class commands::SendFileCommand friend
Definition at line 134 of file Request.h.
commands::SendFragmentCommand
friend class commands::SendFragmentCommand friend
Definition at line 135 of file Request.h.
commands::SendHeaderCommand
friend class commands::SendHeaderCommand friend
Definition at line 136 of file Request.h.
commands::UpgradeCommand
friend class commands::UpgradeCommand friend
Definition at line 137 of file Request.h.
SocketContext
friend class SocketContext friend
Definition at line 195 of file Request.h.
Member Data Documentation
connectionState
ConnectionState web::http::client::Request::connectionState = ConnectionState::Default private
Definition at line 186 of file Request.h.
Referenced by init(), Request(), and set().
contentLength
std::size_t web::http::client::Request::contentLength = 0 private
Definition at line 183 of file Request.h.
Referenced by executeSendFile(), executeSendFragment(), executeSendHeader(), init(), Request(), requestDelivered(), sendFragment(), and set().
contentLengthSent
std::size_t web::http::client::Request::contentLengthSent = 0 private
Definition at line 184 of file Request.h.
Referenced by executeSendFragment(), init(), initiate(), Request(), and requestDelivered().
cookies
CiStringMap<std::string> web::http::client::Request::cookies protected
Definition at line 175 of file Request.h.
Referenced by cookie(), executeSendHeader(), executeUpgrade(), getCookies(), init(), and Request().
headers
CiStringMap<std::string> web::http::client::Request::headers protected
Definition at line 174 of file Request.h.
Referenced by append(), executeSendHeader(), executeUpgrade(), getHeaders(), header(), init(), Request(), set(), setTrailer(), and type().
hostFieldValue
std::string web::http::client::Request::hostFieldValue
Definition at line 166 of file Request.h.
Referenced by init(), Request(), and Request().
httpMajor
int web::http::client::Request::httpMajor = 1
Definition at line 169 of file Request.h.
Referenced by web::http::client::SocketContext::deliverResponse(), web::http::client::SocketContext::deliverResponseParseError(), executeSendFile(), executeSendHeader(), executeUpgrade(), init(), web::http::client::SocketContext::initiateRequest(), web::http::client::SocketContext::onDisconnected(), Request(), web::http::client::SocketContext::requestDelivered(), web::http::client::SocketContext::requestPrepared(), web::http::client::SocketContext::responseDelivered(), responseParseError(), web::http::client::SocketContext::responseStarted(), upgrade(), and web::http::client::SocketContext::~SocketContext().
httpMinor
int web::http::client::Request::httpMinor = 1
Definition at line 170 of file Request.h.
Referenced by web::http::client::SocketContext::deliverResponse(), web::http::client::SocketContext::deliverResponseParseError(), executeSendFile(), executeSendHeader(), executeUpgrade(), init(), web::http::client::SocketContext::initiateRequest(), web::http::client::SocketContext::onDisconnected(), Request(), web::http::client::SocketContext::requestDelivered(), web::http::client::SocketContext::requestPrepared(), web::http::client::SocketContext::responseDelivered(), responseParseError(), web::http::client::SocketContext::responseStarted(), upgrade(), and web::http::client::SocketContext::~SocketContext().
masterRequest
std::weak_ptr<Request> web::http::client::Request::masterRequest private
Definition at line 191 of file Request.h.
Referenced by end(), onSourceConnect(), onSourceEof(), onSourceError(), Request(), requestDelivered(), send(), sendFile(), sendFragment(), sendHeader(), setMasterRequest(), upgrade(), upgrade(), and ~Request().
method
std::string web::http::client::Request::method = "GET"
Definition at line 167 of file Request.h.
Referenced by web::http::client::SocketContext::deliverResponse(), web::http::client::SocketContext::deliverResponseParseError(), executeSendHeader(), executeUpgrade(), init(), web::http::client::SocketContext::initiateRequest(), main(), Request(), web::http::client::SocketContext::requestDelivered(), web::http::client::SocketContext::requestPrepared(), web::http::client::SocketContext::responseDelivered(), responseParseError(), web::http::client::SocketContext::responseStarted(), upgrade(), and web::http::client::SocketContext::~SocketContext().
onResponseParseError
std::function<void(const std::shared_ptr<Request>& request, const std::string& message)> web::http::client::Request::onResponseParseError private
Definition at line 189 of file Request.h.
Referenced by deliverResponseParseError(), end(), init(), Request(), send(), sendFile(), and upgrade().
onResponseReceived
std::function<void(const std::shared_ptr<Request>&, const std::shared_ptr<Response>&)> web::http::client::Request::onResponseReceived private
Definition at line 188 of file Request.h.
Referenced by deliverResponse(), end(), init(), Request(), send(), sendFile(), and upgrade().
queries
CiStringMap<std::string> web::http::client::Request::queries protected
Definition at line 173 of file Request.h.
Referenced by executeSendHeader(), executeUpgrade(), getQueries(), init(), query(), and Request().
requestCommands
std::list<RequestCommand*> web::http::client::Request::requestCommands private
Definition at line 179 of file Request.h.
Referenced by end(), init(), initiate(), Request(), send(), sendFile(), sendFragment(), sendHeader(), upgrade(), and ~Request().
socketContext
web::http::client::SocketContext* web::http::client::Request::socketContext private
Definition at line 193 of file Request.h.
Referenced by executeSendFragment(), executeSendHeader(), executeUpgrade(), getSocketContext(), onSourceConnect(), onSourceEof(), onSourceError(), Request(), Request(), requestDelivered(), requestPrepared(), upgrade(), and ~Request().
trailer
CiStringMap<std::string> web::http::client::Request::trailer protected
Definition at line 176 of file Request.h.
Referenced by init(), Request(), requestDelivered(), and setTrailer().
transferEncoding
TransferEncoding web::http::client::Request::transferEncoding = TransferEncoding::HTTP10 private
Definition at line 181 of file Request.h.
Referenced by executeSendFragment(), init(), Request(), requestDelivered(), and set().
url
std::string web::http::client::Request::url = "/"
Definition at line 168 of file Request.h.
Referenced by web::http::client::SocketContext::deliverResponse(), web::http::client::SocketContext::deliverResponseParseError(), executeSendHeader(), executeUpgrade(), init(), web::http::client::SocketContext::initiateRequest(), main(), Request(), web::http::client::SocketContext::requestDelivered(), web::http::client::SocketContext::requestPrepared(), web::http::client::SocketContext::responseDelivered(), responseParseError(), web::http::client::SocketContext::responseStarted(), upgrade(), and web::http::client::SocketContext::~SocketContext().
The documentation for this class was generated from the following files:
web/http/client/Request.h
web/http/client/Request.cpp