SNode.C: express::dispatcher::ApplicationDispatcher Class Reference
express::dispatcher::ApplicationDispatcher Class Reference
#include <ApplicationDispatcher.h>
Public Member Functions
ApplicationDispatcher (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda)
Public Member Functions inherited from express::Dispatcher
Dispatcher (const Dispatcher &)=delete
Dispatcher & operator= (const Dispatcher &)=delete
Dispatcher ()=default
virtual ~Dispatcher ()
bool dispatchNext (Controller &controller, const std::string &parentMountPath)
Private Member Functions
bool dispatch (express::Controller &controller, const std::string &parentMountPath, const express::MountPoint &mountPoint) override
std::list< std::string > getRoutes (const std::string &parentMountPath, const MountPoint &mountPoint, bool strictRouting) const override
Private Attributes
const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> lambda
std::regex regex
std::vector< std::string > names
Additional Inherited Members
Protected Attributes inherited from express::Dispatcher
std::shared_ptr< Route > nextRoute = nullptr
Detailed Description
Definition at line 64 of file ApplicationDispatcher.h.
Constructor & Destructor Documentation
ApplicationDispatcher()
express::dispatcher::ApplicationDispatcher::ApplicationDispatcher (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) explicit
Definition at line 65 of file ApplicationDispatcher.cpp.
        : lambda(lambda) {
    }
References lambda.
Member Function Documentation
dispatch()
bool express::dispatcher::ApplicationDispatcher::dispatch (express::Controller & controller, const std::string & parentMountPath, const express::MountPoint & mountPoint) override private virtual
Implements express::Dispatcher.
Definition at line 70 of file ApplicationDispatcher.cpp.
{
        bool requestMatched = false;
        if (controller.getRequest()->method == mountPoint.method || mountPoint.method == "use" || mountPoint.method == "all") {
            const std::string absoluteMountPath = parentMountPath + mountPoint.relativeMountPath;
            if ((controller.getFlags() & Controller::NEXT) == 0) {
                // Split mount & request into path + query
                std::string_view mountPath;
                std::string_view mountQueryString;
                splitPathAndQuery(absoluteMountPath, mountPath, mountQueryString);
                auto requiredQueryPairs = parseQuery(mountQueryString);
                std::string_view requestPath;
                std::string_view requestQueryString;
                splitPathAndQuery(controller.getRequest()->originalUrl, requestPath, requestQueryString);
                auto requestQueryPairs = parseQuery(requestQueryString);
                // End-anchored equality (verbs) with one trailing slash relaxed when !strict
                std::string_view normalizedMountPath = mountPath;
                std::string_view normalizedRequestPath = requestPath;
                if (!controller.getStrictRouting()) {
                    normalizedMountPath = trimOneTrailingSlash(normalizedMountPath);
                    normalizedRequestPath = trimOneTrailingSlash(normalizedRequestPath);
                }
                if (normalizedMountPath.empty()) {
                    normalizedMountPath = "/";
                }
                bool pathMatches = false;
                if (mountPath.find(':') != std::string::npos) {
                    if (regex.mark_count() == 0) {
                        LOG(TRACE) << "ApplicationDispatcher: precompiled regex";
                        std::tie(regex, names) = compileParamRegex(mountPath,
                                                                   /*isPrefix*/ true,
                                                                   controller.getStrictRouting(),
                                                                   controller.getCaseInsensitiveRouting());
                    } else {
                        LOG(TRACE) << "ApplicationDispatcher: using precompiled regex";
                    }
                    pathMatches = matchAndFillParams(regex, names, requestPath, *controller.getRequest());
                } else {
                    pathMatches = equalPath(normalizedRequestPath, normalizedMountPath, controller.getCaseInsensitiveRouting());
                }
                const bool queryMatches = querySupersetMatches(requestQueryPairs, requiredQueryPairs);
                requestMatched = (pathMatches && queryMatches);
                LOG(TRACE) << controller.getResponse()->getSocketContext()->getSocketConnection()->getConnectionName()
                           << " HTTP Express: application -> " << (requestMatched ? "MATCH" : "NO MATCH");
                LOG(TRACE) << "           RequestMethod: " << controller.getRequest()->method;
                LOG(TRACE) << "              RequestUrl: " << controller.getRequest()->url;
                LOG(TRACE) << "             RequestPath: " << controller.getRequest()->path;
                LOG(TRACE) << "       Mountpoint Method: " << mountPoint.method;
                LOG(TRACE) << " Mountpoint RelativePath: " << mountPoint.relativeMountPath;
                LOG(TRACE) << " Mountpoint AbsolutePath: " << absoluteMountPath;
                LOG(TRACE) << "           StrictRouting: " << controller.getStrictRouting();
                LOG(TRACE) << "  CaseInsensitiveRouting: " << controller.getCaseInsensitiveRouting();
                if (requestMatched) {
                    controller.getRequest()->queries.insert(requestQueryPairs.begin(), requestQueryPairs.end());
                    if (hasResult(absoluteMountPath)) {
                        setParams(absoluteMountPath, *controller.getRequest());
                    }
                    lambda(controller.getRequest(), controller.getResponse());
                }
            } else {
                LOG(TRACE) << controller.getResponse()->getSocketContext()->getSocketConnection()->getConnectionName()
                           << " HTTP Express: application -> next(...) called";
                LOG(TRACE) << "           RequestMethod: " << controller.getRequest()->method;
                LOG(TRACE) << "              RequestUrl: " << controller.getRequest()->url;
                LOG(TRACE) << "             RequestPath: " << controller.getRequest()->path;
                LOG(TRACE) << "       AbsoluteMountPath: " << absoluteMountPath;
            }
        }
        return requestMatched;
    }
References express::dispatcher::compileParamRegex(), express::dispatcher::equalPath(), express::Controller::getCaseInsensitiveRouting(), core::socket::stream::SocketConnection::getConnectionName(), express::Controller::getFlags(), express::Controller::getRequest(), express::Controller::getResponse(), core::socket::stream::SocketContext::getSocketConnection(), express::Response::getSocketContext(), express::Controller::getStrictRouting(), express::dispatcher::hasResult(), lambda, express::dispatcher::matchAndFillParams(), express::MountPoint::method, express::Request::method, names, express::Controller::NEXT, express::Request::originalUrl, express::dispatcher::parseQuery(), express::Request::path, express::Request::queries, express::dispatcher::querySupersetMatches(), express::MountPoint::relativeMountPath, express::dispatcher::setParams(), express::dispatcher::splitPathAndQuery(), express::dispatcher::trimOneTrailingSlash(), and express::Request::url.
getRoutes()
std::list< std::string > express::dispatcher::ApplicationDispatcher::getRoutes (const std::string & parentMountPath, const MountPoint & mountPoint, bool strictRouting) const override private virtual
Implements express::Dispatcher.
Definition at line 154 of file ApplicationDispatcher.cpp.
{
        std::list<std::string> routes{"A " + parentMountPath + mountPoint.relativeMountPath + (!strictRouting ? "*" : "")};
        routes.push_back("  " + mountPoint.method + " " + mountPoint.relativeMountPath);
        if (nextRoute) {
            routes.splice(routes.end(), nextRoute->getRoute(parentMountPath, strictRouting));
        }
        return routes;
    }
References express::Route::getRoute(), express::MountPoint::method, express::Dispatcher::nextRoute, and express::MountPoint::relativeMountPath.
Member Data Documentation
lambda
const std::function<void(const std::shared_ptr<Request>&, const std::shared_ptr<Response>&)> express::dispatcher::ApplicationDispatcher::lambda private
Definition at line 74 of file ApplicationDispatcher.h.
Referenced by ApplicationDispatcher(), and dispatch().
names
std::vector<std::string> express::dispatcher::ApplicationDispatcher::names private
Definition at line 77 of file ApplicationDispatcher.h.
Referenced by dispatch().
regex
std::regex express::dispatcher::ApplicationDispatcher::regex private
Definition at line 76 of file ApplicationDispatcher.h.
The documentation for this class was generated from the following files:
express/dispatcher/ApplicationDispatcher.h
express/dispatcher/ApplicationDispatcher.cpp