SNode.C: net::un::config::ConfigAddress< ConfigAddressTypeT > Class Template Reference
net::un::config::ConfigAddress< ConfigAddressTypeT > Class Template Reference
#include <ConfigAddress.h>
Public Member Functions
ConfigAddress & setSocketAddress (const SocketAddress &socketAddress)
ConfigAddress & setSunPath (const std::string &sunPath)
std::string getSunPath () const
Protected Member Functions
ConfigAddress (net::config::ConfigInstance *instance, const std::string &addressOptionName, const std::string &addressOptionDescription)
ConfigAddress & sunPathRequired (bool required=true)
Private Types
using Super = ConfigAddressTypeT< net::un::SocketAddress >
Private Member Functions
SocketAddress * init () final
Private Attributes
CLI::Option * sunPathOpt = nullptr
Detailed Description
template<template< typename SocketAddressT > typename ConfigAddressTypeT>
class net::un::config::ConfigAddress< ConfigAddressTypeT >
Definition at line 76 of file ConfigAddress.h.
Member Typedef Documentation
Super
template<template< typename SocketAddressT > typename ConfigAddressTypeT> using net::un::config::ConfigAddress< ConfigAddressTypeT >::Super = ConfigAddressTypeT<net::un::SocketAddress> private
Definition at line 78 of file ConfigAddress.h.
Constructor & Destructor Documentation
ConfigAddress()
template<template< typename SocketAddress > typename ConfigAddressType> net::un::config::ConfigAddress< ConfigAddressType >::ConfigAddress (net::config::ConfigInstance * instance, const std::string & addressOptionName, const std::string & addressOptionDescription) explicit protected
Definition at line 62 of file ConfigAddress.cpp.
        : Super(instance, addressOptionName, addressOptionDescription) {
        sunPathOpt = Super::addOption( //
            "--sun-path",
            "Unix domain bind path",
            "filename:FILE",
            std::string('\0' + instance->getInstanceName() + std::to_string(getpid()) + "_" + utils::Uuid::getUuid()));
    }
References net::config::ConfigInstance::getInstanceName(), utils::Uuid::getUuid(), and net::un::config::ConfigAddress< ConfigAddressTypeT >::sunPathOpt.
Member Function Documentation
getSunPath()
template<template< typename SocketAddress > typename ConfigAddressType> std::string net::un::config::ConfigAddress< ConfigAddressType >::getSunPath () const
Definition at line 109 of file ConfigAddress.cpp.
{
        return sunPathOpt->as<std::string>();
    }
References net::un::config::ConfigAddress< ConfigAddressTypeT >::sunPathOpt.
init()
template<template< typename SocketAddress > typename ConfigAddressType> SocketAddress * net::un::config::ConfigAddress< ConfigAddressType >::init () final private
Definition at line 74 of file ConfigAddress.cpp.
{
        SocketAddress* socketAddress = new SocketAddress(sunPathOpt->as<std::string>());
        try {
            socketAddress->init();
        } catch (const core::socket::SocketAddress::BadSocketAddress&) {
            delete socketAddress;
            socketAddress = nullptr;
            throw;
        }
        return socketAddress;
    }
References net::un::SocketAddress::init(), net::un::SocketAddress::SocketAddress(), and net::un::config::ConfigAddress< ConfigAddressTypeT >::sunPathOpt.
setSocketAddress()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::un::config::ConfigAddress< ConfigAddressType >::setSocketAddress (const SocketAddress & socketAddress)
Definition at line 90 of file ConfigAddress.cpp.
{
        setSunPath(socketAddress.getSunPath());
        return *this;
    }
References net::un::SocketAddress::getSunPath(), and net::un::config::ConfigAddress< ConfigAddressTypeT >::setSunPath().
setSunPath()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::un::config::ConfigAddress< ConfigAddressType >::setSunPath (const std::string & sunPath)
Definition at line 97 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        sunPathOpt //
            ->default_val(sunPath)
            ->clear();
        Super::required(sunPathOpt, false);
        return *this;
    }
References net::un::config::ConfigAddress< ConfigAddressTypeT >::sunPathOpt.
Referenced by net::un::config::ConfigAddress< ConfigAddressTypeT >::setSocketAddress().
sunPathRequired()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::un::config::ConfigAddress< ConfigAddressType >::sunPathRequired (bool required = true) protected
Definition at line 114 of file ConfigAddress.cpp.
{
        Super::required(sunPathOpt, required);
        return *this;
    }
References net::un::config::ConfigAddress< ConfigAddressTypeT >::sunPathOpt.
Referenced by net::un::stream::config::ConfigSocketClient::ConfigSocketClient(), and net::un::stream::config::ConfigSocketServer::ConfigSocketServer().
Member Data Documentation
sunPathOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::un::config::ConfigAddress< ConfigAddressTypeT >::sunPathOpt = nullptr private
Definition at line 98 of file ConfigAddress.h.
Referenced by net::un::config::ConfigAddress< ConfigAddressTypeT >::ConfigAddress(), net::un::config::ConfigAddress< ConfigAddressTypeT >::getSunPath(), net::un::config::ConfigAddress< ConfigAddressTypeT >::init(), net::un::config::ConfigAddress< ConfigAddressTypeT >::setSunPath(), and net::un::config::ConfigAddress< ConfigAddressTypeT >::sunPathRequired().
The documentation for this class was generated from the following files:
net/un/config/ConfigAddress.h
net/un/config/ConfigAddress.cpp