SNode.C: web::http::client::Client< SocketClientT, RequestT, ResponseT > Class Template Reference
web::http::client::Client< SocketClientT, RequestT, ResponseT > Class Template Reference
#include <Client.h>
Public Types
using Request = RequestT
using Response = ResponseT
using SocketConnection = typename Super::SocketConnection
using SocketAddress = typename Super::SocketAddress
Public Member Functions
Client (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, std::function< void(const std::shared_ptr< Request > &)> &&onRequestBegin, std::function< void(const std::shared_ptr< Request > &)> &&onRequestEnd)
Client (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, std::function< void(const std::shared_ptr< Request > &)> &&onRequestBegin, std::function< void(const std::shared_ptr< Request > &)> &&onRequestEnd)
Client (const std::string &name, std::function< void(const std::shared_ptr< Request > &)> &&onRequestBegin, std::function< void(const std::shared_ptr< Request > &)> &&onRequestEnd)
Client (std::function< void(const std::shared_ptr< Request > &)> &&onRequestBegin, std::function< void(const std::shared_ptr< Request > &)> &&onRequestEnd)
void setPipelinedRequests (bool pipelinedRequests)
Private Types
using Super
Detailed Description
template<template< typename SocketContextFactoryT, typename... Args > typename SocketClientT, typename RequestT, typename ResponseT>
class web::http::client::Client< SocketClientT, RequestT, ResponseT >
Definition at line 35 of file Client.h.
Member Typedef Documentation
Request
template<template< typename SocketContextFactoryT, typename... Args > typename SocketClientT, typename RequestT , typename ResponseT > using web::http::client::Client< SocketClientT, RequestT, ResponseT >::Request = RequestT
Definition at line 41 of file Client.h.
Response
template<template< typename SocketContextFactoryT, typename... Args > typename SocketClientT, typename RequestT , typename ResponseT > using web::http::client::Client< SocketClientT, RequestT, ResponseT >::Response = ResponseT
Definition at line 42 of file Client.h.
SocketAddress
template<template< typename SocketContextFactoryT, typename... Args > typename SocketClientT, typename RequestT , typename ResponseT > using web::http::client::Client< SocketClientT, RequestT, ResponseT >::SocketAddress = typename Super::SocketAddress
Definition at line 52 of file Client.h.
SocketConnection
template<template< typename SocketContextFactoryT, typename... Args > typename SocketClientT, typename RequestT , typename ResponseT > using web::http::client::Client< SocketClientT, RequestT, ResponseT >::SocketConnection = typename Super::SocketConnection
Definition at line 51 of file Client.h.
Super
template<template< typename SocketContextFactoryT, typename... Args > typename SocketClientT, typename RequestT , typename ResponseT > using web::http::client::Client< SocketClientT, RequestT, ResponseT >::Super private
Initial value:
 SocketClientT<web::http::client::SocketContextFactory<Request, Response>,
                                    std::function<void(const std::shared_ptr<Request>&)>,
                                    std::function<void(const std::shared_ptr<RequestT>&)>,
                                    std::function<net::config::ConfigInstance&()>>
Definition at line 45 of file Client.h.
Constructor & Destructor Documentation
Client() [1/4]
template<template< typename SocketContextFactoryT, typename... Args > typename SocketClientT, typename RequestT , typename ResponseT > web::http::client::Client< SocketClientT, RequestT, ResponseT >::Client (const std::string & name, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, std::function< void(const std::shared_ptr< Request > &)> && onRequestBegin, std::function< void(const std::shared_ptr< Request > &)> && onRequestEnd) inline
Definition at line 54 of file Client.h.
            : Super(name,
                    onConnect,
                    onConnected,
                    onDisconnect,
                    std::forward<std::function<void(const std::shared_ptr<Request>&)>>(onRequestBegin),
                    std::forward<std::function<void(const std::shared_ptr<Request>&)>>(onRequestEnd),
                    [this]() -> net::config::ConfigInstance& {
                        return Super::getConfig();
                    }) {
        }
References web::http::client::Client< SocketClientT, RequestT, ResponseT >::Client().
Referenced by web::http::client::Client< SocketClientT, RequestT, ResponseT >::Client().
Client() [2/4]
template<template< typename SocketContextFactoryT, typename... Args > typename SocketClientT, typename RequestT , typename ResponseT > web::http::client::Client< SocketClientT, RequestT, ResponseT >::Client (const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, std::function< void(const std::shared_ptr< Request > &)> && onRequestBegin, std::function< void(const std::shared_ptr< Request > &)> && onRequestEnd) inline
Definition at line 71 of file Client.h.
            : Client("",
                     onConnect,
                     onConnected,
                     onDisconnect,
                     std::forward<std::function<void(const std::shared_ptr<Request>&)>>(onRequestBegin),
                     std::forward<std::function<void(const std::shared_ptr<Request>&)>>(onRequestEnd)) {
        }
References web::http::client::Client< SocketClientT, RequestT, ResponseT >::Client().
Referenced by web::http::client::Client< SocketClientT, RequestT, ResponseT >::Client().
Client() [3/4]
template<template< typename SocketContextFactoryT, typename... Args > typename SocketClientT, typename RequestT , typename ResponseT > web::http::client::Client< SocketClientT, RequestT, ResponseT >::Client (const std::string & name, std::function< void(const std::shared_ptr< Request > &)> && onRequestBegin, std::function< void(const std::shared_ptr< Request > &)> && onRequestEnd) inline
Definition at line 84 of file Client.h.
            : Super(name,
                    std::forward<std::function<void(const std::shared_ptr<Request>&)>>(onRequestBegin),
                    std::forward<std::function<void(const std::shared_ptr<Request>&)>>(onRequestEnd),
                    [this]() -> net::config::ConfigInstance& {
                        return Super::getConfig();
                    }) {
        }
References web::http::client::Client< SocketClientT, RequestT, ResponseT >::Client().
Referenced by web::http::client::Client< SocketClientT, RequestT, ResponseT >::Client().
Client() [4/4]
template<template< typename SocketContextFactoryT, typename... Args > typename SocketClientT, typename RequestT , typename ResponseT > web::http::client::Client< SocketClientT, RequestT, ResponseT >::Client (std::function< void(const std::shared_ptr< Request > &)> && onRequestBegin, std::function< void(const std::shared_ptr< Request > &)> && onRequestEnd) inline
Definition at line 95 of file Client.h.
            : Client("",
                     std::forward<std::function<void(const std::shared_ptr<Request>&)>>(onRequestBegin),
                     std::forward<std::function<void(const std::shared_ptr<Request>&)>>(onRequestEnd)) {
        }
References web::http::client::Client< SocketClientT, RequestT, ResponseT >::Client().
Referenced by web::http::client::Client< SocketClientT, RequestT, ResponseT >::Client().
Member Function Documentation
setPipelinedRequests()
template<template< typename SocketContextFactoryT, typename... Args > typename SocketClientT, typename RequestT , typename ResponseT > void web::http::client::Client< SocketClientT, RequestT, ResponseT >::setPipelinedRequests (bool pipelinedRequests) inline
Definition at line 102 of file Client.h.
{
            Super::getSocketContextFactory()->setPipelinedRequests(pipelinedRequests);
        }
The documentation for this class was generated from the following file:
web/http/client/Client.h