SNode.C: express::Dispatcher Class Reference
express::Dispatcher Class Reference abstract
#include <Dispatcher.h>
Public Member Functions
Dispatcher (const Dispatcher &)=delete
Dispatcher & operator= (const Dispatcher &)=delete
Dispatcher ()=default
virtual ~Dispatcher ()
virtual bool dispatch (Controller &controller, const std::string &parentMountPath, const MountPoint &mountPoint)=0
bool dispatchNext (Controller &controller, const std::string &parentMountPath)
virtual std::list< std::string > getRoutes (const std::string &parentMountPath, const MountPoint &mountPoint, bool strictRouting) const =0
Protected Attributes
std::shared_ptr< Route > nextRoute = nullptr
Friends
class Route
Detailed Description
Definition at line 63 of file Dispatcher.h.
Constructor & Destructor Documentation
Dispatcher() [1/2]
express::Dispatcher::Dispatcher (const Dispatcher &) delete
Dispatcher() [2/2]
express::Dispatcher::Dispatcher () default
~Dispatcher()
express::Dispatcher::~Dispatcher () virtual
Definition at line 52 of file Dispatcher.cpp.
{
    }
Member Function Documentation
dispatch()
virtual bool express::Dispatcher::dispatch (Controller & controller, const std::string & parentMountPath, const MountPoint & mountPoint) pure virtual
Implemented in express::dispatcher::ApplicationDispatcher, express::dispatcher::MiddlewareDispatcher, and express::dispatcher::RouterDispatcher.
Referenced by express::Route::dispatch().
dispatchNext()
bool express::Dispatcher::dispatchNext (Controller & controller, const std::string & parentMountPath)
Definition at line 55 of file Dispatcher.cpp.
{
        bool dispatched = false;
        if (nextRoute != nullptr) {
            dispatched = nextRoute->dispatch(controller, parentMountPath);
        }
        return dispatched;
    }
References express::Route::dispatch(), and nextRoute.
Referenced by express::Route::dispatchNext().
getRoutes()
virtual std::list< std::string > express::Dispatcher::getRoutes (const std::string & parentMountPath, const MountPoint & mountPoint, bool strictRouting) const pure virtual
Implemented in express::dispatcher::ApplicationDispatcher, express::dispatcher::MiddlewareDispatcher, and express::dispatcher::RouterDispatcher.
Referenced by express::Route::getRoute().
operator=()
Dispatcher & express::Dispatcher::operator= (const Dispatcher &) delete
Friends And Related Symbol Documentation
Route
friend class Route friend
Definition at line 83 of file Dispatcher.h.
Member Data Documentation
nextRoute
std::shared_ptr<Route> express::Dispatcher::nextRoute = nullptr protected
Definition at line 80 of file Dispatcher.h.
Referenced by dispatchNext(), express::dispatcher::ApplicationDispatcher::getRoutes(), and express::dispatcher::MiddlewareDispatcher::getRoutes().
The documentation for this class was generated from the following files:
express/Dispatcher.h
express/Dispatcher.cpp