SNode.C: net::config::ConfigAddressBase< SocketAddressT > Class Template Reference
net::config::ConfigAddressBase< SocketAddressT > Class Template Reference
#include <ConfigAddressBase.h>
Public Member Functions
SocketAddressT getSocketAddress (const typename SocketAddressT::SockAddr &sockAddr, typename SocketAddressT::SockLen sockAddrLen)
Protected Types
using Super = ConfigSection
Protected Member Functions
ConfigAddressBase (ConfigInstance *instance, const std::string &addressOptionName="", const std::string &addressOptionDescription="")
virtual ~ConfigAddressBase ()=default
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
Protected Attributes
CLI::App * section = nullptr
Private Attributes
ConfigInstance * instance = nullptr
uint8_t requiredCount = 0
Detailed Description
template<typename SocketAddressT>
class net::config::ConfigAddressBase< SocketAddressT >
Definition at line 40 of file ConfigAddressBase.h.
Member Typedef Documentation
Super
template<typename SocketAddressT > using net::config::ConfigAddressBase< SocketAddressT >::Super = ConfigSection protected
Definition at line 42 of file ConfigAddressBase.h.
Constructor & Destructor Documentation
ConfigAddressBase()
template<typename SocketAddress > net::config::ConfigAddressBase< SocketAddress >::ConfigAddressBase (ConfigInstance * instance, const std::string & addressOptionName = "", const std::string & addressOptionDescription = "") explicit protected
Definition at line 29 of file ConfigAddressBase.hpp.
        : net::config::ConfigSection(instance, addressOptionName, addressOptionDescription) {
    }
~ConfigAddressBase()
template<typename SocketAddressT > virtual net::config::ConfigAddressBase< SocketAddressT >::~ConfigAddressBase () protected virtual default
Member Function Documentation
add_flag() [1/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 110 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag(name, description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [2/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 125 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [3/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 64 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [4/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 71 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [5/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_flag() [6/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag_function() [1/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) protected inherited
Definition at line 134 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [2/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 155 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), and net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient().
add_option() [1/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) protected inherited
Definition at line 79 of file ConfigSection.cpp.
{
        if (!instance->getInstanceName().empty() && !section->get_display_name().empty()) {
            section->disabled(false);
        }
        opt = section //
                  ->add_option(name, description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigInstance::getInstanceName(), net::config::ConfigSection::instance, and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [2/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 95 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [3/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 100 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [4/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 46 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [5/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 53 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [6/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
Referenced by net::config::ConfigTls::ConfigTls().
add_option() [7/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
getSocketAddress()
template<typename SocketAddressT > SocketAddress net::config::ConfigAddressBase< SocketAddress >::getSocketAddress (const typename SocketAddressT::SockAddr & sockAddr, typename SocketAddressT::SockLen sockAddrLen)
Definition at line 36 of file ConfigAddressBase.hpp.
{
        return SocketAddress(sockAddr, sockAddrLen);
    }
required() [1/2]
bool net::config::ConfigSection::required () const protected inherited
Definition at line 75 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [2/2]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) protected inherited
Definition at line 58 of file ConfigSection.cpp.
{
        if (req != opt->get_required()) {
            if (req) {
                ++requiredCount;
                section->needs(opt);
                opt->default_str("");
            } else {
                --requiredCount;
                section->remove_needs(opt);
            }
            opt->required(req);
            instance->required(section, requiredCount > 0);
        }
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
Member Data Documentation
instance
ConfigInstance* net::config::ConfigSection::instance = nullptr private inherited
Definition at line 121 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), and net::config::ConfigSection::required().
requiredCount
uint8_t net::config::ConfigSection::requiredCount = 0 private inherited
Definition at line 123 of file ConfigSection.h.
Referenced by net::config::ConfigSection::required(), and net::config::ConfigSection::required().
section
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 126 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
The documentation for this class was generated from the following files:
net/config/ConfigAddressBase.h
net/config/ConfigAddressBase.hpp