SNode.C: net::SocketAddress< SockAddrT > Class Template Reference
net::SocketAddress< SockAddrT > Class Template Reference
#include <SocketAddress.h>
Public Types
using SockAddr = SockAddrT
using SockLen = socklen_t
Public Member Functions
SocketAddress (sa_family_t af, SockLen sockAddrLen=sizeof(SockAddr))
SocketAddress (const SocketAddress &socketAddress)
SocketAddress (const SockAddr &sockAddr, SockLen sockAddrLen)
SocketAddress & operator= (const SocketAddress &socketAddress)
const sockaddr & getSockAddr ()
const SockLen & getSockAddrLen () const
sa_family_t getAddressFamily () const
Public Member Functions inherited from core::socket::SocketAddress
virtual ~SocketAddress ()
virtual bool useNext ()
virtual std::string toString (bool expanded=true) const =0
virtual std::string getEndpoint (const std::string_view &format={}) const
Protected Attributes
SockAddr sockAddr {}
SockLen sockAddrLen = 0
Detailed Description
template<typename SockAddrT>
class net::SocketAddress< SockAddrT >
Definition at line 57 of file SocketAddress.h.
Member Typedef Documentation
SockAddr
template<typename SockAddrT> using net::SocketAddress< SockAddrT >::SockAddr = SockAddrT
Definition at line 59 of file SocketAddress.h.
SockLen
template<typename SockAddrT> using net::SocketAddress< SockAddrT >::SockLen = socklen_t
Definition at line 60 of file SocketAddress.h.
Constructor & Destructor Documentation
SocketAddress() [1/3]
template<typename SockAddr> net::SocketAddress< SockAddr >::SocketAddress (sa_family_t af, SockLen sockAddrLen = sizeof(SockAddr)) explicit
Definition at line 53 of file SocketAddress.hpp.
        : sockAddrLen(sockAddrLen) {
        std::memset(&sockAddr, 0, sizeof(sockAddr));
        reinterpret_cast<sockaddr*>(&sockAddr)->sa_family = af;
    }
References sockAddr, and sockAddrLen.
Referenced by net::in6::SocketAddress::SocketAddress(), net::in::SocketAddress::SocketAddress(), net::l2::SocketAddress::SocketAddress(), net::rc::SocketAddress::SocketAddress(), and net::un::SocketAddress::SocketAddress().
SocketAddress() [2/3]
template<typename SockAddr> net::SocketAddress< SockAddr >::SocketAddress (const SocketAddress< SockAddrT > & socketAddress)
Definition at line 60 of file SocketAddress.hpp.
        : sockAddr(socketAddress.sockAddr)
        , sockAddrLen(socketAddress.sockAddrLen) {
    }
References sockAddr, and sockAddrLen.
SocketAddress() [3/3]
template<typename SockAddr> net::SocketAddress< SockAddr >::SocketAddress (const SockAddr & sockAddr, SockLen sockAddrLen)
Definition at line 66 of file SocketAddress.hpp.
        : sockAddr(sockAddr)
        , sockAddrLen(sockAddrLen) {
    }
References sockAddr, and sockAddrLen.
Referenced by net::in6::SocketAddress::SocketAddress(), net::in::SocketAddress::SocketAddress(), net::l2::SocketAddress::SocketAddress(), net::rc::SocketAddress::SocketAddress(), and net::un::SocketAddress::SocketAddress().
Member Function Documentation
getAddressFamily()
template<typename SockAddr> sa_family_t net::SocketAddress< SockAddr >::getAddressFamily () const
Definition at line 92 of file SocketAddress.hpp.
{
        return reinterpret_cast<const sockaddr*>(&sockAddr)->sa_family;
    }
References sockAddr.
Referenced by net::in6::SocketAddress::init(), and net::in::SocketAddress::init().
getSockAddr()
template<typename SockAddr> const sockaddr & net::SocketAddress< SockAddr >::getSockAddr ()
Definition at line 82 of file SocketAddress.hpp.
{
        return reinterpret_cast<const sockaddr&>(sockAddr);
    }
References sockAddr.
Referenced by net::un::dgram::Socket::sendFd().
getSockAddrLen()
template<typename SockAddr> const SocketAddress< SockAddr >::SockLen & net::SocketAddress< SockAddr >::getSockAddrLen () const
Definition at line 87 of file SocketAddress.hpp.
{
        return sockAddrLen;
    }
References sockAddrLen.
Referenced by net::un::dgram::Socket::sendFd().
operator=()
template<typename SockAddr> SocketAddress< SockAddr > & net::SocketAddress< SockAddr >::operator= (const SocketAddress< SockAddrT > & socketAddress)
Definition at line 72 of file SocketAddress.hpp.
{
        if (this != &socketAddress) {
            this->sockAddr = socketAddress.sockAddr;
            this->sockAddrLen = socketAddress.sockAddrLen;
        }
        return *this;
    }
References sockAddr, and sockAddrLen.
Member Data Documentation
sockAddr
template<typename SockAddrT> SockAddr net::SocketAddress< SockAddrT >::sockAddr {} protected
Definition at line 76 of file SocketAddress.h.
{};
Referenced by getAddressFamily(), getSockAddr(), operator=(), SocketAddress(), SocketAddress(), and SocketAddress().
sockAddrLen
template<typename SockAddrT> SockLen net::SocketAddress< SockAddrT >::sockAddrLen = 0 protected
Definition at line 77 of file SocketAddress.h.
Referenced by getSockAddrLen(), operator=(), SocketAddress(), SocketAddress(), and SocketAddress().
The documentation for this class was generated from the following files:
net/SocketAddress.h
net/SocketAddress.hpp