SNode.C: utils::SubCommand Class Reference
utils::SubCommand Class Reference
#include <SubCommand.h>
Public Member Functions
SubCommand (const SubCommand &)=delete
SubCommand (SubCommand &&)=delete
SubCommand & operator= (const SubCommand &)=delete
SubCommand & operator= (SubCommand &&)=delete
virtual ~SubCommand ()
std::string getName () const
std::string version () const
void parse (int argc, char *argv[])
CLI::Option * setConfig (const std::string &defaultConfigFile) const
CLI::Option * setLogFile (const std::string &defaultLogFile) const
CLI::Option * setVersionFlag (const std::string &version) const
bool hasParent () const
SubCommand * getParent ()
SubCommand * allowExtras (bool allow=true)
SubCommand * required (bool required=true, bool force=true)
SubCommand * required (SubCommand *subCommand, bool required=true)
SubCommand * required (CLI::Option *option, bool required=true)
SubCommand * needs (SubCommand *subCommand, bool needs=true)
SubCommand * disabled (SubCommand *subCommand, bool disabled=true)
SubCommand * setRequireCallback (const std::function< void(void)> &callback)
SubCommand * finalCallback (const std::function< void()> &finalCallback)
std::string configToStr () const
std::string help (const CLI::App *helpApp, const CLI::AppFormatMode &mode) const
template<typename NewSubCommand, typename... Args>
NewSubCommand * newSubCommand (Args &&... args)
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand ()
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand () const
CLI::Option * getOption (const std::string &name) const
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator) const
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Static Public Member Functions
static CLI::App * getHelpTriggerApp ()
static CLI::App * getShowConfigTriggerApp ()
static CLI::App * getCommandlineTriggerApp ()
Static Public Attributes
static std::shared_ptr< CLI::Formatter > sectionFormatter = makeSectionFormatter()
Protected Member Functions
SubCommand (SubCommand *parent, std::shared_ptr< utils::AppWithPtr > appWithPtr, const std::string &group, bool final)
template<typename ConcretSubCommand>
SubCommand (SubCommand *parent, ConcretSubCommand *concretSubCommand, const std::string &group, bool final=true)
SubCommand * description (const std::string &description)
SubCommand * footer (const std::string &footer)
template<typename ValueTypeT>
CLI::Option * setDefaultValue (CLI::Option *option, const ValueTypeT &value, bool clear=true) const
CLI::Option * setConfigurable (CLI::Option *option, bool configurable) const
Static Protected Attributes
static std::map< std::string, std::string > aliases
static CLI::App * helpTriggerApp = nullptr
static CLI::App * showConfigTriggerApp = nullptr
static CLI::App * commandlineTriggerApp = nullptr
Private Member Functions
CLI::Option * initialize (CLI::Option *option, const std::string &typeName, const CLI::Validator &validator, bool configurable) const
Private Attributes
AppWithPtr * subCommandApp
SubCommand * parent
bool final
CLI::Option * helpOpt = nullptr
CLI::Option * showConfigOpt = nullptr
CLI::Option * commandlineOpt = nullptr
int requiredCount = 0
Detailed Description
Definition at line 96 of file SubCommand.h.
Constructor & Destructor Documentation
SubCommand() [1/4]
utils::SubCommand::SubCommand (SubCommand * parent, std::shared_ptr< utils::AppWithPtr > appWithPtr, const std::string & group, bool final) protected
Definition at line 57 of file SubCommand.cpp.
        : subCommandApp(appWithPtr.get())
        , parent(parent)
        , final(final) {
        if (appWithPtr != nullptr) {
            if (parent != nullptr) {
                parent->subCommandApp->add_subcommand(appWithPtr);
            }
            subCommandApp->group(group);
            subCommandApp->configurable(false);
            subCommandApp->allow_extras();
            static const std::shared_ptr<CLI::HelpFormatter> helpFormatter = std::make_shared<CLI::HelpFormatter>();
            helpFormatter->label("SUBCOMMAND", "INSTANCE");
            helpFormatter->label("SUBCOMMANDS", "INSTANCES");
            helpFormatter->label("PERSISTENT", "");
            helpFormatter->label("Persistent Options", "Options (persistent)");
            helpFormatter->label("Nonpersistent Options", "Options (nonpersistent)");
            helpFormatter->label("Usage", "\nUsage");
            helpFormatter->label("bool:{true,false}", "{true,false}");
            helpFormatter->label(":{standard,active,complete,required}", "{standard,active,complete,required}");
            helpFormatter->label(":{standard,exact,expanded}", "{standard,exact,expanded}");
            helpFormatter->column_width(7);
            subCommandApp->formatter(helpFormatter);
            static const std::shared_ptr<CLI::Config> configFormatter = std::make_shared<CLI::ConfigFormatter>();
            subCommandApp->config_formatter(configFormatter);
            subCommandApp->option_defaults()->take_last()->group(subCommandApp->get_formatter()->get_label("Nonpersistent Options"));
            if (!final) {
                helpOpt = setConfigurable(subCommandApp
                                              ->set_help_flag(
                                                  "--help{exact},-h{exact}",
                                                  [subCommandApp = this->subCommandApp](std::size_t) {
                                                      helpTriggerApp = subCommandApp;
                                                  },
                                                  "Print help message and exit\n"
                                                  "* standard: display help for the last command processed\n"
                                                  "* exact: display help for the command directly preceding --help")
                                              ->take_first()
                                              ->check(CLI::IsMember({"standard", "exact", "expanded"}))
                                              ->trigger_on_parse(),
                                          false);
            } else {
                helpOpt = setConfigurable(subCommandApp
                                              ->set_help_flag(
                                                  "--help{exact},-h{exact}",
                                                  [subCommandApp = this->subCommandApp](std::size_t) {
                                                      helpTriggerApp = subCommandApp;
                                                  },
                                                  "Print help message and exit\n"
                                                  "* standard: display help for the last command processed\n"
                                                  "* exact: display help for the command directly preceding --help")
                                              ->take_first()
                                              ->check(CLI::IsMember({"standard", "exact"}))
                                              ->trigger_on_parse(),
                                          false);
            }
            showConfigOpt = setConfigurable(subCommandApp
                                                ->add_flag_function(
                                                    "-s,--show-config",
                                                    [subCommandApp = this->subCommandApp](std::size_t) {
                                                        showConfigTriggerApp = subCommandApp;
                                                    },
                                                    "Show current configuration and exit")
                                                ->take_first()
                                                ->disable_flag_override()
                                                ->configurable(false)
                                                ->trigger_on_parse(),
                                            false);
            commandlineOpt = setConfigurable(subCommandApp
                                                 ->add_flag_function(
                                                     "--command-line{standard}",
                                                     [subCommandApp = this->subCommandApp]([[maybe_unused]] std::int64_t count) {
                                                         commandlineTriggerApp = subCommandApp;
                                                     },
                                                     "Print command-line\n"
                                                     "* standard (default): Show all non-default and required options\n"
                                                     "* active: Show all active options\n"
                                                     "* complete: Show the complete option set with default values\n"
                                                     "* required: Show only required options")
                                                 ->take_first()
                                                 ->check(CLI::IsMember({"standard", "active", "complete", "required"}))
                                                 ->trigger_on_parse(),
                                             false);
        }
    }
References commandlineOpt, commandlineTriggerApp, final, helpOpt, helpTriggerApp, parent, setConfigurable(), showConfigOpt, showConfigTriggerApp, and subCommandApp.
Referenced by net::config::ConfigInstance::ConfigInstance(), and utils::ConfigRoot::ConfigRoot().
SubCommand() [2/4]
template<typename ConcretSubCommand> utils::SubCommand::SubCommand (SubCommand * parent, ConcretSubCommand * concretSubCommand, const std::string & group, bool final = true) inline protected
Definition at line 257 of file SubCommand.h.
        : SubCommand(parent,
                     std::make_shared<utils::AppWithPtr>(
                         std::string(ConcretSubCommand::DESCRIPTION), std::string(ConcretSubCommand::NAME), concretSubCommand, true),
                     group,
                     final) {
    }
Referenced by web::http::client::ConfigHTTP::ConfigHTTP(), and subcommand::ConfigWWW::ConfigWWW().
SubCommand() [3/4]
utils::SubCommand::SubCommand (const SubCommand &) delete
SubCommand() [4/4]
utils::SubCommand::SubCommand (SubCommand &&) delete
~SubCommand()
utils::SubCommand::~SubCommand () virtual
Definition at line 152 of file SubCommand.cpp.
{
    }
Member Function Documentation
addFlag() [1/2]
CLI::Option * utils::SubCommand::addFlag (const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & validator) const
Definition at line 396 of file SubCommand.cpp.
{
        return initialize(subCommandApp //
                              ->add_flag(name, description),
                          typeName,
                          validator,
                          !subCommandApp->get_disabled());
    }
References initialize(), and subCommandApp.
Referenced by addFlag(), and utils::ConfigRoot::addRootOptions().
addFlag() [2/2]
template<typename ValueTypeT> CLI::Option * utils::SubCommand::addFlag (const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & validator) const
Definition at line 328 of file SubCommand.h.
{
        return setDefaultValue(addFlag(name, description, typeName, additionalValidator), defaultValue);
    }
References addFlag().
Referenced by utils::ConfigRoot::addRootOptions(), web::http::client::ConfigHTTP::ConfigHTTP(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
addFlagFunction() [1/2]
CLI::Option * utils::SubCommand::addFlagFunction (const std::string & name, const std::function< void()> & callback, const std::string & description, const std::string & typeName, const CLI::Validator & validator)
Definition at line 407 of file SubCommand.cpp.
{
        CLI::Option* opt = subCommandApp //
                               ->add_flag_function(
                                   name,
                                   [callback](std::int64_t) {
                                       callback();
                                   },
                                   description)
                               ->type_name(typeName)
                               ->check(validator)
                               ->take_last();
        if (opt->get_configurable()) {
            opt->group(subCommandApp->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References subCommandApp.
Referenced by addFlagFunction().
addFlagFunction() [2/2]
CLI::Option * utils::SubCommand::addFlagFunction (const std::string & name, const std::function< void()> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator)
Definition at line 429 of file SubCommand.cpp.
{
        return setDefaultValue(addFlagFunction(name, callback, description, typeName, validator), defaultValue);
    }
References addFlagFunction(), and setDefaultValue().
Referenced by utils::ConfigRoot::addRootOptions(), net::config::ConfigPhysicalSocket::addSocketOption(), net::config::ConfigInstance::ConfigInstance(), and net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient().
addOption() [1/2]
CLI::Option * utils::SubCommand::addOption (const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & validator) const
Definition at line 373 of file SubCommand.cpp.
{
        return initialize(subCommandApp //
                              ->add_option(name, description),
                          typeName,
                          validator,
                          !subCommandApp->get_disabled());
    }
References initialize(), and subCommandApp.
Referenced by addOption(), utils::ConfigRoot::addRootOptions(), web::http::client::ConfigHTTP::ConfigHTTP(), net::config::ConfigTls::ConfigTls(), net::config::ConfigTlsClient::ConfigTlsClient(), and subcommand::ConfigWWW::ConfigWWW().
addOption() [2/2]
template<typename ValueTypeT> CLI::Option * utils::SubCommand::addOption (const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & validator) const
Definition at line 289 of file SubCommand.h.
{
        return setDefaultValue(addOption(name, description, typeName, additionalValidator), defaultValue);
    }
References addOption().
Referenced by utils::ConfigRoot::addRootOptions(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigTls::ConfigTls(), and setLogFile().
addOptionFunction() [1/2]
CLI::Option * utils::SubCommand::addOptionFunction (const std::string & name, std::function< void(const std::string &)> & callback, const std::string & description, const std::string & typeName, const CLI::Validator & validator) const
Definition at line 384 of file SubCommand.cpp.
{
        return initialize(subCommandApp //
                              ->add_option_function(name, callback, description),
                          typeName,
                          validator,
                          !subCommandApp->get_disabled());
    }
References initialize(), and subCommandApp.
Referenced by addOptionFunction().
addOptionFunction() [2/2]
template<typename ValueTypeT> CLI::Option * utils::SubCommand::addOptionFunction (const std::string & name, std::function< void(const std::string &)> & callback, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & validator) const
Definition at line 318 of file SubCommand.h.
{
        return setDefaultValue(addOptionFunction(name, callback, description, typeName, validator), defaultValue);
    }
References addOptionFunction().
addOptionVariable() [1/2]
template<typename ValueTypeT> CLI::Option * utils::SubCommand::addOptionVariable (const std::string & name, ValueTypeT & variable, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) const
Definition at line 298 of file SubCommand.h.
{
        return initialize(
            subCommandApp->add_option(name, variable, description), typeName, additionalValidator, !subCommandApp->get_disabled());
    }
References initialize(), and subCommandApp.
Referenced by net::config::ConfigTlsServer::ConfigTlsServer().
addOptionVariable() [2/2]
template<typename ValueTypeT> CLI::Option * utils::SubCommand::addOptionVariable (const std::string & name, ValueTypeT & variable, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) const
Definition at line 308 of file SubCommand.h.
{
        return setDefaultValue(addOptionVariable(name, variable, description, typeName, additionalValidator), defaultValue);
    }
allowExtras()
SubCommand * utils::SubCommand::allowExtras (bool allow = true)
Definition at line 213 of file SubCommand.cpp.
{
        subCommandApp->allow_extras(allow);
        return this;
    }
References subCommandApp.
Referenced by utils::ConfigRoot::parse1().
configToStr()
std::string utils::SubCommand::configToStr () const
Definition at line 342 of file SubCommand.cpp.
{
        return subCommandApp->config_to_str(true, true);
    }
References subCommandApp.
Referenced by utils::doWriteConfig().
description()
SubCommand * utils::SubCommand::description (const std::string & description) protected
Definition at line 167 of file SubCommand.cpp.
{
        subCommandApp->description(description);
        return this;
    }
References subCommandApp.
Referenced by utils::ConfigRoot::addRootOptions(), and net::config::ConfigSection::ConfigSection().
disabled()
SubCommand * utils::SubCommand::disabled (SubCommand * subCommand, bool disabled = true)
Definition at line 306 of file SubCommand.cpp.
{
        if (disabled) {
            if (subCommand->subCommandApp->get_ignore_case()) {
                needs(subCommand, false);
            }
            for (const auto& sub : subCommand->subCommandApp->get_subcommands({})) {
                if (sub->get_ignore_case()) {
                    subCommand->subCommandApp->remove_needs(sub);
                    sub->required(false);
                }
            }
        } else {
            if (subCommand->subCommandApp->get_ignore_case()) {
                needs(subCommand);
            }
            for (const auto& sub : subCommand->subCommandApp->get_subcommands({})) {
                if (sub->get_ignore_case()) {
                    subCommand->subCommandApp->needs(sub);
                    sub->required();
                }
            }
        }
        subCommand->subCommandApp->required(disabled ? false : subCommand->subCommandApp->get_ignore_case());
        return this;
    }
References needs(), and subCommandApp.
Referenced by net::config::ConfigInstance::ConfigInstance(), and net::config::ConfigInstance::setDisabled().
finalCallback()
SubCommand * utils::SubCommand::finalCallback (const std::function< void()> & finalCallback)
Definition at line 336 of file SubCommand.cpp.
{
        subCommandApp->final_callback(finalCallback);
        return this;
    }
References subCommandApp.
Referenced by utils::ConfigRoot::bootstrap(), and net::config::ConfigTlsServer::ConfigTlsServer().
footer()
SubCommand * utils::SubCommand::footer (const std::string & footer) protected
Definition at line 173 of file SubCommand.cpp.
{
        subCommandApp->footer(footer);
        return this;
    }
References subCommandApp.
Referenced by utils::ConfigRoot::addRootOptions().
getCommandlineTriggerApp()
CLI::App * utils::SubCommand::getCommandlineTriggerApp () static
Definition at line 219 of file SubCommand.cpp.
{
        return commandlineTriggerApp;
    }
References commandlineTriggerApp.
getHelpTriggerApp()
CLI::App * utils::SubCommand::getHelpTriggerApp () static
Definition at line 227 of file SubCommand.cpp.
{
        return helpTriggerApp;
    }
References helpTriggerApp.
getName()
std::string utils::SubCommand::getName () const
Definition at line 155 of file SubCommand.cpp.
{
        return subCommandApp->get_name();
    }
References subCommandApp.
Referenced by net::config::ConfigTlsServer::ConfigTlsServer().
getOption()
CLI::Option * utils::SubCommand::getOption (const std::string & name) const
Definition at line 369 of file SubCommand.cpp.
{
        return subCommandApp->get_option_no_throw(name);
    }
References subCommandApp.
Referenced by net::config::ConfigPhysicalSocket::addSocketOption(), utils::doWriteConfig(), utils::getHelp(), and utils::ConfigRoot::parse2().
getParent()
SubCommand * utils::SubCommand::getParent ()
Definition at line 203 of file SubCommand.cpp.
{
        return parent;
    }
References parent.
Referenced by net::config::ConfigTlsServer::ConfigTlsServer(), and required().
getShowConfigTriggerApp()
CLI::App * utils::SubCommand::getShowConfigTriggerApp () static
Definition at line 223 of file SubCommand.cpp.
{
        return showConfigTriggerApp;
    }
References showConfigTriggerApp.
getSubCommand() [1/2]
template<typename RequestedSubCommand> RequestedSubCommand * utils::SubCommand::getSubCommand ()
Definition at line 271 of file SubCommand.h.
{
        auto* appWithPtr = subCommandApp->get_subcommand_no_throw(std::string(RequestedSubCommand::NAME));
        AppWithPtr* subCommandApp = dynamic_cast<utils::AppWithPtr*>(appWithPtr);
        return subCommandApp != nullptr ? dynamic_cast<RequestedSubCommand*>(subCommandApp->getPtr()) : nullptr;
    }
References utils::AppWithPtr::getPtr(), and subCommandApp.
Referenced by web::http::client::SocketContextFactory::create(), and main().
getSubCommand() [2/2]
template<typename RequestedSubCommand> RequestedSubCommand * utils::SubCommand::getSubCommand () const
Definition at line 280 of file SubCommand.h.
{
        auto* appWithPtr = subCommandApp->get_subcommand_no_throw(std::string(RequestedSubCommand::NAME));
        AppWithPtr* subCommandApp = dynamic_cast<utils::AppWithPtr*>(appWithPtr);
        return subCommandApp != nullptr ? dynamic_cast<RequestedSubCommand*>(subCommandApp->getPtr()) : nullptr;
    }
References utils::AppWithPtr::getPtr(), and subCommandApp.
hasParent()
bool utils::SubCommand::hasParent () const
Definition at line 199 of file SubCommand.cpp.
{
        return subCommandApp->get_parent() != nullptr;
    }
References subCommandApp.
help()
std::string utils::SubCommand::help (const CLI::App * helpApp, const CLI::AppFormatMode & mode) const
Definition at line 346 of file SubCommand.cpp.
{
        return subCommandApp->help(helpApp, "", mode);
    }
References subCommandApp.
Referenced by utils::getHelp().
initialize()
CLI::Option * utils::SubCommand::initialize (CLI::Option * option, const std::string & typeName, const CLI::Validator & validator, bool configurable) const private
Definition at line 445 of file SubCommand.cpp.
{
        return setConfigurable(option, configurable) //
            ->type_name(typeName)
            ->check(validator);
    }
References setConfigurable().
Referenced by addFlag(), addOption(), addOptionFunction(), and addOptionVariable().
needs()
SubCommand * utils::SubCommand::needs (SubCommand * subCommand, bool needs = true)
Definition at line 296 of file SubCommand.cpp.
{
        if (needs) {
            subCommandApp->needs(subCommand->subCommandApp);
        } else {
            subCommandApp->remove_needs(subCommand->subCommandApp);
        }
        return this;
    }
References subCommandApp.
Referenced by disabled(), required(), and required().
newSubCommand()
template<typename NewSubCommand, typename... Args> NewSubCommand * utils::SubCommand::newSubCommand (Args &&... args)
Definition at line 266 of file SubCommand.h.
{
        return !final ? new NewSubCommand(this, std::forward(args)...) : nullptr;
    }
References final.
Referenced by main().
operator=() [1/2]
SubCommand & utils::SubCommand::operator= (const SubCommand &) delete
operator=() [2/2]
SubCommand & utils::SubCommand::operator= (SubCommand &&) delete
parse()
void utils::SubCommand::parse (int argc, char * argv[])
Definition at line 163 of file SubCommand.cpp.
{
        subCommandApp->parse(argc, argv);
    }
References subCommandApp.
Referenced by utils::Config::parse(), and utils::ConfigRoot::parse2().
required() [1/3]
SubCommand * utils::SubCommand::required (bool required = true, bool force = true)
Definition at line 231 of file SubCommand.cpp.
{
        requiredCount += required ? 1 : -1;
        required = force ? required : requiredCount > 0;
        subCommandApp->required(required);
        SubCommand* parent = getParent();
        if (parent != nullptr) {
            if (required) {
                parent->needs(this);
            }
            parent->required(this, required);
        }
        return this;
    }
References getParent(), needs(), required(), requiredCount, and subCommandApp.
Referenced by required(), and required().
required() [2/3]
SubCommand * utils::SubCommand::required (CLI::Option * option, bool required = true)
Definition at line 279 of file SubCommand.cpp.
{
        if (option->get_required() != required) {
            option->required(required);
            if (required) {
                subCommandApp->needs(option);
                option->default_str("");
            } else {
                subCommandApp->remove_needs(option);
            }
            this->required(required, false);
        }
        return this;
    }
References required(), and subCommandApp.
Referenced by ConfigDb::ConfigDb(), subcommand::ConfigWWW::ConfigWWW(), ConfigDb::setHost(), and subcommand::ConfigWWW::setHtmlRoot().
required() [3/3]
SubCommand * utils::SubCommand::required (SubCommand * subCommand, bool required = true)
Definition at line 250 of file SubCommand.cpp.
{
        if (subCommandApp->get_required() != required) {
            if (required) {
                needs(subCommand);
                for (const auto& sub : subCommand->subCommandApp->get_subcommands([](const CLI::App* sc) -> bool {
                         return sc->get_required();
                     })) {
                    subCommand->subCommandApp->needs(sub);
                }
            } else {
                needs(subCommand, false);
                for (const auto& sub : subCommand->subCommandApp->get_subcommands([](const CLI::App* sc) -> bool {
                         return sc->get_required();
                     })) {
                    subCommand->subCommandApp->remove_needs(sub);
                }
            }
            this->required(required, false);
            subCommand->subCommandApp->required(required);
            subCommand->subCommandApp->ignore_case(required);
        }
        return this;
    }
References needs(), required(), and subCommandApp.
Referenced by required().
setConfig()
CLI::Option * utils::SubCommand::setConfig (const std::string & defaultConfigFile) const
Definition at line 179 of file SubCommand.cpp.
{
        return subCommandApp
            ->set_config( //
                "-c,--config-file",
                defaultConfigFile,
                "Read a config file",
                false) //
            ->take_all()
            ->type_name("configfile")
            ->check(!CLI::ExistingDirectory);
    }
References subCommandApp.
Referenced by utils::ConfigRoot::addRootOptions().
setConfigurable()
CLI::Option * utils::SubCommand::setConfigurable (CLI::Option * option, bool configurable) const protected
Definition at line 438 of file SubCommand.cpp.
{
        return option //
            ->configurable(configurable)
            ->group(subCommandApp->get_formatter()->get_label(configurable ? "Persistent Options" : "Nonpersistent Options"));
    }
References subCommandApp.
Referenced by utils::ConfigRoot::addRootOptions(), ConfigDb::ConfigDb(), net::config::ConfigInstance::ConfigInstance(), net::config::ConfigInstance::configurable(), initialize(), and SubCommand().
setDefaultValue()
template<typename ValueTypeT> CLI::Option * utils::SubCommand::setDefaultValue (CLI::Option * option, const ValueTypeT & value, bool clear = true) const protected
Definition at line 337 of file SubCommand.h.
{
        try {
            option->default_val(value);
            if (clear) {
                option->clear();
            }
        } catch (const CLI::ParseError&) {
            option = nullptr;
        }
        return option;
    }
Referenced by addFlagFunction(), net::in6::stream::config::ConfigSocketClient::ConfigSocketClient(), net::in::stream::config::ConfigSocketClient::ConfigSocketClient(), net::in6::stream::config::ConfigSocketServer::ConfigSocketServer(), net::in::stream::config::ConfigSocketServer::ConfigSocketServer(), net::config::ConfigPhysicalSocketServer::setAcceptsPerTick(), net::config::ConfigPhysicalSocketServer::setAcceptTimeout(), net::config::ConfigPhysicalSocketServer::setBacklog(), net::config::ConfigTls::setCaCert(), net::config::ConfigTls::setCaCertAcceptUnknown(), net::config::ConfigTls::setCaCertDir(), net::config::ConfigTls::setCaCertUseDefaultDir(), net::config::ConfigTls::setCert(), net::config::ConfigTls::setCertKey(), net::config::ConfigTls::setCertKeyPassword(), net::config::ConfigTls::setCipherList(), net::config::ConfigPhysicalSocketClient::setConnectTimeout(), net::config::ConfigInstance::setDisabled(), net::in6::stream::config::ConfigSocketClient::setDisableNagleAlgorithm(), net::in6::stream::config::ConfigSocketServer::setDisableNagleAlgorithm(), net::in::stream::config::ConfigSocketClient::setDisableNagleAlgorithm(), net::in::stream::config::ConfigSocketServer::setDisableNagleAlgorithm(), net::config::ConfigTlsServer::setForceSni(), web::http::client::ConfigHTTP::setHostHeader(), subcommand::ConfigWWW::setHtmlRoot(), net::config::ConfigTls::setInitTimeout(), net::in6::stream::config::ConfigSocketServer::setIPv6Only(), web::http::client::ConfigHTTP::setPipelinedRequests(), net::config::ConfigConnection::setReadBlockSize(), net::config::ConfigConnection::setReadTimeout(), net::config::ConfigPhysicalSocketClient::setReconnect(), net::config::ConfigPhysicalSocketClient::setReconnectTime(), net::config::ConfigPhysicalSocket::setRetry(), net::config::ConfigPhysicalSocket::setRetryBase(), net::config::ConfigPhysicalSocket::setRetryJitter(), net::config::ConfigPhysicalSocket::setRetryLimit(), net::config::ConfigPhysicalSocket::setRetryOnFatal(), net::config::ConfigPhysicalSocket::setRetryTimeout(), net::config::ConfigPhysicalSocket::setRetryTries(), net::in6::stream::config::ConfigSocketServer::setReuseAddress(), net::in::stream::config::ConfigSocketServer::setReuseAddress(), net::in6::stream::config::ConfigSocketServer::setReusePort(), net::in::stream::config::ConfigSocketServer::setReusePort(), net::config::ConfigTls::setShutdownTimeout(), net::config::ConfigTlsClient::setSni(), net::config::ConfigTls::setSslOptions(), net::config::ConfigConnection::setTerminateTimeout(), net::config::ConfigConnection::setWriteBlockSize(), and net::config::ConfigConnection::setWriteTimeout().
setLogFile()
CLI::Option * utils::SubCommand::setLogFile (const std::string & defaultLogFile) const
Definition at line 191 of file SubCommand.cpp.
{
        return addOption("-l,--log-file", "Log file", "logFile", defaultLogFile, !CLI::ExistingDirectory);
    }
References addOption().
Referenced by utils::ConfigRoot::addRootOptions().
setRequireCallback()
SubCommand * utils::SubCommand::setRequireCallback (const std::function< void(void)> & callback)
Definition at line 207 of file SubCommand.cpp.
{
        subCommandApp->require_callback(callback);
        return this;
    }
References subCommandApp.
setVersionFlag()
CLI::Option * utils::SubCommand::setVersionFlag (const std::string & version) const
Definition at line 195 of file SubCommand.cpp.
{
        return subCommandApp->set_version_flag("-v,--version", version, "Framework version");
    }
References subCommandApp.
Referenced by utils::ConfigRoot::addRootOptions().
version()
std::string utils::SubCommand::version () const
Definition at line 159 of file SubCommand.cpp.
{
        return subCommandApp->version();
    }
References subCommandApp.
Referenced by utils::ConfigRoot::parse2().
Member Data Documentation
aliases
std::map< std::string, std::string > utils::SubCommand::aliases static protected
Definition at line 235 of file SubCommand.h.
Referenced by utils::ConfigRoot::parse2().
commandlineOpt
CLI::Option* utils::SubCommand::commandlineOpt = nullptr private
Definition at line 251 of file SubCommand.h.
Referenced by SubCommand().
commandlineTriggerApp
CLI::App * utils::SubCommand::commandlineTriggerApp = nullptr static protected
Definition at line 239 of file SubCommand.h.
Referenced by utils::ConfigRoot::bootstrap(), getCommandlineTriggerApp(), utils::ConfigRoot::parse1(), utils::ConfigRoot::parse2(), and SubCommand().
final
bool utils::SubCommand::final private
Definition at line 247 of file SubCommand.h.
Referenced by newSubCommand(), and SubCommand().
helpOpt
CLI::Option* utils::SubCommand::helpOpt = nullptr private
Definition at line 249 of file SubCommand.h.
Referenced by SubCommand().
helpTriggerApp
CLI::App * utils::SubCommand::helpTriggerApp = nullptr static protected
Definition at line 237 of file SubCommand.h.
Referenced by utils::ConfigRoot::bootstrap(), getHelpTriggerApp(), utils::ConfigRoot::parse1(), utils::ConfigRoot::parse2(), and SubCommand().
parent
SubCommand* utils::SubCommand::parent private
Definition at line 245 of file SubCommand.h.
Referenced by getParent(), and SubCommand().
requiredCount
int utils::SubCommand::requiredCount = 0 private
Definition at line 253 of file SubCommand.h.
Referenced by required().
sectionFormatter
std::shared_ptr< CLI::Formatter > utils::SubCommand::sectionFormatter = makeSectionFormatter() static
Definition at line 232 of file SubCommand.h.
showConfigOpt
CLI::Option* utils::SubCommand::showConfigOpt = nullptr private
Definition at line 250 of file SubCommand.h.
Referenced by SubCommand().
showConfigTriggerApp
CLI::App * utils::SubCommand::showConfigTriggerApp = nullptr static protected
Definition at line 238 of file SubCommand.h.
Referenced by utils::ConfigRoot::bootstrap(), getShowConfigTriggerApp(), utils::ConfigRoot::parse1(), utils::ConfigRoot::parse2(), and SubCommand().
subCommandApp
AppWithPtr* utils::SubCommand::subCommandApp private
Definition at line 244 of file SubCommand.h.
Referenced by addFlag(), addFlagFunction(), addOption(), addOptionFunction(), addOptionVariable(), allowExtras(), configToStr(), description(), disabled(), finalCallback(), footer(), getName(), getOption(), getSubCommand(), getSubCommand(), hasParent(), help(), needs(), parse(), required(), required(), required(), setConfig(), setConfigurable(), setRequireCallback(), setVersionFlag(), SubCommand(), and version().
The documentation for this class was generated from the following files:
utils/SubCommand.h
utils/SubCommand.cpp