SNode.C: core::socket::stream::legacy::SocketConnector< PhysicalClientSocketT, ConfigT > Class Template Reference
core::socket::stream::legacy::SocketConnector< PhysicalClientSocketT, ConfigT > Class Template Reference
#include <SocketConnector.h>
Public Types
using SocketAddress = typename Super::SocketAddress
using Config = typename Super::Config
using SocketConnection = typename Super::SocketConnection
Public Member Functions
SocketConnector (const std::shared_ptr< core::socket::stream::SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus, const std::shared_ptr< Config > &config)
SocketConnector (const SocketConnector &socketConnector)
Private Types
using Super = core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >
using PhysicalClientSocket = PhysicalClientSocketT
Private Member Functions
void useNextSocketAddress () override
virtual void init ()
void connectEvent () override
void unobservedEvent () final
void connectTimeout () final
void destruct () final
void dispatchEvent () final
void timeoutEvent () final
void signalEvent (int signum) override
int getRegisteredFd () const
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
void onEvent (const utils::Timeval &currentTime) final
void onSignal (int signum)
void triggered (const utils::Timeval &currentTime)
void setEnabled (const utils::Timeval &currentTime)
void setDisabled ()
void observed ()
void unObserved ()
void span ()
void relax ()
const std::string & getName () const
Static Private Member Functions
static void atNextTick (const std::function< void(void)> &callBack)
Private Attributes
PhysicalClientSocket physicalClientSocket
SocketAddress remoteAddress
std::shared_ptr< core::socket::stream::SocketContextFactory > socketContextFactory
std::function< void(SocketConnection *)> onConnect
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
std::function< void(const SocketAddress &, core::socket::State)> onStatus
std::shared_ptr< Config > config
DescriptorEventPublisher & descriptorEventPublisher
int observedFd = -1
bool enabled = false
bool suspended = false
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
int observationCounter = 0
Event event
Detailed Description
template<typename PhysicalClientSocketT, typename ConfigT>
class core::socket::stream::legacy::SocketConnector< PhysicalClientSocketT, ConfigT >
Definition at line 37 of file SocketConnector.h.
Member Typedef Documentation
Config
template<typename PhysicalClientSocketT , typename ConfigT > using core::socket::stream::legacy::SocketConnector< PhysicalClientSocketT, ConfigT >::Config = typename Super::Config
Definition at line 44 of file SocketConnector.h.
PhysicalClientSocket
using core::socket::stream::SocketConnector< PhysicalClientSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::PhysicalClientSocket = PhysicalClientSocketT private inherited
Definition at line 42 of file SocketConnector.h.
SocketAddress
template<typename PhysicalClientSocketT , typename ConfigT > using core::socket::stream::legacy::SocketConnector< PhysicalClientSocketT, ConfigT >::SocketAddress = typename Super::SocketAddress
Definition at line 43 of file SocketConnector.h.
SocketConnection
template<typename PhysicalClientSocketT , typename ConfigT > using core::socket::stream::legacy::SocketConnector< PhysicalClientSocketT, ConfigT >::SocketConnection = typename Super::SocketConnection
Definition at line 45 of file SocketConnector.h.
Super
template<typename PhysicalClientSocketT , typename ConfigT > using core::socket::stream::legacy::SocketConnector< PhysicalClientSocketT, ConfigT >::Super = core::socket::stream::SocketConnector<PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection> private
Definition at line 40 of file SocketConnector.h.
Constructor & Destructor Documentation
SocketConnector() [1/2]
template<typename PhysicalClientSocket , typename Config > core::socket::stream::legacy::SocketConnector< PhysicalClientSocket, Config >::SocketConnector (const std::shared_ptr< core::socket::stream::SocketContextFactory > & socketContextFactory, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::function< void(const SocketAddress &, core::socket::State)> & onStatus, const std::shared_ptr< Config > & config)
Definition at line 32 of file SocketConnector.hpp.
        : Super(
              socketContextFactory,
              onConnect,
              [socketContextFactory, onConnected](SocketConnection* socketConnection) -> void {
                  onConnected(socketConnection);
                  socketConnection->connectSocketContext(socketContextFactory);
              },
              onDisconnect,
              onStatus,
              config) {
    }
SocketConnector() [2/2]
template<typename PhysicalSocketServer , typename Config > core::socket::stream::legacy::SocketConnector< PhysicalSocketServer, Config >::SocketConnector (const SocketConnector< PhysicalClientSocketT, ConfigT > & socketConnector)
Definition at line 52 of file SocketConnector.hpp.
        : core::Observer(socketConnector)
        , Super::SocketConnector(socketConnector) {
    }
References core::socket::stream::legacy::SocketConnector< PhysicalClientSocketT, ConfigT >::SocketConnector().
Referenced by core::socket::stream::legacy::SocketConnector< PhysicalClientSocketT, ConfigT >::SocketConnector().
Member Function Documentation
atNextTick()
void core::EventReceiver::atNextTick (const std::function< void(void)> & callBack) static inherited
Definition at line 28 of file EventReceiver.cpp.
{
        class NextTickEvent : public core::EventReceiver {
        public:
            explicit NextTickEvent(const std::function<void(void)>& callBack)
                : core::EventReceiver("RequestEvent")
                , callBack(callBack) {
            }
            void onEvent([[maybe_unused]] const utils::Timeval& currentTime) override {
                callBack();
                delete this;
            }
        private:
            std::function<void(void)> callBack;
        };
        (new NextTickEvent(callBack))->span();
    }
References core::EventReceiver::EventReceiver(), and core::EventReceiver::span().
Referenced by web::http::client::SocketContext::dispatchNextRequest(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestSent(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), and core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector().
checkTimeout()
void core::DescriptorEventReceiver::checkTimeout (const utils::Timeval & currentTime) inherited
Definition at line 171 of file DescriptorEventReceiver.cpp.
{
        if (maxInactivity > 0 && currentTime - lastTriggered >= maxInactivity) {
            timeoutEvent();
        }
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), utils::Timeval::operator>(), utils::Timeval::operator>=(), and core::DescriptorEventReceiver::timeoutEvent().
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents().
connectEvent()
void core::socket::stream::SocketConnector< PhysicalSocketClient, Config, SocketConnection >::connectEvent () override private virtual inherited
Implements core::eventreceiver::ConnectEventReceiver.
Definition at line 73 of file SocketConnector.hpp.
{
        int cErrno = 0;
        if (physicalClientSocket.getSockError(cErrno) == 0) { //  == 0->return valid : < 0->getsockopt failed
            const utils::PreserveErrno pe(cErrno);            // errno = cErrno
            if (errno == 0) {
                LOG(TRACE) << config->getInstanceName() << ": connect success '" << remoteAddress.toString() << "'";
                onStatus(remoteAddress, core::socket::STATE_OK);
                SocketConnection* socketConnection =
                    new SocketConnection(config->getInstanceName(),
                                         std::move(physicalClientSocket),
                                         onDisconnect,
                                         remoteAddress.toString(false),
                                         getLocalSocketAddress<SocketAddress>(physicalClientSocket, config),
                                         getRemoteSocketAddress<SocketAddress>(physicalClientSocket, config),
                                         config->getReadTimeout(),
                                         config->getWriteTimeout(),
                                         config->getReadBlockSize(),
                                         config->getWriteBlockSize(),
                                         config->getTerminateTimeout());
                onConnect(socketConnection);
                onConnected(socketConnection);
                disable();
            } else if (PhysicalClientSocket::connectInProgress(errno)) {
                LOG(TRACE) << config->getInstanceName() << ": connect still in progress '" << remoteAddress.toString() << "'";
            } else if (remoteAddress.useNext()) {
                core::socket::State state = core::socket::STATE_OK;
                switch (errno) {
                    case EADDRINUSE:
                    case EADDRNOTAVAIL:
                    case ECONNREFUSED:
                    case ENETUNREACH:
                    case ENOENT:
                    case EHOSTDOWN:
                        PLOG(TRACE) << config->getInstanceName() << ": connect failed '" << remoteAddress.toString() << "'";
                        state = core::socket::STATE_ERROR;
                        break;
                    default:
                        PLOG(TRACE) << config->getInstanceName() << ": connect failed '" << remoteAddress.toString() << "'";
                        state = core::socket::STATE_FATAL;
                        break;
                }
                onStatus(remoteAddress, (state | core::socket::State::NO_RETRY));
                LOG(TRACE) << config->getInstanceName() << ": using next SocketAddress '" << config->Remote::getSocketAddress().toString()
                           << "'";
                useNextSocketAddress();
                disable();
            } else {
                core::socket::State state = core::socket::STATE_OK;
                switch (errno) {
                    case EADDRINUSE:
                    case EADDRNOTAVAIL:
                    case ECONNREFUSED:
                    case ENETUNREACH:
                    case ENOENT:
                    case EHOSTDOWN:
                        PLOG(TRACE) << config->getInstanceName() << ": connect failed '" << remoteAddress.toString() << "'";
                        state = core::socket::STATE_ERROR;
                        break;
                    default:
                        PLOG(TRACE) << config->getInstanceName() << ": connect failed '" << remoteAddress.toString() << "'";
                        state = core::socket::STATE_FATAL;
                        break;
                }
                onStatus(remoteAddress, state);
                disable();
            }
        } else {
            PLOG(TRACE) << config->getInstanceName() << ": getsockopt syscall error '" << remoteAddress.toString() << "'";
            onStatus(remoteAddress, core::socket::STATE_FATAL);
            disable();
        }
    }
connectTimeout()
void core::socket::stream::SocketConnector< PhysicalSocketClient, Config, SocketConnection >::connectTimeout () final private virtual inherited
Reimplemented from core::eventreceiver::ConnectEventReceiver.
Definition at line 76 of file SocketConnector.hpp.
{
        LOG(TRACE) << config->getInstanceName() << ": connect timeout " << remoteAddress.toString();
        if (remoteAddress.useNext()) {
            LOG(TRACE) << config->getInstanceName() << ": using next SocketAddress '" << config->Remote::getSocketAddress().toString()
                       << "'";
            useNextSocketAddress();
        } else {
            LOG(TRACE) << config->getInstanceName() << ": connect timeout '" << remoteAddress.toString() << "'";
            onStatus(remoteAddress, core::socket::STATE_ERROR);
        }
        disable();
    }
destruct()
void core::socket::stream::SocketConnector< PhysicalSocketClient, Config, SocketConnection >::destruct () final protected virtual inherited
Reimplemented from core::EventReceiver.
Definition at line 79 of file SocketConnector.hpp.
{
        delete this;
    }
disable()
void core::DescriptorEventReceiver::disable () protected inherited
Definition at line 93 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            enabled = false;
            descriptorEventPublisher.disable(this);
            LOG(TRACE) << getName() << " (" << observedFd << "): Disabled";
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Double disable";
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::disable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), and core::DescriptorEventReceiver::observedFd.
Referenced by core::eventreceiver::AcceptEventReceiver::acceptTimeout(), database::mariadb::MariaDBConnection::commandContinue(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectEvent(), core::eventreceiver::ConnectEventReceiver::connectTimeout(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectTimeout(), core::DescriptorEventPublisher::disable(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::pipe::PipeSource::eof(), core::eventreceiver::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSink::readEvent(), core::eventreceiver::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::socket::stream::SocketWriter::signalEvent(), core::eventreceiver::AcceptEventReceiver::signalEvent(), core::eventreceiver::ConnectEventReceiver::signalEvent(), core::eventreceiver::ExceptionalConditionEventReceiver::signalEvent(), core::eventreceiver::ReadEventReceiver::signalEvent(), core::eventreceiver::WriteEventReceiver::signalEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), core::pipe::PipeSource::writeEvent(), core::eventreceiver::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
dispatchEvent()
void core::eventreceiver::ConnectEventReceiver::dispatchEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 42 of file ConnectEventReceiver.cpp.
{
        connectEvent();
    }
References core::eventreceiver::ConnectEventReceiver::connectEvent().
enable()
bool core::DescriptorEventReceiver::enable (int fd) protected inherited
Definition at line 70 of file DescriptorEventReceiver.cpp.
{
        if (core::eventLoopState() != core::State::STOPPING) {
            if (!enabled) {
                observedFd = fd;
                enabled = true;
                descriptorEventPublisher.enable(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double enable";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Enable after signal";
        }
        return enabled;
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::enable(), core::DescriptorEventReceiver::enabled, core::eventLoopState(), core::EventReceiver::getName(), core::DescriptorEventReceiver::observedFd, and core::STOPPING.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::init(), core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 65 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::socket::stream::tls::SocketReader::read(), core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::SocketWriter::shutdownWrite(), core::socket::stream::SocketWriter::streamToPeer(), core::DescriptorEventReceiver::suspend(), and core::socket::stream::tls::SocketWriter::write().
getRegisteredFd()
int core::DescriptorEventReceiver::getRegisteredFd () const inherited
Definition at line 66 of file DescriptorEventReceiver.cpp.
{
        return observedFd;
    }
References core::DescriptorEventReceiver::observedFd.
Referenced by core::DescriptorEventPublisher::enable(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::select::DescriptorEventPublisher::muxAdd(), core::poll::PollFdsManager::muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOff(), core::select::DescriptorEventPublisher::muxOff(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOn(), core::select::DescriptorEventPublisher::muxOn(), core::socket::stream::legacy::SocketReader::read(), core::pipe::PipeSink::readEvent(), core::socket::stream::legacy::SocketWriter::write(), core::pipe::PipeSource::writeEvent(), core::pipe::PipeSink::~PipeSink(), and core::pipe::PipeSource::~PipeSource().
getTimeout()
utils::Timeval core::DescriptorEventReceiver::getTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 152 of file DescriptorEventReceiver.cpp.
{
        return maxInactivity > 0 ? currentTime > lastTriggered ? maxInactivity - (currentTime - lastTriggered) : 0 : TIMEOUT::MAX;
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::DescriptorEventPublisher::getNextTimeout().
init()
void core::socket::stream::SocketConnector< PhysicalSocketClient, Config, SocketConnection >::init () protected virtual inherited
Definition at line 70 of file SocketConnector.hpp.
{
        if (!config->getDisabled()) {
            try {
                LOG(TRACE) << config->getInstanceName() << ": Starting";
                remoteAddress = config->Remote::getSocketAddress();
                SocketAddress localAddress = config->Local::getSocketAddress();
                try {
                    if (physicalClientSocket.open(config->getSocketOptions(), PhysicalClientSocket::Flags::NONBLOCK) < 0) {
                        core::socket::State state = core::socket::STATE_OK;
                        switch (errno) {
                            case EMFILE:
                            case ENFILE:
                            case ENOBUFS:
                            case ENOMEM:
                                PLOG(TRACE) << config->getInstanceName() << ": open '" << localAddress.toString() << "'";
                                state = core::socket::STATE_ERROR;
                                break;
                            default:
                                PLOG(TRACE) << config->getInstanceName() << ": open failed '" << localAddress.toString() << "'";
                                state = core::socket::STATE_FATAL;
                                break;
                        }
                        onStatus(remoteAddress, state);
                    } else if (physicalClientSocket.bind(localAddress) < 0) {
                        core::socket::State state = core::socket::STATE_OK;
                        switch (errno) {
                            case EADDRINUSE:
                                PLOG(TRACE) << config->getInstanceName() << ": bind '" << localAddress.toString() << "'";
                                state = core::socket::STATE_ERROR;
                                break;
                            default:
                                PLOG(TRACE) << config->getInstanceName() << ": bind failed '" << localAddress.toString() << "'";
                                state = core::socket::STATE_FATAL;
                                break;
                        }
                        onStatus(remoteAddress, state);
                    } else if (physicalClientSocket.connect(remoteAddress) < 0 && !PhysicalClientSocket::connectInProgress(errno)) {
                        core::socket::State state = core::socket::STATE_OK;
                        switch (errno) {
                            case EADDRINUSE:
                            case EADDRNOTAVAIL:
                            case ECONNREFUSED:
                            case ENETUNREACH:
                            case ENOENT:
                            case EHOSTDOWN:
                                PLOG(TRACE) << config->getInstanceName() << ": connect '" << remoteAddress.toString() << "'";
                                state = core::socket::STATE_ERROR;
                                break;
                            default:
                                PLOG(TRACE) << config->getInstanceName() << ": connect failed '" << remoteAddress.toString() << "'";
                                state = core::socket::STATE_FATAL;
                                break;
                        }
                        if (remoteAddress.useNext()) {
                            onStatus(remoteAddress, state | core::socket::State::NO_RETRY);
                            LOG(TRACE) << config->getInstanceName() << ": using next SocketAddress '"
                                       << config->Remote::getSocketAddress().toString() << "'";
                            useNextSocketAddress();
                        } else {
                            onStatus(remoteAddress, state);
                        }
                    } else if (PhysicalClientSocket::connectInProgress(errno)) {
                        if (enable(physicalClientSocket.getFd())) {
                            LOG(TRACE) << config->getInstanceName() << ": connect in progress '" << remoteAddress.toString() << "'";
                        } else {
                            LOG(TRACE) << config->getInstanceName() << ": Error: not monitored by SNode.C";
                        }
                    } else {
                        LOG(TRACE) << config->getInstanceName() << ": connect success '" << remoteAddress.toString() << "'";
                        onStatus(remoteAddress, core::socket::STATE_OK);
                        SocketConnection* socketConnection =
                            new SocketConnection(config->getInstanceName(),
                                                 std::move(physicalClientSocket),
                                                 onDisconnect,
                                                 remoteAddress.toString(false),
                                                 getLocalSocketAddress<SocketAddress>(physicalClientSocket, config),
                                                 getRemoteSocketAddress<SocketAddress>(physicalClientSocket, config),
                                                 config->getReadTimeout(),
                                                 config->getWriteTimeout(),
                                                 config->getReadBlockSize(),
                                                 config->getWriteBlockSize(),
                                                 config->getTerminateTimeout());
                        onConnect(socketConnection);
                        onConnected(socketConnection);
                    }
                } catch (const typename SocketAddress::BadSocketAddress& badSocketAddress) {
                    LOG(TRACE) << config->getInstanceName() << ": " << badSocketAddress.what();
                    onStatus({}, core::socket::STATE(badSocketAddress.getState(), badSocketAddress.getErrnum(), badSocketAddress.what()));
                }
            } catch (const typename SocketAddress::BadSocketAddress& badSocketAddress) {
                LOG(TRACE) << config->getInstanceName() << ": " << badSocketAddress.what();
                onStatus({}, core::socket::STATE(badSocketAddress.getState(), badSocketAddress.getErrnum(), badSocketAddress.what()));
            }
        } else {
            LOG(TRACE) << config->getInstanceName() << ": disabled";
            onStatus({}, core::socket::STATE_DISABLED);
        }
        if (isEnabled()) {
            core::eventreceiver::ConnectEventReceiver::setTimeout(config->getConnectTimeout());
        } else {
            destruct();
        }
    }
isEnabled()
bool core::DescriptorEventReceiver::isEnabled () const inherited
Definition at line 107 of file DescriptorEventReceiver.cpp.
{
        return enabled;
    }
References core::DescriptorEventReceiver::enabled.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketWriter::sendToPeer(), and core::socket::stream::SocketWriter::streamToPeer().
isSuspended()
bool core::DescriptorEventReceiver::isSuspended () const inherited
Definition at line 138 of file DescriptorEventReceiver.cpp.
{
        return suspended;
    }
References core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::pipe::PipeSource::send().
observed()
void core::Observer::observed () protected inherited
Definition at line 41 of file DescriptorEventReceiver.cpp.
{
        observationCounter++;
    }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setEnabled().
onEvent()
void core::DescriptorEventReceiver::onEvent (const utils::Timeval & currentTime) final private virtual inherited
Implements core::EventReceiver.
Definition at line 156 of file DescriptorEventReceiver.cpp.
{
        eventCounter++;
        triggered(currentTime);
        dispatchEvent();
    }
References core::DescriptorEventReceiver::dispatchEvent(), core::DescriptorEventReceiver::eventCounter, and core::DescriptorEventReceiver::triggered().
onSignal()
void core::DescriptorEventReceiver::onSignal (int signum) private inherited
Definition at line 163 of file DescriptorEventReceiver.cpp.
{
        signalEvent(signum);
    }
References core::DescriptorEventReceiver::signalEvent().
Referenced by core::DescriptorEventPublisher::signal().
relax()
void core::EventReceiver::relax () inherited
Definition at line 61 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
resume()
void core::DescriptorEventReceiver::resume () protected inherited
Definition at line 124 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (suspended) {
                suspended = false;
                lastTriggered = utils::Timeval::currentTime();
                descriptorEventPublisher.resume(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double resume";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Resume while not enabled";
        }
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::observedFd, utils::Timeval::operator=(), core::DescriptorEventPublisher::resume(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
setDisabled()
void core::DescriptorEventReceiver::setDisabled () private inherited
Definition at line 103 of file DescriptorEventReceiver.cpp.
{
        unObserved();
    }
References core::Observer::unObserved().
setEnabled()
void core::DescriptorEventReceiver::setEnabled (const utils::Timeval & currentTime) private inherited
Definition at line 87 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
        observed();
    }
References core::DescriptorEventReceiver::lastTriggered, core::Observer::observed(), and utils::Timeval::operator=().
Referenced by core::DescriptorEventPublisher::enable().
setTimeout()
void core::DescriptorEventReceiver::setTimeout (const utils::Timeval & timeout) inherited
Definition at line 142 of file DescriptorEventReceiver.cpp.
{
        if (timeout == TIMEOUT::DEFAULT) {
            this->maxInactivity = initialTimeout;
        } else {
            this->maxInactivity = timeout;
        }
        triggered(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::TIMEOUT::DEFAULT, core::DescriptorEventReceiver::initialTimeout, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator=(), utils::Timeval::operator==(), and core::DescriptorEventReceiver::triggered().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::init(), and core::socket::stream::SocketWriter::shutdownWrite().
signalEvent()
void core::eventreceiver::ConnectEventReceiver::signalEvent (int signum) override private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 50 of file ConnectEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
span()
void core::EventReceiver::span () inherited
Definition at line 57 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by core::EventReceiver::atNextTick(), database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), core::file::FileReader::start(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
suspend()
void core::DescriptorEventReceiver::suspend () protected inherited
Definition at line 111 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!suspended) {
                suspended = true;
                descriptorEventPublisher.suspend(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double suspend";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Suspend while not enabled";
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::observedFd, core::DescriptorEventPublisher::suspend(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), and core::pipe::PipeSource::writeEvent().
timeoutEvent()
void core::eventreceiver::ConnectEventReceiver::timeoutEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 46 of file ConnectEventReceiver.cpp.
{
        connectTimeout();
    }
References core::eventreceiver::ConnectEventReceiver::connectTimeout().
triggered()
void core::DescriptorEventReceiver::triggered (const utils::Timeval & currentTime) private inherited
Definition at line 167 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
    }
References core::DescriptorEventReceiver::lastTriggered, and utils::Timeval::operator=().
Referenced by core::DescriptorEventReceiver::onEvent(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::DescriptorEventReceiver::setTimeout().
unObserved()
void core::Observer::unObserved () protected inherited
Definition at line 45 of file DescriptorEventReceiver.cpp.
{
        observationCounter--;
        if (observationCounter == 0) {
            unobservedEvent();
        }
    }
References core::Observer::observationCounter, and core::Observer::unobservedEvent().
Referenced by core::DescriptorEventReceiver::setDisabled().
unobservedEvent()
void core::socket::stream::SocketConnector< PhysicalSocketClient, Config, SocketConnection >::unobservedEvent () final private virtual inherited
Implements core::Observer.
Definition at line 75 of file SocketConnector.hpp.
{
        destruct();
    }
useNextSocketAddress()
template<typename PhysicalClientSocket , typename Config > void core::socket::stream::legacy::SocketConnector< PhysicalClientSocket, Config >::useNextSocketAddress () override private virtual
Implements core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >.
Definition at line 58 of file SocketConnector.hpp.
{
        new SocketConnector(*this);
    }
Member Data Documentation
config
std::shared_ptr<Config> core::socket::stream::SocketConnector< PhysicalClientSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::config protected inherited
Definition at line 94 of file SocketConnector.h.
descriptorEventPublisher
DescriptorEventPublisher& core::DescriptorEventReceiver::descriptorEventPublisher private inherited
Definition at line 104 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
enabled
bool core::DescriptorEventReceiver::enabled = false private inherited
Definition at line 108 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
event
Event core::EventReceiver::event private inherited
Definition at line 59 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
eventCounter
int core::DescriptorEventReceiver::eventCounter = 0 private inherited
Definition at line 115 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::onEvent().
initialTimeout
const utils::Timeval core::DescriptorEventReceiver::initialTimeout private inherited
Definition at line 113 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), and core::DescriptorEventReceiver::setTimeout().
lastTriggered
utils::Timeval core::DescriptorEventReceiver::lastTriggered private inherited
Definition at line 111 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setEnabled(), and core::DescriptorEventReceiver::triggered().
maxInactivity
utils::Timeval core::DescriptorEventReceiver::maxInactivity private inherited
Definition at line 112 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::getTimeout(), and core::DescriptorEventReceiver::setTimeout().
observationCounter
int core::Observer::observationCounter = 0 private inherited
Definition at line 53 of file DescriptorEventReceiver.h.
Referenced by core::Observer::observed(), and core::Observer::unObserved().
observedFd
int core::DescriptorEventReceiver::observedFd = -1 private inherited
Definition at line 106 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
onConnect
std::function<void(SocketConnection*)> core::socket::stream::SocketConnector< PhysicalClientSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::onConnect protected inherited
Definition at line 88 of file SocketConnector.h.
onConnected
std::function<void(SocketConnection*)> core::socket::stream::SocketConnector< PhysicalClientSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::onConnected protected inherited
Definition at line 89 of file SocketConnector.h.
onDisconnect
std::function<void(SocketConnection*)> core::socket::stream::SocketConnector< PhysicalClientSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::onDisconnect protected inherited
Definition at line 90 of file SocketConnector.h.
onStatus
std::function<void(const SocketAddress&, core::socket::State)> core::socket::stream::SocketConnector< PhysicalClientSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::onStatus protected inherited
Definition at line 92 of file SocketConnector.h.
physicalClientSocket
PhysicalClientSocket core::socket::stream::SocketConnector< PhysicalClientSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::physicalClientSocket private inherited
Definition at line 82 of file SocketConnector.h.
remoteAddress
SocketAddress core::socket::stream::SocketConnector< PhysicalClientSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::remoteAddress private inherited
Definition at line 83 of file SocketConnector.h.
socketContextFactory
std::shared_ptr<core::socket::stream::SocketContextFactory> core::socket::stream::SocketConnector< PhysicalClientSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::socketContextFactory protected inherited
Definition at line 86 of file SocketConnector.h.
suspended
bool core::DescriptorEventReceiver::suspended = false private inherited
Definition at line 109 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
The documentation for this class was generated from the following files:
core/socket/stream/legacy/SocketConnector.h
core/socket/stream/legacy/SocketConnector.hpp