SNode.C: core::eventreceiver::WriteEventReceiver Class Reference
core::eventreceiver::WriteEventReceiver Class Reference abstract
#include <WriteEventReceiver.h>
Protected Member Functions
WriteEventReceiver (const std::string &name, const utils::Timeval &timeout)
Protected Member Functions inherited from core::Observer
Observer ()=default
virtual ~Observer ()
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
virtual void unobservedEvent ()=0
Protected Member Functions inherited from core::EventReceiver
virtual ~EventReceiver ()=default
EventReceiver (const std::string &name)
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Private Member Functions
virtual void writeEvent ()=0
virtual void writeTimeout ()
void dispatchEvent () final
void timeoutEvent () final
Additional Inherited Members
Public Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const DescriptorEventReceiver &)=delete
DescriptorEventReceiver & operator= (const DescriptorEventReceiver &)=delete
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
int getRegisteredFd ()
void enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
virtual void terminate ()
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Detailed Description
Definition at line 34 of file WriteEventReceiver.h.
Constructor & Destructor Documentation
WriteEventReceiver()
core::eventreceiver::WriteEventReceiver::WriteEventReceiver (const std::string & name, const utils::Timeval & timeout) protected
Definition at line 30 of file WriteEventReceiver.cpp.
        : core::DescriptorEventReceiver(
              "WriteEventReceiver: " + name,
              core::EventLoop::instance().getEventMultiplexer().getDescriptorEventPublisher(core::EventMultiplexer::DISP_TYPE::WR),
              timeout) {
    }
References core::DescriptorEventReceiver::DescriptorEventReceiver(), core::EventMultiplexer::getDescriptorEventPublisher(), core::EventLoop::getEventMultiplexer(), core::EventLoop::instance(), and core::EventMultiplexer::WR.
Referenced by core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
Member Function Documentation
dispatchEvent()
void core::eventreceiver::WriteEventReceiver::dispatchEvent () final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 41 of file WriteEventReceiver.cpp.
{
        writeEvent();
    }
References writeEvent().
timeoutEvent()
void core::eventreceiver::WriteEventReceiver::timeoutEvent () final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 45 of file WriteEventReceiver.cpp.
{
        writeTimeout();
    }
References writeTimeout().
writeEvent()
virtual void core::eventreceiver::WriteEventReceiver::writeEvent () private pure virtual
Implemented in core::socket::stream::SocketWriter< PhysicalSocketT >, core::socket::stream::tls::TLSHandshake, core::socket::stream::tls::TLSShutdown, core::pipe::PipeSource, and database::mariadb::MariaDBConnection.
Referenced by dispatchEvent().
writeTimeout()
void core::eventreceiver::WriteEventReceiver::writeTimeout () private virtual
Reimplemented in core::socket::stream::tls::TLSHandshake, core::socket::stream::tls::TLSShutdown, and database::mariadb::MariaDBConnection.
Definition at line 37 of file WriteEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
Referenced by timeoutEvent().
The documentation for this class was generated from the following files:
core/eventreceiver/WriteEventReceiver.h
core/eventreceiver/WriteEventReceiver.cpp