SNode.C: core::DescriptorEventReceiver Class Reference
core::DescriptorEventReceiver Class Reference abstract
#include <DescriptorEventReceiver.h>
Classes
struct TIMEOUT
Public Member Functions
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
int getRegisteredFd () const
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Member Functions
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
Protected Member Functions inherited from core::Observer
void observed ()
void unObserved ()
virtual void unobservedEvent ()=0
Observer ()=default
Observer (Observer &)=delete
Observer (Observer &&)=delete
virtual ~Observer ()
Protected Member Functions inherited from core::EventReceiver
virtual ~EventReceiver ()=default
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Private Member Functions
void onEvent (const utils::Timeval &currentTime) final
void onSignal (int signum)
void triggered (const utils::Timeval &currentTime)
void setEnabled (const utils::Timeval &currentTime)
void setDisabled ()
virtual void dispatchEvent ()=0
virtual void timeoutEvent ()=0
virtual void signalEvent (int signum)=0
Private Attributes
DescriptorEventPublisher & descriptorEventPublisher
int observedFd = -1
bool enabled = false
bool suspended = false
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
Friends
class DescriptorEventPublisher
Additional Inherited Members
Static Public Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Static Protected Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Detailed Description
Definition at line 57 of file DescriptorEventReceiver.h.
Constructor & Destructor Documentation
DescriptorEventReceiver()
core::DescriptorEventReceiver::DescriptorEventReceiver (const std::string & name, DescriptorEventPublisher & descriptorEventPublisher, const utils::Timeval & timeout = TIMEOUT::DISABLE)
Definition at line 53 of file DescriptorEventReceiver.cpp.
        : EventReceiver(name)
        , descriptorEventPublisher(descriptorEventPublisher)
        , maxInactivity(timeout)
        , initialTimeout(timeout) {
    }
References descriptorEventPublisher, core::EventReceiver::EventReceiver(), initialTimeout, maxInactivity, and utils::Timeval::Timeval().
Member Function Documentation
checkTimeout()
void core::DescriptorEventReceiver::checkTimeout (const utils::Timeval & currentTime)
Definition at line 164 of file DescriptorEventReceiver.cpp.
{
        if (maxInactivity > 0 && currentTime - lastTriggered >= maxInactivity) {
            timeoutEvent();
        }
    }
References lastTriggered, maxInactivity, utils::Timeval::operator-(), utils::Timeval::operator>(), utils::Timeval::operator>=(), and timeoutEvent().
disable()
void core::DescriptorEventReceiver::disable () protected
Definition at line 86 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            enabled = false;
            descriptorEventPublisher.disable(this);
            LOG(TRACE) << getName() << " (" << observedFd << "): Disabled";
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Double disable";
        }
    }
References descriptorEventPublisher, core::DescriptorEventPublisher::disable(), enabled, core::EventReceiver::getName(), and observedFd.
Referenced by core::eventreceiver::AcceptEventReceiver::acceptTimeout(), database::mariadb::MariaDBConnection::commandContinue(), database::mariadb::MariaDBConnection::commandStart(), core::eventreceiver::ConnectEventReceiver::connectTimeout(), core::pipe::PipeSource::eof(), core::eventreceiver::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::pipe::PipeSink::readEvent(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::eventreceiver::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::eventreceiver::AcceptEventReceiver::signalEvent(), core::eventreceiver::ConnectEventReceiver::signalEvent(), core::eventreceiver::ExceptionalConditionEventReceiver::signalEvent(), core::eventreceiver::ReadEventReceiver::signalEvent(), core::eventreceiver::WriteEventReceiver::signalEvent(), core::socket::stream::SocketWriter::signalEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::pipe::PipeSource::writeEvent(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), core::eventreceiver::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
dispatchEvent()
virtual void core::DescriptorEventReceiver::dispatchEvent () private pure virtual
Implemented in core::eventreceiver::AcceptEventReceiver, core::eventreceiver::ConnectEventReceiver, core::eventreceiver::ExceptionalConditionEventReceiver, core::eventreceiver::ReadEventReceiver, and core::eventreceiver::WriteEventReceiver.
Referenced by onEvent().
enable()
bool core::DescriptorEventReceiver::enable (int fd) protected
Definition at line 66 of file DescriptorEventReceiver.cpp.
{
        if (!enabled) {
            observedFd = fd;
            enabled = true;
            descriptorEventPublisher.enable(this);
            LOG(TRACE) << getName() << " (" << observedFd << "): Enabled";
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Double enable";
        }
        return enabled;
    }
References descriptorEventPublisher, core::DescriptorEventPublisher::enable(), enabled, core::EventReceiver::getName(), and observedFd.
Referenced by core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
getRegisteredFd()
int core::DescriptorEventReceiver::getRegisteredFd () const
Definition at line 62 of file DescriptorEventReceiver.cpp.
{
        return observedFd;
    }
References observedFd.
Referenced by core::DescriptorEventPublisher::disable(), core::DescriptorEventPublisher::enable(), core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::multiplexer::poll::PollFdsManager::muxAdd(), core::multiplexer::select::DescriptorEventPublisher::muxAdd(), core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::muxOff(), core::multiplexer::select::DescriptorEventPublisher::muxOff(), core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::muxOn(), core::multiplexer::select::DescriptorEventPublisher::muxOn(), core::socket::stream::SocketReader::read(), core::pipe::PipeSink::readEvent(), core::socket::stream::SocketWriter::write(), core::pipe::PipeSink::~PipeSink(), and core::pipe::PipeSource::~PipeSource().
getTimeout()
utils::Timeval core::DescriptorEventReceiver::getTimeout (const utils::Timeval & currentTime) const
Definition at line 145 of file DescriptorEventReceiver.cpp.
{
        return maxInactivity > 0 ? currentTime > lastTriggered ? maxInactivity - (currentTime - lastTriggered) : 0 : TIMEOUT::MAX;
    }
References lastTriggered, core::DescriptorEventReceiver::TIMEOUT::MAX, maxInactivity, utils::Timeval::operator-(), and utils::Timeval::operator>().
isEnabled()
bool core::DescriptorEventReceiver::isEnabled () const
Definition at line 100 of file DescriptorEventReceiver.cpp.
{
        return enabled;
    }
References enabled.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketWriter::sendToPeer(), and core::socket::stream::SocketWriter::streamToPeer().
isSuspended()
bool core::DescriptorEventReceiver::isSuspended () const
Definition at line 131 of file DescriptorEventReceiver.cpp.
{
        return suspended;
    }
References suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::DescriptorEventPublisher::enable(), and core::pipe::PipeSource::send().
onEvent()
void core::DescriptorEventReceiver::onEvent (const utils::Timeval & currentTime) final private virtual
Implements core::EventReceiver.
Definition at line 149 of file DescriptorEventReceiver.cpp.
{
        eventCounter++;
        triggered(currentTime);
        dispatchEvent();
    }
References dispatchEvent(), eventCounter, and triggered().
onSignal()
void core::DescriptorEventReceiver::onSignal (int signum) private
Definition at line 156 of file DescriptorEventReceiver.cpp.
{
        signalEvent(signum);
    }
References signalEvent().
resume()
void core::DescriptorEventReceiver::resume () protected
Definition at line 117 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (suspended) {
                suspended = false;
                lastTriggered = utils::Timeval::currentTime();
                descriptorEventPublisher.resume(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double resume";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Resume while not enabled";
        }
    }
References utils::Timeval::currentTime(), descriptorEventPublisher, enabled, core::EventReceiver::getName(), lastTriggered, observedFd, utils::Timeval::operator=(), core::DescriptorEventPublisher::resume(), and suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
setDisabled()
void core::DescriptorEventReceiver::setDisabled () private
Definition at line 96 of file DescriptorEventReceiver.cpp.
{
        unObserved();
    }
References core::Observer::unObserved().
setEnabled()
void core::DescriptorEventReceiver::setEnabled (const utils::Timeval & currentTime) private
Definition at line 80 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
        observed();
    }
References lastTriggered, core::Observer::observed(), and utils::Timeval::operator=().
Referenced by core::DescriptorEventPublisher::enable().
setTimeout()
void core::DescriptorEventReceiver::setTimeout (const utils::Timeval & timeout)
Definition at line 135 of file DescriptorEventReceiver.cpp.
{
        if (timeout == TIMEOUT::DEFAULT) {
            this->maxInactivity = initialTimeout;
        } else {
            this->maxInactivity = timeout;
        }
        triggered(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::TIMEOUT::DEFAULT, initialTimeout, maxInactivity, utils::Timeval::operator=(), utils::Timeval::operator==(), and triggered().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), and core::socket::stream::SocketReader::shutdownRead().
signalEvent()
virtual void core::DescriptorEventReceiver::signalEvent (int signum) private pure virtual
Implemented in core::eventreceiver::AcceptEventReceiver, core::eventreceiver::ConnectEventReceiver, core::eventreceiver::ExceptionalConditionEventReceiver, core::eventreceiver::ReadEventReceiver, core::eventreceiver::WriteEventReceiver, core::socket::stream::SocketReader, core::socket::stream::SocketWriter, core::socket::stream::tls::TLSHandshake, and core::socket::stream::tls::TLSShutdown.
Referenced by onSignal().
suspend()
void core::DescriptorEventReceiver::suspend () protected
Definition at line 104 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!suspended) {
                suspended = true;
                descriptorEventPublisher.suspend(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double suspend";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Suspend while not enabled";
        }
    }
References descriptorEventPublisher, enabled, core::EventReceiver::getName(), observedFd, core::DescriptorEventPublisher::suspend(), and suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::pipe::PipeSource::writeEvent(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
timeoutEvent()
virtual void core::DescriptorEventReceiver::timeoutEvent () private pure virtual
Implemented in core::eventreceiver::AcceptEventReceiver, core::eventreceiver::ConnectEventReceiver, core::eventreceiver::ExceptionalConditionEventReceiver, core::eventreceiver::ReadEventReceiver, and core::eventreceiver::WriteEventReceiver.
Referenced by checkTimeout().
triggered()
void core::DescriptorEventReceiver::triggered (const utils::Timeval & currentTime) private
Definition at line 160 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
    }
References lastTriggered, and utils::Timeval::operator=().
Referenced by onEvent(), and setTimeout().
Friends And Related Symbol Documentation
DescriptorEventPublisher
friend class DescriptorEventPublisher friend
Definition at line 114 of file DescriptorEventReceiver.h.
Member Data Documentation
descriptorEventPublisher
DescriptorEventPublisher& core::DescriptorEventReceiver::descriptorEventPublisher private
Definition at line 101 of file DescriptorEventReceiver.h.
Referenced by DescriptorEventReceiver(), disable(), enable(), resume(), and suspend().
enabled
bool core::DescriptorEventReceiver::enabled = false private
Definition at line 105 of file DescriptorEventReceiver.h.
Referenced by disable(), enable(), isEnabled(), resume(), and suspend().
eventCounter
int core::DescriptorEventReceiver::eventCounter = 0 private
Definition at line 112 of file DescriptorEventReceiver.h.
Referenced by onEvent().
initialTimeout
const utils::Timeval core::DescriptorEventReceiver::initialTimeout private
Definition at line 110 of file DescriptorEventReceiver.h.
Referenced by DescriptorEventReceiver(), and setTimeout().
lastTriggered
utils::Timeval core::DescriptorEventReceiver::lastTriggered private
Definition at line 108 of file DescriptorEventReceiver.h.
Referenced by checkTimeout(), getTimeout(), resume(), setEnabled(), and triggered().
maxInactivity
utils::Timeval core::DescriptorEventReceiver::maxInactivity private
Definition at line 109 of file DescriptorEventReceiver.h.
Referenced by checkTimeout(), DescriptorEventReceiver(), getTimeout(), and setTimeout().
observedFd
int core::DescriptorEventReceiver::observedFd = -1 private
Definition at line 103 of file DescriptorEventReceiver.h.
Referenced by disable(), enable(), getRegisteredFd(), resume(), and suspend().
suspended
bool core::DescriptorEventReceiver::suspended = false private
Definition at line 106 of file DescriptorEventReceiver.h.
Referenced by isSuspended(), resume(), and suspend().
The documentation for this class was generated from the following files:
src/core/DescriptorEventReceiver.h
src/core/DescriptorEventReceiver.cpp