SNode.C: core::pipe::Pipe Class Reference
core::pipe::Pipe Class Reference
#include <Pipe.h>
Public Member Functions
Pipe (const Pipe &pipe)=delete
Pipe & operator= (const Pipe &pipe)=delete
Pipe (const std::function< void(PipeSource &, PipeSink &)> &onSuccess, const std::function< void(int)> &onError)
Private Attributes
int pipeFd [2] {}
Detailed Description
Definition at line 36 of file Pipe.h.
Constructor & Destructor Documentation
Pipe() [1/2]
core::pipe::Pipe::Pipe (const Pipe & pipe) delete
Pipe() [2/2]
core::pipe::Pipe::Pipe (const std::function< void(PipeSource &, PipeSink &)> & onSuccess, const std::function< void(int)> & onError)
Definition at line 35 of file Pipe.cpp.
{
        const int ret = core::system::pipe2(pipeFd, O_NONBLOCK);
        if (ret == 0) {
            onSuccess(*(new PipeSource(pipeFd[1])), *(new PipeSink(pipeFd[0])));
        } else {
            onError(errno);
        }
    }
References core::system::pipe2(), pipeFd, core::pipe::PipeSink::PipeSink(), and core::pipe::PipeSource::PipeSource().
Member Function Documentation
operator=()
Pipe & core::pipe::Pipe::operator= (const Pipe & pipe) delete
Member Data Documentation
pipeFd
int core::pipe::Pipe::pipeFd[2] {} private
Definition at line 45 of file Pipe.h.
{};
Referenced by Pipe().
The documentation for this class was generated from the following files:
core/pipe/Pipe.h
core/pipe/Pipe.cpp