SNode.C: core::multiplexer::poll::PollFdsManager Class Reference
core::multiplexer::poll::PollFdsManager Class Reference
#include <EventMultiplexer.h>
Classes
struct PollFdIndex
class VarSizeTypeAllocator
Public Types
using pollfd_vector = std::vector< pollfd, VarSizeTypeAllocator< pollfd, nfds_t > >
using pollfdindex_map = std::unordered_map< int, PollFdIndex, std::hash< int >, std::equal_to<>, VarSizeTypeAllocator< std::pair< const int, PollFdIndex >, nfds_t > >
Public Member Functions
PollFdsManager ()
void muxAdd (core::DescriptorEventReceiver *eventReceiver, short event)
void muxDel (int fd, short event)
void muxOn (const core::DescriptorEventReceiver *eventReceiver, short event)
void muxOff (const DescriptorEventReceiver *eventReceiver, short event)
pollfd * getEvents ()
const pollfdindex_map & getPollFdIndices () const
nfds_t getCurrentSize () const
Private Member Functions
void compress ()
Private Attributes
nfds_t nextIndex = 0
pollfd_vector pollfds
pollfdindex_map pollFdIndices
Detailed Description
Definition at line 68 of file EventMultiplexer.h.
Member Typedef Documentation
pollfd_vector
using core::multiplexer::poll::PollFdsManager::pollfd_vector = std::vector<pollfd, VarSizeTypeAllocator<pollfd, nfds_t> >
Definition at line 145 of file EventMultiplexer.h.
pollfdindex_map
using core::multiplexer::poll::PollFdsManager::pollfdindex_map = std::unordered_map<int, PollFdIndex, std::hash<int>, std::equal_to<>, VarSizeTypeAllocator<std::pair<const int, PollFdIndex>, nfds_t> >
Definition at line 152 of file EventMultiplexer.h.
Constructor & Destructor Documentation
PollFdsManager()
core::multiplexer::poll::PollFdsManager::PollFdsManager () explicit
Definition at line 68 of file EventMultiplexer.cpp.
{
        pollfds.resize(1, {-1, 0, 0});
        pollFdIndices.reserve(1);
    }
Member Function Documentation
compress()
void core::multiplexer::poll::PollFdsManager::compress () private
Definition at line 124 of file EventMultiplexer.cpp.
{
        (void) std::remove_if(pollfds.begin(), pollfds.end(), [](const pollfd& pollFd) -> bool {
            return pollFd.fd < 0;
        });
        pollfds.resize(pollFdIndices.size() + 1, {-1, 0, 0});
        pollFdIndices.reserve(pollFdIndices.size() + 1);
        for (uint32_t i = 0; i < pollFdIndices.size(); i++) {
            pollFdIndices[pollfds[i].fd].index = i;
        }
        nextIndex = pollFdIndices.size();
    }
Referenced by muxDel().
getCurrentSize()
nfds_t core::multiplexer::poll::PollFdsManager::getCurrentSize () const
Definition at line 148 of file EventMultiplexer.cpp.
{
        return nextIndex;
    }
getEvents()
pollfd * core::multiplexer::poll::PollFdsManager::getEvents ()
Definition at line 140 of file EventMultiplexer.cpp.
{
        return pollfds.data();
    }
getPollFdIndices()
const PollFdsManager::pollfdindex_map & core::multiplexer::poll::PollFdsManager::getPollFdIndices () const
Definition at line 144 of file EventMultiplexer.cpp.
{
        return pollFdIndices;
    }
muxAdd()
void core::multiplexer::poll::PollFdsManager::muxAdd (core::DescriptorEventReceiver * eventReceiver, short event)
Definition at line 73 of file EventMultiplexer.cpp.
{
        const int fd = eventReceiver->getRegisteredFd();
        if (!pollFdIndices.contains(fd)) {
            pollfds[nextIndex].events = event;
            pollfds[nextIndex].fd = fd;
            pollFdIndices[fd].index = nextIndex;
            pollFdIndices[fd].events = event;
            ++nextIndex;
            if (nextIndex == pollfds.size()) {
                pollfds.resize(pollfds.size() * 2, {-1, 0, 0});
                pollFdIndices.reserve(pollfds.size());
            }
        } else {
            PollFdIndex& pollFdIndex = pollFdIndices[fd];
            pollfds[pollFdIndex.index].events |= event;
            pollFdIndex.events |= event;
        }
    }
References core::multiplexer::poll::PollFdsManager::PollFdIndex::events, and core::DescriptorEventReceiver::getRegisteredFd().
Referenced by core::multiplexer::poll::DescriptorEventPublisher::muxAdd().
muxDel()
void core::multiplexer::poll::PollFdsManager::muxDel (int fd, short event)
Definition at line 97 of file EventMultiplexer.cpp.
{
        const pollfdindex_map::iterator itPollFdIndex = pollFdIndices.find(fd);
        PollFdIndex& pollFdIndex = itPollFdIndex->second;
        pollfds[pollFdIndex.index].events &= static_cast<short>(~event); // tilde promotes to int
        pollFdIndex.events &= static_cast<short>(~event);                // tilde promotes to int
        if (pollFdIndex.events == 0) {
            pollfds[pollFdIndex.index].fd = -1; // Compress will keep track of that descriptor
            pollFdIndices.erase(fd);
            if (pollfds.size() > (pollFdIndices.size() * 2) + 1) {
                compress();
            }
        }
    }
References compress(), and core::multiplexer::poll::PollFdsManager::PollFdIndex::events.
Referenced by core::multiplexer::poll::DescriptorEventPublisher::muxDel().
muxOff()
void core::multiplexer::poll::PollFdsManager::muxOff (const DescriptorEventReceiver * eventReceiver, short event)
Definition at line 119 of file EventMultiplexer.cpp.
{
        pollfds[pollFdIndices.find(eventReceiver->getRegisteredFd())->second.index].events &=
            static_cast<short>(~event); // Tilde promotes to int
    }
Referenced by core::multiplexer::poll::DescriptorEventPublisher::muxOff().
muxOn()
void core::multiplexer::poll::PollFdsManager::muxOn (const core::DescriptorEventReceiver * eventReceiver, short event)
Definition at line 115 of file EventMultiplexer.cpp.
{
        pollfds[pollFdIndices.find(eventReceiver->getRegisteredFd())->second.index].events |= event;
    }
Referenced by core::multiplexer::poll::DescriptorEventPublisher::muxOn().
Member Data Documentation
nextIndex
nfds_t core::multiplexer::poll::PollFdsManager::nextIndex = 0 private
Definition at line 172 of file EventMultiplexer.h.
pollFdIndices
pollfdindex_map core::multiplexer::poll::PollFdsManager::pollFdIndices private
Definition at line 176 of file EventMultiplexer.h.
pollfds
pollfd_vector core::multiplexer::poll::PollFdsManager::pollfds private
Definition at line 175 of file EventMultiplexer.h.
The documentation for this class was generated from the following files:
core/multiplexer/poll/EventMultiplexer.h
core/multiplexer/poll/EventMultiplexer.cpp