SNode.C: database::mariadb::MariaDBClient Class Reference
database::mariadb::MariaDBClient Class Reference
#include <MariaDBClient.h>
Public Member Functions
MariaDBClient (const MariaDBConnectionDetails &details)
~MariaDBClient () override
MariaDBCommandSequence & query (const std::string &sql, const std::function< void(const MYSQL_ROW)> &onQuery, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & exec (const std::string &sql, const std::function< void(void)> &onExec, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & startTransactions (const std::function< void(void)> &onAutoCommit, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & endTransactions (const std::function< void(void)> &onAutoCommit, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & commit (const std::function< void(void)> &onCommit, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & rollback (const std::function< void(void)> &onRollback, const std::function< void(const std::string &, unsigned int)> &onError)
void affectedRows (const std::function< void(int)> &onAffectedRows, const std::function< void(const std::string &, unsigned int)> &onErro)
void fieldCount (const std::function< void(unsigned int)> &onFieldCount, const std::function< void(const std::string &, unsigned int)> &onError)
Protected Attributes
MYSQL_RES * lastResult = nullptr
Private Member Functions
MariaDBCommandSequence & execute_async (MariaDBCommand *mariaDBCommand) final
void execute_sync (MariaDBCommandSync *mariaDBCommand) final
void connectionVanished ()
Private Attributes
MariaDBConnection * mariaDBConnection = nullptr
MariaDBConnectionDetails details
Friends
class MariaDBConnection
Detailed Description
Definition at line 66 of file MariaDBClient.h.
Constructor & Destructor Documentation
MariaDBClient()
database::mariadb::MariaDBClient::MariaDBClient (const MariaDBConnectionDetails & details) explicit
Definition at line 34 of file MariaDBClient.cpp.
        : details(details) {
    }
References details.
~MariaDBClient()
database::mariadb::MariaDBClient::~MariaDBClient () override
Definition at line 38 of file MariaDBClient.cpp.
{
        if (mariaDBConnection != nullptr) {
            mariaDBConnection->unmanaged();
        }
    }
References mariaDBConnection, and database::mariadb::MariaDBConnection::unmanaged().
Member Function Documentation
affectedRows()
void database::mariadb::MariaDBClientSyncAPI::affectedRows (const std::function< void(int)> & onAffectedRows, const std::function< void(const std::string &, unsigned int)> & onErro) inherited
Definition at line 35 of file MariaDBClientSyncAPI.cpp.
{
        execute_sync(new database::mariadb::commands::sync::MariaDBAffectedRowsCommand(onAffectedRows, onError));
    }
commit()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::commit (const std::function< void(void)> & onCommit, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 82 of file MariaDBClientASyncAPI.cpp.
{
        return execute_async(new database::mariadb::commands::async::MariaDBCommitCommand(onCommit, onError));
    }
References database::mariadb::MariaDBClientASyncAPI::execute_async().
connectionVanished()
void database::mariadb::MariaDBClient::connectionVanished () private
Definition at line 60 of file MariaDBClient.cpp.
{
        mariaDBConnection = nullptr;
    }
References mariaDBConnection.
Referenced by database::mariadb::MariaDBConnection::~MariaDBConnection().
endTransactions()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::endTransactions (const std::function< void(void)> & onAutoCommit, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 77 of file MariaDBClientASyncAPI.cpp.
{
        return execute_async(new database::mariadb::commands::async::MariaDBAutoCommitCommand(1, onAutoCommit, onError));
    }
exec()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::exec (const std::string & sql, const std::function< void(void)> & onExec, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 66 of file MariaDBClientASyncAPI.cpp.
{
        return execute_async(new database::mariadb::commands::async::MariaDBExecCommand(sql, onExec, onError));
    }
References database::mariadb::MariaDBClientASyncAPI::execute_async().
execute_async()
MariaDBCommandSequence & database::mariadb::MariaDBClient::execute_async (MariaDBCommand * mariaDBCommand) final private virtual
Implements database::mariadb::MariaDBClientASyncAPI.
Definition at line 44 of file MariaDBClient.cpp.
{
        if (mariaDBConnection == nullptr) {
            mariaDBConnection = new MariaDBConnection(this, details);
        }
        return mariaDBConnection->execute_async(std::move(MariaDBCommandSequence().execute_async(mariaDBCommand)));
    }
References details, database::mariadb::MariaDBCommandSequence::execute_async(), database::mariadb::MariaDBConnection::execute_async(), database::mariadb::MariaDBCommandSequence::MariaDBCommandSequence(), mariaDBConnection, and database::mariadb::MariaDBConnection::MariaDBConnection().
execute_sync()
void database::mariadb::MariaDBClient::execute_sync (MariaDBCommandSync * mariaDBCommand) final private virtual
Implements database::mariadb::MariaDBClientSyncAPI.
Definition at line 52 of file MariaDBClient.cpp.
{
        if (mariaDBConnection == nullptr) {
            mariaDBConnection = new MariaDBConnection(this, details);
        }
        mariaDBConnection->execute_sync(mariaDBCommand);
    }
References details, database::mariadb::MariaDBConnection::execute_sync(), mariaDBConnection, and database::mariadb::MariaDBConnection::MariaDBConnection().
fieldCount()
void database::mariadb::MariaDBClientSyncAPI::fieldCount (const std::function< void(unsigned int)> & onFieldCount, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 40 of file MariaDBClientSyncAPI.cpp.
{
        execute_sync(new database::mariadb::commands::sync::MariaDBFieldCountCommand(onFieldCount, onError));
    }
References database::mariadb::MariaDBClientSyncAPI::execute_sync(), and database::mariadb::commands::sync::MariaDBFieldCountCommand::MariaDBFieldCountCommand().
query()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::query (const std::string & sql, const std::function< void(const MYSQL_ROW)> & onQuery, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 44 of file MariaDBClientASyncAPI.cpp.
{
        return execute_async(new database::mariadb::commands::async::MariaDBQueryCommand(
                                 sql,
                                 []() -> void {
                                 },
                                 onError))
            .execute_async(new database::mariadb::commands::sync::MariaDBUseResultCommand(
                [&lastResult = this->lastResult](MYSQL_RES* result) -> void {
                    lastResult = result;
                },
                onError))
            .execute_async(new database::mariadb::commands::async::MariaDBFetchRowCommand(lastResult, onQuery, onError))
            .execute_async(new database::mariadb::commands::async::MariaDBFreeResultCommand(
                lastResult,
                [this]() -> void {
                    lastResult = nullptr;
                },
                onError));
    }
rollback()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::rollback (const std::function< void(void)> & onRollback, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 87 of file MariaDBClientASyncAPI.cpp.
{
        return execute_async(new database::mariadb::commands::async::MariaDBRollbackCommand(onRollback, onError));
    }
References database::mariadb::MariaDBClientASyncAPI::execute_async().
startTransactions()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::startTransactions (const std::function< void(void)> & onAutoCommit, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 72 of file MariaDBClientASyncAPI.cpp.
{
        return execute_async(new database::mariadb::commands::async::MariaDBAutoCommitCommand(0, onAutoCommit, onError));
    }
Friends And Related Symbol Documentation
MariaDBConnection
friend class MariaDBConnection friend
Definition at line 83 of file MariaDBClient.h.
Member Data Documentation
details
MariaDBConnectionDetails database::mariadb::MariaDBClient::details private
Definition at line 81 of file MariaDBClient.h.
Referenced by execute_async(), execute_sync(), and MariaDBClient().
lastResult
MYSQL_RES* database::mariadb::MariaDBClientASyncAPI::lastResult = nullptr protected inherited
Definition at line 69 of file MariaDBClientASyncAPI.h.
mariaDBConnection
MariaDBConnection* database::mariadb::MariaDBClient::mariaDBConnection = nullptr private
Definition at line 79 of file MariaDBClient.h.
Referenced by connectionVanished(), execute_async(), execute_sync(), and ~MariaDBClient().
The documentation for this class was generated from the following files:
database/mariadb/MariaDBClient.h
database/mariadb/MariaDBClient.cpp