SNode.C: core::Descriptor Class Reference
core::Descriptor Class Reference
#include <Descriptor.h>
Public Member Functions
Descriptor ()=delete
Descriptor (const Descriptor &d)=delete
Descriptor (Descriptor &&d)=delete
int getFd () const
void setDontClose (bool dontClose=true)
Protected Member Functions
Descriptor (int fd)
Descriptor & operator= (int fd)
Descriptor & operator= (const Descriptor &descriptor)=delete
Descriptor & operator= (Descriptor &&descriptor)=delete
virtual ~Descriptor ()
Private Attributes
int fd = -1
bool autoClose = true
Detailed Description
Definition at line 28 of file Descriptor.h.
Constructor & Destructor Documentation
Descriptor() [1/4]
core::Descriptor::Descriptor () delete
Descriptor() [2/4]
core::Descriptor::Descriptor (const Descriptor & d) delete
Descriptor() [3/4]
core::Descriptor::Descriptor (Descriptor && d) delete
Descriptor() [4/4]
core::Descriptor::Descriptor (int fd) explicit protected
Definition at line 29 of file Descriptor.cpp.
        : fd(fd) {
    }
References fd.
Referenced by core::file::File::File(), and core::file::FileReader::FileReader().
~Descriptor()
core::Descriptor::~Descriptor () protected virtual
Definition at line 39 of file Descriptor.cpp.
{
        if (autoClose && fd >= 0) {
            core::system::close(fd);
            fd = -1;
        }
    }
References autoClose, core::system::close(), and fd.
Member Function Documentation
getFd()
int core::Descriptor::getFd () const
Definition at line 46 of file Descriptor.cpp.
{
        return fd;
    }
References fd.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::bind(), net::phy::PhysicalSocket< SocketAddressT >::getPeername(), net::phy::PhysicalSocket< SocketAddressT >::getSockname(), net::phy::PhysicalSocket< SocketAddressT >::getSockopt(), net::phy::PhysicalSocket< SocketAddressT >::isValid(), core::file::FileReader::onEvent(), net::un::dgram::Socket::recvFd(), net::un::dgram::Socket::sendFd(), net::phy::PhysicalSocket< SocketAddressT >::setSockopt(), and net::phy::stream::PhysicalSocket< SocketAddressT >::shutdown().
operator=() [1/3]
Descriptor & core::Descriptor::operator= (const Descriptor & descriptor) protected delete
operator=() [2/3]
Descriptor & core::Descriptor::operator= (Descriptor && descriptor) protected delete
operator=() [3/3]
Descriptor & core::Descriptor::operator= (int fd) protected
Definition at line 33 of file Descriptor.cpp.
{
        this->fd = fd;
        return *this;
    }
References fd.
setDontClose()
void core::Descriptor::setDontClose (bool dontClose = true)
Definition at line 50 of file Descriptor.cpp.
{
        autoClose = !dontClose;
    }
References autoClose.
Member Data Documentation
autoClose
bool core::Descriptor::autoClose = true private
Definition at line 50 of file Descriptor.h.
Referenced by setDontClose(), and ~Descriptor().
fd
int core::Descriptor::fd = -1 private
Definition at line 49 of file Descriptor.h.
Referenced by Descriptor(), getFd(), operator=(), and ~Descriptor().
The documentation for this class was generated from the following files:
core/Descriptor.h
core/Descriptor.cpp