SNode.C: web::http::StatusCode Class Reference
web::http::StatusCode Class Reference
#include <StatusCodes.h>
Static Public Member Functions
static std::string reason (int status)
static bool contains (int status)
Static Private Attributes
static std::map< int, std::string > statusCode
Detailed Description
Definition at line 53 of file StatusCodes.h.
Member Function Documentation
contains()
bool web::http::StatusCode::contains (int status) static
Definition at line 131 of file StatusCodes.cpp.
{
        return statusCode.contains(status);
    }
References statusCode.
Referenced by web::http::client::ResponseParser::parseStartLine(), and reason().
reason()
std::string web::http::StatusCode::reason (int status) static
Definition at line 121 of file StatusCodes.cpp.
{
        std::string reasonPhrase = "unknown status code";
        if (StatusCode::contains(status)) {
            reasonPhrase = statusCode[status];
        }
        return reasonPhrase;
    }
References contains(), and statusCode.
Referenced by web::http::server::Request::Request(), web::http::server::SocketContext::requestCompleted(), web::http::server::SocketContext::responseCompleted(), web::http::server::SocketContext::responseStarted(), web::http::server::Response::sendHeader(), express::Response::sendStatus(), web::http::server::Response::sendStatus(), and web::http::server::Response::upgrade().
Member Data Documentation
statusCode
std::map< int, std::string > web::http::StatusCode::statusCode static private
Definition at line 60 of file StatusCodes.h.
Referenced by contains(), and reason().
The documentation for this class was generated from the following files:
web/http/StatusCodes.h
web/http/StatusCodes.cpp