SNode.C: iot::mqtt::FixedHeader Class Reference
iot::mqtt::FixedHeader Class Reference
#include <FixedHeader.h>
Public Member Functions
FixedHeader ()
FixedHeader (uint8_t type, uint8_t flags, uint32_t remainingLength=0)
~FixedHeader ()
std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
std::vector< char > serialize () const
uint8_t getType () const
uint8_t getFlags () const
void setRemainingLength (uint32_t remainingLength)
uint32_t getRemainingLength () const
bool isComplete () const
bool isError () const
void reset ()
Private Attributes
types::UInt8 typeFlags
types::UIntV remainingLength
bool complete = false
bool error = false
int state = 0
Detailed Description
Definition at line 62 of file FixedHeader.h.
Constructor & Destructor Documentation
FixedHeader() [1/2]
iot::mqtt::FixedHeader::FixedHeader ()
Definition at line 50 of file FixedHeader.cpp.
{
    }
FixedHeader() [2/2]
iot::mqtt::FixedHeader::FixedHeader (uint8_t type, uint8_t flags, uint32_t remainingLength = 0)
Definition at line 53 of file FixedHeader.cpp.
{
        this->typeFlags = static_cast<uint8_t>((type << 4) | (flags & 0x0F));
        this->remainingLength = remainingLength;
    }
References iot::mqtt::types::UIntV::operator=(), iot::mqtt::types::UInt8::operator=(), remainingLength, and typeFlags.
Referenced by iot::mqtt::ControlPacket::serialize().
~FixedHeader()
iot::mqtt::FixedHeader::~FixedHeader ()
Definition at line 58 of file FixedHeader.cpp.
{
    }
Member Function Documentation
deserialize()
std::size_t iot::mqtt::FixedHeader::deserialize (iot::mqtt::MqttContext * mqttContext)
Definition at line 61 of file FixedHeader.cpp.
{
        std::size_t consumed = 0;
        switch (state) {
            case 0:
                consumed += typeFlags.deserialize(mqttContext);
                if (!typeFlags.isComplete()) {
                    break;
                }
                state++;
                [[fallthrough]];
            case 1:
                consumed += remainingLength.deserialize(mqttContext);
                complete = remainingLength.isComplete();
                error = remainingLength.isError();
                break;
        }
        return consumed;
    }
References complete, iot::mqtt::types::TypeBase< ValueTypeT >::deserialize(), iot::mqtt::types::UIntV::deserialize(), error, iot::mqtt::types::TypeBase< ValueTypeT >::isComplete(), iot::mqtt::types::UIntV::isError(), remainingLength, state, and typeFlags.
Referenced by iot::mqtt::Mqtt::onReceivedFromPeer().
getFlags()
uint8_t iot::mqtt::FixedHeader::getFlags () const
Definition at line 89 of file FixedHeader.cpp.
{
        return static_cast<uint8_t>(typeFlags & 0x0F);
    }
References typeFlags.
Referenced by iot::mqtt::client::Mqtt::createControlPacketDeserializer(), iot::mqtt::server::Mqtt::createControlPacketDeserializer(), and iot::mqtt::Mqtt::printFixedHeader().
getRemainingLength()
uint32_t iot::mqtt::FixedHeader::getRemainingLength () const
Definition at line 97 of file FixedHeader.cpp.
{
        return remainingLength;
    }
References remainingLength.
Referenced by iot::mqtt::client::Mqtt::createControlPacketDeserializer(), iot::mqtt::server::Mqtt::createControlPacketDeserializer(), and iot::mqtt::Mqtt::printFixedHeader().
getType()
uint8_t iot::mqtt::FixedHeader::getType () const
Definition at line 85 of file FixedHeader.cpp.
{
        return static_cast<uint8_t>(typeFlags >> 0x04);
    }
References typeFlags.
Referenced by iot::mqtt::client::Mqtt::createControlPacketDeserializer(), iot::mqtt::server::Mqtt::createControlPacketDeserializer(), and iot::mqtt::Mqtt::printFixedHeader().
isComplete()
bool iot::mqtt::FixedHeader::isComplete () const
Definition at line 101 of file FixedHeader.cpp.
{
        return complete;
    }
References complete.
isError()
bool iot::mqtt::FixedHeader::isError () const
Definition at line 105 of file FixedHeader.cpp.
{
        return error;
    }
References error.
reset()
void iot::mqtt::FixedHeader::reset ()
Definition at line 118 of file FixedHeader.cpp.
{
        typeFlags.reset();
        remainingLength.reset();
        complete = false;
        error = false;
        state = 0;
    }
References complete, error, remainingLength, iot::mqtt::types::TypeBase< ValueTypeT >::reset(), iot::mqtt::types::UIntV::reset(), state, and typeFlags.
serialize()
std::vector< char > iot::mqtt::FixedHeader::serialize () const
Definition at line 109 of file FixedHeader.cpp.
{
        std::vector<char> packet = typeFlags.serialize();
        std::vector<char> tmpVector = remainingLength.serialize();
        packet.insert(packet.end(), tmpVector.begin(), tmpVector.end());
        return packet;
    }
References remainingLength, iot::mqtt::types::TypeBase< ValueTypeT >::serialize(), and typeFlags.
Referenced by iot::mqtt::Mqtt::printFixedHeader(), and iot::mqtt::ControlPacket::serialize().
setRemainingLength()
void iot::mqtt::FixedHeader::setRemainingLength (uint32_t remainingLength)
Definition at line 93 of file FixedHeader.cpp.
{
        this->remainingLength = remainingLength;
    }
References iot::mqtt::types::UIntV::operator=(), and remainingLength.
Member Data Documentation
complete
bool iot::mqtt::FixedHeader::complete = false private
Definition at line 87 of file FixedHeader.h.
Referenced by deserialize(), isComplete(), and reset().
error
bool iot::mqtt::FixedHeader::error = false private
Definition at line 88 of file FixedHeader.h.
Referenced by deserialize(), isError(), and reset().
remainingLength
types::UIntV iot::mqtt::FixedHeader::remainingLength private
Definition at line 85 of file FixedHeader.h.
Referenced by deserialize(), FixedHeader(), getRemainingLength(), reset(), serialize(), and setRemainingLength().
state
int iot::mqtt::FixedHeader::state = 0 private
Definition at line 90 of file FixedHeader.h.
Referenced by deserialize(), and reset().
typeFlags
types::UInt8 iot::mqtt::FixedHeader::typeFlags private
Definition at line 84 of file FixedHeader.h.
Referenced by deserialize(), FixedHeader(), getFlags(), getType(), reset(), and serialize().
The documentation for this class was generated from the following files:
iot/mqtt/FixedHeader.h
iot/mqtt/FixedHeader.cpp