SNode.C: iot::mqtt_fast::ControlPacketFactory Class Reference
iot::mqtt_fast::ControlPacketFactory Class Reference
#include <ControlPacketFactory.h>
Public Member Functions
ControlPacketFactory (core::socket::SocketContext *socketContext)
std::size_t construct ()
bool isComplete () const
bool isError () const
iot::mqtt_fast::types::Binary & getPacket ()
uint8_t getPacketType ()
uint8_t getPacketFlags ()
uint64_t getRemainingLength ()
void reset ()
Private Attributes
bool completed = false
bool error = false
int state = 0
iot::mqtt_fast::types::Int_1 typeFlags
iot::mqtt_fast::types::Int_V remainingLength
iot::mqtt_fast::types::Binary data
Detailed Description
Definition at line 62 of file ControlPacketFactory.h.
Constructor & Destructor Documentation
ControlPacketFactory()
iot::mqtt_fast::ControlPacketFactory::ControlPacketFactory (core::socket::SocketContext * socketContext) explicit
Definition at line 52 of file ControlPacketFactory.cpp.
        : typeFlags(socketContext)
        , remainingLength(socketContext)
        , data(socketContext) {
    }
References iot::mqtt_fast::types::Binary::Binary(), data, iot::mqtt_fast::types::Int_1::Int_1(), iot::mqtt_fast::types::Int_V::Int_V(), remainingLength, and typeFlags.
Referenced by iot::mqtt_fast::SocketContext::SocketContext().
Member Function Documentation
construct()
std::size_t iot::mqtt_fast::ControlPacketFactory::construct ()
Definition at line 58 of file ControlPacketFactory.cpp.
{
        std::size_t consumed = 0;
        switch (state) {
            case 0: // Type - Flags
                consumed = typeFlags.construct();
                if (typeFlags.isComplete()) {
                    state++;
                } else {
                    error = typeFlags.isError();
                }
                break;
            case 1: // Remaining length
                consumed = remainingLength.construct();
                if (remainingLength.isComplete()) {
                    data.setLength(remainingLength.getValue());
                    completed = remainingLength.getValue() == 0;
                    state++;
                } else {
                    error = remainingLength.isError();
                }
                break;
            case 2: // Var-Header + Payload
                consumed = data.construct();
                if (data.isComplete()) {
                    completed = true;
                    state++;
                } else {
                    error = data.isError();
                }
                break;
        }
        return consumed;
    }
References completed, iot::mqtt_fast::types::Binary::construct(), iot::mqtt_fast::types::Int_1::construct(), iot::mqtt_fast::types::Int_V::construct(), data, error, iot::mqtt_fast::types::Int_V::getValue(), iot::mqtt_fast::types::TypeBase::isComplete(), iot::mqtt_fast::types::TypeBase::isError(), remainingLength, iot::mqtt_fast::types::Binary::setLength(), state, and typeFlags.
Referenced by iot::mqtt_fast::SocketContext::onReceivedFromPeer().
getPacket()
iot::mqtt_fast::types::Binary & iot::mqtt_fast::ControlPacketFactory::getPacket ()
Definition at line 102 of file ControlPacketFactory.cpp.
{
        return data;
    }
References data.
Referenced by iot::mqtt_fast::ControlPacket::ControlPacket(), and iot::mqtt_fast::SocketContext::onReceivedFromPeer().
getPacketFlags()
uint8_t iot::mqtt_fast::ControlPacketFactory::getPacketFlags ()
Definition at line 110 of file ControlPacketFactory.cpp.
{
        return static_cast<uint8_t>(typeFlags.getValue() & 0x0F);
    }
References iot::mqtt_fast::types::Int_1::getValue(), and typeFlags.
Referenced by iot::mqtt_fast::ControlPacket::ControlPacket(), iot::mqtt_fast::SocketContext::onReceivedFromPeer(), and iot::mqtt_fast::packets::Publish::Publish().
getPacketType()
uint8_t iot::mqtt_fast::ControlPacketFactory::getPacketType ()
Definition at line 106 of file ControlPacketFactory.cpp.
{
        return static_cast<uint8_t>(typeFlags.getValue() >> 0x04);
    }
References iot::mqtt_fast::types::Int_1::getValue(), and typeFlags.
Referenced by iot::mqtt_fast::ControlPacket::ControlPacket(), and iot::mqtt_fast::SocketContext::onReceivedFromPeer().
getRemainingLength()
uint64_t iot::mqtt_fast::ControlPacketFactory::getRemainingLength ()
Definition at line 114 of file ControlPacketFactory.cpp.
{
        return data.getValue().size();
    }
References data, and iot::mqtt_fast::types::Binary::getValue().
Referenced by iot::mqtt_fast::SocketContext::onReceivedFromPeer().
isComplete()
bool iot::mqtt_fast::ControlPacketFactory::isComplete () const
Definition at line 94 of file ControlPacketFactory.cpp.
{
        return completed;
    }
References completed.
Referenced by iot::mqtt_fast::SocketContext::onReceivedFromPeer().
isError()
bool iot::mqtt_fast::ControlPacketFactory::isError () const
Definition at line 98 of file ControlPacketFactory.cpp.
{
        return error;
    }
References error.
Referenced by iot::mqtt_fast::SocketContext::onReceivedFromPeer().
reset()
void iot::mqtt_fast::ControlPacketFactory::reset ()
Definition at line 118 of file ControlPacketFactory.cpp.
{
        completed = false;
        error = false;
        state = 0;
        typeFlags.reset();
        remainingLength.reset();
        data.reset();
    }
References completed, data, error, remainingLength, iot::mqtt_fast::types::Binary::reset(), iot::mqtt_fast::types::Int_1::reset(), iot::mqtt_fast::types::Int_V::reset(), state, and typeFlags.
Referenced by iot::mqtt_fast::SocketContext::onReceivedFromPeer().
Member Data Documentation
completed
bool iot::mqtt_fast::ControlPacketFactory::completed = false private
Definition at line 77 of file ControlPacketFactory.h.
Referenced by construct(), isComplete(), and reset().
data
iot::mqtt_fast::types::Binary iot::mqtt_fast::ControlPacketFactory::data private
Definition at line 83 of file ControlPacketFactory.h.
Referenced by construct(), ControlPacketFactory(), getPacket(), getRemainingLength(), and reset().
error
bool iot::mqtt_fast::ControlPacketFactory::error = false private
Definition at line 78 of file ControlPacketFactory.h.
Referenced by construct(), isError(), and reset().
remainingLength
iot::mqtt_fast::types::Int_V iot::mqtt_fast::ControlPacketFactory::remainingLength private
Definition at line 82 of file ControlPacketFactory.h.
Referenced by construct(), ControlPacketFactory(), and reset().
state
int iot::mqtt_fast::ControlPacketFactory::state = 0 private
Definition at line 79 of file ControlPacketFactory.h.
Referenced by construct(), and reset().
typeFlags
iot::mqtt_fast::types::Int_1 iot::mqtt_fast::ControlPacketFactory::typeFlags private
Definition at line 81 of file ControlPacketFactory.h.
Referenced by construct(), ControlPacketFactory(), getPacketFlags(), getPacketType(), and reset().
The documentation for this class was generated from the following files:
iot/mqtt-fast/ControlPacketFactory.h
iot/mqtt-fast/ControlPacketFactory.cpp