SNode.C: web::http::server::SocketContextUpgradeFactorySelector Class Reference
web::http::server::SocketContextUpgradeFactorySelector Class Reference
#include <SocketContextUpgradeFactorySelector.h>
Public Types
using SocketContextUpgradeFactory = web::http::server::SocketContextUpgradeFactory
using Request = typename SocketContextUpgradeFactory::Request
using Response = typename SocketContextUpgradeFactory::Response
Public Member Functions
SocketContextUpgradeFactory * select (Request &req, Response &res) override
bool add (SocketContextUpgradeFactory *socketContextUpgradeFactory)
void link (const std::string &socketContextUpgradeName, SocketContextUpgradeFactory *(*linkedPlugin)())
void allowDlOpen ()
void unload (SocketContextUpgradeFactory *socketContextUpgradeFactory)
Static Public Member Functions
static SocketContextUpgradeFactorySelector * instance ()
Protected Member Functions
SocketContextUpgradeFactory * select (const std::string &socketContextUpgradeName)
bool add (SocketContextUpgradeFactory *socketContextUpgradeFactory, void *handler)
SocketContextUpgradeFactory * load (const std::string &socketContextUpgradeName, const std::string &socketContextUpgradeFactoryLibraryFile, const std::string &socketContextUpgradeFactoryFunctionName)
Private Types
using Super = web::http::SocketContextUpgradeFactorySelector< web::http::server::SocketContextUpgradeFactory >
Private Member Functions
SocketContextUpgradeFactory * load (const std::string &socketContextUpgradeName) override
Private Attributes
std::map< std::string, SocketContextPlugin > socketContextUpgradePlugins
std::map< std::string, SocketContextUpgradeFactory *(*)()> linkedSocketContextUpgradePlugins
bool onlyLinked
Detailed Description
Definition at line 34 of file SocketContextUpgradeFactorySelector.h.
Member Typedef Documentation
Request
using web::http::SocketContextUpgradeFactorySelector< web::http::server::SocketContextUpgradeFactory >::Request = typename SocketContextUpgradeFactory::Request inherited
Definition at line 38 of file SocketContextUpgradeFactorySelector.h.
Response
using web::http::SocketContextUpgradeFactorySelector< web::http::server::SocketContextUpgradeFactory >::Response = typename SocketContextUpgradeFactory::Response inherited
Definition at line 39 of file SocketContextUpgradeFactorySelector.h.
SocketContextUpgradeFactory
using web::http::SocketContextUpgradeFactorySelector< web::http::server::SocketContextUpgradeFactory >::SocketContextUpgradeFactory = web::http::server::SocketContextUpgradeFactory inherited
Definition at line 37 of file SocketContextUpgradeFactorySelector.h.
Super
using web::http::server::SocketContextUpgradeFactorySelector::Super = web::http::SocketContextUpgradeFactorySelector<web::http::server::SocketContextUpgradeFactory> private
Definition at line 37 of file SocketContextUpgradeFactorySelector.h.
Member Function Documentation
add() [1/2]
bool web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::add (SocketContextUpgradeFactory * socketContextUpgradeFactory) inherited
Definition at line 54 of file SocketContextUpgradeFactorySelector.hpp.
{
        return add(socketContextUpgradeFactory, nullptr);
    }
add() [2/2]
bool web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::add (SocketContextUpgradeFactory * socketContextUpgradeFactory, void * handler) protected inherited
Definition at line 71 of file SocketContextUpgradeFactorySelector.hpp.
{
        bool success = false;
        if (socketContextUpgradeFactory != nullptr) {
            SocketContextPlugin socketContextPlugin = {.socketContextUpgradeFactory = socketContextUpgradeFactory, .handle = handle};
            std::tie(std::ignore, success) = socketContextUpgradePlugins.insert({socketContextUpgradeFactory->name(), socketContextPlugin});
        }
        return success;
    }
allowDlOpen()
void web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::allowDlOpen () inherited
Definition at line 58 of file SocketContextUpgradeFactorySelector.hpp.
{
        onlyLinked = false;
    }
instance()
SocketContextUpgradeFactorySelector * web::http::server::SocketContextUpgradeFactorySelector::instance () static
Definition at line 60 of file SocketContextUpgradeFactorySelector.cpp.
{
        static SocketContextUpgradeFactorySelector socketContextUpgradeFactorySelector;
        return &socketContextUpgradeFactorySelector;
    }
Referenced by web::http::server::SocketContextUpgradeFactory::checkRefCount(), web::http::server::SocketContextUpgradeFactory::link(), and web::http::server::Response::upgrade().
link()
void web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::link (const std::string & socketContextUpgradeName, SocketContextUpgradeFactory *(*)() linkedPlugin) inherited
Definition at line 56 of file SocketContextUpgradeFactorySelector.hpp.
{
        if (!linkedSocketContextUpgradePlugins.contains(socketContextUpgradeName)) {
            linkedSocketContextUpgradePlugins[socketContextUpgradeName] = linkedPlugin;
        }
        onlyLinked = true;
    }
load() [1/2]
SocketContextUpgradeFactorySelector::SocketContextUpgradeFactory * web::http::server::SocketContextUpgradeFactorySelector::load (const std::string & socketContextUpgradeName) override private virtual
Implements web::http::SocketContextUpgradeFactorySelector< web::http::server::SocketContextUpgradeFactory >.
Definition at line 42 of file SocketContextUpgradeFactorySelector.cpp.
{
        const std::string socketContextUpgradeFactoryLibraryFile = socketContextUpgradeName + "-server.so." SOVERSION;
        const std::string socketContextUpgradeFactoryFunctionName = socketContextUpgradeName + "ServerContextUpgradeFactory";
        std::string httpUpgradeInstallLibdir = HTTP_UPGRADE_INSTALL_LIBDIR;
#if !defined(NDEBUG)
        if (const char* httpUpgradeInstallLibdirEnv = std::getenv("HTTP_UPGRADE_INSTALL_LIBDIR")) {
            LOG(WARNING) << "HTTP: Overriding http upgrade library dir";
            httpUpgradeInstallLibdir = std::string(httpUpgradeInstallLibdirEnv);
        }
#endif
        return Super::load(socketContextUpgradeName,
                           httpUpgradeInstallLibdir + "/libsnodec-" + socketContextUpgradeFactoryLibraryFile,
                           socketContextUpgradeFactoryFunctionName);
    }
References web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::load().
load() [2/2]
SocketContextUpgradeFactory * web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::load (const std::string & socketContextUpgradeName, const std::string & socketContextUpgradeFactoryLibraryFile, const std::string & socketContextUpgradeFactoryFunctionName) protected inherited
Definition at line 67 of file SocketContextUpgradeFactorySelector.hpp.
{
        SocketContextUpgradeFactory* socketContextUpgradeFactory = nullptr;
        void* handle = core::DynamicLoader::dlOpen(socketContextUpgradeFactoryLibraryFile, RTLD_LAZY | RTLD_GLOBAL);
        if (handle != nullptr) {
            SocketContextUpgradeFactory* (*getSocketContextUpgradeFactory)() = reinterpret_cast<SocketContextUpgradeFactory* (*) ()>(
                core::DynamicLoader::dlSym(handle, socketContextUpgradeFactoryFunctionName));
            if (getSocketContextUpgradeFactory != nullptr) {
                socketContextUpgradeFactory = getSocketContextUpgradeFactory();
                if (socketContextUpgradeFactory != nullptr) {
                    if (add(socketContextUpgradeFactory, handle)) {
                        LOG(DEBUG) << "HTTP: SocketContextUpgradeFactory created successfull: " << socketContextUpgradeName;
                    } else {
                        LOG(DEBUG) << "HTTP: UpgradeSocketContext already existing. Not using: " << socketContextUpgradeName;
                        delete socketContextUpgradeFactory;
                        socketContextUpgradeFactory = nullptr;
                        core::DynamicLoader::dlClose(handle);
                    }
                } else {
                    LOG(DEBUG) << "HTTP: SocketContextUpgradeFactory not created: " << socketContextUpgradeName;
                    core::DynamicLoader::dlClose(handle);
                }
            } else {
                LOG(DEBUG) << "HTTP: Optaining function \"" << socketContextUpgradeFactoryFunctionName
                           << "\" in plugin failed: " << core::DynamicLoader::dlError();
                core::DynamicLoader::dlClose(handle);
            }
        }
        return socketContextUpgradeFactory;
    }
select() [1/2]
SocketContextUpgradeFactory * web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::select (const std::string & socketContextUpgradeName) protected inherited
Definition at line 63 of file SocketContextUpgradeFactorySelector.hpp.
{
        SocketContextUpgradeFactory* socketContextUpgradeFactory = nullptr;
        if (socketContextUpgradePlugins.contains(socketContextUpgradeName)) {
            socketContextUpgradeFactory = socketContextUpgradePlugins[socketContextUpgradeName].socketContextUpgradeFactory;
        } else if (linkedSocketContextUpgradePlugins.contains(socketContextUpgradeName)) {
            socketContextUpgradeFactory = linkedSocketContextUpgradePlugins[socketContextUpgradeName]();
            add(socketContextUpgradeFactory);
        } else if (!onlyLinked) {
            socketContextUpgradeFactory = load(socketContextUpgradeName);
        }
        return socketContextUpgradeFactory;
    }
select() [2/2]
SocketContextUpgradeFactory * web::http::server::SocketContextUpgradeFactorySelector::select (Request & req, Response & res) override virtual
Implements web::http::SocketContextUpgradeFactorySelector< web::http::server::SocketContextUpgradeFactory >.
Definition at line 66 of file SocketContextUpgradeFactorySelector.cpp.
{
        SocketContextUpgradeFactory* socketContextUpgradeFactory = nullptr;
        std::string upgradeContextNames = req.get("upgrade");
        while (!upgradeContextNames.empty() && socketContextUpgradeFactory == nullptr) {
            std::string upgradeContextName;
            std::string upgradeContextVersion;
            std::tie(upgradeContextName, upgradeContextNames) = httputils::str_split(upgradeContextNames, ',');
            std::tie(upgradeContextName, upgradeContextVersion) = httputils::str_split(upgradeContextName, '/');
            httputils::str_trimm(upgradeContextName);
            httputils::to_lower(upgradeContextName);
            socketContextUpgradeFactory = select(upgradeContextName);
        }
        if (socketContextUpgradeFactory != nullptr) {
            socketContextUpgradeFactory->prepare(req, res);
        }
        return socketContextUpgradeFactory;
    }
References web::http::server::Request::get(), web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::prepare(), web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactoryT >::select(), httputils::str_split(), httputils::str_trimm(), and httputils::to_lower().
Referenced by web::http::server::Response::upgrade().
unload()
void web::http::SocketContextUpgradeFactorySelector< SocketContextUpgradeFactory >::unload (SocketContextUpgradeFactory * socketContextUpgradeFactory) inherited
Definition at line 60 of file SocketContextUpgradeFactorySelector.hpp.
{
        std::string upgradeContextNames = socketContextUpgradeFactory->name();
        if (socketContextUpgradePlugins.contains(upgradeContextNames)) {
            SocketContextPlugin socketContextPlugin = socketContextUpgradePlugins[upgradeContextNames];
            socketContextUpgradePlugins.erase(upgradeContextNames);
            delete socketContextUpgradeFactory;
            if (socketContextPlugin.handle != nullptr) {
                core::DynamicLoader::dlCloseDelayed(socketContextPlugin.handle);
            }
        }
    }
Member Data Documentation
linkedSocketContextUpgradePlugins
std::map<std::string, SocketContextUpgradeFactory* (*) ()> web::http::SocketContextUpgradeFactorySelector< web::http::server::SocketContextUpgradeFactory >::linkedSocketContextUpgradePlugins private inherited
Definition at line 75 of file SocketContextUpgradeFactorySelector.h.
onlyLinked
bool web::http::SocketContextUpgradeFactorySelector< web::http::server::SocketContextUpgradeFactory >::onlyLinked private inherited
Definition at line 77 of file SocketContextUpgradeFactorySelector.h.
socketContextUpgradePlugins
std::map<std::string, SocketContextPlugin> web::http::SocketContextUpgradeFactorySelector< web::http::server::SocketContextUpgradeFactory >::socketContextUpgradePlugins private inherited
Definition at line 74 of file SocketContextUpgradeFactorySelector.h.
The documentation for this class was generated from the following files:
web/http/server/SocketContextUpgradeFactorySelector.h
web/http/server/SocketContextUpgradeFactorySelector.cpp