SNode.C: net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT > Class Template Reference
net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT > Class Template Reference
#include <ConfigSocketServer.h>
Public Member Functions
SSL_CTX * getSslCtx ()
SSL_CTX * getSniCtx (const std::string &serverNameIndication)
Public Member Functions inherited from net::config::ConfigInstance
ConfigInstance (ConfigInstance &)=delete
ConfigInstance (ConfigInstance &&)=delete
ConfigInstance & operator= (ConfigInstance &)=delete
ConfigInstance & operator= (ConfigInstance &&)=delete
Role getRole ()
const std::string & getInstanceName () const
void setInstanceName (const std::string &instanceName)
bool getDisabled () const
void setDisabled (bool disabled=true)
Public Member Functions inherited from net::config::ConfigTlsServer
ConfigTlsServer & setForceSni (bool forceSni=true)
bool getForceSni () const
ConfigTlsServer & addSniCerts (const std::map< std::string, std::map< std::string, std::variant< std::string, bool, ssl_option_t > > > &sniCerts)
ConfigTlsServer & addSniCert (const std::string &domain, const std::map< std::string, std::variant< std::string, bool, ssl_option_t > > &sniCert)
std::map< std::string, std::map< std::string, std::variant< std::string, bool, ssl_option_t > > > & getSniCerts ()
Public Member Functions inherited from net::config::ConfigTls
ConfigTls & setInitTimeout (const utils::Timeval &newInitTimeout)
utils::Timeval getInitTimeout () const
ConfigTls & setShutdownTimeout (const utils::Timeval &newShutdownTimeout)
utils::Timeval getShutdownTimeout () const
ConfigTls & setCert (const std::string &cert)
std::string getCert () const
ConfigTls & setCertKey (const std::string &certKey)
std::string getCertKey () const
ConfigTls & setCertKeyPassword (const std::string &certKeyPassword)
std::string getCertKeyPassword () const
ConfigTls & setCaCert (const std::string &caCert)
std::string getCaCert () const
ConfigTls & setCaCertDir (const std::string &caCertDir)
std::string getCaCertDir () const
ConfigTls & setCaCertUseDefaultDir (bool set=true)
bool getCaCertUseDefaultDir () const
ConfigTls & setCipherList (const std::string &cipherList)
std::string getCipherList () const
ConfigTls & setSslOptions (ssl_option_t sslOptions)
ssl_option_t getSslOptions () const
Protected Member Functions
ConfigSocketServer (const std::string &name)
~ConfigSocketServer () override
Protected Member Functions inherited from net::config::ConfigInstance
ConfigInstance (const std::string &instanceName, Role role)
virtual ~ConfigInstance ()
Protected Member Functions inherited from net::config::ConfigTlsServer
ConfigTlsServer (ConfigInstance *instance)
Protected Member Functions inherited from net::config::ConfigTls
ConfigTls (ConfigInstance *instance)
Protected Member Functions inherited from net::config::ConfigSection
ConfigSection (ConfigInstance *instance, const std::string &name, const std::string &description)
ConfigSection (const ConfigSection &)=delete
ConfigSection (ConfigSection &&)=delete
ConfigSection & operator= (const ConfigSection &)=delete
ConfigSection & operator= (ConfigSection &&)=delete
CLI::Option * addOption (const std::string &name, const std::string &description)
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
template<typename ValueType >
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
Static Private Member Functions
static int clientHelloCallback (SSL *ssl, int *al, void *arg)
Private Attributes
SSL_CTX * sslCtx = nullptr
std::list< SSL_CTX * > sniCtxs
std::map< std::string, SSL_CTX * > sniCtxMap
Additional Inherited Members
Public Types inherited from net::config::ConfigInstance
enum class Role { SERVER , CLIENT }
using Instance = ConfigInstance
Public Types inherited from net::config::ConfigTlsServer
using Tls = ConfigTlsServer
Protected Attributes inherited from net::config::ConfigSection
CLI::App * section = nullptr
Detailed Description
template<typename ConfigSocketServerBaseT>
class net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >
Definition at line 37 of file ConfigSocketServer.h.
Constructor & Destructor Documentation
ConfigSocketServer()
template<typename ConfigSocketServerBase > net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBase >::ConfigSocketServer (const std::string & name) explicit protected
Definition at line 36 of file ConfigSocketServer.hpp.
        : net::config::ConfigInstance(name, net::config::ConfigInstance::Role::SERVER)
        , ConfigSocketServerBase(this)
        , net::config::ConfigTlsServer(this) {
    }
References net::config::ConfigInstance::SERVER.
~ConfigSocketServer()
template<typename ConfigSocketServerBase > net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBase >::~ConfigSocketServer () override protected
Definition at line 43 of file ConfigSocketServer.hpp.
{
        if (sslCtx != nullptr) {
            core::socket::stream::tls::ssl_ctx_free(sslCtx);
        }
        for (SSL_CTX* sniCtx : sniCtxs) {
            if (sniCtx != nullptr) {
                core::socket::stream::tls::ssl_ctx_free(sniCtx);
            }
        }
    }
Member Function Documentation
clientHelloCallback()
template<typename ConfigSocketServerBase > int net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBase >::clientHelloCallback (SSL * ssl, int * al, void * arg) static private
Definition at line 163 of file ConfigSocketServer.hpp.
{
        int ret = SSL_CLIENT_HELLO_SUCCESS;
        ConfigSocketServer* config = static_cast<ConfigSocketServer*>(arg);
        std::string serverNameIndication = core::socket::stream::tls::ssl_get_servername_from_client_hello(ssl);
        if (!serverNameIndication.empty()) {
            SSL_CTX* sniSslCtx = config->getSniCtx(serverNameIndication);
            if (sniSslCtx != nullptr) {
                LOG(TRACE) << config->getInstanceName() << " SSL/TLS: Setting sni certificate for '" << serverNameIndication << "'";
                core::socket::stream::tls::ssl_set_ssl_ctx(ssl, sniSslCtx);
            } else if (config->getForceSni()) {
                LOG(TRACE) << config->getInstanceName() << " SSL/TLS: No sni certificate found for '" << serverNameIndication
                           << "' but forceSni set - terminating";
                ret = SSL_CLIENT_HELLO_ERROR;
                *al = SSL_AD_UNRECOGNIZED_NAME;
            } else {
                LOG(TRACE) << config->getInstanceName() << " SSL/TLS: No sni certificate found for '" << serverNameIndication
                           << "'. Still using master certificate";
            }
        } else {
            LOG(TRACE) << config->getInstanceName() << " SSL/TLS: No sni certificate requested from client. Still using master certificate";
        }
        return ret;
    }
References core::socket::stream::tls::ssl_set_ssl_ctx().
Referenced by net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getSniCtx()
template<typename ConfigSocketServerBase > SSL_CTX * net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBase >::getSniCtx (const std::string & serverNameIndication)
Definition at line 82 of file ConfigSocketServer.hpp.
{
        SSL_CTX* sniCtx = nullptr;
        if (sniCtxMap.empty()) {
            std::map<std::string, SSL_CTX*> sslSans = core::socket::stream::tls::ssl_get_sans(sslCtx);
            sniCtxMap.insert(sslSans.begin(), sslSans.end());
            for (const auto& [sni, ctx] : sniCtxMap) {
                LOG(TRACE) << getInstanceName() << " SSL/TLS: SSL_CTX (M) sni for '" << sni << "' from master certificate installed";
            }
            for (const auto& [domain, sniCertConf] : getSniCerts()) {
                if (!domain.empty()) {
                    core::socket::stream::tls::SslConfig sslConfig(true);
                    sslConfig.instanceName = getInstanceName();
                    for (const auto& [key, value] : sniCertConf) {
                        if (key == "Cert") {
                            sslConfig.cert = std::get<std::string>(value);
                        } else if (key == "CertKey") {
                            sslConfig.certKey = std::get<std::string>(value);
                        } else if (key == "CertKeyPassword") {
                            sslConfig.password = std::get<std::string>(value);
                        } else if (key == "CaCert") {
                            sslConfig.caCert = std::get<std::string>(value);
                        } else if (key == "CaCertDir") {
                            sslConfig.caCertDir = std::get<std::string>(value);
                        } else if (key == "CaCertUseDefaultDir") {
                            sslConfig.caCertUseDefaultDir = std::get<bool>(value);
                        } else if (key == "CipherList") {
                            sslConfig.cipherList = std::get<std::string>(value);
                        } else if (key == "SslOptions") {
                            sslConfig.sslOptions = std::get<ssl_option_t>(value);
                        }
                    }
                    SSL_CTX* newCtx = core::socket::stream::tls::ssl_ctx_new(sslConfig);
                    if (newCtx != nullptr) {
                        sniCtxs.push_back(newCtx);
                        sniCtxMap.insert({domain, newCtx});
                        LOG(TRACE) << getInstanceName() << " SSL/TLS: SSL_CTX (E) sni for '" << domain << "' explicitly installed";
                        for (const auto& [san, ctx] : core::socket::stream::tls::ssl_get_sans(newCtx)) {
                            sniCtxMap.insert({san, ctx});
                            LOG(TRACE) << getInstanceName() << " SSL/TLS: SSL_CTX (S) sni for '" << san << "' from SAN installed";
                        }
                    } else {
                        LOG(TRACE) << getInstanceName() << " SSL/TLS: Can not create SNI_SSL_CTX for domain '" << domain << "'";
                    }
                }
            }
            LOG(TRACE) << getInstanceName() << " SSL/TLS: SNI list result:";
            for (const auto& [sni, ctx] : sniCtxMap) {
                LOG(TRACE) << "  SNI: " << sni;
            }
        }
        LOG(TRACE) << getInstanceName() << " SSL/TLS: Lookup for sni='" << serverNameIndication << "' in sni certificates";
        std::map<std::string, SSL_CTX*>::iterator sniPairIt = std::find_if(
            sniCtxMap.begin(), sniCtxMap.end(), [&serverNameIndication, this](const std::pair<std::string, SSL_CTX*>& sniPair) -> bool {
                LOG(TRACE) << getInstanceName() << " SSL/TLS:  .. " << sniPair.first.c_str();
                return core::socket::stream::tls::match(sniPair.first.c_str(), serverNameIndication.c_str());
            });
        if (sniPairIt != sniCtxMap.end()) {
            LOG(TRACE) << getInstanceName() << " SSL/TLS: found '" << sniPairIt->first << "'";
            sniCtx = sniPairIt->second;
        } else {
            LOG(TRACE) << getInstanceName() << " SSL/TLS: not found";
        }
        return sniCtx;
    }
References net::config::ConfigInstance::getInstanceName().
getSslCtx()
template<typename ConfigSocketServerBase > SSL_CTX * net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBase >::getSslCtx ()
Definition at line 56 of file ConfigSocketServer.hpp.
{
        if (sslCtx == nullptr) {
            core::socket::stream::tls::SslConfig sslConfig(true);
            sslConfig.instanceName = getInstanceName();
            sslConfig.cert = getCert();
            sslConfig.certKey = getCertKey();
            sslConfig.password = getCertKeyPassword();
            sslConfig.caCert = getCaCert();
            sslConfig.caCertDir = getCaCertDir();
            sslConfig.cipherList = getCipherList();
            sslConfig.sslOptions = getSslOptions();
            sslConfig.caCertUseDefaultDir = getCaCertUseDefaultDir();
            sslCtx = core::socket::stream::tls::ssl_ctx_new(sslConfig);
            if (sslCtx != nullptr) {
                SSL_CTX_set_client_hello_cb(sslCtx, clientHelloCallback, this);
            }
        }
        return sslCtx;
    }
References core::socket::stream::tls::SslConfig::caCertUseDefaultDir, net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::clientHelloCallback(), net::config::ConfigTls::getCaCert(), net::config::ConfigTls::getCaCertDir(), net::config::ConfigTls::getCaCertUseDefaultDir(), net::config::ConfigTls::getCert(), net::config::ConfigTls::getCertKey(), net::config::ConfigTls::getCertKeyPassword(), net::config::ConfigTls::getCipherList(), net::config::ConfigInstance::getInstanceName(), net::config::ConfigTls::getSslOptions(), core::socket::stream::tls::ssl_ctx_new(), core::socket::stream::tls::SslConfig::SslConfig(), net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::sslCtx, and core::socket::stream::tls::SslConfig::sslOptions.
Member Data Documentation
sniCtxMap
template<typename ConfigSocketServerBaseT > std::map<std::string, SSL_CTX*> net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::sniCtxMap private
Definition at line 55 of file ConfigSocketServer.h.
sniCtxs
template<typename ConfigSocketServerBaseT > std::list<SSL_CTX*> net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::sniCtxs private
Definition at line 54 of file ConfigSocketServer.h.
sslCtx
template<typename ConfigSocketServerBaseT > SSL_CTX* net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::sslCtx = nullptr private
Definition at line 53 of file ConfigSocketServer.h.
Referenced by net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< net::in6::stream::config::ConfigSocketServer >::~ConfigSocketServer().
The documentation for this class was generated from the following files:
net/config/stream/tls/ConfigSocketServer.h
net/config/stream/tls/ConfigSocketServer.hpp