SNode.C: core::eventreceiver::ReadEventReceiver Class Reference
core::eventreceiver::ReadEventReceiver Class Reference abstract
#include <ReadEventReceiver.h>
Protected Member Functions
ReadEventReceiver (const std::string &name, const utils::Timeval &timeout)
virtual void readTimeout ()
Protected Member Functions inherited from core::DescriptorEventReceiver
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
Protected Member Functions inherited from core::Observer
void observed ()
void unObserved ()
virtual void unobservedEvent ()=0
Observer ()=default
Observer (Observer &)=delete
Observer (Observer &&)=delete
virtual ~Observer ()
Protected Member Functions inherited from core::EventReceiver
virtual ~EventReceiver ()=default
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Private Member Functions
virtual void readEvent ()=0
void dispatchEvent () final
void timeoutEvent () final
void signalEvent (int signum) override
Additional Inherited Members
Public Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
int getRegisteredFd () const
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Static Public Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Static Protected Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Detailed Description
Definition at line 57 of file ReadEventReceiver.h.
Constructor & Destructor Documentation
ReadEventReceiver()
core::eventreceiver::ReadEventReceiver::ReadEventReceiver (const std::string & name, const utils::Timeval & timeout) protected
Definition at line 53 of file ReadEventReceiver.cpp.
        : core::DescriptorEventReceiver(
              name + " Read",
              core::EventLoop::instance().getEventMultiplexer().getDescriptorEventPublisher(core::EventMultiplexer::DISP_TYPE::RD),
              timeout) {
    }
References core::DescriptorEventReceiver::DescriptorEventReceiver(), core::EventMultiplexer::getDescriptorEventPublisher(), core::EventLoop::getEventMultiplexer(), core::EventLoop::instance(), and core::EventMultiplexer::RD.
Referenced by apps::towercalculator::KeyboardReader::KeyboardReader(), core::pipe::PipeSink::PipeSink(), core::socket::stream::SocketReader::SocketReader(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
Member Function Documentation
dispatchEvent()
void core::eventreceiver::ReadEventReceiver::dispatchEvent () final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 64 of file ReadEventReceiver.cpp.
{
        readEvent();
    }
References readEvent().
readEvent()
virtual void core::eventreceiver::ReadEventReceiver::readEvent () private pure virtual
Implemented in core::socket::stream::SocketReader, core::socket::stream::tls::TLSHandshake, core::socket::stream::tls::TLSShutdown, apps::towercalculator::KeyboardReader, core::pipe::PipeSink, and database::mariadb::MariaDBConnection.
Referenced by dispatchEvent().
readTimeout()
void core::eventreceiver::ReadEventReceiver::readTimeout () protected virtual
Reimplemented in core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::legacy::SocketReader, core::socket::stream::legacy::SocketWriter, ConfigT >, core::socket::stream::SocketConnectionT< PhysicalSocketT, core::socket::stream::tls::SocketReader, core::socket::stream::tls::SocketWriter, ConfigT >, core::socket::stream::tls::TLSHandshake, core::socket::stream::tls::TLSShutdown, and database::mariadb::MariaDBConnection.
Definition at line 60 of file ReadEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
Referenced by timeoutEvent().
signalEvent()
void core::eventreceiver::ReadEventReceiver::signalEvent (int signum) override private virtual
Implements core::DescriptorEventReceiver.
Reimplemented in core::socket::stream::SocketReader, core::socket::stream::tls::TLSHandshake, and core::socket::stream::tls::TLSShutdown.
Definition at line 72 of file ReadEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
timeoutEvent()
void core::eventreceiver::ReadEventReceiver::timeoutEvent () final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 68 of file ReadEventReceiver.cpp.
{
        readTimeout();
    }
References readTimeout().
The documentation for this class was generated from the following files:
core/eventreceiver/ReadEventReceiver.h
core/eventreceiver/ReadEventReceiver.cpp