SNode.C: utils::SHA1 Class Reference
utils::SHA1 Class Reference
#include <sha1.h>
Public Member Functions
SHA1 ()
void update (const std::string &s)
void update (std::istream &is)
std::string final ()
Private Member Functions
void reset ()
void transform (uint32_t block[BLOCK_BYTES])
Static Private Member Functions
static void buffer_to_block (const std::string &buffer, uint32_t block[BLOCK_BYTES])
static void read (std::istream &is, std::string &s, std::size_t max)
Private Attributes
uint32_t digest [DIGEST_INTS] {}
std::string buffer
uint64_t transforms = 0
Static Private Attributes
static const unsigned int DIGEST_INTS = 5
static const unsigned int BLOCK_INTS = 16
static const unsigned int BLOCK_BYTES = BLOCK_INTS * 4
Detailed Description
Definition at line 35 of file sha1.h.
Constructor & Destructor Documentation
SHA1()
utils::SHA1::SHA1 ()
Definition at line 53 of file sha1.cpp.
               {
        reset();
    }
References reset().
Member Function Documentation
buffer_to_block()
void utils::SHA1::buffer_to_block (const std::string & buffer, uint32_t block[BLOCK_BYTES]) static private
Definition at line 236 of file sha1.cpp.
{
        /* Convert the std::string (byte buffer) to a uint32 array (MSB) */
        for (unsigned int i = 0; i < BLOCK_INTS; i++) {
            block[i] = static_cast<uint32_t>((buffer[4 * i + 3] & 0xff) | (buffer[4 * i + 2] & 0xff) << 8 |
                                             (buffer[4 * i + 1] & 0xff) << 16 | (buffer[4 * i + 0] & 0xff) << 24);
        }
    }
References BLOCK_INTS.
Referenced by final(), and update().
final()
std::string utils::SHA1::final ()
Definition at line 79 of file sha1.cpp.
{
        /* Total number of hashed bits */
        const uint64_t total_bits = (transforms * BLOCK_BYTES + buffer.size()) * 8;
        /* Padding */
        buffer += static_cast<std::string::value_type>(0x80);
        const std::size_t orig_size = buffer.size();
        while (buffer.size() < BLOCK_BYTES) {
            buffer += static_cast<char>(0x00);
        }
        uint32_t block[BLOCK_INTS];
        buffer_to_block(buffer, block);
        if (orig_size > BLOCK_BYTES - 8) {
            transform(block);
            for (unsigned int i = 0; i < BLOCK_INTS - 2; i++) {
                block[i] = 0;
            }
        }
        /* Append total_bits, split this uint64 into two uint32 */
        block[BLOCK_INTS - 1] = static_cast<uint32_t>(total_bits & 0x00000000FFFFFFFF);
        block[BLOCK_INTS - 2] = static_cast<uint32_t>((total_bits >> 32) & 0x00000000FFFFFFFF);
        transform(block);
        /* Hex std::string */
        std::ostringstream result;
        for (unsigned int i = 0; i < DIGEST_INTS; i++) {
            result << std::hex << std::setfill('0') << std::setw(8);
            result << (digest[i] & 0xffffffff);
        }
        /* Reset for next run */
        reset();
        return result.str();
    }
References BLOCK_BYTES, BLOCK_INTS, buffer, buffer_to_block(), digest, DIGEST_INTS, reset(), transform(), and transforms.
Referenced by utils::sha1().
read()
void utils::SHA1::read (std::istream & is, std::string & s, std::size_t max) static private
Definition at line 244 of file sha1.cpp.
{
        char* sbuf = new char[max];
        is.read(sbuf, static_cast<std::streamsize>(max));
        s.assign(sbuf, static_cast<unsigned long>(is.gcount()));
        delete[] sbuf;
    }
Referenced by update().
reset()
void utils::SHA1::reset () private
Definition at line 118 of file sha1.cpp.
                     {
        /* SHA1 initialization constants */
        digest[0] = 0x67452301;
        digest[1] = 0xefcdab89;
        digest[2] = 0x98badcfe;
        digest[3] = 0x10325476;
        digest[4] = 0xc3d2e1f0;
        /* Reset counters */
        transforms = 0;
        buffer = "";
    }
References buffer, digest, and transforms.
Referenced by final(), and SHA1().
transform()
void utils::SHA1::transform (uint32_t block[BLOCK_BYTES]) private
Definition at line 135 of file sha1.cpp.
{
        /* Copy digest[] to working vars */
        uint32_t a = digest[0];
        uint32_t b = digest[1];
        uint32_t c = digest[2];
        uint32_t d = digest[3];
        uint32_t e = digest[4];
        /* 4 rounds of 20 operations each. Loop unrolled. */
        SHA1_R0(a, b, c, d, e, 0)
        SHA1_R0(e, a, b, c, d, 1)
        SHA1_R0(d, e, a, b, c, 2)
        SHA1_R0(c, d, e, a, b, 3)
        SHA1_R0(b, c, d, e, a, 4)
        SHA1_R0(a, b, c, d, e, 5)
        SHA1_R0(e, a, b, c, d, 6)
        SHA1_R0(d, e, a, b, c, 7)
        SHA1_R0(c, d, e, a, b, 8)
        SHA1_R0(b, c, d, e, a, 9)
        SHA1_R0(a, b, c, d, e, 10)
        SHA1_R0(e, a, b, c, d, 11)
        SHA1_R0(d, e, a, b, c, 12)
        SHA1_R0(c, d, e, a, b, 13)
        SHA1_R0(b, c, d, e, a, 14)
        SHA1_R0(a, b, c, d, e, 15)
        SHA1_R1(e, a, b, c, d, 16)
        SHA1_R1(d, e, a, b, c, 17)
        SHA1_R1(c, d, e, a, b, 18)
        SHA1_R1(b, c, d, e, a, 19)
        SHA1_R2(a, b, c, d, e, 20)
        SHA1_R2(e, a, b, c, d, 21)
        SHA1_R2(d, e, a, b, c, 22)
        SHA1_R2(c, d, e, a, b, 23)
        SHA1_R2(b, c, d, e, a, 24)
        SHA1_R2(a, b, c, d, e, 25)
        SHA1_R2(e, a, b, c, d, 26)
        SHA1_R2(d, e, a, b, c, 27)
        SHA1_R2(c, d, e, a, b, 28)
        SHA1_R2(b, c, d, e, a, 29)
        SHA1_R2(a, b, c, d, e, 30)
        SHA1_R2(e, a, b, c, d, 31)
        SHA1_R2(d, e, a, b, c, 32)
        SHA1_R2(c, d, e, a, b, 33)
        SHA1_R2(b, c, d, e, a, 34)
        SHA1_R2(a, b, c, d, e, 35)
        SHA1_R2(e, a, b, c, d, 36)
        SHA1_R2(d, e, a, b, c, 37)
        SHA1_R2(c, d, e, a, b, 38)
        SHA1_R2(b, c, d, e, a, 39)
        SHA1_R3(a, b, c, d, e, 40)
        SHA1_R3(e, a, b, c, d, 41)
        SHA1_R3(d, e, a, b, c, 42)
        SHA1_R3(c, d, e, a, b, 43)
        SHA1_R3(b, c, d, e, a, 44)
        SHA1_R3(a, b, c, d, e, 45)
        SHA1_R3(e, a, b, c, d, 46)
        SHA1_R3(d, e, a, b, c, 47)
        SHA1_R3(c, d, e, a, b, 48)
        SHA1_R3(b, c, d, e, a, 49)
        SHA1_R3(a, b, c, d, e, 50)
        SHA1_R3(e, a, b, c, d, 51)
        SHA1_R3(d, e, a, b, c, 52)
        SHA1_R3(c, d, e, a, b, 53)
        SHA1_R3(b, c, d, e, a, 54)
        SHA1_R3(a, b, c, d, e, 55)
        SHA1_R3(e, a, b, c, d, 56)
        SHA1_R3(d, e, a, b, c, 57)
        SHA1_R3(c, d, e, a, b, 58)
        SHA1_R3(b, c, d, e, a, 59)
        SHA1_R4(a, b, c, d, e, 60)
        SHA1_R4(e, a, b, c, d, 61)
        SHA1_R4(d, e, a, b, c, 62)
        SHA1_R4(c, d, e, a, b, 63)
        SHA1_R4(b, c, d, e, a, 64)
        SHA1_R4(a, b, c, d, e, 65)
        SHA1_R4(e, a, b, c, d, 66)
        SHA1_R4(d, e, a, b, c, 67)
        SHA1_R4(c, d, e, a, b, 68)
        SHA1_R4(b, c, d, e, a, 69)
        SHA1_R4(a, b, c, d, e, 70)
        SHA1_R4(e, a, b, c, d, 71)
        SHA1_R4(d, e, a, b, c, 72)
        SHA1_R4(c, d, e, a, b, 73)
        SHA1_R4(b, c, d, e, a, 74)
        SHA1_R4(a, b, c, d, e, 75)
        SHA1_R4(e, a, b, c, d, 76)
        SHA1_R4(d, e, a, b, c, 77)
        SHA1_R4(c, d, e, a, b, 78)
        SHA1_R4(b, c, d, e, a, 79)
        /* Add the working vars back into digest[] */
        digest[0] += a;
        digest[1] += b;
        digest[2] += c;
        digest[3] += d;
        digest[4] += e;
        /* Count the number of transformations */
        transforms++;
    }
References digest, and transforms.
Referenced by final(), and update().
update() [1/2]
void utils::SHA1::update (const std::string & s)
Definition at line 57 of file sha1.cpp.
{
        std::istringstream is(s);
        update(is);
    }
References update().
Referenced by utils::sha1().
update() [2/2]
void utils::SHA1::update (std::istream & is)
Definition at line 62 of file sha1.cpp.
{
        std::string rest_of_buffer;
        read(is, rest_of_buffer, static_cast<std::size_t>(static_cast<int>(BLOCK_BYTES) - static_cast<int>(buffer.size())));
        buffer += rest_of_buffer;
        while (is) {
            uint32_t block[BLOCK_INTS];
            buffer_to_block(buffer, block);
            transform(block);
            read(is, buffer, BLOCK_BYTES);
        }
    }
References BLOCK_BYTES, BLOCK_INTS, buffer, buffer_to_block(), read(), and transform().
Referenced by update().
Member Data Documentation
BLOCK_BYTES
const unsigned int utils::SHA1::BLOCK_BYTES = BLOCK_INTS * 4 static private
Definition at line 45 of file sha1.h.
Referenced by final(), and update().
BLOCK_INTS
const unsigned int utils::SHA1::BLOCK_INTS = 16 static private
Definition at line 44 of file sha1.h.
Referenced by buffer_to_block(), final(), and update().
buffer
std::string utils::SHA1::buffer private
Definition at line 48 of file sha1.h.
Referenced by final(), reset(), and update().
digest
uint32_t utils::SHA1::digest[DIGEST_INTS] {} private
Definition at line 47 of file sha1.h.
{};
Referenced by final(), reset(), and transform().
DIGEST_INTS
const unsigned int utils::SHA1::DIGEST_INTS = 5 static private
Definition at line 43 of file sha1.h.
Referenced by final().
transforms
uint64_t utils::SHA1::transforms = 0 private
Definition at line 49 of file sha1.h.
Referenced by final(), reset(), and transform().
The documentation for this class was generated from the following files:
utils/sha1.h
utils/sha1.cpp