SNode.C: express::Request Class Reference
express::Request Class Reference
#include <Request.h>
Public Member Functions
Request ()=default
Request (const std::shared_ptr< web::http::server::Request > &request) noexcept
Request (Request &)=delete
Request (Request &&) noexcept=delete
Request & operator= (Request &)=delete
Request & operator= (Request &&) noexcept=delete
const std::string & param (const std::string &id, const std::string &fallBack="")
const std::string & get (const std::string &key, int i=0) const
const std::string & cookie (const std::string &key) const
const std::string & query (const std::string &key) const
Public Member Functions inherited from utils::MultibleAttributeInjector
template<InjectableAttribute Attribute, fixed_string key = "">
constexpr bool setAttribute (const Attribute &attribute, const std::string &subKey="", bool overwrite=false)
template<InjectableAttribute Attribute, fixed_string key = "">
constexpr bool setAttribute (const Attribute &&attribute, const std::string &subKey="", bool overwrite=false)
template<InjectableAttribute Attribute, fixed_string key = "">
constexpr bool delAttribute (const std::string &subKey="")
template<InjectableAttribute Attribute, fixed_string key = "">
constexpr bool hasAttribute (const std::string &subKey="") const
template<InjectableAttribute Attribute, fixed_string key = "">
bool getAttribute (const std::function< void(Attribute &)> &onFound, const std::string &subKey="") const
template<InjectableAttribute Attribute, fixed_string key = "">
void getAttribute (const std::function< void(Attribute &)> &onFound, const std::function< void(const std::string &)> &onNotFound, const std::string &subKey="") const
void reset ()
Public Attributes
std::string originalUrl
std::string path
std::map< std::string, std::string > params
std::string method
std::string url
std::string httpVersion
int httpMajor = 0
int httpMinor = 0
web::http::CiStringMap< std::string > queries
web::http::CiStringMap< std::string > headers
web::http::CiStringMap< std::string > cookies
std::vector< char > body
Private Member Functions
Request & extend ()
Private Attributes
std::shared_ptr< web::http::server::Request > requestBase
std::string nullstr
Friends
class Response
Detailed Description
Definition at line 41 of file Request.h.
Constructor & Destructor Documentation
Request() [1/4]
express::Request::Request () default
Request() [2/4]
express::Request::Request (const std::shared_ptr< web::http::server::Request > & request) explicit noexcept
Definition at line 34 of file Request.cpp.
        : requestBase(request)
        , method(request->method)
        , url(request->url)
        , httpVersion(request->httpVersion)
        , httpMajor(request->httpMajor)
        , httpMinor(request->httpMinor)
        , queries(std::move(request->queries))
        , headers(request->headers) // Do not move headers as they are possibly still needed in the source request
        , cookies(std::move(request->cookies))
        , body(std::move(request->body)) {
        extend();
    }
References extend(), and Request().
Referenced by Request().
Request() [3/4]
express::Request::Request (Request &) explicit delete
Request() [4/4]
express::Request::Request (Request &&) explicit delete noexcept
Member Function Documentation
cookie()
const std::string & express::Request::cookie (const std::string & key) const
Definition at line 67 of file Request.cpp.
{
        const std::map<std::string, std::string>::const_iterator it = cookies.find(key);
        if (it != cookies.end()) {
            return it->second;
        }
        return nullstr;
    }
References nullstr.
extend()
Request & express::Request::extend () private
Definition at line 52 of file Request.cpp.
{
        originalUrl = url;
        url = httputils::url_decode(httputils::str_split_last(originalUrl, '?').first);
        path = httputils::str_split_last(url, '/').first;
        if (path.empty()) {
            path = std::string("/");
        }
        return *this;
    }
References originalUrl, path, and url.
Referenced by Request().
get()
const std::string & express::Request::get (const std::string & key, int i = 0) const
Definition at line 63 of file Request.cpp.
{
        return requestBase->get(key, i);
    }
operator=() [1/2]
Request & express::Request::operator= (Request &&) delete noexcept
operator=() [2/2]
Request & express::Request::operator= (Request &) delete
param()
const std::string & express::Request::param (const std::string & id, const std::string & fallBack = "")
Definition at line 48 of file Request.cpp.
{
        return params.contains(id) ? params[id] : fallBack;
    }
query()
const std::string & express::Request::query (const std::string & key) const
Definition at line 77 of file Request.cpp.
{
        const std::map<std::string, std::string>::const_iterator it = queries.find(key);
        if (it != queries.end()) {
            return it->second;
        }
        return nullstr;
    }
References nullstr.
Friends And Related Symbol Documentation
Response
friend class Response friend
Definition at line 63 of file Request.h.
Member Data Documentation
body
std::vector<char> express::Request::body
Definition at line 81 of file Request.h.
cookies
web::http::CiStringMap<std::string> express::Request::cookies
Definition at line 80 of file Request.h.
headers
web::http::CiStringMap<std::string> express::Request::headers
Definition at line 79 of file Request.h.
httpMajor
int express::Request::httpMajor = 0
Definition at line 75 of file Request.h.
httpMinor
int express::Request::httpMinor = 0
Definition at line 76 of file Request.h.
httpVersion
std::string express::Request::httpVersion
Definition at line 74 of file Request.h.
method
std::string express::Request::method
Definition at line 72 of file Request.h.
nullstr
std::string express::Request::nullstr private
Definition at line 84 of file Request.h.
Referenced by cookie(), and query().
originalUrl
std::string express::Request::originalUrl
Definition at line 54 of file Request.h.
Referenced by extend().
params
std::map<std::string, std::string> express::Request::params
Definition at line 56 of file Request.h.
path
std::string express::Request::path
Definition at line 55 of file Request.h.
Referenced by extend().
queries
web::http::CiStringMap<std::string> express::Request::queries
Definition at line 78 of file Request.h.
requestBase
std::shared_ptr<web::http::server::Request> express::Request::requestBase private
Definition at line 61 of file Request.h.
url
std::string express::Request::url
Definition at line 73 of file Request.h.
Referenced by extend().
The documentation for this class was generated from the following files:
express/Request.h
express/Request.cpp