SNode.C: iot::mqtt::OnDataEvent Class Reference
iot::mqtt::OnDataEvent Class Reference
#include <SubProtocol.h>
Public Member Functions
OnDataEvent (const std::function< void(const utils::Timeval &currentTime)> &event)
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Private Member Functions
void onEvent (const utils::Timeval &currentTime) override
Private Attributes
std::function< void(const utils::Timeval &currentTime)> event
Detailed Description
Definition at line 49 of file SubProtocol.h.
Constructor & Destructor Documentation
OnDataEvent()
iot::mqtt::OnDataEvent::OnDataEvent (const std::function< void(const utils::Timeval &currentTime)> & event) explicit
Definition at line 38 of file SubProtocol.hpp.
        : core::EventReceiver("WS-OnData")
        , event(event) {
    }
References event, and core::EventReceiver::EventReceiver().
Member Function Documentation
destruct()
void core::EventReceiver::destruct () virtual inherited
Reimplemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, and database::mariadb::MariaDBCommandStartEvent.
Definition at line 31 of file EventReceiver.cpp.
{
        delete this;
    }
Referenced by core::EventMultiplexer::EventQueue::clear().
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 43 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
onEvent()
void iot::mqtt::OnDataEvent::onEvent (const utils::Timeval & currentTime) override private virtual
Implements core::EventReceiver.
Definition at line 43 of file SubProtocol.hpp.
{
        event(currentTime);
    }
References event.
relax()
void core::EventReceiver::relax () inherited
Definition at line 39 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
span()
void core::EventReceiver::span () inherited
Definition at line 35 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::FileReader(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
Member Data Documentation
event
std::function<void(const utils::Timeval& currentTime)> iot::mqtt::OnDataEvent::event private
Definition at line 56 of file SubProtocol.h.
Referenced by OnDataEvent(), and onEvent().
The documentation for this class was generated from the following files:
iot/mqtt/SubProtocol.h
iot/mqtt/SubProtocol.hpp