SNode.C: core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT > Class Template Reference
core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT > Class Template Reference
#include <SocketConnection.h>
Public Member Functions
SocketConnectionT ()=delete
int getFd () const
void setTimeout (const utils::Timeval &timeout) final
const SocketAddress & getLocalAddress () const final
const SocketAddress & getRemoteAddress () const final
std::size_t readFromPeer (char *junk, std::size_t junkLen) final
void sendToPeer (const char *junk, std::size_t junkLen) final
bool streamToPeer (core::pipe::Source *source) final
void streamEof () final
void shutdownRead () final
void shutdownWrite (bool forceClose) final
void close () final
virtual void sendToPeer (const char *junk, std::size_t junkLen)=0
void sendToPeer (const std::string &data)
void switchSocketContext (SocketContext *newSocketContext)
void sentToPeer (const std::vector< uint8_t > &data)
void sentToPeer (const std::vector< char > &data)
const std::string & getInstanceName () const
const std::string & getConfiguredServer () const
Protected Types
using Super = core::socket::stream::SocketConnection
using PhysicalSocket = PhysicalSocketT
using SocketReader = SocketReaderT
using SocketWriter = SocketWriterT
using SocketAddress = typename PhysicalSocket::SocketAddress
Protected Member Functions
SocketConnectionT (const std::string &instanceName, PhysicalSocket &&physicalSocket, const std::function< void()> &onDisconnect, const std::string &configuredServer, const SocketAddress &localAddress, const SocketAddress &remoteAddress, const utils::Timeval &readTimeout, const utils::Timeval &writeTimeout, std::size_t readBlockSize, std::size_t writeBlockSize, const utils::Timeval &terminateTimeout)
~SocketConnectionT () override
void doWriteShutdown (const std::function< void()> &onShutdown) override
void setSocketContext (SocketContext *socketContext)
void connectSocketContext (const std::shared_ptr< core::socket::stream::SocketContextFactory > &socketContextFactory)
void disconnectCurrentSocketContext ()
Protected Attributes
core::socket::stream::SocketContext * socketContext = nullptr
core::socket::stream::SocketContext * newSocketContext = nullptr
std::string instanceName
std::string configuredServer
Private Member Functions
void onReceivedFromPeer (std::size_t available) final
void onWriteError (int errnum)
void onReadError (int errnum)
bool onSignal (int signum) final
void readTimeout () final
void writeTimeout () final
void unobservedEvent () final
Private Attributes
PhysicalSocket physicalSocket
std::function< void()> onDisconnect
SocketAddress localAddress {}
SocketAddress remoteAddress {}
Detailed Description
template<typename PhysicalSocketT, typename SocketReaderT, typename SocketWriterT>
class core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >
Definition at line 101 of file SocketConnection.h.
Member Typedef Documentation
PhysicalSocket
template<typename PhysicalSocketT , typename SocketReaderT , typename SocketWriterT > using core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::PhysicalSocket = PhysicalSocketT protected
Definition at line 108 of file SocketConnection.h.
SocketAddress
template<typename PhysicalSocketT , typename SocketReaderT , typename SocketWriterT > using core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::SocketAddress = typename PhysicalSocket::SocketAddress protected
Definition at line 111 of file SocketConnection.h.
SocketReader
template<typename PhysicalSocketT , typename SocketReaderT , typename SocketWriterT > using core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::SocketReader = SocketReaderT protected
Definition at line 109 of file SocketConnection.h.
SocketWriter
template<typename PhysicalSocketT , typename SocketReaderT , typename SocketWriterT > using core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::SocketWriter = SocketWriterT protected
Definition at line 110 of file SocketConnection.h.
Super
template<typename PhysicalSocketT , typename SocketReaderT , typename SocketWriterT > using core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::Super = core::socket::stream::SocketConnection protected
Definition at line 106 of file SocketConnection.h.
Constructor & Destructor Documentation
SocketConnectionT() [1/2]
template<typename PhysicalSocketT , typename SocketReaderT , typename SocketWriterT > core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::SocketConnectionT () delete
SocketConnectionT() [2/2]
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::SocketConnectionT (const std::string & instanceName, PhysicalSocket && physicalSocket, const std::function< void()> & onDisconnect, const std::string & configuredServer, const SocketAddress & localAddress, const SocketAddress & remoteAddress, const utils::Timeval & readTimeout, const utils::Timeval & writeTimeout, std::size_t readBlockSize, std::size_t writeBlockSize, const utils::Timeval & terminateTimeout) protected
Definition at line 37 of file SocketConnection.hpp.
        : SocketConnection(instanceName, configuredServer)
        , SocketReader(
              instanceName,
              [this](int errnum) -> void {
                  const utils::PreserveErrno pe(errnum);
                  if (errno == 0) {
                      LOG(TRACE) << this->instanceName << ": EOF received";
                  } else {
                      PLOG(TRACE) << this->instanceName << ": ReadError";
                  }
                  onReadError(errnum);
              },
              readTimeout,
              readBlockSize,
              terminateTimeout)
        , SocketWriter(
              instanceName,
              [this](int errnum) -> void {
                  const utils::PreserveErrno pe(errnum);
                  PLOG(TRACE) << this->instanceName << ": OnWriteError";
                  onWriteError(errnum);
              },
              writeTimeout,
              writeBlockSize,
              terminateTimeout)
        , physicalSocket(std::move(physicalSocket))
        , onDisconnect(onDisconnect)     // cppcheck-suppress selfInitialization
        , localAddress(localAddress)     // cppcheck-suppress selfInitialization
        , remoteAddress(remoteAddress) { // cppcheck-suppress selfInitialization
        if (!SocketReader::enable(this->physicalSocket.getFd())) {
            delete this;
        } else if (!SocketWriter::enable(this->physicalSocket.getFd())) {
            delete this;
        } else {
            SocketWriter::suspend();
        }
    }
References core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReadError(), and utils::PreserveErrno::PreserveErrno().
~SocketConnectionT()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::~SocketConnectionT () override protected
Definition at line 91 of file SocketConnection.hpp.
{
    }
Member Function Documentation
close()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::close () final virtual
Implements core::socket::stream::SocketConnection.
Definition at line 169 of file SocketConnection.hpp.
{
        if (SocketWriter::isEnabled()) {
            SocketWriter::disable();
        }
        if (SocketReader::isEnabled()) {
            SocketReader::disable();
        }
    }
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReceivedFromPeer(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::readTimeout(), and core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::writeTimeout().
connectSocketContext()
void core::socket::stream::SocketConnection::connectSocketContext (const std::shared_ptr< core::socket::stream::SocketContextFactory > & socketContextFactory) protected inherited
Definition at line 74 of file SocketConnection.cpp.
{
        SocketContext* socketContext = socketContextFactory->create(this);
        if (socketContext != nullptr) {
            setSocketContext(socketContext);
        } else {
            LOG(TRACE) << "SocketConnection: Failed creating new SocketContext";
            close();
        }
    }
References core::socket::stream::SocketConnection::close(), core::socket::stream::SocketContextFactory::create(), and core::socket::stream::SocketConnection::setSocketContext().
disconnectCurrentSocketContext()
void core::socket::stream::SocketConnection::disconnectCurrentSocketContext () protected inherited
Definition at line 85 of file SocketConnection.cpp.
{
        if (socketContext != nullptr) {
            socketContext->onDisconnected();
            delete socketContext;
        }
    }
References core::socket::stream::SocketContext::onDisconnected(), and core::socket::stream::SocketConnection::socketContext.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReceivedFromPeer(), and core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::unobservedEvent().
doWriteShutdown()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::doWriteShutdown (const std::function< void()> & onShutdown) override protected
Definition at line 179 of file SocketConnection.hpp.
{
        errno = 0;
        LOG(TRACE) << instanceName << ": Do syscall shutdown (WR)";
        if (physicalSocket.shutdown(PhysicalSocket::SHUT::WR) != 0) {
            PLOG(TRACE) << instanceName << ": SocketWriter::doWriteShutdown";
        }
        onShutdown();
    }
References core::socket::stream::SocketConnection::instanceName, and core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::physicalSocket.
getConfiguredServer()
const std::string & core::socket::stream::SocketConnection::getConfiguredServer () const inherited
Definition at line 70 of file SocketConnection.cpp.
{
        return configuredServer;
    }
References core::socket::stream::SocketConnection::configuredServer.
Referenced by web::http::client::SocketContext::onConnected(), and web::http::client::SocketContext::SocketContext().
getFd()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > int core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::getFd () const
Definition at line 101 of file SocketConnection.hpp.
{
        return physicalSocket.getFd();
    }
References core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::physicalSocket.
getInstanceName()
const std::string & core::socket::stream::SocketConnection::getInstanceName () const inherited
Definition at line 66 of file SocketConnection.cpp.
{
        return instanceName;
    }
References core::socket::stream::SocketConnection::instanceName.
Referenced by web::http::client::SocketContext::dispatchNextRequest(), web::http::client::SocketContext::onConnected(), web::http::server::SocketContext::onConnected(), web::http::client::SocketContext::onDisconnected(), web::http::server::SocketContext::onDisconnected(), web::http::client::SocketContext::onSignal(), web::http::server::SocketContext::onSignal(), web::http::client::SocketContext::requestCompleted(), web::http::server::SocketContext::requestCompleted(), web::http::server::SocketContext::requestParsed(), web::http::server::SocketContext::requestParseError(), web::http::client::SocketContext::requestPrepared(), web::http::client::SocketContext::requestSendError(), web::http::client::SocketContext::requestSent(), web::http::server::SocketContext::requestStarted(), web::http::server::SocketContext::responseCompleted(), web::http::client::SocketContext::responseError(), web::http::client::SocketContext::responseParsed(), web::http::client::SocketContext::responseStarted(), web::http::server::SocketContext::responseStarted(), and express::middleware::VerboseRequest::VerboseRequest().
getLocalAddress()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > const SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::SocketAddress & core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::getLocalAddress () const final virtual
Implements core::socket::stream::SocketConnection.
Definition at line 107 of file SocketConnection.hpp.
{
        return localAddress;
    }
References core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::localAddress.
getRemoteAddress()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > const SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::SocketAddress & core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::getRemoteAddress () const final virtual
Implements core::socket::stream::SocketConnection.
Definition at line 113 of file SocketConnection.hpp.
{
        return remoteAddress;
    }
References core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::remoteAddress.
onReadError()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::onReadError (int errnum) private
Definition at line 214 of file SocketConnection.hpp.
{
        socketContext->onReadError(errnum);
    }
References core::socket::stream::SocketContext::onReadError(), and core::socket::stream::SocketConnection::socketContext.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::SocketConnectionT().
onReceivedFromPeer()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::onReceivedFromPeer (std::size_t available) final private
Definition at line 192 of file SocketConnection.hpp.
{
        std::size_t consumed = socketContext->onReceivedFromPeer();
        if (newSocketContext != nullptr) { // Perform a pending SocketContextSwitch
            disconnectCurrentSocketContext();
            setSocketContext(newSocketContext);
            newSocketContext = nullptr;
        }
        if (available != 0 && consumed == 0) {
            close();
            delete newSocketContext; // delete of nullptr is valid since C++14!
        }
    }
References core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::close(), core::socket::stream::SocketConnection::disconnectCurrentSocketContext(), core::socket::stream::SocketConnection::newSocketContext, core::socket::SocketContext::onReceivedFromPeer(), core::socket::stream::SocketConnection::setSocketContext(), and core::socket::stream::SocketConnection::socketContext.
onSignal()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > bool core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::onSignal (int signum) final private
Definition at line 219 of file SocketConnection.hpp.
{
        switch (signum) {
            case SIGINT:
                [[fallthrough]];
            case SIGTERM:
                [[fallthrough]];
            case SIGABRT:
                [[fallthrough]];
            case SIGHUP:
                LOG(TRACE) << instanceName << ": Shutting down due to signal '" << strsignal(signum) << "' (SIG"
                           << utils::system::sigabbrev_np(signum) << " = " << signum << ")";
                break;
            case SIGALRM:
                break;
        }
        return socketContext != nullptr ? socketContext->onSignal(signum) : true;
    }
References core::socket::stream::SocketConnection::instanceName, core::socket::SocketContext::onSignal(), utils::system::sigabbrev_np(), and core::socket::stream::SocketConnection::socketContext.
onWriteError()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::onWriteError (int errnum) private
Definition at line 209 of file SocketConnection.hpp.
{
        socketContext->onWriteError(errnum);
    }
References core::socket::stream::SocketContext::onWriteError(), and core::socket::stream::SocketConnection::socketContext.
readFromPeer()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > std::size_t core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::readFromPeer (char * junk, std::size_t junkLen) final virtual
Implements core::socket::stream::SocketConnection.
Definition at line 118 of file SocketConnection.hpp.
{
        std::size_t ret = 0;
        if (newSocketContext == nullptr) {
            ret = SocketReader::readFromPeer(junk, junkLen);
        } else {
            LOG(TRACE) << instanceName << ": ReadFromPeer: OldSocketContext != nullptr: SocketContextSwitch still in progress";
        }
        return ret;
    }
References core::socket::stream::SocketConnection::instanceName, and core::socket::stream::SocketConnection::newSocketContext.
readTimeout()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::readTimeout () final private
Definition at line 239 of file SocketConnection.hpp.
{
        close();
    }
References core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::close().
sendToPeer() [1/3]
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::sendToPeer (const char * junk, std::size_t junkLen) final virtual
Implements core::socket::stream::SocketConnection.
Definition at line 131 of file SocketConnection.hpp.
{
        SocketWriter::sendToPeer(junk, junkLen);
    }
sendToPeer() [2/3]
template<typename PhysicalSocketT , typename SocketReaderT , typename SocketWriterT > virtual void core::socket::stream::SocketConnection::sendToPeer (const char * junk, std::size_t junkLen) virtual
Implements core::socket::stream::SocketConnection.
sendToPeer() [3/3]
template<typename PhysicalSocketT , typename SocketReaderT , typename SocketWriterT > void core::socket::stream::SocketConnection::sendToPeer (const std::string & data)
Definition at line 66 of file SocketConnection.cpp.
{
        sendToPeer(data.data(), data.size());
    }
sentToPeer() [1/2]
void core::socket::stream::SocketConnection::sentToPeer (const std::vector< char > & data) inherited
Definition at line 62 of file SocketConnection.cpp.
{
        sendToPeer(data.data(), data.size());
    }
References core::socket::stream::SocketConnection::sendToPeer().
sentToPeer() [2/2]
void core::socket::stream::SocketConnection::sentToPeer (const std::vector< uint8_t > & data) inherited
Definition at line 58 of file SocketConnection.cpp.
{
        sendToPeer(reinterpret_cast<const char*>(data.data()), data.size());
    }
References core::socket::stream::SocketConnection::sendToPeer().
setSocketContext()
void core::socket::stream::SocketConnection::setSocketContext (SocketContext * socketContext) protected inherited
Definition at line 45 of file SocketConnection.cpp.
{
        if (socketContext != nullptr) { // Perform a pending SocketContextSwitch
            this->socketContext = socketContext;
            socketContext->onConnected();
        } else {
            LOG(TRACE) << "SocketConnection: Set socket context unsuccessful: new socket context not created";
        }
    }
References core::socket::stream::SocketContext::onConnected(), and core::socket::stream::SocketConnection::socketContext.
Referenced by core::socket::stream::SocketConnection::connectSocketContext(), and core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReceivedFromPeer().
setTimeout()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::setTimeout (const utils::Timeval & timeout) final virtual
Implements core::socket::stream::SocketConnection.
Definition at line 95 of file SocketConnection.hpp.
{
        SocketReader::setTimeout(timeout);
        SocketWriter::setTimeout(timeout);
    }
shutdownRead()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::shutdownRead () final virtual
Implements core::socket::stream::SocketConnection.
Definition at line 146 of file SocketConnection.hpp.
{
        LOG(TRACE) << instanceName << ": Do syscall shutdown (RD)";
        physicalSocket.shutdown(PhysicalSocket::SHUT::RD);
    }
References core::socket::stream::SocketConnection::instanceName, and core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::physicalSocket.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::shutdownWrite().
shutdownWrite()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::shutdownWrite (bool forceClose) final virtual
Implements core::socket::stream::SocketConnection.
Definition at line 153 of file SocketConnection.hpp.
{
        if (!SocketWriter::shutdownInProgress) {
            LOG(TRACE) << instanceName << ": Initiating shutdown process";
            SocketWriter::shutdownWrite([forceClose, this]() -> void {
                if (forceClose && SocketReader::isEnabled()) {
                    shutdownRead();
                }
                if (SocketWriter::isEnabled()) {
                    SocketWriter::disable();
                }
            });
        }
    }
References core::socket::stream::SocketConnection::instanceName, and core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::shutdownRead().
streamEof()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::streamEof () final virtual
Implements core::socket::stream::SocketConnection.
Definition at line 141 of file SocketConnection.hpp.
{
        SocketWriter::streamEof();
    }
streamToPeer()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > bool core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::streamToPeer (core::pipe::Source * source) final virtual
Implements core::socket::stream::SocketConnection.
Definition at line 136 of file SocketConnection.hpp.
{
        return SocketWriter::streamToPeer(source);
    }
switchSocketContext()
void core::socket::stream::SocketConnection::switchSocketContext (SocketContext * newSocketContext) inherited
Definition at line 41 of file SocketConnection.cpp.
{
        this->newSocketContext = newSocketContext;
    }
References core::socket::stream::SocketConnection::newSocketContext.
Referenced by core::socket::stream::SocketContext::switchSocketContext().
unobservedEvent()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::unobservedEvent () final private
Definition at line 249 of file SocketConnection.hpp.
{
        disconnectCurrentSocketContext();
        onDisconnect();
        delete this;
    }
References core::socket::stream::SocketConnection::disconnectCurrentSocketContext(), and core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onDisconnect.
writeTimeout()
template<typename PhysicalSocket , typename SocketReader , typename SocketWriter > void core::socket::stream::SocketConnectionT< PhysicalSocket, SocketReader, SocketWriter >::writeTimeout () final private
Definition at line 244 of file SocketConnection.hpp.
{
        close();
    }
References core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::close().
Member Data Documentation
configuredServer
std::string core::socket::stream::SocketConnection::configuredServer protected inherited
Definition at line 97 of file SocketConnection.h.
Referenced by core::socket::stream::SocketConnection::getConfiguredServer(), and core::socket::stream::SocketConnection::SocketConnection().
instanceName
std::string core::socket::stream::SocketConnection::instanceName protected inherited
Definition at line 96 of file SocketConnection.h.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::doWriteShutdown(), core::socket::stream::SocketConnection::getInstanceName(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onSignal(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::readFromPeer(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::shutdownRead(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::shutdownWrite(), and core::socket::stream::SocketConnection::SocketConnection().
localAddress
template<typename PhysicalSocketT , typename SocketReaderT , typename SocketWriterT > SocketAddress core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::localAddress {} private
Definition at line 171 of file SocketConnection.h.
{};
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::getLocalAddress().
newSocketContext
core::socket::stream::SocketContext* core::socket::stream::SocketConnection::newSocketContext = nullptr protected inherited
Definition at line 94 of file SocketConnection.h.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReceivedFromPeer(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::readFromPeer(), and core::socket::stream::SocketConnection::switchSocketContext().
onDisconnect
template<typename PhysicalSocketT , typename SocketReaderT , typename SocketWriterT > std::function<void()> core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onDisconnect private
Definition at line 169 of file SocketConnection.h.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::unobservedEvent().
physicalSocket
template<typename PhysicalSocketT , typename SocketReaderT , typename SocketWriterT > PhysicalSocket core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::physicalSocket private
Definition at line 156 of file SocketConnection.h.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::doWriteShutdown(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::getFd(), and core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::shutdownRead().
remoteAddress
template<typename PhysicalSocketT , typename SocketReaderT , typename SocketWriterT > SocketAddress core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::remoteAddress {} private
Definition at line 172 of file SocketConnection.h.
{};
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::getRemoteAddress().
socketContext
core::socket::stream::SocketContext* core::socket::stream::SocketConnection::socketContext = nullptr protected inherited
Definition at line 93 of file SocketConnection.h.
Referenced by core::socket::stream::SocketConnection::disconnectCurrentSocketContext(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReadError(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReceivedFromPeer(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onSignal(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onWriteError(), and core::socket::stream::SocketConnection::setSocketContext().
The documentation for this class was generated from the following files:
core/socket/stream/SocketConnection.h
core/socket/stream/SocketConnection.hpp