SNode.C: iot::mqtt::packets::Unsuback Class Reference
iot::mqtt::packets::Unsuback Class Reference
#include <Unsuback.h>
Public Member Functions
Unsuback ()
Unsuback (uint16_t packetIdentifier)
uint16_t getPacketIdentifier () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type, const std::string &name)
ControlPacket (const ControlPacket &)=default
ControlPacket (ControlPacket &&)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
ControlPacket & operator= (ControlPacket &&)=default
std::vector< char > serialize () const
const std::string & getName () const
Protected Attributes
iot::mqtt::types::UInt16 packetIdentifier
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t flags = 0
Private Member Functions
std::vector< char > serializeVP () const override
Additional Inherited Members
Protected Member Functions inherited from iot::mqtt::ControlPacket
uint8_t getType () const
uint8_t getFlags () const
Detailed Description
Definition at line 56 of file Unsuback.h.
Constructor & Destructor Documentation
Unsuback() [1/2]
iot::mqtt::packets::Unsuback::Unsuback ()
Definition at line 53 of file Unsuback.cpp.
        : iot::mqtt::ControlPacket(MQTT_UNSUBACK, "UNSUBACK") {
    }
References iot::mqtt::ControlPacket::ControlPacket().
Referenced by Unsuback().
Unsuback() [2/2]
iot::mqtt::packets::Unsuback::Unsuback (uint16_t packetIdentifier) explicit
Definition at line 57 of file Unsuback.cpp.
        : Unsuback() {
        this->packetIdentifier = packetIdentifier;
    }
References iot::mqtt::types::UInt16::operator=(), packetIdentifier, and Unsuback().
Referenced by iot::mqtt::server::Mqtt::sendUnsuback().
Member Function Documentation
getPacketIdentifier()
uint16_t iot::mqtt::packets::Unsuback::getPacketIdentifier () const
Definition at line 66 of file Unsuback.cpp.
{
        return packetIdentifier;
    }
References packetIdentifier.
Referenced by iot::mqtt::client::Mqtt::_onUnsuback().
serializeVP()
std::vector< char > iot::mqtt::packets::Unsuback::serializeVP () const override private virtual
Implements iot::mqtt::ControlPacket.
Definition at line 62 of file Unsuback.cpp.
{
        return std::vector<char>(packetIdentifier.serialize());
    }
References packetIdentifier, and iot::mqtt::types::TypeBase< ValueTypeT >::serialize().
Member Data Documentation
packetIdentifier
iot::mqtt::types::UInt16 iot::mqtt::packets::Unsuback::packetIdentifier protected
Definition at line 68 of file Unsuback.h.
Referenced by iot::mqtt::client::packets::Unsuback::deserializeVP(), getPacketIdentifier(), serializeVP(), and Unsuback().
The documentation for this class was generated from the following files:
iot/mqtt/packets/Unsuback.h
iot/mqtt/packets/Unsuback.cpp