snode.c: iot::mqtt::client::packets::Pubcomp Class Reference
iot::mqtt::client::packets::Pubcomp Class Reference
#include <Pubcomp.h>
Public Member Functions
Pubcomp (uint32_t remainingLength, uint8_t flags)
Public Member Functions inherited from iot::mqtt::packets::Pubcomp
Pubcomp ()
Pubcomp (const uint16_t packetIdentifier)
uint16_t getPacketIdentifier () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type)
ControlPacket (const ControlPacket &)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
std::vector< char > serialize () const
uint8_t getType () const
uint8_t getFlags () const
Public Member Functions inherited from iot::mqtt::client::ControlPacketDeserializer
~ControlPacketDeserializer () override
Public Member Functions inherited from iot::mqtt::ControlPacketDeserializer
ControlPacketDeserializer ()=default
ControlPacketDeserializer (uint32_t remainingLength, uint8_t flags, uint8_t mustFlags)
ControlPacketDeserializer & operator= (const ControlPacketDeserializer &)=default
std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
uint32_t getRemainingLength () const
bool isComplete () const
bool isError () const
std::size_t getConsumed () const
Private Member Functions
std::size_t deserializeVP (iot::mqtt::MqttContext *mqttContext) override
void deliverPacket (iot::mqtt::client::Mqtt *mqtt) override
Additional Inherited Members
Protected Attributes inherited from iot::mqtt::packets::Pubcomp
iot::mqtt::types::UInt16 packetIdentifier
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t type = 0
uint8_t flags = 0
Protected Attributes inherited from iot::mqtt::ControlPacketDeserializer
bool complete = false
bool error = false
uint32_t remainingLength = 0
std::size_t consumed = 0
Detailed Description
Definition at line 38 of file Pubcomp.h.
Constructor & Destructor Documentation
Pubcomp()
iot::mqtt::client::packets::Pubcomp::Pubcomp (uint32_t remainingLength, uint8_t flags)
Definition at line 29 of file Pubcomp.cpp.
        : iot::mqtt::client::ControlPacketDeserializer(remainingLength, flags, MQTT_PUBCOMP_FLAGS) {
        this->flags = flags;
    }
References iot::mqtt::ControlPacket::flags.
Member Function Documentation
deliverPacket()
void iot::mqtt::client::packets::Pubcomp::deliverPacket (iot::mqtt::client::Mqtt * mqtt) override private virtual
Implements iot::mqtt::client::ControlPacketDeserializer.
Definition at line 44 of file Pubcomp.cpp.
{
        mqtt->_onPubcomp(*this);
    }
References iot::mqtt::Mqtt::_onPubcomp().
deserializeVP()
std::size_t iot::mqtt::client::packets::Pubcomp::deserializeVP (iot::mqtt::MqttContext * mqttContext) override private virtual
Implements iot::mqtt::ControlPacketDeserializer.
Definition at line 34 of file Pubcomp.cpp.
{
        // V-Header
        std::size_t consumed = packetIdentifier.deserialize(mqttContext);
        complete = packetIdentifier.isComplete();
        // no Payload
        return consumed;
    }
References iot::mqtt::ControlPacketDeserializer::complete, iot::mqtt::ControlPacketDeserializer::consumed, iot::mqtt::types::TypeBase< ValueTypeT >::deserialize(), iot::mqtt::types::TypeBase< ValueTypeT >::isComplete(), and iot::mqtt::packets::Pubcomp::packetIdentifier.
The documentation for this class was generated from the following files:
iot/mqtt/client/packets/Pubcomp.h
iot/mqtt/client/packets/Pubcomp.cpp