SNode.C: iot::mqtt::packets::Subscribe Class Reference
iot::mqtt::packets::Subscribe Class Reference
#include <Subscribe.h>
Public Member Functions
Subscribe ()
Subscribe (uint16_t packetIdentifier, std::list< iot::mqtt::Topic > &topics)
uint16_t getPacketIdentifier () const
const std::list< iot::mqtt::Topic > & getTopics () const
std::vector< char > serialize () const
const std::string & getName () const
uint8_t getType () const
uint8_t getFlags () const
Protected Attributes
iot::mqtt::types::UInt16 packetIdentifier
std::list< iot::mqtt::Topic > topics
uint8_t flags = 0
Private Member Functions
std::vector< char > serializeVP () const override
Private Attributes
std::string name
uint8_t type = 0
Detailed Description
Definition at line 39 of file Subscribe.h.
Constructor & Destructor Documentation
Subscribe() [1/2]
iot::mqtt::packets::Subscribe::Subscribe ()
Definition at line 31 of file Subscribe.cpp.
        : iot::mqtt::ControlPacket(MQTT_SUBSCRIBE, "SUBSCRIBE") {
    }
References iot::mqtt::ControlPacket::ControlPacket().
Referenced by Subscribe().
Subscribe() [2/2]
iot::mqtt::packets::Subscribe::Subscribe (uint16_t packetIdentifier, std::list< iot::mqtt::Topic > & topics)
Definition at line 35 of file Subscribe.cpp.
        : Subscribe() {
        this->packetIdentifier = packetIdentifier;
        this->topics = topics;
    }
References iot::mqtt::types::UInt16::operator=(), packetIdentifier, Subscribe(), and topics.
Referenced by iot::mqtt::client::Mqtt::sendSubscribe().
Member Function Documentation
getFlags()
uint8_t iot::mqtt::ControlPacket::getFlags () const inherited
Definition at line 119 of file ControlPacket.cpp.
{
        return flags;
    }
References iot::mqtt::ControlPacket::flags.
getName()
const std::string & iot::mqtt::ControlPacket::getName () const inherited
Definition at line 100 of file ControlPacket.cpp.
{
        return name;
    }
References iot::mqtt::ControlPacket::name.
Referenced by iot::mqtt::Mqtt::printVP(), and iot::mqtt::Mqtt::send().
getPacketIdentifier()
uint16_t iot::mqtt::packets::Subscribe::getPacketIdentifier () const
Definition at line 57 of file Subscribe.cpp.
{
        return packetIdentifier;
    }
References packetIdentifier.
Referenced by iot::mqtt::server::Mqtt::_onSubscribe().
getTopics()
const std::list< Topic > & iot::mqtt::packets::Subscribe::getTopics () const
Definition at line 61 of file Subscribe.cpp.
{
        return topics;
    }
References topics.
Referenced by iot::mqtt::server::Mqtt::_onSubscribe().
getType()
uint8_t iot::mqtt::ControlPacket::getType () const inherited
Definition at line 115 of file ControlPacket.cpp.
{
        return type;
    }
References iot::mqtt::ControlPacket::type.
serialize()
std::vector< char > iot::mqtt::ControlPacket::serialize () const inherited
Definition at line 104 of file ControlPacket.cpp.
{
        std::vector<char> variablHeaderPayload = serializeVP();
        const iot::mqtt::FixedHeader fixedHeader(type, flags, static_cast<uint32_t>(variablHeaderPayload.size()));
        std::vector<char> packet = fixedHeader.serialize();
        packet.insert(packet.end(), variablHeaderPayload.begin(), variablHeaderPayload.end());
        return packet;
    }
References iot::mqtt::FixedHeader::FixedHeader(), iot::mqtt::ControlPacket::flags, iot::mqtt::FixedHeader::serialize(), iot::mqtt::ControlPacket::serializeVP(), and iot::mqtt::ControlPacket::type.
Referenced by iot::mqtt::Mqtt::send().
serializeVP()
std::vector< char > iot::mqtt::packets::Subscribe::serializeVP () const override private virtual
Implements iot::mqtt::ControlPacket.
Definition at line 41 of file Subscribe.cpp.
{
        std::vector<char> packet(packetIdentifier.serialize());
        for (const Topic& topic : topics) {
            iot::mqtt::types::String topicString;
            topicString = topic.getName();
            std::vector<char> tmpPacket = topicString.serialize();
            packet.insert(packet.end(), tmpPacket.begin(), tmpPacket.end());
            packet.push_back(static_cast<char>(topic.getQoS()));
        }
        return packet;
    }
References iot::mqtt::Topic::getName(), iot::mqtt::Topic::getQoS(), iot::mqtt::types::String::operator=(), packetIdentifier, iot::mqtt::types::TypeBase< ValueTypeT >::serialize(), iot::mqtt::types::String::serialize(), and topics.
Member Data Documentation
flags
uint8_t iot::mqtt::ControlPacket::flags = 0 protected inherited
Definition at line 92 of file ControlPacket.h.
Referenced by iot::mqtt::client::packets::Connack::Connack(), iot::mqtt::server::packets::Connect::Connect(), iot::mqtt::ControlPacket::ControlPacket(), iot::mqtt::server::packets::Disconnect::Disconnect(), iot::mqtt::ControlPacket::getFlags(), iot::mqtt::server::packets::Pingreq::Pingreq(), iot::mqtt::client::packets::Pingresp::Pingresp(), iot::mqtt::client::packets::Puback::Puback(), iot::mqtt::server::packets::Puback::Puback(), iot::mqtt::client::packets::Pubcomp::Pubcomp(), iot::mqtt::server::packets::Pubcomp::Pubcomp(), iot::mqtt::packets::Publish::Publish(), iot::mqtt::client::packets::Publish::Publish(), iot::mqtt::server::packets::Publish::Publish(), iot::mqtt::client::packets::Pubrec::Pubrec(), iot::mqtt::server::packets::Pubrec::Pubrec(), iot::mqtt::client::packets::Pubrel::Pubrel(), iot::mqtt::server::packets::Pubrel::Pubrel(), iot::mqtt::ControlPacket::serialize(), iot::mqtt::client::packets::Suback::Suback(), iot::mqtt::server::packets::Subscribe::Subscribe(), iot::mqtt::client::packets::Unsuback::Unsuback(), and iot::mqtt::server::packets::Unsubscribe::Unsubscribe().
name
std::string iot::mqtt::ControlPacket::name private inherited
Definition at line 88 of file ControlPacket.h.
Referenced by iot::mqtt::ControlPacket::ControlPacket(), and iot::mqtt::ControlPacket::getName().
packetIdentifier
iot::mqtt::types::UInt16 iot::mqtt::packets::Subscribe::packetIdentifier protected
Definition at line 52 of file Subscribe.h.
Referenced by iot::mqtt::server::packets::Subscribe::deserializeVP(), getPacketIdentifier(), serializeVP(), and Subscribe().
topics
std::list<iot::mqtt::Topic> iot::mqtt::packets::Subscribe::topics protected
Definition at line 54 of file Subscribe.h.
Referenced by iot::mqtt::server::packets::Subscribe::deserializeVP(), getTopics(), serializeVP(), and Subscribe().
type
uint8_t iot::mqtt::ControlPacket::type = 0 private inherited
Definition at line 89 of file ControlPacket.h.
Referenced by iot::mqtt::ControlPacket::ControlPacket(), iot::mqtt::ControlPacket::getType(), and iot::mqtt::ControlPacket::serialize().
The documentation for this class was generated from the following files:
iot/mqtt/packets/Subscribe.h
iot/mqtt/packets/Subscribe.cpp