SNode.C: iot::mqtt::server::broker::RetainTree Class Reference
iot::mqtt::server::broker::RetainTree Class Reference
#include <RetainTree.h>
Classes
class TopicLevel
Public Member Functions
RetainTree (iot::mqtt::server::broker::Broker *broker)
void retain (Message &&message)
void appear (const std::string &clientId, const std::string &topic, uint8_t qoS)
void release (const std::string &topic)
nlohmann::json toJson () const
void fromJson (const nlohmann::json &json)
std::list< std::pair< std::string, std::string > > getRetainTree () const
void clear ()
Private Attributes
TopicLevel head
Detailed Description
Definition at line 65 of file RetainTree.h.
Constructor & Destructor Documentation
RetainTree()
iot::mqtt::server::broker::RetainTree::RetainTree (iot::mqtt::server::broker::Broker * broker) explicit
Definition at line 61 of file RetainTree.cpp.
        : head(broker) {
    }
References head, and iot::mqtt::server::broker::RetainTree::TopicLevel::TopicLevel().
Referenced by iot::mqtt::server::broker::Broker::Broker().
Member Function Documentation
appear()
void iot::mqtt::server::broker::RetainTree::appear (const std::string & clientId, const std::string & topic, uint8_t qoS)
Definition at line 75 of file RetainTree.cpp.
{
        head.appear(clientId, topic, qoS);
    }
References iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), and head.
Referenced by iot::mqtt::server::broker::Broker::appear(), and iot::mqtt::server::broker::Broker::subscribe().
clear()
void iot::mqtt::server::broker::RetainTree::clear ()
Definition at line 97 of file RetainTree.cpp.
{
        head.clear();
    }
References iot::mqtt::server::broker::RetainTree::TopicLevel::clear(), and head.
Referenced by iot::mqtt::server::broker::Broker::Broker().
fromJson()
void iot::mqtt::server::broker::RetainTree::fromJson (const nlohmann::json & json)
Definition at line 83 of file RetainTree.cpp.
{
        if (!json.empty()) {
            head.fromJson(json);
        }
    }
References iot::mqtt::server::broker::RetainTree::TopicLevel::fromJson(), and head.
Referenced by iot::mqtt::server::broker::Broker::Broker().
getRetainTree()
std::list< std::pair< std::string, std::string > > iot::mqtt::server::broker::RetainTree::getRetainTree () const
Definition at line 89 of file RetainTree.cpp.
{
        return head.getRetainTree();
    }
References iot::mqtt::server::broker::RetainTree::TopicLevel::getRetainTree(), and head.
Referenced by iot::mqtt::server::broker::Broker::getRetainTree().
release()
void iot::mqtt::server::broker::RetainTree::release (const std::string & topic)
Definition at line 79 of file RetainTree.cpp.
{
        head.release(topic);
    }
References head, and iot::mqtt::server::broker::RetainTree::TopicLevel::release().
Referenced by iot::mqtt::server::broker::Broker::release().
retain()
void iot::mqtt::server::broker::RetainTree::retain (Message && message)
Definition at line 65 of file RetainTree.cpp.
{
        if (!message.getTopic().empty()) {
            if (!message.getMessage().empty()) {
                head.retain(message, message.getTopic());
            } else {
                head.release(message.getTopic());
            }
        }
    }
References iot::mqtt::server::broker::Message::getMessage(), iot::mqtt::server::broker::Message::getTopic(), head, iot::mqtt::server::broker::RetainTree::TopicLevel::release(), and iot::mqtt::server::broker::RetainTree::TopicLevel::retain().
Referenced by iot::mqtt::server::broker::Broker::publish().
toJson()
nlohmann::json iot::mqtt::server::broker::RetainTree::toJson () const
Definition at line 93 of file RetainTree.cpp.
{
        return head.toJson();
    }
References head, and iot::mqtt::server::broker::RetainTree::TopicLevel::toJson().
Referenced by iot::mqtt::server::broker::Broker::~Broker().
Member Data Documentation
head
TopicLevel iot::mqtt::server::broker::RetainTree::head private
Definition at line 110 of file RetainTree.h.
Referenced by appear(), clear(), fromJson(), getRetainTree(), release(), retain(), RetainTree(), and toJson().
The documentation for this class was generated from the following files:
iot/mqtt/server/broker/RetainTree.h
iot/mqtt/server/broker/RetainTree.cpp