SNode.C: net::rc::config::ConfigAddress< ConfigAddressTypeT > Class Template Reference
net::rc::config::ConfigAddress< ConfigAddressTypeT > Class Template Reference
#include <ConfigAddress.h>
Public Member Functions
ConfigAddress & setSocketAddress (const SocketAddress &socketAddress)
ConfigAddress & setBtAddress (const std::string &btAddress)
std::string getBtAddress () const
ConfigAddress & setChannel (uint8_t channel)
uint8_t getChannel () const
void configurable (bool configurable=true) final
Public Member Functions inherited from net::config::ConfigSection
template<typename T>
ConfigSection (ConfigInstance *instance, T *sectionPtr, const std::string &group="Sections")
~ConfigSection () override
ConfigSection (const ConfigSection &)=delete
ConfigSection (ConfigSection &&)=delete
ConfigSection & operator= (const ConfigSection &)=delete
Public Member Functions inherited from utils::SubCommand
SubCommand (const SubCommand &)=delete
SubCommand (SubCommand &&)=delete
SubCommand & operator= (const SubCommand &)=delete
SubCommand & operator= (SubCommand &&)=delete
virtual ~SubCommand ()
std::string getName () const
std::string version () const
void parse (int argc, char *argv[])
CLI::Option * setConfig (const std::string &defaultConfigFile) const
CLI::Option * setLogFile (const std::string &defaultLogFile) const
CLI::Option * setVersionFlag (const std::string &version) const
bool hasParent () const
SubCommand * getParent ()
SubCommand * allowExtras (bool allow=true)
SubCommand * required (bool required=true, bool force=true)
SubCommand * required (SubCommand *subCommand, bool required=true)
SubCommand * required (CLI::Option *option, bool required=true)
SubCommand * needs (SubCommand *subCommand, bool needs=true)
SubCommand * disabled (SubCommand *subCommand, bool disabled=true)
SubCommand * setRequireCallback (const std::function< void(void)> &callback)
SubCommand * finalCallback (const std::function< void()> &finalCallback)
std::string configToStr () const
std::string help (const CLI::App *helpApp, const CLI::AppFormatMode &mode) const
template<typename NewSubCommand, typename... Args>
NewSubCommand * newSubCommand (Args &&... args)
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand ()
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand () const
CLI::Option * getOption (const std::string &name) const
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator) const
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Protected Member Functions
ConfigAddress (net::config::ConfigInstance *instance, const std::string &addressOptionName, const std::string &addressOptionDescription)
ConfigAddress & setBtAddressRequired (bool required=true)
ConfigAddress & setChannelRequired (bool required=true)
Protected Member Functions inherited from utils::SubCommand
SubCommand (SubCommand *parent, std::shared_ptr< utils::AppWithPtr > appWithPtr, const std::string &group, bool final)
template<typename ConcretSubCommand>
SubCommand (SubCommand *parent, ConcretSubCommand *concretSubCommand, const std::string &group, bool final=true)
SubCommand * description (const std::string &description)
SubCommand * footer (const std::string &footer)
template<typename ValueTypeT>
CLI::Option * setDefaultValue (CLI::Option *option, const ValueTypeT &value, bool clear=true) const
CLI::Option * setConfigurable (CLI::Option *option, bool configurable) const
Protected Attributes
CLI::Option * btAddressOpt = nullptr
CLI::Option * channelOpt = nullptr
Private Types
using Super = ConfigAddressTypeT<net::rc::SocketAddress>
Private Member Functions
SocketAddress * init () final
Additional Inherited Members
Static Public Member Functions inherited from utils::SubCommand
static CLI::App * getHelpTriggerApp ()
static CLI::App * getShowConfigTriggerApp ()
static CLI::App * getCommandlineTriggerApp ()
Static Public Attributes inherited from utils::SubCommand
static std::shared_ptr< CLI::Formatter > sectionFormatter = makeSectionFormatter()
Static Protected Attributes inherited from utils::SubCommand
static std::map< std::string, std::string > aliases
static CLI::App * helpTriggerApp = nullptr
static CLI::App * showConfigTriggerApp = nullptr
static CLI::App * commandlineTriggerApp = nullptr
Detailed Description
template<template< typename SocketAddressT > typename ConfigAddressTypeT>
class net::rc::config::ConfigAddress< ConfigAddressTypeT >
Definition at line 77 of file ConfigAddress.h.
Member Typedef Documentation
Super
template<template< typename SocketAddressT > typename ConfigAddressTypeT> using net::rc::config::ConfigAddress< ConfigAddressTypeT >::Super = ConfigAddressTypeT<net::rc::SocketAddress> private
Definition at line 81 of file ConfigAddress.h.
Constructor & Destructor Documentation
ConfigAddress()
template<template< typename SocketAddress > typename ConfigAddressType> net::rc::config::ConfigAddress< ConfigAddressType >::ConfigAddress (net::config::ConfigInstance * instance, const std::string & addressOptionName, const std::string & addressOptionDescription) protected
Definition at line 69 of file ConfigAddress.cpp.
        : ConfigSection(instance, this)
        , ConfigAddressType<net::rc::SocketAddress>(this) {
        btAddressOpt = addOption( //
            "--host",
            "Bluetooth address (format 01:23:45:67:89:AB)",
            "address",
            "00:00:00:00:00:00",
            CLI::Validator(
                [](std::string& s) -> std::string {
                    // Classic 48-bit Bluetooth/MAC style: "01:23:45:67:89:AB"
                    static const std::regex re(R"(^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$)");
                    if (std::regex_match(s, re)) {
                        return {}; // OK
                    }
                    return "Invalid Bluetooth address. Expected format like \"01:23:45:67:89:AB\" "
                           "(6 hex octets separated by ':').";
                },
                "BT_ADDR")
                .name("BT_ADDR"));
        channelOpt = addOption( //
            "--channel",
            "Channel number",
            "channel",
            "1",
            CLI::Range(static_cast<uint16_t>(1), static_cast<uint16_t>(30)));
    }
Member Function Documentation
configurable()
template<template< typename SocketAddressT > typename ConfigAddressTypeT> void net::rc::config::ConfigAddress< ConfigAddressTypeT >::configurable (bool configurable = true) final
Definition at line 149 of file ConfigAddress.cpp.
{
        this->setConfigurable(btAddressOpt, configurable);
        this->setConfigurable(channelOpt, configurable);
    }
References btAddressOpt, and channelOpt.
getBtAddress()
template<template< typename SocketAddress > typename ConfigAddressType> std::string net::rc::config::ConfigAddress< ConfigAddressType >::getBtAddress () const
Definition at line 129 of file ConfigAddress.cpp.
{
        return btAddressOpt->as<std::string>();
    }
References btAddressOpt.
getChannel()
template<template< typename SocketAddress > typename ConfigAddressType> uint8_t net::rc::config::ConfigAddress< ConfigAddressType >::getChannel () const
Definition at line 144 of file ConfigAddress.cpp.
{
        return channelOpt->as<uint8_t>();
    }
References channelOpt.
init()
template<template< typename SocketAddress > typename ConfigAddressType> SocketAddress * net::rc::config::ConfigAddress< ConfigAddressType >::init () final private
Definition at line 103 of file ConfigAddress.cpp.
{
        SocketAddress* socketAddress = new SocketAddress(btAddressOpt->as<std::string>(), channelOpt->as<uint8_t>());
        socketAddress->init();
        return socketAddress;
    }
setBtAddress()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::rc::config::ConfigAddress< ConfigAddressType >::setBtAddress (const std::string & btAddress)
Definition at line 119 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue(btAddressOpt, btAddress);
        required(btAddressOpt, false);
        return *this;
    }
References btAddressOpt.
Referenced by setSocketAddress().
setBtAddressRequired()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::rc::config::ConfigAddress< ConfigAddressType >::setBtAddressRequired (bool required = true) protected
Definition at line 155 of file ConfigAddress.cpp.
{
        this->required(btAddressOpt, required);
        return *this;
    }
References btAddressOpt.
Referenced by net::rc::stream::config::ConfigSocketClient::ConfigSocketClient().
setChannel()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::rc::config::ConfigAddress< ConfigAddressType >::setChannel (uint8_t channel)
Definition at line 134 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue<int>(channelOpt, channel);
        required(channelOpt, false);
        return *this;
    }
References channelOpt.
Referenced by setSocketAddress().
setChannelRequired()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::rc::config::ConfigAddress< ConfigAddressType >::setChannelRequired (bool required = true) protected
Definition at line 162 of file ConfigAddress.cpp.
{
        this->required(channelOpt, required);
        return *this;
    }
References channelOpt.
Referenced by net::rc::stream::config::ConfigSocketClient::ConfigSocketClient(), and net::rc::stream::config::ConfigSocketServer::ConfigSocketServer().
setSocketAddress()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::rc::config::ConfigAddress< ConfigAddressType >::setSocketAddress (const SocketAddress & socketAddress)
Definition at line 111 of file ConfigAddress.cpp.
{
        setBtAddress(socketAddress.getBtAddress());
        setChannel(socketAddress.getChannel());
        return *this;
    }
References net::rc::SocketAddress::getBtAddress(), net::rc::SocketAddress::getChannel(), setBtAddress(), and setChannel().
Member Data Documentation
btAddressOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::rc::config::ConfigAddress< ConfigAddressTypeT >::btAddressOpt = nullptr protected
Definition at line 106 of file ConfigAddress.h.
Referenced by net::rc::config::ConfigAddressReverse< net::config::ConfigAddressReverse >::ConfigAddressReverse(), configurable(), getBtAddress(), setBtAddress(), and setBtAddressRequired().
channelOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::rc::config::ConfigAddress< ConfigAddressTypeT >::channelOpt = nullptr protected
Definition at line 107 of file ConfigAddress.h.
Referenced by configurable(), getChannel(), setChannel(), and setChannelRequired().
The documentation for this class was generated from the following files:
net/rc/config/ConfigAddress.h
net/rc/config/ConfigAddress.cpp