SNode.C: express::middleware::StaticMiddleware Class Reference
express::middleware::StaticMiddleware Class Reference
#include <StaticMiddleware.h>
Public Member Functions
StaticMiddleware (const StaticMiddleware &)=delete
StaticMiddleware & operator= (const StaticMiddleware &)=delete
StaticMiddleware & clearStdHeaders ()
StaticMiddleware & setStdHeaders (const std::map< std::string, std::string > &stdHeaders)
StaticMiddleware & appendStdHeaders (const std::map< std::string, std::string > &stdHeaders)
StaticMiddleware & appendStdHeaders (const std::string &field, const std::string &value)
StaticMiddleware & appendStdCookie (const std::string &name, const std::string &value, const std::map< std::string, std::string > &options={})
StaticMiddleware & afterResponse (web::http::ConnectionState connectionState)
void laxRouting (bool strict=false)
Route & use (const Router &router) const
Route & use (const std::string &relativeMountPath, const Router &router) const
Route & use (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & use (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & use (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
Route & use (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
template<typename... Lambdas>
Route & use (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & use (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
Route & all (const Router &router) const
Route & all (const std::string &relativeMountPath, const Router &router) const
Route & all (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & all (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & all (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
Route & all (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
template<typename... Lambdas>
Route & all (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & all (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
Route & get (const Router &router) const
Route & get (const std::string &relativeMountPath, const Router &router) const
Route & get (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & get (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & get (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
Route & get (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
template<typename... Lambdas>
Route & get (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & get (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
Route & put (const Router &router) const
Route & put (const std::string &relativeMountPath, const Router &router) const
Route & put (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & put (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & put (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
Route & put (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
template<typename... Lambdas>
Route & put (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & put (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
Route & post (const Router &router) const
Route & post (const std::string &relativeMountPath, const Router &router) const
Route & post (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & post (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & post (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
Route & post (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
template<typename... Lambdas>
Route & post (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & post (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
Route & del (const Router &router) const
Route & del (const std::string &relativeMountPath, const Router &router) const
Route & del (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & del (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & del (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
Route & del (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
template<typename... Lambdas>
Route & del (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & del (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
Route & connect (const Router &router) const
Route & connect (const std::string &relativeMountPath, const Router &router) const
Route & connect (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & connect (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & connect (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
Route & connect (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
template<typename... Lambdas>
Route & connect (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & connect (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
Route & options (const Router &router) const
Route & options (const std::string &relativeMountPath, const Router &router) const
Route & options (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & options (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & options (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
Route & options (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
template<typename... Lambdas>
Route & options (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & options (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
Route & trace (const Router &router) const
Route & trace (const std::string &relativeMountPath, const Router &router) const
Route & trace (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & trace (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & trace (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
Route & trace (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
template<typename... Lambdas>
Route & trace (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & trace (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
Route & patch (const Router &router) const
Route & patch (const std::string &relativeMountPath, const Router &router) const
Route & patch (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & patch (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & patch (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
Route & patch (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
template<typename... Lambdas>
Route & patch (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & patch (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
Route & head (const Router &router) const
Route & head (const std::string &relativeMountPath, const Router &router) const
Route & head (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & head (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda) const
Route & head (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
Route & head (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda) const
template<typename... Lambdas>
Route & head (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & head (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> &lambda, Lambdas... lambdas) const
Protected Member Functions
StaticMiddleware (const std::string &root)
Static Protected Member Functions
static class StaticMiddleware & instance (const std::string &root)
Protected Attributes
std::shared_ptr< RootRoute > rootRoute = nullptr
Private Attributes
std::string root
std::map< std::string, std::string > stdHeaders = {{"Cache-Control", "public, max-age=0"}, {"Accept-Ranges", "bytes"}}
std::map< std::string, web::http::CookieOptions > stdCookies = {}
web::http::ConnectionState defaultConnectionState = web::http::ConnectionState::Default
Friends
class StaticMiddleware & StaticMiddleware (const std::string &root)
Detailed Description
Definition at line 36 of file StaticMiddleware.h.
Constructor & Destructor Documentation
StaticMiddleware() [1/2]
express::middleware::StaticMiddleware::StaticMiddleware (const StaticMiddleware &) delete
StaticMiddleware() [2/2]
express::middleware::StaticMiddleware::StaticMiddleware (const std::string & root) explicit protected
Definition at line 33 of file StaticMiddleware.cpp.
        : root(root) {
        use(
            [&stdHeaders = this->stdHeaders, &stdCookies = this->stdCookies, &connectionState = this->defaultConnectionState] MIDDLEWARE(
                req, res, next) {
                if (req->method == "GET") {
                    if (connectionState == web::http::ConnectionState::Close) {
                        res->set("Connection", "close");
                    } else if (connectionState == web::http::ConnectionState::Keep) {
                        res->set("Connection", "keep-alive");
                    }
                    res->set(stdHeaders);
                    for (auto& [value, options] : stdCookies) {
                        res->cookie(value, options.getValue(), options.getOptions());
                    }
                    next();
                } else {
                    LOG(INFO) << "Express StaticMiddleware: Wrong method " << req->method;
                    if (connectionState == web::http::ConnectionState::Close) {
                        res->set("Connection", "close");
                    } else if (connectionState == web::http::ConnectionState::Keep) {
                        res->set("Connection", "keep-alive");
                    }
                    res->sendStatus(405);
                }
            },
            [] MIDDLEWARE(req, res, next) {
                if (req->url == "/") {
                    LOG(INFO) << "Express StaticMiddleware: REDIRECTING " + req->url + " -> " + "/index.html";
                    res->redirect(308, "/index.html");
                } else {
                    next();
                }
            },
            [&root = this->root] APPLICATION(req, res) {
                res->sendFile(root + req->url, [&root, req, res](int ret) -> void {
                    PLOG(INFO) << "Express StaticMiddleware: GET " + req->url + " -> " + root + req->url;
                    if (ret != 0) {
                        res->status(404).end();
                    }
                });
            });
    }
References web::http::Close, express::Response::cookie(), defaultConnectionState, express::Response::end(), web::http::CookieOptions::getOptions(), web::http::CookieOptions::getValue(), web::http::Keep, express::Request::method, express::Next::operator()(), express::Response::redirect(), root, express::Response::sendFile(), express::Response::sendStatus(), express::Response::set(), express::Response::set(), express::Response::status(), and express::Request::url.
Referenced by instance().
Member Function Documentation
afterResponse()
class StaticMiddleware & express::middleware::StaticMiddleware::afterResponse (web::http::ConnectionState connectionState)
Definition at line 110 of file StaticMiddleware.cpp.
{
        this->defaultConnectionState = connectionState;
        return *this;
    }
References defaultConnectionState.
all() [1/10]
Route & express::Router::all (const Router & router) const inherited
Definition at line 61 of file Router.cpp.
all() [2/10]
Route & express::Router::all (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 61 of file Router.cpp.
all() [3/10]
template<typename... Lambdas> Route & express::Router::all (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 58 of file Router.hpp.
all() [4/10]
Route & express::Router::all (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 61 of file Router.cpp.
all() [5/10]
template<typename... Lambdas> Route & express::Router::all (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 58 of file Router.hpp.
all() [6/10]
Route & express::Router::all (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 61 of file Router.cpp.
all() [7/10]
Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 61 of file Router.cpp.
all() [8/10]
template<typename... Lambdas> Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 58 of file Router.hpp.
all() [9/10]
Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 61 of file Router.cpp.
all() [10/10]
template<typename... Lambdas> Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 58 of file Router.hpp.
appendStdCookie()
class StaticMiddleware & express::middleware::StaticMiddleware::appendStdCookie (const std::string & name, const std::string & value, const std::map< std::string, std::string > & options = {})
Definition at line 102 of file StaticMiddleware.cpp.
{
        this->stdCookies.insert({name, web::http::CookieOptions(value, options)});
        return *this;
    }
References web::http::CookieOptions::CookieOptions(), and stdCookies.
appendStdHeaders() [1/2]
class StaticMiddleware & express::middleware::StaticMiddleware::appendStdHeaders (const std::map< std::string, std::string > & stdHeaders)
Definition at line 90 of file StaticMiddleware.cpp.
{
        this->stdHeaders.insert(stdHeaders.begin(), stdHeaders.end());
        return *this;
    }
References stdHeaders.
appendStdHeaders() [2/2]
class StaticMiddleware & express::middleware::StaticMiddleware::appendStdHeaders (const std::string & field, const std::string & value)
Definition at line 96 of file StaticMiddleware.cpp.
{
        this->stdHeaders[field] = value;
        return *this;
    }
References stdHeaders.
clearStdHeaders()
class StaticMiddleware & express::middleware::StaticMiddleware::clearStdHeaders ()
Definition at line 78 of file StaticMiddleware.cpp.
{
        this->stdHeaders.clear();
        return *this;
    }
References stdHeaders.
connect() [1/10]
Route & express::Router::connect (const Router & router) const inherited
Definition at line 66 of file Router.cpp.
connect() [2/10]
Route & express::Router::connect (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 66 of file Router.cpp.
connect() [3/10]
template<typename... Lambdas> Route & express::Router::connect (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 63 of file Router.hpp.
connect() [4/10]
Route & express::Router::connect (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 66 of file Router.cpp.
connect() [5/10]
template<typename... Lambdas> Route & express::Router::connect (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 63 of file Router.hpp.
connect() [6/10]
Route & express::Router::connect (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 66 of file Router.cpp.
connect() [7/10]
Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 66 of file Router.cpp.
connect() [8/10]
template<typename... Lambdas> Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 63 of file Router.hpp.
connect() [9/10]
Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 66 of file Router.cpp.
connect() [10/10]
template<typename... Lambdas> Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 63 of file Router.hpp.
del() [1/10]
Route & express::Router::del (const Router & router) const inherited
Definition at line 65 of file Router.cpp.
del() [2/10]
Route & express::Router::del (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 65 of file Router.cpp.
del() [3/10]
template<typename... Lambdas> Route & express::Router::del (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 62 of file Router.hpp.
del() [4/10]
Route & express::Router::del (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 65 of file Router.cpp.
del() [5/10]
template<typename... Lambdas> Route & express::Router::del (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 62 of file Router.hpp.
del() [6/10]
Route & express::Router::del (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 65 of file Router.cpp.
del() [7/10]
Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 65 of file Router.cpp.
del() [8/10]
template<typename... Lambdas> Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 62 of file Router.hpp.
del() [9/10]
Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 65 of file Router.cpp.
del() [10/10]
template<typename... Lambdas> Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 62 of file Router.hpp.
get() [1/10]
Route & express::Router::get (const Router & router) const inherited
Definition at line 62 of file Router.cpp.
get() [2/10]
Route & express::Router::get (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 62 of file Router.cpp.
get() [3/10]
template<typename... Lambdas> Route & express::Router::get (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 59 of file Router.hpp.
get() [4/10]
Route & express::Router::get (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 62 of file Router.cpp.
get() [5/10]
template<typename... Lambdas> Route & express::Router::get (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 59 of file Router.hpp.
get() [6/10]
Route & express::Router::get (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 62 of file Router.cpp.
get() [7/10]
Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 62 of file Router.cpp.
get() [8/10]
template<typename... Lambdas> Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 59 of file Router.hpp.
get() [9/10]
Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 62 of file Router.cpp.
get() [10/10]
template<typename... Lambdas> Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 59 of file Router.hpp.
head() [1/10]
Route & express::Router::head (const Router & router) const inherited
Definition at line 70 of file Router.cpp.
head() [2/10]
Route & express::Router::head (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 70 of file Router.cpp.
head() [3/10]
template<typename... Lambdas> Route & express::Router::head (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 67 of file Router.hpp.
head() [4/10]
Route & express::Router::head (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 70 of file Router.cpp.
head() [5/10]
template<typename... Lambdas> Route & express::Router::head (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 67 of file Router.hpp.
head() [6/10]
Route & express::Router::head (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 70 of file Router.cpp.
head() [7/10]
Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 70 of file Router.cpp.
head() [8/10]
template<typename... Lambdas> Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 67 of file Router.hpp.
head() [9/10]
Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 70 of file Router.cpp.
head() [10/10]
template<typename... Lambdas> Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 67 of file Router.hpp.
instance()
class StaticMiddleware & express::middleware::StaticMiddleware::instance (const std::string & root) static protected
Definition at line 116 of file StaticMiddleware.cpp.
{
        // Keep all created static middlewares alive
        static std::map<const std::string, std::shared_ptr<class StaticMiddleware>> staticMiddlewares;
        if (!staticMiddlewares.contains(root)) {
            staticMiddlewares[root] = std::shared_ptr<StaticMiddleware>(new StaticMiddleware(root));
        }
        return *staticMiddlewares[root];
    }
References StaticMiddleware().
Referenced by StaticMiddleware.
laxRouting()
void express::Router::laxRouting (bool strict = false) inherited
Definition at line 56 of file Router.cpp.
{
        rootRoute->strict = strict;
    }
References express::Router::rootRoute, and express::RootRoute::strict.
operator=()
StaticMiddleware & express::middleware::StaticMiddleware::operator= (const StaticMiddleware &) delete
options() [1/10]
Route & express::Router::options (const Router & router) const inherited
Definition at line 67 of file Router.cpp.
options() [2/10]
Route & express::Router::options (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 67 of file Router.cpp.
options() [3/10]
template<typename... Lambdas> Route & express::Router::options (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 64 of file Router.hpp.
options() [4/10]
Route & express::Router::options (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 67 of file Router.cpp.
options() [5/10]
template<typename... Lambdas> Route & express::Router::options (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 64 of file Router.hpp.
options() [6/10]
Route & express::Router::options (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 67 of file Router.cpp.
options() [7/10]
Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 67 of file Router.cpp.
options() [8/10]
template<typename... Lambdas> Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 64 of file Router.hpp.
options() [9/10]
Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 67 of file Router.cpp.
options() [10/10]
template<typename... Lambdas> Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 64 of file Router.hpp.
patch() [1/10]
Route & express::Router::patch (const Router & router) const inherited
Definition at line 69 of file Router.cpp.
patch() [2/10]
Route & express::Router::patch (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 69 of file Router.cpp.
patch() [3/10]
template<typename... Lambdas> Route & express::Router::patch (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 66 of file Router.hpp.
patch() [4/10]
Route & express::Router::patch (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 69 of file Router.cpp.
patch() [5/10]
template<typename... Lambdas> Route & express::Router::patch (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 66 of file Router.hpp.
patch() [6/10]
Route & express::Router::patch (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 69 of file Router.cpp.
patch() [7/10]
Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 69 of file Router.cpp.
patch() [8/10]
template<typename... Lambdas> Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 66 of file Router.hpp.
patch() [9/10]
Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 69 of file Router.cpp.
patch() [10/10]
template<typename... Lambdas> Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 66 of file Router.hpp.
post() [1/10]
Route & express::Router::post (const Router & router) const inherited
Definition at line 64 of file Router.cpp.
post() [2/10]
Route & express::Router::post (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 64 of file Router.cpp.
post() [3/10]
template<typename... Lambdas> Route & express::Router::post (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 61 of file Router.hpp.
post() [4/10]
Route & express::Router::post (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 64 of file Router.cpp.
post() [5/10]
template<typename... Lambdas> Route & express::Router::post (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 61 of file Router.hpp.
post() [6/10]
Route & express::Router::post (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 64 of file Router.cpp.
post() [7/10]
Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 64 of file Router.cpp.
post() [8/10]
template<typename... Lambdas> Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 61 of file Router.hpp.
post() [9/10]
Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 64 of file Router.cpp.
post() [10/10]
template<typename... Lambdas> Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 61 of file Router.hpp.
put() [1/10]
Route & express::Router::put (const Router & router) const inherited
Definition at line 63 of file Router.cpp.
put() [2/10]
Route & express::Router::put (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 63 of file Router.cpp.
put() [3/10]
template<typename... Lambdas> Route & express::Router::put (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 60 of file Router.hpp.
put() [4/10]
Route & express::Router::put (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 63 of file Router.cpp.
put() [5/10]
template<typename... Lambdas> Route & express::Router::put (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 60 of file Router.hpp.
put() [6/10]
Route & express::Router::put (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 63 of file Router.cpp.
put() [7/10]
Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 63 of file Router.cpp.
put() [8/10]
template<typename... Lambdas> Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 60 of file Router.hpp.
put() [9/10]
Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 63 of file Router.cpp.
put() [10/10]
template<typename... Lambdas> Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 60 of file Router.hpp.
setStdHeaders()
class StaticMiddleware & express::middleware::StaticMiddleware::setStdHeaders (const std::map< std::string, std::string > & stdHeaders)
Definition at line 84 of file StaticMiddleware.cpp.
{
        this->stdHeaders = stdHeaders;
        return *this;
    }
References stdHeaders.
trace() [1/10]
Route & express::Router::trace (const Router & router) const inherited
Definition at line 68 of file Router.cpp.
trace() [2/10]
Route & express::Router::trace (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 68 of file Router.cpp.
trace() [3/10]
template<typename... Lambdas> Route & express::Router::trace (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 65 of file Router.hpp.
trace() [4/10]
Route & express::Router::trace (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 68 of file Router.cpp.
trace() [5/10]
template<typename... Lambdas> Route & express::Router::trace (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 65 of file Router.hpp.
trace() [6/10]
Route & express::Router::trace (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 68 of file Router.cpp.
trace() [7/10]
Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 68 of file Router.cpp.
trace() [8/10]
template<typename... Lambdas> Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 65 of file Router.hpp.
trace() [9/10]
Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 68 of file Router.cpp.
trace() [10/10]
template<typename... Lambdas> Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 65 of file Router.hpp.
use() [1/10]
Route & express::Router::use (const Router & router) const inherited
Definition at line 60 of file Router.cpp.
use() [2/10]
Route & express::Router::use (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 60 of file Router.cpp.
use() [3/10]
template<typename... Lambdas> Route & express::Router::use (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 57 of file Router.hpp.
use() [4/10]
Route & express::Router::use (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 60 of file Router.cpp.
use() [5/10]
template<typename... Lambdas> Route & express::Router::use (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 57 of file Router.hpp.
use() [6/10]
Route & express::Router::use (const std::string & relativeMountPath, const Router & router) const inherited
Definition at line 60 of file Router.cpp.
use() [7/10]
Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda) const inherited
Definition at line 60 of file Router.cpp.
use() [8/10]
template<typename... Lambdas> Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 57 of file Router.hpp.
use() [9/10]
Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda) const inherited
Definition at line 60 of file Router.cpp.
use() [10/10]
template<typename... Lambdas> Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, Next &)> & lambda, Lambdas... lambdas) const inherited
Definition at line 57 of file Router.hpp.
Friends And Related Symbol Documentation
StaticMiddleware
class StaticMiddleware & StaticMiddleware (const std::string & root) friend
Definition at line 128 of file StaticMiddleware.cpp.
{
        return StaticMiddleware::instance(root);
    }
References instance().
Member Data Documentation
defaultConnectionState
web::http::ConnectionState express::middleware::StaticMiddleware::defaultConnectionState = web::http::ConnectionState::Default private
Definition at line 59 of file StaticMiddleware.h.
Referenced by afterResponse(), and StaticMiddleware().
root
std::string express::middleware::StaticMiddleware::root private
Definition at line 56 of file StaticMiddleware.h.
Referenced by StaticMiddleware().
rootRoute
std::shared_ptr<RootRoute> express::Router::rootRoute = nullptr protected inherited
Definition at line 95 of file Router.h.
Referenced by express::Router::laxRouting(), and express::Router::Router().
stdCookies
std::map<std::string, web::http::CookieOptions> express::middleware::StaticMiddleware::stdCookies = {} private
Definition at line 58 of file StaticMiddleware.h.
{};
Referenced by appendStdCookie().
stdHeaders
std::map<std::string, std::string> express::middleware::StaticMiddleware::stdHeaders = {{"Cache-Control", "public, max-age=0"}, {"Accept-Ranges", "bytes"}} private
Definition at line 57 of file StaticMiddleware.h.
{{"Cache-Control", "public, max-age=0"}, {"Accept-Ranges", "bytes"}};
Referenced by appendStdHeaders(), appendStdHeaders(), clearStdHeaders(), and setStdHeaders().
The documentation for this class was generated from the following files:
express/middleware/StaticMiddleware.h
express/middleware/StaticMiddleware.cpp