SNode.C: iot::mqtt::Mqtt Class Reference
iot::mqtt::Mqtt Class Reference abstract
#include <Mqtt.h>
Public Member Functions
Mqtt (const std::string &connectionName)
Mqtt (const std::string &connectionName, const std::string &clientId)
Mqtt (Mqtt &&)=delete
Mqtt (const Mqtt &)=delete
Mqtt & operator= (Mqtt &&)=delete
Mqtt & operator= (const Mqtt &)=delete
virtual ~Mqtt ()
virtual void onConnected ()
virtual void onDisconnected ()
virtual bool onSignal (int sig)=0
const std::string & getConnectionName () const
const MqttContext * getMqttContext () const
void sendPublish (const std::string &topic, const std::string &message, uint8_t qoS, bool retain) const
void sendPuback (uint16_t packetIdentifier) const
void sendPubrec (uint16_t packetIdentifier) const
void sendPubrel (uint16_t packetIdentifier) const
void sendPubcomp (uint16_t packetIdentifier) const
Static Public Member Functions
static std::string toHexString (const std::vector< char > &data)
static std::string toHexString (const std::string &data)
Protected Member Functions
void initSession (Session *session, utils::Timeval keepAlive)
virtual void onPublish (const iot::mqtt::packets::Publish &publish)
virtual void onPuback (const iot::mqtt::packets::Puback &puback)
virtual void onPubrec (const iot::mqtt::packets::Pubrec &pubrec)
virtual void onPubrel (const iot::mqtt::packets::Pubrel &pubrel)
virtual void onPubcomp (const iot::mqtt::packets::Pubcomp &pubcomp)
bool _onPublish (const iot::mqtt::packets::Publish &publish)
void _onPuback (const iot::mqtt::packets::Puback &puback)
void _onPubrec (const iot::mqtt::packets::Pubrec &pubrec)
void _onPubrel (const iot::mqtt::packets::Pubrel &pubrel)
void _onPubcomp (const iot::mqtt::packets::Pubcomp &pubcomp)
uint16_t getPacketIdentifier () const
void send (const iot::mqtt::ControlPacket &controlPacket) const
virtual void deliverPublish (const iot::mqtt::packets::Publish &publish)=0
void printVP (const iot::mqtt::ControlPacket &packet) const
void printFixedHeader (const iot::mqtt::FixedHeader &fixedHeader) const
Protected Attributes
std::string connectionName
std::string clientId
MqttContext * mqttContext = nullptr
Private Member Functions
std::size_t onReceivedFromPeer ()
void setMqttContext (MqttContext *mqttContext)
virtual iot::mqtt::ControlPacketDeserializer * createControlPacketDeserializer (iot::mqtt::FixedHeader &staticHeader) const =0
virtual void deliverPacket (iot::mqtt::ControlPacketDeserializer *controlPacketDeserializer)=0
void send (const std::vector< char > &data) const
Private Attributes
iot::mqtt::FixedHeader fixedHeader
iot::mqtt::ControlPacketDeserializer * controlPacketDeserializer = nullptr
uint16_t _packetIdentifier = 0
core::timer::Timer keepAliveTimer
int state = 0
Session * session = nullptr
Friends
class MqttContext
Detailed Description
Definition at line 74 of file Mqtt.h.
Constructor & Destructor Documentation
Mqtt() [1/4]
iot::mqtt::Mqtt::Mqtt (const std::string & connectionName)
Definition at line 69 of file Mqtt.cpp.
        : connectionName(connectionName) {
    }
References connectionName.
Referenced by iot::mqtt::server::Mqtt::Mqtt().
Mqtt() [2/4]
iot::mqtt::Mqtt::Mqtt (const std::string & connectionName, const std::string & clientId)
Definition at line 73 of file Mqtt.cpp.
        : connectionName(connectionName)
        , clientId(clientId) {
    }
References clientId, and connectionName.
Referenced by iot::mqtt::client::Mqtt::Mqtt().
Mqtt() [3/4]
iot::mqtt::Mqtt::Mqtt (Mqtt &&) delete
Mqtt() [4/4]
iot::mqtt::Mqtt::Mqtt (const Mqtt &) delete
~Mqtt()
iot::mqtt::Mqtt::~Mqtt () virtual
Reimplemented in iot::mqtt::client::Mqtt, and iot::mqtt::server::Mqtt.
Definition at line 78 of file Mqtt.cpp.
                {
        if (controlPacketDeserializer != nullptr) {
            delete controlPacketDeserializer;
            controlPacketDeserializer = nullptr;
        }
        keepAliveTimer.cancel();
    }
References core::Timer::cancel(), controlPacketDeserializer, and keepAliveTimer.
Member Function Documentation
_onPuback()
void iot::mqtt::Mqtt::_onPuback (const iot::mqtt::packets::Puback & puback) protected
Definition at line 323 of file Mqtt.cpp.
{
        if (puback.getPacketIdentifier() == 0) {
            LOG(ERROR) << connectionName << " MQTT:   PackageIdentifier missing";
            mqttContext->close();
        } else {
            LOG(DEBUG) << connectionName << " MQTT:   PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4)
                       << puback.getPacketIdentifier() << std::dec;
            session->outgoingPublishMap.erase(puback.getPacketIdentifier());
        }
        onPuback(puback);
    }
References iot::mqtt::MqttContext::close(), connectionName, iot::mqtt::packets::Puback::getPacketIdentifier(), mqttContext, onPuback(), iot::mqtt::Session::outgoingPublishMap, and session.
Referenced by iot::mqtt::client::packets::Puback::deliverPacket(), and iot::mqtt::server::packets::Puback::deliverPacket().
_onPubcomp()
void iot::mqtt::Mqtt::_onPubcomp (const iot::mqtt::packets::Pubcomp & pubcomp) protected
Definition at line 385 of file Mqtt.cpp.
{
        if (pubcomp.getPacketIdentifier() == 0) {
            LOG(ERROR) << connectionName << " MQTT:   PackageIdentifier missing";
            mqttContext->close();
        } else {
            LOG(DEBUG) << connectionName << " MQTT:   PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4)
                       << pubcomp.getPacketIdentifier() << std::dec;
            session->outgoingPublishMap.erase(pubcomp.getPacketIdentifier());
            session->pubrelPacketIdentifierSet.erase(pubcomp.getPacketIdentifier());
        }
        onPubcomp(pubcomp);
    }
References iot::mqtt::MqttContext::close(), connectionName, iot::mqtt::packets::Pubcomp::getPacketIdentifier(), mqttContext, onPubcomp(), iot::mqtt::Session::outgoingPublishMap, iot::mqtt::Session::pubrelPacketIdentifierSet, and session.
Referenced by iot::mqtt::client::packets::Pubcomp::deliverPacket(), and iot::mqtt::server::packets::Pubcomp::deliverPacket().
_onPublish()
bool iot::mqtt::Mqtt::_onPublish (const iot::mqtt::packets::Publish & publish) protected
Definition at line 266 of file Mqtt.cpp.
{
        bool deliver = true;
        LOG(INFO) << connectionName << " MQTT:   Topic: " << publish.getTopic();
        LOG(INFO) << connectionName << " MQTT:   Message:\n" << toHexString(publish.getMessage());
        LOG(DEBUG) << connectionName << " MQTT:   QoS: " << static_cast<uint16_t>(publish.getQoS());
        LOG(DEBUG) << connectionName << " MQTT:   PacketIdentifier: " << publish.getPacketIdentifier();
        LOG(DEBUG) << connectionName << " MQTT:   DUP: " << publish.getDup();
        LOG(DEBUG) << connectionName << " MQTT:   Retain: " << publish.getRetain();
        if (publish.getQoS() > 2) {
            LOG(ERROR) << connectionName << " MQTT:   Received invalid QoS: " << publish.getQoS();
            mqttContext->close();
            deliver = false;
        } else if (publish.getPacketIdentifier() == 0 && publish.getQoS() > 0) {
            LOG(ERROR) << connectionName << " MQTT:   Received QoS > 0 but no PackageIdentifier present";
            mqttContext->close();
            deliver = false;
        } else if (publish.getQoS() == 0 && publish.getDup()) {
            LOG(ERROR) << connectionName << " MQTT:   Received QoS == 0 but dup is set";
            mqttContext->close();
            deliver = false;
        } else {
            switch (publish.getQoS()) {
                case 1:
                    sendPuback(publish.getPacketIdentifier());
                    break;
                case 2:
                    sendPubrec(publish.getPacketIdentifier());
                    deliver = false;
                    const uint16_t pid = publish.getPacketIdentifier();
                    if (session->pubcompPacketIdentifierSet.contains(pid)) {
                        if (!publish.getDup()) {
                            session->pubcompPacketIdentifierSet.erase(pid);
                        } else {
                            LOG(WARNING) << connectionName << " MQTT:   Duplicate QoS2 PUBLISH after PUBCOMP for PacketIdentifier: " << pid;
                            break;
                        }
                    }
                    if (session->incomingPublishMap.contains(pid)) {
                        LOG(INFO) << connectionName << " MQTT:   Duplicate QoS2 PUBLISH suppressed for PacketIdentifier: " << pid;
                    } else {
                        session->incomingPublishMap.emplace(pid, publish);
                    }
                    break;
            }
        }
        return deliver;
    }
References iot::mqtt::MqttContext::close(), connectionName, iot::mqtt::packets::Publish::getDup(), iot::mqtt::packets::Publish::getMessage(), iot::mqtt::packets::Publish::getPacketIdentifier(), iot::mqtt::packets::Publish::getQoS(), iot::mqtt::packets::Publish::getRetain(), iot::mqtt::packets::Publish::getTopic(), iot::mqtt::Session::incomingPublishMap, mqttContext, iot::mqtt::Session::pubcompPacketIdentifierSet, sendPuback(), sendPubrec(), session, and toHexString().
Referenced by iot::mqtt::client::Mqtt::_onPublish(), and iot::mqtt::server::Mqtt::_onPublish().
_onPubrec()
void iot::mqtt::Mqtt::_onPubrec (const iot::mqtt::packets::Pubrec & pubrec) protected
Definition at line 337 of file Mqtt.cpp.
{
        if (pubrec.getPacketIdentifier() == 0) {
            LOG(ERROR) << connectionName << " MQTT:   PackageIdentifier missing";
            mqttContext->close();
        } else {
            LOG(DEBUG) << connectionName << " MQTT:   PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4)
                       << pubrec.getPacketIdentifier() << std::dec;
            session->outgoingPublishMap.erase(pubrec.getPacketIdentifier());
            session->pubrelPacketIdentifierSet.insert(pubrec.getPacketIdentifier());
            sendPubrel(pubrec.getPacketIdentifier());
        }
        onPubrec(pubrec);
    }
References iot::mqtt::MqttContext::close(), connectionName, iot::mqtt::packets::Pubrec::getPacketIdentifier(), mqttContext, onPubrec(), iot::mqtt::Session::outgoingPublishMap, iot::mqtt::Session::pubrelPacketIdentifierSet, sendPubrel(), and session.
Referenced by iot::mqtt::client::packets::Pubrec::deliverPacket(), and iot::mqtt::server::packets::Pubrec::deliverPacket().
_onPubrel()
void iot::mqtt::Mqtt::_onPubrel (const iot::mqtt::packets::Pubrel & pubrel) protected
Definition at line 354 of file Mqtt.cpp.
{
        if (pubrel.getPacketIdentifier() == 0) {
            LOG(ERROR) << connectionName << " MQTT:   PackageIdentifier missing";
            mqttContext->close();
        } else {
            LOG(DEBUG) << connectionName << " MQTT:   PacketIdentifier: 0x" << std::hex << std::setfill('0') << std::setw(4)
                       << pubrel.getPacketIdentifier() << std::dec;
            const uint16_t pid = pubrel.getPacketIdentifier();
            if (session->incomingPublishMap.contains(pid)) {
                LOG(INFO) << connectionName << " MQTT:   QoS2 PUBREL received. Deliver publish: " << pid;
                deliverPublish(session->incomingPublishMap[pid]);
                session->incomingPublishMap.erase(pid);
                session->pubcompPacketIdentifierSet.insert(pid);
            } else if (session->pubcompPacketIdentifierSet.contains(pid)) {
                LOG(INFO) << connectionName << " MQTT:   Duplicate QoS2 PUBREL for completed PacketIdentifier: " << pid;
            } else {
                LOG(WARNING) << connectionName << " MQTT:   QoS2 PUBREL received for unknown PacketIdentifier: " << pid;
                session->pubcompPacketIdentifierSet.insert(pid);
            }
            sendPubcomp(pid);
        }
        onPubrel(pubrel);
    }
References iot::mqtt::MqttContext::close(), connectionName, deliverPublish(), iot::mqtt::packets::Pubrel::getPacketIdentifier(), iot::mqtt::Session::incomingPublishMap, mqttContext, onPubrel(), iot::mqtt::Session::pubcompPacketIdentifierSet, sendPubcomp(), and session.
Referenced by iot::mqtt::client::packets::Pubrel::deliverPacket(), and iot::mqtt::server::packets::Pubrel::deliverPacket().
createControlPacketDeserializer()
virtual iot::mqtt::ControlPacketDeserializer * iot::mqtt::Mqtt::createControlPacketDeserializer (iot::mqtt::FixedHeader & staticHeader) const private pure virtual
Implemented in iot::mqtt::client::Mqtt, and iot::mqtt::server::Mqtt.
deliverPacket()
virtual void iot::mqtt::Mqtt::deliverPacket (iot::mqtt::ControlPacketDeserializer * controlPacketDeserializer) private pure virtual
Implemented in iot::mqtt::client::Mqtt, and iot::mqtt::server::Mqtt.
deliverPublish()
virtual void iot::mqtt::Mqtt::deliverPublish (const iot::mqtt::packets::Publish & publish) protected pure virtual
Implemented in iot::mqtt::client::Mqtt, and iot::mqtt::server::Mqtt.
Referenced by _onPubrel().
getConnectionName()
const std::string & iot::mqtt::Mqtt::getConnectionName () const
Definition at line 170 of file Mqtt.cpp.
{
        return connectionName;
    }
References connectionName.
getMqttContext()
const MqttContext * iot::mqtt::Mqtt::getMqttContext () const
Definition at line 91 of file Mqtt.cpp.
{
        return mqttContext;
    }
References mqttContext.
getPacketIdentifier()
uint16_t iot::mqtt::Mqtt::getPacketIdentifier () const protected
Definition at line 431 of file Mqtt.cpp.
{
        do {
            ++_packetIdentifier;
            if (_packetIdentifier == 0) {
                _packetIdentifier = 1;
            }
        } while (session->outgoingPublishMap.contains(_packetIdentifier) || session->pubrelPacketIdentifierSet.contains(_packetIdentifier));
        return _packetIdentifier;
    }
References _packetIdentifier, iot::mqtt::Session::outgoingPublishMap, iot::mqtt::Session::pubrelPacketIdentifierSet, and session.
Referenced by sendPublish(), iot::mqtt::client::Mqtt::sendSubscribe(), and iot::mqtt::client::Mqtt::sendUnsubscribe().
initSession()
void iot::mqtt::Mqtt::initSession (Session * session, utils::Timeval keepAlive) protected
Definition at line 174 of file Mqtt.cpp.
{
        this->session = session;
        for (const auto& [packetIdentifier, publish] : session->outgoingPublishMap) {
            LOG(INFO) << connectionName << " MQTT: PUBLISH Resend";
            send(publish);
        }
        for (const uint16_t packetIdentifier : session->pubrelPacketIdentifierSet) {
            LOG(INFO) << connectionName << " MQTT: PUBREL Resend";
            sendPubrel(packetIdentifier);
        }
        if (keepAlive > 0) {
            keepAlive *= 1.5;
            LOG(INFO) << connectionName << " MQTT: Keep alive initialized with: " << keepAlive;
            keepAliveTimer = core::timer::Timer::singleshotTimer(
                [this, keepAlive]() {
                    LOG(ERROR) << connectionName << " MQTT: Keep-alive timer expired. Interval was: " << keepAlive;
                    mqttContext->close();
                },
                keepAlive);
        }
        mqttContext->getSocketConnection()->setTimeout(0);
    }
References iot::mqtt::MqttContext::close(), connectionName, iot::mqtt::MqttContext::getSocketConnection(), keepAliveTimer, mqttContext, utils::Timeval::operator*=(), core::timer::Timer::operator=(), utils::Timeval::operator>(), iot::mqtt::Session::outgoingPublishMap, iot::mqtt::Session::pubrelPacketIdentifierSet, send(), sendPubrel(), session, core::socket::stream::SocketConnection::setTimeout(), and core::timer::Timer::singleshotTimer().
Referenced by iot::mqtt::client::Mqtt::_onConnack(), and iot::mqtt::server::Mqtt::initSession().
onConnected()
void iot::mqtt::Mqtt::onConnected () virtual
Definition at line 95 of file Mqtt.cpp.
{
        LOG(INFO) << "MQTT: Connected";
    }
Referenced by iot::mqtt::MqttContext::onConnected().
onDisconnected()
void iot::mqtt::Mqtt::onDisconnected () virtual
Definition at line 166 of file Mqtt.cpp.
{
        LOG(INFO) << connectionName << " MQTT: Disconnected";
    }
References connectionName.
Referenced by iot::mqtt::MqttContext::onDisconnected().
onPuback()
void iot::mqtt::Mqtt::onPuback (const iot::mqtt::packets::Puback & puback) protected virtual
Definition at line 254 of file Mqtt.cpp.
{
    }
Referenced by _onPuback().
onPubcomp()
void iot::mqtt::Mqtt::onPubcomp (const iot::mqtt::packets::Pubcomp & pubcomp) protected virtual
Definition at line 263 of file Mqtt.cpp.
{
    }
Referenced by _onPubcomp().
onPublish()
void iot::mqtt::Mqtt::onPublish (const iot::mqtt::packets::Publish & publish) protected virtual
Definition at line 251 of file Mqtt.cpp.
{
    }
Referenced by iot::mqtt::client::Mqtt::deliverPublish(), and iot::mqtt::server::Mqtt::deliverPublish().
onPubrec()
void iot::mqtt::Mqtt::onPubrec (const iot::mqtt::packets::Pubrec & pubrec) protected virtual
Definition at line 257 of file Mqtt.cpp.
{
    }
Referenced by _onPubrec().
onPubrel()
void iot::mqtt::Mqtt::onPubrel (const iot::mqtt::packets::Pubrel & pubrel) protected virtual
Definition at line 260 of file Mqtt.cpp.
{
    }
Referenced by _onPubrel().
onReceivedFromPeer()
std::size_t iot::mqtt::Mqtt::onReceivedFromPeer () private
Definition at line 99 of file Mqtt.cpp.
{
        std::size_t consumed = 0;
        switch (state) {
            case 0:
                consumed = fixedHeader.deserialize(mqttContext);
                if (!fixedHeader.isComplete()) {
                    break;
                }
                if (fixedHeader.isError()) {
                    mqttContext->close();
                    break;
                }
                printFixedHeader(fixedHeader);
                controlPacketDeserializer = createControlPacketDeserializer(fixedHeader);
                fixedHeader.reset();
                if (controlPacketDeserializer == nullptr) {
                    LOG(DEBUG) << connectionName << " MQTT: Received packet-type is unavailable ... closing connection";
                    mqttContext->close();
                    break;
                }
                if (controlPacketDeserializer->isError()) {
                    LOG(DEBUG) << connectionName << " MQTT: Fixed header has error ... closing connection";
                    delete controlPacketDeserializer;
                    controlPacketDeserializer = nullptr;
                    mqttContext->close();
                    break;
                }
                state++;
                [[fallthrough]];
            case 1:
                consumed += controlPacketDeserializer->deserialize(mqttContext);
                if (controlPacketDeserializer->isError()) {
                    LOG(DEBUG) << connectionName << " MQTT: Control packet has error ... closing connection";
                    mqttContext->close();
                    delete controlPacketDeserializer;
                    controlPacketDeserializer = nullptr;
                    state = 0;
                } else if (controlPacketDeserializer->isComplete()) {
                    deliverPacket(controlPacketDeserializer);
                    delete controlPacketDeserializer;
                    controlPacketDeserializer = nullptr;
                    state = 0;
                    keepAliveTimer.restart();
                }
                break;
        }
        return consumed;
    }
References iot::mqtt::FixedHeader::deserialize(), fixedHeader, mqttContext, and state.
Referenced by iot::mqtt::MqttContext::onReceivedFromPeer().
onSignal()
virtual bool iot::mqtt::Mqtt::onSignal (int sig) pure virtual
Implemented in iot::mqtt::client::Mqtt, and iot::mqtt::server::Mqtt.
Referenced by iot::mqtt::MqttContext::onSignal().
operator=() [1/2]
Mqtt & iot::mqtt::Mqtt::operator= (const Mqtt &) delete
operator=() [2/2]
Mqtt & iot::mqtt::Mqtt::operator= (Mqtt &&) delete
printFixedHeader()
void iot::mqtt::Mqtt::printFixedHeader (const iot::mqtt::FixedHeader & fixedHeader) const protected
Definition at line 409 of file Mqtt.cpp.
{
        LOG(INFO) << connectionName << " MQTT: ====================================";
        LOG(TRACE) << connectionName << " MQTT: Received data (fixed header):\n" << toHexString(fixedHeader.serialize());
        LOG(DEBUG) << connectionName << " MQTT: Fixed Header: PacketType: 0x" << std::hex << std::setfill('0') << std::setw(2)
                   << static_cast<uint16_t>(fixedHeader.getType()) << " (" << iot::mqtt::mqttPackageName[fixedHeader.getType()] << ")"
                   << std::dec;
        LOG(DEBUG) << connectionName << " MQTT:   PacketFlags: 0x" << std::hex << std::setfill('0') << std::setw(2)
                   << static_cast<uint16_t>(fixedHeader.getFlags()) << std::dec;
        LOG(DEBUG) << connectionName << " MQTT:   RemainingLength: " << fixedHeader.getRemainingLength();
    }
References connectionName, iot::mqtt::FixedHeader::getFlags(), iot::mqtt::FixedHeader::getRemainingLength(), iot::mqtt::FixedHeader::getType(), iot::mqtt::mqttPackageName, iot::mqtt::FixedHeader::serialize(), and toHexString().
printVP()
void iot::mqtt::Mqtt::printVP (const iot::mqtt::ControlPacket & packet) const protected
Definition at line 400 of file Mqtt.cpp.
{
        LOG(INFO) << connectionName << " MQTT: " << packet.getName() << " received: " << clientId;
        const std::string hexString = toHexString(packet.serializeVP());
        if (!hexString.empty()) {
            LOG(TRACE) << connectionName << " MQTT: Received data (variable header and payload):\n" << hexString;
        }
    }
References clientId, connectionName, iot::mqtt::ControlPacket::getName(), iot::mqtt::ControlPacket::serializeVP(), and toHexString().
Referenced by iot::mqtt::client::packets::Connack::deliverPacket(), iot::mqtt::client::packets::Pingresp::deliverPacket(), iot::mqtt::client::packets::Puback::deliverPacket(), iot::mqtt::client::packets::Pubcomp::deliverPacket(), iot::mqtt::client::packets::Publish::deliverPacket(), iot::mqtt::client::packets::Pubrec::deliverPacket(), iot::mqtt::client::packets::Pubrel::deliverPacket(), iot::mqtt::client::packets::Suback::deliverPacket(), iot::mqtt::client::packets::Unsuback::deliverPacket(), iot::mqtt::server::packets::Connect::deliverPacket(), iot::mqtt::server::packets::Disconnect::deliverPacket(), iot::mqtt::server::packets::Pingreq::deliverPacket(), iot::mqtt::server::packets::Puback::deliverPacket(), iot::mqtt::server::packets::Pubcomp::deliverPacket(), iot::mqtt::server::packets::Publish::deliverPacket(), iot::mqtt::server::packets::Pubrec::deliverPacket(), iot::mqtt::server::packets::Pubrel::deliverPacket(), iot::mqtt::server::packets::Subscribe::deliverPacket(), and iot::mqtt::server::packets::Unsubscribe::deliverPacket().
send() [1/2]
void iot::mqtt::Mqtt::send (const iot::mqtt::ControlPacket & controlPacket) const protected
Definition at line 205 of file Mqtt.cpp.
{
        LOG(INFO) << connectionName << " MQTT: " << controlPacket.getName() << " send: " << clientId;
        send(controlPacket.serialize());
    }
References clientId, connectionName, iot::mqtt::ControlPacket::getName(), send(), and iot::mqtt::ControlPacket::serialize().
Referenced by initSession(), iot::mqtt::server::Mqtt::sendConnack(), iot::mqtt::client::Mqtt::sendConnect(), iot::mqtt::client::Mqtt::sendDisconnect(), iot::mqtt::client::Mqtt::sendPingreq(), iot::mqtt::server::Mqtt::sendPingresp(), sendPuback(), sendPubcomp(), sendPublish(), sendPubrec(), sendPubrel(), iot::mqtt::server::Mqtt::sendSuback(), iot::mqtt::client::Mqtt::sendSubscribe(), iot::mqtt::server::Mqtt::sendUnsuback(), and iot::mqtt::client::Mqtt::sendUnsubscribe().
send() [2/2]
void iot::mqtt::Mqtt::send (const std::vector< char > & data) const private
Definition at line 211 of file Mqtt.cpp.
{
        LOG(TRACE) << connectionName << " MQTT: Send data (full message):\n" << toHexString(data);
        mqttContext->send(data.data(), data.size());
    }
References connectionName, mqttContext, iot::mqtt::MqttContext::send(), and toHexString().
Referenced by send().
sendPuback()
void iot::mqtt::Mqtt::sendPuback (uint16_t packetIdentifier) const
Definition at line 235 of file Mqtt.cpp.
                                                         { // Server & Client
        send(iot::mqtt::packets::Puback(packetIdentifier));
    }
References iot::mqtt::packets::Puback::Puback(), and send().
Referenced by _onPublish().
sendPubcomp()
void iot::mqtt::Mqtt::sendPubcomp (uint16_t packetIdentifier) const
Definition at line 247 of file Mqtt.cpp.
                                                          { // Server & Client
        send(iot::mqtt::packets::Pubcomp(packetIdentifier));
    }
References iot::mqtt::packets::Pubcomp::Pubcomp(), and send().
Referenced by _onPubrel().
sendPublish()
void iot::mqtt::Mqtt::sendPublish (const std::string & topic, const std::string & message, uint8_t qoS, bool retain) const
Definition at line 217 of file Mqtt.cpp.
{
        const uint16_t packetIdentifier = qoS != 0 ? getPacketIdentifier() : 0;
        send(iot::mqtt::packets::Publish(packetIdentifier, topic, message, qoS, false, retain));
        LOG(INFO) << connectionName << " MQTT:   Topic: " << topic;
        LOG(INFO) << connectionName << " MQTT:   Message:\n" << toHexString(message);
        LOG(DEBUG) << connectionName << " MQTT:   QoS: " << static_cast<uint16_t>(qoS);
        LOG(DEBUG) << connectionName << " MQTT:   PacketIdentifier: " << packetIdentifier;
        LOG(DEBUG) << connectionName << " MQTT:   DUP: " << false;
        LOG(DEBUG) << connectionName << " MQTT:   Retain: " << retain;
        if (qoS >= 1) {
            session->outgoingPublishMap.insert_or_assign(packetIdentifier,
                                                         iot::mqtt::packets::Publish(packetIdentifier, topic, message, qoS, true, retain));
        }
    }
References connectionName, getPacketIdentifier(), iot::mqtt::Session::outgoingPublishMap, iot::mqtt::packets::Publish::Publish(), send(), session, and toHexString().
Referenced by iot::mqtt::server::broker::Session::sendPublish().
sendPubrec()
void iot::mqtt::Mqtt::sendPubrec (uint16_t packetIdentifier) const
Definition at line 239 of file Mqtt.cpp.
                                                         { // Server & Client
        send(iot::mqtt::packets::Pubrec(packetIdentifier));
    }
References iot::mqtt::packets::Pubrec::Pubrec(), and send().
Referenced by _onPublish().
sendPubrel()
void iot::mqtt::Mqtt::sendPubrel (uint16_t packetIdentifier) const
Definition at line 243 of file Mqtt.cpp.
                                                         { // Server & Client
        send(iot::mqtt::packets::Pubrel(packetIdentifier));
    }
References iot::mqtt::packets::Pubrel::Pubrel(), and send().
Referenced by _onPubrec(), and initSession().
setMqttContext()
void iot::mqtt::Mqtt::setMqttContext (MqttContext * mqttContext) private
Definition at line 87 of file Mqtt.cpp.
{
        this->mqttContext = mqttContext;
    }
References mqttContext.
Referenced by iot::mqtt::MqttContext::MqttContext().
toHexString() [1/2]
std::string iot::mqtt::Mqtt::toHexString (const std::string & data) static
Definition at line 427 of file Mqtt.cpp.
{
        return toHexString(std::vector<char>(data.begin(), data.end()));
    }
References toHexString().
Referenced by _onPublish(), iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), iot::mqtt::server::broker::RetainTree::TopicLevel::appear(), iot::mqtt::server::broker::SubscriptionTree::TopicLevel::publish(), iot::mqtt::server::broker::RetainTree::TopicLevel::retain(), sendPublish(), and iot::mqtt::server::broker::Session::sendPublish().
toHexString() [2/2]
std::string iot::mqtt::Mqtt::toHexString (const std::vector< char > & data) static
Definition at line 422 of file Mqtt.cpp.
{
        const std::string hexDump = utils::hexDump(data, 32);
        return !hexDump.empty() ? std::string(32, ' ').append(hexDump) : "";
    }
References utils::hexDump().
Referenced by printFixedHeader(), printVP(), send(), and toHexString().
Friends And Related Symbol Documentation
MqttContext
friend class MqttContext friend
Definition at line 162 of file Mqtt.h.
Member Data Documentation
_packetIdentifier
uint16_t iot::mqtt::Mqtt::_packetIdentifier = 0 mutable private
Definition at line 151 of file Mqtt.h.
Referenced by getPacketIdentifier().
clientId
std::string iot::mqtt::Mqtt::clientId protected
Definition at line 145 of file Mqtt.h.
Referenced by iot::mqtt::server::Mqtt::_onConnect(), iot::mqtt::server::Mqtt::_onSubscribe(), iot::mqtt::server::Mqtt::_onUnsubscribe(), iot::mqtt::server::Mqtt::deliverPublish(), iot::mqtt::server::Mqtt::getClientId(), iot::mqtt::server::Mqtt::getSubscriptions(), iot::mqtt::server::Mqtt::initSession(), Mqtt(), printVP(), iot::mqtt::server::Mqtt::releaseSession(), send(), iot::mqtt::client::Mqtt::sendConnect(), and iot::mqtt::server::Mqtt::~Mqtt().
connectionName
std::string iot::mqtt::Mqtt::connectionName protected
Definition at line 144 of file Mqtt.h.
Referenced by iot::mqtt::client::Mqtt::_onConnack(), iot::mqtt::server::Mqtt::_onConnect(), _onPuback(), _onPubcomp(), _onPublish(), _onPubrec(), _onPubrel(), iot::mqtt::client::Mqtt::_onSuback(), iot::mqtt::server::Mqtt::_onSubscribe(), iot::mqtt::client::Mqtt::_onUnsuback(), iot::mqtt::server::Mqtt::_onUnsubscribe(), getConnectionName(), initSession(), iot::mqtt::server::Mqtt::initSession(), Mqtt(), Mqtt(), onDisconnected(), printFixedHeader(), printVP(), iot::mqtt::server::Mqtt::releaseSession(), send(), send(), iot::mqtt::client::Mqtt::sendConnect(), sendPublish(), and iot::mqtt::client::Mqtt::~Mqtt().
controlPacketDeserializer
iot::mqtt::ControlPacketDeserializer* iot::mqtt::Mqtt::controlPacketDeserializer = nullptr private
Definition at line 149 of file Mqtt.h.
Referenced by ~Mqtt().
fixedHeader
iot::mqtt::FixedHeader iot::mqtt::Mqtt::fixedHeader private
Definition at line 148 of file Mqtt.h.
Referenced by onReceivedFromPeer().
keepAliveTimer
core::timer::Timer iot::mqtt::Mqtt::keepAliveTimer private
Definition at line 153 of file Mqtt.h.
Referenced by initSession(), and ~Mqtt().
mqttContext
MqttContext* iot::mqtt::Mqtt::mqttContext = nullptr protected
Definition at line 160 of file Mqtt.h.
Referenced by iot::mqtt::server::Mqtt::_onConnect(), _onPuback(), _onPubcomp(), _onPublish(), _onPubrec(), _onPubrel(), iot::mqtt::client::Mqtt::_onSuback(), iot::mqtt::server::Mqtt::_onSubscribe(), iot::mqtt::client::Mqtt::_onUnsuback(), iot::mqtt::server::Mqtt::_onUnsubscribe(), getMqttContext(), initSession(), onReceivedFromPeer(), send(), iot::mqtt::client::Mqtt::sendDisconnect(), and setMqttContext().
session
Session* iot::mqtt::Mqtt::session = nullptr private
Definition at line 157 of file Mqtt.h.
Referenced by _onPuback(), _onPubcomp(), _onPublish(), _onPubrec(), _onPubrel(), getPacketIdentifier(), initSession(), and sendPublish().
state
int iot::mqtt::Mqtt::state = 0 private
Definition at line 155 of file Mqtt.h.
Referenced by onReceivedFromPeer().
The documentation for this class was generated from the following files:
iot/mqtt/Mqtt.h
iot/mqtt/Mqtt.cpp