snode.c: net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT > Class Template Reference
net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT > Class Template Reference
#include <SocketServer.h>
Public Member Functions
void listen (uint16_t port, const std::function< void(const core::ProgressLog &)> &onError) const
void listen (uint16_t port, int backlog, const std::function< void(const core::ProgressLog &)> &onError) const
void listen (const std::string &ipOrHostname, uint16_t port, const std::function< void(const core::ProgressLog &)> &onError) const
void listen (const std::string &ipOrHostname, uint16_t port, int backlog, const std::function< void(const core::ProgressLog &)> &onError) const
Public Member Functions inherited from core::socket::stream::SocketServer< SocketAcceptorT< net::in6::stream::PhysicalServerSocket, ConfigSocketServerT >, SocketContextFactoryT >
SocketServer (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect)
SocketServer (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect)
SocketServer (const std::string &name)
SocketServer ()
SocketServer (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, SocketContextFactory *socketContextFactory)
SocketServer (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, SocketContextFactory *socketContextFactory)
SocketServer (const std::string &name, SocketContextFactory *socketContextFactory)
SocketServer (SocketContextFactory *socketContextFactory)
void listen (const std::function< void(const core::ProgressLog &)> &onError) const
void listen (const SocketAddress &localAddress, const std::function< void(const core::ProgressLog &)> &onError) const
void listen (const SocketAddress &localAddress, int backlog, const std::function< void(const core::ProgressLog &)> &onError) const
void setOnConnect (const std::function< void(SocketConnection *)> &onConnect)
void setOnConnected (const std::function< void(SocketConnection *)> &onConnected)
void setOnDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
Public Member Functions inherited from core::socket::LogicalSocket< SocketAcceptorT::Config >
LogicalSocket (const std::string &name)
LogicalSocket (const LogicalSocket &)=default
LogicalSocket (LogicalSocket &&)=default
LogicalSocket & operator= (const LogicalSocket &)=default
LogicalSocket & operator= (LogicalSocket &&)=default
virtual ~LogicalSocket ()
Config & getConfig () const
Private Types
using Super = core::socket::stream::SocketServer< SocketAcceptorT< net::in6::stream::PhysicalServerSocket, ConfigSocketServerT >, SocketContextFactoryT >
Additional Inherited Members
Public Types inherited from core::socket::stream::SocketServer< SocketAcceptorT< net::in6::stream::PhysicalServerSocket, ConfigSocketServerT >, SocketContextFactoryT >
using SocketConnection = typename SocketAcceptor::SocketConnection
using SocketAddress = typename SocketAcceptor::SocketAddress
Public Types inherited from core::socket::LogicalSocket< SocketAcceptorT::Config >
using Config = SocketAcceptorT::Config
Protected Attributes inherited from core::socket::stream::SocketServer< SocketAcceptorT< net::in6::stream::PhysicalServerSocket, ConfigSocketServerT >, SocketContextFactoryT >
std::function< void(SocketConnection *)> onConnect
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
Protected Attributes inherited from core::socket::LogicalSocket< SocketAcceptorT::Config >
std::shared_ptr< Config > config
Detailed Description
template<template< typename PhysicalServerSocket, typename ConfigSocketServer > typename SocketAcceptorT, typename ConfigSocketServerT, typename SocketContextFactoryT>
class net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >
Definition at line 38 of file SocketServer.h.
Member Typedef Documentation
Super
template<template< typename PhysicalServerSocket, typename ConfigSocketServer > typename SocketAcceptorT, typename ConfigSocketServerT , typename SocketContextFactoryT > using net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::Super = core::socket::stream::SocketServer<SocketAcceptorT<net::in6::stream::PhysicalServerSocket, ConfigSocketServerT>, SocketContextFactoryT> private
Definition at line 42 of file SocketServer.h.
Member Function Documentation
listen() [1/4]
template<template< typename PhysicalServerSocket, typename ConfigSocketServer > typename SocketAcceptorT, typename ConfigSocketServerT , typename SocketContextFactoryT > void net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::listen (const std::string & ipOrHostname, uint16_t port, const std::function< void(const core::ProgressLog &)> & onError) const inline
Definition at line 62 of file SocketServer.h.
{
            Super::getConfig().Local::setHost(ipOrHostname).setPort(port);
            listen(onError);
        }
References core::socket::LogicalSocket< SocketAcceptorT::Config >::getConfig(), and net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::listen().
listen() [2/4]
template<template< typename PhysicalServerSocket, typename ConfigSocketServer > typename SocketAcceptorT, typename ConfigSocketServerT , typename SocketContextFactoryT > void net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::listen (const std::string & ipOrHostname, uint16_t port, int backlog, const std::function< void(const core::ProgressLog &)> & onError) const inline
Definition at line 68 of file SocketServer.h.
{
            Super::getConfig().Local::setHost(ipOrHostname).setPort(port);
            Super::getConfig().setBacklog(backlog);
            listen(onError);
        }
References core::socket::LogicalSocket< SocketAcceptorT::Config >::getConfig(), and net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::listen().
listen() [3/4]
template<template< typename PhysicalServerSocket, typename ConfigSocketServer > typename SocketAcceptorT, typename ConfigSocketServerT , typename SocketContextFactoryT > void net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::listen (uint16_t port, const std::function< void(const core::ProgressLog &)> & onError) const inline
Definition at line 50 of file SocketServer.h.
{
            Super::getConfig().Local::setPort(port);
            listen(onError);
        }
References core::socket::LogicalSocket< SocketAcceptorT::Config >::getConfig(), and net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::listen().
Referenced by net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::listen(), net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::listen(), net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::listen(), and net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::listen().
listen() [4/4]
template<template< typename PhysicalServerSocket, typename ConfigSocketServer > typename SocketAcceptorT, typename ConfigSocketServerT , typename SocketContextFactoryT > void net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::listen (uint16_t port, int backlog, const std::function< void(const core::ProgressLog &)> & onError) const inline
Definition at line 55 of file SocketServer.h.
{
            Super::getConfig().Local::setPort(port);
            Super::getConfig().setBacklog(backlog);
            listen(onError);
        }
References core::socket::LogicalSocket< SocketAcceptorT::Config >::getConfig(), and net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT >::listen().
The documentation for this class was generated from the following file:
net/in6/stream/SocketServer.h