SNode.C: net::in::stream::tls::config::ConfigSocketServer Class Reference
net::in::stream::tls::config::ConfigSocketServer Class Reference final
#include <ConfigSocketServer.h>
Public Types
enum class Role { SERVER , CLIENT }
Public Member Functions
ConfigSocketServer (const std::string &name)
~ConfigSocketServer () override
SSL_CTX * getSslCtx ()
SSL_CTX * getSniCtx (const std::string &serverNameIndication)
Role getRole ()
const std::string & getInstanceName () const
void setInstanceName (const std::string &instanceName)
bool getDisabled () const
void setDisabled (bool disabled=true)
CLI::App * add_section (const std::string &name, const std::string &description)
void required (CLI::App *section, bool req=true)
void required (CLI::Option *opt, bool req=true)
bool required () const
bool getRequired () const
bool hasSection (const std::string &name) const
CLI::App * getSection (const std::string &name) const
ConfigTlsServer & setForceSni (bool forceSni=true)
bool getForceSni () const
ConfigTlsServer & addSniCerts (const std::map< std::string, std::map< std::string, std::variant< std::string, bool, ssl_option_t > > > &sniCerts)
ConfigTlsServer & addSniCert (const std::string &domain, const std::map< std::string, std::variant< std::string, bool, ssl_option_t > > &sniCert)
std::map< std::string, std::map< std::string, std::variant< std::string, bool, ssl_option_t > > > & getSniCerts ()
ConfigTls & setInitTimeout (const utils::Timeval &newInitTimeout)
utils::Timeval getInitTimeout () const
ConfigTls & setShutdownTimeout (const utils::Timeval &newShutdownTimeout)
utils::Timeval getShutdownTimeout () const
ConfigTls & setCertChain (const std::string &newCertChain)
std::string getCertChain () const
ConfigTls & setCertKey (const std::string &newCertKey)
std::string getCertKey () const
ConfigTls & setCertKeyPassword (const std::string &newCertKeyPassword)
std::string getCertKeyPassword () const
ConfigTls & setCaCertFile (const std::string &newCaCertFile)
std::string getCaCertFile () const
ConfigTls & setCaCertDir (const std::string &newCaCertDir)
std::string getCaCertDir () const
ConfigTls & setUseDefaultCaCertDir (bool set=true)
bool getUseDefaultCaCertDir () const
ConfigTls & setCipherList (const std::string &newCipherList)
std::string getCipherList () const
ConfigTls & setSslTlsOptions (ssl_option_t newSslTlsOptions)
ssl_option_t getSslTlsOptions () const
Protected Member Functions
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Protected Attributes
CLI::App * section = nullptr
Static Private Member Functions
static int clientHelloCallback (SSL *ssl, int *al, void *arg)
Private Attributes
SSL_CTX * sslCtx = nullptr
std::list< SSL_CTX * > sniCtxs
std::map< std::string, SSL_CTX * > sniCtxMap
uint8_t requiredCount = 0
std::string instanceName
Role role
CLI::App * instanceSc = nullptr
CLI::Option * disableOpt = nullptr
std::map< std::string, std::map< std::string, std::variant< std::string, bool, ssl_option_t > > > sniCerts
CLI::Option * sniCertsOpt = nullptr
CLI::Option * forceSniOpt = nullptr
CLI::Option * certChainOpt = nullptr
CLI::Option * certKeyOpt = nullptr
CLI::Option * certKeyPasswordOpt = nullptr
CLI::Option * caCertFileOpt = nullptr
CLI::Option * caCertDirOpt = nullptr
CLI::Option * useDefaultCaCertDirOpt = nullptr
CLI::Option * cipherListOpt = nullptr
CLI::Option * tlsOptionsOpt = nullptr
CLI::Option * initTimeoutOpt = nullptr
CLI::Option * shutdownTimeoutOpt = nullptr
ConfigInstance * instance = nullptr
Static Private Attributes
static const std::string nameAnonymous = "<anonymous>"
Detailed Description
Definition at line 34 of file ConfigSocketServer.h.
Member Enumeration Documentation
Role
enum class net::config::ConfigInstance::Role strong inherited
Enumerator
SERVER
CLIENT
Definition at line 39 of file ConfigInstance.h.
{ SERVER, CLIENT };
Constructor & Destructor Documentation
ConfigSocketServer()
net::in::stream::tls::config::ConfigSocketServer::ConfigSocketServer (const std::string & name) explicit
Definition at line 30 of file ConfigSocketServer.cpp.
        : net::config::stream::tls::ConfigSocketServer<net::in::stream::config::ConfigSocketServer>(name) {
    }
References net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::ConfigSocketServer().
~ConfigSocketServer()
net::in::stream::tls::config::ConfigSocketServer::~ConfigSocketServer () override
Definition at line 34 of file ConfigSocketServer.cpp.
{
    }
Member Function Documentation
add_flag() [1/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) inherited
Definition at line 111 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag(name, description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [2/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) inherited
Definition at line 126 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [3/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 67 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [4/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 74 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [5/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) inherited
add_flag() [6/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) inherited
Referenced by web::http::client::ConfigHTTP::ConfigHTTP(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag_function() [1/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) inherited
Definition at line 135 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [2/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) inherited
Definition at line 156 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), and net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient().
add_option() [1/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) inherited
Definition at line 80 of file ConfigSection.cpp.
{
        if (!instance->getInstanceName().empty() && !section->get_display_name().empty()) {
            section->disabled(false);
        }
        opt = section //
                  ->add_option(name, description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigInstance::getInstanceName(), net::config::ConfigSection::instance, and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [2/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) inherited
Definition at line 96 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [3/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) inherited
Definition at line 101 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [4/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 49 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [5/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 56 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [6/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) inherited
Referenced by net::config::ConfigTls::ConfigTls().
add_option() [7/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
add_section()
CLI::App * net::config::ConfigInstance::add_section (const std::string & name, const std::string & description) inherited
Definition at line 98 of file ConfigInstance.cpp.
{
        CLI::App* sectionSc = instanceSc //
                                  ->add_subcommand(name, description)
                                  ->fallthrough()
                                  ->configurable(false)
                                  ->allow_extras(false)
                                  ->group("Sections")
                                  ->disabled(this->instanceName.empty() || name.empty());
        sectionSc //
            ->option_defaults()
            ->configurable(!sectionSc->get_disabled());
        if (!sectionSc->get_disabled()) {
            utils::Config::add_standard_flags(sectionSc);
            utils::Config::add_help_flag(sectionSc);
        }
        return sectionSc;
    }
References utils::Config::add_help_flag(), utils::Config::add_standard_flags(), net::config::ConfigInstance::instanceName, and net::config::ConfigInstance::instanceSc.
Referenced by net::config::ConfigSection::ConfigSection().
addSniCert()
ConfigTlsServer & net::config::ConfigTlsServer::addSniCert (const std::string & domain, const std::map< std::string, std::variant< std::string, bool, ssl_option_t > > & sniCert) inherited
Definition at line 139 of file ConfigTlsServer.cpp.
{
        this->sniCerts[domain] = sniCert;
        sniCertsOpt->capture_default_str();
        return *this;
    }
References net::config::ConfigTlsServer::sniCerts, and net::config::ConfigTlsServer::sniCertsOpt.
addSniCerts()
ConfigTlsServer & net::config::ConfigTlsServer::addSniCerts (const std::map< std::string, std::map< std::string, std::variant< std::string, bool, ssl_option_t > > > & sniCerts) inherited
Definition at line 130 of file ConfigTlsServer.cpp.
{
        this->sniCerts.insert(sniCerts.begin(), sniCerts.end());
        sniCertsOpt->capture_default_str();
        return *this;
    }
References net::config::ConfigTlsServer::sniCerts, and net::config::ConfigTlsServer::sniCertsOpt.
clientHelloCallback()
template<typename ConfigSocketServerBase > int net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBase >::clientHelloCallback (SSL * ssl, int * al, void * arg) static private inherited
Definition at line 161 of file ConfigSocketServer.hpp.
{
        int ret = SSL_CLIENT_HELLO_SUCCESS;
        ConfigSocketServer* config = static_cast<ConfigSocketServer*>(arg);
        std::string serverNameIndication = core::socket::stream::tls::ssl_get_servername_from_client_hello(ssl);
        if (!serverNameIndication.empty()) {
            SSL_CTX* sniSslCtx = config->getSniCtx(serverNameIndication);
            if (sniSslCtx != nullptr) {
                LOG(TRACE) << config->getInstanceName() << " SSL/TLS: Setting sni certificate for '" << serverNameIndication << "'";
                core::socket::stream::tls::ssl_set_ssl_ctx(ssl, sniSslCtx);
            } else if (config->getForceSni()) {
                LOG(TRACE) << config->getInstanceName() << " SSL/TLS: No sni certificate found for '" << serverNameIndication
                           << "' but forceSni set - terminating";
                ret = SSL_CLIENT_HELLO_ERROR;
                *al = SSL_AD_UNRECOGNIZED_NAME;
            } else {
                LOG(TRACE) << config->getInstanceName() << " SSL/TLS: No sni certificate found for '" << serverNameIndication
                           << "' still using master certificate";
            }
        } else {
            LOG(TRACE) << config->getInstanceName() << " SSL/TLS: No sni certificate set - the client did not request one";
        }
        return ret;
    }
References core::socket::stream::tls::ssl_get_servername_from_client_hello(), and core::socket::stream::tls::ssl_set_ssl_ctx().
Referenced by net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getCaCertDir()
std::string net::config::ConfigTls::getCaCertDir () const inherited
Definition at line 155 of file ConfigTls.cpp.
{
        return caCertDirOpt->as<std::string>();
    }
References net::config::ConfigTls::caCertDirOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getCaCertFile()
std::string net::config::ConfigTls::getCaCertFile () const inherited
Definition at line 143 of file ConfigTls.cpp.
{
        return caCertFileOpt->as<std::string>();
    }
References net::config::ConfigTls::caCertFileOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getCertChain()
std::string net::config::ConfigTls::getCertChain () const inherited
Definition at line 107 of file ConfigTls.cpp.
{
        return certChainOpt->as<std::string>();
    }
References net::config::ConfigTls::certChainOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getCertKey()
std::string net::config::ConfigTls::getCertKey () const inherited
Definition at line 119 of file ConfigTls.cpp.
{
        return certKeyOpt->as<std::string>();
    }
References net::config::ConfigTls::certKeyOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getCertKeyPassword()
std::string net::config::ConfigTls::getCertKeyPassword () const inherited
Definition at line 131 of file ConfigTls.cpp.
{
        return certKeyPasswordOpt->as<std::string>();
    }
References net::config::ConfigTls::certKeyPasswordOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getCipherList()
std::string net::config::ConfigTls::getCipherList () const inherited
Definition at line 179 of file ConfigTls.cpp.
{
        return cipherListOpt->as<std::string>();
    }
References net::config::ConfigTls::cipherListOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getDisabled()
bool net::config::ConfigInstance::getDisabled () const inherited
Definition at line 157 of file ConfigInstance.cpp.
{
        return disableOpt //
            ->as<bool>();
    }
References net::config::ConfigInstance::disableOpt.
getForceSni()
bool net::config::ConfigTlsServer::getForceSni () const inherited
Definition at line 126 of file ConfigTlsServer.cpp.
{
        return forceSniOpt->as<bool>();
    }
References net::config::ConfigTlsServer::forceSniOpt.
getInitTimeout()
utils::Timeval net::config::ConfigTls::getInitTimeout () const inherited
Definition at line 203 of file ConfigTls.cpp.
{
        return initTimeoutOpt->as<utils::Timeval>();
    }
References net::config::ConfigTls::initTimeoutOpt.
getInstanceName()
const std::string & net::config::ConfigInstance::getInstanceName () const inherited
Definition at line 90 of file ConfigInstance.cpp.
{
        return instanceName.empty() ? nameAnonymous : instanceName;
    }
References net::config::ConfigInstance::instanceName, and net::config::ConfigInstance::nameAnonymous.
Referenced by net::config::ConfigSection::add_option(), net::un::config::ConfigAddress< ConfigAddressTypeT >::ConfigAddress(), net::config::ConfigSection::ConfigSection(), net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSniCtx(), net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getRequired()
bool net::config::ConfigInstance::getRequired () const inherited
Definition at line 137 of file ConfigInstance.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigInstance::requiredCount.
getRole()
ConfigInstance::Role net::config::ConfigInstance::getRole () inherited
Definition at line 86 of file ConfigInstance.cpp.
{
        return role;
    }
References net::config::ConfigInstance::role.
getSection()
CLI::App * net::config::ConfigInstance::getSection (const std::string & name) const inherited
Definition at line 153 of file ConfigInstance.cpp.
{
        return hasSection(name) ? instanceSc->get_subcommand(name) : nullptr;
    }
References net::config::ConfigInstance::hasSection(), and net::config::ConfigInstance::instanceSc.
Referenced by net::config::ConfigSection::ConfigSection().
getShutdownTimeout()
utils::Timeval net::config::ConfigTls::getShutdownTimeout () const inherited
Definition at line 215 of file ConfigTls.cpp.
{
        return shutdownTimeoutOpt //
            ->as<utils::Timeval>();
    }
References net::config::ConfigTls::shutdownTimeoutOpt.
getSniCerts()
std::map< std::string, std::map< std::string, std::variant< std::string, bool, ssl_option_t > > > & net::config::ConfigTlsServer::getSniCerts () inherited
Definition at line 148 of file ConfigTlsServer.cpp.
{
        return sniCerts;
    }
References net::config::ConfigTlsServer::sniCerts.
Referenced by net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSniCtx().
getSniCtx()
template<typename ConfigSocketServerBase > SSL_CTX * net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBase >::getSniCtx (const std::string & serverNameIndication) inherited
Definition at line 80 of file ConfigSocketServer.hpp.
{
        SSL_CTX* sniCtx = nullptr;
        if (sniCtxMap.empty()) {
            std::map<std::string, SSL_CTX*> sslSans = core::socket::stream::tls::ssl_get_sans(sslCtx);
            sniCtxMap.insert(sslSans.begin(), sslSans.end());
            for (const auto& [sni, ctx] : sniCtxMap) {
                LOG(TRACE) << getInstanceName() << " SSL/TLS: SSL_CTX (E) sni for '" << sni << "' from master certificate installed";
            }
            for (const auto& [domain, sniCertConf] : getSniCerts()) {
                if (!domain.empty()) {
                    core::socket::stream::tls::SslConfig sslConfig(true);
                    sslConfig.instanceName = getInstanceName();
                    for (const auto& [key, value] : sniCertConf) {
                        if (key == "CertChain") {
                            sslConfig.certChain = std::get<std::string>(value);
                        } else if (key == "CertKey") {
                            sslConfig.certChainKey = std::get<std::string>(value);
                        } else if (key == "CertKeyPassword") {
                            sslConfig.password = std::get<std::string>(value);
                        } else if (key == "CaCertFile") {
                            sslConfig.caFile = std::get<std::string>(value);
                        } else if (key == "CaCertDir") {
                            sslConfig.caDir = std::get<std::string>(value);
                        } else if (key == "UseDefaultCaDir") {
                            sslConfig.useDefaultCaDir = std::get<bool>(value);
                        } else if (key == "CipherList") {
                            sslConfig.cipherList = std::get<std::string>(value);
                        } else if (key == "SslOptions") {
                            sslConfig.sslOptions = std::get<ssl_option_t>(value);
                        }
                    }
                    SSL_CTX* newCtx = core::socket::stream::tls::ssl_ctx_new(sslConfig);
                    if (newCtx != nullptr) {
                        sniCtxs.push_back(newCtx);
                        sniCtxMap.insert({domain, newCtx});
                        LOG(TRACE) << getInstanceName() << " SSL/TLS: SSL_CTX (E) sni for '" << domain << "' explicitly installed";
                        for (const auto& [san, ctx] : core::socket::stream::tls::ssl_get_sans(newCtx)) {
                            sniCtxMap.insert({san, ctx});
                            LOG(TRACE) << getInstanceName() << " SSL/TLS: SSL_CTX (S) sni for '" << san << "' from SAN installed";
                        }
                    } else {
                        LOG(TRACE) << getInstanceName() << " SSL/TLS: Can not create SNI_SSL_CTX for domain '" << domain << "'";
                    }
                }
            }
            LOG(TRACE) << getInstanceName() << " SSL/TLS: SNI list result:";
            for (const auto& [sni, ctx] : sniCtxMap) {
                LOG(TRACE) << "  SNI: " << sni;
            }
        }
        LOG(TRACE) << getInstanceName() << " SSL/TLS: Lookup for sni='" << serverNameIndication << "' in sni certificates";
        std::map<std::string, SSL_CTX*>::iterator sniPairIt = std::find_if(
            sniCtxMap.begin(), sniCtxMap.end(), [&serverNameIndication, this](const std::pair<std::string, SSL_CTX*>& sniPair) -> bool {
                LOG(TRACE) << getInstanceName() << " SSL/TLS:  .. " << sniPair.first.c_str();
                return core::socket::stream::tls::match(sniPair.first.c_str(), serverNameIndication.c_str());
            });
        if (sniPairIt != sniCtxMap.end()) {
            LOG(TRACE) << getInstanceName() << " SSL/TLS: found '" << sniPairIt->first << "'";
            sniCtx = sniPairIt->second;
        } else {
            LOG(TRACE) << getInstanceName() << " SSL/TLS: not found";
        }
        return sniCtx;
    }
References core::socket::stream::tls::SslConfig::caDir, core::socket::stream::tls::SslConfig::caFile, core::socket::stream::tls::SslConfig::certChain, core::socket::stream::tls::SslConfig::certChainKey, core::socket::stream::tls::SslConfig::cipherList, net::config::ConfigInstance::getInstanceName(), net::config::ConfigTlsServer::getSniCerts(), core::socket::stream::tls::SslConfig::instanceName, core::socket::stream::tls::match(), core::socket::stream::tls::SslConfig::password, net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::sniCtxMap, net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::sniCtxs, core::socket::stream::tls::ssl_ctx_new(), core::socket::stream::tls::ssl_get_sans(), core::socket::stream::tls::SslConfig::SslConfig(), net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::sslCtx, core::socket::stream::tls::SslConfig::sslOptions, and core::socket::stream::tls::SslConfig::useDefaultCaDir.
getSslCtx()
template<typename ConfigSocketServerBase > SSL_CTX * net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBase >::getSslCtx () inherited
Definition at line 54 of file ConfigSocketServer.hpp.
{
        if (sslCtx == nullptr) {
            core::socket::stream::tls::SslConfig sslConfig(true);
            sslConfig.instanceName = getInstanceName();
            sslConfig.certChain = getCertChain();
            sslConfig.certChainKey = getCertKey();
            sslConfig.caDir = getCaCertDir();
            sslConfig.caFile = getCaCertFile();
            sslConfig.cipherList = getCipherList();
            sslConfig.password = getCertKeyPassword();
            sslConfig.sslOptions = getSslTlsOptions();
            sslConfig.useDefaultCaDir = getUseDefaultCaCertDir();
            sslCtx = core::socket::stream::tls::ssl_ctx_new(sslConfig);
            if (sslCtx != nullptr) {
                SSL_CTX_set_client_hello_cb(sslCtx, clientHelloCallback, this);
            }
        }
        return sslCtx;
    }
References core::socket::stream::tls::SslConfig::caDir, core::socket::stream::tls::SslConfig::caFile, core::socket::stream::tls::SslConfig::certChain, core::socket::stream::tls::SslConfig::certChainKey, core::socket::stream::tls::SslConfig::cipherList, net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::clientHelloCallback(), net::config::ConfigTls::getCaCertDir(), net::config::ConfigTls::getCaCertFile(), net::config::ConfigTls::getCertChain(), net::config::ConfigTls::getCertKey(), net::config::ConfigTls::getCertKeyPassword(), net::config::ConfigTls::getCipherList(), net::config::ConfigInstance::getInstanceName(), net::config::ConfigTls::getSslTlsOptions(), net::config::ConfigTls::getUseDefaultCaCertDir(), core::socket::stream::tls::SslConfig::instanceName, core::socket::stream::tls::SslConfig::password, core::socket::stream::tls::ssl_ctx_new(), core::socket::stream::tls::SslConfig::SslConfig(), net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::sslCtx, core::socket::stream::tls::SslConfig::sslOptions, and core::socket::stream::tls::SslConfig::useDefaultCaDir.
getSslTlsOptions()
ssl_option_t net::config::ConfigTls::getSslTlsOptions () const inherited
Definition at line 191 of file ConfigTls.cpp.
{
        return tlsOptionsOpt->as<ssl_option_t>();
    }
References net::config::ConfigTls::tlsOptionsOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getUseDefaultCaCertDir()
bool net::config::ConfigTls::getUseDefaultCaCertDir () const inherited
Definition at line 167 of file ConfigTls.cpp.
{
        return useDefaultCaCertDirOpt->as<bool>();
    }
References net::config::ConfigTls::useDefaultCaCertDirOpt.
Referenced by net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
hasSection()
bool net::config::ConfigInstance::hasSection (const std::string & name) const inherited
Definition at line 141 of file ConfigInstance.cpp.
{
        CLI::App* sectionSc = nullptr;
        try {
            sectionSc = instanceSc->get_subcommand(name);
        } catch (CLI::OptionNotFound&) {
            sectionSc = nullptr;
        }
        return sectionSc != nullptr;
    }
References net::config::ConfigInstance::instanceSc.
Referenced by net::config::ConfigSection::ConfigSection(), and net::config::ConfigInstance::getSection().
required() [1/3]
bool net::config::ConfigSection::required () const inherited
Definition at line 76 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [2/3]
void net::config::ConfigInstance::required (CLI::App * section, bool req = true) inherited
Definition at line 119 of file ConfigInstance.cpp.
{
        if (req != section->get_required()) {
            if (req) {
                ++requiredCount;
                instanceSc->needs(section);
            } else {
                --requiredCount;
                instanceSc->remove_needs(section);
            }
            section->required(req);
            if (!disableOpt->as<bool>()) {
                utils::Config::required(instanceSc, requiredCount > 0);
            }
        }
    }
References net::config::ConfigInstance::disableOpt, net::config::ConfigInstance::instanceSc, utils::Config::required(), and net::config::ConfigInstance::requiredCount.
Referenced by net::config::ConfigSection::required().
required() [3/3]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) inherited
Definition at line 59 of file ConfigSection.cpp.
{
        if (req != opt->get_required()) {
            if (req) {
                ++requiredCount;
                section->needs(opt);
                opt->default_str("");
            } else {
                --requiredCount;
                section->remove_needs(opt);
            }
            opt->required(req);
            instance->required(section, requiredCount > 0);
        }
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
setCaCertDir()
ConfigTls & net::config::ConfigTls::setCaCertDir (const std::string & newCaCertDir) inherited
Definition at line 147 of file ConfigTls.cpp.
{
        caCertDirOpt //
            ->default_val(newCaCertDir)
            ->clear();
        return *this;
    }
References net::config::ConfigTls::caCertDirOpt.
setCaCertFile()
ConfigTls & net::config::ConfigTls::setCaCertFile (const std::string & newCaCertFile) inherited
Definition at line 135 of file ConfigTls.cpp.
{
        caCertFileOpt //
            ->default_val(newCaCertFile)
            ->clear();
        return *this;
    }
References net::config::ConfigTls::caCertFileOpt.
setCertChain()
ConfigTls & net::config::ConfigTls::setCertChain (const std::string & newCertChain) inherited
Definition at line 99 of file ConfigTls.cpp.
{
        certChainOpt //
            ->default_val(newCertChain)
            ->clear();
        return *this;
    }
References net::config::ConfigTls::certChainOpt.
setCertKey()
ConfigTls & net::config::ConfigTls::setCertKey (const std::string & newCertKey) inherited
Definition at line 111 of file ConfigTls.cpp.
{
        certKeyOpt //
            ->default_val(newCertKey)
            ->clear();
        return *this;
    }
References net::config::ConfigTls::certKeyOpt.
setCertKeyPassword()
ConfigTls & net::config::ConfigTls::setCertKeyPassword (const std::string & newCertKeyPassword) inherited
Definition at line 123 of file ConfigTls.cpp.
{
        certKeyPasswordOpt //
            ->default_val(newCertKeyPassword)
            ->clear();
        return *this;
    }
References net::config::ConfigTls::certKeyPasswordOpt.
setCipherList()
ConfigTls & net::config::ConfigTls::setCipherList (const std::string & newCipherList) inherited
Definition at line 171 of file ConfigTls.cpp.
{
        cipherListOpt //
            ->default_val(newCipherList)
            ->clear();
        return *this;
    }
References net::config::ConfigTls::cipherListOpt.
setDisabled()
void net::config::ConfigInstance::setDisabled (bool disabled = true) inherited
Definition at line 162 of file ConfigInstance.cpp.
{
        disableOpt //
            ->default_val(disabled ? "true" : "false")
            ->clear();
        utils::Config::disabled(instanceSc, disabled);
    }
References utils::Config::disabled(), net::config::ConfigInstance::disableOpt, and net::config::ConfigInstance::instanceSc.
setForceSni()
ConfigTlsServer & net::config::ConfigTlsServer::setForceSni (bool forceSni = true) inherited
Definition at line 118 of file ConfigTlsServer.cpp.
{
        forceSniOpt //
            ->default_val(forceSni ? "true" : "false")
            ->clear();
        return *this;
    }
References net::config::ConfigTlsServer::forceSniOpt.
setInitTimeout()
ConfigTls & net::config::ConfigTls::setInitTimeout (const utils::Timeval & newInitTimeout) inherited
Definition at line 195 of file ConfigTls.cpp.
{
        initTimeoutOpt //
            ->default_val(newInitTimeout)
            ->clear();
        return *this;
    }
References net::config::ConfigTls::initTimeoutOpt.
setInstanceName()
void net::config::ConfigInstance::setInstanceName (const std::string & instanceName) inherited
Definition at line 94 of file ConfigInstance.cpp.
{
        this->instanceName = instanceName;
    }
References net::config::ConfigInstance::instanceName.
setShutdownTimeout()
ConfigTls & net::config::ConfigTls::setShutdownTimeout (const utils::Timeval & newShutdownTimeout) inherited
Definition at line 207 of file ConfigTls.cpp.
{
        shutdownTimeoutOpt //
            ->default_val(newShutdownTimeout)
            ->clear();
        return *this;
    }
References net::config::ConfigTls::shutdownTimeoutOpt.
setSslTlsOptions()
ConfigTls & net::config::ConfigTls::setSslTlsOptions (ssl_option_t newSslTlsOptions) inherited
Definition at line 183 of file ConfigTls.cpp.
{
        tlsOptionsOpt //
            ->default_val(newSslTlsOptions)
            ->clear();
        return *this;
    }
References net::config::ConfigTls::tlsOptionsOpt.
setUseDefaultCaCertDir()
ConfigTls & net::config::ConfigTls::setUseDefaultCaCertDir (bool set = true) inherited
Definition at line 159 of file ConfigTls.cpp.
{
        useDefaultCaCertDirOpt //
            ->default_val(set ? "true" : "false")
            ->clear();
        return *this;
    }
References net::config::ConfigTls::useDefaultCaCertDirOpt.
Member Data Documentation
caCertDirOpt
CLI::Option* net::config::ConfigTls::caCertDirOpt = nullptr private inherited
Definition at line 84 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCaCertDir(), and net::config::ConfigTls::setCaCertDir().
caCertFileOpt
CLI::Option* net::config::ConfigTls::caCertFileOpt = nullptr private inherited
Definition at line 83 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCaCertFile(), and net::config::ConfigTls::setCaCertFile().
certChainOpt
CLI::Option* net::config::ConfigTls::certChainOpt = nullptr private inherited
Definition at line 80 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCertChain(), and net::config::ConfigTls::setCertChain().
certKeyOpt
CLI::Option* net::config::ConfigTls::certKeyOpt = nullptr private inherited
Definition at line 81 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCertKey(), and net::config::ConfigTls::setCertKey().
certKeyPasswordOpt
CLI::Option* net::config::ConfigTls::certKeyPasswordOpt = nullptr private inherited
Definition at line 82 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCertKeyPassword(), and net::config::ConfigTls::setCertKeyPassword().
cipherListOpt
CLI::Option* net::config::ConfigTls::cipherListOpt = nullptr private inherited
Definition at line 86 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCipherList(), and net::config::ConfigTls::setCipherList().
disableOpt
CLI::Option* net::config::ConfigInstance::disableOpt = nullptr private inherited
Definition at line 76 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::ConfigInstance(), net::config::ConfigInstance::getDisabled(), net::config::ConfigInstance::required(), and net::config::ConfigInstance::setDisabled().
forceSniOpt
CLI::Option* net::config::ConfigTlsServer::forceSniOpt = nullptr private inherited
Definition at line 60 of file ConfigTlsServer.h.
Referenced by net::config::ConfigTlsServer::ConfigTlsServer(), net::config::ConfigTlsServer::getForceSni(), and net::config::ConfigTlsServer::setForceSni().
initTimeoutOpt
CLI::Option* net::config::ConfigTls::initTimeoutOpt = nullptr private inherited
Definition at line 88 of file ConfigTls.h.
Referenced by net::config::ConfigTls::getInitTimeout(), and net::config::ConfigTls::setInitTimeout().
instance
ConfigInstance* net::config::ConfigSection::instance = nullptr private inherited
Definition at line 120 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), and net::config::ConfigSection::required().
instanceName
std::string net::config::ConfigInstance::instanceName private inherited
Definition at line 70 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::add_section(), net::config::ConfigInstance::ConfigInstance(), net::config::ConfigInstance::getInstanceName(), and net::config::ConfigInstance::setInstanceName().
instanceSc
CLI::App* net::config::ConfigInstance::instanceSc = nullptr private inherited
Definition at line 75 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::add_section(), net::config::ConfigInstance::ConfigInstance(), net::config::ConfigInstance::getSection(), net::config::ConfigInstance::hasSection(), net::config::ConfigInstance::required(), net::config::ConfigInstance::setDisabled(), and net::config::ConfigInstance::~ConfigInstance().
nameAnonymous
const std::string net::config::ConfigInstance::nameAnonymous = "<anonymous>" static private inherited
Definition at line 71 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::getInstanceName().
requiredCount
uint8_t net::config::ConfigInstance::requiredCount = 0 private inherited
Definition at line 68 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::getRequired(), and net::config::ConfigInstance::required().
role
Role net::config::ConfigInstance::role private inherited
Definition at line 73 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::ConfigInstance(), and net::config::ConfigInstance::getRole().
section
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 125 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
shutdownTimeoutOpt
CLI::Option* net::config::ConfigTls::shutdownTimeoutOpt = nullptr private inherited
Definition at line 89 of file ConfigTls.h.
Referenced by net::config::ConfigTls::getShutdownTimeout(), and net::config::ConfigTls::setShutdownTimeout().
sniCerts
std::map<std::string, std::map<std::string, std::variant<std::string, bool, ssl_option_t> > > net::config::ConfigTlsServer::sniCerts private inherited
Definition at line 57 of file ConfigTlsServer.h.
Referenced by net::config::ConfigTlsServer::addSniCert(), net::config::ConfigTlsServer::addSniCerts(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigTlsServer::getSniCerts().
sniCertsOpt
CLI::Option* net::config::ConfigTlsServer::sniCertsOpt = nullptr private inherited
Definition at line 59 of file ConfigTlsServer.h.
Referenced by net::config::ConfigTlsServer::addSniCert(), net::config::ConfigTlsServer::addSniCerts(), and net::config::ConfigTlsServer::ConfigTlsServer().
sniCtxMap
template<typename ConfigSocketServerBaseT > std::map<std::string, SSL_CTX*> net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::sniCtxMap private inherited
Definition at line 53 of file ConfigSocketServer.h.
Referenced by net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSniCtx().
sniCtxs
template<typename ConfigSocketServerBaseT > std::list<SSL_CTX*> net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::sniCtxs private inherited
Definition at line 52 of file ConfigSocketServer.h.
Referenced by net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSniCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::~ConfigSocketServer().
sslCtx
template<typename ConfigSocketServerBaseT > SSL_CTX* net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::sslCtx = nullptr private inherited
Definition at line 51 of file ConfigSocketServer.h.
Referenced by net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSniCtx(), net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::~ConfigSocketServer().
tlsOptionsOpt
CLI::Option* net::config::ConfigTls::tlsOptionsOpt = nullptr private inherited
Definition at line 87 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getSslTlsOptions(), and net::config::ConfigTls::setSslTlsOptions().
useDefaultCaCertDirOpt
CLI::Option* net::config::ConfigTls::useDefaultCaCertDirOpt = nullptr private inherited
Definition at line 85 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getUseDefaultCaCertDir(), and net::config::ConfigTls::setUseDefaultCaCertDir().
The documentation for this class was generated from the following files:
net/in/stream/tls/config/ConfigSocketServer.h
net/in/stream/tls/config/ConfigSocketServer.cpp