SNode.C: database::mariadb::commands::sync::MariaDBAffectedRowsCommand Class Reference
database::mariadb::commands::sync::MariaDBAffectedRowsCommand Class Reference
#include <MariaDBAffectedRowsCommand.h>
Public Member Functions
MariaDBAffectedRowsCommand (const std::function< void(my_ulonglong)> &onAffectedRows, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommand (const std::string &name, const std::function< void(const std::string &, unsigned int)> &onError)
const std::string & commandName ()
int commandStart (MYSQL *mysql, const utils::Timeval &currentTime)
void setMariaDBConnection (MariaDBConnection *mariaDBConnection)
virtual std::string commandInfo ()
Protected Attributes
MYSQL * mysql = nullptr
const std::function< void(const std::string &, unsigned int)> onError
Private Member Functions
int commandStart () override
bool commandCompleted () override
void commandError (const std::string &errorString, unsigned int errorNumber) override
int commandContinue (int status) final
Private Attributes
my_ulonglong affectedRows = 0
const std::function< void(my_ulonglong)> onAffectedRows
std::string name
MariaDBConnection * mariaDBConnection = nullptr
utils::Timeval startTime = 0
Detailed Description
Definition at line 32 of file MariaDBAffectedRowsCommand.h.
Constructor & Destructor Documentation
MariaDBAffectedRowsCommand()
database::mariadb::commands::sync::MariaDBAffectedRowsCommand::MariaDBAffectedRowsCommand (const std::function< void(my_ulonglong)> & onAffectedRows, const std::function< void(const std::string &, unsigned int)> & onError)
Definition at line 29 of file MariaDBAffectedRowsCommand.cpp.
        : MariaDBCommandSync("AffectedRows", onError)
        , onAffectedRows(onAffectedRows) {
    }
References MariaDBAffectedRowsCommand().
Referenced by MariaDBAffectedRowsCommand().
Member Function Documentation
commandCompleted()
bool database::mariadb::commands::sync::MariaDBAffectedRowsCommand::commandCompleted () override private virtual
Implements database::mariadb::MariaDBCommand.
Definition at line 41 of file MariaDBAffectedRowsCommand.cpp.
{
        onAffectedRows(affectedRows);
        return true;
    }
commandContinue()
int database::mariadb::MariaDBCommandSync::commandContinue (int status) final private virtual inherited
Implements database::mariadb::MariaDBCommand.
Definition at line 29 of file MariaDBCommandSync.cpp.
{
        return 0;
    }
commandError()
void database::mariadb::commands::sync::MariaDBAffectedRowsCommand::commandError (const std::string & errorString, unsigned int errorNumber) override private virtual
Implements database::mariadb::MariaDBCommand.
Definition at line 47 of file MariaDBAffectedRowsCommand.cpp.
{
        onError(errorString, errorNumber);
    }
commandInfo()
std::string database::mariadb::MariaDBCommand::commandInfo () virtual inherited
Reimplemented in database::mariadb::commands::async::MariaDBAutoCommitCommand, database::mariadb::commands::async::MariaDBConnectCommand, database::mariadb::commands::async::MariaDBExecCommand, and database::mariadb::commands::async::MariaDBQueryCommand.
Definition at line 45 of file MariaDBCommand.cpp.
{
        return commandName();
    }
Referenced by database::mariadb::MariaDBConnection::commandCompleted(), and database::mariadb::MariaDBConnection::commandStart().
commandName()
const std::string & database::mariadb::MariaDBCommand::commandName () inherited
Definition at line 49 of file MariaDBCommand.cpp.
{
        return name;
    }
References database::mariadb::MariaDBCommand::name.
Referenced by database::mariadb::commands::async::MariaDBConnectCommand::commandInfo(), database::mariadb::commands::async::MariaDBExecCommand::commandInfo(), and database::mariadb::commands::async::MariaDBQueryCommand::commandInfo().
commandStart() [1/2]
int database::mariadb::commands::sync::MariaDBAffectedRowsCommand::commandStart () override private virtual
Implements database::mariadb::MariaDBCommand.
Definition at line 35 of file MariaDBAffectedRowsCommand.cpp.
{
        affectedRows = mysql_affected_rows(mysql);
        return 0;
    }
commandStart() [2/2]
int database::mariadb::MariaDBCommand::commandStart (MYSQL * mysql, const utils::Timeval & currentTime) inherited
Definition at line 34 of file MariaDBCommand.cpp.
{
        this->mysql = mysql;
        startTime = currentTime;
        return commandStart();
    }
References database::mariadb::MariaDBCommand::commandStart(), utils::Timeval::operator=(), and database::mariadb::MariaDBCommand::startTime.
MariaDBCommand()
database::mariadb::MariaDBCommand::MariaDBCommand (const std::string & name, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 46 of file MariaDBCommand.cpp.
        : name(name)
        , onError(onError) {
    }
setMariaDBConnection()
void database::mariadb::MariaDBCommand::setMariaDBConnection (MariaDBConnection * mariaDBConnection) inherited
Definition at line 41 of file MariaDBCommand.cpp.
{
        this->mariaDBConnection = mariaDBConnection;
    }
References database::mariadb::MariaDBCommand::mariaDBConnection.
Referenced by database::mariadb::MariaDBConnection::commandStart().
Member Data Documentation
affectedRows
my_ulonglong database::mariadb::commands::sync::MariaDBAffectedRowsCommand::affectedRows = 0 private
Definition at line 42 of file MariaDBAffectedRowsCommand.h.
mariaDBConnection
MariaDBConnection* database::mariadb::MariaDBCommand::mariaDBConnection = nullptr private inherited
Definition at line 67 of file MariaDBCommand.h.
Referenced by database::mariadb::MariaDBCommand::setMariaDBConnection().
mysql
MYSQL* database::mariadb::MariaDBCommand::mysql = nullptr protected inherited
Definition at line 70 of file MariaDBCommand.h.
name
std::string database::mariadb::MariaDBCommand::name private inherited
Definition at line 65 of file MariaDBCommand.h.
Referenced by database::mariadb::MariaDBCommand::commandName(), and database::mariadb::MariaDBCommand::MariaDBCommand().
onAffectedRows
const std::function<void(my_ulonglong)> database::mariadb::commands::sync::MariaDBAffectedRowsCommand::onAffectedRows private
Definition at line 44 of file MariaDBAffectedRowsCommand.h.
onError
const std::function<void(const std::string&, unsigned int)> database::mariadb::MariaDBCommand::onError protected inherited
Definition at line 72 of file MariaDBCommand.h.
startTime
utils::Timeval database::mariadb::MariaDBCommand::startTime = 0 private inherited
Definition at line 75 of file MariaDBCommand.h.
Referenced by database::mariadb::MariaDBCommand::commandStart().
The documentation for this class was generated from the following files:
database/mariadb/commands/sync/MariaDBAffectedRowsCommand.h
database/mariadb/commands/sync/MariaDBAffectedRowsCommand.cpp