SNode.C: iot::mqtt_fast::types::Int_V Class Reference
iot::mqtt_fast::types::Int_V Class Reference
#include <Int_V.h>
Public Member Functions
Int_V (core::socket::SocketContext *socketContext=nullptr)
std::size_t construct () override
uint32_t getValue () const
void reset () override
bool isComplete () const
bool isError () const
Protected Member Functions
std::size_t read (char *buf, std::size_t count)
Protected Attributes
core::socket::SocketContext * socketContext
bool completed = false
bool error = false
Private Attributes
std::size_t multiplier = 1
std::uint32_t value = 0
Detailed Description
Definition at line 38 of file Int_V.h.
Constructor & Destructor Documentation
Int_V()
iot::mqtt_fast::types::Int_V::Int_V (core::socket::SocketContext * socketContext = nullptr) explicit
Definition at line 28 of file Int_V.cpp.
        : iot::mqtt_fast::types::TypeBase(socketContext) {
    }
References iot::mqtt_fast::types::TypeBase::TypeBase().
Referenced by iot::mqtt_fast::ControlPacketFactory::ControlPacketFactory().
Member Function Documentation
construct()
std::size_t iot::mqtt_fast::types::Int_V::construct () override virtual
Implements iot::mqtt_fast::types::TypeBase.
Definition at line 32 of file Int_V.cpp.
{
        std::size_t consumed = 0;
        std::size_t ret = 0;
        do {
            char byte = 0;
            ret = read(&byte, 1);
            if (ret > 0) {
                value += static_cast<uint32_t>((byte & 0x7F) * multiplier);
                if (multiplier > 0x80 * 0x80 * 0x80) {
                    error = true;
                } else {
                    multiplier *= 0x80;
                    completed = (byte & 0x80) == 0;
                }
                consumed += ret;
            }
        } while (ret > 0 && !completed && !error);
        return consumed;
    }
References iot::mqtt_fast::types::TypeBase::completed, iot::mqtt_fast::types::TypeBase::error, multiplier, iot::mqtt_fast::types::TypeBase::read(), and value.
Referenced by iot::mqtt_fast::ControlPacketFactory::construct().
getValue()
uint32_t iot::mqtt_fast::types::Int_V::getValue () const
Definition at line 55 of file Int_V.cpp.
{
        return value;
    }
References value.
Referenced by iot::mqtt_fast::ControlPacketFactory::construct().
isComplete()
bool iot::mqtt_fast::types::TypeBase::isComplete () const inherited
Definition at line 34 of file TypeBase.cpp.
{
        return completed;
    }
References iot::mqtt_fast::types::TypeBase::completed.
Referenced by iot::mqtt_fast::ControlPacketFactory::construct().
isError()
bool iot::mqtt_fast::types::TypeBase::isError () const inherited
Definition at line 38 of file TypeBase.cpp.
{
        return error;
    }
References iot::mqtt_fast::types::TypeBase::error.
Referenced by iot::mqtt_fast::ControlPacketFactory::construct(), and iot::mqtt_fast::ControlPacket::isError().
read()
std::size_t iot::mqtt_fast::types::TypeBase::read (char * buf, std::size_t count) protected inherited
Definition at line 42 of file TypeBase.cpp.
{
        std::size_t ret = 0;
        ret = socketContext->readFromPeer(buf, count);
        return ret;
    }
References core::socket::SocketContext::readFromPeer(), and iot::mqtt_fast::types::TypeBase::socketContext.
Referenced by iot::mqtt_fast::types::Binary::construct(), iot::mqtt_fast::types::Int_1::construct(), and construct().
reset()
void iot::mqtt_fast::types::Int_V::reset () override virtual
Reimplemented from iot::mqtt_fast::types::TypeBase.
Definition at line 59 of file Int_V.cpp.
                      {
        multiplier = 1;
        value = 0;
        iot::mqtt_fast::types::TypeBase::reset();
    }
References multiplier, iot::mqtt_fast::types::TypeBase::reset(), and value.
Referenced by iot::mqtt_fast::ControlPacketFactory::reset().
Member Data Documentation
completed
bool iot::mqtt_fast::types::TypeBase::completed = false protected inherited
Definition at line 58 of file TypeBase.h.
Referenced by iot::mqtt_fast::types::Binary::construct(), iot::mqtt_fast::types::Int_1::construct(), construct(), iot::mqtt_fast::types::Binary::getIntV(), iot::mqtt_fast::types::TypeBase::isComplete(), and iot::mqtt_fast::types::TypeBase::reset().
error
bool iot::mqtt_fast::types::TypeBase::error = false protected inherited
Definition at line 59 of file TypeBase.h.
Referenced by construct(), iot::mqtt_fast::types::Binary::getInt16(), iot::mqtt_fast::types::Binary::getInt32(), iot::mqtt_fast::types::Binary::getInt64(), iot::mqtt_fast::types::Binary::getInt8(), iot::mqtt_fast::types::Binary::getIntV(), iot::mqtt_fast::types::Binary::getString(), iot::mqtt_fast::types::Binary::getStringRaw(), iot::mqtt_fast::types::Binary::getUint8ListRaw(), iot::mqtt_fast::types::TypeBase::isError(), and iot::mqtt_fast::types::TypeBase::reset().
multiplier
std::size_t iot::mqtt_fast::types::Int_V::multiplier = 1 private
Definition at line 49 of file Int_V.h.
Referenced by construct(), and reset().
socketContext
core::socket::SocketContext* iot::mqtt_fast::types::TypeBase::socketContext protected inherited
Definition at line 56 of file TypeBase.h.
Referenced by iot::mqtt_fast::types::TypeBase::read(), and iot::mqtt_fast::types::TypeBase::TypeBase().
value
std::uint32_t iot::mqtt_fast::types::Int_V::value = 0 private
Definition at line 50 of file Int_V.h.
Referenced by construct(), getValue(), and reset().
The documentation for this class was generated from the following files:
iot/mqtt-fast/types/Int_V.h
iot/mqtt-fast/types/Int_V.cpp