SNode.C: core::socket::stream::tls::TLSHandshake Class Reference
core::socket::stream::tls::TLSHandshake Class Reference
#include <TLSHandshake.h>
Static Public Member Functions
static void doHandshake (const std::string &instanceName, SSL *ssl, const std::function< void(void)> &onSuccess, const std::function< void(void)> &onTimeout, const std::function< void(int)> &onStatus, const utils::Timeval &timeout)
Static Public Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Private Member Functions
TLSHandshake (const std::string &instanceName, SSL *ssl, const std::function< void(void)> &onSuccess, const std::function< void(void)> &onTimeout, const std::function< void(int)> &onStatus, const utils::Timeval &timeout)
void readEvent () final
void writeEvent () final
void signalEvent (int signum) final
void readTimeout () final
void writeTimeout () final
void unobservedEvent () final
Private Attributes
SSL * ssl = nullptr
std::function< void(void)> onSuccess
std::function< void(void)> onTimeout
std::function< void(int)> onStatus
bool timeoutTriggered
int fd = -1
Additional Inherited Members
Public Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
int getRegisteredFd () const
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Member Functions inherited from core::eventreceiver::ReadEventReceiver
ReadEventReceiver (const std::string &name, const utils::Timeval &timeout)
Protected Member Functions inherited from core::DescriptorEventReceiver
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
Protected Member Functions inherited from core::Observer
void observed ()
void unObserved ()
Observer ()=default
Observer (Observer &)=delete
Observer (Observer &&)=delete
virtual ~Observer ()
Protected Member Functions inherited from core::EventReceiver
virtual ~EventReceiver ()=default
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Member Functions inherited from core::eventreceiver::WriteEventReceiver
WriteEventReceiver (const std::string &name, const utils::Timeval &timeout)
Static Protected Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Detailed Description
Definition at line 46 of file TLSHandshake.h.
Constructor & Destructor Documentation
TLSHandshake()
core::socket::stream::tls::TLSHandshake::TLSHandshake (const std::string & instanceName, SSL * ssl, const std::function< void(void)> & onSuccess, const std::function< void(void)> & onTimeout, const std::function< void(int)> & onStatus, const utils::Timeval & timeout) private
Definition at line 39 of file TLSHandshake.cpp.
        : ReadEventReceiver(instanceName + " SSL/TLS: Handshake", timeout)
        , WriteEventReceiver(instanceName + " SSL/TLS: Handshake", timeout)
        , ssl(ssl)
        , onSuccess(onSuccess)
        , onTimeout(onTimeout)
        , onStatus(onStatus)
        , timeoutTriggered(false)
        , fd(SSL_get_fd(ssl)) {
        const int ret = SSL_do_handshake(ssl);
        int sslErr = SSL_ERROR_NONE;
        if (ret < 1) {
            sslErr = SSL_get_error(ssl, ret);
        }
        if (!ReadEventReceiver::enable(fd)) {
            delete this;
        } else if (!WriteEventReceiver::enable(fd)) {
            ReadEventReceiver::disable();
        } else {
            ReadEventReceiver::suspend();
            WriteEventReceiver::suspend();
            switch (sslErr) {
                case SSL_ERROR_WANT_READ:
                    ReadEventReceiver::resume();
                    break;
                case SSL_ERROR_WANT_WRITE:
                    WriteEventReceiver::resume();
                    break;
                case SSL_ERROR_NONE:
                case SSL_ERROR_ZERO_RETURN:
                    ReadEventReceiver::disable();
                    WriteEventReceiver::disable();
                    onSuccess();
                    break;
                default:
                    ReadEventReceiver::disable();
                    WriteEventReceiver::disable();
                    onStatus(sslErr);
                    break;
            }
        }
    }
References core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), fd, core::DescriptorEventReceiver::resume(), ssl, core::DescriptorEventReceiver::suspend(), timeoutTriggered, and TLSHandshake().
Referenced by doHandshake(), and TLSHandshake().
Member Function Documentation
doHandshake()
void core::socket::stream::tls::TLSHandshake::doHandshake (const std::string & instanceName, SSL * ssl, const std::function< void(void)> & onSuccess, const std::function< void(void)> & onTimeout, const std::function< void(int)> & onStatus, const utils::Timeval & timeout) static
Definition at line 30 of file TLSHandshake.cpp.
{
        new TLSHandshake(instanceName, ssl, onSuccess, onTimeout, onStatus, timeout);
    }
References TLSHandshake().
readEvent()
void core::socket::stream::tls::TLSHandshake::readEvent () final private virtual
Implements core::eventreceiver::ReadEventReceiver.
Definition at line 90 of file TLSHandshake.cpp.
{
        const int ret = SSL_do_handshake(ssl);
        int sslErr = SSL_ERROR_NONE;
        if (ret < 1) {
            sslErr = SSL_get_error(ssl, ret);
        }
        switch (sslErr) {
            case SSL_ERROR_WANT_READ:
                break;
            case SSL_ERROR_WANT_WRITE:
                ReadEventReceiver::suspend();
                WriteEventReceiver::resume();
                break;
            case SSL_ERROR_NONE:
            case SSL_ERROR_ZERO_RETURN:
                ReadEventReceiver::disable();
                WriteEventReceiver::disable();
                onSuccess();
                break;
            default:
                ReadEventReceiver::disable();
                WriteEventReceiver::disable();
                onStatus(sslErr);
                break;
        }
    }
References core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::resume(), ssl, and core::DescriptorEventReceiver::suspend().
readTimeout()
void core::socket::stream::tls::TLSHandshake::readTimeout () final private virtual
Reimplemented from core::eventreceiver::ReadEventReceiver.
Definition at line 148 of file TLSHandshake.cpp.
{
        if (!timeoutTriggered) {
            timeoutTriggered = true;
            ReadEventReceiver::disable();
            WriteEventReceiver::disable();
            onTimeout();
        }
    }
References core::DescriptorEventReceiver::disable(), and timeoutTriggered.
signalEvent()
void core::socket::stream::tls::TLSHandshake::signalEvent (int signum) final private virtual
Reimplemented from core::eventreceiver::ReadEventReceiver.
Definition at line 166 of file TLSHandshake.cpp.
                                                              { // Do nothing on signal event
    }
unobservedEvent()
void core::socket::stream::tls::TLSHandshake::unobservedEvent () final private virtual
Implements core::Observer.
Definition at line 169 of file TLSHandshake.cpp.
{
        delete this;
    }
writeEvent()
void core::socket::stream::tls::TLSHandshake::writeEvent () final private virtual
Implements core::eventreceiver::WriteEventReceiver.
Definition at line 119 of file TLSHandshake.cpp.
{
        const int ret = SSL_do_handshake(ssl);
        int sslErr = SSL_ERROR_NONE;
        if (ret < 1) {
            sslErr = SSL_get_error(ssl, ret);
        }
        switch (sslErr) {
            case SSL_ERROR_WANT_READ:
                WriteEventReceiver::suspend();
                ReadEventReceiver::resume();
                break;
            case SSL_ERROR_WANT_WRITE:
                break;
            case SSL_ERROR_NONE:
            case SSL_ERROR_ZERO_RETURN:
                ReadEventReceiver::disable();
                WriteEventReceiver::disable();
                onSuccess();
                break;
            default:
                ReadEventReceiver::disable();
                WriteEventReceiver::disable();
                onStatus(sslErr);
                break;
        }
    }
References core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::resume(), ssl, and core::DescriptorEventReceiver::suspend().
writeTimeout()
void core::socket::stream::tls::TLSHandshake::writeTimeout () final private virtual
Reimplemented from core::eventreceiver::WriteEventReceiver.
Definition at line 157 of file TLSHandshake.cpp.
{
        if (!timeoutTriggered) {
            timeoutTriggered = true;
            ReadEventReceiver::disable();
            WriteEventReceiver::disable();
            onTimeout();
        }
    }
References core::DescriptorEventReceiver::disable(), and timeoutTriggered.
Member Data Documentation
fd
int core::socket::stream::tls::TLSHandshake::fd = -1 private
Definition at line 81 of file TLSHandshake.h.
Referenced by TLSHandshake().
onStatus
std::function<void(int)> core::socket::stream::tls::TLSHandshake::onStatus private
Definition at line 77 of file TLSHandshake.h.
onSuccess
std::function<void(void)> core::socket::stream::tls::TLSHandshake::onSuccess private
Definition at line 75 of file TLSHandshake.h.
onTimeout
std::function<void(void)> core::socket::stream::tls::TLSHandshake::onTimeout private
Definition at line 76 of file TLSHandshake.h.
ssl
SSL* core::socket::stream::tls::TLSHandshake::ssl = nullptr private
Definition at line 74 of file TLSHandshake.h.
Referenced by readEvent(), TLSHandshake(), and writeEvent().
timeoutTriggered
bool core::socket::stream::tls::TLSHandshake::timeoutTriggered private
Definition at line 79 of file TLSHandshake.h.
Referenced by readTimeout(), TLSHandshake(), and writeTimeout().
The documentation for this class was generated from the following files:
src/core/socket/stream/tls/TLSHandshake.h
src/core/socket/stream/tls/TLSHandshake.cpp