SNode.C: ExtrasError Class Reference
ExtrasError Class Reference
Errors
Thrown when too many positionals or options are found.
#include <CLI11.hpp>
Public Member Functions
ExtrasError (std::string msg, ExitCodes exit_code)
ExtrasError (std::string msg, int exit_code)
ExtrasError (std::vector< std::string > args)
ExtrasError (const std::string &name, std::vector< std::string > args)
Public Member Functions inherited from ParseError
ParseError (std::string msg, ExitCodes exit_code)
ParseError (std::string msg, int exit_code)
Public Member Functions inherited from Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Protected Member Functions
ExtrasError (std::string ename, std::string msg, int exit_code)
ExtrasError (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from ParseError
ParseError (std::string ename, std::string msg, int exit_code)
ParseError (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
Thrown when too many positionals or options are found.
Definition at line 1311 of file CLI11.hpp.
Constructor & Destructor Documentation
ExtrasError() [1/6]
ExtrasError::ExtrasError (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 1312 of file CLI11.hpp.
ExtrasError() [2/6]
ExtrasError::ExtrasError (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 1312 of file CLI11.hpp.
ExtrasError() [3/6]
ExtrasError::ExtrasError (std::string msg, ExitCodes exit_code) inline
Definition at line 1312 of file CLI11.hpp.
ExtrasError() [4/6]
ExtrasError::ExtrasError (std::string msg, int exit_code) inline
Definition at line 1312 of file CLI11.hpp.
ExtrasError() [5/6]
ExtrasError::ExtrasError (std::vector< std::string > args) inline explicit
Definition at line 1313 of file CLI11.hpp.
            : ExtrasError((args.size() > 1 ? "The following arguments were not expected: " : "The following argument was not expected: ") +
                              detail::rjoin(args, " "),
                          ExitCodes::ExtrasError) {
        }
References ExtrasError().
Referenced by ExtrasError().
ExtrasError() [6/6]
ExtrasError::ExtrasError (const std::string & name, std::vector< std::string > args) inline
Definition at line 1318 of file CLI11.hpp.
            : ExtrasError(name,
                          (args.size() > 1 ? "The following arguments were not expected: " : "The following argument was not expected: ") +
                              detail::rjoin(args, " "),
                          ExitCodes::ExtrasError) {
        }
References ExtrasError().
Referenced by ExtrasError().
The documentation for this class was generated from the following file:
src/utils/CLI11.hpp