SNode.C: express::dispatcher::ScopedParams Class Reference
express::dispatcher::ScopedParams Class Reference
#include <regex_utils.h>
Public Member Functions
ScopedParams (express::Request &req, const std::map< std::string, std::string > &params, bool mergeWithParent)
~ScopedParams ()
ScopedParams (const ScopedParams &)=delete
ScopedParams & operator= (const ScopedParams &)=delete
ScopedParams (ScopedParams &&)=delete
ScopedParams & operator= (ScopedParams &&)=delete
Private Attributes
express::Request * req_ {nullptr}
std::map< std::string, std::string > backup_
Detailed Description
Definition at line 121 of file regex_utils.h.
Constructor & Destructor Documentation
ScopedParams() [1/3]
express::dispatcher::ScopedParams::ScopedParams (express::Request & req, const std::map< std::string, std::string > & params, bool mergeWithParent)
Definition at line 780 of file regex_utils.cpp.
        : req_(&req)
        , backup_(req.params) {
        req.params.clear();
        if (mergeWithParent) {
            for (const auto& [k, v] : backup_) {
                req.params[k] = v;
            }
        }
        for (const auto& [k, v] : params) {
            req.params[k] = v;
        }
    }
References backup_, express::Request::params, and req_.
Referenced by express::dispatcher::ApplicationDispatcher::dispatch(), express::dispatcher::MiddlewareDispatcher::dispatch(), and express::dispatcher::RouterDispatcher::dispatch().
~ScopedParams()
express::dispatcher::ScopedParams::~ScopedParams ()
Definition at line 795 of file regex_utils.cpp.
{
        if (req_ != nullptr) {
            req_->params = std::move(backup_);
        }
    }
References backup_, express::Request::params, and req_.
ScopedParams() [2/3]
express::dispatcher::ScopedParams::ScopedParams (const ScopedParams &) delete
ScopedParams() [3/3]
express::dispatcher::ScopedParams::ScopedParams (ScopedParams &&) delete
Member Function Documentation
operator=() [1/2]
ScopedParams & express::dispatcher::ScopedParams::operator= (const ScopedParams &) delete
operator=() [2/2]
ScopedParams & express::dispatcher::ScopedParams::operator= (ScopedParams &&) delete
Member Data Documentation
backup_
std::map<std::string, std::string> express::dispatcher::ScopedParams::backup_ private
Definition at line 133 of file regex_utils.h.
Referenced by ScopedParams(), and ~ScopedParams().
req_
express::Request* express::dispatcher::ScopedParams::req_ {nullptr} private
Definition at line 132 of file regex_utils.h.
{nullptr};
Referenced by ScopedParams(), and ~ScopedParams().
The documentation for this class was generated from the following files:
express/dispatcher/regex_utils.h
express/dispatcher/regex_utils.cpp