SNode.C: iot::mqtt::packets::Pubrec Class Reference
iot::mqtt::packets::Pubrec Class Reference
#include <Pubrec.h>
Public Member Functions
Pubrec ()
Pubrec (const uint16_t packetIdentifier)
uint16_t getPacketIdentifier () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type)
ControlPacket (const ControlPacket &)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
std::vector< char > serialize () const
uint8_t getType () const
uint8_t getFlags () const
Protected Attributes
iot::mqtt::types::UInt16 packetIdentifier
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t type = 0
uint8_t flags = 0
Private Member Functions
std::vector< char > serializeVP () const override
Detailed Description
Definition at line 31 of file Pubrec.h.
Constructor & Destructor Documentation
Pubrec() [1/2]
iot::mqtt::packets::Pubrec::Pubrec ()
Definition at line 27 of file Pubrec.cpp.
        : iot::mqtt::ControlPacket(MQTT_PUBREC) {
    }
References iot::mqtt::ControlPacket::ControlPacket().
Referenced by Pubrec().
Pubrec() [2/2]
iot::mqtt::packets::Pubrec::Pubrec (const uint16_t packetIdentifier) explicit
Definition at line 31 of file Pubrec.cpp.
        : Pubrec() {
        this->packetIdentifier = packetIdentifier;
    }
References iot::mqtt::types::UInt16::operator=(), packetIdentifier, and Pubrec().
Referenced by iot::mqtt::Mqtt::sendPubrec().
Member Function Documentation
getPacketIdentifier()
uint16_t iot::mqtt::packets::Pubrec::getPacketIdentifier () const
Definition at line 40 of file Pubrec.cpp.
{
        return packetIdentifier;
    }
References packetIdentifier.
Referenced by iot::mqtt::Mqtt::_onPubrec().
serializeVP()
std::vector< char > iot::mqtt::packets::Pubrec::serializeVP () const override private virtual
Implements iot::mqtt::ControlPacket.
Definition at line 36 of file Pubrec.cpp.
{
        return std::vector<char>(packetIdentifier.serialize());
    }
References packetIdentifier, and iot::mqtt::types::TypeBase< ValueTypeT >::serialize().
Member Data Documentation
packetIdentifier
iot::mqtt::types::UInt16 iot::mqtt::packets::Pubrec::packetIdentifier protected
Definition at line 43 of file Pubrec.h.
Referenced by iot::mqtt::client::packets::Pubrec::deserializeVP(), iot::mqtt::server::packets::Pubrec::deserializeVP(), getPacketIdentifier(), Pubrec(), and serializeVP().
The documentation for this class was generated from the following files:
iot/mqtt/packets/Pubrec.h
iot/mqtt/packets/Pubrec.cpp