SNode.C: core::DescriptorEventPublisher Class Reference
core::DescriptorEventPublisher Class Reference abstract
#include <DescriptorEventPublisher.h>
Public Member Functions
DescriptorEventPublisher ()=delete
virtual ~DescriptorEventPublisher ()
DescriptorEventPublisher (const DescriptorEventPublisher &)=delete
DescriptorEventPublisher & operator= (const DescriptorEventPublisher &)=delete
void enable (DescriptorEventReceiver *descriptorEventReceiver)
void disable (DescriptorEventReceiver *descriptorEventReceiver)
void suspend (DescriptorEventReceiver *descriptorEventReceiver)
void resume (DescriptorEventReceiver *descriptorEventReceiver)
virtual void spanActiveEvents ()=0
void checkTimedOutEvents (const utils::Timeval &currentTime)
void releaseDisabledEvents (const utils::Timeval &currentTime)
int getObservedEventReceiverCount () const
int maxFd () const
utils::Timeval getNextTimeout (const utils::Timeval &currentTime) const
void signal (int sigNum)
void disable ()
const std::string & getName () const
Protected Member Functions
DescriptorEventPublisher (std::string name)
virtual void muxAdd (DescriptorEventReceiver *descriptorEventReceiver)=0
virtual void muxDel (int fd)=0
virtual void muxOn (DescriptorEventReceiver *descriptorEventReceiver)=0
virtual void muxOff (DescriptorEventReceiver *descriptorEventReceiver)=0
Protected Attributes
unsigned long eventCounter = 0
std::map< int, std::list< DescriptorEventReceiver * > > observedEventReceivers
Private Attributes
bool observedEventReceiversDirty = false
std::string name
Detailed Description
Definition at line 41 of file DescriptorEventPublisher.h.
Constructor & Destructor Documentation
DescriptorEventPublisher() [1/3]
core::DescriptorEventPublisher::DescriptorEventPublisher (std::string name) protected
Definition at line 36 of file DescriptorEventPublisher.cpp.
        : name(std::move(name)) {
    }
References name.
Referenced by core::poll::DescriptorEventPublisher::DescriptorEventPublisher(), core::select::DescriptorEventPublisher::DescriptorEventPublisher(), and core::epoll::DescriptorEventPublisher::DescriptorEventPublisher().
DescriptorEventPublisher() [2/3]
core::DescriptorEventPublisher::DescriptorEventPublisher () delete
~DescriptorEventPublisher()
core::DescriptorEventPublisher::~DescriptorEventPublisher () virtual
Definition at line 40 of file DescriptorEventPublisher.cpp.
{
    }
DescriptorEventPublisher() [3/3]
core::DescriptorEventPublisher::DescriptorEventPublisher (const DescriptorEventPublisher &) delete
Member Function Documentation
checkTimedOutEvents()
void core::DescriptorEventPublisher::checkTimedOutEvents (const utils::Timeval & currentTime)
Definition at line 65 of file DescriptorEventPublisher.cpp.
{
        for (auto& [fd, eventReceivers] : observedEventReceivers) {
            eventReceivers.front()->checkTimeout(currentTime);
        }
    }
References core::DescriptorEventReceiver::checkTimeout(), and observedEventReceivers.
Referenced by core::EventMultiplexer::checkTimedOutEvents().
disable() [1/2]
void core::DescriptorEventPublisher::disable ()
Definition at line 139 of file DescriptorEventPublisher.cpp.
{
        for (auto& [fd, eventReceivers] : observedEventReceivers) {
            for (DescriptorEventReceiver* eventReceiver : eventReceivers) {
                eventReceiver->disable();
            }
        }
    }
References core::DescriptorEventReceiver::disable(), and observedEventReceivers.
Referenced by core::EventMultiplexer::terminate().
disable() [2/2]
void core::DescriptorEventPublisher::disable (DescriptorEventReceiver * descriptorEventReceiver)
Definition at line 53 of file DescriptorEventPublisher.cpp.
{
        observedEventReceiversDirty = true;
    }
References observedEventReceiversDirty.
Referenced by core::DescriptorEventReceiver::disable().
enable()
void core::DescriptorEventPublisher::enable (DescriptorEventReceiver * descriptorEventReceiver)
Definition at line 43 of file DescriptorEventPublisher.cpp.
{
        const int fd = descriptorEventReceiver->getRegisteredFd();
        observedEventReceivers[fd].push_front(descriptorEventReceiver);
        muxAdd(descriptorEventReceiver);
        if (descriptorEventReceiver->isSuspended()) {
            muxOff(descriptorEventReceiver);
        }
        descriptorEventReceiver->setEnabled(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::isSuspended(), muxAdd(), muxOff(), observedEventReceivers, and core::DescriptorEventReceiver::setEnabled().
Referenced by core::DescriptorEventReceiver::enable().
getName()
const std::string & core::DescriptorEventPublisher::getName () const
Definition at line 147 of file DescriptorEventPublisher.cpp.
{
        return name;
    }
References name.
getNextTimeout()
utils::Timeval core::DescriptorEventPublisher::getNextTimeout (const utils::Timeval & currentTime) const
Definition at line 117 of file DescriptorEventPublisher.cpp.
{
        utils::Timeval nextTimeout = DescriptorEventReceiver::TIMEOUT::MAX;
        if (!observedEventReceiversDirty) {
            for (const auto& [fd, eventReceivers] : observedEventReceivers) {
                nextTimeout = std::min(eventReceivers.front()->getTimeout(currentTime), nextTimeout);
            }
        } else {
            nextTimeout = 0;
        }
        return nextTimeout;
    }
References core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::TIMEOUT::MAX, observedEventReceivers, observedEventReceiversDirty, and utils::Timeval::operator=().
Referenced by core::EventMultiplexer::getNextTimeout().
getObservedEventReceiverCount()
int core::DescriptorEventPublisher::getObservedEventReceiverCount () const
Definition at line 103 of file DescriptorEventPublisher.cpp.
{
        return static_cast<int>(observedEventReceivers.size());
    }
References observedEventReceivers.
Referenced by core::EventMultiplexer::observedEventReceiverCount().
maxFd()
int core::DescriptorEventPublisher::maxFd () const
Definition at line 107 of file DescriptorEventPublisher.cpp.
{
        int maxFd = -1;
        if (!observedEventReceivers.empty()) {
            maxFd = observedEventReceivers.rbegin()->first;
        }
        return maxFd;
    }
References observedEventReceivers.
Referenced by core::EventMultiplexer::maxFd().
muxAdd()
virtual void core::DescriptorEventPublisher::muxAdd (DescriptorEventReceiver * descriptorEventReceiver) protected pure virtual
Implemented in core::epoll::DescriptorEventPublisher, core::poll::DescriptorEventPublisher, and core::select::DescriptorEventPublisher.
Referenced by enable().
muxDel()
virtual void core::DescriptorEventPublisher::muxDel (int fd) protected pure virtual
Implemented in core::epoll::DescriptorEventPublisher, core::poll::DescriptorEventPublisher, and core::select::DescriptorEventPublisher.
Referenced by releaseDisabledEvents().
muxOff()
virtual void core::DescriptorEventPublisher::muxOff (DescriptorEventReceiver * descriptorEventReceiver) protected pure virtual
Implemented in core::epoll::DescriptorEventPublisher, core::poll::DescriptorEventPublisher, and core::select::DescriptorEventPublisher.
Referenced by enable(), releaseDisabledEvents(), and suspend().
muxOn()
virtual void core::DescriptorEventPublisher::muxOn (DescriptorEventReceiver * descriptorEventReceiver) protected pure virtual
Implemented in core::epoll::DescriptorEventPublisher, core::poll::DescriptorEventPublisher, and core::select::DescriptorEventPublisher.
Referenced by releaseDisabledEvents(), and resume().
operator=()
DescriptorEventPublisher & core::DescriptorEventPublisher::operator= (const DescriptorEventPublisher &) delete
releaseDisabledEvents()
void core::DescriptorEventPublisher::releaseDisabledEvents (const utils::Timeval & currentTime)
Definition at line 71 of file DescriptorEventPublisher.cpp.
{
        if (observedEventReceiversDirty) {
            observedEventReceiversDirty = false;
            for (auto& [fd, observedEventReceiverList] : observedEventReceivers) {
                if (std::erase_if(observedEventReceiverList, [](DescriptorEventReceiver* descriptorEventReceiver) -> bool {
                        const bool isDisabled = !descriptorEventReceiver->isEnabled();
                        if (isDisabled) {
                            descriptorEventReceiver->setDisabled();
                        }
                        return isDisabled;
                    }) > 0) {
                    if (observedEventReceiverList.empty()) {
                        muxDel(fd);
                    } else {
                        DescriptorEventReceiver* activeDescriptorEventReceiver = observedEventReceiverList.front();
                        activeDescriptorEventReceiver->triggered(currentTime);
                        if (!activeDescriptorEventReceiver->isSuspended()) {
                            muxOn(activeDescriptorEventReceiver);
                        } else {
                            muxOff(activeDescriptorEventReceiver);
                        }
                    }
                }
            }
            std::erase_if(observedEventReceivers, [](const auto& observedEventReceiversEntry) -> bool {
                return observedEventReceiversEntry.second.empty();
            });
        }
    }
References core::DescriptorEventReceiver::isSuspended(), muxDel(), muxOff(), muxOn(), observedEventReceivers, observedEventReceiversDirty, and core::DescriptorEventReceiver::triggered().
Referenced by core::EventMultiplexer::releaseExpiredResources().
resume()
void core::DescriptorEventPublisher::resume (DescriptorEventReceiver * descriptorEventReceiver)
Definition at line 61 of file DescriptorEventPublisher.cpp.
{
        muxOn(descriptorEventReceiver);
    }
References muxOn().
Referenced by core::DescriptorEventReceiver::resume().
signal()
void core::DescriptorEventPublisher::signal (int sigNum)
Definition at line 131 of file DescriptorEventPublisher.cpp.
{
        for (auto& [fd, eventReceivers] : observedEventReceivers) {
            for (DescriptorEventReceiver* eventReceiver : eventReceivers) {
                eventReceiver->onSignal(sigNum);
            }
        }
    }
References observedEventReceivers, and core::DescriptorEventReceiver::onSignal().
Referenced by core::EventMultiplexer::signal().
spanActiveEvents()
virtual void core::DescriptorEventPublisher::spanActiveEvents () pure virtual
Implemented in core::epoll::DescriptorEventPublisher, core::poll::DescriptorEventPublisher, and core::select::DescriptorEventPublisher.
Referenced by core::epoll::EventMultiplexer::spanActiveEvents(), core::poll::EventMultiplexer::spanActiveEvents(), and core::select::EventMultiplexer::spanActiveEvents().
suspend()
void core::DescriptorEventPublisher::suspend (DescriptorEventReceiver * descriptorEventReceiver)
Definition at line 57 of file DescriptorEventPublisher.cpp.
{
        muxOff(descriptorEventReceiver);
    }
References muxOff().
Referenced by core::DescriptorEventReceiver::suspend().
Member Data Documentation
eventCounter
unsigned long core::DescriptorEventPublisher::eventCounter = 0 protected
Definition at line 79 of file DescriptorEventPublisher.h.
Referenced by core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), and core::select::DescriptorEventPublisher::spanActiveEvents().
name
std::string core::DescriptorEventPublisher::name private
Definition at line 86 of file DescriptorEventPublisher.h.
Referenced by DescriptorEventPublisher(), and getName().
observedEventReceivers
std::map<int, std::list<DescriptorEventReceiver*> > core::DescriptorEventPublisher::observedEventReceivers protected
Definition at line 81 of file DescriptorEventPublisher.h.
Referenced by checkTimedOutEvents(), disable(), enable(), getNextTimeout(), getObservedEventReceiverCount(), maxFd(), releaseDisabledEvents(), signal(), core::poll::DescriptorEventPublisher::spanActiveEvents(), and core::select::DescriptorEventPublisher::spanActiveEvents().
observedEventReceiversDirty
bool core::DescriptorEventPublisher::observedEventReceiversDirty = false private
Definition at line 84 of file DescriptorEventPublisher.h.
Referenced by disable(), getNextTimeout(), and releaseDisabledEvents().
The documentation for this class was generated from the following files:
core/DescriptorEventPublisher.h
core/DescriptorEventPublisher.cpp