SNode.C: core::epoll::DescriptorEventPublisher Class Reference
core::epoll::DescriptorEventPublisher Class Reference
#include <DescriptorEventPublisher.h>
Classes
class EPollEvents
Public Member Functions
DescriptorEventPublisher (const std::string &name, int &epfd, uint32_t events, uint32_t revents)
void enable (DescriptorEventReceiver *descriptorEventReceiver)
void disable (DescriptorEventReceiver *descriptorEventReceiver)
void disable ()
void suspend (DescriptorEventReceiver *descriptorEventReceiver)
void resume (DescriptorEventReceiver *descriptorEventReceiver)
void checkTimedOutEvents (const utils::Timeval &currentTime)
void releaseDisabledEvents (const utils::Timeval &currentTime)
int getObservedEventReceiverCount () const
int maxFd () const
utils::Timeval getNextTimeout (const utils::Timeval &currentTime) const
void signal (int sigNum)
const std::string & getName () const
Protected Attributes
unsigned long eventCounter = 0
std::map< int, std::list< DescriptorEventReceiver * > > observedEventReceivers
Private Member Functions
void muxAdd (core::DescriptorEventReceiver *eventReceiver) override
void muxDel (int fd) override
void muxOn (core::DescriptorEventReceiver *eventReceiver) override
void muxOff (core::DescriptorEventReceiver *eventReceiver) override
void spanActiveEvents () override
Private Attributes
EPollEvents ePollEvents
uint32_t revents
bool observedEventReceiversDirty = false
std::string name
Detailed Description
Definition at line 41 of file DescriptorEventPublisher.h.
Constructor & Destructor Documentation
DescriptorEventPublisher()
core::epoll::DescriptorEventPublisher::DescriptorEventPublisher (const std::string & name, int & epfd, uint32_t events, uint32_t revents)
Definition at line 104 of file DescriptorEventPublisher.cpp.
        : core::DescriptorEventPublisher(name)
        , ePollEvents(epfd, events)
        , revents(revents) {
    }
References core::DescriptorEventPublisher::DescriptorEventPublisher(), core::epoll::DescriptorEventPublisher::EPollEvents::EPollEvents(), ePollEvents, and revents.
Referenced by core::epoll::EventMultiplexer::EventMultiplexer().
Member Function Documentation
checkTimedOutEvents()
void core::DescriptorEventPublisher::checkTimedOutEvents (const utils::Timeval & currentTime) inherited
Definition at line 65 of file DescriptorEventPublisher.cpp.
{
        for (auto& [fd, eventReceivers] : observedEventReceivers) {
            eventReceivers.front()->checkTimeout(currentTime);
        }
    }
References core::DescriptorEventReceiver::checkTimeout(), and core::DescriptorEventPublisher::observedEventReceivers.
Referenced by core::EventMultiplexer::checkTimedOutEvents().
disable() [1/2]
void core::DescriptorEventPublisher::disable () inherited
Definition at line 139 of file DescriptorEventPublisher.cpp.
{
        for (auto& [fd, eventReceivers] : observedEventReceivers) {
            for (DescriptorEventReceiver* eventReceiver : eventReceivers) {
                eventReceiver->disable();
            }
        }
    }
References core::DescriptorEventReceiver::disable(), and core::DescriptorEventPublisher::observedEventReceivers.
Referenced by core::EventMultiplexer::terminate().
disable() [2/2]
void core::DescriptorEventPublisher::disable (DescriptorEventReceiver * descriptorEventReceiver) inherited
Definition at line 53 of file DescriptorEventPublisher.cpp.
{
        observedEventReceiversDirty = true;
    }
References core::DescriptorEventPublisher::observedEventReceiversDirty.
Referenced by core::DescriptorEventReceiver::disable().
enable()
void core::DescriptorEventPublisher::enable (DescriptorEventReceiver * descriptorEventReceiver) inherited
Definition at line 43 of file DescriptorEventPublisher.cpp.
{
        const int fd = descriptorEventReceiver->getRegisteredFd();
        observedEventReceivers[fd].push_front(descriptorEventReceiver);
        muxAdd(descriptorEventReceiver);
        if (descriptorEventReceiver->isSuspended()) {
            muxOff(descriptorEventReceiver);
        }
        descriptorEventReceiver->setEnabled(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventPublisher::muxAdd(), core::DescriptorEventPublisher::muxOff(), core::DescriptorEventPublisher::observedEventReceivers, and core::DescriptorEventReceiver::setEnabled().
Referenced by core::DescriptorEventReceiver::enable().
getName()
const std::string & core::DescriptorEventPublisher::getName () const inherited
Definition at line 147 of file DescriptorEventPublisher.cpp.
{
        return name;
    }
References core::DescriptorEventPublisher::name.
getNextTimeout()
utils::Timeval core::DescriptorEventPublisher::getNextTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 117 of file DescriptorEventPublisher.cpp.
{
        utils::Timeval nextTimeout = DescriptorEventReceiver::TIMEOUT::MAX;
        if (!observedEventReceiversDirty) {
            for (const auto& [fd, eventReceivers] : observedEventReceivers) {
                nextTimeout = std::min(eventReceivers.front()->getTimeout(currentTime), nextTimeout);
            }
        } else {
            nextTimeout = 0;
        }
        return nextTimeout;
    }
References core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventPublisher::observedEventReceivers, core::DescriptorEventPublisher::observedEventReceiversDirty, and utils::Timeval::operator=().
Referenced by core::EventMultiplexer::getNextTimeout().
getObservedEventReceiverCount()
int core::DescriptorEventPublisher::getObservedEventReceiverCount () const inherited
Definition at line 103 of file DescriptorEventPublisher.cpp.
{
        return static_cast<int>(observedEventReceivers.size());
    }
References core::DescriptorEventPublisher::observedEventReceivers.
Referenced by core::EventMultiplexer::observedEventReceiverCount().
maxFd()
int core::DescriptorEventPublisher::maxFd () const inherited
Definition at line 107 of file DescriptorEventPublisher.cpp.
{
        int maxFd = -1;
        if (!observedEventReceivers.empty()) {
            maxFd = observedEventReceivers.rbegin()->first;
        }
        return maxFd;
    }
References core::DescriptorEventPublisher::observedEventReceivers.
Referenced by core::EventMultiplexer::maxFd().
muxAdd()
void core::epoll::DescriptorEventPublisher::muxAdd (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 110 of file DescriptorEventPublisher.cpp.
{
        ePollEvents.muxAdd(eventReceiver);
    }
References ePollEvents, and core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd().
muxDel()
void core::epoll::DescriptorEventPublisher::muxDel (int fd) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 114 of file DescriptorEventPublisher.cpp.
{
        ePollEvents.muxDel(fd);
    }
References ePollEvents, and core::epoll::DescriptorEventPublisher::EPollEvents::muxDel().
muxOff()
void core::epoll::DescriptorEventPublisher::muxOff (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 122 of file DescriptorEventPublisher.cpp.
{
        ePollEvents.muxOff(eventReceiver);
    }
References ePollEvents, and core::epoll::DescriptorEventPublisher::EPollEvents::muxOff().
muxOn()
void core::epoll::DescriptorEventPublisher::muxOn (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 118 of file DescriptorEventPublisher.cpp.
{
        ePollEvents.muxOn(eventReceiver);
    }
References ePollEvents, and core::epoll::DescriptorEventPublisher::EPollEvents::muxOn().
releaseDisabledEvents()
void core::DescriptorEventPublisher::releaseDisabledEvents (const utils::Timeval & currentTime) inherited
Definition at line 71 of file DescriptorEventPublisher.cpp.
{
        if (observedEventReceiversDirty) {
            observedEventReceiversDirty = false;
            for (auto& [fd, observedEventReceiverList] : observedEventReceivers) {
                if (std::erase_if(observedEventReceiverList, [](DescriptorEventReceiver* descriptorEventReceiver) -> bool {
                        const bool isDisabled = !descriptorEventReceiver->isEnabled();
                        if (isDisabled) {
                            descriptorEventReceiver->setDisabled();
                        }
                        return isDisabled;
                    }) > 0) {
                    if (observedEventReceiverList.empty()) {
                        muxDel(fd);
                    } else {
                        DescriptorEventReceiver* activeDescriptorEventReceiver = observedEventReceiverList.front();
                        activeDescriptorEventReceiver->triggered(currentTime);
                        if (!activeDescriptorEventReceiver->isSuspended()) {
                            muxOn(activeDescriptorEventReceiver);
                        } else {
                            muxOff(activeDescriptorEventReceiver);
                        }
                    }
                }
            }
            std::erase_if(observedEventReceivers, [](const auto& observedEventReceiversEntry) -> bool {
                return observedEventReceiversEntry.second.empty();
            });
        }
    }
References core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventPublisher::muxDel(), core::DescriptorEventPublisher::muxOff(), core::DescriptorEventPublisher::muxOn(), core::DescriptorEventPublisher::observedEventReceivers, core::DescriptorEventPublisher::observedEventReceiversDirty, and core::DescriptorEventReceiver::triggered().
Referenced by core::EventMultiplexer::releaseExpiredResources().
resume()
void core::DescriptorEventPublisher::resume (DescriptorEventReceiver * descriptorEventReceiver) inherited
Definition at line 61 of file DescriptorEventPublisher.cpp.
{
        muxOn(descriptorEventReceiver);
    }
References core::DescriptorEventPublisher::muxOn().
Referenced by core::DescriptorEventReceiver::resume().
signal()
void core::DescriptorEventPublisher::signal (int sigNum) inherited
Definition at line 131 of file DescriptorEventPublisher.cpp.
{
        for (auto& [fd, eventReceivers] : observedEventReceivers) {
            for (DescriptorEventReceiver* eventReceiver : eventReceivers) {
                eventReceiver->onSignal(sigNum);
            }
        }
    }
References core::DescriptorEventPublisher::observedEventReceivers, and core::DescriptorEventReceiver::onSignal().
Referenced by core::EventMultiplexer::signal().
spanActiveEvents()
void core::epoll::DescriptorEventPublisher::spanActiveEvents () override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 126 of file DescriptorEventPublisher.cpp.
{
        const int count = core::system::epoll_wait(ePollEvents.getEPFd(), ePollEvents.getEvents(), ePollEvents.getInterestCount(), 0);
        for (int i = 0; i < count; i++) {
            const epoll_event& ev = ePollEvents.getEvents()[i];
            core::DescriptorEventReceiver* eventReceiver = static_cast<core::DescriptorEventReceiver*>(ev.data.ptr);
            if (eventReceiver != nullptr && (ev.events & revents) != 0) {
                eventCounter++;
                eventReceiver->span();
            }
        }
    }
References core::system::epoll_wait(), ePollEvents, core::DescriptorEventPublisher::eventCounter, core::epoll::DescriptorEventPublisher::EPollEvents::getEPFd(), core::epoll::DescriptorEventPublisher::EPollEvents::getEvents(), core::epoll::DescriptorEventPublisher::EPollEvents::getInterestCount(), revents, and core::EventReceiver::span().
suspend()
void core::DescriptorEventPublisher::suspend (DescriptorEventReceiver * descriptorEventReceiver) inherited
Definition at line 57 of file DescriptorEventPublisher.cpp.
{
        muxOff(descriptorEventReceiver);
    }
References core::DescriptorEventPublisher::muxOff().
Referenced by core::DescriptorEventReceiver::suspend().
Member Data Documentation
ePollEvents
EPollEvents core::epoll::DescriptorEventPublisher::ePollEvents private
Definition at line 80 of file DescriptorEventPublisher.h.
Referenced by DescriptorEventPublisher(), muxAdd(), muxDel(), muxOff(), muxOn(), and spanActiveEvents().
eventCounter
unsigned long core::DescriptorEventPublisher::eventCounter = 0 protected inherited
Definition at line 79 of file DescriptorEventPublisher.h.
Referenced by spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), and core::select::DescriptorEventPublisher::spanActiveEvents().
name
std::string core::DescriptorEventPublisher::name private inherited
Definition at line 86 of file DescriptorEventPublisher.h.
Referenced by core::DescriptorEventPublisher::DescriptorEventPublisher(), and core::DescriptorEventPublisher::getName().
observedEventReceivers
std::map<int, std::list<DescriptorEventReceiver*> > core::DescriptorEventPublisher::observedEventReceivers protected inherited
Definition at line 81 of file DescriptorEventPublisher.h.
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents(), core::DescriptorEventPublisher::disable(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::getNextTimeout(), core::DescriptorEventPublisher::getObservedEventReceiverCount(), core::DescriptorEventPublisher::maxFd(), core::DescriptorEventPublisher::releaseDisabledEvents(), core::DescriptorEventPublisher::signal(), core::poll::DescriptorEventPublisher::spanActiveEvents(), and core::select::DescriptorEventPublisher::spanActiveEvents().
observedEventReceiversDirty
bool core::DescriptorEventPublisher::observedEventReceiversDirty = false private inherited
Definition at line 84 of file DescriptorEventPublisher.h.
Referenced by core::DescriptorEventPublisher::disable(), core::DescriptorEventPublisher::getNextTimeout(), and core::DescriptorEventPublisher::releaseDisabledEvents().
revents
uint32_t core::epoll::DescriptorEventPublisher::revents private
Definition at line 81 of file DescriptorEventPublisher.h.
Referenced by DescriptorEventPublisher(), and spanActiveEvents().
The documentation for this class was generated from the following files:
core/multiplexer/epoll/DescriptorEventPublisher.h
core/multiplexer/epoll/DescriptorEventPublisher.cpp