SNode.C: net::config::ConfigPhysicalSocket Class Reference
net::config::ConfigPhysicalSocket Class Reference
#include <ConfigPhysicalSocket.h>
Public Member Functions
ConfigPhysicalSocket (ConfigInstance *instance)
const std::map< int, const net::phy::PhysicalSocketOption > & getSocketOptions ()
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, int optValue)
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, const std::string &optValue)
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, const std::vector< char > &optValue)
ConfigPhysicalSocket & removeSocketOption (int optName)
ConfigPhysicalSocket & setReuseAddress (bool reuseAddress=true)
bool getReuseAddress () const
ConfigPhysicalSocket & setRetry (bool retry=true)
bool getRetry () const
ConfigPhysicalSocket & setRetryOnFatal (bool retry=true)
bool getRetryOnFatal () const
ConfigPhysicalSocket & setRetryTimeout (double sec)
double getRetryTimeout () const
ConfigPhysicalSocket & setRetryTries (unsigned int tries=0)
unsigned int getRetryTries () const
ConfigPhysicalSocket & setRetryBase (double base)
double getRetryBase () const
ConfigPhysicalSocket & setRetryLimit (unsigned int limit)
unsigned int getRetryLimit () const
ConfigPhysicalSocket & setRetryJitter (double percent)
double getRetryJitter () const
Protected Member Functions
CLI::Option * add_socket_option (CLI::Option *&opt, const std::string &name, int optLevel, int optName, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
Protected Attributes
CLI::Option * reuseAddressOpt = nullptr
CLI::Option * retryOpt = nullptr
CLI::Option * retryOnFatalOpt = nullptr
CLI::Option * retryTriesOpt = nullptr
CLI::Option * retryTimeoutOpt = nullptr
CLI::Option * retryBaseOpt = nullptr
CLI::Option * retryLimitOpt = nullptr
CLI::Option * retryJitterOpt = nullptr
std::map< int, const net::phy::PhysicalSocketOption > socketOptionsMap
CLI::App * section = nullptr
Private Attributes
ConfigInstance * instance = nullptr
uint8_t requiredCount = 0
Detailed Description
Definition at line 45 of file ConfigPhysicalSocket.h.
Constructor & Destructor Documentation
ConfigPhysicalSocket()
net::config::ConfigPhysicalSocket::ConfigPhysicalSocket (ConfigInstance * instance) explicit
Definition at line 38 of file ConfigPhysicalSocket.cpp.
        : ConfigSection(instance, "socket", "Configuration of socket behavior") {
        add_socket_option(reuseAddressOpt, //
                          "--reuse-address{true}",
                          SOL_SOCKET,
                          SO_REUSEADDR,
                          "Reuse socket address",
                          "bool",
                          XSTR(REUSE_ADDRESS),
                          CLI::IsMember({"true", "false"}));
        add_flag(retryOpt, //
                 "--retry{true}",
                 "Automatically retry listen|connect",
                 "bool",
                 XSTR(RETRY),
                 CLI::IsMember({"true", "false"}));
        add_flag_function(
            retryOnFatalOpt, //
            "--retry-on-fatal{true}",
            [this](int64_t) -> void {
                if (retryOnFatalOpt->as<bool>() && !retryOpt->as<bool>()) {
                    throw CLI::RequiresError(retryOnFatalOpt->get_name(), retryOpt->get_name().append("=true"));
                }
            },
            "Retry also on fatal errors",
            "bool",
            XSTR(RETRY_ON_FATAL),
            CLI::IsMember({"true", "false"}));
        retryOnFatalOpt->needs(retryOpt);
        add_option(retryTimeoutOpt, //
                   "--retry-timeout",
                   "Timeout of the retry timer",
                   "sec",
                   RETRY_TIMEOUT,
                   CLI::NonNegativeNumber);
        retryTimeoutOpt->needs(retryOpt);
        add_option(retryTriesOpt, //
                   "--retry-tries",
                   "Number of retry attempts before giving up (0 = unlimited)",
                   "tries",
                   RETRY_TRIES,
                   CLI::TypeValidator<unsigned int>());
        retryTriesOpt->needs(retryOpt);
        add_option(retryBaseOpt, //
                   "--retry-base",
                   "Base of exponential backoff",
                   "base",
                   RETRY_BASE,
                   CLI::PositiveNumber);
        retryBaseOpt->needs(retryOpt);
        add_option(retryJitterOpt, //
                   "--retry-jitter",
                   "Maximum jitter in percent to apply randomly to calculated retry timeout (0 to disable)",
                   "jitter",
                   RETRY_JITTER,
                   CLI::Range(0., 100.));
        retryJitterOpt->needs(retryOpt);
        retryJitterOpt->needs(retryOpt);
        retryBaseOpt->needs(retryOpt);
        retryTriesOpt->needs(retryOpt);
        retryTimeoutOpt->needs(retryOpt);
        retryOnFatalOpt->needs(retryOpt);
        add_option(retryLimitOpt, //
                   "--retry-limit",
                   "Upper limit in seconds of retry timeout",
                   "sec",
                   RETRY_LIMIT,
                   CLI::NonNegativeNumber);
        retryLimitOpt->needs(retryOpt);
    }
References net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), add_socket_option(), net::config::ConfigSection::ConfigSection(), retryBaseOpt, retryJitterOpt, retryLimitOpt, retryOnFatalOpt, retryOpt, retryTimeoutOpt, retryTriesOpt, and reuseAddressOpt.
Referenced by net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient(), and net::config::ConfigPhysicalSocketServer::ConfigPhysicalSocketServer().
Member Function Documentation
add_flag() [1/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 110 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag(name, description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [2/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 125 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [3/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 64 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [4/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 71 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [5/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_flag() [6/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by ConfigPhysicalSocket(), net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag_function() [1/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) protected inherited
Definition at line 134 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [2/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 155 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by add_socket_option(), ConfigPhysicalSocket(), and net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient().
add_option() [1/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) protected inherited
Definition at line 79 of file ConfigSection.cpp.
{
        if (!instance->getInstanceName().empty() && !section->get_display_name().empty()) {
            section->disabled(false);
        }
        opt = section //
                  ->add_option(name, description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigInstance::getInstanceName(), net::config::ConfigSection::instance, and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [2/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 95 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [3/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 100 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [4/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 46 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [5/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 53 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [6/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
Referenced by net::config::ConfigTls::ConfigTls().
add_option() [7/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
add_socket_option()
CLI::Option * net::config::ConfigPhysicalSocket::add_socket_option (CLI::Option *& opt, const std::string & name, int optLevel, int optName, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected
Definition at line 121 of file ConfigPhysicalSocket.cpp.
{
        return net::config::ConfigSection::add_flag_function(
            opt,
            name,
            [this, &opt, optLevel, optName](int64_t) -> void {
                if (opt->as<bool>()) {
                    socketOptionsMap.insert({optName, net::phy::PhysicalSocketOption(optLevel, optName, 1)});
                } else {
                    socketOptionsMap.erase(optName);
                }
            },
            description,
            typeName,
            defaultValue,
            validator);
    }
References net::config::ConfigSection::add_flag_function(), net::phy::PhysicalSocketOption::PhysicalSocketOption(), and socketOptionsMap.
Referenced by ConfigPhysicalSocket(), net::in::stream::config::ConfigSocketServer::ConfigSocketServer(), and net::in6::stream::config::ConfigSocketServer::ConfigSocketServer().
addSocketOption() [1/3]
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::addSocketOption (int optLevel, int optName, const std::string & optValue)
Definition at line 151 of file ConfigPhysicalSocket.cpp.
{
        socketOptionsMap.insert({optName, net::phy::PhysicalSocketOption(optLevel, optName, optValue)});
        return *this;
    }
References net::phy::PhysicalSocketOption::PhysicalSocketOption(), and socketOptionsMap.
addSocketOption() [2/3]
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::addSocketOption (int optLevel, int optName, const std::vector< char > & optValue)
Definition at line 157 of file ConfigPhysicalSocket.cpp.
{
        socketOptionsMap.insert({optName, net::phy::PhysicalSocketOption(optLevel, optName, optValue)});
        return *this;
    }
References net::phy::PhysicalSocketOption::PhysicalSocketOption(), and socketOptionsMap.
addSocketOption() [3/3]
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::addSocketOption (int optLevel, int optName, int optValue)
Definition at line 145 of file ConfigPhysicalSocket.cpp.
{
        socketOptionsMap.insert({optName, net::phy::PhysicalSocketOption(optLevel, optName, optValue)});
        return *this;
    }
References net::phy::PhysicalSocketOption::PhysicalSocketOption(), and socketOptionsMap.
Referenced by net::in6::stream::config::ConfigSocketServer::setIPv6Only(), setReuseAddress(), net::in::stream::config::ConfigSocketServer::setReusePort(), and net::in6::stream::config::ConfigSocketServer::setReusePort().
getRetry()
bool net::config::ConfigPhysicalSocket::getRetry () const
Definition at line 211 of file ConfigPhysicalSocket.cpp.
{
        return retryOpt->as<bool>();
    }
References retryOpt.
getRetryBase()
double net::config::ConfigPhysicalSocket::getRetryBase () const
Definition at line 259 of file ConfigPhysicalSocket.cpp.
{
        return retryBaseOpt->as<double>();
    }
References retryBaseOpt.
getRetryJitter()
double net::config::ConfigPhysicalSocket::getRetryJitter () const
Definition at line 283 of file ConfigPhysicalSocket.cpp.
{
        return retryJitterOpt->as<double>();
    }
References retryJitterOpt.
getRetryLimit()
unsigned int net::config::ConfigPhysicalSocket::getRetryLimit () const
Definition at line 271 of file ConfigPhysicalSocket.cpp.
{
        return retryLimitOpt->as<unsigned int>();
    }
References retryLimitOpt.
getRetryOnFatal()
bool net::config::ConfigPhysicalSocket::getRetryOnFatal () const
Definition at line 223 of file ConfigPhysicalSocket.cpp.
{
        return retryOnFatalOpt->as<bool>();
    }
References retryOnFatalOpt.
getRetryTimeout()
double net::config::ConfigPhysicalSocket::getRetryTimeout () const
Definition at line 235 of file ConfigPhysicalSocket.cpp.
{
        return retryTimeoutOpt->as<double>();
    }
References retryTimeoutOpt.
getRetryTries()
unsigned int net::config::ConfigPhysicalSocket::getRetryTries () const
Definition at line 247 of file ConfigPhysicalSocket.cpp.
{
        return retryTriesOpt->as<unsigned int>();
    }
References retryTriesOpt.
getReuseAddress()
bool net::config::ConfigPhysicalSocket::getReuseAddress () const
Definition at line 183 of file ConfigPhysicalSocket.cpp.
{
        return reuseAddressOpt->as<bool>();
    }
References reuseAddressOpt.
getSocketOptions()
const std::map< int, const net::phy::PhysicalSocketOption > & net::config::ConfigPhysicalSocket::getSocketOptions ()
Definition at line 117 of file ConfigPhysicalSocket.cpp.
{
        return socketOptionsMap;
    }
References socketOptionsMap.
removeSocketOption()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::removeSocketOption (int optName)
Definition at line 163 of file ConfigPhysicalSocket.cpp.
{
        socketOptionsMap.erase(optName);
        return *this;
    }
References socketOptionsMap.
Referenced by net::in6::stream::config::ConfigSocketServer::setIPv6Only(), setReuseAddress(), net::in::stream::config::ConfigSocketServer::setReusePort(), and net::in6::stream::config::ConfigSocketServer::setReusePort().
required() [1/2]
bool net::config::ConfigSection::required () const protected inherited
Definition at line 75 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [2/2]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) protected inherited
Definition at line 58 of file ConfigSection.cpp.
{
        if (req != opt->get_required()) {
            if (req) {
                ++requiredCount;
                section->needs(opt);
                opt->default_str("");
            } else {
                --requiredCount;
                section->remove_needs(opt);
            }
            opt->required(req);
            instance->required(section, requiredCount > 0);
        }
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
setRetry()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetry (bool retry = true)
Definition at line 187 of file ConfigPhysicalSocket.cpp.
{
        retryOpt //
            ->default_val(retry ? "true" : "false")
            ->clear();
        if (retry) {
            retryLimitOpt->remove_needs(retryOpt);
            retryJitterOpt->remove_needs(retryOpt);
            retryBaseOpt->remove_needs(retryOpt);
            retryTriesOpt->remove_needs(retryOpt);
            retryTimeoutOpt->remove_needs(retryOpt);
            retryOnFatalOpt->remove_needs(retryOpt);
        } else {
            retryLimitOpt->needs(retryOpt);
            retryJitterOpt->needs(retryOpt);
            retryBaseOpt->needs(retryOpt);
            retryTriesOpt->needs(retryOpt);
            retryTimeoutOpt->needs(retryOpt);
            retryOnFatalOpt->needs(retryOpt);
        }
        return *this;
    }
References retryBaseOpt, retryJitterOpt, retryLimitOpt, retryOnFatalOpt, retryOpt, retryTimeoutOpt, and retryTriesOpt.
setRetryBase()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetryBase (double base)
Definition at line 251 of file ConfigPhysicalSocket.cpp.
{
        retryBaseOpt //
            ->default_val(base)
            ->clear();
        return *this;
    }
References retryBaseOpt.
setRetryJitter()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetryJitter (double percent)
Definition at line 275 of file ConfigPhysicalSocket.cpp.
{
        retryJitterOpt //
            ->default_val(percent)
            ->clear();
        return *this;
    }
References retryJitterOpt.
setRetryLimit()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetryLimit (unsigned int limit)
Definition at line 263 of file ConfigPhysicalSocket.cpp.
{
        retryLimitOpt //
            ->default_val(limit)
            ->clear();
        return *this;
    }
References retryLimitOpt.
setRetryOnFatal()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetryOnFatal (bool retry = true)
Definition at line 215 of file ConfigPhysicalSocket.cpp.
{
        retryOnFatalOpt //
            ->default_val(retry ? "true" : "false")
            ->clear();
        return *this;
    }
References retryOnFatalOpt.
setRetryTimeout()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetryTimeout (double sec)
Definition at line 227 of file ConfigPhysicalSocket.cpp.
{
        retryTimeoutOpt //
            ->default_val(sec)
            ->clear();
        return *this;
    }
References retryTimeoutOpt.
setRetryTries()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetryTries (unsigned int tries = 0)
Definition at line 239 of file ConfigPhysicalSocket.cpp.
{
        retryTriesOpt //
            ->default_val(tries)
            ->clear();
        return *this;
    }
References retryTriesOpt.
setReuseAddress()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setReuseAddress (bool reuseAddress = true)
Definition at line 169 of file ConfigPhysicalSocket.cpp.
{
        if (reuseAddress) {
            addSocketOption(SOL_SOCKET, SO_REUSEADDR, 1);
        } else {
            removeSocketOption(SO_REUSEADDR);
        }
        reuseAddressOpt //
            ->default_val(reuseAddress ? "true" : "false")
            ->clear();
        return *this;
    }
References addSocketOption(), removeSocketOption(), and reuseAddressOpt.
Member Data Documentation
instance
ConfigInstance* net::config::ConfigSection::instance = nullptr private inherited
Definition at line 121 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), and net::config::ConfigSection::required().
requiredCount
uint8_t net::config::ConfigSection::requiredCount = 0 private inherited
Definition at line 123 of file ConfigSection.h.
Referenced by net::config::ConfigSection::required(), and net::config::ConfigSection::required().
retryBaseOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryBaseOpt = nullptr protected
Definition at line 96 of file ConfigPhysicalSocket.h.
Referenced by ConfigPhysicalSocket(), getRetryBase(), setRetry(), and setRetryBase().
retryJitterOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryJitterOpt = nullptr protected
Definition at line 98 of file ConfigPhysicalSocket.h.
Referenced by ConfigPhysicalSocket(), getRetryJitter(), setRetry(), and setRetryJitter().
retryLimitOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryLimitOpt = nullptr protected
Definition at line 97 of file ConfigPhysicalSocket.h.
Referenced by ConfigPhysicalSocket(), getRetryLimit(), setRetry(), and setRetryLimit().
retryOnFatalOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryOnFatalOpt = nullptr protected
Definition at line 93 of file ConfigPhysicalSocket.h.
Referenced by ConfigPhysicalSocket(), getRetryOnFatal(), setRetry(), and setRetryOnFatal().
retryOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryOpt = nullptr protected
Definition at line 92 of file ConfigPhysicalSocket.h.
Referenced by ConfigPhysicalSocket(), getRetry(), and setRetry().
retryTimeoutOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryTimeoutOpt = nullptr protected
Definition at line 95 of file ConfigPhysicalSocket.h.
Referenced by ConfigPhysicalSocket(), getRetryTimeout(), setRetry(), and setRetryTimeout().
retryTriesOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryTriesOpt = nullptr protected
Definition at line 94 of file ConfigPhysicalSocket.h.
Referenced by ConfigPhysicalSocket(), getRetryTries(), setRetry(), and setRetryTries().
reuseAddressOpt
CLI::Option* net::config::ConfigPhysicalSocket::reuseAddressOpt = nullptr protected
Definition at line 91 of file ConfigPhysicalSocket.h.
Referenced by ConfigPhysicalSocket(), getReuseAddress(), and setReuseAddress().
section
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 126 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
socketOptionsMap
std::map<int, const net::phy::PhysicalSocketOption> net::config::ConfigPhysicalSocket::socketOptionsMap protected
Definition at line 100 of file ConfigPhysicalSocket.h.
Referenced by add_socket_option(), addSocketOption(), addSocketOption(), addSocketOption(), getSocketOptions(), and removeSocketOption().
The documentation for this class was generated from the following files:
net/config/ConfigPhysicalSocket.h
net/config/ConfigPhysicalSocket.cpp