SNode.C: core::eventreceiver::InitConnectEventReceiver Class Reference
core::eventreceiver::InitConnectEventReceiver Class Reference abstract
#include <ConnectEventReceiver.h>
Public Member Functions
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Member Functions
InitConnectEventReceiver (const std::string &name)
Private Member Functions
void onEvent (const utils::Timeval &currentTime) override
virtual void initConnectEvent ()=0
Private Attributes
Event event
Detailed Description
Definition at line 46 of file ConnectEventReceiver.h.
Constructor & Destructor Documentation
InitConnectEventReceiver()
core::eventreceiver::InitConnectEventReceiver::InitConnectEventReceiver (const std::string & name) protected
Definition at line 49 of file ConnectEventReceiver.cpp.
        : core::EventReceiver("InitConnectEventReceiver: " + name) {
    }
References core::EventReceiver::EventReceiver().
Member Function Documentation
destruct()
void core::EventReceiver::destruct () virtual inherited
Reimplemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, and database::mariadb::MariaDBCommandStartEvent.
Definition at line 31 of file EventReceiver.cpp.
{
        delete this;
    }
Referenced by core::EventMultiplexer::EventQueue::clear().
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 43 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
initConnectEvent()
virtual void core::eventreceiver::InitConnectEventReceiver::initConnectEvent () private pure virtual
Implemented in core::socket::stream::tls::SocketConnector< PhysicalSocketClientT, ConfigT >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, and core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >.
Referenced by onEvent().
onEvent()
void core::eventreceiver::InitConnectEventReceiver::onEvent (const utils::Timeval & currentTime) override private virtual
Implements core::EventReceiver.
Definition at line 53 of file ConnectEventReceiver.cpp.
{
        initConnectEvent();
    }
References initConnectEvent().
relax()
void core::EventReceiver::relax () inherited
Definition at line 39 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
span()
void core::EventReceiver::span () inherited
Definition at line 35 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::FileReader(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
Member Data Documentation
event
Event core::EventReceiver::event private inherited
Definition at line 54 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
The documentation for this class was generated from the following files:
core/eventreceiver/ConnectEventReceiver.h
core/eventreceiver/ConnectEventReceiver.cpp