SNode.C: iot::mqtt::packets::Pingreq Class Reference
iot::mqtt::packets::Pingreq Class Reference
#include <Pingreq.h>
Public Member Functions
Pingreq ()
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type, const std::string &name)
ControlPacket (const ControlPacket &)=default
ControlPacket (ControlPacket &&)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
ControlPacket & operator= (ControlPacket &&)=default
std::vector< char > serialize () const
const std::string & getName () const
uint8_t getType () const
uint8_t getFlags () const
Private Member Functions
std::vector< char > serializeVP () const override
Additional Inherited Members
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t flags = 0
Detailed Description
Definition at line 33 of file Pingreq.h.
Constructor & Destructor Documentation
Pingreq()
iot::mqtt::packets::Pingreq::Pingreq ()
Definition at line 28 of file Pingreq.cpp.
        : iot::mqtt::ControlPacket(MQTT_PINGREQ, "PINGREQ") {
    }
References Pingreq().
Referenced by Pingreq(), and iot::mqtt::client::Mqtt::sendPingreq().
Member Function Documentation
serializeVP()
std::vector< char > iot::mqtt::packets::Pingreq::serializeVP () const override private virtual
Implements iot::mqtt::ControlPacket.
Definition at line 32 of file Pingreq.cpp.
{
        return std::vector<char>();
    }
The documentation for this class was generated from the following files:
iot/mqtt/packets/Pingreq.h
iot/mqtt/packets/Pingreq.cpp