SNode.C: web::http::client::commands::EndCommand Class Reference
web::http::client::commands::EndCommand Class Reference
#include <EndCommand.h>
Public Member Functions
EndCommand (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError)
~EndCommand () override=default
bool execute (const std::shared_ptr< MasterRequest > &request) override
Public Member Functions inherited from web::http::client::RequestCommand
RequestCommand (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError)
RequestCommand (const RequestCommand &)=delete
RequestCommand (RequestCommand &&) noexcept=delete
RequestCommand & operator= (const RequestCommand &)=delete
RequestCommand & operator= (RequestCommand &&) noexcept=delete
virtual ~RequestCommand ()
bool getError () const
Additional Inherited Members
Public Attributes inherited from web::http::client::RequestCommand
const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> onResponseReceived
const std::function< void(const std::shared_ptr< Request > &, const std::string &)> onResponseParseError
Protected Attributes inherited from web::http::client::RequestCommand
bool error = false
Detailed Description
Definition at line 60 of file EndCommand.h.
Constructor & Destructor Documentation
EndCommand()
web::http::client::commands::EndCommand::EndCommand (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> & onResponseParseError)
Definition at line 52 of file EndCommand.cpp.
        : web::http::client::RequestCommand(onResponseReceived, onResponseParseError) {
    }
References web::http::client::RequestCommand::RequestCommand().
Referenced by web::http::client::MasterRequest::end(), and web::http::client::MasterRequest::send().
~EndCommand()
web::http::client::commands::EndCommand::~EndCommand () override default
Member Function Documentation
execute()
bool web::http::client::commands::EndCommand::execute (const std::shared_ptr< MasterRequest > & request) override virtual
Implements web::http::client::RequestCommand.
Definition at line 57 of file EndCommand.cpp.
{
        return request->executeEnd();
    }
References web::http::client::MasterRequest::executeEnd().
The documentation for this class was generated from the following files:
web/http/client/commands/EndCommand.h
web/http/client/commands/EndCommand.cpp