SNode.C: net::un::SocketAddress Class Reference
net::un::SocketAddress Class Reference final
#include <SocketAddress.h>
Public Member Functions
SocketAddress ()
SocketAddress (const std::string &sunPath)
SocketAddress (const SockAddr &sockAddr, SockLen sockAddrLen)
void init ()
SocketAddress & setSunPath (const std::string &sunPath)
std::string getSunPath () const
std::string toString (bool expanded=true) const override
Public Member Functions inherited from net::SocketAddress< sockaddr_un >
SocketAddress (sa_family_t af, SockLen sockAddrLen=sizeof(SockAddr))
SocketAddress (const SocketAddress &socketAddress)
SocketAddress (const SockAddr &sockAddr, SockLen sockAddrLen)
SocketAddress & operator= (const SocketAddress &socketAddress)
const sockaddr & getSockAddr ()
const SockLen & getSockAddrLen () const
sa_family_t getAddressFamily () const
Public Member Functions inherited from core::socket::SocketAddress
virtual ~SocketAddress ()
virtual bool useNext ()
virtual std::string getEndpoint (const std::string_view &format={}) const
Private Types
using Super = net::SocketAddress<sockaddr_un>
Private Attributes
std::string sunPath
Additional Inherited Members
Public Types inherited from net::SocketAddress< sockaddr_un >
using SockAddr
using SockLen
Protected Attributes inherited from net::SocketAddress< sockaddr_un >
SockAddr sockAddr
SockLen sockAddrLen
Detailed Description
Definition at line 58 of file SocketAddress.h.
Member Typedef Documentation
Super
using net::un::SocketAddress::Super = net::SocketAddress<sockaddr_un> private
Definition at line 60 of file SocketAddress.h.
Constructor & Destructor Documentation
SocketAddress() [1/3]
net::un::SocketAddress::SocketAddress ()
Definition at line 57 of file SocketAddress.cpp.
        : Super(AF_UNIX, offsetof(sockaddr_un, sun_path)) {
    }
References net::SocketAddress< SockAddrT >::SocketAddress().
Referenced by SocketAddress().
SocketAddress() [2/3]
net::un::SocketAddress::SocketAddress (const std::string & sunPath) explicit
Definition at line 61 of file SocketAddress.cpp.
        : SocketAddress() {
        setSunPath(sunPath);
    }
References setSunPath(), and SocketAddress().
Referenced by web::http::legacy::un::EventSource(), web::http::legacy::un::EventSource(), web::http::tls::un::EventSource(), web::http::tls::un::EventSource(), and net::un::config::ConfigAddress< ConfigAddressTypeT >::init().
SocketAddress() [3/3]
net::un::SocketAddress::SocketAddress (const SockAddr & sockAddr, SockLen sockAddrLen)
Definition at line 66 of file SocketAddress.cpp.
        : net::SocketAddress<SockAddr>(sockAddr, sockAddrLen)
        , sunPath(sockAddr.sun_path) {
    }
References net::SocketAddress< SockAddrT >::SocketAddress(), and sunPath.
Member Function Documentation
getSunPath()
std::string net::un::SocketAddress::getSunPath () const
Definition at line 92 of file SocketAddress.cpp.
{
        return sunPath;
    }
References sunPath.
Referenced by net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::bind().
init()
void net::un::SocketAddress::init ()
Definition at line 71 of file SocketAddress.cpp.
{
        if (sunPath.length() < sizeof(sockAddr.sun_path)) {
            const std::size_t len = sunPath.length();
            std::memcpy(sockAddr.sun_path, sunPath.data(), len);
            sockAddr.sun_path[len] = 0;
            sockAddrLen = static_cast<SockLen>(offsetof(sockaddr_un, sun_path) + len + 1);
        } else {
            throw core::socket::SocketAddress::BadSocketAddress(
                core::socket::STATE_FATAL,
                "Unix-Domain error sun-path to long: Lenght is = " + std::to_string(sunPath.length()) +
                    ", should be: " + std::to_string(sizeof(sockAddr.sun_path) - 1),
                EINVAL);
        }
    }
References sunPath.
Referenced by net::un::config::ConfigAddress< ConfigAddressTypeT >::init().
setSunPath()
SocketAddress & net::un::SocketAddress::setSunPath (const std::string & sunPath)
Definition at line 86 of file SocketAddress.cpp.
{
        this->sunPath = sunPath;
        return *this;
    }
References sunPath.
Referenced by SocketAddress().
toString()
std::string net::un::SocketAddress::toString (bool expanded = true) const override virtual
Implements core::socket::SocketAddress.
Definition at line 96 of file SocketAddress.cpp.
{
        return sockAddr.sun_path[0] != '\0' ? sockAddr.sun_path : std::string("@").append(sockAddr.sun_path + 1);
    }
Referenced by express::legacy::un::Server(), and express::tls::un::Server().
Member Data Documentation
sunPath
std::string net::un::SocketAddress::sunPath private
Definition at line 75 of file SocketAddress.h.
Referenced by getSunPath(), init(), setSunPath(), and SocketAddress().
The documentation for this class was generated from the following files:
net/un/SocketAddress.h
net/un/SocketAddress.cpp