SNode.C: net::config::ConfigTlsServer Class Reference
net::config::ConfigTlsServer Class Reference
#include <ConfigTlsServer.h>
Public Member Functions
ConfigTlsServer (ConfigInstance *instance)
bool getForceSni () const
void setForceSni (bool forceSni=true)
std::map< std::string, std::map< std::string, std::variant< std::string, bool, ssl_option_t > > > & getSniCerts ()
void addSniCerts (const std::map< std::string, std::map< std::string, std::variant< std::string, bool, ssl_option_t > > > &sniCerts)
void addSniCert (const std::string &domain, const std::map< std::string, std::variant< std::string, bool, ssl_option_t > > &sniCert)
utils::Timeval getInitTimeout () const
void setInitTimeout (const utils::Timeval &newInitTimeout)
utils::Timeval getShutdownTimeout () const
void setShutdownTimeout (const utils::Timeval &newShutdownTimeout)
std::string getCertChain () const
void setCertChain (const std::string &newCertChain)
std::string getCertKey () const
void setCertKey (const std::string &newCertKey)
std::string getCertKeyPassword () const
void setCertKeyPassword (const std::string &newCertKeyPassword)
std::string getCaCertFile () const
void setCaCertFile (const std::string &newCaCertFile)
std::string getCaCertDir () const
void setCaCertDir (const std::string &newCaCertDir)
bool getUseDefaultCaCertDir () const
void setUseDefaultCaCertDir (bool set=true)
std::string getCipherList () const
void setCipherList (const std::string &newCipherList)
ssl_option_t getSslTlsOptions () const
void setSslTlsOptions (ssl_option_t newSslTlsOptions)
Protected Member Functions
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
Protected Attributes
CLI::App * section = nullptr
Private Attributes
std::map< std::string, std::map< std::string, std::variant< std::string, bool, ssl_option_t > > > sniCerts
CLI::Option * sniCertsOpt = nullptr
CLI::Option * forceSniOpt = nullptr
CLI::Option * certChainOpt = nullptr
CLI::Option * certKeyOpt = nullptr
CLI::Option * certKeyPasswordOpt = nullptr
CLI::Option * caCertFileOpt = nullptr
CLI::Option * caCertDirOpt = nullptr
CLI::Option * useDefaultCaCertDirOpt = nullptr
CLI::Option * cipherListOpt = nullptr
CLI::Option * tlsOptionsOpt = nullptr
CLI::Option * initTimeoutOpt = nullptr
CLI::Option * shutdownTimeoutOpt = nullptr
ConfigInstance * instance = nullptr
uint8_t requiredCount = 0
Detailed Description
Definition at line 42 of file ConfigTlsServer.h.
Constructor & Destructor Documentation
ConfigTlsServer()
net::config::ConfigTlsServer::ConfigTlsServer (ConfigInstance * instance) explicit
Definition at line 36 of file ConfigTlsServer.cpp.
        : ConfigTls(instance) {
        sniCertsOpt = section //
                          ->add_option("--sni-cert",
                                       sniCerts,
                                       "Server Name Indication (SNI) Certificates:\n"
                                       "sni = SNI of the virtual server\n"
                                       "<key> = {\n"
                                       "          \"CertChain\" -> value:PEM-FILE,\n"
                                       "          \"CertKey\" -> value:PEM-FILE,\n"
                                       "          \"CertKeyPassword\" -> value:TEXT,\n"
                                       "          \"CaCertFile\" -> value:PEM-FILE,\n"
                                       "          \"CaCertDir\" -> value:PEM-CONTAINER:DIR,\n"
                                       "          \"UseDefaultCaDir\" -> value:BOOLEAN [false],\n"
                                       "          \"SslOptions\" -> value:UINT\n"
                                       "        }") //
                          ->type_name("sni <key> value {<key> value} ... {%% sni <key> value {<key> value} ...}")
                          ->default_val("\"\" \"\" \"\" \"\"");
        if (sniCertsOpt->get_configurable()) {
            sniCertsOpt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        add_flag(
            forceSniOpt, "--force-sni,", "Force using of the Server Name Indication", "bool", "false", CLI::IsMember({"true", "false"}));
        section->final_callback([this](void) -> void {
            std::list<std::string> vaultyDomainConfigs;
            for (auto& [domain, sniMap] : sniCerts) {
                if (sniMap.begin()->first.empty()) {
                    sniCertsOpt //
                        ->clear();
                    break;
                } else {
                    for (auto& [key, value] : sniMap) {
                        if (key != "CertChain" && key != "CertKey" && key != "CertKeyPassword" && key != "CaCertFile" &&
                            key != "CaCertDir" && key != "UseDefaultCaDir" && key != "CipherList" && key != "SslOptions") {
                            vaultyDomainConfigs.push_back(key);
                            throw CLI::ConversionError("'" + key + "' of option '--" + section->get_parent()->get_name() + "." +
                                                           section->get_name() + ".sni-cert'",
                                                       "<key>");
                        }
                    }
                }
            }
            for (const std::string& domain : vaultyDomainConfigs) {
                sniCerts.erase(domain);
            }
        });
    }
References net::config::ConfigSection::add_flag(), net::config::ConfigTls::ConfigTls(), forceSniOpt, net::config::ConfigSection::section, sniCerts, and sniCertsOpt.
Member Function Documentation
add_flag() [1/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 116 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_flag_function(name, utils::ResetToDefault(opt), description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References utils::ResetToDefault::ResetToDefault(), and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [2/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 129 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [3/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 63 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [4/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 70 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [5/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_flag() [6/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and ConfigTlsServer().
add_flag_function() [1/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) protected inherited
Definition at line 138 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [2/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 157 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option().
add_option() [1/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) protected inherited
Definition at line 89 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_option_function<std::string>(name, utils::ResetToDefault(opt), description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References utils::ResetToDefault::ResetToDefault(), and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [2/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 101 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [3/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 106 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [4/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 45 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [5/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 52 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [6/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
Referenced by net::config::ConfigTls::ConfigTls().
add_option() [7/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
addSniCert()
void net::config::ConfigTlsServer::addSniCert (const std::string & domain, const std::map< std::string, std::variant< std::string, bool, ssl_option_t > > & sniCert)
Definition at line 106 of file ConfigTlsServer.cpp.
{
        this->sniCerts[domain] = newSniCert;
    }
References sniCerts.
addSniCerts()
void net::config::ConfigTlsServer::addSniCerts (const std::map< std::string, std::map< std::string, std::variant< std::string, bool, ssl_option_t > > > & sniCerts)
Definition at line 101 of file ConfigTlsServer.cpp.
{
        this->sniCerts.insert(sniCerts.begin(), sniCerts.end());
    }
References sniCerts.
getCaCertDir()
std::string net::config::ConfigTls::getCaCertDir () const inherited
Definition at line 122 of file ConfigTls.cpp.
{
        return caCertDirOpt->as<std::string>();
    }
References net::config::ConfigTls::caCertDirOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getCaCertFile()
std::string net::config::ConfigTls::getCaCertFile () const inherited
Definition at line 112 of file ConfigTls.cpp.
{
        return caCertFileOpt->as<std::string>();
    }
References net::config::ConfigTls::caCertFileOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getCertChain()
std::string net::config::ConfigTls::getCertChain () const inherited
Definition at line 84 of file ConfigTls.cpp.
{
        return certChainOpt->as<std::string>();
    }
References net::config::ConfigTls::certChainOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getCertKey()
std::string net::config::ConfigTls::getCertKey () const inherited
Definition at line 93 of file ConfigTls.cpp.
{
        return certKeyOpt->as<std::string>();
    }
References net::config::ConfigTls::certKeyOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getCertKeyPassword()
std::string net::config::ConfigTls::getCertKeyPassword () const inherited
Definition at line 102 of file ConfigTls.cpp.
{
        return certKeyPasswordOpt->as<std::string>();
    }
References net::config::ConfigTls::certKeyPasswordOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getCipherList()
std::string net::config::ConfigTls::getCipherList () const inherited
Definition at line 142 of file ConfigTls.cpp.
{
        return cipherListOpt->as<std::string>();
    }
References net::config::ConfigTls::cipherListOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getForceSni()
bool net::config::ConfigTlsServer::getForceSni () const
Definition at line 87 of file ConfigTlsServer.cpp.
{
        return forceSniOpt->as<bool>();
    }
References forceSniOpt.
getInitTimeout()
utils::Timeval net::config::ConfigTls::getInitTimeout () const inherited
Definition at line 162 of file ConfigTls.cpp.
{
        return initTimeoutOpt->as<utils::Timeval>();
    }
References net::config::ConfigTls::initTimeoutOpt.
getShutdownTimeout()
utils::Timeval net::config::ConfigTls::getShutdownTimeout () const inherited
Definition at line 172 of file ConfigTls.cpp.
{
        return shutdownTimeoutOpt //
            ->as<utils::Timeval>();
    }
References net::config::ConfigTls::shutdownTimeoutOpt.
getSniCerts()
std::map< std::string, std::map< std::string, std::variant< std::string, bool, ssl_option_t > > > & net::config::ConfigTlsServer::getSniCerts ()
Definition at line 97 of file ConfigTlsServer.cpp.
{
        return sniCerts;
    }
References sniCerts.
getSslTlsOptions()
ssl_option_t net::config::ConfigTls::getSslTlsOptions () const inherited
Definition at line 152 of file ConfigTls.cpp.
{
        return tlsOptionsOpt->as<ssl_option_t>();
    }
References net::config::ConfigTls::tlsOptionsOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getUseDefaultCaCertDir()
bool net::config::ConfigTls::getUseDefaultCaCertDir () const inherited
Definition at line 132 of file ConfigTls.cpp.
{
        return useDefaultCaCertDirOpt->as<bool>();
    }
References net::config::ConfigTls::useDefaultCaCertDirOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
required() [1/2]
bool net::config::ConfigSection::required () const protected inherited
Definition at line 85 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [2/2]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) protected inherited
Definition at line 61 of file ConfigSection.cpp.
{
        if (req && !opt->get_required()) {
            ++requiredCount;
            opt //
                ->default_str("")
                ->required()
                ->clear();
            section //
                ->needs(opt);
        } else if (opt->get_required()) {
            --requiredCount;
            opt //
                ->required(false)
                ->clear();
            section //
                ->remove_needs(opt);
        }
        section //
            ->required(requiredCount > 0);
        instance->required(section, req);
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
setCaCertDir()
void net::config::ConfigTls::setCaCertDir (const std::string & newCaCertDir) inherited
Definition at line 126 of file ConfigTls.cpp.
{
        caCertDirOpt //
            ->default_str(newCaCertDir)
            ->clear();
    }
References net::config::ConfigTls::caCertDirOpt.
setCaCertFile()
void net::config::ConfigTls::setCaCertFile (const std::string & newCaCertFile) inherited
Definition at line 116 of file ConfigTls.cpp.
{
        caCertFileOpt //
            ->default_str(newCaCertFile)
            ->clear();
    }
References net::config::ConfigTls::caCertFileOpt.
setCertChain()
void net::config::ConfigTls::setCertChain (const std::string & newCertChain) inherited
Definition at line 88 of file ConfigTls.cpp.
{
        certChainOpt //
            ->default_str(newCertChain);
    }
References net::config::ConfigTls::certChainOpt.
setCertKey()
void net::config::ConfigTls::setCertKey (const std::string & newCertKey) inherited
Definition at line 97 of file ConfigTls.cpp.
{
        certKeyOpt //
            ->default_str(newCertKey);
    }
References net::config::ConfigTls::certKeyOpt.
setCertKeyPassword()
void net::config::ConfigTls::setCertKeyPassword (const std::string & newCertKeyPassword) inherited
Definition at line 106 of file ConfigTls.cpp.
{
        certKeyPasswordOpt //
            ->default_val(newCertKeyPassword)
            ->clear();
    }
References net::config::ConfigTls::certKeyPasswordOpt.
setCipherList()
void net::config::ConfigTls::setCipherList (const std::string & newCipherList) inherited
Definition at line 146 of file ConfigTls.cpp.
{
        cipherListOpt //
            ->default_val(newCipherList)
            ->clear();
    }
References net::config::ConfigTls::cipherListOpt.
setForceSni()
void net::config::ConfigTlsServer::setForceSni (bool forceSni = true)
Definition at line 91 of file ConfigTlsServer.cpp.
{
        forceSniOpt //
            ->default_val(forceSni ? "true" : "false")
            ->clear();
    }
References forceSniOpt.
setInitTimeout()
void net::config::ConfigTls::setInitTimeout (const utils::Timeval & newInitTimeout) inherited
Definition at line 166 of file ConfigTls.cpp.
{
        initTimeoutOpt //
            ->default_val(newInitTimeout)
            ->clear();
    }
References net::config::ConfigTls::initTimeoutOpt.
setShutdownTimeout()
void net::config::ConfigTls::setShutdownTimeout (const utils::Timeval & newShutdownTimeout) inherited
Definition at line 177 of file ConfigTls.cpp.
{
        shutdownTimeoutOpt //
            ->default_val(newShutdownTimeout)
            ->clear();
    }
References net::config::ConfigTls::shutdownTimeoutOpt.
setSslTlsOptions()
void net::config::ConfigTls::setSslTlsOptions (ssl_option_t newSslTlsOptions) inherited
Definition at line 156 of file ConfigTls.cpp.
{
        tlsOptionsOpt //
            ->default_val(newSslTlsOptions)
            ->clear();
    }
References net::config::ConfigTls::tlsOptionsOpt.
setUseDefaultCaCertDir()
void net::config::ConfigTls::setUseDefaultCaCertDir (bool set = true) inherited
Definition at line 136 of file ConfigTls.cpp.
{
        useDefaultCaCertDirOpt //
            ->default_val(set ? "true" : "false")
            ->clear();
    }
References net::config::ConfigTls::useDefaultCaCertDirOpt.
Member Data Documentation
caCertDirOpt
CLI::Option* net::config::ConfigTls::caCertDirOpt = nullptr private inherited
Definition at line 83 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCaCertDir(), and net::config::ConfigTls::setCaCertDir().
caCertFileOpt
CLI::Option* net::config::ConfigTls::caCertFileOpt = nullptr private inherited
Definition at line 82 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCaCertFile(), and net::config::ConfigTls::setCaCertFile().
certChainOpt
CLI::Option* net::config::ConfigTls::certChainOpt = nullptr private inherited
Definition at line 79 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCertChain(), and net::config::ConfigTls::setCertChain().
certKeyOpt
CLI::Option* net::config::ConfigTls::certKeyOpt = nullptr private inherited
Definition at line 80 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCertKey(), and net::config::ConfigTls::setCertKey().
certKeyPasswordOpt
CLI::Option* net::config::ConfigTls::certKeyPasswordOpt = nullptr private inherited
Definition at line 81 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCertKeyPassword(), and net::config::ConfigTls::setCertKeyPassword().
cipherListOpt
CLI::Option* net::config::ConfigTls::cipherListOpt = nullptr private inherited
Definition at line 85 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCipherList(), and net::config::ConfigTls::setCipherList().
forceSniOpt
CLI::Option* net::config::ConfigTlsServer::forceSniOpt = nullptr private
Definition at line 57 of file ConfigTlsServer.h.
Referenced by ConfigTlsServer(), getForceSni(), and setForceSni().
initTimeoutOpt
CLI::Option* net::config::ConfigTls::initTimeoutOpt = nullptr private inherited
Definition at line 87 of file ConfigTls.h.
Referenced by net::config::ConfigTls::getInitTimeout(), and net::config::ConfigTls::setInitTimeout().
instance
ConfigInstance* net::config::ConfigSection::instance = nullptr private inherited
Definition at line 120 of file ConfigSection.h.
Referenced by net::config::ConfigSection::ConfigSection(), and net::config::ConfigSection::required().
requiredCount
uint8_t net::config::ConfigSection::requiredCount = 0 private inherited
Definition at line 122 of file ConfigSection.h.
Referenced by net::config::ConfigSection::required(), and net::config::ConfigSection::required().
section
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 125 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), ConfigTlsServer(), and net::config::ConfigSection::required().
shutdownTimeoutOpt
CLI::Option* net::config::ConfigTls::shutdownTimeoutOpt = nullptr private inherited
Definition at line 88 of file ConfigTls.h.
Referenced by net::config::ConfigTls::getShutdownTimeout(), and net::config::ConfigTls::setShutdownTimeout().
sniCerts
std::map<std::string, std::map<std::string, std::variant<std::string, bool, ssl_option_t> > > net::config::ConfigTlsServer::sniCerts private
Definition at line 54 of file ConfigTlsServer.h.
Referenced by addSniCert(), addSniCerts(), ConfigTlsServer(), and getSniCerts().
sniCertsOpt
CLI::Option* net::config::ConfigTlsServer::sniCertsOpt = nullptr private
Definition at line 56 of file ConfigTlsServer.h.
Referenced by ConfigTlsServer().
tlsOptionsOpt
CLI::Option* net::config::ConfigTls::tlsOptionsOpt = nullptr private inherited
Definition at line 86 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getSslTlsOptions(), and net::config::ConfigTls::setSslTlsOptions().
useDefaultCaCertDirOpt
CLI::Option* net::config::ConfigTls::useDefaultCaCertDirOpt = nullptr private inherited
Definition at line 84 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getUseDefaultCaCertDir(), and net::config::ConfigTls::setUseDefaultCaCertDir().
The documentation for this class was generated from the following files:
net/config/ConfigTlsServer.h
net/config/ConfigTlsServer.cpp