SNode.C: core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents Class Reference
core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents Class Reference
Public Member Functions
EPollEvents (int &epfd, uint32_t event)
void muxAdd (core::DescriptorEventReceiver *eventReceiver)
void muxDel (int fd)
void muxOn (core::DescriptorEventReceiver *eventReceiver)
void muxOff (core::DescriptorEventReceiver *eventReceiver)
int getEPFd () const
epoll_event * getEvents ()
int getInterestCount () const
Private Member Functions
void muxMod (int fd, uint32_t events, core::DescriptorEventReceiver *eventReceiver) const
Private Attributes
int & epfd
uint32_t events
std::vector< epoll_event > ePollEvents
std::vector< epoll_event >::size_type interestCount = 0
Detailed Description
Definition at line 65 of file DescriptorEventPublisher.h.
Constructor & Destructor Documentation
EPollEvents()
core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::EPollEvents (int & epfd, uint32_t event) explicit
Definition at line 56 of file DescriptorEventPublisher.cpp.
        : epfd(epfd)
        , events(events) {
        epfd = core::system::epoll_create1(EPOLL_CLOEXEC);
        ePollEvents.resize(1);
    }
References epfd, core::system::epoll_create1(), ePollEvents, and events.
Referenced by core::multiplexer::epoll::DescriptorEventPublisher::DescriptorEventPublisher().
Member Function Documentation
getEPFd()
int core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::getEPFd () const
Definition at line 111 of file DescriptorEventPublisher.cpp.
{
        return epfd;
    }
References epfd.
Referenced by core::multiplexer::epoll::DescriptorEventPublisher::spanActiveEvents().
getEvents()
epoll_event * core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::getEvents ()
Definition at line 115 of file DescriptorEventPublisher.cpp.
{
        return ePollEvents.data();
    }
References ePollEvents.
Referenced by core::multiplexer::epoll::DescriptorEventPublisher::spanActiveEvents().
getInterestCount()
int core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::getInterestCount () const
Definition at line 119 of file DescriptorEventPublisher.cpp.
{
        return static_cast<int>(interestCount);
    }
References interestCount.
Referenced by core::multiplexer::epoll::DescriptorEventPublisher::spanActiveEvents().
muxAdd()
void core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::muxAdd (core::DescriptorEventReceiver * eventReceiver)
Definition at line 63 of file DescriptorEventPublisher.cpp.
{
        const utils::PreserveErrno preserveErrno;
        epoll_event ePollEvent{};
        ePollEvent.data.ptr = eventReceiver;
        ePollEvent.events = events;
        if (core::system::epoll_ctl(epfd, EPOLL_CTL_ADD, eventReceiver->getRegisteredFd(), &ePollEvent) == 0) {
            interestCount++;
            if (interestCount >= ePollEvents.size()) {
                ePollEvents.resize(ePollEvents.size() * 2);
            }
        } else if (errno == EEXIST) {
            muxMod(eventReceiver->getRegisteredFd(), events, eventReceiver);
        }
    }
References epfd, core::system::epoll_ctl(), ePollEvents, events, core::DescriptorEventReceiver::getRegisteredFd(), interestCount, and muxMod().
Referenced by core::multiplexer::epoll::DescriptorEventPublisher::muxAdd().
muxDel()
void core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::muxDel (int fd)
Definition at line 82 of file DescriptorEventPublisher.cpp.
{
        const utils::PreserveErrno preserveErrno;
        if (core::system::epoll_ctl(epfd, EPOLL_CTL_DEL, fd, nullptr) == 0 || errno == EBADF) {
            interestCount--;
            if (ePollEvents.size() > (interestCount * 2) + 1) {
                ePollEvents.resize(ePollEvents.size() / 2);
                ePollEvents.shrink_to_fit();
            }
        }
    }
References epfd, core::system::epoll_ctl(), ePollEvents, and interestCount.
Referenced by core::multiplexer::epoll::DescriptorEventPublisher::muxDel().
muxMod()
void core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::muxMod (int fd, uint32_t events, core::DescriptorEventReceiver * eventReceiver) const private
Definition at line 95 of file DescriptorEventPublisher.cpp.
{
        const utils::PreserveErrno preserveErrno;
        epoll_event ePollEvent{events, {eventReceiver}};
        core::system::epoll_ctl(epfd, EPOLL_CTL_MOD, fd, &ePollEvent);
    }
References epfd, and core::system::epoll_ctl().
Referenced by muxAdd(), muxOff(), and muxOn().
muxOff()
void core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::muxOff (core::DescriptorEventReceiver * eventReceiver)
Definition at line 107 of file DescriptorEventPublisher.cpp.
{
        muxMod(eventReceiver->getRegisteredFd(), 0, eventReceiver);
    }
References core::DescriptorEventReceiver::getRegisteredFd(), and muxMod().
Referenced by core::multiplexer::epoll::DescriptorEventPublisher::muxOff().
muxOn()
void core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::muxOn (core::DescriptorEventReceiver * eventReceiver)
Definition at line 103 of file DescriptorEventPublisher.cpp.
{
        muxMod(eventReceiver->getRegisteredFd(), events, eventReceiver);
    }
References events, core::DescriptorEventReceiver::getRegisteredFd(), and muxMod().
Referenced by core::multiplexer::epoll::DescriptorEventPublisher::muxOn().
Member Data Documentation
epfd
int& core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::epfd private
Definition at line 84 of file DescriptorEventPublisher.h.
Referenced by EPollEvents(), getEPFd(), muxAdd(), muxDel(), and muxMod().
ePollEvents
std::vector<epoll_event> core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::ePollEvents private
Definition at line 87 of file DescriptorEventPublisher.h.
Referenced by EPollEvents(), getEvents(), muxAdd(), and muxDel().
events
uint32_t core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::events private
Definition at line 85 of file DescriptorEventPublisher.h.
Referenced by EPollEvents(), muxAdd(), and muxOn().
interestCount
std::vector<epoll_event>::size_type core::multiplexer::epoll::DescriptorEventPublisher::EPollEvents::interestCount = 0 private
Definition at line 88 of file DescriptorEventPublisher.h.
Referenced by getInterestCount(), muxAdd(), and muxDel().
The documentation for this class was generated from the following files:
core/multiplexer/epoll/DescriptorEventPublisher.h
core/multiplexer/epoll/DescriptorEventPublisher.cpp