SNode.C: web::websocket::Receiver Class Reference
web::websocket::Receiver Class Reference abstract
#include <Receiver.h>
Classes
union ELength2
union ELength8
Public Member Functions
Receiver (core::socket::stream::SocketConnection *socketConnection)
Receiver (const Receiver &)=delete
Receiver & operator= (const Receiver &)=delete
virtual ~Receiver ()
std::size_t receive ()
Private Types
enum struct ParserState {
BEGIN , OPCODE , LENGTH , ELENGTH ,
MASKINGKEY , PAYLOAD , ERROR
}
Private Member Functions
std::size_t readOpcode ()
std::size_t readLength ()
std::size_t readELength ()
std::size_t readMaskingKey ()
std::size_t readPayload ()
std::size_t readFrameData (char *chunk, std::size_t chunkLen)
std::size_t readELength2 ()
std::size_t readELength8 ()
virtual void onMessageStart (int opCode)=0
virtual void onMessageData (const char *chunk, uint64_t chunkLen)=0
virtual void onMessageEnd ()=0
virtual void onMessageError (uint16_t errnum)=0
void reset ()
Private Attributes
enum web::websocket::Receiver::ParserState parserState = ParserState::BEGIN
bool fin = false
bool continuation = false
bool masked = false
uint8_t opCode = 0
char maskingKey [4]
union web::websocket::Receiver::ELength8 eLength8
union web::websocket::Receiver::ELength2 eLength2
uint8_t elengthNumBytes = 0
uint8_t elengthNumBytesLeft = 0
uint64_t payLoadNumBytes = 0
uint64_t payLoadNumBytesLeft = 0
uint8_t maskingKeyNumBytes = 4
uint8_t maskingKeyNumBytesLeft = 4
uint16_t errorState = 0
core::socket::stream::SocketConnection * socketConnection = nullptr
Detailed Description
Definition at line 64 of file Receiver.h.
Member Enumeration Documentation
ParserState
enum struct web::websocket::Receiver::ParserState strong private
Enumerator
BEGIN
OPCODE
LENGTH
ELENGTH
MASKINGKEY
PAYLOAD
ERROR
Definition at line 95 of file Receiver.h.
{ BEGIN, OPCODE, LENGTH, ELENGTH, MASKINGKEY, PAYLOAD, ERROR } parserState = ParserState::BEGIN;
Constructor & Destructor Documentation
Receiver() [1/2]
web::websocket::Receiver::Receiver (core::socket::stream::SocketConnection * socketConnection)
Definition at line 58 of file Receiver.cpp.
        : socketConnection(socketConnection) {
    }
References socketConnection.
Referenced by web::websocket::SubProtocolContext::SubProtocolContext().
Receiver() [2/2]
web::websocket::Receiver::Receiver (const Receiver &) delete
~Receiver()
web::websocket::Receiver::~Receiver () virtual
Definition at line 62 of file Receiver.cpp.
{
    }
Member Function Documentation
onMessageData()
virtual void web::websocket::Receiver::onMessageData (const char * chunk, uint64_t chunkLen) private pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by readPayload().
onMessageEnd()
virtual void web::websocket::Receiver::onMessageEnd () private pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by readLength(), readMaskingKey(), and readPayload().
onMessageError()
virtual void web::websocket::Receiver::onMessageError (uint16_t errnum) private pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by receive().
onMessageStart()
virtual void web::websocket::Receiver::onMessageStart (int opCode) private pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by readOpcode().
operator=()
Receiver & web::websocket::Receiver::operator= (const Receiver &) delete
readELength()
std::size_t web::websocket::Receiver::readELength () private
Definition at line 206 of file Receiver.cpp.
{
        std::size_t ret = 0;
        switch (elengthNumBytes) {
            case 2:
                ret = readELength2();
                break;
            case 8:
                ret = readELength8();
                break;
        }
        if (elengthNumBytesLeft == 0) {
            if ((payLoadNumBytes & static_cast<uint64_t>(0x01) << 63) != 0) {
                parserState = ParserState::ERROR;
                errorState = 1004;
            } else if (masked) {
                parserState = ParserState::MASKINGKEY;
            } else {
                parserState = ParserState::PAYLOAD;
            }
        }
        return ret;
    }
References elengthNumBytes, elengthNumBytesLeft, ERROR, errorState, masked, MASKINGKEY, PAYLOAD, payLoadNumBytes, readELength2(), and readELength8().
Referenced by receive().
readELength2()
std::size_t web::websocket::Receiver::readELength2 () private
Definition at line 170 of file Receiver.cpp.
{
        char elengthChunk[2];
        const std::size_t ret = readFrameData(elengthChunk, elengthNumBytesLeft);
        const std::size_t cursor = static_cast<std::size_t>(elengthNumBytes - elengthNumBytesLeft);
        for (std::size_t i = 0; i < ret; i++) {
            eLength2.asBytes[cursor + i] = elengthChunk[i];
            elengthNumBytesLeft--;
        }
        if (elengthNumBytesLeft == 0) {
            payLoadNumBytes = payLoadNumBytesLeft = be16toh(eLength2.asValue);
        }
        return ret;
    }
References web::websocket::Receiver::ELength2::asBytes, web::websocket::Receiver::ELength2::asValue, elengthNumBytes, elengthNumBytesLeft, payLoadNumBytes, payLoadNumBytesLeft, and readFrameData().
Referenced by readELength().
readELength8()
std::size_t web::websocket::Receiver::readELength8 () private
Definition at line 188 of file Receiver.cpp.
{
        char elengthChunk[8];
        const std::size_t ret = readFrameData(elengthChunk, elengthNumBytesLeft);
        const std::size_t cursor = static_cast<std::size_t>(elengthNumBytes - elengthNumBytesLeft);
        for (std::size_t i = 0; i < ret; i++) {
            eLength8.asBytes[cursor + i] = elengthChunk[i];
            elengthNumBytesLeft--;
        }
        if (elengthNumBytesLeft == 0) {
            payLoadNumBytes = payLoadNumBytesLeft = be64toh(eLength8.asValue);
        }
        return ret;
    }
References web::websocket::Receiver::ELength8::asBytes, web::websocket::Receiver::ELength8::asValue, elengthNumBytes, elengthNumBytesLeft, payLoadNumBytes, payLoadNumBytesLeft, and readFrameData().
Referenced by readELength().
readFrameData()
std::size_t web::websocket::Receiver::readFrameData (char * chunk, std::size_t chunkLen) private
Definition at line 166 of file Receiver.cpp.
{
        return socketConnection->readFromPeer(chunk, chunkLen);
    }
References core::socket::stream::SocketConnection::readFromPeer(), and socketConnection.
Referenced by readELength2(), readELength8(), readLength(), readMaskingKey(), readOpcode(), and readPayload().
readLength()
std::size_t web::websocket::Receiver::readLength () private
Definition at line 128 of file Receiver.cpp.
{
        char byte = 0;
        const std::size_t ret = readFrameData(&byte, 1);
        if (ret > 0) {
            const uint8_t lengthByte = static_cast<uint8_t>(byte);
            masked = (lengthByte & 0b10000000) != 0;
            payLoadNumBytes = payLoadNumBytesLeft = lengthByte & 0b01111111;
            if (payLoadNumBytes > 125) {
                switch (payLoadNumBytes) {
                    case 126:
                        elengthNumBytes = elengthNumBytesLeft = 2;
                        break;
                    case 127:
                        elengthNumBytes = elengthNumBytesLeft = 8;
                        break;
                }
                parserState = ParserState::ELENGTH;
                payLoadNumBytes = payLoadNumBytesLeft = 0;
            } else {
                if (masked) {
                    parserState = ParserState::MASKINGKEY;
                } else if (payLoadNumBytes > 0) {
                    parserState = ParserState::PAYLOAD;
                } else {
                    if (fin) {
                        onMessageEnd();
                    }
                    reset();
                }
            }
        }
        return ret;
    }
References ELENGTH, elengthNumBytes, elengthNumBytesLeft, fin, masked, MASKINGKEY, onMessageEnd(), PAYLOAD, payLoadNumBytes, payLoadNumBytesLeft, readFrameData(), and reset().
Referenced by receive().
readMaskingKey()
std::size_t web::websocket::Receiver::readMaskingKey () private
Definition at line 232 of file Receiver.cpp.
{
        char maskingKeyChunk[4]{};
        const std::size_t ret = readFrameData(maskingKeyChunk, maskingKeyNumBytesLeft);
        const std::size_t cursor = static_cast<std::size_t>(maskingKeyNumBytes - maskingKeyNumBytesLeft);
        for (std::size_t i = 0; i < ret; i++) {
            maskingKey[cursor + i] = maskingKeyChunk[i];
            maskingKeyNumBytesLeft -= 1;
        }
        if (maskingKeyNumBytesLeft == 0) {
            if (payLoadNumBytes > 0) {
                parserState = ParserState::PAYLOAD;
            } else {
                if (fin) {
                    onMessageEnd();
                }
                reset();
            }
        }
        return ret;
    }
References fin, maskingKey, maskingKeyNumBytes, maskingKeyNumBytesLeft, onMessageEnd(), PAYLOAD, payLoadNumBytes, readFrameData(), and reset().
Referenced by receive().
readOpcode()
std::size_t web::websocket::Receiver::readOpcode () private
Definition at line 102 of file Receiver.cpp.
{
        char byte = 0;
        const std::size_t ret = readFrameData(&byte, 1);
        if (ret > 0) {
            const uint8_t opCodeByte = static_cast<uint8_t>(byte);
            fin = (opCodeByte & 0b10000000) != 0;
            opCode = opCodeByte & 0b00001111;
            if (!continuation) {
                onMessageStart(opCode);
                parserState = ParserState::LENGTH;
            } else if (opCode == 0) {
                parserState = ParserState::LENGTH;
            } else {
                parserState = ParserState::ERROR;
                errorState = 1002;
                LOG(ERROR) << "WebSocket: Error opcode in continuation frame";
            }
            continuation = !fin;
        }
        return ret;
    }
References continuation, ERROR, errorState, fin, LENGTH, onMessageStart(), opCode, and readFrameData().
Referenced by receive().
readPayload()
std::size_t web::websocket::Receiver::readPayload () private
Definition at line 257 of file Receiver.cpp.
{
        char payloadChunk[MAX_PAYLOAD_JUNK_LEN]{};
        const std::size_t payloadChunkLeft = (MAX_PAYLOAD_JUNK_LEN <= payLoadNumBytesLeft) ? static_cast<std::size_t>(MAX_PAYLOAD_JUNK_LEN)
                                                                                           : static_cast<std::size_t>(payLoadNumBytesLeft);
        const std::size_t ret = readFrameData(payloadChunk, payloadChunkLeft);
        if (ret > 0) {
            const std::size_t payloadChunkLen = static_cast<std::size_t>(ret);
            if (masked) {
                for (std::size_t i = 0; i < payloadChunkLen; i++) {
                    *(payloadChunk + i) = *(payloadChunk + i) ^ *(maskingKey + (i + payLoadNumBytes - payLoadNumBytesLeft) % 4);
                }
            }
            LOG(TRACE) << "WebSocket receive: Frame data\n" << utils::hexDump(payloadChunk, payloadChunkLen, 32, true);
            onMessageData(payloadChunk, payloadChunkLen);
            payLoadNumBytesLeft -= payloadChunkLen;
        }
        if (payLoadNumBytesLeft == 0) {
            if (fin) {
                onMessageEnd();
            }
            reset();
        }
        return ret;
    }
References fin, utils::hexDump(), masked, maskingKey, onMessageData(), onMessageEnd(), payLoadNumBytes, payLoadNumBytesLeft, readFrameData(), and reset().
Referenced by receive().
receive()
std::size_t web::websocket::Receiver::receive ()
Definition at line 65 of file Receiver.cpp.
{
        std::size_t ret = 0;
        std::size_t consumed = 0;
        // dumpFrame(chunk, chunkLen);
        do {
            switch (parserState) {
                case ParserState::BEGIN:
                    parserState = ParserState::OPCODE;
                    [[fallthrough]];
                case ParserState::OPCODE:
                    ret = readOpcode();
                    break;
                case ParserState::LENGTH:
                    ret = readLength();
                    break;
                case ParserState::ELENGTH:
                    ret = readELength();
                    break;
                case ParserState::MASKINGKEY:
                    ret = readMaskingKey();
                    break;
                case ParserState::PAYLOAD:
                    ret = readPayload();
                    break;
                case ParserState::ERROR:
                    onMessageError(errorState);
                    reset();
                    break;
            }
            consumed += ret;
        } while (ret > 0 && parserState != ParserState::BEGIN && parserState != ParserState::ERROR);
        return consumed;
    }
References BEGIN, ELENGTH, ERROR, errorState, LENGTH, MASKINGKEY, onMessageError(), OPCODE, PAYLOAD, readELength(), readLength(), readMaskingKey(), readOpcode(), readPayload(), and reset().
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onReceivedFromPeer().
reset()
void web::websocket::Receiver::reset () private
Definition at line 290 of file Receiver.cpp.
{
        parserState = ParserState::BEGIN;
        fin = false;
        continuation = false;
        masked = false;
        opCode = 0;
        elengthNumBytes = 0;
        elengthNumBytesLeft = 0;
        payLoadNumBytes = 0;
        payLoadNumBytesLeft = 0;
        maskingKeyNumBytes = 4;
        maskingKeyNumBytesLeft = 4;
        errorState = 0;
    }
References BEGIN, continuation, elengthNumBytes, elengthNumBytesLeft, errorState, fin, masked, maskingKeyNumBytes, maskingKeyNumBytesLeft, opCode, payLoadNumBytes, and payLoadNumBytesLeft.
Referenced by readLength(), readMaskingKey(), readPayload(), and receive().
Member Data Documentation
continuation
bool web::websocket::Receiver::continuation = false private
Definition at line 98 of file Receiver.h.
Referenced by readOpcode(), and reset().
eLength2
union web::websocket::Receiver::ELength2 web::websocket::Receiver::eLength2 private
eLength8
union web::websocket::Receiver::ELength8 web::websocket::Receiver::eLength8 private
elengthNumBytes
uint8_t web::websocket::Receiver::elengthNumBytes = 0 private
Definition at line 115 of file Receiver.h.
Referenced by readELength(), readELength2(), readELength8(), readLength(), and reset().
elengthNumBytesLeft
uint8_t web::websocket::Receiver::elengthNumBytesLeft = 0 private
Definition at line 116 of file Receiver.h.
Referenced by readELength(), readELength2(), readELength8(), readLength(), and reset().
errorState
uint16_t web::websocket::Receiver::errorState = 0 private
Definition at line 124 of file Receiver.h.
Referenced by readELength(), readOpcode(), receive(), and reset().
fin
bool web::websocket::Receiver::fin = false private
Definition at line 97 of file Receiver.h.
Referenced by readLength(), readMaskingKey(), readOpcode(), readPayload(), and reset().
masked
bool web::websocket::Receiver::masked = false private
Definition at line 99 of file Receiver.h.
Referenced by readELength(), readLength(), readPayload(), and reset().
maskingKey
char web::websocket::Receiver::maskingKey[4] private
Definition at line 103 of file Receiver.h.
Referenced by readMaskingKey(), and readPayload().
maskingKeyNumBytes
uint8_t web::websocket::Receiver::maskingKeyNumBytes = 4 private
Definition at line 121 of file Receiver.h.
Referenced by readMaskingKey(), and reset().
maskingKeyNumBytesLeft
uint8_t web::websocket::Receiver::maskingKeyNumBytesLeft = 4 private
Definition at line 122 of file Receiver.h.
Referenced by readMaskingKey(), and reset().
opCode
uint8_t web::websocket::Receiver::opCode = 0 private
Definition at line 101 of file Receiver.h.
Referenced by readOpcode(), and reset().
parserState
enum web::websocket::Receiver::ParserState web::websocket::Receiver::parserState = ParserState::BEGIN private
payLoadNumBytes
uint64_t web::websocket::Receiver::payLoadNumBytes = 0 private
Definition at line 118 of file Receiver.h.
Referenced by readELength(), readELength2(), readELength8(), readLength(), readMaskingKey(), readPayload(), and reset().
payLoadNumBytesLeft
uint64_t web::websocket::Receiver::payLoadNumBytesLeft = 0 private
Definition at line 119 of file Receiver.h.
Referenced by readELength2(), readELength8(), readLength(), readPayload(), and reset().
socketConnection
core::socket::stream::SocketConnection* web::websocket::Receiver::socketConnection = nullptr private
Definition at line 126 of file Receiver.h.
Referenced by readFrameData(), and Receiver().
The documentation for this class was generated from the following files:
web/websocket/Receiver.h
web/websocket/Receiver.cpp