SNode.C: iot::mqtt::server::packets::Puback Class Reference
iot::mqtt::server::packets::Puback Class Reference
#include <Puback.h>
Public Member Functions
Puback (uint32_t remainingLength, uint8_t flags)
Public Member Functions inherited from iot::mqtt::packets::Puback
Puback ()
Puback (const uint16_t packetIdentifier)
uint16_t getPacketIdentifier () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type)
ControlPacket (const ControlPacket &)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
std::vector< char > serialize () const
uint8_t getType () const
uint8_t getFlags () const
Public Member Functions inherited from iot::mqtt::server::ControlPacketDeserializer
~ControlPacketDeserializer () override
Public Member Functions inherited from iot::mqtt::ControlPacketDeserializer
ControlPacketDeserializer ()=default
ControlPacketDeserializer (uint32_t remainingLength, uint8_t flags, uint8_t mustFlags)
ControlPacketDeserializer & operator= (const ControlPacketDeserializer &)=default
std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
uint32_t getRemainingLength () const
bool isComplete () const
bool isError () const
std::size_t getConsumed () const
Private Member Functions
std::size_t deserializeVP (iot::mqtt::MqttContext *mqttContext) override
void deliverPacket (iot::mqtt::server::Mqtt *mqtt) override
Additional Inherited Members
Protected Attributes inherited from iot::mqtt::packets::Puback
iot::mqtt::types::UInt16 packetIdentifier
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t type = 0
uint8_t flags = 0
Protected Attributes inherited from iot::mqtt::ControlPacketDeserializer
bool complete = false
bool error = false
uint32_t remainingLength = 0
std::size_t consumed = 0
Detailed Description
Definition at line 38 of file Puback.h.
Constructor & Destructor Documentation
Puback()
iot::mqtt::server::packets::Puback::Puback (uint32_t remainingLength, uint8_t flags)
Definition at line 29 of file Puback.cpp.
        : iot::mqtt::server::ControlPacketDeserializer(remainingLength, flags, MQTT_PUBACK_FLAGS) {
        this->flags = flags;
    }
References iot::mqtt::ControlPacket::flags.
Referenced by iot::mqtt::server::Mqtt::createControlPacketDeserializer().
Member Function Documentation
deliverPacket()
void iot::mqtt::server::packets::Puback::deliverPacket (iot::mqtt::server::Mqtt * mqtt) override private virtual
Implements iot::mqtt::server::ControlPacketDeserializer.
Definition at line 44 of file Puback.cpp.
{
        mqtt->_onPuback(*this);
    }
References iot::mqtt::Mqtt::_onPuback().
deserializeVP()
std::size_t iot::mqtt::server::packets::Puback::deserializeVP (iot::mqtt::MqttContext * mqttContext) override private virtual
Implements iot::mqtt::ControlPacketDeserializer.
Definition at line 34 of file Puback.cpp.
{
        // V-Header
        std::size_t consumed = packetIdentifier.deserialize(mqttContext);
        complete = packetIdentifier.isComplete();
        // no Payload
        return consumed;
    }
References iot::mqtt::ControlPacketDeserializer::complete, iot::mqtt::types::TypeBase< ValueTypeT >::deserialize(), iot::mqtt::types::TypeBase< ValueTypeT >::isComplete(), and iot::mqtt::packets::Puback::packetIdentifier.
The documentation for this class was generated from the following files:
iot/mqtt/server/packets/Puback.h
iot/mqtt/server/packets/Puback.cpp