SNode.C: iot::mqtt::server::packets::Publish Class Reference
iot::mqtt::server::packets::Publish Class Reference
#include <Publish.h>
Public Member Functions
Publish (uint32_t remainingLength, uint8_t flags)
bool getDup () const
uint8_t getQoS () const
uint16_t getPacketIdentifier () const
std::string getTopic () const
std::string getMessage () const
bool getRetain () const
std::vector< char > serialize () const
const std::string & getName () const
uint8_t getType () const
uint8_t getFlags () const
std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
uint32_t getRemainingLength () const
bool isComplete () const
bool isError () const
std::size_t getConsumed () const
Protected Attributes
iot::mqtt::types::UInt16 packetIdentifier
iot::mqtt::types::String topic
iot::mqtt::types::StringRaw message
bool dup = false
uint8_t qoS = 0
bool retain = false
uint8_t flags = 0
bool complete = false
bool error = false
uint32_t remainingLength = 0
std::size_t consumed = 0
Private Member Functions
std::size_t deserializeVP (iot::mqtt::MqttContext *mqttContext) override
void deliverPacket (iot::mqtt::server::Mqtt *mqtt) override
std::vector< char > serializeVP () const override
Private Attributes
int state = 0
std::string name
uint8_t type = 0
Detailed Description
Definition at line 41 of file Publish.h.
Constructor & Destructor Documentation
Publish()
iot::mqtt::server::packets::Publish::Publish (uint32_t remainingLength, uint8_t flags)
Definition at line 30 of file Publish.cpp.
        : iot::mqtt::server::ControlPacketDeserializer(remainingLength, flags, flags) {
        this->flags = flags;
        this->qoS = flags >> 1 & 0x03;
        this->dup = (flags & 0x08) != 0;
        this->retain = (flags & 0x01) != 0;
        error = this->qoS > 2;
    }
References iot::mqtt::packets::Publish::dup, iot::mqtt::ControlPacketDeserializer::error, iot::mqtt::ControlPacket::flags, iot::mqtt::packets::Publish::qoS, and iot::mqtt::packets::Publish::retain.
Referenced by iot::mqtt::server::Mqtt::createControlPacketDeserializer().
Member Function Documentation
deliverPacket()
void iot::mqtt::server::packets::Publish::deliverPacket (iot::mqtt::server::Mqtt * mqtt) override private virtual
Implements iot::mqtt::server::ControlPacketDeserializer.
Definition at line 77 of file Publish.cpp.
{
        mqtt->printVP(*this);
        mqtt->_onPublish(*this);
    }
References iot::mqtt::server::Mqtt::_onPublish(), and iot::mqtt::Mqtt::printVP().
deserialize()
std::size_t iot::mqtt::ControlPacketDeserializer::deserialize (iot::mqtt::MqttContext * mqttContext) inherited
Definition at line 36 of file ControlPacketDeserializer.cpp.
{
        const std::size_t currentConsumed = deserializeVP(mqttContext);
        consumed += currentConsumed;
        error = (complete && consumed != this->getRemainingLength()) || (!complete && consumed >= this->getRemainingLength());
        return currentConsumed;
    }
References iot::mqtt::ControlPacketDeserializer::complete, iot::mqtt::ControlPacketDeserializer::consumed, iot::mqtt::ControlPacketDeserializer::deserializeVP(), iot::mqtt::ControlPacketDeserializer::error, and iot::mqtt::ControlPacketDeserializer::getRemainingLength().
deserializeVP()
std::size_t iot::mqtt::server::packets::Publish::deserializeVP (iot::mqtt::MqttContext * mqttContext) override private virtual
Implements iot::mqtt::ControlPacketDeserializer.
Definition at line 40 of file Publish.cpp.
{
        std::size_t consumed = 0;
        switch (state) {
            case 0: // V-Header
                consumed += topic.deserialize(mqttContext);
                if (!topic.isComplete()) {
                    break;
                }
                state++;
                [[fallthrough]];
            case 1:
                if (qoS > 0) {
                    consumed += packetIdentifier.deserialize(mqttContext);
                    if (!packetIdentifier.isComplete()) {
                        break;
                    }
                }
                message.setSize(static_cast<uint16_t>(getRemainingLength() - getConsumed() - consumed));
                state++;
                [[fallthrough]];
            case 2: // Payload
                consumed += message.deserialize(mqttContext);
                if (!message.isComplete()) {
                    break;
                }
                complete = true;
                break;
        }
        return consumed;
    }
References iot::mqtt::ControlPacketDeserializer::complete, iot::mqtt::types::TypeBase< ValueTypeT >::deserialize(), iot::mqtt::types::String::deserialize(), iot::mqtt::ControlPacketDeserializer::getConsumed(), iot::mqtt::ControlPacketDeserializer::getRemainingLength(), iot::mqtt::types::TypeBase< ValueTypeT >::isComplete(), iot::mqtt::packets::Publish::message, iot::mqtt::packets::Publish::packetIdentifier, iot::mqtt::packets::Publish::qoS, iot::mqtt::types::TypeBase< ValueTypeT >::setSize(), state, and iot::mqtt::packets::Publish::topic.
getConsumed()
std::size_t iot::mqtt::ControlPacketDeserializer::getConsumed () const inherited
Definition at line 57 of file ControlPacketDeserializer.cpp.
{
        return consumed;
    }
References iot::mqtt::ControlPacketDeserializer::consumed.
Referenced by iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::client::packets::Suback::deserializeVP(), deserializeVP(), iot::mqtt::server::packets::Subscribe::deserializeVP(), and iot::mqtt::server::packets::Unsubscribe::deserializeVP().
getDup()
bool iot::mqtt::packets::Publish::getDup () const inherited
Definition at line 57 of file Publish.cpp.
{
        return dup;
    }
References iot::mqtt::packets::Publish::dup.
Referenced by iot::mqtt::Mqtt::_onPublish(), and iot::mqtt::Session::toJson().
getFlags()
uint8_t iot::mqtt::ControlPacket::getFlags () const inherited
Definition at line 119 of file ControlPacket.cpp.
{
        return flags;
    }
References iot::mqtt::ControlPacket::flags.
getMessage()
std::string iot::mqtt::packets::Publish::getMessage () const inherited
Definition at line 73 of file Publish.cpp.
{
        return message;
    }
References iot::mqtt::packets::Publish::message.
Referenced by iot::mqtt::Mqtt::_onPublish(), iot::mqtt::server::Mqtt::_onPublish(), and iot::mqtt::Session::toJson().
getName()
const std::string & iot::mqtt::ControlPacket::getName () const inherited
Definition at line 100 of file ControlPacket.cpp.
{
        return name;
    }
References iot::mqtt::ControlPacket::name.
Referenced by iot::mqtt::Mqtt::printVP(), and iot::mqtt::Mqtt::send().
getPacketIdentifier()
uint16_t iot::mqtt::packets::Publish::getPacketIdentifier () const inherited
Definition at line 65 of file Publish.cpp.
{
        return packetIdentifier;
    }
References iot::mqtt::packets::Publish::packetIdentifier.
Referenced by iot::mqtt::Mqtt::_onPublish().
getQoS()
uint8_t iot::mqtt::packets::Publish::getQoS () const inherited
Definition at line 61 of file Publish.cpp.
{
        return qoS;
    }
References iot::mqtt::packets::Publish::qoS.
Referenced by iot::mqtt::Mqtt::_onPublish(), iot::mqtt::server::Mqtt::_onPublish(), and iot::mqtt::Session::toJson().
getRemainingLength()
uint32_t iot::mqtt::ControlPacketDeserializer::getRemainingLength () const inherited
Definition at line 45 of file ControlPacketDeserializer.cpp.
{
        return remainingLength;
    }
References iot::mqtt::ControlPacketDeserializer::remainingLength.
Referenced by iot::mqtt::ControlPacketDeserializer::deserialize(), iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::client::packets::Suback::deserializeVP(), deserializeVP(), iot::mqtt::server::packets::Subscribe::deserializeVP(), and iot::mqtt::server::packets::Unsubscribe::deserializeVP().
getRetain()
bool iot::mqtt::packets::Publish::getRetain () const inherited
Definition at line 77 of file Publish.cpp.
{
        return retain;
    }
References iot::mqtt::packets::Publish::retain.
Referenced by iot::mqtt::Mqtt::_onPublish(), iot::mqtt::server::Mqtt::_onPublish(), and iot::mqtt::Session::toJson().
getTopic()
std::string iot::mqtt::packets::Publish::getTopic () const inherited
Definition at line 69 of file Publish.cpp.
{
        return topic;
    }
References iot::mqtt::packets::Publish::topic.
Referenced by iot::mqtt::Mqtt::_onPublish(), iot::mqtt::server::Mqtt::_onPublish(), and iot::mqtt::Session::toJson().
getType()
uint8_t iot::mqtt::ControlPacket::getType () const inherited
Definition at line 115 of file ControlPacket.cpp.
{
        return type;
    }
References iot::mqtt::ControlPacket::type.
isComplete()
bool iot::mqtt::ControlPacketDeserializer::isComplete () const inherited
Definition at line 49 of file ControlPacketDeserializer.cpp.
{
        return complete;
    }
References iot::mqtt::ControlPacketDeserializer::complete.
isError()
bool iot::mqtt::ControlPacketDeserializer::isError () const inherited
Definition at line 53 of file ControlPacketDeserializer.cpp.
{
        return error;
    }
References iot::mqtt::ControlPacketDeserializer::error.
serialize()
std::vector< char > iot::mqtt::ControlPacket::serialize () const inherited
Definition at line 104 of file ControlPacket.cpp.
{
        std::vector<char> variablHeaderPayload = serializeVP();
        const iot::mqtt::FixedHeader fixedHeader(type, flags, static_cast<uint32_t>(variablHeaderPayload.size()));
        std::vector<char> packet = fixedHeader.serialize();
        packet.insert(packet.end(), variablHeaderPayload.begin(), variablHeaderPayload.end());
        return packet;
    }
References iot::mqtt::FixedHeader::FixedHeader(), iot::mqtt::ControlPacket::flags, iot::mqtt::FixedHeader::serialize(), iot::mqtt::ControlPacket::serializeVP(), and iot::mqtt::ControlPacket::type.
Referenced by iot::mqtt::Mqtt::send().
serializeVP()
std::vector< char > iot::mqtt::packets::Publish::serializeVP () const override private virtual inherited
Implements iot::mqtt::ControlPacket.
Definition at line 43 of file Publish.cpp.
{
        std::vector<char> packet(topic.serialize());
        if (qoS > 0) {
            std::vector<char> tmpVector = packetIdentifier.serialize();
            packet.insert(packet.end(), tmpVector.begin(), tmpVector.end());
        }
        std::vector<char> tmpVector = message.serialize();
        packet.insert(packet.end(), tmpVector.begin(), tmpVector.end());
        return packet;
    }
References iot::mqtt::packets::Publish::message, iot::mqtt::packets::Publish::packetIdentifier, iot::mqtt::packets::Publish::qoS, iot::mqtt::types::TypeBase< ValueTypeT >::serialize(), iot::mqtt::types::String::serialize(), and iot::mqtt::packets::Publish::topic.
Member Data Documentation
complete
bool iot::mqtt::ControlPacketDeserializer::complete = false protected inherited
Definition at line 60 of file ControlPacketDeserializer.h.
Referenced by iot::mqtt::ControlPacketDeserializer::deserialize(), iot::mqtt::client::packets::Connack::deserializeVP(), iot::mqtt::client::packets::Pingresp::deserializeVP(), iot::mqtt::client::packets::Puback::deserializeVP(), iot::mqtt::client::packets::Pubcomp::deserializeVP(), iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::client::packets::Pubrec::deserializeVP(), iot::mqtt::client::packets::Pubrel::deserializeVP(), iot::mqtt::client::packets::Suback::deserializeVP(), iot::mqtt::client::packets::Unsuback::deserializeVP(), iot::mqtt::server::packets::Connect::deserializeVP(), iot::mqtt::server::packets::Disconnect::deserializeVP(), iot::mqtt::server::packets::Puback::deserializeVP(), iot::mqtt::server::packets::Pubcomp::deserializeVP(), deserializeVP(), iot::mqtt::server::packets::Pubrec::deserializeVP(), iot::mqtt::server::packets::Pubrel::deserializeVP(), iot::mqtt::server::packets::Subscribe::deserializeVP(), iot::mqtt::server::packets::Unsubscribe::deserializeVP(), iot::mqtt::server::packets::Pingreq::deserializeVP(), and iot::mqtt::ControlPacketDeserializer::isComplete().
consumed
std::size_t iot::mqtt::ControlPacketDeserializer::consumed = 0 protected inherited
Definition at line 65 of file ControlPacketDeserializer.h.
Referenced by iot::mqtt::ControlPacketDeserializer::deserialize(), and iot::mqtt::ControlPacketDeserializer::getConsumed().
dup
bool iot::mqtt::packets::Publish::dup = false protected inherited
Definition at line 60 of file Publish.h.
Referenced by iot::mqtt::packets::Publish::getDup(), iot::mqtt::packets::Publish::Publish(), iot::mqtt::client::packets::Publish::Publish(), and Publish().
error
bool iot::mqtt::ControlPacketDeserializer::error = false protected inherited
Definition at line 61 of file ControlPacketDeserializer.h.
Referenced by iot::mqtt::ControlPacketDeserializer::ControlPacketDeserializer(), iot::mqtt::ControlPacketDeserializer::deserialize(), iot::mqtt::ControlPacketDeserializer::isError(), iot::mqtt::client::packets::Publish::Publish(), and Publish().
flags
uint8_t iot::mqtt::ControlPacket::flags = 0 protected inherited
Definition at line 92 of file ControlPacket.h.
Referenced by iot::mqtt::client::packets::Connack::Connack(), iot::mqtt::server::packets::Connect::Connect(), iot::mqtt::ControlPacket::ControlPacket(), iot::mqtt::server::packets::Disconnect::Disconnect(), iot::mqtt::ControlPacket::getFlags(), iot::mqtt::server::packets::Pingreq::Pingreq(), iot::mqtt::client::packets::Pingresp::Pingresp(), iot::mqtt::client::packets::Puback::Puback(), iot::mqtt::server::packets::Puback::Puback(), iot::mqtt::client::packets::Pubcomp::Pubcomp(), iot::mqtt::server::packets::Pubcomp::Pubcomp(), iot::mqtt::packets::Publish::Publish(), iot::mqtt::client::packets::Publish::Publish(), Publish(), iot::mqtt::client::packets::Pubrec::Pubrec(), iot::mqtt::server::packets::Pubrec::Pubrec(), iot::mqtt::client::packets::Pubrel::Pubrel(), iot::mqtt::server::packets::Pubrel::Pubrel(), iot::mqtt::ControlPacket::serialize(), iot::mqtt::client::packets::Suback::Suback(), iot::mqtt::server::packets::Subscribe::Subscribe(), iot::mqtt::client::packets::Unsuback::Unsuback(), and iot::mqtt::server::packets::Unsubscribe::Unsubscribe().
message
iot::mqtt::types::StringRaw iot::mqtt::packets::Publish::message protected inherited
Definition at line 58 of file Publish.h.
Referenced by iot::mqtt::client::packets::Publish::deserializeVP(), deserializeVP(), iot::mqtt::packets::Publish::getMessage(), iot::mqtt::packets::Publish::Publish(), and iot::mqtt::packets::Publish::serializeVP().
name
std::string iot::mqtt::ControlPacket::name private inherited
Definition at line 88 of file ControlPacket.h.
Referenced by iot::mqtt::ControlPacket::ControlPacket(), and iot::mqtt::ControlPacket::getName().
packetIdentifier
iot::mqtt::types::UInt16 iot::mqtt::packets::Publish::packetIdentifier protected inherited
Definition at line 56 of file Publish.h.
Referenced by iot::mqtt::client::packets::Publish::deserializeVP(), deserializeVP(), iot::mqtt::packets::Publish::getPacketIdentifier(), iot::mqtt::packets::Publish::Publish(), and iot::mqtt::packets::Publish::serializeVP().
qoS
uint8_t iot::mqtt::packets::Publish::qoS = 0 protected inherited
Definition at line 61 of file Publish.h.
Referenced by iot::mqtt::client::packets::Publish::deserializeVP(), deserializeVP(), iot::mqtt::packets::Publish::getQoS(), iot::mqtt::packets::Publish::Publish(), iot::mqtt::client::packets::Publish::Publish(), Publish(), and iot::mqtt::packets::Publish::serializeVP().
remainingLength
uint32_t iot::mqtt::ControlPacketDeserializer::remainingLength = 0 protected inherited
Definition at line 63 of file ControlPacketDeserializer.h.
Referenced by iot::mqtt::ControlPacketDeserializer::ControlPacketDeserializer(), and iot::mqtt::ControlPacketDeserializer::getRemainingLength().
retain
bool iot::mqtt::packets::Publish::retain = false protected inherited
Definition at line 62 of file Publish.h.
Referenced by iot::mqtt::packets::Publish::getRetain(), iot::mqtt::packets::Publish::Publish(), iot::mqtt::client::packets::Publish::Publish(), and Publish().
state
int iot::mqtt::server::packets::Publish::state = 0 private
Definition at line 51 of file Publish.h.
Referenced by deserializeVP().
topic
iot::mqtt::types::String iot::mqtt::packets::Publish::topic protected inherited
Definition at line 57 of file Publish.h.
Referenced by iot::mqtt::client::packets::Publish::deserializeVP(), deserializeVP(), iot::mqtt::packets::Publish::getTopic(), iot::mqtt::packets::Publish::Publish(), and iot::mqtt::packets::Publish::serializeVP().
type
uint8_t iot::mqtt::ControlPacket::type = 0 private inherited
Definition at line 89 of file ControlPacket.h.
Referenced by iot::mqtt::ControlPacket::ControlPacket(), iot::mqtt::ControlPacket::getType(), and iot::mqtt::ControlPacket::serialize().
The documentation for this class was generated from the following files:
iot/mqtt/server/packets/Publish.h
iot/mqtt/server/packets/Publish.cpp