SNode.C: net::un::phy::stream::PhysicalSocketClient Class Reference
net::un::phy::stream::PhysicalSocketClient Class Reference
#include <PhysicalSocketClient.h>
Public Types
using Super = net::un::phy::stream::PhysicalSocket< net::phy::stream::PhysicalSocketClient >
using Super = net::un::phy::PhysicalSocket< PhysicalPeerSocketT >
using Super = PhysicalPeerSocketT< net::un::SocketAddress >
Public Member Functions
PhysicalSocketClient (PhysicalSocketClient &&) noexcept=default
~PhysicalSocketClient () override
int bind (SocketAddress &bindAddress)
Static Public Member Functions
static bool connectInProgress (int cErrno)
Private Attributes
int lockFd = -1
Detailed Description
Definition at line 34 of file PhysicalSocketClient.h.
Member Typedef Documentation
Super [1/3]
using net::un::phy::stream::PhysicalSocketClient::Super = net::un::phy::stream::PhysicalSocket<net::phy::stream::PhysicalSocketClient>
Definition at line 36 of file PhysicalSocketClient.h.
Super [2/3]
using net::un::phy::stream::PhysicalSocket< PhysicalPeerSocketT >::Super = net::un::phy::PhysicalSocket<PhysicalPeerSocketT>
Definition at line 35 of file PhysicalSocket.h.
Super [3/3]
using net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::Super = PhysicalPeerSocketT<net::un::SocketAddress>
Definition at line 36 of file PhysicalSocket.h.
Constructor & Destructor Documentation
PhysicalSocketClient()
net::un::phy::stream::PhysicalSocketClient::PhysicalSocketClient (PhysicalSocketClient &&) default noexcept
~PhysicalSocketClient()
net::un::phy::stream::PhysicalSocketClient::~PhysicalSocketClient () override
Definition at line 33 of file PhysicalSocketClient.cpp.
{
    }
Member Function Documentation
bind()
template<template< typename SocketAddress > typename PhysicalPeerSocket> int net::un::phy::PhysicalSocket< PhysicalPeerSocket >::bind (SocketAddress & bindAddress) inherited
Definition at line 83 of file PhysicalSocket.hpp.
{
        if (!bindAddress.getSunPath().empty()) {
            if ((lockFd = open(bindAddress.getSunPath().append(".lock").data(), O_RDONLY | O_CREAT, 0600)) >= 0) {
                LOG(TRACE) << "Opening lock file: " << bindAddress.getSunPath().append(".lock").data();
                if (core::system::flock(lockFd, LOCK_EX | LOCK_NB) == 0) {
                    LOG(TRACE) << "Locking lock file: " << bindAddress.getSunPath().append(".lock").data();
                    if (std::filesystem::exists(bindAddress.getSunPath().data())) {
                        if (std::remove(bindAddress.getSunPath().data()) == 0) {
                            LOG(TRACE) << "Removed stalled sun_path: " << bindAddress.getSunPath().data();
                        } else {
                            PLOG(TRACE) << "Removed stalled sun path: " << bindAddress.getSunPath().data();
                        }
                    }
                } else {
                    PLOG(TRACE) << "Locking lock file " << bindAddress.getSunPath().append(".lock").data();
                    core::system::close(lockFd);
                    lockFd = -1;
                }
            } else {
                PLOG(TRACE) << "Opening lock file: " << bindAddress.getSunPath().append(".lock").data();
            }
        }
        return Super::bind(bindAddress);
    }
References core::system::close(), core::system::flock(), net::un::SocketAddress::getSunPath(), and net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::lockFd.
connectInProgress()
bool net::un::phy::stream::PhysicalSocketClient::connectInProgress (int cErrno) static
Definition at line 36 of file PhysicalSocketClient.cpp.
{
        return cErrno == EAGAIN;
    }
Member Data Documentation
lockFd
template<template< typename SocketAddressT > typename PhysicalPeerSocketT> int net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::lockFd = -1 private inherited
Definition at line 48 of file PhysicalSocket.h.
Referenced by net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::bind(), net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::operator=(), and net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::~PhysicalSocket().
The documentation for this class was generated from the following files:
net/un/phy/stream/PhysicalSocketClient.h
net/un/phy/stream/PhysicalSocketClient.cpp