SNode.C: Test Class Reference
Test Class Reference
Public Member Functions
Test ()
Test (int a, int b)
Test (Test &&test) noexcept
Test (const Test &test)
Test & operator= (Test &&test) noexcept
Test & operator= (const Test &test)
void print (const std::string &message) const
Test ()
Test (int a, int b)
Test (Test &&test) noexcept
Test (const Test &test)
Test & operator= (Test &&test) noexcept
Test & operator= (const Test &test)
void print (const std::string &message) const
Public Attributes
Member member
Detailed Description
Definition at line 143 of file main.cpp.
Constructor & Destructor Documentation
Test() [1/8]
Test::Test () inline
Definition at line 145 of file main.cpp.
           {
        std::cout << "Test()" << std::endl;
    }
Test() [2/8]
Test::Test (int a, int b) inline
Definition at line 149 of file main.cpp.
        : member(a, b) {
        std::cout << "Test(int a, int b)" << std::endl;
    }
References Member::Member(), and member.
Referenced by getTest(), and main().
Test() [3/8]
Test::Test (Test && test) inline noexcept
Definition at line 154 of file main.cpp.
        : member(std::move(test.member)) {
        std::cout << "Test(Test&& test)" << std::endl;
    }
References member.
Test() [4/8]
Test::Test (const Test & test) inline
Definition at line 159 of file main.cpp.
        : member(test.member) {
        std::cout << "Test(const Test& test)" << std::endl;
    }
References Member::Member(), and member.
Referenced by main().
Test() [5/8]
Test::Test () inline
Definition at line 145 of file main.cpp.
           {
        std::cout << "Test()" << std::endl;
    }
Test() [6/8]
Test::Test (int a, int b) inline
Definition at line 149 of file main.cpp.
        : member(a, b) {
        std::cout << "Test(int a, int b)" << std::endl;
    }
Test() [7/8]
Test::Test (Test && test) inline noexcept
Definition at line 154 of file main.cpp.
        : member(std::move(test.member)) {
        std::cout << "Test(Test&& test)" << std::endl;
    }
Test() [8/8]
Test::Test (const Test & test) inline
Definition at line 159 of file main.cpp.
        : member(test.member) {
        std::cout << "Test(const Test& test)" << std::endl;
    }
Member Function Documentation
operator=() [1/4]
Test & Test::operator= (const Test & test) inline
Definition at line 170 of file main.cpp.
{
        std::cout << "Test& operator=(const Test& test)" << std::endl;
        if (this != &test) {
            member = test.member;
        }
        return *this;
    }
References member, and Member::operator=().
Referenced by main().
operator=() [2/4]
Test & Test::operator= (const Test & test) inline
Definition at line 170 of file main.cpp.
{
        std::cout << "Test& operator=(const Test& test)" << std::endl;
        if (this != &test) {
            member = test.member;
        }
        return *this;
    }
operator=() [3/4]
Test & Test::operator= (Test && test) inline noexcept
Definition at line 164 of file main.cpp.
{
        std::cout << "Test& operator=(Test&& test)" << std::endl;
        member = std::move(test.member);
        return *this;
    }
References member.
Referenced by main().
operator=() [4/4]
Test & Test::operator= (Test && test) inline noexcept
Definition at line 164 of file main.cpp.
{
        std::cout << "Test& operator=(Test&& test)" << std::endl;
        member = std::move(test.member);
        return *this;
    }
print() [1/2]
void Test::print (const std::string & message) const inline
Definition at line 178 of file main.cpp.
{
        std::cout << "Message: " << message << std::endl;
        member.print();
        std::cout << "-----------------------------" << std::endl;
    }
References member, and Member::print().
Referenced by main().
print() [2/2]
void Test::print (const std::string & message) const inline
Definition at line 178 of file main.cpp.
{
        std::cout << "Message: " << message << std::endl;
        member.print();
        std::cout << "-----------------------------" << std::endl;
    }
Member Data Documentation
member
Member Test::member
Definition at line 185 of file main.cpp.
Referenced by operator=(), operator=(), print(), Test(), Test(), and Test().
The documentation for this class was generated from the following file:
src/apps/main.cpp