SNode.C: utils::ResetToDefault Class Reference
utils::ResetToDefault Class Reference
#include <ResetToDefault.h>
Public Member Functions
ResetToDefault (CLI::Option *&option)
void operator() (const std::string &value)
void operator() (int64_t count)
Private Attributes
CLI::Option *& option
Detailed Description
Definition at line 35 of file ResetToDefault.h.
Constructor & Destructor Documentation
ResetToDefault()
utils::ResetToDefault::ResetToDefault (CLI::Option *& option) explicit
Definition at line 44 of file ResetToDefault.cpp.
        : option(option) {
    }
References option.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_option(), net::config::ConfigPhysicalSocket::add_socket_option(), utils::Config::add_string_option(), net::config::ConfigInstance::ConfigInstance(), and utils::Config::init().
Member Function Documentation
operator()() [1/2]
void utils::ResetToDefault::operator() (const std::string & value)
Definition at line 48 of file ResetToDefault.cpp.
{
        if (option != nullptr && value == option->get_default_str()) {
            option->take_all()->clear();
        }
    }
References option.
Referenced by net::config::ConfigPhysicalSocket::add_socket_option(), and net::config::ConfigInstance::ConfigInstance().
operator()() [2/2]
void utils::ResetToDefault::operator() (int64_t count)
Definition at line 54 of file ResetToDefault.cpp.
{
        if (option != nullptr && option->as<std::string>() == option->get_default_str()) {
            option->take_all()->clear();
        }
    }
References option.
Member Data Documentation
option
CLI::Option*& utils::ResetToDefault::option private
Definition at line 44 of file ResetToDefault.h.
Referenced by operator()(), operator()(), and ResetToDefault().
The documentation for this class was generated from the following files:
utils/ResetToDefault.h
utils/ResetToDefault.cpp