SNode.C: web::http::server::RequestParser Class Reference
web::http::server::RequestParser Class Reference
#include <RequestParser.h>
Public Member Functions
RequestParser (core::socket::stream::SocketContext *socketContext, const std::function< void()> &onRequestStart, const std::function< void(Request &&)> &onRequestParsed, const std::function< void(int, const std::string &)> &onRequestParseError)
RequestParser (const RequestParser &)=delete
RequestParser & operator= (const RequestParser &)=delete
std::size_t parse ()
void reset ()
Protected Types
enum struct HTTPCompliance : unsigned short {
RFC1945 = 0x01 << 0 , RFC2616 = 0x01 << 1 , RFC7230 = 0x01 << 2 , RFC7231 = 0x01 << 3 ,
RFC7232 = 0x01 << 4 , RFC7233 = 0x01 << 5 , RFC7234 = 0x01 << 6 , RFC7235 = 0x01 << 7 ,
RFC7540 = 0x01 << 8 , RFC7541 = 0x01 << 9
}
enum struct ParserState {
BEGIN , FIRSTLINE , HEADER , BODY ,
ERROR
}
Protected Attributes
enum web::http::Parser::HTTPCompliance hTTPCompliance
TransferEncoding transferEncoding = TransferEncoding::HTTP10
std::size_t contentLength = 0
CiStringMap< std::string > headers
std::vector< char > content
int httpMajor = 0
int httpMinor = 0
std::list< web::http::ContentDecoder * > decoderQueue
core::socket::stream::SocketContext * socketContext = nullptr
Static Protected Attributes
static const std::regex httpVersionRegex
Private Member Functions
virtual bool methodSupported (const std::string &method) const
void begin () override
ParserState parseStartLine (const std::string &line) override
ParserState parseHeader () override
ParserState parseContent (std::vector< char > &content) override
ParserState parsingFinished ()
ParserState parsingError (int code, const std::string &reason) override
std::size_t readStartLine ()
std::size_t readHeaderLine ()
void splitHeaderLine (const std::string &line)
ParserState analyzeHeaders ()
std::size_t readContent ()
Private Attributes
std::set< std::string > supportedMethods {"GET", "PUT", "POST", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH", "HEAD"}
Request request
std::function< void()> onRequestStart
std::function< void(Request &&)> onRequestParsed
std::function< void(int, const std::string &)> onRequestParseError
ParserState parserState = ParserState::BEGIN
bool EOL {false}
std::string line
std::size_t contentRead = 0
Detailed Description
Definition at line 40 of file RequestParser.h.
Member Enumeration Documentation
HTTPCompliance
enum struct web::http::Parser::HTTPCompliance : unsigned short strong protected inherited
Enumerator
RFC1945
RFC2616
RFC7230
RFC7231
RFC7232
RFC7233
RFC7234
RFC7235
RFC7540
RFC7541
Definition at line 49 of file Parser.h.
                                   : unsigned short {
            RFC1945 = 0x01 << 0, // HTTP 1.0
            RFC2616 = 0x01 << 1, // HTTP 1.1
            RFC7230 = 0x01 << 2, // Message Syntax and Routing
            RFC7231 = 0x01 << 3, // Semantics and Content
            RFC7232 = 0x01 << 4, // Conditional Requests
            RFC7233 = 0x01 << 5, // Range Requests
            RFC7234 = 0x01 << 6, // Caching
            RFC7235 = 0x01 << 7, // Authentication
            RFC7540 = 0x01 << 8, // HTTP 2.0
            RFC7541 = 0x01 << 9  // Header Compression
        } hTTPCompliance;
ParserState
enum struct web::http::Parser::ParserState strong protected inherited
Enumerator
BEGIN
FIRSTLINE
HEADER
BODY
ERROR
Definition at line 74 of file Parser.h.
{ BEGIN, FIRSTLINE, HEADER, BODY, ERROR };
Constructor & Destructor Documentation
RequestParser() [1/2]
web::http::server::RequestParser::RequestParser (core::socket::stream::SocketContext * socketContext, const std::function< void()> & onRequestStart, const std::function< void(Request &&)> & onRequestParsed, const std::function< void(int, const std::string &)> & onRequestParseError)
Definition at line 34 of file RequestParser.cpp.
        : Parser(socketContext)
        , onRequestStart(onRequestStart)
        , onRequestParsed(onRequestParsed)
        , onRequestParseError(onRequestParseError) {
    }
References onRequestParsed, onRequestParseError, onRequestStart, and web::http::Parser::Parser().
RequestParser() [2/2]
web::http::server::RequestParser::RequestParser (const RequestParser &) delete
Member Function Documentation
analyzeHeaders()
Parser::ParserState web::http::Parser::analyzeHeaders () private inherited
Definition at line 190 of file Parser.cpp.
{
        if (headers.contains("Content-Length")) {
            contentLength = std::stoul(headers["Content-Length"]);
            transferEncoding = TransferEncoding::Identity;
            decoderQueue.emplace_back(new web::http::decoder::Identity(socketContext, contentLength));
        }
        if (headers.contains("Transfer-Encoding")) {
            const std::string& encoding = headers["Transfer-Encoding"];
            if (web::http::ciContains(encoding, "chunked")) {
                transferEncoding = TransferEncoding::Chunked;
                decoderQueue.emplace_back(new web::http::decoder::Chunked(socketContext));
            }
            if (web::http::ciContains(encoding, "compressed")) {
                //  decoderQueue.emplace_back(new web::http::decoder::Compress(socketContext));
            }
            if (web::http::ciContains(encoding, "deflate")) {
                //  decoderQueue.emplace_back(new web::http::decoder::Deflate(socketContext));
            }
            if (web::http::ciContains(encoding, "gzip")) {
                //  decoderQueue.emplace_back(new web::http::decoder::GZip(socketContext));
            }
        }
        if (decoderQueue.empty()) {
            transferEncoding = TransferEncoding::HTTP10;
            decoderQueue.emplace_back(new web::http::decoder::HTTP10Response(socketContext));
        }
        if (headers.contains("Content-Encoding")) {
            const std::string& encoding = headers["Content-Encoding"];
            if (web::http::ciContains(encoding, "compressed")) {
                //  decoderQueue.emplace_back(new web::http::decoder::Compress(socketContext));
            }
            if (web::http::ciContains(encoding, "deflate")) {
                //  decoderQueue.emplace_back(new web::http::decoder::Deflate(socketContext));
            }
            if (web::http::ciContains(encoding, "gzip")) {
                //  decoderQueue.emplace_back(new web::http::decoder::GZip(socketContext));
            }
            if (web::http::ciContains(encoding, "br")) {
                //  decoderQueue.emplace_back(new web::http::decoder::Br(socketContext));
            }
        }
        return parseHeader();
    }
References web::http::decoder::Chunked::Chunked(), web::http::Chunked, web::http::ciContains(), web::http::Parser::contentLength, web::http::Parser::decoderQueue, web::http::Parser::headers, web::http::HTTP10, web::http::decoder::HTTP10Response::HTTP10Response(), web::http::decoder::Identity::Identity(), web::http::Identity, web::http::Parser::parseHeader(), web::http::Parser::socketContext, and web::http::Parser::transferEncoding.
Referenced by web::http::Parser::readHeaderLine().
begin()
void web::http::server::RequestParser::begin () override private virtual
Implements web::http::Parser.
Definition at line 48 of file RequestParser.cpp.
{
        onRequestStart();
    }
References onRequestStart.
methodSupported()
bool web::http::server::RequestParser::methodSupported (const std::string & method) const private virtual
Definition at line 44 of file RequestParser.cpp.
{
        return supportedMethods.contains(method);
    }
References supportedMethods.
Referenced by parseStartLine().
operator=()
RequestParser & web::http::server::RequestParser::operator= (const RequestParser &) delete
parse()
std::size_t web::http::Parser::parse () inherited
Definition at line 65 of file Parser.cpp.
{
        std::size_t ret = 0;
        std::size_t consumed = 0;
        do {
            switch (parserState) {
                case ParserState::BEGIN:
                    begin();
                    parserState = ParserState::FIRSTLINE;
                    [[fallthrough]];
                case ParserState::FIRSTLINE:
                    ret = readStartLine();
                    break;
                case ParserState::HEADER:
                    ret = readHeaderLine();
                    break;
                case ParserState::BODY:
                    ret = readContent();
                    break;
                case ParserState::ERROR:
                    break;
            }
            consumed += ret;
        } while (ret > 0 && parserState != ParserState::BEGIN && parserState != ParserState::ERROR);
        return consumed;
    }
References web::http::Parser::BEGIN, web::http::Parser::begin(), web::http::Parser::BODY, web::http::Parser::ERROR, web::http::Parser::FIRSTLINE, web::http::Parser::HEADER, web::http::Parser::parserState, web::http::Parser::readContent(), web::http::Parser::readHeaderLine(), and web::http::Parser::readStartLine().
Referenced by web::http::client::SocketContext::onReceivedFromPeer(), and web::http::server::SocketContext::onReceivedFromPeer().
parseContent()
Parser::ParserState web::http::server::RequestParser::parseContent (std::vector< char > & content) override private virtual
Implements web::http::Parser.
Definition at line 139 of file RequestParser.cpp.
{
        request.body = std::move(content);
        return parsingFinished();
    }
References web::http::server::Request::body, parsingFinished(), and request.
parseHeader()
Parser::ParserState web::http::server::RequestParser::parseHeader () override private virtual
Implements web::http::Parser.
Definition at line 91 of file RequestParser.cpp.
{
        if (headers.contains("Connection")) {
            const std::string& connection = headers["Connection"];
            if (web::http::ciContains(connection, "keep-alive")) {
                request.connectionState = ConnectionState::Keep;
            } else if (web::http::ciContains(connection, "close")) {
                request.connectionState = ConnectionState::Close;
            }
        }
        if (headers.contains("Cookie")) {
            std::string& cookiesLine = headers["Cookie"];
            while (!cookiesLine.empty()) {
                std::string cookieLine;
                std::tie(cookieLine, cookiesLine) = httputils::str_split(cookiesLine, ',');
                while (!cookieLine.empty()) {
                    std::string cookie;
                    std::tie(cookie, cookieLine) = httputils::str_split(cookieLine, ';');
                    std::string cookieName;
                    std::string cookieValue;
                    std::tie(cookieName, cookieValue) = httputils::str_split(cookie, '=');
                    httputils::str_trimm(cookieName);
                    httputils::str_trimm(cookieValue);
                    request.cookies.insert({cookieName, cookieValue});
                }
            }
            headers.erase("Cookie");
        }
        request.headers = std::move(Parser::headers);
        httpMajor = request.httpMajor;
        httpMinor = request.httpMinor;
        ParserState parserState = Parser::ParserState::BODY;
        if (transferEncoding != TransferEncoding::Chunked && contentLength == 0) {
            parserState = parsingFinished();
        }
        return parserState;
    }
References web::http::Parser::BODY, web::http::Chunked, web::http::ciContains(), web::http::Close, web::http::server::Request::connectionState, web::http::Parser::contentLength, web::http::server::Request::cookies, web::http::Parser::headers, web::http::server::Request::headers, web::http::Parser::httpMajor, web::http::server::Request::httpMajor, web::http::Parser::httpMinor, web::http::server::Request::httpMinor, web::http::Keep, parsingFinished(), request, httputils::str_split(), httputils::str_trimm(), and web::http::Parser::transferEncoding.
parseStartLine()
Parser::ParserState web::http::server::RequestParser::parseStartLine (const std::string & line) override private virtual
Implements web::http::Parser.
Definition at line 52 of file RequestParser.cpp.
{
        Parser::ParserState parserState = Parser::ParserState::HEADER;
        if (!line.empty()) {
            std::string remaining;
            std::tie(request.method, remaining) = httputils::str_split(line, ' ');
            std::tie(request.url, request.httpVersion) = httputils::str_split(remaining, ' ');
            std::string queriesLine;
            std::tie(std::ignore, queriesLine) = httputils::str_split(request.url, '?');
            if (!methodSupported(request.method)) {
                parserState = parsingError(400, "Bad request method");
            } else if (request.url.empty() || request.url.front() != '/') {
                parserState = parsingError(400, "Malformed request");
            } else {
                std::smatch httpVersionMatch;
                if (!std::regex_match(request.httpVersion, httpVersionMatch, httpVersionRegex)) {
                    parserState = parsingError(400, "Wrong protocol-version");
                } else {
                    request.httpMajor = std::stoi(httpVersionMatch.str(1));
                    request.httpMinor = std::stoi(httpVersionMatch.str(2));
                    while (!queriesLine.empty()) {
                        std::string query;
                        std::tie(query, queriesLine) = httputils::str_split(queriesLine, '&');
                        request.queries.insert(httputils::str_split(query, '='));
                    }
                }
            }
        } else {
            parserState = parsingError(400, "Request-line empty");
        }
        return parserState;
    }
References web::http::Parser::HEADER, web::http::server::Request::httpMajor, web::http::server::Request::httpMinor, web::http::server::Request::httpVersion, web::http::Parser::httpVersionRegex, web::http::server::Request::method, methodSupported(), parsingError(), web::http::server::Request::queries, request, httputils::str_split(), and web::http::server::Request::url.
parsingError()
Parser::ParserState web::http::server::RequestParser::parsingError (int code, const std::string & reason) override private virtual
Implements web::http::Parser.
Definition at line 153 of file RequestParser.cpp.
{
        onRequestParseError(code, reason + "\r\n");
        reset();
        return ParserState::ERROR;
    }
References web::http::Parser::ERROR, onRequestParseError, and web::http::Parser::reset().
Referenced by parseStartLine().
parsingFinished()
Parser::ParserState web::http::server::RequestParser::parsingFinished () private
Definition at line 145 of file RequestParser.cpp.
{
        onRequestParsed(std::move(request));
        reset();
        return ParserState::BEGIN;
    }
References web::http::Parser::BEGIN, onRequestParsed, request, and web::http::Parser::reset().
Referenced by parseContent(), and parseHeader().
readContent()
std::size_t web::http::Parser::readContent () private inherited
Definition at line 238 of file Parser.cpp.
{
        ContentDecoder* contentDecoder = decoderQueue.front();
        const std::size_t consumed = contentDecoder->read();
        if (contentDecoder->isCompleted()) {
            contentDecoder = decoderQueue.back();
            std::vector<char> chunk = std::move(contentDecoder->getContent());
            content.insert(content.end(), chunk.begin(), chunk.end());
            parserState = parseContent(content);
        } else if (contentDecoder->isError()) {
            parserState = parsingError(400, "Wrong content encoding");
        }
        return consumed;
    }
References web::http::Parser::content, web::http::Parser::decoderQueue, web::http::ContentDecoder::getContent(), web::http::ContentDecoder::isCompleted(), web::http::ContentDecoder::isError(), web::http::Parser::parseContent(), web::http::Parser::parserState, web::http::Parser::parsingError(), and web::http::ContentDecoder::read().
Referenced by web::http::Parser::parse().
readHeaderLine()
std::size_t web::http::Parser::readHeaderLine () private inherited
Definition at line 117 of file Parser.cpp.
{
        std::size_t consumed = 0;
        std::size_t ret = 0;
        do {
            char ch = 0;
            ret = socketContext->readFromPeer(&ch, 1);
            if (ret > 0) {
                consumed++;
                if (ch == '\r' || ch == '\n') {
                    if (ch == '\n') {
                        if (EOL || line.empty()) {
                            if (!line.empty()) {
                                splitHeaderLine(line);
                                line.clear();
                            }
                            if (parserState != ParserState::ERROR) {
                                parserState = analyzeHeaders();
                            }
                            EOL = false;
                        } else {
                            EOL = true;
                        }
                    }
                } else if (EOL) {
                    EOL = false;
                    if (std::isblank(ch) != 0) {
                        if ((hTTPCompliance & HTTPCompliance::RFC7230) == HTTPCompliance::RFC7230) {
                            parserState = parsingError(400, "Header Folding");
                        } else {
                            line += ch;
                        }
                    } else {
                        splitHeaderLine(line);
                        line.clear();
                        line += ch;
                    }
                } else {
                    line += ch;
                }
            }
        } while (ret > 0 && parserState == ParserState::HEADER);
        return consumed;
    }
References web::http::Parser::analyzeHeaders(), web::http::Parser::EOL, web::http::Parser::ERROR, web::http::Parser::HEADER, web::http::Parser::line, web::http::Parser::operator&, web::http::Parser::parserState, web::http::Parser::parsingError(), core::socket::stream::SocketContext::readFromPeer(), web::http::Parser::RFC7230, web::http::Parser::socketContext, and web::http::Parser::splitHeaderLine().
Referenced by web::http::Parser::parse().
readStartLine()
std::size_t web::http::Parser::readStartLine () private inherited
Definition at line 93 of file Parser.cpp.
{
        std::size_t consumed = 0;
        std::size_t ret = 0;
        do {
            char ch = 0;
            ret = socketContext->readFromPeer(&ch, 1);
            if (ret > 0) {
                consumed += ret;
                if (ch == '\r' || ch == '\n') {
                    if (ch == '\n') {
                        parserState = parseStartLine(line);
                        line.clear();
                    }
                } else {
                    line += ch;
                }
            }
        } while (ret > 0 && parserState == ParserState::FIRSTLINE);
        return consumed;
    }
References web::http::Parser::FIRSTLINE, web::http::Parser::line, web::http::Parser::parserState, web::http::Parser::parseStartLine(), core::socket::stream::SocketContext::readFromPeer(), and web::http::Parser::socketContext.
Referenced by web::http::Parser::parse().
reset()
void web::http::Parser::reset () inherited
Definition at line 51 of file Parser.cpp.
                       {
        parserState = ParserState::BEGIN;
        contentLength = 0;
        contentRead = 0;
        httpMinor = 0;
        httpMajor = 0;
        for (ContentDecoder* contentDecoder : decoderQueue) {
            delete contentDecoder;
        }
        decoderQueue.clear();
    }
References web::http::Parser::BEGIN, web::http::Parser::contentLength, web::http::Parser::contentRead, web::http::Parser::decoderQueue, web::http::Parser::httpMajor, web::http::Parser::httpMinor, and web::http::Parser::parserState.
Referenced by web::http::client::ResponseParser::parsingError(), parsingError(), web::http::client::ResponseParser::parsingFinished(), parsingFinished(), and web::http::Parser::~Parser().
splitHeaderLine()
void web::http::Parser::splitHeaderLine (const std::string & line) private inherited
Definition at line 166 of file Parser.cpp.
{
        if (!line.empty()) {
            auto [headerFieldName, value] = httputils::str_split(line, ':');
            if (headerFieldName.empty()) {
                parserState = parsingError(400, "Header-field empty");
            } else if ((std::isblank(headerFieldName.back()) != 0) || (std::isblank(headerFieldName.front()) != 0)) {
                parserState = parsingError(400, "White space before or after header-field");
            } else if (value.empty()) {
                parserState = parsingError(400, "Header-value of field \"" + headerFieldName + "\" empty");
            } else {
                httputils::str_trimm(value);
                if (headers.find(headerFieldName) == headers.end()) {
                    headers.emplace(headerFieldName, value);
                } else {
                    headers[headerFieldName] += "," + value;
                }
            }
        } else {
            parserState = parsingError(400, "Header-line empty");
        }
    }
References web::http::Parser::headers, web::http::Parser::parserState, web::http::Parser::parsingError(), httputils::str_split(), and httputils::str_trimm().
Referenced by web::http::Parser::readHeaderLine().
Member Data Documentation
content
std::vector<char> web::http::Parser::content protected inherited
Definition at line 95 of file Parser.h.
Referenced by web::http::Parser::readContent().
contentLength
std::size_t web::http::Parser::contentLength = 0 protected inherited
Definition at line 93 of file Parser.h.
Referenced by web::http::Parser::analyzeHeaders(), web::http::client::ResponseParser::parseHeader(), parseHeader(), and web::http::Parser::reset().
contentRead
std::size_t web::http::Parser::contentRead = 0 private inherited
Definition at line 116 of file Parser.h.
Referenced by web::http::Parser::reset().
decoderQueue
std::list<web::http::ContentDecoder*> web::http::Parser::decoderQueue protected inherited
Definition at line 100 of file Parser.h.
Referenced by web::http::Parser::analyzeHeaders(), web::http::client::ResponseParser::getResponse(), web::http::Parser::readContent(), and web::http::Parser::reset().
EOL
bool web::http::Parser::EOL {false} private inherited
Definition at line 112 of file Parser.h.
{false};
Referenced by web::http::Parser::readHeaderLine().
headers
CiStringMap<std::string> web::http::Parser::headers protected inherited
Definition at line 94 of file Parser.h.
Referenced by web::http::Parser::analyzeHeaders(), web::http::client::ResponseParser::parseHeader(), parseHeader(), and web::http::Parser::splitHeaderLine().
hTTPCompliance
enum web::http::Parser::HTTPCompliance web::http::Parser::hTTPCompliance protected inherited
httpMajor
int web::http::Parser::httpMajor = 0 protected inherited
Definition at line 97 of file Parser.h.
Referenced by web::http::client::ResponseParser::parseHeader(), parseHeader(), and web::http::Parser::reset().
httpMinor
int web::http::Parser::httpMinor = 0 protected inherited
Definition at line 98 of file Parser.h.
Referenced by web::http::client::ResponseParser::parseHeader(), parseHeader(), and web::http::Parser::reset().
httpVersionRegex
const std::regex web::http::Parser::httpVersionRegex static protected inherited
Definition at line 82 of file Parser.h.
Referenced by web::http::client::ResponseParser::parseStartLine(), and parseStartLine().
line
std::string web::http::Parser::line private inherited
Definition at line 115 of file Parser.h.
Referenced by web::http::Parser::readHeaderLine(), and web::http::Parser::readStartLine().
onRequestParsed
std::function<void(Request&&)> web::http::server::RequestParser::onRequestParsed private
Definition at line 73 of file RequestParser.h.
Referenced by parsingFinished(), and RequestParser().
onRequestParseError
std::function<void(int, const std::string&)> web::http::server::RequestParser::onRequestParseError private
Definition at line 74 of file RequestParser.h.
Referenced by parsingError(), and RequestParser().
onRequestStart
std::function<void()> web::http::server::RequestParser::onRequestStart private
Definition at line 72 of file RequestParser.h.
Referenced by begin(), and RequestParser().
parserState
ParserState web::http::Parser::parserState = ParserState::BEGIN private inherited
Definition at line 77 of file Parser.h.
Referenced by web::http::Parser::parse(), web::http::Parser::readContent(), web::http::Parser::readHeaderLine(), web::http::Parser::readStartLine(), web::http::Parser::reset(), and web::http::Parser::splitHeaderLine().
request
Request web::http::server::RequestParser::request private
Definition at line 69 of file RequestParser.h.
Referenced by parseContent(), parseHeader(), parseStartLine(), and parsingFinished().
socketContext
core::socket::stream::SocketContext* web::http::Parser::socketContext = nullptr protected inherited
Definition at line 102 of file Parser.h.
Referenced by web::http::Parser::analyzeHeaders(), web::http::Parser::Parser(), web::http::Parser::readHeaderLine(), and web::http::Parser::readStartLine().
supportedMethods
std::set<std::string> web::http::server::RequestParser::supportedMethods {"GET", "PUT", "POST", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH", "HEAD"} private
Definition at line 52 of file RequestParser.h.
{"GET", "PUT", "POST", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH", "HEAD"};
Referenced by methodSupported().
transferEncoding
TransferEncoding web::http::Parser::transferEncoding = TransferEncoding::HTTP10 protected inherited
Definition at line 80 of file Parser.h.
Referenced by web::http::Parser::analyzeHeaders(), web::http::client::ResponseParser::parseHeader(), and parseHeader().
The documentation for this class was generated from the following files:
web/http/server/RequestParser.h
web/http/server/RequestParser.cpp