SNode.C: iot::mqtt::types::TypeBase< ValueTypeT > Class Template Reference
iot::mqtt::types::TypeBase< ValueTypeT > Class Template Reference
#include <TypeBase.h>
Public Member Functions
TypeBase (std::size_t size=sizeof(ValueType))
TypeBase (const TypeBase &)=default
TypeBase (TypeBase &&) noexcept=default
virtual ~TypeBase ()=default
TypeBase & operator= (const TypeBase &)=default
TypeBase & operator= (TypeBase &&) noexcept=default
virtual std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
virtual std::vector< char > serialize () const
void setSize (std::size_t size)
std::size_t size ()
bool isComplete () const
virtual void reset (std::size_t size=sizeof(ValueType))
Protected Types
using ValueType = ValueTypeT
Protected Attributes
std::vector< char > value
std::size_t length = 0
std::size_t needed = 0
bool complete = false
int state = 0
Detailed Description
template<typename ValueTypeT>
class iot::mqtt::types::TypeBase< ValueTypeT >
Definition at line 37 of file TypeBase.h.
Member Typedef Documentation
ValueType
template<typename ValueTypeT > using iot::mqtt::types::TypeBase< ValueTypeT >::ValueType = ValueTypeT protected
Definition at line 39 of file TypeBase.h.
Constructor & Destructor Documentation
TypeBase() [1/3]
template<typename ValueType > iot::mqtt::types::TypeBase< ValueType >::TypeBase (std::size_t size = sizeof(ValueType)) explicit
Definition at line 30 of file TypeBase.hpp.
{
        value.resize(size);
        length = size;
        needed = size;
    }
References iot::mqtt::types::TypeBase< ValueTypeT >::length, iot::mqtt::types::TypeBase< ValueTypeT >::needed, and iot::mqtt::types::TypeBase< ValueTypeT >::value.
Referenced by iot::mqtt::types::String::String(), iot::mqtt::types::StringRaw::StringRaw(), and iot::mqtt::types::UIntV::UIntV().
TypeBase() [2/3]
template<typename ValueTypeT > iot::mqtt::types::TypeBase< ValueTypeT >::TypeBase (const TypeBase< ValueTypeT > &) default
TypeBase() [3/3]
template<typename ValueTypeT > iot::mqtt::types::TypeBase< ValueTypeT >::TypeBase (TypeBase< ValueTypeT > &&) default noexcept
~TypeBase()
template<typename ValueTypeT > virtual iot::mqtt::types::TypeBase< ValueTypeT >::~TypeBase () virtual default
Member Function Documentation
deserialize()
template<typename ValueType > std::size_t iot::mqtt::types::TypeBase< ValueType >::deserialize (iot::mqtt::MqttContext * mqttContext) virtual
Reimplemented in iot::mqtt::types::String, and iot::mqtt::types::UIntV.
Definition at line 37 of file TypeBase.hpp.
{
        std::size_t consumed = 0;
        consumed = mqttContext->recv(value.data() + length - needed, needed);
        needed -= consumed;
        complete = needed == 0;
        return consumed;
    }
References iot::mqtt::types::TypeBase< ValueTypeT >::length, iot::mqtt::types::TypeBase< ValueTypeT >::needed, iot::mqtt::MqttContext::recv(), and iot::mqtt::types::TypeBase< ValueTypeT >::value.
Referenced by iot::mqtt::FixedHeader::deserialize(), iot::mqtt::types::String::deserialize(), iot::mqtt::client::packets::Connack::deserializeVP(), iot::mqtt::client::packets::Puback::deserializeVP(), iot::mqtt::client::packets::Pubcomp::deserializeVP(), iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::client::packets::Pubrec::deserializeVP(), iot::mqtt::client::packets::Pubrel::deserializeVP(), iot::mqtt::client::packets::Suback::deserializeVP(), iot::mqtt::client::packets::Unsuback::deserializeVP(), iot::mqtt::server::packets::Connect::deserializeVP(), iot::mqtt::server::packets::Puback::deserializeVP(), iot::mqtt::server::packets::Pubcomp::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), iot::mqtt::server::packets::Pubrec::deserializeVP(), iot::mqtt::server::packets::Pubrel::deserializeVP(), iot::mqtt::server::packets::Subscribe::deserializeVP(), and iot::mqtt::server::packets::Unsubscribe::deserializeVP().
isComplete()
template<typename ValueType > bool iot::mqtt::types::TypeBase< ValueType >::isComplete () const
Definition at line 66 of file TypeBase.hpp.
{
        return complete;
    }
References iot::mqtt::types::TypeBase< ValueTypeT >::complete.
Referenced by iot::mqtt::FixedHeader::deserialize(), iot::mqtt::types::String::deserialize(), iot::mqtt::client::packets::Connack::deserializeVP(), iot::mqtt::client::packets::Puback::deserializeVP(), iot::mqtt::client::packets::Pubcomp::deserializeVP(), iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::client::packets::Pubrec::deserializeVP(), iot::mqtt::client::packets::Pubrel::deserializeVP(), iot::mqtt::client::packets::Suback::deserializeVP(), iot::mqtt::client::packets::Unsuback::deserializeVP(), iot::mqtt::server::packets::Connect::deserializeVP(), iot::mqtt::server::packets::Puback::deserializeVP(), iot::mqtt::server::packets::Pubcomp::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), iot::mqtt::server::packets::Pubrec::deserializeVP(), iot::mqtt::server::packets::Pubrel::deserializeVP(), iot::mqtt::server::packets::Subscribe::deserializeVP(), and iot::mqtt::server::packets::Unsubscribe::deserializeVP().
operator=() [1/2]
template<typename ValueTypeT > TypeBase & iot::mqtt::types::TypeBase< ValueTypeT >::operator= (const TypeBase< ValueTypeT > &) default
operator=() [2/2]
template<typename ValueTypeT > TypeBase & iot::mqtt::types::TypeBase< ValueTypeT >::operator= (TypeBase< ValueTypeT > &&) default noexcept
reset()
template<typename ValueType > void iot::mqtt::types::TypeBase< ValueType >::reset (std::size_t size = sizeof(ValueType)) virtual
Reimplemented in iot::mqtt::types::String, iot::mqtt::types::StringRaw, and iot::mqtt::types::UIntV.
Definition at line 71 of file TypeBase.hpp.
{
        value.resize(size);
        length = size;
        needed = size;
        complete = false;
        state = 0;
    }
References iot::mqtt::types::TypeBase< ValueTypeT >::complete, iot::mqtt::types::TypeBase< ValueTypeT >::length, iot::mqtt::types::TypeBase< ValueTypeT >::needed, iot::mqtt::types::TypeBase< ValueTypeT >::state, and iot::mqtt::types::TypeBase< ValueTypeT >::value.
Referenced by iot::mqtt::client::packets::Suback::deserializeVP(), iot::mqtt::server::packets::Subscribe::deserializeVP(), iot::mqtt::FixedHeader::reset(), iot::mqtt::types::String::reset(), iot::mqtt::types::StringRaw::reset(), and iot::mqtt::types::UIntV::reset().
serialize()
template<typename ValueType > std::vector< char > iot::mqtt::types::TypeBase< ValueType >::serialize () const virtual
Reimplemented in iot::mqtt::types::String.
Definition at line 61 of file TypeBase.hpp.
{
        return value;
    }
References iot::mqtt::types::TypeBase< ValueTypeT >::value.
Referenced by iot::mqtt::FixedHeader::serialize(), iot::mqtt::types::String::serialize(), iot::mqtt::packets::Connack::serializeVP(), iot::mqtt::packets::Connect::serializeVP(), iot::mqtt::packets::Puback::serializeVP(), iot::mqtt::packets::Pubcomp::serializeVP(), iot::mqtt::packets::Publish::serializeVP(), iot::mqtt::packets::Pubrec::serializeVP(), iot::mqtt::packets::Pubrel::serializeVP(), iot::mqtt::packets::Suback::serializeVP(), iot::mqtt::packets::Subscribe::serializeVP(), iot::mqtt::packets::Unsuback::serializeVP(), and iot::mqtt::packets::Unsubscribe::serializeVP().
setSize()
template<typename ValueType > void iot::mqtt::types::TypeBase< ValueType >::setSize (std::size_t size)
Definition at line 48 of file TypeBase.hpp.
{
        value.resize(size);
        length = size;
        needed = size;
    }
References iot::mqtt::types::TypeBase< ValueTypeT >::value.
Referenced by iot::mqtt::types::String::deserialize(), iot::mqtt::client::packets::Publish::deserializeVP(), and iot::mqtt::server::packets::Publish::deserializeVP().
size()
template<typename ValueTypeT > std::size_t iot::mqtt::types::TypeBase< ValueTypeT >::size ()
Definition at line 56 of file TypeBase.hpp.
{
        return length;
    }
References iot::mqtt::types::TypeBase< ValueTypeT >::length.
Referenced by iot::mqtt::server::packets::Connect::deserializeVP().
Member Data Documentation
complete
template<typename ValueTypeT > bool iot::mqtt::types::TypeBase< ValueTypeT >::complete = false protected
Definition at line 68 of file TypeBase.h.
Referenced by iot::mqtt::types::TypeBase< ValueTypeT >::isComplete(), and iot::mqtt::types::TypeBase< ValueTypeT >::reset().
length
template<typename ValueTypeT > std::size_t iot::mqtt::types::TypeBase< ValueTypeT >::length = 0 protected
Definition at line 65 of file TypeBase.h.
Referenced by iot::mqtt::types::TypeBase< ValueTypeT >::deserialize(), iot::mqtt::types::TypeBase< ValueTypeT >::reset(), iot::mqtt::types::TypeBase< ValueTypeT >::size(), and iot::mqtt::types::TypeBase< ValueTypeT >::TypeBase().
needed
template<typename ValueTypeT > std::size_t iot::mqtt::types::TypeBase< ValueTypeT >::needed = 0 protected
Definition at line 66 of file TypeBase.h.
Referenced by iot::mqtt::types::TypeBase< ValueTypeT >::deserialize(), iot::mqtt::types::TypeBase< ValueTypeT >::reset(), and iot::mqtt::types::TypeBase< ValueTypeT >::TypeBase().
state
template<typename ValueTypeT > int iot::mqtt::types::TypeBase< ValueTypeT >::state = 0 protected
Definition at line 70 of file TypeBase.h.
Referenced by iot::mqtt::types::TypeBase< ValueTypeT >::reset().
value
template<typename ValueTypeT > std::vector<char> iot::mqtt::types::TypeBase< ValueTypeT >::value protected
Definition at line 63 of file TypeBase.h.
Referenced by iot::mqtt::types::TypeBase< ValueTypeT >::deserialize(), iot::mqtt::types::TypeBase< ValueTypeT >::reset(), iot::mqtt::types::TypeBase< ValueTypeT >::serialize(), iot::mqtt::types::TypeBase< ValueTypeT >::setSize(), and iot::mqtt::types::TypeBase< ValueTypeT >::TypeBase().
The documentation for this class was generated from the following files:
iot/mqtt/types/TypeBase.h
iot/mqtt/types/TypeBase.hpp