SNode.C: iot::mqtt::packets::Unsubscribe Class Reference
iot::mqtt::packets::Unsubscribe Class Reference
#include <Unsubscribe.h>
Public Member Functions
Unsubscribe ()
Unsubscribe (uint16_t packetIdentifier, const std::list< std::string > &topics)
uint16_t getPacketIdentifier () const
const std::list< std::string > & getTopics () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type, const std::string &name)
ControlPacket (const ControlPacket &)=default
ControlPacket (ControlPacket &&)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
ControlPacket & operator= (ControlPacket &&)=default
std::vector< char > serialize () const
const std::string & getName () const
uint8_t getType () const
uint8_t getFlags () const
Protected Attributes
iot::mqtt::types::UInt16 packetIdentifier
std::list< std::string > topics
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t flags = 0
Private Member Functions
std::vector< char > serializeVP () const override
Detailed Description
Definition at line 37 of file Unsubscribe.h.
Constructor & Destructor Documentation
Unsubscribe() [1/2]
iot::mqtt::packets::Unsubscribe::Unsubscribe ()
Definition at line 30 of file Unsubscribe.cpp.
        : iot::mqtt::ControlPacket(MQTT_UNSUBSCRIBE, "UNSUBSCRIBE") {
    }
References Unsubscribe().
Referenced by Unsubscribe(), and Unsubscribe().
Unsubscribe() [2/2]
iot::mqtt::packets::Unsubscribe::Unsubscribe (uint16_t packetIdentifier, const std::list< std::string > & topics)
Definition at line 34 of file Unsubscribe.cpp.
        : Unsubscribe() {
        this->packetIdentifier = packetIdentifier;
        this->topics = topics;
    }
References Unsubscribe().
Member Function Documentation
getPacketIdentifier()
uint16_t iot::mqtt::packets::Unsubscribe::getPacketIdentifier () const
Definition at line 54 of file Unsubscribe.cpp.
{
        return packetIdentifier;
    }
getTopics()
const std::list< std::string > & iot::mqtt::packets::Unsubscribe::getTopics () const
Definition at line 58 of file Unsubscribe.cpp.
{
        return topics;
    }
serializeVP()
std::vector< char > iot::mqtt::packets::Unsubscribe::serializeVP () const override private virtual
Implements iot::mqtt::ControlPacket.
Definition at line 40 of file Unsubscribe.cpp.
{
        std::vector<char> packet(packetIdentifier.serialize());
        for (const std::string& topic : topics) {
            iot::mqtt::types::String topicString;
            topicString = topic;
            std::vector<char> tmpPacket = topicString.serialize();
            packet.insert(packet.end(), tmpPacket.begin(), tmpPacket.end());
        }
        return packet;
    }
Member Data Documentation
packetIdentifier
iot::mqtt::types::UInt16 iot::mqtt::packets::Unsubscribe::packetIdentifier protected
Definition at line 50 of file Unsubscribe.h.
topics
std::list<std::string> iot::mqtt::packets::Unsubscribe::topics protected
Definition at line 52 of file Unsubscribe.h.
The documentation for this class was generated from the following files:
iot/mqtt/packets/Unsubscribe.h
iot/mqtt/packets/Unsubscribe.cpp