snode.c: core::pipe::PipeSink Class Reference
core::pipe::PipeSink Class Reference
#include <PipeSink.h>
Public Member Functions
PipeSink (const PipeSink &)=delete
PipeSink & operator= (const PipeSink &)=delete
PipeSink (int fd)
~PipeSink () override
void setOnData (const std::function< void(const char *junk, std::size_t junkLen)> &onData)
void setOnEof (const std::function< void()> &onEof)
void setOnError (const std::function< void(int errnum)> &onError)
Public Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const DescriptorEventReceiver &)=delete
DescriptorEventReceiver & operator= (const DescriptorEventReceiver &)=delete
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
int getRegisteredFd ()
void enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Private Member Functions
void terminate () override
void readEvent () override
void unobservedEvent () override
Private Attributes
std::function< void(const char *junk, std::size_t junkLen)> onData
std::function< void()> onEof
std::function< void(int errnum)> onError
Additional Inherited Members
Protected Member Functions inherited from core::eventreceiver::ReadEventReceiver
ReadEventReceiver (const std::string &name, const utils::Timeval &timeout)
Protected Member Functions inherited from core::Observer
Observer ()=default
virtual ~Observer ()
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
Protected Member Functions inherited from core::EventReceiver
virtual ~EventReceiver ()=default
EventReceiver (const std::string &name)
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Detailed Description
Definition at line 33 of file PipeSink.h.
Constructor & Destructor Documentation
PipeSink() [1/2]
core::pipe::PipeSink::PipeSink (const PipeSink &) delete
PipeSink() [2/2]
core::pipe::PipeSink::PipeSink (int fd) explicit
Definition at line 36 of file PipeSink.cpp.
        : core::eventreceiver::ReadEventReceiver("PipeSink fd = " + std::to_string(fd), 60) {
        ReadEventReceiver::enable(fd);
    }
~PipeSink()
core::pipe::PipeSink::~PipeSink () override
Definition at line 41 of file PipeSink.cpp.
{
        close(getRegisteredFd());
    }
References core::DescriptorEventReceiver::getRegisteredFd().
Member Function Documentation
operator=()
PipeSink & core::pipe::PipeSink::operator= (const PipeSink &) delete
readEvent()
void core::pipe::PipeSink::readEvent () override private virtual
Implements core::eventreceiver::ReadEventReceiver.
Definition at line 45 of file PipeSink.cpp.
{
        // NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays, hicpp-avoid-c-arrays, modernize-avoid-c-arrays)
        static char junk[MAX_READ_JUNKSIZE];
        ssize_t ret = core::system::read(getRegisteredFd(), junk, MAX_READ_JUNKSIZE);
        if (ret > 0) {
            if (onData) {
                onData(junk, static_cast<std::size_t>(ret));
            }
        } else {
            ReadEventReceiver::disable();
            if (ret == 0) {
                if (onEof) {
                    onEof();
                }
            } else {
                if (onError) {
                    onError(errno);
                }
            }
        }
    }
References core::DescriptorEventReceiver::getRegisteredFd(), MAX_READ_JUNKSIZE, onData, onEof, onError, and core::system::read().
setOnData()
void core::pipe::PipeSink::setOnData (const std::function< void(const char *junk, std::size_t junkLen)> & onData)
Definition at line 70 of file PipeSink.cpp.
{
        this->onData = onData;
    }
References onData.
setOnEof()
void core::pipe::PipeSink::setOnEof (const std::function< void()> & onEof)
Definition at line 74 of file PipeSink.cpp.
{
        this->onEof = onEof;
    }
References onEof.
setOnError()
void core::pipe::PipeSink::setOnError (const std::function< void(int errnum)> & onError)
Definition at line 78 of file PipeSink.cpp.
{
        this->onError = onError;
    }
References onError.
terminate()
void core::pipe::PipeSink::terminate () override private virtual
Reimplemented from core::DescriptorEventReceiver.
Definition at line 82 of file PipeSink.cpp.
{
        ReadEventReceiver::terminate();
    }
unobservedEvent()
void core::pipe::PipeSink::unobservedEvent () override private virtual
Implements core::Observer.
Definition at line 86 of file PipeSink.cpp.
{
        delete this;
    }
Member Data Documentation
onData
std::function<void(const char* junk, std::size_t junkLen)> core::pipe::PipeSink::onData private
Definition at line 52 of file PipeSink.h.
Referenced by readEvent(), and setOnData().
onEof
std::function<void()> core::pipe::PipeSink::onEof private
Definition at line 53 of file PipeSink.h.
Referenced by readEvent(), and setOnEof().
onError
std::function<void(int errnum)> core::pipe::PipeSink::onError private
Definition at line 54 of file PipeSink.h.
Referenced by readEvent(), and setOnError().
The documentation for this class was generated from the following files:
core/pipe/PipeSink.h
core/pipe/PipeSink.cpp