SNode.C: utils::DaemonizeError Class Reference
utils::DaemonizeError Class Reference
#include <Daemon.h>
Public Member Functions
DaemonizeError (const std::string &errorMessage)
~DaemonizeError () override
Public Member Functions inherited from utils::DaemonizeFailure
DaemonizeFailure (const std::string &failureMessage)
~DaemonizeFailure () override
Detailed Description
Definition at line 39 of file Daemon.h.
Constructor & Destructor Documentation
DaemonizeError()
utils::DaemonizeError::DaemonizeError (const std::string & errorMessage) explicit
Definition at line 49 of file Daemon.cpp.
        : DaemonizeFailure(errorMessage + ": " + std::strerror(errno)) {
    }
References utils::DaemonizeFailure::DaemonizeFailure().
Referenced by utils::Daemon::startDaemon(), and utils::Daemon::stopDaemon().
~DaemonizeError()
utils::DaemonizeError::~DaemonizeError () override
Definition at line 53 of file Daemon.cpp.
{
    }
The documentation for this class was generated from the following files:
utils/Daemon.h
utils/Daemon.cpp