SNode.C: iot::mqtt::types::UIntV Class Reference
iot::mqtt::types::UIntV Class Reference
#include <UIntV.h>
Public Member Functions
UIntV ()
UIntV (const UIntV &)=default
UIntV (UIntV &&) noexcept=default
~UIntV () override
UIntV & operator= (const UIntV &)=default
UIntV & operator= (UIntV &&) noexcept=default
std::size_t deserialize (iot::mqtt::MqttContext *mqttContext) override
UIntV & operator= (const uint32_t &newValue)
operator uint32_t () const
bool isError () const
void reset (std::size_t size=sizeof(ValueType)) override
Public Member Functions inherited from iot::mqtt::types::TypeBase< uint32_t >
TypeBase (std::size_t size=sizeof(ValueType))
TypeBase (const TypeBase &)=default
TypeBase (TypeBase &&) noexcept=default
virtual ~TypeBase ()=default
TypeBase & operator= (const TypeBase &)=default
TypeBase & operator= (TypeBase &&) noexcept=default
virtual std::vector< char > serialize () const
void setSize (std::size_t size)
std::size_t size ()
bool isComplete () const
Private Attributes
bool error = false
Additional Inherited Members
Protected Types inherited from iot::mqtt::types::TypeBase< uint32_t >
using ValueType = uint32_t
Protected Attributes inherited from iot::mqtt::types::TypeBase< uint32_t >
std::vector< char > value
std::size_t length
std::size_t needed
bool complete
int state
Detailed Description
Definition at line 56 of file UIntV.h.
Constructor & Destructor Documentation
UIntV() [1/3]
iot::mqtt::types::UIntV::UIntV ()
Definition at line 55 of file UIntV.cpp.
        : TypeBase(0) {
    }
References iot::mqtt::types::TypeBase< ValueTypeT >::TypeBase().
UIntV() [2/3]
iot::mqtt::types::UIntV::UIntV (const UIntV &) default
UIntV() [3/3]
iot::mqtt::types::UIntV::UIntV (UIntV &&) default noexcept
~UIntV()
iot::mqtt::types::UIntV::~UIntV () override
Definition at line 59 of file UIntV.cpp.
                  {
    }
Member Function Documentation
deserialize()
std::size_t iot::mqtt::types::UIntV::deserialize (iot::mqtt::MqttContext * mqttContext) override virtual
Reimplemented from iot::mqtt::types::TypeBase< uint32_t >.
Definition at line 62 of file UIntV.cpp.
{
        std::size_t consumed = 0;
        do {
            char byte = 0;
            consumed = mqttContext->recv(&byte, 1);
            if (consumed > 0) {
                value.push_back(byte);
                if (value.size() > sizeof(uint32_t)) {
                    error = true;
                } else {
                    complete = (byte & 0x80) == 0;
                }
            }
        } while (consumed > 0 && !complete && !error);
        return consumed;
    }
References error, and iot::mqtt::MqttContext::recv().
Referenced by iot::mqtt::FixedHeader::deserialize().
isError()
bool iot::mqtt::types::UIntV::isError () const
Definition at line 112 of file UIntV.cpp.
{
        return error;
    }
References error.
Referenced by iot::mqtt::FixedHeader::deserialize().
operator uint32_t()
iot::mqtt::types::UIntV::operator uint32_t () const
Definition at line 101 of file UIntV.cpp.
{
        uint32_t uint32Value = 0;
        uint32_t multiplicator = 1;
        for (std::size_t i = 0; i < value.size(); i++, multiplicator *= 0x80) {
            uint32Value += static_cast<uint8_t>(value[i] & 0x7F) * multiplicator;
        }
        return uint32Value;
    }
operator=() [1/3]
UIntV & iot::mqtt::types::UIntV::operator= (const uint32_t & newValue)
Definition at line 83 of file UIntV.cpp.
{
        uint32_t remainingValue = newValue;
        value.clear();
        do {
            char encodedByte = static_cast<char>(remainingValue % 0x80);
            remainingValue /= 0x80;
            if (remainingValue > 0) {
                encodedByte |= static_cast<char>(0x80);
            }
            value.push_back(encodedByte);
        } while (remainingValue > 0);
        return *this;
    }
Referenced by iot::mqtt::FixedHeader::FixedHeader(), and iot::mqtt::FixedHeader::setRemainingLength().
operator=() [2/3]
UIntV & iot::mqtt::types::UIntV::operator= (const UIntV &) default
operator=() [3/3]
UIntV & iot::mqtt::types::UIntV::operator= (UIntV &&) default noexcept
reset()
void iot::mqtt::types::UIntV::reset (std::size_t size = sizeof(ValueType)) override virtual
Reimplemented from iot::mqtt::types::TypeBase< uint32_t >.
Definition at line 116 of file UIntV.cpp.
{
        error = false;
        TypeBase::reset(0);
    }
References error, and iot::mqtt::types::TypeBase< ValueTypeT >::reset().
Referenced by iot::mqtt::FixedHeader::reset().
Member Data Documentation
error
bool iot::mqtt::types::UIntV::error = false private
Definition at line 77 of file UIntV.h.
Referenced by deserialize(), isError(), and reset().
The documentation for this class was generated from the following files:
iot/mqtt/types/UIntV.h
iot/mqtt/types/UIntV.cpp