SNode.C: web::http::SocketContext Class Reference
web::http::SocketContext Class Reference abstract
#include <SocketContext.h>
Public Member Functions
SocketContext (const SocketContext &)=delete
~SocketContext () override
SocketContext & operator= (const SocketContext &)=delete
virtual void sendToPeerCompleted ()=0
void sendToPeer (const char *junk, std::size_t junkLen) const final
void sendToPeer (const std::string &data) const
virtual void sendToPeer (const char *junk, std::size_t junkLen) const=0
void streamToPeer (core::pipe::Source *source) const final
std::size_t readFromPeer (char *junk, std::size_t junklen) const final
void setTimeout (const utils::Timeval &timeout) final
void shutdownRead ()
void shutdownWrite (bool forceClose=false)
void close () override
SocketConnection * getSocketConnection () const
virtual void switchSocketContext (SocketContext *newSocketContext)
Protected Member Functions
std::size_t onReceivedFromPeer () override=0
void onWriteError (int errnum) override
void onReadError (int errnum) override
virtual bool onSignal (int sig)=0
Private Types
using Super = core::socket::stream::SocketContext
Private Member Functions
virtual void onConnected ()=0
virtual void onDisconnected ()=0
Private Attributes
core::socket::stream::SocketConnection * socketConnection
Detailed Description
Definition at line 33 of file SocketContext.h.
Member Typedef Documentation
Super
using web::http::SocketContext::Super = core::socket::stream::SocketContext private
Definition at line 42 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext()
web::http::SocketContext::SocketContext (const SocketContext &) delete
~SocketContext()
web::http::SocketContext::~SocketContext () override virtual
Reimplemented from core::socket::SocketContext.
Definition at line 28 of file SocketContext.cpp.
{
    }
Member Function Documentation
close()
void core::socket::stream::SocketContext::close () override virtual inherited
Implements core::socket::SocketContext.
Reimplemented in iot::mqtt::SocketContext.
Definition at line 58 of file SocketContext.cpp.
{
        socketConnection->close();
    }
References core::socket::stream::SocketConnection::close(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::server::RequestContextBase::close(), iot::mqtt::SocketContext::close(), web::http::client::Request::enqueue(), iot::mqtt_fast::SocketContext::onReceivedFromPeer(), web::http::client::Request::upgrade(), and web::http::client::Response::upgrade().
getSocketConnection()
SocketConnection * core::socket::stream::SocketContext::getSocketConnection () const inherited
Definition at line 38 of file SocketContext.cpp.
{
        return socketConnection;
    }
References core::socket::stream::SocketContext::socketConnection.
Referenced by iot::mqtt::SocketContext::getSocketConnection(), web::http::client::SocketContext< RequestT, ResponseT >::onConnected(), web::http::server::SocketContext< RequestT, ResponseT >::onConnected(), web::http::server::SocketContext< RequestT, ResponseT >::onDisconnected(), web::http::server::SocketContext< RequestT, ResponseT >::onSignal(), web::http::server::RequestContextBase::switchSocketContext(), and web::http::client::Response::upgrade().
onConnected()
virtual void core::socket::stream::SocketContext::onConnected () private pure virtual inherited
Implemented in apps::echo::model::EchoSocketContext, SimpleSocketProtocol, iot::mqtt::SocketContext, web::http::client::SocketContext< RequestT, ResponseT >, web::http::server::SocketContext< RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by core::socket::stream::SocketConnection::setSocketContext().
onDisconnected()
virtual void core::socket::stream::SocketContext::onDisconnected () private pure virtual inherited
Implemented in apps::echo::model::EchoSocketContext, SimpleSocketProtocol, iot::mqtt::SocketContext, web::http::client::SocketContext< RequestT, ResponseT >, web::http::server::SocketContext< RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by core::socket::stream::SocketConnection::disconnectCurrentSocketContext().
onReadError()
void core::socket::stream::SocketContext::onReadError (int errnum) override protected virtual inherited
Implements core::socket::SocketContext.
Definition at line 74 of file SocketContext.cpp.
{
        shutdownWrite();
    }
References core::socket::stream::SocketContext::shutdownWrite().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReadError(), and SimpleSocketProtocol::onReadError().
onReceivedFromPeer()
std::size_t web::http::SocketContext::onReceivedFromPeer () override protected pure virtual
Implements core::socket::SocketContext.
Implemented in web::http::client::SocketContext< RequestT, ResponseT >, and web::http::server::SocketContext< RequestT, ResponseT >.
onSignal()
virtual bool core::socket::SocketContext::onSignal (int sig) protected pure virtual inherited
Implemented in iot::mqtt::SocketContext, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >, apps::echo::model::EchoSocketContext, SimpleSocketProtocol, web::http::client::SocketContext< RequestT, ResponseT >, and web::http::server::SocketContext< RequestT, ResponseT >.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onSignal().
onWriteError()
void core::socket::stream::SocketContext::onWriteError (int errnum) override protected virtual inherited
Implements core::socket::SocketContext.
Definition at line 70 of file SocketContext.cpp.
{
        shutdownRead();
    }
References core::socket::stream::SocketContext::shutdownRead().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onWriteError(), and SimpleSocketProtocol::onWriteError().
operator=()
SocketContext & web::http::SocketContext::operator= (const SocketContext &) delete
readFromPeer()
std::size_t core::socket::stream::SocketContext::readFromPeer (char * junk, std::size_t junklen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 50 of file SocketContext.cpp.
{
        return socketConnection->readFromPeer(junk, junklen);
    }
References core::socket::stream::SocketConnection::readFromPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by apps::echo::model::EchoSocketContext::onReceivedFromPeer(), web::http::Parser::readContent(), web::http::Parser::readHeaderLine(), web::http::Parser::readStartLine(), and iot::mqtt::SocketContext::recv().
sendToPeer() [1/3]
void core::socket::stream::SocketContext::sendToPeer (const char * junk, std::size_t junkLen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 42 of file SocketContext.cpp.
{
        socketConnection->sendToPeer(junk, junkLen);
    }
References core::socket::stream::SocketConnection::sendToPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::Request::enqueue(), apps::echo::model::EchoSocketContext::onReceivedFromPeer(), iot::mqtt::SocketContext::send(), iot::mqtt_fast::SocketContext::send(), and web::http::server::RequestContextBase::sendToPeer().
sendToPeer() [2/3]
virtual void core::socket::SocketContext::sendToPeer (const char * junk, std::size_t junkLen) const virtual inherited
Implements core::socket::SocketContext.
sendToPeer() [3/3]
void core::socket::SocketContext::sendToPeer (const std::string & data) const inherited
Definition at line 55 of file SocketContext.cpp.
{
        sendToPeer(data.data(), data.length());
    }
sendToPeerCompleted()
virtual void web::http::SocketContext::sendToPeerCompleted () pure virtual
Implemented in web::http::client::SocketContext< RequestT, ResponseT >, and web::http::server::SocketContext< RequestT, ResponseT >.
Referenced by web::http::client::Request::enqueue(), and web::http::server::RequestContextBase::sendToPeerCompleted().
setTimeout()
void core::socket::stream::SocketContext::setTimeout (const utils::Timeval & timeout) final virtual inherited
Implements core::socket::SocketContext.
Definition at line 54 of file SocketContext.cpp.
{
        socketConnection->setTimeout(timeout);
    }
References core::socket::stream::SocketConnection::setTimeout(), and core::socket::stream::SocketContext::socketConnection.
shutdownRead()
void core::socket::stream::SocketContext::shutdownRead () inherited
Definition at line 62 of file SocketContext.cpp.
{
        socketConnection->shutdownRead();
    }
References core::socket::stream::SocketConnection::shutdownRead(), and core::socket::stream::SocketContext::socketConnection.
Referenced by SimpleSocketProtocol::onWriteError(), and core::socket::stream::SocketContext::onWriteError().
shutdownWrite()
void core::socket::stream::SocketContext::shutdownWrite (bool forceClose = false) inherited
Definition at line 66 of file SocketContext.cpp.
{
        socketConnection->shutdownWrite(forceClose);
    }
References core::socket::stream::SocketConnection::shutdownWrite(), and core::socket::stream::SocketContext::socketConnection.
Referenced by iot::mqtt::SocketContext::end(), SimpleSocketProtocol::onReadError(), core::socket::stream::SocketContext::onReadError(), web::http::server::SocketContext< RequestT, ResponseT >::requestParsed(), and web::http::server::SocketContext< RequestT, ResponseT >::sendToPeerCompleted().
streamToPeer()
void core::socket::stream::SocketContext::streamToPeer (core::pipe::Source * source) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 46 of file SocketContext.cpp.
{
        socketConnection->streamToPeer(source);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::streamToPeer().
Referenced by web::http::server::RequestContextBase::streamToPeer().
switchSocketContext()
void core::socket::stream::SocketContext::switchSocketContext (SocketContext * newSocketContext) virtual inherited
Definition at line 34 of file SocketContext.cpp.
{
        socketConnection->switchSocketContext(newSocketContext);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::switchSocketContext().
Referenced by web::http::server::RequestContextBase::sendToPeerCompleted(), and web::http::client::Response::upgrade().
Member Data Documentation
socketConnection
core::socket::stream::SocketConnection* core::socket::stream::SocketContext::socketConnection private inherited
Definition at line 77 of file SocketContext.h.
Referenced by core::socket::stream::SocketContext::close(), core::socket::stream::SocketContext::getSocketConnection(), core::socket::stream::SocketContext::readFromPeer(), core::socket::stream::SocketContext::sendToPeer(), core::socket::stream::SocketContext::setTimeout(), core::socket::stream::SocketContext::shutdownRead(), core::socket::stream::SocketContext::shutdownWrite(), core::socket::stream::SocketContext::SocketContext(), core::socket::stream::SocketContext::streamToPeer(), and core::socket::stream::SocketContext::switchSocketContext().
The documentation for this class was generated from the following files:
web/http/SocketContext.h
web/http/SocketContext.cpp