SNode.C: database::mariadb::MariaDBCommandStartEvent Class Reference
database::mariadb::MariaDBCommandStartEvent Class Reference
#include <MariaDBConnection.h>
Public Member Functions
MariaDBCommandStartEvent (const std::string &name, MariaDBConnection *mariaDBConnection)
Private Member Functions
void onEvent (const utils::Timeval &currentTime) override
void destruct () override
void span ()
void relax ()
const std::string & getName () const
Static Private Member Functions
static void atNextTick (const std::function< void(void)> &callBack)
Private Attributes
MariaDBConnection * mariaDBConnection = nullptr
Event event
Detailed Description
Definition at line 50 of file MariaDBConnection.h.
Constructor & Destructor Documentation
MariaDBCommandStartEvent()
database::mariadb::MariaDBCommandStartEvent::MariaDBCommandStartEvent (const std::string & name, MariaDBConnection * mariaDBConnection)
Definition at line 256 of file MariaDBConnection.cpp.
        : core::EventReceiver(name)
        , mariaDBConnection(mariaDBConnection) {
    }
References core::EventReceiver::EventReceiver(), and mariaDBConnection.
Member Function Documentation
atNextTick()
void core::EventReceiver::atNextTick (const std::function< void(void)> & callBack) static inherited
Definition at line 28 of file EventReceiver.cpp.
{
        class NextTickEvent : public core::EventReceiver {
        public:
            explicit NextTickEvent(const std::function<void(void)>& callBack)
                : core::EventReceiver("RequestEvent")
                , callBack(callBack) {
            }
            void onEvent([[maybe_unused]] const utils::Timeval& currentTime) override {
                callBack();
                delete this;
            }
        private:
            std::function<void(void)> callBack;
        };
        (new NextTickEvent(callBack))->span();
    }
References core::EventReceiver::EventReceiver(), and core::EventReceiver::span().
Referenced by web::http::client::SocketContext::initiateRequest(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestDelivered(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), and core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector().
destruct()
void database::mariadb::MariaDBCommandStartEvent::destruct () override private virtual
Reimplemented from core::EventReceiver.
Definition at line 265 of file MariaDBConnection.cpp.
{
        delete mariaDBConnection;
    }
References mariaDBConnection.
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 65 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::socket::stream::tls::SocketReader::read(), core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::SocketWriter::shutdownWrite(), core::socket::stream::SocketWriter::streamEof(), core::socket::stream::SocketWriter::streamToPeer(), core::DescriptorEventReceiver::suspend(), and core::socket::stream::tls::SocketWriter::write().
onEvent()
void database::mariadb::MariaDBCommandStartEvent::onEvent (const utils::Timeval & currentTime) override private virtual
Implements core::EventReceiver.
Definition at line 261 of file MariaDBConnection.cpp.
{
        mariaDBConnection->commandStart(currentTime);
    }
References database::mariadb::MariaDBConnection::commandStart(), and mariaDBConnection.
relax()
void core::EventReceiver::relax () inherited
Definition at line 61 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
span()
void core::EventReceiver::span () inherited
Definition at line 57 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by core::EventReceiver::atNextTick(), database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), core::file::FileReader::start(), core::file::FileReader::stop(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
Member Data Documentation
event
Event core::EventReceiver::event private inherited
Definition at line 59 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
mariaDBConnection
MariaDBConnection* database::mariadb::MariaDBCommandStartEvent::mariaDBConnection = nullptr private
Definition at line 61 of file MariaDBConnection.h.
Referenced by destruct(), MariaDBCommandStartEvent(), and onEvent().
The documentation for this class was generated from the following files:
database/mariadb/MariaDBConnection.h
database/mariadb/MariaDBConnection.cpp