SNode.C: net::l2::SocketAddress Class Reference
net::l2::SocketAddress Class Reference final
#include <SocketAddress.h>
Public Member Functions
SocketAddress ()
SocketAddress (const std::string &btAddress)
SocketAddress (uint16_t psm)
SocketAddress (const std::string &btAddress, uint16_t psm)
SocketAddress (const SockAddr &sockAddr, SockLen sockAddrLen)
void init ()
SocketAddress & setBtAddress (const std::string &btAddress)
std::string getBtAddress () const
SocketAddress & setPsm (uint16_t psm)
uint16_t getPsm () const
std::string toString (bool expanded=true) const override
Public Member Functions inherited from net::SocketAddress< sockaddr_l2 >
SocketAddress (sa_family_t af, SockLen sockAddrLen=sizeof(SockAddr))
SocketAddress (const SocketAddress &socketAddress)
SocketAddress (const SockAddr &sockAddr, SockLen sockAddrLen)
SocketAddress & operator= (const SocketAddress &socketAddress)
const sockaddr & getSockAddr ()
const SockLen & getSockAddrLen () const
sa_family_t getAddressFamily () const
Public Member Functions inherited from core::socket::SocketAddress
virtual ~SocketAddress ()
virtual bool useNext ()
virtual std::string getEndpoint (const std::string_view &format={}) const
Private Types
using Super = net::SocketAddress<sockaddr_l2>
Private Attributes
std::string btAddress
uint16_t psm = 0
Additional Inherited Members
Public Types inherited from net::SocketAddress< sockaddr_l2 >
using SockAddr
using SockLen
Protected Attributes inherited from net::SocketAddress< sockaddr_l2 >
SockAddr sockAddr
SockLen sockAddrLen
Detailed Description
Definition at line 60 of file SocketAddress.h.
Member Typedef Documentation
Super
using net::l2::SocketAddress::Super = net::SocketAddress<sockaddr_l2> private
Definition at line 62 of file SocketAddress.h.
Constructor & Destructor Documentation
SocketAddress() [1/5]
net::l2::SocketAddress::SocketAddress ()
Definition at line 52 of file SocketAddress.cpp.
        : Super(AF_BLUETOOTH) {
    }
References net::SocketAddress< SockAddrT >::SocketAddress().
Referenced by SocketAddress(), SocketAddress(), and SocketAddress().
SocketAddress() [2/5]
net::l2::SocketAddress::SocketAddress (const std::string & btAddress) explicit
Definition at line 56 of file SocketAddress.cpp.
        : SocketAddress() {
        setBtAddress(btAddress);
    }
References setBtAddress(), and SocketAddress().
SocketAddress() [3/5]
net::l2::SocketAddress::SocketAddress (uint16_t psm) explicit
Definition at line 61 of file SocketAddress.cpp.
        : SocketAddress() {
        setPsm(psm);
    }
References setPsm(), and SocketAddress().
SocketAddress() [4/5]
net::l2::SocketAddress::SocketAddress (const std::string & btAddress, uint16_t psm)
Definition at line 66 of file SocketAddress.cpp.
        : SocketAddress() {
        setBtAddress(btAddress);
        setPsm(psm);
    }
References setBtAddress(), setPsm(), and SocketAddress().
Referenced by net::l2::stream::SocketClient< core::socket::stream::legacy::SocketConnector, net::l2::stream::legacy::config::ConfigSocketClient, SocketContextFactoryT, Args... >::connect(), and net::l2::config::ConfigAddress< ConfigAddressTypeT >::init().
SocketAddress() [5/5]
net::l2::SocketAddress::SocketAddress (const SockAddr & sockAddr, SockLen sockAddrLen)
Definition at line 72 of file SocketAddress.cpp.
        : net::SocketAddress<SockAddr>(sockAddr, sockAddrLen) {
        psm = btohs(sockAddr.l2_psm);
        char btAddressC[15];
        ba2str(&sockAddr.l2_bdaddr, btAddressC);
        btAddress = btAddressC;
    }
References btAddress, psm, and net::SocketAddress< SockAddrT >::SocketAddress().
Member Function Documentation
getBtAddress()
std::string net::l2::SocketAddress::getBtAddress () const
Definition at line 92 of file SocketAddress.cpp.
{
        return btAddress;
    }
References btAddress.
Referenced by net::l2::config::ConfigAddress< ConfigAddressTypeT >::setSocketAddress().
getPsm()
uint16_t net::l2::SocketAddress::getPsm () const
Definition at line 102 of file SocketAddress.cpp.
{
        return psm;
    }
References psm.
Referenced by net::l2::config::ConfigAddress< ConfigAddressTypeT >::setSocketAddress().
init()
void net::l2::SocketAddress::init ()
Definition at line 81 of file SocketAddress.cpp.
{
        sockAddr.l2_psm = htobs(psm);
        str2ba(btAddress.c_str(), &sockAddr.l2_bdaddr);
    }
References btAddress, and psm.
Referenced by net::l2::config::ConfigAddress< ConfigAddressTypeT >::init().
setBtAddress()
SocketAddress & net::l2::SocketAddress::setBtAddress (const std::string & btAddress)
Definition at line 86 of file SocketAddress.cpp.
{
        this->btAddress = btAddress;
        return *this;
    }
References btAddress.
Referenced by SocketAddress(), and SocketAddress().
setPsm()
SocketAddress & net::l2::SocketAddress::setPsm (uint16_t psm)
Definition at line 96 of file SocketAddress.cpp.
{
        this->psm = psm;
        return *this;
    }
References psm.
Referenced by SocketAddress(), and SocketAddress().
toString()
std::string net::l2::SocketAddress::toString (bool expanded = true) const override virtual
Implements core::socket::SocketAddress.
Definition at line 106 of file SocketAddress.cpp.
{
        return std::string(btAddress).append(":").append(std::to_string(psm));
    }
References btAddress, and psm.
Member Data Documentation
btAddress
std::string net::l2::SocketAddress::btAddress private
Definition at line 82 of file SocketAddress.h.
Referenced by getBtAddress(), init(), setBtAddress(), SocketAddress(), and toString().
psm
uint16_t net::l2::SocketAddress::psm = 0 private
Definition at line 83 of file SocketAddress.h.
Referenced by getPsm(), init(), setPsm(), SocketAddress(), and toString().
The documentation for this class was generated from the following files:
net/l2/SocketAddress.h
net/l2/SocketAddress.cpp