SNode.C: iot::mqtt::server::broker::SubscriptionTree::TopicLevel Class Reference
iot::mqtt::server::broker::SubscriptionTree::TopicLevel Class Reference
Public Member Functions
TopicLevel (iot::mqtt::server::broker::Broker *broker, const std::string &topicLevel)
void appear (const std::string &clientId, const std::string &topic)
bool subscribe (const std::string &clientId, uint8_t qoS, std::string topic)
void publish (Message &message, std::string topic)
bool unsubscribe (const std::string &clientId, std::string topic)
bool unsubscribe (const std::string &clientId)
std::list< std::string > getSubscriptions (const std::string &clientId) const
std::map< std::string, std::list< std::pair< std::string, uint8_t > > > getSubscriptionTree () const
TopicLevel & fromJson (const nlohmann::json &json)
nlohmann::json toJson () const
void clear ()
Private Member Functions
std::list< std::string > getSubscriptions (const std::string &absoluteTopicLevel, const std::string &clientId) const
std::map< std::string, std::list< std::pair< std::string, uint8_t > > > getSubscriptionTree (const std::string &absoluteTopicLevel) const
Private Attributes
iot::mqtt::server::broker::Broker * broker
std::map< std::string, uint8_t > clientIds
std::map< std::string, TopicLevel > topicLevels
std::string topicLevel
Detailed Description
Definition at line 87 of file SubscriptionTree.h.
Constructor & Destructor Documentation
TopicLevel()
iot::mqtt::server::broker::SubscriptionTree::TopicLevel::TopicLevel (iot::mqtt::server::broker::Broker * broker, const std::string & topicLevel) explicit
Definition at line 128 of file SubscriptionTree.cpp.
        : broker(broker)
        , topicLevel(topicLevel) {
    }
References topicLevel.
Referenced by clear(), fromJson(), subscribe(), and iot::mqtt::server::broker::SubscriptionTree::SubscriptionTree().
Member Function Documentation
appear()
void iot::mqtt::server::broker::SubscriptionTree::TopicLevel::appear (const std::string & clientId, const std::string & topic)
Definition at line 133 of file SubscriptionTree.cpp.
{
        if (clientIds.contains(clientId)) {
            broker->appear(clientId, topic, clientIds[clientId]);
        }
        for (auto& [topicLevel, subscription] : topicLevels) {
            subscription.appear(clientId, std::string(topic).append(topic.empty() ? "" : "/").append(topicLevel));
        }
    }
References iot::mqtt::server::broker::Broker::appear(), appear(), clientIds, and topicLevels.
Referenced by iot::mqtt::server::broker::SubscriptionTree::appear(), and appear().
clear()
void iot::mqtt::server::broker::SubscriptionTree::TopicLevel::clear ()
Definition at line 345 of file SubscriptionTree.cpp.
{
        *this = TopicLevel(broker, "");
    }
References TopicLevel().
Referenced by iot::mqtt::server::broker::SubscriptionTree::clear().
fromJson()
SubscriptionTree::TopicLevel & iot::mqtt::server::broker::SubscriptionTree::TopicLevel::fromJson (const nlohmann::json & json)
Definition at line 326 of file SubscriptionTree.cpp.
{
        clientIds.clear();
        topicLevels.clear();
        if (json.contains("qos_map")) {
            for (const auto& subscriber : json["qos_map"].items()) {
                clientIds.emplace(subscriber.key(), subscriber.value());
            }
        }
        if (json.contains("topic_filter")) {
            for (const auto& topicLevelItem : json["topic_filter"].items()) {
                topicLevels.emplace(topicLevelItem.key(), TopicLevel(broker, topicLevelItem.key()).fromJson(topicLevelItem.value()));
            }
        }
        return *this;
    }
References clientIds, fromJson(), TopicLevel(), and topicLevels.
Referenced by iot::mqtt::server::broker::SubscriptionTree::fromJson(), and fromJson().
getSubscriptions() [1/2]
std::list< std::string > iot::mqtt::server::broker::SubscriptionTree::TopicLevel::getSubscriptions (const std::string & absoluteTopicLevel, const std::string & clientId) const private
Definition at line 289 of file SubscriptionTree.cpp.
{
        std::list<std::string> topicLevelList;
        for (const auto& [topicLevelName, nextTopicLevel] : topicLevels) {
            const std::string currentAbsoluteTopicLevel = absoluteTopicLevel + topicLevelName;
            if (nextTopicLevel.clientIds.contains(clientId)) {
                topicLevelList.push_back(currentAbsoluteTopicLevel);
            }
            topicLevelList.splice(topicLevelList.end(), nextTopicLevel.getSubscriptions(currentAbsoluteTopicLevel + "/", clientId));
        }
        return topicLevelList;
    }
References clientIds, getSubscriptions(), and topicLevels.
Referenced by getSubscriptions(), and getSubscriptions().
getSubscriptions() [2/2]
std::list< std::string > iot::mqtt::server::broker::SubscriptionTree::TopicLevel::getSubscriptions (const std::string & clientId) const
Definition at line 281 of file SubscriptionTree.cpp.
{
        return getSubscriptions("", clientId);
    }
References getSubscriptions().
Referenced by iot::mqtt::server::broker::SubscriptionTree::getSubscriptions().
getSubscriptionTree() [1/2]
std::map< std::string, std::list< std::pair< std::string, uint8_t > > > iot::mqtt::server::broker::SubscriptionTree::TopicLevel::getSubscriptionTree () const
Definition at line 285 of file SubscriptionTree.cpp.
{
        return getSubscriptionTree("");
    }
References getSubscriptionTree().
Referenced by iot::mqtt::server::broker::SubscriptionTree::getSubscriptionTree().
getSubscriptionTree() [2/2]
std::map< std::string, std::list< std::pair< std::string, uint8_t > > > iot::mqtt::server::broker::SubscriptionTree::TopicLevel::getSubscriptionTree (const std::string & absoluteTopicLevel) const private
Definition at line 307 of file SubscriptionTree.cpp.
{
        std::map<std::string, std::list<std::pair<std::string, uint8_t>>> topicLevelTree;
        for (const auto& [topicLevelName, nextTopicLevel] : topicLevels) {
            const std::string composedAbsoluteTopicLevelName = absoluteTopicLevel + topicLevelName;
            for (const auto& clientId : nextTopicLevel.clientIds) {
                topicLevelTree[composedAbsoluteTopicLevelName].emplace_back(clientId);
            }
            std::map<std::string, std::list<std::pair<std::string, uint8_t>>> subSubscriptionTree =
                nextTopicLevel.getSubscriptionTree(composedAbsoluteTopicLevelName + "/");
            topicLevelTree.insert(subSubscriptionTree.begin(), subSubscriptionTree.end());
        }
        return topicLevelTree;
    }
References clientIds, getSubscriptionTree(), and topicLevels.
Referenced by getSubscriptionTree(), and getSubscriptionTree().
publish()
void iot::mqtt::server::broker::SubscriptionTree::TopicLevel::publish (Message & message, std::string topic)
Definition at line 168 of file SubscriptionTree.cpp.
{
        if (topic.empty()) {
            LOG(INFO) << "MQTT Broker: Found match:";
            LOG(INFO) << "MQTT Broker:   Topic: '" << message.getTopic() << "';";
            LOG(INFO) << "MQTT Broker:   Message:\n" << iot::mqtt::Mqtt::toHexString(message.getMessage());
            LOG(INFO) << "MQTT Broker: Distribute PUBLISH for match ...";
            for (auto& [clientId, clientQoS] : clientIds) {
                broker->sendPublish(clientId, message, clientQoS, false);
            }
            LOG(INFO) << "MQTT Broker: ... distributing PUBLISH for match completed";
            const auto nextHashLevel = topicLevels.find("#");
            if (nextHashLevel != topicLevels.end()) {
                LOG(INFO) << "MQTT Broker: Found parent match:";
                LOG(INFO) << "MQTT Broker:   Topic: '" << message.getTopic() << "'";
                LOG(INFO) << "MQTT Broker:   Message:\n" << iot::mqtt::Mqtt::toHexString(message.getMessage());
                LOG(INFO) << "MQTT Broker: Distribute PUBLISH for match ...";
                for (auto& [clientId, clientQoS] : nextHashLevel->second.clientIds) {
                    broker->sendPublish(clientId, message, clientQoS, false);
                }
                LOG(INFO) << "MQTT Broker: ... distributing PUBLISH for match completed";
            }
        } else {
            const std::string topicLevel = topic.substr(0, topic.find('/'));
            topic.erase(0, topicLevel.size() + 1);
            auto foundNode = topicLevels.find(topicLevel);
            if (foundNode != topicLevels.end()) {
                foundNode->second.publish(message, topic);
            }
            foundNode = topicLevels.find("+");
            if (foundNode != topicLevels.end()) {
                foundNode->second.publish(message, topic);
            }
            foundNode = topicLevels.find("#");
            if (foundNode != topicLevels.end()) {
                LOG(INFO) << "MQTT Broker: Found match:";
                LOG(INFO) << "MQTT Broker:   Topic: '" << message.getTopic() << "'";
                LOG(INFO) << "MQTT Broker:   Message:\n" << iot::mqtt::Mqtt::toHexString(message.getMessage());
                LOG(INFO) << "MQTT Broker: Distribute PUBLISH for match '" << message.getTopic() << "' ...";
                for (auto& [clientId, clientQoS] : foundNode->second.clientIds) {
                    broker->sendPublish(clientId, message, clientQoS, false);
                }
                LOG(INFO) << "MQTT Broker: ... distributing PUBLISH for match completed";
            }
        }
    }
References clientIds, iot::mqtt::server::broker::Message::getMessage(), iot::mqtt::server::broker::Message::getTopic(), publish(), iot::mqtt::server::broker::Broker::sendPublish(), iot::mqtt::Mqtt::toHexString(), and topicLevels.
Referenced by iot::mqtt::server::broker::SubscriptionTree::publish(), and publish().
subscribe()
bool iot::mqtt::server::broker::SubscriptionTree::TopicLevel::subscribe (const std::string & clientId, uint8_t qoS, std::string topic)
Definition at line 143 of file SubscriptionTree.cpp.
{
        if (topic.empty()) {
            LOG(INFO) << "MQTT Broker: Subscribe";
            LOG(INFO) << "MQTT Broker:   ClientId: " << clientId;
            clientIds[clientId] = qoS;
        } else {
            const std::string topicLevel = topic.substr(0, topic.find('/'));
            topic.erase(0, topicLevel.size() + 1);
            const auto& [it, inserted] = topicLevels.insert({topicLevel, SubscriptionTree::TopicLevel(broker, topicLevel)});
            if (!it->second.subscribe(clientId, qoS, topic)) {
                LOG(DEBUG) << "MQTT Broker:   Erase topic: " << topicLevel << " /" << topic;
                topicLevels.erase(it);
            } else {
                LOG(INFO) << "MQTT Broker:   Topic: " << topicLevel << " /" << topic;
            }
        }
        return !topicLevels.empty() || !clientIds.empty();
    }
References clientIds, subscribe(), TopicLevel(), and topicLevels.
Referenced by iot::mqtt::server::broker::SubscriptionTree::subscribe(), and subscribe().
toJson()
nlohmann::json iot::mqtt::server::broker::SubscriptionTree::TopicLevel::toJson () const
Definition at line 267 of file SubscriptionTree.cpp.
{
        nlohmann::json json;
        for (const auto& [topicLevelName, topicLevel] : topicLevels) {
            json["topic_filter"][topicLevelName] = topicLevel.toJson();
        }
        for (const auto& [subscriber, qoS] : clientIds) {
            json["qos_map"][subscriber] = qoS;
        }
        return json;
    }
References clientIds, toJson(), and topicLevels.
Referenced by iot::mqtt::server::broker::SubscriptionTree::toJson(), and toJson().
unsubscribe() [1/2]
bool iot::mqtt::server::broker::SubscriptionTree::TopicLevel::unsubscribe (const std::string & clientId)
Definition at line 247 of file SubscriptionTree.cpp.
{
        if (clientIds.erase(clientId) != 0) {
            LOG(INFO) << "MQTT Broker: Unsubscribe";
            LOG(INFO) << "MQTT Broker:   ClientId: " << clientId;
            LOG(INFO) << "MQTT Broker:   Topic: " << topicLevel;
        }
        for (auto it = topicLevels.begin(); it != topicLevels.end();) {
            if (it->second.unsubscribe(clientId)) {
                LOG(DEBUG) << "MQTT Broker:   Erase Topic: " << it->first;
                it = topicLevels.erase(it);
            } else {
                ++it;
            }
        }
        return clientIds.empty() && topicLevels.empty();
    }
References clientIds, topicLevel, topicLevels, and unsubscribe().
Referenced by unsubscribe(), and iot::mqtt::server::broker::SubscriptionTree::unsubscribe().
unsubscribe() [2/2]
bool iot::mqtt::server::broker::SubscriptionTree::TopicLevel::unsubscribe (const std::string & clientId, std::string topic)
Definition at line 222 of file SubscriptionTree.cpp.
{
        if (topic.empty()) {
            if (clientIds.erase(clientId) != 0) {
                LOG(INFO) << "MQTT Broker: Unsubscribe";
                LOG(INFO) << "MQTT Broker:   ClientId: " << clientId;
                LOG(INFO) << "MQTT Broker:   Topic: " << topicLevel;
            }
        } else {
            const std::string topicLevel = topic.substr(0, topic.find('/'));
            auto&& it = topicLevels.find(topicLevel);
            if (it != topicLevels.end()) {
                topic.erase(0, topicLevel.size() + 1);
                if (it->second.unsubscribe(clientId, topic)) {
                    LOG(DEBUG) << "MQTT Broker:   Erase Topic: " << it->first;
                    topicLevels.erase(it);
                }
            }
        }
        return clientIds.empty() && topicLevels.empty();
    }
References clientIds, topicLevel, topicLevels, and unsubscribe().
Referenced by unsubscribe(), and iot::mqtt::server::broker::SubscriptionTree::unsubscribe().
Member Data Documentation
broker
iot::mqtt::server::broker::Broker* iot::mqtt::server::broker::SubscriptionTree::TopicLevel::broker private
Definition at line 114 of file SubscriptionTree.h.
clientIds
std::map<std::string, uint8_t> iot::mqtt::server::broker::SubscriptionTree::TopicLevel::clientIds private
Definition at line 116 of file SubscriptionTree.h.
Referenced by appear(), fromJson(), getSubscriptions(), getSubscriptionTree(), publish(), subscribe(), toJson(), unsubscribe(), and unsubscribe().
topicLevel
std::string iot::mqtt::server::broker::SubscriptionTree::TopicLevel::topicLevel private
Definition at line 119 of file SubscriptionTree.h.
Referenced by TopicLevel(), unsubscribe(), and unsubscribe().
topicLevels
std::map<std::string, TopicLevel> iot::mqtt::server::broker::SubscriptionTree::TopicLevel::topicLevels private
Definition at line 117 of file SubscriptionTree.h.
Referenced by appear(), fromJson(), getSubscriptions(), getSubscriptionTree(), publish(), subscribe(), toJson(), unsubscribe(), and unsubscribe().
The documentation for this class was generated from the following files:
iot/mqtt/server/broker/SubscriptionTree.h
iot/mqtt/server/broker/SubscriptionTree.cpp