SNode.C: net::config::ConfigConnection Class Reference
net::config::ConfigConnection Class Reference
#include <ConfigConnection.h>
Public Member Functions
ConfigConnection (ConfigInstance *instance)
utils::Timeval getReadTimeout () const
ConfigConnection & setReadTimeout (const utils::Timeval &newReadTimeoutSet)
utils::Timeval getWriteTimeout () const
ConfigConnection & setWriteTimeout (const utils::Timeval &newWriteTimeoutSet)
std::size_t getReadBlockSize () const
ConfigConnection & setReadBlockSize (std::size_t newReadBlockSize)
std::size_t getWriteBlockSize () const
ConfigConnection & setWriteBlockSize (std::size_t newWriteBlockSize)
utils::Timeval getTerminateTimeout () const
ConfigConnection & setTerminateTimeout (const utils::Timeval &newTerminateTimeout)
Protected Member Functions
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
Protected Attributes
CLI::App * section = nullptr
Private Attributes
CLI::Option * readTimeoutOpt = nullptr
CLI::Option * writeTimeoutOpt = nullptr
CLI::Option * readBlockSizeOpt = nullptr
CLI::Option * writeBlockSizeOpt = nullptr
CLI::Option * terminateTimeoutOpt = nullptr
ConfigInstance * instance = nullptr
uint8_t requiredCount = 0
Detailed Description
Definition at line 42 of file ConfigConnection.h.
Constructor & Destructor Documentation
ConfigConnection()
net::config::ConfigConnection::ConfigConnection (ConfigInstance * instance) explicit
Definition at line 32 of file ConfigConnection.cpp.
        : net::config::ConfigSection(instance, "connection", "Configuration of established connections") {
        add_option(readTimeoutOpt, //
                   "--read-timeout",
                   "Read timeout in seconds",
                   "timeout",
                   READ_TIMEOUT,
                   CLI::PositiveNumber);
        add_option(writeTimeoutOpt, //
                   "--write-timeout",
                   "Write timeout in seconds",
                   "timeout",
                   WRITE_TIMEOUT,
                   CLI::PositiveNumber);
        add_option(readBlockSizeOpt, //
                   "--read-block-size",
                   "Read block size",
                   "size",
                   READ_BLOCKSIZE,
                   CLI::PositiveNumber);
        add_option(writeBlockSizeOpt, //
                   "--write-block-size",
                   "Write block size",
                   "size",
                   WRITE_BLOCKSIZE,
                   CLI::PositiveNumber);
        add_option(terminateTimeoutOpt, //
                   "--terminate-timeout",
                   "Terminate timeout",
                   "timeout",
                   TERMINATE_TIMEOUT,
                   CLI::PositiveNumber);
    }
References net::config::ConfigSection::ConfigSection().
Member Function Documentation
add_flag() [1/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 110 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag(name, description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [2/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 125 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [3/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 64 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [4/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 71 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [5/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_flag() [6/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag_function() [1/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) protected inherited
Definition at line 134 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [2/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 155 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), and net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient().
add_option() [1/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) protected inherited
Definition at line 79 of file ConfigSection.cpp.
{
        if (!instance->getInstanceName().empty() && !section->get_display_name().empty()) {
            section->disabled(false);
        }
        opt = section //
                  ->add_option(name, description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigInstance::getInstanceName(), net::config::ConfigSection::instance, and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [2/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 95 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [3/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 100 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [4/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 46 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [5/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 53 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [6/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
Referenced by net::config::ConfigTls::ConfigTls().
add_option() [7/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
getReadBlockSize()
std::size_t net::config::ConfigConnection::getReadBlockSize () const
Definition at line 94 of file ConfigConnection.cpp.
{
        return readBlockSizeOpt->as<std::size_t>();
    }
References readBlockSizeOpt.
getReadTimeout()
utils::Timeval net::config::ConfigConnection::getReadTimeout () const
Definition at line 70 of file ConfigConnection.cpp.
{
        return readTimeoutOpt->as<utils::Timeval>();
    }
References readTimeoutOpt.
getTerminateTimeout()
utils::Timeval net::config::ConfigConnection::getTerminateTimeout () const
Definition at line 118 of file ConfigConnection.cpp.
{
        return terminateTimeoutOpt->as<utils::Timeval>();
    }
References terminateTimeoutOpt.
getWriteBlockSize()
std::size_t net::config::ConfigConnection::getWriteBlockSize () const
Definition at line 106 of file ConfigConnection.cpp.
{
        return writeBlockSizeOpt->as<std::size_t>();
    }
References writeBlockSizeOpt.
getWriteTimeout()
utils::Timeval net::config::ConfigConnection::getWriteTimeout () const
Definition at line 82 of file ConfigConnection.cpp.
{
        return writeTimeoutOpt->as<utils::Timeval>();
    }
References writeTimeoutOpt.
required() [1/2]
bool net::config::ConfigSection::required () const protected inherited
Definition at line 75 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [2/2]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) protected inherited
Definition at line 58 of file ConfigSection.cpp.
{
        if (req != opt->get_required()) {
            if (req) {
                ++requiredCount;
                section->needs(opt);
                opt->default_str("");
            } else {
                --requiredCount;
                section->remove_needs(opt);
            }
            opt->required(req);
            instance->required(section, requiredCount > 0);
        }
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
setReadBlockSize()
ConfigConnection & net::config::ConfigConnection::setReadBlockSize (std::size_t newReadBlockSize)
Definition at line 98 of file ConfigConnection.cpp.
{
        readBlockSizeOpt //
            ->default_val(newReadBlockSize)
            ->clear();
        return *this;
    }
References readBlockSizeOpt.
setReadTimeout()
ConfigConnection & net::config::ConfigConnection::setReadTimeout (const utils::Timeval & newReadTimeoutSet)
Definition at line 74 of file ConfigConnection.cpp.
{
        readTimeoutOpt //
            ->default_val(newReadTimeoutSet)
            ->clear();
        return *this;
    }
References readTimeoutOpt.
setTerminateTimeout()
ConfigConnection & net::config::ConfigConnection::setTerminateTimeout (const utils::Timeval & newTerminateTimeout)
Definition at line 122 of file ConfigConnection.cpp.
{
        terminateTimeoutOpt //
            ->default_val(newTerminateTimeout)
            ->clear();
        return *this;
    }
References terminateTimeoutOpt.
setWriteBlockSize()
ConfigConnection & net::config::ConfigConnection::setWriteBlockSize (std::size_t newWriteBlockSize)
Definition at line 110 of file ConfigConnection.cpp.
{
        writeBlockSizeOpt //
            ->default_val(newWriteBlockSize)
            ->clear();
        return *this;
    }
References writeBlockSizeOpt.
setWriteTimeout()
ConfigConnection & net::config::ConfigConnection::setWriteTimeout (const utils::Timeval & newWriteTimeoutSet)
Definition at line 86 of file ConfigConnection.cpp.
{
        writeTimeoutOpt //
            ->default_val(newWriteTimeoutSet)
            ->clear();
        return *this;
    }
References writeTimeoutOpt.
Member Data Documentation
instance
ConfigInstance* net::config::ConfigSection::instance = nullptr private inherited
Definition at line 121 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), and net::config::ConfigSection::required().
readBlockSizeOpt
CLI::Option* net::config::ConfigConnection::readBlockSizeOpt = nullptr private
Definition at line 64 of file ConfigConnection.h.
Referenced by getReadBlockSize(), and setReadBlockSize().
readTimeoutOpt
CLI::Option* net::config::ConfigConnection::readTimeoutOpt = nullptr private
Definition at line 62 of file ConfigConnection.h.
Referenced by getReadTimeout(), and setReadTimeout().
requiredCount
uint8_t net::config::ConfigSection::requiredCount = 0 private inherited
Definition at line 123 of file ConfigSection.h.
Referenced by net::config::ConfigSection::required(), and net::config::ConfigSection::required().
section
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 126 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
terminateTimeoutOpt
CLI::Option* net::config::ConfigConnection::terminateTimeoutOpt = nullptr private
Definition at line 66 of file ConfigConnection.h.
Referenced by getTerminateTimeout(), and setTerminateTimeout().
writeBlockSizeOpt
CLI::Option* net::config::ConfigConnection::writeBlockSizeOpt = nullptr private
Definition at line 65 of file ConfigConnection.h.
Referenced by getWriteBlockSize(), and setWriteBlockSize().
writeTimeoutOpt
CLI::Option* net::config::ConfigConnection::writeTimeoutOpt = nullptr private
Definition at line 63 of file ConfigConnection.h.
Referenced by getWriteTimeout(), and setWriteTimeout().
The documentation for this class was generated from the following files:
net/config/ConfigConnection.h
net/config/ConfigConnection.cpp