SNode.C: utils::Timeval Class Reference
utils::Timeval Class Reference
#include <Timeval.h>
Public Member Functions
Timeval () noexcept
Timeval (const std::initializer_list< time_t > &initList) noexcept
Timeval (const Timeval &timeVal) noexcept=default
Timeval (double time) noexcept
Timeval (const timeval &timeVal) noexcept
Timeval & operator= (const Timeval &timeVal)
Timeval & operator= (const timeval &timeVal)
Timeval operator+ (const Timeval &timeVal) const
Timeval operator- (const Timeval &timeVal) const
Timeval operator* (double mul) const
Timeval & operator+= (const Timeval &timeVal)
Timeval & operator-= (const Timeval &timeVal)
Timeval & operator*= (double mul)
Timeval operator- () const
bool operator< (const Timeval &timeVal) const
bool operator> (const Timeval &timeVal) const
bool operator<= (const Timeval &timeVal) const
bool operator>= (const Timeval &timeVal) const
bool operator== (const Timeval &timeVal) const
bool operator!= (const Timeval &timeVal) const
timeval * operator& ()
const timeval * operator& () const
timespec getTimespec () const
int getMs () const
double getMsd () const
Static Public Member Functions
static Timeval currentTime ()
Private Member Functions
const Timeval & normalize ()
Private Attributes
timeval timeVal = {0, 0}
Friends
std::ostream & operator<< (std::ostream &ostream, const utils::Timeval &timeVal)
Timeval operator* (double mul, const Timeval &timeVal)
Detailed Description
Definition at line 58 of file Timeval.h.
Constructor & Destructor Documentation
Timeval() [1/5]
utils::Timeval::Timeval () noexcept
Definition at line 55 of file Timeval.cpp.
        : timeVal({}) {
    }
References timeVal.
Referenced by core::EventMultiplexer::getNextTimeout().
Timeval() [2/5]
utils::Timeval::Timeval (const std::initializer_list< time_t > & initList) noexcept
Definition at line 59 of file Timeval.cpp.
        : timeVal({}) {
        timeVal.tv_sec = *initList.begin();
        timeVal.tv_usec = static_cast<suseconds_t>(*(initList.begin() + 1));
    }
References timeVal.
Referenced by core::TimerEventPublisher::getNextTimeout(), and operator-().
Timeval() [3/5]
utils::Timeval::Timeval (const Timeval & timeVal) default noexcept
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), core::socket::stream::SocketReader::SocketReader(), core::socket::stream::SocketWriter::SocketWriter(), and core::TimerEventReceiver::TimerEventReceiver().
Timeval() [4/5]
utils::Timeval::Timeval (double time) noexcept
Definition at line 65 of file Timeval.cpp.
{
        timeVal.tv_sec = static_cast<time_t>(time);
        timeVal.tv_usec = static_cast<suseconds_t>((time - static_cast<double>(timeVal.tv_sec)) * 1'000'000.0);
        normalize();
    }
References normalize(), and timeVal.
Referenced by net::config::ConfigPhysicalSocketClient::getConnectTimeout().
Timeval() [5/5]
utils::Timeval::Timeval (const timeval & timeVal) noexcept
Definition at line 72 of file Timeval.cpp.
        : timeVal(timeVal) {
    }
References timeVal.
Member Function Documentation
currentTime()
Timeval utils::Timeval::currentTime () static
Definition at line 76 of file Timeval.cpp.
{
        utils::Timeval currentTime;
        utils::system::gettimeofday(&currentTime, nullptr);
        return currentTime;
    }
References utils::system::gettimeofday(), and operator&().
Referenced by core::DescriptorEventPublisher::enable(), core::TimerEventReceiver::restart(), core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setTimeout(), core::EventMultiplexer::signal(), core::EventMultiplexer::terminate(), core::EventMultiplexer::tick(), and core::TimerEventReceiver::TimerEventReceiver().
getMs()
int utils::Timeval::getMs () const
Definition at line 177 of file Timeval.cpp.
{
        int ms = 0;
        if (timeVal.tv_sec > INT_MAX - 1) {
            ms = INT_MAX;
        } else {
            ms = static_cast<int>(static_cast<double>(timeVal.tv_sec) * 1'000. + static_cast<double>(timeVal.tv_usec) / 1'000. + 0.5);
        }
        return ms;
    }
References timeVal.
Referenced by core::multiplexer::epoll::EventMultiplexer::monitorDescriptors().
getMsd()
double utils::Timeval::getMsd () const
Definition at line 189 of file Timeval.cpp.
{
        double msd = 0;
        if (timeVal.tv_sec > INT_MAX - 1) {
            msd = INT_MAX;
        } else {
            msd = static_cast<double>(timeVal.tv_sec) * 1'000. + static_cast<double>(timeVal.tv_usec) / 1'000.;
        }
        return msd;
    }
References timeVal.
Referenced by core::TimerEventReceiver::onEvent().
getTimespec()
timespec utils::Timeval::getTimespec () const
Definition at line 173 of file Timeval.cpp.
{
        return timespec{timeVal.tv_sec, static_cast<int32_t>(timeVal.tv_usec * 1000)};
    }
References timeVal.
Referenced by core::multiplexer::poll::EventMultiplexer::monitorDescriptors(), and core::multiplexer::select::EventMultiplexer::monitorDescriptors().
normalize()
const Timeval & utils::Timeval::normalize () private
Definition at line 204 of file Timeval.cpp.
{
        while (timeVal.tv_usec > 999'999 || timeVal.tv_usec < 0) {
            if (timeVal.tv_usec > 999'999) {
                timeVal.tv_usec -= 1'000'000;
                timeVal.tv_sec++;
            } else if (timeVal.tv_usec < 0) {
                timeVal.tv_usec += 1'000'000;
                timeVal.tv_sec--;
            }
        }
        return *this;
    }
References timeVal.
Referenced by operator*(), operator*, operator*=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), and Timeval().
operator!=()
bool utils::Timeval::operator!= (const Timeval & timeVal) const
Definition at line 165 of file Timeval.cpp.
{
        return !(*this == timeVal);
    }
References operator==().
operator&() [1/2]
timeval * utils::Timeval::operator& ()
Definition at line 169 of file Timeval.cpp.
{
        return &timeVal;
    }
References timeVal.
Referenced by currentTime().
operator&() [2/2]
const timeval * utils::Timeval::operator& () const
Definition at line 200 of file Timeval.cpp.
{
        return &timeVal;
    }
References timeVal.
Referenced by operator=().
operator*()
Timeval utils::Timeval::operator* (double mul) const
Definition at line 116 of file Timeval.cpp.
{
        utils::Timeval help;
        help.timeVal.tv_sec = static_cast<time_t>(static_cast<double>(this->timeVal.tv_sec) * mul);
        help.timeVal.tv_usec = static_cast<suseconds_t>(static_cast<double>(this->timeVal.tv_usec) * mul);
        return help.normalize();
    }
References normalize(), and timeVal.
Referenced by operator*=().
operator*=()
Timeval & utils::Timeval::operator*= (double mul)
Definition at line 135 of file Timeval.cpp.
{
        *this = (*this * mul).normalize();
        return *this;
    }
References normalize(), operator*(), and operator=().
Referenced by iot::mqtt::Mqtt::initSession().
operator+()
Timeval utils::Timeval::operator+ (const Timeval & timeVal) const
Definition at line 98 of file Timeval.cpp.
{
        utils::Timeval help;
        help.timeVal.tv_sec = this->timeVal.tv_sec + timeVal.timeVal.tv_sec;
        help.timeVal.tv_usec = this->timeVal.tv_usec + timeVal.timeVal.tv_usec;
        return help.normalize();
    }
References normalize(), and timeVal.
Referenced by operator+=(), core::TimerEventReceiver::restart(), and core::TimerEventReceiver::TimerEventReceiver().
operator+=()
Timeval & utils::Timeval::operator+= (const Timeval & timeVal)
Definition at line 125 of file Timeval.cpp.
{
        *this = (*this + timeVal).normalize();
        return *this;
    }
References normalize(), operator+(), and operator=().
Referenced by core::TimerEventReceiver::update().
operator-() [1/2]
Timeval utils::Timeval::operator- () const
Definition at line 140 of file Timeval.cpp.
{
        return Timeval({-this->timeVal.tv_sec, -this->timeVal.tv_usec}).normalize();
    }
References normalize(), Timeval(), and timeVal.
operator-() [2/2]
Timeval utils::Timeval::operator- (const Timeval & timeVal) const
Definition at line 107 of file Timeval.cpp.
{
        utils::Timeval help;
        help.timeVal.tv_sec = this->timeVal.tv_sec - timeVal.timeVal.tv_sec;
        help.timeVal.tv_usec = this->timeVal.tv_usec - timeVal.timeVal.tv_usec;
        return help.normalize();
    }
References normalize(), and timeVal.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::getTimeout(), core::TimerEventReceiver::getTimeoutRelative(), core::TimerEventReceiver::onEvent(), and operator-=().
operator-=()
Timeval & utils::Timeval::operator-= (const Timeval & timeVal)
Definition at line 130 of file Timeval.cpp.
{
        *this = (*this - timeVal).normalize();
        return *this;
    }
References normalize(), operator-(), and operator=().
Referenced by core::EventLoop::free().
operator<()
bool utils::Timeval::operator< (const Timeval & timeVal) const
Definition at line 144 of file Timeval.cpp.
{
        return (this->timeVal.tv_sec < timeVal.timeVal.tv_sec) ||
               ((this->timeVal.tv_sec == timeVal.timeVal.tv_sec) && (this->timeVal.tv_usec < timeVal.timeVal.tv_usec));
    }
References timeVal.
Referenced by core::TimerEventPublisher::timernode_lt::operator()(), operator==(), operator>(), and operator>=().
operator<=()
bool utils::Timeval::operator<= (const Timeval & timeVal) const
Definition at line 153 of file Timeval.cpp.
{
        return !(*this > timeVal);
    }
References operator>().
Referenced by core::TimerEventPublisher::spanActiveEvents().
operator=() [1/2]
Timeval & utils::Timeval::operator= (const Timeval & timeVal)
Definition at line 83 of file Timeval.cpp.
                                                      { // NOLINT
        if (&this->timeVal != &timeVal) {
            this->timeVal.tv_sec = timeVal.timeVal.tv_sec;
            this->timeVal.tv_usec = timeVal.timeVal.tv_usec;
        }
        return *this;
    }
References operator&(), and timeVal.
Referenced by database::mariadb::MariaDBCommand::commandStart(), core::DescriptorEventPublisher::getNextTimeout(), core::EventMultiplexer::getNextTimeout(), core::TimerEventPublisher::getNextTimeout(), operator*=(), operator+=(), operator-=(), core::TimerEventReceiver::restart(), core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setEnabled(), core::DescriptorEventReceiver::setTimeout(), and core::DescriptorEventReceiver::triggered().
operator=() [2/2]
Timeval & utils::Timeval::operator= (const timeval & timeVal)
Definition at line 92 of file Timeval.cpp.
{
        this->timeVal = timeVal;
        return *this;
    }
References timeVal.
operator==()
bool utils::Timeval::operator== (const Timeval & timeVal) const
Definition at line 161 of file Timeval.cpp.
{
        return !(*this < timeVal) && !(*this > timeVal);
    }
References operator<(), and operator>().
Referenced by operator!=(), and core::DescriptorEventReceiver::setTimeout().
operator>()
bool utils::Timeval::operator> (const Timeval & timeVal) const
Definition at line 149 of file Timeval.cpp.
{
        return timeVal < *this;
    }
References operator<().
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::EventLoop::free(), core::DescriptorEventReceiver::getTimeout(), core::TimerEventReceiver::getTimeoutRelative(), iot::mqtt::Mqtt::initSession(), operator<=(), and operator==().
operator>=()
bool utils::Timeval::operator>= (const Timeval & timeVal) const
Definition at line 157 of file Timeval.cpp.
{
        return !(*this < timeVal);
    }
References operator<().
Referenced by core::DescriptorEventReceiver::checkTimeout().
Friends And Related Symbol Documentation
operator*
Timeval operator* (double mul, const Timeval & timeVal) friend
Definition at line 223 of file Timeval.cpp.
{
        utils::Timeval help;
        help.timeVal.tv_sec = static_cast<time_t>(static_cast<double>(timeVal.timeVal.tv_sec) * mul);
        help.timeVal.tv_usec = static_cast<suseconds_t>(static_cast<double>(timeVal.timeVal.tv_usec) * mul);
        return help.normalize();
    }
References normalize(), and timeVal.
operator<<
std::ostream & operator<< (std::ostream & ostream, const utils::Timeval & timeVal) friend
Definition at line 218 of file Timeval.cpp.
{
        return ostream << std::string("{") + std::to_string(timeVal.timeVal.tv_sec) + std::string(":") +
                              std::to_string(timeVal.timeVal.tv_usec) + std::string("}");
    }
References timeVal.
Member Data Documentation
timeVal
timeval utils::Timeval::timeVal = {0, 0} private
Definition at line 99 of file Timeval.h.
{0, 0};
Referenced by getMs(), getMsd(), getTimespec(), normalize(), operator&(), operator&(), operator*(), operator*, operator+(), operator-(), operator-(), operator<(), operator<<, operator=(), operator=(), Timeval(), Timeval(), Timeval(), and Timeval().
The documentation for this class was generated from the following files:
utils/Timeval.h
utils/Timeval.cpp