SNode.C: apps::towercalculator::KeyboardReader Class Reference
apps::towercalculator::KeyboardReader Class Reference
#include <KeyboardReader.h>
Public Member Functions
KeyboardReader (const std::function< void(long)> &cb)
Protected Member Functions
void readEvent () override
void unobservedEvent () override
Protected Attributes
std::function< void(long)> callBack
Additional Inherited Members
Private Member Functions inherited from core::eventreceiver::ReadEventReceiver
ReadEventReceiver (const std::string &name, const utils::Timeval &timeout)
virtual void readTimeout ()
Private Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
int getRegisteredFd () const
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
Private Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
virtual ~EventReceiver ()=default
Static Private Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Detailed Description
Definition at line 55 of file KeyboardReader.h.
Constructor & Destructor Documentation
KeyboardReader()
apps::towercalculator::KeyboardReader::KeyboardReader (const std::function< void(long)> & cb) explicit
Definition at line 58 of file KeyboardReader.cpp.
        : core::eventreceiver::ReadEventReceiver("KeyboardReader", 0)
        , callBack(cb) {
        if (!enable(STDIN_FILENO)) {
            std::cout << "KeyboardReader not activated";
        }
    }
References callBack, and core::eventreceiver::ReadEventReceiver::ReadEventReceiver().
Referenced by main().
Member Function Documentation
readEvent()
void apps::towercalculator::KeyboardReader::readEvent () override protected virtual
Implements core::eventreceiver::ReadEventReceiver.
Definition at line 66 of file KeyboardReader.cpp.
{
        std::cout << "ReadEvent" << std::endl;
        /*
            long value;
            std::cin >> long;
        */
        char buffer[256];
        const ssize_t ret = read(STDIN_FILENO, buffer, 256);
        if (ret > 0) {
            buffer[ret] = 0;
            try {
                long value = 0;
                value = std::stol(buffer);
                std::cout << "Value = " << value << std::endl;
                callBack(value);
            } catch (std::invalid_argument& e) {
                std::cout << e.what() << ": "
                          << "no conversion possible: input = " << buffer << std::endl;
            }
        }
    }
References callBack.
unobservedEvent()
void apps::towercalculator::KeyboardReader::unobservedEvent () override protected virtual
Implements core::Observer.
Definition at line 93 of file KeyboardReader.cpp.
{
        //    delete this; // do not delete
    }
Member Data Documentation
callBack
std::function<void(long)> apps::towercalculator::KeyboardReader::callBack protected
Definition at line 63 of file KeyboardReader.h.
Referenced by KeyboardReader(), and readEvent().
The documentation for this class was generated from the following files:
apps/towercalculator/KeyboardReader.h
apps/towercalculator/KeyboardReader.cpp