SNode.C: express::Controller Class Reference
express::Controller Class Reference
#include <Controller.h>
Public Types
enum Flags { NONE = 0 , NEXT = 1 << 0 , NEXT_ROUTE = 1 << 1 , NEXT_ROUTER = 1 << 2 }
Public Member Functions
Controller (const std::shared_ptr< web::http::server::Request > &request, const std::shared_ptr< web::http::server::Response > &response)
Controller (const Controller &controller)
Controller & operator= (const Controller &controller) noexcept
void setRootRoute (RootRoute *rootRoute)
void setCurrentRoute (Route *currentRoute)
const std::shared_ptr< Request > & getRequest ()
const std::shared_ptr< Response > & getResponse ()
int getFlags () const
void next (const std::string &how) const
bool nextRouter ()
bool dispatchNext (const std::string &parentMountPath)
bool laxRouting ()
Private Attributes
std::shared_ptr< Request > request
std::shared_ptr< Response > response
RootRoute * rootRoute = nullptr
Route * lastRoute = nullptr
Route * currentRoute = nullptr
unsigned long lastTick = 0
int flags = NONE
Detailed Description
Definition at line 44 of file Controller.h.
Member Enumeration Documentation
Flags
enum express::Controller::Flags
Enumerator
NONE
NEXT
NEXT_ROUTE
NEXT_ROUTER
Definition at line 66 of file Controller.h.
{ NONE = 0, NEXT = 1 << 0, NEXT_ROUTE = 1 << 1, NEXT_ROUTER = 1 << 2 };
Constructor & Destructor Documentation
Controller() [1/2]
express::Controller::Controller (const std::shared_ptr< web::http::server::Request > & request, const std::shared_ptr< web::http::server::Response > & response)
Definition at line 33 of file Controller.cpp.
        : request(std::make_shared<Request>(request))
        , response(std::make_shared<Response>(response))
        , lastTick(core::EventLoop::getTickCounter()) {
    }
References Controller(), core::EventLoop::getTickCounter(), and lastTick.
Referenced by Controller(), and express::WebAppT< ServerT >::WebAppT().
Controller() [2/2]
express::Controller::Controller (const Controller & controller)
Definition at line 40 of file Controller.cpp.
        : request(controller.request)
        , response(controller.response)
        , rootRoute(controller.rootRoute)
        , lastRoute(controller.lastRoute)
        , currentRoute(controller.currentRoute)
        , lastTick(controller.lastTick)
        , flags(controller.flags) {
    }
References Controller(), currentRoute, flags, lastRoute, lastTick, and rootRoute.
Referenced by Controller().
Member Function Documentation
dispatchNext()
bool express::Controller::dispatchNext (const std::string & parentMountPath)
Definition at line 110 of file Controller.cpp.
{
        bool dispatched = false;
        if (((flags & Controller::NEXT) != 0)) {
            if (lastRoute == currentRoute) {
                flags &= ~Controller::NEXT;
                if ((flags & Controller::NEXT_ROUTE) != 0) {
                    flags &= ~Controller::NEXT_ROUTE;
                } else if ((flags & Controller::NEXT_ROUTER) == 0) {
                    dispatched = currentRoute->dispatchNext(*this, parentMountPath);
                }
            } else { // ? Optimization: Dispatch only parent route matched path
                dispatched = currentRoute->dispatchNext(*this, parentMountPath);
            }
        }
        return dispatched;
    }
References currentRoute, express::Route::dispatchNext(), flags, lastRoute, NEXT, NEXT_ROUTE, and NEXT_ROUTER.
Referenced by express::Route::dispatch().
getFlags()
int express::Controller::getFlags () const
Definition at line 80 of file Controller.cpp.
{
        return flags;
    }
References flags.
Referenced by express::dispatcher::ApplicationDispatcher::dispatch(), and express::dispatcher::MiddlewareDispatcher::dispatch().
getRequest()
const std::shared_ptr< Request > & express::Controller::getRequest ()
Definition at line 72 of file Controller.cpp.
{
        return request;
    }
getResponse()
const std::shared_ptr< Response > & express::Controller::getResponse ()
Definition at line 76 of file Controller.cpp.
{
        return response;
    }
laxRouting()
bool express::Controller::laxRouting ()
Definition at line 129 of file Controller.cpp.
{
        bool ret = false;
        if (!request->url.ends_with('/')) {
            request->url.append("/");
            ret = true;
        }
        return ret;
    }
Referenced by express::RootRoute::dispatch().
next()
void express::Controller::next (const std::string & how) const
Definition at line 84 of file Controller.cpp.
{
        flags = NEXT;
        if (how == "route") {
            flags |= NEXT_ROUTE;
        } else if (how == "router") {
            flags |= NEXT_ROUTER;
        }
        lastRoute = currentRoute;
        if (lastTick != core::EventLoop::getTickCounter()) { // If asynchronous next() start traversing of route-tree
            rootRoute->dispatch(*const_cast<express::Controller*>(this));
        }
    }
References currentRoute, express::RootRoute::dispatch(), flags, core::EventLoop::getTickCounter(), lastRoute, lastTick, NEXT, NEXT_ROUTE, NEXT_ROUTER, and rootRoute.
nextRouter()
bool express::Controller::nextRouter ()
Definition at line 100 of file Controller.cpp.
{
        const bool breakDispatching = lastRoute == currentRoute && (flags & Controller::NEXT_ROUTER) != 0;
        if (breakDispatching) {
            flags &= ~Controller::NEXT_ROUTER;
        }
        return breakDispatching;
    }
References currentRoute, flags, lastRoute, and NEXT_ROUTER.
operator=()
Controller & express::Controller::operator= (const Controller & controller) noexcept
Definition at line 50 of file Controller.cpp.
{
        if (this != &controller) {
            request = controller.request;
            response = controller.response;
            rootRoute = controller.rootRoute;
            lastRoute = controller.lastRoute;
            currentRoute = controller.currentRoute;
            lastTick = controller.lastTick;
            flags = controller.flags;
        }
        return *this;
    }
References currentRoute, flags, lastRoute, lastTick, and rootRoute.
setCurrentRoute()
void express::Controller::setCurrentRoute (Route * currentRoute)
Definition at line 68 of file Controller.cpp.
{
        this->currentRoute = currentRoute;
    }
References currentRoute.
Referenced by express::Route::dispatch().
setRootRoute()
void express::Controller::setRootRoute (RootRoute * rootRoute)
Definition at line 64 of file Controller.cpp.
{
        this->rootRoute = rootRoute;
    }
References rootRoute.
Referenced by express::RootRoute::dispatch().
Member Data Documentation
currentRoute
Route* express::Controller::currentRoute = nullptr private
Definition at line 75 of file Controller.h.
Referenced by Controller(), dispatchNext(), next(), nextRouter(), operator=(), and setCurrentRoute().
flags
int express::Controller::flags = NONE mutable private
Definition at line 79 of file Controller.h.
Referenced by Controller(), dispatchNext(), getFlags(), next(), nextRouter(), and operator=().
lastRoute
Route* express::Controller::lastRoute = nullptr mutable private
Definition at line 74 of file Controller.h.
Referenced by Controller(), dispatchNext(), next(), nextRouter(), and operator=().
lastTick
unsigned long express::Controller::lastTick = 0 private
Definition at line 77 of file Controller.h.
Referenced by Controller(), Controller(), next(), and operator=().
request
std::shared_ptr<Request> express::Controller::request private
Definition at line 69 of file Controller.h.
response
std::shared_ptr<Response> express::Controller::response private
Definition at line 70 of file Controller.h.
rootRoute
RootRoute* express::Controller::rootRoute = nullptr private
Definition at line 72 of file Controller.h.
Referenced by Controller(), next(), operator=(), and setRootRoute().
The documentation for this class was generated from the following files:
express/Controller.h
express/Controller.cpp