snode.c: core::select::EventMultiplexer Class Reference
core::select::EventMultiplexer Class Reference
#include <EventMultiplexer.h>
Public Member Functions
EventMultiplexer (const EventMultiplexer &)=delete
EventMultiplexer & operator= (const EventMultiplexer &)=delete
EventMultiplexer ()
~EventMultiplexer () override=default
Public Member Functions inherited from core::EventMultiplexer
EventMultiplexer (const EventMultiplexer &)=delete
EventMultiplexer & operator= (const EventMultiplexer &)=delete
DescriptorEventPublisher & getDescriptorEventPublisher (DISP_TYPE dispType)
TimerEventPublisher & getTimerEventPublisher ()
void span (core::Event *event)
void relax (core::Event *event)
void sigExit (int sigNum)
void stop ()
void clear ()
TickStatus tick (const utils::Timeval &tickTimeOut, const sigset_t &sigMask)
Private Member Functions
int monitorDescriptors (utils::Timeval &tickTimeOut, const sigset_t &sigMask) override
void spanActiveEvents (int activeDescriptorCount) override
Private Attributes
FdSet fdSets [3]
Additional Inherited Members
Public Types inherited from core::EventMultiplexer
enum DISP_TYPE { RD = 0 , WR = 1 , EX = 2 }
Protected Member Functions inherited from core::EventMultiplexer
EventMultiplexer (DescriptorEventPublisher *const readDescriptorEventPublisher, DescriptorEventPublisher *const writeDescriptorEventPublisher, DescriptorEventPublisher *const exceptionDescriptorEventPublisher)
int maxFd ()
Protected Attributes inherited from core::EventMultiplexer
std::array< DescriptorEventPublisher *, 3 > descriptorEventPublishers
Detailed Description
Definition at line 37 of file EventMultiplexer.h.
Constructor & Destructor Documentation
EventMultiplexer() [1/2]
core::select::EventMultiplexer::EventMultiplexer (const EventMultiplexer &) delete
EventMultiplexer() [2/2]
core::select::EventMultiplexer::EventMultiplexer ()
Definition at line 37 of file EventMultiplexer.cpp.
        : core::EventMultiplexer(new core::select::DescriptorEventPublisher("READ", fdSets[core::EventMultiplexer::DISP_TYPE::RD]),
                                 new core::select::DescriptorEventPublisher("WRITE", fdSets[core::EventMultiplexer::DISP_TYPE::WR]),
                                 new core::select::DescriptorEventPublisher("EXCEPT", fdSets[core::EventMultiplexer::DISP_TYPE::EX])) {
        LOG(TRACE) << "IO-Multiplexer: select";
    }
~EventMultiplexer()
core::select::EventMultiplexer::~EventMultiplexer () override virtual default
Reimplemented from core::EventMultiplexer.
Member Function Documentation
monitorDescriptors()
int core::select::EventMultiplexer::monitorDescriptors (utils::Timeval & tickTimeOut, const sigset_t & sigMask) override private virtual
Implements core::EventMultiplexer.
Definition at line 44 of file EventMultiplexer.cpp.
{
        timespec timeSpec = tickTimeOut.getTimespec();
        return core::system::pselect(maxFd() + 1,
                                     &fdSets[core::EventMultiplexer::DISP_TYPE::RD].get(),
                                     &fdSets[core::EventMultiplexer::DISP_TYPE::WR].get(),
                                     &fdSets[core::EventMultiplexer::DISP_TYPE::EX].get(),
                                     &timeSpec,
                                     &sigMask);
    }
References core::EventMultiplexer::EX, fdSets, utils::Timeval::getTimespec(), core::EventMultiplexer::maxFd(), core::system::pselect(), core::EventMultiplexer::RD, and core::EventMultiplexer::WR.
operator=()
EventMultiplexer & core::select::EventMultiplexer::operator= (const EventMultiplexer &) delete
spanActiveEvents()
void core::select::EventMultiplexer::spanActiveEvents (int activeDescriptorCount) override private virtual
Implements core::EventMultiplexer.
Definition at line 55 of file EventMultiplexer.cpp.
{
        if (activeDescriptorCount > 0) {
            for (core::DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
                descriptorEventPublisher->spanActiveEvents();
            }
        }
    }
References core::EventMultiplexer::descriptorEventPublishers.
Member Data Documentation
fdSets
FdSet core::select::EventMultiplexer::fdSets[3] private
Definition at line 50 of file EventMultiplexer.h.
Referenced by monitorDescriptors().
The documentation for this class was generated from the following files:
core/multiplexer/select/EventMultiplexer.h
core/multiplexer/select/EventMultiplexer.cpp