SNode.C: iot::mqtt::client::packets::Pingresp Class Reference
iot::mqtt::client::packets::Pingresp Class Reference
#include <Pingresp.h>
Public Member Functions
Pingresp (uint32_t remainingLength, uint8_t flags)
Public Member Functions inherited from iot::mqtt::packets::Pingresp
Pingresp ()
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type, const std::string &name)
ControlPacket (const ControlPacket &)=default
ControlPacket (ControlPacket &&)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
ControlPacket & operator= (ControlPacket &&)=default
std::vector< char > serialize () const
const std::string & getName () const
uint8_t getType () const
uint8_t getFlags () const
Public Member Functions inherited from iot::mqtt::client::ControlPacketDeserializer
~ControlPacketDeserializer () override
Public Member Functions inherited from iot::mqtt::ControlPacketDeserializer
ControlPacketDeserializer ()=default
ControlPacketDeserializer (uint32_t remainingLength, uint8_t flags, uint8_t mustFlags)
ControlPacketDeserializer & operator= (const ControlPacketDeserializer &)=default
std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
uint32_t getRemainingLength () const
bool isComplete () const
bool isError () const
std::size_t getConsumed () const
Private Member Functions
std::size_t deserializeVP (iot::mqtt::MqttContext *mqttContext) override
void deliverPacket (iot::mqtt::client::Mqtt *mqtt) override
Additional Inherited Members
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t flags = 0
Protected Attributes inherited from iot::mqtt::ControlPacketDeserializer
bool complete = false
bool error = false
uint32_t remainingLength = 0
std::size_t consumed = 0
Detailed Description
Definition at line 35 of file Pingresp.h.
Constructor & Destructor Documentation
Pingresp()
iot::mqtt::client::packets::Pingresp::Pingresp (uint32_t remainingLength, uint8_t flags)
Definition at line 30 of file Pingresp.cpp.
        : iot::mqtt::client::ControlPacketDeserializer(remainingLength, flags, MQTT_PINGRESP_FLAGS) {
        this->flags = flags;
    }
References iot::mqtt::ControlPacket::flags.
Referenced by iot::mqtt::client::Mqtt::createControlPacketDeserializer().
Member Function Documentation
deliverPacket()
void iot::mqtt::client::packets::Pingresp::deliverPacket (iot::mqtt::client::Mqtt * mqtt) override private virtual
Implements iot::mqtt::client::ControlPacketDeserializer.
Definition at line 43 of file Pingresp.cpp.
{
        mqtt->printVP(*this);
        mqtt->_onPingresp(*this);
    }
References iot::mqtt::client::Mqtt::_onPingresp(), and iot::mqtt::Mqtt::printVP().
deserializeVP()
std::size_t iot::mqtt::client::packets::Pingresp::deserializeVP (iot::mqtt::MqttContext * mqttContext) override private virtual
Implements iot::mqtt::ControlPacketDeserializer.
Definition at line 35 of file Pingresp.cpp.
{
        // no V-Header
        // no Payload
        complete = true;
        return 0;
    }
References iot::mqtt::ControlPacketDeserializer::complete.
The documentation for this class was generated from the following files:
iot/mqtt/client/packets/Pingresp.h
iot/mqtt/client/packets/Pingresp.cpp