SNode.C: iot::mqtt::client::packets::Pubrel Class Reference
iot::mqtt::client::packets::Pubrel Class Reference
#include <Pubrel.h>
Public Member Functions
Pubrel (uint32_t remainingLength, uint8_t flags)
Public Member Functions inherited from iot::mqtt::packets::Pubrel
Pubrel ()
Pubrel (uint16_t packetIdentifier)
uint16_t getPacketIdentifier () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type, const std::string &name)
ControlPacket (const ControlPacket &)=default
ControlPacket (ControlPacket &&)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
ControlPacket & operator= (ControlPacket &&)=default
std::vector< char > serialize () const
const std::string & getName () const
Public Member Functions inherited from iot::mqtt::client::ControlPacketDeserializer
~ControlPacketDeserializer () override
ControlPacketDeserializer ()=default
ControlPacketDeserializer (uint32_t remainingLength, uint8_t flags, uint8_t mustFlags)
Public Member Functions inherited from iot::mqtt::ControlPacketDeserializer
ControlPacketDeserializer ()=default
ControlPacketDeserializer (uint32_t remainingLength, uint8_t flags, uint8_t mustFlags)
ControlPacketDeserializer & operator= (const ControlPacketDeserializer &)=default
std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
uint32_t getRemainingLength () const
bool isComplete () const
bool isError () const
std::size_t getConsumed () const
Private Member Functions
std::size_t deserializeVP (iot::mqtt::MqttContext *mqttContext) override
void deliverPacket (iot::mqtt::client::Mqtt *mqtt) override
Additional Inherited Members
Protected Member Functions inherited from iot::mqtt::ControlPacket
uint8_t getType () const
uint8_t getFlags () const
Protected Attributes inherited from iot::mqtt::packets::Pubrel
iot::mqtt::types::UInt16 packetIdentifier
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t flags = 0
Protected Attributes inherited from iot::mqtt::ControlPacketDeserializer
bool complete = false
bool error = false
uint32_t remainingLength = 0
std::size_t consumed = 0
Detailed Description
Definition at line 57 of file Pubrel.h.
Constructor & Destructor Documentation
Pubrel()
iot::mqtt::client::packets::Pubrel::Pubrel (uint32_t remainingLength, uint8_t flags)
Definition at line 52 of file Pubrel.cpp.
        : iot::mqtt::client::ControlPacketDeserializer(remainingLength, flags, MQTT_PUBREL_FLAGS) {
        this->flags = flags;
    }
References iot::mqtt::ControlPacket::flags.
Referenced by iot::mqtt::client::Mqtt::createControlPacketDeserializer().
Member Function Documentation
deliverPacket()
void iot::mqtt::client::packets::Pubrel::deliverPacket (iot::mqtt::client::Mqtt * mqtt) override private virtual
Implements iot::mqtt::client::ControlPacketDeserializer.
Definition at line 67 of file Pubrel.cpp.
{
        mqtt->printVP(*this);
        mqtt->_onPubrel(*this);
    }
References iot::mqtt::Mqtt::_onPubrel(), and iot::mqtt::Mqtt::printVP().
deserializeVP()
std::size_t iot::mqtt::client::packets::Pubrel::deserializeVP (iot::mqtt::MqttContext * mqttContext) override private virtual
Implements iot::mqtt::ControlPacketDeserializer.
Definition at line 57 of file Pubrel.cpp.
{
        // V-Header
        const std::size_t consumed = packetIdentifier.deserialize(mqttContext);
        complete = packetIdentifier.isComplete();
        // no Payload
        return consumed;
    }
References iot::mqtt::ControlPacketDeserializer::complete, iot::mqtt::types::TypeBase< ValueTypeT >::deserialize(), iot::mqtt::types::TypeBase< ValueTypeT >::isComplete(), and iot::mqtt::packets::Pubrel::packetIdentifier.
The documentation for this class was generated from the following files:
iot/mqtt/client/packets/Pubrel.h
iot/mqtt/client/packets/Pubrel.cpp