SNode.C: iot::mqtt::SocketContext Class Reference
iot::mqtt::SocketContext Class Reference
#include <SocketContext.h>
Public Member Functions
SocketContext (core::socket::stream::SocketConnection *socketConnection, Mqtt *mqtt)
void sendToPeer (const char *chunk, std::size_t chunkLen) const final
void sendToPeer (const std::string &data) const
virtual void sendToPeer (const char *chunk, std::size_t chunkLen) const=0
bool streamToPeer (core::pipe::Source *source) const
void streamEof ()
std::size_t readFromPeer (char *chunk, std::size_t chunklen) const final
void setTimeout (const utils::Timeval &timeout) final
void shutdownRead ()
void shutdownWrite (bool forceClose=false)
SocketConnection * getSocketConnection () const
virtual void switchSocketContext (SocketContext *newSocketContext)
Protected Member Functions
void onWriteError (int errnum) override
void onReadError (int errnum) override
Private Types
using Super = core::socket::SocketContext
Private Member Functions
void onConnected () override
std::size_t onReceivedFromPeer () override
void onDisconnected () override
bool onSignal (int sig) override
core::socket::stream::SocketConnection * getSocketConnection () override
std::size_t recv (char *chunk, std::size_t chunklen) override
void send (const char *chunk, std::size_t chunklen) override
void end (bool fatal) override
void close () override
Private Attributes
core::socket::stream::SocketConnection * socketConnection
Mqtt * mqtt
Detailed Description
Definition at line 42 of file SocketContext.h.
Member Typedef Documentation
Super
using core::socket::stream::SocketContext::Super = core::socket::SocketContext private inherited
Definition at line 48 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext()
iot::mqtt::SocketContext::SocketContext (core::socket::stream::SocketConnection * socketConnection, Mqtt * mqtt) explicit
Definition at line 28 of file SocketContext.cpp.
        : core::socket::stream::SocketContext(socketConnection)
        , iot::mqtt::MqttContext(mqtt) {
    }
References iot::mqtt::MqttContext::MqttContext(), and core::socket::stream::SocketContext::SocketContext().
Member Function Documentation
close()
void iot::mqtt::SocketContext::close () override private virtual
Reimplemented from core::socket::stream::SocketContext.
Definition at line 65 of file SocketContext.cpp.
{
        core::socket::stream::SocketContext::close();
    }
References core::socket::stream::SocketContext::close().
end()
void iot::mqtt::SocketContext::end (bool fatal) override private virtual
Implements iot::mqtt::MqttContext.
Definition at line 61 of file SocketContext.cpp.
{
        core::socket::stream::SocketContext::shutdownWrite(fatal);
    }
References core::socket::stream::SocketContext::shutdownWrite().
getSocketConnection() [1/2]
SocketConnection * core::socket::stream::SocketContext::getSocketConnection () const inherited
Definition at line 38 of file SocketContext.cpp.
{
        return socketConnection;
    }
References core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::server::SocketContext::deliverRequest(), web::http::client::SocketContext::deliverResponse(), web::http::client::SocketContext::deliverResponseParseError(), getSocketConnection(), web::http::client::SocketContext::initiateRequest(), web::http::client::SocketContext::onConnected(), web::http::server::SocketContext::onConnected(), web::http::client::SocketContext::onDisconnected(), web::http::server::SocketContext::onDisconnected(), web::http::client::SocketContext::onSignal(), web::http::server::SocketContext::onSignal(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestDelivered(), web::http::client::SocketContext::requestPrepared(), web::http::server::SocketContext::requestStarted(), web::http::server::SocketContext::responseCompleted(), web::http::client::SocketContext::responseDelivered(), web::http::client::SocketContext::responseStarted(), web::http::server::SocketContext::responseStarted(), web::http::client::SocketContext::SocketContext(), web::http::server::Response::upgrade(), web::http::client::Request::upgrade(), and express::middleware::VerboseRequest::VerboseRequest().
getSocketConnection() [2/2]
core::socket::stream::SocketConnection * iot::mqtt::SocketContext::getSocketConnection () override private virtual
Implements iot::mqtt::MqttContext.
Definition at line 45 of file SocketContext.cpp.
{
        return core::socket::stream::SocketContext::getSocketConnection();
    }
References core::socket::stream::SocketContext::getSocketConnection().
onConnected()
void iot::mqtt::SocketContext::onConnected () override private virtual
Implements core::socket::stream::SocketContext.
Definition at line 33 of file SocketContext.cpp.
{
        iot::mqtt::MqttContext::onConnected();
    }
References iot::mqtt::MqttContext::onConnected().
onDisconnected()
void iot::mqtt::SocketContext::onDisconnected () override private virtual
Implements core::socket::stream::SocketContext.
Definition at line 37 of file SocketContext.cpp.
{
        iot::mqtt::MqttContext::onDisconnected();
    }
References iot::mqtt::MqttContext::onDisconnected().
onReadError()
void core::socket::stream::SocketContext::onReadError (int errnum) override protected virtual inherited
Implements core::socket::SocketContext.
Definition at line 78 of file SocketContext.cpp.
{
        shutdownWrite();
    }
References core::socket::stream::SocketContext::shutdownWrite().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReadError().
onReceivedFromPeer()
std::size_t iot::mqtt::SocketContext::onReceivedFromPeer () override private virtual
Implements core::socket::SocketContext.
Definition at line 49 of file SocketContext.cpp.
{
        return iot::mqtt::MqttContext::onReceivedFromPeer();
    }
References iot::mqtt::MqttContext::onReceivedFromPeer().
onSignal()
bool iot::mqtt::SocketContext::onSignal (int sig) override private virtual
Implements core::socket::SocketContext.
Definition at line 41 of file SocketContext.cpp.
{
        return iot::mqtt::MqttContext::onSignal(sig);
    }
References iot::mqtt::MqttContext::onSignal().
onWriteError()
void core::socket::stream::SocketContext::onWriteError (int errnum) override protected virtual inherited
Implements core::socket::SocketContext.
Reimplemented in web::http::client::SocketContext, and web::http::server::SocketContext.
Definition at line 74 of file SocketContext.cpp.
{
        shutdownRead();
    }
References core::socket::stream::SocketContext::shutdownRead().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onWriteError().
readFromPeer()
std::size_t core::socket::stream::SocketContext::readFromPeer (char * chunk, std::size_t chunklen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 54 of file SocketContext.cpp.
{
        return socketConnection->readFromPeer(chunk, chunklen);
    }
References core::socket::stream::SocketConnection::readFromPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::decoder::Fields::read(), web::http::decoder::HTTP10Response::read(), web::http::decoder::Identity::read(), web::http::decoder::Chunked::Chunk::read(), web::http::Parser::readStartLine(), and recv().
recv()
std::size_t iot::mqtt::SocketContext::recv (char * chunk, std::size_t chunklen) override private virtual
Implements iot::mqtt::MqttContext.
Definition at line 53 of file SocketContext.cpp.
{
        return core::socket::stream::SocketContext::readFromPeer(chunk, chunklen);
    }
References core::socket::stream::SocketContext::readFromPeer().
send()
void iot::mqtt::SocketContext::send (const char * chunk, std::size_t chunklen) override private virtual
Implements iot::mqtt::MqttContext.
Definition at line 57 of file SocketContext.cpp.
{
        core::socket::stream::SocketContext::sendToPeer(chunk, chunklen);
    }
References core::socket::stream::SocketContext::sendToPeer().
sendToPeer() [1/3]
void core::socket::stream::SocketContext::sendToPeer (const char * chunk, std::size_t chunkLen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 42 of file SocketContext.cpp.
{
        socketConnection->sendToPeer(chunk, chunkLen);
    }
References core::socket::stream::SocketConnection::sendToPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::Request::executeSendFragment(), send(), iot::mqtt_fast::SocketContext::send(), and web::http::server::Response::sendFragment().
sendToPeer() [2/3]
virtual void core::socket::SocketContext::sendToPeer (const char * chunk, std::size_t chunkLen) const virtual inherited
Implements core::socket::SocketContext.
sendToPeer() [3/3]
void core::socket::SocketContext::sendToPeer (const std::string & data) const inherited
Definition at line 53 of file SocketContext.cpp.
{
        sendToPeer(data.data(), data.length());
    }
setTimeout()
void core::socket::stream::SocketContext::setTimeout (const utils::Timeval & timeout) final virtual inherited
Implements core::socket::SocketContext.
Definition at line 58 of file SocketContext.cpp.
{
        socketConnection->setTimeout(timeout);
    }
References core::socket::stream::SocketConnection::setTimeout(), and core::socket::stream::SocketContext::socketConnection.
shutdownRead()
void core::socket::stream::SocketContext::shutdownRead () inherited
Definition at line 66 of file SocketContext.cpp.
{
        socketConnection->shutdownRead();
    }
References core::socket::stream::SocketConnection::shutdownRead(), and core::socket::stream::SocketContext::socketConnection.
Referenced by core::socket::stream::SocketContext::onWriteError().
shutdownWrite()
void core::socket::stream::SocketContext::shutdownWrite (bool forceClose = false) inherited
Definition at line 70 of file SocketContext.cpp.
{
        socketConnection->shutdownWrite(forceClose);
    }
References core::socket::stream::SocketConnection::shutdownWrite(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::SocketContext::deliverResponseParseError(), end(), core::socket::stream::SocketContext::onReadError(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestDelivered(), web::http::server::SocketContext::responseCompleted(), web::http::client::SocketContext::responseDelivered(), and web::http::client::SocketContext::responseStarted().
streamEof()
void core::socket::stream::SocketContext::streamEof () inherited
Definition at line 50 of file SocketContext.cpp.
{
        socketConnection->streamEof();
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::streamEof().
Referenced by web::http::client::Request::onSourceEof(), web::http::server::Response::onSourceEof(), web::http::client::Request::onSourceError(), web::http::server::Response::onSourceError(), web::http::client::Request::~Request(), and web::http::server::Response::~Response().
streamToPeer()
bool core::socket::stream::SocketContext::streamToPeer (core::pipe::Source * source) const inherited
Definition at line 46 of file SocketContext.cpp.
{
        return socketConnection->streamToPeer(source);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::streamToPeer().
Referenced by web::http::client::Request::onSourceConnect(), and web::http::server::Response::onSourceConnect().
switchSocketContext()
void core::socket::stream::SocketContext::switchSocketContext (SocketContext * newSocketContext) virtual inherited
Definition at line 34 of file SocketContext.cpp.
{
        socketConnection->switchSocketContext(newSocketContext);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::switchSocketContext().
Referenced by web::http::server::Response::sendCompleted(), and web::http::client::Request::upgrade().
Member Data Documentation
mqtt
Mqtt* iot::mqtt::MqttContext::mqtt protected inherited
Definition at line 62 of file MqttContext.h.
Referenced by iot::mqtt::MqttContext::MqttContext(), iot::mqtt::MqttContext::onConnected(), iot::mqtt::MqttContext::onDisconnected(), iot::mqtt::MqttContext::onReceivedFromPeer(), iot::mqtt::MqttContext::onSignal(), and iot::mqtt::MqttContext::~MqttContext().
socketConnection
core::socket::stream::SocketConnection* core::socket::stream::SocketContext::socketConnection private inherited
Definition at line 78 of file SocketContext.h.
Referenced by core::socket::stream::SocketContext::close(), core::socket::stream::SocketContext::getSocketConnection(), core::socket::stream::SocketContext::readFromPeer(), core::socket::stream::SocketContext::sendToPeer(), core::socket::stream::SocketContext::setTimeout(), core::socket::stream::SocketContext::shutdownRead(), core::socket::stream::SocketContext::shutdownWrite(), core::socket::stream::SocketContext::SocketContext(), core::socket::stream::SocketContext::streamEof(), core::socket::stream::SocketContext::streamToPeer(), and core::socket::stream::SocketContext::switchSocketContext().
The documentation for this class was generated from the following files:
iot/mqtt/SocketContext.h
iot/mqtt/SocketContext.cpp