SNode.C: net::un::dgram::Socket Class Reference
net::un::dgram::Socket Class Reference
#include <Socket.h>
Public Member Functions
Socket ()
~Socket () override
ssize_t sendFd (SocketAddress &&destAddress, int sendfd)
ssize_t sendFd (SocketAddress &destAddress, int sendfd)
ssize_t recvFd (int *recvfd)
Public Member Functions inherited from net::un::phy::PhysicalSocket< net::phy::dgram::PeerSocket >
PhysicalSocket (int type, int protocol)
PhysicalSocket (PhysicalSocket &&physicalSocket) noexcept
PhysicalSocket & operator= (PhysicalSocket &&physicalSocket) noexcept
~PhysicalSocket () override
int bind (SocketAddress &bindAddress)
Public Member Functions inherited from net::phy::PhysicalSocket< net::un::SocketAddress >
PhysicalSocket ()=delete
PhysicalSocket (PhysicalSocket &)=delete
PhysicalSocket (const PhysicalSocket &)=delete
PhysicalSocket (int fd, const SocketAddress &bindAddress)
PhysicalSocket & operator= (PhysicalSocket &)=delete
PhysicalSocket & operator= (const PhysicalSocket &)=delete
int open (const std::map< int, const PhysicalSocketOption > &socketOptions, Flags flags)
int bind (SocketAddress &bindAddress)
bool isValid () const
int getSockError (int &cErrno) const
int getSockName (typename SocketAddress::SockAddr &localSockAddr, typename SocketAddress::SockLen &localSockAddrLen)
int getPeerName (typename SocketAddress::SockAddr &remoteSockAddr, typename SocketAddress::SockLen &remoteSockAddrLen)
SocketAddress getBindAddress () const
Public Member Functions inherited from core::Descriptor
Descriptor ()=delete
Descriptor (const Descriptor &d)=delete
Descriptor & operator= (int fd)
Descriptor & operator= (const Descriptor &descriptor)=delete
Descriptor & operator= (Descriptor &&descriptor) noexcept
int getFd () const
Private Types
using Super = net::un::phy::PhysicalSocket<net::phy::dgram::PeerSocket>
Additional Inherited Members
Public Types inherited from net::un::phy::PhysicalSocket< net::phy::dgram::PeerSocket >
using Super
Public Types inherited from net::phy::dgram::PeerSocket< net::un::SocketAddress >
using SocketAddress
Public Types inherited from net::phy::PhysicalSocket< net::un::SocketAddress >
enum Flags
Protected Types inherited from net::phy::dgram::PeerSocket< net::un::SocketAddress >
using Super
Protected Types inherited from net::phy::PhysicalSocket< net::un::SocketAddress >
using SocketAddress
Protected Member Functions inherited from net::phy::PhysicalSocket< net::un::SocketAddress >
PhysicalSocket (int domain, int type, int protocol)
PhysicalSocket (PhysicalSocket &&physicalSocket) noexcept=default
PhysicalSocket & operator= (PhysicalSocket &&) noexcept=default
~PhysicalSocket () override
Protected Member Functions inherited from core::Descriptor
Descriptor (int fd)
Descriptor (Descriptor &&descriptor) noexcept
virtual ~Descriptor ()
Protected Attributes inherited from net::phy::PhysicalSocket< net::un::SocketAddress >
SocketAddress bindAddress
int domain
int type
int protocol
Detailed Description
Definition at line 34 of file Socket.h.
Member Typedef Documentation
Super
using net::un::dgram::Socket::Super = net::un::phy::PhysicalSocket<net::phy::dgram::PeerSocket> private
Definition at line 36 of file Socket.h.
Constructor & Destructor Documentation
Socket()
net::un::dgram::Socket::Socket ()
Definition at line 34 of file Socket.cpp.
        : Super(SOCK_DGRAM, 0) {
    }
References Socket().
Referenced by Socket().
~Socket()
net::un::dgram::Socket::~Socket () override
Definition at line 38 of file Socket.cpp.
                    {
    }
Member Function Documentation
recvFd()
ssize_t net::un::dgram::Socket::recvFd (int * recvfd)
Definition at line 75 of file Socket.cpp.
{
        union {
            struct cmsghdr cm;
            char control[CMSG_SPACE(sizeof(int))] = {};
        } control_un;
        msghdr msg{};
        msg.msg_control = control_un.control;
        msg.msg_controllen = sizeof(control_un.control);
        msg.msg_name = nullptr;
        msg.msg_namelen = 0;
        iovec iov[1];
        msg.msg_iov = iov;
        msg.msg_iovlen = 1;
        char ptr = 0;
        msg.msg_iov[0].iov_base = &ptr;
        msg.msg_iov[0].iov_len = 1;
        ssize_t n = 0;
        if ((n = recvmsg(core::Descriptor::getFd(), &msg, 0)) > 0) {
            cmsghdr* cmptr = nullptr;
            if ((cmptr = CMSG_FIRSTHDR(&msg)) != nullptr && cmptr->cmsg_len == CMSG_LEN(sizeof(int))) {
                if (cmptr->cmsg_level != SOL_SOCKET || cmptr->cmsg_type != SCM_RIGHTS) {
                    errno = EBADE;
                    *recvfd = -1;
                    n = -1;
                } else {
                    *recvfd = *reinterpret_cast<int*>(CMSG_DATA(cmptr));
                }
            } else {
                errno = ENOMSG;
                *recvfd = -1;
                n = -1;
            }
        }
        return n;
    }
sendFd() [1/2]
ssize_t net::un::dgram::Socket::sendFd (SocketAddress && destAddress, int sendfd)
Definition at line 41 of file Socket.cpp.
{
        return sendFd(destAddress, sendfd);
    }
References sendFd().
sendFd() [2/2]
ssize_t net::un::dgram::Socket::sendFd (SocketAddress & destAddress, int sendfd)
Definition at line 45 of file Socket.cpp.
{
        union {
            struct cmsghdr cm;
            char control[CMSG_SPACE(sizeof(int))] = {};
        } control_un;
        msghdr msg{};
        msg.msg_name = const_cast<sockaddr*>(&destAddress.getSockAddr());
        msg.msg_namelen = destAddress.getSockAddrLen();
        msg.msg_control = control_un.control;
        msg.msg_controllen = sizeof(control_un.control);
        iovec iov[1];
        msg.msg_iov = iov;
        msg.msg_iovlen = 1;
        char ptr = 0;
        msg.msg_iov[0].iov_base = &ptr;
        msg.msg_iov[0].iov_len = 1;
        cmsghdr* cmptr = CMSG_FIRSTHDR(&msg);
        cmptr->cmsg_level = SOL_SOCKET;
        cmptr->cmsg_type = SCM_RIGHTS;
        *reinterpret_cast<int*>(CMSG_DATA(cmptr)) = sendfd;
        cmptr->cmsg_len = CMSG_LEN(sizeof(int));
        return sendmsg(core::Descriptor::getFd(), &msg, 0);
    }
Referenced by sendFd().
The documentation for this class was generated from the following files:
net/un/dgram/Socket.h
net/un/dgram/Socket.cpp