SNode.C: core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args > Class Template Reference
core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args > Class Template Reference
#include <SocketClient.h>
Classes
struct Context
Public Types
using SocketConnection = typename SocketConnector::SocketConnection
using SocketAddress = typename SocketConnector::SocketAddress
using Config = typename SocketConnector::Config
Public Types inherited from core::socket::Socket< SocketConnectorT::Config >
using Config
Public Member Functions
SocketClient (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, Args &&... args)
SocketClient (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, Args &&... args)
SocketClient (const std::string &name, Args &&... args)
SocketClient (Args &&... args)
const SocketClient & connect (const std::function< void(const SocketAddress &, core::socket::State)> &onStatus) const
const SocketClient & connect (const SocketAddress &remoteAddress, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus) const
const SocketClient & connect (const SocketAddress &remoteAddress, const SocketAddress &localAddress, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus) const
std::function< void(SocketConnection *)> & getOnConnect ()
const SocketClient & setOnConnect (const std::function< void(SocketConnection *)> &onConnect, bool initialize=false) const
std::function< void(SocketConnection *)> & getOnConnected () const
const SocketClient & setOnConnected (const std::function< void(SocketConnection *)> &onConnected, bool initialize=false) const
std::function< void(SocketConnection *)> & getOnDisconnect () const
const SocketClient & setOnDisconnect (const std::function< void(SocketConnection *)> &onDisconnect, bool initialize=false) const
std::function< void(const std::shared_ptr< AutoConnectControl > &)> & getOnAutoConnectControl ()
const SocketClient & setOnAutoConnectControl (const std::function< void(const std::shared_ptr< AutoConnectControl > &)> &onAutoConnectControl, bool initialize=false) const
std::function< void(core::eventreceiver::ConnectEventReceiver *)> & getOnInitState () const
const SocketClient & setOnInitState (const std::function< void(core::eventreceiver::ConnectEventReceiver *)> &onInitState, bool initialize=false) const
std::shared_ptr< SocketContextFactory > getSocketContextFactory () const
Public Member Functions inherited from core::socket::Socket< SocketConnectorT::Config >
Socket (const std::string &name)
virtual ~Socket ()
Config & getConfig () const
Private Types
using SocketConnector = SocketConnectorT
using SocketContextFactory = SocketContextFactoryT
using Super = core::socket::Socket<typename SocketConnector::Config>
Private Member Functions
SocketClient (const std::shared_ptr< Config > &config, const std::shared_ptr< SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect)
SocketClient (const std::shared_ptr< Config > &config, const std::shared_ptr< Context > &sharedContext)
const SocketClient & realConnect (const std::function< void(const SocketAddress &, core::socket::State)> &onStatus, unsigned int tries, double retryTimeoutScale) const
Private Attributes
std::shared_ptr< Context > sharedContext
Additional Inherited Members
Protected Member Functions inherited from core::socket::Socket< SocketConnectorT::Config >
Socket & operator= (const Socket &)=default
Protected Attributes inherited from core::socket::Socket< SocketConnectorT::Config >
const std::shared_ptr< Config > config
Detailed Description
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args>
requires std::is_base_of_v<core::eventreceiver::ConnectEventReceiver, SocketConnectorT> && std::is_base_of_v<core::socket::stream::SocketContextFactory, SocketContextFactoryT>
class core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >
Sequence diagram showing how a connect to a peer is performed.
Definition at line 74 of file SocketClient.h.
Member Typedef Documentation
Config
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> using core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::Config = typename SocketConnector::Config
Definition at line 84 of file SocketClient.h.
SocketAddress
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> using core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::SocketAddress = typename SocketConnector::SocketAddress
Definition at line 83 of file SocketClient.h.
SocketConnection
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> using core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::SocketConnection = typename SocketConnector::SocketConnection
Definition at line 82 of file SocketClient.h.
SocketConnector
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> using core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::SocketConnector = SocketConnectorT private
Definition at line 76 of file SocketClient.h.
SocketContextFactory
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> using core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::SocketContextFactory = SocketContextFactoryT private
Definition at line 77 of file SocketClient.h.
Super
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> using core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::Super = core::socket::Socket<typename SocketConnector::Config> private
Definition at line 79 of file SocketClient.h.
Constructor & Destructor Documentation
SocketClient() [1/6]
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::SocketClient (const std::shared_ptr< Config > & config, const std::shared_ptr< SocketContextFactory > & socketContextFactory, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect) inline private
Definition at line 113 of file SocketClient.h.
            : Super(config)
            , sharedContext(std::make_shared<Context>(socketContextFactory, onConnect, onConnected, onDisconnect)) {
        }
SocketClient() [2/6]
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::SocketClient (const std::shared_ptr< Config > & config, const std::shared_ptr< Context > & sharedContext) inline private
Definition at line 122 of file SocketClient.h.
            : Super(config)
            , sharedContext(sharedContext) {
        }
SocketClient() [3/6]
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::SocketClient (const std::string & name, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, Args &&... args) inline
Definition at line 128 of file SocketClient.h.
            : Super(name)
            , sharedContext(std::make_shared<Context>(
                  std::make_shared<SocketContextFactory>(std::forward<Args>(args)...),
                  [onConnect](SocketConnection* socketConnection) { // onConnect
                      LOG(DEBUG) << socketConnection->getConnectionName() << ": OnConnect";
                      LOG(DEBUG) << "  Local: " << socketConnection->getLocalAddress().toString();
                      LOG(DEBUG) << "   Peer: " << socketConnection->getRemoteAddress().toString();
                      if (onConnect) {
                          onConnect(socketConnection);
                      }
                  },
                  [onConnected](SocketConnection* socketConnection) { // onConnected
                      LOG(DEBUG) << socketConnection->getConnectionName() << ": OnConnected";
                      LOG(DEBUG) << "  Local: " << socketConnection->getLocalAddress().toString();
                      LOG(DEBUG) << "   Peer: " << socketConnection->getRemoteAddress().toString();
                      if (onConnected) {
                          onConnected(socketConnection);
                      }
                  },
                  [onDisconnect](SocketConnection* socketConnection) { // onDisconnect
                      LOG(DEBUG) << socketConnection->getConnectionName() << ": OnDisconnect";
                      LOG(DEBUG) << "            Local: " << socketConnection->getLocalAddress().toString();
                      LOG(DEBUG) << "             Peer: " << socketConnection->getRemoteAddress().toString();
                      LOG(DEBUG) << "     Online Since: " << socketConnection->getOnlineSince();
                      LOG(DEBUG) << "  Online Duration: " << socketConnection->getOnlineDuration();
                      LOG(DEBUG) << "     Total Queued: " << socketConnection->getTotalQueued();
                      LOG(DEBUG) << "       Total Sent: " << socketConnection->getTotalSent();
                      LOG(DEBUG) << "      Write Delta: " << socketConnection->getTotalQueued() - socketConnection->getTotalSent();
                      LOG(DEBUG) << "       Total Read: " << socketConnection->getTotalRead();
                      LOG(DEBUG) << "  Total Processed: " << socketConnection->getTotalProcessed();
                      LOG(DEBUG) << "       Read Delta: " << socketConnection->getTotalRead() - socketConnection->getTotalProcessed();
                      if (onDisconnect) {
                          onDisconnect(socketConnection);
                      }
                  })) {
        }
SocketClient() [4/6]
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::SocketClient (const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, Args &&... args) inline
Definition at line 178 of file SocketClient.h.
            : SocketClient("", onConnect, onConnected, onDisconnect, std::forward<Args>(args)...) {
        }
SocketClient() [5/6]
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::SocketClient (const std::string & name, Args &&... args) inline
Definition at line 185 of file SocketClient.h.
            : SocketClient(name, {}, {}, {}, std::forward<Args>(args)...) {
        }
SocketClient() [6/6]
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::SocketClient (Args &&... args) inline explicit
Definition at line 189 of file SocketClient.h.
            : SocketClient("", std::forward<Args>(args)...) {
        }
Member Function Documentation
connect() [1/3]
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> const SocketClient & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::connect (const SocketAddress & remoteAddress, const SocketAddress & localAddress, const std::function< void(const SocketAddress &, core::socket::State)> & onStatus) const inline
Definition at line 294 of file SocketClient.h.
{
            Super::config->Local::setSocketAddress(localAddress);
            return connect(remoteAddress, onStatus);
        }
connect() [2/3]
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> const SocketClient & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::connect (const SocketAddress & remoteAddress, const std::function< void(const SocketAddress &, core::socket::State)> & onStatus) const inline
Definition at line 287 of file SocketClient.h.
{
            Super::config->Remote::setSocketAddress(remoteAddress);
            return connect(onStatus);
        }
Referenced by tls::getClient(), legacy::getLegacyClient(), and main().
connect() [3/3]
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> const SocketClient & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::connect (const std::function< void(const SocketAddress &, core::socket::State)> & onStatus) const inline
Definition at line 283 of file SocketClient.h.
{
            return realConnect(onStatus, 0, 1);
        }
Referenced by main().
getOnAutoConnectControl()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> std::function< void(const std::shared_ptr< AutoConnectControl > &)> & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::getOnAutoConnectControl () inline
Definition at line 345 of file SocketClient.h.
{
            return sharedContext->onAutoConnectControl;
        }
getOnConnect()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> std::function< void(SocketConnection *)> & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::getOnConnect () inline
Definition at line 302 of file SocketClient.h.
{
            return sharedContext->onConnect;
        }
getOnConnected()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> std::function< void(SocketConnection *)> & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::getOnConnected () const inline
Definition at line 316 of file SocketClient.h.
{
            return sharedContext->onConnected;
        }
getOnDisconnect()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> std::function< void(SocketConnection *)> & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::getOnDisconnect () const inline
Definition at line 330 of file SocketClient.h.
{
            return sharedContext->onDisconnect;
        }
getOnInitState()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> std::function< void(core::eventreceiver::ConnectEventReceiver *)> & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::getOnInitState () const inline
Definition at line 368 of file SocketClient.h.
{
            return sharedContext->onInitState;
        }
getSocketContextFactory()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> std::shared_ptr< SocketContextFactory > core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::getSocketContextFactory () const inline
Definition at line 384 of file SocketClient.h.
{
            return sharedContext->socketContextFactory;
        }
realConnect()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> const SocketClient & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::realConnect (const std::function< void(const SocketAddress &, core::socket::State)> & onStatus, unsigned int tries, double retryTimeoutScale) const inline private
Definition at line 194 of file SocketClient.h.
{
            LOG(DEBUG) << this->config->getInstanceName() << ": Initiating connect";
            core::EventReceiver::atNextTick(
                [config = this->config, sharedContext = this->sharedContext, onStatus, tries, retryTimeoutScale] {
                    if (core::SNodeC::state() == core::State::RUNNING || core::SNodeC::state() == core::State::INITIALIZED) {
                        auto autoConnectControl = sharedContext->autoConnectControl;
                        if (!autoConnectControl) {
                            autoConnectControl = std::make_shared<AutoConnectControl>();
                            sharedContext->autoConnectControl = autoConnectControl;
                            if (sharedContext->onAutoConnectControl) {
                                sharedContext->onAutoConnectControl(autoConnectControl);
                            }
                        }
                        new SocketConnector(
                            sharedContext->socketContextFactory,
                            sharedContext->onConnect,
                            sharedContext->onConnected,
                            [config, sharedContext, autoConnectControl, onDisconnect = sharedContext->onDisconnect, onStatus](
                                SocketConnection* socketConnection) {
                                onDisconnect(socketConnection);
                                if (config->getReconnect() && autoConnectControl->isReconnectEnabled() &&
                                    core::eventLoopState() == core::State::RUNNING) {
                                    double relativeReconnectTimeout = config->getReconnectTime();
                                    LOG(INFO) << config->getInstanceName() << ": Reconnect in " << relativeReconnectTimeout << " seconds";
                                    autoConnectControl->armReconnectTimer(
                                        relativeReconnectTimeout, [config, sharedContext, autoConnectControl, /*generation,*/ onStatus]() {
                                            if (!autoConnectControl->isReconnectEnabled()) {
                                                return;
                                            }
                                            if (config->getReconnect()) {
                                                SocketClient(config, sharedContext).realConnect(onStatus, 0, config->getRetryBase());
                                            } else {
                                                LOG(INFO) << config->getInstanceName() << ": Reconnect disabled during wait";
                                            }
                                        });
                                }
                            },
                            sharedContext->onInitState,
                            [config, sharedContext, autoConnectControl, onStatus, tries, retryTimeoutScale](
                                const SocketAddress& socketAddress, core::socket::State state) {
                                const bool retryFlag = (state & core::socket::State::NO_RETRY) == 0;
                                state &= ~core::socket::State::NO_RETRY;
                                onStatus(socketAddress, state);
                                if (retryFlag && config->getRetry() // Shall we potentially retry? In case are the ...
                                    && autoConnectControl->isRetryEnabled() &&
                                    (config->getRetryTries() == 0 ||
                                     tries < config->getRetryTries()) // ... limits not reached and has an ...
                                    && (state == core::socket::State::ERROR ||
                                        (state == core::socket::State::FATAL && config->getRetryOnFatal()))) { // error occurred?
                                    double relativeRetryTimeout =
                                        config->getRetryLimit() > 0
                                            ? std::min<double>(config->getRetryTimeout() * retryTimeoutScale, config->getRetryLimit())
                                            : config->getRetryTimeout() * retryTimeoutScale;
                                    relativeRetryTimeout -= utils::Random::getInRange(-config->getRetryJitter(), config->getRetryJitter()) *
                                                            relativeRetryTimeout / 100.;
                                    LOG(INFO) << config->getInstanceName() << ": Retry connect in " << relativeRetryTimeout << " seconds";
                                    autoConnectControl->armRetryTimer(
                                        relativeRetryTimeout,
                                        [config, sharedContext, autoConnectControl, /*generation,*/ onStatus, tries, retryTimeoutScale]() {
                                            if (!autoConnectControl->isRetryEnabled()) {
                                                return;
                                            }
                                            if (config->getRetry()) {
                                                SocketClient(config, sharedContext)
                                                    .realConnect(onStatus, tries + 1, retryTimeoutScale * config->getRetryBase());
                                            } else {
                                                LOG(INFO) << config->getInstanceName() << ": Retry connect disabled during wait";
                                            }
                                        });
                                }
                            },
                            config);
                    }
                });
            return *this;
        }
Referenced by core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::connect(), and core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::realConnect().
setOnAutoConnectControl()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> const SocketClient & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::setOnAutoConnectControl (const std::function< void(const std::shared_ptr< AutoConnectControl > &)> & onAutoConnectControl, bool initialize = false) const inline
Definition at line 350 of file SocketClient.h.
{
            sharedContext->onAutoConnectControl = initialize ? onAutoConnectControl
                                                             : [oldOnAutoConnectControl = sharedContext->onAutoConnectControl,
                                                                onAutoConnectControl](const std::shared_ptr<AutoConnectControl>& control) {
                                                                   oldOnAutoConnectControl(control);
                                                                   onAutoConnectControl(control);
                                                               };
            if (sharedContext->autoConnectControl && onAutoConnectControl) {
                core::EventReceiver::atNextTick([sharedContext = this->sharedContext, onAutoConnectControl] {
                    onAutoConnectControl(sharedContext->autoConnectControl);
                });
            }
            return *this;
        }
setOnConnect()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> const SocketClient & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::setOnConnect (const std::function< void(SocketConnection *)> & onConnect, bool initialize = false) const inline
Definition at line 306 of file SocketClient.h.
{
            sharedContext->onConnect =
                initialize ? onConnect : [oldOnConnect = sharedContext->onConnect, onConnect](SocketConnection* socketConnection) {
                    oldOnConnect(socketConnection);
                    onConnect(socketConnection);
                };
            return *this;
        }
setOnConnected()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> const SocketClient & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::setOnConnected (const std::function< void(SocketConnection *)> & onConnected, bool initialize = false) const inline
Definition at line 320 of file SocketClient.h.
{
            sharedContext->onConnected =
                initialize ? onConnected : [oldOnConnected = sharedContext->onConnected, onConnected](SocketConnection* socketConnection) {
                    oldOnConnected(socketConnection);
                    onConnected(socketConnection);
                };
            return *this;
        }
setOnDisconnect()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> const SocketClient & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::setOnDisconnect (const std::function< void(SocketConnection *)> & onDisconnect, bool initialize = false) const inline
Definition at line 334 of file SocketClient.h.
{
            sharedContext->onDisconnect =
                initialize ? onDisconnect
                           : [oldOnDisconnect = sharedContext->onDisconnect, onDisconnect](SocketConnection* socketConnection) {
                                 oldOnDisconnect(socketConnection);
                                 onDisconnect(socketConnection);
                             };
            return *this;
        }
setOnInitState()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> const SocketClient & core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::setOnInitState (const std::function< void(core::eventreceiver::ConnectEventReceiver *)> & onInitState, bool initialize = false) const inline
Definition at line 372 of file SocketClient.h.
{
            sharedContext->onInitState = initialize ? onInitState
                                                    : [oldOnInitState = sharedContext->onInitState,
                                                       onInitState](core::eventreceiver::ConnectEventReceiver* descriptorEventReceiver) {
                                                          oldOnInitState(descriptorEventReceiver);
                                                          onInitState(descriptorEventReceiver);
                                                      };
            return *this;
        }
Referenced by main().
Member Data Documentation
sharedContext
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> std::shared_ptr<Context> core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::sharedContext private
Definition at line 389 of file SocketClient.h.
Referenced by core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::getOnAutoConnectControl(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::getOnConnect(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::getOnConnected(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::getOnDisconnect(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::getOnInitState(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::getSocketContextFactory(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::setOnAutoConnectControl(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::setOnConnect(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::setOnConnected(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::setOnDisconnect(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::setOnInitState(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::SocketClient(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::SocketClient(), and core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::SocketClient().
The documentation for this class was generated from the following file:
core/socket/stream/SocketClient.h