SNode.C: ConfigDb Class Reference
ConfigDb Class Reference
Public Member Functions
ConfigDb (SubCommand *parent)
ConfigDb & setHost (const std::string &host)
std::string getHost ()
ConfigDb (SubCommand *parent)
ConfigDb & setHost (const std::string &host)
std::string getHost ()
Public Member Functions inherited from utils::SubCommand
SubCommand (const SubCommand &)=delete
SubCommand (SubCommand &&)=delete
SubCommand & operator= (const SubCommand &)=delete
SubCommand & operator= (SubCommand &&)=delete
virtual ~SubCommand ()
std::string getName () const
std::string version () const
void parse (int argc, char *argv[])
CLI::Option * setConfig (const std::string &defaultConfigFile) const
CLI::Option * setLogFile (const std::string &defaultLogFile) const
CLI::Option * setVersionFlag (const std::string &version) const
bool hasParent () const
SubCommand * getParent ()
SubCommand * allowExtras (bool allow=true)
SubCommand * required (bool required=true, bool force=true)
SubCommand * required (SubCommand *subCommand, bool required=true)
SubCommand * required (CLI::Option *option, bool required=true)
SubCommand * needs (SubCommand *subCommand, bool needs=true)
SubCommand * disabled (SubCommand *subCommand, bool disabled=true)
SubCommand * setRequireCallback (const std::function< void(void)> &callback)
SubCommand * finalCallback (const std::function< void()> &finalCallback)
std::string configToStr () const
std::string help (const CLI::App *helpApp, const CLI::AppFormatMode &mode) const
template<typename NewSubCommand, typename... Args>
NewSubCommand * newSubCommand (Args &&... args)
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand ()
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand () const
CLI::Option * getOption (const std::string &name) const
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator) const
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Static Public Attributes
static constexpr std::string_view NAME {"db"}
static constexpr std::string_view DESCRIPTION {"Database connection"}
Static Public Attributes inherited from utils::SubCommand
static std::shared_ptr< CLI::Formatter > sectionFormatter = makeSectionFormatter()
Private Attributes
CLI::Option * hostOpt
Additional Inherited Members
Static Public Member Functions inherited from utils::SubCommand
static CLI::App * getHelpTriggerApp ()
static CLI::App * getShowConfigTriggerApp ()
static CLI::App * getCommandlineTriggerApp ()
Protected Member Functions inherited from utils::SubCommand
SubCommand (SubCommand *parent, std::shared_ptr< utils::AppWithPtr > appWithPtr, const std::string &group, bool final)
template<typename ConcretSubCommand>
SubCommand (SubCommand *parent, ConcretSubCommand *concretSubCommand, const std::string &group, bool final=true)
SubCommand * description (const std::string &description)
SubCommand * footer (const std::string &footer)
template<typename ValueTypeT>
CLI::Option * setDefaultValue (CLI::Option *option, const ValueTypeT &value, bool clear=true) const
CLI::Option * setConfigurable (CLI::Option *option, bool configurable) const
Static Protected Attributes inherited from utils::SubCommand
static std::map< std::string, std::string > aliases
static CLI::App * helpTriggerApp = nullptr
static CLI::App * showConfigTriggerApp = nullptr
static CLI::App * commandlineTriggerApp = nullptr
Detailed Description
Definition at line 62 of file testmariadb.cpp.
Constructor & Destructor Documentation
ConfigDb() [1/2]
ConfigDb::ConfigDb (SubCommand * parent) inline
Definition at line 67 of file testmariadb.cpp.
        : SubCommand(parent, this, "Database") {
        hostOpt = setConfigurable(
            addOption("--db-host", "Hostname or IP-Address of Server", "hostname|IPv4", CLI::TypeValidator<std::string>()), true);
        required(hostOpt);
    }
References hostOpt, utils::SubCommand::required(), and utils::SubCommand::setConfigurable().
ConfigDb() [2/2]
ConfigDb::ConfigDb (SubCommand * parent) inline
Definition at line 67 of file testmariadb.cpp.
        : SubCommand(parent, this, "Database") {
        hostOpt = setConfigurable(
            addOption("--db-host", "Hostname or IP-Address of Server", "hostname|IPv4", CLI::TypeValidator<std::string>()), true);
        required(hostOpt);
    }
Member Function Documentation
getHost() [1/2]
std::string ConfigDb::getHost () inline
Definition at line 84 of file testmariadb.cpp.
{
        return hostOpt->as<std::string>();
    }
References hostOpt.
getHost() [2/2]
std::string ConfigDb::getHost () inline
Definition at line 84 of file testmariadb.cpp.
{
        return hostOpt->as<std::string>();
    }
setHost() [1/2]
ConfigDb & ConfigDb::setHost (const std::string & host) inline
Definition at line 75 of file testmariadb.cpp.
{
        setDefaultValue(hostOpt, host);
        hostOpt->required(false);
        required(hostOpt, false);
        return *this;
    }
References hostOpt, and utils::SubCommand::required().
setHost() [2/2]
ConfigDb & ConfigDb::setHost (const std::string & host) inline
Definition at line 75 of file testmariadb.cpp.
{
        setDefaultValue(hostOpt, host);
        hostOpt->required(false);
        required(hostOpt, false);
        return *this;
    }
Member Data Documentation
DESCRIPTION
constexpr std::string_view ConfigDb::DESCRIPTION {"Database connection"} static constexpr
Definition at line 65 of file testmariadb.cpp.
{"Database connection"};
hostOpt
CLI::Option * ConfigDb::hostOpt private
Definition at line 89 of file testmariadb.cpp.
Referenced by ConfigDb(), getHost(), and setHost().
NAME
constexpr std::string_view ConfigDb::NAME {"db"} static constexpr
Definition at line 64 of file testmariadb.cpp.
{"db"};
The documentation for this class was generated from the following file:
apps/database/testmariadb.cpp