SNode.C: web::http::CookieOptions Class Reference
web::http::CookieOptions Class Reference
#include <CookieOptions.h>
Public Member Functions
CookieOptions (const std::string &value, const std::map< std::string, std::string > &options)
CookieOptions (const std::string &value)
void setOption (const std::string &optionName, const std::string &optionValue)
const std::map< std::string, std::string > & getOptions () const
const std::string & getValue () const
Private Attributes
std::string value
std::map< std::string, std::string > options
Detailed Description
Definition at line 54 of file CookieOptions.h.
Constructor & Destructor Documentation
CookieOptions() [1/2]
web::http::CookieOptions::CookieOptions (const std::string & value, const std::map< std::string, std::string > & options) inline
Definition at line 56 of file CookieOptions.h.
            : value(value)
            , options(options) {
        }
References options, and value.
Referenced by express::middleware::StaticMiddleware::appendStdCookie(), and web::http::server::Response::cookie().
CookieOptions() [2/2]
web::http::CookieOptions::CookieOptions (const std::string & value) inline explicit
Definition at line 61 of file CookieOptions.h.
            : value(value) {
        }
References value.
Referenced by web::http::client::ResponseParser::analyzeHeader().
Member Function Documentation
getOptions()
const std::map< std::string, std::string > & web::http::CookieOptions::getOptions () const inline
Definition at line 69 of file CookieOptions.h.
{
            return options;
        }
References options.
Referenced by main(), web::http::server::Response::sendHeader(), express::middleware::StaticMiddleware::StaticMiddleware(), and httputils::toString().
getValue()
const std::string & web::http::CookieOptions::getValue () const inline
Definition at line 73 of file CookieOptions.h.
{
            return value;
        }
References value.
Referenced by web::http::client::Response::cookie(), main(), web::http::server::Response::sendHeader(), express::middleware::StaticMiddleware::StaticMiddleware(), and httputils::toString().
setOption()
void web::http::CookieOptions::setOption (const std::string & optionName, const std::string & optionValue) inline
Definition at line 65 of file CookieOptions.h.
{
            options[optionName] = optionValue;
        }
References options.
Referenced by web::http::client::ResponseParser::analyzeHeader().
Member Data Documentation
options
std::map<std::string, std::string> web::http::CookieOptions::options private
Definition at line 79 of file CookieOptions.h.
Referenced by CookieOptions(), getOptions(), and setOption().
value
std::string web::http::CookieOptions::value private
Definition at line 78 of file CookieOptions.h.
Referenced by CookieOptions(), CookieOptions(), and getValue().
The documentation for this class was generated from the following file:
web/http/CookieOptions.h