SNode.C: web::websocket::SubProtocolContext Class Reference
web::websocket::SubProtocolContext Class Reference abstract
#include <SubProtocolContext.h>
Public Types
enum OpCode {
CONTINUATION = 0x00 , TEXT = 0x01 , BINARY = 0x02 , CLOSE = 0x08 ,
PING = 0x09 , PONG = 0x0A
}
Public Member Functions
SubProtocolContext (bool role)
SubProtocolContext (const SubProtocolContext &)=delete
~SubProtocolContext () override
SubProtocolContext & operator= (const SubProtocolContext &)=delete
virtual void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)=0
virtual void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)=0
virtual void sendMessageFrame (const char *message, std::size_t messageLength)=0
virtual void sendMessageEnd (const char *message, std::size_t messageLength)=0
virtual void sendPing (const char *reason=nullptr, std::size_t reasonLength=0)=0
virtual void sendPong (const char *reason=nullptr, std::size_t reasonLength=0)=0
virtual void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)=0
virtual core::socket::stream::SocketConnection * getSocketConnection ()=0
Protected Member Functions
std::size_t receive ()
Private Types
enum struct ParserState {
BEGIN , OPCODE , LENGTH , ELENGTH ,
MASKINGKEY , PAYLOAD , ERROR
}
Private Member Functions
virtual void sendClose (const char *message, std::size_t messageLength)=0
std::size_t readOpcode ()
std::size_t readLength ()
std::size_t readELength ()
std::size_t readMaskingKey ()
std::size_t readPayload ()
virtual void onMessageStart (int opCode)=0
virtual void onMessageData (const char *junk, uint64_t junkLen)=0
virtual void onMessageEnd ()=0
virtual void onMessageError (uint16_t errnum)=0
virtual std::size_t readFrameData (char *junk, std::size_t junkLen)=0
void reset ()
void send (bool end, uint8_t opCode, const char *message, std::size_t messageLength)
void sendFrame (bool fin, uint8_t opCode, const char *payload, uint64_t payloadLength)
virtual void sendFrameData (uint8_t data) const =0
virtual void sendFrameData (uint16_t data) const =0
virtual void sendFrameData (uint32_t data) const =0
virtual void sendFrameData (uint64_t data) const =0
virtual void sendFrameData (const char *frame, uint64_t frameLength) const =0
Private Attributes
enum web::websocket::Receiver::ParserState parserState = ParserState::BEGIN
bool fin = false
bool continuation = false
bool masked = false
uint8_t opCode = 0
uint8_t elengthNumBytes = 0
uint8_t elengthNumBytesLeft = 0
uint64_t payLoadNumBytes = 0
uint64_t payLoadNumBytesLeft = 0
uint32_t maskingKey = 0
MaskingKey maskingKeyAsArray {}
uint8_t maskingKeyNumBytes = 4
uint8_t maskingKeyNumBytesLeft = 4
uint16_t errorState = 0
char elengthJunk [8] {}
char maskingKeyJunk [4] {}
char payloadJunk [16384] {}
std::random_device randomDevice
std::uniform_int_distribution< uint32_t > distribution {0, UINT32_MAX}
bool masking = false
Detailed Description
Definition at line 39 of file SubProtocolContext.h.
Member Enumeration Documentation
OpCode
enum web::websocket::SubProtocolContext::OpCode
Enumerator
CONTINUATION
TEXT
BINARY
CLOSE
PING
PONG
Definition at line 61 of file SubProtocolContext.h.
{ CONTINUATION = 0x00, TEXT = 0x01, BINARY = 0x02, CLOSE = 0x08, PING = 0x09, PONG = 0x0A };
ParserState
enum struct web::websocket::Receiver::ParserState strong private inherited
Enumerator
BEGIN
OPCODE
LENGTH
ELENGTH
MASKINGKEY
PAYLOAD
ERROR
Definition at line 69 of file Receiver.h.
{ BEGIN, OPCODE, LENGTH, ELENGTH, MASKINGKEY, PAYLOAD, ERROR } parserState = ParserState::BEGIN;
Constructor & Destructor Documentation
SubProtocolContext() [1/2]
web::websocket::SubProtocolContext::SubProtocolContext (bool role)
Definition at line 28 of file SubProtocolContext.cpp.
        : Transmitter(role) {
    }
References web::websocket::Transmitter::Transmitter().
SubProtocolContext() [2/2]
web::websocket::SubProtocolContext::SubProtocolContext (const SubProtocolContext &) delete
~SubProtocolContext()
web::websocket::SubProtocolContext::~SubProtocolContext () override
Definition at line 32 of file SubProtocolContext.cpp.
{
    }
Member Function Documentation
getSocketConnection()
virtual core::socket::stream::SocketConnection * web::websocket::SubProtocolContext::getSocketConnection () pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::getSocketConnection().
onMessageData()
virtual void web::websocket::Receiver::onMessageData (const char * junk, uint64_t junkLen) private pure virtual inherited
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::Receiver::readPayload().
onMessageEnd()
virtual void web::websocket::Receiver::onMessageEnd () private pure virtual inherited
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::Receiver::readLength(), web::websocket::Receiver::readMaskingKey(), and web::websocket::Receiver::readPayload().
onMessageError()
virtual void web::websocket::Receiver::onMessageError (uint16_t errnum) private pure virtual inherited
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::Receiver::receive().
onMessageStart()
virtual void web::websocket::Receiver::onMessageStart (int opCode) private pure virtual inherited
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::Receiver::readOpcode().
operator=()
SubProtocolContext & web::websocket::SubProtocolContext::operator= (const SubProtocolContext &) delete
readELength()
std::size_t web::websocket::Receiver::readELength () private inherited
Definition at line 136 of file Receiver.cpp.
{
        const std::size_t ret = readFrameData(elengthJunk, elengthNumBytesLeft);
        for (std::size_t i = 0; i < ret; i++) {
            payLoadNumBytes |= *reinterpret_cast<uint64_t*>(elengthJunk + i) << (elengthNumBytes - elengthNumBytesLeft) * 8;
            elengthNumBytesLeft--;
        }
        if (elengthNumBytesLeft == 0) {
            switch (elengthNumBytes) {
                case 2:
                    payLoadNumBytes = payLoadNumBytesLeft = be16toh(static_cast<uint16_t>(payLoadNumBytes));
                    break;
                case 8:
                    payLoadNumBytes = payLoadNumBytesLeft = be64toh(payLoadNumBytes);
                    break;
            }
            if ((payLoadNumBytes & static_cast<uint64_t>(0x01) << 63) != 0) {
                parserState = ParserState::ERROR;
                errorState = 1004;
            } else if (masked) {
                parserState = ParserState::MASKINGKEY;
            } else {
                parserState = ParserState::PAYLOAD;
            }
        }
        return ret;
    }
References web::websocket::Receiver::elengthJunk, web::websocket::Receiver::elengthNumBytes, web::websocket::Receiver::elengthNumBytesLeft, web::websocket::Receiver::ERROR, web::websocket::Receiver::errorState, web::websocket::Receiver::masked, web::websocket::Receiver::MASKINGKEY, web::websocket::Receiver::PAYLOAD, web::websocket::Receiver::payLoadNumBytes, web::websocket::Receiver::payLoadNumBytesLeft, and web::websocket::Receiver::readFrameData().
Referenced by web::websocket::Receiver::receive().
readFrameData()
virtual std::size_t web::websocket::Receiver::readFrameData (char * junk, std::size_t junkLen) private pure virtual inherited
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), web::websocket::Receiver::readMaskingKey(), web::websocket::Receiver::readOpcode(), and web::websocket::Receiver::readPayload().
readLength()
std::size_t web::websocket::Receiver::readLength () private inherited
Definition at line 98 of file Receiver.cpp.
{
        char byte = 0;
        const std::size_t ret = readFrameData(&byte, 1);
        if (ret > 0) {
            const uint8_t lengthByte = static_cast<uint8_t>(byte);
            masked = (lengthByte & 0b10000000) != 0;
            payLoadNumBytes = payLoadNumBytesLeft = lengthByte & 0b01111111;
            if (payLoadNumBytes > 125) {
                switch (payLoadNumBytes) {
                    case 126:
                        elengthNumBytes = elengthNumBytesLeft = 2;
                        break;
                    case 127:
                        elengthNumBytes = elengthNumBytesLeft = 8;
                        break;
                }
                parserState = ParserState::ELENGTH;
                payLoadNumBytes = payLoadNumBytesLeft = 0;
            } else {
                if (masked) {
                    parserState = ParserState::MASKINGKEY;
                } else if (payLoadNumBytes > 0) {
                    parserState = ParserState::PAYLOAD;
                } else {
                    if (fin) {
                        onMessageEnd();
                    }
                    reset();
                }
            }
        }
        return ret;
    }
References web::websocket::Receiver::ELENGTH, web::websocket::Receiver::elengthNumBytes, web::websocket::Receiver::elengthNumBytesLeft, web::websocket::Receiver::fin, web::websocket::Receiver::masked, web::websocket::Receiver::MASKINGKEY, web::websocket::Receiver::onMessageEnd(), web::websocket::Receiver::PAYLOAD, web::websocket::Receiver::payLoadNumBytes, web::websocket::Receiver::payLoadNumBytesLeft, web::websocket::Receiver::readFrameData(), and web::websocket::Receiver::reset().
Referenced by web::websocket::Receiver::receive().
readMaskingKey()
std::size_t web::websocket::Receiver::readMaskingKey () private inherited
Definition at line 168 of file Receiver.cpp.
{
        const std::size_t ret = readFrameData(maskingKeyJunk, maskingKeyNumBytesLeft);
        for (std::size_t i = 0; i < ret; i++) {
            maskingKey |= static_cast<uint32_t>(*reinterpret_cast<unsigned char*>(maskingKeyJunk + i))
                          << (maskingKeyNumBytes - maskingKeyNumBytesLeft) * 8;
            maskingKeyNumBytesLeft--;
        }
        if (maskingKeyNumBytesLeft == 0) {
            maskingKeyAsArray = {.key = maskingKey};
            if (payLoadNumBytes > 0) {
                parserState = ParserState::PAYLOAD;
            } else {
                if (fin) {
                    onMessageEnd();
                }
                reset();
            }
        }
        return ret;
    }
References web::websocket::Receiver::fin, web::websocket::Receiver::MaskingKey::key, web::websocket::Receiver::maskingKey, web::websocket::Receiver::maskingKeyAsArray, web::websocket::Receiver::maskingKeyJunk, web::websocket::Receiver::maskingKeyNumBytes, web::websocket::Receiver::maskingKeyNumBytesLeft, web::websocket::Receiver::onMessageEnd(), web::websocket::Receiver::PAYLOAD, web::websocket::Receiver::payLoadNumBytes, web::websocket::Receiver::readFrameData(), and web::websocket::Receiver::reset().
Referenced by web::websocket::Receiver::receive().
readOpcode()
std::size_t web::websocket::Receiver::readOpcode () private inherited
Definition at line 72 of file Receiver.cpp.
{
        char byte = 0;
        const std::size_t ret = readFrameData(&byte, 1);
        if (ret > 0) {
            const uint8_t opCodeByte = static_cast<uint8_t>(byte);
            fin = (opCodeByte & 0b10000000) != 0;
            opCode = opCodeByte & 0b00001111;
            if (!continuation) {
                onMessageStart(opCode);
                parserState = ParserState::LENGTH;
            } else if (opCode == 0) {
                parserState = ParserState::LENGTH;
            } else {
                parserState = ParserState::ERROR;
                errorState = 1002;
                LOG(DEBUG) << "WebSocket: Error opcode in continuation frame";
            }
            continuation = !fin;
        }
        return ret;
    }
References web::websocket::Receiver::continuation, web::websocket::Receiver::ERROR, web::websocket::Receiver::errorState, web::websocket::Receiver::fin, web::websocket::Receiver::LENGTH, web::websocket::Receiver::onMessageStart(), web::websocket::Receiver::opCode, and web::websocket::Receiver::readFrameData().
Referenced by web::websocket::Receiver::receive().
readPayload()
std::size_t web::websocket::Receiver::readPayload () private inherited
Definition at line 193 of file Receiver.cpp.
{
        const std::size_t payloadJunkLeft = (MAX_PAYLOAD_JUNK_LEN <= payLoadNumBytesLeft) ? static_cast<std::size_t>(MAX_PAYLOAD_JUNK_LEN)
                                                                                          : static_cast<std::size_t>(payLoadNumBytesLeft);
        const std::size_t ret = readFrameData(payloadJunk, payloadJunkLeft);
        if (ret > 0) {
            const std::size_t payloadJunkLen = static_cast<std::size_t>(ret);
            if (masked) {
                for (std::size_t i = 0; i < payloadJunkLen; i++) {
                    *(payloadJunk + i) =
                        *(payloadJunk + i) ^ *(maskingKeyAsArray.keyAsArray + (i + payLoadNumBytes - payLoadNumBytesLeft) % 4);
                }
            }
            onMessageData(payloadJunk, payloadJunkLen);
            payLoadNumBytesLeft -= payloadJunkLen;
        }
        if (payLoadNumBytesLeft == 0) {
            if (fin) {
                onMessageEnd();
            }
            reset();
        }
        return ret;
    }
References web::websocket::Receiver::fin, web::websocket::Receiver::MaskingKey::keyAsArray, web::websocket::Receiver::masked, web::websocket::Receiver::maskingKeyAsArray, web::websocket::Receiver::onMessageData(), web::websocket::Receiver::onMessageEnd(), web::websocket::Receiver::payloadJunk, web::websocket::Receiver::payLoadNumBytes, web::websocket::Receiver::payLoadNumBytesLeft, web::websocket::Receiver::readFrameData(), and web::websocket::Receiver::reset().
Referenced by web::websocket::Receiver::receive().
receive()
std::size_t web::websocket::Receiver::receive () inherited
Definition at line 35 of file Receiver.cpp.
{
        std::size_t ret = 0;
        std::size_t consumed = 0;
        // dumpFrame(junk, junkLen);
        do {
            switch (parserState) {
                case ParserState::BEGIN:
                    parserState = ParserState::OPCODE;
                    [[fallthrough]];
                case ParserState::OPCODE:
                    ret = readOpcode();
                    break;
                case ParserState::LENGTH:
                    ret = readLength();
                    break;
                case ParserState::ELENGTH:
                    ret = readELength();
                    break;
                case ParserState::MASKINGKEY:
                    ret = readMaskingKey();
                    break;
                case ParserState::PAYLOAD:
                    ret = readPayload();
                    break;
                case ParserState::ERROR:
                    onMessageError(errorState);
                    reset();
                    break;
            }
            consumed += ret;
        } while (ret > 0 && parserState != ParserState::BEGIN && parserState != ParserState::ERROR);
        return consumed;
    }
References web::websocket::Receiver::BEGIN, web::websocket::Receiver::ELENGTH, web::websocket::Receiver::ERROR, web::websocket::Receiver::errorState, web::websocket::Receiver::LENGTH, web::websocket::Receiver::MASKINGKEY, web::websocket::Receiver::onMessageError(), web::websocket::Receiver::OPCODE, web::websocket::Receiver::PAYLOAD, web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), web::websocket::Receiver::readMaskingKey(), web::websocket::Receiver::readOpcode(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::reset().
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onReceivedFromPeer().
reset()
void web::websocket::Receiver::reset () private inherited
Definition at line 224 of file Receiver.cpp.
{
        parserState = ParserState::BEGIN;
        fin = false;
        continuation = false;
        masked = false;
        opCode = 0;
        elengthNumBytes = 0;
        elengthNumBytesLeft = 0;
        payLoadNumBytes = 0;
        payLoadNumBytesLeft = 0;
        maskingKey = 0;
        maskingKeyAsArray = {.key = 0};
        maskingKeyNumBytes = 4;
        maskingKeyNumBytesLeft = 4;
        errorState = 0;
    }
References web::websocket::Receiver::BEGIN, web::websocket::Receiver::continuation, web::websocket::Receiver::elengthNumBytes, web::websocket::Receiver::elengthNumBytesLeft, web::websocket::Receiver::errorState, web::websocket::Receiver::fin, web::websocket::Receiver::MaskingKey::key, web::websocket::Receiver::masked, web::websocket::Receiver::maskingKey, web::websocket::Receiver::maskingKeyAsArray, web::websocket::Receiver::maskingKeyNumBytes, web::websocket::Receiver::maskingKeyNumBytesLeft, web::websocket::Receiver::opCode, web::websocket::Receiver::payLoadNumBytes, and web::websocket::Receiver::payLoadNumBytesLeft.
Referenced by web::websocket::Receiver::readLength(), web::websocket::Receiver::readMaskingKey(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::receive().
send()
void web::websocket::Transmitter::send (bool end, uint8_t opCode, const char * message, std::size_t messageLength) private inherited
Definition at line 55 of file Transmitter.cpp.
{
        std::size_t messageOffset = 0;
        do {
            const std::size_t sendFrameLength =
                (messageLength - messageOffset <= WSMAXFRAMEPAYLOADLENGTH) ? messageLength - messageOffset : WSMAXFRAMEPAYLOADLENGTH;
            const bool fin = (sendFrameLength == messageLength - messageOffset) && end; // cppcheck-suppress knownConditionTrueFalse
            sendFrame(fin, opCode, message + messageOffset, sendFrameLength);
            messageOffset += sendFrameLength;
            opCode = 0; // continuation
        } while (messageLength - messageOffset > 0);
    }
References web::websocket::Transmitter::sendFrame(), and WSMAXFRAMEPAYLOADLENGTH.
Referenced by web::websocket::Transmitter::sendMessage(), web::websocket::Transmitter::sendMessageEnd(), web::websocket::Transmitter::sendMessageFrame(), and web::websocket::Transmitter::sendMessageStart().
sendClose() [1/2]
virtual void web::websocket::SubProtocolContext::sendClose (const char * message, std::size_t messageLength) private pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
sendClose() [2/2]
virtual void web::websocket::SubProtocolContext::sendClose (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0) pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::sendClose().
sendFrame()
void web::websocket::Transmitter::sendFrame (bool fin, uint8_t opCode, const char * payload, uint64_t payloadLength) private inherited
Definition at line 72 of file Transmitter.cpp.
{
        uint64_t length = 0;
        if (payloadLength < 126) {
            length = payloadLength;
        } else if (payloadLength < 0x10000) {
            length = 126;
        } else {
            length = 127;
        }
        char header[2];
        header[0] = static_cast<char>((fin ? 0b10000000 : 0) | opCode);
        header[1] = static_cast<char>((masking ? 0b10000000 : 0) | length);
        sendFrameData(header, 2);
        switch (length) {
            case 126:
                sendFrameData(static_cast<uint16_t>(payloadLength));
                break;
            case 127:
                sendFrameData(payloadLength);
                break;
        }
        union MaskingKey {
            uint32_t keyAsValue;
            char keyAsBytes[4];
        };
        MaskingKey maskingKeyAsArray = {.keyAsValue = distribution(randomDevice)};
        if (masking) {
            sendFrameData(htobe32(maskingKeyAsArray.keyAsValue));
            for (uint64_t i = 0; i < payloadLength; i++) {
                *(const_cast<char*>(payload) + i) = static_cast<char>(*(payload + i) ^ *(maskingKeyAsArray.keyAsBytes + i % 4));
            }
        }
        sendFrameData(payload, payloadLength);
        if (masking) {
            for (uint64_t i = 0; i < payloadLength; i++) {
                *(const_cast<char*>(payload) + i) = static_cast<char>(*(payload + i) ^ *(maskingKeyAsArray.keyAsBytes + i % 4));
            }
        }
    }
References web::websocket::Transmitter::distribution, web::websocket::Transmitter::masking, web::websocket::Transmitter::randomDevice, web::websocket::Transmitter::sendFrameData(), web::websocket::Transmitter::sendFrameData(), web::websocket::Transmitter::sendFrameData(), and web::websocket::Transmitter::sendFrameData().
Referenced by web::websocket::Transmitter::send().
sendFrameData() [1/5]
virtual void web::websocket::Transmitter::sendFrameData (const char * frame, uint64_t frameLength) const private pure virtual inherited
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::Transmitter::sendFrame().
sendFrameData() [2/5]
virtual void web::websocket::Transmitter::sendFrameData (uint16_t data) const private pure virtual inherited
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::Transmitter::sendFrame().
sendFrameData() [3/5]
virtual void web::websocket::Transmitter::sendFrameData (uint32_t data) const private pure virtual inherited
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::Transmitter::sendFrame().
sendFrameData() [4/5]
virtual void web::websocket::Transmitter::sendFrameData (uint64_t data) const private pure virtual inherited
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::Transmitter::sendFrame().
sendFrameData() [5/5]
virtual void web::websocket::Transmitter::sendFrameData (uint8_t data) const private pure virtual inherited
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
sendMessage()
virtual void web::websocket::SubProtocolContext::sendMessage (uint8_t opCode, const char * message, std::size_t messageLength) pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::sendMessage().
sendMessageEnd()
virtual void web::websocket::SubProtocolContext::sendMessageEnd (const char * message, std::size_t messageLength) pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::sendMessageEnd().
sendMessageFrame()
virtual void web::websocket::SubProtocolContext::sendMessageFrame (const char * message, std::size_t messageLength) pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::SubProtocol< web::websocket::client::SocketContextUpgrade >::getSocketConnection().
sendMessageStart()
virtual void web::websocket::SubProtocolContext::sendMessageStart (uint8_t opCode, const char * message, std::size_t messageLength) pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::sendMessageStart().
sendPing()
virtual void web::websocket::SubProtocolContext::sendPing (const char * reason = nullptr, std::size_t reasonLength = 0) pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by web::websocket::SubProtocol< SocketContextUpgradeT >::sendPing().
sendPong()
virtual void web::websocket::SubProtocolContext::sendPong (const char * reason = nullptr, std::size_t reasonLength = 0) pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Member Data Documentation
continuation
bool web::websocket::Receiver::continuation = false private inherited
Definition at line 72 of file Receiver.h.
Referenced by web::websocket::Receiver::readOpcode(), and web::websocket::Receiver::reset().
distribution
std::uniform_int_distribution<uint32_t> web::websocket::Transmitter::distribution {0, UINT32_MAX} private inherited
Definition at line 63 of file Transmitter.h.
{0, UINT32_MAX};
Referenced by web::websocket::Transmitter::sendFrame().
elengthJunk
char web::websocket::Receiver::elengthJunk[8] {} private inherited
Definition at line 90 of file Receiver.h.
{};
Referenced by web::websocket::Receiver::readELength().
elengthNumBytes
uint8_t web::websocket::Receiver::elengthNumBytes = 0 private inherited
Definition at line 77 of file Receiver.h.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), and web::websocket::Receiver::reset().
elengthNumBytesLeft
uint8_t web::websocket::Receiver::elengthNumBytesLeft = 0 private inherited
Definition at line 78 of file Receiver.h.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), and web::websocket::Receiver::reset().
errorState
uint16_t web::websocket::Receiver::errorState = 0 private inherited
Definition at line 88 of file Receiver.h.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readOpcode(), web::websocket::Receiver::receive(), and web::websocket::Receiver::reset().
fin
bool web::websocket::Receiver::fin = false private inherited
Definition at line 71 of file Receiver.h.
Referenced by web::websocket::Receiver::readLength(), web::websocket::Receiver::readMaskingKey(), web::websocket::Receiver::readOpcode(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::reset().
masked
bool web::websocket::Receiver::masked = false private inherited
Definition at line 73 of file Receiver.h.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::reset().
masking
bool web::websocket::Transmitter::masking = false private inherited
Definition at line 65 of file Transmitter.h.
Referenced by web::websocket::Transmitter::sendFrame(), and web::websocket::Transmitter::Transmitter().
maskingKey
uint32_t web::websocket::Receiver::maskingKey = 0 private inherited
Definition at line 83 of file Receiver.h.
Referenced by web::websocket::Receiver::readMaskingKey(), and web::websocket::Receiver::reset().
maskingKeyAsArray
MaskingKey web::websocket::Receiver::maskingKeyAsArray {} private inherited
Definition at line 84 of file Receiver.h.
{};
Referenced by web::websocket::Receiver::readMaskingKey(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::reset().
maskingKeyJunk
char web::websocket::Receiver::maskingKeyJunk[4] {} private inherited
Definition at line 91 of file Receiver.h.
{};
Referenced by web::websocket::Receiver::readMaskingKey().
maskingKeyNumBytes
uint8_t web::websocket::Receiver::maskingKeyNumBytes = 4 private inherited
Definition at line 85 of file Receiver.h.
Referenced by web::websocket::Receiver::readMaskingKey(), and web::websocket::Receiver::reset().
maskingKeyNumBytesLeft
uint8_t web::websocket::Receiver::maskingKeyNumBytesLeft = 4 private inherited
Definition at line 86 of file Receiver.h.
Referenced by web::websocket::Receiver::readMaskingKey(), and web::websocket::Receiver::reset().
opCode
uint8_t web::websocket::Receiver::opCode = 0 private inherited
Definition at line 75 of file Receiver.h.
Referenced by web::websocket::Receiver::readOpcode(), and web::websocket::Receiver::reset().
parserState
enum web::websocket::Receiver::ParserState web::websocket::Receiver::parserState = ParserState::BEGIN private inherited
payloadJunk
char web::websocket::Receiver::payloadJunk[16384] {} private inherited
Definition at line 92 of file Receiver.h.
{};
Referenced by web::websocket::Receiver::readPayload().
payLoadNumBytes
uint64_t web::websocket::Receiver::payLoadNumBytes = 0 private inherited
Definition at line 80 of file Receiver.h.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), web::websocket::Receiver::readMaskingKey(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::reset().
payLoadNumBytesLeft
uint64_t web::websocket::Receiver::payLoadNumBytesLeft = 0 private inherited
Definition at line 81 of file Receiver.h.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::reset().
randomDevice
std::random_device web::websocket::Transmitter::randomDevice private inherited
Definition at line 62 of file Transmitter.h.
Referenced by web::websocket::Transmitter::sendFrame().
The documentation for this class was generated from the following files:
web/websocket/SubProtocolContext.h
web/websocket/SubProtocolContext.cpp