SNode.C: web::websocket::SubProtocolFactory< SubProtocolT > Class Template Reference
web::websocket::SubProtocolFactory< SubProtocolT > Class Template Reference abstract
#include <SubProtocolFactory.h>
Public Types
using SubProtocol = SubProtocolT
Public Member Functions
SubProtocolFactory ()=delete
SubProtocolFactory (const std::string &name)
SubProtocolFactory (SubProtocolFactory &)=delete
SubProtocolFactory (SubProtocolFactory &&)=delete
SubProtocolFactory & operator= (SubProtocolFactory &)=delete
SubProtocolFactory & operator= (SubProtocolFactory &&)=delete
virtual ~SubProtocolFactory ()=default
SubProtocol * createSubProtocol (SubProtocolContext *subProtocolContext)
virtual std::size_t deleteSubProtocol (SubProtocol *subProtocol)
const std::string & getName ()
void setHandle (void *handle)
void * getHandle ()
Private Member Functions
virtual SubProtocol * create (SubProtocolContext *subProtocolContext)=0
Private Attributes
std::size_t refCount = 0
std::string subProtocolName
void * handle = nullptr
Detailed Description
template<typename SubProtocolT>
class web::websocket::SubProtocolFactory< SubProtocolT >
Definition at line 60 of file SubProtocolFactory.h.
Member Typedef Documentation
SubProtocol
template<typename SubProtocolT> using web::websocket::SubProtocolFactory< SubProtocolT >::SubProtocol = SubProtocolT
Definition at line 62 of file SubProtocolFactory.h.
Constructor & Destructor Documentation
SubProtocolFactory() [1/4]
template<typename SubProtocolT> web::websocket::SubProtocolFactory< SubProtocolT >::SubProtocolFactory () delete
SubProtocolFactory() [2/4]
template<typename SubProtocolT> web::websocket::SubProtocolFactory< SubProtocolT >::SubProtocolFactory (const std::string & name) inline
Definition at line 66 of file SubProtocolFactory.h.
            : subProtocolName(name) {
        }
References subProtocolName.
SubProtocolFactory() [3/4]
template<typename SubProtocolT> web::websocket::SubProtocolFactory< SubProtocolT >::SubProtocolFactory (SubProtocolFactory< SubProtocolT > &) delete
SubProtocolFactory() [4/4]
template<typename SubProtocolT> web::websocket::SubProtocolFactory< SubProtocolT >::SubProtocolFactory (SubProtocolFactory< SubProtocolT > &&) delete
~SubProtocolFactory()
template<typename SubProtocolT> virtual web::websocket::SubProtocolFactory< SubProtocolT >::~SubProtocolFactory () virtual default
Member Function Documentation
create()
template<typename SubProtocolT> virtual SubProtocol * web::websocket::SubProtocolFactory< SubProtocolT >::create (SubProtocolContext * subProtocolContext) private pure virtual
Implemented in apps::websocket::subprotocol::echo::client::EchoFactory, and apps::websocket::subprotocol::echo::server::EchoFactory.
Referenced by createSubProtocol().
createSubProtocol()
template<typename SubProtocolT> SubProtocol * web::websocket::SubProtocolFactory< SubProtocolT >::createSubProtocol (SubProtocolContext * subProtocolContext) inline
Definition at line 78 of file SubProtocolFactory.h.
{
            SubProtocol* subProtocol = create(subProtocolContext);
            if (subProtocol != nullptr) {
                refCount++;
            }
            return subProtocol;
        }
References create(), and refCount.
Referenced by web::websocket::client::SocketContextUpgrade::loadSubProtocol(), and web::websocket::server::SocketContextUpgrade::loadSubProtocol().
deleteSubProtocol()
template<typename SubProtocolT> virtual std::size_t web::websocket::SubProtocolFactory< SubProtocolT >::deleteSubProtocol (SubProtocol * subProtocol) inline virtual
Definition at line 92 of file SubProtocolFactory.h.
{
            if (subProtocol != nullptr) {
                delete subProtocol;
                refCount--;
            }
            return refCount;
        }
References refCount.
Referenced by web::websocket::client::SocketContextUpgrade::~SocketContextUpgrade(), and web::websocket::server::SocketContextUpgrade::~SocketContextUpgrade().
getHandle()
template<typename SubProtocolT> void * web::websocket::SubProtocolFactory< SubProtocolT >::getHandle () inline
Definition at line 110 of file SubProtocolFactory.h.
{
            return handle;
        }
References handle.
getName()
template<typename SubProtocolT> const std::string & web::websocket::SubProtocolFactory< SubProtocolT >::getName () inline
Definition at line 102 of file SubProtocolFactory.h.
{
            return subProtocolName;
        }
References subProtocolName.
Referenced by apps::websocket::subprotocol::echo::client::EchoFactory::create(), and apps::websocket::subprotocol::echo::server::EchoFactory::create().
operator=() [1/2]
template<typename SubProtocolT> SubProtocolFactory & web::websocket::SubProtocolFactory< SubProtocolT >::operator= (SubProtocolFactory< SubProtocolT > &&) delete
operator=() [2/2]
template<typename SubProtocolT> SubProtocolFactory & web::websocket::SubProtocolFactory< SubProtocolT >::operator= (SubProtocolFactory< SubProtocolT > &) delete
setHandle()
template<typename SubProtocolT> void web::websocket::SubProtocolFactory< SubProtocolT >::setHandle (void * handle) inline
Definition at line 106 of file SubProtocolFactory.h.
{
            this->handle = handle;
        }
References handle.
Member Data Documentation
handle
template<typename SubProtocolT> void* web::websocket::SubProtocolFactory< SubProtocolT >::handle = nullptr private
Definition at line 119 of file SubProtocolFactory.h.
Referenced by getHandle(), and setHandle().
refCount
template<typename SubProtocolT> std::size_t web::websocket::SubProtocolFactory< SubProtocolT >::refCount = 0 private
Definition at line 115 of file SubProtocolFactory.h.
Referenced by createSubProtocol(), and deleteSubProtocol().
subProtocolName
template<typename SubProtocolT> std::string web::websocket::SubProtocolFactory< SubProtocolT >::subProtocolName private
Definition at line 117 of file SubProtocolFactory.h.
Referenced by getName(), and SubProtocolFactory().
The documentation for this class was generated from the following files:
web/websocket/client/SocketContextUpgrade.h
web/websocket/SubProtocolFactory.h