SNode.C: web::http::server::SocketContextFactory Class Reference
web::http::server::SocketContextFactory Class Reference
#include <SocketContextFactory.h>
Public Types
using Request = web::http::server::Request
using Response = web::http::server::Response
Public Member Functions
SocketContextFactory (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &onRequestReady)
Public Member Functions inherited from core::socket::stream::SocketContextFactory
SocketContextFactory (SocketContextFactory &)=delete
SocketContextFactory (SocketContextFactory &&)=delete
SocketContextFactory & operator= (SocketContextFactory &)=delete
SocketContextFactory & operator= (SocketContextFactory &&)=delete
Private Member Functions
core::socket::stream::SocketContext * create (core::socket::stream::SocketConnection *socketConnection) override
Private Attributes
std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> onRequestReady
Additional Inherited Members
Protected Member Functions inherited from web::http::SocketContextFactory< web::http::server::SocketContext >
SocketContextFactory ()=default
~SocketContextFactory () override=default
Protected Member Functions inherited from core::socket::stream::SocketContextFactory
SocketContextFactory ()=default
Detailed Description
Definition at line 64 of file SocketContextFactory.h.
Member Typedef Documentation
Request
using web::http::server::SocketContextFactory::Request = web::http::server::Request
Definition at line 66 of file SocketContextFactory.h.
Response
using web::http::server::SocketContextFactory::Response = web::http::server::Response
Definition at line 67 of file SocketContextFactory.h.
Constructor & Destructor Documentation
SocketContextFactory()
web::http::server::SocketContextFactory::SocketContextFactory (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & onRequestReady) inline explicit
Definition at line 69 of file SocketContextFactory.h.
            : onRequestReady(onRequestReady) {
        }
References onRequestReady.
Member Function Documentation
create()
core::socket::stream::SocketContext * web::http::server::SocketContextFactory::create (core::socket::stream::SocketConnection * socketConnection) override private virtual
Implements core::socket::stream::SocketContextFactory.
Definition at line 50 of file SocketContextFactory.cpp.
{
        return new web::http::server::SocketContext(socketConnection, onRequestReady);
    }
References onRequestReady, and web::http::server::SocketContext::SocketContext().
Member Data Documentation
onRequestReady
std::function<void(const std::shared_ptr<Request>&, const std::shared_ptr<Response>&)> web::http::server::SocketContextFactory::onRequestReady private
Definition at line 77 of file SocketContextFactory.h.
Referenced by create(), and SocketContextFactory().
The documentation for this class was generated from the following files:
web/http/server/SocketContextFactory.h
web/http/server/SocketContextFactory.cpp