SNode.C: express::Next Class Reference
express::Next Class Reference
#include <Next.h>
Public Member Functions
Next (Controller &controller)
void operator() (const std::string &how="") const
Private Attributes
Controller controller
Friends
class dispatcher::MiddlewareDispatcher
Detailed Description
Definition at line 59 of file Next.h.
Constructor & Destructor Documentation
Next()
express::Next::Next (Controller & controller) explicit
Definition at line 52 of file Next.cpp.
        : controller(controller) {
    }
References express::Controller::Controller(), and controller.
Referenced by express::dispatcher::MiddlewareDispatcher::dispatch().
Member Function Documentation
operator()()
void express::Next::operator() (const std::string & how = "") const
Definition at line 56 of file Next.cpp.
{
        controller.next(how);
    }
References controller, and express::Controller::next().
Referenced by express::middleware::BasicAuthentication::BasicAuthentication(), express::middleware::JsonMiddleware::JsonMiddleware(), main(), express::middleware::StaticMiddleware::StaticMiddleware(), express::middleware::VerboseRequest::VerboseRequest(), and express::middleware::VHost::VHost().
Friends And Related Symbol Documentation
dispatcher::MiddlewareDispatcher
friend class dispatcher::MiddlewareDispatcher friend
Definition at line 68 of file Next.h.
Member Data Documentation
controller
Controller express::Next::controller private
Definition at line 66 of file Next.h.
Referenced by express::dispatcher::MiddlewareDispatcher::dispatch(), Next(), and operator()().
The documentation for this class was generated from the following files:
express/Next.h
express/Next.cpp