SNode.C: net::in::config::ConfigAddress< ConfigAddressTypeT > Class Template Reference
net::in::config::ConfigAddress< ConfigAddressTypeT > Class Template Reference
#include <ConfigAddress.h>
Public Member Functions
SocketAddress getSocketAddress (const SocketAddress::SockAddr &sockAddr, SocketAddress::SockLen sockAddrLen)
ConfigAddress & setSocketAddress (const SocketAddress &socketAddress)
ConfigAddress & setHost (const std::string &ipOrHostname)
std::string getHost () const
ConfigAddress & setPort (uint16_t port)
uint16_t getPort () const
ConfigAddress & setNumeric (bool numeric=true)
bool getNumeric () const
ConfigAddress & setNumericReverse (bool numeric=true)
bool getNumericReverse () const
void configurable (bool configurable=true) final
Public Member Functions inherited from net::config::ConfigSection
template<typename T>
ConfigSection (ConfigInstance *instance, T *sectionPtr, const std::string &group="Sections")
~ConfigSection () override
ConfigSection (const ConfigSection &)=delete
ConfigSection (ConfigSection &&)=delete
ConfigSection & operator= (const ConfigSection &)=delete
Public Member Functions inherited from utils::SubCommand
SubCommand (const SubCommand &)=delete
SubCommand (SubCommand &&)=delete
SubCommand & operator= (const SubCommand &)=delete
SubCommand & operator= (SubCommand &&)=delete
virtual ~SubCommand ()
std::string getName () const
std::string version () const
void parse (int argc, char *argv[])
CLI::Option * setConfig (const std::string &defaultConfigFile) const
CLI::Option * setLogFile (const std::string &defaultLogFile) const
CLI::Option * setVersionFlag (const std::string &version) const
bool hasParent () const
SubCommand * getParent ()
SubCommand * allowExtras (bool allow=true)
SubCommand * required (bool required=true, bool force=true)
SubCommand * required (SubCommand *subCommand, bool required=true)
SubCommand * required (CLI::Option *option, bool required=true)
SubCommand * needs (SubCommand *subCommand, bool needs=true)
SubCommand * disabled (SubCommand *subCommand, bool disabled=true)
SubCommand * setRequireCallback (const std::function< void(void)> &callback)
SubCommand * finalCallback (const std::function< void()> &finalCallback)
std::string configToStr () const
std::string help (const CLI::App *helpApp, const CLI::AppFormatMode &mode) const
template<typename NewSubCommand, typename... Args>
NewSubCommand * newSubCommand (Args &&... args)
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand ()
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand () const
CLI::Option * getOption (const std::string &name) const
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator) const
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Protected Member Functions
ConfigAddress (net::config::ConfigInstance *instance, const std::string &addressOptionName, const std::string &addressOptionDescription)
ConfigAddress & setAiFlags (int aiFlags)
int getAiFlags () const
ConfigAddress & setAiSockType (int aiSockType)
int getAiSockType () const
ConfigAddress & setAiProtocol (int aiProtocol)
int getAiProtocol () const
ConfigAddress & setHostRequired (bool required=true)
ConfigAddress & setPortRequired (bool required=true)
Protected Member Functions inherited from utils::SubCommand
SubCommand (SubCommand *parent, std::shared_ptr< utils::AppWithPtr > appWithPtr, const std::string &group, bool final)
template<typename ConcretSubCommand>
SubCommand (SubCommand *parent, ConcretSubCommand *concretSubCommand, const std::string &group, bool final=true)
SubCommand * description (const std::string &description)
SubCommand * footer (const std::string &footer)
template<typename ValueTypeT>
CLI::Option * setDefaultValue (CLI::Option *option, const ValueTypeT &value, bool clear=true) const
CLI::Option * setConfigurable (CLI::Option *option, bool configurable) const
Private Types
using Super = ConfigAddressTypeT<net::in::SocketAddress>
Private Member Functions
SocketAddress * init () final
Private Attributes
CLI::Option * hostOpt = nullptr
CLI::Option * portOpt = nullptr
CLI::Option * numericOpt = nullptr
CLI::Option * numericReverseOpt = nullptr
int aiFlags = 0
int aiSockType = 0
int aiProtocol = 0
Additional Inherited Members
Static Public Member Functions inherited from utils::SubCommand
static CLI::App * getHelpTriggerApp ()
static CLI::App * getShowConfigTriggerApp ()
static CLI::App * getCommandlineTriggerApp ()
Static Public Attributes inherited from utils::SubCommand
static std::shared_ptr< CLI::Formatter > sectionFormatter = makeSectionFormatter()
Static Protected Attributes inherited from utils::SubCommand
static std::map< std::string, std::string > aliases
static CLI::App * helpTriggerApp = nullptr
static CLI::App * showConfigTriggerApp = nullptr
static CLI::App * commandlineTriggerApp = nullptr
Detailed Description
template<template< typename SocketAddressT > typename ConfigAddressTypeT>
class net::in::config::ConfigAddress< ConfigAddressTypeT >
Definition at line 86 of file ConfigAddress.h.
Member Typedef Documentation
Super
template<template< typename SocketAddressT > typename ConfigAddressTypeT> using net::in::config::ConfigAddress< ConfigAddressTypeT >::Super = ConfigAddressTypeT<net::in::SocketAddress> private
Definition at line 90 of file ConfigAddress.h.
Constructor & Destructor Documentation
ConfigAddress()
template<template< typename SocketAddress > typename ConfigAddressType> net::in::config::ConfigAddress< ConfigAddressType >::ConfigAddress (net::config::ConfigInstance * instance, const std::string & addressOptionName, const std::string & addressOptionDescription) explicit protected
Definition at line 108 of file ConfigAddress.cpp.
        : ConfigSection(instance, this)
        , ConfigAddressType<net::in::SocketAddress>(this) {
        hostOpt = addOption( //
            "--host",
            "Host name or IPv4 address",
            "hostname|IPv4",
            "0.0.0.0",
            CLI::TypeValidator<std::string>());
        portOpt = addOption( //
            "--port",
            "Port number",
            "port",
            0,
            CLI::Range(std::numeric_limits<uint16_t>::min(), std::numeric_limits<uint16_t>::max()));
        numericOpt = addFlag( //
            "--numeric{true}",
            "Suppress host name lookup",
            "bool",
            XSTR(IN_NUMERIC),
            CLI::IsMember({"true", "false"}));
        numericReverseOpt = addFlag( //
            "--numeric-reverse{true}",
            "Suppress reverse host name lookup",
            "bool",
            XSTR(IN_NUMERIC_REVERSE),
            CLI::IsMember({"true", "false"}));
    }
Member Function Documentation
configurable()
template<template< typename SocketAddressT > typename ConfigAddressTypeT> void net::in::config::ConfigAddress< ConfigAddressTypeT >::configurable (bool configurable = true) final
Definition at line 244 of file ConfigAddress.cpp.
{
        this->setConfigurable(hostOpt, configurable);
        this->setConfigurable(portOpt, configurable);
    }
References hostOpt, and portOpt.
getAiFlags()
template<template< typename SocketAddress > typename ConfigAddressType> int net::in::config::ConfigAddress< ConfigAddressType >::getAiFlags () const protected
Definition at line 257 of file ConfigAddress.cpp.
{
        return aiFlags;
    }
References aiFlags.
getAiProtocol()
template<template< typename SocketAddress > typename ConfigAddressType> int net::in::config::ConfigAddress< ConfigAddressType >::getAiProtocol () const protected
Definition at line 281 of file ConfigAddress.cpp.
{
        return aiProtocol;
    }
References aiProtocol.
getAiSockType()
template<template< typename SocketAddress > typename ConfigAddressType> int net::in::config::ConfigAddress< ConfigAddressType >::getAiSockType () const protected
Definition at line 269 of file ConfigAddress.cpp.
{
        return aiSockType;
    }
References aiSockType.
getHost()
template<template< typename SocketAddress > typename ConfigAddressType> std::string net::in::config::ConfigAddress< ConfigAddressType >::getHost () const
Definition at line 196 of file ConfigAddress.cpp.
{
        return hostOpt->as<std::string>();
    }
References hostOpt.
getNumeric()
template<template< typename SocketAddress > typename ConfigAddressType> bool net::in::config::ConfigAddress< ConfigAddressType >::getNumeric () const
Definition at line 225 of file ConfigAddress.cpp.
{
        return numericOpt->as<bool>();
    }
References numericOpt.
getNumericReverse()
template<template< typename SocketAddress > typename ConfigAddressType> bool net::in::config::ConfigAddress< ConfigAddressType >::getNumericReverse () const
Definition at line 239 of file ConfigAddress.cpp.
{
        return numericReverseOpt->as<bool>();
    }
References numericReverseOpt.
getPort()
template<template< typename SocketAddress > typename ConfigAddressType> uint16_t net::in::config::ConfigAddress< ConfigAddressType >::getPort () const
Definition at line 211 of file ConfigAddress.cpp.
{
        return portOpt->as<uint16_t>();
    }
References portOpt.
getSocketAddress()
template<template< typename SocketAddress > typename ConfigAddressType> SocketAddress net::in::config::ConfigAddress< ConfigAddressType >::getSocketAddress (const SocketAddress::SockAddr & sockAddr, SocketAddress::SockLen sockAddrLen)
Definition at line 161 of file ConfigAddress.cpp.
{
        SocketAddress socketAddress;
        try {
            socketAddress = SocketAddress(sockAddr, sockAddrLen, numericReverseOpt->as<bool>());
        } catch ([[maybe_unused]] const SocketAddress::BadSocketAddress& badSocketAddress) {
            try {
                socketAddress = Super::getSocketAddress(sockAddr, sockAddrLen);
            } catch ([[maybe_unused]] const SocketAddress::BadSocketAddress& badSocketAddress) {
                throw;
            }
        }
        return socketAddress;
    }
References numericReverseOpt, and net::in::SocketAddress::SocketAddress().
init()
template<template< typename SocketAddress > typename ConfigAddressType> SocketAddress * net::in::config::ConfigAddress< ConfigAddressType >::init () final private
Definition at line 143 of file ConfigAddress.cpp.
{
        SocketAddress* socketAddress = new SocketAddress(hostOpt->as<std::string>(), portOpt->as<uint16_t>());
        try {
            socketAddress->init({.aiFlags = (aiFlags & ~AI_NUMERICHOST) | (numericOpt->as<bool>() ? AI_NUMERICHOST : 0),
                                 .aiSockType = aiSockType,
                                 .aiProtocol = aiProtocol});
        } catch ([[maybe_unused]] const core::socket::SocketAddress::BadSocketAddress& badSocketAddress) {
            delete socketAddress;
            socketAddress = nullptr;
            throw;
        }
        return socketAddress;
    }
References hostOpt, net::in::SocketAddress::init(), portOpt, and net::in::SocketAddress::SocketAddress().
setAiFlags()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in::config::ConfigAddress< ConfigAddressType >::setAiFlags (int aiFlags) protected
Definition at line 250 of file ConfigAddress.cpp.
{
        this->aiFlags = aiFlags;
        return *this;
    }
References aiFlags.
Referenced by net::in::stream::config::ConfigSocketServer::ConfigSocketServer().
setAiProtocol()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in::config::ConfigAddress< ConfigAddressType >::setAiProtocol (int aiProtocol) protected
Definition at line 274 of file ConfigAddress.cpp.
{
        this->aiProtocol = aiProtocol;
        return *this;
    }
References aiProtocol.
Referenced by net::in::stream::config::ConfigSocketClient::ConfigSocketClient(), and net::in::stream::config::ConfigSocketServer::ConfigSocketServer().
setAiSockType()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in::config::ConfigAddress< ConfigAddressType >::setAiSockType (int aiSockType) protected
Definition at line 262 of file ConfigAddress.cpp.
{
        this->aiSockType = aiSockType;
        return *this;
    }
References aiSockType.
Referenced by net::in::stream::config::ConfigSocketClient::ConfigSocketClient(), and net::in::stream::config::ConfigSocketServer::ConfigSocketServer().
setHost()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in::config::ConfigAddress< ConfigAddressType >::setHost (const std::string & ipOrHostname)
Definition at line 186 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue(hostOpt, ipOrHostname);
        required(hostOpt, false);
        return *this;
    }
References hostOpt.
Referenced by setSocketAddress().
setHostRequired()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in::config::ConfigAddress< ConfigAddressType >::setHostRequired (bool required = true) protected
Definition at line 286 of file ConfigAddress.cpp.
{
        this->required(hostOpt, required);
        return *this;
    }
References hostOpt.
Referenced by net::in::stream::config::ConfigSocketClient::ConfigSocketClient().
setNumeric()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in::config::ConfigAddress< ConfigAddressType >::setNumeric (bool numeric = true)
Definition at line 216 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue(numericOpt, numeric ? "true" : "false");
        return *this;
    }
References numericOpt.
setNumericReverse()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in::config::ConfigAddress< ConfigAddressType >::setNumericReverse (bool numeric = true)
Definition at line 230 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue(numericReverseOpt, numeric ? "true" : "false");
        return *this;
    }
References numericReverseOpt.
setPort()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in::config::ConfigAddress< ConfigAddressType >::setPort (uint16_t port)
Definition at line 201 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue(portOpt, port);
        required(portOpt, false);
        return *this;
    }
References portOpt.
Referenced by setSocketAddress().
setPortRequired()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in::config::ConfigAddress< ConfigAddressType >::setPortRequired (bool required = true) protected
Definition at line 293 of file ConfigAddress.cpp.
{
        this->required(portOpt, required);
        return *this;
    }
References portOpt.
Referenced by net::in::stream::config::ConfigSocketClient::ConfigSocketClient(), and net::in::stream::config::ConfigSocketServer::ConfigSocketServer().
setSocketAddress()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in::config::ConfigAddress< ConfigAddressType >::setSocketAddress (const SocketAddress & socketAddress)
Definition at line 178 of file ConfigAddress.cpp.
{
        setHost(socketAddress.getHost());
        setPort(socketAddress.getPort());
        return *this;
    }
References net::in::SocketAddress::getHost(), net::in::SocketAddress::getPort(), setHost(), and setPort().
Member Data Documentation
aiFlags
template<template< typename SocketAddressT > typename ConfigAddressTypeT> int net::in::config::ConfigAddress< ConfigAddressTypeT >::aiFlags = 0 private
Definition at line 139 of file ConfigAddress.h.
Referenced by getAiFlags(), and setAiFlags().
aiProtocol
template<template< typename SocketAddressT > typename ConfigAddressTypeT> int net::in::config::ConfigAddress< ConfigAddressTypeT >::aiProtocol = 0 private
Definition at line 141 of file ConfigAddress.h.
Referenced by getAiProtocol(), and setAiProtocol().
aiSockType
template<template< typename SocketAddressT > typename ConfigAddressTypeT> int net::in::config::ConfigAddress< ConfigAddressTypeT >::aiSockType = 0 private
Definition at line 140 of file ConfigAddress.h.
Referenced by getAiSockType(), and setAiSockType().
hostOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::in::config::ConfigAddress< ConfigAddressTypeT >::hostOpt = nullptr private
Definition at line 134 of file ConfigAddress.h.
Referenced by configurable(), getHost(), init(), setHost(), and setHostRequired().
numericOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::in::config::ConfigAddress< ConfigAddressTypeT >::numericOpt = nullptr private
Definition at line 136 of file ConfigAddress.h.
Referenced by getNumeric(), and setNumeric().
numericReverseOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::in::config::ConfigAddress< ConfigAddressTypeT >::numericReverseOpt = nullptr private
Definition at line 137 of file ConfigAddress.h.
Referenced by getNumericReverse(), getSocketAddress(), and setNumericReverse().
portOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::in::config::ConfigAddress< ConfigAddressTypeT >::portOpt = nullptr private
Definition at line 135 of file ConfigAddress.h.
Referenced by configurable(), getPort(), init(), setPort(), and setPortRequired().
The documentation for this class was generated from the following files:
net/in/config/ConfigAddress.h
net/in/config/ConfigAddress.cpp