SNode.C: apps::towercalculator::TowerCalculator Class Reference
apps::towercalculator::TowerCalculator Class Reference
#include <TowerCalculator.h>
Public Member Functions
void * operator new (std::size_t size)=delete
TowerCalculator ()
void calculate (long startValue)
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Types
enum class State { NEXT , MULTIPLY , DIVIDE }
Protected Member Functions
void calculate ()
void onEvent (const utils::Timeval &currentTime) override
Protected Member Functions inherited from core::EventReceiver
virtual ~EventReceiver ()=default
Protected Attributes
long currentValue
std::deque< long > values
int multiplicator = 1
int divisor = 2
State state
Additional Inherited Members
Static Public Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Detailed Description
Definition at line 56 of file TowerCalculator.h.
Member Enumeration Documentation
State
enum class apps::towercalculator::TowerCalculator::State strong protected
Enumerator
NEXT
MULTIPLY
DIVIDE
Definition at line 65 of file TowerCalculator.h.
{ NEXT, MULTIPLY, DIVIDE };
Constructor & Destructor Documentation
TowerCalculator()
apps::towercalculator::TowerCalculator::TowerCalculator ()
Definition at line 53 of file TowerCalculator.cpp.
        : core::EventReceiver("TowerCalculator")
        , currentValue(0)
        , state(State::NEXT) {
    }
References currentValue, NEXT, state, and TowerCalculator().
Referenced by TowerCalculator().
Member Function Documentation
calculate() [1/2]
void apps::towercalculator::TowerCalculator::calculate () protected
Definition at line 65 of file TowerCalculator.cpp.
{
        if (!values.empty() && state == State::NEXT) {
            currentValue = values.front();
            values.pop_front();
            state = State::MULTIPLY;
            multiplicator = 1;
            divisor = 2;
            std::cout << std::endl << "Starting calculation with value = " << currentValue << std::endl;
            span();
        }
    }
References currentValue, divisor, multiplicator, MULTIPLY, core::EventReceiver::span(), and state.
Referenced by calculate(), and onEvent().
calculate() [2/2]
void apps::towercalculator::TowerCalculator::calculate (long startValue)
Definition at line 59 of file TowerCalculator.cpp.
{
        values.push_back(startValue);
        calculate();
    }
References calculate().
Referenced by main().
onEvent()
void apps::towercalculator::TowerCalculator::onEvent (const utils::Timeval & currentTime) override protected virtual
Implements core::EventReceiver.
Definition at line 80 of file TowerCalculator.cpp.
{
        switch (state) {
            case State::MULTIPLY:
                if (multiplicator < 10) {
                    std::cout << currentValue << " * " << multiplicator << " = ";
                    currentValue = currentValue * multiplicator;
                    std::cout << currentValue << std::endl;
                    multiplicator++;
                } else {
                    state = State::DIVIDE;
                }
                span();
                break;
            case State::DIVIDE:
                if (divisor < 10) {
                    std::cout << currentValue << " / " << divisor << " = ";
                    currentValue = currentValue / divisor;
                    std::cout << currentValue << std::endl;
                    divisor++;
                } else {
                    state = State::NEXT;
                }
                span();
                break;
            case State::NEXT:
                calculate();
                break;
        }
    }
References calculate(), currentValue, DIVIDE, divisor, multiplicator, MULTIPLY, NEXT, core::EventReceiver::span(), and state.
operator new()
void * apps::towercalculator::TowerCalculator::operator new (std::size_t size) delete
Member Data Documentation
currentValue
long apps::towercalculator::TowerCalculator::currentValue protected
Definition at line 71 of file TowerCalculator.h.
Referenced by calculate(), onEvent(), and TowerCalculator().
divisor
int apps::towercalculator::TowerCalculator::divisor = 2 protected
Definition at line 76 of file TowerCalculator.h.
Referenced by calculate(), and onEvent().
multiplicator
int apps::towercalculator::TowerCalculator::multiplicator = 1 protected
Definition at line 75 of file TowerCalculator.h.
Referenced by calculate(), and onEvent().
state
State apps::towercalculator::TowerCalculator::state protected
Definition at line 78 of file TowerCalculator.h.
Referenced by calculate(), onEvent(), and TowerCalculator().
values
std::deque<long> apps::towercalculator::TowerCalculator::values protected
Definition at line 73 of file TowerCalculator.h.
The documentation for this class was generated from the following files:
apps/towercalculator/TowerCalculator.h
apps/towercalculator/TowerCalculator.cpp