SNode.C: web::http::client::SocketContext Class Reference
web::http::client::SocketContext Class Reference
#include <SocketContext.h>
Public Member Functions
SocketContext (core::socket::stream::SocketConnection *socketConnection, const std::function< void(const std::shared_ptr< MasterRequest > &)> &onHttpConnected, const std::function< void(const std::shared_ptr< MasterRequest > &)> &onHttpDisconnected, const std::string &hostHeader, bool pipelinedRequests)
~SocketContext () override
Public Member Functions inherited from core::socket::stream::SocketContext
SocketContext (core::socket::stream::SocketConnection *socketConnection)
void sendToPeer (const char *chunk, std::size_t chunkLen) const final
bool streamToPeer (core::pipe::Source *source) const
void streamEof ()
std::size_t readFromPeer (char *chunk, std::size_t chunklen) const final
void setTimeout (const utils::Timeval &timeout) final
void shutdownRead ()
void shutdownWrite (bool forceClose=false)
void close () override
std::size_t getTotalSent () const override
std::size_t getTotalQueued () const override
std::size_t getTotalRead () const override
std::size_t getTotalProcessed () const override
std::string getOnlineSince () const override
std::string getOnlineDuration () const override
SocketConnection * getSocketConnection () const
void sendToPeer (const std::string &data) const
Public Member Functions inherited from core::socket::SocketContext
SocketContext (const SocketContext &)=delete
SocketContext (SocketContext &&)=delete
SocketContext & operator= (const SocketContext &)=delete
SocketContext & operator= (SocketContext &&)=delete
void sendToPeer (const std::string &data) const
Private Types
enum Flags {
NONE = 0b00000000 , HTTP10 = 0b00000001 , HTTP11 = 0b00000010 , KEEPALIVE = 0b00000100 ,
CLOSE = 0b00001000
}
using Super = core::socket::stream::SocketContext
using Response = web::http::client::Response
Private Member Functions
void requestPrepared (const std::shared_ptr< MasterRequest > &request)
void initiateRequest ()
void requestDelivered (bool success)
void responseStarted ()
void deliverResponse (const std::shared_ptr< Response > &response)
void deliverResponseParseError (int status, const std::string &reason)
void requestCompleted (const std::shared_ptr< Response > &response)
void setSseEventReceiver (const std::function< std::size_t()> &onServerSentEvent)
void onConnected () override
std::size_t onReceivedFromPeer () override
void onDisconnected () override
bool onSignal (int signum) override
void onWriteError (int errnum) override
Private Attributes
std::function< void(const std::shared_ptr< MasterRequest > &)> onHttpConnected
std::function< void(const std::shared_ptr< MasterRequest > &)> onHttpDisconnected
std::function< std::size_t()> onServerSentEvent = nullptr
std::list< std::shared_ptr< MasterRequest > > pendingRequests
std::list< std::shared_ptr< MasterRequest > > deliveredRequests
bool pipelinedRequests = false
std::shared_ptr< MasterRequest > masterRequest
ResponseParser parser
int flags = Flags::NONE
bool httpClose = false
Friends
class web::http::client::MasterRequest
Additional Inherited Members
Protected Member Functions inherited from core::socket::stream::SocketContext
void onReadError (int errnum) override
std::size_t readFromPeer ()
Protected Member Functions inherited from core::socket::SocketContext
SocketContext ()=default
Detailed Description
Definition at line 65 of file SocketContext.h.
Member Typedef Documentation
Response
using web::http::client::SocketContext::Response = web::http::client::Response private
Definition at line 68 of file SocketContext.h.
Super
using web::http::client::SocketContext::Super = core::socket::stream::SocketContext private
Definition at line 67 of file SocketContext.h.
Member Enumeration Documentation
Flags
enum web::http::client::SocketContext::Flags private
Enumerator
NONE
HTTP10
HTTP11
KEEPALIVE
CLOSE
Definition at line 110 of file SocketContext.h.
                   { //
            NONE = 0b00000000,
            HTTP10 = 0b00000001,
            HTTP11 = 0b00000010,
            KEEPALIVE = 0b00000100,
            CLOSE = 0b00001000
        };
Constructor & Destructor Documentation
SocketContext()
web::http::client::SocketContext::SocketContext (core::socket::stream::SocketConnection * socketConnection, const std::function< void(const std::shared_ptr< MasterRequest > &)> & onHttpConnected, const std::function< void(const std::shared_ptr< MasterRequest > &)> & onHttpDisconnected, const std::string & hostHeader, bool pipelinedRequests)
Definition at line 63 of file SocketContext.cpp.
        : Super(socketConnection)
        , onHttpConnected(onHttpConnected)
        , onHttpDisconnected(onHttpDisconnected)
        , pipelinedRequests(pipelinedRequests)
        , masterRequest(std::make_shared<MasterRequest>(this, hostHeader))
        , parser(
              this,
              [this]() {
                  responseStarted();
              },
              [this](web::http::client::Response& response) {
                  deliverResponse(std::make_shared<Response>(std::move(response)));
              },
              [this](int status, const std::string& reason) {
                  deliverResponseParseError(status, reason);
              }) {
        masterRequest->setMasterRequest(masterRequest);
    }
References masterRequest, onHttpConnected, onHttpDisconnected, parser, pipelinedRequests, web::http::client::ResponseParser::ResponseParser(), responseStarted(), and core::socket::stream::SocketContext::SocketContext().
Referenced by web::http::client::SocketContextFactory::create().
~SocketContext()
web::http::client::SocketContext::~SocketContext () override virtual
Reimplemented from core::socket::SocketContext.
Definition at line 87 of file SocketContext.cpp.
{
        if (!deliveredRequests.empty()) {
            LOG(DEBUG) << getSocketConnection()->getConnectionName() << " HTTP: Responses missed";
            for (const std::shared_ptr<MasterRequest>& request : deliveredRequests) {
                LOG(DEBUG) << "  " << request->method << " " << request->url << " HTTP/" << request->httpMajor << "." << request->httpMinor;
            }
        }
        if (!pendingRequests.empty()) {
            LOG(DEBUG) << getSocketConnection()->getConnectionName() << " HTTP: Requests ignored";
            for (const std::shared_ptr<MasterRequest>& request : pendingRequests) {
                LOG(DEBUG) << "  " << request->method << " " << request->url << " HTTP/" << request->httpMajor << "." << request->httpMinor;
            }
        }
    }
References deliveredRequests, core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), web::http::client::Request::httpMajor, web::http::client::Request::httpMinor, web::http::client::Request::method, pendingRequests, and web::http::client::Request::url.
Member Function Documentation
deliverResponse()
void web::http::client::SocketContext::deliverResponse (const std::shared_ptr< Response > & response) private
Definition at line 227 of file SocketContext.cpp.
{
        const std::shared_ptr<MasterRequest> request = std::move(deliveredRequests.front());
        deliveredRequests.pop_front();
        const std::string requestLine = std::string(request->method)
                                            .append(" ")
                                            .append(request->url)
                                            .append(" HTTP/")
                                            .append(std::to_string(request->httpMajor))
                                            .append(".")
                                            .append(std::to_string(request->httpMinor));
        LOG(INFO) << getSocketConnection()->getConnectionName() << " HTTP: Response received for request (" << request->count
                  << "): " << requestLine;
        LOG(INFO) << getSocketConnection()->getConnectionName() << "   HTTP/" << response->httpMajor << "." << response->httpMinor << " "
                  << response->statusCode << " " << response->reason;
        request->deliverResponse(request, response);
        LOG(INFO) << getSocketConnection()->getConnectionName() << " HTTP: Request (" << request->count << ") completed: " << requestLine;
        requestCompleted(response);
    }
References web::http::client::Request::count, deliveredRequests, web::http::client::MasterRequest::deliverResponse(), core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), web::http::client::Request::httpMajor, web::http::client::Response::httpMajor, web::http::client::Request::httpMinor, web::http::client::Response::httpMinor, web::http::client::Request::method, web::http::client::Response::reason, requestCompleted(), web::http::client::Response::statusCode, and web::http::client::Request::url.
Referenced by onDisconnected().
deliverResponseParseError()
void web::http::client::SocketContext::deliverResponseParseError (int status, const std::string & reason) private
Definition at line 252 of file SocketContext.cpp.
{
        const std::shared_ptr<MasterRequest> request = std::move(deliveredRequests.front());
        deliveredRequests.pop_front();
        const std::string requestLine = std::string(request->method)
                                            .append(" ")
                                            .append(request->url)
                                            .append(" HTTP/")
                                            .append(std::to_string(request->httpMajor))
                                            .append(".")
                                            .append(std::to_string(request->httpMinor));
        LOG(WARNING) << getSocketConnection()->getConnectionName() << " HTTP: Response parse error: " << reason << " (" << status
                     << ") for request (" << request->count << "): " << requestLine
                     << std::string(request->method)
                            .append(" ")
                            .append(request->url)
                            .append(" HTTP/")
                            .append(std::to_string(request->httpMajor))
                            .append(".")
                            .append(std::to_string(request->httpMinor));
        request->deliverResponseParseError(request, reason);
        shutdownWrite(true);
    }
References web::http::client::Request::count, deliveredRequests, web::http::client::MasterRequest::deliverResponseParseError(), core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), web::http::client::Request::httpMajor, web::http::client::Request::httpMinor, web::http::client::Request::method, core::socket::stream::SocketContext::shutdownWrite(), and web::http::client::Request::url.
initiateRequest()
void web::http::client::SocketContext::initiateRequest () private
Definition at line 146 of file SocketContext.cpp.
{
        if (!pendingRequests.empty()) {
            const std::shared_ptr<MasterRequest>& request = pendingRequests.front();
            const std::string requestLine = std::string(request->method)
                                                .append(" ")
                                                .append(request->url)
                                                .append(" HTTP/")
                                                .append(std::to_string(request->httpMajor))
                                                .append(".")
                                                .append(std::to_string(request->httpMinor));
            LOG(DEBUG) << getSocketConnection()->getConnectionName() << " HTTP: Request (" << request->count << ") start: " << requestLine;
            if (!request->initiate(request)) {
                LOG(WARNING) << getSocketConnection()->getConnectionName() << " HTTP: Request (" << request->count
                             << ") delivering failed: " << requestLine;
                core::EventReceiver::atNextTick([this, masterRequest = static_cast<std::weak_ptr<Request>>(masterRequest)]() {
                    pendingRequests.pop_front();
                    if (!masterRequest.expired() && !pendingRequests.empty()) {
                        const std::shared_ptr<Request>& request = pendingRequests.front();
                        LOG(DEBUG) << getSocketConnection()->getConnectionName() << " HTTP: Request (" << request->count
                                   << ") dequeued: " << request->method << " " << request->url << " HTTP/" << request->httpMajor << "."
                                   << request->httpMinor;
                        initiateRequest();
                    }
                });
            }
        }
    }
References core::EventReceiver::atNextTick(), web::http::client::Request::count, core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), web::http::client::Request::httpMajor, web::http::client::Request::httpMinor, web::http::client::MasterRequest::initiate(), initiateRequest(), masterRequest, web::http::client::Request::method, pendingRequests, and web::http::client::Request::url.
Referenced by initiateRequest(), requestCompleted(), requestDelivered(), and requestPrepared().
onConnected()
void web::http::client::SocketContext::onConnected () override private virtual
Implements core::socket::stream::SocketContext.
Definition at line 313 of file SocketContext.cpp.
{
        LOG(INFO) << getSocketConnection()->getConnectionName() << " HTTP: Connected";
        onHttpConnected(masterRequest);
    }
References core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), masterRequest, and onHttpConnected.
onDisconnected()
void web::http::client::SocketContext::onDisconnected () override private virtual
Implements core::socket::stream::SocketContext.
Definition at line 333 of file SocketContext.cpp.
{
        while (!deliveredRequests.empty()) {
            const std::shared_ptr<Response> response(new Response());
            response->httpVersion = "HTTP/1.1";
            response->httpMajor = 1;
            response->httpMinor = 1;
            response->statusCode = "0";
            response->reason = "Connection loss";
            deliverResponse(response);
        }
        onHttpDisconnected(masterRequest);
        LOG(INFO) << getSocketConnection()->getConnectionName() << " HTTP: Received disconnect";
    }
References deliveredRequests, deliverResponse(), core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), web::http::client::Response::httpMajor, web::http::client::Response::httpMinor, web::http::client::Response::httpVersion, masterRequest, onHttpDisconnected, web::http::client::Response::reason, web::http::client::Response::Response(), and web::http::client::Response::statusCode.
onReceivedFromPeer()
std::size_t web::http::client::SocketContext::onReceivedFromPeer () override private virtual
Implements core::socket::SocketContext.
Definition at line 319 of file SocketContext.cpp.
{
        std::size_t consumed = 0;
        if (!httpClose && (!deliveredRequests.empty() || onServerSentEvent)) {
            if (!onServerSentEvent) {
                consumed = parser.parse();
            } else if (onServerSentEvent) {
                consumed = onServerSentEvent();
            }
        }
        return consumed;
    }
References deliveredRequests, httpClose, onServerSentEvent, web::http::Parser::parse(), and parser.
onSignal()
bool web::http::client::SocketContext::onSignal (int signum) override private virtual
Implements core::socket::SocketContext.
Definition at line 350 of file SocketContext.cpp.
{
        LOG(INFO) << getSocketConnection()->getConnectionName() << " HTTP: Received signal " << signum;
        return true;
    }
References core::socket::stream::SocketConnection::getConnectionName(), and core::socket::stream::SocketContext::getSocketConnection().
onWriteError()
void web::http::client::SocketContext::onWriteError (int errnum) override private virtual
Reimplemented from core::socket::stream::SocketContext.
Definition at line 356 of file SocketContext.cpp.
{
        // Do nothing in case of an write error
    }
requestCompleted()
void web::http::client::SocketContext::requestCompleted (const std::shared_ptr< Response > & response) private
Definition at line 279 of file SocketContext.cpp.
{
        httpClose = response->connectionState == ConnectionState::Close ||
                    (response->connectionState == ConnectionState::Default &&
                     ((response->httpMajor == 0 && response->httpMinor == 0) || (response->httpMajor == 1 && response->httpMinor == 0)));
        if (httpClose) {
            LOG(DEBUG) << getSocketConnection()->getConnectionName() << " HTTP: Connection = Close";
            shutdownWrite();
        } else {
            LOG(DEBUG) << getSocketConnection()->getConnectionName() << " HTTP: Connection = Keep-Alive";
            if (!pipelinedRequests && !pendingRequests.empty()) {
                core::EventReceiver::atNextTick([this, masterRequest = static_cast<std::weak_ptr<Request>>(masterRequest)]() {
                    if (!masterRequest.expired()) {
                        const std::shared_ptr<Request>& request = pendingRequests.front();
                        LOG(DEBUG) << getSocketConnection()->getConnectionName() << " HTTP: Initiating request (" << request->count
                                   << "): " << request->method << " " << request->url << " HTTP/" << request->httpMajor << "."
                                   << request->httpMinor;
                        initiateRequest();
                    }
                });
            }
        }
    }
References core::EventReceiver::atNextTick(), web::http::Close, web::http::client::Response::connectionState, web::http::client::Request::count, web::http::Default, core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), httpClose, web::http::client::Request::httpMajor, web::http::client::Response::httpMajor, web::http::client::Request::httpMinor, web::http::client::Response::httpMinor, initiateRequest(), masterRequest, web::http::client::Request::method, pendingRequests, pipelinedRequests, core::socket::stream::SocketContext::shutdownWrite(), and web::http::client::Request::url.
Referenced by deliverResponse().
requestDelivered()
void web::http::client::SocketContext::requestDelivered (bool success) private
Definition at line 180 of file SocketContext.cpp.
{
        const std::shared_ptr<MasterRequest> currentRequest = std::move(pendingRequests.front());
        pendingRequests.pop_front();
        const std::string requestLine = std::string(currentRequest->method)
                                            .append(" ")
                                            .append(currentRequest->url)
                                            .append(" HTTP/")
                                            .append(std::to_string(currentRequest->httpMajor))
                                            .append(".")
                                            .append(std::to_string(currentRequest->httpMinor));
        if (success) {
            LOG(DEBUG) << getSocketConnection()->getConnectionName() << " HTTP: Request (" << currentRequest->count
                       << ") delivered: " << requestLine << " " << pendingRequests.size();
            deliveredRequests.push_back(currentRequest);
            if (pipelinedRequests && !pendingRequests.empty()) {
                core::EventReceiver::atNextTick([this, masterRequest = static_cast<std::weak_ptr<Request>>(masterRequest)]() {
                    if (!masterRequest.expired()) {
                        const std::shared_ptr<Request>& request = pendingRequests.front();
                        LOG(DEBUG) << getSocketConnection()->getConnectionName() << " HTTP: Request (" << request->count
                                   << ") dequeued: " << request->method << " " << request->url << " HTTP/" << request->httpMajor << "."
                                   << request->httpMinor;
                        initiateRequest();
                    }
                });
            }
        } else {
            LOG(WARNING) << getSocketConnection()->getConnectionName() << " HTTP: Request (" << currentRequest->count
                         << ") deliver failed: " << requestLine;
            shutdownWrite();
        }
    }
References core::EventReceiver::atNextTick(), web::http::client::Request::count, deliveredRequests, core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), web::http::client::Request::httpMajor, web::http::client::Request::httpMinor, initiateRequest(), masterRequest, web::http::client::Request::method, pendingRequests, pipelinedRequests, core::socket::stream::SocketContext::shutdownWrite(), and web::http::client::Request::url.
Referenced by web::http::client::MasterRequest::requestDelivered().
requestPrepared()
void web::http::client::SocketContext::requestPrepared (const std::shared_ptr< MasterRequest > & request) private
Definition at line 103 of file SocketContext.cpp.
{
        const std::string requestLine = std::string(request->method)
                                            .append(" ")
                                            .append(request->url)
                                            .append(" HTTP/")
                                            .append(std::to_string(request->httpMajor))
                                            .append(".")
                                            .append(std::to_string(request->httpMinor));
        if ((flags == Flags::NONE || (flags & Flags::HTTP11) == Flags::HTTP11 || (flags & Flags::KEEPALIVE) == Flags::KEEPALIVE) &&
            (flags & Flags::CLOSE) != Flags::CLOSE) {
            LOG(INFO) << getSocketConnection()->getConnectionName() << " HTTP: Request (" << request->count
                      << ") accepted: " << requestLine;
            flags = (flags & Flags::HTTP11) | ((request->httpMajor == 1 && request->httpMinor == 1) ? Flags::HTTP11 : Flags::NONE);
            flags = (flags & Flags::HTTP10) | ((request->httpMajor == 1 && request->httpMinor == 0) ? Flags::HTTP10 : Flags::NONE);
            flags = (flags & Flags::KEEPALIVE) |
                    (web::http::ciContains(request->header("Connection"), "keep-alive") ? Flags::KEEPALIVE : Flags::NONE);
            flags = (flags & Flags::CLOSE) | (web::http::ciContains(request->header("Connection"), "close") ? Flags::CLOSE : Flags::NONE);
            pendingRequests.push_back(request);
            LOG(DEBUG) << getSocketConnection()->getConnectionName() << " HTTP: Request (" << request->count << ") queued: " << requestLine
                       << " - QueueSize = " << pendingRequests.size() << " - Flags: " << flags << " - "
                       << web::http::ciContains(request->header("Connection"), "close");
            if (pendingRequests.size() == 1) {
                initiateRequest();
            }
        } else {
            LOG(WARNING) << getSocketConnection()->getConnectionName() << " HTTP: Request (" << request->count
                         << ") rejected: " << requestLine;
            LOG(WARNING) << httputils::toString(request->method,
                                                request->url,
                                                "HTTP/" + std::to_string(request->httpMajor) + "." + std::to_string(request->httpMinor),
                                                request->getQueries(),
                                                request->getHeaders(),
                                                request->getTrailer(),
                                                request->getCookies(),
                                                {});
        }
    }
References web::http::ciContains(), CLOSE, web::http::client::Request::count, flags, core::socket::stream::SocketConnection::getConnectionName(), web::http::client::Request::getCookies(), web::http::client::Request::getHeaders(), web::http::client::Request::getQueries(), core::socket::stream::SocketContext::getSocketConnection(), web::http::client::Request::getTrailer(), web::http::client::Request::header(), HTTP10, HTTP11, web::http::client::Request::httpMajor, web::http::client::Request::httpMinor, initiateRequest(), KEEPALIVE, web::http::client::Request::method, NONE, pendingRequests, httputils::toString(), and web::http::client::Request::url.
Referenced by web::http::client::MasterRequest::requestPrepared().
responseStarted()
void web::http::client::SocketContext::responseStarted () private
Definition at line 219 of file SocketContext.cpp.
{
        if (deliveredRequests.empty()) {
            LOG(ERROR) << getSocketConnection()->getConnectionName() << " HTTP: Response without delivered request";
            shutdownWrite(true);
        }
    }
References deliveredRequests, core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), and core::socket::stream::SocketContext::shutdownWrite().
Referenced by SocketContext().
setSseEventReceiver()
void web::http::client::SocketContext::setSseEventReceiver (const std::function< std::size_t()> & onServerSentEvent) private
Definition at line 307 of file SocketContext.cpp.
{
        this->onServerSentEvent = onServerSentEvent;
        getSocketConnection()->setWriteTimeout(0);
    }
References core::socket::stream::SocketContext::getSocketConnection(), onServerSentEvent, and core::socket::stream::SocketConnection::setWriteTimeout().
Referenced by web::http::client::MasterRequest::requestEventSource().
Friends And Related Symbol Documentation
web::http::client::MasterRequest
friend class web::http::client::MasterRequest friend
Definition at line 121 of file SocketContext.h.
Member Data Documentation
deliveredRequests
std::list<std::shared_ptr<MasterRequest> > web::http::client::SocketContext::deliveredRequests private
Definition at line 102 of file SocketContext.h.
Referenced by deliverResponse(), deliverResponseParseError(), onDisconnected(), onReceivedFromPeer(), requestDelivered(), responseStarted(), and ~SocketContext().
flags
int web::http::client::SocketContext::flags = Flags::NONE private
Definition at line 117 of file SocketContext.h.
Referenced by requestPrepared().
httpClose
bool web::http::client::SocketContext::httpClose = false private
Definition at line 119 of file SocketContext.h.
Referenced by onReceivedFromPeer(), and requestCompleted().
masterRequest
std::shared_ptr<MasterRequest> web::http::client::SocketContext::masterRequest private
Definition at line 106 of file SocketContext.h.
Referenced by initiateRequest(), onConnected(), onDisconnected(), requestCompleted(), requestDelivered(), and SocketContext().
onHttpConnected
std::function<void(const std::shared_ptr<MasterRequest>&)> web::http::client::SocketContext::onHttpConnected private
Definition at line 90 of file SocketContext.h.
Referenced by onConnected(), and SocketContext().
onHttpDisconnected
std::function<void(const std::shared_ptr<MasterRequest>&)> web::http::client::SocketContext::onHttpDisconnected private
Definition at line 91 of file SocketContext.h.
Referenced by onDisconnected(), and SocketContext().
onServerSentEvent
std::function<std::size_t()> web::http::client::SocketContext::onServerSentEvent = nullptr private
Definition at line 99 of file SocketContext.h.
Referenced by onReceivedFromPeer(), and setSseEventReceiver().
parser
ResponseParser web::http::client::SocketContext::parser private
Definition at line 108 of file SocketContext.h.
Referenced by onReceivedFromPeer(), and SocketContext().
pendingRequests
std::list<std::shared_ptr<MasterRequest> > web::http::client::SocketContext::pendingRequests private
Definition at line 101 of file SocketContext.h.
Referenced by initiateRequest(), requestCompleted(), requestDelivered(), requestPrepared(), and ~SocketContext().
pipelinedRequests
bool web::http::client::SocketContext::pipelinedRequests = false private
Definition at line 104 of file SocketContext.h.
Referenced by requestCompleted(), requestDelivered(), and SocketContext().
The documentation for this class was generated from the following files:
web/http/client/SocketContext.h
web/http/client/SocketContext.cpp