SNode.C: iot::mqtt::types::String Class Reference
iot::mqtt::types::String Class Reference
#include <String.h>
Public Member Functions
String ()
String (const std::string &value)
String (const String &)=default
String (String &&) noexcept=default
~String () override
String & operator= (const String &)=default
String & operator= (String &&) noexcept=default
std::size_t deserialize (iot::mqtt::MqttContext *mqttContext) override
std::vector< char > serialize () const override
String & operator= (const std::string &newValue)
operator std::string () const
bool operator== (const std::string &rhsValue) const
bool operator!= (const std::string &rhsValue) const
void reset (std::size_t size=0) override
Public Member Functions inherited from iot::mqtt::types::TypeBase< std::string >
TypeBase (std::size_t size=sizeof(ValueType))
TypeBase (const TypeBase &)=default
TypeBase (TypeBase &&) noexcept=default
virtual ~TypeBase ()=default
TypeBase & operator= (const TypeBase &)=default
TypeBase & operator= (TypeBase &&) noexcept=default
void setSize (std::size_t size)
std::size_t size ()
bool isComplete () const
Private Attributes
UInt16 stringLength
Additional Inherited Members
Protected Types inherited from iot::mqtt::types::TypeBase< std::string >
using ValueType = std::string
Protected Attributes inherited from iot::mqtt::types::TypeBase< std::string >
std::vector< char > value
std::size_t length
std::size_t needed
bool complete
int state
Detailed Description
Definition at line 57 of file String.h.
Constructor & Destructor Documentation
String() [1/4]
iot::mqtt::types::String::String ()
Definition at line 55 of file String.cpp.
        : TypeBase(0) {
    }
References iot::mqtt::types::TypeBase< ValueTypeT >::TypeBase().
String() [2/4]
iot::mqtt::types::String::String (const std::string & value) explicit
Definition at line 59 of file String.cpp.
{
        this->value = std::vector<char>(value.begin(), value.end());
        stringLength = static_cast<uint16_t>(value.size());
    }
References iot::mqtt::types::UInt16::operator=(), and stringLength.
Referenced by iot::mqtt::types::StringPair::StringPair().
String() [3/4]
iot::mqtt::types::String::String (const String &) default
String() [4/4]
iot::mqtt::types::String::String (String &&) default noexcept
~String()
iot::mqtt::types::String::~String () override
Definition at line 64 of file String.cpp.
                    {
    }
Member Function Documentation
deserialize()
std::size_t iot::mqtt::types::String::deserialize (iot::mqtt::MqttContext * mqttContext) override virtual
Reimplemented from iot::mqtt::types::TypeBase< std::string >.
Definition at line 67 of file String.cpp.
{
        std::size_t consumed = 0;
        switch (state) {
            case 0:
                consumed = stringLength.deserialize(mqttContext);
                if (!stringLength.isComplete()) {
                    break;
                }
                setSize(stringLength);
                state++;
                [[fallthrough]];
            case 1:
                consumed += TypeBase::deserialize(mqttContext);
                break;
        }
        // MUST close
        // Check for UTF-16 (U+D800 - U+DFFF) surrogates
        // Check for U+0000 in string
        // MAY close
        // Check for U+0001 - U+001F
        // Check for U+007F - U+009F
        // Check for non-characters
        return consumed;
    }
References iot::mqtt::types::TypeBase< ValueTypeT >::deserialize(), iot::mqtt::types::TypeBase< ValueTypeT >::isComplete(), iot::mqtt::types::TypeBase< ValueTypeT >::setSize(), and stringLength.
Referenced by iot::mqtt::types::StringPair::deserialize(), iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::server::packets::Connect::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), iot::mqtt::server::packets::Subscribe::deserializeVP(), and iot::mqtt::server::packets::Unsubscribe::deserializeVP().
operator std::string()
iot::mqtt::types::String::operator std::string () const
Definition at line 111 of file String.cpp.
{
        return std::string(value.begin(), value.end());
    }
operator!=()
bool iot::mqtt::types::String::operator!= (const std::string & rhsValue) const
Definition at line 119 of file String.cpp.
{
        return static_cast<std::string>(*this) != rhsValue;
    }
operator=() [1/3]
String & iot::mqtt::types::String::operator= (const std::string & newValue)
Definition at line 104 of file String.cpp.
{
        value = std::vector<char>(newValue.begin(), newValue.end());
        stringLength = static_cast<uint16_t>(value.size());
        return *this;
    }
References iot::mqtt::types::UInt16::operator=(), and stringLength.
Referenced by iot::mqtt::packets::Connect::Connect(), iot::mqtt::server::packets::Connect::deserializeVP(), iot::mqtt::packets::Publish::Publish(), iot::mqtt::packets::Subscribe::serializeVP(), and iot::mqtt::packets::Unsubscribe::serializeVP().
operator=() [2/3]
String & iot::mqtt::types::String::operator= (const String &) default
operator=() [3/3]
String & iot::mqtt::types::String::operator= (String &&) default noexcept
operator==()
bool iot::mqtt::types::String::operator== (const std::string & rhsValue) const
Definition at line 115 of file String.cpp.
{
        return static_cast<std::string>(*this) == rhsValue;
    }
reset()
void iot::mqtt::types::String::reset (std::size_t size = 0) override virtual
Reimplemented from iot::mqtt::types::TypeBase< std::string >.
Definition at line 123 of file String.cpp.
{
        stringLength.reset();
        TypeBase::reset(0);
        state = 0;
    }
References iot::mqtt::types::TypeBase< ValueTypeT >::reset(), and stringLength.
Referenced by iot::mqtt::server::packets::Subscribe::deserializeVP(), iot::mqtt::server::packets::Unsubscribe::deserializeVP(), and iot::mqtt::types::StringPair::reset().
serialize()
std::vector< char > iot::mqtt::types::String::serialize () const override virtual
Reimplemented from iot::mqtt::types::TypeBase< std::string >.
Definition at line 97 of file String.cpp.
{
        std::vector<char> returnVector = stringLength.serialize();
        returnVector.insert(returnVector.end(), value.begin(), value.end());
        return returnVector;
    }
References iot::mqtt::types::TypeBase< ValueTypeT >::serialize(), and stringLength.
Referenced by iot::mqtt::types::StringPair::serialize(), iot::mqtt::packets::Connect::serializeVP(), iot::mqtt::packets::Publish::serializeVP(), iot::mqtt::packets::Subscribe::serializeVP(), and iot::mqtt::packets::Unsubscribe::serializeVP().
Member Data Documentation
stringLength
UInt16 iot::mqtt::types::String::stringLength private
Definition at line 81 of file String.h.
Referenced by deserialize(), operator=(), reset(), serialize(), and String().
The documentation for this class was generated from the following files:
iot/mqtt/types/String.h
iot/mqtt/types/String.cpp