SNode.C: core::EventReceiver Class Reference
core::EventReceiver Class Reference abstract
#include <EventReceiver.h>
Public Member Functions
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
virtual void onEvent (const utils::Timeval &currentTime)=0
const std::string & getName () const
Static Public Member Functions
static void atNextTick (const std::function< void(void)> &callBack)
Protected Member Functions
virtual ~EventReceiver ()=default
Private Attributes
Event event
Detailed Description
Definition at line 61 of file EventReceiver.h.
Constructor & Destructor Documentation
EventReceiver() [1/3]
core::EventReceiver::EventReceiver (const std::string & name)
Definition at line 71 of file EventReceiver.cpp.
        : event(this, name) {
    }
References core::Event::Event(), and event.
Referenced by atNextTick(), core::DescriptorEventReceiver::DescriptorEventReceiver(), core::file::FileReader::FileReader(), iot::mqtt::OnReceivedFromPeerEvent::OnReceivedFromPeerEvent(), core::TimerEventReceiver::TimerEventReceiver(), and apps::towercalculator::TowerCalculator::TowerCalculator().
EventReceiver() [2/3]
core::EventReceiver::EventReceiver (EventReceiver &) delete
EventReceiver() [3/3]
core::EventReceiver::EventReceiver (EventReceiver &&) delete
~EventReceiver()
virtual core::EventReceiver::~EventReceiver () protected virtual default
Member Function Documentation
atNextTick()
void core::EventReceiver::atNextTick (const std::function< void(void)> & callBack) static
Definition at line 50 of file EventReceiver.cpp.
{
        class NextTickEvent : public core::EventReceiver {
        public:
            explicit NextTickEvent(const std::function<void(void)>& callBack)
                : core::EventReceiver("RequestEvent")
                , callBack(callBack) {
            }
            void onEvent([[maybe_unused]] const utils::Timeval& currentTime) override {
                callBack();
                delete this;
            }
        private:
            std::function<void(void)> callBack;
        };
        (new NextTickEvent(callBack))->span();
    }
References EventReceiver(), and span().
Referenced by web::http::client::SocketContext::initiateRequest(), web::http::client::SocketContext::requestCompleted(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestDelivered(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), and core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector().
destruct()
void core::EventReceiver::destruct () virtual
Reimplemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, and database::mariadb::MariaDBCommandStartEvent.
Definition at line 75 of file EventReceiver.cpp.
{
        delete this;
    }
Referenced by core::EventMultiplexer::EventQueue::clear().
getName()
const std::string & core::EventReceiver::getName () const
Definition at line 87 of file EventReceiver.cpp.
{
        return event.getName();
    }
References event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::socket::stream::SocketWriter::doWrite(), core::DescriptorEventReceiver::enable(), core::socket::stream::tls::SocketReader::read(), core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::SocketWriter::shutdownWrite(), core::socket::stream::SocketWriter::streamEof(), core::socket::stream::SocketWriter::streamToPeer(), core::DescriptorEventReceiver::suspend(), and core::socket::stream::tls::SocketWriter::write().
onEvent()
virtual void core::EventReceiver::onEvent (const utils::Timeval & currentTime) pure virtual
Implemented in apps::towercalculator::TowerCalculator, core::DescriptorEventReceiver, core::file::FileReader, core::TimerEventReceiver, database::mariadb::MariaDBCommandStartEvent, and iot::mqtt::OnReceivedFromPeerEvent.
Referenced by core::Event::dispatch().
operator=() [1/2]
EventReceiver & core::EventReceiver::operator= (EventReceiver &&) delete
operator=() [2/2]
EventReceiver & core::EventReceiver::operator= (EventReceiver &) delete
relax()
void core::EventReceiver::relax ()
Definition at line 83 of file EventReceiver.cpp.
{
        event.relax();
    }
References event, and core::Event::relax().
span()
void core::EventReceiver::span ()
Definition at line 79 of file EventReceiver.cpp.
{
        event.span();
    }
References event, and core::Event::span().
Referenced by atNextTick(), apps::towercalculator::TowerCalculator::calculate(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), apps::towercalculator::TowerCalculator::onEvent(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::multiplexer::epoll::DescriptorEventPublisher::spanActiveEvents(), core::multiplexer::poll::DescriptorEventPublisher::spanActiveEvents(), core::multiplexer::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), core::file::FileReader::start(), core::file::FileReader::stop(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
Member Data Documentation
event
Event core::EventReceiver::event private
Definition at line 87 of file EventReceiver.h.
Referenced by EventReceiver(), getName(), relax(), and span().
The documentation for this class was generated from the following files:
core/EventReceiver.h
core/EventReceiver.cpp