SNode.C: iot::mqtt::SubProtocol< WSSubProtocolRoleT > Class Template Reference
iot::mqtt::SubProtocol< WSSubProtocolRoleT > Class Template Reference
#include <SubProtocol.h>
Public Member Functions
SubProtocol (web::websocket::SubProtocolContext *subProtocolContext, const std::string &name, iot::mqtt::Mqtt *mqtt)
~SubProtocol () override=default
std::size_t recv (char *chunk, std::size_t chunklen) override
void send (const char *chunk, std::size_t chunklen) override
void end (bool fatal=false) override
void close () override
Private Types
using WSSubProtocolRole = WSSubProtocolRoleT
Private Member Functions
void onConnected () override
void onMessageStart (int opCode) override
void onMessageData (const char *chunk, std::size_t chunkLen) override
void onMessageEnd () override
void onMessageError (uint16_t errnum) override
void onDisconnected () override
bool onSignal (int sig) override
core::socket::stream::SocketConnection * getSocketConnection () const override
Private Member Functions inherited from iot::mqtt::MqttContext
MqttContext (Mqtt *mqtt)
MqttContext (const MqttContext &)=default
MqttContext & operator= (const MqttContext &)=default
virtual ~MqttContext ()
void onConnected ()
std::size_t onReceivedFromPeer ()
void onDisconnected ()
bool onSignal (int sig)
Private Attributes
OnReceivedFromPeerEvent onReceivedFromPeerEvent
std::string data
std::vector< char > buffer
std::size_t cursor = 0
std::size_t size = 0
Private Attributes inherited from iot::mqtt::MqttContext
Mqtt * mqtt
Detailed Description
template<typename WSSubProtocolRoleT>
class iot::mqtt::SubProtocol< WSSubProtocolRoleT >
Definition at line 83 of file SubProtocol.h.
Member Typedef Documentation
WSSubProtocolRole
template<typename WSSubProtocolRoleT > using iot::mqtt::SubProtocol< WSSubProtocolRoleT >::WSSubProtocolRole = WSSubProtocolRoleT private
Definition at line 87 of file SubProtocol.h.
Constructor & Destructor Documentation
SubProtocol()
template<typename WSSubProtocolRole > iot::mqtt::SubProtocol< WSSubProtocolRole >::SubProtocol (web::websocket::SubProtocolContext * subProtocolContext, const std::string & name, iot::mqtt::Mqtt * mqtt)
Definition at line 59 of file SubProtocol.hpp.
        : WSSubProtocolRole(subProtocolContext, name, 0)
        , iot::mqtt::MqttContext(mqtt)
        , onReceivedFromPeerEvent([this]([[maybe_unused]] const utils::Timeval& currentTime) {
            iot::mqtt::MqttContext::onReceivedFromPeer();
            if (size > 0) {
                onReceivedFromPeerEvent.span();
            } else {
                buffer.clear();
                cursor = 0;
            }
        }) {
    }
References iot::mqtt::SubProtocol< WSSubProtocolRoleT >::buffer, iot::mqtt::SubProtocol< WSSubProtocolRoleT >::cursor, iot::mqtt::MqttContext::onReceivedFromPeer(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onReceivedFromPeerEvent, iot::mqtt::SubProtocol< WSSubProtocolRoleT >::size, and core::EventReceiver::span().
~SubProtocol()
template<typename WSSubProtocolRoleT > iot::mqtt::SubProtocol< WSSubProtocolRoleT >::~SubProtocol () override default
Member Function Documentation
close()
template<typename WSSubProtocolRole > void iot::mqtt::SubProtocol< WSSubProtocolRole >::close () override virtual
Implements iot::mqtt::MqttContext.
Definition at line 99 of file SubProtocol.hpp.
{
        WSSubProtocolRole::sendClose();
    }
end()
template<typename WSSubProtocolRole > void iot::mqtt::SubProtocol< WSSubProtocolRole >::end (bool fatal = false) override virtual
Implements iot::mqtt::MqttContext.
Definition at line 94 of file SubProtocol.hpp.
{
        WSSubProtocolRole::sendClose();
    }
Referenced by iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageStart().
getSocketConnection()
template<typename WSSubProtocolRole > core::socket::stream::SocketConnection * iot::mqtt::SubProtocol< WSSubProtocolRole >::getSocketConnection () const override private virtual
Implements iot::mqtt::MqttContext.
Definition at line 166 of file SubProtocol.hpp.
{
        return WSSubProtocolRole::subProtocolContext->getSocketConnection();
    }
Referenced by iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onConnected(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onDisconnected(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageData(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageError(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageStart(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onSignal().
onConnected()
template<typename WSSubProtocolRole > void iot::mqtt::SubProtocol< WSSubProtocolRole >::onConnected () override private
Definition at line 104 of file SubProtocol.hpp.
{
        LOG(INFO) << getSocketConnection()->getConnectionName() << " WsMqtt: connected:";
        iot::mqtt::MqttContext::onConnected();
    }
References iot::mqtt::SubProtocol< WSSubProtocolRoleT >::getSocketConnection(), and iot::mqtt::MqttContext::onConnected().
onDisconnected()
template<typename WSSubProtocolRole > void iot::mqtt::SubProtocol< WSSubProtocolRole >::onDisconnected () override private
Definition at line 149 of file SubProtocol.hpp.
{
        iot::mqtt::MqttContext::onDisconnected();
        LOG(DEBUG) << getSocketConnection()->getConnectionName() << " WsMqtt: disconnected";
    }
References iot::mqtt::SubProtocol< WSSubProtocolRoleT >::getSocketConnection(), and iot::mqtt::MqttContext::onDisconnected().
onMessageData()
template<typename WSSubProtocolRole > void iot::mqtt::SubProtocol< WSSubProtocolRole >::onMessageData (const char * chunk, std::size_t chunkLen) override private
Definition at line 120 of file SubProtocol.hpp.
{
        data.append(std::string(chunk, chunkLen));
        LOG(DEBUG) << getSocketConnection()->getConnectionName() << " WsMqtt: Frame Data:\n"
                   << std::string(32, ' ').append(utils::hexDump(std::vector<char>(chunk, chunk + chunkLen), 32));
    }
References iot::mqtt::SubProtocol< WSSubProtocolRoleT >::data, iot::mqtt::SubProtocol< WSSubProtocolRoleT >::getSocketConnection(), and utils::hexDump().
onMessageEnd()
template<typename WSSubProtocolRole > void iot::mqtt::SubProtocol< WSSubProtocolRole >::onMessageEnd () override private
Definition at line 128 of file SubProtocol.hpp.
{
        LOG(DEBUG) << getSocketConnection()->getConnectionName() << " WsMqtt: Message END";
        buffer.insert(buffer.end(), data.begin(), data.end());
        size += data.size();
        data.clear();
        if (size > 0) {
            onReceivedFromPeerEvent.span();
        } else {
            buffer.clear();
            cursor = 0;
        }
    }
References iot::mqtt::SubProtocol< WSSubProtocolRoleT >::buffer, iot::mqtt::SubProtocol< WSSubProtocolRoleT >::cursor, iot::mqtt::SubProtocol< WSSubProtocolRoleT >::data, iot::mqtt::SubProtocol< WSSubProtocolRoleT >::getSocketConnection(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onReceivedFromPeerEvent, iot::mqtt::SubProtocol< WSSubProtocolRoleT >::size, and core::EventReceiver::span().
onMessageError()
template<typename WSSubProtocolRole > void iot::mqtt::SubProtocol< WSSubProtocolRole >::onMessageError (uint16_t errnum) override private
Definition at line 144 of file SubProtocol.hpp.
{
        LOG(ERROR) << getSocketConnection()->getConnectionName() << " WsMqtt: Message error: " << errnum;
    }
References iot::mqtt::SubProtocol< WSSubProtocolRoleT >::getSocketConnection().
onMessageStart()
template<typename WSSubProtocolRole > void iot::mqtt::SubProtocol< WSSubProtocolRole >::onMessageStart (int opCode) override private
Definition at line 110 of file SubProtocol.hpp.
{
        if (opCode == web::websocket::SubProtocolContext::OpCode::TEXT) {
            LOG(ERROR) << getSocketConnection()->getConnectionName() << " WsMqtt: Wrong Opcode: " << opCode << " (TEXT)";
            this->end(true);
        } else {
            LOG(DEBUG) << getSocketConnection()->getConnectionName() << " WsMqtt: Message START: " << opCode << " (BIN)";
        }
    }
References iot::mqtt::SubProtocol< WSSubProtocolRoleT >::end(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::getSocketConnection(), and web::websocket::SubProtocolContext::TEXT.
onSignal()
template<typename WSSubProtocolRole > bool iot::mqtt::SubProtocol< WSSubProtocolRole >::onSignal (int sig) override private
Definition at line 155 of file SubProtocol.hpp.
{
        bool ret = iot::mqtt::MqttContext::onSignal(sig);
        LOG(INFO) << getSocketConnection()->getConnectionName() << " WsMqtt: exit due to '" << strsignal(sig) << "' (SIG"
                  << utils::system::sigabbrev_np(sig) << " = " << sig << ")";
        this->sendClose();
        return ret;
    }
References iot::mqtt::SubProtocol< WSSubProtocolRoleT >::getSocketConnection(), iot::mqtt::MqttContext::onSignal(), and utils::system::sigabbrev_np().
recv()
template<typename WSSubProtocolRole > std::size_t iot::mqtt::SubProtocol< WSSubProtocolRole >::recv (char * chunk, std::size_t chunklen) override virtual
Implements iot::mqtt::MqttContext.
Definition at line 77 of file SubProtocol.hpp.
{
        std::size_t maxReturn = std::min(chunklen, size);
        std::copy(buffer.data() + cursor, buffer.data() + cursor + maxReturn, chunk);
        cursor += maxReturn;
        size -= maxReturn;
        return maxReturn;
    }
References iot::mqtt::SubProtocol< WSSubProtocolRoleT >::buffer, iot::mqtt::SubProtocol< WSSubProtocolRoleT >::cursor, and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::size.
send()
template<typename WSSubProtocolRole > void iot::mqtt::SubProtocol< WSSubProtocolRole >::send (const char * chunk, std::size_t chunklen) override virtual
Implements iot::mqtt::MqttContext.
Definition at line 89 of file SubProtocol.hpp.
{
        WSSubProtocolRole::sendMessage(chunk, chunklen);
    }
Member Data Documentation
buffer
template<typename WSSubProtocolRoleT > std::vector<char> iot::mqtt::SubProtocol< WSSubProtocolRoleT >::buffer private
Definition at line 113 of file SubProtocol.h.
Referenced by iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::recv(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
cursor
template<typename WSSubProtocolRoleT > std::size_t iot::mqtt::SubProtocol< WSSubProtocolRoleT >::cursor = 0 private
Definition at line 114 of file SubProtocol.h.
Referenced by iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::recv(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
data
template<typename WSSubProtocolRoleT > std::string iot::mqtt::SubProtocol< WSSubProtocolRoleT >::data private
Definition at line 112 of file SubProtocol.h.
Referenced by iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageData(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd().
onReceivedFromPeerEvent
template<typename WSSubProtocolRoleT > OnReceivedFromPeerEvent iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onReceivedFromPeerEvent private
Definition at line 110 of file SubProtocol.h.
Referenced by iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
size
template<typename WSSubProtocolRoleT > std::size_t iot::mqtt::SubProtocol< WSSubProtocolRoleT >::size = 0 private
Definition at line 115 of file SubProtocol.h.
Referenced by iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::recv(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
The documentation for this class was generated from the following files:
iot/mqtt/SubProtocol.h
iot/mqtt/SubProtocol.hpp