SNode.C: iot::mqtt::server::packets::Subscribe Class Reference
iot::mqtt::server::packets::Subscribe Class Reference
#include <Subscribe.h>
Public Member Functions
Subscribe (uint32_t remainingLength, uint8_t flags)
uint16_t getPacketIdentifier () const
const std::list< iot::mqtt::Topic > & getTopics () const
std::vector< char > serialize () const
const std::string & getName () const
uint8_t getType () const
uint8_t getFlags () const
std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
uint32_t getRemainingLength () const
bool isComplete () const
bool isError () const
std::size_t getConsumed () const
Protected Attributes
iot::mqtt::types::UInt16 packetIdentifier
iot::mqtt::types::String topic
iot::mqtt::types::UInt8 qoS
std::list< iot::mqtt::Topic > topics
uint8_t flags = 0
bool complete = false
bool error = false
uint32_t remainingLength = 0
std::size_t consumed = 0
Private Member Functions
std::size_t deserializeVP (iot::mqtt::MqttContext *mqttContext) override
void deliverPacket (iot::mqtt::server::Mqtt *mqtt) override
std::vector< char > serializeVP () const override
Private Attributes
int state = 0
std::string name
uint8_t type = 0
Detailed Description
Definition at line 38 of file Subscribe.h.
Constructor & Destructor Documentation
Subscribe()
iot::mqtt::server::packets::Subscribe::Subscribe (uint32_t remainingLength, uint8_t flags)
Definition at line 29 of file Subscribe.cpp.
        : iot::mqtt::server::ControlPacketDeserializer(remainingLength, flags, MQTT_SUBSCRIBE_FLAGS) {
        this->flags = flags;
    }
References iot::mqtt::ControlPacket::flags.
Referenced by iot::mqtt::server::Mqtt::createControlPacketDeserializer().
Member Function Documentation
deliverPacket()
void iot::mqtt::server::packets::Subscribe::deliverPacket (iot::mqtt::server::Mqtt * mqtt) override private virtual
Implements iot::mqtt::server::ControlPacketDeserializer.
Definition at line 79 of file Subscribe.cpp.
{
        mqtt->printVP(*this);
        mqtt->_onSubscribe(*this);
    }
References iot::mqtt::server::Mqtt::_onSubscribe(), and iot::mqtt::Mqtt::printVP().
deserialize()
std::size_t iot::mqtt::ControlPacketDeserializer::deserialize (iot::mqtt::MqttContext * mqttContext) inherited
Definition at line 35 of file ControlPacketDeserializer.cpp.
{
        std::size_t currentConsumed = deserializeVP(mqttContext);
        consumed += currentConsumed;
        error = (complete && consumed != this->getRemainingLength()) || (!complete && consumed >= this->getRemainingLength());
        return currentConsumed;
    }
References iot::mqtt::ControlPacketDeserializer::complete, iot::mqtt::ControlPacketDeserializer::consumed, iot::mqtt::ControlPacketDeserializer::deserializeVP(), iot::mqtt::ControlPacketDeserializer::error, and iot::mqtt::ControlPacketDeserializer::getRemainingLength().
deserializeVP()
std::size_t iot::mqtt::server::packets::Subscribe::deserializeVP (iot::mqtt::MqttContext * mqttContext) override private virtual
Implements iot::mqtt::ControlPacketDeserializer.
Definition at line 34 of file Subscribe.cpp.
{
        std::size_t consumed = 0;
        switch (state) {
            case 0: // V-Header
                consumed += packetIdentifier.deserialize(mqttContext);
                if (!packetIdentifier.isComplete()) {
                    break;
                }
                state++;
                [[fallthrough]];
            case 1: // Payload
                consumed += topic.deserialize(mqttContext);
                if (!topic.isComplete()) {
                    break;
                }
                state++;
                [[fallthrough]];
            case 2:
                consumed += qoS.deserialize(mqttContext);
                if (!qoS.isComplete()) {
                    break;
                } else {
                    topics.push_back(Topic(topic, qoS));
                    topic.reset();
                    qoS.reset();
                    if (getConsumed() + consumed < this->getRemainingLength()) {
                        state = 1;
                        break;
                    }
                }
                complete = true;
                break;
        }
        return consumed;
    }
References iot::mqtt::ControlPacketDeserializer::complete, iot::mqtt::types::TypeBase< ValueTypeT >::deserialize(), iot::mqtt::types::String::deserialize(), iot::mqtt::ControlPacketDeserializer::getConsumed(), iot::mqtt::ControlPacketDeserializer::getRemainingLength(), iot::mqtt::types::TypeBase< ValueTypeT >::isComplete(), iot::mqtt::packets::Subscribe::packetIdentifier, iot::mqtt::packets::Subscribe::qoS, iot::mqtt::types::TypeBase< ValueTypeT >::reset(), iot::mqtt::types::String::reset(), state, iot::mqtt::packets::Subscribe::topic, iot::mqtt::Topic::Topic(), and iot::mqtt::packets::Subscribe::topics.
getConsumed()
std::size_t iot::mqtt::ControlPacketDeserializer::getConsumed () const inherited
Definition at line 56 of file ControlPacketDeserializer.cpp.
{
        return consumed;
    }
References iot::mqtt::ControlPacketDeserializer::consumed.
Referenced by iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::client::packets::Suback::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), deserializeVP(), and iot::mqtt::server::packets::Unsubscribe::deserializeVP().
getFlags()
uint8_t iot::mqtt::ControlPacket::getFlags () const inherited
Definition at line 100 of file ControlPacket.cpp.
{
        return flags;
    }
References iot::mqtt::ControlPacket::flags.
getName()
const std::string & iot::mqtt::ControlPacket::getName () const inherited
Definition at line 81 of file ControlPacket.cpp.
{
        return name;
    }
References iot::mqtt::ControlPacket::name.
Referenced by iot::mqtt::Mqtt::printVP(), and iot::mqtt::Mqtt::send().
getPacketIdentifier()
uint16_t iot::mqtt::packets::Subscribe::getPacketIdentifier () const inherited
Definition at line 56 of file Subscribe.cpp.
{
        return packetIdentifier;
    }
References iot::mqtt::packets::Subscribe::packetIdentifier.
Referenced by iot::mqtt::server::Mqtt::_onSubscribe().
getRemainingLength()
uint32_t iot::mqtt::ControlPacketDeserializer::getRemainingLength () const inherited
Definition at line 44 of file ControlPacketDeserializer.cpp.
{
        return remainingLength;
    }
References iot::mqtt::ControlPacketDeserializer::remainingLength.
Referenced by iot::mqtt::ControlPacketDeserializer::deserialize(), iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::client::packets::Suback::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), deserializeVP(), and iot::mqtt::server::packets::Unsubscribe::deserializeVP().
getTopics()
const std::list< Topic > & iot::mqtt::packets::Subscribe::getTopics () const inherited
Definition at line 60 of file Subscribe.cpp.
{
        return topics;
    }
References iot::mqtt::packets::Subscribe::topics.
Referenced by iot::mqtt::server::Mqtt::_onSubscribe().
getType()
uint8_t iot::mqtt::ControlPacket::getType () const inherited
Definition at line 96 of file ControlPacket.cpp.
{
        return type;
    }
References iot::mqtt::ControlPacket::type.
isComplete()
bool iot::mqtt::ControlPacketDeserializer::isComplete () const inherited
Definition at line 48 of file ControlPacketDeserializer.cpp.
{
        return complete;
    }
References iot::mqtt::ControlPacketDeserializer::complete.
isError()
bool iot::mqtt::ControlPacketDeserializer::isError () const inherited
Definition at line 52 of file ControlPacketDeserializer.cpp.
{
        return error;
    }
References iot::mqtt::ControlPacketDeserializer::error.
serialize()
std::vector< char > iot::mqtt::ControlPacket::serialize () const inherited
Definition at line 85 of file ControlPacket.cpp.
{
        std::vector<char> variablHeaderPayload = serializeVP();
        iot::mqtt::FixedHeader fixedHeader(type, flags, static_cast<uint32_t>(variablHeaderPayload.size()));
        std::vector<char> packet = fixedHeader.serialize();
        packet.insert(packet.end(), variablHeaderPayload.begin(), variablHeaderPayload.end());
        return packet;
    }
References iot::mqtt::FixedHeader::FixedHeader(), iot::mqtt::ControlPacket::flags, iot::mqtt::FixedHeader::serialize(), iot::mqtt::ControlPacket::serializeVP(), and iot::mqtt::ControlPacket::type.
Referenced by iot::mqtt::Mqtt::printVP(), and iot::mqtt::Mqtt::send().
serializeVP()
std::vector< char > iot::mqtt::packets::Subscribe::serializeVP () const override private virtual inherited
Implements iot::mqtt::ControlPacket.
Definition at line 40 of file Subscribe.cpp.
{
        std::vector<char> packet(packetIdentifier.serialize());
        for (const Topic& topic : topics) {
            iot::mqtt::types::String topicString;
            topicString = topic.getName();
            std::vector<char> tmpPacket = topicString.serialize();
            packet.insert(packet.end(), tmpPacket.begin(), tmpPacket.end());
            packet.push_back(static_cast<char>(topic.getQoS()));
        }
        return packet;
    }
References iot::mqtt::Topic::getName(), iot::mqtt::Topic::getQoS(), iot::mqtt::types::String::operator=(), iot::mqtt::packets::Subscribe::packetIdentifier, iot::mqtt::types::TypeBase< ValueTypeT >::serialize(), iot::mqtt::types::String::serialize(), and iot::mqtt::packets::Subscribe::topics.
Member Data Documentation
complete
bool iot::mqtt::ControlPacketDeserializer::complete = false protected inherited
Definition at line 59 of file ControlPacketDeserializer.h.
Referenced by iot::mqtt::ControlPacketDeserializer::deserialize(), iot::mqtt::client::packets::Connack::deserializeVP(), iot::mqtt::client::packets::Pingresp::deserializeVP(), iot::mqtt::client::packets::Puback::deserializeVP(), iot::mqtt::client::packets::Pubcomp::deserializeVP(), iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::client::packets::Pubrec::deserializeVP(), iot::mqtt::client::packets::Pubrel::deserializeVP(), iot::mqtt::client::packets::Suback::deserializeVP(), iot::mqtt::client::packets::Unsuback::deserializeVP(), iot::mqtt::server::packets::Connect::deserializeVP(), iot::mqtt::server::packets::Disconnect::deserializeVP(), iot::mqtt::server::packets::Puback::deserializeVP(), iot::mqtt::server::packets::Pubcomp::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), iot::mqtt::server::packets::Pubrec::deserializeVP(), iot::mqtt::server::packets::Pubrel::deserializeVP(), deserializeVP(), iot::mqtt::server::packets::Unsubscribe::deserializeVP(), iot::mqtt::server::packets::Pingreq::deserializeVP(), and iot::mqtt::ControlPacketDeserializer::isComplete().
consumed
std::size_t iot::mqtt::ControlPacketDeserializer::consumed = 0 protected inherited
Definition at line 64 of file ControlPacketDeserializer.h.
Referenced by iot::mqtt::ControlPacketDeserializer::deserialize(), and iot::mqtt::ControlPacketDeserializer::getConsumed().
error
bool iot::mqtt::ControlPacketDeserializer::error = false protected inherited
Definition at line 60 of file ControlPacketDeserializer.h.
Referenced by iot::mqtt::ControlPacketDeserializer::ControlPacketDeserializer(), iot::mqtt::ControlPacketDeserializer::deserialize(), iot::mqtt::ControlPacketDeserializer::isError(), iot::mqtt::client::packets::Publish::Publish(), and iot::mqtt::server::packets::Publish::Publish().
flags
uint8_t iot::mqtt::ControlPacket::flags = 0 protected inherited
Definition at line 86 of file ControlPacket.h.
Referenced by iot::mqtt::client::packets::Connack::Connack(), iot::mqtt::server::packets::Connect::Connect(), iot::mqtt::ControlPacket::ControlPacket(), iot::mqtt::server::packets::Disconnect::Disconnect(), iot::mqtt::ControlPacket::getFlags(), iot::mqtt::server::packets::Pingreq::Pingreq(), iot::mqtt::client::packets::Pingresp::Pingresp(), iot::mqtt::client::packets::Puback::Puback(), iot::mqtt::server::packets::Puback::Puback(), iot::mqtt::client::packets::Pubcomp::Pubcomp(), iot::mqtt::server::packets::Pubcomp::Pubcomp(), iot::mqtt::packets::Publish::Publish(), iot::mqtt::client::packets::Publish::Publish(), iot::mqtt::server::packets::Publish::Publish(), iot::mqtt::client::packets::Pubrec::Pubrec(), iot::mqtt::server::packets::Pubrec::Pubrec(), iot::mqtt::client::packets::Pubrel::Pubrel(), iot::mqtt::server::packets::Pubrel::Pubrel(), iot::mqtt::ControlPacket::serialize(), iot::mqtt::client::packets::Suback::Suback(), Subscribe(), iot::mqtt::client::packets::Unsuback::Unsuback(), and iot::mqtt::server::packets::Unsubscribe::Unsubscribe().
name
std::string iot::mqtt::ControlPacket::name private inherited
Definition at line 82 of file ControlPacket.h.
Referenced by iot::mqtt::ControlPacket::ControlPacket(), and iot::mqtt::ControlPacket::getName().
packetIdentifier
iot::mqtt::types::UInt16 iot::mqtt::packets::Subscribe::packetIdentifier protected inherited
Definition at line 49 of file Subscribe.h.
Referenced by deserializeVP(), iot::mqtt::packets::Subscribe::getPacketIdentifier(), iot::mqtt::packets::Subscribe::serializeVP(), and iot::mqtt::packets::Subscribe::Subscribe().
qoS
iot::mqtt::types::UInt8 iot::mqtt::packets::Subscribe::qoS protected inherited
Definition at line 51 of file Subscribe.h.
Referenced by deserializeVP().
remainingLength
uint32_t iot::mqtt::ControlPacketDeserializer::remainingLength = 0 protected inherited
Definition at line 62 of file ControlPacketDeserializer.h.
Referenced by iot::mqtt::ControlPacketDeserializer::ControlPacketDeserializer(), and iot::mqtt::ControlPacketDeserializer::getRemainingLength().
state
int iot::mqtt::server::packets::Subscribe::state = 0 private
Definition at line 49 of file Subscribe.h.
Referenced by deserializeVP().
topic
iot::mqtt::types::String iot::mqtt::packets::Subscribe::topic protected inherited
Definition at line 50 of file Subscribe.h.
Referenced by deserializeVP().
topics
std::list<iot::mqtt::Topic> iot::mqtt::packets::Subscribe::topics protected inherited
Definition at line 53 of file Subscribe.h.
Referenced by deserializeVP(), iot::mqtt::packets::Subscribe::getTopics(), iot::mqtt::packets::Subscribe::serializeVP(), and iot::mqtt::packets::Subscribe::Subscribe().
type
uint8_t iot::mqtt::ControlPacket::type = 0 private inherited
Definition at line 83 of file ControlPacket.h.
Referenced by iot::mqtt::ControlPacket::ControlPacket(), iot::mqtt::ControlPacket::getType(), and iot::mqtt::ControlPacket::serialize().
The documentation for this class was generated from the following files:
iot/mqtt/server/packets/Subscribe.h
iot/mqtt/server/packets/Subscribe.cpp