SNode.C: net::in::SocketAddress Class Reference
net::in::SocketAddress Class Reference final
#include <SocketAddress.h>
Public Types
using SockAddr = sockaddr_in
Public Member Functions
SocketAddress ()
SocketAddress (const std::string &ipOrHostname)
SocketAddress (const std::string &ipOrHostname, uint16_t port)
SocketAddress (uint16_t port)
SocketAddress (const SocketAddress::SockAddr &sockAddr, socklen_t sockAddrLen)
SocketAddress & init ()
SocketAddress & setHost (const std::string &ipOrHostname)
std::string getHost () const
SocketAddress & setPort (uint16_t port)
uint16_t getPort () const
SocketAddress & setAiSockType (int aiSocktype)
int getAiSockType () const
SocketAddress & setAiProtocol (int aiProtocol)
int getAiProtocol () const
SocketAddress & setAiFlags (int aiFlags)
int getAiFlags () const
std::string getAddress () const override
std::string toString () const override
bool useNext () override
virtual const sockaddr & getSockAddr ()
virtual const socklen_t & getSockAddrLen () const
Protected Attributes
SockAddr sockAddr
socklen_t sockAddrLen
Private Types
using Super = net::SocketAddress< sockaddr_in >
Private Attributes
std::shared_ptr< SocketAddrInfo > socketAddrInfo
int aiFlags = 0
int aiSocktype = 0
int aiProtocol = 0
std::string host = ""
uint16_t port = 0
Detailed Description
Definition at line 41 of file SocketAddress.h.
Member Typedef Documentation
SockAddr
using net::SocketAddress< sockaddr_in >::SockAddr = sockaddr_in inherited
Definition at line 36 of file SocketAddress.h.
Super
using net::in::SocketAddress::Super = net::SocketAddress<sockaddr_in> private
Definition at line 43 of file SocketAddress.h.
Constructor & Destructor Documentation
SocketAddress() [1/5]
net::in::SocketAddress::SocketAddress ()
Definition at line 38 of file SocketAddress.cpp.
        : socketAddrInfo(std::make_shared<SocketAddrInfo>()) {
        sockAddr.sin_family = AF_INET;
    }
References socketAddrInfo.
Referenced by SocketAddress(), SocketAddress(), and SocketAddress().
SocketAddress() [2/5]
net::in::SocketAddress::SocketAddress (const std::string & ipOrHostname) explicit
Definition at line 43 of file SocketAddress.cpp.
        : SocketAddress() {
        setHost(ipOrHostname);
    }
References setHost(), and SocketAddress().
SocketAddress() [3/5]
net::in::SocketAddress::SocketAddress (const std::string & ipOrHostname, uint16_t port)
Definition at line 48 of file SocketAddress.cpp.
        : SocketAddress() {
        setHost(ipOrHostname);
        setPort(port);
    }
References setHost(), setPort(), and SocketAddress().
Referenced by net::in::config::ConfigAddress< ConfigAddressTypeT >::init().
SocketAddress() [4/5]
net::in::SocketAddress::SocketAddress (uint16_t port) explicit
Definition at line 54 of file SocketAddress.cpp.
        : SocketAddress() {
        setPort(port);
    }
References setPort(), and SocketAddress().
SocketAddress() [5/5]
net::in::SocketAddress::SocketAddress (const SocketAddress::SockAddr & sockAddr, socklen_t sockAddrLen)
Member Function Documentation
getAddress()
std::string net::in::SocketAddress::getAddress () const override virtual
Implements core::socket::SocketAddress.
Definition at line 167 of file SocketAddress.cpp.
{
        utils::PreserveErrno preserveErrno;
        char ip[NI_MAXHOST];
        std::memset(ip, 0, NI_MAXHOST);
        int ret = core::system::getnameinfo(
            reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), ip, NI_MAXHOST, nullptr, 0, NI_NUMERICHOST);
        return ret >= 0 ? ip : gai_strerror(ret);
    }
getAiFlags()
int net::in::SocketAddress::getAiFlags () const
Definition at line 163 of file SocketAddress.cpp.
{
        return aiFlags;
    }
References aiFlags.
getAiProtocol()
int net::in::SocketAddress::getAiProtocol () const
Definition at line 153 of file SocketAddress.cpp.
{
        return aiProtocol;
    }
References aiProtocol.
getAiSockType()
int net::in::SocketAddress::getAiSockType () const
Definition at line 143 of file SocketAddress.cpp.
{
        return aiSocktype;
    }
References aiSocktype.
getHost()
std::string net::in::SocketAddress::getHost () const
Definition at line 124 of file SocketAddress.cpp.
{
        return host;
    }
References host.
Referenced by net::in::config::ConfigAddress< ConfigAddressTypeT >::setSocketAddress(), and toString().
getPort()
uint16_t net::in::SocketAddress::getPort () const
Definition at line 133 of file SocketAddress.cpp.
{
        return port;
    }
References port.
Referenced by net::in::config::ConfigAddress< ConfigAddressTypeT >::setSocketAddress(), and toString().
getSockAddr()
const sockaddr & net::SocketAddress< SockAddr >::getSockAddr () virtual inherited
Definition at line 46 of file SocketAddress.hpp.
{
        return reinterpret_cast<const sockaddr&>(sockAddr);
    }
getSockAddrLen()
const socklen_t & net::SocketAddress< SockAddr >::getSockAddrLen () const virtual inherited
Definition at line 47 of file SocketAddress.hpp.
{
        return sockAddrLen;
    }
init()
SocketAddress & net::in::SocketAddress::init ()
Definition at line 87 of file SocketAddress.cpp.
{
        addrinfo hints{};
        hints.ai_family = AF_INET;
        hints.ai_socktype = aiSocktype;
        hints.ai_protocol = aiProtocol;
        hints.ai_flags = aiFlags | AI_ADDRCONFIG | AI_ALL;
        int aiErrCode = 0;
        if ((aiErrCode = socketAddrInfo->init(host, std::to_string(port), hints)) == 0) {
            sockAddr = *reinterpret_cast<const SockAddr*>(socketAddrInfo->getSockAddr());
        } else {
            core::socket::State state = core::socket::STATE_OK;
            switch (aiErrCode) {
                case EAI_AGAIN:
                case EAI_MEMORY:
                    state = core::socket::STATE_ERROR;
                    break;
                default:
                    state = core::socket::STATE_FATAL;
                    break;
            }
            throw core::socket::SocketAddress::BadSocketAddress(state,
                                                                host + ": " +
                                                                    (aiErrCode == EAI_SYSTEM ? strerror(errno) : gai_strerror(aiErrCode)),
                                                                (aiErrCode == EAI_SYSTEM ? errno : aiErrCode));
        }
        return *this;
    }
References aiProtocol, aiSocktype, net::in::SocketAddrInfo::getSockAddr(), host, port, and socketAddrInfo.
Referenced by net::in::config::ConfigAddress< ConfigAddressTypeT >::init().
setAiFlags()
SocketAddress & net::in::SocketAddress::setAiFlags (int aiFlags)
Definition at line 157 of file SocketAddress.cpp.
{
        this->aiFlags = aiFlags;
        return *this;
    }
References aiFlags.
Referenced by net::in::config::ConfigAddress< ConfigAddressTypeT >::init().
setAiProtocol()
SocketAddress & net::in::SocketAddress::setAiProtocol (int aiProtocol)
Definition at line 147 of file SocketAddress.cpp.
{
        this->aiProtocol = aiProtocol;
        return *this;
    }
References aiProtocol.
Referenced by net::in::config::ConfigAddress< ConfigAddressTypeT >::init().
setAiSockType()
SocketAddress & net::in::SocketAddress::setAiSockType (int aiSocktype)
Definition at line 137 of file SocketAddress.cpp.
{
        this->aiSocktype = aiSocktype;
        return *this;
    }
References aiSocktype.
Referenced by net::in::config::ConfigAddress< ConfigAddressTypeT >::init().
setHost()
SocketAddress & net::in::SocketAddress::setHost (const std::string & ipOrHostname)
Definition at line 119 of file SocketAddress.cpp.
{
        this->host = ipOrHostname;
        return *this;
    }
References host.
Referenced by SocketAddress(), and SocketAddress().
setPort()
SocketAddress & net::in::SocketAddress::setPort (uint16_t port)
Definition at line 128 of file SocketAddress.cpp.
{
        this->port = port;
        return *this;
    }
References port.
Referenced by SocketAddress(), and SocketAddress().
toString()
std::string net::in::SocketAddress::toString () const override virtual
Implements core::socket::SocketAddress.
Definition at line 179 of file SocketAddress.cpp.
{
        return getHost() + ":" + std::to_string(getPort());
    }
References getHost(), and getPort().
useNext()
bool net::in::SocketAddress::useNext () override virtual
Reimplemented from core::socket::SocketAddress.
Definition at line 183 of file SocketAddress.cpp.
{
        bool useNext = socketAddrInfo->useNext();
        if (useNext) {
            sockAddr = *reinterpret_cast<const SockAddr*>(socketAddrInfo->getSockAddr());
        }
        return useNext;
    }
References net::in::SocketAddrInfo::getSockAddr(), socketAddrInfo, and net::in::SocketAddrInfo::useNext().
Member Data Documentation
aiFlags
int net::in::SocketAddress::aiFlags = 0 private
Definition at line 79 of file SocketAddress.h.
Referenced by getAiFlags(), and setAiFlags().
aiProtocol
int net::in::SocketAddress::aiProtocol = 0 private
Definition at line 81 of file SocketAddress.h.
Referenced by getAiProtocol(), init(), and setAiProtocol().
aiSocktype
int net::in::SocketAddress::aiSocktype = 0 private
Definition at line 80 of file SocketAddress.h.
Referenced by getAiSockType(), init(), and setAiSockType().
host
std::string net::in::SocketAddress::host = "" private
Definition at line 83 of file SocketAddress.h.
Referenced by getHost(), init(), setHost(), and net::SocketAddress< SockAddrT >::SocketAddress().
port
uint16_t net::in::SocketAddress::port = 0 private
Definition at line 84 of file SocketAddress.h.
Referenced by getPort(), init(), setPort(), and net::SocketAddress< SockAddrT >::SocketAddress().
sockAddr
SockAddr net::SocketAddress< sockaddr_in >::sockAddr protected inherited
Definition at line 50 of file SocketAddress.h.
{0};
sockAddrLen
socklen_t net::SocketAddress< sockaddr_in >::sockAddrLen protected inherited
Definition at line 51 of file SocketAddress.h.
socketAddrInfo
std::shared_ptr<SocketAddrInfo> net::in::SocketAddress::socketAddrInfo private
Definition at line 78 of file SocketAddress.h.
Referenced by init(), SocketAddress(), net::SocketAddress< SockAddrT >::SocketAddress(), and useNext().
The documentation for this class was generated from the following files:
net/in/SocketAddress.h
net/in/SocketAddress.cpp