SNode.C: web::http::SocketContextUpgradeFactory< RequestT, ResponseT > Class Template Reference
web::http::SocketContextUpgradeFactory< RequestT, ResponseT > Class Template Reference abstract
#include <SocketContextUpgradeFactory.h>
Public Types
using Request = RequestT
using Response = ResponseT
Public Member Functions
virtual std::string name ()=0
void prepare (Request &request, Response &response)
void incRefCount ()
void decRefCount ()
virtual void checkRefCount ()=0
Protected Member Functions
SocketContextUpgradeFactory ()=default
~SocketContextUpgradeFactory () override=default
Protected Member Functions inherited from core::socket::stream::SocketContextFactory
SocketContextFactory ()=default
virtual ~SocketContextFactory ()
Protected Attributes
std::size_t refCount = 0
Private Member Functions
virtual SocketContextUpgrade< Request, Response > * create (core::socket::stream::SocketConnection *socketConnection, Request *request, Response *response)=0
core::socket::stream::SocketContext * create (core::socket::stream::SocketConnection *socketConnection) final
Private Attributes
Request * request = nullptr
Response * response = nullptr
Detailed Description
template<typename RequestT, typename ResponseT>
class web::http::SocketContextUpgradeFactory< RequestT, ResponseT >
Definition at line 45 of file SocketContextUpgradeFactory.h.
Member Typedef Documentation
Request
template<typename RequestT , typename ResponseT > using web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::Request = RequestT
Definition at line 47 of file SocketContextUpgradeFactory.h.
Response
template<typename RequestT , typename ResponseT > using web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::Response = ResponseT
Definition at line 48 of file SocketContextUpgradeFactory.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactory()
template<typename RequestT , typename ResponseT > web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::SocketContextUpgradeFactory () protected default
Referenced by web::http::client::SocketContextUpgradeFactory::SocketContextUpgradeFactory(), and web::http::server::SocketContextUpgradeFactory::SocketContextUpgradeFactory().
~SocketContextUpgradeFactory()
template<typename RequestT , typename ResponseT > web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::~SocketContextUpgradeFactory () override protected default
Member Function Documentation
checkRefCount()
template<typename RequestT , typename ResponseT > virtual void web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::checkRefCount () pure virtual
Implemented in web::http::client::SocketContextUpgradeFactory, and web::http::server::SocketContextUpgradeFactory.
Referenced by web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::create(), and web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::decRefCount().
create() [1/2]
template<typename Request , typename Response > core::socket::stream::SocketContext * web::http::SocketContextUpgradeFactory< Request, Response >::create (core::socket::stream::SocketConnection * socketConnection) final private virtual
Implements core::socket::stream::SocketContextFactory.
Definition at line 36 of file SocketContextUpgradeFactory.hpp.
{
        SocketContextUpgrade<Request, Response>* socketContext = create(socketConnection, request, response);
        checkRefCount();
        return socketContext;
    }
References web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::checkRefCount(), web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::request, and web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::response.
create() [2/2]
template<typename RequestT , typename ResponseT > virtual SocketContextUpgrade< Request, Response > * web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::create (core::socket::stream::SocketConnection * socketConnection, Request * request, Response * response) private pure virtual
Implemented in web::websocket::client::SocketContextUpgradeFactory, and web::websocket::server::SocketContextUpgradeFactory.
decRefCount()
template<typename Request , typename Response > void web::http::SocketContextUpgradeFactory< Request, Response >::decRefCount ()
Definition at line 50 of file SocketContextUpgradeFactory.hpp.
{
        --refCount;
        checkRefCount();
    }
References web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::checkRefCount(), and web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::refCount.
incRefCount()
template<typename Request , typename Response > void web::http::SocketContextUpgradeFactory< Request, Response >::incRefCount ()
Definition at line 45 of file SocketContextUpgradeFactory.hpp.
{
        ++refCount;
    }
References web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::refCount.
name()
template<typename RequestT , typename ResponseT > virtual std::string web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::name () pure virtual
Implemented in web::websocket::client::SocketContextUpgradeFactory, and web::websocket::server::SocketContextUpgradeFactory.
prepare()
template<typename Request , typename Response > void web::http::SocketContextUpgradeFactory< Request, Response >::prepare (Request & request, Response & response)
Definition at line 29 of file SocketContextUpgradeFactory.hpp.
{
        this->request = &request;
        this->response = &response;
    }
Referenced by web::http::client::SocketContextUpgradeFactorySelector::select(), and web::http::server::SocketContextUpgradeFactorySelector::select().
Member Data Documentation
refCount
template<typename RequestT , typename ResponseT > std::size_t web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::refCount = 0 protected
Definition at line 66 of file SocketContextUpgradeFactory.h.
Referenced by web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::decRefCount(), and web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::incRefCount().
request
template<typename RequestT , typename ResponseT > Request* web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::request = nullptr private
Definition at line 69 of file SocketContextUpgradeFactory.h.
Referenced by web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::create().
response
template<typename RequestT , typename ResponseT > Response* web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::response = nullptr private
Definition at line 70 of file SocketContextUpgradeFactory.h.
Referenced by web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::create().
The documentation for this class was generated from the following files:
web/http/SocketContextUpgradeFactory.h
web/http/SocketContextUpgradeFactory.hpp