SNode.C: net::config::stream::ConfigSocketClient< ConfigAddressLocalT, ConfigAddressRemoteT > Class Template Reference
net::config::stream::ConfigSocketClient< ConfigAddressLocalT, ConfigAddressRemoteT > Class Template Reference
#include <ConfigSocketClient.h>
Public Types
using Remote = ConfigAddressRemoteT< net::config::ConfigAddressRemote >
using Local = ConfigAddressLocalT< net::config::ConfigAddressLocal >
Public Member Functions
ConfigSocketClient (net::config::ConfigInstance *instance)
utils::Timeval getReadTimeout () const
ConfigConnection & setReadTimeout (const utils::Timeval &newReadTimeoutSet)
utils::Timeval getWriteTimeout () const
ConfigConnection & setWriteTimeout (const utils::Timeval &newWriteTimeoutSet)
std::size_t getReadBlockSize () const
ConfigConnection & setReadBlockSize (std::size_t newReadBlockSize)
std::size_t getWriteBlockSize () const
ConfigConnection & setWriteBlockSize (std::size_t newWriteBlockSize)
utils::Timeval getTerminateTimeout () const
ConfigConnection & setTerminateTimeout (const utils::Timeval &newTerminateTimeout)
ConfigPhysicalSocketClient & setReconnect (bool reconnect=true)
bool getReconnect () const
ConfigPhysicalSocketClient & setReconnectTime (double time)
double getReconnectTime () const
ConfigPhysicalSocketClient & setConnectTimeout (const utils::Timeval &connectTimeout)
utils::Timeval getConnectTimeout () const
const std::map< int, const net::phy::PhysicalSocketOption > & getSocketOptions ()
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, int optValue)
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, const std::string &optValue)
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, const std::vector< char > &optValue)
ConfigPhysicalSocket & removeSocketOption (int optName)
ConfigPhysicalSocket & setReuseAddress (bool reuseAddress=true)
bool getReuseAddress () const
ConfigPhysicalSocket & setRetry (bool retry=true)
bool getRetry () const
ConfigPhysicalSocket & setRetryOnFatal (bool retry=true)
bool getRetryOnFatal () const
ConfigPhysicalSocket & setRetryTimeout (double sec)
double getRetryTimeout () const
ConfigPhysicalSocket & setRetryTries (unsigned int tries=0)
unsigned int getRetryTries () const
ConfigPhysicalSocket & setRetryBase (double base)
double getRetryBase () const
ConfigPhysicalSocket & setRetryLimit (unsigned int limit)
unsigned int getRetryLimit () const
ConfigPhysicalSocket & setRetryJitter (double percent)
double getRetryJitter () const
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
Protected Member Functions
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
CLI::Option * add_socket_option (CLI::Option *&opt, const std::string &name, int optLevel, int optName, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Protected Attributes
CLI::App * section = nullptr
CLI::Option * reuseAddressOpt = nullptr
CLI::Option * retryOpt = nullptr
CLI::Option * retryOnFatalOpt = nullptr
CLI::Option * retryTriesOpt = nullptr
CLI::Option * retryTimeoutOpt = nullptr
CLI::Option * retryBaseOpt = nullptr
CLI::Option * retryLimitOpt = nullptr
CLI::Option * retryJitterOpt = nullptr
std::map< int, const net::phy::PhysicalSocketOption > socketOptionsMap
CLI::App * section = nullptr
Private Types
using Super = ConfigPhysicalSocket
Private Attributes
CLI::Option * readTimeoutOpt = nullptr
CLI::Option * writeTimeoutOpt = nullptr
CLI::Option * readBlockSizeOpt = nullptr
CLI::Option * writeBlockSizeOpt = nullptr
CLI::Option * terminateTimeoutOpt = nullptr
ConfigInstance * instance = nullptr
uint8_t requiredCount = 0
CLI::Option * reconnectOpt = nullptr
CLI::Option * reconnectTimeOpt = nullptr
CLI::Option * connectTimeoutOpt = nullptr
Detailed Description
template<template< template< typename SocketAddress > typename ConfigAddressTypeT > typename ConfigAddressLocalT, template< template< typename SocketAddress > typename ConfigAddressTypeT > typename ConfigAddressRemoteT = ConfigAddressLocalT>
class net::config::stream::ConfigSocketClient< ConfigAddressLocalT, ConfigAddressRemoteT >
Definition at line 36 of file ConfigSocketClient.h.
Member Typedef Documentation
Local
template<template< template< typename SocketAddress > typename ConfigAddressTypeT > typename ConfigAddressLocalT, template< template< typename SocketAddress > typename ConfigAddressTypeT > typename ConfigAddressRemoteT = ConfigAddressLocalT> using net::config::stream::ConfigSocketClient< ConfigAddressLocalT, ConfigAddressRemoteT >::Local = ConfigAddressLocalT<net::config::ConfigAddressLocal>
Definition at line 43 of file ConfigSocketClient.h.
Remote
template<template< template< typename SocketAddress > typename ConfigAddressTypeT > typename ConfigAddressLocalT, template< template< typename SocketAddress > typename ConfigAddressTypeT > typename ConfigAddressRemoteT = ConfigAddressLocalT> using net::config::stream::ConfigSocketClient< ConfigAddressLocalT, ConfigAddressRemoteT >::Remote = ConfigAddressRemoteT<net::config::ConfigAddressRemote>
Definition at line 42 of file ConfigSocketClient.h.
Super
using net::config::ConfigPhysicalSocketClient::Super = ConfigPhysicalSocket private inherited
Definition at line 45 of file ConfigPhysicalSocketClient.h.
Constructor & Destructor Documentation
ConfigSocketClient()
template<template< template< typename SocketAddress > typename ConfigAddressType > typename ConfigAddressLocal, template< template< typename SocketAddress > typename ConfigAddressType > typename ConfigAddressRemote> net::config::stream::ConfigSocketClient< ConfigAddressLocal, ConfigAddressRemote >::ConfigSocketClient (net::config::ConfigInstance * instance) explicit
Definition at line 31 of file ConfigSocketClient.hpp.
        : ConfigAddressRemote<net::config::ConfigAddressRemote>(instance, "remote", "Remote side of connection")
        , ConfigAddressLocal<net::config::ConfigAddressLocal>(instance, "local", "Local side of connection")
        , net::config::ConfigConnection(instance)
        , net::config::ConfigPhysicalSocketClient(instance) {
    }
Referenced by net::in::stream::config::ConfigSocketClient::ConfigSocketClient(), net::in6::stream::config::ConfigSocketClient::ConfigSocketClient(), net::l2::stream::config::ConfigSocketClient::ConfigSocketClient(), net::rc::stream::config::ConfigSocketClient::ConfigSocketClient(), and net::un::stream::config::ConfigSocketClient::ConfigSocketClient().
Member Function Documentation
add_flag() [1/12]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) inherited
Definition at line 111 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag(name, description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [2/12]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) inherited
Definition at line 111 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag(name, description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [3/12]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) inherited
Definition at line 126 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [4/12]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) inherited
Definition at line 126 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [5/12]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 67 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [6/12]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 67 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [7/12]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 74 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [8/12]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 74 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [9/12]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) inherited
add_flag() [10/12]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) inherited
add_flag() [11/12]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) inherited
Referenced by web::http::client::ConfigHTTP::ConfigHTTP(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag() [12/12]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) inherited
Referenced by web::http::client::ConfigHTTP::ConfigHTTP(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag_function() [1/4]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) inherited
Definition at line 135 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [2/4]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) inherited
Definition at line 135 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [3/4]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) inherited
Definition at line 156 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), and net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient().
add_flag_function() [4/4]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) inherited
Definition at line 156 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), and net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient().
add_option() [1/14]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) inherited
Definition at line 80 of file ConfigSection.cpp.
{
        if (!instance->getInstanceName().empty() && !section->get_display_name().empty()) {
            section->disabled(false);
        }
        opt = section //
                  ->add_option(name, description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigInstance::getInstanceName(), net::config::ConfigSection::instance, and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [2/14]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) inherited
Definition at line 80 of file ConfigSection.cpp.
{
        if (!instance->getInstanceName().empty() && !section->get_display_name().empty()) {
            section->disabled(false);
        }
        opt = section //
                  ->add_option(name, description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigInstance::getInstanceName(), net::config::ConfigSection::instance, and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [3/14]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) inherited
Definition at line 96 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [4/14]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) inherited
Definition at line 96 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [5/14]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) inherited
Definition at line 101 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [6/14]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) inherited
Definition at line 101 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [7/14]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 49 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [8/14]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 49 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [9/14]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 56 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [10/14]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 56 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [11/14]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) inherited
Referenced by net::config::ConfigTls::ConfigTls().
add_option() [12/14]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) inherited
Referenced by net::config::ConfigTls::ConfigTls().
add_option() [13/14]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
add_option() [14/14]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
add_socket_option()
CLI::Option * net::config::ConfigPhysicalSocket::add_socket_option (CLI::Option *& opt, const std::string & name, int optLevel, int optName, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 121 of file ConfigPhysicalSocket.cpp.
{
        return net::config::ConfigSection::add_flag_function(
            opt,
            name,
            [this, &opt, optLevel, optName](int64_t) -> void {
                if (opt->as<bool>()) {
                    socketOptionsMap.insert({optName, net::phy::PhysicalSocketOption(optLevel, optName, 1)});
                } else {
                    socketOptionsMap.erase(optName);
                }
            },
            description,
            typeName,
            defaultValue,
            validator);
    }
References net::config::ConfigSection::add_flag_function(), net::phy::PhysicalSocketOption::PhysicalSocketOption(), and net::config::ConfigPhysicalSocket::socketOptionsMap.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::in::stream::config::ConfigSocketServer::ConfigSocketServer(), and net::in6::stream::config::ConfigSocketServer::ConfigSocketServer().
addSocketOption() [1/3]
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::addSocketOption (int optLevel, int optName, const std::string & optValue) inherited
Definition at line 151 of file ConfigPhysicalSocket.cpp.
{
        socketOptionsMap.insert({optName, net::phy::PhysicalSocketOption(optLevel, optName, optValue)});
        return *this;
    }
References net::phy::PhysicalSocketOption::PhysicalSocketOption(), and net::config::ConfigPhysicalSocket::socketOptionsMap.
addSocketOption() [2/3]
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::addSocketOption (int optLevel, int optName, const std::vector< char > & optValue) inherited
Definition at line 157 of file ConfigPhysicalSocket.cpp.
{
        socketOptionsMap.insert({optName, net::phy::PhysicalSocketOption(optLevel, optName, optValue)});
        return *this;
    }
References net::phy::PhysicalSocketOption::PhysicalSocketOption(), and net::config::ConfigPhysicalSocket::socketOptionsMap.
addSocketOption() [3/3]
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::addSocketOption (int optLevel, int optName, int optValue) inherited
Definition at line 145 of file ConfigPhysicalSocket.cpp.
{
        socketOptionsMap.insert({optName, net::phy::PhysicalSocketOption(optLevel, optName, optValue)});
        return *this;
    }
References net::phy::PhysicalSocketOption::PhysicalSocketOption(), and net::config::ConfigPhysicalSocket::socketOptionsMap.
Referenced by net::in6::stream::config::ConfigSocketServer::setIPv6Only(), net::config::ConfigPhysicalSocket::setReuseAddress(), net::in::stream::config::ConfigSocketServer::setReusePort(), and net::in6::stream::config::ConfigSocketServer::setReusePort().
getConnectTimeout()
utils::Timeval net::config::ConfigPhysicalSocketClient::getConnectTimeout () const inherited
Definition at line 125 of file ConfigPhysicalSocketClient.cpp.
{
        const double connectTimeout = connectTimeoutOpt->as<double>();
        return utils::Timeval(connectTimeout);
    }
References net::config::ConfigPhysicalSocketClient::connectTimeoutOpt, and utils::Timeval::Timeval().
getReadBlockSize()
std::size_t net::config::ConfigConnection::getReadBlockSize () const inherited
Definition at line 94 of file ConfigConnection.cpp.
{
        return readBlockSizeOpt->as<std::size_t>();
    }
References net::config::ConfigConnection::readBlockSizeOpt.
getReadTimeout()
utils::Timeval net::config::ConfigConnection::getReadTimeout () const inherited
Definition at line 70 of file ConfigConnection.cpp.
{
        return readTimeoutOpt->as<utils::Timeval>();
    }
References net::config::ConfigConnection::readTimeoutOpt.
getReconnect()
bool net::config::ConfigPhysicalSocketClient::getReconnect () const inherited
Definition at line 101 of file ConfigPhysicalSocketClient.cpp.
{
        return reconnectOpt->as<bool>();
    }
References net::config::ConfigPhysicalSocketClient::reconnectOpt.
getReconnectTime()
double net::config::ConfigPhysicalSocketClient::getReconnectTime () const inherited
Definition at line 113 of file ConfigPhysicalSocketClient.cpp.
{
        return reconnectTimeOpt->as<double>();
    }
References net::config::ConfigPhysicalSocketClient::reconnectTimeOpt.
getRetry()
bool net::config::ConfigPhysicalSocket::getRetry () const inherited
Definition at line 211 of file ConfigPhysicalSocket.cpp.
{
        return retryOpt->as<bool>();
    }
References net::config::ConfigPhysicalSocket::retryOpt.
getRetryBase()
double net::config::ConfigPhysicalSocket::getRetryBase () const inherited
Definition at line 259 of file ConfigPhysicalSocket.cpp.
{
        return retryBaseOpt->as<double>();
    }
References net::config::ConfigPhysicalSocket::retryBaseOpt.
getRetryJitter()
double net::config::ConfigPhysicalSocket::getRetryJitter () const inherited
Definition at line 283 of file ConfigPhysicalSocket.cpp.
{
        return retryJitterOpt->as<double>();
    }
References net::config::ConfigPhysicalSocket::retryJitterOpt.
getRetryLimit()
unsigned int net::config::ConfigPhysicalSocket::getRetryLimit () const inherited
Definition at line 271 of file ConfigPhysicalSocket.cpp.
{
        return retryLimitOpt->as<unsigned int>();
    }
References net::config::ConfigPhysicalSocket::retryLimitOpt.
getRetryOnFatal()
bool net::config::ConfigPhysicalSocket::getRetryOnFatal () const inherited
Definition at line 223 of file ConfigPhysicalSocket.cpp.
{
        return retryOnFatalOpt->as<bool>();
    }
References net::config::ConfigPhysicalSocket::retryOnFatalOpt.
getRetryTimeout()
double net::config::ConfigPhysicalSocket::getRetryTimeout () const inherited
Definition at line 235 of file ConfigPhysicalSocket.cpp.
{
        return retryTimeoutOpt->as<double>();
    }
References net::config::ConfigPhysicalSocket::retryTimeoutOpt.
getRetryTries()
unsigned int net::config::ConfigPhysicalSocket::getRetryTries () const inherited
Definition at line 247 of file ConfigPhysicalSocket.cpp.
{
        return retryTriesOpt->as<unsigned int>();
    }
References net::config::ConfigPhysicalSocket::retryTriesOpt.
getReuseAddress()
bool net::config::ConfigPhysicalSocket::getReuseAddress () const inherited
Definition at line 183 of file ConfigPhysicalSocket.cpp.
{
        return reuseAddressOpt->as<bool>();
    }
References net::config::ConfigPhysicalSocket::reuseAddressOpt.
getSocketOptions()
const std::map< int, const net::phy::PhysicalSocketOption > & net::config::ConfigPhysicalSocket::getSocketOptions () inherited
Definition at line 117 of file ConfigPhysicalSocket.cpp.
{
        return socketOptionsMap;
    }
References net::config::ConfigPhysicalSocket::socketOptionsMap.
getTerminateTimeout()
utils::Timeval net::config::ConfigConnection::getTerminateTimeout () const inherited
Definition at line 118 of file ConfigConnection.cpp.
{
        return terminateTimeoutOpt->as<utils::Timeval>();
    }
References net::config::ConfigConnection::terminateTimeoutOpt.
getWriteBlockSize()
std::size_t net::config::ConfigConnection::getWriteBlockSize () const inherited
Definition at line 106 of file ConfigConnection.cpp.
{
        return writeBlockSizeOpt->as<std::size_t>();
    }
References net::config::ConfigConnection::writeBlockSizeOpt.
getWriteTimeout()
utils::Timeval net::config::ConfigConnection::getWriteTimeout () const inherited
Definition at line 82 of file ConfigConnection.cpp.
{
        return writeTimeoutOpt->as<utils::Timeval>();
    }
References net::config::ConfigConnection::writeTimeoutOpt.
removeSocketOption()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::removeSocketOption (int optName) inherited
Definition at line 163 of file ConfigPhysicalSocket.cpp.
{
        socketOptionsMap.erase(optName);
        return *this;
    }
References net::config::ConfigPhysicalSocket::socketOptionsMap.
Referenced by net::in6::stream::config::ConfigSocketServer::setIPv6Only(), net::config::ConfigPhysicalSocket::setReuseAddress(), net::in::stream::config::ConfigSocketServer::setReusePort(), and net::in6::stream::config::ConfigSocketServer::setReusePort().
required() [1/4]
bool net::config::ConfigSection::required () const inherited
Definition at line 76 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [2/4]
bool net::config::ConfigSection::required () const inherited
Definition at line 76 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [3/4]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) inherited
Definition at line 59 of file ConfigSection.cpp.
{
        if (req != opt->get_required()) {
            if (req) {
                ++requiredCount;
                section->needs(opt);
                opt->default_str("");
            } else {
                --requiredCount;
                section->remove_needs(opt);
            }
            opt->required(req);
            instance->required(section, requiredCount > 0);
        }
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
required() [4/4]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) inherited
Definition at line 59 of file ConfigSection.cpp.
{
        if (req != opt->get_required()) {
            if (req) {
                ++requiredCount;
                section->needs(opt);
                opt->default_str("");
            } else {
                --requiredCount;
                section->remove_needs(opt);
            }
            opt->required(req);
            instance->required(section, requiredCount > 0);
        }
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
setConnectTimeout()
ConfigPhysicalSocketClient & net::config::ConfigPhysicalSocketClient::setConnectTimeout (const utils::Timeval & connectTimeout) inherited
Definition at line 117 of file ConfigPhysicalSocketClient.cpp.
{
        connectTimeoutOpt //
            ->default_val(connectTimeout)
            ->clear();
        return *this;
    }
References net::config::ConfigPhysicalSocketClient::connectTimeoutOpt.
setReadBlockSize()
ConfigConnection & net::config::ConfigConnection::setReadBlockSize (std::size_t newReadBlockSize) inherited
Definition at line 98 of file ConfigConnection.cpp.
{
        readBlockSizeOpt //
            ->default_val(newReadBlockSize)
            ->clear();
        return *this;
    }
References net::config::ConfigConnection::readBlockSizeOpt.
setReadTimeout()
ConfigConnection & net::config::ConfigConnection::setReadTimeout (const utils::Timeval & newReadTimeoutSet) inherited
Definition at line 74 of file ConfigConnection.cpp.
{
        readTimeoutOpt //
            ->default_val(newReadTimeoutSet)
            ->clear();
        return *this;
    }
References net::config::ConfigConnection::readTimeoutOpt.
setReconnect()
ConfigPhysicalSocketClient & net::config::ConfigPhysicalSocketClient::setReconnect (bool reconnect = true) inherited
Definition at line 87 of file ConfigPhysicalSocketClient.cpp.
{
        reconnectOpt //
            ->default_val(reconnect ? "true" : "false")
            ->clear();
        if (reconnect) {
            reconnectTimeOpt->remove_needs(reconnectOpt);
        } else {
            reconnectTimeOpt->needs(reconnectOpt);
        }
        return *this;
    }
References net::config::ConfigPhysicalSocketClient::reconnectOpt, and net::config::ConfigPhysicalSocketClient::reconnectTimeOpt.
setReconnectTime()
ConfigPhysicalSocketClient & net::config::ConfigPhysicalSocketClient::setReconnectTime (double time) inherited
Definition at line 105 of file ConfigPhysicalSocketClient.cpp.
{
        reconnectTimeOpt //
            ->default_val(time)
            ->clear();
        return *this;
    }
References net::config::ConfigPhysicalSocketClient::reconnectTimeOpt.
setRetry()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetry (bool retry = true) inherited
Definition at line 187 of file ConfigPhysicalSocket.cpp.
{
        retryOpt //
            ->default_val(retry ? "true" : "false")
            ->clear();
        if (retry) {
            retryLimitOpt->remove_needs(retryOpt);
            retryJitterOpt->remove_needs(retryOpt);
            retryBaseOpt->remove_needs(retryOpt);
            retryTriesOpt->remove_needs(retryOpt);
            retryTimeoutOpt->remove_needs(retryOpt);
            retryOnFatalOpt->remove_needs(retryOpt);
        } else {
            retryLimitOpt->needs(retryOpt);
            retryJitterOpt->needs(retryOpt);
            retryBaseOpt->needs(retryOpt);
            retryTriesOpt->needs(retryOpt);
            retryTimeoutOpt->needs(retryOpt);
            retryOnFatalOpt->needs(retryOpt);
        }
        return *this;
    }
References net::config::ConfigPhysicalSocket::retryBaseOpt, net::config::ConfigPhysicalSocket::retryJitterOpt, net::config::ConfigPhysicalSocket::retryLimitOpt, net::config::ConfigPhysicalSocket::retryOnFatalOpt, net::config::ConfigPhysicalSocket::retryOpt, net::config::ConfigPhysicalSocket::retryTimeoutOpt, and net::config::ConfigPhysicalSocket::retryTriesOpt.
setRetryBase()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetryBase (double base) inherited
Definition at line 251 of file ConfigPhysicalSocket.cpp.
{
        retryBaseOpt //
            ->default_val(base)
            ->clear();
        return *this;
    }
References net::config::ConfigPhysicalSocket::retryBaseOpt.
setRetryJitter()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetryJitter (double percent) inherited
Definition at line 275 of file ConfigPhysicalSocket.cpp.
{
        retryJitterOpt //
            ->default_val(percent)
            ->clear();
        return *this;
    }
References net::config::ConfigPhysicalSocket::retryJitterOpt.
setRetryLimit()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetryLimit (unsigned int limit) inherited
Definition at line 263 of file ConfigPhysicalSocket.cpp.
{
        retryLimitOpt //
            ->default_val(limit)
            ->clear();
        return *this;
    }
References net::config::ConfigPhysicalSocket::retryLimitOpt.
setRetryOnFatal()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetryOnFatal (bool retry = true) inherited
Definition at line 215 of file ConfigPhysicalSocket.cpp.
{
        retryOnFatalOpt //
            ->default_val(retry ? "true" : "false")
            ->clear();
        return *this;
    }
References net::config::ConfigPhysicalSocket::retryOnFatalOpt.
setRetryTimeout()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetryTimeout (double sec) inherited
Definition at line 227 of file ConfigPhysicalSocket.cpp.
{
        retryTimeoutOpt //
            ->default_val(sec)
            ->clear();
        return *this;
    }
References net::config::ConfigPhysicalSocket::retryTimeoutOpt.
setRetryTries()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setRetryTries (unsigned int tries = 0) inherited
Definition at line 239 of file ConfigPhysicalSocket.cpp.
{
        retryTriesOpt //
            ->default_val(tries)
            ->clear();
        return *this;
    }
References net::config::ConfigPhysicalSocket::retryTriesOpt.
setReuseAddress()
ConfigPhysicalSocket & net::config::ConfigPhysicalSocket::setReuseAddress (bool reuseAddress = true) inherited
Definition at line 169 of file ConfigPhysicalSocket.cpp.
{
        if (reuseAddress) {
            addSocketOption(SOL_SOCKET, SO_REUSEADDR, 1);
        } else {
            removeSocketOption(SO_REUSEADDR);
        }
        reuseAddressOpt //
            ->default_val(reuseAddress ? "true" : "false")
            ->clear();
        return *this;
    }
References net::config::ConfigPhysicalSocket::addSocketOption(), net::config::ConfigPhysicalSocket::removeSocketOption(), and net::config::ConfigPhysicalSocket::reuseAddressOpt.
setTerminateTimeout()
ConfigConnection & net::config::ConfigConnection::setTerminateTimeout (const utils::Timeval & newTerminateTimeout) inherited
Definition at line 122 of file ConfigConnection.cpp.
{
        terminateTimeoutOpt //
            ->default_val(newTerminateTimeout)
            ->clear();
        return *this;
    }
References net::config::ConfigConnection::terminateTimeoutOpt.
setWriteBlockSize()
ConfigConnection & net::config::ConfigConnection::setWriteBlockSize (std::size_t newWriteBlockSize) inherited
Definition at line 110 of file ConfigConnection.cpp.
{
        writeBlockSizeOpt //
            ->default_val(newWriteBlockSize)
            ->clear();
        return *this;
    }
References net::config::ConfigConnection::writeBlockSizeOpt.
setWriteTimeout()
ConfigConnection & net::config::ConfigConnection::setWriteTimeout (const utils::Timeval & newWriteTimeoutSet) inherited
Definition at line 86 of file ConfigConnection.cpp.
{
        writeTimeoutOpt //
            ->default_val(newWriteTimeoutSet)
            ->clear();
        return *this;
    }
References net::config::ConfigConnection::writeTimeoutOpt.
Member Data Documentation
connectTimeoutOpt
CLI::Option* net::config::ConfigPhysicalSocketClient::connectTimeoutOpt = nullptr private inherited
Definition at line 63 of file ConfigPhysicalSocketClient.h.
Referenced by net::config::ConfigPhysicalSocketClient::getConnectTimeout(), and net::config::ConfigPhysicalSocketClient::setConnectTimeout().
instance
ConfigInstance* net::config::ConfigSection::instance = nullptr private inherited
Definition at line 120 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), and net::config::ConfigSection::required().
readBlockSizeOpt
CLI::Option* net::config::ConfigConnection::readBlockSizeOpt = nullptr private inherited
Definition at line 64 of file ConfigConnection.h.
Referenced by net::config::ConfigConnection::getReadBlockSize(), and net::config::ConfigConnection::setReadBlockSize().
readTimeoutOpt
CLI::Option* net::config::ConfigConnection::readTimeoutOpt = nullptr private inherited
Definition at line 62 of file ConfigConnection.h.
Referenced by net::config::ConfigConnection::getReadTimeout(), and net::config::ConfigConnection::setReadTimeout().
reconnectOpt
CLI::Option* net::config::ConfigPhysicalSocketClient::reconnectOpt = nullptr private inherited
Definition at line 60 of file ConfigPhysicalSocketClient.h.
Referenced by net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient(), net::config::ConfigPhysicalSocketClient::getReconnect(), and net::config::ConfigPhysicalSocketClient::setReconnect().
reconnectTimeOpt
CLI::Option* net::config::ConfigPhysicalSocketClient::reconnectTimeOpt = nullptr private inherited
Definition at line 61 of file ConfigPhysicalSocketClient.h.
Referenced by net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient(), net::config::ConfigPhysicalSocketClient::getReconnectTime(), net::config::ConfigPhysicalSocketClient::setReconnect(), and net::config::ConfigPhysicalSocketClient::setReconnectTime().
requiredCount
uint8_t net::config::ConfigSection::requiredCount = 0 private inherited
Definition at line 122 of file ConfigSection.h.
Referenced by net::config::ConfigSection::required(), and net::config::ConfigSection::required().
retryBaseOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryBaseOpt = nullptr protected inherited
Definition at line 96 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetryBase(), net::config::ConfigPhysicalSocket::setRetry(), and net::config::ConfigPhysicalSocket::setRetryBase().
retryJitterOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryJitterOpt = nullptr protected inherited
Definition at line 98 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetryJitter(), net::config::ConfigPhysicalSocket::setRetry(), and net::config::ConfigPhysicalSocket::setRetryJitter().
retryLimitOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryLimitOpt = nullptr protected inherited
Definition at line 97 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetryLimit(), net::config::ConfigPhysicalSocket::setRetry(), and net::config::ConfigPhysicalSocket::setRetryLimit().
retryOnFatalOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryOnFatalOpt = nullptr protected inherited
Definition at line 93 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetryOnFatal(), net::config::ConfigPhysicalSocket::setRetry(), and net::config::ConfigPhysicalSocket::setRetryOnFatal().
retryOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryOpt = nullptr protected inherited
Definition at line 92 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetry(), and net::config::ConfigPhysicalSocket::setRetry().
retryTimeoutOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryTimeoutOpt = nullptr protected inherited
Definition at line 95 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetryTimeout(), net::config::ConfigPhysicalSocket::setRetry(), and net::config::ConfigPhysicalSocket::setRetryTimeout().
retryTriesOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryTriesOpt = nullptr protected inherited
Definition at line 94 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetryTries(), net::config::ConfigPhysicalSocket::setRetry(), and net::config::ConfigPhysicalSocket::setRetryTries().
reuseAddressOpt
CLI::Option* net::config::ConfigPhysicalSocket::reuseAddressOpt = nullptr protected inherited
Definition at line 91 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getReuseAddress(), and net::config::ConfigPhysicalSocket::setReuseAddress().
section [1/2]
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 125 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
section [2/2]
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 125 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
socketOptionsMap
std::map<int, const net::phy::PhysicalSocketOption> net::config::ConfigPhysicalSocket::socketOptionsMap protected inherited
Definition at line 100 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::add_socket_option(), net::config::ConfigPhysicalSocket::addSocketOption(), net::config::ConfigPhysicalSocket::addSocketOption(), net::config::ConfigPhysicalSocket::addSocketOption(), net::config::ConfigPhysicalSocket::getSocketOptions(), and net::config::ConfigPhysicalSocket::removeSocketOption().
terminateTimeoutOpt
CLI::Option* net::config::ConfigConnection::terminateTimeoutOpt = nullptr private inherited
Definition at line 66 of file ConfigConnection.h.
Referenced by net::config::ConfigConnection::getTerminateTimeout(), and net::config::ConfigConnection::setTerminateTimeout().
writeBlockSizeOpt
CLI::Option* net::config::ConfigConnection::writeBlockSizeOpt = nullptr private inherited
Definition at line 65 of file ConfigConnection.h.
Referenced by net::config::ConfigConnection::getWriteBlockSize(), and net::config::ConfigConnection::setWriteBlockSize().
writeTimeoutOpt
CLI::Option* net::config::ConfigConnection::writeTimeoutOpt = nullptr private inherited
Definition at line 63 of file ConfigConnection.h.
Referenced by net::config::ConfigConnection::getWriteTimeout(), and net::config::ConfigConnection::setWriteTimeout().
The documentation for this class was generated from the following files:
net/config/stream/ConfigSocketClient.h
net/config/stream/ConfigSocketClient.hpp