SNode.C: core::epoll::EventMultiplexer Class Reference
core::epoll::EventMultiplexer Class Reference
#include <EventMultiplexer.h>
Public Types
enum DISP_TYPE { RD = 0 , WR = 1 , EX = 2 }
Public Member Functions
EventMultiplexer ()
~EventMultiplexer () override=default
DescriptorEventPublisher & getDescriptorEventPublisher (DISP_TYPE dispType)
TimerEventPublisher & getTimerEventPublisher ()
void span (core::Event *event)
void relax (core::Event *event)
void signal (int sigNum)
void terminate ()
void clearEventQueue ()
TickStatus tick (const utils::Timeval &tickTimeOut, const sigset_t &sigMask)
Protected Member Functions
int maxFd ()
Protected Attributes
std::array< DescriptorEventPublisher *, 3 > descriptorEventPublishers
Private Member Functions
int monitorDescriptors (utils::Timeval &tickTimeout, const sigset_t &sigMask) override
void spanActiveEvents (int activeDescriptorCount) override
TickStatus waitForEvents (const utils::Timeval &tickTimeOut, const utils::Timeval &currentTime, const sigset_t &sigMask, int &activeDescriptorCount)
void executeEventQueue (const utils::Timeval &currentTime)
void checkTimedOutEvents (const utils::Timeval &currentTime)
void releaseExpiredResources (const utils::Timeval &currentTime)
utils::Timeval getNextTimeout (const utils::Timeval &currentTime)
int observedEventReceiverCount ()
Private Attributes
int epfd
int epfds [3]
epoll_event ePollEvents [3] {}
core::TimerEventPublisher *const timerEventPublisher
EventQueue eventQueue
Detailed Description
Definition at line 37 of file EventMultiplexer.h.
Member Enumeration Documentation
DISP_TYPE
enum core::EventMultiplexer::DISP_TYPE inherited
Enumerator
RD
WR
EX
Definition at line 84 of file EventMultiplexer.h.
{ RD = 0, WR = 1, EX = 2 };
Constructor & Destructor Documentation
EventMultiplexer()
core::epoll::EventMultiplexer::EventMultiplexer ()
Definition at line 42 of file EventMultiplexer.cpp.
        : core::EventMultiplexer(
              new core::epoll::DescriptorEventPublisher(
                  "READ", epfds[core::EventMultiplexer::DISP_TYPE::RD], EPOLLIN, EPOLLIN | EPOLLHUP | EPOLLRDHUP | EPOLLERR),
              new core::epoll::DescriptorEventPublisher("WRITE", epfds[core::EventMultiplexer::DISP_TYPE::WR], EPOLLOUT, EPOLLOUT),
              new core::epoll::DescriptorEventPublisher("EXCEPT", epfds[core::EventMultiplexer::DISP_TYPE::EX], EPOLLPRI, EPOLLPRI))
        , epfd(core::system::epoll_create1(EPOLL_CLOEXEC)) {
        epoll_event event{};
        event.events = EPOLLIN;
        event.data.ptr = descriptorEventPublishers[core::EventMultiplexer::DISP_TYPE::RD];
        core::system::epoll_ctl(epfd, EPOLL_CTL_ADD, epfds[core::EventMultiplexer::DISP_TYPE::RD], &event);
        event.data.ptr = descriptorEventPublishers[core::EventMultiplexer::DISP_TYPE::WR];
        core::system::epoll_ctl(epfd, EPOLL_CTL_ADD, epfds[core::EventMultiplexer::DISP_TYPE::WR], &event);
        event.data.ptr = descriptorEventPublishers[core::EventMultiplexer::DISP_TYPE::EX];
        core::system::epoll_ctl(epfd, EPOLL_CTL_ADD, epfds[core::EventMultiplexer::DISP_TYPE::EX], &event);
        LOG(DEBUG) << "Core::multiplexer: epoll";
    }
References core::epoll::DescriptorEventPublisher::DescriptorEventPublisher(), core::EventMultiplexer::descriptorEventPublishers, epfd, epfds, core::system::epoll_create1(), core::system::epoll_ctl(), core::EventMultiplexer::EventMultiplexer(), core::EventMultiplexer::EX, core::EventMultiplexer::RD, and core::EventMultiplexer::WR.
~EventMultiplexer()
core::epoll::EventMultiplexer::~EventMultiplexer () override virtual default
Reimplemented from core::EventMultiplexer.
Member Function Documentation
checkTimedOutEvents()
void core::EventMultiplexer::checkTimedOutEvents (const utils::Timeval & currentTime) private inherited
Definition at line 143 of file EventMultiplexer.cpp.
{
        for (DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
            descriptorEventPublisher->checkTimedOutEvents(currentTime);
        }
    }
References core::DescriptorEventPublisher::checkTimedOutEvents(), and core::EventMultiplexer::descriptorEventPublishers.
Referenced by core::EventMultiplexer::tick().
clearEventQueue()
void core::EventMultiplexer::clearEventQueue () inherited
Definition at line 105 of file EventMultiplexer.cpp.
{
        eventQueue.clear();
    }
References core::EventMultiplexer::EventQueue::clear(), and core::EventMultiplexer::eventQueue.
Referenced by core::EventLoop::start(), and core::EventLoop::tick().
executeEventQueue()
void core::EventMultiplexer::executeEventQueue (const utils::Timeval & currentTime) private inherited
Definition at line 139 of file EventMultiplexer.cpp.
{
        eventQueue.execute(currentTime);
    }
References core::EventMultiplexer::eventQueue, and core::EventMultiplexer::EventQueue::execute().
Referenced by core::EventMultiplexer::tick().
getDescriptorEventPublisher()
DescriptorEventPublisher & core::EventMultiplexer::getDescriptorEventPublisher (DISP_TYPE dispType) inherited
Definition at line 54 of file EventMultiplexer.cpp.
{
        return *descriptorEventPublishers[dispType];
    }
References core::EventMultiplexer::descriptorEventPublishers.
Referenced by core::eventreceiver::AcceptEventReceiver::AcceptEventReceiver(), core::eventreceiver::ConnectEventReceiver::ConnectEventReceiver(), core::eventreceiver::ExceptionalConditionEventReceiver::ExceptionalConditionEventReceiver(), core::eventreceiver::ReadEventReceiver::ReadEventReceiver(), and core::eventreceiver::WriteEventReceiver::WriteEventReceiver().
getNextTimeout()
utils::Timeval core::EventMultiplexer::getNextTimeout (const utils::Timeval & currentTime) private inherited
Definition at line 157 of file EventMultiplexer.cpp.
{
        utils::Timeval nextTimeout = DescriptorEventReceiver::TIMEOUT::MAX;
        if (eventQueue.empty()) {
            for (const DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
                nextTimeout = // cppcheck-suppress useStlAlgorithm
                    std::min(descriptorEventPublisher->getNextTimeout(currentTime), nextTimeout);
            }
            nextTimeout = std::min(timerEventPublisher->getNextTimeout(currentTime), nextTimeout);
            nextTimeout = std::max(nextTimeout, utils::Timeval()); // In case nextTimeout is negative
        } else {
            nextTimeout = 0;
        }
        return nextTimeout;
    }
References core::EventMultiplexer::descriptorEventPublishers, core::EventMultiplexer::EventQueue::empty(), core::EventMultiplexer::eventQueue, core::TimerEventPublisher::getNextTimeout(), core::DescriptorEventPublisher::getNextTimeout(), core::DescriptorEventReceiver::TIMEOUT::MAX, utils::Timeval::operator=(), core::EventMultiplexer::timerEventPublisher, and utils::Timeval::Timeval().
Referenced by core::EventMultiplexer::waitForEvents().
getTimerEventPublisher()
core::TimerEventPublisher & core::EventMultiplexer::getTimerEventPublisher () inherited
Definition at line 58 of file EventMultiplexer.cpp.
{
        return *timerEventPublisher;
    }
References core::EventMultiplexer::timerEventPublisher.
Referenced by core::TimerEventReceiver::TimerEventReceiver().
maxFd()
int core::EventMultiplexer::maxFd () protected inherited
Definition at line 183 of file EventMultiplexer.cpp.
{
        return std::accumulate(descriptorEventPublishers.begin(),
                               descriptorEventPublishers.end(),
                               -1,
                               [](int count, const DescriptorEventPublisher* descriptorEventPublisher) -> int {
                                   return std::max(descriptorEventPublisher->maxFd(), count);
                               });
    }
References core::EventMultiplexer::descriptorEventPublishers, and core::DescriptorEventPublisher::maxFd().
Referenced by core::select::EventMultiplexer::monitorDescriptors().
monitorDescriptors()
int core::epoll::EventMultiplexer::monitorDescriptors (utils::Timeval & tickTimeout, const sigset_t & sigMask) override private virtual
Implements core::EventMultiplexer.
Definition at line 64 of file EventMultiplexer.cpp.
{
        return core::system::epoll_pwait(epfd, ePollEvents, 3, tickTimeout.getMs(), &sigMask);
    }
References epfd, core::system::epoll_pwait(), ePollEvents, and utils::Timeval::getMs().
observedEventReceiverCount()
int core::EventMultiplexer::observedEventReceiverCount () private inherited
Definition at line 174 of file EventMultiplexer.cpp.
{
        return std::accumulate(descriptorEventPublishers.begin(),
                               descriptorEventPublishers.end(),
                               0,
                               [](int count, const DescriptorEventPublisher* descriptorEventPublisher) -> int {
                                   return count + descriptorEventPublisher->getObservedEventReceiverCount();
                               });
    }
References core::EventMultiplexer::descriptorEventPublishers, and core::DescriptorEventPublisher::getObservedEventReceiverCount().
Referenced by core::EventMultiplexer::waitForEvents().
relax()
void core::EventMultiplexer::relax (core::Event * event) inherited
Definition at line 66 of file EventMultiplexer.cpp.
{
        eventQueue.remove(event);
    }
References core::EventMultiplexer::eventQueue, and core::EventMultiplexer::EventQueue::remove().
Referenced by core::Event::relax().
releaseExpiredResources()
void core::EventMultiplexer::releaseExpiredResources (const utils::Timeval & currentTime) private inherited
Definition at line 149 of file EventMultiplexer.cpp.
{
        for (DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
            descriptorEventPublisher->releaseDisabledEvents(currentTime);
        }
        timerEventPublisher->unobserveDisableEvents();
        DynamicLoader::execDlCloseDeleyed();
    }
References core::EventMultiplexer::descriptorEventPublishers, core::DynamicLoader::execDlCloseDeleyed(), core::DescriptorEventPublisher::releaseDisabledEvents(), core::EventMultiplexer::timerEventPublisher, and core::TimerEventPublisher::unobserveDisableEvents().
Referenced by core::EventMultiplexer::signal(), core::EventMultiplexer::terminate(), and core::EventMultiplexer::tick().
signal()
void core::EventMultiplexer::signal (int sigNum) inherited
Definition at line 87 of file EventMultiplexer.cpp.
{
        for (DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
            descriptorEventPublisher->signal(sigNum);
        }
        timerEventPublisher->stop();
        releaseExpiredResources(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::EventMultiplexer::descriptorEventPublishers, core::EventMultiplexer::releaseExpiredResources(), core::DescriptorEventPublisher::signal(), core::TimerEventPublisher::stop(), and core::EventMultiplexer::timerEventPublisher.
Referenced by core::EventLoop::free().
span()
void core::EventMultiplexer::span (core::Event * event) inherited
Definition at line 62 of file EventMultiplexer.cpp.
{
        eventQueue.insert(event);
    }
References core::EventMultiplexer::eventQueue, and core::EventMultiplexer::EventQueue::insert().
Referenced by core::Event::span().
spanActiveEvents()
void core::epoll::EventMultiplexer::spanActiveEvents (int activeDescriptorCount) override private virtual
Implements core::EventMultiplexer.
Definition at line 68 of file EventMultiplexer.cpp.
{
        for (int i = 0; i < activeDescriptorCount; i++) {
            if ((ePollEvents[i].events & EPOLLIN) != 0) {
                static_cast<core::DescriptorEventPublisher*>(ePollEvents[i].data.ptr)->spanActiveEvents();
            }
        }
    }
References ePollEvents, and core::DescriptorEventPublisher::spanActiveEvents().
terminate()
void core::EventMultiplexer::terminate () inherited
Definition at line 96 of file EventMultiplexer.cpp.
{
        for (DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
            descriptorEventPublisher->disable();
        }
        timerEventPublisher->stop();
        releaseExpiredResources(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::EventMultiplexer::descriptorEventPublishers, core::DescriptorEventPublisher::disable(), core::EventMultiplexer::releaseExpiredResources(), core::TimerEventPublisher::stop(), and core::EventMultiplexer::timerEventPublisher.
Referenced by core::EventLoop::free().
tick()
TickStatus core::EventMultiplexer::tick (const utils::Timeval & tickTimeOut, const sigset_t & sigMask) inherited
Definition at line 70 of file EventMultiplexer.cpp.
{
        const utils::Timeval currentTime = utils::Timeval::currentTime();
        int activeDescriptorCount = 0;
        const TickStatus tickStatus = waitForEvents(tickTimeOut, currentTime, sigMask, activeDescriptorCount);
        if (tickStatus == TickStatus::SUCCESS) {
            spanActiveEvents(currentTime, activeDescriptorCount);
            executeEventQueue(currentTime);
            checkTimedOutEvents(currentTime);
            releaseExpiredResources(currentTime);
        }
        return tickStatus;
    }
References core::EventMultiplexer::checkTimedOutEvents(), utils::Timeval::currentTime(), core::EventMultiplexer::executeEventQueue(), core::EventMultiplexer::releaseExpiredResources(), core::EventMultiplexer::spanActiveEvents(), core::SUCCESS, and core::EventMultiplexer::waitForEvents().
Referenced by core::EventLoop::_tick().
waitForEvents()
TickStatus core::EventMultiplexer::waitForEvents (const utils::Timeval & tickTimeOut, const utils::Timeval & currentTime, const sigset_t & sigMask, int & activeDescriptorCount) private inherited
Definition at line 109 of file EventMultiplexer.cpp.
{
        TickStatus tickStatus = TickStatus::SUCCESS;
        if (observedEventReceiverCount() > 0 || !timerEventPublisher->empty() || !eventQueue.empty()) {
            utils::Timeval nextTimeout = std::min(getNextTimeout(currentTime), tickTimeOut);
            activeDescriptorCount = monitorDescriptors(nextTimeout, sigMask);
            if (activeDescriptorCount < 0) {
                if (errno == EINTR) {
                    tickStatus = TickStatus::INTERRUPTED;
                } else {
                    tickStatus = TickStatus::TRACE;
                }
            }
        } else {
            tickStatus = TickStatus::NOOBSERVER;
        }
        return tickStatus;
    }
References core::TimerEventPublisher::empty(), core::EventMultiplexer::EventQueue::empty(), core::EventMultiplexer::eventQueue, core::EventMultiplexer::getNextTimeout(), core::INTERRUPTED, core::EventMultiplexer::monitorDescriptors(), core::NOOBSERVER, core::EventMultiplexer::observedEventReceiverCount(), core::SUCCESS, core::EventMultiplexer::timerEventPublisher, and core::TRACE.
Referenced by core::EventMultiplexer::tick().
Member Data Documentation
descriptorEventPublishers
std::array<DescriptorEventPublisher*, 3 > core::EventMultiplexer::descriptorEventPublishers protected inherited
Definition at line 118 of file EventMultiplexer.h.
Referenced by core::EventMultiplexer::checkTimedOutEvents(), EventMultiplexer(), core::EventMultiplexer::EventMultiplexer(), core::EventMultiplexer::getDescriptorEventPublisher(), core::EventMultiplexer::getNextTimeout(), core::EventMultiplexer::maxFd(), core::EventMultiplexer::observedEventReceiverCount(), core::EventMultiplexer::releaseExpiredResources(), core::EventMultiplexer::signal(), core::poll::EventMultiplexer::spanActiveEvents(), core::select::EventMultiplexer::spanActiveEvents(), core::EventMultiplexer::terminate(), and core::EventMultiplexer::~EventMultiplexer().
epfd
int core::epoll::EventMultiplexer::epfd private
Definition at line 46 of file EventMultiplexer.h.
Referenced by EventMultiplexer(), and monitorDescriptors().
epfds
int core::epoll::EventMultiplexer::epfds[3] private
Definition at line 48 of file EventMultiplexer.h.
Referenced by EventMultiplexer().
ePollEvents
epoll_event core::epoll::EventMultiplexer::ePollEvents[3] {} private
Definition at line 49 of file EventMultiplexer.h.
{};
Referenced by monitorDescriptors(), and spanActiveEvents().
eventQueue
EventQueue core::EventMultiplexer::eventQueue private inherited
Definition at line 125 of file EventMultiplexer.h.
Referenced by core::EventMultiplexer::clearEventQueue(), core::EventMultiplexer::executeEventQueue(), core::EventMultiplexer::getNextTimeout(), core::EventMultiplexer::relax(), core::EventMultiplexer::span(), and core::EventMultiplexer::waitForEvents().
timerEventPublisher
core::TimerEventPublisher* const core::EventMultiplexer::timerEventPublisher private inherited
Definition at line 123 of file EventMultiplexer.h.
Referenced by core::EventMultiplexer::getNextTimeout(), core::EventMultiplexer::getTimerEventPublisher(), core::EventMultiplexer::releaseExpiredResources(), core::EventMultiplexer::signal(), core::EventMultiplexer::spanActiveEvents(), core::EventMultiplexer::terminate(), core::EventMultiplexer::waitForEvents(), and core::EventMultiplexer::~EventMultiplexer().
The documentation for this class was generated from the following files:
core/multiplexer/epoll/EventMultiplexer.h
core/multiplexer/epoll/EventMultiplexer.cpp