SNode.C: core::file::File Class Reference
core::file::File Class Reference
#include <File.h>
Public Member Functions
File ()
~File () override
int getFd () const
Private Attributes
int fd = -1
Detailed Description
Definition at line 30 of file File.h.
Constructor & Destructor Documentation
File()
core::file::File::File ()
Definition at line 28 of file File.cpp.
        : Descriptor(-1) {
    }
References core::Descriptor::Descriptor().
~File()
core::file::File::~File () override
Definition at line 32 of file File.cpp.
                {
    }
Member Function Documentation
getFd()
int core::Descriptor::getFd () const inherited
Definition at line 59 of file Descriptor.cpp.
{
        return fd;
    }
References core::Descriptor::fd.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::bind(), net::phy::PhysicalSocket< SocketAddressT >::getPeerName(), net::phy::PhysicalSocket< SocketAddressT >::getSockName(), net::phy::PhysicalSocket< SocketAddressT >::getSockopt(), core::file::FileReader::isOpen(), net::phy::PhysicalSocket< SocketAddressT >::isValid(), core::file::FileReader::onEvent(), net::un::dgram::Socket::recvFd(), net::un::dgram::Socket::sendFd(), net::phy::PhysicalSocket< SocketAddressT >::setSockopt(), and net::phy::stream::PhysicalSocket< SocketAddressT >::shutdown().
Member Data Documentation
fd
int core::Descriptor::fd = -1 private inherited
Definition at line 48 of file Descriptor.h.
Referenced by core::Descriptor::Descriptor(), core::Descriptor::Descriptor(), core::Descriptor::getFd(), core::Descriptor::operator=(), core::Descriptor::operator=(), and core::Descriptor::~Descriptor().
The documentation for this class was generated from the following files:
core/file/File.h
core/file/File.cpp