snode.c: net::phy::stream::PhysicalSocketServer< SocketAddressT > Class Template Reference
net::phy::stream::PhysicalSocketServer< SocketAddressT > Class Template Reference
#include <PhysicalSocketServer.h>
Public Types
using SocketAddress = SocketAddressT
Public Types inherited from net::phy::stream::PhysicalSocket< SocketAddressT >
using SocketAddress = SocketAddressT
Public Types inherited from net::phy::PhysicalSocket< SocketAddressT >
enum Flags { NONE = 0 , NONBLOCK = SOCK_NONBLOCK , CLOEXIT = SOCK_CLOEXEC }
Public Member Functions
int listen (int backlog)
int accept ()
int accept4 (int flags)
Public Member Functions inherited from net::phy::PhysicalSocket< SocketAddressT >
PhysicalSocket (int fd)
int open (const std::map< int, const PhysicalSocketOption > &socketOptions, Flags flags)
int bind (SocketAddress &bindAddress)
bool isValid () const
int getSockError (int &cErrno) const
int getSockname (typename SocketAddress::SockAddr &localSockAddr, socklen_t &localSockAddrLen)
int getPeername (typename SocketAddress::SockAddr &remoteSockAddr, socklen_t &remoteSockAddrLen)
const SocketAddress & getBindAddress () const
Public Member Functions inherited from core::Descriptor
Descriptor ()=delete
Descriptor (const Descriptor &d)=delete
Descriptor (Descriptor &&d)=delete
int getFd () const
void setDontClose (bool dontClose=true)
Private Types
using Super = net::phy::stream::PhysicalSocket< SocketAddressT >
Additional Inherited Members
Protected Types inherited from net::phy::stream::PhysicalSocket< SocketAddressT >
enum SHUT { WR = SHUT_WR , RD = SHUT_RD , RDWR = SHUT_RDWR }
Protected Types inherited from net::phy::PhysicalSocket< SocketAddressT >
using SocketAddress = SocketAddressT
Protected Member Functions inherited from net::phy::stream::PhysicalSocket< SocketAddressT >
void shutdown (SHUT how)
Protected Member Functions inherited from net::phy::PhysicalSocket< SocketAddressT >
PhysicalSocket ()=delete
PhysicalSocket (int domain, int type, int protocol)
PhysicalSocket (const PhysicalSocket &physicalSocket)
~PhysicalSocket () override
Protected Member Functions inherited from core::Descriptor
Descriptor (int fd)
Descriptor & operator= (int fd)
Descriptor & operator= (const Descriptor &descriptor)=delete
Descriptor & operator= (Descriptor &&descriptor)=delete
virtual ~Descriptor ()
Detailed Description
template<typename SocketAddressT>
class net::phy::stream::PhysicalSocketServer< SocketAddressT >
Definition at line 33 of file PhysicalSocketServer.h.
Member Typedef Documentation
SocketAddress
template<typename SocketAddressT > using net::phy::stream::PhysicalSocketServer< SocketAddressT >::SocketAddress = SocketAddressT
Definition at line 38 of file PhysicalSocketServer.h.
Super
template<typename SocketAddressT > using net::phy::stream::PhysicalSocketServer< SocketAddressT >::Super = net::phy::stream::PhysicalSocket<SocketAddressT> private
Definition at line 35 of file PhysicalSocketServer.h.
Member Function Documentation
accept()
template<typename SocketAddress > int net::phy::stream::PhysicalSocketServer< SocketAddress >::accept ()
Definition at line 35 of file PhysicalSocketServer.hpp.
{
        return core::system::accept(Super::getFd(), nullptr, nullptr);
    }
References core::system::accept().
accept4()
template<typename SocketAddress > int net::phy::stream::PhysicalSocketServer< SocketAddress >::accept4 (int flags)
Definition at line 40 of file PhysicalSocketServer.hpp.
{
        return core::system::accept4(Super::getFd(), nullptr, nullptr, flags);
    }
References core::system::accept4().
listen()
template<typename SocketAddress > int net::phy::stream::PhysicalSocketServer< SocketAddress >::listen (int backlog)
Definition at line 30 of file PhysicalSocketServer.hpp.
{
        return core::system::listen(Super::getFd(), backlog);
    }
References core::system::listen().
The documentation for this class was generated from the following files:
net/phy/stream/PhysicalSocketServer.h
net/phy/stream/PhysicalSocketServer.hpp