SNode.C: net::l2::stream::config::ConfigSocketClient Class Reference
net::l2::stream::config::ConfigSocketClient Class Reference
#include <ConfigSocketClient.h>
Protected Member Functions
ConfigSocketClient (net::config::ConfigInstance *instance)
~ConfigSocketClient () override
Protected Member Functions inherited from net::config::stream::ConfigSocketClient< net::l2::config::ConfigAddress >
ConfigSocketClient (net::config::ConfigInstance *instance)
Protected Member Functions inherited from net::l2::config::ConfigAddress< net::config::ConfigAddressRemote >
ConfigAddress (net::config::ConfigInstance *instance, const std::string &addressOptionName, const std::string &addressOptionDescription)
ConfigAddress & setBtAddressRequired (bool required=true)
ConfigAddress & setPsmRequired (bool required=true)
Protected Member Functions inherited from utils::SubCommand
SubCommand (SubCommand *parent, std::shared_ptr< utils::AppWithPtr > appWithPtr, const std::string &group, bool final)
template<typename ConcretSubCommand>
SubCommand (SubCommand *parent, ConcretSubCommand *concretSubCommand, const std::string &group, bool final=true)
SubCommand * description (const std::string &description)
SubCommand * footer (const std::string &footer)
template<typename ValueTypeT>
CLI::Option * setDefaultValue (CLI::Option *option, const ValueTypeT &value, bool clear=true) const
CLI::Option * setConfigurable (CLI::Option *option, bool configurable) const
Protected Member Functions inherited from net::config::ConfigAddress< net::l2::SocketAddress >
ConfigAddress (ConfigInstance *instance, const std::string &addressOptionName, const std::string &addressOptionDescription)
~ConfigAddress () override
Protected Member Functions inherited from net::config::ConfigAddressBase< net::l2::SocketAddress >
ConfigAddressBase (ConfigInstance *instance, const std::string &addressOptionName="", const std::string &addressOptionDescription="")
virtual ~ConfigAddressBase ()=default
Protected Member Functions inherited from net::l2::config::ConfigAddress< net::config::ConfigAddressLocal >
ConfigAddress (net::config::ConfigInstance *instance, const std::string &addressOptionName, const std::string &addressOptionDescription)
ConfigAddress & setBtAddressRequired (bool required=true)
ConfigAddress & setPsmRequired (bool required=true)
Protected Member Functions inherited from net::config::ConfigConnection
ConfigConnection (ConfigInstance *instance)
~ConfigConnection () override
Protected Member Functions inherited from net::config::ConfigPhysicalSocketClient
ConfigPhysicalSocketClient (ConfigInstance *instance)
~ConfigPhysicalSocketClient () override
Protected Member Functions inherited from net::config::ConfigPhysicalSocket
template<typename ConcretConfigPhysicalSocketT>
ConfigPhysicalSocket (ConfigInstance *instance, ConcretConfigPhysicalSocketT *section)
~ConfigPhysicalSocket () override
CLI::Option * addSocketOption (const std::string &name, int optLevel, int optName, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Additional Inherited Members
Public Types inherited from net::config::stream::ConfigSocketClient< net::l2::config::ConfigAddress >
using Remote
using Local
using Connection
using Socket
Public Member Functions inherited from net::l2::config::ConfigAddress< net::config::ConfigAddressRemote >
ConfigAddress & setSocketAddress (const SocketAddress &socketAddress)
ConfigAddress & setBtAddress (const std::string &btAddress)
std::string getBtAddress () const
ConfigAddress & setPsm (uint16_t psm)
uint16_t getPsm () const
void configurable (bool configurable=true) final
Public Member Functions inherited from net::config::ConfigSection
template<typename T>
ConfigSection (ConfigInstance *instance, T *sectionPtr, const std::string &group="Sections")
~ConfigSection () override
ConfigSection (const ConfigSection &)=delete
ConfigSection (ConfigSection &&)=delete
ConfigSection & operator= (const ConfigSection &)=delete
Public Member Functions inherited from utils::SubCommand
SubCommand (const SubCommand &)=delete
SubCommand (SubCommand &&)=delete
SubCommand & operator= (const SubCommand &)=delete
SubCommand & operator= (SubCommand &&)=delete
virtual ~SubCommand ()
std::string getName () const
std::string version () const
void parse (int argc, char *argv[])
CLI::Option * setConfig (const std::string &defaultConfigFile) const
CLI::Option * setLogFile (const std::string &defaultLogFile) const
CLI::Option * setVersionFlag (const std::string &version) const
bool hasParent () const
SubCommand * getParent ()
SubCommand * allowExtras (bool allow=true)
SubCommand * required (bool required=true, bool force=true)
SubCommand * required (SubCommand *subCommand, bool required=true)
SubCommand * required (CLI::Option *option, bool required=true)
SubCommand * needs (SubCommand *subCommand, bool needs=true)
SubCommand * disabled (SubCommand *subCommand, bool disabled=true)
SubCommand * setRequireCallback (const std::function< void(void)> &callback)
SubCommand * finalCallback (const std::function< void()> &finalCallback)
std::string configToStr () const
std::string help (const CLI::App *helpApp, const CLI::AppFormatMode &mode) const
template<typename NewSubCommand, typename... Args>
NewSubCommand * newSubCommand (Args &&... args)
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand ()
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand () const
CLI::Option * getOption (const std::string &name) const
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator) const
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Public Member Functions inherited from net::config::ConfigAddress< net::l2::SocketAddress >
net::l2::SocketAddress getSocketAddress (const typename net::l2::SocketAddress::SockAddr &sockAddr, typename net::l2::SocketAddress::SockLen sockAddrLen)
void renew ()
Public Member Functions inherited from net::config::ConfigAddressBase< net::l2::SocketAddress >
net::l2::SocketAddress getSocketAddress (const typename net::l2::SocketAddress::SockAddr &sockAddr, typename net::l2::SocketAddress::SockLen sockAddrLen)
Public Member Functions inherited from net::l2::config::ConfigAddress< net::config::ConfigAddressLocal >
ConfigAddress & setSocketAddress (const SocketAddress &socketAddress)
ConfigAddress & setBtAddress (const std::string &btAddress)
std::string getBtAddress () const
ConfigAddress & setPsm (uint16_t psm)
uint16_t getPsm () const
void configurable (bool configurable=true) final
Public Member Functions inherited from net::config::ConfigConnection
utils::Timeval getReadTimeout () const
ConfigConnection & setReadTimeout (const utils::Timeval &newReadTimeoutSet)
utils::Timeval getWriteTimeout () const
ConfigConnection & setWriteTimeout (const utils::Timeval &newWriteTimeoutSet)
std::size_t getReadBlockSize () const
ConfigConnection & setReadBlockSize (std::size_t newReadBlockSize)
std::size_t getWriteBlockSize () const
ConfigConnection & setWriteBlockSize (std::size_t newWriteBlockSize)
utils::Timeval getTerminateTimeout () const
ConfigConnection & setTerminateTimeout (const utils::Timeval &newTerminateTimeout)
Public Member Functions inherited from net::config::ConfigPhysicalSocketClient
ConfigPhysicalSocketClient & setReconnect (bool reconnect=true)
bool getReconnect () const
ConfigPhysicalSocketClient & setReconnectTime (double time)
double getReconnectTime () const
ConfigPhysicalSocketClient & setConnectTimeout (const utils::Timeval &connectTimeout)
utils::Timeval getConnectTimeout () const
Public Member Functions inherited from net::config::ConfigPhysicalSocket
const std::map< int, std::map< int, net::phy::PhysicalSocketOption > > & getSocketOptions () const
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, int optValue)
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, const std::string &optValue)
ConfigPhysicalSocket & addSocketOption (int optLevel, int optName, const std::vector< char > &optValue)
ConfigPhysicalSocket & removeSocketOption (int optLevel, int optName)
ConfigPhysicalSocket & setRetry (bool retry=true)
bool getRetry () const
ConfigPhysicalSocket & setRetryOnFatal (bool retry=true)
bool getRetryOnFatal () const
ConfigPhysicalSocket & setRetryTimeout (double sec)
double getRetryTimeout () const
ConfigPhysicalSocket & setRetryTries (unsigned int tries=0)
unsigned int getRetryTries () const
ConfigPhysicalSocket & setRetryBase (double base)
double getRetryBase () const
ConfigPhysicalSocket & setRetryLimit (unsigned int limit)
unsigned int getRetryLimit () const
ConfigPhysicalSocket & setRetryJitter (double percent)
double getRetryJitter () const
template<typename ConcretConfigPhysicalSocket>
ConfigPhysicalSocket (ConfigInstance *instance, ConcretConfigPhysicalSocket *section)
Static Public Member Functions inherited from utils::SubCommand
static CLI::App * getHelpTriggerApp ()
static CLI::App * getShowConfigTriggerApp ()
static CLI::App * getCommandlineTriggerApp ()
Static Public Attributes inherited from utils::SubCommand
static std::shared_ptr< CLI::Formatter > sectionFormatter = makeSectionFormatter()
Static Public Attributes inherited from net::config::ConfigAddressRemote< net::l2::SocketAddress >
static constexpr std::string_view NAME
static constexpr std::string_view DESCRIPTION
Static Public Attributes inherited from net::config::ConfigAddressLocal< net::l2::SocketAddress >
static constexpr std::string_view NAME
static constexpr std::string_view DESCRIPTION
Static Public Attributes inherited from net::config::ConfigConnection
static constexpr std::string_view NAME {"connection"}
static constexpr std::string_view DESCRIPTION {"Configuration of established connections"}
Static Public Attributes inherited from net::config::ConfigPhysicalSocket
static constexpr std::string_view NAME {"socket"}
static constexpr std::string_view DESCRIPTION {"Configuration of socket behavior"}
Protected Attributes inherited from net::l2::config::ConfigAddress< net::config::ConfigAddressRemote >
CLI::Option * btAddressOpt
CLI::Option * psmOpt
Protected Attributes inherited from net::l2::config::ConfigAddress< net::config::ConfigAddressLocal >
CLI::Option * btAddressOpt
CLI::Option * psmOpt
Static Protected Attributes inherited from utils::SubCommand
static std::map< std::string, std::string > aliases
static CLI::App * helpTriggerApp = nullptr
static CLI::App * showConfigTriggerApp = nullptr
static CLI::App * commandlineTriggerApp = nullptr
Detailed Description
Definition at line 58 of file ConfigSocketClient.h.
Constructor & Destructor Documentation
ConfigSocketClient()
net::l2::stream::config::ConfigSocketClient::ConfigSocketClient (net::config::ConfigInstance * instance) explicit protected
Definition at line 52 of file ConfigSocketClient.cpp.
        : net::config::stream::ConfigSocketClient<net::l2::config::ConfigAddress>(instance) {
        Remote::setBtAddressRequired();
        Remote::setPsmRequired();
    }
References net::config::stream::ConfigSocketClient< ConfigAddressLocalT, ConfigAddressRemoteT >::ConfigSocketClient(), net::l2::config::ConfigAddress< ConfigAddressTypeT >::setBtAddressRequired(), and net::l2::config::ConfigAddress< ConfigAddressTypeT >::setPsmRequired().
~ConfigSocketClient()
net::l2::stream::config::ConfigSocketClient::~ConfigSocketClient () override protected
Definition at line 58 of file ConfigSocketClient.cpp.
{
    }
The documentation for this class was generated from the following files:
net/l2/stream/config/ConfigSocketClient.h
net/l2/stream/config/ConfigSocketClient.cpp