SNode.C: core::socket::stream::SocketContext Class Reference
core::socket::stream::SocketContext Class Reference abstract
#include <SocketContext.h>
Public Member Functions
SocketContext (core::socket::stream::SocketConnection *socketConnection)
~SocketContext () override
void sendToPeer (const char *chunk, std::size_t chunkLen) const final
bool streamToPeer (core::pipe::Source *source) const
void streamEof ()
std::size_t readFromPeer (char *chunk, std::size_t chunklen) const final
void setTimeout (const utils::Timeval &timeout) final
void shutdownRead ()
void shutdownWrite (bool forceClose=false)
void close () override
std::size_t getTotalSent () const override
std::size_t getTotalQueued () const override
std::size_t getTotalRead () const override
std::size_t getTotalProcessed () const override
std::string getOnlineSince () const override
std::string getOnlineDuration () const override
SocketConnection * getSocketConnection () const
virtual void switchSocketContext (SocketContext *newSocketContext)
void sendToPeer (const std::string &data) const
virtual void sendToPeer (const char *chunk, std::size_t chunkLen) const=0
Public Member Functions inherited from core::socket::SocketContext
SocketContext (const SocketContext &)=delete
SocketContext (SocketContext &&)=delete
SocketContext & operator= (const SocketContext &)=delete
SocketContext & operator= (SocketContext &&)=delete
void sendToPeer (const std::string &data) const
Protected Member Functions
void onWriteError (int errnum) override
void onReadError (int errnum) override
Protected Member Functions inherited from core::socket::SocketContext
SocketContext ()=default
virtual std::size_t onReceivedFromPeer ()=0
virtual bool onSignal (int sig)=0
Private Types
using Super = core::socket::SocketContext
Private Member Functions
virtual void onConnected ()=0
virtual void onDisconnected ()=0
virtual void attach ()
virtual void detach ()
Static Private Member Functions
static std::string timePointToString (const std::chrono::time_point< std::chrono::system_clock > &timePoint)
static std::string durationToString (const std::chrono::time_point< std::chrono::system_clock > &bevore, const std::chrono::time_point< std::chrono::system_clock > &later=std::chrono::system_clock::now())
Private Attributes
core::socket::stream::SocketConnection * socketConnection
std::string onlineSince
std::size_t alreadyTotalQueued = 0
std::size_t alreadyTotalProcessed = 0
std::chrono::time_point< std::chrono::system_clock > onlineSinceTimePoint
Friends
template<typename PhysicalSocketT , class SocketReaderT , class SocketWriterT >
class SocketConnectionT
class SocketConnection
Detailed Description
Definition at line 66 of file SocketContext.h.
Member Typedef Documentation
Super
using core::socket::stream::SocketContext::Super = core::socket::SocketContext private
Definition at line 68 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext()
core::socket::stream::SocketContext::SocketContext (core::socket::stream::SocketConnection * socketConnection) explicit
Definition at line 60 of file SocketContext.cpp.
        : socketConnection(socketConnection)
        , onlineSinceTimePoint(std::chrono::system_clock::now()) {
        LOG(DEBUG) << socketConnection->getConnectionName() << " SocketContext: created";
    }
References core::socket::stream::SocketConnection::getConnectionName(), onlineSinceTimePoint, and socketConnection.
Referenced by apps::echo::model::EchoSocketContext::EchoSocketContext(), apps::http::SimpleSocketProtocol::SimpleSocketProtocol(), iot::mqtt_fast::SocketContext::SocketContext(), web::http::client::SocketContext::SocketContext(), web::http::server::SocketContext::SocketContext(), and iot::mqtt::SocketContext::SocketContext().
~SocketContext()
core::socket::stream::SocketContext::~SocketContext () override virtual
Reimplemented from core::socket::SocketContext.
Reimplemented in web::http::client::SocketContext.
Definition at line 66 of file SocketContext.cpp.
{
        LOG(DEBUG) << socketConnection->getConnectionName() << " SocketContext: disconnected";
    }
References core::socket::stream::SocketConnection::getConnectionName(), and socketConnection.
Member Function Documentation
attach()
void core::socket::stream::SocketContext::attach () private virtual
Definition at line 152 of file SocketContext.cpp.
{
        alreadyTotalQueued = socketConnection->getTotalQueued();
        alreadyTotalProcessed = socketConnection->getTotalProcessed();
        LOG(DEBUG) << socketConnection->getConnectionName() << " SocketContext: attach";
        onConnected();
    }
References alreadyTotalProcessed, alreadyTotalQueued, core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketConnection::getTotalProcessed(), core::socket::stream::SocketConnection::getTotalQueued(), onConnected(), and socketConnection.
Referenced by core::socket::stream::SocketConnection::setSocketContext().
close()
void core::socket::stream::SocketContext::close () override virtual
Implements core::socket::SocketContext.
Reimplemented in iot::mqtt::SocketContext.
Definition at line 99 of file SocketContext.cpp.
{
        socketConnection->close();
    }
References core::socket::stream::SocketConnection::close(), and socketConnection.
Referenced by iot::mqtt::SocketContext::close(), web::http::client::Request::executeUpgrade(), iot::mqtt_fast::SocketContext::onReceivedFromPeer(), web::http::client::Request::onSourceError(), web::http::server::Response::onSourceError(), and web::http::client::Request::upgrade().
detach()
void core::socket::stream::SocketContext::detach () private virtual
Definition at line 161 of file SocketContext.cpp.
{
        onDisconnected();
        LOG(DEBUG) << socketConnection->getConnectionName() << " SocketContext: detach";
        LOG(DEBUG) << "     Online Since: " << getOnlineSince();
        LOG(DEBUG) << "  Online Duration: " << getOnlineDuration();
        LOG(DEBUG) << "       Total Sent: " << getTotalQueued();
        LOG(DEBUG) << "  Total Processed: " << getTotalProcessed();
    }
References core::socket::stream::SocketConnection::getConnectionName(), getOnlineDuration(), getOnlineSince(), getTotalProcessed(), getTotalQueued(), onDisconnected(), and socketConnection.
Referenced by core::socket::stream::SocketConnection::disconnectCurrentSocketContext().
durationToString()
std::string core::socket::stream::SocketContext::durationToString (const std::chrono::time_point< std::chrono::system_clock > & bevore, const std::chrono::time_point< std::chrono::system_clock > & later = std::chrono::system_clock::now()) static private
Definition at line 186 of file SocketContext.cpp.
{
        using seconds_duration_type = std::chrono::duration<std::chrono::seconds::rep>::rep;
        const seconds_duration_type totalSeconds = std::chrono::duration_cast<std::chrono::seconds>(later - bevore).count();
        // Compute days, hours, minutes, and seconds
        const seconds_duration_type days = totalSeconds / 86400; // 86400 seconds in a day
        seconds_duration_type remainder = totalSeconds % 86400;
        const seconds_duration_type hours = remainder / 3600;
        remainder = remainder % 3600;
        const seconds_duration_type minutes = remainder / 60;
        const seconds_duration_type seconds = remainder % 60;
        // Format the components into a string using stringstream
        std::ostringstream oss;
        if (days > 0) {
            oss << days << " day" << (days == 1 ? "" : "s") << ", ";
        }
        oss << std::setw(2) << std::setfill('0') << hours << ":" << std::setw(2) << std::setfill('0') << minutes << ":" << std::setw(2)
            << std::setfill('0') << seconds;
        return oss.str();
    }
Referenced by getOnlineDuration().
getOnlineDuration()
std::string core::socket::stream::SocketContext::getOnlineDuration () const override virtual
Implements core::socket::SocketContext.
Reimplemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Definition at line 122 of file SocketContext.cpp.
{
        return durationToString(onlineSinceTimePoint);
    }
References durationToString(), and onlineSinceTimePoint.
Referenced by detach().
getOnlineSince()
std::string core::socket::stream::SocketContext::getOnlineSince () const override virtual
Implements core::socket::SocketContext.
Reimplemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Definition at line 119 of file SocketContext.cpp.
{
        return timePointToString(onlineSinceTimePoint);
    }
References onlineSinceTimePoint, and timePointToString().
Referenced by detach().
getSocketConnection()
SocketConnection * core::socket::stream::SocketContext::getSocketConnection () const
Definition at line 75 of file SocketContext.cpp.
{
        return socketConnection;
    }
References socketConnection.
Referenced by web::http::server::SocketContext::deliverRequest(), web::http::client::SocketContext::deliverResponse(), web::http::client::SocketContext::deliverResponseParseError(), iot::mqtt::SocketContext::getSocketConnection(), web::http::client::SocketContext::initiateRequest(), web::http::client::SocketContext::onConnected(), web::http::server::SocketContext::onConnected(), web::http::client::SocketContext::onDisconnected(), web::http::server::SocketContext::onDisconnected(), web::http::client::SocketContext::onSignal(), web::http::server::SocketContext::onSignal(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestDelivered(), web::http::client::SocketContext::requestPrepared(), web::http::server::SocketContext::responseCompleted(), web::http::client::SocketContext::responseDelivered(), web::http::client::Request::responseParseError(), web::http::client::SocketContext::responseStarted(), web::http::server::SocketContext::responseStarted(), web::http::client::SocketContext::SocketContext(), web::http::server::SocketContext::SocketContext(), express::middleware::StaticMiddleware::StaticMiddleware(), web::http::server::Response::upgrade(), web::http::client::Request::upgrade(), express::middleware::VerboseRequest::VerboseRequest(), and web::http::client::SocketContext::~SocketContext().
getTotalProcessed()
std::size_t core::socket::stream::SocketContext::getTotalProcessed () const override virtual
Implements core::socket::SocketContext.
Definition at line 115 of file SocketContext.cpp.
{
        return socketConnection->getTotalProcessed() - alreadyTotalProcessed;
    }
References alreadyTotalProcessed, core::socket::stream::SocketConnection::getTotalProcessed(), and socketConnection.
Referenced by detach().
getTotalQueued()
std::size_t core::socket::stream::SocketContext::getTotalQueued () const override virtual
Implements core::socket::SocketContext.
Definition at line 107 of file SocketContext.cpp.
{
        return socketConnection->getTotalQueued() - alreadyTotalQueued;
    }
References alreadyTotalQueued, core::socket::stream::SocketConnection::getTotalQueued(), and socketConnection.
Referenced by detach().
getTotalRead()
std::size_t core::socket::stream::SocketContext::getTotalRead () const override virtual
Implements core::socket::SocketContext.
Definition at line 111 of file SocketContext.cpp.
{
        return socketConnection->getTotalRead();
    }
References core::socket::stream::SocketConnection::getTotalRead(), and socketConnection.
getTotalSent()
std::size_t core::socket::stream::SocketContext::getTotalSent () const override virtual
Implements core::socket::SocketContext.
Definition at line 103 of file SocketContext.cpp.
{
        return socketConnection->getTotalSent();
    }
References core::socket::stream::SocketConnection::getTotalSent(), and socketConnection.
onConnected()
virtual void core::socket::stream::SocketContext::onConnected () private pure virtual
Implemented in apps::echo::model::EchoSocketContext, apps::http::SimpleSocketProtocol, apps::http::SimpleSocketProtocol, iot::mqtt::SocketContext, web::http::client::SocketContext, web::http::server::SocketContext, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by attach().
onDisconnected()
virtual void core::socket::stream::SocketContext::onDisconnected () private pure virtual
Implemented in apps::echo::model::EchoSocketContext, apps::http::SimpleSocketProtocol, apps::http::SimpleSocketProtocol, iot::mqtt::SocketContext, web::http::client::SocketContext, web::http::server::SocketContext, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by detach().
onReadError()
void core::socket::stream::SocketContext::onReadError (int errnum) override protected virtual
Implements core::socket::SocketContext.
Definition at line 141 of file SocketContext.cpp.
{
        errno = errnum;
        if (errno == 0) {
            LOG(DEBUG) << socketConnection->getConnectionName() << " SocketContext: EOF received";
        } else {
            PLOG(DEBUG) << socketConnection->getConnectionName() << " SocketContext: onReadError";
        }
        shutdownWrite();
    }
References core::socket::stream::SocketConnection::getConnectionName(), shutdownWrite(), and socketConnection.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReadError(), and apps::http::SimpleSocketProtocol::onReadError().
onWriteError()
void core::socket::stream::SocketContext::onWriteError (int errnum) override protected virtual
Implements core::socket::SocketContext.
Reimplemented in web::http::client::SocketContext, and web::http::server::SocketContext.
Definition at line 134 of file SocketContext.cpp.
{
        errno = errnum;
        PLOG(DEBUG) << socketConnection->getConnectionName() << " SocketContext: onWriteError";
        shutdownRead();
    }
References core::socket::stream::SocketConnection::getConnectionName(), shutdownRead(), and socketConnection.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onWriteError(), and apps::http::SimpleSocketProtocol::onWriteError().
readFromPeer()
std::size_t core::socket::stream::SocketContext::readFromPeer (char * chunk, std::size_t chunklen) const final virtual
Implements core::socket::SocketContext.
Definition at line 91 of file SocketContext.cpp.
{
        return socketConnection->readFromPeer(chunk, chunklen);
    }
References core::socket::stream::SocketConnection::readFromPeer(), and socketConnection.
Referenced by apps::echo::model::EchoSocketContext::onReceivedFromPeer(), web::http::decoder::Fields::read(), web::http::decoder::HTTP10Response::read(), web::http::decoder::Identity::read(), web::http::decoder::Chunked::Chunk::read(), web::http::Parser::readStartLine(), and iot::mqtt::SocketContext::recv().
sendToPeer() [1/3]
void core::socket::stream::SocketContext::sendToPeer (const char * chunk, std::size_t chunkLen) const final virtual
Implements core::socket::SocketContext.
Definition at line 79 of file SocketContext.cpp.
{
        socketConnection->sendToPeer(chunk, chunkLen);
    }
References core::socket::stream::SocketConnection::sendToPeer(), and socketConnection.
Referenced by web::http::client::Request::executeSendFragment(), apps::echo::model::EchoSocketContext::onReceivedFromPeer(), iot::mqtt::SocketContext::send(), iot::mqtt_fast::SocketContext::send(), and web::http::server::Response::sendFragment().
sendToPeer() [2/3]
virtual void core::socket::SocketContext::sendToPeer (const char * chunk, std::size_t chunkLen) const virtual
Implements core::socket::SocketContext.
sendToPeer() [3/3]
void core::socket::SocketContext::sendToPeer (const std::string & data) const
Definition at line 75 of file SocketContext.cpp.
{
        sendToPeer(data.data(), data.length());
    }
setTimeout()
void core::socket::stream::SocketContext::setTimeout (const utils::Timeval & timeout) final virtual
Implements core::socket::SocketContext.
Definition at line 95 of file SocketContext.cpp.
{
        socketConnection->setTimeout(timeout);
    }
References core::socket::stream::SocketConnection::setTimeout(), and socketConnection.
shutdownRead()
void core::socket::stream::SocketContext::shutdownRead ()
Definition at line 126 of file SocketContext.cpp.
{
        socketConnection->shutdownRead();
    }
References core::socket::stream::SocketConnection::shutdownRead(), and socketConnection.
Referenced by apps::http::SimpleSocketProtocol::onWriteError(), and onWriteError().
shutdownWrite()
void core::socket::stream::SocketContext::shutdownWrite (bool forceClose = false)
Definition at line 130 of file SocketContext.cpp.
{
        socketConnection->shutdownWrite(forceClose);
    }
References core::socket::stream::SocketConnection::shutdownWrite(), and socketConnection.
Referenced by web::http::client::SocketContext::deliverResponseParseError(), iot::mqtt::SocketContext::end(), apps::http::SimpleSocketProtocol::onReadError(), onReadError(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestDelivered(), web::http::server::SocketContext::responseCompleted(), and web::http::client::SocketContext::responseStarted().
streamEof()
void core::socket::stream::SocketContext::streamEof ()
Definition at line 87 of file SocketContext.cpp.
{
        socketConnection->streamEof();
    }
References socketConnection, and core::socket::stream::SocketConnection::streamEof().
Referenced by web::http::client::Request::onSourceEof(), web::http::server::Response::onSourceEof(), web::http::client::Request::onSourceError(), web::http::server::Response::onSourceError(), web::http::client::Request::~Request(), and web::http::server::Response::~Response().
streamToPeer()
bool core::socket::stream::SocketContext::streamToPeer (core::pipe::Source * source) const
Definition at line 83 of file SocketContext.cpp.
{
        return socketConnection->streamToPeer(source);
    }
References socketConnection, and core::socket::stream::SocketConnection::streamToPeer().
Referenced by web::http::client::Request::onSourceConnect(), and web::http::server::Response::onSourceConnect().
switchSocketContext()
void core::socket::stream::SocketContext::switchSocketContext (SocketContext * newSocketContext) virtual
Definition at line 70 of file SocketContext.cpp.
{
        LOG(DEBUG) << socketConnection->getConnectionName() << " SocketContext: switch";
        socketConnection->switchSocketContext(newSocketContext);
    }
References core::socket::stream::SocketConnection::getConnectionName(), socketConnection, and core::socket::stream::SocketConnection::switchSocketContext().
Referenced by web::http::server::Response::sendCompleted(), and web::http::client::Request::upgrade().
timePointToString()
std::string core::socket::stream::SocketContext::timePointToString (const std::chrono::time_point< std::chrono::system_clock > & timePoint) static private
Definition at line 171 of file SocketContext.cpp.
{
        const std::time_t time = std::chrono::system_clock::to_time_t(timePoint);
        std::tm* tm_ptr = std::gmtime(&time);
        char buffer[100];
        std::string onlineSince = "Formatting error";
        // Format: "2025-02-02 14:30:00"
        if (std::strftime(buffer, sizeof(buffer), "%Y-%m-%d %H:%M:%S", tm_ptr) > 0) {
            onlineSince = std::string(buffer) + " UTC";
        }
        return onlineSince;
    }
Referenced by getOnlineSince().
Friends And Related Symbol Documentation
SocketConnection
friend class SocketConnection friend
Definition at line 126 of file SocketContext.h.
SocketConnectionT
template<typename PhysicalSocketT , class SocketReaderT , class SocketWriterT > friend class SocketConnectionT friend
Definition at line 125 of file SocketContext.h.
Member Data Documentation
alreadyTotalProcessed
std::size_t core::socket::stream::SocketContext::alreadyTotalProcessed = 0 private
Definition at line 120 of file SocketContext.h.
Referenced by attach(), and getTotalProcessed().
alreadyTotalQueued
std::size_t core::socket::stream::SocketContext::alreadyTotalQueued = 0 private
Definition at line 119 of file SocketContext.h.
Referenced by attach(), and getTotalQueued().
onlineSince
std::string core::socket::stream::SocketContext::onlineSince private
Definition at line 118 of file SocketContext.h.
onlineSinceTimePoint
std::chrono::time_point<std::chrono::system_clock> core::socket::stream::SocketContext::onlineSinceTimePoint private
Definition at line 122 of file SocketContext.h.
Referenced by getOnlineDuration(), getOnlineSince(), and SocketContext().
socketConnection
core::socket::stream::SocketConnection* core::socket::stream::SocketContext::socketConnection private
Definition at line 116 of file SocketContext.h.
Referenced by attach(), close(), detach(), getSocketConnection(), getTotalProcessed(), getTotalQueued(), getTotalRead(), getTotalSent(), onReadError(), onWriteError(), readFromPeer(), sendToPeer(), setTimeout(), shutdownRead(), shutdownWrite(), SocketContext(), streamEof(), streamToPeer(), switchSocketContext(), and ~SocketContext().
The documentation for this class was generated from the following files:
core/socket/stream/SocketContext.h
core/socket/stream/SocketContext.cpp