SNode.C: OptionNotFound Class Reference
OptionNotFound Class Reference
Errors
Thrown when counting a non-existent option.
#include <CLI11.hpp>
Public Member Functions
OptionNotFound (std::string msg, ExitCodes exit_code)
OptionNotFound (std::string msg, int exit_code)
OptionNotFound (std::string name)
Public Member Functions inherited from Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Protected Member Functions
OptionNotFound (std::string ename, std::string msg, int exit_code)
OptionNotFound (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
Thrown when counting a non-existent option.
Definition at line 1356 of file CLI11.hpp.
Constructor & Destructor Documentation
OptionNotFound() [1/5]
OptionNotFound::OptionNotFound (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 1357 of file CLI11.hpp.
OptionNotFound() [2/5]
OptionNotFound::OptionNotFound (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 1357 of file CLI11.hpp.
OptionNotFound() [3/5]
OptionNotFound::OptionNotFound (std::string msg, ExitCodes exit_code) inline
Definition at line 1357 of file CLI11.hpp.
OptionNotFound() [4/5]
OptionNotFound::OptionNotFound (std::string msg, int exit_code) inline
Definition at line 1357 of file CLI11.hpp.
OptionNotFound() [5/5]
OptionNotFound::OptionNotFound (std::string name) inline explicit
Definition at line 1358 of file CLI11.hpp.
            : OptionNotFound(name + " not found", ExitCodes::OptionNotFound) {
        }
References OptionNotFound().
Referenced by App::get_option(), App::get_option(), App::get_option_group(), App::get_subcommand(), App::get_subcommand(), App::get_subcommand(), App::get_subcommand_ptr(), App::get_subcommand_ptr(), App::get_subcommand_ptr(), and OptionNotFound().
The documentation for this class was generated from the following file:
src/utils/CLI11.hpp