SNode.C: net::config::ConfigInstance Class Reference
net::config::ConfigInstance Class Reference
#include <ConfigInstance.h>
Public Types
enum class Role { SERVER , CLIENT }
Public Member Functions
ConfigInstance (ConfigInstance &)=delete
ConfigInstance (ConfigInstance &&)=delete
ConfigInstance & operator= (ConfigInstance &)=delete
ConfigInstance & operator= (ConfigInstance &&)=delete
Role getRole () const
const std::string & getInstanceName () const
void setInstanceName (const std::string &instanceName)
bool getDisabled () const
ConfigInstance & setDisabled (bool disabled=true)
CLI::App * newSection (std::shared_ptr< CLI::App > appWithPtr, const std::string &group)
ConfigSection * addSection (std::shared_ptr< ConfigSection > &&configSection)
template<typename ConcreteConfigSection, typename... Args>
ConcreteConfigSection * addSection (Args &&... args)
template<typename SectionTypeT>
SectionTypeT * getSection () const
bool gotSection (const std::string &name) const
ConfigInstance & required (bool required=true)
ConfigInstance & required (CLI::App *section, bool req=true)
bool getRequired () const
CLI::App * get () const
ConfigInstance & configurable (bool configurable=true)
template<typename SectionType>
SectionType * getSection () const
Protected Member Functions
ConfigInstance (const std::string &instanceName, Role role)
virtual ~ConfigInstance ()
Private Member Functions
const CLI::App * getSection (const std::string &name) const
Private Attributes
uint8_t requiredCount = 0
std::string instanceName
Role role
CLI::App * instanceSc = nullptr
CLI::Option * disableOpt = nullptr
std::vector< std::shared_ptr< net::config::ConfigSection > > configSections
Static Private Attributes
static const std::string nameAnonymous = "<anonymous>"
Friends
class net::config::ConfigSection
Detailed Description
Definition at line 65 of file ConfigInstance.h.
Member Enumeration Documentation
Role
enum class net::config::ConfigInstance::Role strong
Enumerator
SERVER
CLIENT
Definition at line 67 of file ConfigInstance.h.
{ SERVER, CLIENT };
Constructor & Destructor Documentation
ConfigInstance() [1/3]
net::config::ConfigInstance::ConfigInstance (const std::string & instanceName, Role role) explicit protected
Definition at line 61 of file ConfigInstance.cpp.
        : instanceName(instanceName)
        , role(role) {
        auto configInstanceApp = net::config::Instance(instanceName,
                                                       std::string("Configuration for ")
                                                           .append(role == Role::SERVER ? "server" : "client")
                                                           .append(" instance '")
                                                           .append(instanceName)
                                                           .append("'"),
                                                       this);
        instanceSc = utils::Config::newInstance(configInstanceApp, "Instances");
        disableOpt = instanceSc
                         ->add_flag_function(
                             "--disabled{true}",
                             [this](std::size_t) {
                                 utils::Config::disabled(instanceSc, disableOpt->as<bool>());
                             },
                             "Disable this instance")
                         ->multi_option_policy(CLI::MultiOptionPolicy::TakeLast)
                         ->trigger_on_parse()
                         ->default_str("false")
                         ->type_name("bool")
                         ->check(CLI::IsMember({"true", "false"}))
                         ->group(instanceSc->get_formatter()->get_label("Persistent Options"));
    }
References utils::Config::disabled(), disableOpt, net::config::Instance(), instanceName, instanceSc, utils::Config::newInstance(), role, and SERVER.
~ConfigInstance()
net::config::ConfigInstance::~ConfigInstance () protected virtual
Definition at line 88 of file ConfigInstance.cpp.
{
        utils::Config::removeInstance(instanceSc);
    }
References instanceSc, and utils::Config::removeInstance().
ConfigInstance() [2/3]
net::config::ConfigInstance::ConfigInstance (ConfigInstance &) delete
ConfigInstance() [3/3]
net::config::ConfigInstance::ConfigInstance (ConfigInstance &&) delete
Member Function Documentation
addSection() [1/2]
template<typename ConcreteConfigSection, typename... Args> ConcreteConfigSection * net::config::ConfigInstance::addSection (Args &&... args)
Definition at line 79 of file ConfigInstanceAPI.hpp.
{
        return dynamic_cast<ConcreteConfigSection*>(addSection(std::make_shared<ConcreteConfigSection>(this, std::forward<Args>(args)...)));
    }
addSection() [2/2]
ConfigSection * net::config::ConfigInstance::addSection (std::shared_ptr< ConfigSection > && configSection)
Definition at line 127 of file ConfigInstance.cpp.
{
        return configSections.emplace_back(configSection).get();
    }
References configSections.
configurable()
ConfigInstance & net::config::ConfigInstance::configurable (bool configurable = true)
Definition at line 170 of file ConfigInstance.cpp.
{
        disableOpt->configurable(configurable);
        disableOpt->group(instanceSc->get_formatter()->get_label(configurable ? "Persistent Options" : "Nonpersistent Options"));
        return *this;
    }
References disableOpt, and instanceSc.
get()
CLI::App * net::config::ConfigInstance::get () const
Definition at line 166 of file ConfigInstance.cpp.
{
        return instanceSc;
    }
References instanceSc.
getDisabled()
bool net::config::ConfigInstance::getDisabled () const
Definition at line 187 of file ConfigInstance.cpp.
{
        return disableOpt //
            ->as<bool>();
    }
References disableOpt.
Referenced by required().
getInstanceName()
const std::string & net::config::ConfigInstance::getInstanceName () const
Definition at line 96 of file ConfigInstance.cpp.
{
        return instanceName.empty() ? nameAnonymous : instanceName;
    }
References instanceName, and nameAnonymous.
Referenced by net::config::ConfigSection::addOption(), net::un::config::ConfigAddressReverse< net::config::ConfigAddressReverse >::ConfigAddressReverse(), net::config::ConfigSection::ConfigSection(), tls::getClient(), legacy::getLegacyClient(), net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSniCtx(), net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx(), main(), and core::socket::stream::SocketConnection::SocketConnection().
getRequired()
bool net::config::ConfigInstance::getRequired () const
Definition at line 162 of file ConfigInstance.cpp.
{
        return requiredCount > 0;
    }
References requiredCount.
getRole()
ConfigInstance::Role net::config::ConfigInstance::getRole () const
Definition at line 92 of file ConfigInstance.cpp.
{
        return role;
    }
References role.
getSection() [1/3]
template<typename SectionTypeT> SectionTypeT * net::config::ConfigInstance::getSection () const
Referenced by web::http::client::SocketContextFactory::create().
getSection() [2/3]
template<typename SectionType> SectionType * net::config::ConfigInstance::getSection () const
Definition at line 71 of file ConfigInstanceAPI.hpp.
{
        utils::AppWithPtr<SectionType>* sectionApp =
            dynamic_cast<utils::AppWithPtr<SectionType>*>(instanceSc->get_subcommand_no_throw(std::string(SectionType::name)));
        return sectionApp != nullptr ? sectionApp->getPtr() : nullptr;
    }
References instanceSc.
getSection() [3/3]
const CLI::App * net::config::ConfigInstance::getSection (const std::string & name) const private
Definition at line 178 of file ConfigInstance.cpp.
{
        return instanceSc->get_subcommand_no_throw(name);
    }
References instanceSc.
gotSection()
bool net::config::ConfigInstance::gotSection (const std::string & name) const
Definition at line 182 of file ConfigInstance.cpp.
{
        return instanceSc //
            ->got_subcommand(name);
    }
References instanceSc.
newSection()
CLI::App * net::config::ConfigInstance::newSection (std::shared_ptr< CLI::App > appWithPtr, const std::string & group)
Definition at line 104 of file ConfigInstance.cpp.
{
        CLI::App* sectionSc = instanceSc->add_subcommand(appWithPtr)
                                  ->fallthrough()
                                  ->configurable(false)
                                  ->allow_extras()
                                  ->group(group)
                                  ->ignore_case(false)
                                  ->disabled(appWithPtr->get_name().empty())
                                  ->formatter(instanceSc->get_formatter())
                                  ->config_formatter(instanceSc->get_config_formatter());
        sectionSc //
            ->option_defaults()
            ->configurable(!sectionSc->get_disabled());
        if (!sectionSc->get_disabled()) {
            utils::Config::addStandardFlags(sectionSc);
            utils::Config::addSimpleHelp(sectionSc);
        }
        return sectionSc;
    }
References utils::Config::addSimpleHelp(), utils::Config::addStandardFlags(), and instanceSc.
Referenced by net::config::ConfigSection::ConfigSection().
operator=() [1/2]
ConfigInstance & net::config::ConfigInstance::operator= (ConfigInstance &&) delete
operator=() [2/2]
ConfigInstance & net::config::ConfigInstance::operator= (ConfigInstance &) delete
required() [1/2]
ConfigInstance & net::config::ConfigInstance::required (bool required = true)
Definition at line 131 of file ConfigInstance.cpp.
{
        if (!getDisabled()) {
            utils::Config::required(instanceSc, required);
        }
        return *this;
    }
References getDisabled(), instanceSc, and utils::Config::required().
Referenced by required().
required() [2/2]
ConfigInstance & net::config::ConfigInstance::required (CLI::App * section, bool req = true)
Definition at line 139 of file ConfigInstance.cpp.
{
        if (req != section->get_required()) {
            if (req) {
                ++requiredCount;
                instanceSc //
                    ->needs(section);
            } else {
                --requiredCount;
                instanceSc //
                    ->remove_needs(section);
            }
            section //
                ->required(req);
            section //
                ->ignore_case(req);
            required(requiredCount > 0);
        }
        return *this;
    }
References instanceSc, required(), and requiredCount.
Referenced by net::config::ConfigSection::required().
setDisabled()
ConfigInstance & net::config::ConfigInstance::setDisabled (bool disabled = true)
Definition at line 192 of file ConfigInstance.cpp.
{
        disableOpt //
            ->default_str(disabled ? "true" : "false")
            ->clear();
        utils::Config::disabled(instanceSc, disabled);
        return *this;
    }
References utils::Config::disabled(), disableOpt, and instanceSc.
setInstanceName()
void net::config::ConfigInstance::setInstanceName (const std::string & instanceName)
Definition at line 100 of file ConfigInstance.cpp.
{
        this->instanceName = instanceName;
    }
References instanceName.
Friends And Related Symbol Documentation
net::config::ConfigSection
friend class net::config::ConfigSection friend
Definition at line 126 of file ConfigInstance.h.
Member Data Documentation
configSections
std::vector<std::shared_ptr<net::config::ConfigSection> > net::config::ConfigInstance::configSections private
Definition at line 124 of file ConfigInstance.h.
Referenced by addSection().
disableOpt
CLI::Option* net::config::ConfigInstance::disableOpt = nullptr private
Definition at line 122 of file ConfigInstance.h.
Referenced by ConfigInstance(), configurable(), getDisabled(), and setDisabled().
instanceName
std::string net::config::ConfigInstance::instanceName private
Definition at line 116 of file ConfigInstance.h.
Referenced by ConfigInstance(), getInstanceName(), and setInstanceName().
instanceSc
CLI::App* net::config::ConfigInstance::instanceSc = nullptr private
Definition at line 121 of file ConfigInstance.h.
Referenced by ConfigInstance(), configurable(), get(), getSection(), getSection(), gotSection(), newSection(), required(), required(), setDisabled(), and ~ConfigInstance().
nameAnonymous
const std::string net::config::ConfigInstance::nameAnonymous = "<anonymous>" static private
Definition at line 117 of file ConfigInstance.h.
Referenced by getInstanceName().
requiredCount
uint8_t net::config::ConfigInstance::requiredCount = 0 private
Definition at line 114 of file ConfigInstance.h.
Referenced by getRequired(), and required().
role
Role net::config::ConfigInstance::role private
Definition at line 119 of file ConfigInstance.h.
Referenced by ConfigInstance(), and getRole().
The documentation for this class was generated from the following files:
net/config/ConfigInstance.h
net/config/ConfigInstanceAPI.hpp
net/config/ConfigInstance.cpp