SNode.C: database::mariadb::MariaDBClientSyncAPI Class Reference
database::mariadb::MariaDBClientSyncAPI Class Reference abstract
#include <MariaDBClientSyncAPI.h>
Public Member Functions
void affectedRows (const std::function< void(int)> &onAffectedRows, const std::function< void(const std::string &, unsigned int)> &onErro)
void fieldCount (const std::function< void(unsigned int)> &onFieldCount, const std::function< void(const std::string &, unsigned int)> &onError)
Protected Member Functions
MariaDBClientSyncAPI ()=default
MariaDBClientSyncAPI (const MariaDBClientSyncAPI &)=default
virtual ~MariaDBClientSyncAPI ()
virtual void execute_sync (MariaDBCommandSync *mariaDBCommand)=0
Detailed Description
Definition at line 59 of file MariaDBClientSyncAPI.h.
Constructor & Destructor Documentation
MariaDBClientSyncAPI() [1/2]
database::mariadb::MariaDBClientSyncAPI::MariaDBClientSyncAPI () protected default
MariaDBClientSyncAPI() [2/2]
database::mariadb::MariaDBClientSyncAPI::MariaDBClientSyncAPI (const MariaDBClientSyncAPI &) protected default
~MariaDBClientSyncAPI()
database::mariadb::MariaDBClientSyncAPI::~MariaDBClientSyncAPI () protected virtual
Definition at line 54 of file MariaDBClientSyncAPI.cpp.
{
    }
Member Function Documentation
affectedRows()
void database::mariadb::MariaDBClientSyncAPI::affectedRows (const std::function< void(int)> & onAffectedRows, const std::function< void(const std::string &, unsigned int)> & onErro)
Definition at line 57 of file MariaDBClientSyncAPI.cpp.
{
        execute_sync(new database::mariadb::commands::sync::MariaDBAffectedRowsCommand(onAffectedRows, onError));
    }
execute_sync()
virtual void database::mariadb::MariaDBClientSyncAPI::execute_sync (MariaDBCommandSync * mariaDBCommand) protected pure virtual
Implemented in database::mariadb::MariaDBClient, and database::mariadb::MariaDBCommandSequence.
Referenced by fieldCount().
fieldCount()
void database::mariadb::MariaDBClientSyncAPI::fieldCount (const std::function< void(unsigned int)> & onFieldCount, const std::function< void(const std::string &, unsigned int)> & onError)
Definition at line 62 of file MariaDBClientSyncAPI.cpp.
{
        execute_sync(new database::mariadb::commands::sync::MariaDBFieldCountCommand(onFieldCount, onError));
    }
References execute_sync(), and database::mariadb::commands::sync::MariaDBFieldCountCommand::MariaDBFieldCountCommand().
The documentation for this class was generated from the following files:
database/mariadb/MariaDBClientSyncAPI.h
database/mariadb/MariaDBClientSyncAPI.cpp