SNode.C: iot::mqtt::server::packets::Pubrec Class Reference
iot::mqtt::server::packets::Pubrec Class Reference
#include <Pubrec.h>
Public Member Functions
Pubrec (uint32_t remainingLength, uint8_t flags)
Public Member Functions inherited from iot::mqtt::packets::Pubrec
Pubrec ()
Pubrec (uint16_t packetIdentifier)
uint16_t getPacketIdentifier () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type, const std::string &name)
ControlPacket (const ControlPacket &)=default
ControlPacket (ControlPacket &&)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
ControlPacket & operator= (ControlPacket &&)=default
std::vector< char > serialize () const
const std::string & getName () const
uint8_t getType () const
uint8_t getFlags () const
Public Member Functions inherited from iot::mqtt::server::ControlPacketDeserializer
~ControlPacketDeserializer () override
Public Member Functions inherited from iot::mqtt::ControlPacketDeserializer
ControlPacketDeserializer ()=default
ControlPacketDeserializer (uint32_t remainingLength, uint8_t flags, uint8_t mustFlags)
ControlPacketDeserializer & operator= (const ControlPacketDeserializer &)=default
std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
uint32_t getRemainingLength () const
bool isComplete () const
bool isError () const
std::size_t getConsumed () const
Private Member Functions
std::size_t deserializeVP (iot::mqtt::MqttContext *mqttContext) override
void deliverPacket (iot::mqtt::server::Mqtt *mqtt) override
Additional Inherited Members
Protected Attributes inherited from iot::mqtt::packets::Pubrec
iot::mqtt::types::UInt16 packetIdentifier
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t flags = 0
Protected Attributes inherited from iot::mqtt::ControlPacketDeserializer
bool complete = false
bool error = false
uint32_t remainingLength = 0
std::size_t consumed = 0
Detailed Description
Definition at line 41 of file Pubrec.h.
Constructor & Destructor Documentation
Pubrec()
iot::mqtt::server::packets::Pubrec::Pubrec (uint32_t remainingLength, uint8_t flags)
Definition at line 30 of file Pubrec.cpp.
        : iot::mqtt::server::ControlPacketDeserializer(remainingLength, flags, MQTT_PUBREC_FLAGS) {
        this->flags = flags;
    }
References iot::mqtt::ControlPacket::flags.
Referenced by iot::mqtt::server::Mqtt::createControlPacketDeserializer().
Member Function Documentation
deliverPacket()
void iot::mqtt::server::packets::Pubrec::deliverPacket (iot::mqtt::server::Mqtt * mqtt) override private virtual
Implements iot::mqtt::server::ControlPacketDeserializer.
Definition at line 45 of file Pubrec.cpp.
{
        mqtt->printVP(*this);
        mqtt->_onPubrec(*this);
    }
References iot::mqtt::Mqtt::_onPubrec(), and iot::mqtt::Mqtt::printVP().
deserializeVP()
std::size_t iot::mqtt::server::packets::Pubrec::deserializeVP (iot::mqtt::MqttContext * mqttContext) override private virtual
Implements iot::mqtt::ControlPacketDeserializer.
Definition at line 35 of file Pubrec.cpp.
{
        // V-Header
        const std::size_t consumed = packetIdentifier.deserialize(mqttContext);
        complete = packetIdentifier.isComplete();
        // no Payload
        return consumed;
    }
The documentation for this class was generated from the following files:
iot/mqtt/server/packets/Pubrec.h
iot/mqtt/server/packets/Pubrec.cpp