SNode.C: database::mariadb::MariaDBCommandSync Class Reference
database::mariadb::MariaDBCommandSync Class Reference abstract
#include <MariaDBCommandSync.h>
Public Member Functions
MariaDBCommand (const std::string &name, const std::function< void(const std::string &, unsigned int)> &onError)
const std::string & commandName ()
int commandStart (MYSQL *mysql, const utils::Timeval &currentTime)
void setMariaDBConnection (MariaDBConnection *mariaDBConnection)
virtual bool commandCompleted ()=0
virtual void commandError (const std::string &errorString, unsigned int errorNumber)=0
virtual std::string commandInfo ()
Protected Attributes
MYSQL * mysql = nullptr
const std::function< void(const std::string &, unsigned int)> onError
Private Member Functions
int commandContinue (int status) final
virtual int commandStart ()=0
Private Attributes
std::string name
MariaDBConnection * mariaDBConnection = nullptr
utils::Timeval startTime = 0
Detailed Description
Definition at line 32 of file MariaDBCommandSync.h.
Member Function Documentation
commandCompleted()
virtual bool database::mariadb::MariaDBCommand::commandCompleted () pure virtual inherited
Implemented in database::mariadb::commands::async::MariaDBAutoCommitCommand, database::mariadb::commands::async::MariaDBCommitCommand, database::mariadb::commands::async::MariaDBConnectCommand, database::mariadb::commands::async::MariaDBExecCommand, database::mariadb::commands::async::MariaDBFetchRowCommand, database::mariadb::commands::async::MariaDBFreeResultCommand, database::mariadb::commands::async::MariaDBQueryCommand, database::mariadb::commands::async::MariaDBRollbackCommand, database::mariadb::commands::sync::MariaDBAffectedRowsCommand, database::mariadb::commands::sync::MariaDBFieldCountCommand, and database::mariadb::commands::sync::MariaDBUseResultCommand.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), and database::mariadb::MariaDBConnection::execute_sync().
commandContinue()
int database::mariadb::MariaDBCommandSync::commandContinue (int status) final private virtual
Implements database::mariadb::MariaDBCommand.
Definition at line 29 of file MariaDBCommandSync.cpp.
{
        return 0;
    }
commandError()
virtual void database::mariadb::MariaDBCommand::commandError (const std::string & errorString, unsigned int errorNumber) pure virtual inherited
Implemented in database::mariadb::commands::async::MariaDBAutoCommitCommand, database::mariadb::commands::async::MariaDBCommitCommand, database::mariadb::commands::async::MariaDBConnectCommand, database::mariadb::commands::async::MariaDBExecCommand, database::mariadb::commands::async::MariaDBFetchRowCommand, database::mariadb::commands::async::MariaDBFreeResultCommand, database::mariadb::commands::async::MariaDBQueryCommand, database::mariadb::commands::async::MariaDBRollbackCommand, database::mariadb::commands::sync::MariaDBAffectedRowsCommand, database::mariadb::commands::sync::MariaDBFieldCountCommand, and database::mariadb::commands::sync::MariaDBUseResultCommand.
commandInfo()
std::string database::mariadb::MariaDBCommand::commandInfo () virtual inherited
Reimplemented in database::mariadb::commands::async::MariaDBAutoCommitCommand, database::mariadb::commands::async::MariaDBConnectCommand, database::mariadb::commands::async::MariaDBExecCommand, and database::mariadb::commands::async::MariaDBQueryCommand.
Definition at line 45 of file MariaDBCommand.cpp.
{
        return commandName();
    }
Referenced by database::mariadb::MariaDBConnection::commandCompleted(), and database::mariadb::MariaDBConnection::commandStart().
commandName()
const std::string & database::mariadb::MariaDBCommand::commandName () inherited
Definition at line 49 of file MariaDBCommand.cpp.
{
        return name;
    }
References database::mariadb::MariaDBCommand::name.
Referenced by database::mariadb::commands::async::MariaDBConnectCommand::commandInfo(), database::mariadb::commands::async::MariaDBExecCommand::commandInfo(), and database::mariadb::commands::async::MariaDBQueryCommand::commandInfo().
commandStart() [1/2]
virtual int database::mariadb::MariaDBCommand::commandStart () private pure virtual inherited
Implemented in database::mariadb::commands::async::MariaDBAutoCommitCommand, database::mariadb::commands::async::MariaDBCommitCommand, database::mariadb::commands::async::MariaDBConnectCommand, database::mariadb::commands::async::MariaDBExecCommand, database::mariadb::commands::async::MariaDBFetchRowCommand, database::mariadb::commands::async::MariaDBFreeResultCommand, database::mariadb::commands::async::MariaDBQueryCommand, database::mariadb::commands::async::MariaDBRollbackCommand, database::mariadb::commands::sync::MariaDBAffectedRowsCommand, database::mariadb::commands::sync::MariaDBFieldCountCommand, and database::mariadb::commands::sync::MariaDBUseResultCommand.
Referenced by database::mariadb::MariaDBCommand::commandStart().
commandStart() [2/2]
int database::mariadb::MariaDBCommand::commandStart (MYSQL * mysql, const utils::Timeval & currentTime) inherited
Definition at line 34 of file MariaDBCommand.cpp.
{
        this->mysql = mysql;
        startTime = currentTime;
        return commandStart();
    }
References database::mariadb::MariaDBCommand::commandStart(), utils::Timeval::operator=(), and database::mariadb::MariaDBCommand::startTime.
MariaDBCommand()
database::mariadb::MariaDBCommand::MariaDBCommand (const std::string & name, const std::function< void(const std::string &, unsigned int)> & onError)
Definition at line 46 of file MariaDBCommand.cpp.
        : name(name)
        , onError(onError) {
    }
setMariaDBConnection()
void database::mariadb::MariaDBCommand::setMariaDBConnection (MariaDBConnection * mariaDBConnection) inherited
Definition at line 41 of file MariaDBCommand.cpp.
{
        this->mariaDBConnection = mariaDBConnection;
    }
References database::mariadb::MariaDBCommand::mariaDBConnection.
Referenced by database::mariadb::MariaDBConnection::commandStart().
Member Data Documentation
mariaDBConnection
MariaDBConnection* database::mariadb::MariaDBCommand::mariaDBConnection = nullptr private inherited
Definition at line 67 of file MariaDBCommand.h.
Referenced by database::mariadb::MariaDBCommand::setMariaDBConnection().
mysql
MYSQL* database::mariadb::MariaDBCommand::mysql = nullptr protected inherited
Definition at line 70 of file MariaDBCommand.h.
name
std::string database::mariadb::MariaDBCommand::name private inherited
Definition at line 65 of file MariaDBCommand.h.
Referenced by database::mariadb::MariaDBCommand::commandName(), and database::mariadb::MariaDBCommand::MariaDBCommand().
onError
const std::function<void(const std::string&, unsigned int)> database::mariadb::MariaDBCommand::onError protected inherited
Definition at line 72 of file MariaDBCommand.h.
startTime
utils::Timeval database::mariadb::MariaDBCommand::startTime = 0 private inherited
Definition at line 75 of file MariaDBCommand.h.
Referenced by database::mariadb::MariaDBCommand::commandStart().
The documentation for this class was generated from the following files:
database/mariadb/MariaDBCommandSync.h
database/mariadb/MariaDBCommandSync.cpp