SNode.C: iot::mqtt_fast::packets::Connack Class Reference
iot::mqtt_fast::packets::Connack Class Reference
#include <Connack.h>
Public Member Functions
Connack (uint8_t reason, uint8_t flags)
Connack (mqtt_fast::ControlPacketFactory &controlPacketFactory)
uint8_t getFlags () const
uint8_t getReason () const
Public Member Functions inherited from iot::mqtt_fast::ControlPacket
ControlPacket (uint8_t type, uint8_t reserved=0)
ControlPacket (iot::mqtt_fast::ControlPacketFactory &controlPacketFactory)
ControlPacket (const ControlPacket &)=delete
ControlPacket (ControlPacket &&)=delete
ControlPacket & operator= (const ControlPacket &)=delete
ControlPacket & operator= (ControlPacket &&)=delete
uint8_t getType () const
uint8_t getReserved () const
uint64_t getRemainingLength () const
std::vector< char > getPacket ()
bool isError () const
Private Attributes
uint8_t flags = 0
uint8_t reason = 0
Additional Inherited Members
Protected Member Functions inherited from iot::mqtt_fast::ControlPacket
std::vector< char > & getValue ()
uint8_t getInt8 ()
uint16_t getInt16 ()
uint32_t getInt32 ()
uint64_t getInt64 ()
uint32_t getIntV ()
std::string getString ()
std::string getStringRaw ()
std::list< uint8_t > getUint8ListRaw ()
void putInt8 (uint8_t value)
void putInt16 (uint16_t value)
void putInt32 (uint32_t value)
void putInt64 (uint64_t value)
void putIntV (uint32_t value)
void putString (const std::string &value)
void putStringRaw (const std::string &value)
void putUint8ListRaw (const std::list< uint8_t > &value)
bool isError ()
Protected Attributes inherited from iot::mqtt_fast::ControlPacket
bool error = false
Detailed Description
Definition at line 71 of file Connack.h.
Constructor & Destructor Documentation
Connack() [1/2]
iot::mqtt_fast::packets::Connack::Connack (uint8_t reason, uint8_t flags) explicit
Definition at line 50 of file Connack.cpp.
        : iot::mqtt_fast::ControlPacket(MQTT_CONNACK)
        , flags(flags)
        , reason(reason) {
        // V-Header
        putInt8(this->flags);
        putInt8(this->reason);
        // no Payload
    }
References iot::mqtt_fast::ControlPacket::ControlPacket(), flags, iot::mqtt_fast::ControlPacket::putInt8(), and reason.
Referenced by iot::mqtt_fast::SocketContext::sendConnack().
Connack() [2/2]
iot::mqtt_fast::packets::Connack::Connack (mqtt_fast::ControlPacketFactory & controlPacketFactory) explicit
Definition at line 61 of file Connack.cpp.
        : iot::mqtt_fast::ControlPacket(controlPacketFactory) {
        // V-Header
        flags = getInt8();
        reason = getInt8();
        // no Payload
        error = isError();
    }
References iot::mqtt_fast::ControlPacket::ControlPacket(), iot::mqtt_fast::ControlPacket::error, flags, iot::mqtt_fast::ControlPacket::getInt8(), iot::mqtt_fast::ControlPacket::isError(), and reason.
Referenced by iot::mqtt_fast::SocketContext::onReceivedFromPeer().
Member Function Documentation
getFlags()
uint8_t iot::mqtt_fast::packets::Connack::getFlags () const
Definition at line 72 of file Connack.cpp.
{
        return flags;
    }
References flags.
getReason()
uint8_t iot::mqtt_fast::packets::Connack::getReason () const
Definition at line 76 of file Connack.cpp.
{
        return reason;
    }
References reason.
Member Data Documentation
flags
uint8_t iot::mqtt_fast::packets::Connack::flags = 0 private
Definition at line 81 of file Connack.h.
Referenced by Connack(), Connack(), and getFlags().
reason
uint8_t iot::mqtt_fast::packets::Connack::reason = 0 private
Definition at line 82 of file Connack.h.
Referenced by Connack(), Connack(), and getReason().
The documentation for this class was generated from the following files:
iot/mqtt-fast/packets/Connack.h
iot/mqtt-fast/packets/Connack.cpp