SNode.C: core::SNodeC Class Reference
core::SNodeC Class Reference
#include <SNodeC.h>
Public Member Functions
SNodeC ()=delete
~SNodeC ()=delete
void * operator new (std::size_t count)=delete
Static Public Member Functions
static void init (int argc, char *argv[])
static int start (const utils::Timeval &timeOut={LONG_MAX, 0})
static void stop ()
static TickStatus tick (const utils::Timeval &timeOut=0)
static void free ()
static State state ()
Detailed Description
Definition at line 35 of file SNodeC.h.
Constructor & Destructor Documentation
SNodeC()
core::SNodeC::SNodeC () delete
~SNodeC()
core::SNodeC::~SNodeC () delete
Member Function Documentation
free()
void core::SNodeC::free () static
Definition at line 49 of file SNodeC.cpp.
                      {
        EventLoop::free();
    }
References core::EventLoop::free().
Referenced by express::WebApp::free().
init()
void core::SNodeC::init (int argc, char * argv[]) static
Definition at line 31 of file SNodeC.cpp.
{
        if (!EventLoop::init(argc, argv)) {
            exit(1);
        }
    }
References core::EventLoop::init().
Referenced by express::WebApp::init().
operator new()
void * core::SNodeC::operator new (std::size_t count) delete
start()
int core::SNodeC::start (const utils::Timeval & timeOut = {LONG_MAX, 0}) static
Definition at line 37 of file SNodeC.cpp.
{
        return EventLoop::start(timeOut);
    }
References core::EventLoop::start().
Referenced by express::WebApp::start().
state()
State core::SNodeC::state () static
Definition at line 53 of file SNodeC.cpp.
{
        return EventLoop::state();
    }
References core::EventLoop::state().
Referenced by core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::realConnect(), core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::realListen(), and express::WebApp::state().
stop()
void core::SNodeC::stop () static
Definition at line 41 of file SNodeC.cpp.
                      {
        EventLoop::stop();
    }
References core::EventLoop::stop().
Referenced by express::WebApp::stop().
tick()
TickStatus core::SNodeC::tick (const utils::Timeval & timeOut = 0) static
Definition at line 45 of file SNodeC.cpp.
{
        return EventLoop::tick(timeOut);
    }
References core::EventLoop::tick().
Referenced by express::WebApp::tick().
The documentation for this class was generated from the following files:
core/SNodeC.h
core/SNodeC.cpp