SNode.C: iot::mqtt::ControlPacket Class Reference
iot::mqtt::ControlPacket Class Reference abstract
#include <ControlPacket.h>
Public Member Functions
ControlPacket (uint8_t type, const std::string &name)
ControlPacket (const ControlPacket &)=default
ControlPacket (ControlPacket &&)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
ControlPacket & operator= (ControlPacket &&)=default
virtual std::vector< char > serializeVP () const =0
std::vector< char > serialize () const
const std::string & getName () const
uint8_t getType () const
uint8_t getFlags () const
Protected Attributes
uint8_t flags = 0
Private Attributes
std::string name
uint8_t type = 0
Detailed Description
Definition at line 69 of file ControlPacket.h.
Constructor & Destructor Documentation
ControlPacket() [1/3]
iot::mqtt::ControlPacket::ControlPacket (uint8_t type, const std::string & name)
Definition at line 48 of file ControlPacket.cpp.
        : name(name)
        , type(type) {
        switch (type) {
            case MQTT_CONNECT:
                flags = MQTT_CONNECT_FLAGS;
                break;
            case MQTT_CONNACK:
                flags = MQTT_CONNACK_FLAGS;
                break;
            case MQTT_PUBLISH:
                // no flags for MQTT_PUBLISH_FLAGS
                break;
            case MQTT_PUBACK:
                flags = MQTT_PUBACK_FLAGS;
                break;
            case MQTT_PUBREC:
                flags = MQTT_PUBREC_FLAGS;
                break;
            case MQTT_PUBREL:
                flags = MQTT_PUBREL_FLAGS;
                break;
            case MQTT_PUBCOMP:
                flags = MQTT_PUBCOMP_FLAGS;
                break;
            case MQTT_SUBSCRIBE:
                flags = MQTT_SUBSCRIBE_FLAGS;
                break;
            case MQTT_SUBACK:
                flags = MQTT_SUBACK_FLAGS;
                break;
            case MQTT_UNSUBSCRIBE:
                flags = MQTT_UNSUBSCRIBE_FLAGS;
                break;
            case MQTT_UNSUBACK:
                flags = MQTT_UNSUBACK_FLAGS;
                break;
            case MQTT_PINGREQ:
                flags = MQTT_PINGREQ_FLAGS;
                break;
            case MQTT_PINGRESP:
                flags = MQTT_PINGRESP_FLAGS;
                break;
            case MQTT_DISCONNECT:
                flags = MQTT_DISCONNECT_FLAGS;
                break;
        }
    }
References flags, name, and type.
Referenced by iot::mqtt::packets::Connack::Connack(), iot::mqtt::packets::Connect::Connect(), iot::mqtt::packets::Disconnect::Disconnect(), iot::mqtt::packets::Pingreq::Pingreq(), iot::mqtt::packets::Pingresp::Pingresp(), iot::mqtt::packets::Puback::Puback(), iot::mqtt::packets::Pubcomp::Pubcomp(), iot::mqtt::packets::Publish::Publish(), iot::mqtt::packets::Pubrec::Pubrec(), iot::mqtt::packets::Pubrel::Pubrel(), iot::mqtt::packets::Suback::Suback(), iot::mqtt::packets::Subscribe::Subscribe(), iot::mqtt::packets::Unsuback::Unsuback(), and iot::mqtt::packets::Unsubscribe::Unsubscribe().
ControlPacket() [2/3]
iot::mqtt::ControlPacket::ControlPacket (const ControlPacket &) default
ControlPacket() [3/3]
iot::mqtt::ControlPacket::ControlPacket (ControlPacket &&) default
~ControlPacket()
iot::mqtt::ControlPacket::~ControlPacket () virtual
Definition at line 97 of file ControlPacket.cpp.
{
    }
Member Function Documentation
getFlags()
uint8_t iot::mqtt::ControlPacket::getFlags () const
Definition at line 119 of file ControlPacket.cpp.
{
        return flags;
    }
References flags.
getName()
const std::string & iot::mqtt::ControlPacket::getName () const
Definition at line 100 of file ControlPacket.cpp.
{
        return name;
    }
References name.
Referenced by iot::mqtt::Mqtt::printVP(), and iot::mqtt::Mqtt::send().
getType()
uint8_t iot::mqtt::ControlPacket::getType () const
Definition at line 115 of file ControlPacket.cpp.
{
        return type;
    }
References type.
operator=() [1/2]
ControlPacket & iot::mqtt::ControlPacket::operator= (const ControlPacket &) default
operator=() [2/2]
ControlPacket & iot::mqtt::ControlPacket::operator= (ControlPacket &&) default
serialize()
std::vector< char > iot::mqtt::ControlPacket::serialize () const
Definition at line 104 of file ControlPacket.cpp.
{
        std::vector<char> variablHeaderPayload = serializeVP();
        const iot::mqtt::FixedHeader fixedHeader(type, flags, static_cast<uint32_t>(variablHeaderPayload.size()));
        std::vector<char> packet = fixedHeader.serialize();
        packet.insert(packet.end(), variablHeaderPayload.begin(), variablHeaderPayload.end());
        return packet;
    }
References iot::mqtt::FixedHeader::FixedHeader(), flags, iot::mqtt::FixedHeader::serialize(), serializeVP(), and type.
Referenced by iot::mqtt::Mqtt::send().
serializeVP()
virtual std::vector< char > iot::mqtt::ControlPacket::serializeVP () const pure virtual
Implemented in iot::mqtt::packets::Connack, iot::mqtt::packets::Connect, iot::mqtt::packets::Disconnect, iot::mqtt::packets::Pingreq, iot::mqtt::packets::Pingresp, iot::mqtt::packets::Puback, iot::mqtt::packets::Pubcomp, iot::mqtt::packets::Publish, iot::mqtt::packets::Pubrec, iot::mqtt::packets::Pubrel, iot::mqtt::packets::Suback, iot::mqtt::packets::Subscribe, iot::mqtt::packets::Unsuback, and iot::mqtt::packets::Unsubscribe.
Referenced by iot::mqtt::Mqtt::printVP(), and serialize().
Member Data Documentation
flags
uint8_t iot::mqtt::ControlPacket::flags = 0 protected
Definition at line 92 of file ControlPacket.h.
Referenced by iot::mqtt::client::packets::Connack::Connack(), iot::mqtt::server::packets::Connect::Connect(), ControlPacket(), iot::mqtt::server::packets::Disconnect::Disconnect(), getFlags(), iot::mqtt::server::packets::Pingreq::Pingreq(), iot::mqtt::client::packets::Pingresp::Pingresp(), iot::mqtt::client::packets::Puback::Puback(), iot::mqtt::server::packets::Puback::Puback(), iot::mqtt::client::packets::Pubcomp::Pubcomp(), iot::mqtt::server::packets::Pubcomp::Pubcomp(), iot::mqtt::packets::Publish::Publish(), iot::mqtt::client::packets::Publish::Publish(), iot::mqtt::server::packets::Publish::Publish(), iot::mqtt::client::packets::Pubrec::Pubrec(), iot::mqtt::server::packets::Pubrec::Pubrec(), iot::mqtt::client::packets::Pubrel::Pubrel(), iot::mqtt::server::packets::Pubrel::Pubrel(), serialize(), iot::mqtt::client::packets::Suback::Suback(), iot::mqtt::server::packets::Subscribe::Subscribe(), iot::mqtt::client::packets::Unsuback::Unsuback(), and iot::mqtt::server::packets::Unsubscribe::Unsubscribe().
name
std::string iot::mqtt::ControlPacket::name private
Definition at line 88 of file ControlPacket.h.
Referenced by ControlPacket(), and getName().
type
uint8_t iot::mqtt::ControlPacket::type = 0 private
Definition at line 89 of file ControlPacket.h.
Referenced by ControlPacket(), getType(), and serialize().
The documentation for this class was generated from the following files:
iot/mqtt/ControlPacket.h
iot/mqtt/ControlPacket.cpp