SNode.C: iot::mqtt::server::broker::RetainTree::TopicLevel Class Reference
iot::mqtt::server::broker::RetainTree::TopicLevel Class Reference
Public Member Functions
TopicLevel (iot::mqtt::server::broker::Broker *broker)
void retain (const Message &message, std::string topic)
bool release (std::string topic)
void appear (const std::string &clientId, std::string topic, uint8_t qoS)
std::list< std::pair< std::string, std::string > > getRetainTree () const
TopicLevel & fromJson (const nlohmann::json &json)
nlohmann::json toJson () const
void clear ()
Private Member Functions
void appear (const std::string &clientId, uint8_t clientQoS)
std::list< std::pair< std::string, std::string > > getRetainTree (const std::string &absoluteParentTopicLevel) const
Private Attributes
Message message
std::map< std::string, TopicLevel > subTopicLevels
iot::mqtt::server::broker::Broker * broker = nullptr
Detailed Description
Definition at line 82 of file RetainTree.h.
Constructor & Destructor Documentation
TopicLevel()
iot::mqtt::server::broker::RetainTree::TopicLevel::TopicLevel (iot::mqtt::server::broker::Broker * broker) explicit
Definition at line 101 of file RetainTree.cpp.
        : broker(broker) {
    }
Referenced by clear(), fromJson(), retain(), and iot::mqtt::server::broker::RetainTree::RetainTree().
Member Function Documentation
appear() [1/2]
void iot::mqtt::server::broker::RetainTree::TopicLevel::appear (const std::string & clientId, std::string topic, uint8_t qoS)
Definition at line 159 of file RetainTree.cpp.
{
        if (topic.empty()) {
            if (!message.getTopic().empty()) {
                LOG(INFO) << "MQTT Broker: Retained Topic found:";
                LOG(INFO) << "MQTT Broker:   Topic: " << message.getTopic();
                LOG(INFO) << "MQTT Broker:   Message:\n" << iot::mqtt::Mqtt::toHexString(message.getMessage());
                LOG(DEBUG) << "MQTT Broker:     QoS: " << static_cast<uint16_t>(message.getQoS());
                LOG(DEBUG) << "MQTT Broker:   Client:";
                LOG(DEBUG) << "MQTT Broker:     QoS: " << static_cast<uint16_t>(qoS);
                LOG(INFO) << "MQTT Broker: Distributing message ...";
                broker->sendPublish(clientId, message, std::min(message.getQoS(), qoS), true);
                LOG(INFO) << "MQTT Broker: ... distributing message completed";
            }
        } else {
            const std::string topicLevel = topic.substr(0, topic.find('/'));
            topic.erase(0, topicLevel.size() + 1);
            auto foundNode = subTopicLevels.find(topicLevel);
            if (foundNode != subTopicLevels.end()) {
                foundNode->second.appear(clientId, topic, qoS);
            } else if (topicLevel == "+") {
                for (auto& [notUsed, subTopicLevel] : subTopicLevels) {
                    subTopicLevel.appear(clientId, topic, qoS);
                }
            } else if (topicLevel == "#") {
                appear(clientId, qoS);
            }
        }
    }
References appear(), appear(), iot::mqtt::server::broker::Message::getMessage(), iot::mqtt::server::broker::Message::getQoS(), iot::mqtt::server::broker::Message::getTopic(), message, iot::mqtt::server::broker::Broker::sendPublish(), subTopicLevels, and iot::mqtt::Mqtt::toHexString().
Referenced by iot::mqtt::server::broker::RetainTree::appear(), and appear().
appear() [2/2]
void iot::mqtt::server::broker::RetainTree::TopicLevel::appear (const std::string & clientId, uint8_t clientQoS) private
Definition at line 195 of file RetainTree.cpp.
{
        if (!message.getTopic().empty()) {
            LOG(INFO) << "MQTT Broker: Retained Topic found:";
            LOG(INFO) << "MQTT Broker:   Topic: " << message.getTopic();
            LOG(INFO) << "MQTT Broker:   Message:\n" << iot::mqtt::Mqtt::toHexString(message.getMessage());
            LOG(DEBUG) << "MQTT Broker:     QoS: " << static_cast<uint16_t>(message.getQoS());
            LOG(DEBUG) << "MQTT Broker:   Client:";
            LOG(DEBUG) << "MQTT Broker:     QoS: " << static_cast<uint16_t>(clientQoS);
            LOG(INFO) << "MQTT Broker: Distributing message ...";
            broker->sendPublish(clientId, message, std::min(message.getQoS(), clientQoS), true);
            LOG(INFO) << "MQTT Broker: ... distributing message completed";
        }
        for (auto& [topicLevel, subTopicLevel] : subTopicLevels) {
            subTopicLevel.appear(clientId, clientQoS);
        }
    }
References appear(), iot::mqtt::server::broker::Message::getMessage(), iot::mqtt::server::broker::Message::getQoS(), iot::mqtt::server::broker::Message::getTopic(), message, iot::mqtt::server::broker::Broker::sendPublish(), subTopicLevels, and iot::mqtt::Mqtt::toHexString().
Referenced by appear(), and appear().
clear()
void iot::mqtt::server::broker::RetainTree::TopicLevel::clear ()
Definition at line 244 of file RetainTree.cpp.
{
        *this = TopicLevel(broker);
    }
References TopicLevel().
Referenced by iot::mqtt::server::broker::RetainTree::clear().
fromJson()
RetainTree::TopicLevel & iot::mqtt::server::broker::RetainTree::TopicLevel::fromJson (const nlohmann::json & json)
Definition at line 105 of file RetainTree.cpp.
{
        subTopicLevels.clear();
        message.fromJson(json.value("message", nlohmann::json()));
        if (json.contains("topic_level")) {
            for (const auto& topicLevelItem : json["topic_level"].items()) {
                subTopicLevels.emplace(topicLevelItem.key(), TopicLevel(broker).fromJson(topicLevelItem.value()));
            }
        }
        return *this;
    }
References iot::mqtt::server::broker::Message::fromJson(), fromJson(), message, subTopicLevels, and TopicLevel().
Referenced by iot::mqtt::server::broker::RetainTree::fromJson(), and fromJson().
getRetainTree() [1/2]
std::list< std::pair< std::string, std::string > > iot::mqtt::server::broker::RetainTree::TopicLevel::getRetainTree () const
Definition at line 191 of file RetainTree.cpp.
{
        return getRetainTree("");
    }
References getRetainTree().
Referenced by iot::mqtt::server::broker::RetainTree::getRetainTree().
getRetainTree() [2/2]
std::list< std::pair< std::string, std::string > > iot::mqtt::server::broker::RetainTree::TopicLevel::getRetainTree (const std::string & absoluteParentTopicLevel) const private
Definition at line 215 of file RetainTree.cpp.
{
        std::list<std::pair<std::string, std::string>> topicLevelTree;
        for (const auto& [topicLevel, subTopicLevel] : subTopicLevels) {
            const std::string absoluteTopicLevel = absoluteParentTopicLevel + topicLevel;
            if (!subTopicLevel.message.getMessage().empty()) {
                topicLevelTree.emplace_back(absoluteTopicLevel, subTopicLevel.message.getMessage());
            }
            topicLevelTree.splice(topicLevelTree.end(), subTopicLevel.getRetainTree(absoluteTopicLevel + "/"));
        }
        return topicLevelTree;
    }
References iot::mqtt::server::broker::Message::getMessage(), getRetainTree(), message, and subTopicLevels.
Referenced by getRetainTree(), and getRetainTree().
release()
bool iot::mqtt::server::broker::RetainTree::TopicLevel::release (std::string topic)
Definition at line 135 of file RetainTree.cpp.
{
        if (topic.empty()) {
            LOG(DEBUG) << "MQTT Broker: Release retained:";
            LOG(DEBUG) << "MQTT Broker:   Topic: " << message.getTopic();
            message = Message();
        } else {
            const std::string topicLevel = topic.substr(0, topic.find('/'));
            auto&& it = subTopicLevels.find(topicLevel);
            if (it != subTopicLevels.end()) {
                topic.erase(0, topicLevel.size() + 1);
                if (it->second.release(topic)) {
                    LOG(DEBUG) << "               Erase: " << topicLevel;
                    subTopicLevels.erase(it);
                }
            }
        }
        return subTopicLevels.empty() && message.getMessage().empty();
    }
References iot::mqtt::server::broker::Message::getMessage(), iot::mqtt::server::broker::Message::getTopic(), iot::mqtt::server::broker::Message::Message(), message, iot::mqtt::server::broker::Message::operator=(), release(), and subTopicLevels.
Referenced by iot::mqtt::server::broker::RetainTree::release(), release(), and iot::mqtt::server::broker::RetainTree::retain().
retain()
void iot::mqtt::server::broker::RetainTree::TopicLevel::retain (const Message & message, std::string topic)
Definition at line 118 of file RetainTree.cpp.
{
        if (topic.empty()) {
            LOG(DEBUG) << "MQTT Broker: Retain:";
            LOG(DEBUG) << "MQTT Broker:   Topic: " << message.getTopic();
            LOG(DEBUG) << "MQTT Broker:   Message:\n" << iot::mqtt::Mqtt::toHexString(message.getMessage());
            LOG(DEBUG) << "MQTT Broker:     QoS: " << static_cast<uint16_t>(message.getQoS());
            this->message = message;
        } else {
            const std::string topicLevel = topic.substr(0, topic.find('/'));
            topic.erase(0, topicLevel.size() + 1);
            subTopicLevels.insert({topicLevel, RetainTree::TopicLevel(broker)}).first->second.retain(message, topic);
        }
    }
References iot::mqtt::server::broker::Message::getMessage(), iot::mqtt::server::broker::Message::getQoS(), iot::mqtt::server::broker::Message::getTopic(), message, iot::mqtt::server::broker::Message::operator=(), retain(), subTopicLevels, iot::mqtt::Mqtt::toHexString(), and TopicLevel().
Referenced by retain(), and iot::mqtt::server::broker::RetainTree::retain().
toJson()
nlohmann::json iot::mqtt::server::broker::RetainTree::TopicLevel::toJson () const
Definition at line 230 of file RetainTree.cpp.
{
        nlohmann::json json;
        if (!message.getMessage().empty()) {
            json["message"] = message.toJson();
        }
        for (const auto& [topicLevel, topicLevelValue] : subTopicLevels) {
            json["topic_level"][topicLevel] = topicLevelValue.toJson();
        }
        return json;
    }
References iot::mqtt::server::broker::Message::getMessage(), message, subTopicLevels, iot::mqtt::server::broker::Message::toJson(), and toJson().
Referenced by iot::mqtt::server::broker::RetainTree::toJson(), and toJson().
Member Data Documentation
broker
iot::mqtt::server::broker::Broker* iot::mqtt::server::broker::RetainTree::TopicLevel::broker = nullptr private
Definition at line 107 of file RetainTree.h.
message
Message iot::mqtt::server::broker::RetainTree::TopicLevel::message private
Definition at line 103 of file RetainTree.h.
Referenced by appear(), appear(), fromJson(), getRetainTree(), release(), retain(), and toJson().
subTopicLevels
std::map<std::string, TopicLevel> iot::mqtt::server::broker::RetainTree::TopicLevel::subTopicLevels private
Definition at line 105 of file RetainTree.h.
Referenced by appear(), appear(), fromJson(), getRetainTree(), release(), retain(), and toJson().
The documentation for this class was generated from the following files:
iot/mqtt/server/broker/RetainTree.h
iot/mqtt/server/broker/RetainTree.cpp