SNode.C: iot::mqtt::server::broker::SubscribtionTree Class Reference
iot::mqtt::server::broker::SubscribtionTree Class Reference
#include <SubscribtionTree.h>
Classes
class TopicLevel
Public Member Functions
SubscribtionTree (iot::mqtt::server::broker::Broker *broker)
void appear (const std::string &clientId)
bool subscribe (const std::string &topic, const std::string &clientId, uint8_t qoS)
void publish (Message &&message)
void unsubscribe (const std::string &topic, const std::string &clientId)
void unsubscribe (const std::string &clientId)
nlohmann::json toJson () const
void fromJson (const nlohmann::json &json)
std::list< std::string > getSubscriptions (const std::string &clientId) const
std::map< std::string, std::list< std::pair< std::string, uint8_t > > > getSubscriptionTree () const
void clear ()
Private Attributes
TopicLevel head
Detailed Description
Definition at line 65 of file SubscribtionTree.h.
Constructor & Destructor Documentation
SubscribtionTree()
iot::mqtt::server::broker::SubscribtionTree::SubscribtionTree (iot::mqtt::server::broker::Broker * broker) explicit
Definition at line 61 of file SubscribtionTree.cpp.
        : head(broker, "") {
    }
References head, and iot::mqtt::server::broker::SubscribtionTree::TopicLevel::TopicLevel().
Referenced by iot::mqtt::server::broker::Broker::Broker().
Member Function Documentation
appear()
void iot::mqtt::server::broker::SubscribtionTree::appear (const std::string & clientId)
Definition at line 65 of file SubscribtionTree.cpp.
{
        head.appear(clientId, "");
    }
References iot::mqtt::server::broker::SubscribtionTree::TopicLevel::appear(), and head.
Referenced by iot::mqtt::server::broker::Broker::restartSession().
clear()
void iot::mqtt::server::broker::SubscribtionTree::clear ()
Definition at line 126 of file SubscribtionTree.cpp.
{
        head.clear();
    }
References iot::mqtt::server::broker::SubscribtionTree::TopicLevel::clear(), and head.
Referenced by iot::mqtt::server::broker::Broker::Broker().
fromJson()
void iot::mqtt::server::broker::SubscribtionTree::fromJson (const nlohmann::json & json)
Definition at line 116 of file SubscribtionTree.cpp.
{
        if (!json.empty()) {
            head.fromJson(json);
        }
    }
References iot::mqtt::server::broker::SubscribtionTree::TopicLevel::fromJson(), and head.
Referenced by iot::mqtt::server::broker::Broker::Broker().
getSubscriptions()
std::list< std::string > iot::mqtt::server::broker::SubscribtionTree::getSubscriptions (const std::string & clientId) const
Definition at line 106 of file SubscribtionTree.cpp.
{
        std::list<std::string> subscriptions = head.getSubscriptions(clientId);
        return subscriptions;
    }
References iot::mqtt::server::broker::SubscribtionTree::TopicLevel::getSubscriptions(), and head.
Referenced by iot::mqtt::server::broker::Broker::getSubscriptions().
getSubscriptionTree()
std::map< std::string, std::list< std::pair< std::string, uint8_t > > > iot::mqtt::server::broker::SubscribtionTree::getSubscriptionTree () const
Definition at line 112 of file SubscribtionTree.cpp.
{
        return head.getSubscriptionTree();
    }
References iot::mqtt::server::broker::SubscribtionTree::TopicLevel::getSubscriptionTree(), and head.
Referenced by iot::mqtt::server::broker::Broker::getSubscriptionTree().
publish()
void iot::mqtt::server::broker::SubscribtionTree::publish (Message && message)
Definition at line 84 of file SubscribtionTree.cpp.
{
        auto hashCount = std::ranges::count(message.getTopic(), '#');
        if (!message.getTopic().empty() && (hashCount == 0 || (hashCount == 1 && message.getTopic().ends_with('#')))) {
            head.publish(message, message.getTopic());
        } else {
            LOG(ERROR) << "MQTT Broker: Publish: Wrong '#' placement: " << message.getTopic();
        }
    }
References iot::mqtt::server::broker::Message::getTopic(), head, and iot::mqtt::server::broker::SubscribtionTree::TopicLevel::publish().
Referenced by iot::mqtt::server::broker::Broker::publish().
subscribe()
bool iot::mqtt::server::broker::SubscribtionTree::subscribe (const std::string & topic, const std::string & clientId, uint8_t qoS)
Definition at line 69 of file SubscribtionTree.cpp.
{
        bool success = false;
        auto hashCount = std::ranges::count(topic, '#');
        if (!topic.empty() && (hashCount == 0 || (hashCount == 1 && topic.ends_with('#')))) {
            head.subscribe(clientId, qoS, topic);
            success = true;
        } else {
            LOG(ERROR) << "MQTT Broker: Subscribe: Wrong '#' placement: " << topic;
        }
        return success;
    }
References head, and iot::mqtt::server::broker::SubscribtionTree::TopicLevel::subscribe().
Referenced by iot::mqtt::server::broker::Broker::subscribe().
toJson()
nlohmann::json iot::mqtt::server::broker::SubscribtionTree::toJson () const
Definition at line 122 of file SubscribtionTree.cpp.
{
        return head.toJson();
    }
References head, and iot::mqtt::server::broker::SubscribtionTree::TopicLevel::toJson().
Referenced by iot::mqtt::server::broker::Broker::~Broker().
unsubscribe() [1/2]
void iot::mqtt::server::broker::SubscribtionTree::unsubscribe (const std::string & clientId)
Definition at line 102 of file SubscribtionTree.cpp.
{
        head.unsubscribe(clientId);
    }
References head, and iot::mqtt::server::broker::SubscribtionTree::TopicLevel::unsubscribe().
Referenced by iot::mqtt::server::broker::Broker::deleteSession(), and iot::mqtt::server::broker::Broker::unsubscribe().
unsubscribe() [2/2]
void iot::mqtt::server::broker::SubscribtionTree::unsubscribe (const std::string & topic, const std::string & clientId)
Definition at line 93 of file SubscribtionTree.cpp.
{
        auto hashCount = std::ranges::count(topic, '#');
        if (!topic.empty() && (hashCount == 0 || (hashCount == 1 && topic.ends_with('#')))) {
            head.unsubscribe(clientId, topic);
        } else {
            LOG(ERROR) << "MQTT Broker: Unsubscribe: Wrong '#' placement: " << topic;
        }
    }
References head, and iot::mqtt::server::broker::SubscribtionTree::TopicLevel::unsubscribe().
Referenced by iot::mqtt::server::broker::Broker::unsubscribe().
Member Data Documentation
head
TopicLevel iot::mqtt::server::broker::SubscribtionTree::head private
Definition at line 122 of file SubscribtionTree.h.
Referenced by appear(), clear(), fromJson(), getSubscriptions(), getSubscriptionTree(), publish(), subscribe(), SubscribtionTree(), toJson(), unsubscribe(), and unsubscribe().
The documentation for this class was generated from the following files:
iot/mqtt/server/broker/SubscribtionTree.h
iot/mqtt/server/broker/SubscribtionTree.cpp