SNode.C: core::pipe::PipeSource Class Reference
core::pipe::PipeSource Class Reference
#include <PipeSource.h>
Public Member Functions
PipeSource (const PipeSource &)=delete
PipeSource & operator= (const PipeSource &)=delete
PipeSource (int fd)
~PipeSource () override
void send (const char *junk, std::size_t junkLen)
void send (const std::string &data)
void eof ()
void setOnError (const std::function< void(int errnum)> &onError)
int getRegisteredFd ()
void enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Member Functions
void writeEvent () override
void unobservedEvent () override
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
Private Member Functions
void terminate () override
virtual void writeTimeout ()
void dispatchEvent () final
void timeoutEvent () final
void onEvent (const utils::Timeval &currentTime) final
virtual void onExit (int sig)
void triggered (const utils::Timeval &currentTime)
void setEnabled (const utils::Timeval &currentTime)
void setDisabled ()
Private Attributes
std::function< void(int errnum)> onError
std::vector< char > writeBuffer
DescriptorEventPublisher & descriptorEventPublisher
int observedFd = -1
bool enabled = false
bool suspended = false
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
int observationCounter = 0
Event event
Detailed Description
Definition at line 35 of file PipeSource.h.
Constructor & Destructor Documentation
PipeSource() [1/2]
core::pipe::PipeSource::PipeSource (const PipeSource &) delete
PipeSource() [2/2]
core::pipe::PipeSource::PipeSource (int fd) explicit
Definition at line 36 of file PipeSource.cpp.
        : core::eventreceiver::WriteEventReceiver("PipeSource fd = " + std::to_string(fd), 60) {
        WriteEventReceiver::enable(fd);
        WriteEventReceiver::suspend();
    }
References core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::suspend(), and core::eventreceiver::WriteEventReceiver::WriteEventReceiver().
Referenced by core::pipe::Pipe::Pipe().
~PipeSource()
core::pipe::PipeSource::~PipeSource () override
Definition at line 42 of file PipeSource.cpp.
{
        close(getRegisteredFd());
    }
References core::DescriptorEventReceiver::getRegisteredFd().
Member Function Documentation
checkTimeout()
void core::DescriptorEventReceiver::checkTimeout (const utils::Timeval & currentTime) inherited
Definition at line 159 of file DescriptorEventReceiver.cpp.
{
        if (maxInactivity > 0 && currentTime - lastTriggered >= maxInactivity) {
            timeoutEvent();
        }
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), utils::Timeval::operator>(), utils::Timeval::operator>=(), and core::DescriptorEventReceiver::timeoutEvent().
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents().
destruct()
void core::EventReceiver::destruct () virtual inherited
Reimplemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, and database::mariadb::MariaDBCommandStartEvent.
Definition at line 31 of file EventReceiver.cpp.
{
        delete this;
    }
Referenced by core::EventMultiplexer::EventQueue::clear().
disable()
void core::DescriptorEventReceiver::disable () inherited
Definition at line 67 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!isSuspended()) {
                suspend();
            }
            enabled = false;
            descriptorEventPublisher.disable(this);
        } else {
            LOG(TRACE) << "Double disable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::disable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::observedFd, and core::DescriptorEventReceiver::suspend().
Referenced by core::eventreceiver::AcceptEventReceiver::acceptTimeout(), database::mariadb::MariaDBConnection::commandContinue(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectEvent(), core::eventreceiver::ConnectEventReceiver::connectTimeout(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectTimeout(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), eof(), core::eventreceiver::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSink::readEvent(), core::eventreceiver::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::DescriptorEventReceiver::terminate(), core::socket::stream::SocketWriter< PhysicalSocketT >::terminate(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), writeEvent(), core::eventreceiver::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
dispatchEvent()
void core::eventreceiver::WriteEventReceiver::dispatchEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 41 of file WriteEventReceiver.cpp.
{
        writeEvent();
    }
References core::eventreceiver::WriteEventReceiver::writeEvent().
enable()
void core::DescriptorEventReceiver::enable (int fd) inherited
Definition at line 50 of file DescriptorEventReceiver.cpp.
{
        if (!enabled) {
            observedFd = fd;
            enabled = true;
            descriptorEventPublisher.enable(this);
        } else {
            LOG(TRACE) << "Double enable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::enable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), and core::DescriptorEventReceiver::observedFd.
Referenced by core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >::connectTimeout(), core::pipe::PipeSink::PipeSink(), PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
eof()
void core::pipe::PipeSource::eof ()
Definition at line 62 of file PipeSource.cpp.
{
        WriteEventReceiver::disable();
    }
References core::DescriptorEventReceiver::disable().
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 43 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
getObservationCounter()
int core::Observer::getObservationCounter () inline inherited
Definition at line 55 of file DescriptorEventReceiver.h.
{
            return observationCounter;
        }
References core::Observer::observationCounter.
getRegisteredFd()
int core::DescriptorEventReceiver::getRegisteredFd () inherited
Definition at line 46 of file DescriptorEventReceiver.cpp.
{
        return observedFd;
    }
References core::DescriptorEventReceiver::observedFd.
Referenced by core::DescriptorEventPublisher::enable(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::select::DescriptorEventPublisher::muxAdd(), core::poll::PollFdsManager::muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOff(), core::select::DescriptorEventPublisher::muxOff(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOn(), core::select::DescriptorEventPublisher::muxOn(), core::poll::PollFdsManager::muxOn(), core::pipe::PipeSink::readEvent(), writeEvent(), core::pipe::PipeSink::~PipeSink(), and ~PipeSource().
getTimeout()
utils::Timeval core::DescriptorEventReceiver::getTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 141 of file DescriptorEventReceiver.cpp.
{
        return maxInactivity > 0 ? currentTime > lastTriggered ? maxInactivity - (currentTime - lastTriggered) : 0 : TIMEOUT::MAX;
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::DescriptorEventPublisher::getNextTimeout().
isEnabled()
bool core::DescriptorEventReceiver::isEnabled () const inherited
Definition at line 84 of file DescriptorEventReceiver.cpp.
{
        return enabled;
    }
References core::DescriptorEventReceiver::enabled.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >::connectTimeout(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), and core::DescriptorEventReceiver::terminate().
isObserved()
bool core::Observer::isObserved () inline inherited
Definition at line 43 of file DescriptorEventReceiver.h.
{
            return observationCounter > 0;
        }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
isSuspended()
bool core::DescriptorEventReceiver::isSuspended () const inherited
Definition at line 121 of file DescriptorEventReceiver.cpp.
{
        return suspended;
    }
References core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::releaseDisabledEvents(), and send().
observed()
void core::Observer::observed () inline inherited
Definition at line 47 of file DescriptorEventReceiver.h.
{
            observationCounter++;
        }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setEnabled().
onEvent()
void core::DescriptorEventReceiver::onEvent (const utils::Timeval & currentTime) final private virtual inherited
Implements core::EventReceiver.
Definition at line 145 of file DescriptorEventReceiver.cpp.
{
        eventCounter++;
        triggered(currentTime);
        dispatchEvent();
    }
References core::DescriptorEventReceiver::dispatchEvent(), core::DescriptorEventReceiver::eventCounter, and core::DescriptorEventReceiver::triggered().
onExit()
void core::DescriptorEventReceiver::onExit (int sig) private virtual inherited
Definition at line 152 of file DescriptorEventReceiver.cpp.
{
    }
Referenced by core::DescriptorEventPublisher::sigExit().
operator=()
PipeSource & core::pipe::PipeSource::operator= (const PipeSource &) delete
relax()
void core::EventReceiver::relax () inherited
Definition at line 39 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
resume()
void core::DescriptorEventReceiver::resume () inherited
Definition at line 104 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (suspended) {
                suspended = false;
                lastTriggered = utils::Timeval::currentTime();
                if (isObserved()) {
                    descriptorEventPublisher.resume(this);
                }
            } else {
                LOG(TRACE) << "Double resume: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "Resume while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::Observer::isObserved(), core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::observedFd, utils::Timeval::operator=(), core::DescriptorEventPublisher::resume(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), send(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
send() [1/2]
void core::pipe::PipeSource::send (const char * junk, std::size_t junkLen)
Definition at line 50 of file PipeSource.cpp.
{
        writeBuffer.insert(writeBuffer.end(), junk, junk + junkLen);
        if (WriteEventReceiver::isSuspended()) {
            WriteEventReceiver::resume();
        }
    }
References core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), and writeBuffer.
Referenced by send().
send() [2/2]
void core::pipe::PipeSource::send (const std::string & data)
Definition at line 58 of file PipeSource.cpp.
{
        send(data.data(), data.size());
    }
References send().
setDisabled()
void core::DescriptorEventReceiver::setDisabled () private inherited
Definition at line 80 of file DescriptorEventReceiver.cpp.
{
        unObserved();
    }
References core::Observer::unObserved().
setEnabled()
void core::DescriptorEventReceiver::setEnabled (const utils::Timeval & currentTime) private inherited
Definition at line 61 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
        observed();
    }
References core::DescriptorEventReceiver::lastTriggered, core::Observer::observed(), and utils::Timeval::operator=().
Referenced by core::DescriptorEventPublisher::enable().
setOnError()
void core::pipe::PipeSource::setOnError (const std::function< void(int errnum)> & onError)
Definition at line 46 of file PipeSource.cpp.
{
        this->onError = onError;
    }
References onError.
setTimeout()
void core::DescriptorEventReceiver::setTimeout (const utils::Timeval & timeout) inherited
Definition at line 131 of file DescriptorEventReceiver.cpp.
{
        if (timeout == TIMEOUT::DEFAULT) {
            this->maxInactivity = initialTimeout;
        } else {
            this->maxInactivity = timeout;
        }
        triggered(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::TIMEOUT::DEFAULT, core::DescriptorEventReceiver::initialTimeout, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator=(), utils::Timeval::operator==(), and core::DescriptorEventReceiver::triggered().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::initConnectEvent(), core::socket::stream::SocketReader< PhysicalSocketT >::terminate(), and core::socket::stream::SocketWriter< PhysicalSocketT >::terminate().
span()
void core::EventReceiver::span () inherited
Definition at line 35 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::FileReader(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
suspend()
void core::DescriptorEventReceiver::suspend () inherited
Definition at line 88 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!suspended) {
                suspended = true;
                if (isObserved()) {
                    descriptorEventPublisher.suspend(this);
                }
            } else {
                LOG(TRACE) << "Double suspend: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "Suspend while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::Observer::isObserved(), core::DescriptorEventReceiver::observedFd, core::DescriptorEventPublisher::suspend(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), and writeEvent().
terminate()
void core::pipe::PipeSource::terminate () override private virtual
Reimplemented from core::DescriptorEventReceiver.
Definition at line 89 of file PipeSource.cpp.
{
        WriteEventReceiver::terminate();
    }
References core::DescriptorEventReceiver::terminate().
timeoutEvent()
void core::eventreceiver::WriteEventReceiver::timeoutEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 45 of file WriteEventReceiver.cpp.
{
        writeTimeout();
    }
References core::eventreceiver::WriteEventReceiver::writeTimeout().
triggered()
void core::DescriptorEventReceiver::triggered (const utils::Timeval & currentTime) private inherited
Definition at line 155 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
    }
References core::DescriptorEventReceiver::lastTriggered, and utils::Timeval::operator=().
Referenced by core::DescriptorEventReceiver::onEvent(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::DescriptorEventReceiver::setTimeout().
unObserved()
void core::Observer::unObserved () inline inherited
Definition at line 51 of file DescriptorEventReceiver.h.
{
            observationCounter--;
        }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setDisabled().
unobservedEvent()
void core::pipe::PipeSource::unobservedEvent () override protected virtual
Implements core::Observer.
Definition at line 85 of file PipeSource.cpp.
{
        delete this;
    }
writeEvent()
void core::pipe::PipeSource::writeEvent () override protected virtual
Implements core::eventreceiver::WriteEventReceiver.
Definition at line 66 of file PipeSource.cpp.
{
        ssize_t ret = core::system::write(
            getRegisteredFd(), writeBuffer.data(), (writeBuffer.size() < MAX_SEND_JUNKSIZE) ? writeBuffer.size() : MAX_SEND_JUNKSIZE);
        if (ret > 0) {
            writeBuffer.erase(writeBuffer.begin(), writeBuffer.begin() + ret);
            if (writeBuffer.empty()) {
                WriteEventReceiver::suspend();
            }
        } else if (errno != EAGAIN && errno != EWOULDBLOCK && errno != EINTR) {
            WriteEventReceiver::disable();
            if (onError) {
                onError(errno);
            }
        }
    }
References core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::getRegisteredFd(), onError, core::DescriptorEventReceiver::suspend(), core::system::write(), and writeBuffer.
writeTimeout()
void core::eventreceiver::WriteEventReceiver::writeTimeout () private virtual inherited
Reimplemented in core::socket::stream::tls::TLSHandshake, core::socket::stream::tls::TLSShutdown, and database::mariadb::MariaDBConnection.
Definition at line 37 of file WriteEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
Referenced by core::eventreceiver::WriteEventReceiver::timeoutEvent().
Member Data Documentation
descriptorEventPublisher
DescriptorEventPublisher& core::DescriptorEventReceiver::descriptorEventPublisher private inherited
Definition at line 112 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
enabled
bool core::DescriptorEventReceiver::enabled = false private inherited
Definition at line 116 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
event
Event core::EventReceiver::event private inherited
Definition at line 54 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
eventCounter
int core::DescriptorEventReceiver::eventCounter = 0 private inherited
Definition at line 123 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::onEvent().
initialTimeout
const utils::Timeval core::DescriptorEventReceiver::initialTimeout private inherited
Definition at line 121 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), and core::DescriptorEventReceiver::setTimeout().
lastTriggered
utils::Timeval core::DescriptorEventReceiver::lastTriggered private inherited
Definition at line 119 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setEnabled(), and core::DescriptorEventReceiver::triggered().
maxInactivity
utils::Timeval core::DescriptorEventReceiver::maxInactivity private inherited
Definition at line 120 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::getTimeout(), and core::DescriptorEventReceiver::setTimeout().
observationCounter
int core::Observer::observationCounter = 0 private inherited
Definition at line 62 of file DescriptorEventReceiver.h.
Referenced by core::Observer::getObservationCounter(), core::Observer::isObserved(), core::Observer::observed(), and core::Observer::unObserved().
observedFd
int core::DescriptorEventReceiver::observedFd = -1 private inherited
Definition at line 114 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
onError
std::function<void(int errnum)> core::pipe::PipeSource::onError private
Definition at line 57 of file PipeSource.h.
Referenced by setOnError(), and writeEvent().
suspended
bool core::DescriptorEventReceiver::suspended = false private inherited
Definition at line 117 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
writeBuffer
std::vector<char> core::pipe::PipeSource::writeBuffer private
Definition at line 59 of file PipeSource.h.
Referenced by send(), and writeEvent().
The documentation for this class was generated from the following files:
core/pipe/PipeSource.h
core/pipe/PipeSource.cpp