SNode.C: iot::mqtt::Topic Class Reference
iot::mqtt::Topic Class Reference
#include <Topic.h>
Public Member Functions
Topic (const std::string &name, uint8_t qoS)
Topic (const Topic &)=default
Topic & operator= (const Topic &)=default
~Topic ()
const std::string & getName () const
uint8_t getQoS () const
Private Attributes
std::string name
uint8_t qoS
Detailed Description
Definition at line 54 of file Topic.h.
Constructor & Destructor Documentation
Topic() [1/2]
iot::mqtt::Topic::Topic (const std::string & name, uint8_t qoS)
Definition at line 50 of file Topic.cpp.
        : name(name)
        , qoS(qoS) {
    }
References name, and qoS.
Topic() [2/2]
iot::mqtt::Topic::Topic (const Topic &) default
~Topic()
iot::mqtt::Topic::~Topic ()
Definition at line 55 of file Topic.cpp.
                  {
    }
Member Function Documentation
getName()
const std::string & iot::mqtt::Topic::getName () const
Definition at line 58 of file Topic.cpp.
{
        return name;
    }
References name.
Referenced by iot::mqtt::server::Mqtt::_onSubscribe(), and iot::mqtt::packets::Subscribe::serializeVP().
getQoS()
uint8_t iot::mqtt::Topic::getQoS () const
Definition at line 62 of file Topic.cpp.
{
        return qoS;
    }
References qoS.
Referenced by iot::mqtt::server::Mqtt::_onSubscribe(), and iot::mqtt::packets::Subscribe::serializeVP().
operator=()
Topic & iot::mqtt::Topic::operator= (const Topic &) default
Member Data Documentation
name
std::string iot::mqtt::Topic::name private
Definition at line 67 of file Topic.h.
Referenced by getName(), and Topic().
qoS
uint8_t iot::mqtt::Topic::qoS private
Definition at line 68 of file Topic.h.
Referenced by getQoS(), and Topic().
The documentation for this class was generated from the following files:
iot/mqtt/Topic.h
iot/mqtt/Topic.cpp