SNode.C: core::socket::stream::AutoConnectControl Class Reference
core::socket::stream::AutoConnectControl Class Reference
#include <AutoConnectControl.h>
Public Member Functions
AutoConnectControl ()
AutoConnectControl (const AutoConnectControl &)=delete
AutoConnectControl & operator= (const AutoConnectControl &)=delete
AutoConnectControl (AutoConnectControl &&)=delete
AutoConnectControl & operator= (AutoConnectControl &&)=delete
~AutoConnectControl ()
void stopRetry ()
void stopReconnect ()
void stopReconnectAndRetry ()
bool isRetryEnabled () const
bool isReconnectEnabled () const
Private Member Functions
void armRetryTimer (double timeoutSeconds, const std::function< void()> &dispatcher)
void armReconnectTimer (double timeoutSeconds, const std::function< void()> &dispatcher)
void cancelRetryTimer ()
void cancelReconnectTimer ()
Private Attributes
bool retryEnabled {true}
bool reconnectEnabled {true}
bool cancelRetryScheduled {false}
bool cancelReconnectScheduled {false}
std::unique_ptr< core::timer::Timer > retryTimer
std::unique_ptr< core::timer::Timer > reconnectTimer
Friends
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args>
class SocketClient
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args>
class SocketServer
Detailed Description
Definition at line 70 of file AutoConnectControl.h.
Constructor & Destructor Documentation
AutoConnectControl() [1/3]
core::socket::stream::AutoConnectControl::AutoConnectControl () default
AutoConnectControl() [2/3]
core::socket::stream::AutoConnectControl::AutoConnectControl (const AutoConnectControl &) delete
AutoConnectControl() [3/3]
core::socket::stream::AutoConnectControl::AutoConnectControl (AutoConnectControl &&) delete
~AutoConnectControl()
core::socket::stream::AutoConnectControl::~AutoConnectControl () default
Member Function Documentation
armReconnectTimer()
void core::socket::stream::AutoConnectControl::armReconnectTimer (double timeoutSeconds, const std::function< void()> & dispatcher) private
Definition at line 90 of file AutoConnectControl.cpp.
{
        if (reconnectEnabled) {
            reconnectTimer = std::make_unique<core::timer::Timer>(core::timer::Timer::singleshotTimer(dispatcher, timeoutSeconds));
        }
    }
References reconnectEnabled, reconnectTimer, and core::timer::Timer::singleshotTimer().
armRetryTimer()
void core::socket::stream::AutoConnectControl::armRetryTimer (double timeoutSeconds, const std::function< void()> & dispatcher) private
Definition at line 84 of file AutoConnectControl.cpp.
{
        if (retryEnabled) {
            retryTimer = std::make_unique<core::timer::Timer>(core::timer::Timer::singleshotTimer(dispatcher, timeoutSeconds));
        }
    }
References retryEnabled, retryTimer, and core::timer::Timer::singleshotTimer().
cancelReconnectTimer()
void core::socket::stream::AutoConnectControl::cancelReconnectTimer () private
Definition at line 103 of file AutoConnectControl.cpp.
{
        if (reconnectTimer) {
            reconnectTimer->cancel();
            reconnectTimer.reset();
        }
    }
References core::Timer::cancel(), and reconnectTimer.
Referenced by stopReconnect(), and stopReconnectAndRetry().
cancelRetryTimer()
void core::socket::stream::AutoConnectControl::cancelRetryTimer () private
Definition at line 96 of file AutoConnectControl.cpp.
{
        if (retryTimer) {
            retryTimer->cancel();
            retryTimer.reset();
        }
    }
References core::Timer::cancel(), and retryTimer.
Referenced by stopReconnectAndRetry(), and stopRetry().
isReconnectEnabled()
bool core::socket::stream::AutoConnectControl::isReconnectEnabled () const
Definition at line 80 of file AutoConnectControl.cpp.
{
        return reconnectEnabled;
    }
References reconnectEnabled.
isRetryEnabled()
bool core::socket::stream::AutoConnectControl::isRetryEnabled () const
Definition at line 76 of file AutoConnectControl.cpp.
{
        return retryEnabled;
    }
References retryEnabled.
operator=() [1/2]
AutoConnectControl & core::socket::stream::AutoConnectControl::operator= (AutoConnectControl &&) delete
operator=() [2/2]
AutoConnectControl & core::socket::stream::AutoConnectControl::operator= (const AutoConnectControl &) delete
stopReconnect()
void core::socket::stream::AutoConnectControl::stopReconnect ()
Definition at line 62 of file AutoConnectControl.cpp.
{
        reconnectEnabled = false;
        cancelReconnectTimer();
    }
References cancelReconnectTimer(), and reconnectEnabled.
stopReconnectAndRetry()
void core::socket::stream::AutoConnectControl::stopReconnectAndRetry ()
Definition at line 68 of file AutoConnectControl.cpp.
{
        retryEnabled = false;
        reconnectEnabled = false;
        cancelRetryTimer();
        cancelReconnectTimer();
    }
References cancelReconnectTimer(), cancelRetryTimer(), reconnectEnabled, and retryEnabled.
stopRetry()
void core::socket::stream::AutoConnectControl::stopRetry ()
Definition at line 56 of file AutoConnectControl.cpp.
{
        retryEnabled = false;
        cancelRetryTimer();
    }
References cancelRetryTimer(), and retryEnabled.
Friends And Related Symbol Documentation
SocketClient
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> friend class SocketClient friend
Definition at line 108 of file AutoConnectControl.h.
SocketServer
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> friend class SocketServer friend
Definition at line 113 of file AutoConnectControl.h.
Member Data Documentation
cancelReconnectScheduled
bool core::socket::stream::AutoConnectControl::cancelReconnectScheduled {false} private
Definition at line 100 of file AutoConnectControl.h.
{false};
cancelRetryScheduled
bool core::socket::stream::AutoConnectControl::cancelRetryScheduled {false} private
Definition at line 99 of file AutoConnectControl.h.
{false};
reconnectEnabled
bool core::socket::stream::AutoConnectControl::reconnectEnabled {true} private
Definition at line 97 of file AutoConnectControl.h.
{true};
Referenced by armReconnectTimer(), isReconnectEnabled(), stopReconnect(), and stopReconnectAndRetry().
reconnectTimer
std::unique_ptr<core::timer::Timer> core::socket::stream::AutoConnectControl::reconnectTimer private
Definition at line 103 of file AutoConnectControl.h.
Referenced by armReconnectTimer(), and cancelReconnectTimer().
retryEnabled
bool core::socket::stream::AutoConnectControl::retryEnabled {true} private
Definition at line 96 of file AutoConnectControl.h.
{true};
Referenced by armRetryTimer(), isRetryEnabled(), stopReconnectAndRetry(), and stopRetry().
retryTimer
std::unique_ptr<core::timer::Timer> core::socket::stream::AutoConnectControl::retryTimer private
Definition at line 102 of file AutoConnectControl.h.
Referenced by armRetryTimer(), and cancelRetryTimer().
The documentation for this class was generated from the following files:
core/socket/stream/AutoConnectControl.h
core/socket/stream/AutoConnectControl.cpp