SNode.C: iot::mqtt::server::SharedSocketContextFactory Class Reference
iot::mqtt::server::SharedSocketContextFactory Class Reference abstract
#include <SharedSocketContextFactory.h>
Public Member Functions
SharedSocketContextFactory (const std::string &sessionStoreFileName)
Public Member Functions inherited from core::socket::stream::SocketContextFactory
SocketContextFactory (SocketContextFactory &)=delete
SocketContextFactory (SocketContextFactory &&)=delete
SocketContextFactory & operator= (SocketContextFactory &)=delete
SocketContextFactory & operator= (SocketContextFactory &&)=delete
Private Member Functions
virtual core::socket::stream::SocketContext * create (core::socket::stream::SocketConnection *socketConnection, std::shared_ptr< iot::mqtt::server::broker::Broker > broker)=0
core::socket::stream::SocketContext * create (core::socket::stream::SocketConnection *socketConnection) final
Private Attributes
const std::string sessionStoreFileName
Additional Inherited Members
Protected Member Functions inherited from core::socket::stream::SocketContextFactory
SocketContextFactory ()=default
virtual ~SocketContextFactory ()
Detailed Description
Definition at line 66 of file SharedSocketContextFactory.h.
Constructor & Destructor Documentation
SharedSocketContextFactory()
iot::mqtt::server::SharedSocketContextFactory::SharedSocketContextFactory (const std::string & sessionStoreFileName)
Definition at line 52 of file SharedSocketContextFactory.cpp.
        : sessionStoreFileName(sessionStoreFileName) {
    }
References sessionStoreFileName.
Member Function Documentation
create() [1/2]
core::socket::stream::SocketContext * iot::mqtt::server::SharedSocketContextFactory::create (core::socket::stream::SocketConnection * socketConnection) final private virtual
Implements core::socket::stream::SocketContextFactory.
Definition at line 56 of file SharedSocketContextFactory.cpp.
{
        return create(socketConnection, iot::mqtt::server::broker::Broker::instance(SUBSCRIBTION_MAX_QOS, sessionStoreFileName));
    }
References create(), iot::mqtt::server::broker::Broker::instance(), and sessionStoreFileName.
create() [2/2]
virtual core::socket::stream::SocketContext * iot::mqtt::server::SharedSocketContextFactory::create (core::socket::stream::SocketConnection * socketConnection, std::shared_ptr< iot::mqtt::server::broker::Broker > broker) private pure virtual
Referenced by create().
Member Data Documentation
sessionStoreFileName
const std::string iot::mqtt::server::SharedSocketContextFactory::sessionStoreFileName private
Definition at line 76 of file SharedSocketContextFactory.h.
Referenced by create(), and SharedSocketContextFactory().
The documentation for this class was generated from the following files:
iot/mqtt/server/SharedSocketContextFactory.h
iot/mqtt/server/SharedSocketContextFactory.cpp