SNode.C: net::phy::stream::PhysicalSocket< SocketAddressT > Class Template Reference
net::phy::stream::PhysicalSocket< SocketAddressT > Class Template Reference
#include <PhysicalSocket.h>
Public Types
enum SHUT { WR = SHUT_WR , RD = SHUT_RD , RDWR = SHUT_RDWR }
using Super = net::phy::PhysicalSocket< SocketAddressT >
using SocketAddress = SocketAddressT
enum Flags { NONE = 0 , NONBLOCK = SOCK_NONBLOCK , CLOEXIT = SOCK_CLOEXEC }
Public Member Functions
int shutdown (SHUT how)
int open (const std::map< int, const PhysicalSocketOption > &socketOptions, Flags flags)
int bind (SocketAddress &bindAddress)
bool isValid () const
int getSockError (int &cErrno) const
int getSockName (typename SocketAddress::SockAddr &localSockAddr, typename SocketAddress::SockLen &localSockAddrLen)
int getPeerName (typename SocketAddress::SockAddr &remoteSockAddr, typename SocketAddress::SockLen &remoteSockAddrLen)
SocketAddress getBindAddress () const
int getFd () const
Protected Attributes
SocketAddress bindAddress
int domain = 0
int type = 0
int protocol = 0
Private Member Functions
int setSockopt (int level, int optname, const void *optval, typename SocketAddress::SockLen optlen) const
int getSockopt (int level, int optname, void *optval, typename SocketAddress::SockLen *optlen) const
Private Attributes
int fd = -1
Detailed Description
template<typename SocketAddressT>
class net::phy::stream::PhysicalSocket< SocketAddressT >
Definition at line 32 of file PhysicalSocket.h.
Member Typedef Documentation
SocketAddress
template<typename SocketAddressT > using net::phy::stream::PhysicalSocket< SocketAddressT >::SocketAddress = SocketAddressT
Definition at line 35 of file PhysicalSocket.h.
Super
template<typename SocketAddressT > using net::phy::stream::PhysicalSocket< SocketAddressT >::Super = net::phy::PhysicalSocket<SocketAddressT>
Definition at line 34 of file PhysicalSocket.h.
Member Enumeration Documentation
Flags
template<typename SocketAddressT > enum net::phy::PhysicalSocket::Flags inherited
Enumerator
NONE
NONBLOCK
CLOEXIT
Definition at line 43 of file PhysicalSocket.h.
{ NONE = 0, NONBLOCK = SOCK_NONBLOCK, CLOEXIT = SOCK_CLOEXEC };
SHUT
template<typename SocketAddressT > enum net::phy::stream::PhysicalSocket::SHUT
Enumerator
WR
RD
RDWR
Definition at line 38 of file PhysicalSocket.h.
{ WR = SHUT_WR, RD = SHUT_RD, RDWR = SHUT_RDWR };
Member Function Documentation
bind()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::bind (SocketAddress & bindAddress) inherited
Definition at line 78 of file PhysicalSocket.hpp.
{
        int ret = core::system::bind(core::Descriptor::getFd(), &bindAddress.getSockAddr(), bindAddress.getSockAddrLen());
        if (ret == 0) {
            this->bindAddress = bindAddress;
        }
        return ret;
    }
References core::system::bind(), and core::Descriptor::getFd().
getBindAddress()
template<typename SocketAddress > SocketAddress net::phy::PhysicalSocket< SocketAddress >::getBindAddress () const inherited
Definition at line 123 of file PhysicalSocket.hpp.
{
        return bindAddress;
    }
References net::phy::PhysicalSocket< SocketAddressT >::bindAddress.
getFd()
int core::Descriptor::getFd () const inherited
Definition at line 59 of file Descriptor.cpp.
{
        return fd;
    }
References core::Descriptor::fd.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::bind(), net::phy::PhysicalSocket< SocketAddressT >::getPeerName(), net::phy::PhysicalSocket< SocketAddressT >::getSockName(), net::phy::PhysicalSocket< SocketAddressT >::getSockopt(), core::file::FileReader::isOpen(), net::phy::PhysicalSocket< SocketAddressT >::isValid(), core::file::FileReader::onEvent(), net::un::dgram::Socket::recvFd(), net::un::dgram::Socket::sendFd(), net::phy::PhysicalSocket< SocketAddressT >::setSockopt(), and net::phy::stream::PhysicalSocket< SocketAddressT >::shutdown().
getPeerName()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::getPeerName (typename SocketAddress::SockAddr & remoteSockAddr, typename SocketAddress::SockLen & remoteSockAddrLen) inherited
Definition at line 117 of file PhysicalSocket.hpp.
{
        return core::system::getpeername(core::Descriptor::getFd(), reinterpret_cast<sockaddr*>(&remoteSockAddr), &remoteSockAddrLen);
    }
References core::Descriptor::getFd(), and core::system::getpeername().
getSockError()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::getSockError (int & cErrno) const inherited
Definition at line 94 of file PhysicalSocket.hpp.
{
        typename SocketAddress::SockLen cErrnoLen = sizeof(cErrno);
        return getSockopt(SOL_SOCKET, SO_ERROR, &cErrno, &cErrnoLen);
    }
References net::phy::PhysicalSocket< SocketAddressT >::getSockopt().
getSockName()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::getSockName (typename SocketAddress::SockAddr & localSockAddr, typename SocketAddress::SockLen & localSockAddrLen) inherited
Definition at line 111 of file PhysicalSocket.hpp.
{
        return core::system::getsockname(core::Descriptor::getFd(), reinterpret_cast<sockaddr*>(&localSockAddr), &localSockAddrLen);
    }
References core::Descriptor::getFd(), and core::system::getsockname().
getSockopt()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::getSockopt (int level, int optname, void * optval, typename SocketAddress::SockLen * optlen) const private inherited
Definition at line 106 of file PhysicalSocket.hpp.
{
        return core::system::getsockopt(PhysicalSocket::getFd(), level, optname, optval, optlen);
    }
References core::Descriptor::getFd(), and core::system::getsockopt().
Referenced by net::phy::PhysicalSocket< SocketAddressT >::getSockError(), and net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket().
isValid()
template<typename SocketAddress > bool net::phy::PhysicalSocket< SocketAddress >::isValid () const inherited
Definition at line 89 of file PhysicalSocket.hpp.
{
        return core::Descriptor::getFd() >= 0;
    }
References core::Descriptor::getFd().
open()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::open (const std::map< int, const PhysicalSocketOption > & socketOptions, Flags flags) inherited
Definition at line 58 of file PhysicalSocket.hpp.
{
        int ret = Super::operator=(core::system::socket(domain, type | flags, protocol)).getFd();
        if (ret >= 0) {
            for (const auto& [optName, socketOption] : socketOptions) {
                int setSockoptRet =
                    setSockopt(socketOption.getOptLevel(), socketOption.getOptName(), socketOption.getOptValue(), socketOption.getOptLen());
                ret = (ret >= 0 && setSockoptRet < 0) ? setSockoptRet : ret;
                if (ret < 0) {
                    break;
                }
            }
        }
        return ret;
    }
References net::phy::PhysicalSocket< SocketAddressT >::domain, net::phy::PhysicalSocketOption::getOptLen(), net::phy::PhysicalSocketOption::getOptLevel(), net::phy::PhysicalSocketOption::getOptName(), net::phy::PhysicalSocketOption::getOptValue(), net::phy::PhysicalSocket< SocketAddressT >::protocol, net::phy::PhysicalSocket< SocketAddressT >::setSockopt(), core::system::socket(), and net::phy::PhysicalSocket< SocketAddressT >::type.
setSockopt()
template<typename SocketAddress > int net::phy::PhysicalSocket< SocketAddress >::setSockopt (int level, int optname, const void * optval, typename SocketAddress::SockLen optlen) const private inherited
Definition at line 101 of file PhysicalSocket.hpp.
{
        return core::system::setsockopt(PhysicalSocket::getFd(), level, optname, optval, optlen);
    }
References core::Descriptor::getFd(), and core::system::setsockopt().
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open().
shutdown()
template<typename SocketAddress > int net::phy::stream::PhysicalSocket< SocketAddress >::shutdown (SHUT how)
Definition at line 29 of file PhysicalSocket.hpp.
{
        return core::system::shutdown(core::Descriptor::getFd(), how);
    }
References core::Descriptor::getFd(), and core::system::shutdown().
Member Data Documentation
bindAddress
template<typename SocketAddressT > SocketAddress net::phy::PhysicalSocket< SocketAddressT >::bindAddress protected inherited
Definition at line 82 of file PhysicalSocket.h.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::getBindAddress(), and net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket().
domain
template<typename SocketAddressT > int net::phy::PhysicalSocket< SocketAddressT >::domain = 0 protected inherited
Definition at line 84 of file PhysicalSocket.h.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open(), net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket(), and net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket().
fd
int core::Descriptor::fd = -1 private inherited
Definition at line 48 of file Descriptor.h.
Referenced by core::Descriptor::Descriptor(), core::Descriptor::Descriptor(), core::Descriptor::getFd(), core::Descriptor::operator=(), core::Descriptor::operator=(), and core::Descriptor::~Descriptor().
protocol
template<typename SocketAddressT > int net::phy::PhysicalSocket< SocketAddressT >::protocol = 0 protected inherited
Definition at line 86 of file PhysicalSocket.h.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open(), net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket(), and net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket().
type
template<typename SocketAddressT > int net::phy::PhysicalSocket< SocketAddressT >::type = 0 protected inherited
Definition at line 85 of file PhysicalSocket.h.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open(), net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket(), and net::phy::PhysicalSocket< SocketAddressT >::PhysicalSocket().
The documentation for this class was generated from the following files:
net/phy/stream/PhysicalSocket.h
net/phy/stream/PhysicalSocket.hpp