SNode.C: iot::mqtt::packets::Suback Class Reference
iot::mqtt::packets::Suback Class Reference
#include <Suback.h>
Public Member Functions
Suback ()
Suback (uint16_t packetIdentifier, const std::list< uint8_t > &returnCodes)
uint16_t getPacketIdentifier () const
const std::list< uint8_t > & getReturnCodes () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type, const std::string &name)
ControlPacket (const ControlPacket &)=default
ControlPacket (ControlPacket &&)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
ControlPacket & operator= (ControlPacket &&)=default
std::vector< char > serialize () const
const std::string & getName () const
Protected Attributes
iot::mqtt::types::UInt16 packetIdentifier
iot::mqtt::types::UInt8 returnCode
std::list< uint8_t > returnCodes
int state = 0
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t flags = 0
Private Member Functions
std::vector< char > serializeVP () const override
Additional Inherited Members
Protected Member Functions inherited from iot::mqtt::ControlPacket
uint8_t getType () const
uint8_t getFlags () const
Detailed Description
Definition at line 58 of file Suback.h.
Constructor & Destructor Documentation
Suback() [1/2]
iot::mqtt::packets::Suback::Suback ()
Definition at line 53 of file Suback.cpp.
        : iot::mqtt::ControlPacket(MQTT_SUBACK, "SUBACK") {
    }
References iot::mqtt::ControlPacket::ControlPacket().
Referenced by Suback().
Suback() [2/2]
iot::mqtt::packets::Suback::Suback (uint16_t packetIdentifier, const std::list< uint8_t > & returnCodes)
Definition at line 57 of file Suback.cpp.
        : Suback() {
        this->packetIdentifier = packetIdentifier;
        this->returnCodes = returnCodes;
    }
References iot::mqtt::types::UInt16::operator=(), packetIdentifier, returnCodes, and Suback().
Referenced by iot::mqtt::server::Mqtt::sendSuback().
Member Function Documentation
getPacketIdentifier()
uint16_t iot::mqtt::packets::Suback::getPacketIdentifier () const
Definition at line 71 of file Suback.cpp.
{
        return packetIdentifier;
    }
References packetIdentifier.
Referenced by iot::mqtt::client::Mqtt::_onSuback().
getReturnCodes()
const std::list< uint8_t > & iot::mqtt::packets::Suback::getReturnCodes () const
Definition at line 75 of file Suback.cpp.
{
        return returnCodes;
    }
References returnCodes.
Referenced by iot::mqtt::client::Mqtt::_onSuback().
serializeVP()
std::vector< char > iot::mqtt::packets::Suback::serializeVP () const override private virtual
Implements iot::mqtt::ControlPacket.
Definition at line 63 of file Suback.cpp.
{
        std::vector<char> packet(packetIdentifier.serialize());
        packet.insert(packet.end(), returnCodes.begin(), returnCodes.end());
        return packet;
    }
References packetIdentifier, returnCodes, and iot::mqtt::types::TypeBase< ValueTypeT >::serialize().
Member Data Documentation
packetIdentifier
iot::mqtt::types::UInt16 iot::mqtt::packets::Suback::packetIdentifier protected
Definition at line 71 of file Suback.h.
Referenced by iot::mqtt::client::packets::Suback::deserializeVP(), getPacketIdentifier(), serializeVP(), and Suback().
returnCode
iot::mqtt::types::UInt8 iot::mqtt::packets::Suback::returnCode protected
Definition at line 72 of file Suback.h.
Referenced by iot::mqtt::client::packets::Suback::deserializeVP().
returnCodes
std::list<uint8_t> iot::mqtt::packets::Suback::returnCodes protected
Definition at line 73 of file Suback.h.
Referenced by iot::mqtt::client::packets::Suback::deserializeVP(), getReturnCodes(), serializeVP(), and Suback().
state
int iot::mqtt::packets::Suback::state = 0 protected
Definition at line 75 of file Suback.h.
The documentation for this class was generated from the following files:
iot/mqtt/packets/Suback.h
iot/mqtt/packets/Suback.cpp