SNode.C: net::un::phy::PhysicalSocket< PhysicalPeerSocketT > Class Template Reference
net::un::phy::PhysicalSocket< PhysicalPeerSocketT > Class Template Reference
#include <PhysicalSocket.h>
Public Types
using Super = PhysicalPeerSocketT< net::un::SocketAddress >
Public Member Functions
PhysicalSocket (int type, int protocol)
PhysicalSocket (PhysicalSocket &&physicalSocket) noexcept
PhysicalSocket & operator= (PhysicalSocket &&physicalSocket) noexcept
~PhysicalSocket () override
int bind (SocketAddress &bindAddress)
Private Attributes
int lockFd = -1
Detailed Description
template<template< typename SocketAddressT > typename PhysicalPeerSocketT>
class net::un::phy::PhysicalSocket< PhysicalPeerSocketT >
Definition at line 33 of file PhysicalSocket.h.
Member Typedef Documentation
Super
template<template< typename SocketAddressT > typename PhysicalPeerSocketT> using net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::Super = PhysicalPeerSocketT<net::un::SocketAddress>
Definition at line 35 of file PhysicalSocket.h.
Constructor & Destructor Documentation
PhysicalSocket() [1/2]
template<template< typename SocketAddress > typename PhysicalPeerSocket> net::un::phy::PhysicalSocket< PhysicalPeerSocket >::PhysicalSocket (int type, int protocol)
Definition at line 38 of file PhysicalSocket.hpp.
        : Super(PF_UNIX, type, protocol) {
    }
Referenced by net::un::dgram::Socket::Socket().
PhysicalSocket() [2/2]
template<template< typename SocketAddress > typename PhysicalPeerSocket> net::un::phy::PhysicalSocket< PhysicalPeerSocket >::PhysicalSocket (PhysicalSocket< PhysicalPeerSocketT > && physicalSocket) noexcept
Definition at line 43 of file PhysicalSocket.hpp.
        : Super(std::move(physicalSocket))
        , lockFd(std::exchange(physicalSocket.lockFd, -1)) {
    }
~PhysicalSocket()
template<template< typename SocketAddress > typename PhysicalPeerSocket> net::un::phy::PhysicalSocket< PhysicalPeerSocket >::~PhysicalSocket () override
Definition at line 57 of file PhysicalSocket.hpp.
{
        if (lockFd >= 0) {
            if (std::remove(Super::getBindAddress().getSunPath().data()) == 0) {
                LOG(TRACE) << "Remove sun path: " << Super::getBindAddress().getSunPath();
            } else {
                PLOG(TRACE) << "Remove sun path: " << Super::getBindAddress().getSunPath();
            }
            if (core::system::flock(lockFd, LOCK_UN) == 0) {
                LOG(TRACE) << "Remove lock from file: " << Super::getBindAddress().getSunPath().append(".lock");
            } else {
                PLOG(TRACE) << "Remove lock from file: " << Super::getBindAddress().getSunPath().append(".lock");
            }
            if (std::remove(Super::bindAddress.getSunPath().append(".lock").data()) == 0) {
                LOG(TRACE) << "Remove lock file: " << Super::getBindAddress().getSunPath().append(".lock");
            } else {
                PLOG(TRACE) << "Remove lock file: " << Super::getBindAddress().getSunPath().append(".lock");
            }
            core::system::close(lockFd);
            lockFd = -1;
        }
    }
References core::system::close(), core::system::flock(), and net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::lockFd.
Member Function Documentation
bind()
template<template< typename SocketAddress > typename PhysicalPeerSocket> int net::un::phy::PhysicalSocket< PhysicalPeerSocket >::bind (SocketAddress & bindAddress)
Definition at line 83 of file PhysicalSocket.hpp.
{
        if (!bindAddress.getSunPath().empty()) {
            if ((lockFd = open(bindAddress.getSunPath().append(".lock").data(), O_RDONLY | O_CREAT, 0600)) >= 0) {
                LOG(TRACE) << "Opening lock file: " << bindAddress.getSunPath().append(".lock").data();
                if (core::system::flock(lockFd, LOCK_EX | LOCK_NB) == 0) {
                    LOG(TRACE) << "Locking lock file: " << bindAddress.getSunPath().append(".lock").data();
                    if (std::filesystem::exists(bindAddress.getSunPath().data())) {
                        if (std::remove(bindAddress.getSunPath().data()) == 0) {
                            LOG(TRACE) << "Removed stalled sun_path: " << bindAddress.getSunPath().data();
                        } else {
                            PLOG(TRACE) << "Removed stalled sun path: " << bindAddress.getSunPath().data();
                        }
                    }
                } else {
                    PLOG(TRACE) << "Locking lock file " << bindAddress.getSunPath().append(".lock").data();
                    core::system::close(lockFd);
                    lockFd = -1;
                }
            } else {
                PLOG(TRACE) << "Opening lock file: " << bindAddress.getSunPath().append(".lock").data();
            }
        }
        return Super::bind(bindAddress);
    }
References core::system::close(), core::system::flock(), net::un::SocketAddress::getSunPath(), and net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::lockFd.
operator=()
template<template< typename SocketAddress > typename PhysicalPeerSocket> PhysicalSocket< PhysicalPeerSocket > & net::un::phy::PhysicalSocket< PhysicalPeerSocket >::operator= (PhysicalSocket< PhysicalPeerSocketT > && physicalSocket) noexcept
Definition at line 49 of file PhysicalSocket.hpp.
{
        Super::operator=(std::move(physicalSocket));
        lockFd = std::exchange(physicalSocket.lockFd, -1);
        return *this;
    }
References net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::lockFd.
Member Data Documentation
lockFd
template<template< typename SocketAddressT > typename PhysicalPeerSocketT> int net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::lockFd = -1 private
Definition at line 48 of file PhysicalSocket.h.
Referenced by net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::bind(), net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::operator=(), and net::un::phy::PhysicalSocket< PhysicalPeerSocketT >::~PhysicalSocket().
The documentation for this class was generated from the following files:
net/un/phy/PhysicalSocket.h
net/un/phy/PhysicalSocket.hpp