snode.c: web::websocket::server::SocketContextUpgrade Class Reference
web::websocket::server::SocketContextUpgrade Class Reference
#include <SocketContextUpgrade.h>
Public Member Functions
SocketContextUpgrade (core::socket::stream::SocketConnection *socketConnection, web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response > *socketContextUpgradeFactory, web::websocket::SubProtocolFactory< SubProtocol > *subProtocolFactory)
Public Member Functions inherited from web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >
SocketContextUpgrade ()=delete
SocketContextUpgrade (const SocketContextUpgrade &)=delete
SocketContextUpgrade & operator= (const SocketContextUpgrade &)=delete
Public Member Functions inherited from core::socket::stream::SocketContext
~SocketContext () override=default
void sendToPeer (const char *junk, std::size_t junkLen) const final
std::size_t readFromPeer (char *junk, std::size_t junklen) const final
void setTimeout (const utils::Timeval &timeout) final
void shutdownRead ()
void shutdownWrite (bool forceClose=false)
void shutdown (bool forceClose=false)
void close () override
core::socket::stream::SocketConnection * getSocketConnection () const
core::socket::stream::SocketContext * switchSocketContext (core::socket::stream::SocketContextFactory *socketContextFactory)
virtual void sendToPeer (const char *junk, std::size_t junkLen) const=0
void sendToPeer (const std::string &data) const
Public Member Functions inherited from core::socket::SocketContext
SocketContext (const SocketContext &)=delete
SocketContext (SocketContext &&)=delete
SocketContext & operator= (const SocketContext &)=delete
SocketContext & operator= (SocketContext &&)=delete
void sendToPeer (const std::string &data) const
Static Public Member Functions
static SocketContextUpgrade * create (web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response > *socketContextUpgradeFactory, core::socket::stream::SocketConnection *socketConnection, const std::string &subProtocolName)
Protected Member Functions
~SocketContextUpgrade () override
Protected Member Functions inherited from web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >
SocketContextUpgrade (core::socket::stream::SocketConnection *socketConnection, web::http::SocketContextUpgradeFactory< Request, Response > *socketContextUpgradeFactory, web::websocket::SubProtocolFactory< SubProtocol > *subProtocolFactory, Role role)
~SocketContextUpgrade () override=default
Protected Member Functions inherited from web::http::SocketContextUpgrade< RequestT, ResponseT >
SocketContextUpgrade (core::socket::stream::SocketConnection *socketConnection, SocketContextUpgradeFactory *socketContextUpgradeFactory)
~SocketContextUpgrade () override
Protected Member Functions inherited from core::socket::stream::SocketContext
SocketContext (core::socket::stream::SocketConnection *socketConnection)
Protected Member Functions inherited from core::socket::SocketContext
SocketContext ()=default
Additional Inherited Members
Public Types inherited from web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >
using SubProtocol = SubProtocol
using Request = web::http::server::Request
using Response = web::http::server::Response
Public Types inherited from web::http::SocketContextUpgrade< RequestT, ResponseT >
enum class Role { SERVER , CLIENT }
Protected Types inherited from web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >
enum Role
Protected Types inherited from web::http::SocketContextUpgrade< RequestT, ResponseT >
using Request = RequestT
using Response = ResponseT
using SocketContextUpgradeFactory = web::http::SocketContextUpgradeFactory< Request, Response >
Protected Attributes inherited from web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >
web::websocket::SubProtocolFactory< SubProtocol > * subProtocolFactory
SubProtocol * subProtocol
Detailed Description
Definition at line 52 of file SocketContextUpgrade.h.
Constructor & Destructor Documentation
SocketContextUpgrade()
web::websocket::server::SocketContextUpgrade::SocketContextUpgrade (core::socket::stream::SocketConnection * socketConnection, web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response > * socketContextUpgradeFactory, web::websocket::SubProtocolFactory< SubProtocol > * subProtocolFactory)
Definition at line 31 of file SocketContextUpgrade.cpp.
        : web::websocket::SocketContextUpgrade<SubProtocol, web::http::server::Request, web::http::server::Response>(
              socketConnection, socketContextUpgradeFactory, subProtocolFactory, Role::SERVER) {
    }
~SocketContextUpgrade()
web::websocket::server::SocketContextUpgrade::~SocketContextUpgrade () override protected
Definition at line 60 of file SocketContextUpgrade.cpp.
{
        if (subProtocolFactory->deleteSubProtocol(subProtocol) == 0) {
            SubProtocolFactorySelector::instance()->unload(subProtocolFactory);
        }
    }
References web::websocket::SubProtocolFactory< SubProtocolT >::deleteSubProtocol(), web::websocket::server::SubProtocolFactorySelector::instance(), web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >::subProtocol, web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >::subProtocolFactory, and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::unload().
Member Function Documentation
create()
SocketContextUpgrade * web::websocket::server::SocketContextUpgrade::create (web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response > * socketContextUpgradeFactory, core::socket::stream::SocketConnection * socketConnection, const std::string & subProtocolName) static
Definition at line 39 of file SocketContextUpgrade.cpp.
{
        SocketContextUpgrade* socketContextUpgrade = nullptr;
        web::websocket::SubProtocolFactory<SubProtocol>* subProtocolFactory =
            SubProtocolFactorySelector::instance()->select(subProtocolName, SubProtocolFactorySelector::Role::SERVER);
        if (subProtocolFactory != nullptr) {
            socketContextUpgrade = new SocketContextUpgrade(socketConnection, socketContextUpgradeFactory, subProtocolFactory);
            if (socketContextUpgrade->subProtocol == nullptr) {
                delete socketContextUpgrade;
                socketContextUpgrade = nullptr;
            }
        }
        return socketContextUpgrade;
    }
References web::websocket::server::SubProtocolFactorySelector::instance(), web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::select(), web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::SERVER, core::socket::stream::SocketContext::socketConnection, web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >::SocketContextUpgrade(), web::http::SocketContextUpgrade< RequestT, ResponseT >::socketContextUpgradeFactory, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::subProtocol, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >::subProtocolFactory.
Referenced by web::websocket::server::SocketContextUpgradeFactory::create().
The documentation for this class was generated from the following files:
web/websocket/server/SocketContextUpgrade.h
web/websocket/server/SocketContextUpgrade.cpp