SNode.C: net::in6::config::ConfigAddress< ConfigAddressTypeT > Class Template Reference
net::in6::config::ConfigAddress< ConfigAddressTypeT > Class Template Reference
#include <ConfigAddress.h>
Public Member Functions
SocketAddress getSocketAddress (const SocketAddress::SockAddr &sockAddr, SocketAddress::SockLen sockAddrLen)
ConfigAddress & setSocketAddress (const SocketAddress &socketAddress)
ConfigAddress & setHost (const std::string &ipOrHostname)
std::string getHost () const
ConfigAddress & setPort (uint16_t port)
uint16_t getPort () const
ConfigAddress & setNumeric (bool numeric=true)
bool getNumeric () const
ConfigAddress & setNumericReverse (bool numeric=true)
bool getNumericReverse () const
void configurable (bool configurable=true) final
Public Member Functions inherited from net::config::ConfigSection
template<typename T>
ConfigSection (ConfigInstance *instance, T *sectionPtr, const std::string &group="Sections")
~ConfigSection () override
ConfigSection (const ConfigSection &)=delete
ConfigSection (ConfigSection &&)=delete
ConfigSection & operator= (const ConfigSection &)=delete
Public Member Functions inherited from utils::SubCommand
SubCommand (const SubCommand &)=delete
SubCommand (SubCommand &&)=delete
SubCommand & operator= (const SubCommand &)=delete
SubCommand & operator= (SubCommand &&)=delete
virtual ~SubCommand ()
std::string getName () const
std::string version () const
void parse (int argc, char *argv[])
CLI::Option * setConfig (const std::string &defaultConfigFile) const
CLI::Option * setLogFile (const std::string &defaultLogFile) const
CLI::Option * setVersionFlag (const std::string &version) const
bool hasParent () const
SubCommand * getParent ()
SubCommand * allowExtras (bool allow=true)
SubCommand * required (bool required=true, bool force=true)
SubCommand * required (SubCommand *subCommand, bool required=true)
SubCommand * required (CLI::Option *option, bool required=true)
SubCommand * needs (SubCommand *subCommand, bool needs=true)
SubCommand * disabled (SubCommand *subCommand, bool disabled=true)
SubCommand * setRequireCallback (const std::function< void(void)> &callback)
SubCommand * finalCallback (const std::function< void()> &finalCallback)
std::string configToStr () const
std::string help (const CLI::App *helpApp, const CLI::AppFormatMode &mode) const
template<typename NewSubCommand, typename... Args>
NewSubCommand * newSubCommand (Args &&... args)
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand ()
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand () const
CLI::Option * getOption (const std::string &name) const
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator) const
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Protected Member Functions
ConfigAddress (net::config::ConfigInstance *instance, const std::string &addressOptionName, const std::string &addressOptionDescription)
ConfigAddress & setIpv4Mapped (bool ipv4Mapped=true)
bool getIpv4Mapped () const
ConfigAddress & setAiFlags (int aiFlags)
int getAiFlags () const
ConfigAddress & setAiSockType (int aiSocktype)
int getAiSockType () const
ConfigAddress & setAiProtocol (int aiProtocol)
int getAiProtocol () const
ConfigAddress & setHostRequired (bool required=true)
ConfigAddress & setPortRequired (bool required=true)
Protected Member Functions inherited from utils::SubCommand
SubCommand (SubCommand *parent, std::shared_ptr< utils::AppWithPtr > appWithPtr, const std::string &group, bool final)
template<typename ConcretSubCommand>
SubCommand (SubCommand *parent, ConcretSubCommand *concretSubCommand, const std::string &group, bool final=true)
SubCommand * description (const std::string &description)
SubCommand * footer (const std::string &footer)
template<typename ValueTypeT>
CLI::Option * setDefaultValue (CLI::Option *option, const ValueTypeT &value, bool clear=true) const
CLI::Option * setConfigurable (CLI::Option *option, bool configurable) const
Private Types
using Super = ConfigAddressTypeT<SocketAddress>
Private Member Functions
SocketAddress * init () final
Private Attributes
CLI::Option * hostOpt = nullptr
CLI::Option * portOpt = nullptr
CLI::Option * numericOpt = nullptr
CLI::Option * numericReverseOpt = nullptr
CLI::Option * ipv4MappedOpt = nullptr
int aiFlags = 0
int aiSockType = 0
int aiProtocol = 0
Additional Inherited Members
Static Public Member Functions inherited from utils::SubCommand
static CLI::App * getHelpTriggerApp ()
static CLI::App * getShowConfigTriggerApp ()
static CLI::App * getCommandlineTriggerApp ()
Static Public Attributes inherited from utils::SubCommand
static std::shared_ptr< CLI::Formatter > sectionFormatter = makeSectionFormatter()
Static Protected Attributes inherited from utils::SubCommand
static std::map< std::string, std::string > aliases
static CLI::App * helpTriggerApp = nullptr
static CLI::App * showConfigTriggerApp = nullptr
static CLI::App * commandlineTriggerApp = nullptr
Detailed Description
template<template< typename SocketAddressT > typename ConfigAddressTypeT>
class net::in6::config::ConfigAddress< ConfigAddressTypeT >
Definition at line 88 of file ConfigAddress.h.
Member Typedef Documentation
Super
template<template< typename SocketAddressT > typename ConfigAddressTypeT> using net::in6::config::ConfigAddress< ConfigAddressTypeT >::Super = ConfigAddressTypeT<SocketAddress> private
Definition at line 92 of file ConfigAddress.h.
Constructor & Destructor Documentation
ConfigAddress()
template<template< typename SocketAddress > typename ConfigAddressType> net::in6::config::ConfigAddress< ConfigAddressType >::ConfigAddress (net::config::ConfigInstance * instance, const std::string & addressOptionName, const std::string & addressOptionDescription) protected
Definition at line 108 of file ConfigAddress.cpp.
        : ConfigSection(instance, this)
        , ConfigAddressType<net::in6::SocketAddress>(this) {
        hostOpt = addOption( //
            "--host",
            "Host name or IPv6 address",
            "hostname|IPv6",
            "::",
            CLI::TypeValidator<std::string>());
        portOpt = addOption( //
            "--port",
            "Port number",
            "port",
            0,
            CLI::Range(std::numeric_limits<uint16_t>::min(), std::numeric_limits<uint16_t>::max()));
        numericOpt = addFlag( //
            "--numeric",
            "Suppress host name lookup",
            "bool",
            XSTR(IN6_NUMERIC),
            CLI::IsMember({"true", "false"}));
        numericReverseOpt = addFlag( //
            "--numeric-reverse",
            "Suppress reverse host name lookup",
            "bool",
            XSTR(IN6_NUMERIC_REVERSE),
            CLI::IsMember({"true", "false"}));
        ipv4MappedOpt = addFlag( //
            "--ipv4-mapped",
            "Resolve IPv4-mapped IPv6 addresses also",
            "bool",
            XSTR(IN6_IPV4_MAPPED),
            CLI::IsMember({"true", "false"}));
    }
Member Function Documentation
configurable()
template<template< typename SocketAddressT > typename ConfigAddressTypeT> void net::in6::config::ConfigAddress< ConfigAddressTypeT >::configurable (bool configurable = true) final
Definition at line 237 of file ConfigAddress.cpp.
{
        this->setConfigurable(hostOpt, configurable);
        this->setConfigurable(portOpt, configurable);
    }
References hostOpt, and portOpt.
getAiFlags()
template<template< typename SocketAddress > typename ConfigAddressType> int net::in6::config::ConfigAddress< ConfigAddressType >::getAiFlags () const protected
Definition at line 273 of file ConfigAddress.cpp.
{
        return aiFlags;
    }
References aiFlags.
getAiProtocol()
template<template< typename SocketAddress > typename ConfigAddressType> int net::in6::config::ConfigAddress< ConfigAddressType >::getAiProtocol () const protected
Definition at line 297 of file ConfigAddress.cpp.
{
        return aiProtocol;
    }
References aiProtocol.
getAiSockType()
template<template< typename SocketAddress > typename ConfigAddressType> int net::in6::config::ConfigAddress< ConfigAddressType >::getAiSockType () const protected
Definition at line 285 of file ConfigAddress.cpp.
{
        return aiSockType;
    }
References aiSockType.
getHost()
template<template< typename SocketAddress > typename ConfigAddressType> std::string net::in6::config::ConfigAddress< ConfigAddressType >::getHost () const
Definition at line 203 of file ConfigAddress.cpp.
{
        return hostOpt->as<std::string>();
    }
References hostOpt.
getIpv4Mapped()
template<template< typename SocketAddress > typename ConfigAddressType> bool net::in6::config::ConfigAddress< ConfigAddressType >::getIpv4Mapped () const protected
Definition at line 261 of file ConfigAddress.cpp.
{
        return ipv4MappedOpt->as<bool>();
    }
References ipv4MappedOpt.
getNumeric()
template<template< typename SocketAddress > typename ConfigAddressType> bool net::in6::config::ConfigAddress< ConfigAddressType >::getNumeric () const
Definition at line 232 of file ConfigAddress.cpp.
{
        return numericOpt->as<bool>();
    }
References numericOpt.
getNumericReverse()
template<template< typename SocketAddressT > typename ConfigAddressTypeT> bool net::in6::config::ConfigAddress< ConfigAddressTypeT >::getNumericReverse () const
getPort()
template<template< typename SocketAddress > typename ConfigAddressType> uint16_t net::in6::config::ConfigAddress< ConfigAddressType >::getPort () const
Definition at line 218 of file ConfigAddress.cpp.
{
        return portOpt->as<uint16_t>();
    }
References portOpt.
getSocketAddress()
template<template< typename SocketAddress > typename ConfigAddressType> SocketAddress net::in6::config::ConfigAddress< ConfigAddressType >::getSocketAddress (const SocketAddress::SockAddr & sockAddr, SocketAddress::SockLen sockAddrLen)
Definition at line 168 of file ConfigAddress.cpp.
{
        SocketAddress socketAddress;
        try {
            socketAddress = SocketAddress(sockAddr, sockAddrLen, numericReverseOpt->as<bool>());
        } catch ([[maybe_unused]] const SocketAddress::BadSocketAddress& badSocketAddress) {
            try {
                socketAddress = Super::getSocketAddress(sockAddr, sockAddrLen);
            } catch ([[maybe_unused]] const SocketAddress::BadSocketAddress& badSocketAddress) {
                throw;
            }
        }
        return socketAddress;
    }
References numericReverseOpt, and net::in6::SocketAddress::SocketAddress().
init()
template<template< typename SocketAddress > typename ConfigAddressType> SocketAddress * net::in6::config::ConfigAddress< ConfigAddressType >::init () final private
Definition at line 150 of file ConfigAddress.cpp.
{
        SocketAddress* socketAddress = new SocketAddress(hostOpt->as<std::string>(), portOpt->as<uint16_t>());
        try {
            socketAddress->init({.aiFlags = (aiFlags & ~AI_NUMERICHOST) | (numericOpt->as<bool>() ? AI_NUMERICHOST : 0),
                                 .aiSockType = aiSockType,
                                 .aiProtocol = aiProtocol});
        } catch (const core::socket::SocketAddress::BadSocketAddress&) {
            delete socketAddress;
            socketAddress = nullptr;
            throw;
        }
        return socketAddress;
    }
References hostOpt, net::in6::SocketAddress::init(), portOpt, and net::in6::SocketAddress::SocketAddress().
setAiFlags()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in6::config::ConfigAddress< ConfigAddressType >::setAiFlags (int aiFlags) protected
Definition at line 266 of file ConfigAddress.cpp.
{
        this->aiFlags = aiFlags;
        return *this;
    }
References aiFlags.
Referenced by net::in6::stream::config::ConfigSocketServer::ConfigSocketServer().
setAiProtocol()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in6::config::ConfigAddress< ConfigAddressType >::setAiProtocol (int aiProtocol) protected
Definition at line 290 of file ConfigAddress.cpp.
{
        this->aiProtocol = aiProtocol;
        return *this;
    }
References aiProtocol.
Referenced by net::in6::stream::config::ConfigSocketClient::ConfigSocketClient(), and net::in6::stream::config::ConfigSocketServer::ConfigSocketServer().
setAiSockType()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in6::config::ConfigAddress< ConfigAddressType >::setAiSockType (int aiSocktype) protected
Definition at line 278 of file ConfigAddress.cpp.
{
        this->aiSockType = aiSockType;
        return *this;
    }
References aiSockType.
Referenced by net::in6::stream::config::ConfigSocketClient::ConfigSocketClient(), and net::in6::stream::config::ConfigSocketServer::ConfigSocketServer().
setHost()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in6::config::ConfigAddress< ConfigAddressType >::setHost (const std::string & ipOrHostname)
Definition at line 193 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue(hostOpt, ipOrHostname);
        required(hostOpt, false);
        return *this;
    }
References hostOpt.
Referenced by setSocketAddress().
setHostRequired()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in6::config::ConfigAddress< ConfigAddressType >::setHostRequired (bool required = true) protected
Definition at line 302 of file ConfigAddress.cpp.
{
        this->required(hostOpt, required);
        return *this;
    }
References hostOpt.
Referenced by net::in6::stream::config::ConfigSocketClient::ConfigSocketClient().
setIpv4Mapped()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in6::config::ConfigAddress< ConfigAddressType >::setIpv4Mapped (bool ipv4Mapped = true) protected
Definition at line 252 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue(ipv4MappedOpt, ipv4Mapped ? "true" : "false");
        return *this;
    }
References ipv4MappedOpt.
setNumeric()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in6::config::ConfigAddress< ConfigAddressType >::setNumeric (bool numeric = true)
Definition at line 223 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue(numericOpt, numeric ? "true" : "false");
        return *this;
    }
References numericOpt.
setNumericReverse()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in6::config::ConfigAddress< ConfigAddressType >::setNumericReverse (bool numeric = true)
Definition at line 243 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue(numericReverseOpt, numeric ? "true" : "false");
        return *this;
    }
References numericReverseOpt.
setPort()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in6::config::ConfigAddress< ConfigAddressType >::setPort (uint16_t port)
Definition at line 208 of file ConfigAddress.cpp.
{
        const utils::PreserveErrno preserveErrno;
        setDefaultValue(portOpt, port);
        required(portOpt, false);
        return *this;
    }
References portOpt.
Referenced by setSocketAddress().
setPortRequired()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in6::config::ConfigAddress< ConfigAddressType >::setPortRequired (bool required = true) protected
Definition at line 309 of file ConfigAddress.cpp.
{
        this->required(portOpt, required);
        return *this;
    }
References portOpt.
Referenced by net::in6::stream::config::ConfigSocketClient::ConfigSocketClient(), and net::in6::stream::config::ConfigSocketServer::ConfigSocketServer().
setSocketAddress()
template<template< typename SocketAddress > typename ConfigAddressType> ConfigAddress< ConfigAddressType > & net::in6::config::ConfigAddress< ConfigAddressType >::setSocketAddress (const SocketAddress & socketAddress)
Definition at line 185 of file ConfigAddress.cpp.
{
        setHost(socketAddress.getHost());
        setPort(socketAddress.getPort());
        return *this;
    }
References net::in6::SocketAddress::getHost(), net::in6::SocketAddress::getPort(), setHost(), and setPort().
Member Data Documentation
aiFlags
template<template< typename SocketAddressT > typename ConfigAddressTypeT> int net::in6::config::ConfigAddress< ConfigAddressTypeT >::aiFlags = 0 private
Definition at line 145 of file ConfigAddress.h.
Referenced by getAiFlags(), and setAiFlags().
aiProtocol
template<template< typename SocketAddressT > typename ConfigAddressTypeT> int net::in6::config::ConfigAddress< ConfigAddressTypeT >::aiProtocol = 0 private
Definition at line 147 of file ConfigAddress.h.
Referenced by getAiProtocol(), and setAiProtocol().
aiSockType
template<template< typename SocketAddressT > typename ConfigAddressTypeT> int net::in6::config::ConfigAddress< ConfigAddressTypeT >::aiSockType = 0 private
Definition at line 146 of file ConfigAddress.h.
Referenced by getAiSockType(), and setAiSockType().
hostOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::in6::config::ConfigAddress< ConfigAddressTypeT >::hostOpt = nullptr private
Definition at line 139 of file ConfigAddress.h.
Referenced by configurable(), getHost(), net::in6::config::ConfigAddress< net::config::ConfigAddressRemote >::getPort(), init(), setHost(), and setHostRequired().
ipv4MappedOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::in6::config::ConfigAddress< ConfigAddressTypeT >::ipv4MappedOpt = nullptr private
Definition at line 143 of file ConfigAddress.h.
Referenced by getIpv4Mapped(), and setIpv4Mapped().
numericOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::in6::config::ConfigAddress< ConfigAddressTypeT >::numericOpt = nullptr private
Definition at line 141 of file ConfigAddress.h.
Referenced by getNumeric(), and setNumeric().
numericReverseOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::in6::config::ConfigAddress< ConfigAddressTypeT >::numericReverseOpt = nullptr private
Definition at line 142 of file ConfigAddress.h.
Referenced by getSocketAddress(), and setNumericReverse().
portOpt
template<template< typename SocketAddressT > typename ConfigAddressTypeT> CLI::Option* net::in6::config::ConfigAddress< ConfigAddressTypeT >::portOpt = nullptr private
Definition at line 140 of file ConfigAddress.h.
Referenced by configurable(), getPort(), init(), setPort(), and setPortRequired().
The documentation for this class was generated from the following files:
net/in6/config/ConfigAddress.h
net/in6/config/ConfigAddress.cpp