SNode.C: core::socket::stream::tls::SocketWriter< PhysicalSocketT > Class Template Reference
core::socket::stream::tls::SocketWriter< PhysicalSocketT > Class Template Reference abstract
#include <SocketWriter.h>
Public Member Functions
int getRegisteredFd ()
void enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Types
using PhysicalSocket = PhysicalSocketT
Protected Member Functions
virtual void doSSLHandshake (const std::function< void()> &onSuccess, const std::function< void()> &onTimeout, const std::function< void(int)> &onStatus)=0
void setBlockSize (std::size_t writeBlockSize)
void sendToPeer (const char *junk, std::size_t junkLen)
virtual void doWriteShutdown (const std::function< void(int)> &onShutdown)
void shutdown (const std::function< void(int)> &onShutdown)
void terminate () final
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
virtual void unobservedEvent ()=0
Protected Attributes
SSL * ssl = nullptr
Private Types
using Super = core::socket::stream::SocketWriter< PhysicalSocketT >
Private Member Functions
ssize_t write (const char *junk, std::size_t junkLen) override
void writeEvent () final
void doWrite ()
virtual void writeTimeout ()
void dispatchEvent () final
void timeoutEvent () final
void onEvent (const utils::Timeval &currentTime) final
virtual void onExit (int sig)
void triggered (const utils::Timeval &currentTime)
void setEnabled (const utils::Timeval &currentTime)
void setDisabled ()
Private Attributes
std::function< void(int)> onStatus
std::function< void(int)> onShutdown
std::vector< char > writeBuffer
std::size_t blockSize = 0
bool markShutdown = false
bool shutdownInProgress = false
bool terminateInProgress = false
utils::Timeval terminateTimeout
DescriptorEventPublisher & descriptorEventPublisher
int observedFd = -1
bool enabled = false
bool suspended = false
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
int observationCounter = 0
Event event
Detailed Description
template<typename PhysicalSocketT>
class core::socket::stream::tls::SocketWriter< PhysicalSocketT >
Definition at line 35 of file SocketWriter.h.
Member Typedef Documentation
PhysicalSocket
template<typename PhysicalSocketT > using core::socket::stream::SocketWriter< PhysicalSocketT >::PhysicalSocket = PhysicalSocketT protected inherited
Definition at line 44 of file SocketWriter.h.
Super
template<typename PhysicalSocketT > using core::socket::stream::tls::SocketWriter< PhysicalSocketT >::Super = core::socket::stream::SocketWriter<PhysicalSocketT> private
Definition at line 37 of file SocketWriter.h.
Member Function Documentation
checkTimeout()
void core::DescriptorEventReceiver::checkTimeout (const utils::Timeval & currentTime) inherited
Definition at line 159 of file DescriptorEventReceiver.cpp.
{
        if (maxInactivity > 0 && currentTime - lastTriggered >= maxInactivity) {
            timeoutEvent();
        }
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), utils::Timeval::operator>(), utils::Timeval::operator>=(), and core::DescriptorEventReceiver::timeoutEvent().
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents().
destruct()
void core::EventReceiver::destruct () virtual inherited
Reimplemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, and database::mariadb::MariaDBCommandStartEvent.
Definition at line 31 of file EventReceiver.cpp.
{
        delete this;
    }
Referenced by core::EventMultiplexer::EventQueue::clear().
disable()
void core::DescriptorEventReceiver::disable () inherited
Definition at line 67 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!isSuspended()) {
                suspend();
            }
            enabled = false;
            descriptorEventPublisher.disable(this);
        } else {
            LOG(TRACE) << "Double disable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::disable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::observedFd, and core::DescriptorEventReceiver::suspend().
Referenced by core::eventreceiver::AcceptEventReceiver::acceptTimeout(), database::mariadb::MariaDBConnection::commandContinue(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectEvent(), core::eventreceiver::ConnectEventReceiver::connectTimeout(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectTimeout(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::pipe::PipeSource::eof(), core::eventreceiver::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSink::readEvent(), core::eventreceiver::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::DescriptorEventReceiver::terminate(), core::socket::stream::SocketWriter< PhysicalSocketT >::terminate(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), core::pipe::PipeSource::writeEvent(), core::eventreceiver::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
dispatchEvent()
void core::eventreceiver::WriteEventReceiver::dispatchEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 41 of file WriteEventReceiver.cpp.
{
        writeEvent();
    }
References core::eventreceiver::WriteEventReceiver::writeEvent().
doSSLHandshake()
template<typename PhysicalSocketT > virtual void core::socket::stream::tls::SocketWriter< PhysicalSocketT >::doSSLHandshake (const std::function< void()> & onSuccess, const std::function< void()> & onTimeout, const std::function< void(int)> & onStatus) protected pure virtual
Referenced by core::socket::stream::tls::SocketWriter< PhysicalSocketT >::write().
doWrite()
template<typename PhysicalSocket > void core::socket::stream::SocketWriter< PhysicalSocket >::doWrite () private inherited
Definition at line 46 of file SocketWriter.hpp.
{
        if (!writeBuffer.empty()) {
            std::size_t writeLen = (writeBuffer.size() < blockSize) ? writeBuffer.size() : blockSize;
            ssize_t retWrite = write(writeBuffer.data(), writeLen);
            if (retWrite > 0) {
                writeBuffer.erase(writeBuffer.begin(), writeBuffer.begin() + retWrite);
                if (!isSuspended()) {
                    suspend();
                }
                if (!writeBuffer.empty()) {
                    if (writeBuffer.capacity() > writeBuffer.size() * 2) {
                        writeBuffer.shrink_to_fit();
                    }
                    span();
                } else {
                    writeBuffer.shrink_to_fit();
                    if (markShutdown) {
                        shutdown(onShutdown);
                    }
                }
            } else if (errno == EAGAIN || errno == EWOULDBLOCK || errno == EINTR) {
                if (isSuspended()) {
                    resume();
                }
            } else {
                disable();
                onStatus(errno);
            }
        } else if (!isSuspended()) {
            suspend();
        }
    }
References core::socket::stream::SocketWriter< PhysicalSocketT >::blockSize, core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::isSuspended(), core::socket::stream::SocketWriter< PhysicalSocketT >::markShutdown, core::socket::stream::SocketWriter< PhysicalSocketT >::onShutdown, core::socket::stream::SocketWriter< PhysicalSocketT >::onStatus, core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter< PhysicalSocketT >::shutdown(), core::EventReceiver::span(), core::DescriptorEventReceiver::suspend(), core::socket::stream::SocketWriter< PhysicalSocketT >::write(), and core::socket::stream::SocketWriter< PhysicalSocketT >::writeBuffer.
Referenced by core::socket::stream::SocketWriter< PhysicalSocketT >::writeEvent().
doWriteShutdown()
template<typename PhysicalSocket > void core::socket::stream::SocketWriter< PhysicalSocket >::doWriteShutdown (const std::function< void(int)> & onShutdown) protected virtual inherited
Definition at line 99 of file SocketWriter.hpp.
{
        errno = 0;
        LOG(TRACE) << "Do syscall shutdonw(WR)";
        PhysicalSocket::shutdown(PhysicalSocket::SHUT::WR);
        onShutdown(errno);
    }
Referenced by core::socket::stream::SocketWriter< PhysicalSocketT >::shutdown().
enable()
void core::DescriptorEventReceiver::enable (int fd) inherited
Definition at line 50 of file DescriptorEventReceiver.cpp.
{
        if (!enabled) {
            observedFd = fd;
            enabled = true;
            descriptorEventPublisher.enable(this);
        } else {
            LOG(TRACE) << "Double enable: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::enable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), and core::DescriptorEventReceiver::observedFd.
Referenced by core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >::connectTimeout(), core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 43 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
getObservationCounter()
int core::Observer::getObservationCounter () inline inherited
Definition at line 55 of file DescriptorEventReceiver.h.
{
            return observationCounter;
        }
References core::Observer::observationCounter.
getRegisteredFd()
int core::DescriptorEventReceiver::getRegisteredFd () inherited
Definition at line 46 of file DescriptorEventReceiver.cpp.
{
        return observedFd;
    }
References core::DescriptorEventReceiver::observedFd.
Referenced by core::DescriptorEventPublisher::enable(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::select::DescriptorEventPublisher::muxAdd(), core::poll::PollFdsManager::muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOff(), core::select::DescriptorEventPublisher::muxOff(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOn(), core::select::DescriptorEventPublisher::muxOn(), core::poll::PollFdsManager::muxOn(), core::pipe::PipeSink::readEvent(), core::pipe::PipeSource::writeEvent(), core::pipe::PipeSink::~PipeSink(), and core::pipe::PipeSource::~PipeSource().
getTimeout()
utils::Timeval core::DescriptorEventReceiver::getTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 141 of file DescriptorEventReceiver.cpp.
{
        return maxInactivity > 0 ? currentTime > lastTriggered ? maxInactivity - (currentTime - lastTriggered) : 0 : TIMEOUT::MAX;
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::DescriptorEventPublisher::getNextTimeout().
isEnabled()
bool core::DescriptorEventReceiver::isEnabled () const inherited
Definition at line 84 of file DescriptorEventReceiver.cpp.
{
        return enabled;
    }
References core::DescriptorEventReceiver::enabled.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >::connectTimeout(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), and core::DescriptorEventReceiver::terminate().
isObserved()
bool core::Observer::isObserved () inline inherited
Definition at line 43 of file DescriptorEventReceiver.h.
{
            return observationCounter > 0;
        }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
isSuspended()
bool core::DescriptorEventReceiver::isSuspended () const inherited
Definition at line 121 of file DescriptorEventReceiver.cpp.
{
        return suspended;
    }
References core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::pipe::PipeSource::send().
observed()
void core::Observer::observed () inline inherited
Definition at line 47 of file DescriptorEventReceiver.h.
{
            observationCounter++;
        }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setEnabled().
onEvent()
void core::DescriptorEventReceiver::onEvent (const utils::Timeval & currentTime) final private virtual inherited
Implements core::EventReceiver.
Definition at line 145 of file DescriptorEventReceiver.cpp.
{
        eventCounter++;
        triggered(currentTime);
        dispatchEvent();
    }
References core::DescriptorEventReceiver::dispatchEvent(), core::DescriptorEventReceiver::eventCounter, and core::DescriptorEventReceiver::triggered().
onExit()
void core::DescriptorEventReceiver::onExit (int sig) private virtual inherited
Definition at line 152 of file DescriptorEventReceiver.cpp.
{
    }
Referenced by core::DescriptorEventPublisher::sigExit().
relax()
void core::EventReceiver::relax () inherited
Definition at line 39 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
resume()
void core::DescriptorEventReceiver::resume () inherited
Definition at line 104 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (suspended) {
                suspended = false;
                lastTriggered = utils::Timeval::currentTime();
                if (isObserved()) {
                    descriptorEventPublisher.resume(this);
                }
            } else {
                LOG(TRACE) << "Double resume: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "Resume while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::Observer::isObserved(), core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::observedFd, utils::Timeval::operator=(), core::DescriptorEventPublisher::resume(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
sendToPeer()
template<typename PhysicalSocket > void core::socket::stream::SocketWriter< PhysicalSocket >::sendToPeer (const char * junk, std::size_t junkLen) protected inherited
Definition at line 88 of file SocketWriter.hpp.
{
        if (!shutdownInProgress && !markShutdown && isEnabled()) {
            if (writeBuffer.empty()) {
                resume();
            }
            writeBuffer.insert(writeBuffer.end(), junk, junk + junkLen);
        }
    }
References core::DescriptorEventReceiver::isEnabled(), core::socket::stream::SocketWriter< PhysicalSocketT >::markShutdown, core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter< PhysicalSocketT >::shutdownInProgress, and core::socket::stream::SocketWriter< PhysicalSocketT >::writeBuffer.
setBlockSize()
template<typename PhysicalSocket > void core::socket::stream::SocketWriter< PhysicalSocket >::setBlockSize (std::size_t writeBlockSize) protected inherited
Definition at line 83 of file SocketWriter.hpp.
{
        this->blockSize = writeBlockSize;
    }
Referenced by core::socket::stream::SocketWriter< PhysicalSocketT >::SocketWriter().
setDisabled()
void core::DescriptorEventReceiver::setDisabled () private inherited
Definition at line 80 of file DescriptorEventReceiver.cpp.
{
        unObserved();
    }
References core::Observer::unObserved().
setEnabled()
void core::DescriptorEventReceiver::setEnabled (const utils::Timeval & currentTime) private inherited
Definition at line 61 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
        observed();
    }
References core::DescriptorEventReceiver::lastTriggered, core::Observer::observed(), and utils::Timeval::operator=().
Referenced by core::DescriptorEventPublisher::enable().
setTimeout()
void core::DescriptorEventReceiver::setTimeout (const utils::Timeval & timeout) inherited
Definition at line 131 of file DescriptorEventReceiver.cpp.
{
        if (timeout == TIMEOUT::DEFAULT) {
            this->maxInactivity = initialTimeout;
        } else {
            this->maxInactivity = timeout;
        }
        triggered(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::TIMEOUT::DEFAULT, core::DescriptorEventReceiver::initialTimeout, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator=(), utils::Timeval::operator==(), and core::DescriptorEventReceiver::triggered().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::initAcceptEvent(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::initConnectEvent(), core::socket::stream::SocketReader< PhysicalSocketT >::terminate(), and core::socket::stream::SocketWriter< PhysicalSocketT >::terminate().
shutdown()
template<typename PhysicalSocket > void core::socket::stream::SocketWriter< PhysicalSocket >::shutdown (const std::function< void(int)> & onShutdown) protected inherited
Definition at line 110 of file SocketWriter.hpp.
{
        if (!shutdownInProgress) {
            this->onShutdown = onShutdown;
            if (writeBuffer.empty()) {
                shutdownInProgress = true;
                LOG(TRACE) << "Initiating shutdown process";
                doWriteShutdown(onShutdown);
            } else {
                markShutdown = true;
            }
        }
    }
References core::socket::stream::SocketWriter< PhysicalSocketT >::doWriteShutdown(), core::socket::stream::SocketWriter< PhysicalSocketT >::markShutdown, core::socket::stream::SocketWriter< PhysicalSocketT >::shutdownInProgress, and core::socket::stream::SocketWriter< PhysicalSocketT >::writeBuffer.
Referenced by core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), and core::socket::stream::SocketWriter< PhysicalSocketT >::terminate().
span()
void core::EventReceiver::span () inherited
Definition at line 35 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::FileReader(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
suspend()
void core::DescriptorEventReceiver::suspend () inherited
Definition at line 88 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!suspended) {
                suspended = true;
                if (isObserved()) {
                    descriptorEventPublisher.suspend(this);
                }
            } else {
                LOG(TRACE) << "Double suspend: " << getName() << ": fd = " << observedFd;
            }
        } else {
            LOG(TRACE) << "Suspend while not enabled: " << getName() << ": fd = " << observedFd;
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::Observer::isObserved(), core::DescriptorEventReceiver::observedFd, core::DescriptorEventPublisher::suspend(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), and core::pipe::PipeSource::writeEvent().
terminate()
template<typename PhysicalSocket > void core::socket::stream::SocketWriter< PhysicalSocket >::terminate () final protected virtual inherited
Reimplemented from core::DescriptorEventReceiver.
Definition at line 124 of file SocketWriter.hpp.
{
        if (!terminateInProgress) {
            setTimeout(terminateTimeout);
            shutdown([this]([[maybe_unused]] int errnum) -> void {
                if (errnum != 0) {
                    PLOG(TRACE) << "SocketWriter::doWriteShutdown";
                }
                disable();
            });
            terminateInProgress = true;
        }
    }
References core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::setTimeout(), core::socket::stream::SocketWriter< PhysicalSocketT >::shutdown(), core::socket::stream::SocketWriter< PhysicalSocketT >::terminateInProgress, and core::socket::stream::SocketWriter< PhysicalSocketT >::terminateTimeout.
timeoutEvent()
void core::eventreceiver::WriteEventReceiver::timeoutEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 45 of file WriteEventReceiver.cpp.
{
        writeTimeout();
    }
References core::eventreceiver::WriteEventReceiver::writeTimeout().
triggered()
void core::DescriptorEventReceiver::triggered (const utils::Timeval & currentTime) private inherited
Definition at line 155 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
    }
References core::DescriptorEventReceiver::lastTriggered, and utils::Timeval::operator=().
Referenced by core::DescriptorEventReceiver::onEvent(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::DescriptorEventReceiver::setTimeout().
unObserved()
void core::Observer::unObserved () inline inherited
Definition at line 51 of file DescriptorEventReceiver.h.
{
            observationCounter--;
        }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setDisabled().
unobservedEvent()
virtual void core::Observer::unobservedEvent () pure virtual inherited
Implemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::tls::TLSHandshake, core::socket::stream::tls::TLSShutdown, core::pipe::PipeSink, core::pipe::PipeSource, and database::mariadb::MariaDBConnection.
write()
template<typename PhysicalSocket > ssize_t core::socket::stream::tls::SocketWriter< PhysicalSocket >::write (const char * junk, std::size_t junkLen) override private virtual
Implements core::socket::stream::SocketWriter< PhysicalSocketT >.
Definition at line 33 of file SocketWriter.hpp.
{
        int ret = SSL_write(ssl, junk, static_cast<int>(junkLen));
        if (ret <= 0) {
            int ssl_err = SSL_get_error(ssl, ret);
            switch (ssl_err) {
                case SSL_ERROR_NONE:
                    break;
                case SSL_ERROR_WANT_READ: {
                    utils::PreserveErrno preserveErrno;
                    LOG(TRACE) << "SSL/TLS start renegotiation on write";
                    doSSLHandshake(
                        []() -> void {
                            LOG(TRACE) << "SSL/TLS renegotiation on write success";
                        },
                        []() -> void {
                            LOG(TRACE) << "SSL/TLS renegotiation on write timed out";
                        },
                        [](int ssl_err) -> void {
                            ssl_log("SSL/TLS renegotiation", ssl_err);
                        });
                }
                    ret = -1;
                    break;
                case SSL_ERROR_WANT_WRITE:
                    ret = -1;
                    break;
                case SSL_ERROR_ZERO_RETURN: // shutdown cleanly
                    errno = EPIPE;
                    ret = -1; // on the write side this means a TCP broken pipe
                    break;
                case SSL_ERROR_SYSCALL:
                    ret = -1;
                    break;
                default:
                    ssl_log("SSL/TLS write failed", ssl_err);
                    errno = EIO;
                    ret = -1;
                    break;
            }
        }
        return ret;
    }
References core::socket::stream::tls::SocketWriter< PhysicalSocketT >::doSSLHandshake(), core::socket::stream::tls::SocketWriter< PhysicalSocketT >::ssl, and core::socket::stream::tls::ssl_log().
writeEvent()
template<typename PhysicalSocket > void core::socket::stream::SocketWriter< PhysicalSocket >::writeEvent () final private virtual inherited
Implements core::eventreceiver::WriteEventReceiver.
Definition at line 41 of file SocketWriter.hpp.
{
        doWrite();
    }
References core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite().
writeTimeout()
void core::eventreceiver::WriteEventReceiver::writeTimeout () private virtual inherited
Reimplemented in core::socket::stream::tls::TLSHandshake, core::socket::stream::tls::TLSShutdown, and database::mariadb::MariaDBConnection.
Definition at line 37 of file WriteEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
Referenced by core::eventreceiver::WriteEventReceiver::timeoutEvent().
Member Data Documentation
blockSize
template<typename PhysicalSocketT > std::size_t core::socket::stream::SocketWriter< PhysicalSocketT >::blockSize = 0 private inherited
Definition at line 76 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite().
descriptorEventPublisher
DescriptorEventPublisher& core::DescriptorEventReceiver::descriptorEventPublisher private inherited
Definition at line 112 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
enabled
bool core::DescriptorEventReceiver::enabled = false private inherited
Definition at line 116 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
event
Event core::EventReceiver::event private inherited
Definition at line 54 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
eventCounter
int core::DescriptorEventReceiver::eventCounter = 0 private inherited
Definition at line 123 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::onEvent().
initialTimeout
const utils::Timeval core::DescriptorEventReceiver::initialTimeout private inherited
Definition at line 121 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), and core::DescriptorEventReceiver::setTimeout().
lastTriggered
utils::Timeval core::DescriptorEventReceiver::lastTriggered private inherited
Definition at line 119 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setEnabled(), and core::DescriptorEventReceiver::triggered().
markShutdown
template<typename PhysicalSocketT > bool core::socket::stream::SocketWriter< PhysicalSocketT >::markShutdown = false private inherited
Definition at line 78 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), and core::socket::stream::SocketWriter< PhysicalSocketT >::shutdown().
maxInactivity
utils::Timeval core::DescriptorEventReceiver::maxInactivity private inherited
Definition at line 120 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::getTimeout(), and core::DescriptorEventReceiver::setTimeout().
observationCounter
int core::Observer::observationCounter = 0 private inherited
Definition at line 62 of file DescriptorEventReceiver.h.
Referenced by core::Observer::getObservationCounter(), core::Observer::isObserved(), core::Observer::observed(), and core::Observer::unObserved().
observedFd
int core::DescriptorEventReceiver::observedFd = -1 private inherited
Definition at line 114 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
onShutdown
template<typename PhysicalSocketT > std::function<void(int)> core::socket::stream::SocketWriter< PhysicalSocketT >::onShutdown private inherited
Definition at line 73 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite().
onStatus
template<typename PhysicalSocketT > std::function<void(int)> core::socket::stream::SocketWriter< PhysicalSocketT >::onStatus private inherited
Definition at line 72 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), and core::socket::stream::SocketWriter< PhysicalSocketT >::SocketWriter().
shutdownInProgress
template<typename PhysicalSocketT > bool core::socket::stream::SocketWriter< PhysicalSocketT >::shutdownInProgress = false private inherited
Definition at line 79 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), and core::socket::stream::SocketWriter< PhysicalSocketT >::shutdown().
ssl
template<typename PhysicalSocketT > SSL* core::socket::stream::tls::SocketWriter< PhysicalSocketT >::ssl = nullptr protected
Definition at line 47 of file SocketWriter.h.
Referenced by core::socket::stream::tls::SocketWriter< PhysicalSocketT >::write().
suspended
bool core::DescriptorEventReceiver::suspended = false private inherited
Definition at line 117 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
terminateInProgress
template<typename PhysicalSocketT > bool core::socket::stream::SocketWriter< PhysicalSocketT >::terminateInProgress = false private inherited
Definition at line 80 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< PhysicalSocketT >::terminate().
terminateTimeout
template<typename PhysicalSocketT > utils::Timeval core::socket::stream::SocketWriter< PhysicalSocketT >::terminateTimeout private inherited
Definition at line 82 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< PhysicalSocketT >::SocketWriter(), and core::socket::stream::SocketWriter< PhysicalSocketT >::terminate().
writeBuffer
template<typename PhysicalSocketT > std::vector<char> core::socket::stream::SocketWriter< PhysicalSocketT >::writeBuffer private inherited
Definition at line 75 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), core::socket::stream::SocketWriter< PhysicalSocketT >::sendToPeer(), and core::socket::stream::SocketWriter< PhysicalSocketT >::shutdown().
The documentation for this class was generated from the following files:
core/socket/stream/tls/SocketWriter.h
core/socket/stream/tls/SocketWriter.hpp