SNode.C: net::config::ConfigAddressLocal< SocketAddressT > Class Template Reference
net::config::ConfigAddressLocal< SocketAddressT > Class Template Reference
#include <ConfigAddressLocal.h>
Protected Member Functions
ConfigAddressLocal (ConfigInstance *instance)
Protected Member Functions inherited from net::config::ConfigAddress< SocketAddressT >
ConfigAddress (ConfigInstance *instance, const std::string &addressOptionName, const std::string &addressOptionDescription)
virtual ~ConfigAddress ()
Protected Member Functions inherited from net::config::ConfigSection
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
ConfigSection (ConfigInstance *instance, const std::string &name, const std::string &description, bool hidden=false)
ConfigSection (const ConfigSection &)=delete
ConfigSection (ConfigSection &&)=delete
ConfigSection & operator= (const ConfigSection &)=delete
ConfigSection & operator= (ConfigSection &&)=delete
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
Private Types
using Super = net::config::ConfigAddress< SocketAddressT >
Additional Inherited Members
Public Member Functions inherited from net::config::ConfigAddress< SocketAddressT >
SocketAddress & getSocketAddress ()
Protected Attributes inherited from net::config::ConfigSection
CLI::App * section = nullptr
Detailed Description
template<typename SocketAddressT>
class net::config::ConfigAddressLocal< SocketAddressT >
Definition at line 35 of file ConfigAddressLocal.h.
Member Typedef Documentation
Super
template<typename SocketAddressT > using net::config::ConfigAddressLocal< SocketAddressT >::Super = net::config::ConfigAddress<SocketAddressT> private
Definition at line 36 of file ConfigAddressLocal.h.
Constructor & Destructor Documentation
ConfigAddressLocal()
template<typename SocketAddress > net::config::ConfigAddressLocal< SocketAddress >::ConfigAddressLocal (ConfigInstance * instance) explicit protected
Definition at line 31 of file ConfigAddressLocal.hpp.
        : Super::ConfigAddress(instance, "local", "Local side of connection for instance '" + instance->getInstanceName() + "'") {
    }
References net::config::ConfigAddressLocal< SocketAddressT >::ConfigAddressLocal(), and net::config::ConfigInstance::getInstanceName().
Referenced by net::config::ConfigAddressLocal< SocketAddressT >::ConfigAddressLocal().
The documentation for this class was generated from the following files:
net/config/ConfigAddressLocal.h
net/config/ConfigAddressLocal.hpp