SNode.C: core::socket::stream::legacy::SocketAcceptor< PhysicalServerSocketT, ConfigT > Class Template Reference
core::socket::stream::legacy::SocketAcceptor< PhysicalServerSocketT, ConfigT > Class Template Reference
#include <SocketAcceptor.h>
Public Types
using SocketAddress = typename Super::SocketAddress
using Config = typename Super::Config
using SocketConnection = typename Super::SocketConnection
Public Member Functions
SocketAcceptor (const std::shared_ptr< core::socket::stream::SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus, const std::shared_ptr< Config > &config)
SocketAcceptor (const SocketAcceptor &socketAcceptor)
Private Types
using Super = core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >
using PhysicalServerSocket = PhysicalServerSocketT
Private Member Functions
void useNextSocketAddress () override
virtual void init ()
void acceptEvent () override
void unobservedEvent () final
void destruct () final
virtual void acceptTimeout ()
void dispatchEvent () final
void timeoutEvent () final
void signalEvent (int signum) override
int getRegisteredFd () const
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
void onEvent (const utils::Timeval &currentTime) final
void onSignal (int signum)
void triggered (const utils::Timeval &currentTime)
void setEnabled (const utils::Timeval &currentTime)
void setDisabled ()
void observed ()
void unObserved ()
void span ()
void relax ()
const std::string & getName () const
Static Private Member Functions
static void atNextTick (const std::function< void(void)> &callBack)
Private Attributes
PhysicalServerSocket physicalServerSocket
SocketAddress localAddress
std::shared_ptr< core::socket::stream::SocketContextFactory > socketContextFactory
std::function< void(SocketConnection *)> onConnect
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
std::function< void(const SocketAddress &, core::socket::State)> onStatus
std::shared_ptr< Config > config
DescriptorEventPublisher & descriptorEventPublisher
int observedFd = -1
bool enabled = false
bool suspended = false
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
int observationCounter = 0
Event event
Detailed Description
template<typename PhysicalServerSocketT, typename ConfigT>
class core::socket::stream::legacy::SocketAcceptor< PhysicalServerSocketT, ConfigT >
Definition at line 39 of file SocketAcceptor.h.
Member Typedef Documentation
Config
template<typename PhysicalServerSocketT , typename ConfigT > using core::socket::stream::legacy::SocketAcceptor< PhysicalServerSocketT, ConfigT >::Config = typename Super::Config
Definition at line 46 of file SocketAcceptor.h.
PhysicalServerSocket
using core::socket::stream::SocketAcceptor< PhysicalServerSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::PhysicalServerSocket = PhysicalServerSocketT private inherited
Definition at line 42 of file SocketAcceptor.h.
SocketAddress
template<typename PhysicalServerSocketT , typename ConfigT > using core::socket::stream::legacy::SocketAcceptor< PhysicalServerSocketT, ConfigT >::SocketAddress = typename Super::SocketAddress
Definition at line 45 of file SocketAcceptor.h.
SocketConnection
template<typename PhysicalServerSocketT , typename ConfigT > using core::socket::stream::legacy::SocketAcceptor< PhysicalServerSocketT, ConfigT >::SocketConnection = typename Super::SocketConnection
Definition at line 47 of file SocketAcceptor.h.
Super
template<typename PhysicalServerSocketT , typename ConfigT > using core::socket::stream::legacy::SocketAcceptor< PhysicalServerSocketT, ConfigT >::Super = core::socket::stream::SocketAcceptor<PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection> private
Definition at line 42 of file SocketAcceptor.h.
Constructor & Destructor Documentation
SocketAcceptor() [1/2]
template<typename PhysicalServerSocket , typename Config > core::socket::stream::legacy::SocketAcceptor< PhysicalServerSocket, Config >::SocketAcceptor (const std::shared_ptr< core::socket::stream::SocketContextFactory > & socketContextFactory, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::function< void(const SocketAddress &, core::socket::State)> & onStatus, const std::shared_ptr< Config > & config)
Definition at line 32 of file SocketAcceptor.hpp.
        : Super(
              socketContextFactory,
              onConnect,
              [socketContextFactory, onConnected](SocketConnection* socketConnection) -> void {
                  onConnected(socketConnection);
                  socketConnection->connectSocketContext(socketContextFactory);
              },
              onDisconnect,
              onStatus,
              config) {
    }
SocketAcceptor() [2/2]
template<typename PhysicalSocketServer , typename Config > core::socket::stream::legacy::SocketAcceptor< PhysicalSocketServer, Config >::SocketAcceptor (const SocketAcceptor< PhysicalServerSocketT, ConfigT > & socketAcceptor)
Definition at line 52 of file SocketAcceptor.hpp.
        : Super(socketAcceptor) {
    }
Member Function Documentation
acceptEvent()
void core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::acceptEvent () override private virtual inherited
Implements core::eventreceiver::AcceptEventReceiver.
Definition at line 67 of file SocketAcceptor.hpp.
{
        int acceptsPerTick = config->getAcceptsPerTick();
        do {
            PhysicalServerSocket connectedPhysicalSocket(physicalServerSocket.accept4(PhysicalServerSocket::Flags::NONBLOCK),
                                                         physicalServerSocket.getBindAddress());
            if (connectedPhysicalSocket.isValid()) {
                LOG(TRACE) << config->getInstanceName() << " accept: Success '" << connectedPhysicalSocket.getBindAddress().toString()
                           << "'";
                SocketConnection* socketConnection =
                    new SocketConnection(config->getInstanceName(),
                                         std::move(connectedPhysicalSocket),
                                         onDisconnect,
                                         localAddress.toString(false),
                                         getLocalSocketAddress<SocketAddress>(connectedPhysicalSocket, config),
                                         getRemoteSocketAddress<SocketAddress>(connectedPhysicalSocket, config),
                                         config->getReadTimeout(),
                                         config->getWriteTimeout(),
                                         config->getReadBlockSize(),
                                         config->getWriteBlockSize(),
                                         config->getTerminateTimeout());
                onConnect(socketConnection);
                onConnected(socketConnection);
            } else if (errno != EINTR && errno != EAGAIN && errno != EWOULDBLOCK) {
                PLOG(TRACE) << config->getInstanceName() << " accept: Failed '" << physicalServerSocket.getBindAddress().toString() << "'";
            }
        } while (--acceptsPerTick > 0);
    }
acceptTimeout()
void core::eventreceiver::AcceptEventReceiver::acceptTimeout () private virtual inherited
Definition at line 38 of file AcceptEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
Referenced by core::eventreceiver::AcceptEventReceiver::timeoutEvent().
atNextTick()
void core::EventReceiver::atNextTick (const std::function< void(void)> & callBack) static inherited
Definition at line 28 of file EventReceiver.cpp.
{
        class NextTickEvent : public core::EventReceiver {
        public:
            explicit NextTickEvent(const std::function<void(void)>& callBack)
                : core::EventReceiver("RequestEvent")
                , callBack(callBack) {
            }
            void onEvent([[maybe_unused]] const utils::Timeval& currentTime) override {
                callBack();
                delete this;
            }
        private:
            std::function<void(void)> callBack;
        };
        (new NextTickEvent(callBack))->span();
    }
References core::EventReceiver::EventReceiver(), and core::EventReceiver::span().
Referenced by web::http::client::SocketContext::initiateRequest(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestDelivered(), web::http::client::SocketContext::responseDelivered(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), and core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector().
checkTimeout()
void core::DescriptorEventReceiver::checkTimeout (const utils::Timeval & currentTime) inherited
Definition at line 168 of file DescriptorEventReceiver.cpp.
{
        if (maxInactivity > 0 && currentTime - lastTriggered >= maxInactivity) {
            timeoutEvent();
        }
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), utils::Timeval::operator>(), utils::Timeval::operator>=(), and core::DescriptorEventReceiver::timeoutEvent().
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents().
destruct()
void core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::destruct () final protected virtual inherited
Reimplemented from core::EventReceiver.
Definition at line 72 of file SocketAcceptor.hpp.
{
        delete this;
    }
disable()
void core::DescriptorEventReceiver::disable () protected inherited
Definition at line 90 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            enabled = false;
            descriptorEventPublisher.disable(this);
            LOG(TRACE) << getName() << " (" << observedFd << "): Disabled";
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Double disable";
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::disable(), core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), and core::DescriptorEventReceiver::observedFd.
Referenced by core::eventreceiver::AcceptEventReceiver::acceptTimeout(), database::mariadb::MariaDBConnection::commandContinue(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectEvent(), core::eventreceiver::ConnectEventReceiver::connectTimeout(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::connectTimeout(), core::DescriptorEventPublisher::disable(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::pipe::PipeSource::eof(), core::eventreceiver::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSink::readEvent(), core::eventreceiver::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::socket::stream::SocketWriter::signalEvent(), core::eventreceiver::AcceptEventReceiver::signalEvent(), core::eventreceiver::ConnectEventReceiver::signalEvent(), core::eventreceiver::ExceptionalConditionEventReceiver::signalEvent(), core::eventreceiver::ReadEventReceiver::signalEvent(), core::eventreceiver::WriteEventReceiver::signalEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), core::pipe::PipeSource::writeEvent(), core::eventreceiver::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
dispatchEvent()
void core::eventreceiver::AcceptEventReceiver::dispatchEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 42 of file AcceptEventReceiver.cpp.
{
        acceptEvent();
    }
References core::eventreceiver::AcceptEventReceiver::acceptEvent().
enable()
bool core::DescriptorEventReceiver::enable (int fd) protected inherited
Definition at line 67 of file DescriptorEventReceiver.cpp.
{
        if (core::eventLoopState() != core::State::STOPPING) {
            if (!enabled) {
                observedFd = fd;
                enabled = true;
                descriptorEventPublisher.enable(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double enable";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Enable after signal";
        }
        return enabled;
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventPublisher::enable(), core::DescriptorEventReceiver::enabled, core::eventLoopState(), core::EventReceiver::getName(), core::DescriptorEventReceiver::observedFd, and core::STOPPING.
Referenced by core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::init(), core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 65 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::socket::stream::tls::SocketReader::read(), core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::SocketWriter::shutdownWrite(), core::socket::stream::SocketWriter::streamEof(), core::socket::stream::SocketWriter::streamToPeer(), core::DescriptorEventReceiver::suspend(), and core::socket::stream::tls::SocketWriter::write().
getRegisteredFd()
int core::DescriptorEventReceiver::getRegisteredFd () const inherited
Definition at line 63 of file DescriptorEventReceiver.cpp.
{
        return observedFd;
    }
References core::DescriptorEventReceiver::observedFd.
Referenced by core::DescriptorEventPublisher::enable(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::select::DescriptorEventPublisher::muxAdd(), core::poll::PollFdsManager::muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOff(), core::select::DescriptorEventPublisher::muxOff(), core::epoll::DescriptorEventPublisher::EPollEvents::muxOn(), core::select::DescriptorEventPublisher::muxOn(), core::socket::stream::legacy::SocketReader::read(), core::pipe::PipeSink::readEvent(), core::socket::stream::legacy::SocketWriter::write(), core::pipe::PipeSource::writeEvent(), core::pipe::PipeSink::~PipeSink(), and core::pipe::PipeSource::~PipeSource().
getTimeout()
utils::Timeval core::DescriptorEventReceiver::getTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 149 of file DescriptorEventReceiver.cpp.
{
        return maxInactivity > 0 ? currentTime > lastTriggered ? maxInactivity - (currentTime - lastTriggered) : 0 : TIMEOUT::MAX;
    }
References core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::DescriptorEventPublisher::getNextTimeout().
init()
void core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::init () protected virtual inherited
Definition at line 64 of file SocketAcceptor.hpp.
{
        if (!config->getDisabled()) {
            try {
                LOG(TRACE) << config->getInstanceName() << ": Starting";
                localAddress = config->Local::getSocketAddress();
                core::socket::State state = core::socket::STATE_OK;
                if (physicalServerSocket.open(config->getSocketOptions(), PhysicalServerSocket::Flags::NONBLOCK) < 0) {
                    switch (errno) {
                        case EMFILE:
                        case ENFILE:
                        case ENOBUFS:
                        case ENOMEM:
                            state = core::socket::STATE_ERROR;
                            PLOG(TRACE) << config->getInstanceName() << " open: '" << localAddress.toString() << "'";
                            break;
                        default:
                            state = core::socket::STATE_FATAL;
                            PLOG(TRACE) << config->getInstanceName() << " open: '" << localAddress.toString() << "'";
                            break;
                    }
                } else if (physicalServerSocket.bind(localAddress) < 0) {
                    switch (errno) {
                        case EADDRINUSE:
                            state = core::socket::STATE_ERROR;
                            PLOG(TRACE) << config->getInstanceName() << " bind: '" << localAddress.toString() << "'";
                            break;
                        default:
                            state = core::socket::STATE_FATAL;
                            PLOG(TRACE) << config->getInstanceName() << " bind: '" << localAddress.toString() << "'";
                            break;
                    }
                } else if (physicalServerSocket.listen(config->getBacklog()) < 0) {
                    switch (errno) {
                        case EADDRINUSE:
                            state = core::socket::STATE_ERROR;
                            PLOG(TRACE) << config->getInstanceName() << " listen: '" << localAddress.toString() << "'";
                            break;
                        default:
                            state = core::socket::STATE_FATAL;
                            PLOG(TRACE) << config->getInstanceName() << " listen: '" << localAddress.toString() << "'";
                            break;
                    }
                } else {
                    if (enable(physicalServerSocket.getFd())) {
                        LOG(TRACE) << config->getInstanceName() << " enabled: '" << localAddress.toString() << "' success";
                    } else {
                        LOG(TRACE) << config->getInstanceName() << " enabled: '" << localAddress.toString() << "' failed";
                    }
                }
                if (localAddress.useNext()) {
                    LOG(TRACE) << config->getInstanceName() << ": Using next SocketAddress '"
                               << config->Local::getSocketAddress().toString() << "'";
                    onStatus(localAddress, (state | core::socket::State::NO_RETRY));
                    useNextSocketAddress();
                } else {
                    onStatus(localAddress, state);
                }
            } catch (const typename SocketAddress::BadSocketAddress& badSocketAddress) {
                LOG(TRACE) << config->getInstanceName() << ": " << badSocketAddress.what();
                onStatus({}, core::socket::STATE(badSocketAddress.getState(), badSocketAddress.getErrnum(), badSocketAddress.what()));
            }
        } else {
            LOG(TRACE) << config->getInstanceName() << ": Disabled";
            onStatus({}, core::socket::STATE_DISABLED);
        }
        if (isEnabled()) {
            core::eventreceiver::AcceptEventReceiver::setTimeout(config->getAcceptTimeout());
        } else {
            destruct();
        }
    }
isEnabled()
bool core::DescriptorEventReceiver::isEnabled () const inherited
Definition at line 104 of file DescriptorEventReceiver.cpp.
{
        return enabled;
    }
References core::DescriptorEventReceiver::enabled.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketWriter::sendToPeer(), and core::socket::stream::SocketWriter::streamToPeer().
isSuspended()
bool core::DescriptorEventReceiver::isSuspended () const inherited
Definition at line 135 of file DescriptorEventReceiver.cpp.
{
        return suspended;
    }
References core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::pipe::PipeSource::send().
observed()
void core::Observer::observed () protected inherited
Definition at line 38 of file DescriptorEventReceiver.cpp.
{
        observationCounter++;
    }
References core::Observer::observationCounter.
Referenced by core::DescriptorEventReceiver::setEnabled().
onEvent()
void core::DescriptorEventReceiver::onEvent (const utils::Timeval & currentTime) final private virtual inherited
Implements core::EventReceiver.
Definition at line 153 of file DescriptorEventReceiver.cpp.
{
        eventCounter++;
        triggered(currentTime);
        dispatchEvent();
    }
References core::DescriptorEventReceiver::dispatchEvent(), core::DescriptorEventReceiver::eventCounter, and core::DescriptorEventReceiver::triggered().
onSignal()
void core::DescriptorEventReceiver::onSignal (int signum) private inherited
Definition at line 160 of file DescriptorEventReceiver.cpp.
{
        signalEvent(signum);
    }
References core::DescriptorEventReceiver::signalEvent().
Referenced by core::DescriptorEventPublisher::signal().
relax()
void core::EventReceiver::relax () inherited
Definition at line 61 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
resume()
void core::DescriptorEventReceiver::resume () protected inherited
Definition at line 121 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (suspended) {
                suspended = false;
                lastTriggered = utils::Timeval::currentTime();
                descriptorEventPublisher.resume(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double resume";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Resume while not enabled";
        }
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::lastTriggered, core::DescriptorEventReceiver::observedFd, utils::Timeval::operator=(), core::DescriptorEventPublisher::resume(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), database::mariadb::MariaDBConnection::commandStart(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
setDisabled()
void core::DescriptorEventReceiver::setDisabled () private inherited
Definition at line 100 of file DescriptorEventReceiver.cpp.
{
        unObserved();
    }
References core::Observer::unObserved().
setEnabled()
void core::DescriptorEventReceiver::setEnabled (const utils::Timeval & currentTime) private inherited
Definition at line 84 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
        observed();
    }
References core::DescriptorEventReceiver::lastTriggered, core::Observer::observed(), and utils::Timeval::operator=().
Referenced by core::DescriptorEventPublisher::enable().
setTimeout()
void core::DescriptorEventReceiver::setTimeout (const utils::Timeval & timeout) inherited
Definition at line 139 of file DescriptorEventReceiver.cpp.
{
        if (timeout == TIMEOUT::DEFAULT) {
            this->maxInactivity = initialTimeout;
        } else {
            this->maxInactivity = timeout;
        }
        triggered(utils::Timeval::currentTime());
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::TIMEOUT::DEFAULT, core::DescriptorEventReceiver::initialTimeout, core::DescriptorEventReceiver::maxInactivity, utils::Timeval::operator=(), utils::Timeval::operator==(), and core::DescriptorEventReceiver::triggered().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::init(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::init(), and core::socket::stream::SocketWriter::shutdownWrite().
signalEvent()
void core::eventreceiver::AcceptEventReceiver::signalEvent (int signum) override private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 50 of file AcceptEventReceiver.cpp.
{
        disable();
    }
References core::DescriptorEventReceiver::disable().
span()
void core::EventReceiver::span () inherited
Definition at line 57 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by core::EventReceiver::atNextTick(), database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), core::file::FileReader::start(), core::file::FileReader::stop(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
suspend()
void core::DescriptorEventReceiver::suspend () protected inherited
Definition at line 108 of file DescriptorEventReceiver.cpp.
{
        if (enabled) {
            if (!suspended) {
                suspended = true;
                descriptorEventPublisher.suspend(this);
            } else {
                LOG(TRACE) << getName() << " (" << observedFd << "): Double suspend";
            }
        } else {
            LOG(TRACE) << getName() << " (" << observedFd << "): Suspend while not enabled";
        }
    }
References core::DescriptorEventReceiver::descriptorEventPublisher, core::DescriptorEventReceiver::enabled, core::EventReceiver::getName(), core::DescriptorEventReceiver::observedFd, core::DescriptorEventPublisher::suspend(), and core::DescriptorEventReceiver::suspended.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), and core::pipe::PipeSource::writeEvent().
timeoutEvent()
void core::eventreceiver::AcceptEventReceiver::timeoutEvent () final private virtual inherited
Implements core::DescriptorEventReceiver.
Definition at line 46 of file AcceptEventReceiver.cpp.
{
        acceptTimeout();
    }
References core::eventreceiver::AcceptEventReceiver::acceptTimeout().
triggered()
void core::DescriptorEventReceiver::triggered (const utils::Timeval & currentTime) private inherited
Definition at line 164 of file DescriptorEventReceiver.cpp.
{
        lastTriggered = currentTime;
    }
References core::DescriptorEventReceiver::lastTriggered, and utils::Timeval::operator=().
Referenced by core::DescriptorEventReceiver::onEvent(), core::DescriptorEventPublisher::releaseDisabledEvents(), and core::DescriptorEventReceiver::setTimeout().
unObserved()
void core::Observer::unObserved () protected inherited
Definition at line 42 of file DescriptorEventReceiver.cpp.
{
        observationCounter--;
        if (observationCounter == 0) {
            unobservedEvent();
        }
    }
References core::Observer::observationCounter, and core::Observer::unobservedEvent().
Referenced by core::DescriptorEventReceiver::setDisabled().
unobservedEvent()
void core::socket::stream::SocketAcceptor< PhysicalSocketServer, Config, SocketConnection >::unobservedEvent () final private virtual inherited
Implements core::Observer.
Definition at line 69 of file SocketAcceptor.hpp.
{
        destruct();
    }
useNextSocketAddress()
template<typename PhysicalClientSocket , typename Config > void core::socket::stream::legacy::SocketAcceptor< PhysicalClientSocket, Config >::useNextSocketAddress () override private virtual
Implements core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >.
Definition at line 57 of file SocketAcceptor.hpp.
{
        new SocketAcceptor(*this);
    }
Member Data Documentation
config
std::shared_ptr<Config> core::socket::stream::SocketAcceptor< PhysicalServerSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::config protected inherited
Definition at line 87 of file SocketAcceptor.h.
descriptorEventPublisher
DescriptorEventPublisher& core::DescriptorEventReceiver::descriptorEventPublisher private inherited
Definition at line 101 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
enabled
bool core::DescriptorEventReceiver::enabled = false private inherited
Definition at line 105 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
event
Event core::EventReceiver::event private inherited
Definition at line 65 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
eventCounter
int core::DescriptorEventReceiver::eventCounter = 0 private inherited
Definition at line 112 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::onEvent().
initialTimeout
const utils::Timeval core::DescriptorEventReceiver::initialTimeout private inherited
Definition at line 110 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::DescriptorEventReceiver(), and core::DescriptorEventReceiver::setTimeout().
lastTriggered
utils::Timeval core::DescriptorEventReceiver::lastTriggered private inherited
Definition at line 108 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setEnabled(), and core::DescriptorEventReceiver::triggered().
localAddress
SocketAddress core::socket::stream::SocketAcceptor< PhysicalServerSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::localAddress private inherited
Definition at line 76 of file SocketAcceptor.h.
maxInactivity
utils::Timeval core::DescriptorEventReceiver::maxInactivity private inherited
Definition at line 109 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::checkTimeout(), core::DescriptorEventReceiver::DescriptorEventReceiver(), core::DescriptorEventReceiver::getTimeout(), and core::DescriptorEventReceiver::setTimeout().
observationCounter
int core::Observer::observationCounter = 0 private inherited
Definition at line 54 of file DescriptorEventReceiver.h.
Referenced by core::Observer::observed(), and core::Observer::unObserved().
observedFd
int core::DescriptorEventReceiver::observedFd = -1 private inherited
Definition at line 103 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
onConnect
std::function<void(SocketConnection*)> core::socket::stream::SocketAcceptor< PhysicalServerSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::onConnect protected inherited
Definition at line 81 of file SocketAcceptor.h.
onConnected
std::function<void(SocketConnection*)> core::socket::stream::SocketAcceptor< PhysicalServerSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::onConnected protected inherited
Definition at line 82 of file SocketAcceptor.h.
onDisconnect
std::function<void(SocketConnection*)> core::socket::stream::SocketAcceptor< PhysicalServerSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::onDisconnect protected inherited
Definition at line 83 of file SocketAcceptor.h.
onStatus
std::function<void(const SocketAddress&, core::socket::State)> core::socket::stream::SocketAcceptor< PhysicalServerSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::onStatus protected inherited
Definition at line 85 of file SocketAcceptor.h.
physicalServerSocket
PhysicalServerSocket core::socket::stream::SocketAcceptor< PhysicalServerSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::physicalServerSocket private inherited
Definition at line 75 of file SocketAcceptor.h.
socketContextFactory
std::shared_ptr<core::socket::stream::SocketContextFactory> core::socket::stream::SocketAcceptor< PhysicalServerSocketT , ConfigT, core::socket::stream::legacy::SocketConnection >::socketContextFactory protected inherited
Definition at line 79 of file SocketAcceptor.h.
suspended
bool core::DescriptorEventReceiver::suspended = false private inherited
Definition at line 106 of file DescriptorEventReceiver.h.
Referenced by core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
The documentation for this class was generated from the following files:
core/socket/stream/legacy/SocketAcceptor.h
core/socket/stream/legacy/SocketAcceptor.hpp