SNode.C: net::config::stream::legacy::ConfigSocketServer< ConfigSocketServerBaseT > Class Template Reference
net::config::stream::legacy::ConfigSocketServer< ConfigSocketServerBaseT > Class Template Reference
#include <ConfigSocketServer.h>
Public Types
enum class Role { SERVER , CLIENT }
Public Member Functions
ConfigSocketServer (const std::string &name)
Role getRole ()
const std::string & getInstanceName () const
void setInstanceName (const std::string &instanceName)
bool getDisabled () const
void setDisabled (bool disabled=true)
CLI::App * add_section (const std::string &name, const std::string &description)
void required (CLI::App *section, bool req=true)
bool getRequired () const
Protected Member Functions
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
Protected Attributes
CLI::App * section = nullptr
Private Attributes
uint8_t requiredCount = 0
std::string instanceName
Role role
CLI::App * instanceSc = nullptr
CLI::Option * disableOpt = nullptr
ConfigInstance * instance = nullptr
Static Private Attributes
static const std::string nameAnonymous = "<anonymous>"
Detailed Description
template<typename ConfigSocketServerBaseT>
class net::config::stream::legacy::ConfigSocketServer< ConfigSocketServerBaseT >
Definition at line 33 of file ConfigSocketServer.h.
Member Enumeration Documentation
Role
enum class net::config::ConfigInstance::Role strong inherited
Enumerator
SERVER
CLIENT
Definition at line 39 of file ConfigInstance.h.
{ SERVER, CLIENT };
Constructor & Destructor Documentation
ConfigSocketServer()
template<typename ConfigSocketServerBase > net::config::stream::legacy::ConfigSocketServer< ConfigSocketServerBase >::ConfigSocketServer (const std::string & name) explicit
Definition at line 29 of file ConfigSocketServer.hpp.
        : net::config::ConfigInstance(name, net::config::ConfigInstance::Role::SERVER)
        , ConfigSocketServerBase(this)
        , net::config::ConfigLegacy(this) {
    }
References net::config::ConfigInstance::SERVER.
Referenced by net::in::stream::legacy::config::ConfigSocketServer::ConfigSocketServer(), net::in6::stream::legacy::config::ConfigSocketServer::ConfigSocketServer(), net::l2::stream::legacy::config::ConfigSocketServer::ConfigSocketServer(), net::rc::stream::legacy::config::ConfigSocketServer::ConfigSocketServer(), and net::un::stream::legacy::config::ConfigSocketServer::ConfigSocketServer().
Member Function Documentation
add_flag() [1/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 110 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag(name, description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [2/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 125 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [3/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 64 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [4/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 71 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [5/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_flag() [6/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag_function() [1/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) protected inherited
Definition at line 134 of file ConfigSection.cpp.
{
        section->disabled(false);
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [2/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 155 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), and net::config::ConfigPhysicalSocketClient::ConfigPhysicalSocketClient().
add_option() [1/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) protected inherited
Definition at line 79 of file ConfigSection.cpp.
{
        if (!instance->getInstanceName().empty() && !section->get_display_name().empty()) {
            section->disabled(false);
        }
        opt = section //
                  ->add_option(name, description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigInstance::getInstanceName(), net::config::ConfigSection::instance, and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [2/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 95 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [3/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 100 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [4/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 46 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [5/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 53 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [6/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
Referenced by net::config::ConfigTls::ConfigTls().
add_option() [7/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
add_section()
CLI::App * net::config::ConfigInstance::add_section (const std::string & name, const std::string & description) inherited
Definition at line 98 of file ConfigInstance.cpp.
{
        CLI::App* sectionSc = instanceSc //
                                  ->add_subcommand(name, description)
                                  ->fallthrough()
                                  ->configurable(false)
                                  ->allow_extras(false)
                                  ->group("Sections")
                                  ->disabled(this->instanceName.empty() || name.empty());
        sectionSc //
            ->option_defaults()
            ->configurable(!sectionSc->get_disabled());
        if (!sectionSc->get_disabled()) {
            utils::Config::add_standard_flags(sectionSc);
            utils::Config::add_help_flag(sectionSc);
        }
        return sectionSc;
    }
References utils::Config::add_help_flag(), utils::Config::add_standard_flags(), net::config::ConfigInstance::instanceName, and net::config::ConfigInstance::instanceSc.
Referenced by net::config::ConfigSection::ConfigSection().
getDisabled()
bool net::config::ConfigInstance::getDisabled () const inherited
Definition at line 141 of file ConfigInstance.cpp.
{
        return disableOpt //
            ->as<bool>();
    }
References net::config::ConfigInstance::disableOpt.
getInstanceName()
const std::string & net::config::ConfigInstance::getInstanceName () const inherited
Definition at line 90 of file ConfigInstance.cpp.
{
        return instanceName.empty() ? nameAnonymous : instanceName;
    }
References net::config::ConfigInstance::instanceName, and net::config::ConfigInstance::nameAnonymous.
Referenced by net::config::ConfigSection::add_option(), net::un::config::ConfigAddress< ConfigAddressTypeT >::ConfigAddress(), net::config::ConfigSection::ConfigSection(), net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSniCtx(), net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >::getSslCtx(), and net::config::stream::tls::ConfigSocketServer< ConfigSocketServerBaseT >::getSslCtx().
getRequired()
bool net::config::ConfigInstance::getRequired () const inherited
Definition at line 137 of file ConfigInstance.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigInstance::requiredCount.
getRole()
ConfigInstance::Role net::config::ConfigInstance::getRole () inherited
Definition at line 86 of file ConfigInstance.cpp.
{
        return role;
    }
References net::config::ConfigInstance::role.
required() [1/3]
bool net::config::ConfigSection::required () const protected inherited
Definition at line 75 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [2/3]
void net::config::ConfigInstance::required (CLI::App * section, bool req = true) inherited
Definition at line 119 of file ConfigInstance.cpp.
{
        if (req != section->get_required()) {
            if (req) {
                ++requiredCount;
                instanceSc->needs(section);
            } else {
                --requiredCount;
                instanceSc->remove_needs(section);
            }
            section->required(req);
            if (!disableOpt->as<bool>()) {
                utils::Config::required(instanceSc, requiredCount > 0);
            }
        }
    }
References net::config::ConfigInstance::disableOpt, net::config::ConfigInstance::instanceSc, utils::Config::required(), and net::config::ConfigInstance::requiredCount.
Referenced by net::config::ConfigSection::required().
required() [3/3]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) protected inherited
Definition at line 58 of file ConfigSection.cpp.
{
        if (req != opt->get_required()) {
            if (req) {
                ++requiredCount;
                section->needs(opt);
                opt->default_str("");
            } else {
                --requiredCount;
                section->remove_needs(opt);
            }
            opt->required(req);
            instance->required(section, requiredCount > 0);
        }
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
setDisabled()
void net::config::ConfigInstance::setDisabled (bool disabled = true) inherited
Definition at line 146 of file ConfigInstance.cpp.
{
        disableOpt //
            ->default_val(disabled ? "true" : "false")
            ->clear();
        utils::Config::disabled(instanceSc, disabled);
    }
References utils::Config::disabled(), net::config::ConfigInstance::disableOpt, and net::config::ConfigInstance::instanceSc.
setInstanceName()
void net::config::ConfigInstance::setInstanceName (const std::string & instanceName) inherited
Definition at line 94 of file ConfigInstance.cpp.
{
        this->instanceName = instanceName;
    }
References net::config::ConfigInstance::instanceName.
Member Data Documentation
disableOpt
CLI::Option* net::config::ConfigInstance::disableOpt = nullptr private inherited
Definition at line 73 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::ConfigInstance(), net::config::ConfigInstance::getDisabled(), net::config::ConfigInstance::required(), and net::config::ConfigInstance::setDisabled().
instance
ConfigInstance* net::config::ConfigSection::instance = nullptr private inherited
Definition at line 121 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), and net::config::ConfigSection::required().
instanceName
std::string net::config::ConfigInstance::instanceName private inherited
Definition at line 67 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::add_section(), net::config::ConfigInstance::ConfigInstance(), net::config::ConfigInstance::getInstanceName(), and net::config::ConfigInstance::setInstanceName().
instanceSc
CLI::App* net::config::ConfigInstance::instanceSc = nullptr private inherited
Definition at line 72 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::add_section(), net::config::ConfigInstance::ConfigInstance(), net::config::ConfigInstance::required(), net::config::ConfigInstance::setDisabled(), and net::config::ConfigInstance::~ConfigInstance().
nameAnonymous
const std::string net::config::ConfigInstance::nameAnonymous = "<anonymous>" static private inherited
Definition at line 68 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::getInstanceName().
requiredCount
uint8_t net::config::ConfigInstance::requiredCount = 0 private inherited
Definition at line 65 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::getRequired(), and net::config::ConfigInstance::required().
role
Role net::config::ConfigInstance::role private inherited
Definition at line 70 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::ConfigInstance(), and net::config::ConfigInstance::getRole().
section
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 126 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
The documentation for this class was generated from the following files:
net/config/stream/legacy/ConfigSocketServer.h
net/config/stream/legacy/ConfigSocketServer.hpp