SNode.C: CallForHelp Class Reference
CallForHelp Class Reference
Errors
-h or –help on command line
#include <CLI11.hpp>
Public Member Functions
CallForHelp (std::string msg, ExitCodes exit_code)
CallForHelp (std::string msg, int exit_code)
CallForHelp ()
Public Member Functions inherited from Success
Success (std::string msg, ExitCodes exit_code)
Success (std::string msg, int exit_code)
Success ()
Public Member Functions inherited from ParseError
ParseError (std::string msg, ExitCodes exit_code)
ParseError (std::string msg, int exit_code)
Public Member Functions inherited from Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Protected Member Functions
CallForHelp (std::string ename, std::string msg, int exit_code)
CallForHelp (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from Success
Success (std::string ename, std::string msg, int exit_code)
Success (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from ParseError
ParseError (std::string ename, std::string msg, int exit_code)
ParseError (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
-h or –help on command line
Definition at line 1162 of file CLI11.hpp.
Constructor & Destructor Documentation
CallForHelp() [1/5]
CallForHelp::CallForHelp (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 1163 of file CLI11.hpp.
CallForHelp() [2/5]
CallForHelp::CallForHelp (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 1163 of file CLI11.hpp.
CallForHelp() [3/5]
CallForHelp::CallForHelp (std::string msg, ExitCodes exit_code) inline
Definition at line 1163 of file CLI11.hpp.
CallForHelp() [4/5]
CallForHelp::CallForHelp (std::string msg, int exit_code) inline
Definition at line 1163 of file CLI11.hpp.
CallForHelp() [5/5]
CallForHelp::CallForHelp () inline
Definition at line 1164 of file CLI11.hpp.
            : CallForHelp("This should be caught in your main function, see examples", ExitCodes::Success) {
        }
References CallForHelp().
Referenced by App::_process_help_flags(), utils::Config::addHelp(), utils::Config::addSimpleHelp(), and CallForHelp().
The documentation for this class was generated from the following file:
src/utils/CLI11.hpp