SNode.C: net::rc::stream::config::ConfigSocketServer Class Reference
net::rc::stream::config::ConfigSocketServer Class Reference
#include <ConfigSocketServer.h>
Public Types
using Local = net::rc::config::ConfigAddress< net::config::ConfigAddressLocal >
Public Member Functions
ConfigSocketServer (net::config::ConfigInstance *instance)
~ConfigSocketServer () override
utils::Timeval getReadTimeout () const
void setReadTimeout (const utils::Timeval &newReadTimeoutSet)
utils::Timeval getWriteTimeout () const
void setWriteTimeout (const utils::Timeval &newWriteTimeoutSet)
std::size_t getReadBlockSize () const
void setReadBlockSize (std::size_t newReadBlockSize)
std::size_t getWriteBlockSize () const
void setWriteBlockSize (std::size_t newWriteBlockSize)
utils::Timeval getTerminateTimeout () const
void setTerminateTimeout (const utils::Timeval &newTerminateTimeout)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
void setAcceptTimeout (const utils::Timeval &acceptTimeout)
utils::Timeval getAcceptTimeout () const
const std::map< int, const net::phy::PhysicalSocketOption > & getSocketOptions ()
void addSocketOption (int optLevel, int optName, int optValue)
void addSocketOption (int optLevel, int optName, const std::string &optValue)
void addSocketOption (int optLevel, int optName, const std::vector< char > &optValue)
void removeSocketOption (int optName)
void setReuseAddress (bool reuseAddress=true)
bool getReuseAddress ()
bool getReconnect ()
void setReconnect (bool reconnect=true)
double getReconnectTime ()
void setReconnectTime (double time)
void setRetry (bool retry=true)
bool getRetry ()
void setRetryTimeout (double sec)
double getRetryTimeout ()
void setRetryTries (unsigned int tries=0)
unsigned int getRetryTries ()
void setRetryBase (double base)
double getRetryBase ()
void setRetryLimit (unsigned int limit)
unsigned int getRetryLimit ()
void setRetryJitter (double percent)
double getRetryJitter ()
int getBacklog () const
void setBacklog (int newBacklog)
int getAcceptsPerTick () const
void setAcceptsPerTick (int acceptsPerTickSet)
Protected Member Functions
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
void required (CLI::Option *opt, bool req=true)
bool required () const
void required (CLI::Option *opt, bool req=true)
bool required () const
CLI::Option * add_socket_option (CLI::Option *&opt, const std::string &name, int optLevel, int optName, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Protected Attributes
CLI::App * section = nullptr
CLI::App * section = nullptr
CLI::App * section = nullptr
CLI::Option * reuseAddressOpt = nullptr
CLI::Option * retryOpt = nullptr
CLI::Option * retryTriesOpt = nullptr
CLI::Option * retryTimeoutOpt = nullptr
CLI::Option * retryBaseOpt = nullptr
CLI::Option * retryLimitOpt = nullptr
CLI::Option * retryJitterOpt = nullptr
CLI::Option * reconnectOpt = nullptr
CLI::Option * reconnectTimeOpt = nullptr
std::map< int, const net::phy::PhysicalSocketOption > socketOptionsMap
Private Types
using Super = ConfigPhysicalSocket
Private Attributes
CLI::Option * readTimeoutOpt = nullptr
CLI::Option * writeTimeoutOpt = nullptr
CLI::Option * readBlockSizeOpt = nullptr
CLI::Option * writeBlockSizeOpt = nullptr
CLI::Option * terminateTimeoutOpt = nullptr
ConfigInstance * instance = nullptr
uint8_t requiredCount = 0
CLI::Option * acceptTimeoutOpt = nullptr
CLI::Option * backlogOpt = nullptr
CLI::Option * acceptsPerTickOpt = nullptr
Detailed Description
Definition at line 35 of file ConfigSocketServer.h.
Member Typedef Documentation
Local
using net::config::stream::ConfigSocketServer< net::rc::config::ConfigAddress >::Local = net::rc::config::ConfigAddress <net::config::ConfigAddressLocal> inherited
Definition at line 40 of file ConfigSocketServer.h.
Super
using net::config::ConfigPhysicalSocketServer::Super = ConfigPhysicalSocket private inherited
Definition at line 44 of file ConfigPhysicalSocketServer.h.
Constructor & Destructor Documentation
ConfigSocketServer()
net::rc::stream::config::ConfigSocketServer::ConfigSocketServer (net::config::ConfigInstance * instance) explicit
Definition at line 46 of file ConfigSocketServer.cpp.
        : net::config::stream::ConfigSocketServer<net::rc::config::ConfigAddress>(instance) {
        net::rc::config::ConfigAddress<net::config::ConfigAddressLocal>::channelRequired();
        net::rc::config::ConfigAddress<net::config::ConfigAddressLocal>::channelOpt //
            ->check(CLI::Range(1, 30));
    }
References net::rc::config::ConfigAddress< ConfigAddressTypeT >::channelRequired(), and net::config::stream::ConfigSocketServer< ConfigAddressT >::ConfigSocketServer().
~ConfigSocketServer()
net::rc::stream::config::ConfigSocketServer::~ConfigSocketServer () override
Definition at line 54 of file ConfigSocketServer.cpp.
{
    }
Member Function Documentation
add_flag() [1/18]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 116 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_flag_function(name, utils::ResetToDefault(opt), description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References utils::ResetToDefault::ResetToDefault(), and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [2/18]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 116 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_flag_function(name, utils::ResetToDefault(opt), description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References utils::ResetToDefault::ResetToDefault(), and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [3/18]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 116 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_flag_function(name, utils::ResetToDefault(opt), description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References utils::ResetToDefault::ResetToDefault(), and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [4/18]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 129 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [5/18]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 129 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [6/18]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 129 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [7/18]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 63 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [8/18]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 63 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [9/18]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 63 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [10/18]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 70 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [11/18]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 70 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [12/18]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 70 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [13/18]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_flag() [14/18]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_flag() [15/18]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_flag() [16/18]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag() [17/18]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag() [18/18]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag_function() [1/6]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) protected inherited
Definition at line 138 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [2/6]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) protected inherited
Definition at line 138 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [3/6]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) protected inherited
Definition at line 138 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [4/6]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 157 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option().
add_flag_function() [5/6]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 157 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option().
add_flag_function() [6/6]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 157 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option().
add_option() [1/21]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) protected inherited
Definition at line 89 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_option_function<std::string>(name, utils::ResetToDefault(opt), description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References utils::ResetToDefault::ResetToDefault(), and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [2/21]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) protected inherited
Definition at line 89 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_option_function<std::string>(name, utils::ResetToDefault(opt), description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References utils::ResetToDefault::ResetToDefault(), and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [3/21]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) protected inherited
Definition at line 89 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_option_function<std::string>(name, utils::ResetToDefault(opt), description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References utils::ResetToDefault::ResetToDefault(), and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [4/21]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 101 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [5/21]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 101 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [6/21]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 101 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [7/21]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 106 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [8/21]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 106 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [9/21]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 106 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [10/21]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 45 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [11/21]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 45 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [12/21]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 45 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [13/21]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 52 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [14/21]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 52 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [15/21]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 52 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [16/21]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_option() [17/21]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_option() [18/21]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_option() [19/21]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
add_option() [20/21]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
add_option() [21/21]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
add_socket_option()
CLI::Option * net::config::ConfigPhysicalSocket::add_socket_option (CLI::Option *& opt, const std::string & name, int optLevel, int optName, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 130 of file ConfigPhysicalSocket.cpp.
{
        return net::config::ConfigSection::add_flag_function(
            opt,
            name,
            [this, &opt, optLevel, optName](int64_t) -> void {
                if (opt->as<bool>()) {
                    socketOptionsMap.insert({optName, net::phy::PhysicalSocketOption(optLevel, optName, 1)});
                } else {
                    socketOptionsMap.erase(optName);
                }
                (utils::ResetToDefault(opt))(opt->as<std::string>());
            },
            description,
            typeName,
            defaultValue,
            validator);
    }
References net::config::ConfigSection::add_flag_function(), utils::ResetToDefault::operator()(), net::phy::PhysicalSocketOption::PhysicalSocketOption(), utils::ResetToDefault::ResetToDefault(), and net::config::ConfigPhysicalSocket::socketOptionsMap.
addSocketOption() [1/3]
void net::config::ConfigPhysicalSocket::addSocketOption (int optLevel, int optName, const std::string & optValue) inherited
Definition at line 160 of file ConfigPhysicalSocket.cpp.
{
        socketOptionsMap.insert({optName, net::phy::PhysicalSocketOption(optLevel, optName, optValue)});
    }
References net::phy::PhysicalSocketOption::PhysicalSocketOption(), and net::config::ConfigPhysicalSocket::socketOptionsMap.
addSocketOption() [2/3]
void net::config::ConfigPhysicalSocket::addSocketOption (int optLevel, int optName, const std::vector< char > & optValue) inherited
Definition at line 163 of file ConfigPhysicalSocket.cpp.
{
        socketOptionsMap.insert({optName, net::phy::PhysicalSocketOption(optLevel, optName, optValue)});
    }
References net::phy::PhysicalSocketOption::PhysicalSocketOption(), and net::config::ConfigPhysicalSocket::socketOptionsMap.
addSocketOption() [3/3]
void net::config::ConfigPhysicalSocket::addSocketOption (int optLevel, int optName, int optValue) inherited
Definition at line 156 of file ConfigPhysicalSocket.cpp.
{
        socketOptionsMap.insert({optName, net::phy::PhysicalSocketOption(optLevel, optName, optValue)});
    }
References net::phy::PhysicalSocketOption::PhysicalSocketOption(), and net::config::ConfigPhysicalSocket::socketOptionsMap.
Referenced by net::in6::stream::config::ConfigSocketServer::setIPv6Only(), net::config::ConfigPhysicalSocket::setReuseAddress(), net::in::stream::config::ConfigSocketServer::setReusePort(), and net::in6::stream::config::ConfigSocketServer::setReusePort().
getAcceptsPerTick()
int net::config::ConfigListen::getAcceptsPerTick () const inherited
Definition at line 59 of file ConfigListen.cpp.
{
        return acceptsPerTickOpt->as<int>();
    }
References net::config::ConfigListen::acceptsPerTickOpt.
getAcceptTimeout()
utils::Timeval net::config::ConfigPhysicalSocketServer::getAcceptTimeout () const inherited
Definition at line 66 of file ConfigPhysicalSocketServer.cpp.
{
        return acceptTimeoutOpt->as<utils::Timeval>();
    }
References net::config::ConfigPhysicalSocketServer::acceptTimeoutOpt.
getBacklog()
int net::config::ConfigListen::getBacklog () const inherited
Definition at line 49 of file ConfigListen.cpp.
{
        return backlogOpt->as<int>();
    }
References net::config::ConfigListen::backlogOpt.
getReadBlockSize()
std::size_t net::config::ConfigConnection::getReadBlockSize () const inherited
Definition at line 87 of file ConfigConnection.cpp.
{
        return readBlockSizeOpt->as<std::size_t>();
    }
References net::config::ConfigConnection::readBlockSizeOpt.
getReadTimeout()
utils::Timeval net::config::ConfigConnection::getReadTimeout () const inherited
Definition at line 67 of file ConfigConnection.cpp.
{
        return readTimeoutOpt->as<utils::Timeval>();
    }
References net::config::ConfigConnection::readTimeoutOpt.
getReconnect()
bool net::config::ConfigPhysicalSocket::getReconnect () inherited
Definition at line 188 of file ConfigPhysicalSocket.cpp.
{
        return reconnectOpt->as<bool>();
    }
References net::config::ConfigPhysicalSocket::reconnectOpt.
getReconnectTime()
double net::config::ConfigPhysicalSocket::getReconnectTime () inherited
Definition at line 198 of file ConfigPhysicalSocket.cpp.
{
        return reconnectTimeOpt->as<double>();
    }
References net::config::ConfigPhysicalSocket::reconnectTimeOpt.
getRetry()
bool net::config::ConfigPhysicalSocket::getRetry () inherited
Definition at line 214 of file ConfigPhysicalSocket.cpp.
{
        return retryOpt->as<bool>();
    }
References net::config::ConfigPhysicalSocket::retryOpt.
getRetryBase()
double net::config::ConfigPhysicalSocket::getRetryBase () inherited
Definition at line 244 of file ConfigPhysicalSocket.cpp.
{
        return retryBaseOpt->as<double>();
    }
References net::config::ConfigPhysicalSocket::retryBaseOpt.
getRetryJitter()
double net::config::ConfigPhysicalSocket::getRetryJitter () inherited
Definition at line 264 of file ConfigPhysicalSocket.cpp.
{
        return retryJitterOpt->as<double>();
    }
References net::config::ConfigPhysicalSocket::retryJitterOpt.
getRetryLimit()
unsigned int net::config::ConfigPhysicalSocket::getRetryLimit () inherited
Definition at line 254 of file ConfigPhysicalSocket.cpp.
{
        return retryLimitOpt->as<unsigned int>();
    }
References net::config::ConfigPhysicalSocket::retryLimitOpt.
getRetryTimeout()
double net::config::ConfigPhysicalSocket::getRetryTimeout () inherited
Definition at line 224 of file ConfigPhysicalSocket.cpp.
{
        return retryTimeoutOpt->as<double>();
    }
References net::config::ConfigPhysicalSocket::retryTimeoutOpt.
getRetryTries()
unsigned int net::config::ConfigPhysicalSocket::getRetryTries () inherited
Definition at line 234 of file ConfigPhysicalSocket.cpp.
{
        return retryTriesOpt->as<unsigned int>();
    }
References net::config::ConfigPhysicalSocket::retryTriesOpt.
getReuseAddress()
bool net::config::ConfigPhysicalSocket::getReuseAddress () inherited
Definition at line 184 of file ConfigPhysicalSocket.cpp.
{
        return reuseAddressOpt->as<bool>();
    }
References net::config::ConfigPhysicalSocket::reuseAddressOpt.
getSocketOptions()
const std::map< int, const net::phy::PhysicalSocketOption > & net::config::ConfigPhysicalSocket::getSocketOptions () inherited
Definition at line 126 of file ConfigPhysicalSocket.cpp.
{
        return socketOptionsMap;
    }
References net::config::ConfigPhysicalSocket::socketOptionsMap.
getTerminateTimeout()
utils::Timeval net::config::ConfigConnection::getTerminateTimeout () const inherited
Definition at line 107 of file ConfigConnection.cpp.
{
        return terminateTimeoutOpt->as<utils::Timeval>();
    }
References net::config::ConfigConnection::terminateTimeoutOpt.
getWriteBlockSize()
std::size_t net::config::ConfigConnection::getWriteBlockSize () const inherited
Definition at line 97 of file ConfigConnection.cpp.
{
        return writeBlockSizeOpt->as<std::size_t>();
    }
References net::config::ConfigConnection::writeBlockSizeOpt.
getWriteTimeout()
utils::Timeval net::config::ConfigConnection::getWriteTimeout () const inherited
Definition at line 77 of file ConfigConnection.cpp.
{
        return writeTimeoutOpt->as<utils::Timeval>();
    }
References net::config::ConfigConnection::writeTimeoutOpt.
removeSocketOption()
void net::config::ConfigPhysicalSocket::removeSocketOption (int optName) inherited
Definition at line 167 of file ConfigPhysicalSocket.cpp.
{
        socketOptionsMap.erase(optName);
    }
References net::config::ConfigPhysicalSocket::socketOptionsMap.
Referenced by net::in6::stream::config::ConfigSocketServer::setIPv6Only(), net::config::ConfigPhysicalSocket::setReuseAddress(), net::in::stream::config::ConfigSocketServer::setReusePort(), and net::in6::stream::config::ConfigSocketServer::setReusePort().
required() [1/6]
bool net::config::ConfigSection::required () const protected inherited
Definition at line 85 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [2/6]
bool net::config::ConfigSection::required () const protected inherited
Definition at line 85 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [3/6]
bool net::config::ConfigSection::required () const protected inherited
Definition at line 85 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [4/6]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) protected inherited
Definition at line 61 of file ConfigSection.cpp.
{
        if (req && !opt->get_required()) {
            ++requiredCount;
            opt //
                ->default_str("")
                ->required()
                ->clear();
            section //
                ->needs(opt);
        } else if (opt->get_required()) {
            --requiredCount;
            opt //
                ->required(false)
                ->clear();
            section //
                ->remove_needs(opt);
        }
        section //
            ->required(requiredCount > 0);
        instance->required(section, req);
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
required() [5/6]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) protected inherited
Definition at line 61 of file ConfigSection.cpp.
{
        if (req && !opt->get_required()) {
            ++requiredCount;
            opt //
                ->default_str("")
                ->required()
                ->clear();
            section //
                ->needs(opt);
        } else if (opt->get_required()) {
            --requiredCount;
            opt //
                ->required(false)
                ->clear();
            section //
                ->remove_needs(opt);
        }
        section //
            ->required(requiredCount > 0);
        instance->required(section, req);
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
required() [6/6]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) protected inherited
Definition at line 61 of file ConfigSection.cpp.
{
        if (req && !opt->get_required()) {
            ++requiredCount;
            opt //
                ->default_str("")
                ->required()
                ->clear();
            section //
                ->needs(opt);
        } else if (opt->get_required()) {
            --requiredCount;
            opt //
                ->required(false)
                ->clear();
            section //
                ->remove_needs(opt);
        }
        section //
            ->required(requiredCount > 0);
        instance->required(section, req);
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
setAcceptsPerTick()
void net::config::ConfigListen::setAcceptsPerTick (int acceptsPerTickSet) inherited
Definition at line 63 of file ConfigListen.cpp.
{
        acceptsPerTickOpt //
            ->default_val(acceptsPerTickSet)
            ->clear();
    }
References net::config::ConfigListen::acceptsPerTickOpt.
setAcceptTimeout()
void net::config::ConfigPhysicalSocketServer::setAcceptTimeout (const utils::Timeval & acceptTimeout) inherited
Definition at line 60 of file ConfigPhysicalSocketServer.cpp.
{
        acceptTimeoutOpt //
            ->default_val(acceptTimeout)
            ->clear();
    }
References net::config::ConfigPhysicalSocketServer::acceptTimeoutOpt.
setBacklog()
void net::config::ConfigListen::setBacklog (int newBacklog) inherited
Definition at line 53 of file ConfigListen.cpp.
{
        backlogOpt //
            ->default_val(newBacklog)
            ->clear();
    }
References net::config::ConfigListen::backlogOpt.
setReadBlockSize()
void net::config::ConfigConnection::setReadBlockSize (std::size_t newReadBlockSize) inherited
Definition at line 91 of file ConfigConnection.cpp.
{
        readBlockSizeOpt //
            ->default_val(newReadBlockSize)
            ->clear();
    }
References net::config::ConfigConnection::readBlockSizeOpt.
setReadTimeout()
void net::config::ConfigConnection::setReadTimeout (const utils::Timeval & newReadTimeoutSet) inherited
Definition at line 71 of file ConfigConnection.cpp.
{
        readTimeoutOpt //
            ->default_val(newReadTimeoutSet)
            ->clear();
    }
References net::config::ConfigConnection::readTimeoutOpt.
setReconnect()
void net::config::ConfigPhysicalSocket::setReconnect (bool reconnect = true) inherited
Definition at line 192 of file ConfigPhysicalSocket.cpp.
{
        reconnectOpt //
            ->default_val(reconnect)
            ->clear();
    }
References net::config::ConfigPhysicalSocket::reconnectOpt.
setReconnectTime()
void net::config::ConfigPhysicalSocket::setReconnectTime (double time) inherited
Definition at line 202 of file ConfigPhysicalSocket.cpp.
{
        reconnectTimeOpt //
            ->default_val(time)
            ->clear();
    }
References net::config::ConfigPhysicalSocket::reconnectTimeOpt.
setRetry()
void net::config::ConfigPhysicalSocket::setRetry (bool retry = true) inherited
Definition at line 208 of file ConfigPhysicalSocket.cpp.
{
        retryOpt //
            ->default_val(retry)
            ->clear();
    }
References net::config::ConfigPhysicalSocket::retryOpt.
setRetryBase()
void net::config::ConfigPhysicalSocket::setRetryBase (double base) inherited
Definition at line 238 of file ConfigPhysicalSocket.cpp.
{
        retryBaseOpt //
            ->default_val(base)
            ->clear();
    }
References net::config::ConfigPhysicalSocket::retryBaseOpt.
setRetryJitter()
void net::config::ConfigPhysicalSocket::setRetryJitter (double percent) inherited
Definition at line 258 of file ConfigPhysicalSocket.cpp.
{
        retryJitterOpt //
            ->default_val(percent)
            ->clear();
    }
References net::config::ConfigPhysicalSocket::retryJitterOpt.
setRetryLimit()
void net::config::ConfigPhysicalSocket::setRetryLimit (unsigned int limit) inherited
Definition at line 248 of file ConfigPhysicalSocket.cpp.
{
        retryLimitOpt //
            ->default_val(limit)
            ->clear();
    }
References net::config::ConfigPhysicalSocket::retryLimitOpt.
setRetryTimeout()
void net::config::ConfigPhysicalSocket::setRetryTimeout (double sec) inherited
Definition at line 218 of file ConfigPhysicalSocket.cpp.
{
        retryTimeoutOpt //
            ->default_val(sec)
            ->clear();
    }
References net::config::ConfigPhysicalSocket::retryTimeoutOpt.
setRetryTries()
void net::config::ConfigPhysicalSocket::setRetryTries (unsigned int tries = 0) inherited
Definition at line 228 of file ConfigPhysicalSocket.cpp.
{
        retryTriesOpt //
            ->default_val(tries)
            ->clear();
    }
References net::config::ConfigPhysicalSocket::retryTriesOpt.
setReuseAddress()
void net::config::ConfigPhysicalSocket::setReuseAddress (bool reuseAddress = true) inherited
Definition at line 171 of file ConfigPhysicalSocket.cpp.
{
        if (reuseAddress) {
            addSocketOption(SOL_SOCKET, SO_REUSEADDR, 1);
        } else {
            removeSocketOption(SO_REUSEADDR);
        }
        reuseAddressOpt //
            ->default_val(reuseAddress ? "true" : "false")
            ->take_all()
            ->clear();
    }
References net::config::ConfigPhysicalSocket::addSocketOption(), net::config::ConfigPhysicalSocket::removeSocketOption(), and net::config::ConfigPhysicalSocket::reuseAddressOpt.
setTerminateTimeout()
void net::config::ConfigConnection::setTerminateTimeout (const utils::Timeval & newTerminateTimeout) inherited
Definition at line 111 of file ConfigConnection.cpp.
{
        terminateTimeoutOpt //
            ->default_val(newTerminateTimeout)
            ->clear();
    }
References net::config::ConfigConnection::terminateTimeoutOpt.
setWriteBlockSize()
void net::config::ConfigConnection::setWriteBlockSize (std::size_t newWriteBlockSize) inherited
Definition at line 101 of file ConfigConnection.cpp.
{
        writeBlockSizeOpt //
            ->default_val(newWriteBlockSize)
            ->clear();
    }
References net::config::ConfigConnection::writeBlockSizeOpt.
setWriteTimeout()
void net::config::ConfigConnection::setWriteTimeout (const utils::Timeval & newWriteTimeoutSet) inherited
Definition at line 81 of file ConfigConnection.cpp.
{
        writeTimeoutOpt //
            ->default_val(newWriteTimeoutSet)
            ->clear();
    }
References net::config::ConfigConnection::writeTimeoutOpt.
Member Data Documentation
acceptsPerTickOpt
CLI::Option* net::config::ConfigListen::acceptsPerTickOpt = nullptr private inherited
Definition at line 50 of file ConfigListen.h.
Referenced by net::config::ConfigListen::getAcceptsPerTick(), and net::config::ConfigListen::setAcceptsPerTick().
acceptTimeoutOpt
CLI::Option* net::config::ConfigPhysicalSocketServer::acceptTimeoutOpt = nullptr private inherited
Definition at line 56 of file ConfigPhysicalSocketServer.h.
Referenced by net::config::ConfigPhysicalSocketServer::getAcceptTimeout(), and net::config::ConfigPhysicalSocketServer::setAcceptTimeout().
backlogOpt
CLI::Option* net::config::ConfigListen::backlogOpt = nullptr private inherited
Definition at line 49 of file ConfigListen.h.
Referenced by net::config::ConfigListen::getBacklog(), and net::config::ConfigListen::setBacklog().
instance
ConfigInstance* net::config::ConfigSection::instance = nullptr private inherited
Definition at line 120 of file ConfigSection.h.
Referenced by net::config::ConfigSection::ConfigSection(), and net::config::ConfigSection::required().
readBlockSizeOpt
CLI::Option* net::config::ConfigConnection::readBlockSizeOpt = nullptr private inherited
Definition at line 62 of file ConfigConnection.h.
Referenced by net::config::ConfigConnection::getReadBlockSize(), and net::config::ConfigConnection::setReadBlockSize().
readTimeoutOpt
CLI::Option* net::config::ConfigConnection::readTimeoutOpt = nullptr private inherited
Definition at line 60 of file ConfigConnection.h.
Referenced by net::config::ConfigConnection::getReadTimeout(), and net::config::ConfigConnection::setReadTimeout().
reconnectOpt
CLI::Option* net::config::ConfigPhysicalSocket::reconnectOpt = nullptr protected inherited
Definition at line 100 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getReconnect(), and net::config::ConfigPhysicalSocket::setReconnect().
reconnectTimeOpt
CLI::Option* net::config::ConfigPhysicalSocket::reconnectTimeOpt = nullptr protected inherited
Definition at line 101 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getReconnectTime(), and net::config::ConfigPhysicalSocket::setReconnectTime().
requiredCount
uint8_t net::config::ConfigSection::requiredCount = 0 private inherited
Definition at line 122 of file ConfigSection.h.
Referenced by net::config::ConfigSection::required(), and net::config::ConfigSection::required().
retryBaseOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryBaseOpt = nullptr protected inherited
Definition at line 97 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetryBase(), and net::config::ConfigPhysicalSocket::setRetryBase().
retryJitterOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryJitterOpt = nullptr protected inherited
Definition at line 99 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetryJitter(), and net::config::ConfigPhysicalSocket::setRetryJitter().
retryLimitOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryLimitOpt = nullptr protected inherited
Definition at line 98 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetryLimit(), and net::config::ConfigPhysicalSocket::setRetryLimit().
retryOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryOpt = nullptr protected inherited
Definition at line 94 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetry(), and net::config::ConfigPhysicalSocket::setRetry().
retryTimeoutOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryTimeoutOpt = nullptr protected inherited
Definition at line 96 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetryTimeout(), and net::config::ConfigPhysicalSocket::setRetryTimeout().
retryTriesOpt
CLI::Option* net::config::ConfigPhysicalSocket::retryTriesOpt = nullptr protected inherited
Definition at line 95 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), net::config::ConfigPhysicalSocket::getRetryTries(), and net::config::ConfigPhysicalSocket::setRetryTries().
reuseAddressOpt
CLI::Option* net::config::ConfigPhysicalSocket::reuseAddressOpt = nullptr protected inherited
Definition at line 93 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::getReuseAddress(), and net::config::ConfigPhysicalSocket::setReuseAddress().
section [1/3]
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 125 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
section [2/3]
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 125 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
section [3/3]
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 125 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
socketOptionsMap
std::map<int, const net::phy::PhysicalSocketOption> net::config::ConfigPhysicalSocket::socketOptionsMap protected inherited
Definition at line 103 of file ConfigPhysicalSocket.h.
Referenced by net::config::ConfigPhysicalSocket::add_socket_option(), net::config::ConfigPhysicalSocket::addSocketOption(), net::config::ConfigPhysicalSocket::addSocketOption(), net::config::ConfigPhysicalSocket::addSocketOption(), net::config::ConfigPhysicalSocket::getSocketOptions(), and net::config::ConfigPhysicalSocket::removeSocketOption().
terminateTimeoutOpt
CLI::Option* net::config::ConfigConnection::terminateTimeoutOpt = nullptr private inherited
Definition at line 64 of file ConfigConnection.h.
Referenced by net::config::ConfigConnection::getTerminateTimeout(), and net::config::ConfigConnection::setTerminateTimeout().
writeBlockSizeOpt
CLI::Option* net::config::ConfigConnection::writeBlockSizeOpt = nullptr private inherited
Definition at line 63 of file ConfigConnection.h.
Referenced by net::config::ConfigConnection::getWriteBlockSize(), and net::config::ConfigConnection::setWriteBlockSize().
writeTimeoutOpt
CLI::Option* net::config::ConfigConnection::writeTimeoutOpt = nullptr private inherited
Definition at line 61 of file ConfigConnection.h.
Referenced by net::config::ConfigConnection::getWriteTimeout(), and net::config::ConfigConnection::setWriteTimeout().
The documentation for this class was generated from the following files:
net/rc/stream/config/ConfigSocketServer.h
net/rc/stream/config/ConfigSocketServer.cpp