SNode.C: core::file::FileReader Class Reference
core::file::FileReader Class Reference
#include <FileReader.h>
Public Member Functions
bool isOpen () override
void start () final
void suspend () final
void resume () final
void stop () final
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
void pipe (Sink *sink, const std::function< void(int)> &callback)
void pipe (const std::shared_ptr< Sink > &sink, const std::function< void(int)> &callback)
int getFd () const
Static Public Member Functions
static FileReader * open (const std::string &path)
static void atNextTick (const std::function< void(void)> &callBack)
Protected Member Functions
ssize_t send (const char *chunk, std::size_t chunkLen)
void eof ()
void error (int errnum)
Protected Attributes
int openErrno = 0
bool running = false
Private Member Functions
FileReader (int fd, const std::string &name, std::size_t pufferSize, int openErrno)
void onEvent (const utils::Timeval &currentTime) override
void disconnect (const Sink *sink)
Private Attributes
std::size_t pufferSize = 0
bool suspended = false
Event event
Sink * sink = nullptr
int fd = -1
Detailed Description
Definition at line 40 of file FileReader.h.
Constructor & Destructor Documentation
FileReader()
core::file::FileReader::FileReader (int fd, const std::string & name, std::size_t pufferSize, int openErrno) private
Definition at line 37 of file FileReader.cpp.
        : core::Descriptor(fd)
        , EventReceiver(name)
        , pufferSize(pufferSize)
        , openErrno(openErrno) {
    }
References core::Descriptor::Descriptor(), core::EventReceiver::EventReceiver(), openErrno, and pufferSize.
Referenced by open().
Member Function Documentation
atNextTick()
void core::EventReceiver::atNextTick (const std::function< void(void)> & callBack) static inherited
Definition at line 28 of file EventReceiver.cpp.
{
        class NextTickEvent : public core::EventReceiver {
        public:
            explicit NextTickEvent(const std::function<void(void)>& callBack)
                : core::EventReceiver("RequestEvent")
                , callBack(callBack) {
            }
            void onEvent([[maybe_unused]] const utils::Timeval& currentTime) override {
                callBack();
                delete this;
            }
        private:
            std::function<void(void)> callBack;
        };
        (new NextTickEvent(callBack))->span();
    }
References core::EventReceiver::EventReceiver(), and core::EventReceiver::span().
Referenced by web::http::client::SocketContext::initiateRequest(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestDelivered(), web::http::client::SocketContext::responseDelivered(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), and core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector().
destruct()
void core::EventReceiver::destruct () virtual inherited
Reimplemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, and database::mariadb::MariaDBCommandStartEvent.
Definition at line 53 of file EventReceiver.cpp.
{
        delete this;
    }
Referenced by core::EventMultiplexer::EventQueue::clear().
disconnect()
void core::pipe::Source::disconnect (const Sink * sink) private inherited
Definition at line 59 of file Source.cpp.
{
        if (sink == this->sink) {
            this->sink->disconnect(this);
            this->sink = nullptr;
            stop();
        }
    }
References core::pipe::Sink::disconnect(), core::pipe::Source::sink, and core::pipe::Source::stop().
Referenced by core::pipe::Sink::stop(), and core::pipe::Sink::~Sink().
eof()
void core::pipe::Source::eof () protected inherited
Definition at line 81 of file Source.cpp.
                     {
        if (sink != nullptr) {
            sink->streamEof();
        }
    }
References core::pipe::Source::sink, and core::pipe::Sink::streamEof().
Referenced by onEvent().
error()
void core::pipe::Source::error (int errnum) protected inherited
Definition at line 87 of file Source.cpp.
{
        if (sink != nullptr) {
            sink->streamError(errnum);
        }
    }
References core::pipe::Source::sink, and core::pipe::Sink::streamError().
Referenced by onEvent().
getFd()
int core::Descriptor::getFd () const inherited
Definition at line 59 of file Descriptor.cpp.
{
        return fd;
    }
References core::Descriptor::fd.
Referenced by net::phy::PhysicalSocket< SocketAddressT >::bind(), net::phy::PhysicalSocket< SocketAddressT >::getPeerName(), net::phy::PhysicalSocket< SocketAddressT >::getSockName(), net::phy::PhysicalSocket< SocketAddressT >::getSockopt(), isOpen(), net::phy::PhysicalSocket< SocketAddressT >::isValid(), onEvent(), net::un::dgram::Socket::recvFd(), net::un::dgram::Socket::sendFd(), net::phy::PhysicalSocket< SocketAddressT >::setSockopt(), and net::phy::stream::PhysicalSocket< SocketAddressT >::shutdown().
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 65 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::socket::stream::tls::SocketReader::read(), core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter::sendToPeer(), core::socket::stream::SocketWriter::shutdownWrite(), core::socket::stream::SocketWriter::streamEof(), core::socket::stream::SocketWriter::streamToPeer(), core::DescriptorEventReceiver::suspend(), and core::socket::stream::tls::SocketWriter::write().
isOpen()
bool core::file::FileReader::isOpen () override virtual
Implements core::pipe::Source.
Definition at line 52 of file FileReader.cpp.
{
        return getFd() >= 0;
    }
References core::Descriptor::getFd().
onEvent()
void core::file::FileReader::onEvent (const utils::Timeval & currentTime) override private virtual
Implements core::EventReceiver.
Definition at line 56 of file FileReader.cpp.
{
        if (running && core::eventLoopState() != core::State::STOPPING) {
            if (!suspended) {
                std::vector<char> puffer(pufferSize);
                const ssize_t ret = core::system::read(getFd(), puffer.data(), puffer.capacity());
                if (ret > 0) {
                    if (this->send(puffer.data(), static_cast<std::size_t>(ret)) < 0) {
                        this->error(errno);
                    }
                    span();
                } else {
                    if (ret == 0) {
                        this->eof();
                        delete this;
                    } else {
                        this->error(errno);
                        delete this;
                    }
                }
            }
        } else {
            this->eof();
            delete this;
        }
    }
References core::pipe::Source::eof(), core::pipe::Source::error(), core::eventLoopState(), core::Descriptor::getFd(), pufferSize, core::system::read(), running, core::pipe::Source::send(), core::EventReceiver::span(), core::STOPPING, and suspended.
open()
FileReader * core::file::FileReader::open (const std::string & path) static
Definition at line 44 of file FileReader.cpp.
{
        errno = 0;
        const int fd = core::system::open(path.c_str(), O_RDONLY);
        return new FileReader(fd, "FileReader: " + path, MF_READSIZE, fd < 0 ? errno : 0);
    }
References FileReader(), MF_READSIZE, and core::system::open().
Referenced by web::http::client::Request::executeSendFile(), and web::http::server::Response::sendFile().
pipe() [1/2]
void core::pipe::Source::pipe (const std::shared_ptr< Sink > & sink, const std::function< void(int)> & callback) inherited
Definition at line 55 of file Source.cpp.
{
        pipe(sink.get(), callback);
    }
References core::pipe::Source::pipe().
pipe() [2/2]
void core::pipe::Source::pipe (Sink * sink, const std::function< void(int)> & callback) inherited
Definition at line 38 of file Source.cpp.
{
        if (sink != nullptr) {
            if (isOpen()) {
                callback(0);
                this->sink = sink;
                sink->pipe(this);
            } else {
                callback(errno);
                stop();
            }
        } else {
            callback(EINVAL);
            stop();
        }
    }
References core::pipe::Source::isOpen(), core::pipe::Sink::pipe(), core::pipe::Source::sink, and core::pipe::Source::stop().
Referenced by web::http::client::Request::executeSendFile(), core::pipe::Source::pipe(), and web::http::server::Response::sendFile().
relax()
void core::EventReceiver::relax () inherited
Definition at line 61 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
resume()
void core::file::FileReader::resume () final virtual
Implements core::pipe::Source.
Definition at line 92 of file FileReader.cpp.
{
        suspended = false;
        span();
    }
References core::EventReceiver::span(), and suspended.
send()
ssize_t core::pipe::Source::send (const char * chunk, std::size_t chunkLen) protected inherited
Definition at line 68 of file Source.cpp.
{
        ssize_t ret = static_cast<ssize_t>(chunkLen);
        if (sink != nullptr) {
            sink->streamData(chunk, chunkLen);
        } else {
            ret = -1;
            errno = EPIPE;
        }
        return ret;
    }
References core::pipe::Source::sink, and core::pipe::Sink::streamData().
Referenced by onEvent().
span()
void core::EventReceiver::span () inherited
Definition at line 57 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by core::EventReceiver::atNextTick(), database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), database::mariadb::MariaDBConnection::execute_async(), onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), resume(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), start(), stop(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
start()
void core::file::FileReader::start () final virtual
Implements core::pipe::Source.
Definition at line 83 of file FileReader.cpp.
{
        running = true;
        span();
    }
References running, and core::EventReceiver::span().
stop()
void core::file::FileReader::stop () final virtual
Implements core::pipe::Source.
Definition at line 97 of file FileReader.cpp.
{
        running = false;
        span();
    }
References running, and core::EventReceiver::span().
suspend()
void core::file::FileReader::suspend () final virtual
Implements core::pipe::Source.
Definition at line 88 of file FileReader.cpp.
{
        suspended = true;
    }
References suspended.
Member Data Documentation
event
Event core::EventReceiver::event private inherited
Definition at line 65 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
fd
int core::Descriptor::fd = -1 private inherited
Definition at line 48 of file Descriptor.h.
Referenced by core::Descriptor::Descriptor(), core::Descriptor::Descriptor(), core::Descriptor::getFd(), core::Descriptor::operator=(), core::Descriptor::operator=(), and core::Descriptor::~Descriptor().
openErrno
int core::file::FileReader::openErrno = 0 protected
Definition at line 65 of file FileReader.h.
Referenced by FileReader().
pufferSize
std::size_t core::file::FileReader::pufferSize = 0 private
Definition at line 60 of file FileReader.h.
Referenced by FileReader(), and onEvent().
running
bool core::file::FileReader::running = false protected
Definition at line 66 of file FileReader.h.
Referenced by onEvent(), start(), and stop().
sink
Sink* core::pipe::Source::sink = nullptr private inherited
Definition at line 68 of file Source.h.
Referenced by core::pipe::Source::disconnect(), core::pipe::Source::eof(), core::pipe::Source::error(), core::pipe::Source::pipe(), core::pipe::Source::send(), and core::pipe::Source::~Source().
suspended
bool core::file::FileReader::suspended = false private
Definition at line 62 of file FileReader.h.
Referenced by onEvent(), resume(), and suspend().
The documentation for this class was generated from the following files:
core/file/FileReader.h
core/file/FileReader.cpp