SNode.C: express::Route Class Reference
express::Route Class Reference
#include <Route.h>
Public Member Functions
Route (const std::string &method, const std::string &relativeMountPath, const std::shared_ptr< Dispatcher > &dispatcher)
Route & use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Route & head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda) const
Route & head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda) const
template<typename... Lambdas>
Route & head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> &lambda, Lambdas... lambdas) const
template<typename... Lambdas>
Route & head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> &lambda, Lambdas... lambdas) const
Protected Member Functions
Route ()
bool dispatch (Controller &controller)
bool dispatch (Controller &controller, const std::string &parentMountPath)
bool dispatchNext (Controller &controller, const std::string &parentMountPath)
Private Attributes
MountPoint mountPoint
std::shared_ptr< Dispatcher > dispatcher
Friends
class dispatcher::RouterDispatcher
class Dispatcher
class RootRoute
class Controller
Detailed Description
Definition at line 60 of file Route.h.
Constructor & Destructor Documentation
Route() [1/2]
express::Route::Route (const std::string & method, const std::string & relativeMountPath, const std::shared_ptr< Dispatcher > & dispatcher)
Definition at line 54 of file Route.cpp.
        : mountPoint(method, relativeMountPath)
        , dispatcher(dispatcher) {
    }
References dispatcher, express::MountPoint::MountPoint(), and mountPoint.
Route() [2/2]
express::Route::Route () protected
Definition at line 49 of file Route.cpp.
        : mountPoint("use", "")
        , dispatcher(std::make_shared<dispatcher::RouterDispatcher>()) {
    }
References dispatcher, express::MountPoint::MountPoint(), and mountPoint.
Member Function Documentation
all() [1/4]
Route & express::Route::all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 80 of file Route.cpp.
all() [2/4]
template<typename... Lambdas> Route & express::Route::all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const
Definition at line 55 of file Route.hpp.
all() [3/4]
Route & express::Route::all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 80 of file Route.cpp.
all() [4/4]
template<typename... Lambdas> Route & express::Route::all (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const
Definition at line 55 of file Route.hpp.
connect() [1/4]
Route & express::Route::connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 85 of file Route.cpp.
connect() [2/4]
template<typename... Lambdas> Route & express::Route::connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const
Definition at line 60 of file Route.hpp.
connect() [3/4]
Route & express::Route::connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 85 of file Route.cpp.
connect() [4/4]
template<typename... Lambdas> Route & express::Route::connect (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const
Definition at line 60 of file Route.hpp.
del() [1/4]
Route & express::Route::del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 84 of file Route.cpp.
del() [2/4]
template<typename... Lambdas> Route & express::Route::del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const
Definition at line 59 of file Route.hpp.
del() [3/4]
Route & express::Route::del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 84 of file Route.cpp.
del() [4/4]
template<typename... Lambdas> Route & express::Route::del (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const
Definition at line 59 of file Route.hpp.
dispatch() [1/2]
bool express::Route::dispatch (Controller & controller) protected
Definition at line 59 of file Route.cpp.
{
        return dispatch(controller, "");
    }
References dispatch().
dispatch() [2/2]
bool express::Route::dispatch (Controller & controller, const std::string & parentMountPath) protected
Definition at line 63 of file Route.cpp.
{
        controller.setCurrentRoute(this);
        bool dispatched = dispatcher->dispatch(controller, parentMountPath, mountPoint);
        if (!dispatched) { // TODO: only call if parent route matched
            dispatched = controller.dispatchNext(parentMountPath);
        }
        return dispatched;
    }
References express::Dispatcher::dispatch(), dispatcher, express::Controller::dispatchNext(), mountPoint, and express::Controller::setCurrentRoute().
Referenced by express::RootRoute::dispatch(), dispatch(), express::dispatcher::RouterDispatcher::dispatch(), and express::Dispatcher::dispatchNext().
dispatchNext()
bool express::Route::dispatchNext (Controller & controller, const std::string & parentMountPath) protected
Definition at line 75 of file Route.cpp.
{
        return dispatcher->dispatchNext(controller, parentMountPath);
    }
References dispatcher, and express::Dispatcher::dispatchNext().
Referenced by express::Controller::dispatchNext().
get() [1/4]
Route & express::Route::get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 81 of file Route.cpp.
get() [2/4]
template<typename... Lambdas> Route & express::Route::get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const
Definition at line 56 of file Route.hpp.
get() [3/4]
Route & express::Route::get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 81 of file Route.cpp.
get() [4/4]
template<typename... Lambdas> Route & express::Route::get (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const
Definition at line 56 of file Route.hpp.
head() [1/4]
Route & express::Route::head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 89 of file Route.cpp.
head() [2/4]
template<typename... Lambdas> Route & express::Route::head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const
Definition at line 64 of file Route.hpp.
head() [3/4]
Route & express::Route::head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 89 of file Route.cpp.
head() [4/4]
template<typename... Lambdas> Route & express::Route::head (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const
Definition at line 64 of file Route.hpp.
options() [1/4]
Route & express::Route::options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 86 of file Route.cpp.
options() [2/4]
template<typename... Lambdas> Route & express::Route::options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const
Definition at line 61 of file Route.hpp.
options() [3/4]
Route & express::Route::options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 86 of file Route.cpp.
options() [4/4]
template<typename... Lambdas> Route & express::Route::options (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const
Definition at line 61 of file Route.hpp.
patch() [1/4]
Route & express::Route::patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 88 of file Route.cpp.
patch() [2/4]
template<typename... Lambdas> Route & express::Route::patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const
Definition at line 63 of file Route.hpp.
patch() [3/4]
Route & express::Route::patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 88 of file Route.cpp.
patch() [4/4]
template<typename... Lambdas> Route & express::Route::patch (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const
Definition at line 63 of file Route.hpp.
post() [1/4]
Route & express::Route::post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 83 of file Route.cpp.
post() [2/4]
template<typename... Lambdas> Route & express::Route::post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const
Definition at line 58 of file Route.hpp.
post() [3/4]
Route & express::Route::post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 83 of file Route.cpp.
post() [4/4]
template<typename... Lambdas> Route & express::Route::post (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const
Definition at line 58 of file Route.hpp.
put() [1/4]
Route & express::Route::put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 82 of file Route.cpp.
put() [2/4]
template<typename... Lambdas> Route & express::Route::put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const
Definition at line 57 of file Route.hpp.
put() [3/4]
Route & express::Route::put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 82 of file Route.cpp.
put() [4/4]
template<typename... Lambdas> Route & express::Route::put (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const
Definition at line 57 of file Route.hpp.
trace() [1/4]
Route & express::Route::trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 87 of file Route.cpp.
trace() [2/4]
template<typename... Lambdas> Route & express::Route::trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const
Definition at line 62 of file Route.hpp.
trace() [3/4]
Route & express::Route::trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 87 of file Route.cpp.
trace() [4/4]
template<typename... Lambdas> Route & express::Route::trace (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const
Definition at line 62 of file Route.hpp.
use() [1/4]
Route & express::Route::use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda) const
Definition at line 79 of file Route.cpp.
use() [2/4]
template<typename... Lambdas> Route & express::Route::use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res)> & lambda, Lambdas... lambdas) const
Definition at line 54 of file Route.hpp.
use() [3/4]
Route & express::Route::use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda) const
Definition at line 79 of file Route.cpp.
use() [4/4]
template<typename... Lambdas> Route & express::Route::use (const std::function< void(const std::shared_ptr< Request > &req, const std::shared_ptr< Response > &res, Next &next)> & lambda, Lambdas... lambdas) const
Definition at line 54 of file Route.hpp.
Friends And Related Symbol Documentation
Controller
friend class Controller friend
Definition at line 91 of file Route.h.
Dispatcher
friend class Dispatcher friend
Definition at line 89 of file Route.h.
dispatcher::RouterDispatcher
friend class dispatcher::RouterDispatcher friend
Definition at line 88 of file Route.h.
RootRoute
friend class RootRoute friend
Definition at line 90 of file Route.h.
Member Data Documentation
dispatcher
std::shared_ptr<Dispatcher> express::Route::dispatcher private
Definition at line 73 of file Route.h.
Referenced by dispatch(), dispatchNext(), express::RootRoute::getDispatcher(), Route(), Route(), and express::RootRoute::routes().
mountPoint
MountPoint express::Route::mountPoint private
Definition at line 72 of file Route.h.
Referenced by dispatch(), Route(), and Route().
The documentation for this class was generated from the following files:
express/Route.h
express/Route.hpp
express/Route.cpp