snode.c: net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT > Class Template Reference
net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT > Class Template Reference
#include <SocketClient.h>
Public Member Functions
void connect (const std::string &ipOrHostname, uint16_t port, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus)
void connect (const std::string &ipOrHostname, uint16_t port, const std::string &bindHost, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus)
void connect (const std::string &ipOrHostname, uint16_t port, uint16_t bindPort, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus)
void connect (const std::string &ipOrHostname, uint16_t port, const std::string &bindHost, uint16_t bindPort, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus)
Public Member Functions inherited from core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT >
SocketClient (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect)
SocketClient (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect)
SocketClient (const std::string &name)
SocketClient ()
SocketClient (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, SocketContextFactory *socketContextFactory)
SocketClient (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, SocketContextFactory *socketContextFactory)
SocketClient (const std::string &name, SocketContextFactory *socketContextFactory)
SocketClient (SocketContextFactory *socketContextFactory)
void connect (const std::function< void(const SocketAddress &, core::socket::State)> &onStatus)
void connect (const SocketAddress &remoteAddress, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus)
void connect (const SocketAddress &remoteAddress, const SocketAddress &localAddress, const std::function< void(const SocketAddress &, core::socket::State)> &onStatus)
std::function< void(SocketConnection *)> setOnConnect (const std::function< void(SocketConnection *)> &onConnect)
std::function< void(SocketConnection *)> setOnConnected (const std::function< void(SocketConnection *)> &onConnected)
std::function< void(SocketConnection *)> setOnDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
Public Member Functions inherited from core::socket::Socket< SocketConnectorT::Config >
Socket (const std::string &name)
Socket (const Socket &)=default
Socket (Socket &&)=default
Socket & operator= (const Socket &)=default
Socket & operator= (Socket &&)=default
virtual ~Socket ()
Config & getConfig () const
Private Types
using Super = core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT >
Additional Inherited Members
Public Types inherited from core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT >
using SocketConnection = typename SocketConnector::SocketConnection
using SocketAddress = typename SocketConnector::SocketAddress
Public Types inherited from core::socket::Socket< SocketConnectorT::Config >
using Config = SocketConnectorT::Config
Protected Attributes inherited from core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT >
std::function< void(SocketConnection *)> onConnect
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
Protected Attributes inherited from core::socket::Socket< SocketConnectorT::Config >
std::shared_ptr< Config > config
Detailed Description
template<template< typename PhysicalSocketClient, typename ConfigSocketClientT > typename SocketConnectorT, typename ConfigSocketClientT, typename SocketContextFactoryT>
class net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >
Definition at line 38 of file SocketClient.h.
Member Typedef Documentation
Super
template<template< typename PhysicalSocketClient, typename ConfigSocketClientT > typename SocketConnectorT, typename ConfigSocketClientT , typename SocketContextFactoryT > using net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::Super = core::socket::stream::SocketClient<SocketConnectorT<net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT>, SocketContextFactoryT> private
Definition at line 42 of file SocketClient.h.
Member Function Documentation
connect() [1/4]
template<template< typename PhysicalSocketClient, typename ConfigSocketClientT > typename SocketConnectorT, typename ConfigSocketClientT , typename SocketContextFactoryT > void net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect (const std::string & ipOrHostname, uint16_t port, const std::function< void(const SocketAddress &, core::socket::State)> & onStatus) inline
Definition at line 50 of file SocketClient.h.
{
            Super::getConfig().Remote::setHost(ipOrHostname).setPort(port);
            connect(onStatus);
        }
References net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), and core::socket::Socket< SocketConnectorT::Config >::getConfig().
Referenced by net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), and net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect().
connect() [2/4]
template<template< typename PhysicalSocketClient, typename ConfigSocketClientT > typename SocketConnectorT, typename ConfigSocketClientT , typename SocketContextFactoryT > void net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect (const std::string & ipOrHostname, uint16_t port, const std::string & bindHost, const std::function< void(const SocketAddress &, core::socket::State)> & onStatus) inline
Definition at line 58 of file SocketClient.h.
{
            Super::getConfig().Remote::setHost(ipOrHostname).setPort(port);
            Super::getConfig().Local::setHost(bindHost);
            connect(onStatus);
        }
References net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), and core::socket::Socket< SocketConnectorT::Config >::getConfig().
connect() [3/4]
template<template< typename PhysicalSocketClient, typename ConfigSocketClientT > typename SocketConnectorT, typename ConfigSocketClientT , typename SocketContextFactoryT > void net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect (const std::string & ipOrHostname, uint16_t port, const std::string & bindHost, uint16_t bindPort, const std::function< void(const SocketAddress &, core::socket::State)> & onStatus) inline
Definition at line 78 of file SocketClient.h.
{
            Super::getConfig().Remote::setHost(ipOrHostname).setPort(port);
            Super::getConfig().Local::setHost(bindHost).setPort(bindPort);
            connect(onStatus);
        }
References net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), and core::socket::Socket< SocketConnectorT::Config >::getConfig().
connect() [4/4]
template<template< typename PhysicalSocketClient, typename ConfigSocketClientT > typename SocketConnectorT, typename ConfigSocketClientT , typename SocketContextFactoryT > void net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect (const std::string & ipOrHostname, uint16_t port, uint16_t bindPort, const std::function< void(const SocketAddress &, core::socket::State)> & onStatus) inline
Definition at line 68 of file SocketClient.h.
{
            Super::getConfig().Remote::setHost(ipOrHostname).setPort(port);
            Super::getConfig().Local::setPort(bindPort);
            connect(onStatus);
        }
References net::in6::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), and core::socket::Socket< SocketConnectorT::Config >::getConfig().
The documentation for this class was generated from the following file:
net/in6/stream/SocketClient.h