SNode.C: core::socket::stream::SocketReader Class Reference
core::socket::stream::SocketReader Class Reference abstract
#include <SocketReader.h>
Public Member Functions
SocketReader ()=delete
Public Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
int getRegisteredFd () const
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Member Functions
SocketReader (const std::string &instanceName, const std::function< void(int)> &onStatus, const utils::Timeval &timeout, std::size_t blockSize, const utils::Timeval &terminateTimeout)
virtual ssize_t read (char *chunk, std::size_t chunkLen)
void setBlockSize (std::size_t readBlockSize)
std::size_t readFromPeer (char *chunk, std::size_t chunkLen)
void shutdownRead ()
Protected Member Functions inherited from core::eventreceiver::ReadEventReceiver
ReadEventReceiver (const std::string &name, const utils::Timeval &timeout)
virtual void readTimeout ()
Protected Member Functions inherited from core::DescriptorEventReceiver
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
Protected Member Functions inherited from core::Observer
void observed ()
void unObserved ()
virtual void unobservedEvent ()=0
Observer ()=default
Observer (Observer &)=delete
Observer (Observer &&)=delete
virtual ~Observer ()
Protected Member Functions inherited from core::EventReceiver
virtual ~EventReceiver ()=default
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Attributes
utils::Timeval terminateTimeout
Private Member Functions
virtual void onReceivedFromPeer (std::size_t available)=0
void readEvent () final
std::size_t doRead ()
void signalEvent (int sigNum) final
Private Attributes
std::function< void(int)> onStatus
std::vector< char > readBuffer
std::size_t blockSize = 0
std::size_t size = 0
std::size_t cursor = 0
bool shutdownInProgress = false
Additional Inherited Members
Static Public Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Static Protected Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Detailed Description
Definition at line 61 of file SocketReader.h.
Constructor & Destructor Documentation
SocketReader() [1/2]
core::socket::stream::SocketReader::SocketReader () delete
SocketReader() [2/2]
core::socket::stream::SocketReader::SocketReader (const std::string & instanceName, const std::function< void(int)> & onStatus, const utils::Timeval & timeout, std::size_t blockSize, const utils::Timeval & terminateTimeout) explicit protected
Definition at line 55 of file SocketReader.cpp.
        : core::eventreceiver::ReadEventReceiver(instanceName, timeout)
        , onStatus(onStatus)
        , terminateTimeout(terminateTimeout) {
        setBlockSize(blockSize);
    }
References core::eventreceiver::ReadEventReceiver::ReadEventReceiver(), setBlockSize(), SocketReader(), terminateTimeout, and utils::Timeval::Timeval().
Referenced by SocketReader().
Member Function Documentation
doRead()
std::size_t core::socket::stream::SocketReader::doRead () private
Definition at line 81 of file SocketReader.cpp.
{
        errno = 0;
        if (size == 0) {
            cursor = 0;
            ssize_t retRead = 0;
            if (!shutdownInProgress) {
                const std::size_t readLen = blockSize - size;
                retRead = read(readBuffer.data() + size, readLen);
            }
            if (retRead > 0) {
                size += static_cast<std::size_t>(retRead);
                if (!isSuspended()) {
                    suspend();
                }
                span();
            } else if (errno == EAGAIN || errno == EWOULDBLOCK || errno == EINTR) {
                if (isSuspended()) {
                    resume();
                }
            } else {
                onStatus(errno);
            }
        } else {
            span();
        }
        return size;
    }
References blockSize, cursor, core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), shutdownInProgress, size, core::EventReceiver::span(), and core::DescriptorEventReceiver::suspend().
Referenced by readEvent().
onReceivedFromPeer()
virtual void core::socket::stream::SocketReader::onReceivedFromPeer (std::size_t available) private pure virtual
Referenced by readEvent().
read()
ssize_t core::socket::stream::SocketReader::read (char * chunk, std::size_t chunkLen) protected virtual
Reimplemented in core::socket::stream::tls::SocketReader.
Definition at line 77 of file SocketReader.cpp.
{
        return core::system::recv(this->getRegisteredFd(), chunk, chunkLen, 0);
    }
References core::DescriptorEventReceiver::getRegisteredFd(), and core::system::recv().
readEvent()
void core::socket::stream::SocketReader::readEvent () final private virtual
Implements core::eventreceiver::ReadEventReceiver.
Definition at line 66 of file SocketReader.cpp.
{
        const std::size_t available = doRead();
        if (available > 0) {
            onReceivedFromPeer(available);
        }
    }
References doRead(), and onReceivedFromPeer().
readFromPeer()
std::size_t core::socket::stream::SocketReader::readFromPeer (char * chunk, std::size_t chunkLen) protected
Definition at line 118 of file SocketReader.cpp.
{
        const std::size_t maxReturn = std::min(chunkLen, size);
        std::copy(readBuffer.data() + cursor, readBuffer.data() + cursor + maxReturn, chunk);
        cursor += maxReturn;
        size -= maxReturn;
        return maxReturn;
    }
References cursor, and size.
setBlockSize()
void core::socket::stream::SocketReader::setBlockSize (std::size_t readBlockSize) protected
Definition at line 113 of file SocketReader.cpp.
{
        readBuffer.resize(readBlockSize);
        blockSize = readBlockSize;
    }
References blockSize.
Referenced by SocketReader().
shutdownRead()
void core::socket::stream::SocketReader::shutdownRead () protected
Definition at line 129 of file SocketReader.cpp.
{
        readBuffer.clear();
        size = 0;
        cursor = 0;
        shutdownInProgress = true;
        setTimeout(terminateTimeout);
    }
References cursor, core::DescriptorEventReceiver::setTimeout(), shutdownInProgress, size, and terminateTimeout.
signalEvent()
void core::socket::stream::SocketReader::signalEvent (int sigNum) final private virtual
Reimplemented from core::eventreceiver::ReadEventReceiver.
Definition at line 74 of file SocketReader.cpp.
                                                              { // Do nothing in case a signal was received
    }
Member Data Documentation
blockSize
std::size_t core::socket::stream::SocketReader::blockSize = 0 private
Definition at line 93 of file SocketReader.h.
Referenced by doRead(), and setBlockSize().
cursor
std::size_t core::socket::stream::SocketReader::cursor = 0 private
Definition at line 96 of file SocketReader.h.
Referenced by doRead(), readFromPeer(), and shutdownRead().
onStatus
std::function<void(int)> core::socket::stream::SocketReader::onStatus private
Definition at line 90 of file SocketReader.h.
readBuffer
std::vector<char> core::socket::stream::SocketReader::readBuffer private
Definition at line 92 of file SocketReader.h.
shutdownInProgress
bool core::socket::stream::SocketReader::shutdownInProgress = false private
Definition at line 98 of file SocketReader.h.
Referenced by doRead(), and shutdownRead().
size
std::size_t core::socket::stream::SocketReader::size = 0 private
Definition at line 95 of file SocketReader.h.
Referenced by doRead(), readFromPeer(), and shutdownRead().
terminateTimeout
utils::Timeval core::socket::stream::SocketReader::terminateTimeout protected
Definition at line 101 of file SocketReader.h.
Referenced by shutdownRead(), and SocketReader().
The documentation for this class was generated from the following files:
core/socket/stream/SocketReader.h
core/socket/stream/SocketReader.cpp