SNode.C: net::config::ConfigAddressRemote< SocketAddressT > Class Template Reference
net::config::ConfigAddressRemote< SocketAddressT > Class Template Reference abstract
#include <ConfigAddressRemote.h>
Public Member Functions
SocketAddress & getSocketAddress ()
void reset ()
Protected Member Functions
ConfigAddressRemote (ConfigInstance *instance)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
Protected Attributes
CLI::App * section = nullptr
Private Types
using Super = net::config::ConfigAddress< SocketAddressT >
using SocketAddress = SocketAddressT
Private Member Functions
virtual void setSocketAddress (const SocketAddress &address)=0
virtual SocketAddress * init ()=0
Private Attributes
SocketAddress * socketAddress = nullptr
ConfigInstance * instance = nullptr
uint8_t requiredCount = 0
Detailed Description
template<typename SocketAddressT>
class net::config::ConfigAddressRemote< SocketAddressT >
Definition at line 35 of file ConfigAddressRemote.h.
Member Typedef Documentation
SocketAddress
template<typename SocketAddressT > using net::config::ConfigAddress< SocketAddressT >::SocketAddress = SocketAddressT private inherited
Definition at line 40 of file ConfigAddress.h.
Super
template<typename SocketAddressT > using net::config::ConfigAddressRemote< SocketAddressT >::Super = net::config::ConfigAddress<SocketAddressT> private
Definition at line 36 of file ConfigAddressRemote.h.
Constructor & Destructor Documentation
ConfigAddressRemote()
template<typename SocketAddress > net::config::ConfigAddressRemote< SocketAddress >::ConfigAddressRemote (ConfigInstance * instance) explicit protected
Definition at line 31 of file ConfigAddressRemote.hpp.
        : Super::ConfigAddress(instance, "remote", "Remote side of connection for instance '" + instance->getInstanceName() + "'") {
    }
References net::config::ConfigAddressRemote< SocketAddressT >::ConfigAddressRemote(), and net::config::ConfigInstance::getInstanceName().
Referenced by net::config::ConfigAddressRemote< SocketAddressT >::ConfigAddressRemote().
Member Function Documentation
add_flag() [1/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 116 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_flag_function(name, utils::ResetToDefault(opt), description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References utils::ResetToDefault::ResetToDefault(), and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [2/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 129 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [3/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 63 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [4/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 70 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [5/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_flag() [6/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag_function() [1/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) protected inherited
Definition at line 138 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [2/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 157 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option().
add_option() [1/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) protected inherited
Definition at line 89 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_option_function<std::string>(name, utils::ResetToDefault(opt), description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References utils::ResetToDefault::ResetToDefault(), and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [2/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 101 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [3/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 106 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [4/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 45 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [5/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 52 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [6/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_option() [7/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
getSocketAddress()
template<typename SocketAddress > SocketAddress & net::config::ConfigAddress< SocketAddress >::getSocketAddress () inherited
Definition at line 48 of file ConfigAddress.hpp.
{
        if (socketAddress == nullptr) {
            socketAddress = init();
        }
        return *socketAddress;
    }
References net::config::ConfigAddress< SocketAddressT >::init(), and net::config::ConfigAddress< SocketAddressT >::socketAddress.
init()
template<typename SocketAddressT > virtual SocketAddress * net::config::ConfigAddress< SocketAddressT >::init () private pure virtual inherited
Referenced by net::config::ConfigAddress< SocketAddressT >::getSocketAddress().
required() [1/2]
bool net::config::ConfigSection::required () const protected inherited
Definition at line 85 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [2/2]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) protected inherited
Definition at line 61 of file ConfigSection.cpp.
{
        if (req && !opt->get_required()) {
            ++requiredCount;
            opt //
                ->default_str("")
                ->required()
                ->clear();
            section //
                ->needs(opt);
        } else if (opt->get_required()) {
            --requiredCount;
            opt //
                ->required(false)
                ->clear();
            section //
                ->remove_needs(opt);
        }
        section //
            ->required(requiredCount > 0);
        instance->required(section, req);
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
reset()
template<typename SocketAddress > void net::config::ConfigAddress< SocketAddress >::reset () inherited
Definition at line 57 of file ConfigAddress.hpp.
{
        socketAddress = nullptr;
    }
References net::config::ConfigAddress< SocketAddressT >::socketAddress.
setSocketAddress()
template<typename SocketAddressT > virtual void net::config::ConfigAddress< SocketAddressT >::setSocketAddress (const SocketAddress & address) private pure virtual inherited
Member Data Documentation
instance
ConfigInstance* net::config::ConfigSection::instance = nullptr private inherited
Definition at line 120 of file ConfigSection.h.
Referenced by net::config::ConfigSection::ConfigSection(), and net::config::ConfigSection::required().
requiredCount
uint8_t net::config::ConfigSection::requiredCount = 0 private inherited
Definition at line 122 of file ConfigSection.h.
Referenced by net::config::ConfigSection::required(), and net::config::ConfigSection::required().
section
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 125 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
socketAddress
template<typename SocketAddressT > SocketAddress* net::config::ConfigAddress< SocketAddressT >::socketAddress = nullptr private inherited
Definition at line 57 of file ConfigAddress.h.
Referenced by net::config::ConfigAddress< SocketAddressT >::getSocketAddress(), net::config::ConfigAddress< SocketAddressT >::reset(), and net::config::ConfigAddress< SocketAddressT >::~ConfigAddress().
The documentation for this class was generated from the following files:
net/config/ConfigAddressRemote.h
net/config/ConfigAddressRemote.hpp