SNode.C: web::http::client::SocketContextFactory< RequestT, ResponseT > Class Template Reference
web::http::client::SocketContextFactory< RequestT, ResponseT > Class Template Reference
#include <SocketContextFactory.h>
Public Types
using Request = RequestT
using Response = ResponseT
Public Member Functions
SocketContextFactory ()=default
~SocketContextFactory () override=default
SocketContextFactory (const SocketContextFactory &)=delete
SocketContextFactory & operator= (const SocketContextFactory &)=delete
void setOnRequestBegin (const std::function< void(Request &)> &onRequestBegin)
void setOnResponseReady (const std::function< void(Request &, Response &)> &onResponseReady)
void setOnResponseError (const std::function< void(int, const std::string &)> &onResponseError)
Public Member Functions inherited from web::http::SocketContextFactory< web::http::client::SocketContext, RequestT, ResponseT >
SocketContextFactory (const SocketContextFactory &)=delete
SocketContextFactory & operator= (const SocketContextFactory &)=delete
Private Member Functions
core::socket::stream::SocketContext * create (core::socket::stream::SocketConnection *socketConnection) override
Private Attributes
std::function< void(Request &)> onRequestBegin
std::function< void(Request &, Response &)> onResponseReady
std::function< void(int, const std::string &)> onResponseError
Additional Inherited Members
Protected Types inherited from web::http::SocketContextFactory< web::http::client::SocketContext, RequestT, ResponseT >
using Request = RequestT
using Response = ResponseT
using SocketContext = web::http::client::SocketContext< Request, Response >
Protected Member Functions inherited from web::http::SocketContextFactory< web::http::client::SocketContext, RequestT, ResponseT >
SocketContextFactory ()=default
~SocketContextFactory () override=default
Protected Member Functions inherited from core::socket::stream::SocketContextFactory
SocketContextFactory ()=default
Detailed Description
template<typename RequestT, typename ResponseT>
class web::http::client::SocketContextFactory< RequestT, ResponseT >
Definition at line 36 of file SocketContextFactory.h.
Member Typedef Documentation
Request
template<typename RequestT , typename ResponseT > using web::http::client::SocketContextFactory< RequestT, ResponseT >::Request = RequestT
Definition at line 38 of file SocketContextFactory.h.
Response
template<typename RequestT , typename ResponseT > using web::http::client::SocketContextFactory< RequestT, ResponseT >::Response = ResponseT
Definition at line 39 of file SocketContextFactory.h.
Constructor & Destructor Documentation
SocketContextFactory() [1/2]
template<typename RequestT , typename ResponseT > web::http::client::SocketContextFactory< RequestT, ResponseT >::SocketContextFactory () default
~SocketContextFactory()
template<typename RequestT , typename ResponseT > web::http::client::SocketContextFactory< RequestT, ResponseT >::~SocketContextFactory () override virtual default
Reimplemented from core::socket::stream::SocketContextFactory.
SocketContextFactory() [2/2]
template<typename RequestT , typename ResponseT > web::http::client::SocketContextFactory< RequestT, ResponseT >::SocketContextFactory (const SocketContextFactory< RequestT, ResponseT > &) delete
Member Function Documentation
create()
template<typename RequestT , typename ResponseT > core::socket::stream::SocketContext * web::http::client::SocketContextFactory< RequestT, ResponseT >::create (core::socket::stream::SocketConnection * socketConnection) inline override private virtual
Implements core::socket::stream::SocketContextFactory.
Definition at line 49 of file SocketContextFactory.h.
{
            return new web::http::client::SocketContext<Request, Response>(
                socketConnection, onRequestBegin, onResponseReady, onResponseError);
        }
References web::http::client::SocketContextFactory< RequestT, ResponseT >::onRequestBegin, web::http::client::SocketContextFactory< RequestT, ResponseT >::onResponseError, and web::http::client::SocketContextFactory< RequestT, ResponseT >::onResponseReady.
operator=()
template<typename RequestT , typename ResponseT > SocketContextFactory & web::http::client::SocketContextFactory< RequestT, ResponseT >::operator= (const SocketContextFactory< RequestT, ResponseT > &) delete
setOnRequestBegin()
template<typename RequestT , typename ResponseT > void web::http::client::SocketContextFactory< RequestT, ResponseT >::setOnRequestBegin (const std::function< void(Request &)> & onRequestBegin) inline
Definition at line 55 of file SocketContextFactory.h.
{
            this->onRequestBegin = onRequestBegin;
        }
setOnResponseError()
template<typename RequestT , typename ResponseT > void web::http::client::SocketContextFactory< RequestT, ResponseT >::setOnResponseError (const std::function< void(int, const std::string &)> & onResponseError) inline
Definition at line 63 of file SocketContextFactory.h.
{
            this->onResponseError = onResponseError;
        }
setOnResponseReady()
template<typename RequestT , typename ResponseT > void web::http::client::SocketContextFactory< RequestT, ResponseT >::setOnResponseReady (const std::function< void(Request &, Response &)> & onResponseReady) inline
Definition at line 59 of file SocketContextFactory.h.
{
            this->onResponseReady = onResponseReady;
        }
Member Data Documentation
onRequestBegin
template<typename RequestT , typename ResponseT > std::function<void(Request&)> web::http::client::SocketContextFactory< RequestT, ResponseT >::onRequestBegin private
Definition at line 68 of file SocketContextFactory.h.
Referenced by web::http::client::SocketContextFactory< RequestT, ResponseT >::create().
onResponseError
template<typename RequestT , typename ResponseT > std::function<void(int, const std::string&)> web::http::client::SocketContextFactory< RequestT, ResponseT >::onResponseError private
Definition at line 70 of file SocketContextFactory.h.
Referenced by web::http::client::SocketContextFactory< RequestT, ResponseT >::create().
onResponseReady
template<typename RequestT , typename ResponseT > std::function<void(Request&, Response&)> web::http::client::SocketContextFactory< RequestT, ResponseT >::onResponseReady private
Definition at line 69 of file SocketContextFactory.h.
Referenced by web::http::client::SocketContextFactory< RequestT, ResponseT >::create().
The documentation for this class was generated from the following file:
web/http/client/SocketContextFactory.h