SNode.C: net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT > Class Template Reference
net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT > Class Template Reference
#include <ConfigSocketClient.h>
Public Member Functions
ConfigSocketClient (const std::string &name)
std::string getInstanceName () const
bool getDisabled () const
void setDisabled (bool disabled=true)
CLI::App * add_section (const std::string &name, const std::string &description)
void required (CLI::App *section, bool req=true)
bool getRequired () const
std::string getSni () const
void setSni (const std::string &sni)
utils::Timeval getInitTimeout () const
void setInitTimeout (const utils::Timeval &newInitTimeout)
utils::Timeval getShutdownTimeout () const
void setShutdownTimeout (const utils::Timeval &newShutdownTimeout)
std::string getCertChain () const
void setCertChain (const std::string &newCertChain)
std::string getCertKey () const
void setCertKey (const std::string &newCertKey)
std::string getCertKeyPassword () const
void setCertKeyPassword (const std::string &newCertKeyPassword)
std::string getCaCertFile () const
void setCaCertFile (const std::string &newCaCertFile)
std::string getCaCertDir () const
void setCaCertDir (const std::string &newCaCertDir)
bool getUseDefaultCaCertDir () const
void setUseDefaultCaCertDir (bool set=true)
std::string getCipherList () const
void setCipherList (const std::string &newCipherList)
ssl_option_t getSslTlsOptions () const
void setSslTlsOptions (ssl_option_t newSslTlsOptions)
Protected Member Functions
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_option (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName)
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue)
template<typename ValueTypeT >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue)
template<typename ValueType >
CLI::Option * add_flag (CLI::Option *&opt, const std::string &name, const std::string &description, const std::string &typeName, ValueType defaultValue, const CLI::Validator &additionalValidator)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue)
CLI::Option * add_flag_function (CLI::Option *&opt, const std::string &name, const std::function< void(int64_t)> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
void required (CLI::Option *opt, bool req=true)
bool required () const
Protected Attributes
CLI::App * section = nullptr
Private Attributes
uint8_t requiredCount = 0
const std::string name
CLI::App * instanceSc = nullptr
CLI::Option * disableOpt = nullptr
CLI::Option * sniOpt = nullptr
CLI::Option * certChainOpt = nullptr
CLI::Option * certKeyOpt = nullptr
CLI::Option * certKeyPasswordOpt = nullptr
CLI::Option * caCertFileOpt = nullptr
CLI::Option * caCertDirOpt = nullptr
CLI::Option * useDefaultCaCertDirOpt = nullptr
CLI::Option * cipherListOpt = nullptr
CLI::Option * tlsOptionsOpt = nullptr
CLI::Option * initTimeoutOpt = nullptr
CLI::Option * shutdownTimeoutOpt = nullptr
ConfigInstance * instance = nullptr
Detailed Description
template<typename ConfigSocketClientBaseT>
class net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBaseT >
Definition at line 32 of file ConfigSocketClient.h.
Constructor & Destructor Documentation
ConfigSocketClient()
template<typename ConfigSocketClientBase > net::config::stream::tls::ConfigSocketClient< ConfigSocketClientBase >::ConfigSocketClient (const std::string & name) explicit
Definition at line 28 of file ConfigSocketClient.hpp.
        : net::config::ConfigInstance(name, "client")
        , ConfigSocketClientBase(this)
        , net::config::ConfigTlsClient(this) {
    }
Referenced by net::in::stream::tls::config::ConfigSocketClient::ConfigSocketClient(), net::in6::stream::tls::config::ConfigSocketClient::ConfigSocketClient(), net::l2::stream::tls::config::ConfigSocketClient::ConfigSocketClient(), net::rc::stream::tls::config::ConfigSocketClient::ConfigSocketClient(), and net::un::stream::tls::config::ConfigSocketClient::ConfigSocketClient().
Member Function Documentation
add_flag() [1/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 116 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_flag_function(name, utils::ResetToDefault(opt), description)
                  ->type_name(typeName)
                  ->take_last();
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References utils::ResetToDefault::ResetToDefault(), and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag(), and net::config::ConfigSection::add_flag().
add_flag() [2/6]
CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 129 of file ConfigSection.cpp.
{
        return add_flag(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_flag().
add_flag() [3/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 63 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_flag().
add_flag() [4/6]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 70 of file ConfigSection.hpp.
{
        return add_flag(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_flag() [5/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
add_flag() [6/6]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_flag (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsServer::ConfigTlsServer().
add_flag_function() [1/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue) protected inherited
Definition at line 138 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_flag_function(name, callback, description)
                  ->take_last()
                  ->default_val(defaultValue)
                  ->type_name(typeName);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_flag_function().
add_flag_function() [2/2]
CLI::Option * net::config::ConfigSection::add_flag_function (CLI::Option *& opt, const std::string & name, const std::function< void(int64_t)> & callback, const std::string & description, const std::string & typeName, const std::string & defaultValue, const CLI::Validator & validator) protected inherited
Definition at line 157 of file ConfigSection.cpp.
{
        return add_flag_function(opt, name, callback, description, typeName, defaultValue) //
            ->check(validator);
    }
References net::config::ConfigSection::add_flag_function().
Referenced by net::config::ConfigPhysicalSocket::add_socket_option().
add_option() [1/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description) protected inherited
Definition at line 89 of file ConfigSection.cpp.
{
        opt = section //
                  ->add_option_function<std::string>(name, utils::ResetToDefault(opt), description);
        if (opt->get_configurable()) {
            opt->group(section->get_formatter()->get_label("Persistent Options"));
        }
        return opt;
    }
References utils::ResetToDefault::ResetToDefault(), and net::config::ConfigSection::section.
Referenced by net::config::ConfigSection::add_option().
add_option() [2/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName) protected inherited
Definition at line 101 of file ConfigSection.cpp.
{
        return add_option(opt, name, description) //
            ->type_name(typeName);
    }
References net::config::ConfigSection::add_option().
Referenced by net::config::ConfigSection::add_option(), and net::config::ConfigSection::add_option().
add_option() [3/7]
CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, const CLI::Validator & additionalValidator) protected inherited
Definition at line 106 of file ConfigSection.cpp.
{
        return add_option(opt, name, description, typeName) //
            ->check(additionalValidator);
    }
References net::config::ConfigSection::add_option().
add_option() [4/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue) inherited
Definition at line 45 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName) //
            ->default_val(defaultValue);
    }
References net::config::ConfigSection::add_option().
add_option() [5/7]
template<typename ValueType > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueType defaultValue, const CLI::Validator & additionalValidator) inherited
Definition at line 52 of file ConfigSection.hpp.
{
        return add_option(opt, name, description, typeName, defaultValue) //
            ->check(additionalValidator);
    }
add_option() [6/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue) protected inherited
Referenced by net::config::ConfigTls::ConfigTls().
add_option() [7/7]
template<typename ValueTypeT > CLI::Option * net::config::ConfigSection::add_option (CLI::Option *& opt, const std::string & name, const std::string & description, const std::string & typeName, ValueTypeT defaultValue, const CLI::Validator & additionalValidator) protected inherited
Referenced by net::config::ConfigTls::ConfigTls(), and net::config::ConfigTlsClient::ConfigTlsClient().
add_section()
CLI::App * net::config::ConfigInstance::add_section (const std::string & name, const std::string & description) inherited
Definition at line 85 of file ConfigInstance.cpp.
{
        CLI::App* sectionSc = instanceSc //
                                  ->add_subcommand(name, description)
                                  ->configurable(false)
                                  ->group(this->name.empty() ? "" : "Sections")
                                  ->disabled(this->name.empty())
                                  ->silent(this->name.empty());
        sectionSc //
            ->option_defaults()
            ->configurable(!this->name.empty());
        sectionSc //
            ->add_flag_callback(
                "-h,--help",
                []() {
                    throw CLI::CallForHelp();
                },
                "Print this help message and exit")
            ->configurable(false)
            ->disable_flag_override()
            ->trigger_on_parse();
        sectionSc //
            ->add_flag_callback(
                "-a,--help-all",
                []() {
                    throw CLI::CallForAllHelp();
                },
                "Print this help message and exit")
            ->configurable(false)
            ->disable_flag_override()
            ->trigger_on_parse();
        return sectionSc;
    }
References net::config::ConfigInstance::instanceSc, and net::config::ConfigInstance::name.
Referenced by net::config::ConfigSection::ConfigSection().
getCaCertDir()
std::string net::config::ConfigTls::getCaCertDir () const inherited
Definition at line 122 of file ConfigTls.cpp.
{
        return caCertDirOpt->as<std::string>();
    }
References net::config::ConfigTls::caCertDirOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getCaCertFile()
std::string net::config::ConfigTls::getCaCertFile () const inherited
Definition at line 112 of file ConfigTls.cpp.
{
        return caCertFileOpt->as<std::string>();
    }
References net::config::ConfigTls::caCertFileOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getCertChain()
std::string net::config::ConfigTls::getCertChain () const inherited
Definition at line 84 of file ConfigTls.cpp.
{
        return certChainOpt->as<std::string>();
    }
References net::config::ConfigTls::certChainOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getCertKey()
std::string net::config::ConfigTls::getCertKey () const inherited
Definition at line 93 of file ConfigTls.cpp.
{
        return certKeyOpt->as<std::string>();
    }
References net::config::ConfigTls::certKeyOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getCertKeyPassword()
std::string net::config::ConfigTls::getCertKeyPassword () const inherited
Definition at line 102 of file ConfigTls.cpp.
{
        return certKeyPasswordOpt->as<std::string>();
    }
References net::config::ConfigTls::certKeyPasswordOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getCipherList()
std::string net::config::ConfigTls::getCipherList () const inherited
Definition at line 142 of file ConfigTls.cpp.
{
        return cipherListOpt->as<std::string>();
    }
References net::config::ConfigTls::cipherListOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getDisabled()
bool net::config::ConfigInstance::getDisabled () const inherited
Definition at line 144 of file ConfigInstance.cpp.
{
        return disableOpt //
            ->as<bool>();
    }
References net::config::ConfigInstance::disableOpt.
getInitTimeout()
utils::Timeval net::config::ConfigTls::getInitTimeout () const inherited
Definition at line 162 of file ConfigTls.cpp.
{
        return initTimeoutOpt->as<utils::Timeval>();
    }
References net::config::ConfigTls::initTimeoutOpt.
getInstanceName()
std::string net::config::ConfigInstance::getInstanceName () const inherited
Definition at line 81 of file ConfigInstance.cpp.
{
        return name.empty() ? "<anonymous>" : name;
    }
References net::config::ConfigInstance::name.
Referenced by net::un::config::ConfigAddress< ConfigAddressTypeT >::ConfigAddress(), net::config::ConfigAddressLocal< SocketAddressT >::ConfigAddressLocal(), net::config::ConfigAddressRemote< SocketAddressT >::ConfigAddressRemote(), net::config::ConfigConnection::ConfigConnection(), net::config::ConfigLegacy::ConfigLegacy(), net::config::ConfigListen::ConfigListen(), net::config::ConfigPhysicalSocket::ConfigPhysicalSocket(), and net::config::ConfigTls::ConfigTls().
getRequired()
bool net::config::ConfigInstance::getRequired () const inherited
Definition at line 140 of file ConfigInstance.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigInstance::requiredCount.
getShutdownTimeout()
utils::Timeval net::config::ConfigTls::getShutdownTimeout () const inherited
Definition at line 172 of file ConfigTls.cpp.
{
        return shutdownTimeoutOpt //
            ->as<utils::Timeval>();
    }
References net::config::ConfigTls::shutdownTimeoutOpt.
getSni()
std::string net::config::ConfigTlsClient::getSni () const inherited
Definition at line 34 of file ConfigTlsClient.cpp.
{
        return sniOpt->as<std::string>();
    }
References net::config::ConfigTlsClient::sniOpt.
Referenced by core::socket::stream::tls::ssl_set_sni().
getSslTlsOptions()
ssl_option_t net::config::ConfigTls::getSslTlsOptions () const inherited
Definition at line 152 of file ConfigTls.cpp.
{
        return tlsOptionsOpt->as<ssl_option_t>();
    }
References net::config::ConfigTls::tlsOptionsOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
getUseDefaultCaCertDir()
bool net::config::ConfigTls::getUseDefaultCaCertDir () const inherited
Definition at line 132 of file ConfigTls.cpp.
{
        return useDefaultCaCertDirOpt->as<bool>();
    }
References net::config::ConfigTls::useDefaultCaCertDirOpt.
Referenced by core::socket::stream::tls::SslConfig::SslConfig().
required() [1/3]
bool net::config::ConfigSection::required () const protected inherited
Definition at line 85 of file ConfigSection.cpp.
{
        return requiredCount > 0;
    }
References net::config::ConfigSection::requiredCount.
required() [2/3]
void net::config::ConfigInstance::required (CLI::App * section, bool req = true) inherited
Definition at line 121 of file ConfigInstance.cpp.
{
        if (req) {
            ++requiredCount;
            instanceSc //
                ->needs(section);
        } else {
            if (requiredCount > 0) {
                --requiredCount;
            }
            instanceSc //
                ->remove_needs(section);
        }
        instanceSc //
            ->required(requiredCount > 0);
        utils::Config::needs_instance(instanceSc);
    }
References net::config::ConfigInstance::instanceSc, utils::Config::needs_instance(), and net::config::ConfigInstance::requiredCount.
Referenced by net::config::ConfigSection::required().
required() [3/3]
void net::config::ConfigSection::required (CLI::Option * opt, bool req = true) protected inherited
Definition at line 61 of file ConfigSection.cpp.
{
        if (req && !opt->get_required()) {
            ++requiredCount;
            opt //
                ->default_str("")
                ->required()
                ->clear();
            section //
                ->needs(opt);
        } else if (opt->get_required()) {
            --requiredCount;
            opt //
                ->required(false)
                ->clear();
            section //
                ->remove_needs(opt);
        }
        section //
            ->required(requiredCount > 0);
        instance->required(section, req);
    }
References net::config::ConfigSection::instance, net::config::ConfigInstance::required(), net::config::ConfigSection::requiredCount, and net::config::ConfigSection::section.
setCaCertDir()
void net::config::ConfigTls::setCaCertDir (const std::string & newCaCertDir) inherited
Definition at line 126 of file ConfigTls.cpp.
{
        caCertDirOpt //
            ->default_str(newCaCertDir)
            ->clear();
    }
References net::config::ConfigTls::caCertDirOpt.
setCaCertFile()
void net::config::ConfigTls::setCaCertFile (const std::string & newCaCertFile) inherited
Definition at line 116 of file ConfigTls.cpp.
{
        caCertFileOpt //
            ->default_str(newCaCertFile)
            ->clear();
    }
References net::config::ConfigTls::caCertFileOpt.
setCertChain()
void net::config::ConfigTls::setCertChain (const std::string & newCertChain) inherited
Definition at line 88 of file ConfigTls.cpp.
{
        certChainOpt //
            ->default_str(newCertChain);
    }
References net::config::ConfigTls::certChainOpt.
setCertKey()
void net::config::ConfigTls::setCertKey (const std::string & newCertKey) inherited
Definition at line 97 of file ConfigTls.cpp.
{
        certKeyOpt //
            ->default_str(newCertKey);
    }
References net::config::ConfigTls::certKeyOpt.
setCertKeyPassword()
void net::config::ConfigTls::setCertKeyPassword (const std::string & newCertKeyPassword) inherited
Definition at line 106 of file ConfigTls.cpp.
{
        certKeyPasswordOpt //
            ->default_val(newCertKeyPassword)
            ->clear();
    }
References net::config::ConfigTls::certKeyPasswordOpt.
setCipherList()
void net::config::ConfigTls::setCipherList (const std::string & newCipherList) inherited
Definition at line 146 of file ConfigTls.cpp.
{
        cipherListOpt //
            ->default_val(newCipherList)
            ->clear();
    }
References net::config::ConfigTls::cipherListOpt.
setDisabled()
void net::config::ConfigInstance::setDisabled (bool disabled = true) inherited
Definition at line 149 of file ConfigInstance.cpp.
{
        disableOpt //
            ->default_val(disabled ? "true" : "false")
            ->take_all()
            ->clear();
    }
References net::config::ConfigInstance::disableOpt.
setInitTimeout()
void net::config::ConfigTls::setInitTimeout (const utils::Timeval & newInitTimeout) inherited
Definition at line 166 of file ConfigTls.cpp.
{
        initTimeoutOpt //
            ->default_val(newInitTimeout)
            ->clear();
    }
References net::config::ConfigTls::initTimeoutOpt.
setShutdownTimeout()
void net::config::ConfigTls::setShutdownTimeout (const utils::Timeval & newShutdownTimeout) inherited
Definition at line 177 of file ConfigTls.cpp.
{
        shutdownTimeoutOpt //
            ->default_val(newShutdownTimeout)
            ->clear();
    }
References net::config::ConfigTls::shutdownTimeoutOpt.
setSni()
void net::config::ConfigTlsClient::setSni (const std::string & sni) inherited
Definition at line 38 of file ConfigTlsClient.cpp.
{
        sniOpt //
            ->default_val(sni)
            ->clear();
    }
References net::config::ConfigTlsClient::sniOpt.
setSslTlsOptions()
void net::config::ConfigTls::setSslTlsOptions (ssl_option_t newSslTlsOptions) inherited
Definition at line 156 of file ConfigTls.cpp.
{
        tlsOptionsOpt //
            ->default_val(newSslTlsOptions)
            ->clear();
    }
References net::config::ConfigTls::tlsOptionsOpt.
setUseDefaultCaCertDir()
void net::config::ConfigTls::setUseDefaultCaCertDir (bool set = true) inherited
Definition at line 136 of file ConfigTls.cpp.
{
        useDefaultCaCertDirOpt //
            ->default_val(set ? "true" : "false")
            ->clear();
    }
References net::config::ConfigTls::useDefaultCaCertDirOpt.
Member Data Documentation
caCertDirOpt
CLI::Option* net::config::ConfigTls::caCertDirOpt = nullptr private inherited
Definition at line 83 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCaCertDir(), and net::config::ConfigTls::setCaCertDir().
caCertFileOpt
CLI::Option* net::config::ConfigTls::caCertFileOpt = nullptr private inherited
Definition at line 82 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCaCertFile(), and net::config::ConfigTls::setCaCertFile().
certChainOpt
CLI::Option* net::config::ConfigTls::certChainOpt = nullptr private inherited
Definition at line 79 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCertChain(), and net::config::ConfigTls::setCertChain().
certKeyOpt
CLI::Option* net::config::ConfigTls::certKeyOpt = nullptr private inherited
Definition at line 80 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCertKey(), and net::config::ConfigTls::setCertKey().
certKeyPasswordOpt
CLI::Option* net::config::ConfigTls::certKeyPasswordOpt = nullptr private inherited
Definition at line 81 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCertKeyPassword(), and net::config::ConfigTls::setCertKeyPassword().
cipherListOpt
CLI::Option* net::config::ConfigTls::cipherListOpt = nullptr private inherited
Definition at line 85 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getCipherList(), and net::config::ConfigTls::setCipherList().
disableOpt
CLI::Option* net::config::ConfigInstance::disableOpt = nullptr private inherited
Definition at line 65 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::ConfigInstance(), net::config::ConfigInstance::getDisabled(), and net::config::ConfigInstance::setDisabled().
initTimeoutOpt
CLI::Option* net::config::ConfigTls::initTimeoutOpt = nullptr private inherited
Definition at line 87 of file ConfigTls.h.
Referenced by net::config::ConfigTls::getInitTimeout(), and net::config::ConfigTls::setInitTimeout().
instance
ConfigInstance* net::config::ConfigSection::instance = nullptr private inherited
Definition at line 120 of file ConfigSection.h.
Referenced by net::config::ConfigSection::ConfigSection(), and net::config::ConfigSection::required().
instanceSc
CLI::App* net::config::ConfigInstance::instanceSc = nullptr private inherited
Definition at line 64 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::add_section(), net::config::ConfigInstance::ConfigInstance(), net::config::ConfigInstance::required(), and net::config::ConfigInstance::~ConfigInstance().
name
const std::string net::config::ConfigInstance::name private inherited
Definition at line 62 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::add_section(), net::config::ConfigInstance::ConfigInstance(), and net::config::ConfigInstance::getInstanceName().
requiredCount
uint8_t net::config::ConfigInstance::requiredCount = 0 private inherited
Definition at line 60 of file ConfigInstance.h.
Referenced by net::config::ConfigInstance::getRequired(), and net::config::ConfigInstance::required().
section
CLI::App* net::config::ConfigSection::section = nullptr protected inherited
Definition at line 125 of file ConfigSection.h.
Referenced by net::config::ConfigSection::add_flag(), net::config::ConfigSection::add_flag_function(), net::config::ConfigSection::add_option(), net::config::ConfigSection::ConfigSection(), net::config::ConfigTlsServer::ConfigTlsServer(), and net::config::ConfigSection::required().
shutdownTimeoutOpt
CLI::Option* net::config::ConfigTls::shutdownTimeoutOpt = nullptr private inherited
Definition at line 88 of file ConfigTls.h.
Referenced by net::config::ConfigTls::getShutdownTimeout(), and net::config::ConfigTls::setShutdownTimeout().
sniOpt
CLI::Option* net::config::ConfigTlsClient::sniOpt = nullptr private inherited
Definition at line 48 of file ConfigTlsClient.h.
Referenced by net::config::ConfigTlsClient::ConfigTlsClient(), net::config::ConfigTlsClient::getSni(), and net::config::ConfigTlsClient::setSni().
tlsOptionsOpt
CLI::Option* net::config::ConfigTls::tlsOptionsOpt = nullptr private inherited
Definition at line 86 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getSslTlsOptions(), and net::config::ConfigTls::setSslTlsOptions().
useDefaultCaCertDirOpt
CLI::Option* net::config::ConfigTls::useDefaultCaCertDirOpt = nullptr private inherited
Definition at line 84 of file ConfigTls.h.
Referenced by net::config::ConfigTls::ConfigTls(), net::config::ConfigTls::getUseDefaultCaCertDir(), and net::config::ConfigTls::setUseDefaultCaCertDir().
The documentation for this class was generated from the following files:
net/config/stream/tls/ConfigSocketClient.h
net/config/stream/tls/ConfigSocketClient.hpp