snode.c: express::middleware::JsonMiddleware Class Reference
express::middleware::JsonMiddleware Class Reference
#include <JsonMiddleware.h>
Public Member Functions
JsonMiddleware (const JsonMiddleware &)=delete
JsonMiddleware & operator= (const JsonMiddleware &)=delete
Public Member Functions inherited from express::Router
Router ()
void laxRouting (bool strict=false)
Route & use (const Router &router)
Route & use (const std::string &relativeMountPath, const Router &router)
Route & use (const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & all (const Router &router)
Route & all (const std::string &relativeMountPath, const Router &router)
Route & all (const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & get (const Router &router)
Route & get (const std::string &relativeMountPath, const Router &router)
Route & get (const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & put (const Router &router)
Route & put (const std::string &relativeMountPath, const Router &router)
Route & put (const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & post (const Router &router)
Route & post (const std::string &relativeMountPath, const Router &router)
Route & post (const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & del (const Router &router)
Route & del (const std::string &relativeMountPath, const Router &router)
Route & del (const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & connect (const Router &router)
Route & connect (const std::string &relativeMountPath, const Router &router)
Route & connect (const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & options (const Router &router)
Route & options (const std::string &relativeMountPath, const Router &router)
Route & options (const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & trace (const Router &router)
Route & trace (const std::string &relativeMountPath, const Router &router)
Route & trace (const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & patch (const Router &router)
Route & patch (const std::string &relativeMountPath, const Router &router)
Route & patch (const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & head (const Router &router)
Route & head (const std::string &relativeMountPath, const Router &router)
Route & head (const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Protected Member Functions
JsonMiddleware ()
Static Protected Member Functions
static class JsonMiddleware & instance ()
Friends
class JsonMiddleware & JsonMiddleware ()
Additional Inherited Members
Protected Attributes inherited from express::Router
std::shared_ptr< RootRoute > rootRoute = nullptr
Detailed Description
Definition at line 35 of file JsonMiddleware.h.
Constructor & Destructor Documentation
JsonMiddleware() [1/2]
express::middleware::JsonMiddleware::JsonMiddleware (const JsonMiddleware &) delete
JsonMiddleware() [2/2]
express::middleware::JsonMiddleware::JsonMiddleware () protected
Definition at line 35 of file JsonMiddleware.cpp.
{
        use([] MIDDLEWARE(req, res, next) {
            try {
                // parse body string with json library
                // store it as type json from nlohmann library
                //                nlohmann::json json = nlohmann::json::parse(req.body, req.body + req.contentLength);
                req.body.push_back(0);
                nlohmann::json json = nlohmann::json::parse(req.body);
                // set all the json data as attributes in the request object
                req.setAttribute<nlohmann::json>(json);
            } catch ([[maybe_unused]] const nlohmann::detail::parse_error& error) {
                // silently fail if body is not json
            }
            next();
        });
    }
References MIDDLEWARE, and express::Router::use().
Referenced by instance().
Member Function Documentation
instance()
class JsonMiddleware & express::middleware::JsonMiddleware::instance () static protected
Definition at line 55 of file JsonMiddleware.cpp.
{
        // Keep the created json middleware alive
        static std::shared_ptr<class JsonMiddleware> jsonMiddleware = nullptr;
        if (jsonMiddleware == nullptr) {
            jsonMiddleware = std::shared_ptr<JsonMiddleware>(new JsonMiddleware());
        }
        return *jsonMiddleware;
    }
References JsonMiddleware().
Referenced by JsonMiddleware.
operator=()
JsonMiddleware & express::middleware::JsonMiddleware::operator= (const JsonMiddleware &) delete
Friends And Related Symbol Documentation
JsonMiddleware
class JsonMiddleware & JsonMiddleware () friend
Definition at line 67 of file JsonMiddleware.cpp.
{
        return JsonMiddleware::instance();
    }
References instance().
The documentation for this class was generated from the following files:
express/middleware/JsonMiddleware.h
express/middleware/JsonMiddleware.cpp