SNode.C: iot::mqtt_fast::types::TypeBase Class Reference
iot::mqtt_fast::types::TypeBase Class Reference abstract
#include <TypeBase.h>
Public Member Functions
TypeBase (core::socket::SocketContext *socketContext)
TypeBase (const TypeBase &)=delete
TypeBase (TypeBase &&)=default
TypeBase & operator= (const TypeBase &)=delete
TypeBase & operator= (TypeBase &&)=delete
virtual ~TypeBase ()=default
virtual std::size_t construct ()=0
bool isComplete () const
bool isError () const
Protected Member Functions
std::size_t read (char *buf, std::size_t count)
virtual void reset ()
Protected Attributes
core::socket::SocketContext * socketContext
bool completed = false
bool error = false
Detailed Description
Definition at line 57 of file TypeBase.h.
Constructor & Destructor Documentation
TypeBase() [1/3]
iot::mqtt_fast::types::TypeBase::TypeBase (core::socket::SocketContext * socketContext)
Definition at line 52 of file TypeBase.cpp.
        : socketContext(socketContext) {
    }
References socketContext.
Referenced by iot::mqtt_fast::types::Binary::Binary(), iot::mqtt_fast::types::Int_1::Int_1(), and iot::mqtt_fast::types::Int_V::Int_V().
TypeBase() [2/3]
iot::mqtt_fast::types::TypeBase::TypeBase (const TypeBase &) delete
TypeBase() [3/3]
iot::mqtt_fast::types::TypeBase::TypeBase (TypeBase &&) default
~TypeBase()
virtual iot::mqtt_fast::types::TypeBase::~TypeBase () virtual default
Member Function Documentation
construct()
virtual std::size_t iot::mqtt_fast::types::TypeBase::construct () pure virtual
Implemented in iot::mqtt_fast::types::Binary, iot::mqtt_fast::types::Int_1, and iot::mqtt_fast::types::Int_V.
isComplete()
bool iot::mqtt_fast::types::TypeBase::isComplete () const
Definition at line 56 of file TypeBase.cpp.
{
        return completed;
    }
References completed.
Referenced by iot::mqtt_fast::ControlPacketFactory::construct().
isError()
bool iot::mqtt_fast::types::TypeBase::isError () const
Definition at line 60 of file TypeBase.cpp.
{
        return error;
    }
References error.
Referenced by iot::mqtt_fast::ControlPacketFactory::construct().
operator=() [1/2]
TypeBase & iot::mqtt_fast::types::TypeBase::operator= (const TypeBase &) delete
operator=() [2/2]
TypeBase & iot::mqtt_fast::types::TypeBase::operator= (TypeBase &&) delete
read()
std::size_t iot::mqtt_fast::types::TypeBase::read (char * buf, std::size_t count) protected
Definition at line 64 of file TypeBase.cpp.
{
        std::size_t ret = 0;
        ret = socketContext->readFromPeer(buf, count);
        return ret;
    }
References core::socket::SocketContext::readFromPeer(), and socketContext.
Referenced by iot::mqtt_fast::types::Int_1::construct(), and iot::mqtt_fast::types::Int_V::construct().
reset()
void iot::mqtt_fast::types::TypeBase::reset () protected virtual
Reimplemented in iot::mqtt_fast::types::Binary, iot::mqtt_fast::types::Int_1, and iot::mqtt_fast::types::Int_V.
Definition at line 72 of file TypeBase.cpp.
{
        completed = false;
        error = false;
    }
References completed, and error.
Referenced by iot::mqtt_fast::types::Int_1::reset(), and iot::mqtt_fast::types::Int_V::reset().
Member Data Documentation
completed
bool iot::mqtt_fast::types::TypeBase::completed = false protected
Definition at line 80 of file TypeBase.h.
Referenced by iot::mqtt_fast::types::Int_1::construct(), iot::mqtt_fast::types::Int_V::construct(), isComplete(), and reset().
error
bool iot::mqtt_fast::types::TypeBase::error = false protected
Definition at line 81 of file TypeBase.h.
Referenced by iot::mqtt_fast::types::Int_V::construct(), isError(), and reset().
socketContext
core::socket::SocketContext* iot::mqtt_fast::types::TypeBase::socketContext protected
Definition at line 78 of file TypeBase.h.
Referenced by read(), and TypeBase().
The documentation for this class was generated from the following files:
iot/mqtt-fast/types/TypeBase.h
iot/mqtt-fast/types/TypeBase.cpp