SNode.C: core::socket::stream::tls::TLSShutdown Class Reference
core::socket::stream::tls::TLSShutdown Class Reference
#include <TLSShutdown.h>
Static Public Member Functions
static void doShutdown (const std::string &instanceName, SSL *ssl, const std::function< void(void)> &onSuccess, const std::function< void(void)> &onTimeout, const std::function< void(int)> &onStatus, const utils::Timeval &timeout)
Static Public Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Private Member Functions
TLSShutdown (const std::string &instanceName, SSL *ssl, const std::function< void(void)> &onSuccess, const std::function< void(void)> &onTimeout, const std::function< void(int)> &onStatus, const utils::Timeval &timeout)
void readEvent () final
void writeEvent () final
void signalEvent (int signum) final
void readTimeout () final
void writeTimeout () final
void unobservedEvent () final
Private Attributes
SSL * ssl = nullptr
std::function< void(void)> onSuccess
std::function< void(void)> onTimeout
std::function< void(int)> onStatus
bool timeoutTriggered
int fd = -1
Additional Inherited Members
Public Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
int getRegisteredFd () const
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Member Functions inherited from core::eventreceiver::ReadEventReceiver
ReadEventReceiver (const std::string &name, const utils::Timeval &timeout)
Protected Member Functions inherited from core::DescriptorEventReceiver
bool enable (int fd)
void disable ()
void suspend ()
void resume ()
Protected Member Functions inherited from core::Observer
void observed ()
void unObserved ()
Observer ()=default
Observer (Observer &)=delete
Observer (Observer &&)=delete
virtual ~Observer ()
Protected Member Functions inherited from core::EventReceiver
virtual ~EventReceiver ()=default
EventReceiver (const std::string &name)
EventReceiver (EventReceiver &)=delete
EventReceiver (EventReceiver &&)=delete
EventReceiver & operator= (EventReceiver &)=delete
EventReceiver & operator= (EventReceiver &&)=delete
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Member Functions inherited from core::eventreceiver::WriteEventReceiver
WriteEventReceiver (const std::string &name, const utils::Timeval &timeout)
Static Protected Member Functions inherited from core::EventReceiver
static void atNextTick (const std::function< void(void)> &callBack)
Detailed Description
Definition at line 68 of file TLSShutdown.h.
Constructor & Destructor Documentation
TLSShutdown()
core::socket::stream::tls::TLSShutdown::TLSShutdown (const std::string & instanceName, SSL * ssl, const std::function< void(void)> & onSuccess, const std::function< void(void)> & onTimeout, const std::function< void(int)> & onStatus, const utils::Timeval & timeout) private
Definition at line 61 of file TLSShutdown.cpp.
        : ReadEventReceiver(instanceName + " SSL/TLS: Send close_notify", timeout)
        , WriteEventReceiver(instanceName + " SSL/TLS: Send close_notify", timeout)
        , ssl(ssl)
        , onSuccess(onSuccess)
        , onTimeout(onTimeout)
        , onStatus(onStatus)
        , timeoutTriggered(false)
        , fd(SSL_get_fd(ssl)) {
        const int ret = SSL_shutdown(ssl);
        int sslErr = SSL_ERROR_NONE;
        if (ret < 0) {
            sslErr = SSL_get_error(ssl, ret);
        }
        if (!ReadEventReceiver::enable(fd)) {
            delete this;
        } else if (!WriteEventReceiver::enable(fd)) {
            ReadEventReceiver::disable();
        } else {
            ReadEventReceiver::suspend();
            WriteEventReceiver::suspend();
            switch (sslErr) {
                case SSL_ERROR_WANT_READ:
                    ReadEventReceiver::resume();
                    break;
                case SSL_ERROR_WANT_WRITE:
                    WriteEventReceiver::resume();
                    break;
                case SSL_ERROR_NONE:
                case SSL_ERROR_ZERO_RETURN:
                    ReadEventReceiver::disable();
                    WriteEventReceiver::disable();
                    onSuccess();
                    break;
                default:
                    ReadEventReceiver::disable();
                    WriteEventReceiver::disable();
                    onStatus(sslErr);
                    break;
            }
        }
    }
References core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), fd, core::DescriptorEventReceiver::resume(), ssl, core::DescriptorEventReceiver::suspend(), timeoutTriggered, and TLSShutdown().
Referenced by doShutdown(), and TLSShutdown().
Member Function Documentation
doShutdown()
void core::socket::stream::tls::TLSShutdown::doShutdown (const std::string & instanceName, SSL * ssl, const std::function< void(void)> & onSuccess, const std::function< void(void)> & onTimeout, const std::function< void(int)> & onStatus, const utils::Timeval & timeout) static
Definition at line 52 of file TLSShutdown.cpp.
{
        new TLSShutdown(instanceName, ssl, onSuccess, onTimeout, onStatus, timeout);
    }
References TLSShutdown().
readEvent()
void core::socket::stream::tls::TLSShutdown::readEvent () final private virtual
Implements core::eventreceiver::ReadEventReceiver.
Definition at line 112 of file TLSShutdown.cpp.
{
        const int ret = SSL_shutdown(ssl);
        int sslErr = SSL_ERROR_NONE;
        if (ret < 0) {
            sslErr = SSL_get_error(ssl, ret);
        }
        switch (sslErr) {
            case SSL_ERROR_WANT_READ:
                break;
            case SSL_ERROR_WANT_WRITE:
                ReadEventReceiver::suspend();
                WriteEventReceiver::resume();
                break;
            case SSL_ERROR_NONE:
            case SSL_ERROR_ZERO_RETURN:
                ReadEventReceiver::disable();
                WriteEventReceiver::disable();
                onSuccess();
                break;
            default:
                ReadEventReceiver::disable();
                WriteEventReceiver::disable();
                onStatus(sslErr);
                break;
        }
    }
References core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::resume(), ssl, and core::DescriptorEventReceiver::suspend().
readTimeout()
void core::socket::stream::tls::TLSShutdown::readTimeout () final private virtual
Reimplemented from core::eventreceiver::ReadEventReceiver.
Definition at line 170 of file TLSShutdown.cpp.
{
        if (!timeoutTriggered) {
            timeoutTriggered = true;
            ReadEventReceiver::disable();
            WriteEventReceiver::disable();
            onTimeout();
        }
    }
References core::DescriptorEventReceiver::disable(), and timeoutTriggered.
signalEvent()
void core::socket::stream::tls::TLSShutdown::signalEvent (int signum) final private virtual
Reimplemented from core::eventreceiver::ReadEventReceiver.
Definition at line 188 of file TLSShutdown.cpp.
                                                             { // Do nothing on signal event
    }
unobservedEvent()
void core::socket::stream::tls::TLSShutdown::unobservedEvent () final private virtual
Implements core::Observer.
Definition at line 191 of file TLSShutdown.cpp.
{
        delete this;
    }
writeEvent()
void core::socket::stream::tls::TLSShutdown::writeEvent () final private virtual
Implements core::eventreceiver::WriteEventReceiver.
Definition at line 141 of file TLSShutdown.cpp.
{
        const int ret = SSL_shutdown(ssl);
        int sslErr = SSL_ERROR_NONE;
        if (ret < 0) {
            sslErr = SSL_get_error(ssl, ret);
        }
        switch (sslErr) {
            case SSL_ERROR_WANT_READ:
                WriteEventReceiver::suspend();
                ReadEventReceiver::resume();
                break;
            case SSL_ERROR_WANT_WRITE:
                break;
            case SSL_ERROR_NONE:
            case SSL_ERROR_ZERO_RETURN:
                ReadEventReceiver::disable();
                WriteEventReceiver::disable();
                onSuccess();
                break;
            default:
                ReadEventReceiver::disable();
                WriteEventReceiver::disable();
                onStatus(sslErr);
                break;
        }
    }
References core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::resume(), ssl, and core::DescriptorEventReceiver::suspend().
writeTimeout()
void core::socket::stream::tls::TLSShutdown::writeTimeout () final private virtual
Reimplemented from core::eventreceiver::WriteEventReceiver.
Definition at line 179 of file TLSShutdown.cpp.
{
        if (!timeoutTriggered) {
            timeoutTriggered = true;
            ReadEventReceiver::disable();
            WriteEventReceiver::disable();
            onTimeout();
        }
    }
References core::DescriptorEventReceiver::disable(), and timeoutTriggered.
Member Data Documentation
fd
int core::socket::stream::tls::TLSShutdown::fd = -1 private
Definition at line 103 of file TLSShutdown.h.
Referenced by TLSShutdown().
onStatus
std::function<void(int)> core::socket::stream::tls::TLSShutdown::onStatus private
Definition at line 99 of file TLSShutdown.h.
onSuccess
std::function<void(void)> core::socket::stream::tls::TLSShutdown::onSuccess private
Definition at line 97 of file TLSShutdown.h.
onTimeout
std::function<void(void)> core::socket::stream::tls::TLSShutdown::onTimeout private
Definition at line 98 of file TLSShutdown.h.
ssl
SSL* core::socket::stream::tls::TLSShutdown::ssl = nullptr private
Definition at line 96 of file TLSShutdown.h.
Referenced by readEvent(), TLSShutdown(), and writeEvent().
timeoutTriggered
bool core::socket::stream::tls::TLSShutdown::timeoutTriggered private
Definition at line 101 of file TLSShutdown.h.
Referenced by readTimeout(), TLSShutdown(), and writeTimeout().
The documentation for this class was generated from the following files:
core/socket/stream/tls/TLSShutdown.h
core/socket/stream/tls/TLSShutdown.cpp