SNode.C: core::select::FdSet Class Reference
core::select::FdSet Class Reference
#include <DescriptorEventPublisher.h>
Public Member Functions
FdSet ()
void set (int fd)
void clr (int fd)
int isSet (int fd) const
void zero ()
fd_set & get ()
Private Attributes
fd_set registered {}
fd_set active {}
Detailed Description
Definition at line 38 of file DescriptorEventPublisher.h.
Constructor & Destructor Documentation
FdSet()
core::select::FdSet::FdSet ()
Definition at line 29 of file DescriptorEventPublisher.cpp.
                 {
        zero();
    }
References zero().
Member Function Documentation
clr()
void core::select::FdSet::clr (int fd)
Definition at line 37 of file DescriptorEventPublisher.cpp.
{
        FD_CLR(fd, &registered);
        FD_CLR(fd, &active);
    }
References active, and registered.
Referenced by core::select::DescriptorEventPublisher::muxDel(), and core::select::DescriptorEventPublisher::muxOff().
get()
fd_set & core::select::FdSet::get ()
Definition at line 58 of file DescriptorEventPublisher.cpp.
                       {
        active = registered;
        return active;
    }
References active, and registered.
Referenced by core::select::EventMultiplexer::monitorDescriptors().
isSet()
int core::select::FdSet::isSet (int fd) const
Definition at line 42 of file DescriptorEventPublisher.cpp.
{
        return FD_ISSET(fd, &active);
    }
References active.
Referenced by core::select::DescriptorEventPublisher::spanActiveEvents().
set()
void core::select::FdSet::set (int fd)
Definition at line 33 of file DescriptorEventPublisher.cpp.
{
        FD_SET(fd, &registered);
    }
References registered.
Referenced by core::select::DescriptorEventPublisher::muxAdd(), and core::select::DescriptorEventPublisher::muxOn().
zero()
void core::select::FdSet::zero ()
Definition at line 46 of file DescriptorEventPublisher.cpp.
                     {
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-identifier"
#endif
        FD_ZERO(&registered);
        FD_ZERO(&active);
#ifdef __clang__
#pragma clang diagnostic pop
#endif
    }
References active, and registered.
Referenced by FdSet().
Member Data Documentation
active
fd_set core::select::FdSet::active {} private
Definition at line 50 of file DescriptorEventPublisher.h.
{};
Referenced by clr(), get(), isSet(), and zero().
registered
fd_set core::select::FdSet::registered {} private
Definition at line 49 of file DescriptorEventPublisher.h.
{};
Referenced by clr(), get(), set(), and zero().
The documentation for this class was generated from the following files:
core/multiplexer/select/DescriptorEventPublisher.h
core/multiplexer/select/DescriptorEventPublisher.cpp