SNode.C: iot::mqtt::server::broker::Session Class Reference
iot::mqtt::server::broker::Session Class Reference
#include <Session.h>
Public Member Functions
Session ()=default
Session (iot::mqtt::server::Mqtt *mqtt)
void sendPublish (iot::mqtt::server::broker::Message &message, uint8_t qoS, bool retain)
void publishQueued ()
Session * renew (iot::mqtt::server::Mqtt *mqtt)
void retain ()
bool isActive () const
bool isOwnedBy (const iot::mqtt::server::Mqtt *mqtt) const
nlohmann::json toJson () const final
void fromJson (const nlohmann::json &json)
bool isCleanSession () const
void clear ()
Private Attributes
iot::mqtt::server::Mqtt * mqtt = nullptr
std::deque< Message > messageQueue
std::map< uint16_t, iot::mqtt::packets::Publish > publishMap
std::set< uint16_t > pubrelPacketIdentifierSet
std::set< uint16_t > publishPacketIdentifierSet
Detailed Description
Definition at line 40 of file Session.h.
Constructor & Destructor Documentation
Session() [1/2]
iot::mqtt::server::broker::Session::Session () default
Session() [2/2]
iot::mqtt::server::broker::Session::Session (iot::mqtt::server::Mqtt * mqtt) explicit
Definition at line 40 of file Session.cpp.
        : mqtt(mqtt) {
    }
Referenced by iot::mqtt::server::broker::Broker::newSession().
Member Function Documentation
clear()
void iot::mqtt::Session::clear () inherited
Definition at line 93 of file Session.cpp.
{
        publishMap.clear();
        pubrelPacketIdentifierSet.clear();
        publishPacketIdentifierSet.clear();
    }
References iot::mqtt::Session::publishMap, iot::mqtt::Session::publishPacketIdentifierSet, and iot::mqtt::Session::pubrelPacketIdentifierSet.
Referenced by iot::mqtt::client::Mqtt::Mqtt().
fromJson()
void iot::mqtt::server::broker::Session::fromJson (const nlohmann::json & json)
Definition at line 112 of file Session.cpp.
{
        for (const nlohmann::json& messageJson : json["message_queue"]) {
            messageQueue.emplace_back(Message().fromJson(messageJson));
        }
        iot::mqtt::Session::fromJson(json);
    }
References iot::mqtt::server::broker::Message::fromJson(), iot::mqtt::Session::fromJson(), iot::mqtt::server::broker::Message::Message(), and messageQueue.
Referenced by iot::mqtt::server::broker::Broker::Broker().
isActive()
bool iot::mqtt::server::broker::Session::isActive () const
Definition at line 89 of file Session.cpp.
{
        return mqtt != nullptr;
    }
Referenced by iot::mqtt::server::broker::Broker::hasActiveSession(), iot::mqtt::server::broker::Broker::hasRetainedSession(), and sendPublish().
isCleanSession()
bool iot::mqtt::Session::isCleanSession () const inherited
isOwnedBy()
bool iot::mqtt::server::broker::Session::isOwnedBy (const iot::mqtt::server::Mqtt * mqtt) const
Definition at line 93 of file Session.cpp.
{
        return this->mqtt == mqtt;
    }
Referenced by iot::mqtt::server::broker::Broker::isActiveSession().
publishQueued()
void iot::mqtt::server::broker::Session::publishQueued ()
Definition at line 69 of file Session.cpp.
{
        LOG(DEBUG) << "MQTT Broker:     send queued messages ...";
        for (iot::mqtt::server::broker::Message& message : messageQueue) {
            sendPublish(message, message.getQoS(), false);
        }
        LOG(DEBUG) << "MQTT Broker:     ... done";
        messageQueue.clear();
    }
References iot::mqtt::server::broker::Message::getQoS(), messageQueue, and sendPublish().
Referenced by iot::mqtt::server::broker::Broker::restartSession().
renew()
Session * iot::mqtt::server::broker::Session::renew (iot::mqtt::server::Mqtt * mqtt)
Definition at line 79 of file Session.cpp.
{
        this->mqtt = mqtt;
        return this;
    }
Referenced by iot::mqtt::server::broker::Broker::renewSession().
retain()
void iot::mqtt::server::broker::Session::retain ()
Definition at line 85 of file Session.cpp.
{
        this->mqtt = nullptr;
    }
Referenced by iot::mqtt::server::broker::Broker::retainSession().
sendPublish()
void iot::mqtt::server::broker::Session::sendPublish (iot::mqtt::server::broker::Message & message, uint8_t qoS, bool retain)
Definition at line 44 of file Session.cpp.
{
        LOG(DEBUG) << "MQTT Broker:   TopicName: " << message.getTopic();
        LOG(DEBUG) << "MQTT Broker:   Message:\n" << iot::mqtt::Mqtt::stringToHexString(message.getMessage());
        LOG(DEBUG) << "MQTT Broker:   QoS: " << static_cast<uint16_t>(std::min(qoS, message.getQoS()));
        if (isActive()) {
            if ((mqtt->getReflect() || mqtt->getClientId() != message.getOriginClientId())) {
                mqtt->sendPublish(message.getTopic(),
                                  message.getMessage(),
                                  std::min(message.getQoS(), qoS),
                                  !mqtt->getReflect() ? message.getOriginRetain() || retain : retain);
            } else {
                LOG(DEBUG) << "MQTT Broker:   Suppress reflection to origin to avoid message looping";
                LOG(DEBUG) << "               Origin: " << message.getOriginClientId();
            }
        } else {
            if (message.getQoS() == 0) {
                messageQueue.clear();
            }
            message.setQoS(std::min(message.getQoS(), qoS));
            messageQueue.emplace_back(message);
        }
    }
References iot::mqtt::server::Mqtt::getClientId(), iot::mqtt::server::broker::Message::getMessage(), iot::mqtt::server::broker::Message::getOriginClientId(), iot::mqtt::server::broker::Message::getOriginRetain(), iot::mqtt::server::broker::Message::getQoS(), iot::mqtt::server::Mqtt::getReflect(), iot::mqtt::server::broker::Message::getTopic(), isActive(), messageQueue, iot::mqtt::Mqtt::sendPublish(), iot::mqtt::server::broker::Message::setQoS(), and iot::mqtt::Mqtt::stringToHexString().
Referenced by publishQueued(), and iot::mqtt::server::broker::Broker::sendPublish().
toJson()
nlohmann::json iot::mqtt::server::broker::Session::toJson () const final virtual
Reimplemented from iot::mqtt::Session.
Definition at line 97 of file Session.cpp.
{
        nlohmann::json json = iot::mqtt::Session::toJson();
        std::vector<nlohmann::json> messageVector;
        messageVector.reserve(messageQueue.size());
        for (const Message& message : messageQueue) {
            messageVector.emplace_back(message.toJson());
        }
        json["message_queue"] = messageVector;
        return json;
    }
References messageQueue, iot::mqtt::server::broker::Message::toJson(), and iot::mqtt::Session::toJson().
Referenced by iot::mqtt::server::broker::Broker::~Broker().
Member Data Documentation
messageQueue
std::deque<Message> iot::mqtt::server::broker::Session::messageQueue private
Definition at line 62 of file Session.h.
Referenced by fromJson(), publishQueued(), sendPublish(), and toJson().
mqtt
iot::mqtt::server::Mqtt* iot::mqtt::server::broker::Session::mqtt = nullptr private
Definition at line 60 of file Session.h.
publishMap
std::map<uint16_t, iot::mqtt::packets::Publish> iot::mqtt::Session::publishMap private inherited
Definition at line 59 of file Session.h.
Referenced by iot::mqtt::Mqtt::_onPubcomp(), iot::mqtt::Mqtt::_onPubrec(), iot::mqtt::Session::clear(), iot::mqtt::Session::fromJson(), iot::mqtt::Mqtt::initSession(), iot::mqtt::Mqtt::sendPublish(), and iot::mqtt::Session::toJson().
publishPacketIdentifierSet
std::set<uint16_t> iot::mqtt::Session::publishPacketIdentifierSet private inherited
Definition at line 63 of file Session.h.
Referenced by iot::mqtt::Mqtt::_onPublish(), iot::mqtt::Mqtt::_onPubrel(), iot::mqtt::Session::clear(), iot::mqtt::Session::fromJson(), and iot::mqtt::Session::toJson().
pubrelPacketIdentifierSet
std::set<uint16_t> iot::mqtt::Session::pubrelPacketIdentifierSet private inherited
Definition at line 60 of file Session.h.
Referenced by iot::mqtt::Mqtt::_onPubcomp(), iot::mqtt::Mqtt::_onPubrec(), iot::mqtt::Session::clear(), iot::mqtt::Session::fromJson(), iot::mqtt::Mqtt::initSession(), and iot::mqtt::Session::toJson().
The documentation for this class was generated from the following files:
iot/mqtt/server/broker/Session.h
iot/mqtt/server/broker/Session.cpp