SNode.C: FormatterBase Class Reference
FormatterBase Class Reference abstract
#include <CLI11.hpp>
Public Member Functions
Basic
FormatterBase ()=default
FormatterBase (const FormatterBase &)=default
FormatterBase (FormatterBase &&)=default
FormatterBase & operator= (const FormatterBase &)=default
FormatterBase & operator= (FormatterBase &&)=default
virtual ~FormatterBase () noexcept
Adding a destructor in this form to work around bug in GCC 4.7.
virtual std::string make_help (const App *, std::string, AppFormatMode) const =0
This is the key method that puts together help.
Setters
void label (std::string key, std::string val)
Set the "REQUIRED" label.
void column_width (std::size_t val)
Set the column width.
Getters
std::string get_label (std::string key) const
Get the current value of a name (REQUIRED, etc.)
std::size_t get_column_width () const
Get the current column width.
Protected Attributes
Options
std::size_t column_width_ {30}
The width of the first column.
std::map< std::string, std::string > labels_ {}
The required help printout labels (user changeable) Values are Needs, Excludes, etc.
Detailed Description
This is the minimum requirements to run a formatter.
A user can subclass this is if they do not care at all about the structure in CLI::Formatter.
Definition at line 4571 of file CLI11.hpp.
Constructor & Destructor Documentation
FormatterBase() [1/3]
FormatterBase::FormatterBase () default
FormatterBase() [2/3]
FormatterBase::FormatterBase (const FormatterBase &) default
FormatterBase() [3/3]
FormatterBase::FormatterBase (FormatterBase &&) default
~FormatterBase()
virtual FormatterBase::~FormatterBase () inline virtual noexcept
Adding a destructor in this form to work around bug in GCC 4.7.
Definition at line 4595 of file CLI11.hpp.
{
        } // NOLINT(modernize-use-equals-default)
Member Function Documentation
column_width()
void FormatterBase::column_width (std::size_t val) inline
Set the column width.
Definition at line 4611 of file CLI11.hpp.
{
            column_width_ = val;
        }
References column_width_.
get_column_width()
std::size_t FormatterBase::get_column_width () const inline
Get the current column width.
Definition at line 4627 of file CLI11.hpp.
{
            return column_width_;
        }
References column_width_.
get_label()
std::string FormatterBase::get_label (std::string key) const inline
Get the current value of a name (REQUIRED, etc.)
Definition at line 4620 of file CLI11.hpp.
{
            if (labels_.find(key) == labels_.end())
                return key;
            return labels_.at(key);
        }
Referenced by Formatter::make_description(), CLI::HelpFormatter::make_expanded(), CLI::HelpFormatter::make_option_opts(), Formatter::make_option_opts(), CLI::HelpFormatter::make_subcommand(), Formatter::make_subcommand(), CLI::HelpFormatter::make_usage(), and Formatter::make_usage().
label()
void FormatterBase::label (std::string key, std::string val) inline
Set the "REQUIRED" label.
Definition at line 4606 of file CLI11.hpp.
{
            labels_[key] = val;
        }
make_help()
virtual std::string FormatterBase::make_help (const App * , std::string , AppFormatMode) const pure virtual
This is the key method that puts together help.
Implemented in Formatter, and FormatterLambda.
operator=() [1/2]
FormatterBase & FormatterBase::operator= (const FormatterBase &) default
operator=() [2/2]
FormatterBase & FormatterBase::operator= (FormatterBase &&) default
Member Data Documentation
column_width_
std::size_t FormatterBase::column_width_ {30} protected
The width of the first column.
Definition at line 4577 of file CLI11.hpp.
{30};
Referenced by column_width(), get_column_width(), Formatter::make_option(), CLI::HelpFormatter::make_subcommand(), and Formatter::make_subcommand().
labels_
std::map<std::string, std::string> FormatterBase::labels_ {} protected
The required help printout labels (user changeable) Values are Needs, Excludes, etc.
Definition at line 4581 of file CLI11.hpp.
{};
The documentation for this class was generated from the following file:
src/utils/CLI11.hpp