SNode.C: Error Class Reference
Error Class Reference
Errors
All errors derive from this one.
#include <CLI11.hpp>
Public Member Functions
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Private Attributes
int actual_exit_code
std::string error_name {"Error"}
Detailed Description
All errors derive from this one.
Definition at line 1054 of file CLI11.hpp.
Constructor & Destructor Documentation
Error() [1/2]
Error::Error (std::string name, std::string msg, int exit_code = static_cast<int>(ExitCodes::BaseClass)) inline
Definition at line 1067 of file CLI11.hpp.
            : runtime_error(msg)
            , actual_exit_code(exit_code)
            , error_name(std::move(name)) {
        }
References actual_exit_code, and Error().
Referenced by Error(), and Error().
Error() [2/2]
Error::Error (std::string name, std::string msg, ExitCodes exit_code) inline
Definition at line 1073 of file CLI11.hpp.
            : Error(name, msg, static_cast<int>(exit_code)) {
        }
References Error().
Member Function Documentation
get_exit_code()
int Error::get_exit_code () const inline
Definition at line 1059 of file CLI11.hpp.
{
            return actual_exit_code;
        }
References actual_exit_code.
Referenced by App::exit().
get_name()
std::string Error::get_name () const inline
Definition at line 1063 of file CLI11.hpp.
{
            return error_name;
        }
Referenced by App::exit(), and FailureMessage::help().
Member Data Documentation
actual_exit_code
int Error::actual_exit_code private
Definition at line 1055 of file CLI11.hpp.
Referenced by Error(), and get_exit_code().
error_name
std::string Error::error_name {"Error"} private
Definition at line 1056 of file CLI11.hpp.
{"Error"};
The documentation for this class was generated from the following file:
src/utils/CLI11.hpp