SNode.C: iot::mqtt_fast::SocketContext Class Reference
iot::mqtt_fast::SocketContext Class Reference abstract
#include <SocketContext.h>
Public Member Functions
SocketContext (core::socket::stream::SocketConnection *socketConnection)
void sendConnect (const std::string &clientId)
void sendConnack (uint8_t returnCode, uint8_t flags)
void sendPublish (const std::string &topic, const std::string &message, bool dup=false, uint8_t qoS=0, bool retain=false)
void sendPuback (uint16_t packetIdentifier)
void sendPubrec (uint16_t packetIdentifier)
void sendPubrel (uint16_t packetIdentifier)
void sendPubcomp (uint16_t packetIdentifier)
void sendSubscribe (std::list< Topic > &topics)
void sendSuback (uint16_t packetIdentifier, std::list< uint8_t > &returnCodes)
void sendUnsubscribe (std::list< std::string > &topics)
void sendUnsuback (uint16_t packetIdentifier)
void sendPingreq ()
void sendPingresp ()
void sendDisconnect ()
void sendToPeer (const char *junk, std::size_t junkLen) const final
virtual void sendToPeer (const char *junk, std::size_t junkLen) const=0
void sendToPeer (const std::string &data) const
std::size_t readFromPeer (char *junk, std::size_t junklen) const final
void setTimeout (const utils::Timeval &timeout) final
void shutdownRead ()
void shutdownWrite (bool forceClose=false)
void shutdown (bool forceClose=false)
void close () override
core::socket::stream::SocketConnection * getSocketConnection () const
core::socket::stream::SocketContext * switchSocketContext (core::socket::stream::SocketContextFactory *socketContextFactory)
Protected Member Functions
virtual void onExit (int sig)
Private Types
using Super = core::socket::SocketContext
Private Member Functions
virtual void onConnect (const iot::mqtt_fast::packets::Connect &connect)=0
virtual void onConnack (const iot::mqtt_fast::packets::Connack &connack)=0
virtual void onPublish (const iot::mqtt_fast::packets::Publish &publish)=0
virtual void onPuback (const iot::mqtt_fast::packets::Puback &puback)=0
virtual void onPubrec (const iot::mqtt_fast::packets::Pubrec &pubrec)=0
virtual void onPubrel (const iot::mqtt_fast::packets::Pubrel &pubrel)=0
virtual void onPubcomp (const iot::mqtt_fast::packets::Pubcomp &pubcomp)=0
virtual void onSubscribe (const iot::mqtt_fast::packets::Subscribe &subscribe)=0
virtual void onSuback (const iot::mqtt_fast::packets::Suback &suback)=0
virtual void onUnsubscribe (const iot::mqtt_fast::packets::Unsubscribe &unsubscribe)=0
virtual void onUnsuback (const iot::mqtt_fast::packets::Unsuback &unsuback)=0
virtual void onPingreq (const iot::mqtt_fast::packets::Pingreq &pingreq)=0
virtual void onPingresp (const iot::mqtt_fast::packets::Pingresp &pingresp)=0
virtual void onDisconnect (const iot::mqtt_fast::packets::Disconnect &disconnect)=0
virtual std::size_t onReceivedFromPeer () final
void send (iot::mqtt_fast::ControlPacket &&controlPacket) const
void send (iot::mqtt_fast::ControlPacket &controlPacket) const
void send (std::vector< char > &&data) const
void printData (const std::vector< char > &data) const
uint16_t getPacketIdentifier ()
virtual void onConnected ()=0
virtual void onDisconnected ()=0
void onWriteError (int errnum) override
void onReadError (int errnum) override
Private Attributes
iot::mqtt_fast::ControlPacketFactory controlPacketFactory
uint16_t _packetIdentifier = 0
core::socket::stream::SocketConnection * socketConnection
Detailed Description
Definition at line 59 of file SocketContext.h.
Member Typedef Documentation
Super
using core::socket::stream::SocketContext::Super = core::socket::SocketContext private inherited
Definition at line 42 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext()
iot::mqtt_fast::SocketContext::SocketContext (core::socket::stream::SocketConnection * socketConnection) explicit
Definition at line 36 of file SocketContext.cpp.
        : core::socket::stream::SocketContext(socketConnection)
        , controlPacketFactory(this) {
    }
References iot::mqtt_fast::ControlPacketFactory::ControlPacketFactory(), controlPacketFactory, and core::socket::stream::SocketContext::SocketContext().
Member Function Documentation
close()
void core::socket::stream::SocketContext::close () override virtual inherited
Implements core::socket::SocketContext.
Reimplemented in iot::mqtt::SocketContext.
Definition at line 53 of file SocketContext.cpp.
{
        socketConnection->close();
    }
References core::socket::stream::SocketConnection::close(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::server::RequestContextBase::close(), iot::mqtt::SocketContext::close(), web::http::client::Request::enqueue(), onReceivedFromPeer(), web::http::client::Request::upgrade(), and web::http::client::Response::upgrade().
getPacketIdentifier()
uint16_t iot::mqtt_fast::SocketContext::getPacketIdentifier () inline private
Definition at line 101 of file SocketContext.h.
{
            ++_packetIdentifier;
            if (_packetIdentifier == 0) {
                ++_packetIdentifier;
            }
            return _packetIdentifier;
        }
References _packetIdentifier.
Referenced by sendPublish(), sendSubscribe(), and sendUnsubscribe().
getSocketConnection()
SocketConnection * core::socket::stream::SocketContext::getSocketConnection () const inherited
Definition at line 37 of file SocketContext.cpp.
{
        return socketConnection;
    }
References core::socket::stream::SocketContext::socketConnection.
Referenced by iot::mqtt::SocketContext::getSocketConnection(), and web::http::client::SocketContext< RequestT, ResponseT >::onConnected().
onConnack()
virtual void iot::mqtt_fast::SocketContext::onConnack (const iot::mqtt_fast::packets::Connack & connack) private pure virtual
Referenced by onReceivedFromPeer().
onConnect()
virtual void iot::mqtt_fast::SocketContext::onConnect (const iot::mqtt_fast::packets::Connect & connect) private pure virtual
Referenced by onReceivedFromPeer().
onConnected()
virtual void core::socket::stream::SocketContext::onConnected () private pure virtual inherited
Implemented in iot::mqtt::SocketContext, web::http::client::SocketContext< RequestT, ResponseT >, web::http::server::SocketContext< RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by core::socket::stream::SocketConnection::connected(), and core::socket::stream::SocketConnection::connected().
onDisconnect()
virtual void iot::mqtt_fast::SocketContext::onDisconnect (const iot::mqtt_fast::packets::Disconnect & disconnect) private pure virtual
Referenced by onReceivedFromPeer().
onDisconnected()
virtual void core::socket::stream::SocketContext::onDisconnected () private pure virtual inherited
Implemented in iot::mqtt::SocketContext, web::http::client::SocketContext< RequestT, ResponseT >, web::http::server::SocketContext< RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by core::socket::stream::SocketConnection::disconnected().
onExit()
void core::socket::SocketContext::onExit (int sig) protected virtual inherited
Reimplemented in iot::mqtt::SocketContext, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Definition at line 48 of file SocketContext.cpp.
{
        LOG(TRACE) << "Applicationprotocol exit due to '" << strsignal(sig) << "' (SIG" << utils::system::sigabbrev_np(sig) << " = " << sig
                   << ")";
    }
References utils::system::sigabbrev_np().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onExit().
onPingreq()
virtual void iot::mqtt_fast::SocketContext::onPingreq (const iot::mqtt_fast::packets::Pingreq & pingreq) private pure virtual
Referenced by onReceivedFromPeer().
onPingresp()
virtual void iot::mqtt_fast::SocketContext::onPingresp (const iot::mqtt_fast::packets::Pingresp & pingresp) private pure virtual
Referenced by onReceivedFromPeer().
onPuback()
virtual void iot::mqtt_fast::SocketContext::onPuback (const iot::mqtt_fast::packets::Puback & puback) private pure virtual
Referenced by onReceivedFromPeer().
onPubcomp()
virtual void iot::mqtt_fast::SocketContext::onPubcomp (const iot::mqtt_fast::packets::Pubcomp & pubcomp) private pure virtual
Referenced by onReceivedFromPeer().
onPublish()
virtual void iot::mqtt_fast::SocketContext::onPublish (const iot::mqtt_fast::packets::Publish & publish) private pure virtual
Referenced by onReceivedFromPeer().
onPubrec()
virtual void iot::mqtt_fast::SocketContext::onPubrec (const iot::mqtt_fast::packets::Pubrec & pubrec) private pure virtual
Referenced by onReceivedFromPeer().
onPubrel()
virtual void iot::mqtt_fast::SocketContext::onPubrel (const iot::mqtt_fast::packets::Pubrel & pubrel) private pure virtual
Referenced by onReceivedFromPeer().
onReadError()
void core::socket::stream::SocketContext::onReadError (int errnum) override private virtual inherited
Reimplemented from core::socket::SocketContext.
Definition at line 75 of file SocketContext.cpp.
{
        Super::onReadError(errnum);
        shutdownWrite();
    }
References core::socket::SocketContext::onReadError(), and core::socket::stream::SocketContext::shutdownWrite().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReadError().
onReceivedFromPeer()
std::size_t iot::mqtt_fast::SocketContext::onReceivedFromPeer () final private virtual
Implements core::socket::SocketContext.
Definition at line 139 of file SocketContext.cpp.
{
        std::size_t consumed = controlPacketFactory.construct();
        if (controlPacketFactory.isError()) {
            LOG(ERROR) << "SocketContext: Error during ControlPacket construction";
            close();
        } else if (controlPacketFactory.isComplete()) {
            LOG(DEBUG) << "======================================================";
            LOG(DEBUG) << "PacketType: " << static_cast<uint16_t>(controlPacketFactory.getPacketType());
            LOG(DEBUG) << "PacketFlags: " << static_cast<uint16_t>(controlPacketFactory.getPacketFlags());
            LOG(DEBUG) << "RemainingLength: " << static_cast<uint16_t>(controlPacketFactory.getRemainingLength());
            printData(controlPacketFactory.getPacket().getValue());
            switch (controlPacketFactory.getPacketType()) {
                case MQTT_CONNECT:
                    onConnect(iot::mqtt_fast::packets::Connect(controlPacketFactory));
                    break;
                case MQTT_CONNACK:
                    onConnack(iot::mqtt_fast::packets::Connack(controlPacketFactory));
                    break;
                case MQTT_PUBLISH:
                    onPublish(iot::mqtt_fast::packets::Publish(controlPacketFactory));
                    break;
                case MQTT_PUBACK:
                    onPuback(iot::mqtt_fast::packets::Puback(controlPacketFactory));
                    break;
                case MQTT_PUBREC:
                    onPubrec(iot::mqtt_fast::packets::Pubrec(controlPacketFactory));
                    break;
                case MQTT_PUBREL:
                    onPubrel(iot::mqtt_fast::packets::Pubrel(controlPacketFactory));
                    break;
                case MQTT_PUBCOMP:
                    onPubcomp(iot::mqtt_fast::packets::Pubcomp(controlPacketFactory));
                    break;
                case MQTT_SUBSCRIBE:
                    onSubscribe(iot::mqtt_fast::packets::Subscribe(controlPacketFactory));
                    break;
                case MQTT_SUBACK:
                    onSuback(iot::mqtt_fast::packets::Suback(controlPacketFactory));
                    break;
                case MQTT_UNSUBSCRIBE:
                    onUnsubscribe(iot::mqtt_fast::packets::Unsubscribe(controlPacketFactory));
                    break;
                case MQTT_UNSUBACK:
                    onUnsuback(iot::mqtt_fast::packets::Unsuback(controlPacketFactory));
                    break;
                case MQTT_PINGREQ:
                    onPingreq(iot::mqtt_fast::packets::Pingreq(controlPacketFactory));
                    break;
                case MQTT_PINGRESP:
                    onPingresp(iot::mqtt_fast::packets::Pingresp(controlPacketFactory));
                    break;
                case MQTT_DISCONNECT:
                    onDisconnect(iot::mqtt_fast::packets::Disconnect(controlPacketFactory));
                    break;
                default:
                    close();
                    break;
            }
            controlPacketFactory.reset();
        }
        return consumed;
    }
References core::socket::stream::SocketContext::close(), iot::mqtt_fast::packets::Connack::Connack(), iot::mqtt_fast::packets::Connect::Connect(), iot::mqtt_fast::ControlPacketFactory::construct(), controlPacketFactory, iot::mqtt_fast::packets::Disconnect::Disconnect(), iot::mqtt_fast::ControlPacketFactory::getPacket(), iot::mqtt_fast::ControlPacketFactory::getPacketFlags(), iot::mqtt_fast::ControlPacketFactory::getPacketType(), iot::mqtt_fast::ControlPacketFactory::getRemainingLength(), iot::mqtt_fast::types::Binary::getValue(), iot::mqtt_fast::ControlPacketFactory::isComplete(), iot::mqtt_fast::ControlPacketFactory::isError(), onConnack(), onConnect(), onDisconnect(), onPingreq(), onPingresp(), onPuback(), onPubcomp(), onPublish(), onPubrec(), onPubrel(), onSuback(), onSubscribe(), onUnsuback(), onUnsubscribe(), iot::mqtt_fast::packets::Pingreq::Pingreq(), iot::mqtt_fast::packets::Pingresp::Pingresp(), printData(), iot::mqtt_fast::packets::Puback::Puback(), iot::mqtt_fast::packets::Pubcomp::Pubcomp(), iot::mqtt_fast::packets::Publish::Publish(), iot::mqtt_fast::packets::Pubrec::Pubrec(), iot::mqtt_fast::packets::Pubrel::Pubrel(), iot::mqtt_fast::ControlPacketFactory::reset(), iot::mqtt_fast::packets::Suback::Suback(), iot::mqtt_fast::packets::Subscribe::Subscribe(), iot::mqtt_fast::packets::Unsuback::Unsuback(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
onSuback()
virtual void iot::mqtt_fast::SocketContext::onSuback (const iot::mqtt_fast::packets::Suback & suback) private pure virtual
Referenced by onReceivedFromPeer().
onSubscribe()
virtual void iot::mqtt_fast::SocketContext::onSubscribe (const iot::mqtt_fast::packets::Subscribe & subscribe) private pure virtual
Referenced by onReceivedFromPeer().
onUnsuback()
virtual void iot::mqtt_fast::SocketContext::onUnsuback (const iot::mqtt_fast::packets::Unsuback & unsuback) private pure virtual
Referenced by onReceivedFromPeer().
onUnsubscribe()
virtual void iot::mqtt_fast::SocketContext::onUnsubscribe (const iot::mqtt_fast::packets::Unsubscribe & unsubscribe) private pure virtual
Referenced by onReceivedFromPeer().
onWriteError()
void core::socket::stream::SocketContext::onWriteError (int errnum) override private virtual inherited
Reimplemented from core::socket::SocketContext.
Definition at line 70 of file SocketContext.cpp.
{
        Super::onWriteError(errnum);
        shutdownRead();
    }
References core::socket::SocketContext::onWriteError(), and core::socket::stream::SocketContext::shutdownRead().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onWriteError().
printData()
void iot::mqtt_fast::SocketContext::printData (const std::vector< char > & data) const private
Definition at line 220 of file SocketContext.cpp.
{
        std::stringstream ss;
        ss << "Data: ";
        unsigned long i = 0;
        for (char ch : data) {
            if (i != 0 && i % 8 == 0 && i + 1 != data.size()) {
                ss << std::endl;
                ss << "                                            ";
            }
            ++i;
            ss << "0x" << std::hex << std::setfill('0') << std::setw(2) << static_cast<uint16_t>(static_cast<uint8_t>(ch))
               << " "; // << " | ";
        }
        LOG(DEBUG) << ss.str();
    }
Referenced by onReceivedFromPeer(), and send().
readFromPeer()
std::size_t core::socket::stream::SocketContext::readFromPeer (char * junk, std::size_t junklen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 45 of file SocketContext.cpp.
{
        return socketConnection->readFromPeer(junk, junklen);
    }
References core::socket::stream::SocketConnection::readFromPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::Parser::readContent(), web::http::Parser::readHeaderLine(), web::http::Parser::readStartLine(), and iot::mqtt::SocketContext::recv().
send() [1/3]
void iot::mqtt_fast::SocketContext::send (iot::mqtt_fast::ControlPacket && controlPacket) const private
Definition at line 207 of file SocketContext.cpp.
{
        send(controlPacket.getPacket());
    }
References iot::mqtt_fast::ControlPacket::getPacket(), and send().
Referenced by sendConnack(), sendConnect(), sendDisconnect(), sendPingreq(), sendPingresp(), sendPuback(), sendPubcomp(), sendPublish(), sendPubrec(), sendPubrel(), sendSuback(), sendSubscribe(), sendUnsuback(), and sendUnsubscribe().
send() [2/3]
void iot::mqtt_fast::SocketContext::send (iot::mqtt_fast::ControlPacket & controlPacket) const private
Definition at line 211 of file SocketContext.cpp.
{
        send(controlPacket.getPacket());
    }
References iot::mqtt_fast::ControlPacket::getPacket(), and send().
send() [3/3]
void iot::mqtt_fast::SocketContext::send (std::vector< char > && data) const private
Definition at line 215 of file SocketContext.cpp.
{
        printData(data);
        sendToPeer(data.data(), data.size());
    }
References printData(), and core::socket::stream::SocketContext::sendToPeer().
Referenced by send(), and send().
sendConnack()
void iot::mqtt_fast::SocketContext::sendConnack (uint8_t returnCode, uint8_t flags)
Definition at line 48 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send CONNACK";
        LOG(DEBUG) << "============";
        send(iot::mqtt_fast::packets::Connack(returnCode, flags));
    }
References iot::mqtt_fast::packets::Connack::Connack(), and send().
sendConnect()
void iot::mqtt_fast::SocketContext::sendConnect (const std::string & clientId)
Definition at line 41 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send CONNECT";
        LOG(DEBUG) << "============";
        send(iot::mqtt_fast::packets::Connect(clientId));
    }
References iot::mqtt_fast::packets::Connect::Connect(), and send().
sendDisconnect()
void iot::mqtt_fast::SocketContext::sendDisconnect ()
Definition at line 132 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send Disconnect";
        LOG(DEBUG) << "===============";
        send(iot::mqtt_fast::packets::Disconnect());
    }
References iot::mqtt_fast::packets::Disconnect::Disconnect(), and send().
sendPingreq()
void iot::mqtt_fast::SocketContext::sendPingreq ()
Definition at line 118 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send Pingreq";
        LOG(DEBUG) << "============";
        send(iot::mqtt_fast::packets::Pingreq());
    }
References iot::mqtt_fast::packets::Pingreq::Pingreq(), and send().
sendPingresp()
void iot::mqtt_fast::SocketContext::sendPingresp ()
Definition at line 125 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send Pingresp";
        LOG(DEBUG) << "=============";
        send(iot::mqtt_fast::packets::Pingresp());
    }
References iot::mqtt_fast::packets::Pingresp::Pingresp(), and send().
sendPuback()
void iot::mqtt_fast::SocketContext::sendPuback (uint16_t packetIdentifier)
Definition at line 62 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send PUBACK";
        LOG(DEBUG) << "===========";
        send(iot::mqtt_fast::packets::Puback(packetIdentifier));
    }
References iot::mqtt_fast::packets::Puback::Puback(), and send().
sendPubcomp()
void iot::mqtt_fast::SocketContext::sendPubcomp (uint16_t packetIdentifier)
Definition at line 83 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send PUBCOMP";
        LOG(DEBUG) << "============";
        send(iot::mqtt_fast::packets::Pubcomp(packetIdentifier));
    }
References iot::mqtt_fast::packets::Pubcomp::Pubcomp(), and send().
sendPublish()
void iot::mqtt_fast::SocketContext::sendPublish (const std::string & topic, const std::string & message, bool dup = false, uint8_t qoS = 0, bool retain = false)
Definition at line 55 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send PUBLISH";
        LOG(DEBUG) << "============";
        send(iot::mqtt_fast::packets::Publish(qoS == 0 ? 0 : getPacketIdentifier(), topic, message, dup, qoS, retain));
    }
References getPacketIdentifier(), iot::mqtt_fast::packets::Publish::Publish(), and send().
sendPubrec()
void iot::mqtt_fast::SocketContext::sendPubrec (uint16_t packetIdentifier)
Definition at line 69 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send PUBREC";
        LOG(DEBUG) << "===========";
        send(iot::mqtt_fast::packets::Pubrec(packetIdentifier));
    }
References iot::mqtt_fast::packets::Pubrec::Pubrec(), and send().
sendPubrel()
void iot::mqtt_fast::SocketContext::sendPubrel (uint16_t packetIdentifier)
Definition at line 76 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send PUBREL";
        LOG(DEBUG) << "===========";
        send(iot::mqtt_fast::packets::Pubrel(packetIdentifier));
    }
References iot::mqtt_fast::packets::Pubrel::Pubrel(), and send().
sendSuback()
void iot::mqtt_fast::SocketContext::sendSuback (uint16_t packetIdentifier, std::list< uint8_t > & returnCodes)
Definition at line 97 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send SUBACK";
        LOG(DEBUG) << "===========";
        send(iot::mqtt_fast::packets::Suback(packetIdentifier, returnCodes));
    }
References send(), and iot::mqtt_fast::packets::Suback::Suback().
sendSubscribe()
void iot::mqtt_fast::SocketContext::sendSubscribe (std::list< Topic > & topics)
Definition at line 90 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send SUBSCRIBE";
        LOG(DEBUG) << "==============";
        send(iot::mqtt_fast::packets::Subscribe(getPacketIdentifier(), topics));
    }
References getPacketIdentifier(), send(), and iot::mqtt_fast::packets::Subscribe::Subscribe().
sendToPeer() [1/3]
void core::socket::stream::SocketContext::sendToPeer (const char * junk, std::size_t junkLen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 41 of file SocketContext.cpp.
{
        socketConnection->sendToPeer(junk, junkLen);
    }
References core::socket::stream::SocketConnection::sendToPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::Request::enqueue(), iot::mqtt::SocketContext::send(), send(), and web::http::server::RequestContextBase::sendToPeer().
sendToPeer() [2/3]
virtual void core::socket::SocketContext::sendToPeer (const char * junk, std::size_t junkLen) const virtual inherited
Implements core::socket::SocketContext.
sendToPeer() [3/3]
void core::socket::SocketContext::sendToPeer (const std::string & data) const inherited
Definition at line 51 of file SocketContext.cpp.
{
        sendToPeer(data.data(), data.length());
    }
sendUnsuback()
void iot::mqtt_fast::SocketContext::sendUnsuback (uint16_t packetIdentifier)
Definition at line 111 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send UNSUBACK";
        LOG(DEBUG) << "=============";
        send(iot::mqtt_fast::packets::Unsuback(packetIdentifier));
    }
References send(), and iot::mqtt_fast::packets::Unsuback::Unsuback().
sendUnsubscribe()
void iot::mqtt_fast::SocketContext::sendUnsubscribe (std::list< std::string > & topics)
Definition at line 104 of file SocketContext.cpp.
{
        LOG(DEBUG) << "Send UNSUBSCRIBE";
        LOG(DEBUG) << "================";
        send(iot::mqtt_fast::packets::Unsubscribe(getPacketIdentifier(), topics));
    }
References getPacketIdentifier(), send(), and iot::mqtt_fast::packets::Unsubscribe::Unsubscribe().
setTimeout()
void core::socket::stream::SocketContext::setTimeout (const utils::Timeval & timeout) final virtual inherited
Implements core::socket::SocketContext.
Definition at line 49 of file SocketContext.cpp.
{
        socketConnection->setTimeout(timeout);
    }
References core::socket::stream::SocketConnection::setTimeout(), and core::socket::stream::SocketContext::socketConnection.
shutdown()
void core::socket::stream::SocketContext::shutdown (bool forceClose = false) inherited
Definition at line 65 of file SocketContext.cpp.
{
        shutdownRead();
        shutdownWrite(forceClose);
    }
References core::socket::stream::SocketContext::shutdownRead(), and core::socket::stream::SocketContext::shutdownWrite().
Referenced by iot::mqtt::SocketContext::end().
shutdownRead()
void core::socket::stream::SocketContext::shutdownRead () inherited
Definition at line 57 of file SocketContext.cpp.
{
        socketConnection->shutdownRead();
    }
References core::socket::stream::SocketConnection::shutdownRead(), and core::socket::stream::SocketContext::socketConnection.
Referenced by core::socket::stream::SocketContext::onWriteError(), and core::socket::stream::SocketContext::shutdown().
shutdownWrite()
void core::socket::stream::SocketContext::shutdownWrite (bool forceClose = false) inherited
Definition at line 61 of file SocketContext.cpp.
{
        socketConnection->shutdownWrite(forceClose);
    }
References core::socket::stream::SocketConnection::shutdownWrite(), and core::socket::stream::SocketContext::socketConnection.
Referenced by core::socket::stream::SocketContext::onReadError(), web::http::server::SocketContext< RequestT, ResponseT >::requestParsed(), web::http::server::SocketContext< RequestT, ResponseT >::sendToPeerCompleted(), and core::socket::stream::SocketContext::shutdown().
switchSocketContext()
SocketContext * core::socket::stream::SocketContext::switchSocketContext (core::socket::stream::SocketContextFactory * socketContextFactory) inherited
Definition at line 33 of file SocketContext.cpp.
{
        return socketConnection->switchSocketContext(socketContextFactory);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::switchSocketContext().
Referenced by web::http::server::RequestContextBase::switchSocketContext(), and web::http::client::Response::upgrade().
Member Data Documentation
_packetIdentifier
uint16_t iot::mqtt_fast::SocketContext::_packetIdentifier = 0 private
Definition at line 113 of file SocketContext.h.
Referenced by getPacketIdentifier().
controlPacketFactory
iot::mqtt_fast::ControlPacketFactory iot::mqtt_fast::SocketContext::controlPacketFactory private
Definition at line 111 of file SocketContext.h.
Referenced by onReceivedFromPeer(), and SocketContext().
socketConnection
core::socket::stream::SocketConnection* core::socket::stream::SocketContext::socketConnection private inherited
Definition at line 72 of file SocketContext.h.
Referenced by core::socket::stream::SocketContext::close(), core::socket::stream::SocketContext::getSocketConnection(), core::socket::stream::SocketContext::readFromPeer(), core::socket::stream::SocketContext::sendToPeer(), core::socket::stream::SocketContext::setTimeout(), core::socket::stream::SocketContext::shutdownRead(), core::socket::stream::SocketContext::shutdownWrite(), core::socket::stream::SocketContext::SocketContext(), and core::socket::stream::SocketContext::switchSocketContext().
The documentation for this class was generated from the following files:
iot/mqtt-fast/SocketContext.h
iot/mqtt-fast/SocketContext.cpp