snode.c: net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT > Class Template Reference
net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT > Class Template Reference
#include <SocketClient.h>
Public Member Functions
void connect (const std::string &btAddress, uint8_t channel, const std::function< void(const core::ProgressLog &)> &onError)
void connect (const std::string &btAddress, uint8_t channel, const std::string &bindBtAddress, const std::function< void(const core::ProgressLog &)> &onError)
void connect (const std::string &btAddress, uint8_t channel, uint8_t bindChannel, const std::function< void(const core::ProgressLog &)> &onError)
void connect (const std::string &btAddress, uint8_t channel, const std::string &bindBtAddress, uint8_t bindChannel, const std::function< void(const core::ProgressLog &)> &onError)
Public Member Functions inherited from core::socket::stream::SocketClient< SocketConnectorT< net::rc::stream::PhysicalClientSocket, ConfigSocketClientT >, SocketContextFactoryT >
SocketClient (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect)
SocketClient (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect)
SocketClient (const std::string &name)
SocketClient ()
SocketClient (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, SocketContextFactory *socketContextFactory)
SocketClient (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, SocketContextFactory *socketContextFactory)
SocketClient (const std::string &name, SocketContextFactory *socketContextFactory)
SocketClient (SocketContextFactory *socketContextFactory)
void connect (const std::function< void(const core::ProgressLog &)> &onError)
void connect (const SocketAddress &remoteAddress, const std::function< void(const core::ProgressLog &)> &onError)
void connect (const SocketAddress &remoteAddress, const SocketAddress &localAddress, const std::function< void(const core::ProgressLog &)> &onError)
void setOnConnect (const std::function< void(SocketConnection *)> &onConnect)
void setOnConnected (const std::function< void(SocketConnection *)> &onConnected)
void setOnDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
Public Member Functions inherited from core::socket::LogicalSocket< SocketConnectorT::Config >
LogicalSocket (const std::string &name)
LogicalSocket (const LogicalSocket &)=default
LogicalSocket (LogicalSocket &&)=default
LogicalSocket & operator= (const LogicalSocket &)=default
LogicalSocket & operator= (LogicalSocket &&)=default
virtual ~LogicalSocket ()
Config & getConfig () const
Private Types
using Super = core::socket::stream::SocketClient< SocketConnectorT< net::rc::stream::PhysicalClientSocket, ConfigSocketClientT >, SocketContextFactoryT >
Additional Inherited Members
Public Types inherited from core::socket::stream::SocketClient< SocketConnectorT< net::rc::stream::PhysicalClientSocket, ConfigSocketClientT >, SocketContextFactoryT >
using SocketConnection = typename SocketConnector::SocketConnection
using SocketAddress = typename SocketConnector::SocketAddress
Public Types inherited from core::socket::LogicalSocket< SocketConnectorT::Config >
using Config = SocketConnectorT::Config
Protected Attributes inherited from core::socket::stream::SocketClient< SocketConnectorT< net::rc::stream::PhysicalClientSocket, ConfigSocketClientT >, SocketContextFactoryT >
std::function< void(SocketConnection *)> onConnect
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
Protected Attributes inherited from core::socket::LogicalSocket< SocketConnectorT::Config >
std::shared_ptr< Config > config
Detailed Description
template<template< typename PhysicalClientSocket, typename ConfigSocketClientT > typename SocketConnectorT, typename ConfigSocketClientT, typename SocketContextFactoryT>
class net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >
Definition at line 38 of file SocketClient.h.
Member Typedef Documentation
Super
template<template< typename PhysicalClientSocket, typename ConfigSocketClientT > typename SocketConnectorT, typename ConfigSocketClientT , typename SocketContextFactoryT > using net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::Super = core::socket::stream::SocketClient<SocketConnectorT<net::rc::stream::PhysicalClientSocket, ConfigSocketClientT>, SocketContextFactoryT> private
Definition at line 42 of file SocketClient.h.
Member Function Documentation
connect() [1/4]
template<template< typename PhysicalClientSocket, typename ConfigSocketClientT > typename SocketConnectorT, typename ConfigSocketClientT , typename SocketContextFactoryT > void net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect (const std::string & btAddress, uint8_t channel, const std::function< void(const core::ProgressLog &)> & onError) inline
Definition at line 50 of file SocketClient.h.
{
            Super::getConfig().Remote::setBtAddress(btAddress).setChannel(channel);
            connect(SocketAddress(btAddress, channel), onError);
        }
References net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), and core::socket::LogicalSocket< SocketConnectorT::Config >::getConfig().
Referenced by net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), and net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect().
connect() [2/4]
template<template< typename PhysicalClientSocket, typename ConfigSocketClientT > typename SocketConnectorT, typename ConfigSocketClientT , typename SocketContextFactoryT > void net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect (const std::string & btAddress, uint8_t channel, const std::string & bindBtAddress, const std::function< void(const core::ProgressLog &)> & onError) inline
Definition at line 56 of file SocketClient.h.
{
            Super::getConfig().Remote::setBtAddress(btAddress).setChannel(channel);
            Super::getConfig().Local::setBtAddress(bindBtAddress);
            connect(onError);
        }
References net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), and core::socket::LogicalSocket< SocketConnectorT::Config >::getConfig().
connect() [3/4]
template<template< typename PhysicalClientSocket, typename ConfigSocketClientT > typename SocketConnectorT, typename ConfigSocketClientT , typename SocketContextFactoryT > void net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect (const std::string & btAddress, uint8_t channel, const std::string & bindBtAddress, uint8_t bindChannel, const std::function< void(const core::ProgressLog &)> & onError) inline
Definition at line 76 of file SocketClient.h.
{
            Super::getConfig().Remote::setBtAddress(btAddress).setChannel(channel);
            Super::getConfig().Local::setBtAddress(bindBtAddress).setChannel(bindChannel);
            connect(onError);
        }
References net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), and core::socket::LogicalSocket< SocketConnectorT::Config >::getConfig().
connect() [4/4]
template<template< typename PhysicalClientSocket, typename ConfigSocketClientT > typename SocketConnectorT, typename ConfigSocketClientT , typename SocketContextFactoryT > void net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect (const std::string & btAddress, uint8_t channel, uint8_t bindChannel, const std::function< void(const core::ProgressLog &)> & onError) inline
Definition at line 66 of file SocketClient.h.
{
            Super::getConfig().Remote::setBtAddress(btAddress).setChannel(channel);
            Super::getConfig().Local::setChannel(bindChannel);
            connect(onError);
        }
References net::rc::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT >::connect(), and core::socket::LogicalSocket< SocketConnectorT::Config >::getConfig().
The documentation for this class was generated from the following file:
net/rc/stream/SocketClient.h