SNode.C: core::pipe::Source Class Reference
core::pipe::Source Class Reference abstract
#include <Source.h>
Public Member Functions
Source ()=default
Source (Source &)=delete
Source (Source &&) noexcept=default
Source & operator= (Source &)=delete
Source & operator= (Source &&) noexcept=default
virtual ~Source ()
virtual bool isOpen ()=0
void pipe (Sink *sink, const std::function< void(int)> &callback)
void pipe (const std::shared_ptr< Sink > &sink, const std::function< void(int)> &callback)
virtual void start ()=0
virtual void suspend ()=0
virtual void resume ()=0
virtual void stop ()=0
Protected Member Functions
ssize_t send (const char *chunk, std::size_t chunkLen)
void eof ()
void error (int errnum)
Private Member Functions
void disconnect (const Sink *sink)
Private Attributes
Sink * sink = nullptr
Friends
class Sink
Detailed Description
Definition at line 60 of file Source.h.
Constructor & Destructor Documentation
Source() [1/3]
core::pipe::Source::Source () default
Source() [2/3]
core::pipe::Source::Source (Source &) delete
Source() [3/3]
core::pipe::Source::Source (Source &&) default noexcept
~Source()
core::pipe::Source::~Source () virtual
Definition at line 54 of file Source.cpp.
                    {
        if (sink != nullptr) {
            sink->disconnect(this);
        }
    }
References core::pipe::Sink::disconnect(), and sink.
Member Function Documentation
disconnect()
void core::pipe::Source::disconnect (const Sink * sink) private
Definition at line 81 of file Source.cpp.
{
        if (sink == this->sink) {
            this->sink->disconnect(this);
            this->sink = nullptr;
            stop();
        }
    }
References core::pipe::Sink::disconnect(), sink, and stop().
Referenced by core::pipe::Sink::stop(), and core::pipe::Sink::~Sink().
eof()
void core::pipe::Source::eof () protected
Definition at line 103 of file Source.cpp.
                     {
        if (sink != nullptr) {
            sink->streamEof();
        }
    }
References sink, and core::pipe::Sink::streamEof().
Referenced by core::file::FileReader::onEvent(), and core::file::FileReader::stop().
error()
void core::pipe::Source::error (int errnum) protected
Definition at line 109 of file Source.cpp.
{
        if (sink != nullptr) {
            sink->streamError(errnum);
        }
    }
References sink, and core::pipe::Sink::streamError().
Referenced by core::file::FileReader::onEvent().
isOpen()
virtual bool core::pipe::Source::isOpen () pure virtual
Implemented in core::file::FileReader.
Referenced by pipe().
operator=() [1/2]
Source & core::pipe::Source::operator= (Source &&) default noexcept
operator=() [2/2]
Source & core::pipe::Source::operator= (Source &) delete
pipe() [1/2]
void core::pipe::Source::pipe (const std::shared_ptr< Sink > & sink, const std::function< void(int)> & callback)
Definition at line 77 of file Source.cpp.
{
        pipe(sink.get(), callback);
    }
References pipe().
pipe() [2/2]
void core::pipe::Source::pipe (Sink * sink, const std::function< void(int)> & callback)
Definition at line 60 of file Source.cpp.
{
        if (sink != nullptr) {
            if (isOpen()) {
                callback(0);
                this->sink = sink;
                sink->pipe(this);
            } else {
                callback(errno);
                stop();
            }
        } else {
            callback(EINVAL);
            stop();
        }
    }
References isOpen(), core::pipe::Sink::pipe(), sink, and stop().
Referenced by web::http::client::Request::executeSendFile(), pipe(), and web::http::server::Response::sendFile().
resume()
virtual void core::pipe::Source::resume () pure virtual
Implemented in core::file::FileReader.
Referenced by core::socket::stream::SocketWriter::doWrite().
send()
ssize_t core::pipe::Source::send (const char * chunk, std::size_t chunkLen) protected
Definition at line 90 of file Source.cpp.
{
        ssize_t ret = static_cast<ssize_t>(chunkLen);
        if (sink != nullptr) {
            sink->streamData(chunk, chunkLen);
        } else {
            ret = -1;
            errno = EPIPE;
        }
        return ret;
    }
References sink, and core::pipe::Sink::streamData().
Referenced by core::file::FileReader::onEvent().
start()
virtual void core::pipe::Source::start () pure virtual
Implemented in core::file::FileReader.
Referenced by web::http::client::Request::onSourceConnect(), and web::http::server::Response::onSourceConnect().
stop()
virtual void core::pipe::Source::stop () pure virtual
Implemented in core::file::FileReader.
Referenced by disconnect(), web::http::client::Request::onSourceConnect(), web::http::server::Response::onSourceConnect(), and pipe().
suspend()
virtual void core::pipe::Source::suspend () pure virtual
Implemented in core::file::FileReader.
Referenced by core::socket::stream::SocketWriter::sendToPeer().
Friends And Related Symbol Documentation
Sink
friend class Sink friend
Definition at line 92 of file Source.h.
Member Data Documentation
sink
Sink* core::pipe::Source::sink = nullptr private
Definition at line 90 of file Source.h.
Referenced by disconnect(), eof(), error(), pipe(), send(), and ~Source().
The documentation for this class was generated from the following files:
core/pipe/Source.h
core/pipe/Source.cpp