SNode.C: web::http::server::SocketContext< RequestT, ResponseT > Class Template Reference
web::http::server::SocketContext< RequestT, ResponseT > Class Template Reference
#include <SocketContext.h>
Classes
class RequestContext
Public Member Functions
SocketContext (core::socket::stream::SocketConnection *socketConnection, const std::function< void(Request &, Response &)> &onRequestReady)
void sendToPeer (const char *junk, std::size_t junkLen) const final
virtual void sendToPeer (const char *junk, std::size_t junkLen) const=0
void sendToPeer (const std::string &data) const
std::size_t readFromPeer (char *junk, std::size_t junklen) const final
void setTimeout (const utils::Timeval &timeout) final
void shutdownRead ()
void shutdownWrite (bool forceClose=false)
void shutdown (bool forceClose=false)
void close () override
core::socket::stream::SocketConnection * getSocketConnection () const
core::socket::stream::SocketContext * switchSocketContext (core::socket::stream::SocketContextFactory *socketContextFactory)
Protected Member Functions
~SocketContext () override
virtual void onExit (int sig)
Private Types
using Super = web::http::SocketContext
using Request = RequestT
using Response = ResponseT
Private Member Functions
std::size_t onReceivedFromPeer () override
void sendToPeerCompleted () override
void onConnected () override
void onDisconnected () override
void requestParsed ()
void reset ()
void onWriteError (int errnum) override
void onReadError (int errnum) override
Private Attributes
std::function< void(Request &req, Response &res)> onRequestReady
RequestParser parser
std::list< RequestContext * > requestContexts
RequestContext * currentRequestContext = nullptr
bool requestInProgress = false
bool connectionTerminated = false
core::socket::stream::SocketConnection * socketConnection
Detailed Description
template<typename RequestT, typename ResponseT>
class web::http::server::SocketContext< RequestT, ResponseT >
Definition at line 42 of file SocketContext.h.
Member Typedef Documentation
Request
template<typename RequestT , typename ResponseT > using web::http::server::SocketContext< RequestT, ResponseT >::Request = RequestT private
Definition at line 46 of file SocketContext.h.
Response
template<typename RequestT , typename ResponseT > using web::http::server::SocketContext< RequestT, ResponseT >::Response = ResponseT private
Definition at line 47 of file SocketContext.h.
Super
template<typename RequestT , typename ResponseT > using web::http::server::SocketContext< RequestT, ResponseT >::Super = web::http::SocketContext private
Definition at line 44 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext()
template<typename Request , typename Response > web::http::server::SocketContext< Request, Response >::SocketContext (core::socket::stream::SocketConnection * socketConnection, const std::function< void(Request &, Response &)> & onRequestReady)
Definition at line 33 of file SocketContext.hpp.
        : Super(socketConnection)
        , onRequestReady(onRequestReady)
        , parser(
              this,
              [this](void) -> void {
                  requestContexts.emplace_back(new RequestContext(this));
              },
              [&requestContexts = this->requestContexts](const std::string& method,
                                                         const std::string& url,
                                                         const std::string& httpVersion,
                                                         int httpMajor,
                                                         int httpMinor,
                                                         std::map<std::string, std::string>& queries) -> void {
                  Request& request = requestContexts.back()->request;
                  request.method = method;
                  request.url = url;
                  request.queries = std::move(queries);
                  request.httpVersion = httpVersion;
                  request.httpMajor = httpMajor;
                  request.httpMinor = httpMinor;
              },
              [&requestContexts = this->requestContexts](const std::map<std::string, std::string>& header,
                                                         const std::map<std::string, std::string>& cookies) -> void {
                  Request& request = requestContexts.back()->request;
                  request.headers = std::move(header);
                  for (auto& [field, value] : request.headers) {
                      if (field == "connection" && httputils::ci_contains(value, "close")) {
                          request.connectionState = ConnectionState::Close;
                      } else if (field == "connection" && httputils::ci_contains(value, "keep-alive")) {
                          request.connectionState = ConnectionState::Keep;
                      }
                  }
                  request.cookies = std::move(cookies);
              },
              [&requestContexts = this->requestContexts](std::vector<uint8_t>& content) -> void {
                  Request& request = requestContexts.back()->request;
                  request.body = std::move(content);
              },
              [this]() -> void {
                  RequestContext* requestContext = requestContexts.back();
                  requestContext->ready = true;
                  requestParsed();
              },
              [this](int status, const std::string& reason) -> void {
                  RequestContext* requestContext = requestContexts.back();
                  requestContext->status = status;
                  requestContext->reason = std::move(reason);
                  requestContext->ready = true;
                  requestParsed();
              }) {
    }
References web::http::server::SocketContext< RequestT, ResponseT >::onRequestReady, web::http::server::SocketContext< RequestT, ResponseT >::parser, and web::http::server::SocketContext< RequestT, ResponseT >::requestContexts.
~SocketContext()
template<typename Request , typename Response > web::http::server::SocketContext< Request, Response >::~SocketContext () override protected virtual
Reimplemented from core::socket::stream::SocketContext.
Definition at line 97 of file SocketContext.hpp.
{
        for (RequestContext* requestContext : requestContexts) {
            delete requestContext;
        }
        if (currentRequestContext) {
            currentRequestContext->socketContextGone();
        }
    }
References web::http::server::SocketContext< RequestT, ResponseT >::currentRequestContext, and web::http::server::SocketContext< RequestT, ResponseT >::requestContexts.
Member Function Documentation
close()
void core::socket::stream::SocketContext::close () override virtual inherited
Implements core::socket::SocketContext.
Reimplemented in iot::mqtt::SocketContext.
Definition at line 53 of file SocketContext.cpp.
{
        socketConnection->close();
    }
References core::socket::stream::SocketConnection::close(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::server::RequestContextBase::close(), iot::mqtt::SocketContext::close(), web::http::client::Request::enqueue(), iot::mqtt_fast::SocketContext::onReceivedFromPeer(), web::http::client::Request::upgrade(), and web::http::client::Response::upgrade().
getSocketConnection()
SocketConnection * core::socket::stream::SocketContext::getSocketConnection () const inherited
Definition at line 37 of file SocketContext.cpp.
{
        return socketConnection;
    }
References core::socket::stream::SocketContext::socketConnection.
Referenced by iot::mqtt::SocketContext::getSocketConnection(), and web::http::client::SocketContext< RequestT, ResponseT >::onConnected().
onConnected()
template<typename Request , typename Response > void web::http::server::SocketContext< Request, Response >::onConnected () override private virtual
Implements core::socket::stream::SocketContext.
Definition at line 173 of file SocketContext.hpp.
{
        LOG(INFO) << "HTTP connected";
    }
onDisconnected()
template<typename Request , typename Response > void web::http::server::SocketContext< Request, Response >::onDisconnected () override private virtual
Implements core::socket::stream::SocketContext.
Definition at line 178 of file SocketContext.hpp.
{
        LOG(INFO) << "HTTP disconnected";
    }
onExit()
void core::socket::SocketContext::onExit (int sig) protected virtual inherited
Reimplemented in iot::mqtt::SocketContext, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Definition at line 48 of file SocketContext.cpp.
{
        LOG(TRACE) << "Applicationprotocol exit due to '" << strsignal(sig) << "' (SIG" << utils::system::sigabbrev_np(sig) << " = " << sig
                   << ")";
    }
References utils::system::sigabbrev_np().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onExit().
onReadError()
void core::socket::stream::SocketContext::onReadError (int errnum) override private virtual inherited
Reimplemented from core::socket::SocketContext.
Definition at line 75 of file SocketContext.cpp.
{
        Super::onReadError(errnum);
        shutdownWrite();
    }
References core::socket::SocketContext::onReadError(), and core::socket::stream::SocketContext::shutdownWrite().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReadError().
onReceivedFromPeer()
template<typename Request , typename Response > std::size_t web::http::server::SocketContext< Request, Response >::onReceivedFromPeer () override private virtual
Implements web::http::SocketContext.
Definition at line 108 of file SocketContext.hpp.
{
        return parser.parse();
    }
References web::http::Parser::parse(), and web::http::server::SocketContext< RequestT, ResponseT >::parser.
onWriteError()
void core::socket::stream::SocketContext::onWriteError (int errnum) override private virtual inherited
Reimplemented from core::socket::SocketContext.
Definition at line 70 of file SocketContext.cpp.
{
        Super::onWriteError(errnum);
        shutdownRead();
    }
References core::socket::SocketContext::onWriteError(), and core::socket::stream::SocketContext::shutdownRead().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onWriteError().
readFromPeer()
std::size_t core::socket::stream::SocketContext::readFromPeer (char * junk, std::size_t junklen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 45 of file SocketContext.cpp.
{
        return socketConnection->readFromPeer(junk, junklen);
    }
References core::socket::stream::SocketConnection::readFromPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::Parser::readContent(), web::http::Parser::readHeaderLine(), web::http::Parser::readStartLine(), and iot::mqtt::SocketContext::recv().
requestParsed()
template<typename Request , typename Response > void web::http::server::SocketContext< Request, Response >::requestParsed () private
Definition at line 113 of file SocketContext.hpp.
{
        if (!requestInProgress) {
            currentRequestContext = requestContexts.front();
            requestContexts.pop_front();
            requestInProgress = true;
            if (currentRequestContext->status == 0) {
                if (((currentRequestContext->request.connectionState == ConnectionState::Close) ||
                     (currentRequestContext->request.httpMajor == 0 && currentRequestContext->request.httpMinor == 9) ||
                     (currentRequestContext->request.httpMajor == 1 && currentRequestContext->request.httpMinor == 0 &&
                      currentRequestContext->request.connectionState != ConnectionState::Keep) ||
                     (currentRequestContext->request.httpMajor == 1 && currentRequestContext->request.httpMinor == 1 &&
                      currentRequestContext->request.connectionState == ConnectionState::Close))) {
                    currentRequestContext->response.set("Connection", "close");
                } else {
                    currentRequestContext->response.set("Connection", "keep-alive");
                }
                onRequestReady(currentRequestContext->request, currentRequestContext->response);
            } else {
                currentRequestContext->response.status(currentRequestContext->status).send(currentRequestContext->reason);
                reset();
                shutdownWrite(true);
                // close();
            }
        }
    }
References web::http::Close, web::http::server::SocketContext< RequestT, ResponseT >::currentRequestContext, web::http::Keep, web::http::server::SocketContext< RequestT, ResponseT >::onRequestReady, web::http::server::SocketContext< RequestT, ResponseT >::requestContexts, web::http::server::SocketContext< RequestT, ResponseT >::requestInProgress, web::http::server::SocketContext< RequestT, ResponseT >::reset(), and core::socket::stream::SocketContext::shutdownWrite().
Referenced by web::http::server::SocketContext< RequestT, ResponseT >::sendToPeerCompleted().
reset()
template<typename Request , typename Response > void web::http::server::SocketContext< Request, Response >::reset () private
Definition at line 166 of file SocketContext.hpp.
{
        requestInProgress = false;
        delete currentRequestContext;
        currentRequestContext = nullptr;
    }
References web::http::server::SocketContext< RequestT, ResponseT >::currentRequestContext, and web::http::server::SocketContext< RequestT, ResponseT >::requestInProgress.
Referenced by web::http::server::SocketContext< RequestT, ResponseT >::requestParsed(), and web::http::server::SocketContext< RequestT, ResponseT >::sendToPeerCompleted().
sendToPeer() [1/3]
void core::socket::stream::SocketContext::sendToPeer (const char * junk, std::size_t junkLen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 41 of file SocketContext.cpp.
{
        socketConnection->sendToPeer(junk, junkLen);
    }
References core::socket::stream::SocketConnection::sendToPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::Request::enqueue(), iot::mqtt::SocketContext::send(), iot::mqtt_fast::SocketContext::send(), and web::http::server::RequestContextBase::sendToPeer().
sendToPeer() [2/3]
virtual void core::socket::SocketContext::sendToPeer (const char * junk, std::size_t junkLen) const virtual inherited
Implements core::socket::SocketContext.
sendToPeer() [3/3]
void core::socket::SocketContext::sendToPeer (const std::string & data) const inherited
Definition at line 51 of file SocketContext.cpp.
{
        sendToPeer(data.data(), data.length());
    }
sendToPeerCompleted()
template<typename Request , typename Response > void web::http::server::SocketContext< Request, Response >::sendToPeerCompleted () override private virtual
Implements web::http::SocketContext.
Definition at line 142 of file SocketContext.hpp.
{
        // if 0.9 => terminate
        // if 1.0 && (request != Keep || contentLength = -1) => terminate
        // if 1.1 && (request == Close || contentLength = -1) => terminate
        // if (request == Close) => terminate
        if ((currentRequestContext->request.httpMajor == 0 && currentRequestContext->request.httpMinor == 9) ||
            (currentRequestContext->request.httpMajor == 1 && currentRequestContext->request.httpMinor == 0 &&
             currentRequestContext->request.connectionState != ConnectionState::Keep) ||
            (currentRequestContext->request.httpMajor == 1 && currentRequestContext->request.httpMinor == 1 &&
             currentRequestContext->request.connectionState == ConnectionState::Close) ||
            (currentRequestContext->response.connectionState == ConnectionState::Close)) {
            reset();
            shutdownWrite();
        } else {
            reset();
            if (!requestContexts.empty() && requestContexts.front()->ready) {
                requestParsed();
            }
        }
    }
References web::http::Close, web::http::server::SocketContext< RequestT, ResponseT >::currentRequestContext, web::http::Keep, web::http::server::SocketContext< RequestT, ResponseT >::requestContexts, web::http::server::SocketContext< RequestT, ResponseT >::requestParsed(), web::http::server::SocketContext< RequestT, ResponseT >::reset(), and core::socket::stream::SocketContext::shutdownWrite().
setTimeout()
void core::socket::stream::SocketContext::setTimeout (const utils::Timeval & timeout) final virtual inherited
Implements core::socket::SocketContext.
Definition at line 49 of file SocketContext.cpp.
{
        socketConnection->setTimeout(timeout);
    }
References core::socket::stream::SocketConnection::setTimeout(), and core::socket::stream::SocketContext::socketConnection.
shutdown()
void core::socket::stream::SocketContext::shutdown (bool forceClose = false) inherited
Definition at line 65 of file SocketContext.cpp.
{
        shutdownRead();
        shutdownWrite(forceClose);
    }
References core::socket::stream::SocketContext::shutdownRead(), and core::socket::stream::SocketContext::shutdownWrite().
Referenced by iot::mqtt::SocketContext::end().
shutdownRead()
void core::socket::stream::SocketContext::shutdownRead () inherited
Definition at line 57 of file SocketContext.cpp.
{
        socketConnection->shutdownRead();
    }
References core::socket::stream::SocketConnection::shutdownRead(), and core::socket::stream::SocketContext::socketConnection.
Referenced by core::socket::stream::SocketContext::onWriteError(), and core::socket::stream::SocketContext::shutdown().
shutdownWrite()
void core::socket::stream::SocketContext::shutdownWrite (bool forceClose = false) inherited
Definition at line 61 of file SocketContext.cpp.
{
        socketConnection->shutdownWrite(forceClose);
    }
References core::socket::stream::SocketConnection::shutdownWrite(), and core::socket::stream::SocketContext::socketConnection.
Referenced by core::socket::stream::SocketContext::onReadError(), web::http::server::SocketContext< RequestT, ResponseT >::requestParsed(), web::http::server::SocketContext< RequestT, ResponseT >::sendToPeerCompleted(), and core::socket::stream::SocketContext::shutdown().
switchSocketContext()
SocketContext * core::socket::stream::SocketContext::switchSocketContext (core::socket::stream::SocketContextFactory * socketContextFactory) inherited
Definition at line 33 of file SocketContext.cpp.
{
        return socketConnection->switchSocketContext(socketContextFactory);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::switchSocketContext().
Referenced by web::http::server::RequestContextBase::switchSocketContext(), and web::http::client::Response::upgrade().
Member Data Documentation
connectionTerminated
template<typename RequestT , typename ResponseT > bool web::http::server::SocketContext< RequestT, ResponseT >::connectionTerminated = false private
Definition at line 94 of file SocketContext.h.
currentRequestContext
template<typename RequestT , typename ResponseT > RequestContext* web::http::server::SocketContext< RequestT, ResponseT >::currentRequestContext = nullptr private
Definition at line 91 of file SocketContext.h.
Referenced by web::http::server::SocketContext< RequestT, ResponseT >::requestParsed(), web::http::server::SocketContext< RequestT, ResponseT >::reset(), web::http::server::SocketContext< RequestT, ResponseT >::sendToPeerCompleted(), and web::http::server::SocketContext< RequestT, ResponseT >::~SocketContext().
onRequestReady
template<typename RequestT , typename ResponseT > std::function<void(Request& req, Response& res)> web::http::server::SocketContext< RequestT, ResponseT >::onRequestReady private
Definition at line 86 of file SocketContext.h.
Referenced by web::http::server::SocketContext< RequestT, ResponseT >::requestParsed(), and web::http::server::SocketContext< RequestT, ResponseT >::SocketContext().
parser
template<typename RequestT , typename ResponseT > RequestParser web::http::server::SocketContext< RequestT, ResponseT >::parser private
Definition at line 88 of file SocketContext.h.
Referenced by web::http::server::SocketContext< RequestT, ResponseT >::onReceivedFromPeer(), and web::http::server::SocketContext< RequestT, ResponseT >::SocketContext().
requestContexts
template<typename RequestT , typename ResponseT > std::list<RequestContext*> web::http::server::SocketContext< RequestT, ResponseT >::requestContexts private
Definition at line 90 of file SocketContext.h.
Referenced by web::http::server::SocketContext< RequestT, ResponseT >::requestParsed(), web::http::server::SocketContext< RequestT, ResponseT >::sendToPeerCompleted(), web::http::server::SocketContext< RequestT, ResponseT >::SocketContext(), and web::http::server::SocketContext< RequestT, ResponseT >::~SocketContext().
requestInProgress
template<typename RequestT , typename ResponseT > bool web::http::server::SocketContext< RequestT, ResponseT >::requestInProgress = false private
Definition at line 93 of file SocketContext.h.
Referenced by web::http::server::SocketContext< RequestT, ResponseT >::requestParsed(), and web::http::server::SocketContext< RequestT, ResponseT >::reset().
socketConnection
core::socket::stream::SocketConnection* core::socket::stream::SocketContext::socketConnection private inherited
Definition at line 72 of file SocketContext.h.
Referenced by core::socket::stream::SocketContext::close(), core::socket::stream::SocketContext::getSocketConnection(), core::socket::stream::SocketContext::readFromPeer(), core::socket::stream::SocketContext::sendToPeer(), core::socket::stream::SocketContext::setTimeout(), core::socket::stream::SocketContext::shutdownRead(), core::socket::stream::SocketContext::shutdownWrite(), core::socket::stream::SocketContext::SocketContext(), and core::socket::stream::SocketContext::switchSocketContext().
The documentation for this class was generated from the following files:
web/http/server/SocketContext.h
web/http/server/SocketContext.hpp