SNode.C: iot::mqtt::MqttContext Class Reference
iot::mqtt::MqttContext Class Reference abstract
#include <MqttContext.h>
Public Member Functions
MqttContext (Mqtt *mqtt)
MqttContext (const MqttContext &)=default
MqttContext & operator= (const MqttContext &)=default
virtual ~MqttContext ()
virtual std::size_t recv (char *chunk, std::size_t chunklen)=0
virtual void send (const char *chunk, std::size_t chunklen)=0
virtual core::socket::stream::SocketConnection * getSocketConnection () const =0
virtual void end (bool fatal=false)=0
virtual void close ()=0
void onConnected ()
std::size_t onReceivedFromPeer ()
void onDisconnected ()
bool onSignal (int sig)
Protected Attributes
Mqtt * mqtt
Detailed Description
Definition at line 61 of file MqttContext.h.
Constructor & Destructor Documentation
MqttContext() [1/2]
iot::mqtt::MqttContext::MqttContext (Mqtt * mqtt) explicit
Definition at line 52 of file MqttContext.cpp.
        : mqtt(mqtt) {
        mqtt->setMqttContext(this);
    }
References mqtt, and iot::mqtt::Mqtt::setMqttContext().
Referenced by iot::mqtt::SocketContext::SocketContext().
MqttContext() [2/2]
iot::mqtt::MqttContext::MqttContext (const MqttContext &) default
~MqttContext()
iot::mqtt::MqttContext::~MqttContext () virtual
Definition at line 57 of file MqttContext.cpp.
{
        delete mqtt;
    }
References mqtt.
Member Function Documentation
close()
virtual void iot::mqtt::MqttContext::close () pure virtual
Implemented in iot::mqtt::SocketContext, and iot::mqtt::SubProtocol< WSSubProtocolRoleT >.
end()
virtual void iot::mqtt::MqttContext::end (bool fatal = false) pure virtual
Implemented in iot::mqtt::SocketContext, and iot::mqtt::SubProtocol< WSSubProtocolRoleT >.
getSocketConnection()
virtual core::socket::stream::SocketConnection * iot::mqtt::MqttContext::getSocketConnection () const pure virtual
Implemented in iot::mqtt::SocketContext, and iot::mqtt::SubProtocol< WSSubProtocolRoleT >.
onConnected()
void iot::mqtt::MqttContext::onConnected ()
Definition at line 61 of file MqttContext.cpp.
{
        mqtt->onConnected();
    }
References mqtt, and iot::mqtt::Mqtt::onConnected().
Referenced by iot::mqtt::SocketContext::onConnected().
onDisconnected()
void iot::mqtt::MqttContext::onDisconnected ()
Definition at line 69 of file MqttContext.cpp.
{
        mqtt->onDisconnected();
    }
References mqtt, and iot::mqtt::Mqtt::onDisconnected().
Referenced by iot::mqtt::SocketContext::onDisconnected().
onReceivedFromPeer()
std::size_t iot::mqtt::MqttContext::onReceivedFromPeer ()
Definition at line 65 of file MqttContext.cpp.
{
        return mqtt->onReceivedFromPeer();
    }
References mqtt, and iot::mqtt::Mqtt::onReceivedFromPeer().
Referenced by iot::mqtt::SocketContext::onReceivedFromPeer().
onSignal()
bool iot::mqtt::MqttContext::onSignal (int sig)
Definition at line 73 of file MqttContext.cpp.
{
        return mqtt->onSignal(sig);
    }
References mqtt, and iot::mqtt::Mqtt::onSignal().
Referenced by iot::mqtt::SocketContext::onSignal().
operator=()
MqttContext & iot::mqtt::MqttContext::operator= (const MqttContext &) default
recv()
virtual std::size_t iot::mqtt::MqttContext::recv (char * chunk, std::size_t chunklen) pure virtual
Implemented in iot::mqtt::SocketContext, and iot::mqtt::SubProtocol< WSSubProtocolRoleT >.
send()
virtual void iot::mqtt::MqttContext::send (const char * chunk, std::size_t chunklen) pure virtual
Implemented in iot::mqtt::SocketContext, and iot::mqtt::SubProtocol< WSSubProtocolRoleT >.
Member Data Documentation
mqtt
Mqtt* iot::mqtt::MqttContext::mqtt protected
Definition at line 84 of file MqttContext.h.
Referenced by MqttContext(), onConnected(), onDisconnected(), onReceivedFromPeer(), onSignal(), and ~MqttContext().
The documentation for this class was generated from the following files:
iot/mqtt/MqttContext.h
iot/mqtt/MqttContext.cpp