SNode.C: core::poll::DescriptorEventPublisher Class Reference
core::poll::DescriptorEventPublisher Class Reference
#include <DescriptorEventPublisher.h>
Public Member Functions
DescriptorEventPublisher (const std::string &name, core::poll::PollFdsManager &pollFds, short events, short revents)
void enable (DescriptorEventReceiver *descriptorEventReceiver)
void disable (DescriptorEventReceiver *descriptorEventReceiver)
void disable ()
void suspend (DescriptorEventReceiver *descriptorEventReceiver)
void resume (DescriptorEventReceiver *descriptorEventReceiver)
void checkTimedOutEvents (const utils::Timeval &currentTime)
void releaseDisabledEvents (const utils::Timeval &currentTime)
int getObservedEventReceiverCount () const
int maxFd () const
utils::Timeval getNextTimeout (const utils::Timeval &currentTime) const
void signal (int sigNum)
const std::string & getName () const
Protected Attributes
unsigned long eventCounter = 0
std::map< int, std::list< DescriptorEventReceiver * > > observedEventReceivers
Private Member Functions
void muxAdd (core::DescriptorEventReceiver *eventReceiver) override
void muxDel (int fd) override
void muxOn (core::DescriptorEventReceiver *eventReceiver) override
void muxOff (core::DescriptorEventReceiver *eventReceiver) override
void spanActiveEvents () override
Private Attributes
core::poll::PollFdsManager & pollFds
short events
short revents
bool observedEventReceiversDirty = false
std::string name
Detailed Description
Definition at line 41 of file DescriptorEventPublisher.h.
Constructor & Destructor Documentation
DescriptorEventPublisher()
core::poll::DescriptorEventPublisher::DescriptorEventPublisher (const std::string & name, core::poll::PollFdsManager & pollFds, short events, short revents)
Definition at line 35 of file DescriptorEventPublisher.cpp.
        : core::DescriptorEventPublisher(name)
        , pollFds(pollFds)
        , events(events)
        , revents(revents) {
    }
References core::DescriptorEventPublisher::DescriptorEventPublisher(), events, pollFds, and revents.
Member Function Documentation
checkTimedOutEvents()
void core::DescriptorEventPublisher::checkTimedOutEvents (const utils::Timeval & currentTime) inherited
Definition at line 65 of file DescriptorEventPublisher.cpp.
{
        for (auto& [fd, eventReceivers] : observedEventReceivers) {
            eventReceivers.front()->checkTimeout(currentTime);
        }
    }
References core::DescriptorEventReceiver::checkTimeout(), and core::DescriptorEventPublisher::observedEventReceivers.
Referenced by core::EventMultiplexer::checkTimedOutEvents().
disable() [1/2]
void core::DescriptorEventPublisher::disable () inherited
Definition at line 139 of file DescriptorEventPublisher.cpp.
{
        for (auto& [fd, eventReceivers] : observedEventReceivers) {
            for (DescriptorEventReceiver* eventReceiver : eventReceivers) {
                eventReceiver->disable();
            }
        }
    }
References core::DescriptorEventReceiver::disable(), and core::DescriptorEventPublisher::observedEventReceivers.
Referenced by core::EventMultiplexer::terminate().
disable() [2/2]
void core::DescriptorEventPublisher::disable (DescriptorEventReceiver * descriptorEventReceiver) inherited
Definition at line 53 of file DescriptorEventPublisher.cpp.
{
        observedEventReceiversDirty = true;
    }
References core::DescriptorEventPublisher::observedEventReceiversDirty.
Referenced by core::DescriptorEventReceiver::disable().
enable()
void core::DescriptorEventPublisher::enable (DescriptorEventReceiver * descriptorEventReceiver) inherited
Definition at line 43 of file DescriptorEventPublisher.cpp.
{
        const int fd = descriptorEventReceiver->getRegisteredFd();
        descriptorEventReceiver->setEnabled(utils::Timeval::currentTime());
        observedEventReceivers[fd].push_front(descriptorEventReceiver);
        muxAdd(descriptorEventReceiver);
        if (descriptorEventReceiver->isSuspended()) {
            muxOff(descriptorEventReceiver);
        }
    }
References utils::Timeval::currentTime(), core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventPublisher::muxAdd(), core::DescriptorEventPublisher::muxOff(), core::DescriptorEventPublisher::observedEventReceivers, and core::DescriptorEventReceiver::setEnabled().
Referenced by core::DescriptorEventReceiver::enable().
getName()
const std::string & core::DescriptorEventPublisher::getName () const inherited
Definition at line 147 of file DescriptorEventPublisher.cpp.
{
        return name;
    }
References core::DescriptorEventPublisher::name.
getNextTimeout()
utils::Timeval core::DescriptorEventPublisher::getNextTimeout (const utils::Timeval & currentTime) const inherited
Definition at line 117 of file DescriptorEventPublisher.cpp.
{
        utils::Timeval nextTimeout = DescriptorEventReceiver::TIMEOUT::MAX;
        if (!observedEventReceiversDirty) {
            for (const auto& [fd, eventReceivers] : observedEventReceivers) {
                nextTimeout = std::min(eventReceivers.front()->getTimeout(currentTime), nextTimeout);
            }
        } else {
            nextTimeout = 0;
        }
        return nextTimeout;
    }
References core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::TIMEOUT::MAX, core::DescriptorEventPublisher::observedEventReceivers, core::DescriptorEventPublisher::observedEventReceiversDirty, and utils::Timeval::operator=().
Referenced by core::EventMultiplexer::getNextTimeout().
getObservedEventReceiverCount()
int core::DescriptorEventPublisher::getObservedEventReceiverCount () const inherited
Definition at line 103 of file DescriptorEventPublisher.cpp.
{
        return static_cast<int>(observedEventReceivers.size());
    }
References core::DescriptorEventPublisher::observedEventReceivers.
Referenced by core::EventMultiplexer::observedEventReceiverCount().
maxFd()
int core::DescriptorEventPublisher::maxFd () const inherited
Definition at line 107 of file DescriptorEventPublisher.cpp.
{
        int maxFd = -1;
        if (!observedEventReceivers.empty()) {
            maxFd = observedEventReceivers.rbegin()->first;
        }
        return maxFd;
    }
References core::DescriptorEventPublisher::observedEventReceivers.
Referenced by core::EventMultiplexer::maxFd().
muxAdd()
void core::poll::DescriptorEventPublisher::muxAdd (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 42 of file DescriptorEventPublisher.cpp.
{
        pollFds.muxAdd(eventReceiver, events);
    }
References events, core::poll::PollFdsManager::muxAdd(), and pollFds.
muxDel()
void core::poll::DescriptorEventPublisher::muxDel (int fd) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 46 of file DescriptorEventPublisher.cpp.
{
        pollFds.muxDel(fd, events);
    }
References events, core::poll::PollFdsManager::muxDel(), and pollFds.
muxOff()
void core::poll::DescriptorEventPublisher::muxOff (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 54 of file DescriptorEventPublisher.cpp.
{
        pollFds.muxOff(eventReceiver, events);
    }
References events, core::poll::PollFdsManager::muxOff(), and pollFds.
muxOn()
void core::poll::DescriptorEventPublisher::muxOn (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 50 of file DescriptorEventPublisher.cpp.
{
        pollFds.muxOn(eventReceiver, events);
    }
References events, core::poll::PollFdsManager::muxOn(), and pollFds.
releaseDisabledEvents()
void core::DescriptorEventPublisher::releaseDisabledEvents (const utils::Timeval & currentTime) inherited
Definition at line 71 of file DescriptorEventPublisher.cpp.
{
        if (observedEventReceiversDirty) {
            observedEventReceiversDirty = false;
            for (auto& [fd, observedEventReceiverList] : observedEventReceivers) {
                if (std::erase_if(observedEventReceiverList, [](DescriptorEventReceiver* descriptorEventReceiver) -> bool {
                        const bool isDisabled = !descriptorEventReceiver->isEnabled();
                        if (isDisabled) {
                            descriptorEventReceiver->setDisabled();
                        }
                        return isDisabled;
                    }) > 0) {
                    if (observedEventReceiverList.empty()) {
                        muxDel(fd);
                    } else {
                        DescriptorEventReceiver* activeDescriptorEventReceiver = observedEventReceiverList.front();
                        activeDescriptorEventReceiver->triggered(currentTime);
                        if (!activeDescriptorEventReceiver->isSuspended()) {
                            muxOn(activeDescriptorEventReceiver);
                        } else {
                            muxOff(activeDescriptorEventReceiver);
                        }
                    }
                }
            }
            std::erase_if(observedEventReceivers, [](const auto& observedEventReceiversEntry) -> bool {
                return observedEventReceiversEntry.second.empty();
            });
        }
    }
References core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventPublisher::muxDel(), core::DescriptorEventPublisher::muxOff(), core::DescriptorEventPublisher::muxOn(), core::DescriptorEventPublisher::observedEventReceivers, core::DescriptorEventPublisher::observedEventReceiversDirty, and core::DescriptorEventReceiver::triggered().
Referenced by core::EventMultiplexer::releaseExpiredResources().
resume()
void core::DescriptorEventPublisher::resume (DescriptorEventReceiver * descriptorEventReceiver) inherited
Definition at line 61 of file DescriptorEventPublisher.cpp.
{
        muxOn(descriptorEventReceiver);
    }
References core::DescriptorEventPublisher::muxOn().
Referenced by core::DescriptorEventReceiver::resume().
signal()
void core::DescriptorEventPublisher::signal (int sigNum) inherited
Definition at line 131 of file DescriptorEventPublisher.cpp.
{
        for (auto& [fd, eventReceivers] : observedEventReceivers) {
            for (DescriptorEventReceiver* eventReceiver : eventReceivers) {
                eventReceiver->onSignal(sigNum);
            }
        }
    }
References core::DescriptorEventPublisher::observedEventReceivers, and core::DescriptorEventReceiver::onSignal().
Referenced by core::EventMultiplexer::signal().
spanActiveEvents()
void core::poll::DescriptorEventPublisher::spanActiveEvents () override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 58 of file DescriptorEventPublisher.cpp.
{
        pollfd* pollfds = pollFds.getEvents();
        const std::unordered_map<int, PollFdsManager::PollFdIndex>& pollFdsIndices = pollFds.getPollFdIndices();
        for (auto& [fd, eventReceivers] : observedEventReceivers) {
            const pollfd& pollFd = pollfds[pollFdsIndices.find(fd)->second.index];
            if ((pollFd.events & events) != 0 && (pollFd.revents & revents) != 0) {
                core::DescriptorEventReceiver* eventReceiver = eventReceivers.front();
                eventCounter++;
                eventReceiver->span();
            }
        }
    }
References core::DescriptorEventPublisher::eventCounter, events, core::poll::PollFdsManager::getPollFdIndices(), core::DescriptorEventPublisher::observedEventReceivers, pollFds, revents, and core::EventReceiver::span().
suspend()
void core::DescriptorEventPublisher::suspend (DescriptorEventReceiver * descriptorEventReceiver) inherited
Definition at line 57 of file DescriptorEventPublisher.cpp.
{
        muxOff(descriptorEventReceiver);
    }
References core::DescriptorEventPublisher::muxOff().
Referenced by core::DescriptorEventReceiver::suspend().
Member Data Documentation
eventCounter
unsigned long core::DescriptorEventPublisher::eventCounter = 0 protected inherited
Definition at line 79 of file DescriptorEventPublisher.h.
Referenced by core::epoll::DescriptorEventPublisher::spanActiveEvents(), spanActiveEvents(), and core::select::DescriptorEventPublisher::spanActiveEvents().
events
short core::poll::DescriptorEventPublisher::events private
Definition at line 54 of file DescriptorEventPublisher.h.
Referenced by DescriptorEventPublisher(), muxAdd(), muxDel(), muxOff(), muxOn(), and spanActiveEvents().
name
std::string core::DescriptorEventPublisher::name private inherited
Definition at line 86 of file DescriptorEventPublisher.h.
Referenced by core::DescriptorEventPublisher::DescriptorEventPublisher(), and core::DescriptorEventPublisher::getName().
observedEventReceivers
std::map<int, std::list<DescriptorEventReceiver*> > core::DescriptorEventPublisher::observedEventReceivers protected inherited
Definition at line 81 of file DescriptorEventPublisher.h.
Referenced by core::DescriptorEventPublisher::checkTimedOutEvents(), core::DescriptorEventPublisher::disable(), core::DescriptorEventPublisher::enable(), core::DescriptorEventPublisher::getNextTimeout(), core::DescriptorEventPublisher::getObservedEventReceiverCount(), core::DescriptorEventPublisher::maxFd(), core::DescriptorEventPublisher::releaseDisabledEvents(), core::DescriptorEventPublisher::signal(), spanActiveEvents(), and core::select::DescriptorEventPublisher::spanActiveEvents().
observedEventReceiversDirty
bool core::DescriptorEventPublisher::observedEventReceiversDirty = false private inherited
Definition at line 84 of file DescriptorEventPublisher.h.
Referenced by core::DescriptorEventPublisher::disable(), core::DescriptorEventPublisher::getNextTimeout(), and core::DescriptorEventPublisher::releaseDisabledEvents().
pollFds
core::poll::PollFdsManager& core::poll::DescriptorEventPublisher::pollFds private
Definition at line 53 of file DescriptorEventPublisher.h.
Referenced by DescriptorEventPublisher(), muxAdd(), muxDel(), muxOff(), muxOn(), and spanActiveEvents().
revents
short core::poll::DescriptorEventPublisher::revents private
Definition at line 55 of file DescriptorEventPublisher.h.
Referenced by DescriptorEventPublisher(), and spanActiveEvents().
The documentation for this class was generated from the following files:
core/multiplexer/poll/DescriptorEventPublisher.h
core/multiplexer/poll/DescriptorEventPublisher.cpp