SNode.C: core::Event Class Reference
core::Event Class Reference
#include <Event.h>
Public Member Functions
Event (EventReceiver *eventReceiver, const std::string &name)
~Event ()
void span ()
void relax ()
const std::string & getName () const
void dispatch (const utils::Timeval &currentTime)
EventReceiver * getEventReceiver () const
Private Attributes
std::string name
EventReceiver * eventReceiver
EventMultiplexer & eventMultiplexer
bool published = false
Detailed Description
Definition at line 40 of file Event.h.
Constructor & Destructor Documentation
Event()
core::Event::Event (EventReceiver * eventReceiver, const std::string & name) explicit
Definition at line 31 of file Event.cpp.
        : name(name)
        , eventReceiver(eventReceiver)
        , eventMultiplexer(core::EventLoop::instance().getEventMultiplexer()) {
    }
References eventMultiplexer, eventReceiver, core::EventLoop::getEventMultiplexer(), core::EventLoop::instance(), and name.
Referenced by core::EventReceiver::EventReceiver().
~Event()
core::Event::~Event ()
Definition at line 37 of file Event.cpp.
                  {
        relax();
    }
References relax().
Member Function Documentation
dispatch()
void core::Event::dispatch (const utils::Timeval & currentTime)
Definition at line 59 of file Event.cpp.
{
        published = false;
        eventReceiver->onEvent(currentTime);
    }
References eventReceiver, core::EventReceiver::onEvent(), and published.
Referenced by core::EventMultiplexer::EventQueue::execute().
getEventReceiver()
EventReceiver * core::Event::getEventReceiver () const
Definition at line 64 of file Event.cpp.
{
        return eventReceiver;
    }
References eventReceiver.
Referenced by core::EventMultiplexer::EventQueue::clear().
getName()
const std::string & core::Event::getName () const
Definition at line 55 of file Event.cpp.
{
        return name;
    }
References name.
Referenced by core::EventReceiver::getName().
relax()
void core::Event::relax ()
Definition at line 48 of file Event.cpp.
                      {
        if (published) {
            published = false;
            eventMultiplexer.relax(this);
        }
    }
References eventMultiplexer, published, and core::EventMultiplexer::relax().
Referenced by core::EventReceiver::relax(), and ~Event().
span()
void core::Event::span ()
Definition at line 41 of file Event.cpp.
                     {
        if (!published) {
            published = true;
            eventMultiplexer.span(this);
        }
    }
References eventMultiplexer, published, and core::EventMultiplexer::span().
Referenced by core::EventReceiver::span().
Member Data Documentation
eventMultiplexer
EventMultiplexer& core::Event::eventMultiplexer private
Definition at line 59 of file Event.h.
Referenced by Event(), relax(), and span().
eventReceiver
EventReceiver* core::Event::eventReceiver private
Definition at line 58 of file Event.h.
Referenced by dispatch(), Event(), and getEventReceiver().
name
std::string core::Event::name private
Definition at line 56 of file Event.h.
Referenced by Event(), and getName().
published
bool core::Event::published = false private
Definition at line 61 of file Event.h.
Referenced by dispatch(), relax(), and span().
The documentation for this class was generated from the following files:
core/Event.h
core/Event.cpp