SNode.C: core::socket::SocketContext Class Reference
core::socket::SocketContext Class Reference abstract
#include <SocketContext.h>
Public Member Functions
SocketContext (const SocketContext &)=delete
SocketContext (SocketContext &&)=delete
SocketContext & operator= (const SocketContext &)=delete
SocketContext & operator= (SocketContext &&)=delete
virtual ~SocketContext ()=default
virtual void setTimeout (const utils::Timeval &timeout)=0
virtual void sendToPeer (const char *junk, std::size_t junkLen) const =0
void sendToPeer (const std::string &data) const
virtual std::size_t readFromPeer (char *junk, std::size_t junklen) const =0
virtual void close ()=0
Protected Member Functions
SocketContext ()=default
virtual std::size_t onReceivedFromPeer ()=0
virtual void onExit (int sig)
virtual void onWriteError (int errnum)
virtual void onReadError (int errnum)
Detailed Description
Definition at line 35 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext() [1/3]
core::socket::SocketContext::SocketContext () protected default
SocketContext() [2/3]
core::socket::SocketContext::SocketContext (const SocketContext &) delete
SocketContext() [3/3]
core::socket::SocketContext::SocketContext (SocketContext &&) delete
~SocketContext()
virtual core::socket::SocketContext::~SocketContext () virtual default
Reimplemented in web::http::server::SocketContext< RequestT, ResponseT >, web::http::SocketContext, core::socket::stream::SocketContext, and web::http::client::SocketContext< RequestT, ResponseT >.
Member Function Documentation
close()
virtual void core::socket::SocketContext::close () pure virtual
Implemented in core::socket::stream::SocketContext, and iot::mqtt::SocketContext.
onExit()
void core::socket::SocketContext::onExit (int sig) protected virtual
Reimplemented in iot::mqtt::SocketContext, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Definition at line 48 of file SocketContext.cpp.
{
        LOG(TRACE) << "Applicationprotocol exit due to '" << strsignal(sig) << "' (SIG" << utils::system::sigabbrev_np(sig) << " = " << sig
                   << ")";
    }
References utils::system::sigabbrev_np().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onExit().
onReadError()
void core::socket::SocketContext::onReadError (int errnum) protected virtual
Reimplemented in core::socket::stream::SocketContext.
Definition at line 42 of file SocketContext.cpp.
{
        if (errnum != 0) {
            PLOG(TRACE) << "OnReadError: " << errnum;
        }
    }
Referenced by core::socket::stream::SocketContext::onReadError().
onReceivedFromPeer()
virtual std::size_t core::socket::SocketContext::onReceivedFromPeer () protected pure virtual
Implemented in iot::mqtt_fast::SocketContext, iot::mqtt::SocketContext, web::http::client::SocketContext< RequestT, ResponseT >, web::http::server::SocketContext< RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >, and web::http::SocketContext.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReceivedFromPeer().
onWriteError()
void core::socket::SocketContext::onWriteError (int errnum) protected virtual
Reimplemented in core::socket::stream::SocketContext.
Definition at line 36 of file SocketContext.cpp.
{
        if (errnum != 0) {
            PLOG(TRACE) << "OnWriteError: " << errnum;
        }
    }
Referenced by core::socket::stream::SocketContext::onWriteError().
operator=() [1/2]
SocketContext & core::socket::SocketContext::operator= (const SocketContext &) delete
operator=() [2/2]
SocketContext & core::socket::SocketContext::operator= (SocketContext &&) delete
readFromPeer()
virtual std::size_t core::socket::SocketContext::readFromPeer (char * junk, std::size_t junklen) const pure virtual
Implemented in core::socket::stream::SocketContext.
Referenced by iot::mqtt_fast::types::TypeBase::read().
sendToPeer() [1/2]
virtual void core::socket::SocketContext::sendToPeer (const char * junk, std::size_t junkLen) const pure virtual
Implemented in core::socket::stream::SocketContext, and core::socket::stream::SocketContext.
Referenced by sendToPeer().
sendToPeer() [2/2]
void core::socket::SocketContext::sendToPeer (const std::string & data) const
Definition at line 32 of file SocketContext.cpp.
{
        sendToPeer(data.data(), data.length());
    }
References sendToPeer().
setTimeout()
virtual void core::socket::SocketContext::setTimeout (const utils::Timeval & timeout) pure virtual
Implemented in core::socket::stream::SocketContext.
The documentation for this class was generated from the following files:
core/socket/SocketContext.h
core/socket/SocketContext.cpp