SNode.C: express::dispatcher::ScopedPathStrip Class Reference
express::dispatcher::ScopedPathStrip Class Reference
#include <regex_utils.h>
Public Member Functions
ScopedPathStrip (express::Request &req, bool enabled, std::size_t consumedLength)
~ScopedPathStrip ()
ScopedPathStrip (const ScopedPathStrip &)=delete
ScopedPathStrip & operator= (const ScopedPathStrip &)=delete
ScopedPathStrip (ScopedPathStrip &&)=delete
ScopedPathStrip & operator= (ScopedPathStrip &&)=delete
Private Attributes
express::Request * req_ {nullptr}
std::string backupUrl_
std::string backupBaseUrl_
std::string backupPath_
std::string backupFile_
bool enabled_ {false}
Detailed Description
Definition at line 102 of file regex_utils.h.
Constructor & Destructor Documentation
ScopedPathStrip() [1/3]
express::dispatcher::ScopedPathStrip::ScopedPathStrip (express::Request & req, bool enabled, std::size_t consumedLength)
Definition at line 712 of file regex_utils.cpp.
        : req_(&req)
        , enabled_(enabled) {
        if (!enabled_) {
            return;
        }
        backupUrl_ = req.url;
        backupBaseUrl_ = req.baseUrl;
        backupPath_ = req.path;
        backupFile_ = req.file;
        // Express semantics:
        //  - req.originalUrl stays constant
        //  - req.baseUrl is the consumed mount path (root mount -> empty string)
        //  - req.url and req.path become the remainder (path + query / path)
        std::string_view fullPath;
        std::string_view fullQuery;
        splitPathAndQuery(req.url, fullPath, fullQuery);
        // IMPORTANT:
        // We mutate req.url below, which can reallocate and invalidate fullQuery/fullPath
        // string_views.
        // Keep an owning copy of the query part before touching req.url.
        std::string fullQueryCopy;
        if (!fullQuery.empty()) {
            fullQueryCopy.assign(fullQuery.begin(), fullQuery.end());
        }
        // Compute consumed part and remainder (consumedLength refers to the matched prefix in the path).
        const std::size_t cl = std::min<std::size_t>(consumedLength, fullPath.size());
        std::string_view consumed = fullPath.substr(0, cl);
        const std::string_view remainder = (fullPath.size() > cl) ? fullPath.substr(cl) : std::string_view{};
        // baseUrl never ends with a trailing slash and is empty for the root mount.
        consumed = trimOneTrailingSlash(consumed);
        if (consumed.size() == 1 && consumed[0] == '/') {
            consumed = {};
        }
        req.baseUrl = joinMountPath(backupBaseUrl_, consumed);
        // Ensure remainder starts with '/'.
        std::string remPath;
        if (remainder.empty()) {
            remPath = "/";
        } else if (remainder.front() == '/') {
            remPath.assign(remainder.begin(), remainder.end());
        } else {
            remPath = "/";
            remPath.append(remainder.begin(), remainder.end());
        }
        req.path = remPath;
        req.url = remPath;
        if (!fullQueryCopy.empty()) {
            req.url.push_back('?');
            req.url.append(fullQueryCopy);
        }
    }
References backupBaseUrl_, backupFile_, backupPath_, backupUrl_, express::Request::baseUrl, enabled_, express::Request::file, express::dispatcher::joinMountPath(), express::Request::path, req_, express::dispatcher::splitPathAndQuery(), express::dispatcher::trimOneTrailingSlash(), and express::Request::url.
Referenced by express::dispatcher::ApplicationDispatcher::dispatch(), express::dispatcher::MiddlewareDispatcher::dispatch(), and express::dispatcher::RouterDispatcher::dispatch().
~ScopedPathStrip()
express::dispatcher::ScopedPathStrip::~ScopedPathStrip ()
Definition at line 772 of file regex_utils.cpp.
{
        if (enabled_ && req_ != nullptr) {
            req_->url = backupUrl_;
            req_->baseUrl = backupBaseUrl_;
            req_->path = backupPath_;
            req_->file = backupFile_;
        }
    }
References backupBaseUrl_, backupFile_, backupPath_, backupUrl_, express::Request::baseUrl, enabled_, express::Request::file, express::Request::path, req_, and express::Request::url.
ScopedPathStrip() [2/3]
express::dispatcher::ScopedPathStrip::ScopedPathStrip (const ScopedPathStrip &) delete
ScopedPathStrip() [3/3]
express::dispatcher::ScopedPathStrip::ScopedPathStrip (ScopedPathStrip &&) delete
Member Function Documentation
operator=() [1/2]
ScopedPathStrip & express::dispatcher::ScopedPathStrip::operator= (const ScopedPathStrip &) delete
operator=() [2/2]
ScopedPathStrip & express::dispatcher::ScopedPathStrip::operator= (ScopedPathStrip &&) delete
Member Data Documentation
backupBaseUrl_
std::string express::dispatcher::ScopedPathStrip::backupBaseUrl_ private
Definition at line 115 of file regex_utils.h.
Referenced by ScopedPathStrip(), and ~ScopedPathStrip().
backupFile_
std::string express::dispatcher::ScopedPathStrip::backupFile_ private
Definition at line 117 of file regex_utils.h.
Referenced by ScopedPathStrip(), and ~ScopedPathStrip().
backupPath_
std::string express::dispatcher::ScopedPathStrip::backupPath_ private
Definition at line 116 of file regex_utils.h.
Referenced by ScopedPathStrip(), and ~ScopedPathStrip().
backupUrl_
std::string express::dispatcher::ScopedPathStrip::backupUrl_ private
Definition at line 114 of file regex_utils.h.
Referenced by ScopedPathStrip(), and ~ScopedPathStrip().
enabled_
bool express::dispatcher::ScopedPathStrip::enabled_ {false} private
Definition at line 118 of file regex_utils.h.
{false};
Referenced by ScopedPathStrip(), and ~ScopedPathStrip().
req_
express::Request* express::dispatcher::ScopedPathStrip::req_ {nullptr} private
Definition at line 113 of file regex_utils.h.
{nullptr};
Referenced by ScopedPathStrip(), and ~ScopedPathStrip().
The documentation for this class was generated from the following files:
express/dispatcher/regex_utils.h
express/dispatcher/regex_utils.cpp