SNode.C: net::in6::SocketAddress Class Reference
net::in6::SocketAddress Class Reference final
#include <SocketAddress.h>
Classes
struct Hints
Public Member Functions
SocketAddress ()
SocketAddress (const std::string &ipOrHostname)
SocketAddress (uint16_t port)
SocketAddress (const std::string &ipOrHostname, uint16_t port)
SocketAddress (const SockAddr &sockAddr, SockLen sockAddrLen, bool numeric=true)
void init (const Hints &hints={.aiFlags=0,.aiSockType=0,.aiProtocol=0})
bool useNext () override
SocketAddress & setHost (const std::string &ipOrHostname)
std::string getHost () const
SocketAddress & setPort (uint16_t port)
uint16_t getPort () const
std::string getCanonName () const
std::string toString (bool expanded=true) const override
std::string getEndpoint (const std::string_view &format={}) const override
Public Member Functions inherited from net::SocketAddress< sockaddr_in6 >
SocketAddress (sa_family_t af, SockLen sockAddrLen=sizeof(SockAddr))
SocketAddress (const SocketAddress &socketAddress)
SocketAddress (const SockAddr &sockAddr, SockLen sockAddrLen)
SocketAddress & operator= (const SocketAddress &socketAddress)
const sockaddr & getSockAddr ()
const SockLen & getSockAddrLen () const
sa_family_t getAddressFamily () const
Public Member Functions inherited from core::socket::SocketAddress
virtual ~SocketAddress ()
Private Types
using Super = net::SocketAddress<sockaddr_in6>
Private Attributes
std::string host = "::"
uint16_t port = 0
std::string canonName
std::shared_ptr< SocketAddrInfo > socketAddrInfo
Additional Inherited Members
Public Types inherited from net::SocketAddress< sockaddr_in6 >
using SockAddr
using SockLen
Protected Attributes inherited from net::SocketAddress< sockaddr_in6 >
SockAddr sockAddr
SockLen sockAddrLen
Detailed Description
Definition at line 65 of file SocketAddress.h.
Member Typedef Documentation
Super
using net::in6::SocketAddress::Super = net::SocketAddress<sockaddr_in6> private
Definition at line 67 of file SocketAddress.h.
Constructor & Destructor Documentation
SocketAddress() [1/5]
net::in6::SocketAddress::SocketAddress ()
Definition at line 58 of file SocketAddress.cpp.
        : Super(AF_INET6)
        , socketAddrInfo(std::make_shared<SocketAddrInfo>()) {
    }
References net::SocketAddress< SockAddrT >::SocketAddress(), and socketAddrInfo.
Referenced by SocketAddress(), SocketAddress(), and SocketAddress().
SocketAddress() [2/5]
net::in6::SocketAddress::SocketAddress (const std::string & ipOrHostname) explicit
Definition at line 63 of file SocketAddress.cpp.
        : SocketAddress() {
        setHost(ipOrHostname);
    }
References setHost(), and SocketAddress().
SocketAddress() [3/5]
net::in6::SocketAddress::SocketAddress (uint16_t port) explicit
Definition at line 68 of file SocketAddress.cpp.
        : SocketAddress() {
        setPort(port);
    }
References setPort(), and SocketAddress().
SocketAddress() [4/5]
net::in6::SocketAddress::SocketAddress (const std::string & ipOrHostname, uint16_t port)
Definition at line 73 of file SocketAddress.cpp.
        : SocketAddress() {
        setHost(ipOrHostname);
        setPort(port);
    }
References setHost(), setPort(), and SocketAddress().
Referenced by web::http::legacy::in6::EventSource(), web::http::legacy::in6::EventSource(), web::http::tls::in6::EventSource(), web::http::tls::in6::EventSource(), and net::in6::config::ConfigAddress< ConfigAddressTypeT >::init().
SocketAddress() [5/5]
net::in6::SocketAddress::SocketAddress (const SockAddr & sockAddr, SockLen sockAddrLen, bool numeric = true)
Definition at line 79 of file SocketAddress.cpp.
        : net::SocketAddress<SockAddr>(sockAddr, sockAddrLen)
        , socketAddrInfo(std::make_shared<SocketAddrInfo>()) {
        char hostC[NI_MAXHOST];
        char servC[NI_MAXSERV];
        std::memset(hostC, 0, NI_MAXHOST);
        std::memset(servC, 0, NI_MAXSERV);
        const int aiErrCode = core::system::getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr),
                                                        sizeof(sockAddr),
                                                        hostC,
                                                        NI_MAXHOST,
                                                        servC,
                                                        NI_MAXSERV,
                                                        NI_NUMERICSERV | (numeric ? NI_NUMERICHOST : NI_NAMEREQD));
        if (aiErrCode == 0) {
            this->host = hostC;
            this->port = (servC[0] != '\0') ? static_cast<uint16_t>(std::stoul(servC)) : 0;
        } else {
            core::socket::State state = core::socket::STATE_OK;
            switch (aiErrCode) {
                case EAI_AGAIN:
                case EAI_MEMORY:
                    state = core::socket::STATE_ERROR;
                    break;
                default:
                    state = core::socket::STATE_FATAL;
                    break;
            }
            throw core::socket::SocketAddress::BadSocketAddress(
                state, aiErrCode == EAI_SYSTEM ? strerror(errno) : gai_strerror(aiErrCode), aiErrCode == EAI_SYSTEM ? errno : aiErrCode);
        }
    }
References host, port, net::SocketAddress< SockAddrT >::SocketAddress(), and socketAddrInfo.
Referenced by net::in6::config::ConfigAddress< ConfigAddressTypeT >::getSocketAddress().
Member Function Documentation
getCanonName()
std::string net::in6::SocketAddress::getCanonName () const
Definition at line 167 of file SocketAddress.cpp.
{
        return canonName;
    }
References canonName.
getEndpoint()
std::string net::in6::SocketAddress::getEndpoint (const std::string_view & format = {}) const override virtual
Reimplemented from core::socket::SocketAddress.
Definition at line 177 of file SocketAddress.cpp.
{
        return std::vformat(format, std::make_format_args((port)));
    }
References port.
getHost()
std::string net::in6::SocketAddress::getHost () const
Definition at line 153 of file SocketAddress.cpp.
{
        return host;
    }
References host.
Referenced by net::in6::config::ConfigAddress< ConfigAddressTypeT >::setSocketAddress().
getPort()
uint16_t net::in6::SocketAddress::getPort () const
Definition at line 163 of file SocketAddress.cpp.
{
        return port;
    }
References port.
Referenced by net::in6::config::ConfigAddress< ConfigAddressTypeT >::setSocketAddress().
init()
void net::in6::SocketAddress::init (const Hints & hints = {.aiFlags = 0, .aiSockType = 0, .aiProtocol = 0})
Definition at line 114 of file SocketAddress.cpp.
{
        addrinfo addrInfoHints{};
        addrInfoHints.ai_family = Super::getAddressFamily();
        addrInfoHints.ai_flags = hints.aiFlags | AI_ADDRCONFIG |
                                 AI_CANONNAME /*| AI_CANONIDN*/ /*| AI_ALL*/; // AI_CANONIDN produces a still reachable memory leak
        addrInfoHints.ai_socktype = hints.aiSockType;
        addrInfoHints.ai_protocol = hints.aiProtocol;
        const int aiErrCode = socketAddrInfo->resolve(host, std::to_string(port), addrInfoHints);
        if (aiErrCode == 0) {
            sockAddr = socketAddrInfo->getSockAddr();
            canonName = socketAddrInfo->getCanonName();
        } else {
            core::socket::State state = core::socket::STATE_OK;
            switch (aiErrCode) {
                case EAI_AGAIN:
                case EAI_MEMORY:
                    state = core::socket::STATE_ERROR;
                    break;
                default:
                    state = core::socket::STATE_FATAL;
                    break;
            }
            throw core::socket::SocketAddress::BadSocketAddress(state,
                                                                host + ":" + std::to_string(port) + ": " +
                                                                    (aiErrCode == EAI_SYSTEM ? strerror(errno) : gai_strerror(aiErrCode)),
                                                                (aiErrCode == EAI_SYSTEM ? errno : aiErrCode));
        }
    }
References net::in6::SocketAddress::Hints::aiProtocol, net::in6::SocketAddress::Hints::aiSockType, canonName, net::SocketAddress< SockAddrT >::getAddressFamily(), net::in6::SocketAddrInfo::getCanonName(), net::in6::SocketAddrInfo::getSockAddr(), host, port, and socketAddrInfo.
setHost()
SocketAddress & net::in6::SocketAddress::setHost (const std::string & ipOrHostname)
Definition at line 147 of file SocketAddress.cpp.
{
        this->host = ipOrHostname;
        return *this;
    }
References host.
Referenced by SocketAddress(), and SocketAddress().
setPort()
SocketAddress & net::in6::SocketAddress::setPort (uint16_t port)
Definition at line 157 of file SocketAddress.cpp.
{
        this->port = port;
        return *this;
    }
References port.
Referenced by SocketAddress(), and SocketAddress().
toString()
std::string net::in6::SocketAddress::toString (bool expanded = true) const override virtual
Implements core::socket::SocketAddress.
Definition at line 171 of file SocketAddress.cpp.
{
        return std::string(host).append(std::string(":")
                                            .append(std::to_string(port))
                                            .append(expanded && !canonName.empty() ? std::string(" (").append(canonName).append(")") : ""));
    }
References canonName, host, and port.
Referenced by main(), express::legacy::in6::Server(), and express::tls::in6::Server().
useNext()
bool net::in6::SocketAddress::useNext () override virtual
Reimplemented from core::socket::SocketAddress.
Definition at line 181 of file SocketAddress.cpp.
{
        const bool useNext = socketAddrInfo->useNext();
        if (useNext) {
            sockAddr = socketAddrInfo->getSockAddr();
        }
        return useNext;
    }
References net::in6::SocketAddrInfo::getSockAddr(), socketAddrInfo, and net::in6::SocketAddrInfo::useNext().
Member Data Documentation
canonName
std::string net::in6::SocketAddress::canonName private
Definition at line 101 of file SocketAddress.h.
Referenced by getCanonName(), init(), and toString().
host
std::string net::in6::SocketAddress::host = "::" private
Definition at line 98 of file SocketAddress.h.
Referenced by getHost(), init(), setHost(), SocketAddress(), and toString().
port
uint16_t net::in6::SocketAddress::port = 0 private
Definition at line 99 of file SocketAddress.h.
Referenced by getEndpoint(), getPort(), init(), setPort(), SocketAddress(), and toString().
socketAddrInfo
std::shared_ptr<SocketAddrInfo> net::in6::SocketAddress::socketAddrInfo private
Definition at line 103 of file SocketAddress.h.
Referenced by init(), SocketAddress(), SocketAddress(), and useNext().
The documentation for this class was generated from the following files:
net/in6/SocketAddress.h
net/in6/SocketAddress.cpp