SNode.C: TowerCalculator Class Reference
TowerCalculator Class Reference
#include <TowerCalculator.h>
Public Member Functions
TowerCalculator ()
void calculate (long startValue)
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Types
enum class State { WAITING , MULTIPLY , DIVIDE }
Protected Member Functions
void calculate ()
void onEvent (const utils::Timeval &currentTime) override
Protected Attributes
long currentValue
std::deque< long > values
int multiplicator = 1
int divisor = 2
State state
Private Member Functions
void * operator new (std::size_t size)=delete
Private Attributes
Event event
Detailed Description
Definition at line 34 of file TowerCalculator.h.
Member Enumeration Documentation
State
enum class TowerCalculator::State strong protected
Enumerator
WAITING
MULTIPLY
DIVIDE
Definition at line 45 of file TowerCalculator.h.
{ WAITING, MULTIPLY, DIVIDE };
Constructor & Destructor Documentation
TowerCalculator()
TowerCalculator::TowerCalculator ()
Definition at line 29 of file TowerCalculator.cpp.
    : core::EventReceiver("TowerCalculator")
    , currentValue(0)
    , state(State::WAITING) {
}
References currentValue, core::EventReceiver::EventReceiver(), state, and WAITING.
Member Function Documentation
calculate() [1/2]
void TowerCalculator::calculate () protected
Definition at line 41 of file TowerCalculator.cpp.
{
    if (!values.empty() && state == State::WAITING) {
        currentValue = values.front();
        values.pop_front();
        state = State::MULTIPLY;
        multiplicator = 1;
        divisor = 2;
        std::cout << std::endl << "Starting calculation with value = " << currentValue << std::endl;
        span();
    }
}
References currentValue, divisor, multiplicator, MULTIPLY, core::EventReceiver::span(), state, values, and WAITING.
Referenced by calculate(), and onEvent().
calculate() [2/2]
void TowerCalculator::calculate (long startValue)
Definition at line 35 of file TowerCalculator.cpp.
{
    values.push_back(startValue);
    calculate();
}
References calculate(), and values.
Referenced by main().
destruct()
void core::EventReceiver::destruct () virtual inherited
Reimplemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, and database::mariadb::MariaDBCommandStartEvent.
Definition at line 32 of file EventReceiver.cpp.
{
        delete this;
    }
Referenced by core::EventMultiplexer::EventQueue::clear().
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 44 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
onEvent()
void TowerCalculator::onEvent (const utils::Timeval & currentTime) override protected virtual
Implements core::EventReceiver.
Definition at line 56 of file TowerCalculator.cpp.
{
    switch (state) {
        case State::MULTIPLY:
            if (multiplicator < 10) {
                std::cout << currentValue << " * " << multiplicator << " = ";
                currentValue = currentValue * multiplicator;
                std::cout << currentValue << std::endl;
                multiplicator++;
            } else {
                state = State::DIVIDE;
            }
            span();
            break;
        case State::DIVIDE:
            if (divisor < 10) {
                std::cout << currentValue << " / " << divisor << " = ";
                currentValue = currentValue / divisor;
                std::cout << currentValue << std::endl;
                divisor++;
            } else {
                state = State::WAITING;
            }
            span();
            break;
        case State::WAITING:
            calculate();
            break;
    }
}
References calculate(), currentValue, DIVIDE, divisor, multiplicator, MULTIPLY, core::EventReceiver::span(), state, and WAITING.
operator new()
void * TowerCalculator::operator new (std::size_t size) private delete
relax()
void core::EventReceiver::relax () inherited
Definition at line 40 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
span()
void core::EventReceiver::span () inherited
Definition at line 36 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by calculate(), database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader::doRead(), core::socket::stream::SocketWriter::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::FileReader(), core::eventreceiver::InitAcceptEventReceiver::InitAcceptEventReceiver(), core::eventreceiver::InitConnectEventReceiver::InitConnectEventReceiver(), onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
Member Data Documentation
currentValue
long TowerCalculator::currentValue protected
Definition at line 51 of file TowerCalculator.h.
Referenced by calculate(), onEvent(), and TowerCalculator().
divisor
int TowerCalculator::divisor = 2 protected
Definition at line 56 of file TowerCalculator.h.
Referenced by calculate(), and onEvent().
event
Event core::EventReceiver::event private inherited
Definition at line 55 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
multiplicator
int TowerCalculator::multiplicator = 1 protected
Definition at line 55 of file TowerCalculator.h.
Referenced by calculate(), and onEvent().
state
State TowerCalculator::state protected
Definition at line 58 of file TowerCalculator.h.
Referenced by calculate(), onEvent(), and TowerCalculator().
values
std::deque<long> TowerCalculator::values protected
Definition at line 53 of file TowerCalculator.h.
Referenced by calculate(), and calculate().
The documentation for this class was generated from the following files:
apps/towercalculator/TowerCalculator.h
apps/towercalculator/TowerCalculator.cpp