SNode.C: core::multiplexer::select::DescriptorEventPublisher Class Reference
core::multiplexer::select::DescriptorEventPublisher Class Reference
#include <DescriptorEventPublisher.h>
Public Member Functions
DescriptorEventPublisher (const std::string &name, FdSet &fdSet)
Public Member Functions inherited from core::DescriptorEventPublisher
DescriptorEventPublisher ()=delete
virtual ~DescriptorEventPublisher ()
DescriptorEventPublisher (const DescriptorEventPublisher &)=delete
DescriptorEventPublisher & operator= (const DescriptorEventPublisher &)=delete
void enable (DescriptorEventReceiver *descriptorEventReceiver)
void disable (DescriptorEventReceiver *descriptorEventReceiver)
void suspend (DescriptorEventReceiver *descriptorEventReceiver)
void resume (DescriptorEventReceiver *descriptorEventReceiver)
void checkTimedOutEvents (const utils::Timeval &currentTime)
void releaseDisabledEvents (const utils::Timeval &currentTime)
int getObservedEventReceiverCount () const
int maxFd () const
utils::Timeval getNextTimeout (const utils::Timeval &currentTime) const
void signal (int sigNum)
void disable ()
const std::string & getName () const
Private Member Functions
void muxAdd (core::DescriptorEventReceiver *eventReceiver) override
void muxDel (int fd) override
void muxOn (core::DescriptorEventReceiver *eventReceiver) override
void muxOff (core::DescriptorEventReceiver *eventReceiver) override
void spanActiveEvents () override
Private Attributes
FdSet & fdSet
Additional Inherited Members
Protected Member Functions inherited from core::DescriptorEventPublisher
DescriptorEventPublisher (std::string name)
Protected Attributes inherited from core::DescriptorEventPublisher
std::map< int, std::list< DescriptorEventReceiver * > > observedEventReceiverLists
unsigned long eventCounter = 0
Detailed Description
Definition at line 72 of file DescriptorEventPublisher.h.
Constructor & Destructor Documentation
DescriptorEventPublisher()
core::multiplexer::select::DescriptorEventPublisher::DescriptorEventPublisher (const std::string & name, FdSet & fdSet)
Definition at line 82 of file DescriptorEventPublisher.cpp.
        : core::DescriptorEventPublisher(name)
        , fdSet(fdSet) {
    }
References core::DescriptorEventPublisher::DescriptorEventPublisher(), and fdSet.
Referenced by core::multiplexer::select::EventMultiplexer::EventMultiplexer().
Member Function Documentation
muxAdd()
void core::multiplexer::select::DescriptorEventPublisher::muxAdd (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 87 of file DescriptorEventPublisher.cpp.
{
        fdSet.set(eventReceiver->getRegisteredFd());
    }
References fdSet, core::DescriptorEventReceiver::getRegisteredFd(), and core::multiplexer::select::FdSet::set().
muxDel()
void core::multiplexer::select::DescriptorEventPublisher::muxDel (int fd) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 91 of file DescriptorEventPublisher.cpp.
{
        fdSet.clr(fd);
    }
References core::multiplexer::select::FdSet::clr(), and fdSet.
muxOff()
void core::multiplexer::select::DescriptorEventPublisher::muxOff (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 99 of file DescriptorEventPublisher.cpp.
{
        fdSet.clr(eventReceiver->getRegisteredFd());
    }
References core::multiplexer::select::FdSet::clr(), fdSet, and core::DescriptorEventReceiver::getRegisteredFd().
muxOn()
void core::multiplexer::select::DescriptorEventPublisher::muxOn (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 95 of file DescriptorEventPublisher.cpp.
{
        fdSet.set(eventReceiver->getRegisteredFd());
    }
References fdSet, core::DescriptorEventReceiver::getRegisteredFd(), and core::multiplexer::select::FdSet::set().
spanActiveEvents()
void core::multiplexer::select::DescriptorEventPublisher::spanActiveEvents () override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 103 of file DescriptorEventPublisher.cpp.
{
        for (auto& [fd, eventReceivers] : observedEventReceiverLists) {
            if (fdSet.isSet(fd) != 0) {
                core::DescriptorEventReceiver* eventReceiver = eventReceivers.front();
                eventCounter++;
                eventReceiver->span();
            }
        }
    }
References core::DescriptorEventPublisher::eventCounter, fdSet, core::multiplexer::select::FdSet::isSet(), core::DescriptorEventPublisher::observedEventReceiverLists, and core::EventReceiver::span().
Member Data Documentation
fdSet
FdSet& core::multiplexer::select::DescriptorEventPublisher::fdSet private
Definition at line 84 of file DescriptorEventPublisher.h.
Referenced by DescriptorEventPublisher(), muxAdd(), muxDel(), muxOff(), muxOn(), and spanActiveEvents().
The documentation for this class was generated from the following files:
core/multiplexer/select/DescriptorEventPublisher.h
core/multiplexer/select/DescriptorEventPublisher.cpp