SNode.C: iot::mqtt::server::broker::SubscriptionTree Class Reference
iot::mqtt::server::broker::SubscriptionTree Class Reference
#include <SubscriptionTree.h>
Classes
class TopicLevel
Public Member Functions
SubscriptionTree (iot::mqtt::server::broker::Broker *broker)
void appear (const std::string &clientId)
bool subscribe (const std::string &topic, const std::string &clientId, uint8_t qoS)
void publish (Message &&message)
void unsubscribe (const std::string &topic, const std::string &clientId)
void unsubscribe (const std::string &clientId)
nlohmann::json toJson () const
void fromJson (const nlohmann::json &json)
std::list< std::string > getSubscriptions (const std::string &clientId) const
std::map< std::string, std::list< std::pair< std::string, uint8_t > > > getSubscriptionTree () const
void clear ()
Private Attributes
TopicLevel head
Detailed Description
Definition at line 65 of file SubscriptionTree.h.
Constructor & Destructor Documentation
SubscriptionTree()
iot::mqtt::server::broker::SubscriptionTree::SubscriptionTree (iot::mqtt::server::broker::Broker * broker) explicit
Definition at line 61 of file SubscriptionTree.cpp.
        : head(broker, "") {
    }
References head, and iot::mqtt::server::broker::SubscriptionTree::TopicLevel::TopicLevel().
Referenced by iot::mqtt::server::broker::Broker::Broker().
Member Function Documentation
appear()
void iot::mqtt::server::broker::SubscriptionTree::appear (const std::string & clientId)
Definition at line 65 of file SubscriptionTree.cpp.
{
        head.appear(clientId, "");
    }
References iot::mqtt::server::broker::SubscriptionTree::TopicLevel::appear(), and head.
Referenced by iot::mqtt::server::broker::Broker::restartSession().
clear()
void iot::mqtt::server::broker::SubscriptionTree::clear ()
Definition at line 126 of file SubscriptionTree.cpp.
{
        head.clear();
    }
References iot::mqtt::server::broker::SubscriptionTree::TopicLevel::clear(), and head.
Referenced by iot::mqtt::server::broker::Broker::Broker().
fromJson()
void iot::mqtt::server::broker::SubscriptionTree::fromJson (const nlohmann::json & json)
Definition at line 116 of file SubscriptionTree.cpp.
{
        if (!json.empty()) {
            head.fromJson(json);
        }
    }
References iot::mqtt::server::broker::SubscriptionTree::TopicLevel::fromJson(), and head.
Referenced by iot::mqtt::server::broker::Broker::Broker().
getSubscriptions()
std::list< std::string > iot::mqtt::server::broker::SubscriptionTree::getSubscriptions (const std::string & clientId) const
Definition at line 106 of file SubscriptionTree.cpp.
{
        std::list<std::string> subscriptions = head.getSubscriptions(clientId);
        return subscriptions;
    }
References iot::mqtt::server::broker::SubscriptionTree::TopicLevel::getSubscriptions(), and head.
Referenced by iot::mqtt::server::broker::Broker::getSubscriptions().
getSubscriptionTree()
std::map< std::string, std::list< std::pair< std::string, uint8_t > > > iot::mqtt::server::broker::SubscriptionTree::getSubscriptionTree () const
Definition at line 112 of file SubscriptionTree.cpp.
{
        return head.getSubscriptionTree();
    }
References iot::mqtt::server::broker::SubscriptionTree::TopicLevel::getSubscriptionTree(), and head.
Referenced by iot::mqtt::server::broker::Broker::getSubscriptionTree().
publish()
void iot::mqtt::server::broker::SubscriptionTree::publish (Message && message)
Definition at line 84 of file SubscriptionTree.cpp.
{
        auto hashCount = std::ranges::count(message.getTopic(), '#');
        if (!message.getTopic().empty() && (hashCount == 0 || (hashCount == 1 && message.getTopic().ends_with('#')))) {
            head.publish(message, message.getTopic());
        } else {
            LOG(ERROR) << "MQTT Broker: Publish: Wrong '#' placement: " << message.getTopic();
        }
    }
References iot::mqtt::server::broker::Message::getTopic(), head, and iot::mqtt::server::broker::SubscriptionTree::TopicLevel::publish().
Referenced by iot::mqtt::server::broker::Broker::publish().
subscribe()
bool iot::mqtt::server::broker::SubscriptionTree::subscribe (const std::string & topic, const std::string & clientId, uint8_t qoS)
Definition at line 69 of file SubscriptionTree.cpp.
{
        bool success = false;
        auto hashCount = std::ranges::count(topic, '#');
        if (!topic.empty() && (hashCount == 0 || (hashCount == 1 && topic.ends_with('#')))) {
            head.subscribe(clientId, qoS, topic);
            success = true;
        } else {
            LOG(ERROR) << "MQTT Broker: Subscribe: Wrong '#' placement: " << topic;
        }
        return success;
    }
References head, and iot::mqtt::server::broker::SubscriptionTree::TopicLevel::subscribe().
Referenced by iot::mqtt::server::broker::Broker::subscribe().
toJson()
nlohmann::json iot::mqtt::server::broker::SubscriptionTree::toJson () const
Definition at line 122 of file SubscriptionTree.cpp.
{
        return head.toJson();
    }
References head, and iot::mqtt::server::broker::SubscriptionTree::TopicLevel::toJson().
Referenced by iot::mqtt::server::broker::Broker::~Broker().
unsubscribe() [1/2]
void iot::mqtt::server::broker::SubscriptionTree::unsubscribe (const std::string & clientId)
Definition at line 102 of file SubscriptionTree.cpp.
{
        head.unsubscribe(clientId);
    }
References head, and iot::mqtt::server::broker::SubscriptionTree::TopicLevel::unsubscribe().
Referenced by iot::mqtt::server::broker::Broker::deleteSession(), and iot::mqtt::server::broker::Broker::unsubscribe().
unsubscribe() [2/2]
void iot::mqtt::server::broker::SubscriptionTree::unsubscribe (const std::string & topic, const std::string & clientId)
Definition at line 93 of file SubscriptionTree.cpp.
{
        auto hashCount = std::ranges::count(topic, '#');
        if (!topic.empty() && (hashCount == 0 || (hashCount == 1 && topic.ends_with('#')))) {
            head.unsubscribe(clientId, topic);
        } else {
            LOG(ERROR) << "MQTT Broker: Unsubscribe: Wrong '#' placement: " << topic;
        }
    }
References head, and iot::mqtt::server::broker::SubscriptionTree::TopicLevel::unsubscribe().
Referenced by iot::mqtt::server::broker::Broker::unsubscribe().
Member Data Documentation
head
TopicLevel iot::mqtt::server::broker::SubscriptionTree::head private
Definition at line 122 of file SubscriptionTree.h.
Referenced by appear(), clear(), fromJson(), getSubscriptions(), getSubscriptionTree(), publish(), subscribe(), SubscriptionTree(), toJson(), unsubscribe(), and unsubscribe().
The documentation for this class was generated from the following files:
iot/mqtt/server/broker/SubscriptionTree.h
iot/mqtt/server/broker/SubscriptionTree.cpp