SNode.C: iot::mqtt::server::ControlPacketDeserializer Class Reference
iot::mqtt::server::ControlPacketDeserializer Class Reference abstract
#include <ControlPacketDeserializer.h>
Public Member Functions
~ControlPacketDeserializer () override
virtual void deliverPacket (iot::mqtt::server::Mqtt *socketContext)=0
std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
uint32_t getRemainingLength () const
bool isComplete () const
bool isError () const
std::size_t getConsumed () const
Protected Attributes
bool complete = false
bool error = false
uint32_t remainingLength = 0
std::size_t consumed = 0
Private Member Functions
virtual std::size_t deserializeVP (iot::mqtt::MqttContext *mqttContext)=0
Detailed Description
Definition at line 34 of file ControlPacketDeserializer.h.
Constructor & Destructor Documentation
~ControlPacketDeserializer()
iot::mqtt::server::ControlPacketDeserializer::~ControlPacketDeserializer () override virtual
Reimplemented from iot::mqtt::ControlPacketDeserializer.
Definition at line 27 of file ControlPacketDeserializer.cpp.
{
    }
Member Function Documentation
deliverPacket()
virtual void iot::mqtt::server::ControlPacketDeserializer::deliverPacket (iot::mqtt::server::Mqtt * socketContext) pure virtual
Implemented in iot::mqtt::server::packets::Connect, iot::mqtt::server::packets::Disconnect, iot::mqtt::server::packets::Pingreq, iot::mqtt::server::packets::Puback, iot::mqtt::server::packets::Pubcomp, iot::mqtt::server::packets::Publish, iot::mqtt::server::packets::Pubrec, iot::mqtt::server::packets::Pubrel, iot::mqtt::server::packets::Subscribe, and iot::mqtt::server::packets::Unsubscribe.
Referenced by iot::mqtt::server::Mqtt::deliverPacket().
deserialize()
std::size_t iot::mqtt::ControlPacketDeserializer::deserialize (iot::mqtt::MqttContext * mqttContext) inherited
Definition at line 35 of file ControlPacketDeserializer.cpp.
{
        std::size_t currentConsumed = deserializeVP(mqttContext);
        consumed += currentConsumed;
        error = (complete && consumed != this->getRemainingLength()) || (!complete && consumed >= this->getRemainingLength());
        return currentConsumed;
    }
References iot::mqtt::ControlPacketDeserializer::complete, iot::mqtt::ControlPacketDeserializer::consumed, iot::mqtt::ControlPacketDeserializer::deserializeVP(), iot::mqtt::ControlPacketDeserializer::error, and iot::mqtt::ControlPacketDeserializer::getRemainingLength().
deserializeVP()
virtual std::size_t iot::mqtt::ControlPacketDeserializer::deserializeVP (iot::mqtt::MqttContext * mqttContext) private pure virtual inherited
Implemented in iot::mqtt::client::packets::Connack, iot::mqtt::client::packets::Pingresp, iot::mqtt::client::packets::Puback, iot::mqtt::client::packets::Pubcomp, iot::mqtt::client::packets::Publish, iot::mqtt::client::packets::Pubrec, iot::mqtt::client::packets::Pubrel, iot::mqtt::client::packets::Suback, iot::mqtt::client::packets::Unsuback, iot::mqtt::server::packets::Connect, iot::mqtt::server::packets::Disconnect, iot::mqtt::server::packets::Puback, iot::mqtt::server::packets::Pubcomp, iot::mqtt::server::packets::Publish, iot::mqtt::server::packets::Pubrec, iot::mqtt::server::packets::Pubrel, iot::mqtt::server::packets::Subscribe, iot::mqtt::server::packets::Unsubscribe, and iot::mqtt::server::packets::Pingreq.
Referenced by iot::mqtt::ControlPacketDeserializer::deserialize().
getConsumed()
std::size_t iot::mqtt::ControlPacketDeserializer::getConsumed () const inherited
Definition at line 56 of file ControlPacketDeserializer.cpp.
{
        return consumed;
    }
References iot::mqtt::ControlPacketDeserializer::consumed.
Referenced by iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::client::packets::Suback::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), iot::mqtt::server::packets::Subscribe::deserializeVP(), and iot::mqtt::server::packets::Unsubscribe::deserializeVP().
getRemainingLength()
uint32_t iot::mqtt::ControlPacketDeserializer::getRemainingLength () const inherited
Definition at line 44 of file ControlPacketDeserializer.cpp.
{
        return remainingLength;
    }
References iot::mqtt::ControlPacketDeserializer::remainingLength.
Referenced by iot::mqtt::ControlPacketDeserializer::deserialize(), iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::client::packets::Suback::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), iot::mqtt::server::packets::Subscribe::deserializeVP(), and iot::mqtt::server::packets::Unsubscribe::deserializeVP().
isComplete()
bool iot::mqtt::ControlPacketDeserializer::isComplete () const inherited
Definition at line 48 of file ControlPacketDeserializer.cpp.
{
        return complete;
    }
References iot::mqtt::ControlPacketDeserializer::complete.
isError()
bool iot::mqtt::ControlPacketDeserializer::isError () const inherited
Definition at line 52 of file ControlPacketDeserializer.cpp.
{
        return error;
    }
References iot::mqtt::ControlPacketDeserializer::error.
Member Data Documentation
complete
bool iot::mqtt::ControlPacketDeserializer::complete = false protected inherited
Definition at line 59 of file ControlPacketDeserializer.h.
Referenced by iot::mqtt::ControlPacketDeserializer::deserialize(), iot::mqtt::client::packets::Connack::deserializeVP(), iot::mqtt::client::packets::Pingresp::deserializeVP(), iot::mqtt::client::packets::Puback::deserializeVP(), iot::mqtt::client::packets::Pubcomp::deserializeVP(), iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::client::packets::Pubrec::deserializeVP(), iot::mqtt::client::packets::Pubrel::deserializeVP(), iot::mqtt::client::packets::Suback::deserializeVP(), iot::mqtt::client::packets::Unsuback::deserializeVP(), iot::mqtt::server::packets::Connect::deserializeVP(), iot::mqtt::server::packets::Disconnect::deserializeVP(), iot::mqtt::server::packets::Puback::deserializeVP(), iot::mqtt::server::packets::Pubcomp::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), iot::mqtt::server::packets::Pubrec::deserializeVP(), iot::mqtt::server::packets::Pubrel::deserializeVP(), iot::mqtt::server::packets::Subscribe::deserializeVP(), iot::mqtt::server::packets::Unsubscribe::deserializeVP(), iot::mqtt::server::packets::Pingreq::deserializeVP(), and iot::mqtt::ControlPacketDeserializer::isComplete().
consumed
std::size_t iot::mqtt::ControlPacketDeserializer::consumed = 0 protected inherited
Definition at line 64 of file ControlPacketDeserializer.h.
Referenced by iot::mqtt::ControlPacketDeserializer::deserialize(), and iot::mqtt::ControlPacketDeserializer::getConsumed().
error
bool iot::mqtt::ControlPacketDeserializer::error = false protected inherited
Definition at line 60 of file ControlPacketDeserializer.h.
Referenced by iot::mqtt::ControlPacketDeserializer::ControlPacketDeserializer(), iot::mqtt::ControlPacketDeserializer::deserialize(), iot::mqtt::ControlPacketDeserializer::isError(), iot::mqtt::client::packets::Publish::Publish(), and iot::mqtt::server::packets::Publish::Publish().
remainingLength
uint32_t iot::mqtt::ControlPacketDeserializer::remainingLength = 0 protected inherited
Definition at line 62 of file ControlPacketDeserializer.h.
Referenced by iot::mqtt::ControlPacketDeserializer::ControlPacketDeserializer(), and iot::mqtt::ControlPacketDeserializer::getRemainingLength().
The documentation for this class was generated from the following files:
iot/mqtt/server/ControlPacketDeserializer.h
iot/mqtt/server/ControlPacketDeserializer.cpp