SNode.C: web::http::client::MasterRequest Class Reference
web::http::client::MasterRequest Class Reference
#include <Request.h>
Public Member Functions
MasterRequest (SocketContext *socketContext, const std::string &hostFieldValue)
MasterRequest (MasterRequest &)=delete
MasterRequest (MasterRequest &&) noexcept
MasterRequest & operator= (MasterRequest &)=delete
MasterRequest & operator= (MasterRequest &&) noexcept=delete
~MasterRequest () override
void init ()
bool send (const char *chunk, std::size_t chunkLen, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError)
bool send (const std::string &chunk, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError)
bool upgrade (const std::string &url, const std::string &protocols, const std::function< void(bool)> &onUpgradeInitiate, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, bool)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError)
bool sendFile (const std::string &file, const std::function< void(int errnum)> &onStatus, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError)
MasterRequest & sendHeader ()
MasterRequest & sendFragment (const char *chunk, std::size_t chunkLen)
MasterRequest & sendFragment (const std::string &data)
bool end (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError)
bool requestEventSource (const std::string &url, const std::function< std::size_t()> &onServerSentEvent, const std::function< void()> &onOpen, const std::function< void()> &onError)
Public Member Functions inherited from web::http::client::Request
Request (SocketContext *socketContext, const std::string &host)
Request (Request &)=delete
Request & operator= (Request &)=delete
Request & operator= (Request &&) noexcept=delete
void setMasterRequest (const std::shared_ptr< MasterRequest > &masterRequest)
std::shared_ptr< MasterRequest > getMasterRequest () const
SocketContext * getSocketContext () const
Request & host (const std::string &hostFieldValue)
Request & append (const std::string &field, const std::string &value)
Request & set (const std::string &field, const std::string &value, bool overwrite=true)
Request & set (const std::map< std::string, std::string > &headers, bool overwrite=true)
Request & type (const std::string &type)
Request & cookie (const std::string &name, const std::string &value)
Request & cookie (const std::map< std::string, std::string > &cookies)
Request & query (const std::string &key, const std::string &value)
Request & setTrailer (const std::string &field, const std::string &value, bool overwrite=true)
std::string header (const std::string &field) const
const CiStringMap< std::string > & getQueries () const
const CiStringMap< std::string > & getHeaders () const
const CiStringMap< std::string > & getTrailer () const
const CiStringMap< std::string > & getCookies () const
Public Member Functions inherited from core::pipe::Sink
Sink (Sink &)=delete
Sink & operator= (Sink &)=delete
Private Member Functions
bool initiate (const std::shared_ptr< MasterRequest > &request)
bool executeSendFile (const std::string &file, const std::function< void(int)> &onStatus)
bool executeUpgrade (const std::string &url, const std::string &protocols, const std::function< void(bool)> &onStatus)
bool executeSendHeader ()
bool executeSendFragment (const char *chunk, std::size_t chunkLen)
bool executeEnd ()
bool executeSse ()
void requestPrepared (const std::shared_ptr< MasterRequest > &request)
void requestDelivered ()
void deliverResponse (const std::shared_ptr< MasterRequest > &request, const std::shared_ptr< Response > &response)
void deliverResponseParseError (const std::shared_ptr< MasterRequest > &request, const std::string &message)
void onSourceConnect (core::pipe::Source *source) override
void onSourceData (const char *chunk, std::size_t chunkLen) override
void onSourceEof () override
void onSourceError (int errnum) override
Private Attributes
std::list< RequestCommand * > requestCommands
std::size_t contentLengthSent = 0
std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> onResponseReceived
std::function< void(const std::shared_ptr< Request > &, const std::string &message)> onResponseParseError
Friends
class commands::SendFileCommand
class commands::SendFragmentCommand
class commands::SendHeaderCommand
class commands::UpgradeCommand
class commands::EndCommand
class commands::SseCommand
class SocketContext
Additional Inherited Members
Public Attributes inherited from web::http::client::Request
std::string hostFieldValue
std::string method = "GET"
std::string url = "/"
int httpMajor = 1
int httpMinor = 1
std::size_t count {0}
Protected Member Functions inherited from web::http::client::Request
Request (Request &&request) noexcept
void upgrade (const std::shared_ptr< Response > &response, const std::function< void(const std::string &)> &status)
Protected Member Functions inherited from core::pipe::Sink
Sink ()=default
Sink (Sink &&) noexcept=default
Sink & operator= (Sink &&) noexcept=default
virtual ~Sink ()
bool isStreaming ()
void stop ()
Protected Attributes inherited from web::http::client::Request
CiStringMap< std::string > queries
CiStringMap< std::string > headers
CiStringMap< std::string > cookies
CiStringMap< std::string > trailer
std::size_t contentLength = 0
std::weak_ptr< MasterRequest > masterRequest
web::http::client::SocketContext * socketContext
TransferEncoding transferEncoding = TransferEncoding::HTTP10
ConnectionState connectionState = ConnectionState::Default
Detailed Description
Definition at line 147 of file Request.h.
Constructor & Destructor Documentation
MasterRequest() [1/3]
web::http::client::MasterRequest::MasterRequest (SocketContext * socketContext, const std::string & hostFieldValue)
Definition at line 308 of file Request.cpp.
        : Request(socketContext, host) {
        this->init();
    }
References init(), and web::http::client::Request::Request().
MasterRequest() [2/3]
web::http::client::MasterRequest::MasterRequest (MasterRequest &) explicit delete
MasterRequest() [3/3]
web::http::client::MasterRequest::MasterRequest (MasterRequest && request) explicit noexcept
Definition at line 313 of file Request.cpp.
        : Request(std::move(request))
        , requestCommands(std::move(request.requestCommands))
        , contentLengthSent(request.contentLengthSent)
        , onResponseReceived(std::move(request.onResponseReceived))
        , onResponseParseError(std::move(request.onResponseParseError)) {
        request.init();
    }
References contentLengthSent, init(), onResponseParseError, onResponseReceived, web::http::client::Request::Request(), and requestCommands.
~MasterRequest()
web::http::client::MasterRequest::~MasterRequest () override
Definition at line 322 of file Request.cpp.
{
        for (const RequestCommand* requestCommand : requestCommands) {
            delete requestCommand;
        }
        if (!masterRequest.expired() && Sink::isStreaming()) {
            socketContext->streamEof();
        }
    }
References core::pipe::Sink::isStreaming(), web::http::client::Request::masterRequest, requestCommands, web::http::client::Request::socketContext, and core::socket::stream::SocketContext::streamEof().
Member Function Documentation
deliverResponse()
void web::http::client::MasterRequest::deliverResponse (const std::shared_ptr< MasterRequest > & request, const std::shared_ptr< Response > & response) private
Definition at line 716 of file Request.cpp.
{
        onResponseReceived(request, response);
    }
References onResponseReceived.
Referenced by web::http::client::SocketContext::deliverResponse().
deliverResponseParseError()
void web::http::client::MasterRequest::deliverResponseParseError (const std::shared_ptr< MasterRequest > & request, const std::string & message) private
Definition at line 720 of file Request.cpp.
{
        onResponseParseError(request, message);
    }
References onResponseParseError.
Referenced by web::http::client::SocketContext::deliverResponseParseError().
end()
bool web::http::client::MasterRequest::end (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> & onResponseParseError)
Definition at line 524 of file Request.cpp.
{
        bool queued = true;
        if (!masterRequest.expired()) {
            const std::shared_ptr<MasterRequest> newRequest = std::make_shared<MasterRequest>(std::move(*this));
            newRequest->sendHeader();
            newRequest->requestCommands.push_back(new commands::EndCommand(onResponseReceived, onResponseParseError));
            requestPrepared(newRequest);
        } else {
            queued = false;
        }
        return queued;
    }
References web::http::client::commands::EndCommand::EndCommand(), web::http::client::Request::masterRequest, requestCommands, requestPrepared(), and sendHeader().
executeEnd()
bool web::http::client::MasterRequest::executeEnd () private
Definition at line 656 of file Request.cpp.
{
        return true;
    }
Referenced by web::http::client::commands::EndCommand::execute(), and executeSendFile().
executeSendFile()
bool web::http::client::MasterRequest::executeSendFile (const std::string & file, const std::function< void(int)> & onStatus) private
Definition at line 567 of file Request.cpp.
{
        bool atomar = true;
        std::string absolutFileName = file;
        if (std::filesystem::exists(absolutFileName)) {
            std::error_code ec;
            absolutFileName = std::filesystem::canonical(absolutFileName);
            if (std::filesystem::is_regular_file(absolutFileName, ec) && !ec) {
                core::file::FileReader::open(absolutFileName, [this, &absolutFileName, &onStatus, &atomar](int fd) {
                    onStatus(errno);
                    if (fd >= 0) {
                        if (httpMajor == 1) {
                            atomar = false;
                            set("Content-Type", web::http::MimeTypes::contentType(absolutFileName), false);
                            set("Last-Modified", httputils::file_mod_http_date(absolutFileName), false);
                            if (httpMinor == 1 && contentLength == 0) {
                                set("Transfer-Encoding", "chunked");
                            } else {
                                set("Content-Length", std::to_string(std::filesystem::file_size(absolutFileName) + contentLength));
                            }
                            executeSendHeader();
                        }
                    } else {
                        executeEnd();
                    }
                })->pipe(this);
            } else {
                errno = EINVAL;
                onStatus(errno);
            }
        } else {
            errno = ENOENT;
            onStatus(errno);
        }
        return atomar;
    }
References web::http::client::Request::contentLength, web::http::MimeTypes::contentType(), executeEnd(), executeSendHeader(), httputils::file_mod_http_date(), web::http::client::Request::httpMajor, web::http::client::Request::httpMinor, core::file::FileReader::open(), core::pipe::Source::pipe(), and web::http::client::Request::set().
Referenced by web::http::client::commands::SendFileCommand::execute().
executeSendFragment()
bool web::http::client::MasterRequest::executeSendFragment (const char * chunk, std::size_t chunkLen) private
Definition at line 696 of file Request.cpp.
{
        if (transferEncoding == TransferEncoding::Chunked) {
            socketContext->sendToPeer(to_hex_str(chunkLen).append("\r\n"));
        }
        socketContext->sendToPeer(chunk, chunkLen);
        contentLengthSent += chunkLen;
        if (transferEncoding == TransferEncoding::Chunked) {
            socketContext->sendToPeer("\r\n");
            contentLength += chunkLen;
        }
        return true;
    }
References web::http::Chunked, web::http::client::Request::contentLength, contentLengthSent, core::socket::stream::SocketContext::sendToPeer(), core::socket::SocketContext::sendToPeer(), web::http::client::Request::socketContext, and web::http::client::Request::transferEncoding.
Referenced by web::http::client::commands::SendFragmentCommand::execute(), onSourceData(), and requestDelivered().
executeSendHeader()
bool web::http::client::MasterRequest::executeSendHeader () private
Definition at line 664 of file Request.cpp.
{
        const std::string httpVersion = "HTTP/" + std::to_string(httpMajor) + "." + std::to_string(httpMinor);
        std::string queryString;
        if (!queries.empty()) {
            queryString += "?";
            for (auto& [key, value] : queries) {
                queryString += httputils::url_encode(key) + "=" + httputils::url_encode(value) + "&";
            }
            queryString.pop_back();
        }
        socketContext->sendToPeer(method + " " + url + queryString + " " + httpVersion + "\r\n");
        socketContext->sendToPeer("Date: " + httputils::to_http_date() + "\r\n");
        if (!headers.contains("Transfer-Encoding") && contentLength > 0) {
            set("Content-Length", std::to_string(contentLength));
        }
        for (const auto& [field, value] : headers) {
            socketContext->sendToPeer(std::string(field).append(":").append(value).append("\r\n"));
        }
        for (const auto& [name, value] : cookies) {
            socketContext->sendToPeer(std::string("Cookie:").append(name).append("=").append(value).append("\r\n"));
        }
        socketContext->sendToPeer("\r\n");
        return true;
    }
References web::http::client::Request::contentLength, web::http::client::Request::cookies, web::http::client::Request::headers, web::http::client::Request::httpMajor, web::http::client::Request::httpMinor, web::http::client::Request::method, web::http::client::Request::queries, core::socket::SocketContext::sendToPeer(), web::http::client::Request::set(), web::http::client::Request::socketContext, httputils::to_http_date(), web::http::client::Request::url, and httputils::url_encode().
Referenced by web::http::client::commands::SendHeaderCommand::execute(), executeSendFile(), and executeUpgrade().
executeSse()
bool web::http::client::MasterRequest::executeSse () private
Definition at line 660 of file Request.cpp.
{
        return true;
    }
Referenced by web::http::client::commands::SseCommand::execute().
executeUpgrade()
bool web::http::client::MasterRequest::executeUpgrade (const std::string & url, const std::string & protocols, const std::function< void(bool)> & onStatus) private
Definition at line 610 of file Request.cpp.
{
        const std::string connectionName = this->getSocketContext()->getSocketConnection()->getConnectionName();
        this->url = url;
        set("Connection", "Upgrade", true);
        set("Upgrade", protocols, true);
        web::http::client::SocketContextUpgradeFactory* socketContextUpgradeFactory =
            web::http::client::SocketContextUpgradeFactorySelector::instance()->select(protocols, *this);
        if (socketContextUpgradeFactory != nullptr) {
            LOG(DEBUG) << connectionName << " HTTP: "
                       << "SocketContextUpgradeFactory create success: " << socketContextUpgradeFactory->name();
            LOG(DEBUG) << connectionName << " HTTP: Initiating upgrade: " << method << " " << url
                       << " HTTP/" + std::to_string(httpMajor) + "." + std::to_string(httpMinor);
        } else {
            LOG(DEBUG) << connectionName << " HTTP: "
                       << "SocketContextUpgradeFactory create failed: " << protocols;
            LOG(DEBUG) << connectionName << " HTTP: Not initiating upgrade " << method << " " << url
                       << " HTTP/" + std::to_string(httpMajor) + "." + std::to_string(httpMinor);
        }
        LOG(DEBUG) << connectionName << " HTTP: Upgrade request:\n"
                   << httputils::toString(method,
                                          url,
                                          "HTTP/" + std::to_string(httpMajor) + "." + std::to_string(httpMinor),
                                          queries,
                                          headers,
                                          trailer,
                                          cookies,
                                          std::vector<char>());
        onStatus(socketContextUpgradeFactory != nullptr);
        if (socketContextUpgradeFactory != nullptr) {
            executeSendHeader();
            socketContextUpgradeFactory->checkRefCount();
        } else {
            socketContext->close();
        }
        return true;
    }
References web::http::client::SocketContextUpgradeFactory::checkRefCount(), core::socket::stream::SocketContext::close(), web::http::client::Request::cookies, executeSendHeader(), core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), web::http::client::Request::getSocketContext(), web::http::client::Request::headers, web::http::client::Request::httpMajor, web::http::client::Request::httpMinor, web::http::client::SocketContextUpgradeFactorySelector::instance(), web::http::client::Request::method, web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::name(), web::http::client::Request::queries, web::http::client::SocketContextUpgradeFactorySelector::select(), web::http::client::Request::set(), web::http::client::Request::socketContext, httputils::toString(), web::http::client::Request::trailer, and web::http::client::Request::url.
Referenced by web::http::client::commands::UpgradeCommand::execute().
init()
void web::http::client::MasterRequest::init ()
Definition at line 332 of file Request.cpp.
{
        method = "GET";
        url = "/";
        httpMajor = 1;
        httpMinor = 1;
        queries.clear();
        headers.clear();
        cookies.clear();
        trailer.clear();
        requestCommands.clear();
        transferEncoding = TransferEncoding::HTTP10;
        contentLength = 0;
        contentLengthSent = 0;
        connectionState = ConnectionState::Default;
    }
References web::http::client::Request::connectionState, web::http::client::Request::contentLength, contentLengthSent, web::http::client::Request::cookies, web::http::Default, web::http::client::Request::headers, web::http::HTTP10, web::http::client::Request::httpMajor, web::http::client::Request::httpMinor, web::http::client::Request::method, web::http::client::Request::queries, requestCommands, web::http::client::Request::trailer, web::http::client::Request::transferEncoding, and web::http::client::Request::url.
Referenced by MasterRequest(), and MasterRequest().
initiate()
bool web::http::client::MasterRequest::initiate (const std::shared_ptr< MasterRequest > & request) private
Definition at line 543 of file Request.cpp.
{
        bool error = false;
        bool atomar = true;
        for (RequestCommand* requestCommand : requestCommands) {
            if (!error) {
                this->onResponseParseError = requestCommand->onResponseParseError;
                this->onResponseReceived = requestCommand->onResponseReceived;
                atomar = requestCommand->execute(request);
                error = requestCommand->getError();
            }
            delete requestCommand;
        }
        requestCommands.clear();
        if (atomar && !error) {
            requestDelivered();
        }
        return !error;
    }
References web::http::client::RequestCommand::execute(), web::http::client::RequestCommand::getError(), onResponseParseError, web::http::client::RequestCommand::onResponseParseError, onResponseReceived, web::http::client::RequestCommand::onResponseReceived, requestCommands, and requestDelivered().
Referenced by web::http::client::SocketContext::initiateRequest().
onSourceConnect()
void web::http::client::MasterRequest::onSourceConnect (core::pipe::Source * source) override private virtual
Implements core::pipe::Sink.
Definition at line 741 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            if (socketContext->streamToPeer(source)) {
                source->start();
            }
        } else {
            source->stop();
        }
    }
References web::http::client::Request::masterRequest, web::http::client::Request::socketContext, core::pipe::Source::start(), core::pipe::Source::stop(), and core::socket::stream::SocketContext::streamToPeer().
onSourceData()
void web::http::client::MasterRequest::onSourceData (const char * chunk, std::size_t chunkLen) override private virtual
Implements core::pipe::Sink.
Definition at line 751 of file Request.cpp.
{
        executeSendFragment(chunk, chunkLen);
    }
References executeSendFragment().
onSourceEof()
void web::http::client::MasterRequest::onSourceEof () override private virtual
Implements core::pipe::Sink.
Definition at line 755 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            socketContext->streamEof();
            requestDelivered();
        }
    }
References web::http::client::Request::masterRequest, requestDelivered(), web::http::client::Request::socketContext, and core::socket::stream::SocketContext::streamEof().
onSourceError()
void web::http::client::MasterRequest::onSourceError (int errnum) override private virtual
Implements core::pipe::Sink.
Definition at line 763 of file Request.cpp.
{
        errno = errnum;
        if (!masterRequest.expired()) {
            socketContext->streamEof();
            socketContext->close();
            requestDelivered();
        }
    }
References core::socket::stream::SocketContext::close(), web::http::client::Request::masterRequest, requestDelivered(), web::http::client::Request::socketContext, and core::socket::stream::SocketContext::streamEof().
operator=() [1/2]
MasterRequest & web::http::client::MasterRequest::operator= (MasterRequest &&) delete noexcept
operator=() [2/2]
MasterRequest & web::http::client::MasterRequest::operator= (MasterRequest &) delete
requestDelivered()
void web::http::client::MasterRequest::requestDelivered () private
Definition at line 724 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            if (transferEncoding == TransferEncoding::Chunked) {
                executeSendFragment("", 0); // For transfer encoding chunked. Terminate the chunk sequence.
                if (!trailer.empty()) {
                    for (auto& [field, value] : trailer) {
                        socketContext->sendToPeer(std::string(field).append(":").append(value).append("\r\n"));
                    }
                    socketContext->sendToPeer("\r\n");
                }
            }
            socketContext->requestDelivered(contentLengthSent == contentLength);
        }
    }
References web::http::Chunked, web::http::client::Request::contentLength, contentLengthSent, executeSendFragment(), web::http::client::Request::masterRequest, web::http::client::SocketContext::requestDelivered(), core::socket::SocketContext::sendToPeer(), web::http::client::Request::socketContext, web::http::client::Request::trailer, and web::http::client::Request::transferEncoding.
Referenced by initiate(), onSourceEof(), and onSourceError().
requestEventSource()
bool web::http::client::MasterRequest::requestEventSource (const std::string & url, const std::function< std::size_t()> & onServerSentEvent, const std::function< void()> & onOpen, const std::function< void()> & onError)
Definition at line 435 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            const std::shared_ptr<MasterRequest> newRequest = std::make_shared<MasterRequest>(std::move(*this));
            newRequest->url = url;
            newRequest->httpMajor = 1;
            newRequest->httpMinor = 1;
            newRequest->set("Connection", "keep-alive", true);
            newRequest->set("Accept", "text/event-stream", true);
            newRequest->set("Cache-Control", "no-cache", true);
            newRequest->sendHeader();
            newRequest->requestCommands.push_back(new commands::SseCommand(
                [masterRequest = this->masterRequest, onServerSentEvent, onOpen, onError](const std::shared_ptr<Request>& request,
                                                                                          const std::shared_ptr<Response>& response) {
                    if (!masterRequest.expired()) {
                        if (web::http::ciContains(response->headers["Content-Type"], "text/event-stream") &&
                            web::http::ciContains(request->header("Accept"), "text/event-stream")) {
                            masterRequest.lock()->getSocketContext()->setSseEventReceiver(onServerSentEvent);
                            const std::string connectionName = request->getSocketContext()->getSocketConnection()->getConnectionName();
                            onOpen();
                        } else {
                            masterRequest.lock()->getSocketContext()->shutdownWrite(true);
                            onError();
                        }
                    }
                },
                [masterRequest = this->masterRequest](const std::shared_ptr<Request>& request, const std::string& status) {
                    if (!masterRequest.expired()) {
                        LOG(DEBUG) << request->getSocketContext()->getSocketConnection()->getConnectionName()
                                   << " error in response: " << status;
                        masterRequest.lock()->getSocketContext()->shutdownWrite(true);
                    }
                }));
            requestPrepared(newRequest);
        }
        return !masterRequest.expired();
    }
References web::http::ciContains(), core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), web::http::client::Request::getSocketContext(), web::http::client::Request::header(), web::http::client::Response::headers, web::http::client::Request::httpMajor, web::http::client::Request::httpMinor, web::http::client::Request::masterRequest, requestCommands, requestPrepared(), sendHeader(), web::http::client::Request::set(), web::http::client::SocketContext::setSseEventReceiver(), core::socket::stream::SocketContext::shutdownWrite(), web::http::client::commands::SseCommand::SseCommand(), and web::http::client::Request::url.
requestPrepared()
void web::http::client::MasterRequest::requestPrepared (const std::shared_ptr< MasterRequest > & request) private
Definition at line 712 of file Request.cpp.
{
        socketContext->requestPrepared(request);
    }
References web::http::client::SocketContext::requestPrepared(), and web::http::client::Request::socketContext.
Referenced by end(), requestEventSource(), send(), sendFile(), and upgrade().
send() [1/2]
bool web::http::client::MasterRequest::send (const char * chunk, std::size_t chunkLen, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> & onResponseParseError)
Definition at line 349 of file Request.cpp.
{
        bool queued = true;
        if (!masterRequest.expired()) {
            const std::shared_ptr<MasterRequest> newRequest = std::make_shared<MasterRequest>(std::move(*this));
            if (chunkLen > 0) {
                newRequest->set("Content-Type", "application/octet-stream", false);
            }
            newRequest->sendHeader();
            newRequest->sendFragment(chunk, chunkLen);
            newRequest->requestCommands.push_back(new commands::EndCommand(onResponseReceived, onResponseParseError));
            newRequest->requestPrepared(newRequest);
        } else {
            queued = false;
        }
        return queued;
    }
References web::http::client::commands::EndCommand::EndCommand(), web::http::client::Request::masterRequest, requestCommands, requestPrepared(), sendFragment(), sendHeader(), and web::http::client::Request::set().
Referenced by send().
send() [2/2]
bool web::http::client::MasterRequest::send (const std::string & chunk, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> & onResponseParseError)
Definition at line 377 of file Request.cpp.
{
        if (!chunk.empty()) {
            set("Content-Type", "text/html; charset=utf-8", false);
        }
        return send(chunk.data(), chunk.size(), onResponseReceived, onResponseParseError);
    }
References send(), and web::http::client::Request::set().
Referenced by main().
sendFile()
bool web::http::client::MasterRequest::sendFile (const std::string & file, const std::function< void(int errnum)> & onStatus, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> & onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> & onResponseParseError)
Definition at line 481 of file Request.cpp.
{
        bool queued = false;
        if (!masterRequest.expired()) {
            const std::shared_ptr<MasterRequest> newRequest = std::make_shared<MasterRequest>(std::move(*this));
            newRequest->requestCommands.push_back(new commands::SendFileCommand(file, onStatus, onResponseReceived, onResponseParseError));
            requestPrepared(newRequest);
            queued = true;
        }
        return queued;
    }
References web::http::client::Request::masterRequest, requestCommands, requestPrepared(), and web::http::client::commands::SendFileCommand::SendFileCommand().
sendFragment() [1/2]
MasterRequest & web::http::client::MasterRequest::sendFragment (const char * chunk, std::size_t chunkLen)
Definition at line 509 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            contentLength += chunkLen;
            requestCommands.push_back(new commands::SendFragmentCommand(chunk, chunkLen));
        }
        return *this;
    }
References web::http::client::Request::contentLength, web::http::client::Request::masterRequest, requestCommands, and web::http::client::commands::SendFragmentCommand::SendFragmentCommand().
Referenced by send(), and sendFragment().
sendFragment() [2/2]
MasterRequest & web::http::client::MasterRequest::sendFragment (const std::string & data)
Definition at line 519 of file Request.cpp.
{
        return sendFragment(data.data(), data.size());
    }
References sendFragment().
sendHeader()
MasterRequest & web::http::client::MasterRequest::sendHeader ()
Definition at line 501 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            requestCommands.push_back(new commands::SendHeaderCommand());
        }
        return *this;
    }
References web::http::client::Request::masterRequest, requestCommands, and web::http::client::commands::SendHeaderCommand::SendHeaderCommand().
Referenced by end(), requestEventSource(), and send().
upgrade()
bool web::http::client::MasterRequest::upgrade (const std::string & url, const std::string & protocols, const std::function< void(bool)> & onUpgradeInitiate, const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &, bool)> & onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> & onResponseParseError)
Definition at line 387 of file Request.cpp.
{
        if (!masterRequest.expired()) {
            const std::shared_ptr<MasterRequest> newRequest = std::make_shared<MasterRequest>(std::move(*this));
            newRequest->url = url;
            newRequest->requestCommands.push_back(new commands::UpgradeCommand(
                url,
                protocols,
                onUpgradeInitiate,
                [onResponseReceived](const std::shared_ptr<Request>& request, const std::shared_ptr<Response>& response) {
                    if (request != nullptr) {
                        const std::string connectionName = request->getSocketContext()->getSocketConnection()->getConnectionName();
                        LOG(DEBUG) << connectionName << " HTTP upgrade: Response to upgrade request: " << request->method << " "
                                   << request->url << " "
                                   << "HTTP/" << request->httpMajor << "." << request->httpMinor << "\n"
                                   << httputils::toString(response->httpVersion,
                                                          response->statusCode,
                                                          response->reason,
                                                          response->headers,
                                                          response->cookies,
                                                          response->body);
                        request->upgrade(response, [request, response, connectionName, &onResponseReceived](const std::string& name) {
                            LOG(DEBUG) << connectionName << " HTTP upgrade: bootstrap " << (!name.empty() ? "success" : "failed");
                            LOG(DEBUG) << "      Protocol selected: " << name;
                            LOG(DEBUG) << "              requested: " << request->header("upgrade");
                            LOG(DEBUG) << "  Subprotocol  selected: " << response->get("Sec-WebSocket-Protocol");
                            LOG(DEBUG) << "              requested: " << request->header("Sec-WebSocket-Protocol");
                            onResponseReceived(request, response, !name.empty());
                        });
                    }
                },
                onResponseParseError));
            requestPrepared(newRequest);
        }
        return !masterRequest.expired();
    }
References web::http::client::Response::body, web::http::client::Response::cookies, web::http::client::Response::get(), core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), web::http::client::Request::getSocketContext(), web::http::client::Request::header(), web::http::client::Response::headers, web::http::client::Request::httpMajor, web::http::client::Request::httpMinor, web::http::client::Response::httpVersion, web::http::client::Request::masterRequest, web::http::client::Request::method, web::http::client::Response::reason, requestCommands, requestPrepared(), web::http::client::Response::statusCode, httputils::toString(), web::http::client::Request::upgrade(), web::http::client::commands::UpgradeCommand::UpgradeCommand(), and web::http::client::Request::url.
Referenced by main().
Friends And Related Symbol Documentation
commands::EndCommand
friend class commands::EndCommand friend
Definition at line 197 of file Request.h.
commands::SendFileCommand
friend class commands::SendFileCommand friend
Definition at line 193 of file Request.h.
commands::SendFragmentCommand
friend class commands::SendFragmentCommand friend
Definition at line 194 of file Request.h.
commands::SendHeaderCommand
friend class commands::SendHeaderCommand friend
Definition at line 195 of file Request.h.
commands::SseCommand
friend class commands::SseCommand friend
Definition at line 198 of file Request.h.
commands::UpgradeCommand
friend class commands::UpgradeCommand friend
Definition at line 196 of file Request.h.
SocketContext
friend class SocketContext friend
Definition at line 225 of file Request.h.
Member Data Documentation
contentLengthSent
std::size_t web::http::client::MasterRequest::contentLengthSent = 0 private
Definition at line 220 of file Request.h.
Referenced by executeSendFragment(), init(), MasterRequest(), and requestDelivered().
onResponseParseError
std::function<void(const std::shared_ptr<Request>&, const std::string& message)> web::http::client::MasterRequest::onResponseParseError private
Definition at line 223 of file Request.h.
Referenced by deliverResponseParseError(), initiate(), and MasterRequest().
onResponseReceived
std::function<void(const std::shared_ptr<Request>&, const std::shared_ptr<Response>&)> web::http::client::MasterRequest::onResponseReceived private
Definition at line 222 of file Request.h.
Referenced by deliverResponse(), initiate(), and MasterRequest().
requestCommands
std::list<RequestCommand*> web::http::client::MasterRequest::requestCommands private
Definition at line 218 of file Request.h.
Referenced by end(), init(), initiate(), MasterRequest(), requestEventSource(), send(), sendFile(), sendFragment(), sendHeader(), upgrade(), and ~MasterRequest().
The documentation for this class was generated from the following files:
web/http/client/Request.h
web/http/client/Request.cpp