SNode.C: web::http::client::commands::SendFragmentCommand Class Reference
web::http::client::commands::SendFragmentCommand Class Reference
#include <SendFragmentCommand.h>
Public Member Functions
SendFragmentCommand (const char *chunk, std::size_t chunkLen)
~SendFragmentCommand () override
bool execute (const std::shared_ptr< MasterRequest > &request) override
Public Member Functions inherited from web::http::client::RequestCommand
RequestCommand (const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> &onResponseReceived, const std::function< void(const std::shared_ptr< Request > &, const std::string &)> &onResponseParseError)
RequestCommand (const RequestCommand &)=delete
RequestCommand (RequestCommand &&) noexcept=delete
RequestCommand & operator= (const RequestCommand &)=delete
RequestCommand & operator= (RequestCommand &&) noexcept=delete
virtual ~RequestCommand ()
bool getError () const
Private Attributes
char * chunk
std::size_t chunkLen
Additional Inherited Members
Public Attributes inherited from web::http::client::RequestCommand
const std::function< void(const std::shared_ptr< Request > &, const std::shared_ptr< Response > &)> onResponseReceived
const std::function< void(const std::shared_ptr< Request > &, const std::string &)> onResponseParseError
Protected Attributes inherited from web::http::client::RequestCommand
bool error = false
Detailed Description
Definition at line 54 of file SendFragmentCommand.h.
Constructor & Destructor Documentation
SendFragmentCommand()
web::http::client::commands::SendFragmentCommand::SendFragmentCommand (const char * chunk, std::size_t chunkLen)
Definition at line 54 of file SendFragmentCommand.cpp.
        : web::http::client::RequestCommand({}, {})
        , chunk(new char[chunkLen])
        , chunkLen(chunkLen) {
        std::memcpy(this->chunk, chunk, chunkLen);
    }
References web::http::client::RequestCommand::RequestCommand().
Referenced by web::http::client::MasterRequest::sendFragment().
~SendFragmentCommand()
web::http::client::commands::SendFragmentCommand::~SendFragmentCommand () override
Definition at line 61 of file SendFragmentCommand.cpp.
{
        delete[] chunk;
    }
References chunk.
Member Function Documentation
execute()
bool web::http::client::commands::SendFragmentCommand::execute (const std::shared_ptr< MasterRequest > & request) override virtual
Implements web::http::client::RequestCommand.
Definition at line 65 of file SendFragmentCommand.cpp.
{
        return request->executeSendFragment(chunk, chunkLen);
    }
References chunk, chunkLen, and web::http::client::MasterRequest::executeSendFragment().
Member Data Documentation
chunk
char* web::http::client::commands::SendFragmentCommand::chunk private
Definition at line 63 of file SendFragmentCommand.h.
Referenced by execute(), and ~SendFragmentCommand().
chunkLen
std::size_t web::http::client::commands::SendFragmentCommand::chunkLen private
Definition at line 64 of file SendFragmentCommand.h.
Referenced by execute().
The documentation for this class was generated from the following files:
web/http/client/commands/SendFragmentCommand.h
web/http/client/commands/SendFragmentCommand.cpp