SNode.C: web::websocket::client::SocketContextUpgrade Class Reference
web::websocket::client::SocketContextUpgrade Class Reference
#include <SocketContextUpgrade.h>
Public Types
using SubProtocol = SubProtocol
using Request = web::http::client::Request
using Response = web::http::client::Response
enum OpCode {
CONTINUATION = 0x00 , TEXT = 0x01 , BINARY = 0x02 , CLOSE = 0x08 ,
PING = 0x09 , PONG = 0x0A
}
Public Member Functions
SocketContextUpgrade (core::socket::stream::SocketConnection *socketConnection, web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response > *socketContextUpgradeFactory)
~SocketContextUpgrade () override
std::string loadSubProtocol (const std::string &subProtocolName)
SocketConnection * getSocketConnection () const
void sendToPeer (const char *chunk, std::size_t chunkLen) const final
void sendToPeer (const std::string &data) const
virtual void sendToPeer (const char *chunk, std::size_t chunkLen) const=0
bool streamToPeer (core::pipe::Source *source) const
void streamEof ()
std::size_t readFromPeer (char *chunk, std::size_t chunklen) const final
void setTimeout (const utils::Timeval &timeout) final
void shutdownRead ()
void shutdownWrite (bool forceClose=false)
void close () override
virtual void switchSocketContext (SocketContext *newSocketContext)
Protected Types
enum Role
using SocketContextUpgradeFactory = web::http::SocketContextUpgradeFactory< Request, Response >
Protected Member Functions
void onWriteError (int errnum) override
void onReadError (int errnum) override
std::size_t receive ()
Protected Attributes
SubProtocol * subProtocol
Private Types
using Super = web::http::SocketContextUpgrade< web::http::client::Request, web::http::client::Response >
enum struct ParserState {
BEGIN , OPCODE , LENGTH , ELENGTH ,
MASKINGKEY , PAYLOAD , ERROR
}
Private Member Functions
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength) override
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength) override
void sendMessageFrame (const char *message, std::size_t messageLength) override
void sendMessageEnd (const char *message, std::size_t messageLength) override
void sendPing (const char *reason=nullptr, std::size_t reasonLength=0) override
void sendPong (const char *reason=nullptr, std::size_t reasonLength=0) override
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0) override
void sendClose (const char *message, std::size_t messageLength) override
core::socket::stream::SocketConnection * getSocketConnection () override
void onMessageStart (int opCode) override
void onMessageData (const char *chunk, uint64_t chunkLen) override
void onMessageEnd () override
void onMessageError (uint16_t errnum) override
std::size_t readFrameData (char *chunk, std::size_t chunkLen) override
void onConnected () override
void onDisconnected () override
bool onSignal (int sig) override
void sendFrameData (uint8_t data) const override
void sendFrameData (uint16_t data) const override
void sendFrameData (uint32_t data) const override
void sendFrameData (uint64_t data) const override
void sendFrameData (const char *frame, uint64_t frameLength) const override
std::size_t onReceivedFromPeer () override
void dumpFrame (char *frame, uint64_t frameLength)
std::size_t readOpcode ()
std::size_t readLength ()
std::size_t readELength ()
std::size_t readMaskingKey ()
std::size_t readPayload ()
void reset ()
void send (bool end, uint8_t opCode, const char *message, std::size_t messageLength)
void sendFrame (bool fin, uint8_t opCode, const char *payload, uint64_t payloadLength)
Private Attributes
web::websocket::SubProtocolFactory< SubProtocol > * subProtocolFactory = nullptr
bool closeSent
int receivedOpCode
std::string pongCloseData
SocketContextUpgradeFactory * socketContextUpgradeFactory = nullptr
core::socket::stream::SocketConnection * socketConnection
enum web::websocket::Receiver::ParserState parserState = ParserState::BEGIN
bool fin = false
bool continuation = false
bool masked = false
uint8_t opCode = 0
uint8_t elengthNumBytes = 0
uint8_t elengthNumBytesLeft = 0
uint64_t payLoadNumBytes = 0
uint64_t payLoadNumBytesLeft = 0
uint32_t maskingKey = 0
MaskingKey maskingKeyAsArray {}
uint8_t maskingKeyNumBytes = 4
uint8_t maskingKeyNumBytesLeft = 4
uint16_t errorState = 0
char elengthChunk [8] {}
char maskingKeyChunk [4] {}
char payloadChunk [16384] {}
std::random_device randomDevice
std::uniform_int_distribution< uint32_t > distribution {0, UINT32_MAX}
bool masking = false
Detailed Description
Definition at line 49 of file SocketContextUpgrade.h.
Member Typedef Documentation
Request
using web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::Request = web::http::client::Request inherited
Definition at line 69 of file SocketContextUpgrade.h.
Response
using web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::Response = web::http::client::Response inherited
Definition at line 70 of file SocketContextUpgrade.h.
SocketContextUpgradeFactory
template<typename RequestT , typename ResponseT > using web::http::SocketContextUpgrade< RequestT, ResponseT >::SocketContextUpgradeFactory = web::http::SocketContextUpgradeFactory<Request, Response> protected inherited
Definition at line 42 of file SocketContextUpgrade.h.
SubProtocol
using web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::SubProtocol = SubProtocol inherited
Definition at line 68 of file SocketContextUpgrade.h.
Super
using web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::Super = web::http::SocketContextUpgrade<web::http::client::Request , web::http::client::Response > private inherited
Definition at line 65 of file SocketContextUpgrade.h.
Member Enumeration Documentation
OpCode
enum web::websocket::SubProtocolContext::OpCode inherited
Enumerator
CONTINUATION
TEXT
BINARY
CLOSE
PING
PONG
Definition at line 61 of file SubProtocolContext.h.
{ CONTINUATION = 0x00, TEXT = 0x01, BINARY = 0x02, CLOSE = 0x08, PING = 0x09, PONG = 0x0A };
ParserState
enum struct web::websocket::Receiver::ParserState strong private inherited
Enumerator
BEGIN
OPCODE
LENGTH
ELENGTH
MASKINGKEY
PAYLOAD
ERROR
Definition at line 69 of file Receiver.h.
{ BEGIN, OPCODE, LENGTH, ELENGTH, MASKINGKEY, PAYLOAD, ERROR } parserState = ParserState::BEGIN;
Role
enum web::websocket::SocketContextUpgrade::Role strong protected inherited
Definition at line 79 of file SocketContextUpgrade.h.
{ SERVER, CLIENT };
Constructor & Destructor Documentation
SocketContextUpgrade()
web::websocket::client::SocketContextUpgrade::SocketContextUpgrade (core::socket::stream::SocketConnection * socketConnection, web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response > * socketContextUpgradeFactory)
Definition at line 31 of file SocketContextUpgrade.cpp.
        : web::websocket::SocketContextUpgrade<SubProtocol, web::http::client::Request, web::http::client::Response>(
              socketConnection, socketContextUpgradeFactory, Role::CLIENT) {
    }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::SocketContextUpgrade(), and web::websocket::client::SubProtocol::web::websocket::SocketContextUpgrade.
Referenced by web::websocket::client::SocketContextUpgradeFactory::create().
~SocketContextUpgrade()
web::websocket::client::SocketContextUpgrade::~SocketContextUpgrade () override
Definition at line 38 of file SocketContextUpgrade.cpp.
{
        if (subProtocolFactory != nullptr && subProtocolFactory->deleteSubProtocol(subProtocol) == 0) {
            SubProtocolFactorySelector::instance()->unload(subProtocolFactory);
        }
        subProtocol = nullptr;
    }
References web::websocket::SubProtocolFactory< SubProtocolT >::deleteSubProtocol(), web::websocket::client::SubProtocolFactorySelector::instance(), subProtocolFactory, and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::unload().
Member Function Documentation
close()
void core::socket::stream::SocketContext::close () override virtual inherited
Implements core::socket::SocketContext.
Reimplemented in iot::mqtt::SocketContext.
Definition at line 62 of file SocketContext.cpp.
{
        socketConnection->close();
    }
References core::socket::stream::SocketConnection::close(), and core::socket::stream::SocketContext::socketConnection.
Referenced by iot::mqtt::SocketContext::close(), web::http::client::Request::executeUpgrade(), iot::mqtt_fast::SocketContext::onReceivedFromPeer(), web::http::client::Request::onSourceError(), and web::http::server::Response::onSourceError().
dumpFrame()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::dumpFrame (char * frame, uint64_t frameLength) inline private inherited
Definition at line 292 of file SocketContextUpgrade.h.
{
            const unsigned int modul = 4;
            std::stringstream stringStream;
            for (std::size_t i = 0; i < frameLength; i++) {
                stringStream << std::setfill('0') << std::setw(2) << std::hex
                             << static_cast<unsigned int>(static_cast<unsigned char>(frame[i])) << " ";
                if ((i + 1) % modul == 0 || i == frameLength) { // cppcheck-suppress knownConditionTrueFalse
                    LOG(TRACE) << "WebSocket: Frame = " << stringStream.str();
                    stringStream.str("");
                }
            }
        }
getSocketConnection() [1/2]
SocketConnection * core::socket::stream::SocketContext::getSocketConnection () const inherited
Definition at line 38 of file SocketContext.cpp.
{
        return socketConnection;
    }
References core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::SocketContext::deliverResponse(), web::http::client::SocketContext::dispatchNextRequest(), iot::mqtt::SocketContext::getSocketConnection(), web::http::client::SocketContext::onConnected(), web::http::server::SocketContext::onConnected(), web::http::client::SocketContext::onDisconnected(), web::http::server::SocketContext::onDisconnected(), web::http::client::SocketContext::onSignal(), web::http::server::SocketContext::onSignal(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestCompleted(), web::http::server::SocketContext::requestParsed(), web::http::server::SocketContext::requestParseError(), web::http::client::SocketContext::requestPrepared(), web::http::client::SocketContext::requestSent(), web::http::server::SocketContext::requestStarted(), web::http::server::SocketContext::responseCompleted(), web::http::client::SocketContext::responseError(), web::http::client::SocketContext::responseStarted(), web::http::server::SocketContext::responseStarted(), web::http::client::SocketContext::SocketContext(), and express::middleware::VerboseRequest::VerboseRequest().
getSocketConnection() [2/2]
core::socket::stream::SocketConnection * web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::getSocketConnection () inline override private virtual inherited
Implements web::websocket::SubProtocolContext.
Definition at line 143 of file SocketContextUpgrade.h.
{
            return web::http::SocketContextUpgrade<RequestT, ResponseT>::getSocketConnection();
        }
loadSubProtocol()
std::string web::websocket::client::SocketContextUpgrade::loadSubProtocol (const std::string & subProtocolName)
Definition at line 46 of file SocketContextUpgrade.cpp.
{
        std::string selectedSubProtocolName;
        subProtocolFactory = SubProtocolFactorySelector::instance()->select(subProtocolName, SubProtocolFactorySelector::Role::CLIENT);
        if (subProtocolFactory != nullptr) {
            subProtocol = subProtocolFactory->createSubProtocol(this);
            selectedSubProtocolName = subProtocol != nullptr ? subProtocolName : "";
        }
        return selectedSubProtocolName;
    }
References web::websocket::SubProtocolFactory< SubProtocolT >::createSubProtocol(), web::websocket::client::SubProtocolFactorySelector::instance(), web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::select(), and subProtocolFactory.
Referenced by web::websocket::client::SocketContextUpgradeFactory::create().
onConnected()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::onConnected () inline override private virtual inherited
Implements core::socket::stream::SocketContext.
Definition at line 222 of file SocketContextUpgrade.h.
{
            LOG(INFO) << "WebSocket: connected";
            subProtocol->onConnected();
        }
onDisconnected()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::onDisconnected () inline override private virtual inherited
Implements core::socket::stream::SocketContext.
Definition at line 227 of file SocketContextUpgrade.h.
{
            subProtocol->onDisconnected();
            LOG(INFO) << "WebSocket: disconnected";
        }
onMessageData()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::onMessageData (const char * chunk, uint64_t chunkLen) inline override private virtual inherited
Implements web::websocket::Receiver.
Definition at line 164 of file SocketContextUpgrade.h.
{
            switch (receivedOpCode) {
                case SubProtocolContext::OpCode::CLOSE:
                    [[fallthrough]];
                case SubProtocolContext::OpCode::PING:
                    [[fallthrough]];
                case SubProtocolContext::OpCode::PONG:
                    pongCloseData += std::string(chunk, static_cast<std::size_t>(chunkLen));
                    break;
                default:
                    std::size_t chunkOffset = 0;
                    do {
                        std::size_t sendChunkLen =
                            (chunkLen - chunkOffset <= SIZE_MAX) ? static_cast<std::size_t>(chunkLen - chunkOffset) : SIZE_MAX;
                        subProtocol->onMessageData(chunk + chunkOffset, sendChunkLen);
                        chunkOffset += sendChunkLen;
                    } while (chunkLen - chunkOffset > 0);
                    break;
            }
        }
onMessageEnd()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::onMessageEnd () inline override private virtual inherited
Implements web::websocket::Receiver.
Definition at line 186 of file SocketContextUpgrade.h.
{
            switch (receivedOpCode) {
                case SubProtocolContext::OpCode::CLOSE:
                    if (closeSent) { // active close
                        closeSent = false;
                        LOG(DEBUG) << "WebSocket: Close confirmed from peer";
                    } else { // passive close
                        LOG(DEBUG) << "WebSocket: Close request received - replying with close";
                        sendClose(pongCloseData.data(), pongCloseData.length());
                        pongCloseData.clear();
                        shutdownWrite();
                    }
                    break;
                case SubProtocolContext::OpCode::PING:
                    sendPong(pongCloseData.data(), pongCloseData.length());
                    pongCloseData.clear();
                    break;
                case SubProtocolContext::OpCode::PONG:
                    subProtocol->onPongReceived();
                    break;
                default:
                    subProtocol->onMessageEnd();
                    break;
            }
        }
onMessageError()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::onMessageError (uint16_t errnum) inline override private virtual inherited
Implements web::websocket::Receiver.
Definition at line 212 of file SocketContextUpgrade.h.
{
            subProtocol->onMessageError(errnum);
            sendClose(errnum);
        }
onMessageStart()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::onMessageStart (int opCode) inline override private virtual inherited
Implements web::websocket::Receiver.
Definition at line 148 of file SocketContextUpgrade.h.
{
            receivedOpCode = opCode;
            switch (opCode) {
                case SubProtocolContext::OpCode::CLOSE:
                    [[fallthrough]];
                case SubProtocolContext::OpCode::PING:
                    [[fallthrough]];
                case SubProtocolContext::OpCode::PONG:
                    break;
                default:
                    subProtocol->onMessageStart(opCode);
                    break;
            }
        }
onReadError()
void core::socket::stream::SocketContext::onReadError (int errnum) override protected virtual inherited
Implements core::socket::SocketContext.
Definition at line 78 of file SocketContext.cpp.
{
        shutdownWrite();
    }
References core::socket::stream::SocketContext::shutdownWrite().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReadError().
onReceivedFromPeer()
std::size_t web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::onReceivedFromPeer () inline override private virtual inherited
Implements core::socket::SocketContext.
Definition at line 278 of file SocketContextUpgrade.h.
{
            return Receiver::receive();
        }
onSignal()
bool web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::onSignal (int sig) inline override private virtual inherited
Implements core::socket::SocketContext.
Definition at line 232 of file SocketContextUpgrade.h.
{
            return subProtocol->onSignal(sig);
        }
onWriteError()
void core::socket::stream::SocketContext::onWriteError (int errnum) override protected virtual inherited
Implements core::socket::SocketContext.
Definition at line 74 of file SocketContext.cpp.
{
        shutdownRead();
    }
References core::socket::stream::SocketContext::shutdownRead().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onWriteError().
readELength()
std::size_t web::websocket::Receiver::readELength () private inherited
Definition at line 136 of file Receiver.cpp.
{
        const std::size_t ret = readFrameData(elengthChunk, elengthNumBytesLeft);
        for (std::size_t i = 0; i < ret; i++) {
            payLoadNumBytes |= *reinterpret_cast<uint64_t*>(elengthChunk + i) << (elengthNumBytes - elengthNumBytesLeft) * 8;
            elengthNumBytesLeft--;
        }
        if (elengthNumBytesLeft == 0) {
            switch (elengthNumBytes) {
                case 2:
                    payLoadNumBytes = payLoadNumBytesLeft = be16toh(static_cast<uint16_t>(payLoadNumBytes));
                    break;
                case 8:
                    payLoadNumBytes = payLoadNumBytesLeft = be64toh(payLoadNumBytes);
                    break;
            }
            if ((payLoadNumBytes & static_cast<uint64_t>(0x01) << 63) != 0) {
                parserState = ParserState::ERROR;
                errorState = 1004;
            } else if (masked) {
                parserState = ParserState::MASKINGKEY;
            } else {
                parserState = ParserState::PAYLOAD;
            }
        }
        return ret;
    }
References web::websocket::Receiver::elengthChunk, web::websocket::Receiver::elengthNumBytes, web::websocket::Receiver::elengthNumBytesLeft, web::websocket::Receiver::ERROR, web::websocket::Receiver::errorState, web::websocket::Receiver::masked, web::websocket::Receiver::MASKINGKEY, web::websocket::Receiver::PAYLOAD, web::websocket::Receiver::payLoadNumBytes, web::websocket::Receiver::payLoadNumBytesLeft, and web::websocket::Receiver::readFrameData().
Referenced by web::websocket::Receiver::receive().
readFrameData()
std::size_t web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::readFrameData (char * chunk, std::size_t chunkLen) inline override private virtual inherited
Implements web::websocket::Receiver.
Definition at line 217 of file SocketContextUpgrade.h.
{
            return readFromPeer(chunk, chunkLen);
        }
readFromPeer()
std::size_t core::socket::stream::SocketContext::readFromPeer (char * chunk, std::size_t chunklen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 54 of file SocketContext.cpp.
{
        return socketConnection->readFromPeer(chunk, chunklen);
    }
References core::socket::stream::SocketConnection::readFromPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::decoder::HTTP10Response::read(), web::http::decoder::Identity::read(), web::http::decoder::Chunked::Chunk::read(), web::http::Parser::readHeaderLine(), web::http::Parser::readStartLine(), and iot::mqtt::SocketContext::recv().
readLength()
std::size_t web::websocket::Receiver::readLength () private inherited
Definition at line 98 of file Receiver.cpp.
{
        char byte = 0;
        const std::size_t ret = readFrameData(&byte, 1);
        if (ret > 0) {
            const uint8_t lengthByte = static_cast<uint8_t>(byte);
            masked = (lengthByte & 0b10000000) != 0;
            payLoadNumBytes = payLoadNumBytesLeft = lengthByte & 0b01111111;
            if (payLoadNumBytes > 125) {
                switch (payLoadNumBytes) {
                    case 126:
                        elengthNumBytes = elengthNumBytesLeft = 2;
                        break;
                    case 127:
                        elengthNumBytes = elengthNumBytesLeft = 8;
                        break;
                }
                parserState = ParserState::ELENGTH;
                payLoadNumBytes = payLoadNumBytesLeft = 0;
            } else {
                if (masked) {
                    parserState = ParserState::MASKINGKEY;
                } else if (payLoadNumBytes > 0) {
                    parserState = ParserState::PAYLOAD;
                } else {
                    if (fin) {
                        onMessageEnd();
                    }
                    reset();
                }
            }
        }
        return ret;
    }
References web::websocket::Receiver::ELENGTH, web::websocket::Receiver::elengthNumBytes, web::websocket::Receiver::elengthNumBytesLeft, web::websocket::Receiver::fin, web::websocket::Receiver::masked, web::websocket::Receiver::MASKINGKEY, web::websocket::Receiver::onMessageEnd(), web::websocket::Receiver::PAYLOAD, web::websocket::Receiver::payLoadNumBytes, web::websocket::Receiver::payLoadNumBytesLeft, web::websocket::Receiver::readFrameData(), and web::websocket::Receiver::reset().
Referenced by web::websocket::Receiver::receive().
readMaskingKey()
std::size_t web::websocket::Receiver::readMaskingKey () private inherited
Definition at line 168 of file Receiver.cpp.
{
        const std::size_t ret = readFrameData(maskingKeyChunk, maskingKeyNumBytesLeft);
        for (std::size_t i = 0; i < ret; i++) {
            maskingKey |= static_cast<uint32_t>(*reinterpret_cast<unsigned char*>(maskingKeyChunk + i))
                          << (maskingKeyNumBytes - maskingKeyNumBytesLeft) * 8;
            maskingKeyNumBytesLeft--;
        }
        if (maskingKeyNumBytesLeft == 0) {
            maskingKeyAsArray = {.key = maskingKey};
            if (payLoadNumBytes > 0) {
                parserState = ParserState::PAYLOAD;
            } else {
                if (fin) {
                    onMessageEnd();
                }
                reset();
            }
        }
        return ret;
    }
References web::websocket::Receiver::fin, web::websocket::Receiver::MaskingKey::key, web::websocket::Receiver::maskingKey, web::websocket::Receiver::maskingKeyAsArray, web::websocket::Receiver::maskingKeyChunk, web::websocket::Receiver::maskingKeyNumBytes, web::websocket::Receiver::maskingKeyNumBytesLeft, web::websocket::Receiver::onMessageEnd(), web::websocket::Receiver::PAYLOAD, web::websocket::Receiver::payLoadNumBytes, web::websocket::Receiver::readFrameData(), and web::websocket::Receiver::reset().
Referenced by web::websocket::Receiver::receive().
readOpcode()
std::size_t web::websocket::Receiver::readOpcode () private inherited
Definition at line 72 of file Receiver.cpp.
{
        char byte = 0;
        const std::size_t ret = readFrameData(&byte, 1);
        if (ret > 0) {
            const uint8_t opCodeByte = static_cast<uint8_t>(byte);
            fin = (opCodeByte & 0b10000000) != 0;
            opCode = opCodeByte & 0b00001111;
            if (!continuation) {
                onMessageStart(opCode);
                parserState = ParserState::LENGTH;
            } else if (opCode == 0) {
                parserState = ParserState::LENGTH;
            } else {
                parserState = ParserState::ERROR;
                errorState = 1002;
                LOG(DEBUG) << "WebSocket: Error opcode in continuation frame";
            }
            continuation = !fin;
        }
        return ret;
    }
References web::websocket::Receiver::continuation, web::websocket::Receiver::ERROR, web::websocket::Receiver::errorState, web::websocket::Receiver::fin, web::websocket::Receiver::LENGTH, web::websocket::Receiver::onMessageStart(), web::websocket::Receiver::opCode, and web::websocket::Receiver::readFrameData().
Referenced by web::websocket::Receiver::receive().
readPayload()
std::size_t web::websocket::Receiver::readPayload () private inherited
Definition at line 193 of file Receiver.cpp.
{
        const std::size_t payloadChunkLeft = (MAX_PAYLOAD_JUNK_LEN <= payLoadNumBytesLeft) ? static_cast<std::size_t>(MAX_PAYLOAD_JUNK_LEN)
                                                                                           : static_cast<std::size_t>(payLoadNumBytesLeft);
        const std::size_t ret = readFrameData(payloadChunk, payloadChunkLeft);
        if (ret > 0) {
            const std::size_t payloadChunkLen = static_cast<std::size_t>(ret);
            if (masked) {
                for (std::size_t i = 0; i < payloadChunkLen; i++) {
                    *(payloadChunk + i) =
                        *(payloadChunk + i) ^ *(maskingKeyAsArray.keyAsArray + (i + payLoadNumBytes - payLoadNumBytesLeft) % 4);
                }
            }
            onMessageData(payloadChunk, payloadChunkLen);
            payLoadNumBytesLeft -= payloadChunkLen;
        }
        if (payLoadNumBytesLeft == 0) {
            if (fin) {
                onMessageEnd();
            }
            reset();
        }
        return ret;
    }
References web::websocket::Receiver::fin, web::websocket::Receiver::MaskingKey::keyAsArray, web::websocket::Receiver::masked, web::websocket::Receiver::maskingKeyAsArray, web::websocket::Receiver::onMessageData(), web::websocket::Receiver::onMessageEnd(), web::websocket::Receiver::payloadChunk, web::websocket::Receiver::payLoadNumBytes, web::websocket::Receiver::payLoadNumBytesLeft, web::websocket::Receiver::readFrameData(), and web::websocket::Receiver::reset().
Referenced by web::websocket::Receiver::receive().
receive()
std::size_t web::websocket::Receiver::receive () inherited
Definition at line 35 of file Receiver.cpp.
{
        std::size_t ret = 0;
        std::size_t consumed = 0;
        // dumpFrame(chunk, chunkLen);
        do {
            switch (parserState) {
                case ParserState::BEGIN:
                    parserState = ParserState::OPCODE;
                    [[fallthrough]];
                case ParserState::OPCODE:
                    ret = readOpcode();
                    break;
                case ParserState::LENGTH:
                    ret = readLength();
                    break;
                case ParserState::ELENGTH:
                    ret = readELength();
                    break;
                case ParserState::MASKINGKEY:
                    ret = readMaskingKey();
                    break;
                case ParserState::PAYLOAD:
                    ret = readPayload();
                    break;
                case ParserState::ERROR:
                    onMessageError(errorState);
                    reset();
                    break;
            }
            consumed += ret;
        } while (ret > 0 && parserState != ParserState::BEGIN && parserState != ParserState::ERROR);
        return consumed;
    }
References web::websocket::Receiver::BEGIN, web::websocket::Receiver::ELENGTH, web::websocket::Receiver::ERROR, web::websocket::Receiver::errorState, web::websocket::Receiver::LENGTH, web::websocket::Receiver::MASKINGKEY, web::websocket::Receiver::onMessageError(), web::websocket::Receiver::OPCODE, web::websocket::Receiver::PAYLOAD, web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), web::websocket::Receiver::readMaskingKey(), web::websocket::Receiver::readOpcode(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::reset().
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onReceivedFromPeer().
reset()
void web::websocket::Receiver::reset () private inherited
Definition at line 224 of file Receiver.cpp.
{
        parserState = ParserState::BEGIN;
        fin = false;
        continuation = false;
        masked = false;
        opCode = 0;
        elengthNumBytes = 0;
        elengthNumBytesLeft = 0;
        payLoadNumBytes = 0;
        payLoadNumBytesLeft = 0;
        maskingKey = 0;
        maskingKeyAsArray = {.key = 0};
        maskingKeyNumBytes = 4;
        maskingKeyNumBytesLeft = 4;
        errorState = 0;
    }
References web::websocket::Receiver::BEGIN, web::websocket::Receiver::continuation, web::websocket::Receiver::elengthNumBytes, web::websocket::Receiver::elengthNumBytesLeft, web::websocket::Receiver::errorState, web::websocket::Receiver::fin, web::websocket::Receiver::MaskingKey::key, web::websocket::Receiver::masked, web::websocket::Receiver::maskingKey, web::websocket::Receiver::maskingKeyAsArray, web::websocket::Receiver::maskingKeyNumBytes, web::websocket::Receiver::maskingKeyNumBytesLeft, web::websocket::Receiver::opCode, web::websocket::Receiver::payLoadNumBytes, and web::websocket::Receiver::payLoadNumBytesLeft.
Referenced by web::websocket::Receiver::readLength(), web::websocket::Receiver::readMaskingKey(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::receive().
send()
void web::websocket::Transmitter::send (bool end, uint8_t opCode, const char * message, std::size_t messageLength) private inherited
Definition at line 55 of file Transmitter.cpp.
{
        std::size_t messageOffset = 0;
        do {
            const std::size_t sendFrameLength =
                (messageLength - messageOffset <= WSMAXFRAMEPAYLOADLENGTH) ? messageLength - messageOffset : WSMAXFRAMEPAYLOADLENGTH;
            const bool fin = (sendFrameLength == messageLength - messageOffset) && end; // cppcheck-suppress knownConditionTrueFalse
            sendFrame(fin, opCode, message + messageOffset, sendFrameLength);
            messageOffset += sendFrameLength;
            opCode = 0; // continuation
        } while (messageLength - messageOffset > 0);
    }
References web::websocket::Transmitter::sendFrame(), and WSMAXFRAMEPAYLOADLENGTH.
Referenced by web::websocket::Transmitter::sendMessage(), web::websocket::Transmitter::sendMessageEnd(), web::websocket::Transmitter::sendMessageFrame(), and web::websocket::Transmitter::sendMessageStart().
sendClose() [1/2]
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendClose (const char * message, std::size_t messageLength) inline override private virtual inherited
Implements web::websocket::SubProtocolContext.
Definition at line 131 of file SocketContextUpgrade.h.
{
            if (!closeSent) {
                LOG(DEBUG) << "WebSocket: Sending close to peer";
                sendMessage(8, message, messageLength);
                setTimeout(CLOSE_SOCKET_TIMEOUT);
                closeSent = true;
            }
        }
sendClose() [2/2]
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendClose (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0) inline override private virtual inherited
Implements web::websocket::SubProtocolContext.
Definition at line 116 of file SocketContextUpgrade.h.
{
            std::size_t closePayloadLength = reasonLength + 2;
            char* closePayload = new char[closePayloadLength];
            *reinterpret_cast<uint16_t*>(closePayload) = htobe16(statusCode); // cppcheck-suppress uninitdata
            if (reasonLength > 0) {
                memcpy(closePayload + 2, reason, reasonLength);
            }
            sendClose(closePayload, closePayloadLength);
            delete[] closePayload;
        }
sendFrame()
void web::websocket::Transmitter::sendFrame (bool fin, uint8_t opCode, const char * payload, uint64_t payloadLength) private inherited
Definition at line 72 of file Transmitter.cpp.
{
        uint64_t length = 0;
        if (payloadLength < 126) {
            length = payloadLength;
        } else if (payloadLength < 0x10000) {
            length = 126;
        } else {
            length = 127;
        }
        char header[2];
        header[0] = static_cast<char>((fin ? 0b10000000 : 0) | opCode);
        header[1] = static_cast<char>((masking ? 0b10000000 : 0) | length);
        sendFrameData(header, 2);
        switch (length) {
            case 126:
                sendFrameData(static_cast<uint16_t>(payloadLength));
                break;
            case 127:
                sendFrameData(payloadLength);
                break;
        }
        union MaskingKey {
            uint32_t keyAsValue;
            char keyAsBytes[4];
        };
        MaskingKey maskingKeyAsArray = {.keyAsValue = distribution(randomDevice)};
        if (masking) {
            sendFrameData(htobe32(maskingKeyAsArray.keyAsValue));
            for (uint64_t i = 0; i < payloadLength; i++) {
                *(const_cast<char*>(payload) + i) = static_cast<char>(*(payload + i) ^ *(maskingKeyAsArray.keyAsBytes + i % 4));
            }
        }
        sendFrameData(payload, payloadLength);
        if (masking) {
            for (uint64_t i = 0; i < payloadLength; i++) {
                *(const_cast<char*>(payload) + i) = static_cast<char>(*(payload + i) ^ *(maskingKeyAsArray.keyAsBytes + i % 4));
            }
        }
    }
References web::websocket::Transmitter::distribution, web::websocket::Transmitter::masking, web::websocket::Transmitter::randomDevice, web::websocket::Transmitter::sendFrameData(), web::websocket::Transmitter::sendFrameData(), web::websocket::Transmitter::sendFrameData(), and web::websocket::Transmitter::sendFrameData().
Referenced by web::websocket::Transmitter::send().
sendFrameData() [1/5]
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendFrameData (const char * frame, uint64_t frameLength) const inline override private virtual inherited
Implements web::websocket::Transmitter.
Definition at line 264 of file SocketContextUpgrade.h.
{
            if (!closeSent) {
                uint64_t frameOffset = 0;
                do {
                    std::size_t sendChunkLen =
                        (frameLength - frameOffset <= SIZE_MAX) ? static_cast<std::size_t>(frameLength - frameOffset) : SIZE_MAX;
                    sendToPeer(frame + frameOffset, sendChunkLen);
                    frameOffset += sendChunkLen;
                } while (frameLength - frameOffset > 0);
            }
        }
sendFrameData() [2/5]
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendFrameData (uint16_t data) const inline override private virtual inherited
Implements web::websocket::Transmitter.
Definition at line 243 of file SocketContextUpgrade.h.
{
            if (!closeSent) {
                uint16_t sendData = htobe16(data);
                sendToPeer(reinterpret_cast<char*>(&sendData), sizeof(uint16_t));
            }
        }
sendFrameData() [3/5]
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendFrameData (uint32_t data) const inline override private virtual inherited
Implements web::websocket::Transmitter.
Definition at line 250 of file SocketContextUpgrade.h.
{
            if (!closeSent) {
                uint32_t sendData = htobe32(data);
                sendToPeer(reinterpret_cast<char*>(&sendData), sizeof(uint32_t));
            }
        }
sendFrameData() [4/5]
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendFrameData (uint64_t data) const inline override private virtual inherited
Implements web::websocket::Transmitter.
Definition at line 257 of file SocketContextUpgrade.h.
{
            if (!closeSent) {
                uint64_t sendData = htobe64(data);
                sendToPeer(reinterpret_cast<char*>(&sendData), sizeof(uint64_t));
            }
        }
sendFrameData() [5/5]
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendFrameData (uint8_t data) const inline override private virtual inherited
Implements web::websocket::Transmitter.
Definition at line 237 of file SocketContextUpgrade.h.
{
            if (!closeSent) {
                sendToPeer(reinterpret_cast<char*>(&data), sizeof(uint8_t));
            }
        }
sendMessage()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendMessage (uint8_t opCode, const char * message, std::size_t messageLength) inline override private virtual inherited
Implements web::websocket::SubProtocolContext.
Definition at line 92 of file SocketContextUpgrade.h.
{
            Transmitter::sendMessage(opCode, message, messageLength);
        }
sendMessageEnd()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendMessageEnd (const char * message, std::size_t messageLength) inline override private virtual inherited
Implements web::websocket::SubProtocolContext.
Definition at line 104 of file SocketContextUpgrade.h.
{
            Transmitter::sendMessageEnd(message, messageLength);
        }
sendMessageFrame()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendMessageFrame (const char * message, std::size_t messageLength) inline override private virtual inherited
Implements web::websocket::SubProtocolContext.
Definition at line 100 of file SocketContextUpgrade.h.
{
            Transmitter::sendMessageFrame(message, messageLength);
        }
sendMessageStart()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendMessageStart (uint8_t opCode, const char * message, std::size_t messageLength) inline override private virtual inherited
Implements web::websocket::SubProtocolContext.
Definition at line 96 of file SocketContextUpgrade.h.
{
            Transmitter::sendMessageStart(opCode, message, messageLength);
        }
sendPing()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendPing (const char * reason = nullptr, std::size_t reasonLength = 0) inline override private virtual inherited
Implements web::websocket::SubProtocolContext.
Definition at line 108 of file SocketContextUpgrade.h.
{
            sendMessage(9, reason, reasonLength);
        }
sendPong()
void web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::sendPong (const char * reason = nullptr, std::size_t reasonLength = 0) inline override private virtual inherited
Implements web::websocket::SubProtocolContext.
Definition at line 112 of file SocketContextUpgrade.h.
{
            sendMessage(10, reason, reasonLength);
        }
sendToPeer() [1/3]
void core::socket::stream::SocketContext::sendToPeer (const char * chunk, std::size_t chunkLen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 42 of file SocketContext.cpp.
{
        socketConnection->sendToPeer(chunk, chunkLen);
    }
References core::socket::stream::SocketConnection::sendToPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::Request::executeSendFragment(), iot::mqtt::SocketContext::send(), iot::mqtt_fast::SocketContext::send(), and web::http::server::Response::sendFragment().
sendToPeer() [2/3]
virtual void core::socket::SocketContext::sendToPeer (const char * chunk, std::size_t chunkLen) const virtual inherited
Implements core::socket::SocketContext.
sendToPeer() [3/3]
void core::socket::SocketContext::sendToPeer (const std::string & data) const inherited
Definition at line 53 of file SocketContext.cpp.
{
        sendToPeer(data.data(), data.length());
    }
setTimeout()
void core::socket::stream::SocketContext::setTimeout (const utils::Timeval & timeout) final virtual inherited
Implements core::socket::SocketContext.
Definition at line 58 of file SocketContext.cpp.
{
        socketConnection->setTimeout(timeout);
    }
References core::socket::stream::SocketConnection::setTimeout(), and core::socket::stream::SocketContext::socketConnection.
shutdownRead()
void core::socket::stream::SocketContext::shutdownRead () inherited
Definition at line 66 of file SocketContext.cpp.
{
        socketConnection->shutdownRead();
    }
References core::socket::stream::SocketConnection::shutdownRead(), and core::socket::stream::SocketContext::socketConnection.
Referenced by core::socket::stream::SocketContext::onWriteError().
shutdownWrite()
void core::socket::stream::SocketContext::shutdownWrite (bool forceClose = false) inherited
Definition at line 70 of file SocketContext.cpp.
{
        socketConnection->shutdownWrite(forceClose);
    }
References core::socket::stream::SocketConnection::shutdownWrite(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::SocketContext::dispatchNextRequest(), iot::mqtt::SocketContext::end(), core::socket::stream::SocketContext::onReadError(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestCompleted(), web::http::server::SocketContext::requestParseError(), web::http::client::SocketContext::requestSent(), web::http::server::SocketContext::responseCompleted(), web::http::client::SocketContext::responseError(), and web::http::client::SocketContext::responseStarted().
streamEof()
void core::socket::stream::SocketContext::streamEof () inherited
Definition at line 50 of file SocketContext.cpp.
{
        socketConnection->streamEof();
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::streamEof().
Referenced by web::http::client::Request::onSourceEof(), web::http::server::Response::onSourceEof(), web::http::client::Request::onSourceError(), web::http::server::Response::onSourceError(), web::http::client::Request::~Request(), and web::http::server::Response::~Response().
streamToPeer()
bool core::socket::stream::SocketContext::streamToPeer (core::pipe::Source * source) const inherited
Definition at line 46 of file SocketContext.cpp.
{
        return socketConnection->streamToPeer(source);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::streamToPeer().
Referenced by web::http::client::Request::onSourceConnect(), and web::http::server::Response::onSourceConnect().
switchSocketContext()
void core::socket::stream::SocketContext::switchSocketContext (SocketContext * newSocketContext) virtual inherited
Definition at line 34 of file SocketContext.cpp.
{
        socketConnection->switchSocketContext(newSocketContext);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::switchSocketContext().
Referenced by web::http::server::Response::sendCompleted().
Member Data Documentation
closeSent
bool web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::closeSent private inherited
Definition at line 286 of file SocketContextUpgrade.h.
continuation
bool web::websocket::Receiver::continuation = false private inherited
Definition at line 72 of file Receiver.h.
Referenced by web::websocket::Receiver::readOpcode(), and web::websocket::Receiver::reset().
distribution
std::uniform_int_distribution<uint32_t> web::websocket::Transmitter::distribution {0, UINT32_MAX} private inherited
Definition at line 63 of file Transmitter.h.
{0, UINT32_MAX};
Referenced by web::websocket::Transmitter::sendFrame().
elengthChunk
char web::websocket::Receiver::elengthChunk[8] {} private inherited
Definition at line 90 of file Receiver.h.
{};
Referenced by web::websocket::Receiver::readELength().
elengthNumBytes
uint8_t web::websocket::Receiver::elengthNumBytes = 0 private inherited
Definition at line 77 of file Receiver.h.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), and web::websocket::Receiver::reset().
elengthNumBytesLeft
uint8_t web::websocket::Receiver::elengthNumBytesLeft = 0 private inherited
Definition at line 78 of file Receiver.h.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), and web::websocket::Receiver::reset().
errorState
uint16_t web::websocket::Receiver::errorState = 0 private inherited
Definition at line 88 of file Receiver.h.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readOpcode(), web::websocket::Receiver::receive(), and web::websocket::Receiver::reset().
fin
bool web::websocket::Receiver::fin = false private inherited
Definition at line 71 of file Receiver.h.
Referenced by web::websocket::Receiver::readLength(), web::websocket::Receiver::readMaskingKey(), web::websocket::Receiver::readOpcode(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::reset().
masked
bool web::websocket::Receiver::masked = false private inherited
Definition at line 73 of file Receiver.h.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::reset().
masking
bool web::websocket::Transmitter::masking = false private inherited
Definition at line 65 of file Transmitter.h.
Referenced by web::websocket::Transmitter::sendFrame(), and web::websocket::Transmitter::Transmitter().
maskingKey
uint32_t web::websocket::Receiver::maskingKey = 0 private inherited
Definition at line 83 of file Receiver.h.
Referenced by web::websocket::Receiver::readMaskingKey(), and web::websocket::Receiver::reset().
maskingKeyAsArray
MaskingKey web::websocket::Receiver::maskingKeyAsArray {} private inherited
Definition at line 84 of file Receiver.h.
{};
Referenced by web::websocket::Receiver::readMaskingKey(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::reset().
maskingKeyChunk
char web::websocket::Receiver::maskingKeyChunk[4] {} private inherited
Definition at line 91 of file Receiver.h.
{};
Referenced by web::websocket::Receiver::readMaskingKey().
maskingKeyNumBytes
uint8_t web::websocket::Receiver::maskingKeyNumBytes = 4 private inherited
Definition at line 85 of file Receiver.h.
Referenced by web::websocket::Receiver::readMaskingKey(), and web::websocket::Receiver::reset().
maskingKeyNumBytesLeft
uint8_t web::websocket::Receiver::maskingKeyNumBytesLeft = 4 private inherited
Definition at line 86 of file Receiver.h.
Referenced by web::websocket::Receiver::readMaskingKey(), and web::websocket::Receiver::reset().
opCode
uint8_t web::websocket::Receiver::opCode = 0 private inherited
Definition at line 75 of file Receiver.h.
Referenced by web::websocket::Receiver::readOpcode(), and web::websocket::Receiver::reset().
parserState
enum web::websocket::Receiver::ParserState web::websocket::Receiver::parserState = ParserState::BEGIN private inherited
payloadChunk
char web::websocket::Receiver::payloadChunk[16384] {} private inherited
Definition at line 92 of file Receiver.h.
{};
Referenced by web::websocket::Receiver::readPayload().
payLoadNumBytes
uint64_t web::websocket::Receiver::payLoadNumBytes = 0 private inherited
Definition at line 80 of file Receiver.h.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), web::websocket::Receiver::readMaskingKey(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::reset().
payLoadNumBytesLeft
uint64_t web::websocket::Receiver::payLoadNumBytesLeft = 0 private inherited
Definition at line 81 of file Receiver.h.
Referenced by web::websocket::Receiver::readELength(), web::websocket::Receiver::readLength(), web::websocket::Receiver::readPayload(), and web::websocket::Receiver::reset().
pongCloseData
std::string web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::pongCloseData private inherited
Definition at line 290 of file SocketContextUpgrade.h.
randomDevice
std::random_device web::websocket::Transmitter::randomDevice private inherited
Definition at line 62 of file Transmitter.h.
Referenced by web::websocket::Transmitter::sendFrame().
receivedOpCode
int web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::receivedOpCode private inherited
Definition at line 288 of file SocketContextUpgrade.h.
socketConnection
core::socket::stream::SocketConnection* core::socket::stream::SocketContext::socketConnection private inherited
Definition at line 78 of file SocketContext.h.
Referenced by core::socket::stream::SocketContext::close(), core::socket::stream::SocketContext::getSocketConnection(), core::socket::stream::SocketContext::readFromPeer(), core::socket::stream::SocketContext::sendToPeer(), core::socket::stream::SocketContext::setTimeout(), core::socket::stream::SocketContext::shutdownRead(), core::socket::stream::SocketContext::shutdownWrite(), core::socket::stream::SocketContext::SocketContext(), core::socket::stream::SocketContext::streamEof(), core::socket::stream::SocketContext::streamToPeer(), and core::socket::stream::SocketContext::switchSocketContext().
socketContextUpgradeFactory
template<typename RequestT , typename ResponseT > SocketContextUpgradeFactory* web::http::SocketContextUpgrade< RequestT, ResponseT >::socketContextUpgradeFactory = nullptr private inherited
Definition at line 56 of file SocketContextUpgrade.h.
Referenced by web::http::SocketContextUpgrade< RequestT, ResponseT >::SocketContextUpgrade(), and web::http::SocketContextUpgrade< RequestT, ResponseT >::~SocketContextUpgrade().
subProtocol
SubProtocol* web::websocket::SocketContextUpgrade< SubProtocol , web::http::client::Request , web::http::client::Response >::subProtocol protected inherited
Definition at line 283 of file SocketContextUpgrade.h.
subProtocolFactory
web::websocket::SubProtocolFactory<SubProtocol>* web::websocket::client::SocketContextUpgrade::subProtocolFactory = nullptr private
Definition at line 61 of file SocketContextUpgrade.h.
Referenced by loadSubProtocol(), and ~SocketContextUpgrade().
The documentation for this class was generated from the following files:
web/websocket/client/SocketContextUpgrade.h
web/websocket/client/SocketContextUpgrade.cpp