SNode.C: CLI::CallForCommandline Class Reference
CLI::CallForCommandline Class Reference
Public Types
enum class Mode {
REQUIRED , CONFIGURED , ALL , REQUIRED ,
CONFIGURED , ALL
}
enum class Mode {
REQUIRED , CONFIGURED , ALL , REQUIRED ,
CONFIGURED , ALL
}
Public Member Functions
CallForCommandline (CLI::App *app, Mode mode)
~CallForCommandline () override
CLI::App * getApp () const
Mode getMode () const
CallForCommandline (CLI::App *app, Mode mode)
~CallForCommandline () override
CLI::App * getApp () const
Mode getMode () const
Private Attributes
CLI::App * app
Mode mode
Detailed Description
Definition at line 66 of file Config.cpp.
Member Enumeration Documentation
Mode [1/2]
enum class CLI::CallForCommandline::Mode strong
Enumerator
REQUIRED
CONFIGURED
ALL
REQUIRED
CONFIGURED
ALL
Definition at line 68 of file Config.cpp.
{ REQUIRED, CONFIGURED, ALL };
Mode [2/2]
enum class CLI::CallForCommandline::Mode strong
Enumerator
REQUIRED
CONFIGURED
ALL
REQUIRED
CONFIGURED
ALL
Definition at line 68 of file Config.cpp.
{ REQUIRED, CONFIGURED, ALL };
Constructor & Destructor Documentation
CallForCommandline() [1/2]
CLI::CallForCommandline::CallForCommandline (CLI::App * app, Mode mode) inline
Definition at line 70 of file Config.cpp.
            : CLI::Success("CallForCommandline", "A template command line is showen below:\n", CLI::ExitCodes::Success)
            , app(app)
            , mode(mode) {
        }
References app, and mode.
Referenced by utils::Config::add_instance(), and utils::Config::init().
~CallForCommandline() [1/2]
CLI::CallForCommandline::~CallForCommandline () override
Definition at line 91 of file Config.cpp.
{
    }
CallForCommandline() [2/2]
CLI::CallForCommandline::CallForCommandline (CLI::App * app, Mode mode) inline
Definition at line 70 of file Config.cpp.
            : CLI::Success("CallForCommandline", "A template command line is showen below:\n", CLI::ExitCodes::Success)
            , app(app)
            , mode(mode) {
        }
~CallForCommandline() [2/2]
CLI::CallForCommandline::~CallForCommandline () override
Member Function Documentation
getApp() [1/2]
CLI::App * CLI::CallForCommandline::getApp () const inline
Definition at line 78 of file Config.cpp.
{
            return app;
        }
References app.
Referenced by utils::Config::parse2().
getApp() [2/2]
CLI::App * CLI::CallForCommandline::getApp () const inline
Definition at line 78 of file Config.cpp.
{
            return app;
        }
getMode() [1/2]
Mode CLI::CallForCommandline::getMode () const inline
Definition at line 82 of file Config.cpp.
{
            return mode;
        }
References mode.
Referenced by utils::Config::parse2().
getMode() [2/2]
Mode CLI::CallForCommandline::getMode () const inline
Definition at line 82 of file Config.cpp.
{
            return mode;
        }
Member Data Documentation
app
CLI::App * CLI::CallForCommandline::app private
Definition at line 87 of file Config.cpp.
Referenced by CallForCommandline(), and getApp().
mode
Mode CLI::CallForCommandline::mode private
Definition at line 88 of file Config.cpp.
Referenced by CallForCommandline(), and getMode().
The documentation for this class was generated from the following file:
utils/Config.cpp