SNode.C: web::http::server::Response Class Reference
web::http::server::Response Class Reference
#include <Response.h>
Public Member Functions
Response (SocketContext *socketContext)
Response (Response &)=delete
Response (Response &&) noexcept=delete
Response & operator= (Response &)=delete
Response & operator= (Response &&) noexcept=delete
~Response () override
void stopResponse ()
Response & status (int statusCode)
Response & append (const std::string &field, const std::string &value)
Response & set (const std::string &field, const std::string &value, bool overwrite=true)
Response & set (const std::map< std::string, std::string > &headers, bool overwrite=true)
Response & type (const std::string &type)
Response & cookie (const std::string &name, const std::string &value, const std::map< std::string, std::string > &options={})
Response & clearCookie (const std::string &name, const std::map< std::string, std::string > &options={})
Response & setTrailer (const std::string &field, const std::string &value, bool overwrite=true)
void send (const char *chunk, std::size_t chunkLen)
void send (const std::string &chunk)
void sendStatus (int statusCode)
void upgrade (const std::shared_ptr< Request > &request, const std::function< void(const std::string &)> &status)
void sendFile (const std::string &file, const std::function< void(int)> &callback)
void end ()
Response & sendHeader ()
Response & sendFragment (const char *chunk, std::size_t chunkLen)
Response & sendFragment (const std::string &chunk)
const std::string & header (const std::string &field)
SocketContext * getSocketContext () const
Public Member Functions inherited from core::pipe::Sink
Sink (Sink &)=delete
Sink & operator= (Sink &)=delete
Public Attributes
int statusCode = 200
int httpMajor = 1
int httpMinor = 1
Protected Attributes
web::http::CiStringMap< std::string > headers
web::http::CiStringMap< web::http::CookieOptions > cookies
web::http::CiStringMap< std::string > trailer
Private Member Functions
virtual void init ()
void sendCompleted ()
void onSourceConnect (core::pipe::Source *source) override
void onSourceData (const char *chunk, std::size_t chunkLen) override
void onSourceEof () override
void onSourceError (int errnum) override
Private Attributes
std::size_t contentSent = 0
std::size_t contentLength = 0
SocketContext * socketContext = nullptr
core::socket::stream::SocketContext * socketContextUpgrade = nullptr
ConnectionState connectionState = ConnectionState::Default
TransferEncoding transferEncoding = TransferEncoding::HTTP10
Friends
class SocketContext
Additional Inherited Members
Protected Member Functions inherited from core::pipe::Sink
Sink ()=default
Sink (Sink &&) noexcept=default
Sink & operator= (Sink &&) noexcept=default
virtual ~Sink ()
bool isStreaming ()
void stop ()
Detailed Description
Definition at line 73 of file Response.h.
Constructor & Destructor Documentation
Response() [1/3]
web::http::server::Response::Response (SocketContext * socketContext) explicit
Definition at line 72 of file Response.cpp.
        : socketContext(socketContext) {
    }
References socketContext.
Response() [2/3]
web::http::server::Response::Response (Response &) explicit delete
Response() [3/3]
web::http::server::Response::Response (Response &&) explicit delete noexcept
~Response()
web::http::server::Response::~Response () override
Definition at line 76 of file Response.cpp.
{
        if (socketContext != nullptr && Sink::isStreaming()) {
            socketContext->streamEof();
        }
        delete socketContextUpgrade; // delete of nullptr is valid since C++14!
    }
References core::pipe::Sink::isStreaming(), socketContext, socketContextUpgrade, and core::socket::stream::SocketContext::streamEof().
Member Function Documentation
append()
Response & web::http::server::Response::append (const std::string & field, const std::string & value)
Definition at line 108 of file Response.cpp.
{
        const std::map<std::string, std::string>::iterator it = headers.find(field);
        if (it != headers.end()) {
            set(field, it->second.append(", ").append(value));
        } else {
            set(field, value);
        }
        return *this;
    }
References headers, and set().
Referenced by express::Response::append().
clearCookie()
Response & web::http::server::Response::clearCookie (const std::string & name, const std::map< std::string, std::string > & options = {})
Definition at line 184 of file Response.cpp.
{
        std::map<std::string, std::string> opts = options;
        opts.erase("Max-Age");
        const time_t time = 0;
        opts["Expires"] = httputils::to_http_date(utils::system::gmtime(&time));
        return cookie(name, "", opts);
    }
References cookie(), utils::system::gmtime(), and httputils::to_http_date().
Referenced by express::Response::clearCookie().
cookie()
Response & web::http::server::Response::cookie (const std::string & name, const std::string & value, const std::map< std::string, std::string > & options = {})
Definition at line 178 of file Response.cpp.
{
        cookies.insert({name, CookieOptions(value, options)});
        return *this;
    }
References web::http::CookieOptions::CookieOptions(), and cookies.
Referenced by clearCookie(), and express::Response::cookie().
end()
void web::http::server::Response::end ()
Definition at line 330 of file Response.cpp.
                       {
        send("");
    }
References send().
Referenced by express::Response::end().
getSocketContext()
SocketContext * web::http::server::Response::getSocketContext () const
Definition at line 457 of file Response.cpp.
{
        return socketContext;
    }
References socketContext.
Referenced by express::Response::getSocketContext().
header()
const std::string & web::http::server::Response::header (const std::string & field)
Definition at line 453 of file Response.cpp.
{
        return headers[field];
    }
References headers.
Referenced by express::Response::header().
init()
void web::http::server::Response::init () private virtual
Definition at line 88 of file Response.cpp.
{
        statusCode = 200;
        httpMajor = 1;
        httpMinor = 1;
        headers.clear();
        cookies.clear();
        trailer.clear();
        contentLength = 0;
        contentSent = 0;
        socketContextUpgrade = nullptr;
        connectionState = ConnectionState::Default;
        transferEncoding = TransferEncoding::HTTP10;
    }
References connectionState, contentLength, contentSent, cookies, web::http::Default, headers, web::http::HTTP10, httpMajor, httpMinor, socketContextUpgrade, statusCode, trailer, and transferEncoding.
Referenced by web::http::server::SocketContext::deliverRequest(), and web::http::server::SocketContext::onConnected().
onSourceConnect()
void web::http::server::Response::onSourceConnect (core::pipe::Source * source) override private virtual
Implements core::pipe::Sink.
Definition at line 416 of file Response.cpp.
{
        if (socketContext != nullptr) {
            if (socketContext->streamToPeer(source)) {
                sendHeader();
                source->start();
            } else {
                source->stop();
            }
        } else {
            source->stop();
        }
    }
References sendHeader(), socketContext, core::pipe::Source::start(), core::pipe::Source::stop(), and core::socket::stream::SocketContext::streamToPeer().
onSourceData()
void web::http::server::Response::onSourceData (const char * chunk, std::size_t chunkLen) override private virtual
Implements core::pipe::Sink.
Definition at line 430 of file Response.cpp.
{
        sendFragment(chunk, chunkLen);
    }
References sendFragment().
onSourceEof()
void web::http::server::Response::onSourceEof () override private virtual
Implements core::pipe::Sink.
Definition at line 434 of file Response.cpp.
{
        if (socketContext != nullptr) {
            socketContext->streamEof();
        }
        sendCompleted();
    }
References sendCompleted(), socketContext, and core::socket::stream::SocketContext::streamEof().
onSourceError()
void web::http::server::Response::onSourceError (int errnum) override private virtual
Implements core::pipe::Sink.
Definition at line 442 of file Response.cpp.
{
        errno = errnum;
        if (socketContext != nullptr) {
            socketContext->streamEof();
            socketContext->close();
        }
        sendCompleted();
    }
References core::socket::stream::SocketContext::close(), sendCompleted(), socketContext, and core::socket::stream::SocketContext::streamEof().
operator=() [1/2]
Response & web::http::server::Response::operator= (Response &&) delete noexcept
operator=() [2/2]
Response & web::http::server::Response::operator= (Response &) delete
send() [1/2]
void web::http::server::Response::send (const char * chunk, std::size_t chunkLen)
Definition at line 213 of file Response.cpp.
{
        if (chunkLen > 0) {
            set("Content-Type", "application/octet-stream", false);
        }
        set("Content-Length", std::to_string(chunkLen));
        sendHeader();
        sendFragment(chunk, chunkLen);
        sendCompleted();
    }
References sendCompleted(), sendFragment(), sendHeader(), and set().
Referenced by express::Response::send(), and send().
send() [2/2]
void web::http::server::Response::send (const std::string & chunk)
Definition at line 224 of file Response.cpp.
{
        if (!chunk.empty()) {
            set("Content-Type", "text/html; charset=utf-8", false);
        }
        send(chunk.data(), chunk.size());
    }
References send(), and set().
Referenced by end(), express::Response::send(), and sendStatus().
sendCompleted()
void web::http::server::Response::sendCompleted () private
Definition at line 393 of file Response.cpp.
{
        if (transferEncoding == TransferEncoding::Chunked) {
            sendFragment(""); // For transfer encoding chunked. Terminate the chunk sequence.
            if (!trailer.empty()) {
                for (auto& [field, value] : trailer) {
                    socketContext->sendToPeer(std::string(field).append(":").append(value).append("\r\n"));
                }
                socketContext->sendToPeer("\r\n");
            }
        }
        if (socketContext != nullptr) {
            socketContext->responseCompleted(contentSent == contentLength || (httpMajor == 1 && httpMinor == 0));
            if (socketContextUpgrade != nullptr) {
                socketContext->switchSocketContext(socketContextUpgrade);
                socketContextUpgrade = nullptr;
            }
        }
    }
References web::http::Chunked, contentLength, contentSent, httpMajor, httpMinor, web::http::server::SocketContext::responseCompleted(), sendFragment(), core::socket::SocketContext::sendToPeer(), socketContext, socketContextUpgrade, core::socket::stream::SocketContext::switchSocketContext(), trailer, and transferEncoding.
Referenced by onSourceEof(), onSourceError(), and send().
sendFile()
void web::http::server::Response::sendFile (const std::string & file, const std::function< void(int)> & callback)
Definition at line 292 of file Response.cpp.
{
        if (socketContext != nullptr) {
            std::string absolutFileName = file;
            if (std::filesystem::exists(absolutFileName)) {
                std::error_code ec;
                absolutFileName = std::filesystem::canonical(absolutFileName);
                if (std::filesystem::is_regular_file(absolutFileName, ec) && !ec) {
                    core::file::FileReader::open(absolutFileName)->pipe(this, [this, &absolutFileName, &callback](int errnum) {
                        callback(errnum);
                        if (errnum == 0) {
                            set("Content-Type", web::http::MimeTypes::contentType(absolutFileName), false);
                            set("Last-Modified", httputils::file_mod_http_date(absolutFileName), false);
                            if (httpMajor == 1) {
                                if (httpMinor == 1) {
                                    set("Transfer-Encoding", "chunked");
                                } else {
                                    set("Content-Length", std::to_string(std::filesystem::file_size(absolutFileName)));
                                }
                            }
                        } else {
                            status(404);
                        }
                    });
                } else {
                    status(404);
                    errno = EEXIST;
                    callback(errno);
                }
            } else {
                errno = ENOENT;
                callback(errno);
            }
        }
    }
References web::http::MimeTypes::contentType(), httputils::file_mod_http_date(), httpMajor, httpMinor, core::file::FileReader::open(), core::pipe::Source::pipe(), set(), socketContext, and status().
Referenced by express::Response::sendFile().
sendFragment() [1/2]
Response & web::http::server::Response::sendFragment (const char * chunk, std::size_t chunkLen)
Definition at line 371 of file Response.cpp.
{
        if (socketContext != nullptr) {
            if (transferEncoding == TransferEncoding::Chunked) {
                socketContext->sendToPeer(to_hex_str(chunkLen).append("\r\n"));
            }
            socketContext->sendToPeer(chunk, chunkLen);
            contentSent += chunkLen;
            if (transferEncoding == TransferEncoding::Chunked) {
                socketContext->sendToPeer("\r\n");
                contentLength += chunkLen;
            }
        }
        return *this;
    }
References web::http::Chunked, contentLength, contentSent, core::socket::stream::SocketContext::sendToPeer(), core::socket::SocketContext::sendToPeer(), socketContext, and transferEncoding.
Referenced by onSourceData(), send(), express::Response::sendFragment(), and sendFragment().
sendFragment() [2/2]
Response & web::http::server::Response::sendFragment (const std::string & chunk)
Definition at line 389 of file Response.cpp.
{
        return sendFragment(chunk.data(), chunk.size());
    }
References sendFragment().
Referenced by sendCompleted(), and express::Response::sendFragment().
sendHeader()
Response & web::http::server::Response::sendHeader ()
Definition at line 334 of file Response.cpp.
{
        if (socketContext != nullptr) {
            socketContext->responseStarted();
            socketContext->sendToPeer("HTTP/" + std::to_string(httpMajor)
                                                    .append(".")
                                                    .append(std::to_string(httpMinor))
                                                    .append(" ")
                                                    .append(std::to_string(statusCode))
                                                    .append(" ")
                                                    .append(StatusCode::reason(statusCode))
                                                    .append("\r\n"));
            socketContext->sendToPeer("Date: " + httputils::to_http_date() + "\r\n");
            set("X-Powered-By", "snode.c");
            for (const auto& [field, value] : headers) {
                socketContext->sendToPeer(std::string(field).append(": ").append(value).append("\r\n"));
            }
            for (const auto& [cookie, cookieValue] : cookies) {
                const std::string cookieString = std::accumulate(
                    cookieValue.getOptions().begin(),
                    cookieValue.getOptions().end(),
                    cookie + "=" + cookieValue.getValue(),
                    [](const std::string& str, const std::pair<const std::string&, const std::string&> option) -> std::string {
                        return str + "; " + option.first + (!option.second.empty() ? "=" + option.second : "");
                    });
                socketContext->sendToPeer("Set-Cookie: " + cookieString + "\r\n");
            }
            socketContext->sendToPeer("\r\n");
        }
        return *this;
    }
References cookies, web::http::CookieOptions::getOptions(), web::http::CookieOptions::getValue(), headers, httpMajor, httpMinor, web::http::StatusCode::reason(), web::http::server::SocketContext::responseStarted(), core::socket::SocketContext::sendToPeer(), set(), socketContext, statusCode, and httputils::to_http_date().
Referenced by onSourceConnect(), send(), and express::Response::sendHeader().
sendStatus()
void web::http::server::Response::sendStatus (int statusCode)
Definition at line 232 of file Response.cpp.
{
        status(statusCode);
        send(StatusCode::reason(statusCode));
    }
References web::http::StatusCode::reason(), send(), and status().
set() [1/2]
Response & web::http::server::Response::set (const std::map< std::string, std::string > & headers, bool overwrite = true)
Definition at line 120 of file Response.cpp.
{
        for (const auto& [field, value] : headers) {
            set(field, value, overwrite);
        }
        return *this;
    }
References set().
Referenced by express::Response::set().
set() [2/2]
Response & web::http::server::Response::set (const std::string & field, const std::string & value, bool overwrite = true)
Definition at line 128 of file Response.cpp.
{
        if (!value.empty()) {
            if (overwrite) {
                headers.insert_or_assign(field, value);
            } else {
                headers.insert({field, value});
            }
            if (web::http::ciEquals(field, "Connection")) {
                if (web::http::ciContains(headers[field], "keep-alive")) {
                    connectionState = ConnectionState::Keep;
                } else if (web::http::ciContains(headers[field], "close")) {
                    connectionState = ConnectionState::Close;
                }
            } else if (web::http::ciEquals(field, "Content-Length")) {
                contentLength = std::stoul(value);
                transferEncoding = TransferEncoding::Identity;
                headers.erase("Transfer-Encoding");
            } else if (web::http::ciEquals(field, "Transfer-Encoding")) {
                if (web::http::ciContains(headers[field], "chunked")) {
                    transferEncoding = TransferEncoding::Chunked;
                    headers.erase("Content-Length");
                }
                if (web::http::ciContains(headers[field], "compressed")) {
                }
                if (web::http::ciContains(headers[field], "deflate")) {
                }
                if (web::http::ciContains(headers[field], "gzip")) {
                }
            } else if (web::http::ciEquals(field, "Content-Encoding")) {
                if (web::http::ciContains(headers[field], "compressed")) {
                }
                if (web::http::ciContains(headers[field], "deflate")) {
                }
                if (web::http::ciContains(headers[field], "gzip")) {
                }
                if (web::http::ciContains(headers[field], "br")) {
                }
            }
        } else {
            headers.erase(field);
        }
        return *this;
    }
References web::http::Chunked, web::http::ciContains(), web::http::ciEquals(), web::http::Close, connectionState, contentLength, headers, web::http::Identity, web::http::Keep, and transferEncoding.
Referenced by append(), web::websocket::server::SocketContextUpgradeFactory::create(), web::http::server::SocketContext::deliverRequest(), send(), send(), sendFile(), sendHeader(), set(), express::Response::set(), setTrailer(), type(), and upgrade().
setTrailer()
Response & web::http::server::Response::setTrailer (const std::string & field, const std::string & value, bool overwrite = true)
Definition at line 194 of file Response.cpp.
{
        if (!value.empty()) {
            if (overwrite) {
                trailer.insert_or_assign(field, value);
            } else {
                trailer.insert({field, value});
            }
            if (!headers.contains("Trailer")) {
                set("Trailer", field);
            } else {
                headers["Trailer"].append("," + field);
            }
        } else {
            trailer.erase(field);
        }
        return *this;
    }
References headers, set(), and trailer.
Referenced by express::Response::setTrailer().
status()
Response & web::http::server::Response::status (int statusCode)
Definition at line 102 of file Response.cpp.
{
        this->statusCode = statusCode;
        return *this;
    }
References statusCode.
Referenced by web::websocket::server::SocketContextUpgradeFactory::create(), sendFile(), sendStatus(), express::Response::status(), and upgrade().
stopResponse()
void web::http::server::Response::stopResponse ()
Definition at line 84 of file Response.cpp.
{
        stop();
    }
References core::pipe::Sink::stop().
Referenced by web::http::server::SocketContext::onDisconnected().
type()
Response & web::http::server::Response::type (const std::string & type)
Definition at line 174 of file Response.cpp.
{
        return set("Content-Type", type);
    }
References set().
Referenced by express::Response::type().
upgrade()
void web::http::server::Response::upgrade (const std::shared_ptr< Request > & request, const std::function< void(const std::string &)> & status)
Sequence diagram of res.upgrade(req).
Definition at line 244 of file Response.cpp.
{
        std::string name;
        if (socketContext != nullptr) {
            if (request != nullptr) {
                if (web::http::ciContains(request->get("connection"), "Upgrade")) {
                    web::http::server::SocketContextUpgradeFactory* socketContextUpgradeFactory =
                        web::http::server::SocketContextUpgradeFactorySelector::instance()->select(*request, *this);
                    if (socketContextUpgradeFactory != nullptr) {
                        name = socketContextUpgradeFactory->name();
                        LOG(DEBUG) << socketContext->getSocketConnection()->getConnectionName()
                                   << " HTTP upgrade: SocketContextUpgradeFactory created successful: " << name;
                        socketContextUpgrade = socketContextUpgradeFactory->create(socketContext->getSocketConnection());
                        if (socketContextUpgrade != nullptr) {
                            LOG(DEBUG) << socketContext->getSocketConnection()->getConnectionName()
                                       << " HTTP upgrade: SocketContextUpgrade created successful: " << name;
                        } else {
                            LOG(DEBUG) << socketContext->getSocketConnection()->getConnectionName()
                                       << " HTTP upgrade: Create SocketContextUpgrade failed: " << name;
                            set("Connection", "close").status(404);
                        }
                    } else {
                        LOG(DEBUG) << socketContext->getSocketConnection()->getConnectionName()
                                   << " HTTP upgrade: SocketContextUpgradeFactory not supported: " << request->get("upgrade");
                        set("Connection", "close").status(404);
                    }
                } else {
                    LOG(DEBUG) << socketContext->getSocketConnection()->getConnectionName() << " HTTP upgrade: No upgrade requested";
                    set("Connection", "close").status(400);
                }
            } else {
                LOG(ERROR) << socketContext->getSocketConnection()->getConnectionName() << " HTTP upgrade: Request has gone away";
                set("Connection", "close").status(500);
            }
        } else {
            LOG(ERROR) << "HTTP upgrade: SocketContext has gone away";
        }
        status(name);
    }
References web::http::ciContains(), web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::create(), web::http::server::Request::get(), core::socket::stream::SocketConnection::getConnectionName(), core::socket::stream::SocketContext::getSocketConnection(), web::http::server::SocketContextUpgradeFactorySelector::instance(), web::http::SocketContextUpgradeFactory< RequestT, ResponseT >::name(), web::http::server::SocketContextUpgradeFactorySelector::select(), set(), socketContext, socketContextUpgrade, and status().
Referenced by express::Response::upgrade().
Friends And Related Symbol Documentation
SocketContext
friend class SocketContext friend
Definition at line 143 of file Response.h.
Member Data Documentation
connectionState
ConnectionState web::http::server::Response::connectionState = ConnectionState::Default private
Definition at line 140 of file Response.h.
Referenced by init(), web::http::server::SocketContext::responseCompleted(), and set().
contentLength
std::size_t web::http::server::Response::contentLength = 0 private
Definition at line 135 of file Response.h.
Referenced by init(), sendCompleted(), sendFragment(), and set().
contentSent
std::size_t web::http::server::Response::contentSent = 0 private
Definition at line 134 of file Response.h.
Referenced by init(), sendCompleted(), and sendFragment().
cookies
web::http::CiStringMap<web::http::CookieOptions> web::http::server::Response::cookies protected
Definition at line 130 of file Response.h.
Referenced by cookie(), init(), and sendHeader().
headers
web::http::CiStringMap<std::string> web::http::server::Response::headers protected
Definition at line 129 of file Response.h.
Referenced by append(), header(), init(), sendHeader(), set(), and setTrailer().
httpMajor
int web::http::server::Response::httpMajor = 1
Definition at line 125 of file Response.h.
Referenced by web::http::server::SocketContext::deliverRequest(), init(), web::http::server::SocketContext::responseCompleted(), sendCompleted(), sendFile(), and sendHeader().
httpMinor
int web::http::server::Response::httpMinor = 1
Definition at line 126 of file Response.h.
Referenced by web::http::server::SocketContext::deliverRequest(), init(), web::http::server::SocketContext::responseCompleted(), sendCompleted(), sendFile(), and sendHeader().
socketContext
SocketContext* web::http::server::Response::socketContext = nullptr private
Definition at line 137 of file Response.h.
Referenced by getSocketContext(), onSourceConnect(), onSourceEof(), onSourceError(), Response(), sendCompleted(), sendFile(), sendFragment(), sendHeader(), upgrade(), and ~Response().
socketContextUpgrade
core::socket::stream::SocketContext* web::http::server::Response::socketContextUpgrade = nullptr private
Definition at line 138 of file Response.h.
Referenced by init(), sendCompleted(), upgrade(), and ~Response().
statusCode
int web::http::server::Response::statusCode = 200
Definition at line 124 of file Response.h.
Referenced by init(), sendHeader(), and status().
trailer
web::http::CiStringMap<std::string> web::http::server::Response::trailer protected
Definition at line 131 of file Response.h.
Referenced by init(), sendCompleted(), and setTrailer().
transferEncoding
TransferEncoding web::http::server::Response::transferEncoding = TransferEncoding::HTTP10 private
Definition at line 141 of file Response.h.
Referenced by init(), sendCompleted(), sendFragment(), and set().
The documentation for this class was generated from the following files:
web/http/server/Response.h
web/http/server/Response.cpp