SNode.C: express::WebApp Class Reference
express::WebApp Class Reference
#include <WebApp.h>
Public Member Functions
void laxRouting (bool strict=false)
Route & use (const Router &router)
Route & use (const std::string &relativeMountPath, const Router &router)
Route & use (const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & all (const Router &router)
Route & all (const std::string &relativeMountPath, const Router &router)
Route & all (const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & get (const Router &router)
Route & get (const std::string &relativeMountPath, const Router &router)
Route & get (const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & put (const Router &router)
Route & put (const std::string &relativeMountPath, const Router &router)
Route & put (const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & post (const Router &router)
Route & post (const std::string &relativeMountPath, const Router &router)
Route & post (const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & del (const Router &router)
Route & del (const std::string &relativeMountPath, const Router &router)
Route & del (const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & connect (const Router &router)
Route & connect (const std::string &relativeMountPath, const Router &router)
Route & connect (const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & options (const Router &router)
Route & options (const std::string &relativeMountPath, const Router &router)
Route & options (const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & trace (const Router &router)
Route & trace (const std::string &relativeMountPath, const Router &router)
Route & trace (const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & patch (const Router &router)
Route & patch (const std::string &relativeMountPath, const Router &router)
Route & patch (const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & head (const Router &router)
Route & head (const std::string &relativeMountPath, const Router &router)
Route & head (const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Static Public Member Functions
static void init (int argc, char *argv[])
static int start (const utils::Timeval &timeOut={LONG_MAX, 0})
static void stop ()
static core::TickStatus tick (const utils::Timeval &timeOut=0)
static void free ()
static core::State state ()
Protected Member Functions
WebApp (const Router &router)
Protected Attributes
std::shared_ptr< RootRoute > rootRoute = nullptr
Detailed Description
Definition at line 36 of file WebApp.h.
Constructor & Destructor Documentation
WebApp()
express::WebApp::WebApp (const Router & router) explicit protected
Definition at line 29 of file WebApp.cpp.
        : Router(router) {
    }
Member Function Documentation
all() [1/10]
Route & express::Router::all (const Router & router) inherited
Definition at line 57 of file Router.cpp.
all() [2/10]
Route & express::Router::all (const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 57 of file Router.cpp.
all() [3/10]
template<typename... Lambdas> Route & express::Router::all (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 63 of file Router.hpp.
all() [4/10]
Route & express::Router::all (const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 57 of file Router.cpp.
all() [5/10]
template<typename... Lambdas> Route & express::Router::all (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 63 of file Router.hpp.
all() [6/10]
Route & express::Router::all (const std::string & relativeMountPath, const Router & router) inherited
Definition at line 57 of file Router.cpp.
all() [7/10]
Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 57 of file Router.cpp.
all() [8/10]
template<typename... Lambdas> Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 63 of file Router.hpp.
all() [9/10]
Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 57 of file Router.cpp.
all() [10/10]
template<typename... Lambdas> Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 63 of file Router.hpp.
connect() [1/10]
Route & express::Router::connect (const Router & router) inherited
Definition at line 62 of file Router.cpp.
connect() [2/10]
Route & express::Router::connect (const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 62 of file Router.cpp.
connect() [3/10]
template<typename... Lambdas> Route & express::Router::connect (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 68 of file Router.hpp.
connect() [4/10]
Route & express::Router::connect (const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 62 of file Router.cpp.
connect() [5/10]
template<typename... Lambdas> Route & express::Router::connect (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 68 of file Router.hpp.
connect() [6/10]
Route & express::Router::connect (const std::string & relativeMountPath, const Router & router) inherited
Definition at line 62 of file Router.cpp.
connect() [7/10]
Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 62 of file Router.cpp.
connect() [8/10]
template<typename... Lambdas> Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 68 of file Router.hpp.
connect() [9/10]
Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 62 of file Router.cpp.
connect() [10/10]
template<typename... Lambdas> Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 68 of file Router.hpp.
del() [1/10]
Route & express::Router::del (const Router & router) inherited
Definition at line 61 of file Router.cpp.
del() [2/10]
Route & express::Router::del (const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 61 of file Router.cpp.
del() [3/10]
template<typename... Lambdas> Route & express::Router::del (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 67 of file Router.hpp.
del() [4/10]
Route & express::Router::del (const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 61 of file Router.cpp.
del() [5/10]
template<typename... Lambdas> Route & express::Router::del (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 67 of file Router.hpp.
del() [6/10]
Route & express::Router::del (const std::string & relativeMountPath, const Router & router) inherited
Definition at line 61 of file Router.cpp.
del() [7/10]
Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 61 of file Router.cpp.
del() [8/10]
template<typename... Lambdas> Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 67 of file Router.hpp.
del() [9/10]
Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 61 of file Router.cpp.
del() [10/10]
template<typename... Lambdas> Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 67 of file Router.hpp.
free()
void express::WebApp::free () static
Definition at line 49 of file WebApp.cpp.
                      {
        core::SNodeC::free();
    }
References core::SNodeC::free().
get() [1/10]
Route & express::Router::get (const Router & router) inherited
Definition at line 58 of file Router.cpp.
get() [2/10]
Route & express::Router::get (const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 58 of file Router.cpp.
get() [3/10]
template<typename... Lambdas> Route & express::Router::get (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 64 of file Router.hpp.
get() [4/10]
Route & express::Router::get (const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 58 of file Router.cpp.
get() [5/10]
template<typename... Lambdas> Route & express::Router::get (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 64 of file Router.hpp.
get() [6/10]
Route & express::Router::get (const std::string & relativeMountPath, const Router & router) inherited
Definition at line 58 of file Router.cpp.
get() [7/10]
Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 58 of file Router.cpp.
get() [8/10]
template<typename... Lambdas> Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 64 of file Router.hpp.
get() [9/10]
Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 58 of file Router.cpp.
get() [10/10]
template<typename... Lambdas> Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 64 of file Router.hpp.
head() [1/10]
Route & express::Router::head (const Router & router) inherited
Definition at line 66 of file Router.cpp.
head() [2/10]
Route & express::Router::head (const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 66 of file Router.cpp.
head() [3/10]
template<typename... Lambdas> Route & express::Router::head (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 72 of file Router.hpp.
head() [4/10]
Route & express::Router::head (const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 66 of file Router.cpp.
head() [5/10]
template<typename... Lambdas> Route & express::Router::head (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 72 of file Router.hpp.
head() [6/10]
Route & express::Router::head (const std::string & relativeMountPath, const Router & router) inherited
Definition at line 66 of file Router.cpp.
head() [7/10]
Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 66 of file Router.cpp.
head() [8/10]
template<typename... Lambdas> Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 72 of file Router.hpp.
head() [9/10]
Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 66 of file Router.cpp.
head() [10/10]
template<typename... Lambdas> Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 72 of file Router.hpp.
init()
void express::WebApp::init (int argc, char * argv[]) static
Definition at line 33 of file WebApp.cpp.
{
        core::SNodeC::init(argc, argv);
    }
References core::SNodeC::init().
laxRouting()
void express::Router::laxRouting (bool strict = false) inherited
Definition at line 52 of file Router.cpp.
{
        rootRoute->strict = strict;
    }
References express::Router::rootRoute, and express::RootRoute::strict.
options() [1/10]
Route & express::Router::options (const Router & router) inherited
Definition at line 63 of file Router.cpp.
options() [2/10]
Route & express::Router::options (const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 63 of file Router.cpp.
options() [3/10]
template<typename... Lambdas> Route & express::Router::options (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 69 of file Router.hpp.
options() [4/10]
Route & express::Router::options (const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 63 of file Router.cpp.
options() [5/10]
template<typename... Lambdas> Route & express::Router::options (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 69 of file Router.hpp.
options() [6/10]
Route & express::Router::options (const std::string & relativeMountPath, const Router & router) inherited
Definition at line 63 of file Router.cpp.
options() [7/10]
Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 63 of file Router.cpp.
options() [8/10]
template<typename... Lambdas> Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 69 of file Router.hpp.
options() [9/10]
Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 63 of file Router.cpp.
options() [10/10]
template<typename... Lambdas> Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 69 of file Router.hpp.
patch() [1/10]
Route & express::Router::patch (const Router & router) inherited
Definition at line 65 of file Router.cpp.
patch() [2/10]
Route & express::Router::patch (const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 65 of file Router.cpp.
patch() [3/10]
template<typename... Lambdas> Route & express::Router::patch (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 71 of file Router.hpp.
patch() [4/10]
Route & express::Router::patch (const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 65 of file Router.cpp.
patch() [5/10]
template<typename... Lambdas> Route & express::Router::patch (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 71 of file Router.hpp.
patch() [6/10]
Route & express::Router::patch (const std::string & relativeMountPath, const Router & router) inherited
Definition at line 65 of file Router.cpp.
patch() [7/10]
Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 65 of file Router.cpp.
patch() [8/10]
template<typename... Lambdas> Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 71 of file Router.hpp.
patch() [9/10]
Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 65 of file Router.cpp.
patch() [10/10]
template<typename... Lambdas> Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 71 of file Router.hpp.
post() [1/10]
Route & express::Router::post (const Router & router) inherited
Definition at line 60 of file Router.cpp.
post() [2/10]
Route & express::Router::post (const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 60 of file Router.cpp.
post() [3/10]
template<typename... Lambdas> Route & express::Router::post (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 66 of file Router.hpp.
post() [4/10]
Route & express::Router::post (const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 60 of file Router.cpp.
post() [5/10]
template<typename... Lambdas> Route & express::Router::post (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 66 of file Router.hpp.
post() [6/10]
Route & express::Router::post (const std::string & relativeMountPath, const Router & router) inherited
Definition at line 60 of file Router.cpp.
post() [7/10]
Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 60 of file Router.cpp.
post() [8/10]
template<typename... Lambdas> Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 66 of file Router.hpp.
post() [9/10]
Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 60 of file Router.cpp.
post() [10/10]
template<typename... Lambdas> Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 66 of file Router.hpp.
put() [1/10]
Route & express::Router::put (const Router & router) inherited
Definition at line 59 of file Router.cpp.
put() [2/10]
Route & express::Router::put (const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 59 of file Router.cpp.
put() [3/10]
template<typename... Lambdas> Route & express::Router::put (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 65 of file Router.hpp.
put() [4/10]
Route & express::Router::put (const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 59 of file Router.cpp.
put() [5/10]
template<typename... Lambdas> Route & express::Router::put (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 65 of file Router.hpp.
put() [6/10]
Route & express::Router::put (const std::string & relativeMountPath, const Router & router) inherited
Definition at line 59 of file Router.cpp.
put() [7/10]
Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 59 of file Router.cpp.
put() [8/10]
template<typename... Lambdas> Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 65 of file Router.hpp.
put() [9/10]
Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 59 of file Router.cpp.
put() [10/10]
template<typename... Lambdas> Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 65 of file Router.hpp.
start()
int express::WebApp::start (const utils::Timeval & timeOut = {LONG_MAX, 0}) static
Definition at line 37 of file WebApp.cpp.
{
        return core::SNodeC::start(timeOut);
    }
References core::SNodeC::start().
state()
core::State express::WebApp::state () static
Definition at line 53 of file WebApp.cpp.
{
        return core::SNodeC::state();
    }
References core::SNodeC::state().
stop()
void express::WebApp::stop () static
Definition at line 41 of file WebApp.cpp.
                      {
        core::SNodeC::stop();
    }
References core::SNodeC::stop().
tick()
core::TickStatus express::WebApp::tick (const utils::Timeval & timeOut = 0) static
Definition at line 45 of file WebApp.cpp.
{
        return core::SNodeC::tick(timeOut);
    }
References core::SNodeC::tick().
trace() [1/10]
Route & express::Router::trace (const Router & router) inherited
Definition at line 64 of file Router.cpp.
trace() [2/10]
Route & express::Router::trace (const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 64 of file Router.cpp.
trace() [3/10]
template<typename... Lambdas> Route & express::Router::trace (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 70 of file Router.hpp.
trace() [4/10]
Route & express::Router::trace (const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 64 of file Router.cpp.
trace() [5/10]
template<typename... Lambdas> Route & express::Router::trace (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 70 of file Router.hpp.
trace() [6/10]
Route & express::Router::trace (const std::string & relativeMountPath, const Router & router) inherited
Definition at line 64 of file Router.cpp.
trace() [7/10]
Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 64 of file Router.cpp.
trace() [8/10]
template<typename... Lambdas> Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 70 of file Router.hpp.
trace() [9/10]
Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 64 of file Router.cpp.
trace() [10/10]
template<typename... Lambdas> Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 70 of file Router.hpp.
use() [1/10]
Route & express::Router::use (const Router & router) inherited
Definition at line 56 of file Router.cpp.
use() [2/10]
Route & express::Router::use (const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 56 of file Router.cpp.
use() [3/10]
template<typename... Lambdas> Route & express::Router::use (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 62 of file Router.hpp.
use() [4/10]
Route & express::Router::use (const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 56 of file Router.cpp.
use() [5/10]
template<typename... Lambdas> Route & express::Router::use (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 62 of file Router.hpp.
use() [6/10]
Route & express::Router::use (const std::string & relativeMountPath, const Router & router) inherited
Definition at line 56 of file Router.cpp.
use() [7/10]
Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda) inherited
Definition at line 56 of file Router.cpp.
use() [8/10]
template<typename... Lambdas> Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas) inherited
Definition at line 62 of file Router.hpp.
use() [9/10]
Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda) inherited
Definition at line 56 of file Router.cpp.
use() [10/10]
template<typename... Lambdas> Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas) inherited
Definition at line 62 of file Router.hpp.
Member Data Documentation
rootRoute
std::shared_ptr<RootRoute> express::Router::rootRoute = nullptr protected inherited
Definition at line 83 of file Router.h.
Referenced by express::Router::laxRouting(), and express::Router::Router().
The documentation for this class was generated from the following files:
express/WebApp.h
express/WebApp.cpp