SNode.C: IncorrectConstruction Class Reference
IncorrectConstruction Class Reference
Errors
Thrown when an option is set to conflicting values (non-vector and multi args, for example)
#include <CLI11.hpp>
Public Member Functions
IncorrectConstruction (std::string msg, ExitCodes exit_code)
IncorrectConstruction (std::string msg, int exit_code)
IncorrectConstruction (std::string msg)
Public Member Functions inherited from ConstructionError
ConstructionError (std::string msg, ExitCodes exit_code)
ConstructionError (std::string msg, int exit_code)
Public Member Functions inherited from Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Static Public Member Functions
static IncorrectConstruction PositionalFlag (std::string name)
static IncorrectConstruction Set0Opt (std::string name)
static IncorrectConstruction SetFlag (std::string name)
static IncorrectConstruction ChangeNotVector (std::string name)
static IncorrectConstruction AfterMultiOpt (std::string name)
static IncorrectConstruction MissingOption (std::string name)
static IncorrectConstruction MultiOptionPolicy (std::string name)
Protected Member Functions
IncorrectConstruction (std::string ename, std::string msg, int exit_code)
IncorrectConstruction (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from ConstructionError
ConstructionError (std::string ename, std::string msg, int exit_code)
ConstructionError (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
Thrown when an option is set to conflicting values (non-vector and multi args, for example)
Definition at line 1086 of file CLI11.hpp.
Constructor & Destructor Documentation
IncorrectConstruction() [1/5]
IncorrectConstruction::IncorrectConstruction (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 1087 of file CLI11.hpp.
IncorrectConstruction() [2/5]
IncorrectConstruction::IncorrectConstruction (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 1087 of file CLI11.hpp.
IncorrectConstruction() [3/5]
IncorrectConstruction::IncorrectConstruction (std::string msg, ExitCodes exit_code) inline
Definition at line 1087 of file CLI11.hpp.
IncorrectConstruction() [4/5]
IncorrectConstruction::IncorrectConstruction (std::string msg, int exit_code) inline
Definition at line 1087 of file CLI11.hpp.
IncorrectConstruction() [5/5]
IncorrectConstruction::IncorrectConstruction (std::string msg) inline explicit
Definition at line 1088 of file CLI11.hpp.
Member Function Documentation
AfterMultiOpt()
static IncorrectConstruction IncorrectConstruction::AfterMultiOpt (std::string name) inline static
Definition at line 1101 of file CLI11.hpp.
{
            return IncorrectConstruction(name + ": You can't change expected arguments after you've changed the multi option policy!");
        }
ChangeNotVector()
static IncorrectConstruction IncorrectConstruction::ChangeNotVector (std::string name) inline static
Definition at line 1098 of file CLI11.hpp.
{
            return IncorrectConstruction(name + ": You can only change the expected arguments for vectors");
        }
MissingOption()
static IncorrectConstruction IncorrectConstruction::MissingOption (std::string name) inline static
Definition at line 1104 of file CLI11.hpp.
{
            return IncorrectConstruction("Option " + name + " is not defined");
        }
Referenced by Option::excludes(), and Option::needs().
MultiOptionPolicy()
static IncorrectConstruction IncorrectConstruction::MultiOptionPolicy (std::string name) inline static
Definition at line 1107 of file CLI11.hpp.
{
            return IncorrectConstruction(name + ": multi_option_policy only works for flags and exact value options");
        }
PositionalFlag()
static IncorrectConstruction IncorrectConstruction::PositionalFlag (std::string name) inline static
Definition at line 1089 of file CLI11.hpp.
{
            return IncorrectConstruction(name + ": Flags cannot be positional");
        }
Referenced by App::_add_flag_internal().
Set0Opt()
static IncorrectConstruction IncorrectConstruction::Set0Opt (std::string name) inline static
Definition at line 1092 of file CLI11.hpp.
{
            return IncorrectConstruction(name + ": Cannot set 0 expected, use a flag instead");
        }
SetFlag()
static IncorrectConstruction IncorrectConstruction::SetFlag (std::string name) inline static
Definition at line 1095 of file CLI11.hpp.
{
            return IncorrectConstruction(name + ": Cannot set an expected number for flags");
        }
The documentation for this class was generated from the following file:
src/utils/CLI11.hpp