SNode.C: database::mariadb::MariaDBCommandSequence Class Reference
database::mariadb::MariaDBCommandSequence Class Reference
#include <MariaDBCommandSequence.h>
Public Member Functions
MariaDBCommandSequence ()=default
MariaDBCommandSequence (MariaDBCommandSequence &&mariaDBCommandSequence)=default
~MariaDBCommandSequence () override=default
MariaDBCommandSequence & operator= (MariaDBCommandSequence &&mariaDBCommandSequence)=default
MariaDBCommandSequence & query (const std::string &sql, const std::function< void(const MYSQL_ROW)> &onQuery, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & exec (const std::string &sql, const std::function< void(void)> &onExec, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & startTransactions (const std::function< void(void)> &onAutoCommit, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & endTransactions (const std::function< void(void)> &onAutoCommit, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & commit (const std::function< void(void)> &onCommit, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & rollback (const std::function< void(void)> &onRollback, const std::function< void(const std::string &, unsigned int)> &onError)
void affectedRows (const std::function< void(int)> &onAffectedRows, const std::function< void(const std::string &, unsigned int)> &onErro)
void fieldCount (const std::function< void(unsigned int)> &onFieldCount, const std::function< void(const std::string &, unsigned int)> &onError)
Protected Attributes
MYSQL_RES * lastResult = nullptr
Private Member Functions
MariaDBCommandSequence & execute_async (MariaDBCommand *mariaDBCommand) final
void execute_sync (MariaDBCommandSync *mariaDBCommand) final
std::deque< MariaDBCommand * > & sequence ()
MariaDBCommand * nextCommand ()
void commandCompleted ()
bool empty ()
Private Attributes
std::deque< MariaDBCommand * > commandSequence
Friends
class MariaDBConnection
class MariaDBClient
class MariaDBClientASyncAPI
Detailed Description
Definition at line 39 of file MariaDBCommandSequence.h.
Constructor & Destructor Documentation
MariaDBCommandSequence() [1/2]
database::mariadb::MariaDBCommandSequence::MariaDBCommandSequence () default
Referenced by database::mariadb::MariaDBClient::execute_async().
MariaDBCommandSequence() [2/2]
database::mariadb::MariaDBCommandSequence::MariaDBCommandSequence (MariaDBCommandSequence && mariaDBCommandSequence) default
~MariaDBCommandSequence()
database::mariadb::MariaDBCommandSequence::~MariaDBCommandSequence () override default
Member Function Documentation
affectedRows()
void database::mariadb::MariaDBClientSyncAPI::affectedRows (const std::function< void(int)> & onAffectedRows, const std::function< void(const std::string &, unsigned int)> & onErro) inherited
Definition at line 34 of file MariaDBClientSyncAPI.cpp.
{
        execute_sync(new database::mariadb::commands::sync::MariaDBAffectedRowsCommand(onAffectedRows, onError));
    }
commandCompleted()
void database::mariadb::MariaDBCommandSequence::commandCompleted () private
Definition at line 38 of file MariaDBCommandSequence.cpp.
{
        commandSequence.pop_front();
    }
commit()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::commit (const std::function< void(void)> & onCommit, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 79 of file MariaDBClientASyncAPI.cpp.
{
        return execute_async(new database::mariadb::commands::async::MariaDBCommitCommand(onCommit, onError));
    }
References database::mariadb::MariaDBClientASyncAPI::execute_async().
empty()
bool database::mariadb::MariaDBCommandSequence::empty () private
Definition at line 42 of file MariaDBCommandSequence.cpp.
{
        return commandSequence.empty();
    }
endTransactions()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::endTransactions (const std::function< void(void)> & onAutoCommit, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 74 of file MariaDBClientASyncAPI.cpp.
{
        return execute_async(new database::mariadb::commands::async::MariaDBAutoCommitCommand(true, onAutoCommit, onError));
    }
exec()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::exec (const std::string & sql, const std::function< void(void)> & onExec, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 63 of file MariaDBClientASyncAPI.cpp.
{
        return execute_async(new database::mariadb::commands::async::MariaDBExecCommand(sql, onExec, onError));
    }
References database::mariadb::MariaDBClientASyncAPI::execute_async().
execute_async()
MariaDBCommandSequence & database::mariadb::MariaDBCommandSequence::execute_async (MariaDBCommand * mariaDBCommand) final private virtual
Implements database::mariadb::MariaDBClientASyncAPI.
Definition at line 46 of file MariaDBCommandSequence.cpp.
{
        commandSequence.push_back(mariaDBCommand);
        return *this;
    }
Referenced by database::mariadb::MariaDBClient::execute_async().
execute_sync()
void database::mariadb::MariaDBCommandSequence::execute_sync (MariaDBCommandSync * mariaDBCommand) final private virtual
Implements database::mariadb::MariaDBClientSyncAPI.
Definition at line 52 of file MariaDBCommandSequence.cpp.
{
        commandSequence.push_back(mariaDBCommand);
    }
fieldCount()
void database::mariadb::MariaDBClientSyncAPI::fieldCount (const std::function< void(unsigned int)> & onFieldCount, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 39 of file MariaDBClientSyncAPI.cpp.
{
        execute_sync(new database::mariadb::commands::sync::MariaDBFieldCountCommand(onFieldCount, onError));
    }
References database::mariadb::MariaDBClientSyncAPI::execute_sync(), and database::mariadb::commands::sync::MariaDBFieldCountCommand::MariaDBFieldCountCommand().
nextCommand()
MariaDBCommand * database::mariadb::MariaDBCommandSequence::nextCommand () private
Definition at line 34 of file MariaDBCommandSequence.cpp.
{
        return commandSequence.front();
    }
operator=()
MariaDBCommandSequence & database::mariadb::MariaDBCommandSequence::operator= (MariaDBCommandSequence && mariaDBCommandSequence) default
query()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::query (const std::string & sql, const std::function< void(const MYSQL_ROW)> & onQuery, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 41 of file MariaDBClientASyncAPI.cpp.
{
        return execute_async(new database::mariadb::commands::async::MariaDBQueryCommand(
                                 sql,
                                 []() -> void {
                                 },
                                 onError))
            .execute_async(new database::mariadb::commands::sync::MariaDBUseResultCommand(
                [&lastResult = this->lastResult](MYSQL_RES* result) -> void {
                    lastResult = result;
                },
                onError))
            .execute_async(new database::mariadb::commands::async::MariaDBFetchRowCommand(lastResult, onQuery, onError))
            .execute_async(new database::mariadb::commands::async::MariaDBFreeResultCommand(
                lastResult,
                [this]() -> void {
                    lastResult = nullptr;
                },
                onError));
    }
rollback()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::rollback (const std::function< void(void)> & onRollback, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 84 of file MariaDBClientASyncAPI.cpp.
{
        return execute_async(new database::mariadb::commands::async::MariaDBRollbackCommand(onRollback, onError));
    }
References database::mariadb::MariaDBClientASyncAPI::execute_async().
sequence()
std::deque< MariaDBCommand * > & database::mariadb::MariaDBCommandSequence::sequence () private
Definition at line 30 of file MariaDBCommandSequence.cpp.
{
        return commandSequence;
    }
startTransactions()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::startTransactions (const std::function< void(void)> & onAutoCommit, const std::function< void(const std::string &, unsigned int)> & onError) inherited
Definition at line 69 of file MariaDBClientASyncAPI.cpp.
{
        return execute_async(new database::mariadb::commands::async::MariaDBAutoCommitCommand(false, onAutoCommit, onError));
    }
Friends And Related Symbol Documentation
MariaDBClient
friend class MariaDBClient friend
Definition at line 62 of file MariaDBCommandSequence.h.
MariaDBClientASyncAPI
friend class MariaDBClientASyncAPI friend
Definition at line 63 of file MariaDBCommandSequence.h.
MariaDBConnection
friend class MariaDBConnection friend
Definition at line 61 of file MariaDBCommandSequence.h.
Member Data Documentation
commandSequence
std::deque<MariaDBCommand*> database::mariadb::MariaDBCommandSequence::commandSequence private
Definition at line 59 of file MariaDBCommandSequence.h.
lastResult
MYSQL_RES* database::mariadb::MariaDBClientASyncAPI::lastResult = nullptr protected inherited
Definition at line 68 of file MariaDBClientASyncAPI.h.
The documentation for this class was generated from the following files:
database/mariadb/MariaDBCommandSequence.h
database/mariadb/MariaDBCommandSequence.cpp