SNode.C: iot::mqtt::client::packets::Unsuback Class Reference
iot::mqtt::client::packets::Unsuback Class Reference
#include <Unsuback.h>
Public Member Functions
Unsuback (uint32_t remainingLength, uint8_t flags)
Public Member Functions inherited from iot::mqtt::packets::Unsuback
Unsuback ()
Unsuback (const uint16_t packetIdentifier)
uint16_t getPacketIdentifier () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type)
ControlPacket (const ControlPacket &)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
std::vector< char > serialize () const
uint8_t getType () const
uint8_t getFlags () const
Public Member Functions inherited from iot::mqtt::client::ControlPacketDeserializer
~ControlPacketDeserializer () override
Public Member Functions inherited from iot::mqtt::ControlPacketDeserializer
ControlPacketDeserializer ()=default
ControlPacketDeserializer (uint32_t remainingLength, uint8_t flags, uint8_t mustFlags)
ControlPacketDeserializer & operator= (const ControlPacketDeserializer &)=default
std::size_t deserialize (iot::mqtt::MqttContext *mqttContext)
uint32_t getRemainingLength () const
bool isComplete () const
bool isError () const
std::size_t getConsumed () const
Private Member Functions
std::size_t deserializeVP (iot::mqtt::MqttContext *mqttContext) override
void deliverPacket (iot::mqtt::client::Mqtt *mqtt) override
Additional Inherited Members
Protected Attributes inherited from iot::mqtt::packets::Unsuback
iot::mqtt::types::UInt16 packetIdentifier
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t type = 0
uint8_t flags = 0
Protected Attributes inherited from iot::mqtt::ControlPacketDeserializer
bool complete = false
bool error = false
uint32_t remainingLength = 0
std::size_t consumed = 0
Detailed Description
Definition at line 38 of file Unsuback.h.
Constructor & Destructor Documentation
Unsuback()
iot::mqtt::client::packets::Unsuback::Unsuback (uint32_t remainingLength, uint8_t flags)
Definition at line 29 of file Unsuback.cpp.
        : iot::mqtt::client::ControlPacketDeserializer(remainingLength, flags, MQTT_UNSUBACK_FLAGS) {
        this->flags = flags;
    }
References iot::mqtt::ControlPacket::flags.
Referenced by iot::mqtt::client::Mqtt::createControlPacketDeserializer().
Member Function Documentation
deliverPacket()
void iot::mqtt::client::packets::Unsuback::deliverPacket (iot::mqtt::client::Mqtt * mqtt) override private virtual
Implements iot::mqtt::client::ControlPacketDeserializer.
Definition at line 44 of file Unsuback.cpp.
{
        mqtt->_onUnsuback(*this);
    }
References iot::mqtt::client::Mqtt::_onUnsuback().
deserializeVP()
std::size_t iot::mqtt::client::packets::Unsuback::deserializeVP (iot::mqtt::MqttContext * mqttContext) override private virtual
Implements iot::mqtt::ControlPacketDeserializer.
Definition at line 34 of file Unsuback.cpp.
{
        // V-Header
        std::size_t consumed = packetIdentifier.deserialize(mqttContext);
        complete = packetIdentifier.isComplete();
        // no Payload
        return consumed;
    }
References iot::mqtt::ControlPacketDeserializer::complete, iot::mqtt::types::TypeBase< ValueTypeT >::deserialize(), iot::mqtt::types::TypeBase< ValueTypeT >::isComplete(), and iot::mqtt::packets::Unsuback::packetIdentifier.
The documentation for this class was generated from the following files:
iot/mqtt/client/packets/Unsuback.h
iot/mqtt/client/packets/Unsuback.cpp