SNode.C: express::Response Class Reference
express::Response Class Reference
#include <Response.h>
Public Member Functions
Response (const std::shared_ptr< web::http::server::Response > &response) noexcept
Response (Response &)=delete
Response (Response &&) noexcept=delete
Response & operator= (Response &)=delete
Response & operator= (Response &&) noexcept=delete
~Response ()
bool isConnected () const
web::http::server::SocketContext * getSocketContext () const
void json (const nlohmann::json &json)
void download (const std::string &file, const std::function< void(int)> &onError)
void download (const std::string &file, const std::string &fileName, const std::function< void(int)> &onError)
void redirect (const std::string &loc, const std::string &html={})
void redirect (int state, const std::string &loc, const std::string &html={})
void sendStatus (int state, const std::string &html={})
Response & attachment (const std::string &fileName="")
Response & location (const std::string &loc)
Response & vary (const std::string &field)
Response & status (int status)
Response & append (const std::string &field, const std::string &value)
Response & set (const std::string &field, const std::string &value, bool overwrite=true)
Response & set (const std::map< std::string, std::string > &headers, bool overwrite=true)
Response & type (const std::string &type)
Response & cookie (const std::string &name, const std::string &value, const std::map< std::string, std::string > &options={})
Response & clearCookie (const std::string &name, const std::map< std::string, std::string > &options={})
Response & setTrailer (const std::string &field, const std::string &value, bool overwrite=true)
void send (const char *chunk, std::size_t chunkLen)
void send (const std::string &chunk)
void upgrade (const std::shared_ptr< Request > &request, const std::function< void(const std::string)> &status)
void end ()
void sendFile (const std::string &file, const std::function< void(int)> &callback)
Response & sendHeader ()
Response & sendFragment (const char *chunk, std::size_t chunkLen)
Response & sendFragment (const std::string &chunk="")
const std::string & header (const std::string &field)
Private Attributes
std::shared_ptr< web::http::server::Response > responseBase
Detailed Description
Definition at line 67 of file Response.h.
Constructor & Destructor Documentation
Response() [1/3]
express::Response::Response (const std::shared_ptr< web::http::server::Response > & response) explicit noexcept
Definition at line 57 of file Response.cpp.
        : responseBase(response) {
    }
References responseBase.
Response() [2/3]
express::Response::Response (Response &) explicit delete
Response() [3/3]
express::Response::Response (Response &&) explicit delete noexcept
~Response()
express::Response::~Response ()
Definition at line 61 of file Response.cpp.
{
    }
Member Function Documentation
append()
Response & express::Response::append (const std::string & field, const std::string & value)
Definition at line 123 of file Response.cpp.
{
        responseBase->append(field, value);
        return *this;
    }
References web::http::server::Response::append(), and responseBase.
Referenced by vary().
attachment()
Response & express::Response::attachment (const std::string & fileName = "")
Definition at line 99 of file Response.cpp.
{
        set("Content-Disposition", "attachment" + ((!fileName.empty()) ? ("; filename=\"" + fileName + "\"") : ""));
        return *this;
    }
References set().
Referenced by download().
clearCookie()
Response & express::Response::clearCookie (const std::string & name, const std::map< std::string, std::string > & options = {})
Definition at line 153 of file Response.cpp.
{
        responseBase->clearCookie(name, options);
        return *this;
    }
References web::http::server::Response::clearCookie(), and responseBase.
cookie()
Response & express::Response::cookie (const std::string & name, const std::string & value, const std::map< std::string, std::string > & options = {})
Definition at line 147 of file Response.cpp.
{
        responseBase->cookie(name, value, options);
        return *this;
    }
References web::http::server::Response::cookie(), and responseBase.
Referenced by express::middleware::StaticMiddleware::StaticMiddleware().
download() [1/2]
void express::Response::download (const std::string & file, const std::function< void(int)> & onError)
Definition at line 77 of file Response.cpp.
{
        download(file, std::filesystem::path(file).filename(), onError);
    }
References download().
download() [2/2]
void express::Response::download (const std::string & file, const std::string & fileName, const std::function< void(int)> & onError)
Definition at line 81 of file Response.cpp.
{
        attachment(fileName);
        sendFile(file, onError);
    }
References attachment(), and sendFile().
Referenced by download().
end()
void express::Response::end ()
Definition at line 177 of file Response.cpp.
                       {
        responseBase->end();
    }
References web::http::server::Response::end(), and responseBase.
Referenced by main().
getSocketContext()
web::http::server::SocketContext * express::Response::getSocketContext () const
Definition at line 68 of file Response.cpp.
{
        return responseBase->getSocketContext();
    }
References web::http::server::Response::getSocketContext(), and responseBase.
Referenced by express::dispatcher::ApplicationDispatcher::dispatch(), express::dispatcher::MiddlewareDispatcher::dispatch(), express::dispatcher::RouterDispatcher::dispatch(), main(), express::middleware::StaticMiddleware::StaticMiddleware(), and express::middleware::VerboseRequest::VerboseRequest().
header()
const std::string & express::Response::header (const std::string & field)
Definition at line 203 of file Response.cpp.
{
        return responseBase->header(field);
    }
References web::http::server::Response::header(), and responseBase.
isConnected()
bool express::Response::isConnected () const
Definition at line 64 of file Response.cpp.
{
        return responseBase->isConnected();
    }
References web::http::server::Response::isConnected(), and responseBase.
json()
void express::Response::json (const nlohmann::json & json)
Definition at line 72 of file Response.cpp.
{
        set("Content-Type", "application/json");
        send(json.dump());
    }
References send(), and set().
location()
Response & express::Response::location (const std::string & loc)
Definition at line 105 of file Response.cpp.
{
        set("Location", loc);
        return *this;
    }
References set().
Referenced by redirect().
operator=() [1/2]
Response & express::Response::operator= (Response &&) delete noexcept
operator=() [2/2]
Response & express::Response::operator= (Response &) delete
redirect() [1/2]
void express::Response::redirect (const std::string & loc, const std::string & html = {})
Definition at line 86 of file Response.cpp.
{
        redirect(302, loc, html);
    }
References redirect().
redirect() [2/2]
void express::Response::redirect (int state, const std::string & loc, const std::string & html = {})
Definition at line 90 of file Response.cpp.
{
        location(loc);
        sendStatus(state, html);
    }
References location(), and sendStatus().
Referenced by redirect(), and express::middleware::StaticMiddleware::StaticMiddleware().
send() [1/2]
void express::Response::send (const char * chunk, std::size_t chunkLen)
Definition at line 165 of file Response.cpp.
{
        responseBase->send(chunk, chunkLen);
    }
References responseBase, and web::http::server::Response::send().
send() [2/2]
void express::Response::send (const std::string & chunk)
Definition at line 169 of file Response.cpp.
{
        responseBase->send(chunk);
    }
References responseBase, and web::http::server::Response::send().
Referenced by json(), main(), sendStatus(), and express::middleware::StaticMiddleware::StaticMiddleware().
sendFile()
void express::Response::sendFile (const std::string & file, const std::function< void(int)> & callback)
Definition at line 181 of file Response.cpp.
{
        responseBase->sendFile(file, callback);
    }
References responseBase, and web::http::server::Response::sendFile().
Referenced by download(), main(), and express::middleware::StaticMiddleware::StaticMiddleware().
sendFragment() [1/2]
Response & express::Response::sendFragment (const char * chunk, std::size_t chunkLen)
Definition at line 191 of file Response.cpp.
{
        responseBase->sendFragment(chunk, chunkLen);
        return *this;
    }
References responseBase, and web::http::server::Response::sendFragment().
sendFragment() [2/2]
Response & express::Response::sendFragment (const std::string & chunk = "")
Definition at line 197 of file Response.cpp.
{
        responseBase->sendFragment(chunk);
        return *this;
    }
References responseBase, and web::http::server::Response::sendFragment().
sendHeader()
Response & express::Response::sendHeader ()
Definition at line 185 of file Response.cpp.
{
        responseBase->sendHeader();
        return *this;
    }
References responseBase, and web::http::server::Response::sendHeader().
sendStatus()
void express::Response::sendStatus (int state, const std::string & html = {})
Definition at line 95 of file Response.cpp.
{
        this->status(state).send(!html.empty() ? html : web::http::StatusCode::reason(state) + "\r\n");
    }
References web::http::StatusCode::reason(), send(), and status().
Referenced by express::middleware::BasicAuthentication::BasicAuthentication(), express::RootRoute::dispatch(), main(), redirect(), and express::middleware::StaticMiddleware::StaticMiddleware().
set() [1/2]
Response & express::Response::set (const std::map< std::string, std::string > & headers, bool overwrite = true)
Definition at line 135 of file Response.cpp.
{
        responseBase->set(headers, overwrite);
        return *this;
    }
References responseBase, and web::http::server::Response::set().
Referenced by express::middleware::StaticMiddleware::StaticMiddleware().
set() [2/2]
Response & express::Response::set (const std::string & field, const std::string & value, bool overwrite = true)
Definition at line 129 of file Response.cpp.
{
        responseBase->set(field, value, overwrite);
        return *this;
    }
References responseBase, and web::http::server::Response::set().
Referenced by attachment(), express::middleware::BasicAuthentication::BasicAuthentication(), json(), location(), main(), and express::middleware::StaticMiddleware::StaticMiddleware().
setTrailer()
Response & express::Response::setTrailer (const std::string & field, const std::string & value, bool overwrite = true)
Definition at line 159 of file Response.cpp.
{
        responseBase->setTrailer(field, value, overwrite);
        return *this;
    }
References responseBase, and web::http::server::Response::setTrailer().
status()
Response & express::Response::status (int status)
Definition at line 117 of file Response.cpp.
{
        responseBase->status(status);
        return *this;
    }
References responseBase, and web::http::server::Response::status().
Referenced by main(), sendStatus(), and express::middleware::StaticMiddleware::StaticMiddleware().
type()
Response & express::Response::type (const std::string & type)
Definition at line 141 of file Response.cpp.
{
        responseBase->type(type);
        return *this;
    }
References responseBase, and web::http::server::Response::type().
upgrade()
void express::Response::upgrade (const std::shared_ptr< Request > & request, const std::function< void(const std::string)> & status)
Definition at line 173 of file Response.cpp.
{
        responseBase->upgrade(request->requestBase, status);
    }
References express::Request::requestBase, responseBase, and web::http::server::Response::upgrade().
Referenced by main().
vary()
Response & express::Response::vary (const std::string & field)
Definition at line 111 of file Response.cpp.
{
        append("Vary", field);
        return *this;
    }
References append().
Member Data Documentation
responseBase
std::shared_ptr<web::http::server::Response> express::Response::responseBase private
Definition at line 97 of file Response.h.
Referenced by append(), clearCookie(), cookie(), end(), getSocketContext(), header(), isConnected(), Response(), send(), send(), sendFile(), sendFragment(), sendFragment(), sendHeader(), set(), set(), setTrailer(), status(), type(), and upgrade().
The documentation for this class was generated from the following files:
express/Response.h
express/Response.cpp