SNode.C: utils::Config Class Reference
utils::Config Class Reference
#include <Config.h>
Public Member Functions
Config ()=delete
Config (const Config &)=delete
~Config ()=delete
Config & operator= (const Config &)=delete
Static Public Member Functions
static bool init (int argc, char *argv[])
static bool bootstrap ()
static void terminate ()
static CLI::App * addInstance (const std::string &name, const std::string &description, const std::string &group)
static bool removeInstance (CLI::App *instance)
static void required (CLI::App *instance, bool reqired=true)
static void disabled (CLI::App *instance, bool disabled=true)
static CLI::App * addStandardFlags (CLI::App *app)
static CLI::App * addSimpleHelp (CLI::App *app)
static CLI::App * addHelp (CLI::App *app)
static std::string getApplicationName ()
static int getLogLevel ()
static int getVerboseLevel ()
static CLI::Option * addStringOption (const std::string &name, const std::string &description, const std::string &typeName)
static CLI::Option * addStringOption (const std::string &name, const std::string &description, const std::string &typeName, bool configurable)
static CLI::Option * addStringOption (const std::string &name, const std::string &description, const std::string &typeName, const std::string &defaultValue)
static CLI::Option * addStringOption (const std::string &name, const std::string &description, const std::string &typeName, const std::string &defaultValue, bool configurable)
static CLI::Option * addStringOption (const std::string &name, const std::string &description, const std::string &typeName, const char *defaultValue)
static CLI::Option * addStringOption (const std::string &name, const std::string &description, const std::string &typeName, const char *defaultValue, bool configurable)
static std::string getStringOptionValue (const std::string &name)
static void addFlag (const std::string &name, bool &variable, const std::string &description, bool required, bool configurable=true, const std::string &groupName="Application Options")
Static Private Member Functions
static bool parse1 ()
static bool parse2 ()
Static Private Attributes
static std::shared_ptr< CLI::App > app = makeApp()
static std::shared_ptr< CLI::Formatter > sectionFormatter = makeSectionFormatter()
static int argc = 0
static char ** argv = nullptr
static std::string applicationName
static std::string configDirectory
static std::string logDirectory
static std::string pidDirectory
static CLI::Option * daemonizeOpt = nullptr
static CLI::Option * logFileOpt = nullptr
static CLI::Option * userNameOpt = nullptr
static CLI::Option * groupNameOpt = nullptr
static CLI::Option * enforceLogFileOpt = nullptr
static CLI::Option * logLevelOpt = nullptr
static CLI::Option * verboseLevelOpt = nullptr
static CLI::Option * quietOpt = nullptr
static std::map< std::string, std::string > aliases
static std::map< std::string, CLI::Option * > applicationOptions
Detailed Description
Definition at line 39 of file Config.h.
Constructor & Destructor Documentation
Config() [1/2]
utils::Config::Config () delete
Config() [2/2]
utils::Config::Config (const Config &) delete
~Config()
utils::Config::~Config () delete
Member Function Documentation
addFlag()
void Config::addFlag (const std::string & name, bool & variable, const std::string & description, bool required, bool configurable = true, const std::string & groupName = "Application Options") static
Definition at line 942 of file Config.cpp.
{
        app->add_flag(name, variable, description) //
            ->required(required)                   //
            ->configurable(configurable)           //
            ->group(groupName);
    }
addHelp()
CLI::App * Config::addHelp (CLI::App * app) static
Definition at line 747 of file Config.cpp.
{
        app //
            ->set_help_flag();
        app //
            ->add_flag_function(
                "-h{standard},--help{standard}",
                [app]([[maybe_unused]] std::int64_t count) {
                    const std::size_t disabledCount =
                        app->get_subcommands([](CLI::App* app) -> bool {
                               return app->get_group() == "Instance" && app->get_option("--disabled")->as<bool>();
                           })
                            .size();
                    const std::size_t enabledCount =
                        app->get_subcommands([](CLI::App* app) -> bool {
                               return app->get_group() == "Instance" && !app->get_option("--disabled")->as<bool>();
                           })
                            .size();
                    for (auto* instance : app->get_subcommands({})) {
                        const std::string& group = instance->get_group();
                        if (group == "Instance") {
                            if (instance->get_option("--disabled")->as<bool>()) {
                                instance->group(std::string("Instance").append((disabledCount > 1) ? "s" : "").append(" (disabled)"));
                            } else {
                                instance->group(std::string("Instance").append((enabledCount > 1) ? "s" : ""));
                            }
                        }
                    }
                    const std::string& result = app->get_option("--help")->as<std::string>();
                    if (result == "standard") {
                        throw CLI::CallForHelp();
                    }
                    if (result == "expanded") {
                        throw CLI::CallForAllHelp();
                    }
                },
                "Print help message")
            ->take_last()
            ->configurable(false)
            ->check(CLI::IsMember({"standard", "expanded"}));
        //            ->trigger_on_parse();
        return app;
    }
References CallForAllHelp::CallForAllHelp(), CallForHelp::CallForHelp(), and App::get_group().
Referenced by net::config::ConfigInstance::ConfigInstance().
addInstance()
CLI::App * Config::addInstance (const std::string & name, const std::string & description, const std::string & group) static
Definition at line 655 of file Config.cpp.
{
        CLI::App* instance = app->add_subcommand(name, description) //
                                 ->group(group)
                                 ->fallthrough()
                                 ->formatter(sectionFormatter)
                                 ->configurable(false)
                                 ->allow_extras(false)
                                 ->disabled(name.empty());
        instance //
            ->option_defaults()
            ->configurable(!instance->get_disabled());
        if (!instance->get_disabled() && !aliases.empty()) {
            if (aliases.contains(name)) {
                instance //
                    ->alias(aliases[name]);
            } else {
                instance //
                    ->option_defaults()
                    ->take_first();
            }
        }
        return instance;
    }
References App::get_disabled(), and App::option_defaults().
addSimpleHelp()
CLI::App * Config::addSimpleHelp (CLI::App * app) static
Definition at line 795 of file Config.cpp.
{
        app //
            ->set_help_flag();
        app //
            ->add_flag_function(
                "-h,--help",
                [app]([[maybe_unused]] std::int64_t count) {
                    const std::string& result = app->get_option("--help")->as<std::string>();
                    if (result != "1") {
                        std::cout << "Help: Ignoring mode '" << result << "'" << std::endl;
                    }
                    throw CLI::CallForHelp();
                },
                "Print help message")
            ->configurable(false);
        //            ->trigger_on_parse();
        return app;
    }
References CallForHelp::CallForHelp().
Referenced by net::config::ConfigInstance::addSection().
addStandardFlags()
CLI::App * Config::addStandardFlags (CLI::App * app) static
Definition at line 682 of file Config.cpp.
{
        app //
            ->add_flag_callback(
                "-s,--show-config",
                [app]() {
                    throw CLI::CallForShowConfig(app);
                },
                "Show current configuration and exit") //
            ->configurable(false)
            ->disable_flag_override();
        app //
            ->add_flag_function(
                "--command-line{standard}",
                [app]([[maybe_unused]] std::int64_t count) {
                    const std::string& result = app->get_option("--command-line")->as<std::string>();
                    if (result == "standard") {
                        throw CLI::CallForCommandline( //
                            app,
                            "Below is a command line viewing all non-default and required options:\n"
                            "* Options show their configured value\n"
                            "* Required but not yet configured options show <REQUIRED> as value\n"
                            "* Options marked as <REQUIRED> need to be configured for a successful bootstrap",
                            CLI::CallForCommandline::Mode::STANDARD);
                    }
                    if (result == "required") {
                        throw CLI::CallForCommandline( //
                            app,
                            "Below is a command line viewing required options only:\n"
                            "* Options show either their configured or default value\n"
                            "* Required but not yet configured options show <REQUIRED> as value\n"
                            "* Options marked as <REQUIRED> need to be configured for a successful bootstrap",
                            CLI::CallForCommandline::Mode::REQUIRED);
                    }
                    if (result == "full") {
                        throw CLI::CallForCommandline( //
                            app,
                            "Below is a command line viewing the full set of options with their default or configured values:\n"
                            "* Options show either their configured or default value\n"
                            "* Required but not yet configured options show <REQUIRED> as value\n"
                            "* Options marked as <REQUIRED> need to be configured for a successful bootstrap",
                            CLI::CallForCommandline::Mode::FULL);
                    }
                    if (result == "default") {
                        throw CLI::CallForCommandline( //
                            app,
                            "Below is a command line viewing the full set of options with their default values\n"
                            "* Options show their default value\n"
                            "* Required but not yet configured options show <REQUIRED> as value\n"
                            "* Options marked as <REQUIRED> need to be configured for a successful bootstrap",
                            CLI::CallForCommandline::Mode::DEFAULT);
                    }
                },
                "Print a command line\n"
                "  standard (default): View all non-default and required options\n"
                "  required: View required options only\n"
                "  full: View the full set of options with their default or configured values\n"
                "  default: View the full set of options with their default values")
            ->take_last()
            ->configurable(false)
            ->check(CLI::IsMember({"standard", "required", "full", "default"}));
        return app;
    }
References CLI::CallForShowConfig::CallForShowConfig(), CLI::CallForCommandline::DEFAULT, CLI::CallForCommandline::FULL, CLI::CallForCommandline::REQUIRED, and CLI::CallForCommandline::STANDARD.
Referenced by net::config::ConfigInstance::addSection(), and net::config::ConfigInstance::ConfigInstance().
addStringOption() [1/6]
CLI::Option * Config::addStringOption (const std::string & name, const std::string & description, const std::string & typeName) static
Definition at line 876 of file Config.cpp.
{
        applicationOptions[name] = app //
                                       ->add_option(name, description)
                                       ->take_last()
                                       ->type_name(typeName)
                                       ->configurable()
                                       ->required()
                                       ->group("Application Options");
        app->needs(applicationOptions[name]);
        return applicationOptions[name];
    }
Referenced by addStringOption(), and addStringOption().
addStringOption() [2/6]
CLI::Option * Config::addStringOption (const std::string & name, const std::string & description, const std::string & typeName, bool configurable) static
Definition at line 891 of file Config.cpp.
{
        addStringOption(name, description, typeName);
        return applicationOptions[name] //
            ->configurable(configurable);
    }
References addStringOption().
addStringOption() [3/6]
CLI::Option * Config::addStringOption (const std::string & name, const std::string & description, const std::string & typeName, const char * defaultValue) static
Definition at line 922 of file Config.cpp.
{
        return addStringOption(name, description, typeName, std::string(defaultValue));
    }
References addStringOption().
addStringOption() [4/6]
CLI::Option * Config::addStringOption (const std::string & name, const std::string & description, const std::string & typeName, const char * defaultValue, bool configurable) static
Definition at line 929 of file Config.cpp.
{
        return addStringOption(name, description, typeName, std::string(defaultValue), configurable);
    }
References addStringOption().
addStringOption() [5/6]
CLI::Option * Config::addStringOption (const std::string & name, const std::string & description, const std::string & typeName, const std::string & defaultValue) static
Definition at line 897 of file Config.cpp.
{
        addStringOption(name, description, typeName);
        applicationOptions[name] //
            ->required(false)
            ->default_val(defaultValue);
        app->remove_needs(applicationOptions[name]);
        return applicationOptions[name];
    }
References addStringOption().
Referenced by addStringOption(), and addStringOption().
addStringOption() [6/6]
CLI::Option * Config::addStringOption (const std::string & name, const std::string & description, const std::string & typeName, const std::string & defaultValue, bool configurable) static
Definition at line 912 of file Config.cpp.
{
        addStringOption(name, description, typeName, defaultValue);
        return applicationOptions[name] //
            ->configurable(configurable);
    }
References addStringOption().
Referenced by addStringOption().
bootstrap()
bool Config::bootstrap () static
Definition at line 346 of file Config.cpp.
{
        aliases.clear();
        app->final_callback([]() -> void {
            if (daemonizeOpt->as<bool>() && (*app)["--show-config"]->count() == 0 && (*app)["--write-config"]->count() == 0 &&
                (*app)["--command-line"]->count() == 0) {
                std::cout << "Running as daemon (double fork)" << std::endl;
                utils::Daemon::startDaemon(
                    pidDirectory + "/" + applicationName + ".pid", userNameOpt->as<std::string>(), groupNameOpt->as<std::string>());
                logger::Logger::setQuiet();
                const std::string logFile = logFileOpt->as<std::string>();
                if (!logFile.empty()) {
                    logger::Logger::logToFile(logFile);
                }
            } else if ((*app)["--enforce-log-file"]->as<bool>()) {
                const std::string logFile = logFileOpt->as<std::string>();
                if (!logFile.empty()) {
                    std::cout << "Writing logs to file " << logFile << std::endl;
                    logger::Logger::logToFile(logFile);
                }
            }
        });
        return parse2();
    }
References parse2().
Referenced by core::EventLoop::start().
disabled()
void Config::disabled (CLI::App * instance, bool disabled = true) static
Definition at line 840 of file Config.cpp.
{
        if (disabled) {
            app->remove_needs(instance);
            for (const auto& sub : instance->get_subcommands([](const CLI::App* sc) -> bool {
                     return !sc->get_disabled();
                 })) {
                sub->disabled();
                if (sub->get_required()) {
                    instance->remove_needs(sub);
                }
            }
        } else {
            app->needs(instance);
            for (const auto& sub : instance->get_subcommands([](const CLI::App* sc) -> bool {
                     return sc->get_disabled();
                 })) {
                sub->disabled(false);
                if (sub->get_required()) {
                    instance->needs(sub);
                }
            }
        }
        instance->required(!disabled);
    }
References App::required().
Referenced by net::config::ConfigInstance::ConfigInstance(), and net::config::ConfigInstance::setDisabled().
getApplicationName()
std::string Config::getApplicationName () static
Definition at line 954 of file Config.cpp.
{
        return applicationName;
    }
getLogLevel()
int Config::getLogLevel () static
Definition at line 958 of file Config.cpp.
{
        return logLevelOpt->as<int>();
    }
References logLevelOpt.
getStringOptionValue()
std::string Config::getStringOptionValue (const std::string & name) static
Definition at line 934 of file Config.cpp.
{
        if (app->get_option(name) == nullptr) {
            throw CLI::OptionNotFound(name);
        }
        return (*app)[name]->as<std::string>();
    }
Referenced by main().
getVerboseLevel()
int Config::getVerboseLevel () static
Definition at line 962 of file Config.cpp.
{
        return verboseLevelOpt->as<int>();
    }
References verboseLevelOpt.
init()
bool Config::init (int argc, char * argv[]) static
Definition at line 105 of file Config.cpp.
{
        bool proceed = true;
        Config::argc = argc;
        Config::argv = argv;
        applicationName = std::filesystem::path(argv[0]).filename();
        uid_t euid = 0;
        struct passwd* pw = nullptr;
        struct group* gr = nullptr;
        if ((pw = getpwuid(getuid())) == nullptr) {
            proceed = false;
        } else if ((gr = getgrgid(pw->pw_gid)) == nullptr) {
            proceed = false;
        } else if ((euid = geteuid()) == 0) {
            configDirectory = "/etc/snode.c";
            logDirectory = "/var/log/snode.c";
            pidDirectory = "/var/run/snode.c";
        } else {
            const char* homedir = nullptr;
            if ((homedir = std::getenv("XDG_CONFIG_HOME")) == nullptr) {
                if ((homedir = std::getenv("HOME")) == nullptr) {
                    homedir = pw->pw_dir;
                }
            }
            if (homedir != nullptr) {
                configDirectory = std::string(homedir) + "/.config/snode.c";
                logDirectory = std::string(homedir) + "/.local/log/snode.c";
                pidDirectory = std::string(homedir) + "/.local/run/snode.c";
            } else {
                proceed = false;
            }
        }
        if (proceed && !std::filesystem::exists(configDirectory)) {
            if (std::filesystem::create_directories(configDirectory)) {
                std::filesystem::permissions(
                    configDirectory,
                    (std::filesystem::perms::owner_all | std::filesystem::perms::group_read | std::filesystem::perms::group_exec) &
                        ~std::filesystem::perms::others_all);
                if (geteuid() == 0) {
                    struct group* gr = nullptr; // cppcheck-suppress shadowVariable
                    if ((gr = getgrnam(XSTR(GROUP_NAME))) != nullptr) {
                        if (chown(configDirectory.c_str(), euid, gr->gr_gid) < 0) {
                            std::cout << "Warning: Can not set group ownership of '" << configDirectory
                                      << "' to 'snodec':" << strerror(errno) << std::endl;
                        }
                    } else {
                        std::cout << "Error: Can not find group 'snodec'. Add it using groupadd or addgroup" << std::endl;
                        std::cout << "       and add the current user to this group." << std::endl;
                        std::filesystem::remove(configDirectory);
                        proceed = false;
                    }
                }
            } else {
                std::cout << "Error: Can not create directory '" << configDirectory << "'" << std::endl;
                proceed = false;
            }
        }
        if (proceed && !std::filesystem::exists(logDirectory)) {
            if (std::filesystem::create_directories(logDirectory)) {
                std::filesystem::permissions(logDirectory,
                                             (std::filesystem::perms::owner_all | std::filesystem::perms::group_all) &
                                                 ~std::filesystem::perms::others_all);
                if (geteuid() == 0) {
                    struct group* gr = nullptr; // cppcheck-suppress shadowVariable
                    if ((gr = getgrnam(XSTR(GROUP_NAME))) != nullptr) {
                        if (chown(logDirectory.c_str(), euid, gr->gr_gid) < 0) {
                            std::cout << "Warning: Can not set group ownership of '" << logDirectory << "' to 'snodec':" << strerror(errno)
                                      << std::endl;
                        }
                    } else {
                        std::cout << "Error: Can not find group 'snodec'. Add it using groupadd or addgroup" << std::endl;
                        std::cout << "       and add the current user to this group." << std::endl;
                        std::filesystem::remove(configDirectory);
                        proceed = false;
                    }
                }
            } else {
                std::cout << "Error: Can not create directory '" << logDirectory << "'" << std::endl;
                proceed = false;
            }
        }
        if (proceed && !std::filesystem::exists(pidDirectory)) {
            if (std::filesystem::create_directories(pidDirectory)) {
                std::filesystem::permissions(pidDirectory,
                                             (std::filesystem::perms::owner_all | std::filesystem::perms::group_all) &
                                                 ~std::filesystem::perms::others_all);
                if (geteuid() == 0) {
                    struct group* gr = nullptr; // cppcheck-suppress shadowVariable
                    if ((gr = getgrnam(XSTR(GROUP_NAME))) != nullptr) {
                        if (chown(pidDirectory.c_str(), euid, gr->gr_gid) < 0) {
                            std::cout << "Warning: Can not set group ownership of '" << pidDirectory << "' to 'snodec':" << strerror(errno)
                                      << std::endl;
                        }
                    } else {
                        std::cout << "Error: Can not find group 'snodec'. Add it using groupadd or addgroup." << std::endl;
                        std::cout << "       and add the current user to this group." << std::endl;
                        std::filesystem::remove(configDirectory);
                        proceed = false;
                    }
                }
            } else {
                std::cout << "Error: Can not create directory '" << pidDirectory << "'" << std::endl;
                proceed = false;
            }
        }
        if (proceed) {
            app->description("Configuration for Application '" + applicationName + "'");
            app->footer("Application '" + applicationName +
                        "' powered by SNode.C\n"
                        "(C) 2020-2025 Volker Christian <me@vchrist.at>\n"
                        "https://github.com/SNodeC/snode.c");
            app->set_config( //
                   "-c,--config-file",
                   configDirectory + "/" + applicationName + ".conf",
                   "Read a config file",
                   false) //
                ->take_all()
                ->type_name("configfile")
                ->check(!CLI::ExistingDirectory);
            app->add_option_function<std::string>(
                   "-w,--write-config",
                   []([[maybe_unused]] const std::string& configFile) {
                       throw CLI::CallForWriteConfig(configFile);
                   },
                   "Write config file and exit")
                ->take_last()
                ->configurable(false)
                ->default_val(configDirectory + "/" + applicationName + ".conf")
                ->type_name("[configfile]")
                ->check(!CLI::ExistingDirectory)
                ->expected(0, 1);
            app->add_flag( //
                   "-k,--kill",
                   "Kill running daemon") //
                ->configurable(false)
                ->disable_flag_override();
            app->add_option( //
                   "-i,--instance-alias",
                   "Make an instance also known as an alias in configuration files")
                ->configurable(false)
                ->type_name("instance=instance_alias [instance=instance_alias [...]]")
                ->each([](const std::string& item) -> void {
                    const auto it = item.find('=');
                    if (it != std::string::npos) {
                        aliases[item.substr(0, it)] = item.substr(it + 1);
                    } else {
                        throw CLI::ConversionError("Can not convert '" + item + "' to a 'instance=instance_alias' pair");
                    }
                });
            addStandardFlags(app.get());
            logLevelOpt = app->add_option( //
                                 "-l,--log-level",
                                 "Log level") //
                              ->default_val(4)
                              ->type_name("level")
                              ->check(CLI::Range(0, 6))
                              ->group(app->get_formatter()->get_label("Persistent Options"));
            verboseLevelOpt = app->add_option( //
                                     "-v,--verbose-level",
                                     "Verbose level") //
                                  ->default_val(1)
                                  ->type_name("level")
                                  ->check(CLI::Range(0, 10))
                                  ->group(app->get_formatter()->get_label("Persistent Options"));
            quietOpt = app->add_flag( //
                              "-q{true},!-u,--quiet{true}",
                              "Quiet mode") //
                           ->take_last()
                           ->default_val("false")
                           ->type_name("bool")
                           ->check(CLI::IsMember({"true", "false"}))
                           ->group(app->get_formatter()->get_label("Persistent Options"));
            logFileOpt = app->add_option( //
                                "--log-file",
                                "Log file path") //
                             ->default_val(logDirectory + "/" + applicationName + ".log")
                             ->type_name("logfile")
                             ->check(!CLI::ExistingDirectory)
                             ->group(app->get_formatter()->get_label("Persistent Options"));
            enforceLogFileOpt = app->add_flag( //
                                       "-e{true},!-n,--enforce-log-file{true}",
                                       "Enforce writing of logs to file for foreground applications") //
                                    ->take_last()
                                    ->default_val("false")
                                    ->type_name("bool")
                                    ->check(CLI::IsMember({"true", "false"}))
                                    ->group(app->get_formatter()->get_label("Persistent Options"));
            daemonizeOpt = app->add_flag( //
                                  "-d{true},!-f,--daemonize{true}",
                                  "Start application as daemon") //
                               ->take_last()
                               ->default_val("false")
                               ->type_name("bool")
                               ->check(CLI::IsMember({"true", "false"}))
                               ->group(app->get_formatter()->get_label("Persistent Options"));
            userNameOpt = app->add_option( //
                                 "--user-name",
                                 "Run daemon under specific user permissions") //
                              ->default_val(pw->pw_name)
                              ->type_name("username")
                              ->needs(daemonizeOpt)
                              ->group(app->get_formatter()->get_label("Persistent Options"));
            groupNameOpt = app->add_option( //
                                  "--group-name",
                                  "Run daemon under specific group permissions")
                               ->default_val(gr->gr_name)
                               ->type_name("groupname")
                               ->needs(daemonizeOpt)
                               ->group(app->get_formatter()->get_label("Persistent Options"));
            proceed = parse1(); // for stopDaemon and pre init application options
            app->set_version_flag("--version", "1.0-rc1", "Framework version");
            addHelp(app.get());
        }
        return proceed;
    }
References argc, argv, configDirectory, logDirectory, parse1(), and pidDirectory.
Referenced by core::EventLoop::init().
operator=()
Config & utils::Config::operator= (const Config &) delete
parse1()
bool Config::parse1 () static private
Definition at line 376 of file Config.cpp.
{
        bool proceed = true;
        try {
            app->parse(argc, argv);
        } catch (const CLI::ParseError&) {
            // Do not process ParseError here but on second parse pass
        }
        if ((*app)["--kill"]->count() > 0) {
            try {
                const pid_t daemonPid = utils::Daemon::stopDaemon(pidDirectory + "/" + applicationName + ".pid");
                std::cout << "Daemon terminated: Pid = " << daemonPid << std::endl;
            } catch (const DaemonError& e) {
                std::cout << "DaemonError: " << e.what() << std::endl;
            } catch (const DaemonFailure& e) {
                std::cout << "DaemonFailure: " << e.what() << std::endl;
            }
            proceed = false;
        } else {
            if ((*app)["--show-config"]->count() == 0 && (*app)["--write-config"]->count() == 0 && (*app)["--command-line"]->count() == 0) {
                app->allow_extras(false);
            }
            if (!quietOpt->as<bool>()) {
                logger::Logger::setLogLevel(logLevelOpt->as<int>());
                logger::Logger::setVerboseLevel(verboseLevelOpt->as<int>());
            }
            logger::Logger::setQuiet(quietOpt->as<bool>());
        }
        return proceed;
    }
References applicationName, logLevelOpt, pidDirectory, quietOpt, logger::Logger::setLogLevel(), logger::Logger::setQuiet(), logger::Logger::setVerboseLevel(), and verboseLevelOpt.
Referenced by init().
parse2()
bool Config::parse2 () static private
Definition at line 535 of file Config.cpp.
{
        bool success = false;
        try {
            try {
                app->parse(argc, argv);
                success = true;
            } catch (const DaemonError& e) {
                std::cout << "Daemon error: " << e.what() << " ... exiting" << std::endl;
            } catch (const DaemonFailure& e) {
                std::cout << "Daemon failure: " << e.what() << " ... exiting" << std::endl;
            } catch (const DaemonSignaled& e) {
                std::cout << "Pid: " << getpid() << ", child pid: " << e.getPid() << ": " << e.what() << std::endl;
            } catch (const CLI::CallForHelp&) {
                std::cout << app->help() << std::endl;
            } catch (const CLI::CallForAllHelp&) {
                std::cout << app->help("", CLI::AppFormatMode::All) << std::endl;
            } catch (const CLI::CallForVersion&) {
                std::cout << app->version() << std::endl << std::endl;
            } catch (const CLI::CallForCommandline& e) {
                std::cout << e.what() << std::endl;
                std::cout << std::endl
                          << Color::Code::FG_GREEN << "command@line" << Color::Code::FG_DEFAULT << ":" << Color::Code::FG_BLUE << "~/> "
                          << Color::Code::FG_DEFAULT << createCommandLineTemplate(e.getApp(), e.getMode()) << std::endl
                          << std::endl;
            } catch (const CLI::CallForShowConfig& e) {
                try {
                    std::cout << e.getApp()->config_to_str(true, true);
                } catch (const CLI::ParseError& e1) {
                    std::cout << "Error showing config file: " << e.getApp() << " " << e1.get_name() << " " << e1.what() << std::endl;
                    throw;
                }
            } catch (const CLI::CallForWriteConfig& e) {
                std::cout << e.what() << std::endl;
                std::ofstream confFile(e.getConfigFile());
                if (confFile.is_open()) {
                    try {
                        confFile << app->config_to_str(true, true);
                        confFile.close();
                    } catch (const CLI::ParseError& e1) {
                        confFile.close();
                        std::cout << "Error writing config file: " << e1.get_name() << " " << e1.what() << std::endl;
                        throw;
                    }
                } else {
                    std::cout << "Error writing config file: " << std::strerror(errno) << std::endl;
                }
            } catch (const CLI::ConversionError& e) {
                std::cout << "[" << Color::Code::FG_RED << e.get_name() << Color::Code::FG_DEFAULT << "] " << e.what() << std::endl;
                throw;
            } catch (const CLI::ArgumentMismatch& e) {
                std::cout << "[" << Color::Code::FG_RED << e.get_name() << Color::Code::FG_DEFAULT << "] " << e.what() << std::endl;
                throw;
            } catch (const CLI::ConfigError& e) {
                std::cout << "[" << Color::Code::FG_RED << e.get_name() << Color::Code::FG_DEFAULT << "] " << e.what() << std::endl;
                std::cout << "              Adding '-w' on the command line may solve this problem" << std::endl;
                throw;
            } catch (const CLI::ParseError& e) {
                const std::string what = e.what();
                if (what.find("[Option Group: ") != std::string::npos) { // If CLI11 throws that error it means for us there are
                                                                         // unconfigured anonymous instances
                    std::cout << Color::Code::FG_RED << "[BootstrapError]" << Color::Code::FG_DEFAULT
                              << " Anonymous instance(s) not configured in source code " << std::endl;
                } else {
                    std::cout << "[" << Color::Code::FG_RED << e.get_name() << Color::Code::FG_DEFAULT << "] " << what << std::endl;
                }
                throw;
            }
        } catch (const CLI::ParseError&) {
            std::cout << std::endl << "Append -h or --help  to your command line for more information." << std::endl;
        } catch (const CLI::Error& e) {
            std::cout << "Error: " << e.get_name() << " " << e.what() << std::endl;
            std::cout << "Append -h or --help to your command line for more information." << std::endl;
        }
        if (!success) {
            logger::Logger::setQuiet();
        }
        return success;
    }
References Color::FG_BLUE, Color::FG_DEFAULT, Color::FG_GREEN, Color::FG_RED, CLI::CallForCommandline::getApp(), CLI::CallForShowConfig::getApp(), CLI::CallForWriteConfig::getConfigFile(), CLI::CallForCommandline::getMode(), utils::DaemonSignaled::getPid(), and logger::Logger::setQuiet().
Referenced by bootstrap().
removeInstance()
bool Config::removeInstance (CLI::App * instance) static
Definition at line 870 of file Config.cpp.
{
        Config::required(instance, false);
        return app->remove_subcommand(instance);
    }
References required().
Referenced by net::config::ConfigInstance::~ConfigInstance().
required()
void Config::required (CLI::App * instance, bool reqired = true) static
Definition at line 818 of file Config.cpp.
{
        if (reqired) {
            app->needs(instance);
            for (const auto& sub : instance->get_subcommands([](const CLI::App* sc) -> bool {
                     return sc->get_required();
                 })) {
                instance->needs(sub);
            }
        } else {
            app->remove_needs(instance);
            for (const auto& sub : instance->get_subcommands([](const CLI::App* sc) -> bool {
                     return sc->get_required();
                 })) {
                instance->remove_needs(sub);
            }
        }
        instance->required(reqired);
    }
References App::required().
Referenced by removeInstance(), and net::config::ConfigInstance::required().
terminate()
void Config::terminate () static
Definition at line 617 of file Config.cpp.
{
        if ((*app)["--daemonize"]->as<bool>()) {
            std::ifstream pidFile(pidDirectory + "/" + applicationName + ".pid", std::ifstream::in);
            if (pidFile.good()) {
                pid_t pid = 0;
                pidFile >> pid;
                if (getpid() == pid) {
                    Daemon::erasePidFile(pidDirectory + "/" + applicationName + ".pid");
                }
            }
        } else if (fcntl(STDIN_FILENO, F_SETFL, O_NONBLOCK) >= 0) {
            char buf[1024];
            while (read(STDIN_FILENO, buf, 1024) > 0) {
            }
        }
    }
References applicationName, and pidDirectory.
Referenced by core::EventLoop::free().
Member Data Documentation
aliases
std::map< std::string, std::string > Config::aliases static private
Definition at line 124 of file Config.h.
app
std::shared_ptr< CLI::App > Config::app = makeApp() static private
Definition at line 103 of file Config.h.
applicationName
std::string Config::applicationName static private
Definition at line 109 of file Config.h.
Referenced by parse1(), and terminate().
applicationOptions
std::map< std::string, CLI::Option * > Config::applicationOptions static private
Definition at line 125 of file Config.h.
argc
int Config::argc = 0 static private
Definition at line 106 of file Config.h.
Referenced by init().
argv
char ** Config::argv = nullptr static private
Definition at line 107 of file Config.h.
Referenced by init().
configDirectory
std::string Config::configDirectory static private
Definition at line 111 of file Config.h.
Referenced by init().
daemonizeOpt
CLI::Option * Config::daemonizeOpt = nullptr static private
Definition at line 115 of file Config.h.
enforceLogFileOpt
CLI::Option * Config::enforceLogFileOpt = nullptr static private
Definition at line 119 of file Config.h.
groupNameOpt
CLI::Option * Config::groupNameOpt = nullptr static private
Definition at line 118 of file Config.h.
logDirectory
std::string Config::logDirectory static private
Definition at line 112 of file Config.h.
Referenced by init().
logFileOpt
CLI::Option * Config::logFileOpt = nullptr static private
Definition at line 116 of file Config.h.
logLevelOpt
CLI::Option * Config::logLevelOpt = nullptr static private
Definition at line 120 of file Config.h.
Referenced by getLogLevel(), and parse1().
pidDirectory
std::string Config::pidDirectory static private
Definition at line 113 of file Config.h.
Referenced by init(), parse1(), and terminate().
quietOpt
CLI::Option * Config::quietOpt = nullptr static private
Definition at line 122 of file Config.h.
Referenced by parse1().
sectionFormatter
std::shared_ptr< CLI::Formatter > Config::sectionFormatter = makeSectionFormatter() static private
Definition at line 104 of file Config.h.
userNameOpt
CLI::Option * Config::userNameOpt = nullptr static private
Definition at line 117 of file Config.h.
verboseLevelOpt
CLI::Option * Config::verboseLevelOpt = nullptr static private
Definition at line 121 of file Config.h.
Referenced by getVerboseLevel(), and parse1().
The documentation for this class was generated from the following files:
src/utils/Config.h
src/utils/Config.cpp