snode.c: web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT > Class Template Reference
web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT > Class Template Reference
#include <SocketContextUpgrade.h>
Public Types
using SubProtocol = SubProtocolT
using Request = RequestT
using Response = ResponseT
Public Types inherited from web::http::SocketContextUpgrade< RequestT, ResponseT >
enum class Role { SERVER , CLIENT }
Public Member Functions
SocketContextUpgrade ()=delete
SocketContextUpgrade (const SocketContextUpgrade &)=delete
SocketContextUpgrade & operator= (const SocketContextUpgrade &)=delete
Public Member Functions inherited from core::socket::stream::SocketContext
~SocketContext () override=default
void sendToPeer (const char *junk, std::size_t junkLen) const final
std::size_t readFromPeer (char *junk, std::size_t junklen) const final
void setTimeout (const utils::Timeval &timeout) final
void shutdownRead ()
void shutdownWrite (bool forceClose=false)
void shutdown (bool forceClose=false)
void close () override
core::socket::stream::SocketConnection * getSocketConnection () const
core::socket::stream::SocketContext * switchSocketContext (core::socket::stream::SocketContextFactory *socketContextFactory)
virtual void sendToPeer (const char *junk, std::size_t junkLen) const=0
void sendToPeer (const std::string &data) const
Public Member Functions inherited from core::socket::SocketContext
SocketContext (const SocketContext &)=delete
SocketContext (SocketContext &&)=delete
SocketContext & operator= (const SocketContext &)=delete
SocketContext & operator= (SocketContext &&)=delete
void sendToPeer (const std::string &data) const
Protected Types
enum class Role { SERVER , CLIENT }
Protected Types inherited from web::http::SocketContextUpgrade< RequestT, ResponseT >
using Request = RequestT
using Response = ResponseT
using SocketContextUpgradeFactory = web::http::SocketContextUpgradeFactory< Request, Response >
Protected Member Functions
SocketContextUpgrade (core::socket::stream::SocketConnection *socketConnection, web::http::SocketContextUpgradeFactory< Request, Response > *socketContextUpgradeFactory, web::websocket::SubProtocolFactory< SubProtocol > *subProtocolFactory, Role role)
~SocketContextUpgrade () override=default
Protected Member Functions inherited from web::http::SocketContextUpgrade< RequestT, ResponseT >
SocketContextUpgrade (core::socket::stream::SocketConnection *socketConnection, SocketContextUpgradeFactory *socketContextUpgradeFactory)
~SocketContextUpgrade () override
Protected Member Functions inherited from core::socket::stream::SocketContext
SocketContext (core::socket::stream::SocketConnection *socketConnection)
Protected Member Functions inherited from core::socket::SocketContext
SocketContext ()=default
Protected Attributes
web::websocket::SubProtocolFactory< SubProtocol > * subProtocolFactory = nullptr
SubProtocol * subProtocol = nullptr
Private Types
using Super = web::http::SocketContextUpgrade< RequestT, ResponseT >
Private Types inherited from web::websocket::SubProtocolContext
enum OpCode {
CONTINUATION = 0x00 , TEXT = 0x01 , BINARY = 0x02 , CLOSE = 0x08 ,
PING = 0x09 , PONG = 0x0A
}
Private Member Functions
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength) const override
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength) const override
void sendMessageFrame (const char *message, std::size_t messageLength) const override
void sendMessageEnd (const char *message, std::size_t messageLength) const override
void sendPing (const char *reason=nullptr, std::size_t reasonLength=0) const override
void sendPong (const char *reason=nullptr, std::size_t reasonLength=0) const override
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0) override
void sendClose (const char *message, std::size_t messageLength) override
core::socket::stream::SocketConnection * getSocketConnection () override
void onMessageStart (int opCode) override
void onMessageData (const char *junk, uint64_t junkLen) override
void onMessageEnd () override
void onMessageError (uint16_t errnum) override
std::size_t readFrameData (char *junk, std::size_t junkLen) override
void onConnected () override
void onDisconnected () override
void onExit (int sig) override
void sendFrameData (uint8_t data) const override
void sendFrameData (uint16_t data) const override
void sendFrameData (uint32_t data) const override
void sendFrameData (uint64_t data) const override
void sendFrameData (const char *frame, uint64_t frameLength) const override
std::size_t onReceivedFromPeer () override
void dumpFrame (char *frame, uint64_t frameLength)
Private Member Functions inherited from web::websocket::SubProtocolContext
SubProtocolContext (bool role)
SubProtocolContext (const SubProtocolContext &)=delete
~SubProtocolContext () override
SubProtocolContext & operator= (const SubProtocolContext &)=delete
Private Attributes
bool closeSent = false
int receivedOpCode = 0
std::string pongCloseData
Detailed Description
template<typename SubProtocolT, typename RequestT, typename ResponseT>
class web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >
Definition at line 55 of file SocketContextUpgrade.h.
Member Typedef Documentation
Request
template<typename SubProtocolT , typename RequestT , typename ResponseT > using web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::Request = RequestT
Definition at line 68 of file SocketContextUpgrade.h.
Response
template<typename SubProtocolT , typename RequestT , typename ResponseT > using web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::Response = ResponseT
Definition at line 69 of file SocketContextUpgrade.h.
SubProtocol
template<typename SubProtocolT , typename RequestT , typename ResponseT > using web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::SubProtocol = SubProtocolT
Definition at line 67 of file SocketContextUpgrade.h.
Super
template<typename SubProtocolT , typename RequestT , typename ResponseT > using web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::Super = web::http::SocketContextUpgrade<RequestT, ResponseT> private
Definition at line 64 of file SocketContextUpgrade.h.
Member Enumeration Documentation
Role
template<typename SubProtocolT , typename RequestT , typename ResponseT > enum class web::websocket::SocketContextUpgrade::Role strong protected
Enumerator
SERVER
CLIENT
Definition at line 78 of file SocketContextUpgrade.h.
{ SERVER, CLIENT };
Constructor & Destructor Documentation
SocketContextUpgrade() [1/3]
template<typename SubProtocolT , typename RequestT , typename ResponseT > web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::SocketContextUpgrade () delete
SocketContextUpgrade() [2/3]
template<typename SubProtocolT , typename RequestT , typename ResponseT > web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::SocketContextUpgrade (const SocketContextUpgrade< SubProtocolT, RequestT, ResponseT > &) delete
SocketContextUpgrade() [3/3]
template<typename SubProtocolT , typename RequestT , typename ResponseT > web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::SocketContextUpgrade (core::socket::stream::SocketConnection * socketConnection, web::http::SocketContextUpgradeFactory< Request, Response > * socketContextUpgradeFactory, web::websocket::SubProtocolFactory< SubProtocol > * subProtocolFactory, Role role) inline protected
Definition at line 80 of file SocketContextUpgrade.h.
            : Super(socketConnection, socketContextUpgradeFactory)
            , web::websocket::SubProtocolContext(role == Role::CLIENT)
            , subProtocolFactory(subProtocolFactory)
            , subProtocol(subProtocolFactory->createSubProtocol(this)) {
        }
~SocketContextUpgrade()
template<typename SubProtocolT , typename RequestT , typename ResponseT > web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::~SocketContextUpgrade () override protected default
Member Function Documentation
dumpFrame()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::dumpFrame (char * frame, uint64_t frameLength) inline private
Definition at line 288 of file SocketContextUpgrade.h.
{
            unsigned int modul = 4;
            std::stringstream stringStream;
            for (std::size_t i = 0; i < frameLength; i++) {
                stringStream << std::setfill('0') << std::setw(2) << std::hex
                             << static_cast<unsigned int>(static_cast<unsigned char>(frame[i])) << " ";
                if ((i + 1) % modul == 0 || i == frameLength) {
                    LOG(TRACE) << "Frame: " << stringStream.str();
                    stringStream.str("");
                }
            }
        }
getSocketConnection()
template<typename SubProtocolT , typename RequestT , typename ResponseT > core::socket::stream::SocketConnection * web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::getSocketConnection () inline override private virtual
Implements web::websocket::SubProtocolContext.
Definition at line 145 of file SocketContextUpgrade.h.
{
            return Super::getSocketConnection();
        }
References core::socket::stream::SocketContext::getSocketConnection().
onConnected()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onConnected () inline override private virtual
Implements core::socket::stream::SocketContext.
Definition at line 223 of file SocketContextUpgrade.h.
{
            LOG(INFO) << "Websocket connected";
            subProtocol->onConnected();
        }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::subProtocol.
onDisconnected()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onDisconnected () inline override private virtual
Implements core::socket::stream::SocketContext.
Definition at line 228 of file SocketContextUpgrade.h.
{
            subProtocol->onDisconnected();
            LOG(INFO) << "Websocket disconnected";
        }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::subProtocol.
onExit()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onExit (int sig) inline override private virtual
Reimplemented from core::socket::SocketContext.
Definition at line 233 of file SocketContextUpgrade.h.
{
            subProtocol->onExit(sig);
        }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::subProtocol.
onMessageData()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageData (const char * junk, uint64_t junkLen) inline override private virtual
Implements web::websocket::Receiver.
Definition at line 166 of file SocketContextUpgrade.h.
{
            switch (receivedOpCode) {
                case SubProtocolContext::OpCode::CLOSE:
                    [[fallthrough]];
                case SubProtocolContext::OpCode::PING:
                    [[fallthrough]];
                case SubProtocolContext::OpCode::PONG:
                    pongCloseData += std::string(junk, static_cast<std::size_t>(junkLen));
                    break;
                default:
                    std::size_t junkOffset = 0;
                    do {
                        std::size_t sendJunkLen =
                            (junkLen - junkOffset <= SIZE_MAX) ? static_cast<std::size_t>(junkLen - junkOffset) : SIZE_MAX;
                        subProtocol->onMessageData(junk + junkOffset, sendJunkLen);
                        junkOffset += sendJunkLen;
                    } while (junkLen - junkOffset > 0);
                    break;
            }
        }
References web::websocket::SubProtocolContext::CLOSE, web::websocket::SubProtocolContext::PING, web::websocket::SubProtocolContext::PONG, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::pongCloseData, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::receivedOpCode, and web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::subProtocol.
onMessageEnd()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageEnd () inline override private virtual
Implements web::websocket::Receiver.
Definition at line 188 of file SocketContextUpgrade.h.
{
            switch (receivedOpCode) {
                case SubProtocolContext::OpCode::CLOSE:
                    if (closeSent) { // active close
                        closeSent = false;
                        LOG(DEBUG) << "Close confirmed from peer";
                    } else { // passive close
                        LOG(DEBUG) << "Close request received - replying with close";
                        sendClose(pongCloseData.data(), pongCloseData.length());
                        pongCloseData.clear();
                    }
                    break;
                case SubProtocolContext::OpCode::PING:
                    sendPong(pongCloseData.data(), pongCloseData.length());
                    pongCloseData.clear();
                    break;
                case SubProtocolContext::OpCode::PONG:
                    subProtocol->onPongReceived();
                    break;
                default:
                    subProtocol->onMessageEnd();
                    break;
            }
        }
References web::websocket::SubProtocolContext::CLOSE, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::closeSent, web::websocket::SubProtocolContext::PING, web::websocket::SubProtocolContext::PONG, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::pongCloseData, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::receivedOpCode, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendClose(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendPong(), and web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::subProtocol.
onMessageError()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageError (uint16_t errnum) inline override private virtual
Implements web::websocket::Receiver.
Definition at line 213 of file SocketContextUpgrade.h.
{
            subProtocol->onMessageError(errnum);
            sendClose(errnum);
        }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendClose(), and web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::subProtocol.
onMessageStart()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageStart (int opCode) inline override private virtual
Implements web::websocket::Receiver.
Definition at line 150 of file SocketContextUpgrade.h.
{
            receivedOpCode = opCode;
            switch (opCode) {
                case SubProtocolContext::OpCode::CLOSE:
                    [[fallthrough]];
                case SubProtocolContext::OpCode::PING:
                    [[fallthrough]];
                case SubProtocolContext::OpCode::PONG:
                    break;
                default:
                    subProtocol->onMessageStart(opCode);
                    break;
            }
        }
References web::websocket::SubProtocolContext::CLOSE, web::websocket::Receiver::opCode, web::websocket::SubProtocolContext::PING, web::websocket::SubProtocolContext::PONG, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::receivedOpCode, and web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::subProtocol.
onReceivedFromPeer()
template<typename SubProtocolT , typename RequestT , typename ResponseT > std::size_t web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onReceivedFromPeer () inline override private virtual
Implements core::socket::SocketContext.
Definition at line 279 of file SocketContextUpgrade.h.
{
            return Receiver::receive();
        }
References web::websocket::Receiver::receive().
operator=()
template<typename SubProtocolT , typename RequestT , typename ResponseT > SocketContextUpgrade & web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::operator= (const SocketContextUpgrade< SubProtocolT, RequestT, ResponseT > &) delete
readFrameData()
template<typename SubProtocolT , typename RequestT , typename ResponseT > std::size_t web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::readFrameData (char * junk, std::size_t junkLen) inline override private virtual
Implements web::websocket::Receiver.
Definition at line 218 of file SocketContextUpgrade.h.
{
            return readFromPeer(junk, junkLen);
        }
References core::socket::stream::SocketContext::readFromPeer().
sendClose() [1/2]
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendClose (const char * message, std::size_t messageLength) inline override private virtual
Implements web::websocket::SubProtocolContext.
Definition at line 132 of file SocketContextUpgrade.h.
{
            if (!closeSent) {
                LOG(DEBUG) << "Sending close to peer";
                sendMessage(8, message, messageLength);
                shutdownWrite();
                setTimeout(CLOSE_SOCKET_TIMEOUT);
                closeSent = true;
            }
        }
References CLOSE_SOCKET_TIMEOUT, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::closeSent, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendMessage(), core::socket::stream::SocketContext::setTimeout(), and core::socket::stream::SocketContext::shutdownWrite().
sendClose() [2/2]
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendClose (uint16_t statusCode = 1000, const char * reason = nullptr, std::size_t reasonLength = 0) inline override private virtual
Implements web::websocket::SubProtocolContext.
Definition at line 117 of file SocketContextUpgrade.h.
{
            std::size_t closePayloadLength = reasonLength + 2;
            char* closePayload = new char[closePayloadLength];
            *reinterpret_cast<uint16_t*>(closePayload) = htobe16(statusCode);
            if (reasonLength > 0) {
                memcpy(closePayload + 2, reason, reasonLength);
            }
            sendClose(closePayload, closePayloadLength);
            delete[] closePayload;
        }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendClose().
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageEnd(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageError(), and web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendClose().
sendFrameData() [1/5]
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendFrameData (const char * frame, uint64_t frameLength) const inline override private virtual
Implements web::websocket::Transmitter.
Definition at line 265 of file SocketContextUpgrade.h.
{
            if (!closeSent) {
                uint64_t frameOffset = 0;
                do {
                    std::size_t sendJunkLen =
                        (frameLength - frameOffset <= SIZE_MAX) ? static_cast<std::size_t>(frameLength - frameOffset) : SIZE_MAX;
                    sendToPeer(frame + frameOffset, sendJunkLen);
                    frameOffset += sendJunkLen;
                } while (frameLength - frameOffset > 0);
            }
        }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::closeSent, and core::socket::stream::SocketContext::sendToPeer().
sendFrameData() [2/5]
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendFrameData (uint16_t data) const inline override private virtual
Implements web::websocket::Transmitter.
Definition at line 244 of file SocketContextUpgrade.h.
{
            if (!closeSent) {
                uint16_t sendData = htobe16(data);
                sendToPeer(reinterpret_cast<char*>(&sendData), sizeof(uint16_t));
            }
        }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::closeSent, and core::socket::stream::SocketContext::sendToPeer().
sendFrameData() [3/5]
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendFrameData (uint32_t data) const inline override private virtual
Implements web::websocket::Transmitter.
Definition at line 251 of file SocketContextUpgrade.h.
{
            if (!closeSent) {
                uint32_t sendData = htobe32(data);
                sendToPeer(reinterpret_cast<char*>(&sendData), sizeof(uint32_t));
            }
        }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::closeSent, and core::socket::stream::SocketContext::sendToPeer().
sendFrameData() [4/5]
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendFrameData (uint64_t data) const inline override private virtual
Implements web::websocket::Transmitter.
Definition at line 258 of file SocketContextUpgrade.h.
{
            if (!closeSent) {
                uint64_t sendData = htobe64(data);
                sendToPeer(reinterpret_cast<char*>(&sendData), sizeof(uint64_t));
            }
        }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::closeSent, and core::socket::stream::SocketContext::sendToPeer().
sendFrameData() [5/5]
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendFrameData (uint8_t data) const inline override private virtual
Implements web::websocket::Transmitter.
Definition at line 238 of file SocketContextUpgrade.h.
{
            if (!closeSent) {
                sendToPeer(reinterpret_cast<char*>(&data), sizeof(uint8_t));
            }
        }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::closeSent, and core::socket::stream::SocketContext::sendToPeer().
sendMessage()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendMessage (uint8_t opCode, const char * message, std::size_t messageLength) const inline override private virtual
Implements web::websocket::SubProtocolContext.
Definition at line 93 of file SocketContextUpgrade.h.
{
            Transmitter::sendMessage(opCode, message, messageLength);
        }
References web::websocket::Receiver::opCode, and web::websocket::Transmitter::sendMessage().
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendClose(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendPing(), and web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendPong().
sendMessageEnd()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendMessageEnd (const char * message, std::size_t messageLength) const inline override private virtual
Implements web::websocket::SubProtocolContext.
Definition at line 105 of file SocketContextUpgrade.h.
{
            Transmitter::sendMessageEnd(message, messageLength);
        }
References web::websocket::Transmitter::sendMessageEnd().
sendMessageFrame()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendMessageFrame (const char * message, std::size_t messageLength) const inline override private virtual
Implements web::websocket::SubProtocolContext.
Definition at line 101 of file SocketContextUpgrade.h.
{
            Transmitter::sendMessageFrame(message, messageLength);
        }
References web::websocket::Transmitter::sendMessageFrame().
sendMessageStart()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendMessageStart (uint8_t opCode, const char * message, std::size_t messageLength) const inline override private virtual
Implements web::websocket::SubProtocolContext.
Definition at line 97 of file SocketContextUpgrade.h.
{
            Transmitter::sendMessageStart(opCode, message, messageLength);
        }
References web::websocket::Receiver::opCode, and web::websocket::Transmitter::sendMessageStart().
sendPing()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendPing (const char * reason = nullptr, std::size_t reasonLength = 0) const inline override private virtual
Implements web::websocket::SubProtocolContext.
Definition at line 109 of file SocketContextUpgrade.h.
{
            sendMessage(9, reason, reasonLength);
        }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendMessage().
sendPong()
template<typename SubProtocolT , typename RequestT , typename ResponseT > void web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendPong (const char * reason = nullptr, std::size_t reasonLength = 0) const inline override private virtual
Implements web::websocket::SubProtocolContext.
Definition at line 113 of file SocketContextUpgrade.h.
{
            sendMessage(10, reason, reasonLength);
        }
References web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendMessage().
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageEnd().
Member Data Documentation
closeSent
template<typename SubProtocolT , typename RequestT , typename ResponseT > bool web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::closeSent = false private
Definition at line 304 of file SocketContextUpgrade.h.
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageEnd(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendClose(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendFrameData(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendFrameData(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendFrameData(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendFrameData(), and web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendFrameData().
pongCloseData
template<typename SubProtocolT , typename RequestT , typename ResponseT > std::string web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::pongCloseData private
Definition at line 308 of file SocketContextUpgrade.h.
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageData(), and web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageEnd().
receivedOpCode
template<typename SubProtocolT , typename RequestT , typename ResponseT > int web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::receivedOpCode = 0 private
Definition at line 306 of file SocketContextUpgrade.h.
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageData(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageEnd(), and web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageStart().
subProtocol
template<typename SubProtocolT , typename RequestT , typename ResponseT > SubProtocol* web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::subProtocol = nullptr protected
Definition at line 285 of file SocketContextUpgrade.h.
Referenced by web::websocket::client::SocketContextUpgrade::create(), web::websocket::server::SocketContextUpgrade::create(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onConnected(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onDisconnected(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onExit(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageData(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageEnd(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageError(), and web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::onMessageStart().
subProtocolFactory
template<typename SubProtocolT , typename RequestT , typename ResponseT > web::websocket::SubProtocolFactory<SubProtocol>* web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::subProtocolFactory = nullptr protected
Definition at line 284 of file SocketContextUpgrade.h.
The documentation for this class was generated from the following file:
web/websocket/SocketContextUpgrade.h