SNode.C: core::Timer Class Reference
core::Timer Class Reference
#include <Timer.h>
Public Member Functions
Timer ()=default
void cancel ()
void restart ()
Protected Member Functions
Timer (core::TimerEventReceiver *timerEventReceiver)
Timer (Timer &&timer) noexcept
virtual ~Timer ()
Timer & operator= (Timer &&timer) noexcept
Private Member Functions
void removeTimerEventReceiver ()
Private Attributes
TimerEventReceiver * timerEventReceiver = nullptr
friend TimerEventReceiver
Detailed Description
Definition at line 55 of file Timer.h.
Constructor & Destructor Documentation
Timer() [1/3]
core::Timer::Timer (core::TimerEventReceiver * timerEventReceiver) explicit protected
Definition at line 52 of file Timer.cpp.
        : timerEventReceiver(timerEventReceiver) {
        timerEventReceiver->setTimer(this);
        timerEventReceiver->enable();
    }
References core::TimerEventReceiver::enable(), core::TimerEventReceiver::setTimer(), and timerEventReceiver.
Timer() [2/3]
core::Timer::Timer (Timer && timer) explicit protected noexcept
Definition at line 58 of file Timer.cpp.
        : timerEventReceiver(timer.timerEventReceiver) {
        timer.timerEventReceiver = nullptr;
        if (timerEventReceiver != nullptr) {
            timerEventReceiver->setTimer(this);
        }
    }
References core::TimerEventReceiver::setTimer(), and timerEventReceiver.
~Timer()
core::Timer::~Timer () protected virtual
Reimplemented in core::timer::Timer.
Definition at line 78 of file Timer.cpp.
                  {
        if (timerEventReceiver != nullptr) {
            timerEventReceiver->setTimer(nullptr);
        }
    }
References core::TimerEventReceiver::setTimer(), and timerEventReceiver.
Timer() [3/3]
core::Timer::Timer () default
Member Function Documentation
cancel()
void core::Timer::cancel ()
Definition at line 84 of file Timer.cpp.
                       {
        if (timerEventReceiver != nullptr) {
            timerEventReceiver->cancel();
        }
    }
References core::TimerEventReceiver::cancel(), and timerEventReceiver.
Referenced by iot::mqtt::client::Mqtt::~Mqtt(), iot::mqtt::Mqtt::~Mqtt(), and web::websocket::SubProtocol< SocketContextUpgradeT >::~SubProtocol().
operator=()
Timer & core::Timer::operator= (Timer && timer) protected noexcept
Definition at line 67 of file Timer.cpp.
{
        timerEventReceiver = timer.timerEventReceiver;
        timer.timerEventReceiver = nullptr;
        if (timerEventReceiver != nullptr) {
            timerEventReceiver->setTimer(this);
        }
        return *this;
    }
References core::TimerEventReceiver::setTimer(), and timerEventReceiver.
removeTimerEventReceiver()
void core::Timer::removeTimerEventReceiver () private
Definition at line 96 of file Timer.cpp.
{
        timerEventReceiver = nullptr;
    }
References timerEventReceiver.
Referenced by core::TimerEventReceiver::~TimerEventReceiver().
restart()
void core::Timer::restart ()
Definition at line 90 of file Timer.cpp.
{
        if (timerEventReceiver != nullptr) {
            timerEventReceiver->restart();
        }
    }
References core::TimerEventReceiver::restart(), and timerEventReceiver.
Member Data Documentation
TimerEventReceiver
friend core::Timer::TimerEventReceiver private
Definition at line 75 of file Timer.h.
timerEventReceiver
TimerEventReceiver* core::Timer::timerEventReceiver = nullptr private
Definition at line 73 of file Timer.h.
Referenced by cancel(), operator=(), removeTimerEventReceiver(), restart(), Timer(), Timer(), and ~Timer().
The documentation for this class was generated from the following files:
core/Timer.h
core/Timer.cpp