SNode.C: App Class Reference
App Class Reference
Creates a command line program, with very few defaults.
#include <CLI11.hpp>
Public Member Functions
void _move_option (Option *opt, App *app)
function that could be used by subclasses of App to shift options around into subcommands
Basic
App (std::string app_description="", std::string app_name="")
Create a new program. Pass in the same arguments as main(), along with a help string.
App (const App &)=delete
App & operator= (const App &)=delete
virtual ~App ()=default
virtual destructor
App * callback (std::function< void()> app_callback)
App * final_callback (std::function< void()> app_callback)
App * parse_complete_callback (std::function< void()> pc_callback)
App * preparse_callback (std::function< void(std::size_t)> pp_callback)
App * name (std::string app_name="")
Set a name for the app (empty will use parser to set the name)
App * alias (std::string app_name)
Set an alias for the app.
App * allow_extras (bool allow=true)
Remove the error when extras are left over on the command line.
App * required (bool require=true)
Remove the error when extras are left over on the command line.
App * disabled (bool disable=true)
Disable the subcommand or option group.
App * silent (bool silence=true)
silence the subcommand from showing up in the processed list
App * disabled_by_default (bool disable=true)
Set the subcommand to be disabled by default, so on clear(), at the start of each parse it is disabled.
App * enabled_by_default (bool enable=true)
App * immediate_callback (bool immediate=true)
Set the subcommand callback to be executed immediately on subcommand completion.
App * validate_positionals (bool validate=true)
Set the subcommand to validate positional arguments before assigning.
App * validate_optional_arguments (bool validate=true)
Set the subcommand to validate optional vector arguments before assigning.
App * allow_config_extras (bool allow=true)
ignore extras in config files
App * allow_config_extras (config_extras_mode mode)
ignore extras in config files
App * prefix_command (bool allow=true)
Do not parse anything after the first unrecognized option and return.
App * ignore_case (bool value=true)
Ignore case. Subcommands inherit value.
App * allow_windows_style_options (bool value=true)
App * positionals_at_end (bool value=true)
Specify that the positional arguments are only at the end of the sequence.
App * configurable (bool value=true)
Specify that the subcommand can be triggered by a config file.
App * ignore_underscore (bool value=true)
Ignore underscore. Subcommands inherit value.
App * formatter (std::shared_ptr< FormatterBase > fmt)
Set the help formatter.
App * formatter_fn (std::function< std::string(const App *, std::string, AppFormatMode)> fmt)
Set the help formatter.
App * config_formatter (std::shared_ptr< Config > fmt)
Set the config formatter.
bool parsed () const
Check to see if this subcommand was parsed, true only if received on command line.
OptionDefaults * option_defaults ()
Get the OptionDefault object, to set option defaults.
Extras for subclassing
virtual void pre_callback ()
Post parsing
std::size_t count (std::string option_name) const
Counts the number of times the given option was passed.
std::vector< App * > get_subcommands () const
std::vector< const App * > get_subcommands (const std::function< bool(const App *)> &filter) const
std::vector< App * > get_subcommands (const std::function< bool(App *)> &filter)
bool got_subcommand (const App *subcom) const
Check to see if given subcommand was selected.
bool got_subcommand (std::string subcommand_name) const
Check with name instead of pointer to see if subcommand was selected.
App * excludes (Option *opt)
Sets excluded options for the subcommand.
App * excludes (App *app)
Sets excluded subcommands for the subcommand.
App * needs (Option *opt)
App * needs (App *app)
bool remove_excludes (Option *opt)
Removes an option from the excludes list of this subcommand.
bool remove_excludes (App *app)
Removes a subcommand from the excludes list of this subcommand.
bool remove_needs (Option *opt)
Removes an option from the needs list of this subcommand.
bool remove_needs (App *app)
Removes a subcommand from the needs list of this subcommand.
Getters
std::shared_ptr< FormatterBase > get_formatter () const
Access the formatter.
std::shared_ptr< Config > get_config_formatter () const
Access the config formatter.
std::shared_ptr< ConfigBase > get_config_formatter_base () const
Access the config formatter as a configBase pointer.
std::string get_description () const
Get the app or subcommand description.
App * description (std::string app_description)
Set the description of the app.
std::vector< const Option * > get_options (const std::function< bool(const Option *)> filter={}) const
Get the list of options (user facing function, so returns raw pointers), has optional filter function.
std::vector< Option * > get_options (const std::function< bool(Option *)> filter={})
Non-const version of the above.
Option * get_option_no_throw (std::string option_name) noexcept
Get an option by name (noexcept non-const version)
const Option * get_option_no_throw (std::string option_name) const noexcept
Get an option by name (noexcept const version)
const Option * get_option (std::string option_name) const
Get an option by name.
Option * get_option (std::string option_name)
Get an option by name (non-const version)
const Option * operator[] (const std::string &option_name) const
Shortcut bracket operator for getting a pointer to an option.
const Option * operator[] (const char *option_name) const
Shortcut bracket operator for getting a pointer to an option.
bool get_ignore_case () const
Check the status of ignore_case.
bool get_ignore_underscore () const
Check the status of ignore_underscore.
bool get_fallthrough () const
Check the status of fallthrough.
bool get_allow_windows_style_options () const
Check the status of the allow windows style options.
bool get_positionals_at_end () const
Check the status of the allow windows style options.
bool get_configurable () const
Check the status of the allow windows style options.
const std::string & get_group () const
Get the group of this subcommand.
std::string get_usage () const
Generate and return the usage.
std::string get_footer () const
Generate and return the footer.
std::size_t get_require_subcommand_min () const
Get the required min subcommand value.
std::size_t get_require_subcommand_max () const
Get the required max subcommand value.
std::size_t get_require_option_min () const
Get the required min option value.
std::size_t get_require_option_max () const
Get the required max option value.
bool get_prefix_command () const
Get the prefix command status.
bool get_allow_extras () const
Get the status of allow extras.
bool get_required () const
Get the status of required.
bool get_disabled () const
Get the status of disabled.
bool get_silent () const
Get the status of silence.
bool get_immediate_callback () const
Get the status of disabled.
bool get_disabled_by_default () const
Get the status of disabled by default.
bool get_enabled_by_default () const
Get the status of disabled by default.
bool get_validate_positionals () const
Get the status of validating positionals.
bool get_validate_optional_arguments () const
Get the status of validating optional vector arguments.
config_extras_mode get_allow_config_extras () const
Get the status of allow extras.
Option * get_help_ptr ()
Get a pointer to the help flag.
const Option * get_help_ptr () const
Get a pointer to the help flag. (const)
const Option * get_help_all_ptr () const
Get a pointer to the help all flag. (const)
Option * get_config_ptr ()
Get a pointer to the config option.
const Option * get_config_ptr () const
Get a pointer to the config option. (const)
Option * get_version_ptr ()
Get a pointer to the version option.
const Option * get_version_ptr () const
Get a pointer to the version option. (const)
App * get_parent ()
Get the parent of this subcommand (or nullptr if main app)
const App * get_parent () const
Get the parent of this subcommand (or nullptr if main app) (const version)
const std::string & get_name () const
Get the name of the current app.
const std::vector< std::string > & get_aliases () const
Get the aliases of the current app.
App * clear_aliases ()
clear all the aliases of the current App
std::string get_display_name (bool with_aliases=false) const
Get a display name for an app.
bool check_name (std::string name_to_check) const
Check the name, case insensitive and underscore insensitive if set.
std::vector< std::string > get_groups () const
Get the groups available directly from this option (in order)
const std::vector< Option * > & parse_order () const
This gets a vector of pointers with the original parse order.
std::vector< std::string > remaining (bool recurse=false) const
This returns the missing options from the current subcommand.
std::vector< std::string > remaining_for_passthrough (bool recurse=false) const
This returns the missing options in a form ready for processing by another command line program.
std::size_t remaining_size (bool recurse=false) const
This returns the number of remaining options, minus the – separator.
Protected Member Functions
App (std::string app_description, std::string app_name, App *parent)
Special private constructor for subcommand.
void _validate () const
void _configure ()
void run_callback (bool final_mode=false, bool suppress_final_callback=false)
Internal function to run (App) callback, bottom up.
bool _valid_subcommand (const std::string &current, bool ignore_used=true) const
Check to see if a subcommand is valid. Give up immediately if subcommand max has been reached.
detail::Classifier _recognize (const std::string &current, bool ignore_used_subcommands=true) const
Selects a Classifier enum based on the type of the current argument.
void _process_config_file ()
Read and process a configuration file (main app only)
void _process_env ()
Get envname options if not yet passed. Runs on all subcommands.
void _process_callbacks ()
Process callbacks. Runs on all subcommands.
void _process_help_flags (bool trigger_help=false, bool trigger_all_help=false) const
void _process_requirements ()
Verify required options and cross requirements. Subcommands too (only if selected).
void _process ()
Process callbacks and such.
void _process_extras ()
Throw an error if anything is left over and should not be.
void _process_extras (std::vector< std::string > &args)
void increment_parsed ()
Internal function to recursively increment the parsed counter on the current app as well unnamed subcommands.
void _parse (std::vector< std::string > &args)
Internal parse function.
void _parse (std::vector< std::string > &&args)
Internal parse function.
void _parse_stream (std::istream &input)
Internal function to parse a stream.
void _parse_config (const std::vector< ConfigItem > &args)
bool _parse_single_config (const ConfigItem &item, std::size_t level=0)
Fill in a single config option.
bool _parse_single (std::vector< std::string > &args, bool &positional_only)
std::size_t _count_remaining_positionals (bool required_only=false) const
Count the required remaining positional arguments.
bool _has_remaining_positionals () const
Count the required remaining positional arguments.
bool _parse_positional (std::vector< std::string > &args, bool haltOnSubcommand)
App * _find_subcommand (const std::string &subc_name, bool ignore_disabled, bool ignore_used) const noexcept
bool _parse_subcommand (std::vector< std::string > &args)
bool _parse_arg (std::vector< std::string > &args, detail::Classifier current_type, bool local_processing_only)
void _trigger_pre_parse (std::size_t remaining_args)
Trigger the pre_parse callback if needed.
App * _get_fallthrough_parent ()
Get the appropriate parent to fallthrough to which is the first one that has a name or the main app.
const std::string & _compare_subcommand_names (const App &subcom, const App &base) const
Helper function to run through all possible comparisons of subcommand names to check there is no overlap.
void _move_to_missing (detail::Classifier val_type, const std::string &val)
Helper function to place extra values in the most appropriate position.
Protected Attributes
Basics
std::string name_ {}
Subcommand name or program name (from parser if name is empty)
std::string description_ {}
Description of the current program/subcommand.
bool allow_extras_ {false}
If true, allow extra arguments (ie, don't throw an error). INHERITABLE.
config_extras_mode allow_config_extras_ {config_extras_mode::ignore}
bool prefix_command_ {false}
If true, return immediately on an unrecognized option (implies allow_extras) INHERITABLE.
bool has_automatic_name_ {false}
If set to true the name was automatically generated from the command line vs a user set name.
bool required_ {false}
If set to true the subcommand is required to be processed and used, ignored for main app.
bool disabled_ {false}
If set to true the subcommand is disabled and cannot be used, ignored for main app.
bool pre_parse_called_ {false}
Flag indicating that the pre_parse_callback has been triggered.
bool immediate_callback_ {false}
std::function< void(std::size_t)> pre_parse_callback_ {}
This is a function that runs prior to the start of parsing.
std::function< void()> parse_complete_callback_ {}
This is a function that runs when parsing has finished.
std::function< void()> final_callback_ {}
This is a function that runs when all processing has completed.
Options
OptionDefaults option_defaults_ {}
The default values for options, customizable and changeable INHERITABLE.
std::vector< Option_p > options_ {}
The list of options, stored locally.
Config
Option * config_ptr_ {nullptr}
Pointer to the config option.
std::shared_ptr< Config > config_formatter_ {new ConfigTOML()}
This is the formatter for help printing. Default provided. INHERITABLE (same pointer)
Private Attributes
friend Option
Subcommands
enum class startup_mode : char { stable , enabled , disabled }
std::vector< App_p > subcommands_ {}
Storage for subcommand list.
bool ignore_case_ {false}
If true, the program name is not case sensitive INHERITABLE.
bool ignore_underscore_ {false}
If true, the program should ignore underscores INHERITABLE.
bool fallthrough_ {false}
Allow subcommand fallthrough, so that parent commands can collect commands after subcommand. INHERITABLE.
bool allow_windows_style_options_
Allow '/' for options for Windows like options. Defaults to true on Windows, false otherwise. INHERITABLE.
bool positionals_at_end_ {false}
specify that positional arguments come at the end of the argument sequence not inheritable
startup_mode default_startup {startup_mode::stable}
bool configurable_ {false}
if set to true the subcommand can be triggered via configuration files INHERITABLE
bool validate_positionals_ {false}
If set to true positional options are validated before assigning INHERITABLE.
bool validate_optional_arguments_ {false}
If set to true optional vector arguments are validated before assigning INHERITABLE.
bool silent_ {false}
std::uint32_t parsed_ {0U}
Counts the number of times this command/subcommand was parsed.
std::size_t require_subcommand_min_ {0}
Minimum required subcommands (not inheritable!)
std::size_t require_subcommand_max_ {0}
Max number of subcommands allowed (parsing stops after this number). 0 is unlimited INHERITABLE.
std::size_t require_option_min_ {0}
Minimum required options (not inheritable!)
std::size_t require_option_max_ {0}
Max number of options allowed. 0 is unlimited (not inheritable)
App * parent_ {nullptr}
A pointer to the parent if this is a subcommand.
std::string group_ {"Subcommands"}
The group membership INHERITABLE.
std::vector< std::string > aliases_ {}
Alias names for the subcommand.
App * add_subcommand (std::string subcommand_name="", std::string subcommand_description="")
Add a subcommand. Inherits INHERITABLE and OptionDefaults, and help flag.
App * add_subcommand (CLI::App_p subcom)
Add a previously created app as a subcommand.
bool remove_subcommand (App *subcom)
Removes a subcommand from the App. Takes a subcommand pointer. Returns true if found and removed.
App * get_subcommand (const App *subcom) const
App * get_subcommand (std::string subcom) const
Check to see if a subcommand is part of this command (text version)
App * get_subcommand_no_throw (std::string subcom) const
App * get_subcommand (int index=0) const
Get a pointer to subcommand by index.
CLI::App_p get_subcommand_ptr (App *subcom) const
Check to see if a subcommand is part of this command and get a shared_ptr to it.
CLI::App_p get_subcommand_ptr (std::string subcom) const
Check to see if a subcommand is part of this command (text version)
CLI::App_p get_subcommand_ptr (int index=0) const
Get an owning pointer to subcommand by index.
App * get_option_group (std::string group_name) const
Check to see if an option group is part of this App.
std::size_t count () const
std::size_t count_all () const
App * group (std::string group_name)
Changes the group membership.
App * require_subcommand ()
The argumentless form of require subcommand requires 1 or more subcommands.
App * require_subcommand (int value)
App * require_subcommand (std::size_t min, std::size_t max)
App * require_option ()
The argumentless form of require option requires 1 or more options be used.
App * require_option (int value)
App * require_option (std::size_t min, std::size_t max)
App * fallthrough (bool value=true)
operator bool () const
Parsing
using missing_t = std::vector<std::pair<detail::Classifier, std::string>>
missing_t missing_ {}
std::vector< Option * > parse_order_ {}
This is a list of pointers to options with the original parse order.
std::vector< App * > parsed_subcommands_ {}
This is a list of the subcommands collected, in order.
std::set< App * > exclude_subcommands_ {}
this is a list of subcommands that are exclusionary to this one
std::set< Option * > exclude_options_ {}
std::set< App * > need_subcommands_ {}
std::set< Option * > need_options_ {}
void clear ()
Reset the parsed data.
void parse ()
void parse (int argc, const char *const *argv)
void parse (int argc, const wchar_t *const *argv)
void parse (std::string commandline, bool program_name_included=false)
void parse (std::wstring commandline, bool program_name_included=false)
void parse (std::vector< std::string > &args)
void parse (std::vector< std::string > &&args)
The real work is done here. Expects a reversed vector.
void parse_from_stream (std::istream &input)
void failure_message (std::function< std::string(const App *, const Error &e)> function)
Provide a function to print a help message. The function gets access to the App pointer and error.
int exit (const Error &e, std::ostream &out=std::cout, std::ostream &err=std::cerr) const
Print a nice error message and return the exit code.
template<class CharT >
void parse_char_t (int argc, const CharT *const *argv)
std::string usage_ {}
Usage to put after program/subcommand description in the help output INHERITABLE.
std::function< std::string()> usage_callback_ {}
This is a function that generates a usage to put after program/subcommand description in help output.
std::string footer_ {}
Footer to put after all options in the help output INHERITABLE.
std::function< std::string()> footer_callback_ {}
This is a function that generates a footer to put after all other options in help output.
Option * help_ptr_ {nullptr}
A pointer to the help flag if there is one INHERITABLE.
Option * help_all_ptr_ {nullptr}
A pointer to the help all flag if there is one INHERITABLE.
Option * version_ptr_ {nullptr}
A pointer to a version flag if there is one.
std::shared_ptr< FormatterBase > formatter_ {new Formatter()}
This is the formatter for help printing. Default provided. INHERITABLE (same pointer)
std::function< std::string(const App *, const Error &e)> failure_message_ {FailureMessage::simple}
The error message printing function INHERITABLE.
App * usage (std::string usage_string)
Set usage.
App * usage (std::function< std::string()> usage_function)
Set usage.
App * footer (std::string footer_string)
Set footer.
App * footer (std::function< std::string()> footer_function)
Set footer.
std::string config_to_str (bool default_also=false, bool write_description=false) const
std::string help (std::string prev="", AppFormatMode mode=AppFormatMode::Normal) const
std::string version () const
Displays a version string.
Adding options
Option * add_option (std::string option_name, callback_t option_callback, std::string option_description="", bool defaulted=false, std::function< std::string()> func={})
template<typename AssignTo , typename ConvertTo = AssignTo, enable_if_t<!std::is_const< ConvertTo >::value, detail::enabler > = detail::dummy>
Option * add_option (std::string option_name, AssignTo &variable, std::string option_description="")
Add option for assigning to a variable.
template<typename AssignTo , enable_if_t<!std::is_const< AssignTo >::value, detail::enabler > = detail::dummy>
Option * add_option_no_stream (std::string option_name, AssignTo &variable, std::string option_description="")
Add option for assigning to a variable.
template<typename ArgType >
Option * add_option_function (std::string option_name, const std::function< void(const ArgType &)> &func, std::string option_description="")
Add option for a callback of a specific type.
Option * add_option (std::string option_name)
Add option with no description or variable assignment.
template<typename T , enable_if_t< std::is_const< T >::value &&std::is_constructible< std::string, T >::value, detail::enabler > = detail::dummy>
Option * add_option (std::string option_name, T &option_description)
Add option with description but with no variable assignment or callback.
Option * set_help_flag (std::string flag_name="", const std::string &help_description="")
Set a help flag, replace the existing one if present.
Option * set_help_all_flag (std::string help_name="", const std::string &help_description="")
Set a help all flag, replaced the existing one if present.
Option * set_version_flag (std::string flag_name="", const std::string &versionString="", const std::string &version_help="Display program version information and exit")
Set a version flag and version display string, replace the existing one if present.
Option * set_version_flag (std::string flag_name, std::function< std::string()> vfunc, const std::string &version_help="Display program version information and exit")
Generate the version string through a callback function.
Option * add_flag (std::string flag_name)
Add a flag with no description or variable assignment.
template<typename T , enable_if_t< std::is_const< T >::value &&std::is_constructible< std::string, T >::value, detail::enabler > = detail::dummy>
Option * add_flag (std::string flag_name, T &flag_description)
template<typename T , enable_if_t<!detail::is_mutable_container< T >::value &&!std::is_const< T >::value &&!std::is_constructible< std::function< void(int)>, T >::value, detail::enabler > = detail::dummy>
Option * add_flag (std::string flag_name, T &flag_result, std::string flag_description="")
template<typename T , enable_if_t<!std::is_assignable< std::function< void(std::int64_t)> &, T >::value, detail::enabler > = detail::dummy>
Option * add_flag (std::string flag_name, std::vector< T > &flag_results, std::string flag_description="")
Vector version to capture multiple flags.
Option * add_flag_callback (std::string flag_name, std::function< void(void)> function, std::string flag_description="")
Add option for callback that is triggered with a true flag and takes no arguments.
Option * add_flag_function (std::string flag_name, std::function< void(std::int64_t)> function, std::string flag_description="")
Add option for callback with an integer value.
Option * set_config (std::string option_name="", std::string default_filename="", const std::string &help_message="Read an ini file", bool config_required=false)
Set a configuration ini file option, or clear it if no name passed.
bool remove_option (Option *opt)
Removes an option from the App. Takes an option pointer. Returns true if found and removed.
template<typename T = Option_group>
T * add_option_group (std::string group_name, std::string group_description="")
creates an option group as part of the given app
Option * _add_flag_internal (std::string flag_name, CLI::callback_t fun, std::string flag_description)
Internal function for adding a flag.
Detailed Description
Creates a command line program, with very few defaults.
To use, create a new Program() instance with argc, argv, and a help description. The templated add_option methods make it easy to prepare options. Remember to call .start before starting your program, so that the options can be evaluated and the help option doesn't accidentally run your program.
Definition at line 6279 of file CLI11.hpp.
Member Typedef Documentation
missing_t
using App::missing_t = std::vector<std::pair<detail::Classifier, std::string>> protected
Definition at line 6375 of file CLI11.hpp.
Member Enumeration Documentation
startup_mode
enum class App::startup_mode : char strong protected
Enumerator
stable
enabled
disabled
Definition at line 6430 of file CLI11.hpp.
: char { stable, enabled, disabled };
Constructor & Destructor Documentation
App() [1/3]
App::App (std::string app_description, std::string app_name, App * parent) inline protected
Special private constructor for subcommand.
OptionDefaults
Definition at line 7710 of file CLI11.hpp.
        : name_(std::move(app_name))
        , description_(std::move(app_description))
        , parent_(parent) {
        // Inherit if not from a nullptr
        if (parent_ != nullptr) {
            if (parent_->help_ptr_ != nullptr)
                set_help_flag(parent_->help_ptr_->get_name(false, true), parent_->help_ptr_->get_description());
            if (parent_->help_all_ptr_ != nullptr)
                set_help_all_flag(parent_->help_all_ptr_->get_name(false, true), parent_->help_all_ptr_->get_description());
            option_defaults_ = parent_->option_defaults_;
            // INHERITABLE
            failure_message_ = parent_->failure_message_;
            allow_extras_ = parent_->allow_extras_;
            allow_config_extras_ = parent_->allow_config_extras_;
            prefix_command_ = parent_->prefix_command_;
            immediate_callback_ = parent_->immediate_callback_;
            ignore_case_ = parent_->ignore_case_;
            ignore_underscore_ = parent_->ignore_underscore_;
            fallthrough_ = parent_->fallthrough_;
            validate_positionals_ = parent_->validate_positionals_;
            validate_optional_arguments_ = parent_->validate_optional_arguments_;
            configurable_ = parent_->configurable_;
            allow_windows_style_options_ = parent_->allow_windows_style_options_;
            group_ = parent_->group_;
            usage_ = parent_->usage_;
            footer_ = parent_->footer_;
            formatter_ = parent_->formatter_;
            config_formatter_ = parent_->config_formatter_;
            require_subcommand_max_ = parent_->require_subcommand_max_;
        }
    }
References allow_config_extras_, allow_extras_, allow_windows_style_options_, configurable_, description_, fallthrough_, footer_, Option::get_description(), Option::get_name(), help_all_ptr_, help_ptr_, ignore_case_, ignore_underscore_, immediate_callback_, name_, parent_, prefix_command_, require_subcommand_max_, set_help_all_flag(), set_help_flag(), usage_, validate_optional_arguments_, and validate_positionals_.
App() [2/3]
App::App (std::string app_description = "", std::string app_name = "") inline explicit
Create a new program. Pass in the same arguments as main(), along with a help string.
Definition at line 6492 of file CLI11.hpp.
            : App(app_description, app_name, nullptr) {
            set_help_flag("-h,--help", "Print this help message and exit");
        }
References App(), and set_help_flag().
Referenced by App().
App() [3/3]
App::App (const App &) delete
~App()
virtual App::~App () virtual default
virtual destructor
Member Function Documentation
_add_flag_internal()
Option * App::_add_flag_internal (std::string flag_name, CLI::callback_t fun, std::string flag_description) inline private
Internal function for adding a flag.
Definition at line 7934 of file CLI11.hpp.
{
        Option* opt = nullptr;
        if (detail::has_default_flag_values(flag_name)) {
            // check for default values and if it has them
            auto flag_defaults = detail::get_default_flag_values(flag_name);
            detail::remove_default_flag_values(flag_name);
            opt = add_option(std::move(flag_name), std::move(fun), std::move(flag_description), false);
            for (const auto& fname : flag_defaults)
                opt->fnames_.push_back(fname.first);
            opt->default_flag_values_ = std::move(flag_defaults);
        } else {
            opt = add_option(std::move(flag_name), std::move(fun), std::move(flag_description), false);
        }
        // flags cannot have positional values
        if (opt->get_positional()) {
            auto pos_name = opt->get_name(true);
            remove_option(opt);
            throw IncorrectConstruction::PositionalFlag(pos_name);
        }
        opt->multi_option_policy(MultiOptionPolicy::TakeLast);
        opt->expected(0);
        opt->required(false);
        return opt;
    }
References Option::expected(), Option::get_name(), Option::get_positional(), CLI::detail::has_default_flag_values(), Option::multi_option_policy(), IncorrectConstruction::PositionalFlag(), CLI::detail::remove_default_flag_values(), remove_option(), and TakeLast.
Referenced by add_flag(), and add_flag().
_compare_subcommand_names()
const std::string & App::_compare_subcommand_names (const App & subcom, const App & base) const inline protected
Helper function to run through all possible comparisons of subcommand names to check there is no overlap.
Definition at line 9669 of file CLI11.hpp.
{
        static const std::string estring;
        if (subcom.disabled_) {
            return estring;
        }
        for (const auto& subc : base.subcommands_) {
            if (subc.get() != &subcom) {
                if (subc->disabled_) {
                    continue;
                }
                if (!subcom.get_name().empty()) {
                    if (subc->check_name(subcom.get_name())) {
                        return subcom.get_name();
                    }
                }
                if (!subc->get_name().empty()) {
                    if (subcom.check_name(subc->get_name())) {
                        return subc->get_name();
                    }
                }
                for (const auto& les : subcom.aliases_) {
                    if (subc->check_name(les)) {
                        return les;
                    }
                }
                // this loop is needed in case of ignore_underscore or ignore_case on one but not the other
                for (const auto& les : subc->aliases_) {
                    if (subcom.check_name(les)) {
                        return les;
                    }
                }
                // if the subcommand is an option group we need to check deeper
                if (subc->get_name().empty()) {
                    const auto& cmpres = _compare_subcommand_names(subcom, *subc);
                    if (!cmpres.empty()) {
                        return cmpres;
                    }
                }
                // if the test subcommand is an option group we need to check deeper
                if (subcom.get_name().empty()) {
                    const auto& cmpres = _compare_subcommand_names(*subc, subcom);
                    if (!cmpres.empty()) {
                        return cmpres;
                    }
                }
            }
        }
        return estring;
    }
References disabled_.
Referenced by alias(), ignore_case(), ignore_underscore(), and name().
_configure()
void App::_configure () inline protected
configure subcommands to enable parsing through the current object set the correct fallthrough and prefix for nameless subcommands and manage the automatic enable or disable makes sure parent is set correctly
Definition at line 8629 of file CLI11.hpp.
{
        if (default_startup == startup_mode::enabled) {
            disabled_ = false;
        } else if (default_startup == startup_mode::disabled) {
            disabled_ = true;
        }
        for (const App_p& app : subcommands_) {
            if (app->has_automatic_name_) {
                app->name_.clear();
            }
            if (app->name_.empty()) {
                app->fallthrough_ = false; // make sure fallthrough_ is false to prevent infinite loop
                app->prefix_command_ = false;
            }
            // make sure the parent is set to be this object in preparation for parse
            app->parent_ = this;
            app->_configure();
        }
    }
References default_startup, disabled, disabled_, and enabled.
Referenced by parse(), parse(), and parse_from_stream().
_count_remaining_positionals()
std::size_t App::_count_remaining_positionals (bool required_only = false) const inline protected
Count the required remaining positional arguments.
Definition at line 9221 of file CLI11.hpp.
{
        std::size_t retval = 0;
        for (const Option_p& opt : options_) {
            if (opt->get_positional() && (!required_only || opt->get_required())) {
                if (opt->get_items_expected_min() > 0 && static_cast<int>(opt->count()) < opt->get_items_expected_min()) {
                    retval += static_cast<std::size_t>(opt->get_items_expected_min()) - opt->count();
                }
            }
        }
        return retval;
    }
Referenced by _parse_arg(), _parse_positional(), and _parse_subcommand().
_find_subcommand()
App * App::_find_subcommand (const std::string & subc_name, bool ignore_disabled, bool ignore_used) const inline protected noexcept
Locate a subcommand by name with two conditions, should disabled subcommands be ignored, and should used subcommands be ignored
Definition at line 9365 of file CLI11.hpp.
{
        for (const App_p& com : subcommands_) {
            if (com->disabled_ && ignore_disabled)
                continue;
            if (com->get_name().empty()) {
                auto* subc = com->_find_subcommand(subc_name, ignore_disabled, ignore_used);
                if (subc != nullptr) {
                    return subc;
                }
            }
            if (com->check_name(subc_name)) {
                if ((!*com) || !ignore_used)
                    return com.get();
            }
        }
        return nullptr;
    }
Referenced by _valid_subcommand(), get_subcommand(), and get_subcommand_no_throw().
_get_fallthrough_parent()
App * App::_get_fallthrough_parent () inline protected
Get the appropriate parent to fallthrough to which is the first one that has a name or the main app.
Definition at line 9658 of file CLI11.hpp.
{
        if (parent_ == nullptr) {
            throw(HorribleError("No Valid parent"));
        }
        auto* fallthrough_parent = parent_;
        while ((fallthrough_parent->parent_ != nullptr) && (fallthrough_parent->get_name().empty())) {
            fallthrough_parent = fallthrough_parent->parent_;
        }
        return fallthrough_parent;
    }
References get_name(), and parent_.
Referenced by _parse_positional(), add_subcommand(), alias(), detail::AppFriend::get_fallthrough_parent(), ignore_case(), ignore_underscore(), and name().
_has_remaining_positionals()
bool App::_has_remaining_positionals () const inline protected
Count the required remaining positional arguments.
Definition at line 9233 of file CLI11.hpp.
{
        for (const Option_p& opt : options_) {
            if (opt->get_positional() && ((static_cast<int>(opt->count()) < opt->get_items_expected_min()))) {
                return true;
            }
        }
        return false;
    }
Referenced by _parse_single().
_move_option()
void App::_move_option (Option * opt, App * app) inline
function that could be used by subclasses of App to shift options around into subcommands
Definition at line 9735 of file CLI11.hpp.
{
        if (opt == nullptr) {
            throw OptionNotFound("the option is NULL");
        }
        // verify that the give app is actually a subcommand
        bool found = false;
        for (auto& subc : subcommands_) {
            if (app == subc.get()) {
                found = true;
            }
        }
        if (!found) {
            throw OptionNotFound("The Given app is not a subcommand");
        }
        if ((help_ptr_ == opt) || (help_all_ptr_ == opt))
            throw OptionAlreadyAdded("cannot move help options");
        if (config_ptr_ == opt)
            throw OptionAlreadyAdded("cannot move config file options");
        auto iterator = std::find_if(std::begin(options_), std::end(options_), [opt](const Option_p& v) {
            return v.get() == opt;
        });
        if (iterator != std::end(options_)) {
            const auto& opt_p = *iterator;
            if (std::find_if(std::begin(app->options_), std::end(app->options_), [&opt_p](const Option_p& v) {
                    return (*v == *opt_p);
                }) == std::end(app->options_)) {
                // only erase after the insertion was successful
                app->options_.push_back(std::move(*iterator));
                options_.erase(iterator);
            } else {
                throw OptionAlreadyAdded("option was not located: " + opt->get_name());
            }
        } else {
            throw OptionNotFound("could not locate the given Option");
        }
    }
References config_ptr_, Option::get_name(), help_all_ptr_, and help_ptr_.
_move_to_missing()
void App::_move_to_missing (detail::Classifier val_type, const std::string & val) inline protected
Helper function to place extra values in the most appropriate position.
Definition at line 9719 of file CLI11.hpp.
{
        if (allow_extras_ || subcommands_.empty()) {
            missing_.emplace_back(val_type, val);
            return;
        }
        // allow extra arguments to be places in an option group if it is allowed there
        for (auto& subc : subcommands_) {
            if (subc->name_.empty() && subc->allow_extras_) {
                subc->missing_.emplace_back(val_type, val);
                return;
            }
        }
        // if we haven't found any place to put them yet put them in missing
        missing_.emplace_back(val_type, val);
    }
Referenced by _parse_arg(), _parse_positional(), and _parse_single().
_parse() [1/2]
void App::_parse (std::vector< std::string > && args) inline protected
Internal parse function.
Definition at line 9049 of file CLI11.hpp.
{
        // this can only be called by the top level in which case parent == nullptr by definition
        // operation is simplified
        increment_parsed();
        _trigger_pre_parse(args.size());
        bool positional_only = false;
        while (!args.empty()) {
            _parse_single(args, positional_only);
        }
        _process();
        // Throw error if any items are left over (depending on settings)
        _process_extras();
    }
References _process(), _process_extras(), and increment_parsed().
_parse() [2/2]
void App::_parse (std::vector< std::string > & args) inline protected
Internal parse function.
Definition at line 9021 of file CLI11.hpp.
{
        increment_parsed();
        _trigger_pre_parse(args.size());
        bool positional_only = false;
        while (!args.empty()) {
            if (!_parse_single(args, positional_only)) {
                break;
            }
        }
        if (parent_ == nullptr) {
            _process();
            // Throw error if any items are left over (depending on settings)
            _process_extras(args);
            // Convert missing (pairs) to extras (string only) ready for processing in another app
            args = remaining_for_passthrough(false);
        } else if (parse_complete_callback_) {
            _process_env();
            _process_callbacks();
            _process_help_flags();
            _process_requirements();
            run_callback(false, true);
        }
    }
References _process(), _process_callbacks(), _process_env(), _process_help_flags(), _process_requirements(), increment_parsed(), parent_, and run_callback().
_parse_arg()
bool App::_parse_arg (std::vector< std::string > & args, detail::Classifier current_type, bool local_processing_only) inline protected
Parse a short (false) or long (true) argument, must be at the top of the list if local_processing_only is set to true then fallthrough is disabled will return false if not found return true if the argument was processed or false if nothing was done
if we require a separator add it here
Definition at line 9422 of file CLI11.hpp.
{
        std::string const current = args.back();
        std::string arg_name;
        std::string value;
        std::string rest;
        switch (current_type) {
            case detail::Classifier::LONG:
                if (!detail::split_long(current, arg_name, value))
                    throw HorribleError("Long parsed but missing (you should not see this):" + args.back());
                break;
            case detail::Classifier::SHORT:
                if (!detail::split_short(current, arg_name, rest))
                    throw HorribleError("Short parsed but missing! You should not see this");
                break;
            case detail::Classifier::WINDOWS_STYLE:
                if (!detail::split_windows_style(current, arg_name, value))
                    throw HorribleError("windows option parsed but missing! You should not see this");
                break;
            case detail::Classifier::SUBCOMMAND:
            case detail::Classifier::SUBCOMMAND_TERMINATOR:
            case detail::Classifier::POSITIONAL_MARK:
            case detail::Classifier::NONE:
            default:
                throw HorribleError("parsing got called with invalid option! You should not see this");
        }
        auto op_ptr = std::find_if(std::begin(options_), std::end(options_), [arg_name, current_type](const Option_p& opt) {
            if (current_type == detail::Classifier::LONG)
                return opt->check_lname(arg_name);
            if (current_type == detail::Classifier::SHORT)
                return opt->check_sname(arg_name);
            // this will only get called for detail::Classifier::WINDOWS_STYLE
            return opt->check_lname(arg_name) || opt->check_sname(arg_name);
        });
        // Option not found
        if (op_ptr == std::end(options_)) {
            for (auto& subc : subcommands_) {
                if (subc->name_.empty() && !subc->disabled_) {
                    if (subc->_parse_arg(args, current_type, local_processing_only)) {
                        if (!subc->pre_parse_called_) {
                            subc->_trigger_pre_parse(args.size());
                        }
                        return true;
                    }
                }
            }
            // don't capture missing if this is a nameless subcommand and nameless subcommands can't fallthrough
            if (parent_ != nullptr && name_.empty()) {
                return false;
            }
            // now check for '.' notation of subcommands
            auto dotloc = arg_name.find_first_of('.', 1);
            if (dotloc != std::string::npos) {
                // using dot notation is equivalent to single argument subcommand
                auto* sub = _find_subcommand(arg_name.substr(0, dotloc), true, false);
                if (sub != nullptr) {
                    auto v = args.back();
                    args.pop_back();
                    arg_name = arg_name.substr(dotloc + 1);
                    if (arg_name.size() > 1) {
                        args.push_back(std::string("--") + v.substr(dotloc + 3));
                        current_type = detail::Classifier::LONG;
                    } else {
                        auto nval = v.substr(dotloc + 2);
                        nval.front() = '-';
                        if (nval.size() > 2) {
                            // '=' not allowed in short form arguments
                            args.push_back(nval.substr(3));
                            nval.resize(2);
                        }
                        args.push_back(nval);
                        current_type = detail::Classifier::SHORT;
                    }
                    auto val = sub->_parse_arg(args, current_type, true);
                    if (val) {
                        if (!sub->silent_) {
                            parsed_subcommands_.push_back(sub);
                        }
                        // deal with preparsing
                        increment_parsed();
                        _trigger_pre_parse(args.size());
                        // run the parse complete callback since the subcommand processing is now complete
                        if (sub->parse_complete_callback_) {
                            sub->_process_env();
                            sub->_process_callbacks();
                            sub->_process_help_flags();
                            sub->_process_requirements();
                            sub->run_callback(false, true);
                        }
                        return true;
                    }
                    args.pop_back();
                    args.push_back(v);
                }
            }
            if (local_processing_only) {
                return false;
            }
            // If a subcommand, try the main command
            if (parent_ != nullptr && fallthrough_)
                return _get_fallthrough_parent()->_parse_arg(args, current_type, false);
            // Otherwise, add to missing
            args.pop_back();
            _move_to_missing(current_type, current);
            return true;
        }
        args.pop_back();
        // Get a reference to the pointer to make syntax bearable
        Option_p& op = *op_ptr;
        if (op->get_inject_separator()) {
            if (!op->results().empty() && !op->results().back().empty()) {
                op->add_result(std::string{});
            }
        }
        if (op->get_trigger_on_parse() && op->current_option_state_ == Option::option_state::callback_run) {
            op->clear();
        }
        int const min_num = (std::min)(op->get_type_size_min(), op->get_items_expected_min());
        int max_num = op->get_items_expected_max();
        // check container like options to limit the argument size to a single type if the allow_extra_flags argument is
        // set. 16 is somewhat arbitrary (needs to be at least 4)
        if (max_num >= detail::expected_max_vector_size / 16 && !op->get_allow_extra_args()) {
            auto tmax = op->get_type_size_max();
            max_num = detail::checked_multiply(tmax, op->get_expected_min()) ? tmax : detail::expected_max_vector_size;
        }
        // Make sure we always eat the minimum for unlimited vectors
        int collected = 0;    // total number of arguments collected
        int result_count = 0; // local variable for number of results in a single arg string
        // deal with purely flag like things
        if (max_num == 0) {
            auto res = op->get_flag_value(arg_name, value);
            op->add_result(res);
            parse_order_.push_back(op.get());
        } else if (!value.empty()) { // --this=value
            op->add_result(value, result_count);
            parse_order_.push_back(op.get());
            collected += result_count;
            // -Trest
        } else if (!rest.empty()) {
            op->add_result(rest, result_count);
            parse_order_.push_back(op.get());
            rest = "";
            collected += result_count;
        }
        // gather the minimum number of arguments
        while (min_num > collected && !args.empty()) {
            std::string const current_ = args.back();
            args.pop_back();
            op->add_result(current_, result_count);
            parse_order_.push_back(op.get());
            collected += result_count;
        }
        if (min_num > collected) { // if we have run out of arguments and the minimum was not met
            throw ArgumentMismatch::TypedAtLeast(op->get_name(), min_num, op->get_type_name());
        }
        // now check for optional arguments
        if (max_num > collected || op->get_allow_extra_args()) { // we allow optional arguments
            auto remreqpos = _count_remaining_positionals(true);
            // we have met the minimum now optionally check up to the maximum
            while ((collected < max_num || op->get_allow_extra_args()) && !args.empty() &&
                   _recognize(args.back(), false) == detail::Classifier::NONE) {
                // If any required positionals remain, don't keep eating
                if (remreqpos >= args.size()) {
                    break;
                }
                if (validate_optional_arguments_) {
                    std::string arg = args.back();
                    arg = op->_validate(arg, 0);
                    if (!arg.empty()) {
                        break;
                    }
                }
                op->add_result(args.back(), result_count);
                parse_order_.push_back(op.get());
                args.pop_back();
                collected += result_count;
            }
            // Allow -- to end an unlimited list and "eat" it
            if (!args.empty() && _recognize(args.back()) == detail::Classifier::POSITIONAL_MARK)
                args.pop_back();
            // optional flag that didn't receive anything now get the default value
            if (min_num == 0 && max_num > 0 && collected == 0) {
                auto res = op->get_flag_value(arg_name, std::string{});
                op->add_result(res);
                parse_order_.push_back(op.get());
            }
        }
        // if we only partially completed a type then add an empty string if allowed for later processing
        if (min_num > 0 && (collected % op->get_type_size_max()) != 0) {
            if (op->get_type_size_max() != op->get_type_size_min()) {
                op->add_result(std::string{});
            } else {
                throw ArgumentMismatch::PartialType(op->get_name(), op->get_type_size_min(), op->get_type_name());
            }
        }
        if (op->get_trigger_on_parse()) {
            op->run_callback();
        }
        if (!rest.empty()) {
            rest = "-" + rest;
            args.push_back(rest);
        }
        return true;
    }
References _count_remaining_positionals(), _move_to_missing(), increment_parsed(), detail::LONG, name_, detail::NONE, parent_, detail::POSITIONAL_MARK, detail::SHORT, detail::split_short(), detail::split_windows_style(), detail::SUBCOMMAND, detail::SUBCOMMAND_TERMINATOR, and detail::WINDOWS_STYLE.
_parse_config()
void App::_parse_config (const std::vector< ConfigItem > & args) inline protected
Parse one config param, return false if not found in any subcommand, remove if it is
If this has more than one dot.separated.name, go into the subcommand matching it Returns true if it managed to find the option, if false you'll need to remove the arg manually.
Definition at line 9076 of file CLI11.hpp.
{
        for (const ConfigItem& item : args) {
            if (!_parse_single_config(item) && allow_config_extras_ == config_extras_mode::error)
                throw ConfigError::Extras(item.fullname());
        }
    }
_parse_positional()
bool App::_parse_positional (std::vector< std::string > & args, bool haltOnSubcommand) inline protected
Parse a positional, go up the tree to check
Parameters
haltOnSubcommand if set to true the operation will not process subcommands merely return false Return true if the positional was used false otherwise
if we require a separator add it here
Try to find a local subcommand that is repeated
now try one last gasp at subcommands that have been executed before, go to root app and try to find a subcommand in a broader way, if one exists let the parent deal with it
If this is an option group don't deal with it
We are out of other options this goes to missing
Definition at line 9243 of file CLI11.hpp.
{
        const std::string& positional = args.back();
        if (positionals_at_end_) {
            // deal with the case of required arguments at the end which should take precedence over other arguments
            auto arg_rem = args.size();
            auto remreq = _count_remaining_positionals(true);
            if (arg_rem <= remreq) {
                for (const Option_p& opt : options_) {
                    if (opt->get_positional() && opt->required_) {
                        if (static_cast<int>(opt->count()) < opt->get_items_expected_min()) {
                            if (validate_positionals_) {
                                std::string pos = positional;
                                pos = opt->_validate(pos, 0);
                                if (!pos.empty()) {
                                    continue;
                                }
                            }
                            parse_order_.push_back(opt.get());
                            if (opt->get_inject_separator()) {
                                if (!opt->results().empty() && !opt->results().back().empty()) {
                                    opt->add_result(std::string{});
                                }
                            }
                            if (opt->get_trigger_on_parse() && opt->current_option_state_ == Option::option_state::callback_run) {
                                opt->clear();
                            }
                            opt->add_result(positional);
                            if (opt->get_trigger_on_parse()) {
                                opt->run_callback();
                            }
                            args.pop_back();
                            return true;
                        }
                    }
                }
            }
        }
        for (const Option_p& opt : options_) {
            // Eat options, one by one, until done
            if (opt->get_positional() && (static_cast<int>(opt->count()) < opt->get_items_expected_min() || opt->get_allow_extra_args())) {
                if (validate_positionals_) {
                    std::string pos = positional;
                    pos = opt->_validate(pos, 0);
                    if (!pos.empty()) {
                        continue;
                    }
                }
                if (opt->get_inject_separator()) {
                    if (!opt->results().empty() && !opt->results().back().empty()) {
                        opt->add_result(std::string{});
                    }
                }
                if (opt->get_trigger_on_parse() && opt->current_option_state_ == Option::option_state::callback_run) {
                    opt->clear();
                }
                opt->add_result(positional);
                if (opt->get_trigger_on_parse()) {
                    opt->run_callback();
                }
                parse_order_.push_back(opt.get());
                args.pop_back();
                return true;
            }
        }
        for (auto& subc : subcommands_) {
            if ((subc->name_.empty()) && (!subc->disabled_)) {
                if (subc->_parse_positional(args, false)) {
                    if (!subc->pre_parse_called_) {
                        subc->_trigger_pre_parse(args.size());
                    }
                    return true;
                }
            }
        }
        // let the parent deal with it if possible
        if (parent_ != nullptr && fallthrough_)
            return _get_fallthrough_parent()->_parse_positional(args, static_cast<bool>(parse_complete_callback_));
        auto* com = _find_subcommand(args.back(), true, false);
        if (com != nullptr && (require_subcommand_max_ == 0 || require_subcommand_max_ > parsed_subcommands_.size())) {
            if (haltOnSubcommand) {
                return false;
            }
            args.pop_back();
            com->_parse(args);
            return true;
        }
        auto* parent_app = (parent_ != nullptr) ? _get_fallthrough_parent() : this;
        com = parent_app->_find_subcommand(args.back(), true, false);
        if (com != nullptr && (com->parent_->require_subcommand_max_ == 0 ||
                               com->parent_->require_subcommand_max_ > com->parent_->parsed_subcommands_.size())) {
            return false;
        }
        if (positionals_at_end_) {
            throw CLI::ExtrasError(name_, args);
        }
        if (parent_ != nullptr && name_.empty()) {
            return false;
        }
        _move_to_missing(detail::Classifier::NONE, positional);
        args.pop_back();
        if (prefix_command_) {
            while (!args.empty()) {
                _move_to_missing(detail::Classifier::NONE, args.back());
                args.pop_back();
            }
        }
        return true;
    }
References _count_remaining_positionals(), _get_fallthrough_parent(), _move_to_missing(), name_, detail::NONE, parent_, positionals_at_end_, and prefix_command_.
_parse_single()
bool App::_parse_single (std::vector< std::string > & args, bool & positional_only) inline protected
Parse "one" argument (some may eat more than one), delegate to parent if fails, add to missing if missing from main return false if the parse has failed and needs to return to parent
Definition at line 9179 of file CLI11.hpp.
{
        bool retval = true;
        detail::Classifier const classifier = positional_only ? detail::Classifier::NONE : _recognize(args.back());
        switch (classifier) {
            case detail::Classifier::POSITIONAL_MARK:
                args.pop_back();
                positional_only = true;
                if ((!_has_remaining_positionals()) && (parent_ != nullptr)) {
                    retval = false;
                } else {
                    _move_to_missing(classifier, "--");
                }
                break;
            case detail::Classifier::SUBCOMMAND_TERMINATOR:
                // treat this like a positional mark if in the parent app
                args.pop_back();
                retval = false;
                break;
            case detail::Classifier::SUBCOMMAND:
                retval = _parse_subcommand(args);
                break;
            case detail::Classifier::LONG:
            case detail::Classifier::SHORT:
            case detail::Classifier::WINDOWS_STYLE:
                // If already parsed a subcommand, don't accept options_
                _parse_arg(args, classifier, false);
                break;
            case detail::Classifier::NONE:
                // Probably a positional or something for a parent (sub)command
                retval = _parse_positional(args, false);
                if (retval && positionals_at_end_) {
                    positional_only = true;
                }
                break;
                // LCOV_EXCL_START
            default:
                throw HorribleError("unrecognized classifier (you should not see this!)");
                // LCOV_EXCL_STOP
        }
        return retval;
    }
References _has_remaining_positionals(), _move_to_missing(), parent_, and positionals_at_end_.
_parse_single_config()
bool App::_parse_single_config (const ConfigItem & item, std::size_t level = 0) inline protected
Fill in a single config option.
Definition at line 9083 of file CLI11.hpp.
{
        if (level < item.parents.size()) {
            try {
                auto* subcom = get_subcommand(item.parents.at(level));
                auto result = subcom->_parse_single_config(item, level + 1);
                return result;
            } catch (const OptionNotFound&) {
                return false;
            }
        }
        // check for section open
        if (item.name == "++") {
            if (configurable_) {
                increment_parsed();
                _trigger_pre_parse(2);
                if (parent_ != nullptr) {
                    parent_->parsed_subcommands_.push_back(this);
                }
            }
            return true;
        }
        // check for section close
        if (item.name == "--") {
            if (configurable_ && parse_complete_callback_) {
                _process_callbacks();
                _process_requirements();
                run_callback();
            }
            return true;
        }
        Option* op = get_option_no_throw("--" + item.name);
        if (op == nullptr) {
            if (item.name.size() == 1) {
                op = get_option_no_throw("-" + item.name);
            }
        }
        if (op == nullptr) {
            op = get_option_no_throw(item.name);
        }
        if (op == nullptr) {
            // If the option was not present
            if (get_allow_config_extras() == config_extras_mode::capture)
                // Should we worry about classifying the extras properly?
                missing_.emplace_back(detail::Classifier::NONE, item.fullname());
            for (const auto& input : item.inputs) {
                missing_.emplace_back(detail::Classifier::NONE, input);
            }
            return false;
        }
        if (!op->get_configurable()) {
            if (get_allow_config_extras() == config_extras_mode::ignore_all) {
                return false;
            }
            throw ConfigError::NotConfigurable(item.fullname());
        }
        if (op->empty()) {
            if (op->get_expected_min() == 0) {
                if (item.inputs.size() <= 1) {
                    // Flag parsing
                    auto res = config_formatter_->to_flag(item);
                    bool converted{false};
                    if (op->get_disable_flag_override()) {
                        try {
                            auto val = detail::to_flag_value(res);
                            if (val == 1) {
                                res = op->get_flag_value(item.name, "{}");
                                converted = true;
                            }
                        } catch (...) {
                        }
                    }
                    if (!converted) {
                        res = op->get_flag_value(item.name, res);
                    }
                    op->add_result(res);
                    return true;
                }
                if (static_cast<int>(item.inputs.size()) > op->get_items_expected_max()) {
                    if (op->get_items_expected_max() > 1) {
                        throw ArgumentMismatch::AtMost(item.fullname(), op->get_items_expected_max(), item.inputs.size());
                    }
                    throw ConversionError::TooManyInputsFlag(item.fullname());
                }
            }
            op->add_result(item.inputs);
            op->run_callback();
        }
        return true;
    }
References _process_callbacks(), _process_requirements(), _trigger_pre_parse(), ArgumentMismatch::AtMost(), configurable_, Option::empty(), ConfigItem::fullname(), get_allow_config_extras(), Option::get_expected_min(), Option::get_items_expected_max(), get_option_no_throw(), ignore_all, increment_parsed(), ConfigItem::name, ConfigError::NotConfigurable(), parent_, run_callback(), Option::run_callback(), and ConversionError::TooManyInputsFlag().
_parse_stream()
void App::_parse_stream (std::istream & input) inline protected
Internal function to parse a stream.
Definition at line 9065 of file CLI11.hpp.
{
        auto values = config_formatter_->from_config(input);
        _parse_config(values);
        increment_parsed();
        _trigger_pre_parse(values.size());
        _process();
        // Throw error if any items are left over (depending on settings)
        _process_extras();
    }
References _process(), _process_extras(), and increment_parsed().
Referenced by parse_from_stream().
_parse_subcommand()
bool App::_parse_subcommand (std::vector< std::string > & args) inline protected
Parse a subcommand, modify args and continue
Unlike the others, this one will always allow fallthrough return true if the subcommand was processed false otherwise
Definition at line 9383 of file CLI11.hpp.
{
        if (_count_remaining_positionals(/* required */ true) > 0) {
            _parse_positional(args, false);
            return true;
        }
        auto* com = _find_subcommand(args.back(), true, true);
        if (com == nullptr) {
            // the main way to get here is using .notation
            auto dotloc = args.back().find_first_of('.');
            if (dotloc != std::string::npos) {
                com = _find_subcommand(args.back().substr(0, dotloc), true, true);
                if (com != nullptr) {
                    args.back() = args.back().substr(dotloc + 1);
                    args.push_back(com->get_display_name());
                }
            }
        }
        if (com != nullptr) {
            args.pop_back();
            if (!com->silent_) {
                parsed_subcommands_.push_back(com);
            }
            com->_parse(args);
            auto* parent_app = com->parent_;
            while (parent_app != this) {
                parent_app->_trigger_pre_parse(args.size());
                if (!com->silent_) {
                    parent_app->parsed_subcommands_.push_back(com);
                }
                parent_app = parent_app->parent_;
            }
            return true;
        }
        if (parent_ == nullptr)
            throw HorribleError("Subcommand " + args.back() + " missing");
        return false;
    }
References _count_remaining_positionals().
_process()
void App::_process () inline protected
Process callbacks and such.
Definition at line 8962 of file CLI11.hpp.
{
        try {
            // the config file might generate a FileError but that should not be processed until later in the process
            // to allow for help, version and other errors to generate first.
            _process_config_file();
            // process env shouldn't throw but no reason to process it if config generated an error
            _process_env();
        } catch (const CLI::FileError&) {
            // callbacks and help_flags can generate exceptions which should take priority
            // over the config file error if one exists.
            _process_callbacks();
            _process_help_flags();
            throw;
        }
        _process_callbacks();
        _process_help_flags();
        _process_requirements();
    }
References _process_callbacks(), _process_config_file(), _process_env(), _process_help_flags(), and _process_requirements().
Referenced by _parse(), _parse(), and _parse_stream().
_process_callbacks()
void App::_process_callbacks () inline protected
Process callbacks. Runs on all subcommands.
Definition at line 8787 of file CLI11.hpp.
{
        for (App_p const& sub : subcommands_) {
            // process the priority option_groups first
            if (sub->get_name().empty() && sub->parse_complete_callback_) {
                if (sub->count_all() > 0) {
                    sub->_process_callbacks();
                    sub->run_callback();
                }
            }
        }
        for (const Option_p& opt : options_) {
            if ((*opt) && !opt->get_callback_run()) {
                opt->run_callback();
            }
        }
        for (App_p const& sub : subcommands_) {
            if (!sub->parse_complete_callback_) {
                sub->_process_callbacks();
            }
        }
    }
Referenced by _parse(), _parse_single_config(), and _process().
_process_config_file()
void App::_process_config_file () inline protected
Read and process a configuration file (main app only)
Definition at line 8723 of file CLI11.hpp.
{
        if (config_ptr_ != nullptr) {
            bool const config_required = config_ptr_->get_required();
            auto file_given = config_ptr_->count() > 0;
            auto config_files = config_ptr_->as<std::vector<std::string>>();
            if (config_files.empty() || config_files.front().empty()) {
                if (config_required) {
                    throw FileError::Missing("no specified config file");
                }
                return;
            }
            for (auto rit = config_files.rbegin(); rit != config_files.rend(); ++rit) {
                const auto& config_file = *rit;
                auto path_result = detail::check_path(config_file.c_str());
                if (path_result == detail::path_type::file) {
                    try {
                        std::vector<ConfigItem> const values = config_formatter_->from_file(config_file);
                        _parse_config(values);
                        if (!file_given) {
                            config_ptr_->add_result(config_file);
                        }
                    } catch (const FileError&) {
                        if (config_required || file_given)
                            throw;
                    }
                } else if (config_required || file_given) {
                    throw FileError::Missing(config_file);
                }
            }
        }
    }
References config_ptr_, Option::count(), and FileError::Missing().
Referenced by _process().
_process_env()
void App::_process_env () inline protected
Get envname options if not yet passed. Runs on all subcommands.
Definition at line 8755 of file CLI11.hpp.
{
        for (const Option_p& opt : options_) {
            if (opt->count() == 0 && !opt->envname_.empty()) {
                char* buffer = nullptr;
                std::string ename_string;
#ifdef _MSC_VER
                // Windows version
                std::size_t sz = 0;
                if (_dupenv_s(&buffer, &sz, opt->envname_.c_str()) == 0 && buffer != nullptr) {
                    ename_string = std::string(buffer);
                    free(buffer);
                }
#else
                // This also works on Windows, but gives a warning
                buffer = std::getenv(opt->envname_.c_str());
                if (buffer != nullptr)
                    ename_string = std::string(buffer);
#endif
                if (!ename_string.empty()) {
                    opt->add_result(ename_string);
                }
            }
        }
        for (App_p const& sub : subcommands_) {
            if (sub->get_name().empty() || !sub->parse_complete_callback_)
                sub->_process_env();
        }
    }
Referenced by _parse(), and _process().
_process_extras() [1/2]
void App::_process_extras () inline protected
Throw an error if anything is left over and should not be.
Definition at line 8984 of file CLI11.hpp.
{
        if (!(allow_extras_ || prefix_command_)) {
            std::size_t const num_left_over = remaining_size();
            if (num_left_over > 0) {
                throw ExtrasError(name_, remaining(false));
            }
        }
        for (App_p const& sub : subcommands_) {
            if (sub->count() > 0)
                sub->_process_extras();
        }
    }
References allow_extras_, prefix_command_, and remaining_size().
Referenced by _parse(), and _parse_stream().
_process_extras() [2/2]
void App::_process_extras (std::vector< std::string > & args) inline protected
Throw an error if anything is left over and should not be. Modifies the args to fill in the missing items before throwing.
Definition at line 8998 of file CLI11.hpp.
{
        if (!(allow_extras_ || prefix_command_)) {
            std::size_t const num_left_over = remaining_size();
            if (num_left_over > 0) {
                args = remaining(false);
                throw ExtrasError(name_, args);
            }
        }
        for (App_p const& sub : subcommands_) {
            if (sub->count() > 0)
                sub->_process_extras(args);
        }
    }
References allow_extras_, prefix_command_, and remaining_size().
_process_help_flags()
void App::_process_help_flags (bool trigger_help = false, bool trigger_all_help = false) const inline protected
Run help flag processing if any are found.
The flags allow recursive calls to remember if there was a help flag on a parent.
Definition at line 8810 of file CLI11.hpp.
{
        const Option* help_ptr = get_help_ptr();
        const Option* help_all_ptr = get_help_all_ptr();
        if (help_ptr != nullptr && help_ptr->count() > 0)
            trigger_help = true;
        if (help_all_ptr != nullptr && help_all_ptr->count() > 0)
            trigger_all_help = true;
        // If there were parsed subcommands, call those. First subcommand wins if there are multiple ones.
        if (!parsed_subcommands_.empty()) {
            for (const App* sub : parsed_subcommands_)
                sub->_process_help_flags(trigger_help, trigger_all_help);
            // Only the final subcommand should call for help. All help wins over help.
        } else if (trigger_all_help) {
            throw CallForAllHelp();
        } else if (trigger_help) {
            throw CallForHelp();
        }
    }
References CallForAllHelp::CallForAllHelp(), CallForHelp::CallForHelp(), Option::count(), get_help_all_ptr(), and get_help_ptr().
Referenced by _parse(), and _process().
_process_requirements()
void App::_process_requirements () inline protected
Verify required options and cross requirements. Subcommands too (only if selected).
Definition at line 8832 of file CLI11.hpp.
{
        // check excludes
        bool excluded{false};
        std::string excluder;
        for (const auto& opt : exclude_options_) {
            if (opt->count() > 0) {
                excluded = true;
                excluder = opt->get_name();
            }
        }
        for (const auto& subc : exclude_subcommands_) {
            if (subc->count_all() > 0) {
                excluded = true;
                excluder = subc->get_display_name();
            }
        }
        if (excluded) {
            if (count_all() > 0) {
                throw ExcludesError(get_display_name(), excluder);
            }
            // if we are excluded but didn't receive anything, just return
            return;
        }
        // check needs
        for (const auto& opt : need_options_) {
            if (opt->count() == 0) {
                if (count_all() > 0) {
                    throw RequiresError(get_display_name(), opt->get_name());
                }
                // if we missing something but didn't have any options, just return
                return;
            }
        }
        std::size_t used_options = 0;
        for (const Option_p& opt : options_) {
            if (opt->count() != 0) {
                ++used_options;
            }
            // Required but empty
            if (opt->get_required() && opt->count() == 0) {
                throw RequiredError(opt->get_name());
            }
            // Requires
            for (const Option* opt_req : opt->needs_)
                if (opt->count() > 0 && opt_req->count() == 0)
                    throw RequiresError(opt->get_name(), opt_req->get_name());
            // Excludes
            for (const Option* opt_ex : opt->excludes_)
                if (opt->count() > 0 && opt_ex->count() != 0)
                    throw ExcludesError(opt->get_name(), opt_ex->get_name());
        }
        // check for the required number of subcommands
        if (require_subcommand_min_ > 0) {
            auto selected_subcommands = get_subcommands();
            if (require_subcommand_min_ > selected_subcommands.size())
                throw RequiredError::Subcommand(require_subcommand_min_);
        }
        // Max error cannot occur, the extra subcommand will parse as an ExtrasError or a remaining item.
        // run this loop to check how many unnamed subcommands were actually used since they are considered options
        // from the perspective of an App
        for (App_p const& sub : subcommands_) {
            if (sub->disabled_)
                continue;
            if (sub->name_.empty() && sub->count_all() > 0) {
                ++used_options;
            }
        }
        if (require_option_min_ > used_options || (require_option_max_ > 0 && require_option_max_ < used_options)) {
            auto option_list = detail::join(options_, [this](const Option_p& ptr) {
                if (ptr.get() == help_ptr_ || ptr.get() == help_all_ptr_) {
                    return std::string{};
                }
                return ptr->get_name(false, true);
            });
            auto subc_list = get_subcommands([](App* app) {
                return ((app->get_name().empty()) && (!app->disabled_));
            });
            if (!subc_list.empty()) {
                option_list += "," + detail::join(subc_list, [](const App* app) {
                                   return app->get_display_name();
                               });
            }
            throw RequiredError::Option(require_option_min_, require_option_max_, used_options, option_list);
        }
        // now process the requirements for subcommands if needed
        for (const auto& sub : subcommands_) {
            if (sub->disabled_) // || !sub->required_)
                continue;
            if (sub->count_all() == 0) {
                if (!sub->required_) {
                    if (sub->name_.empty()) {
                        if (require_option_min_ > 0 && require_option_min_ <= used_options) {
                            continue;
                            // if we have met the requirement and there is nothing in this option group skip checking
                            // requirements
                        }
                        if (require_option_max_ > 0 && used_options >= require_option_min_) {
                            continue;
                            // if we have met the requirement and there is nothing in this option group skip checking
                            // requirements
                        }
                    }
                } else {
                    throw(CLI::RequiresError(get_display_name(), sub->get_display_name()));
                }
            }
            sub->_process_requirements();
        }
        // check needs
        for (const auto& subc : need_subcommands_) {
            if (subc->count_all() == 0) {
                if (count_all() > 0) {
                    throw RequiresError(get_display_name(), subc->get_display_name());
                }
                // if we missing something but didn't have any options, just return
                break;
            }
        }
    }
References count_all(), ExcludesError::ExcludesError(), get_display_name(), require_option_max_, require_option_min_, require_subcommand_min_, and RequiredError::Subcommand().
Referenced by _parse(), _parse_single_config(), and _process().
_recognize()
detail::Classifier App::_recognize (const std::string & current, bool ignore_used_subcommands = true) const inline protected
Selects a Classifier enum based on the type of the current argument.
Definition at line 8689 of file CLI11.hpp.
{
        std::string dummy1, dummy2;
        if (current == "--")
            return detail::Classifier::POSITIONAL_MARK;
        if (_valid_subcommand(current, ignore_used_subcommands))
            return detail::Classifier::SUBCOMMAND;
        if (detail::split_long(current, dummy1, dummy2))
            return detail::Classifier::LONG;
        if (detail::split_short(current, dummy1, dummy2)) {
            if (dummy1[0] >= '0' && dummy1[0] <= '9') {
                if (get_option_no_throw(std::string{'-', dummy1[0]}) == nullptr) {
                    return detail::Classifier::NONE;
                }
            }
            return detail::Classifier::SHORT;
        }
        if ((allow_windows_style_options_) && (detail::split_windows_style(current, dummy1, dummy2)))
            return detail::Classifier::WINDOWS_STYLE;
        if ((current == "++") && !name_.empty() && parent_ != nullptr)
            return detail::Classifier::SUBCOMMAND_TERMINATOR;
        auto dotloc = current.find_first_of('.');
        if (dotloc != std::string::npos) {
            auto* cm = _find_subcommand(current.substr(0, dotloc), true, ignore_used_subcommands);
            if (cm != nullptr) {
                auto res = cm->_recognize(current.substr(dotloc + 1), ignore_used_subcommands);
                if (res == detail::Classifier::SUBCOMMAND) {
                    return res;
                }
            }
        }
        return detail::Classifier::NONE;
    }
References _valid_subcommand(), allow_windows_style_options_, detail::LONG, name_, detail::NONE, parent_, detail::POSITIONAL_MARK, detail::SHORT, detail::split_long(), detail::split_short(), detail::split_windows_style(), detail::SUBCOMMAND, detail::SUBCOMMAND_TERMINATOR, and detail::WINDOWS_STYLE.
_trigger_pre_parse()
void App::_trigger_pre_parse (std::size_t remaining_args) inline protected
Trigger the pre_parse callback if needed.
Definition at line 9640 of file CLI11.hpp.
{
        if (!pre_parse_called_) {
            pre_parse_called_ = true;
            if (pre_parse_callback_) {
                pre_parse_callback_(remaining_args);
            }
        } else if (immediate_callback_) {
            if (!name_.empty()) {
                auto pcnt = parsed_;
                auto extras = std::move(missing_);
                clear();
                parsed_ = pcnt;
                pre_parse_called_ = true;
                missing_ = std::move(extras);
            }
        }
    }
References clear(), immediate_callback_, name_, parsed_, and pre_parse_called_.
Referenced by _parse_single_config().
_valid_subcommand()
bool App::_valid_subcommand (const std::string & current, bool ignore_used = true) const inline protected
Check to see if a subcommand is valid. Give up immediately if subcommand max has been reached.
Definition at line 8676 of file CLI11.hpp.
{
        // Don't match if max has been reached - but still check parents
        if (require_subcommand_max_ != 0 && parsed_subcommands_.size() >= require_subcommand_max_) {
            return parent_ != nullptr && parent_->_valid_subcommand(current, ignore_used);
        }
        auto* com = _find_subcommand(current, true, ignore_used);
        if (com != nullptr) {
            return true;
        }
        // Check parent if exists, else return false
        return parent_ != nullptr && parent_->_valid_subcommand(current, ignore_used);
    }
References _find_subcommand(), _valid_subcommand(), and parent_.
Referenced by _recognize(), and _valid_subcommand().
_validate()
void App::_validate () const inline protected
Check the options to make sure there are no conflicts.
Currently checks to see if multiple positionals exist with unlimited args and checks if the min and max options are feasible
Definition at line 8596 of file CLI11.hpp.
{
        // count the number of positional only args
        auto pcount = std::count_if(std::begin(options_), std::end(options_), [](const Option_p& opt) {
            return opt->get_items_expected_max() >= detail::expected_max_vector_size && !opt->nonpositional();
        });
        if (pcount > 1) {
            auto pcount_req = std::count_if(std::begin(options_), std::end(options_), [](const Option_p& opt) {
                return opt->get_items_expected_max() >= detail::expected_max_vector_size && !opt->nonpositional() && opt->get_required();
            });
            if (pcount - pcount_req > 1) {
                throw InvalidError(name_);
            }
        }
        std::size_t nameless_subs{0};
        for (const App_p& app : subcommands_) {
            app->_validate();
            if (app->get_name().empty())
                ++nameless_subs;
        }
        if (require_option_min_ > 0) {
            if (require_option_max_ > 0) {
                if (require_option_max_ < require_option_min_) {
                    throw(InvalidError("Required min options greater than required max options", ExitCodes::InvalidError));
                }
            }
            if (require_option_min_ > (options_.size() + nameless_subs)) {
                throw(InvalidError("Required min options greater than number of available options", ExitCodes::InvalidError));
            }
        }
    }
References InvalidError, InvalidError::InvalidError(), name_, require_option_max_, and require_option_min_.
Referenced by parse(), parse(), and parse_from_stream().
add_flag() [1/4]
Option * App::add_flag (std::string flag_name) inline
Add a flag with no description or variable assignment.
Definition at line 6804 of file CLI11.hpp.
{
            return _add_flag_internal(flag_name, CLI::callback_t(), std::string{});
        }
References _add_flag_internal().
add_flag() [2/4]
template<typename T , enable_if_t<!std::is_assignable< std::function< void(std::int64_t)> &, T >::value, detail::enabler > = detail::dummy> Option * App::add_flag (std::string flag_name, std::vector< T > & flag_results, std::string flag_description = "") inline
Vector version to capture multiple flags.
Parameters
flag_results A vector of values with the flag results
Definition at line 6837 of file CLI11.hpp.
{
            CLI::callback_t fun = [&flag_results](const CLI::results_t& res) {
                bool retval = true;
                for (const auto& elem : res) {
                    using CLI::detail::lexical_cast;
                    flag_results.emplace_back();
                    retval &= lexical_cast(elem, flag_results.back());
                }
                return retval;
            };
            return _add_flag_internal(flag_name, std::move(fun), std::move(flag_description))
                ->multi_option_policy(MultiOptionPolicy::TakeAll)
                ->run_callback_for_default();
        }
add_flag() [3/4]
template<typename T , enable_if_t< std::is_const< T >::value &&std::is_constructible< std::string, T >::value, detail::enabler > = detail::dummy> Option * App::add_flag (std::string flag_name, T & flag_description) inline
Add flag with description but with no variable assignment or callback takes a constant string, if a variable string is passed that variable will be assigned the results from the flag
Definition at line 6813 of file CLI11.hpp.
{
            return _add_flag_internal(flag_name, CLI::callback_t(), flag_description);
        }
References _add_flag_internal().
add_flag() [4/4]
template<typename T , enable_if_t<!detail::is_mutable_container< T >::value &&!std::is_const< T >::value &&!std::is_constructible< std::function< void(int)>, T >::value, detail::enabler > = detail::dummy> Option * App::add_flag (std::string flag_name, T & flag_result, std::string flag_description = "") inline
Other type version accepts all other types that are not vectors such as bool, enum, string or other classes that can be converted from a string
Parameters
flag_result A variable holding the flag result
Definition at line 6823 of file CLI11.hpp.
{
            CLI::callback_t fun = [&flag_result](const CLI::results_t& res) {
                using CLI::detail::lexical_cast;
                return lexical_cast(res[0], flag_result);
            };
            auto* opt = _add_flag_internal(flag_name, std::move(fun), std::move(flag_description));
            return detail::default_flag_modifiers<T>(opt);
        }
add_flag_callback()
Option * App::add_flag_callback (std::string flag_name, std::function< void(void)> function, std::string flag_description = "") inline
Add option for callback that is triggered with a true flag and takes no arguments.
Parameters
function A function to call, void(void)
Definition at line 7959 of file CLI11.hpp.
{
        CLI::callback_t fun = [function](const CLI::results_t& res) {
            using CLI::detail::lexical_cast;
            bool trigger{false};
            auto result = lexical_cast(res[0], trigger);
            if (result && trigger) {
                function();
            }
            return result;
        };
        return _add_flag_internal(flag_name, std::move(fun), std::move(flag_description));
    }
Referenced by set_version_flag(), and set_version_flag().
add_flag_function()
Option * App::add_flag_function (std::string flag_name, std::function< void(std::int64_t)> function, std::string flag_description = "") inline
Add option for callback with an integer value.
Parameters
function A function to call, void(int)
Definition at line 7974 of file CLI11.hpp.
{
        CLI::callback_t fun = [function](const CLI::results_t& res) {
            using CLI::detail::lexical_cast;
            std::int64_t flag_count{0};
            lexical_cast(res[0], flag_count);
            function(flag_count);
            return true;
        };
        return _add_flag_internal(flag_name, std::move(fun), std::move(flag_description))->multi_option_policy(MultiOptionPolicy::Sum);
    }
add_option() [1/4]
Option * App::add_option (std::string option_name) inline
Add option with no description or variable assignment.
Definition at line 6771 of file CLI11.hpp.
{
            return add_option(option_name, CLI::callback_t{}, std::string{}, false);
        }
References add_option().
Referenced by retire_option().
add_option() [2/4]
template<typename AssignTo , typename ConvertTo = AssignTo, enable_if_t<!std::is_const< ConvertTo >::value, detail::enabler > = detail::dummy> Option * App::add_option (std::string option_name, AssignTo & variable, std::string option_description = "") inline
Add option for assigning to a variable.
Parameters
variable The variable to set
Definition at line 6709 of file CLI11.hpp.
{
            auto fun = [&variable](const CLI::results_t& res) { // comment for spacing
                return detail::lexical_conversion<AssignTo, ConvertTo>(res, variable);
            };
            Option* opt = add_option(option_name, fun, option_description, false, [&variable]() {
                return CLI::detail::checked_to_string<AssignTo, ConvertTo>(variable);
            });
            opt->type_name(detail::type_name<ConvertTo>());
            // these must be actual lvalues since (std::max) sometimes is defined in terms of references and references
            // to structs used in the evaluation can be temporary so that would cause issues.
            auto Tcount = detail::type_count<AssignTo>::value;
            auto XCcount = detail::type_count<ConvertTo>::value;
            opt->type_size(detail::type_count_min<ConvertTo>::value, (std::max)(Tcount, XCcount));
            opt->expected(detail::expected_count<ConvertTo>::value);
            opt->run_callback_for_default();
            return opt;
        }
References Option::run_callback_for_default(), and Option::type_name().
add_option() [3/4]
Option * App::add_option (std::string option_name, callback_t option_callback, std::string option_description = "", bool defaulted = false, std::function< std::string()> func = {}) inline
Add an option, will automatically understand the type for common types.
To use, create a variable with the expected type, and pass it in after the name. After start is called, you can use count to see if the value was passed, and the value will be initialized properly. Numbers, vectors, and strings are supported.
->required(), ->default, and the validators are options, The positional options take an optional number of arguments.
For example,
std::string filename;
program.add_option("filename", filename, "description of filename");
Definition at line 7820 of file CLI11.hpp.
{
        Option myopt{option_name, option_description, option_callback, this};
        if (std::find_if(std::begin(options_), std::end(options_), [&myopt](const Option_p& v) {
                return *v == myopt;
            }) == std::end(options_)) {
            options_.emplace_back();
            Option_p& option = options_.back();
            option.reset(new Option(option_name, option_description, option_callback, this));
            // Set the default string capture function
            option->default_function(func);
            // For compatibility with CLI11 1.7 and before, capture the default string here
            if (defaulted)
                option->capture_default_str();
            // Transfer defaults to the new option
            option_defaults_.copy_to(option.get());
            // Don't bother to capture if we already did
            if (!defaulted && option->get_always_capture_default())
                option->capture_default_str();
            return option.get();
        }
        // we know something matches now find what it is so we can produce more error information
        for (auto& opt : options_) {
            const auto& matchname = opt->matching_name(myopt);
            if (!matchname.empty()) {
                throw(OptionAlreadyAdded("added option matched existing option name: " + matchname));
            }
        }
        // this line should not be reached the above loop should trigger the throw
        throw(OptionAlreadyAdded("added option matched existing option name")); // LCOV_EXCL_LINE
    }
Referenced by add_option().
add_option() [4/4]
template<typename T , enable_if_t< std::is_const< T >::value &&std::is_constructible< std::string, T >::value, detail::enabler > = detail::dummy> Option * App::add_option (std::string option_name, T & option_description) inline
Add option with description but with no variable assignment or callback.
Definition at line 6778 of file CLI11.hpp.
{
            return add_option(option_name, CLI::callback_t(), option_description, false);
        }
add_option_function()
template<typename ArgType > Option * App::add_option_function (std::string option_name, const std::function< void(const ArgType &)> & func, std::string option_description = "") inline
Add option for a callback of a specific type.
Parameters
func the callback to execute
Definition at line 6751 of file CLI11.hpp.
{
            auto fun = [func](const CLI::results_t& res) {
                ArgType variable;
                bool result = detail::lexical_conversion<ArgType, ArgType>(res, variable);
                if (result) {
                    func(variable);
                }
                return result;
            };
            Option* opt = add_option(option_name, std::move(fun), option_description, false);
            opt->type_name(detail::type_name<ArgType>());
            opt->type_size(detail::type_count_min<ArgType>::value, detail::type_count<ArgType>::value);
            opt->expected(detail::expected_count<ArgType>::value);
            return opt;
        }
References Option::type_name().
add_option_group()
template<typename T = Option_group> T * App::add_option_group (std::string group_name, std::string group_description = "") inline
creates an option group as part of the given app
Definition at line 6884 of file CLI11.hpp.
{
            if (!detail::valid_alias_name_string(group_name)) {
                throw IncorrectConstruction("option group names may not contain newlines or null characters");
            }
            auto option_group = std::make_shared<T>(std::move(group_description), group_name, this);
            auto* ptr = option_group.get();
            // move to App_p for overload resolution on older gcc versions
            App_p app_ptr = std::dynamic_pointer_cast<App>(option_group);
            add_subcommand(std::move(app_ptr));
            return ptr;
        }
References CLI::detail::valid_alias_name_string().
add_option_no_stream()
template<typename AssignTo , enable_if_t<!std::is_const< AssignTo >::value, detail::enabler > = detail::dummy> Option * App::add_option_no_stream (std::string option_name, AssignTo & variable, std::string option_description = "") inline
Add option for assigning to a variable.
Parameters
variable The variable to set
Definition at line 6732 of file CLI11.hpp.
{
            auto fun = [&variable](const CLI::results_t& res) { // comment for spacing
                return detail::lexical_conversion<AssignTo, AssignTo>(res, variable);
            };
            Option* opt = add_option(option_name, fun, option_description, false, []() {
                return std::string{};
            });
            opt->type_name(detail::type_name<AssignTo>());
            opt->type_size(detail::type_count_min<AssignTo>::value, detail::type_count<AssignTo>::value);
            opt->expected(detail::expected_count<AssignTo>::value);
            opt->run_callback_for_default();
            return opt;
        }
References Option::run_callback_for_default(), and Option::type_name().
add_subcommand() [1/2]
App * App::add_subcommand (CLI::App_p subcom) inline
Add a previously created app as a subcommand.
Definition at line 8049 of file CLI11.hpp.
{
        if (!subcom)
            throw IncorrectConstruction("passed App is not valid");
        auto* ckapp = (name_.empty() && parent_ != nullptr) ? _get_fallthrough_parent() : this;
        const auto& mstrg = _compare_subcommand_names(*subcom, *ckapp);
        if (!mstrg.empty()) {
            throw(OptionAlreadyAdded("subcommand name or alias matches existing subcommand: " + mstrg));
        }
        subcom->parent_ = this;
        subcommands_.push_back(std::move(subcom));
        return subcommands_.back().get();
    }
References _get_fallthrough_parent(), name_, and parent_.
add_subcommand() [2/2]
App * App::add_subcommand (std::string subcommand_name = "", std::string subcommand_description = "") inline
Add a subcommand. Inherits INHERITABLE and OptionDefaults, and help flag.
Definition at line 8032 of file CLI11.hpp.
{
        if (!subcommand_name.empty() && !detail::valid_name_string(subcommand_name)) {
            if (!detail::valid_first_char(subcommand_name[0])) {
                throw IncorrectConstruction("Subcommand name starts with invalid character, '!' and '-' are not allowed");
            }
            for (auto c : subcommand_name) {
                if (!detail::valid_later_char(c)) {
                    throw IncorrectConstruction(std::string("Subcommand name contains invalid character ('") + c +
                                                "'), all characters are allowed except"
                                                "'=',':','{','}', and ' '");
                }
            }
        }
        CLI::App_p subcom = std::shared_ptr<App>(new App(std::move(subcommand_description), subcommand_name, this));
        return add_subcommand(std::move(subcom));
    }
References CLI::detail::valid_name_string().
alias()
App * App::alias (std::string app_name) inline
Set an alias for the app.
Definition at line 7762 of file CLI11.hpp.
{
        if (app_name.empty() || !detail::valid_alias_name_string(app_name)) {
            throw IncorrectConstruction("Aliases may not be empty or contain newlines or null characters");
        }
        if (parent_ != nullptr) {
            aliases_.push_back(app_name);
            const auto& res = _compare_subcommand_names(*this, *_get_fallthrough_parent());
            if (!res.empty()) {
                aliases_.pop_back();
                throw(OptionAlreadyAdded("alias already matches an existing subcommand: " + app_name));
            }
        } else {
            aliases_.push_back(app_name);
        }
        return this;
    }
References _compare_subcommand_names(), _get_fallthrough_parent(), parent_, and CLI::detail::valid_alias_name_string().
allow_config_extras() [1/2]
App * App::allow_config_extras (bool allow = true) inline
ignore extras in config files
Definition at line 6606 of file CLI11.hpp.
{
            if (allow) {
                allow_config_extras_ = config_extras_mode::capture;
                allow_extras_ = true;
            } else {
                allow_config_extras_ = config_extras_mode::error;
            }
            return this;
        }
References allow_config_extras_, allow_extras_, capture, and error.
allow_config_extras() [2/2]
App * App::allow_config_extras (config_extras_mode mode) inline
ignore extras in config files
Definition at line 6617 of file CLI11.hpp.
{
            allow_config_extras_ = mode;
            return this;
        }
References allow_config_extras_.
allow_extras()
App * App::allow_extras (bool allow = true) inline
Remove the error when extras are left over on the command line.
Definition at line 6546 of file CLI11.hpp.
{
            allow_extras_ = allow;
            return this;
        }
References allow_extras_.
allow_windows_style_options()
App * App::allow_windows_style_options (bool value = true) inline
Allow windows style options, such as /opt. First matching short or long name used. Subcommands inherit value.
Definition at line 6633 of file CLI11.hpp.
{
            allow_windows_style_options_ = value;
            return this;
        }
References allow_windows_style_options_.
callback()
App * App::callback (std::function< void()> app_callback) inline
Set a callback for execution when all parsing and processing has completed
Due to a bug in c++11, it is not possible to overload on std::function (fixed in c++14 and backported to c++11 on newer compilers). Use capture by reference to get a pointer to App if needed.
Definition at line 6509 of file CLI11.hpp.
{
            if (immediate_callback_) {
                parse_complete_callback_ = std::move(app_callback);
            } else {
                final_callback_ = std::move(app_callback);
            }
            return this;
        }
References immediate_callback_.
check_name()
bool App::check_name (std::string name_to_check) const inline
Check the name, case insensitive and underscore insensitive if set.
Definition at line 8509 of file CLI11.hpp.
{
        std::string local_name = name_;
        if (ignore_underscore_) {
            local_name = detail::remove_underscore(name_);
            name_to_check = detail::remove_underscore(name_to_check);
        }
        if (ignore_case_) {
            local_name = detail::to_lower(name_);
            name_to_check = detail::to_lower(name_to_check);
        }
        if (local_name == name_to_check) {
            return true;
        }
        for (auto les : aliases_) { // NOLINT(performance-for-range-copy)
            if (ignore_underscore_) {
                les = detail::remove_underscore(les);
            }
            if (ignore_case_) {
                les = detail::to_lower(les);
            }
            if (les == name_to_check) {
                return true;
            }
        }
        return false;
    }
References ignore_case_, ignore_underscore_, name_, CLI::detail::remove_underscore(), and CLI::detail::to_lower().
clear()
void App::clear () inline
Reset the parsed data.
Definition at line 8156 of file CLI11.hpp.
{
        parsed_ = 0;
        pre_parse_called_ = false;
        missing_.clear();
        parsed_subcommands_.clear();
        for (const Option_p& opt : options_) {
            opt->clear();
        }
        for (const App_p& subc : subcommands_) {
            subc->clear();
        }
    }
References parsed_, and pre_parse_called_.
Referenced by _trigger_pre_parse(), parse(), and parse().
clear_aliases()
App * App::clear_aliases () inline
clear all the aliases of the current App
Definition at line 7449 of file CLI11.hpp.
{
            aliases_.clear();
            return this;
        }
config_formatter()
App * App::config_formatter (std::shared_ptr< Config > fmt) inline
Set the config formatter.
Definition at line 6666 of file CLI11.hpp.
{
            config_formatter_ = fmt;
            return this;
        }
config_to_str()
std::string App::config_to_str (bool default_also = false, bool write_description = false) const inline
Produce a string that could be read in as a config of the current values of the App. Set default_also to include default arguments. write_descriptions will print a description for the App and for each option.
Definition at line 7190 of file CLI11.hpp.
{
            return config_formatter_->to_config(this, default_also, write_description, "");
        }
configurable()
App * App::configurable (bool value = true) inline
Specify that the subcommand can be triggered by a config file.
Definition at line 6645 of file CLI11.hpp.
{
            configurable_ = value;
            return this;
        }
References configurable_.
count() [1/2]
std::size_t App::count () const inline
No argument version of count counts the number of times this subcommand was passed in. The main app will return 1. Unnamed subcommands will also return 1 unless otherwise modified in a callback
Definition at line 6935 of file CLI11.hpp.
{
            return parsed_;
        }
References parsed_.
count() [2/2]
std::size_t App::count (std::string option_name) const inline
Counts the number of times the given option was passed.
Definition at line 7080 of file CLI11.hpp.
{
            return get_option(option_name)->count();
        }
References Option::count(), and get_option().
count_all()
std::size_t App::count_all () const inline
Get a count of all the arguments processed in options and subcommands, this excludes arguments which were treated as extras.
Definition at line 8142 of file CLI11.hpp.
{
        std::size_t cnt{0};
        for (const auto& opt : options_) {
            cnt += opt->count();
        }
        for (const auto& sub : subcommands_) {
            cnt += sub->count_all();
        }
        if (!get_name().empty()) { // for named subcommands add the number of times the subcommand was called
            cnt += parsed_;
        }
        return cnt;
    }
References get_name(), and parsed_.
Referenced by _process_requirements(), and run_callback().
description()
App * App::description (std::string app_description) inline
Set the description of the app.
Definition at line 7230 of file CLI11.hpp.
{
            description_ = std::move(app_description);
            return this;
        }
References description_.
disabled()
App * App::disabled (bool disable = true) inline
Disable the subcommand or option group.
Definition at line 6558 of file CLI11.hpp.
{
            disabled_ = disable;
            return this;
        }
References disabled_.
Referenced by net::config::ConfigSection::addFlag(), net::config::ConfigSection::addFlagFunction(), net::config::ConfigSection::addOption(), TriggerOff(), and TriggerOn().
disabled_by_default()
App * App::disabled_by_default (bool disable = true) inline
Set the subcommand to be disabled by default, so on clear(), at the start of each parse it is disabled.
Definition at line 6570 of file CLI11.hpp.
{
            if (disable) {
                default_startup = startup_mode::disabled;
            } else {
                default_startup = (default_startup == startup_mode::enabled) ? startup_mode::enabled : startup_mode::stable;
            }
            return this;
        }
References default_startup, disabled, enabled, and stable.
Referenced by TriggerOff(), and TriggerOn().
enabled_by_default()
App * App::enabled_by_default (bool enable = true) inline
Set the subcommand to be enabled by default, so on clear(), at the start of each parse it is enabled (not disabled)
Definition at line 6581 of file CLI11.hpp.
{
            if (enable) {
                default_startup = startup_mode::enabled;
            } else {
                default_startup = (default_startup == startup_mode::disabled) ? startup_mode::disabled : startup_mode::stable;
            }
            return this;
        }
References default_startup, disabled, enabled, and stable.
Referenced by TriggerOff(), and TriggerOn().
excludes() [1/2]
App * App::excludes (App * app) inline
Sets excluded subcommands for the subcommand.
Definition at line 7119 of file CLI11.hpp.
{
            if (app == nullptr) {
                throw OptionNotFound("nullptr passed");
            }
            if (app == this) {
                throw OptionNotFound("cannot self reference in needs");
            }
            auto res = exclude_subcommands_.insert(app);
            // subcommand exclusion should be symmetric
            if (res.second) {
                app->exclude_subcommands_.insert(this);
            }
            return this;
        }
excludes() [2/2]
App * App::excludes (Option * opt) inline
Sets excluded options for the subcommand.
Definition at line 7110 of file CLI11.hpp.
{
            if (opt == nullptr) {
                throw OptionNotFound("nullptr passed");
            }
            exclude_options_.insert(opt);
            return this;
        }
exit()
int App::exit (const Error & e, std::ostream & out = std::cout, std::ostream & err = std::cerr) const inline
Print a nice error message and return the exit code.
Avoid printing anything if this is a CLI::RuntimeError
Definition at line 8288 of file CLI11.hpp.
{
        if (e.get_name() == "RuntimeError")
            return e.get_exit_code();
        if (e.get_name() == "CallForHelp") {
            out << help();
            return e.get_exit_code();
        }
        if (e.get_name() == "CallForAllHelp") {
            out << help("", AppFormatMode::All);
            return e.get_exit_code();
        }
        if (e.get_name() == "CallForVersion") {
            out << e.what() << std::endl;
            return e.get_exit_code();
        }
        if (e.get_exit_code() != static_cast<int>(ExitCodes::Success)) {
            if (failure_message_)
                err << failure_message_(this, e) << std::flush;
        }
        return e.get_exit_code();
    }
References All, Error::get_exit_code(), Error::get_name(), help(), and Success.
failure_message()
void App::failure_message (std::function< std::string(const App *, const Error &e)> function) inline
Provide a function to print a help message. The function gets access to the App pointer and error.
Definition at line 7068 of file CLI11.hpp.
{
            failure_message_ = function;
        }
fallthrough()
App * App::fallthrough (bool value = true) inline
Stop subcommand fallthrough, so that parent commands cannot collect commands after subcommand. Default from parent, usually set on parent.
Definition at line 7009 of file CLI11.hpp.
{
            fallthrough_ = value;
            return this;
        }
References fallthrough_.
final_callback()
App * App::final_callback (std::function< void()> app_callback) inline
Set a callback for execution when all parsing and processing has completed aliased as callback
Definition at line 6520 of file CLI11.hpp.
{
            final_callback_ = std::move(app_callback);
            return this;
        }
Referenced by net::config::ConfigTlsServer::ConfigTlsServer().
footer() [1/2]
App * App::footer (std::function< std::string()> footer_function) inline
Set footer.
Definition at line 7184 of file CLI11.hpp.
{
            footer_callback_ = std::move(footer_function);
            return this;
        }
footer() [2/2]
App * App::footer (std::string footer_string) inline
Set footer.
Definition at line 7179 of file CLI11.hpp.
{
            footer_ = std::move(footer_string);
            return this;
        }
References footer_.
formatter()
App * App::formatter (std::shared_ptr< FormatterBase > fmt) inline
Set the help formatter.
Definition at line 6654 of file CLI11.hpp.
{
            formatter_ = fmt;
            return this;
        }
formatter_fn()
App * App::formatter_fn (std::function< std::string(const App *, std::string, AppFormatMode)> fmt) inline
Set the help formatter.
Definition at line 6660 of file CLI11.hpp.
{
            formatter_ = std::make_shared<FormatterLambda>(fmt);
            return this;
        }
get_aliases()
const std::vector< std::string > & App::get_aliases () const inline
Get the aliases of the current app.
Definition at line 7444 of file CLI11.hpp.
{
            return aliases_;
        }
get_allow_config_extras()
config_extras_mode App::get_allow_config_extras () const inline
Get the status of allow extras.
Definition at line 7389 of file CLI11.hpp.
{
            return allow_config_extras_;
        }
References allow_config_extras_.
Referenced by _parse_single_config().
get_allow_extras()
bool App::get_allow_extras () const inline
Get the status of allow extras.
Definition at line 7346 of file CLI11.hpp.
{
            return allow_extras_;
        }
References allow_extras_.
get_allow_windows_style_options()
bool App::get_allow_windows_style_options () const inline
Check the status of the allow windows style options.
Definition at line 7291 of file CLI11.hpp.
{
            return allow_windows_style_options_;
        }
References allow_windows_style_options_.
get_config_formatter()
std::shared_ptr< Config > App::get_config_formatter () const inline
Access the config formatter.
Definition at line 7210 of file CLI11.hpp.
{
            return config_formatter_;
        }
get_config_formatter_base()
std::shared_ptr< ConfigBase > App::get_config_formatter_base () const inline
Access the config formatter as a configBase pointer.
Definition at line 7215 of file CLI11.hpp.
{
            // This is safer as a dynamic_cast if we have RTTI, as Config -> ConfigBase
#if CLI11_USE_STATIC_RTTI == 0
            return std::dynamic_pointer_cast<ConfigBase>(config_formatter_);
#else
            return std::static_pointer_cast<ConfigBase>(config_formatter_);
#endif
        }
get_config_ptr() [1/2]
Option * App::get_config_ptr () inline
Get a pointer to the config option.
Definition at line 7409 of file CLI11.hpp.
{
            return config_ptr_;
        }
References config_ptr_.
get_config_ptr() [2/2]
const Option * App::get_config_ptr () const inline
Get a pointer to the config option. (const)
Definition at line 7414 of file CLI11.hpp.
{
            return config_ptr_;
        }
References config_ptr_.
get_configurable()
bool App::get_configurable () const inline
Check the status of the allow windows style options.
Definition at line 7301 of file CLI11.hpp.
{
            return configurable_;
        }
References configurable_.
Referenced by ConfigBase::to_config().
get_description()
std::string App::get_description () const inline
Get the app or subcommand description.
Definition at line 7225 of file CLI11.hpp.
{
            return description_;
        }
References description_.
Referenced by CLI::HelpFormatter::make_description(), Formatter::make_description(), CLI::HelpFormatter::make_subcommand(), Formatter::make_subcommand(), CLI::ConfigFormatter::to_config(), and ConfigBase::to_config().
get_disabled()
bool App::get_disabled () const inline
Get the status of disabled.
Definition at line 7356 of file CLI11.hpp.
{
            return disabled_;
        }
References disabled_.
Referenced by utils::Config::addInstance(), and net::config::ConfigInstance::addSection().
get_disabled_by_default()
bool App::get_disabled_by_default () const inline
Get the status of disabled by default.
Definition at line 7371 of file CLI11.hpp.
{
            return (default_startup == startup_mode::disabled);
        }
References default_startup, and disabled.
get_display_name()
std::string App::get_display_name (bool with_aliases = false) const inline
Get a display name for an app.
Definition at line 8493 of file CLI11.hpp.
{
        if (name_.empty()) {
            return std::string("[Option Group: ") + get_group() + "]";
        }
        if (aliases_.empty() || !with_aliases) {
            return name_;
        }
        std::string dispname = name_;
        for (const auto& lalias : aliases_) {
            dispname.push_back(',');
            dispname.push_back(' ');
            dispname.append(lalias);
        }
        return dispname;
    }
References name_.
Referenced by _process_requirements(), CLI::HelpFormatter::make_expanded(), Formatter::make_expanded(), CLI::HelpFormatter::make_subcommand(), and Formatter::make_subcommand().
get_enabled_by_default()
bool App::get_enabled_by_default () const inline
Get the status of disabled by default.
Definition at line 7376 of file CLI11.hpp.
{
            return (default_startup == startup_mode::enabled);
        }
References default_startup, and enabled.
get_fallthrough()
bool App::get_fallthrough () const inline
Check the status of fallthrough.
Definition at line 7286 of file CLI11.hpp.
{
            return fallthrough_;
        }
References fallthrough_.
get_footer()
std::string App::get_footer () const inline
Generate and return the footer.
Definition at line 7316 of file CLI11.hpp.
{
            return (footer_callback_) ? footer_callback_() + '\n' + footer_ : footer_;
        }
Referenced by Formatter::make_footer().
get_formatter()
std::shared_ptr< FormatterBase > App::get_formatter () const inline
Access the formatter.
Definition at line 7205 of file CLI11.hpp.
{
            return formatter_;
        }
get_group()
const std::string & App::get_group () const inline
Get the group of this subcommand.
Definition at line 7306 of file CLI11.hpp.
{
            return group_;
        }
Referenced by utils::Config::addHelp(), and Formatter::make_help().
get_groups()
std::vector< std::string > App::get_groups () const inline
Get the groups available directly from this option (in order)
Definition at line 8537 of file CLI11.hpp.
{
        std::vector<std::string> groups;
        for (const Option_p& opt : options_) {
            // Add group if it is not already in there
            if (std::find(groups.begin(), groups.end(), opt->get_group()) == groups.end()) {
                groups.push_back(opt->get_group());
            }
        }
        return groups;
    }
get_help_all_ptr()
const Option * App::get_help_all_ptr () const inline
Get a pointer to the help all flag. (const)
Definition at line 7404 of file CLI11.hpp.
{
            return help_all_ptr_;
        }
References help_all_ptr_.
Referenced by _process_help_flags().
get_help_ptr() [1/2]
Option * App::get_help_ptr () inline
Get a pointer to the help flag.
Definition at line 7394 of file CLI11.hpp.
{
            return help_ptr_;
        }
References help_ptr_.
get_help_ptr() [2/2]
const Option * App::get_help_ptr () const inline
Get a pointer to the help flag. (const)
Definition at line 7399 of file CLI11.hpp.
{
            return help_ptr_;
        }
References help_ptr_.
Referenced by _process_help_flags().
get_ignore_case()
bool App::get_ignore_case () const inline
Check the status of ignore_case.
Definition at line 7276 of file CLI11.hpp.
{
            return ignore_case_;
        }
References ignore_case_.
get_ignore_underscore()
bool App::get_ignore_underscore () const inline
Check the status of ignore_underscore.
Definition at line 7281 of file CLI11.hpp.
{
            return ignore_underscore_;
        }
References ignore_underscore_.
get_immediate_callback()
bool App::get_immediate_callback () const inline
Get the status of disabled.
Definition at line 7366 of file CLI11.hpp.
{
            return immediate_callback_;
        }
References immediate_callback_.
get_name()
const std::string & App::get_name () const inline
Get the name of the current app.
Definition at line 7439 of file CLI11.hpp.
{
            return name_;
        }
References name_.
Referenced by _get_fallthrough_parent(), count_all(), get_subcommand(), get_subcommand_ptr(), help(), CLI::HelpFormatter::make_expanded(), Formatter::make_expanded(), Formatter::make_help(), and ConfigBase::to_config().
get_option() [1/2]
Option * App::get_option (std::string option_name) inline
Get an option by name (non-const version)
Definition at line 7257 of file CLI11.hpp.
{
            auto* opt = get_option_no_throw(option_name);
            if (opt == nullptr) {
                throw OptionNotFound(option_name);
            }
            return opt;
        }
References get_option_no_throw(), and OptionNotFound::OptionNotFound().
Referenced by deprecate_option(), and deprecate_option().
get_option() [2/2]
const Option * App::get_option (std::string option_name) const inline
Get an option by name.
Definition at line 7248 of file CLI11.hpp.
{
            const auto* opt = get_option_no_throw(option_name);
            if (opt == nullptr) {
                throw OptionNotFound(option_name);
            }
            return opt;
        }
References get_option_no_throw(), and OptionNotFound::OptionNotFound().
Referenced by count(), and operator[]().
get_option_group()
CLI::App * App::get_option_group (std::string group_name) const inline
Check to see if an option group is part of this App.
Definition at line 8133 of file CLI11.hpp.
{
        for (const App_p& app : subcommands_) {
            if (app->name_.empty() && app->group_ == group_name) {
                return app.get();
            }
        }
        throw OptionNotFound(group_name);
    }
References OptionNotFound::OptionNotFound().
get_option_no_throw() [1/2]
const Option * App::get_option_no_throw (std::string option_name) const inline noexcept
Get an option by name (noexcept const version)
Definition at line 8475 of file CLI11.hpp.
{
        for (const Option_p& opt : options_) {
            if (opt->check_name(option_name)) {
                return opt.get();
            }
        }
        for (const auto& subc : subcommands_) {
            // also check down into nameless subcommands
            if (subc->get_name().empty()) {
                auto* opt = subc->get_option_no_throw(option_name);
                if (opt != nullptr) {
                    return opt;
                }
            }
        }
        return nullptr;
    }
Referenced by get_option().
get_option_no_throw() [2/2]
Option * App::get_option_no_throw (std::string option_name) inline noexcept
Get an option by name (noexcept non-const version)
Definition at line 8457 of file CLI11.hpp.
{
        for (Option_p& opt : options_) {
            if (opt->check_name(option_name)) {
                return opt.get();
            }
        }
        for (auto& subc : subcommands_) {
            // also check down into nameless subcommands
            if (subc->get_name().empty()) {
                auto* opt = subc->get_option_no_throw(option_name);
                if (opt != nullptr) {
                    return opt;
                }
            }
        }
        return nullptr;
    }
Referenced by _parse_single_config(), get_option(), and retire_option().
get_options() [1/2]
std::vector< const Option * > App::get_options (const std::function< bool(const Option *)> filter = {}) const inline
Get the list of options (user facing function, so returns raw pointers), has optional filter function.
Definition at line 8421 of file CLI11.hpp.
{
        std::vector<const Option*> options(options_.size());
        std::transform(std::begin(options_), std::end(options_), std::begin(options), [](const Option_p& val) {
            return val.get();
        });
        if (filter) {
            options.erase(std::remove_if(std::begin(options),
                                         std::end(options),
                                         [&filter](const Option* opt) {
                                             return !filter(opt);
                                         }),
                          std::end(options));
        }
        return options;
    }
get_options() [2/2]
std::vector< Option * > App::get_options (const std::function< bool(Option *)> filter = {}) inline
Non-const version of the above.
Definition at line 8439 of file CLI11.hpp.
{
        std::vector<Option*> options(options_.size());
        std::transform(std::begin(options_), std::end(options_), std::begin(options), [](const Option_p& val) {
            return val.get();
        });
        if (filter) {
            options.erase(std::remove_if(std::begin(options),
                                         std::end(options),
                                         [&filter](Option* opt) {
                                             return !filter(opt);
                                         }),
                          std::end(options));
        }
        return options;
    }
get_parent() [1/2]
App * App::get_parent () inline
Get the parent of this subcommand (or nullptr if main app)
Definition at line 7429 of file CLI11.hpp.
{
            return parent_;
        }
References parent_.
Referenced by utils::createCommandLineTemplate().
get_parent() [2/2]
const App * App::get_parent () const inline
Get the parent of this subcommand (or nullptr if main app) (const version)
Definition at line 7434 of file CLI11.hpp.
{
            return parent_;
        }
References parent_.
Referenced by Formatter::make_help(), and ConfigBase::to_config().
get_positionals_at_end()
bool App::get_positionals_at_end () const inline
Check the status of the allow windows style options.
Definition at line 7296 of file CLI11.hpp.
{
            return positionals_at_end_;
        }
References positionals_at_end_.
get_prefix_command()
bool App::get_prefix_command () const inline
Get the prefix command status.
Definition at line 7341 of file CLI11.hpp.
{
            return prefix_command_;
        }
References prefix_command_.
get_require_option_max()
std::size_t App::get_require_option_max () const inline
Get the required max option value.
Definition at line 7336 of file CLI11.hpp.
{
            return require_option_max_;
        }
References require_option_max_.
Referenced by CLI::HelpFormatter::make_description(), and Formatter::make_description().
get_require_option_min()
std::size_t App::get_require_option_min () const inline
Get the required min option value.
Definition at line 7331 of file CLI11.hpp.
{
            return require_option_min_;
        }
References require_option_min_.
Referenced by CLI::HelpFormatter::make_description(), and Formatter::make_description().
get_require_subcommand_max()
std::size_t App::get_require_subcommand_max () const inline
Get the required max subcommand value.
Definition at line 7326 of file CLI11.hpp.
{
            return require_subcommand_max_;
        }
References require_subcommand_max_.
Referenced by Formatter::make_usage().
get_require_subcommand_min()
std::size_t App::get_require_subcommand_min () const inline
Get the required min subcommand value.
Definition at line 7321 of file CLI11.hpp.
{
            return require_subcommand_min_;
        }
References require_subcommand_min_.
Referenced by Formatter::make_usage().
get_required()
bool App::get_required () const inline
Get the status of required.
Definition at line 7351 of file CLI11.hpp.
{
            return required_;
        }
References required_.
Referenced by Formatter::make_description(), CLI::HelpFormatter::make_expanded(), CLI::HelpFormatter::make_subcommand(), Formatter::make_subcommand(), CLI::HelpFormatter::make_usage(), and net::config::ConfigInstance::required().
get_silent()
bool App::get_silent () const inline
Get the status of silence.
Definition at line 7361 of file CLI11.hpp.
{
            return silent_;
        }
References silent_.
get_subcommand() [1/3]
App * App::get_subcommand (const App * subcom) const inline
Check to see if a subcommand is part of this command (doesn't have to be in command line) returns the first subcommand if passed a nullptr
Definition at line 8079 of file CLI11.hpp.
{
        if (subcom == nullptr)
            throw OptionNotFound("nullptr passed");
        for (const App_p& subcomptr : subcommands_)
            if (subcomptr.get() == subcom)
                return subcomptr.get();
        throw OptionNotFound(subcom->get_name());
    }
References get_name(), and OptionNotFound::OptionNotFound().
Referenced by got_subcommand().
get_subcommand() [2/3]
App * App::get_subcommand (int index = 0) const inline
Get a pointer to subcommand by index.
Definition at line 8099 of file CLI11.hpp.
{
        if (index >= 0) {
            auto uindex = static_cast<unsigned>(index);
            if (uindex < subcommands_.size())
                return subcommands_[uindex].get();
        }
        throw OptionNotFound(std::to_string(index));
    }
References OptionNotFound::OptionNotFound().
get_subcommand() [3/3]
App * App::get_subcommand (std::string subcom) const inline
Check to see if a subcommand is part of this command (text version)
Definition at line 8088 of file CLI11.hpp.
{
        auto* subc = _find_subcommand(subcom, false, false);
        if (subc == nullptr)
            throw OptionNotFound(subcom);
        return subc;
    }
References _find_subcommand(), and OptionNotFound::OptionNotFound().
Referenced by got_subcommand().
get_subcommand_no_throw()
App * App::get_subcommand_no_throw (std::string subcom) const inline
Definition at line 8095 of file CLI11.hpp.
{
        return _find_subcommand(subcom, false, false);
    }
References _find_subcommand().
get_subcommand_ptr() [1/3]
CLI::App_p App::get_subcommand_ptr (App * subcom) const inline
Check to see if a subcommand is part of this command and get a shared_ptr to it.
Definition at line 8108 of file CLI11.hpp.
{
        if (subcom == nullptr)
            throw OptionNotFound("nullptr passed");
        for (const App_p& subcomptr : subcommands_)
            if (subcomptr.get() == subcom)
                return subcomptr;
        throw OptionNotFound(subcom->get_name());
    }
References get_name(), and OptionNotFound::OptionNotFound().
get_subcommand_ptr() [2/3]
CLI::App_p App::get_subcommand_ptr (int index = 0) const inline
Get an owning pointer to subcommand by index.
Definition at line 8124 of file CLI11.hpp.
{
        if (index >= 0) {
            auto uindex = static_cast<unsigned>(index);
            if (uindex < subcommands_.size())
                return subcommands_[uindex];
        }
        throw OptionNotFound(std::to_string(index));
    }
References OptionNotFound::OptionNotFound().
get_subcommand_ptr() [3/3]
CLI::App_p App::get_subcommand_ptr (std::string subcom) const inline
Check to see if a subcommand is part of this command (text version)
Definition at line 8117 of file CLI11.hpp.
{
        for (const App_p& subcomptr : subcommands_)
            if (subcomptr->check_name(subcom))
                return subcomptr;
        throw OptionNotFound(subcom);
    }
References OptionNotFound::OptionNotFound().
get_subcommands() [1/3]
std::vector< App * > App::get_subcommands () const inline
Get a subcommand pointer list to the currently selected subcommands (after parsing by default, in command line order; use parsed = false to get the original definition list.)
Definition at line 7086 of file CLI11.hpp.
{
            return parsed_subcommands_;
        }
get_subcommands() [2/3]
std::vector< App * > App::get_subcommands (const std::function< bool(App *)> & filter) inline
Get a filtered subcommand pointer list from the original definition list. An empty function will provide all subcommands
Definition at line 8334 of file CLI11.hpp.
{
        std::vector<App*> subcomms(subcommands_.size());
        std::transform(std::begin(subcommands_), std::end(subcommands_), std::begin(subcomms), [](const App_p& v) {
            return v.get();
        });
        if (filter) {
            subcomms.erase(std::remove_if(std::begin(subcomms),
                                          std::end(subcomms),
                                          [&filter](App* app) {
                                              return !filter(app);
                                          }),
                           std::end(subcomms));
        }
        return subcomms;
    }
get_subcommands() [3/3]
std::vector< const App * > App::get_subcommands (const std::function< bool(const App *)> & filter) const inline
Get a filtered subcommand pointer list from the original definition list. An empty function will provide all subcommands (const)
Definition at line 8316 of file CLI11.hpp.
{
        std::vector<const App*> subcomms(subcommands_.size());
        std::transform(std::begin(subcommands_), std::end(subcommands_), std::begin(subcomms), [](const App_p& v) {
            return v.get();
        });
        if (filter) {
            subcomms.erase(std::remove_if(std::begin(subcomms),
                                          std::end(subcomms),
                                          [&filter](const App* app) {
                                              return !filter(app);
                                          }),
                           std::end(subcomms));
        }
        return subcomms;
    }
get_usage()
std::string App::get_usage () const inline
Generate and return the usage.
Definition at line 7311 of file CLI11.hpp.
{
            return (usage_callback_) ? usage_callback_() + '\n' + usage_ : usage_;
        }
Referenced by CLI::HelpFormatter::make_usage(), and Formatter::make_usage().
get_validate_optional_arguments()
bool App::get_validate_optional_arguments () const inline
Get the status of validating optional vector arguments.
Definition at line 7384 of file CLI11.hpp.
{
            return validate_optional_arguments_;
        }
References validate_optional_arguments_.
get_validate_positionals()
bool App::get_validate_positionals () const inline
Get the status of validating positionals.
Definition at line 7380 of file CLI11.hpp.
{
            return validate_positionals_;
        }
References validate_positionals_.
get_version_ptr() [1/2]
Option * App::get_version_ptr () inline
Get a pointer to the version option.
Definition at line 7419 of file CLI11.hpp.
{
            return version_ptr_;
        }
References version_ptr_.
get_version_ptr() [2/2]
const Option * App::get_version_ptr () const inline
Get a pointer to the version option. (const)
Definition at line 7424 of file CLI11.hpp.
{
            return version_ptr_;
        }
References version_ptr_.
got_subcommand() [1/2]
bool App::got_subcommand (const App * subcom) const inline
Check to see if given subcommand was selected.
Definition at line 7099 of file CLI11.hpp.
{
            // get subcom needed to verify that this was a real subcommand
            return get_subcommand(subcom)->parsed_ > 0;
        }
References get_subcommand(), and parsed_.
got_subcommand() [2/2]
bool App::got_subcommand (std::string subcommand_name) const inline
Check with name instead of pointer to see if subcommand was selected.
Definition at line 7105 of file CLI11.hpp.
{
            return get_subcommand(subcommand_name)->parsed_ > 0;
        }
References get_subcommand(), and parsed_.
group()
App * App::group (std::string group_name) inline
Changes the group membership.
Definition at line 6944 of file CLI11.hpp.
{
            group_ = group_name;
            return this;
        }
Referenced by Option_group::Option_group().
help()
std::string App::help (std::string prev = "", AppFormatMode mode = AppFormatMode::Normal) const inline
Makes a help message, using the currently configured formatter Will only do one subcommand at a time
Definition at line 8390 of file CLI11.hpp.
{
        if (prev.empty())
            prev = get_name();
        else
            prev += " " + get_name();
        // Delegate to subcommand if needed
        auto selected_subcommands = get_subcommands();
        if (!selected_subcommands.empty()) {
            return selected_subcommands.back()->help(prev, mode);
        }
        return formatter_->make_help(this, prev, mode);
    }
References get_name().
Referenced by exit(), and FailureMessage::help().
ignore_case()
App * App::ignore_case (bool value = true) inline
Ignore case. Subcommands inherit value.
Definition at line 7792 of file CLI11.hpp.
{
        if (value && !ignore_case_) {
            ignore_case_ = true;
            auto* p = (parent_ != nullptr) ? _get_fallthrough_parent() : this;
            const auto& match = _compare_subcommand_names(*this, *p);
            if (!match.empty()) {
                ignore_case_ = false; // we are throwing so need to be exception invariant
                throw OptionAlreadyAdded("ignore case would cause subcommand name conflicts: " + match);
            }
        }
        ignore_case_ = value;
        return this;
    }
References _compare_subcommand_names(), _get_fallthrough_parent(), ignore_case_, and parent_.
ignore_underscore()
App * App::ignore_underscore (bool value = true) inline
Ignore underscore. Subcommands inherit value.
Definition at line 7806 of file CLI11.hpp.
{
        if (value && !ignore_underscore_) {
            ignore_underscore_ = true;
            auto* p = (parent_ != nullptr) ? _get_fallthrough_parent() : this;
            const auto& match = _compare_subcommand_names(*this, *p);
            if (!match.empty()) {
                ignore_underscore_ = false;
                throw OptionAlreadyAdded("ignore underscore would cause subcommand name conflicts: " + match);
            }
        }
        ignore_underscore_ = value;
        return this;
    }
References _compare_subcommand_names(), _get_fallthrough_parent(), ignore_underscore_, and parent_.
immediate_callback()
App * App::immediate_callback (bool immediate = true) inline
Set the subcommand callback to be executed immediately on subcommand completion.
Definition at line 7780 of file CLI11.hpp.
{
        immediate_callback_ = immediate;
        if (immediate_callback_) {
            if (final_callback_ && !(parse_complete_callback_)) {
                std::swap(final_callback_, parse_complete_callback_);
            }
        } else if (!(final_callback_) && parse_complete_callback_) {
            std::swap(final_callback_, parse_complete_callback_);
        }
        return this;
    }
References immediate_callback_.
increment_parsed()
void App::increment_parsed () inline protected
Internal function to recursively increment the parsed counter on the current app as well unnamed subcommands.
Definition at line 9013 of file CLI11.hpp.
{
        ++parsed_;
        for (App_p const& sub : subcommands_) {
            if (sub->get_name().empty())
                sub->increment_parsed();
        }
    }
References parsed_.
Referenced by _parse(), _parse(), _parse_arg(), _parse_single_config(), and _parse_stream().
name()
App * App::name (std::string app_name = "") inline
Set a name for the app (empty will use parser to set the name)
Definition at line 7746 of file CLI11.hpp.
{
        if (parent_ != nullptr) {
            auto oname = name_;
            name_ = app_name;
            const auto& res = _compare_subcommand_names(*this, *_get_fallthrough_parent());
            if (!res.empty()) {
                name_ = oname;
                throw(OptionAlreadyAdded(app_name + " conflicts with existing subcommand names"));
            }
        } else {
            name_ = app_name;
        }
        has_automatic_name_ = false;
        return this;
    }
References _compare_subcommand_names(), _get_fallthrough_parent(), has_automatic_name_, name_, and parent_.
needs() [1/2]
App * App::needs (App * app) inline
Definition at line 7142 of file CLI11.hpp.
{
            if (app == nullptr) {
                throw OptionNotFound("nullptr passed");
            }
            if (app == this) {
                throw OptionNotFound("cannot self reference in needs");
            }
            need_subcommands_.insert(app);
            return this;
        }
Referenced by net::config::ConfigInstance::required().
needs() [2/2]
App * App::needs (Option * opt) inline
Definition at line 7134 of file CLI11.hpp.
{
            if (opt == nullptr) {
                throw OptionNotFound("nullptr passed");
            }
            need_options_.insert(opt);
            return this;
        }
Referenced by net::config::ConfigSection::required().
operator bool()
App::operator bool () const inline explicit
Check to see if this subcommand was parsed, true only if received on command line. This allows the subcommand to be directly checked.
Definition at line 7016 of file CLI11.hpp.
{
            return parsed_ > 0;
        }
References parsed_.
operator=()
App & App::operator= (const App &) delete
operator[]() [1/2]
const Option * App::operator[] (const char * option_name) const inline
Shortcut bracket operator for getting a pointer to an option.
Definition at line 7271 of file CLI11.hpp.
{
            return get_option(option_name);
        }
operator[]() [2/2]
const Option * App::operator[] (const std::string & option_name) const inline
Shortcut bracket operator for getting a pointer to an option.
Definition at line 7266 of file CLI11.hpp.
{
            return get_option(option_name);
        }
References get_option().
option_defaults()
OptionDefaults * App::option_defaults () inline
Get the OptionDefault object, to set option defaults.
Definition at line 6677 of file CLI11.hpp.
{
            return &option_defaults_;
        }
Referenced by utils::Config::addInstance(), and net::config::ConfigInstance::addSection().
parse() [1/7]
void App::parse () inline
Parse the command-line arguments passed to the main function of the executable. This overload will correctly parse unicode arguments on Windows.
Definition at line 8170 of file CLI11.hpp.
{
        parse(argc(), argv());
    } // LCOV_EXCL_LINE
References CLI::argc(), CLI::argv(), and parse().
parse() [2/7]
void App::parse (int argc, const char *const * argv) inline
Parses the command line - throws errors. This must be called after the options are in but before the rest of the program.
Definition at line 8174 of file CLI11.hpp.
{
        parse_char_t(argc, argv);
    }
Referenced by main(), and parse().
parse() [3/7]
void App::parse (int argc, const wchar_t *const * argv) inline
Definition at line 8177 of file CLI11.hpp.
{
        parse_char_t(argc, argv);
    }
parse() [4/7]
void App::parse (std::string commandline, bool program_name_included = false) inline
Parse a single string as if it contained command line arguments. This function splits the string into arguments then calls parse(std::vector<std::string> &) the function takes an optional boolean argument specifying if the programName is included in the string to process
Definition at line 8209 of file CLI11.hpp.
{
        if (program_name_included) {
            auto nstr = detail::split_program_name(commandline);
            if ((name_.empty()) || (has_automatic_name_)) {
                has_automatic_name_ = true;
                name_ = nstr.first;
            }
            commandline = std::move(nstr.second);
        } else {
            detail::trim(commandline);
        }
        // the next section of code is to deal with quoted arguments after an '=' or ':' for windows like operations
        if (!commandline.empty()) {
            commandline = detail::find_and_modify(commandline, "=", detail::escape_detect);
            if (allow_windows_style_options_)
                commandline = detail::find_and_modify(commandline, ":", detail::escape_detect);
        }
        auto args = detail::split_up(std::move(commandline));
        // remove all empty strings
        args.erase(std::remove(args.begin(), args.end(), std::string{}), args.end());
        std::reverse(args.begin(), args.end());
        parse(std::move(args));
    }
References allow_windows_style_options_, CLI::escape_detect(), has_automatic_name_, name_, and CLI::detail::trim().
Referenced by parse().
parse() [5/7]
void App::parse (std::vector< std::string > && args) inline
The real work is done here. Expects a reversed vector.
Definition at line 8258 of file CLI11.hpp.
{
        // Clear if parsed
        if (parsed_ > 0)
            clear();
        // parsed_ is incremented in commands/subcommands,
        // but placed here to make sure this is cleared when
        // running parse after an error is thrown, even by _validate or _configure.
        parsed_ = 1;
        _validate();
        _configure();
        // set the parent as nullptr as this object should be the top now
        parent_ = nullptr;
        parsed_ = 0;
        _parse(std::move(args));
        run_callback();
    }
References _configure(), _validate(), clear(), parent_, parsed_, and run_callback().
parse() [6/7]
void App::parse (std::vector< std::string > & args) inline
The real work is done here. Expects a reversed vector. Changes the vector to the remaining options.
Definition at line 8239 of file CLI11.hpp.
{
        // Clear if parsed
        if (parsed_ > 0)
            clear();
        // parsed_ is incremented in commands/subcommands,
        // but placed here to make sure this is cleared when
        // running parse after an error is thrown, even by _validate or _configure.
        parsed_ = 1;
        _validate();
        _configure();
        // set the parent as nullptr as this object should be the top now
        parent_ = nullptr;
        parsed_ = 0;
        _parse(args);
        run_callback();
    }
References _configure(), _validate(), clear(), parent_, parsed_, and run_callback().
parse() [7/7]
void App::parse (std::wstring commandline, bool program_name_included = false) inline
Definition at line 8235 of file CLI11.hpp.
{
        parse(narrow(commandline), program_name_included);
    }
References CLI::narrow(), and parse().
parse_char_t()
template<class CharT > void App::parse_char_t (int argc, const CharT *const * argv) inline private
Definition at line 8194 of file CLI11.hpp.
{
        // If the name is not set, read from command line
        if (name_.empty() || has_automatic_name_) {
            has_automatic_name_ = true;
            name_ = detail::maybe_narrow(argv[0]);
        }
        std::vector<std::string> args;
        args.reserve(static_cast<std::size_t>(argc) - 1U);
        for (auto i = static_cast<std::size_t>(argc) - 1U; i > 0U; --i)
            args.emplace_back(detail::maybe_narrow(argv[i]));
        parse(std::move(args));
    }
References has_automatic_name_, and name_.
parse_complete_callback()
App * App::parse_complete_callback (std::function< void()> pc_callback) inline
Set a callback to execute when parsing has completed for the app
Definition at line 6527 of file CLI11.hpp.
{
            parse_complete_callback_ = std::move(pc_callback);
            return this;
        }
parse_from_stream()
void App::parse_from_stream (std::istream & input) inline
Definition at line 8277 of file CLI11.hpp.
{
        if (parsed_ == 0) {
            _validate();
            _configure();
            // set the parent as nullptr as this object should be the top now
        }
        _parse_stream(input);
        run_callback();
    }
References _configure(), _parse_stream(), _validate(), parsed_, and run_callback().
parse_order()
const std::vector< Option * > & App::parse_order () const inline
This gets a vector of pointers with the original parse order.
Definition at line 7464 of file CLI11.hpp.
{
            return parse_order_;
        }
parsed()
bool App::parsed () const inline
Check to see if this subcommand was parsed, true only if received on command line.
Definition at line 6672 of file CLI11.hpp.
{
            return parsed_ > 0;
        }
References parsed_.
positionals_at_end()
App * App::positionals_at_end (bool value = true) inline
Specify that the positional arguments are only at the end of the sequence.
Definition at line 6639 of file CLI11.hpp.
{
            positionals_at_end_ = value;
            return this;
        }
References positionals_at_end_.
pre_callback()
virtual void App::pre_callback () inline virtual
This allows subclasses to inject code before callbacks but after parse.
This does not run if any errors or help is thrown.
Definition at line 7027 of file CLI11.hpp.
{
        }
Referenced by run_callback().
prefix_command()
App * App::prefix_command (bool allow = true) inline
Do not parse anything after the first unrecognized option and return.
Definition at line 6623 of file CLI11.hpp.
{
            prefix_command_ = allow;
            return this;
        }
References prefix_command_.
preparse_callback()
App * App::preparse_callback (std::function< void(std::size_t)> pp_callback) inline
Set a callback to execute prior to parsing.
Definition at line 6534 of file CLI11.hpp.
{
            pre_parse_callback_ = std::move(pp_callback);
            return this;
        }
Referenced by TriggerOff(), TriggerOff(), TriggerOn(), and TriggerOn().
remaining()
std::vector< std::string > App::remaining (bool recurse = false) const inline
This returns the missing options from the current subcommand.
Definition at line 8550 of file CLI11.hpp.
{
        std::vector<std::string> miss_list;
        for (const std::pair<detail::Classifier, std::string>& miss : missing_) {
            miss_list.push_back(std::get<1>(miss));
        }
        // Get from a subcommand that may allow extras
        if (recurse) {
            if (!allow_extras_) {
                for (const auto& sub : subcommands_) {
                    if (sub->name_.empty() && !sub->missing_.empty()) {
                        for (const std::pair<detail::Classifier, std::string>& miss : sub->missing_) {
                            miss_list.push_back(std::get<1>(miss));
                        }
                    }
                }
            }
            // Recurse into subcommands
            for (const App* sub : parsed_subcommands_) {
                std::vector<std::string> output = sub->remaining(recurse);
                std::copy(std::begin(output), std::end(output), std::back_inserter(miss_list));
            }
        }
        return miss_list;
    }
References allow_extras_.
remaining_for_passthrough()
std::vector< std::string > App::remaining_for_passthrough (bool recurse = false) const inline
This returns the missing options in a form ready for processing by another command line program.
Definition at line 8576 of file CLI11.hpp.
{
        std::vector<std::string> miss_list = remaining(recurse);
        std::reverse(std::begin(miss_list), std::end(miss_list));
        return miss_list;
    }
remaining_size()
std::size_t App::remaining_size (bool recurse = false) const inline
This returns the number of remaining options, minus the – separator.
Definition at line 8582 of file CLI11.hpp.
{
        auto remaining_options = static_cast<std::size_t>(
            std::count_if(std::begin(missing_), std::end(missing_), [](const std::pair<detail::Classifier, std::string>& val) {
                return val.first != detail::Classifier::POSITIONAL_MARK;
            }));
        if (recurse) {
            for (const App_p& sub : subcommands_) {
                remaining_options += sub->remaining_size(recurse);
            }
        }
        return remaining_options;
    }
Referenced by _process_extras(), and _process_extras().
remove_excludes() [1/2]
bool App::remove_excludes (App * app) inline
Removes a subcommand from the excludes list of this subcommand.
Definition at line 8361 of file CLI11.hpp.
{
        auto iterator = std::find(std::begin(exclude_subcommands_), std::end(exclude_subcommands_), app);
        if (iterator == std::end(exclude_subcommands_)) {
            return false;
        }
        auto* other_app = *iterator;
        exclude_subcommands_.erase(iterator);
        other_app->remove_excludes(this);
        return true;
    }
remove_excludes() [2/2]
bool App::remove_excludes (Option * opt) inline
Removes an option from the excludes list of this subcommand.
Definition at line 8352 of file CLI11.hpp.
{
        auto iterator = std::find(std::begin(exclude_options_), std::end(exclude_options_), opt);
        if (iterator == std::end(exclude_options_)) {
            return false;
        }
        exclude_options_.erase(iterator);
        return true;
    }
remove_needs() [1/2]
bool App::remove_needs (App * app) inline
Removes a subcommand from the needs list of this subcommand.
Definition at line 8381 of file CLI11.hpp.
{
        auto iterator = std::find(std::begin(need_subcommands_), std::end(need_subcommands_), app);
        if (iterator == std::end(need_subcommands_)) {
            return false;
        }
        need_subcommands_.erase(iterator);
        return true;
    }
Referenced by net::config::ConfigInstance::required().
remove_needs() [2/2]
bool App::remove_needs (Option * opt) inline
Removes an option from the needs list of this subcommand.
Definition at line 8372 of file CLI11.hpp.
{
        auto iterator = std::find(std::begin(need_options_), std::end(need_options_), opt);
        if (iterator == std::end(need_options_)) {
            return false;
        }
        need_options_.erase(iterator);
        return true;
    }
Referenced by net::config::ConfigSection::required().
remove_option()
bool App::remove_option (Option * opt) inline
Removes an option from the App. Takes an option pointer. Returns true if found and removed.
Definition at line 8010 of file CLI11.hpp.
{
        // Make sure no links exist
        for (Option_p& op : options_) {
            op->remove_needs(opt);
            op->remove_excludes(opt);
        }
        if (help_ptr_ == opt)
            help_ptr_ = nullptr;
        if (help_all_ptr_ == opt)
            help_all_ptr_ = nullptr;
        auto iterator = std::find_if(std::begin(options_), std::end(options_), [opt](const Option_p& v) {
            return v.get() == opt;
        });
        if (iterator != std::end(options_)) {
            options_.erase(iterator);
            return true;
        }
        return false;
    }
References help_all_ptr_, and help_ptr_.
Referenced by _add_flag_internal(), retire_option(), set_config(), set_help_all_flag(), set_help_flag(), set_version_flag(), and set_version_flag().
remove_subcommand()
bool App::remove_subcommand (App * subcom) inline
Removes a subcommand from the App. Takes a subcommand pointer. Returns true if found and removed.
Definition at line 8062 of file CLI11.hpp.
{
        // Make sure no links exist
        for (App_p const& sub : subcommands_) {
            sub->remove_excludes(subcom);
            sub->remove_needs(subcom);
        }
        auto iterator = std::find_if(std::begin(subcommands_), std::end(subcommands_), [subcom](const App_p& v) {
            return v.get() == subcom;
        });
        if (iterator != std::end(subcommands_)) {
            subcommands_.erase(iterator);
            return true;
        }
        return false;
    }
require_option() [1/3]
App * App::require_option () inline
The argumentless form of require option requires 1 or more options be used.
Definition at line 6979 of file CLI11.hpp.
{
            require_option_min_ = 1;
            require_option_max_ = 0;
            return this;
        }
References require_option_max_, and require_option_min_.
require_option() [2/3]
App * App::require_option (int value) inline
Require an option to be given (does not affect help call) The number required can be given. Negative values indicate maximum number allowed (0 for any number).
Definition at line 6988 of file CLI11.hpp.
{
            if (value < 0) {
                require_option_min_ = 0;
                require_option_max_ = static_cast<std::size_t>(-value);
            } else {
                require_option_min_ = static_cast<std::size_t>(value);
                require_option_max_ = static_cast<std::size_t>(value);
            }
            return this;
        }
References require_option_max_, and require_option_min_.
require_option() [3/3]
App * App::require_option (std::size_t min, std::size_t max) inline
Explicitly control the number of options required. Setting 0 for the max means unlimited number allowed. Max number inheritable.
Definition at line 7001 of file CLI11.hpp.
{
            require_option_min_ = min;
            require_option_max_ = max;
            return this;
        }
References require_option_max_, and require_option_min_.
require_subcommand() [1/3]
App * App::require_subcommand () inline
The argumentless form of require subcommand requires 1 or more subcommands.
Definition at line 6950 of file CLI11.hpp.
{
            require_subcommand_min_ = 1;
            require_subcommand_max_ = 0;
            return this;
        }
References require_subcommand_max_, and require_subcommand_min_.
require_subcommand() [2/3]
App * App::require_subcommand (int value) inline
Require a subcommand to be given (does not affect help call) The number required can be given. Negative values indicate maximum number allowed (0 for any number). Max number inheritable.
Definition at line 6959 of file CLI11.hpp.
{
            if (value < 0) {
                require_subcommand_min_ = 0;
                require_subcommand_max_ = static_cast<std::size_t>(-value);
            } else {
                require_subcommand_min_ = static_cast<std::size_t>(value);
                require_subcommand_max_ = static_cast<std::size_t>(value);
            }
            return this;
        }
References require_subcommand_max_, and require_subcommand_min_.
require_subcommand() [3/3]
App * App::require_subcommand (std::size_t min, std::size_t max) inline
Explicitly control the number of subcommands required. Setting 0 for the max means unlimited number allowed. Max number inheritable.
Definition at line 6972 of file CLI11.hpp.
{
            require_subcommand_min_ = min;
            require_subcommand_max_ = max;
            return this;
        }
References require_subcommand_max_, and require_subcommand_min_.
required()
App * App::required (bool require = true) inline
Remove the error when extras are left over on the command line.
Definition at line 6552 of file CLI11.hpp.
{
            required_ = require;
            return this;
        }
References required_.
Referenced by utils::Config::disabled(), main(), net::config::ConfigInstance::required(), and utils::Config::required().
run_callback()
void App::run_callback (bool final_mode = false, bool suppress_final_callback = false) inline protected
Internal function to run (App) callback, bottom up.
Definition at line 8649 of file CLI11.hpp.
{
        pre_callback();
        // in the main app if immediate_callback_ is set it runs the main callback before the used subcommands
        if (!final_mode && parse_complete_callback_) {
            parse_complete_callback_();
        }
        // run the callbacks for the received subcommands
        for (App* subc : get_subcommands()) {
            if (subc->parent_ == this) {
                subc->run_callback(true, suppress_final_callback);
            }
        }
        // now run callbacks for option_groups
        for (auto& subc : subcommands_) {
            if (subc->name_.empty() && subc->count_all() > 0) {
                subc->run_callback(true, suppress_final_callback);
            }
        }
        // finally run the main callback
        if (final_callback_ && (parsed_ > 0) && (!suppress_final_callback)) {
            if (!name_.empty() || count_all() > 0 || parent_ == nullptr) {
                final_callback_();
            }
        }
    }
References count_all(), name_, parent_, and pre_callback().
Referenced by _parse(), _parse_single_config(), parse(), parse(), and parse_from_stream().
set_config()
Option * App::set_config (std::string option_name = "", std::string default_filename = "", const std::string & help_message = "Read an ini file", bool config_required = false) inline
Set a configuration ini file option, or clear it if no name passed.
Definition at line 7988 of file CLI11.hpp.
{
        // Remove existing config if present
        if (config_ptr_ != nullptr) {
            remove_option(config_ptr_);
            config_ptr_ = nullptr; // need to remove the config_ptr completely
        }
        // Only add config if option passed
        if (!option_name.empty()) {
            config_ptr_ = add_option(option_name, help_message);
            if (config_required) {
                config_ptr_->required();
            }
            if (!default_filename.empty()) {
                config_ptr_->default_str(std::move(default_filename));
            }
            config_ptr_->configurable(false);
        }
        return config_ptr_;
    }
References config_ptr_, Option::default_str(), and remove_option().
set_help_all_flag()
Option * App::set_help_all_flag (std::string help_name = "", const std::string & help_description = "") inline
Set a help all flag, replaced the existing one if present.
Definition at line 7877 of file CLI11.hpp.
{
        // take flag_description by const reference otherwise add_flag tries to assign to flag_description
        if (help_all_ptr_ != nullptr) {
            remove_option(help_all_ptr_);
            help_all_ptr_ = nullptr;
        }
        // Empty name will simply remove the help all flag
        if (!help_name.empty()) {
            help_all_ptr_ = add_flag(help_name, help_description);
            help_all_ptr_->configurable(false);
        }
        return help_all_ptr_;
    }
References help_all_ptr_, and remove_option().
Referenced by App(), and main().
set_help_flag()
Option * App::set_help_flag (std::string flag_name = "", const std::string & help_description = "") inline
Set a help flag, replace the existing one if present.
Definition at line 7861 of file CLI11.hpp.
{
        // take flag_description by const reference otherwise add_flag tries to assign to help_description
        if (help_ptr_ != nullptr) {
            remove_option(help_ptr_);
            help_ptr_ = nullptr;
        }
        // Empty name will simply remove the help flag
        if (!flag_name.empty()) {
            help_ptr_ = add_flag(flag_name, help_description);
            help_ptr_->configurable(false);
        }
        return help_ptr_;
    }
References help_ptr_, and remove_option().
Referenced by App(), and App().
set_version_flag() [1/2]
Option * App::set_version_flag (std::string flag_name, std::function< std::string()> vfunc, const std::string & version_help = "Display program version information and exit") inline
Generate the version string through a callback function.
Definition at line 7914 of file CLI11.hpp.
{
        if (version_ptr_ != nullptr) {
            remove_option(version_ptr_);
            version_ptr_ = nullptr;
        }
        // Empty name will simply remove the version flag
        if (!flag_name.empty()) {
            version_ptr_ = add_flag_callback(
                flag_name,
                [vfunc]() {
                    throw(CLI::CallForVersion(vfunc(), 0));
                },
                version_help);
            version_ptr_->configurable(false);
        }
        return version_ptr_;
    }
References add_flag_callback(), remove_option(), and version_ptr_.
set_version_flag() [2/2]
Option * App::set_version_flag (std::string flag_name = "", const std::string & versionString = "", const std::string & version_help = "Display program version information and exit") inline
Set a version flag and version display string, replace the existing one if present.
Definition at line 7893 of file CLI11.hpp.
{
        // take flag_description by const reference otherwise add_flag tries to assign to version_description
        if (version_ptr_ != nullptr) {
            remove_option(version_ptr_);
            version_ptr_ = nullptr;
        }
        // Empty name will simply remove the version flag
        if (!flag_name.empty()) {
            version_ptr_ = add_flag_callback(
                flag_name,
                [versionString]() {
                    throw(CLI::CallForVersion(versionString, 0));
                },
                version_help);
            version_ptr_->configurable(false);
        }
        return version_ptr_;
    }
References add_flag_callback(), CallForVersion::CallForVersion(), remove_option(), and version_ptr_.
silent()
App * App::silent (bool silence = true) inline
silence the subcommand from showing up in the processed list
Definition at line 6564 of file CLI11.hpp.
{
            silent_ = silence;
            return this;
        }
References silent_.
usage() [1/2]
App * App::usage (std::function< std::string()> usage_function) inline
Set usage.
Definition at line 7174 of file CLI11.hpp.
{
            usage_callback_ = std::move(usage_function);
            return this;
        }
usage() [2/2]
App * App::usage (std::string usage_string) inline
Set usage.
Definition at line 7169 of file CLI11.hpp.
{
            usage_ = std::move(usage_string);
            return this;
        }
References usage_.
validate_optional_arguments()
App * App::validate_optional_arguments (bool validate = true) inline
Set the subcommand to validate optional vector arguments before assigning.
Definition at line 6600 of file CLI11.hpp.
{
            validate_optional_arguments_ = validate;
            return this;
        }
References validate_optional_arguments_.
validate_positionals()
App * App::validate_positionals (bool validate = true) inline
Set the subcommand to validate positional arguments before assigning.
Definition at line 6594 of file CLI11.hpp.
{
            validate_positionals_ = validate;
            return this;
        }
References validate_positionals_.
version()
std::string App::version () const inline
Displays a version string.
Definition at line 8404 of file CLI11.hpp.
{
        std::string val;
        if (version_ptr_ != nullptr) {
            auto rv = version_ptr_->results();
            version_ptr_->clear();
            version_ptr_->add_result("true");
            try {
                version_ptr_->run_callback();
            } catch (const CLI::CallForVersion& cfv) {
                val = cfv.what();
            }
            version_ptr_->clear();
            version_ptr_->add_result(rv);
        }
        return val;
    }
References Option::clear(), Option::run_callback(), and version_ptr_.
Member Data Documentation
aliases_
std::vector<std::string> App::aliases_ {} protected
Alias names for the subcommand.
Definition at line 6470 of file CLI11.hpp.
{};
allow_config_extras_
config_extras_mode App::allow_config_extras_ {config_extras_mode::ignore} protected
If ignore, allow extra arguments in the ini file (ie, don't throw an error). INHERITABLE if error error on an extra argument, and if capture feed it to the app
Definition at line 6300 of file CLI11.hpp.
{config_extras_mode::ignore};
Referenced by allow_config_extras(), allow_config_extras(), App(), and get_allow_config_extras().
allow_extras_
bool App::allow_extras_ {false} protected
If true, allow extra arguments (ie, don't throw an error). INHERITABLE.
Definition at line 6296 of file CLI11.hpp.
{false};
Referenced by _process_extras(), _process_extras(), allow_config_extras(), allow_extras(), App(), get_allow_extras(), and remaining().
allow_windows_style_options_
bool App::allow_windows_style_options_ protected
Initial value:
{
            false
        }
Allow '/' for options for Windows like options. Defaults to true on Windows, false otherwise. INHERITABLE.
Definition at line 6420 of file CLI11.hpp.
{
#ifdef _WIN32
            true
#else
            false
#endif
        };
Referenced by _recognize(), allow_windows_style_options(), App(), get_allow_windows_style_options(), and parse().
config_formatter_
std::shared_ptr<Config> App::config_formatter_ {new ConfigTOML()} protected
This is the formatter for help printing. Default provided. INHERITABLE (same pointer)
Definition at line 6480 of file CLI11.hpp.
{new ConfigTOML()};
config_ptr_
Option* App::config_ptr_ {nullptr} protected
Pointer to the config option.
Definition at line 6477 of file CLI11.hpp.
{nullptr};
Referenced by _move_option(), _process_config_file(), get_config_ptr(), get_config_ptr(), and set_config().
configurable_
bool App::configurable_ {false} protected
if set to true the subcommand can be triggered via configuration files INHERITABLE
Definition at line 6436 of file CLI11.hpp.
{false};
Referenced by _parse_single_config(), App(), configurable(), and get_configurable().
default_startup
startup_mode App::default_startup {startup_mode::stable} protected
specify the startup mode for the app stable=no change, enabled= startup enabled, disabled=startup disabled
Definition at line 6433 of file CLI11.hpp.
{startup_mode::stable};
Referenced by _configure(), disabled_by_default(), enabled_by_default(), get_disabled_by_default(), and get_enabled_by_default().
description_
std::string App::description_ {} protected
Description of the current program/subcommand.
Definition at line 6293 of file CLI11.hpp.
{};
Referenced by App(), description(), and get_description().
disabled_
bool App::disabled_ {false} protected
If set to true the subcommand is disabled and cannot be used, ignored for main app.
Definition at line 6312 of file CLI11.hpp.
{false};
Referenced by _compare_subcommand_names(), _configure(), disabled(), and get_disabled().
exclude_options_
std::set<Option*> App::exclude_options_ {} protected
This is a list of options which are exclusionary to this App, if the options were used this subcommand should not be
Definition at line 6393 of file CLI11.hpp.
{};
exclude_subcommands_
std::set<App*> App::exclude_subcommands_ {} protected
this is a list of subcommands that are exclusionary to this one
Definition at line 6389 of file CLI11.hpp.
{};
failure_message_
std::function<std::string(const App*, const Error& e)> App::failure_message_ {FailureMessage::simple} protected
The error message printing function INHERITABLE.
Definition at line 6369 of file CLI11.hpp.
{FailureMessage::simple};
fallthrough_
bool App::fallthrough_ {false} protected
Allow subcommand fallthrough, so that parent commands can collect commands after subcommand. INHERITABLE.
Definition at line 6417 of file CLI11.hpp.
{false};
Referenced by App(), fallthrough(), and get_fallthrough().
final_callback_
std::function<void()> App::final_callback_ {} protected
This is a function that runs when all processing has completed.
Definition at line 6328 of file CLI11.hpp.
{};
footer_
std::string App::footer_ {} protected
Footer to put after all options in the help output INHERITABLE.
Definition at line 6351 of file CLI11.hpp.
{};
Referenced by App(), and footer().
footer_callback_
std::function<std::string()> App::footer_callback_ {} protected
This is a function that generates a footer to put after all other options in help output.
Definition at line 6354 of file CLI11.hpp.
{};
formatter_
std::shared_ptr<FormatterBase> App::formatter_ {new Formatter()} protected
This is the formatter for help printing. Default provided. INHERITABLE (same pointer)
Definition at line 6366 of file CLI11.hpp.
{new Formatter()};
group_
std::string App::group_ {"Subcommands"} protected
The group membership INHERITABLE.
Definition at line 6467 of file CLI11.hpp.
{"Subcommands"};
has_automatic_name_
bool App::has_automatic_name_ {false} protected
If set to true the name was automatically generated from the command line vs a user set name.
Definition at line 6306 of file CLI11.hpp.
{false};
Referenced by name(), parse(), and parse_char_t().
help_all_ptr_
Option* App::help_all_ptr_ {nullptr} protected
A pointer to the help all flag if there is one INHERITABLE.
Definition at line 6360 of file CLI11.hpp.
{nullptr};
Referenced by _move_option(), App(), get_help_all_ptr(), remove_option(), and set_help_all_flag().
help_ptr_
Option* App::help_ptr_ {nullptr} protected
A pointer to the help flag if there is one INHERITABLE.
Definition at line 6357 of file CLI11.hpp.
{nullptr};
Referenced by _move_option(), App(), get_help_ptr(), get_help_ptr(), remove_option(), and set_help_flag().
ignore_case_
bool App::ignore_case_ {false} protected
If true, the program name is not case sensitive INHERITABLE.
Definition at line 6411 of file CLI11.hpp.
{false};
Referenced by App(), check_name(), get_ignore_case(), and ignore_case().
ignore_underscore_
bool App::ignore_underscore_ {false} protected
If true, the program should ignore underscores INHERITABLE.
Definition at line 6414 of file CLI11.hpp.
{false};
Referenced by App(), check_name(), get_ignore_underscore(), and ignore_underscore().
immediate_callback_
bool App::immediate_callback_ {false} protected
Flag indicating that the callback for the subcommand should be executed immediately on parse completion which is before help or ini files are processed. INHERITABLE
Definition at line 6319 of file CLI11.hpp.
{false};
Referenced by _trigger_pre_parse(), App(), callback(), get_immediate_callback(), and immediate_callback().
missing_
missing_t App::missing_ {} protected
Pair of classifier, string for missing options. (extra detail is removed on returning from parse)
This is faster and cleaner than storing just a list of strings and reparsing. This may contain the – separator.
Definition at line 6380 of file CLI11.hpp.
{};
name_
std::string App::name_ {} protected
Subcommand name or program name (from parser if name is empty)
Definition at line 6290 of file CLI11.hpp.
{};
Referenced by _parse_arg(), _parse_positional(), _recognize(), _trigger_pre_parse(), _validate(), add_subcommand(), App(), check_name(), get_display_name(), get_name(), name(), parse(), parse_char_t(), and run_callback().
need_options_
std::set<Option*> App::need_options_ {} protected
This is a list of options which are required by this app, the list is not mutual, listed options do not need the subcommand not be
Definition at line 6401 of file CLI11.hpp.
{};
need_subcommands_
std::set<App*> App::need_subcommands_ {} protected
this is a list of subcommands or option groups that are required by this one, the list is not mutual, the listed subcommands do not require this one
Definition at line 6397 of file CLI11.hpp.
{};
Option
friend App::Option private
Definition at line 6280 of file CLI11.hpp.
option_defaults_
OptionDefaults App::option_defaults_ {} protected
The default values for options, customizable and changeable INHERITABLE.
Definition at line 6335 of file CLI11.hpp.
{};
options_
std::vector<Option_p> App::options_ {} protected
The list of options, stored locally.
Definition at line 6338 of file CLI11.hpp.
{};
parent_
App* App::parent_ {nullptr} protected
A pointer to the parent if this is a subcommand.
Definition at line 6464 of file CLI11.hpp.
{nullptr};
Referenced by _get_fallthrough_parent(), _parse(), _parse_arg(), _parse_positional(), _parse_single(), _parse_single_config(), _recognize(), _valid_subcommand(), add_subcommand(), alias(), App(), get_parent(), get_parent(), ignore_case(), ignore_underscore(), name(), parse(), parse(), and run_callback().
parse_complete_callback_
std::function<void()> App::parse_complete_callback_ {} protected
This is a function that runs when parsing has finished.
Definition at line 6325 of file CLI11.hpp.
{};
parse_order_
std::vector<Option*> App::parse_order_ {} protected
This is a list of pointers to options with the original parse order.
Definition at line 6383 of file CLI11.hpp.
{};
parsed_
std::uint32_t App::parsed_ {0U} protected
Counts the number of times this command/subcommand was parsed.
Definition at line 6449 of file CLI11.hpp.
{0U};
Referenced by _trigger_pre_parse(), clear(), count(), count_all(), got_subcommand(), got_subcommand(), increment_parsed(), operator bool(), parse(), parse(), parse_from_stream(), and parsed().
parsed_subcommands_
std::vector<App*> App::parsed_subcommands_ {} protected
This is a list of the subcommands collected, in order.
Definition at line 6386 of file CLI11.hpp.
{};
positionals_at_end_
bool App::positionals_at_end_ {false} protected
specify that positional arguments come at the end of the argument sequence not inheritable
Definition at line 6428 of file CLI11.hpp.
{false};
Referenced by _parse_positional(), _parse_single(), get_positionals_at_end(), and positionals_at_end().
pre_parse_callback_
std::function<void(std::size_t)> App::pre_parse_callback_ {} protected
This is a function that runs prior to the start of parsing.
Definition at line 6322 of file CLI11.hpp.
{};
pre_parse_called_
bool App::pre_parse_called_ {false} protected
Flag indicating that the pre_parse_callback has been triggered.
Definition at line 6315 of file CLI11.hpp.
{false};
Referenced by _trigger_pre_parse(), and clear().
prefix_command_
bool App::prefix_command_ {false} protected
If true, return immediately on an unrecognized option (implies allow_extras) INHERITABLE.
Definition at line 6303 of file CLI11.hpp.
{false};
Referenced by _parse_positional(), _process_extras(), _process_extras(), App(), get_prefix_command(), and prefix_command().
require_option_max_
std::size_t App::require_option_max_ {0} protected
Max number of options allowed. 0 is unlimited (not inheritable)
Definition at line 6461 of file CLI11.hpp.
{0};
Referenced by _process_requirements(), _validate(), get_require_option_max(), require_option(), require_option(), and require_option().
require_option_min_
std::size_t App::require_option_min_ {0} protected
Minimum required options (not inheritable!)
Definition at line 6458 of file CLI11.hpp.
{0};
Referenced by _process_requirements(), _validate(), get_require_option_min(), require_option(), require_option(), and require_option().
require_subcommand_max_
std::size_t App::require_subcommand_max_ {0} protected
Max number of subcommands allowed (parsing stops after this number). 0 is unlimited INHERITABLE.
Definition at line 6455 of file CLI11.hpp.
{0};
Referenced by App(), get_require_subcommand_max(), require_subcommand(), require_subcommand(), and require_subcommand().
require_subcommand_min_
std::size_t App::require_subcommand_min_ {0} protected
Minimum required subcommands (not inheritable!)
Definition at line 6452 of file CLI11.hpp.
{0};
Referenced by _process_requirements(), get_require_subcommand_min(), require_subcommand(), require_subcommand(), and require_subcommand().
required_
bool App::required_ {false} protected
If set to true the subcommand is required to be processed and used, ignored for main app.
Definition at line 6309 of file CLI11.hpp.
{false};
Referenced by get_required(), and required().
silent_
bool App::silent_ {false} protected
indicator that the subcommand is silent and won't show up in subcommands list This is potentially useful as a modifier subcommand
Definition at line 6446 of file CLI11.hpp.
{false};
Referenced by get_silent(), and silent().
subcommands_
std::vector<App_p> App::subcommands_ {} protected
Storage for subcommand list.
Definition at line 6408 of file CLI11.hpp.
{};
usage_
std::string App::usage_ {} protected
Usage to put after program/subcommand description in the help output INHERITABLE.
Definition at line 6345 of file CLI11.hpp.
{};
Referenced by App(), and usage().
usage_callback_
std::function<std::string()> App::usage_callback_ {} protected
This is a function that generates a usage to put after program/subcommand description in help output.
Definition at line 6348 of file CLI11.hpp.
{};
validate_optional_arguments_
bool App::validate_optional_arguments_ {false} protected
If set to true optional vector arguments are validated before assigning INHERITABLE.
Definition at line 6442 of file CLI11.hpp.
{false};
Referenced by App(), get_validate_optional_arguments(), and validate_optional_arguments().
validate_positionals_
bool App::validate_positionals_ {false} protected
If set to true positional options are validated before assigning INHERITABLE.
Definition at line 6439 of file CLI11.hpp.
{false};
Referenced by App(), get_validate_positionals(), and validate_positionals().
version_ptr_
Option* App::version_ptr_ {nullptr} protected
A pointer to a version flag if there is one.
Definition at line 6363 of file CLI11.hpp.
{nullptr};
Referenced by get_version_ptr(), get_version_ptr(), set_version_flag(), set_version_flag(), and version().
The documentation for this class was generated from the following file:
src/utils/CLI11.hpp