SNode.C: core::TimerEventReceiver Class Reference
core::TimerEventReceiver Class Reference abstract
#include <TimerEventReceiver.h>
Public Member Functions
TimerEventReceiver (const TimerEventReceiver &)=delete
TimerEventReceiver & operator= (const TimerEventReceiver &)=delete
void restart ()
virtual void destruct ()
void span ()
void relax ()
const std::string & getName () const
Protected Member Functions
TimerEventReceiver (const std::string &name, const utils::Timeval &delay)
~TimerEventReceiver () override
utils::Timeval getTimeoutAbsolut () const
utils::Timeval getTimeoutRelative (const utils::Timeval &currentTime) const
void enable ()
void update ()
void cancel ()
Private Member Functions
void onEvent (const utils::Timeval &currentTime) final
virtual void dispatchEvent ()=0
virtual void unobservedEvent ()=0
void setTimer (Timer *timer)
void updateTimeout ()
Private Attributes
TimerEventPublisher & timerEventPublisher
Timer * timer = nullptr
utils::Timeval absoluteTimeout
utils::Timeval delay
Event event
Friends
class Timer
class TimerEventPublisher
Detailed Description
Definition at line 39 of file TimerEventReceiver.h.
Constructor & Destructor Documentation
TimerEventReceiver() [1/2]
core::TimerEventReceiver::TimerEventReceiver (const TimerEventReceiver &) delete
TimerEventReceiver() [2/2]
core::TimerEventReceiver::TimerEventReceiver (const std::string & name, const utils::Timeval & delay) protected
Definition at line 34 of file TimerEventReceiver.cpp.
        : EventReceiver(name)
        , timerEventPublisher(EventLoop::instance().getEventMultiplexer().getTimerEventPublisher())
        , absoluteTimeout(utils::Timeval::currentTime() + delay)
        , delay(delay) {
    }
References absoluteTimeout, utils::Timeval::currentTime(), delay, core::EventReceiver::EventReceiver(), core::EventLoop::getEventMultiplexer(), core::EventMultiplexer::getTimerEventPublisher(), core::EventLoop::instance(), utils::Timeval::operator+(), timerEventPublisher, and utils::Timeval::Timeval().
Referenced by core::timer::IntervalTimer::IntervalTimer(), core::timer::IntervalTimerStopable::IntervalTimerStopable(), and core::timer::SingleshotTimer::SingleshotTimer().
~TimerEventReceiver()
core::TimerEventReceiver::~TimerEventReceiver () override protected
Definition at line 47 of file TimerEventReceiver.cpp.
{
        if (timer != nullptr) {
            timer->removeTimerEventReceiver();
        }
    }
References core::Timer::removeTimerEventReceiver(), and timer.
Member Function Documentation
cancel()
void core::TimerEventReceiver::cancel () protected
Definition at line 75 of file TimerEventReceiver.cpp.
{
        timerEventPublisher.remove(this);
    }
References core::TimerEventPublisher::remove(), and timerEventPublisher.
Referenced by core::Timer::cancel(), core::timer::IntervalTimerStopable::dispatchEvent(), and core::timer::SingleshotTimer::dispatchEvent().
destruct()
void core::EventReceiver::destruct () virtual inherited
Reimplemented in core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< PhysicalServerSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, core::socket::stream::tls::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< PhysicalClientSocketT, ConfigT, core::socket::stream::legacy::SocketConnection >, core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, core::socket::stream::tls::SocketConnection >, and database::mariadb::MariaDBCommandStartEvent.
Definition at line 31 of file EventReceiver.cpp.
{
        delete this;
    }
Referenced by core::EventMultiplexer::EventQueue::clear().
dispatchEvent()
virtual void core::TimerEventReceiver::dispatchEvent () private pure virtual
Implemented in core::timer::IntervalTimer, core::timer::IntervalTimerStopable, and core::timer::SingleshotTimer.
Referenced by onEvent().
enable()
void core::TimerEventReceiver::enable () protected
Definition at line 65 of file TimerEventReceiver.cpp.
{
        timerEventPublisher.insert(this);
    }
References core::TimerEventPublisher::insert(), and timerEventPublisher.
Referenced by core::Timer::Timer().
getName()
const std::string & core::EventReceiver::getName () const inherited
Definition at line 43 of file EventReceiver.cpp.
{
        return event.getName();
    }
References core::EventReceiver::event, and core::Event::getName().
Referenced by core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::enable(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
getTimeoutAbsolut()
utils::Timeval core::TimerEventReceiver::getTimeoutAbsolut () const protected
Definition at line 53 of file TimerEventReceiver.cpp.
{
        return absoluteTimeout;
    }
References absoluteTimeout.
Referenced by onEvent(), core::TimerEventPublisher::timernode_lt::operator()(), and core::TimerEventPublisher::spanActiveEvents().
getTimeoutRelative()
utils::Timeval core::TimerEventReceiver::getTimeoutRelative (const utils::Timeval & currentTime) const protected
Definition at line 57 of file TimerEventReceiver.cpp.
{
        return absoluteTimeout > currentTime ? absoluteTimeout - currentTime : 0;
    }
References absoluteTimeout, utils::Timeval::operator-(), and utils::Timeval::operator>().
Referenced by core::TimerEventPublisher::getNextTimeout().
onEvent()
void core::TimerEventReceiver::onEvent (const utils::Timeval & currentTime) final private virtual
Implements core::EventReceiver.
Definition at line 79 of file TimerEventReceiver.cpp.
{
        LOG(TRACE) << "Timer: Dispatch delta = " << (currentTime - getTimeoutAbsolut()).getMsd() << " ms";
        dispatchEvent();
    }
References dispatchEvent(), utils::Timeval::getMsd(), getTimeoutAbsolut(), and utils::Timeval::operator-().
operator=()
TimerEventReceiver & core::TimerEventReceiver::operator= (const TimerEventReceiver &) delete
relax()
void core::EventReceiver::relax () inherited
Definition at line 39 of file EventReceiver.cpp.
{
        event.relax();
    }
References core::EventReceiver::event, and core::Event::relax().
restart()
void core::TimerEventReceiver::restart ()
Definition at line 41 of file TimerEventReceiver.cpp.
{
        timerEventPublisher.erase(this);
        absoluteTimeout = utils::Timeval::currentTime() + delay;
        timerEventPublisher.insert(this);
    }
References absoluteTimeout, utils::Timeval::currentTime(), delay, core::TimerEventPublisher::erase(), core::TimerEventPublisher::insert(), utils::Timeval::operator+(), utils::Timeval::operator=(), and timerEventPublisher.
Referenced by core::Timer::restart().
setTimer()
void core::TimerEventReceiver::setTimer (Timer * timer) private
Definition at line 85 of file TimerEventReceiver.cpp.
{
        this->timer = timer;
    }
References timer.
Referenced by core::Timer::operator=(), core::Timer::Timer(), core::Timer::Timer(), and core::Timer::~Timer().
span()
void core::EventReceiver::span () inherited
Definition at line 35 of file EventReceiver.cpp.
{
        event.span();
    }
References core::EventReceiver::event, and core::Event::span().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), core::socket::stream::SocketReader< PhysicalSocketT >::doRead(), core::socket::stream::SocketWriter< PhysicalSocketT >::doWrite(), database::mariadb::MariaDBConnection::execute_async(), core::file::FileReader::FileReader(), core::file::FileReader::onEvent(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageEnd(), core::file::FileReader::resume(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), core::epoll::DescriptorEventPublisher::spanActiveEvents(), core::poll::DescriptorEventPublisher::spanActiveEvents(), core::select::DescriptorEventPublisher::spanActiveEvents(), core::TimerEventPublisher::spanActiveEvents(), and iot::mqtt::SubProtocol< WSSubProtocolRoleT >::SubProtocol().
unobservedEvent()
virtual void core::TimerEventReceiver::unobservedEvent () private pure virtual
Implemented in core::timer::IntervalTimer, core::timer::IntervalTimerStopable, and core::timer::SingleshotTimer.
Referenced by core::TimerEventPublisher::unobserveDisableEvents().
update()
void core::TimerEventReceiver::update () protected
Definition at line 69 of file TimerEventReceiver.cpp.
{
        timerEventPublisher.erase(this);
        absoluteTimeout += delay;
        timerEventPublisher.insert(this);
    }
References absoluteTimeout, delay, core::TimerEventPublisher::erase(), core::TimerEventPublisher::insert(), utils::Timeval::operator+=(), and timerEventPublisher.
Referenced by core::timer::IntervalTimer::dispatchEvent(), core::timer::IntervalTimerStopable::dispatchEvent(), and updateTimeout().
updateTimeout()
void core::TimerEventReceiver::updateTimeout () private
Definition at line 61 of file TimerEventReceiver.cpp.
{
        update();
    }
References update().
Friends And Related Symbol Documentation
Timer
friend class Timer friend
Definition at line 74 of file TimerEventReceiver.h.
TimerEventPublisher
friend class TimerEventPublisher friend
Definition at line 75 of file TimerEventReceiver.h.
Member Data Documentation
absoluteTimeout
utils::Timeval core::TimerEventReceiver::absoluteTimeout private
Definition at line 71 of file TimerEventReceiver.h.
Referenced by getTimeoutAbsolut(), getTimeoutRelative(), restart(), TimerEventReceiver(), and update().
delay
utils::Timeval core::TimerEventReceiver::delay private
Definition at line 72 of file TimerEventReceiver.h.
Referenced by restart(), TimerEventReceiver(), and update().
event
Event core::EventReceiver::event private inherited
Definition at line 54 of file EventReceiver.h.
Referenced by core::EventReceiver::EventReceiver(), core::EventReceiver::getName(), core::EventReceiver::relax(), and core::EventReceiver::span().
timer
Timer* core::TimerEventReceiver::timer = nullptr private
Definition at line 70 of file TimerEventReceiver.h.
Referenced by setTimer(), and ~TimerEventReceiver().
timerEventPublisher
TimerEventPublisher& core::TimerEventReceiver::timerEventPublisher private
Definition at line 68 of file TimerEventReceiver.h.
Referenced by cancel(), enable(), restart(), TimerEventReceiver(), and update().
The documentation for this class was generated from the following files:
core/TimerEventReceiver.h
core/TimerEventReceiver.cpp