SNode.C: web::http::SocketContextUpgrade< RequestT, ResponseT > Class Template Reference
web::http::SocketContextUpgrade< RequestT, ResponseT > Class Template Reference abstract
#include <SocketContextUpgrade.h>
Public Member Functions
void sendToPeer (const char *chunk, std::size_t chunkLen) const final
void sendToPeer (const std::string &data) const
virtual void sendToPeer (const char *chunk, std::size_t chunkLen) const=0
bool streamToPeer (core::pipe::Source *source) const
void streamEof ()
std::size_t readFromPeer (char *chunk, std::size_t chunklen) const final
void setTimeout (const utils::Timeval &timeout) final
void shutdownRead ()
void shutdownWrite (bool forceClose=false)
void close () override
SocketConnection * getSocketConnection () const
virtual void switchSocketContext (SocketContext *newSocketContext)
Protected Types
using Request = RequestT
using Response = ResponseT
using SocketContextUpgradeFactory = web::http::SocketContextUpgradeFactory< Request, Response >
Protected Member Functions
SocketContextUpgrade (core::socket::stream::SocketConnection *socketConnection, SocketContextUpgradeFactory *socketContextUpgradeFactory)
~SocketContextUpgrade () override
void onWriteError (int errnum) override
void onReadError (int errnum) override
virtual std::size_t onReceivedFromPeer ()=0
virtual bool onSignal (int sig)=0
Private Types
using Super = core::socket::SocketContext
Private Member Functions
virtual void onConnected ()=0
virtual void onDisconnected ()=0
Private Attributes
SocketContextUpgradeFactory * socketContextUpgradeFactory = nullptr
core::socket::stream::SocketConnection * socketConnection
Detailed Description
template<typename RequestT, typename ResponseT>
class web::http::SocketContextUpgrade< RequestT, ResponseT >
Definition at line 37 of file SocketContextUpgrade.h.
Member Typedef Documentation
Request
template<typename RequestT , typename ResponseT > using web::http::SocketContextUpgrade< RequestT, ResponseT >::Request = RequestT protected
Definition at line 39 of file SocketContextUpgrade.h.
Response
template<typename RequestT , typename ResponseT > using web::http::SocketContextUpgrade< RequestT, ResponseT >::Response = ResponseT protected
Definition at line 40 of file SocketContextUpgrade.h.
SocketContextUpgradeFactory
template<typename RequestT , typename ResponseT > using web::http::SocketContextUpgrade< RequestT, ResponseT >::SocketContextUpgradeFactory = web::http::SocketContextUpgradeFactory<Request, Response> protected
Definition at line 42 of file SocketContextUpgrade.h.
Super
using core::socket::stream::SocketContext::Super = core::socket::SocketContext private inherited
Definition at line 48 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContextUpgrade()
template<typename RequestT , typename ResponseT > web::http::SocketContextUpgrade< RequestT, ResponseT >::SocketContextUpgrade (core::socket::stream::SocketConnection * socketConnection, SocketContextUpgradeFactory * socketContextUpgradeFactory) inline protected
Definition at line 44 of file SocketContextUpgrade.h.
            : core::socket::stream::SocketContext(socketConnection)
            , socketContextUpgradeFactory(socketContextUpgradeFactory) {
            socketContextUpgradeFactory->incRefCount();
        }
References web::http::SocketContextUpgrade< RequestT, ResponseT >::socketContextUpgradeFactory.
~SocketContextUpgrade()
template<typename RequestT , typename ResponseT > web::http::SocketContextUpgrade< RequestT, ResponseT >::~SocketContextUpgrade () inline override protected
Definition at line 51 of file SocketContextUpgrade.h.
{
            socketContextUpgradeFactory->decRefCount();
        }
References web::http::SocketContextUpgrade< RequestT, ResponseT >::socketContextUpgradeFactory.
Member Function Documentation
close()
void core::socket::stream::SocketContext::close () override virtual inherited
Implements core::socket::SocketContext.
Reimplemented in iot::mqtt::SocketContext.
Definition at line 62 of file SocketContext.cpp.
{
        socketConnection->close();
    }
References core::socket::stream::SocketConnection::close(), and core::socket::stream::SocketContext::socketConnection.
Referenced by iot::mqtt::SocketContext::close(), web::http::client::Request::executeUpgrade(), iot::mqtt_fast::SocketContext::onReceivedFromPeer(), web::http::client::Request::onSourceError(), and web::http::server::Response::onSourceError().
getSocketConnection()
SocketConnection * core::socket::stream::SocketContext::getSocketConnection () const inherited
Definition at line 38 of file SocketContext.cpp.
{
        return socketConnection;
    }
References core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::SocketContext::deliverResponse(), web::http::client::SocketContext::dispatchNextRequest(), iot::mqtt::SocketContext::getSocketConnection(), web::http::client::SocketContext::onConnected(), web::http::server::SocketContext::onConnected(), web::http::client::SocketContext::onDisconnected(), web::http::server::SocketContext::onDisconnected(), web::http::client::SocketContext::onSignal(), web::http::server::SocketContext::onSignal(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestCompleted(), web::http::server::SocketContext::requestParsed(), web::http::server::SocketContext::requestParseError(), web::http::client::SocketContext::requestPrepared(), web::http::client::SocketContext::requestSent(), web::http::server::SocketContext::requestStarted(), web::http::server::SocketContext::responseCompleted(), web::http::client::SocketContext::responseError(), web::http::client::SocketContext::responseStarted(), web::http::server::SocketContext::responseStarted(), web::http::client::SocketContext::SocketContext(), and express::middleware::VerboseRequest::VerboseRequest().
onConnected()
virtual void core::socket::stream::SocketContext::onConnected () private pure virtual inherited
Implemented in iot::mqtt::SocketContext, web::http::client::SocketContext, web::http::server::SocketContext, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by core::socket::stream::SocketConnection::setSocketContext().
onDisconnected()
virtual void core::socket::stream::SocketContext::onDisconnected () private pure virtual inherited
Implemented in iot::mqtt::SocketContext, web::http::client::SocketContext, web::http::server::SocketContext, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by core::socket::stream::SocketConnection::disconnectCurrentSocketContext().
onReadError()
void core::socket::stream::SocketContext::onReadError (int errnum) override protected virtual inherited
Implements core::socket::SocketContext.
Definition at line 78 of file SocketContext.cpp.
{
        shutdownWrite();
    }
References core::socket::stream::SocketContext::shutdownWrite().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReadError().
onReceivedFromPeer()
virtual std::size_t core::socket::SocketContext::onReceivedFromPeer () protected pure virtual inherited
Implemented in iot::mqtt_fast::SocketContext, iot::mqtt::SocketContext, web::http::client::SocketContext, web::http::server::SocketContext, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onReceivedFromPeer().
onSignal()
virtual bool core::socket::SocketContext::onSignal (int sig) protected pure virtual inherited
Implemented in iot::mqtt::SocketContext, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >, web::http::client::SocketContext, and web::http::server::SocketContext.
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onSignal().
onWriteError()
void core::socket::stream::SocketContext::onWriteError (int errnum) override protected virtual inherited
Implements core::socket::SocketContext.
Definition at line 74 of file SocketContext.cpp.
{
        shutdownRead();
    }
References core::socket::stream::SocketContext::shutdownRead().
Referenced by core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT >::onWriteError().
readFromPeer()
std::size_t core::socket::stream::SocketContext::readFromPeer (char * chunk, std::size_t chunklen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 54 of file SocketContext.cpp.
{
        return socketConnection->readFromPeer(chunk, chunklen);
    }
References core::socket::stream::SocketConnection::readFromPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::decoder::HTTP10Response::read(), web::http::decoder::Identity::read(), web::http::decoder::Chunked::Chunk::read(), web::http::Parser::readHeaderLine(), web::http::Parser::readStartLine(), and iot::mqtt::SocketContext::recv().
sendToPeer() [1/3]
void core::socket::stream::SocketContext::sendToPeer (const char * chunk, std::size_t chunkLen) const final virtual inherited
Implements core::socket::SocketContext.
Definition at line 42 of file SocketContext.cpp.
{
        socketConnection->sendToPeer(chunk, chunkLen);
    }
References core::socket::stream::SocketConnection::sendToPeer(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::Request::executeSendFragment(), iot::mqtt::SocketContext::send(), iot::mqtt_fast::SocketContext::send(), and web::http::server::Response::sendFragment().
sendToPeer() [2/3]
virtual void core::socket::SocketContext::sendToPeer (const char * chunk, std::size_t chunkLen) const virtual inherited
Implements core::socket::SocketContext.
sendToPeer() [3/3]
void core::socket::SocketContext::sendToPeer (const std::string & data) const inherited
Definition at line 53 of file SocketContext.cpp.
{
        sendToPeer(data.data(), data.length());
    }
setTimeout()
void core::socket::stream::SocketContext::setTimeout (const utils::Timeval & timeout) final virtual inherited
Implements core::socket::SocketContext.
Definition at line 58 of file SocketContext.cpp.
{
        socketConnection->setTimeout(timeout);
    }
References core::socket::stream::SocketConnection::setTimeout(), and core::socket::stream::SocketContext::socketConnection.
shutdownRead()
void core::socket::stream::SocketContext::shutdownRead () inherited
Definition at line 66 of file SocketContext.cpp.
{
        socketConnection->shutdownRead();
    }
References core::socket::stream::SocketConnection::shutdownRead(), and core::socket::stream::SocketContext::socketConnection.
Referenced by core::socket::stream::SocketContext::onWriteError().
shutdownWrite()
void core::socket::stream::SocketContext::shutdownWrite (bool forceClose = false) inherited
Definition at line 70 of file SocketContext.cpp.
{
        socketConnection->shutdownWrite(forceClose);
    }
References core::socket::stream::SocketConnection::shutdownWrite(), and core::socket::stream::SocketContext::socketConnection.
Referenced by web::http::client::SocketContext::dispatchNextRequest(), iot::mqtt::SocketContext::end(), core::socket::stream::SocketContext::onReadError(), web::http::server::SocketContext::requestCompleted(), web::http::client::SocketContext::requestCompleted(), web::http::server::SocketContext::requestParseError(), web::http::client::SocketContext::requestSent(), web::http::server::SocketContext::responseCompleted(), web::http::client::SocketContext::responseError(), and web::http::client::SocketContext::responseStarted().
streamEof()
void core::socket::stream::SocketContext::streamEof () inherited
Definition at line 50 of file SocketContext.cpp.
{
        socketConnection->streamEof();
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::streamEof().
Referenced by web::http::client::Request::onSourceEof(), web::http::server::Response::onSourceEof(), web::http::client::Request::onSourceError(), web::http::server::Response::onSourceError(), web::http::client::Request::~Request(), and web::http::server::Response::~Response().
streamToPeer()
bool core::socket::stream::SocketContext::streamToPeer (core::pipe::Source * source) const inherited
Definition at line 46 of file SocketContext.cpp.
{
        return socketConnection->streamToPeer(source);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::streamToPeer().
Referenced by web::http::client::Request::onSourceConnect(), and web::http::server::Response::onSourceConnect().
switchSocketContext()
void core::socket::stream::SocketContext::switchSocketContext (SocketContext * newSocketContext) virtual inherited
Definition at line 34 of file SocketContext.cpp.
{
        socketConnection->switchSocketContext(newSocketContext);
    }
References core::socket::stream::SocketContext::socketConnection, and core::socket::stream::SocketConnection::switchSocketContext().
Referenced by web::http::server::Response::sendCompleted().
Member Data Documentation
socketConnection
core::socket::stream::SocketConnection* core::socket::stream::SocketContext::socketConnection private inherited
Definition at line 78 of file SocketContext.h.
Referenced by core::socket::stream::SocketContext::close(), core::socket::stream::SocketContext::getSocketConnection(), core::socket::stream::SocketContext::readFromPeer(), core::socket::stream::SocketContext::sendToPeer(), core::socket::stream::SocketContext::setTimeout(), core::socket::stream::SocketContext::shutdownRead(), core::socket::stream::SocketContext::shutdownWrite(), core::socket::stream::SocketContext::SocketContext(), core::socket::stream::SocketContext::streamEof(), core::socket::stream::SocketContext::streamToPeer(), and core::socket::stream::SocketContext::switchSocketContext().
socketContextUpgradeFactory
template<typename RequestT , typename ResponseT > SocketContextUpgradeFactory* web::http::SocketContextUpgrade< RequestT, ResponseT >::socketContextUpgradeFactory = nullptr private
Definition at line 56 of file SocketContextUpgrade.h.
Referenced by web::http::SocketContextUpgrade< RequestT, ResponseT >::SocketContextUpgrade(), and web::http::SocketContextUpgrade< RequestT, ResponseT >::~SocketContextUpgrade().
The documentation for this class was generated from the following file:
web/http/SocketContextUpgrade.h