SNode.C: core::timer::Timer Class Reference
core::timer::Timer Class Reference
#include <Timer.h>
Public Member Functions
~Timer () override
Timer & operator= (const Timer &)=delete
Timer & operator= (Timer &&timer) noexcept=default
void cancel ()
void restart ()
Static Public Member Functions
static Timer intervalTimer (const std::function< void(const std::function< void()> &stop)> &dispatcher, const utils::Timeval &timeout)
static Timer intervalTimer (const std::function< void()> &dispatcher, const utils::Timeval &timeout)
static Timer singleshotTimer (const std::function< void()> &dispatcher, const utils::Timeval &timeout)
Private Member Functions
void removeTimerEventReceiver ()
Private Attributes
TimerEventReceiver * timerEventReceiver = nullptr
friend TimerEventReceiver
Detailed Description
Definition at line 39 of file Timer.h.
Constructor & Destructor Documentation
~Timer()
core::timer::Timer::~Timer () override virtual
Reimplemented from core::Timer.
Definition at line 32 of file Timer.cpp.
                  {
    }
Member Function Documentation
cancel()
void core::Timer::cancel () inherited
Definition at line 62 of file Timer.cpp.
                       {
        if (timerEventReceiver != nullptr) {
            timerEventReceiver->cancel();
        }
    }
References core::TimerEventReceiver::cancel(), and core::Timer::timerEventReceiver.
Referenced by iot::mqtt::Mqtt::~Mqtt(), and iot::mqtt::client::Mqtt::~Mqtt().
intervalTimer() [1/2]
Timer core::timer::Timer::intervalTimer (const std::function< void()> & dispatcher, const utils::Timeval & timeout) static
Definition at line 43 of file Timer.cpp.
{
        return Timer(new IntervalTimer(dispatcher, timeout));
    }
References core::timer::IntervalTimer::IntervalTimer().
Referenced by iot::mqtt::client::Mqtt::_onConnack().
intervalTimer() [2/2]
Timer core::timer::Timer::intervalTimer (const std::function< void(const std::function< void()> &stop)> & dispatcher, const utils::Timeval & timeout) static
Definition at line 39 of file Timer.cpp.
{
        return Timer(new IntervalTimerStopable(dispatcher, timeout));
    }
References core::timer::IntervalTimerStopable::IntervalTimerStopable().
operator=() [1/2]
Timer & core::timer::Timer::operator= (const Timer &) delete
operator=() [2/2]
Timer & core::timer::Timer::operator= (Timer && timer) default noexcept
Referenced by iot::mqtt::client::Mqtt::_onConnack(), and iot::mqtt::Mqtt::initSession().
removeTimerEventReceiver()
void core::Timer::removeTimerEventReceiver () private inherited
Definition at line 74 of file Timer.cpp.
{
        timerEventReceiver = nullptr;
    }
References core::Timer::timerEventReceiver.
Referenced by core::TimerEventReceiver::~TimerEventReceiver().
restart()
void core::Timer::restart () inherited
Definition at line 68 of file Timer.cpp.
{
        if (timerEventReceiver != nullptr) {
            timerEventReceiver->restart();
        }
    }
References core::TimerEventReceiver::restart(), and core::Timer::timerEventReceiver.
singleshotTimer()
Timer core::timer::Timer::singleshotTimer (const std::function< void()> & dispatcher, const utils::Timeval & timeout) static
Definition at line 35 of file Timer.cpp.
{
        return Timer(new SingleshotTimer(dispatcher, timeout));
    }
References core::timer::SingleshotTimer::SingleshotTimer().
Referenced by iot::mqtt::Mqtt::initSession().
Member Data Documentation
timerEventReceiver
TimerEventReceiver* core::Timer::timerEventReceiver = nullptr private inherited
Definition at line 51 of file Timer.h.
Referenced by core::Timer::cancel(), core::Timer::operator=(), core::Timer::removeTimerEventReceiver(), core::Timer::restart(), core::Timer::Timer(), core::Timer::Timer(), and core::Timer::~Timer().
TimerEventReceiver
friend core::Timer::TimerEventReceiver private inherited
Definition at line 53 of file Timer.h.
The documentation for this class was generated from the following files:
core/timer/Timer.h
core/timer/Timer.cpp