snode.c: core::EventMultiplexer Class Reference
core::EventMultiplexer Class Reference abstract
#include <EventMultiplexer.h>
Classes
class EventQueue
Public Types
enum DISP_TYPE { RD = 0 , WR = 1 , EX = 2 }
Public Member Functions
EventMultiplexer (const EventMultiplexer &)=delete
EventMultiplexer & operator= (const EventMultiplexer &)=delete
DescriptorEventPublisher & getDescriptorEventPublisher (DISP_TYPE dispType)
TimerEventPublisher & getTimerEventPublisher ()
void span (core::Event *event)
void relax (core::Event *event)
void sigExit (int sigNum)
void stop ()
void clear ()
TickStatus tick (const utils::Timeval &tickTimeOut, const sigset_t &sigMask)
Protected Member Functions
EventMultiplexer (DescriptorEventPublisher *const readDescriptorEventPublisher, DescriptorEventPublisher *const writeDescriptorEventPublisher, DescriptorEventPublisher *const exceptionDescriptorEventPublisher)
virtual ~EventMultiplexer ()
int maxFd ()
Protected Attributes
std::array< DescriptorEventPublisher *, 3 > descriptorEventPublishers
Private Member Functions
TickStatus waitForEvents (const utils::Timeval &tickTimeOut, const utils::Timeval &currentTime, const sigset_t &sigMask, int &activeDescriptorCount)
void spanActiveEvents (const utils::Timeval &currentTime, int activeDescriptorCount)
void executeEventQueue (const utils::Timeval &currentTime)
void checkTimedOutEvents (const utils::Timeval &currentTime)
void releaseExpiredResources (const utils::Timeval &currentTime)
utils::Timeval getNextTimeout (const utils::Timeval &currentTime)
virtual void spanActiveEvents (int activeDescriptorCount)=0
virtual int monitorDescriptors (utils::Timeval &tickTimeOut, const sigset_t &sigMask)=0
int observedEventReceiverCount ()
Private Attributes
core::TimerEventPublisher *const timerEventPublisher
EventQueue eventQueue
Friends
class DescriptorEventPublisher
Detailed Description
Definition at line 46 of file EventMultiplexer.h.
Member Enumeration Documentation
DISP_TYPE
enum core::EventMultiplexer::DISP_TYPE
Enumerator
RD
WR
EX
Definition at line 84 of file EventMultiplexer.h.
{ RD = 0, WR = 1, EX = 2 };
Constructor & Destructor Documentation
EventMultiplexer() [1/2]
core::EventMultiplexer::EventMultiplexer (const EventMultiplexer &) delete
EventMultiplexer() [2/2]
core::EventMultiplexer::EventMultiplexer (DescriptorEventPublisher *const readDescriptorEventPublisher, DescriptorEventPublisher *const writeDescriptorEventPublisher, DescriptorEventPublisher *const exceptionDescriptorEventPublisher) protected
Definition at line 39 of file EventMultiplexer.cpp.
        : descriptorEventPublishers{readDescriptorEventPublisher, writeDescriptorEventPublisher, exceptionDescriptorEventPublisher}
        , timerEventPublisher(new core::TimerEventPublisher()) {
    }
~EventMultiplexer()
core::EventMultiplexer::~EventMultiplexer () protected virtual
Reimplemented in core::epoll::EventMultiplexer, core::poll::EventMultiplexer, and core::select::EventMultiplexer.
Definition at line 46 of file EventMultiplexer.cpp.
{
        for (DescriptorEventPublisher* descriptorEventPublisher : descriptorEventPublishers) {
            delete descriptorEventPublisher;
        }
        delete timerEventPublisher;
    }
References descriptorEventPublishers, and timerEventPublisher.
Member Function Documentation
checkTimedOutEvents()
void core::EventMultiplexer::checkTimedOutEvents (const utils::Timeval & currentTime) private
Definition at line 135 of file EventMultiplexer.cpp.
{
        for (DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
            descriptorEventPublisher->checkTimedOutEvents(currentTime);
        }
    }
References descriptorEventPublishers.
Referenced by tick().
clear()
void core::EventMultiplexer::clear ()
Definition at line 99 of file EventMultiplexer.cpp.
{
        eventQueue.clear();
    }
References core::EventMultiplexer::EventQueue::clear(), and eventQueue.
Referenced by core::EventLoop::start(), and core::EventLoop::tick().
executeEventQueue()
void core::EventMultiplexer::executeEventQueue (const utils::Timeval & currentTime) private
Definition at line 131 of file EventMultiplexer.cpp.
{
        eventQueue.execute(currentTime);
    }
References eventQueue, and core::EventMultiplexer::EventQueue::execute().
Referenced by tick().
getDescriptorEventPublisher()
DescriptorEventPublisher & core::EventMultiplexer::getDescriptorEventPublisher (DISP_TYPE dispType)
Definition at line 53 of file EventMultiplexer.cpp.
{
        return *descriptorEventPublishers[dispType];
    }
References descriptorEventPublishers.
getNextTimeout()
utils::Timeval core::EventMultiplexer::getNextTimeout (const utils::Timeval & currentTime) private
Definition at line 149 of file EventMultiplexer.cpp.
{
        utils::Timeval nextTimeout = DescriptorEventReceiver::TIMEOUT::MAX;
        if (eventQueue.empty()) {
            for (DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
                nextTimeout = std::min(descriptorEventPublisher->getNextTimeout(currentTime), nextTimeout);
            }
            nextTimeout = std::min(timerEventPublisher->getNextTimeout(currentTime), nextTimeout);
            nextTimeout = std::max(nextTimeout, utils::Timeval()); // In case nextTimeout is negative
        } else {
            nextTimeout = 0;
        }
        return nextTimeout;
    }
References descriptorEventPublishers, core::EventMultiplexer::EventQueue::empty(), eventQueue, core::TimerEventPublisher::getNextTimeout(), core::DescriptorEventReceiver::TIMEOUT::MAX, and timerEventPublisher.
Referenced by waitForEvents().
getTimerEventPublisher()
core::TimerEventPublisher & core::EventMultiplexer::getTimerEventPublisher ()
Definition at line 57 of file EventMultiplexer.cpp.
{
        return *timerEventPublisher;
    }
References timerEventPublisher.
maxFd()
int core::EventMultiplexer::maxFd () protected
Definition at line 174 of file EventMultiplexer.cpp.
{
        return std::accumulate(descriptorEventPublishers.begin(),
                               descriptorEventPublishers.end(),
                               -1,
                               [](int count, DescriptorEventPublisher* descriptorEventPublisher) -> int {
                                   return std::max(descriptorEventPublisher->maxFd(), count);
                               });
    }
References descriptorEventPublishers.
Referenced by core::select::EventMultiplexer::monitorDescriptors().
monitorDescriptors()
virtual int core::EventMultiplexer::monitorDescriptors (utils::Timeval & tickTimeOut, const sigset_t & sigMask) private pure virtual
Implemented in core::epoll::EventMultiplexer, core::poll::EventMultiplexer, and core::select::EventMultiplexer.
Referenced by waitForEvents().
observedEventReceiverCount()
int core::EventMultiplexer::observedEventReceiverCount () private
Definition at line 165 of file EventMultiplexer.cpp.
{
        return std::accumulate(descriptorEventPublishers.begin(),
                               descriptorEventPublishers.end(),
                               0,
                               [](int count, DescriptorEventPublisher* descriptorEventPublisher) -> int {
                                   return count + descriptorEventPublisher->getObservedEventReceiverCount();
                               });
    }
References descriptorEventPublishers.
Referenced by waitForEvents().
operator=()
EventMultiplexer & core::EventMultiplexer::operator= (const EventMultiplexer &) delete
relax()
void core::EventMultiplexer::relax (core::Event * event)
Definition at line 65 of file EventMultiplexer.cpp.
{
        eventQueue.remove(event);
    }
References eventQueue, and core::EventMultiplexer::EventQueue::remove().
Referenced by core::Event::relax().
releaseExpiredResources()
void core::EventMultiplexer::releaseExpiredResources (const utils::Timeval & currentTime) private
Definition at line 141 of file EventMultiplexer.cpp.
{
        for (DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
            descriptorEventPublisher->releaseDisabledEvents(currentTime);
        }
        timerEventPublisher->unobserveDisableEvents();
        DynamicLoader::execDlCloseDeleyed();
    }
References descriptorEventPublishers, core::DynamicLoader::execDlCloseDeleyed(), timerEventPublisher, and core::TimerEventPublisher::unobserveDisableEvents().
Referenced by tick().
sigExit()
void core::EventMultiplexer::sigExit (int sigNum)
Definition at line 86 of file EventMultiplexer.cpp.
{
        for (DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
            descriptorEventPublisher->sigExit(stopsig);
        }
    }
References descriptorEventPublishers.
Referenced by core::EventLoop::free().
span()
void core::EventMultiplexer::span (core::Event * event)
Definition at line 61 of file EventMultiplexer.cpp.
{
        eventQueue.insert(event);
    }
References eventQueue, and core::EventMultiplexer::EventQueue::insert().
Referenced by core::Event::span().
spanActiveEvents() [1/2]
void core::EventMultiplexer::spanActiveEvents (const utils::Timeval & currentTime, int activeDescriptorCount) private
Definition at line 126 of file EventMultiplexer.cpp.
{
        timerEventPublisher->spanActiveEvents(currentTime);
        spanActiveEvents(activeDescriptorCount);
    }
References core::TimerEventPublisher::spanActiveEvents(), spanActiveEvents(), and timerEventPublisher.
Referenced by spanActiveEvents(), and tick().
spanActiveEvents() [2/2]
virtual void core::EventMultiplexer::spanActiveEvents (int activeDescriptorCount) private pure virtual
Implemented in core::epoll::EventMultiplexer, core::poll::EventMultiplexer, and core::select::EventMultiplexer.
stop()
void core::EventMultiplexer::stop ()
Definition at line 92 of file EventMultiplexer.cpp.
{
        for (DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
            descriptorEventPublisher->stop();
        }
        timerEventPublisher->stop();
    }
References descriptorEventPublishers, core::TimerEventPublisher::stop(), and timerEventPublisher.
Referenced by core::EventLoop::free().
tick()
TickStatus core::EventMultiplexer::tick (const utils::Timeval & tickTimeOut, const sigset_t & sigMask)
Definition at line 69 of file EventMultiplexer.cpp.
{
        utils::Timeval currentTime = utils::Timeval::currentTime();
        int activeDescriptorCount = 0;
        TickStatus tickStatus = waitForEvents(tickTimeOut, currentTime, sigMask, activeDescriptorCount);
        if (tickStatus == TickStatus::SUCCESS) {
            spanActiveEvents(currentTime, activeDescriptorCount);
            executeEventQueue(currentTime);
            checkTimedOutEvents(currentTime);
            releaseExpiredResources(currentTime);
        }
        return tickStatus;
    }
References checkTimedOutEvents(), utils::Timeval::currentTime(), executeEventQueue(), releaseExpiredResources(), spanActiveEvents(), core::SUCCESS, and waitForEvents().
Referenced by core::EventLoop::_tick().
waitForEvents()
TickStatus core::EventMultiplexer::waitForEvents (const utils::Timeval & tickTimeOut, const utils::Timeval & currentTime, const sigset_t & sigMask, int & activeDescriptorCount) private
Definition at line 103 of file EventMultiplexer.cpp.
{
        TickStatus tickStatus = TickStatus::SUCCESS;
        if (observedEventReceiverCount() > 0 || !timerEventPublisher->empty() || !eventQueue.empty()) {
            utils::Timeval nextTimeout = std::min(getNextTimeout(currentTime), tickTimeOut);
            activeDescriptorCount = monitorDescriptors(nextTimeout, sigMask);
            if (activeDescriptorCount < 0 && errno != EINTR) {
                tickStatus = TickStatus::ERROR;
            } else if (errno == EINTR) {
                tickStatus = TickStatus::INTERRUPTED;
            }
        } else {
            tickStatus = TickStatus::NOOBSERVER;
        }
        return tickStatus;
    }
References core::TimerEventPublisher::empty(), core::EventMultiplexer::EventQueue::empty(), core::ERROR, eventQueue, getNextTimeout(), core::INTERRUPTED, monitorDescriptors(), core::NOOBSERVER, observedEventReceiverCount(), core::SUCCESS, and timerEventPublisher.
Referenced by tick().
Friends And Related Symbol Documentation
DescriptorEventPublisher
friend class DescriptorEventPublisher friend
Definition at line 127 of file EventMultiplexer.h.
Member Data Documentation
descriptorEventPublishers
std::array<DescriptorEventPublisher*, 3 > core::EventMultiplexer::descriptorEventPublishers protected
Definition at line 118 of file EventMultiplexer.h.
Referenced by checkTimedOutEvents(), core::epoll::EventMultiplexer::EventMultiplexer(), getDescriptorEventPublisher(), getNextTimeout(), maxFd(), observedEventReceiverCount(), releaseExpiredResources(), sigExit(), core::poll::EventMultiplexer::spanActiveEvents(), core::select::EventMultiplexer::spanActiveEvents(), stop(), and ~EventMultiplexer().
eventQueue
EventQueue core::EventMultiplexer::eventQueue private
Definition at line 125 of file EventMultiplexer.h.
Referenced by clear(), executeEventQueue(), getNextTimeout(), relax(), span(), and waitForEvents().
timerEventPublisher
core::TimerEventPublisher* const core::EventMultiplexer::timerEventPublisher private
Definition at line 123 of file EventMultiplexer.h.
Referenced by getNextTimeout(), getTimerEventPublisher(), releaseExpiredResources(), spanActiveEvents(), stop(), waitForEvents(), and ~EventMultiplexer().
The documentation for this class was generated from the following files:
core/EventMultiplexer.h
core/EventMultiplexer.cpp