SNode.C: ArgumentMismatch Class Reference
ArgumentMismatch Class Reference
Errors
Thrown when the wrong number of arguments has been received.
#include <CLI11.hpp>
Public Member Functions
ArgumentMismatch (std::string msg, ExitCodes exit_code)
ArgumentMismatch (std::string msg, int exit_code)
ArgumentMismatch (std::string msg)
ArgumentMismatch (std::string name, int expected, std::size_t received)
Public Member Functions inherited from ParseError
ParseError (std::string msg, ExitCodes exit_code)
ParseError (std::string msg, int exit_code)
Public Member Functions inherited from Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Static Public Member Functions
static ArgumentMismatch AtLeast (std::string name, int num, std::size_t received)
static ArgumentMismatch AtMost (std::string name, int num, std::size_t received)
static ArgumentMismatch TypedAtLeast (std::string name, int num, std::string type)
static ArgumentMismatch FlagOverride (std::string name)
static ArgumentMismatch PartialType (std::string name, int num, std::string type)
Protected Member Functions
ArgumentMismatch (std::string ename, std::string msg, int exit_code)
ArgumentMismatch (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from ParseError
ParseError (std::string ename, std::string msg, int exit_code)
ParseError (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
Thrown when the wrong number of arguments has been received.
Definition at line 1265 of file CLI11.hpp.
Constructor & Destructor Documentation
ArgumentMismatch() [1/6]
ArgumentMismatch::ArgumentMismatch (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 1266 of file CLI11.hpp.
ArgumentMismatch() [2/6]
ArgumentMismatch::ArgumentMismatch (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 1266 of file CLI11.hpp.
ArgumentMismatch() [3/6]
ArgumentMismatch::ArgumentMismatch (std::string msg, ExitCodes exit_code) inline
Definition at line 1266 of file CLI11.hpp.
ArgumentMismatch() [4/6]
ArgumentMismatch::ArgumentMismatch (std::string msg, int exit_code) inline
Definition at line 1266 of file CLI11.hpp.
ArgumentMismatch() [5/6]
ArgumentMismatch::ArgumentMismatch (std::string msg) inline explicit
Definition at line 1267 of file CLI11.hpp.
ArgumentMismatch() [6/6]
ArgumentMismatch::ArgumentMismatch (std::string name, int expected, std::size_t received) inline
Definition at line 1268 of file CLI11.hpp.
            : ArgumentMismatch(
                  expected > 0
                      ? ("Expected exactly " + std::to_string(expected) + " arguments to " + name + ", got " + std::to_string(received))
                      : ("Expected at least " + std::to_string(-expected) + " arguments to " + name + ", got " + std::to_string(received)),
                  ExitCodes::ArgumentMismatch) {
        }
References ArgumentMismatch().
Referenced by ArgumentMismatch().
Member Function Documentation
AtLeast()
static ArgumentMismatch ArgumentMismatch::AtLeast (std::string name, int num, std::size_t received) inline static
Definition at line 1276 of file CLI11.hpp.
{
            return ArgumentMismatch(name + ": At least " + std::to_string(num) + " required but received " + std::to_string(received));
        }
AtMost()
static ArgumentMismatch ArgumentMismatch::AtMost (std::string name, int num, std::size_t received) inline static
Definition at line 1279 of file CLI11.hpp.
{
            return ArgumentMismatch(name + ": At Most " + std::to_string(num) + " required but received " + std::to_string(received));
        }
Referenced by App::_parse_single_config().
FlagOverride()
static ArgumentMismatch ArgumentMismatch::FlagOverride (std::string name) inline static
Definition at line 1285 of file CLI11.hpp.
{
            return ArgumentMismatch(name + " was given a disallowed flag override");
        }
Referenced by Option::get_flag_value().
PartialType()
static ArgumentMismatch ArgumentMismatch::PartialType (std::string name, int num, std::string type) inline static
Definition at line 1288 of file CLI11.hpp.
{
            return ArgumentMismatch(name + ": " + type + " only partially specified: " + std::to_string(num) +
                                    " required for each element");
        }
TypedAtLeast()
static ArgumentMismatch ArgumentMismatch::TypedAtLeast (std::string name, int num, std::string type) inline static
Definition at line 1282 of file CLI11.hpp.
{
            return ArgumentMismatch(name + ": " + std::to_string(num) + " required " + type + " missing");
        }
The documentation for this class was generated from the following file:
src/utils/CLI11.hpp