SNode.C: iot::mqtt::packets::Publish Class Reference
iot::mqtt::packets::Publish Class Reference
#include <Publish.h>
Public Member Functions
Publish ()
Publish (uint16_t packetIdentifier, const std::string &topic, const std::string &message, uint8_t qoS, bool dup, bool retain)
bool getDup () const
uint8_t getQoS () const
uint16_t getPacketIdentifier () const
std::string getTopic () const
std::string getMessage () const
bool getRetain () const
Public Member Functions inherited from iot::mqtt::ControlPacket
ControlPacket (uint8_t type, const std::string &name)
ControlPacket (const ControlPacket &)=default
ControlPacket (ControlPacket &&)=default
virtual ~ControlPacket ()
ControlPacket & operator= (const ControlPacket &)=default
ControlPacket & operator= (ControlPacket &&)=default
std::vector< char > serialize () const
const std::string & getName () const
Protected Attributes
iot::mqtt::types::UInt16 packetIdentifier
iot::mqtt::types::String topic
iot::mqtt::types::StringRaw message
bool dup = false
uint8_t qoS = 0
bool retain = false
Protected Attributes inherited from iot::mqtt::ControlPacket
uint8_t flags = 0
Private Member Functions
std::vector< char > serializeVP () const override
Additional Inherited Members
Protected Member Functions inherited from iot::mqtt::ControlPacket
uint8_t getType () const
uint8_t getFlags () const
Detailed Description
Definition at line 59 of file Publish.h.
Constructor & Destructor Documentation
Publish() [1/2]
iot::mqtt::packets::Publish::Publish ()
Definition at line 52 of file Publish.cpp.
        : iot::mqtt::ControlPacket(MQTT_PUBLISH, "PUBLISH") {
    }
References iot::mqtt::ControlPacket::ControlPacket().
Referenced by Publish().
Publish() [2/2]
iot::mqtt::packets::Publish::Publish (uint16_t packetIdentifier, const std::string & topic, const std::string & message, uint8_t qoS, bool dup, bool retain)
Definition at line 56 of file Publish.cpp.
        : Publish() {
        this->flags = static_cast<uint8_t>((dup ? 0x08 : 0x00) | ((qoS << 1) & 0x06) | (retain ? 0x01 : 0x00));
        this->packetIdentifier = packetIdentifier;
        this->topic = topic;
        this->message = message;
        this->dup = dup;
        this->qoS = qoS;
        this->retain = retain;
    }
References dup, iot::mqtt::ControlPacket::flags, message, iot::mqtt::types::String::operator=(), iot::mqtt::types::StringRaw::operator=(), iot::mqtt::types::UInt16::operator=(), packetIdentifier, Publish(), qoS, retain, and topic.
Referenced by iot::mqtt::Session::fromJson(), and iot::mqtt::Mqtt::sendPublish().
Member Function Documentation
getDup()
bool iot::mqtt::packets::Publish::getDup () const
Definition at line 81 of file Publish.cpp.
{
        return dup;
    }
References dup.
Referenced by iot::mqtt::Mqtt::_onPublish(), and iot::mqtt::Session::toJson().
getMessage()
std::string iot::mqtt::packets::Publish::getMessage () const
Definition at line 97 of file Publish.cpp.
{
        return message;
    }
References message.
Referenced by iot::mqtt::Mqtt::_onPublish(), iot::mqtt::server::Mqtt::_onPublish(), and iot::mqtt::Session::toJson().
getPacketIdentifier()
uint16_t iot::mqtt::packets::Publish::getPacketIdentifier () const
Definition at line 89 of file Publish.cpp.
{
        return packetIdentifier;
    }
References packetIdentifier.
Referenced by iot::mqtt::Mqtt::_onPublish().
getQoS()
uint8_t iot::mqtt::packets::Publish::getQoS () const
Definition at line 85 of file Publish.cpp.
{
        return qoS;
    }
References qoS.
Referenced by iot::mqtt::Mqtt::_onPublish(), iot::mqtt::server::Mqtt::_onPublish(), and iot::mqtt::Session::toJson().
getRetain()
bool iot::mqtt::packets::Publish::getRetain () const
Definition at line 101 of file Publish.cpp.
{
        return retain;
    }
References retain.
Referenced by iot::mqtt::Mqtt::_onPublish(), iot::mqtt::server::Mqtt::_onPublish(), and iot::mqtt::Session::toJson().
getTopic()
std::string iot::mqtt::packets::Publish::getTopic () const
Definition at line 93 of file Publish.cpp.
{
        return topic;
    }
References topic.
Referenced by iot::mqtt::Mqtt::_onPublish(), iot::mqtt::server::Mqtt::_onPublish(), and iot::mqtt::Session::toJson().
serializeVP()
std::vector< char > iot::mqtt::packets::Publish::serializeVP () const override private virtual
Implements iot::mqtt::ControlPacket.
Definition at line 67 of file Publish.cpp.
{
        std::vector<char> packet(topic.serialize());
        if (qoS > 0) {
            std::vector<char> tmpVector = packetIdentifier.serialize();
            packet.insert(packet.end(), tmpVector.begin(), tmpVector.end());
        }
        std::vector<char> tmpVector = message.serialize();
        packet.insert(packet.end(), tmpVector.begin(), tmpVector.end());
        return packet;
    }
References message, packetIdentifier, qoS, iot::mqtt::types::String::serialize(), iot::mqtt::types::TypeBase< ValueTypeT >::serialize(), and topic.
Member Data Documentation
dup
bool iot::mqtt::packets::Publish::dup = false protected
Definition at line 81 of file Publish.h.
Referenced by getDup(), iot::mqtt::client::packets::Publish::Publish(), Publish(), and iot::mqtt::server::packets::Publish::Publish().
message
iot::mqtt::types::StringRaw iot::mqtt::packets::Publish::message protected
Definition at line 79 of file Publish.h.
Referenced by iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), getMessage(), Publish(), and serializeVP().
packetIdentifier
iot::mqtt::types::UInt16 iot::mqtt::packets::Publish::packetIdentifier protected
Definition at line 77 of file Publish.h.
Referenced by iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), getPacketIdentifier(), Publish(), and serializeVP().
qoS
uint8_t iot::mqtt::packets::Publish::qoS = 0 protected
Definition at line 82 of file Publish.h.
Referenced by iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), getQoS(), iot::mqtt::client::packets::Publish::Publish(), Publish(), iot::mqtt::server::packets::Publish::Publish(), and serializeVP().
retain
bool iot::mqtt::packets::Publish::retain = false protected
Definition at line 83 of file Publish.h.
Referenced by getRetain(), iot::mqtt::client::packets::Publish::Publish(), Publish(), and iot::mqtt::server::packets::Publish::Publish().
topic
iot::mqtt::types::String iot::mqtt::packets::Publish::topic protected
Definition at line 78 of file Publish.h.
Referenced by iot::mqtt::client::packets::Publish::deserializeVP(), iot::mqtt::server::packets::Publish::deserializeVP(), getTopic(), Publish(), and serializeVP().
The documentation for this class was generated from the following files:
iot/mqtt/packets/Publish.h
iot/mqtt/packets/Publish.cpp