SNode.C: net::config::ConfigTlsClient Class Reference
net::config::ConfigTlsClient Class Reference
#include <ConfigTlsClient.h>
Public Member Functions
ConfigTlsClient & setSni (const std::string &sni)
std::string getSni () const
Public Member Functions inherited from net::config::ConfigTls
ConfigTls & setInitTimeout (const utils::Timeval &newInitTimeout)
utils::Timeval getInitTimeout () const
ConfigTls & setShutdownTimeout (const utils::Timeval &newShutdownTimeout)
utils::Timeval getShutdownTimeout () const
ConfigTls & setCert (const std::string &cert)
std::string getCert () const
ConfigTls & setCertKey (const std::string &certKey)
std::string getCertKey () const
ConfigTls & setCertKeyPassword (const std::string &certKeyPassword)
std::string getCertKeyPassword () const
ConfigTls & setCaCert (const std::string &caCert)
std::string getCaCert () const
ConfigTls & setCaCertDir (const std::string &caCertDir)
std::string getCaCertDir () const
ConfigTls & setCaCertUseDefaultDir (bool set=true)
bool getCaCertUseDefaultDir () const
ConfigTls & setCaCertAcceptUnknown (bool set=true)
bool getCaCertAcceptUnknown () const
ConfigTls & setCipherList (const std::string &cipherList)
std::string getCipherList () const
ConfigTls & setSslOptions (ssl_option_t sslOptions)
ssl_option_t getSslOptions () const
ConfigTls & setNoCloseNotifyIsEOF (bool noCloseNotifyIsEOF=true)
bool getNoCloseNotifyIsEOF () const
Public Member Functions inherited from net::config::ConfigSection
template<typename T>
ConfigSection (ConfigInstance *instance, T *sectionPtr, const std::string &group="Sections")
~ConfigSection () override
ConfigSection (const ConfigSection &)=delete
ConfigSection (ConfigSection &&)=delete
ConfigSection & operator= (const ConfigSection &)=delete
Public Member Functions inherited from utils::SubCommand
SubCommand (const SubCommand &)=delete
SubCommand (SubCommand &&)=delete
SubCommand & operator= (const SubCommand &)=delete
SubCommand & operator= (SubCommand &&)=delete
virtual ~SubCommand ()
std::string getName () const
std::string version () const
void parse (int argc, char *argv[])
CLI::Option * setConfig (const std::string &defaultConfigFile) const
CLI::Option * setLogFile (const std::string &defaultLogFile) const
CLI::Option * setVersionFlag (const std::string &version) const
bool hasParent () const
SubCommand * getParent ()
SubCommand * allowExtras (bool allow=true)
SubCommand * required (bool required=true, bool force=true)
SubCommand * required (SubCommand *subCommand, bool required=true)
SubCommand * required (CLI::Option *option, bool required=true)
SubCommand * needs (SubCommand *subCommand, bool needs=true)
SubCommand * disabled (SubCommand *subCommand, bool disabled=true)
SubCommand * setRequireCallback (const std::function< void(void)> &callback)
SubCommand * finalCallback (const std::function< void()> &finalCallback)
std::string configToStr () const
std::string help (const CLI::App *helpApp, const CLI::AppFormatMode &mode) const
template<typename NewSubCommand, typename... Args>
NewSubCommand * newSubCommand (Args &&... args)
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand ()
template<typename RequestedSubCommand>
RequestedSubCommand * getSubCommand () const
CLI::Option * getOption (const std::string &name) const
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOption (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, const CLI::Validator &additionalValidator) const
template<typename ValueTypeT>
CLI::Option * addOptionVariable (const std::string &name, ValueTypeT &variable, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &additionalValidator) const
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addOptionFunction (const std::string &name, std::function< void(const std::string &)> &callback, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, const CLI::Validator &validator) const
template<typename ValueTypeT>
CLI::Option * addFlag (const std::string &name, const std::string &description, const std::string &typeName, ValueTypeT defaultValue, const CLI::Validator &validator) const
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const CLI::Validator &validator)
CLI::Option * addFlagFunction (const std::string &name, const std::function< void()> &callback, const std::string &description, const std::string &typeName, const std::string &defaultValue, const CLI::Validator &validator)
Protected Member Functions
ConfigTlsClient (ConfigInstance *instance)
~ConfigTlsClient () override
Protected Member Functions inherited from net::config::ConfigTls
template<typename ConcretConfigTls>
ConfigTls (ConfigInstance *instance, ConcretConfigTls section)
~ConfigTls () override
Protected Member Functions inherited from utils::SubCommand
SubCommand (SubCommand *parent, std::shared_ptr< utils::AppWithPtr > appWithPtr, const std::string &group, bool final)
template<typename ConcretSubCommand>
SubCommand (SubCommand *parent, ConcretSubCommand *concretSubCommand, const std::string &group, bool final=true)
SubCommand * description (const std::string &description)
SubCommand * footer (const std::string &footer)
template<typename ValueTypeT>
CLI::Option * setDefaultValue (CLI::Option *option, const ValueTypeT &value, bool clear=true) const
CLI::Option * setConfigurable (CLI::Option *option, bool configurable) const
Private Types
using Super = ConfigTls
Private Attributes
CLI::Option * sniOpt = nullptr
Additional Inherited Members
Static Public Member Functions inherited from utils::SubCommand
static CLI::App * getHelpTriggerApp ()
static CLI::App * getShowConfigTriggerApp ()
static CLI::App * getCommandlineTriggerApp ()
Static Public Attributes inherited from net::config::ConfigTls
static constexpr std::string_view NAME {"tls"}
static constexpr std::string_view DESCRIPTION {"Configuration of SSL/TLS behavior"}
Static Public Attributes inherited from utils::SubCommand
static std::shared_ptr< CLI::Formatter > sectionFormatter = makeSectionFormatter()
Static Protected Attributes inherited from utils::SubCommand
static std::map< std::string, std::string > aliases
static CLI::App * helpTriggerApp = nullptr
static CLI::App * showConfigTriggerApp = nullptr
static CLI::App * commandlineTriggerApp = nullptr
Detailed Description
Definition at line 61 of file ConfigTlsClient.h.
Member Typedef Documentation
Super
using net::config::ConfigTlsClient::Super = ConfigTls private
Definition at line 63 of file ConfigTlsClient.h.
Constructor & Destructor Documentation
ConfigTlsClient()
net::config::ConfigTlsClient::ConfigTlsClient (ConfigInstance * instance) explicit protected
Definition at line 56 of file ConfigTlsClient.cpp.
        : ConfigTls(instance, this) {
        sniOpt = addOption( //
            "--sni",
            "Server Name Indication",
            "sni",
            CLI::TypeValidator<std::string>());
    }
References utils::SubCommand::addOption(), net::config::ConfigTls::ConfigTls(), and sniOpt.
~ConfigTlsClient()
net::config::ConfigTlsClient::~ConfigTlsClient () override protected
Definition at line 65 of file ConfigTlsClient.cpp.
{
    }
Member Function Documentation
getSni()
std::string net::config::ConfigTlsClient::getSni () const
Definition at line 74 of file ConfigTlsClient.cpp.
{
        return sniOpt->as<std::string>();
    }
References sniOpt.
setSni()
ConfigTlsClient & net::config::ConfigTlsClient::setSni (const std::string & sni)
Definition at line 68 of file ConfigTlsClient.cpp.
{
        setDefaultValue(sniOpt, sni);
        return *this;
    }
References utils::SubCommand::setDefaultValue(), and sniOpt.
Member Data Documentation
sniOpt
CLI::Option* net::config::ConfigTlsClient::sniOpt = nullptr private
Definition at line 75 of file ConfigTlsClient.h.
Referenced by ConfigTlsClient(), getSni(), and setSni().
The documentation for this class was generated from the following files:
net/config/ConfigTlsClient.h
net/config/ConfigTlsClient.cpp