SNode.C: core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT > Class Template Reference
core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT > Class Template Reference
#include <SocketConnectionFactory.h>
Public Types
using Config = ConfigT
using SocketAddress = typename PhysicalSocket::SocketAddress
Public Member Functions
SocketConnectionFactory (const SocketConnectionFactory &)=delete
SocketConnectionFactory (SocketConnectionFactory &&)=delete
SocketConnectionFactory & operator= (const SocketConnectionFactory &)=delete
SocketConnectionFactory & operator= (SocketConnectionFactory &&)=delete
SocketConnectionFactory (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect)
bool create (PhysicalSocket &physicalSocket, const std::shared_ptr< Config > &config)
Protected Types
using SocketConnection = SocketConnectionT
Protected Attributes
std::function< void(SocketConnection *)> onConnect
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
Private Types
using PhysicalSocket = PhysicalSocketT
Detailed Description
template<typename PhysicalSocketT, typename ConfigT, typename SocketConnectionT>
class core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >
Definition at line 37 of file SocketConnectionFactory.h.
Member Typedef Documentation
Config
template<typename PhysicalSocketT , typename ConfigT , typename SocketConnectionT > using core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::Config = ConfigT
Definition at line 55 of file SocketConnectionFactory.h.
PhysicalSocket
template<typename PhysicalSocketT , typename ConfigT , typename SocketConnectionT > using core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::PhysicalSocket = PhysicalSocketT private
Definition at line 39 of file SocketConnectionFactory.h.
SocketAddress
template<typename PhysicalSocketT , typename ConfigT , typename SocketConnectionT > using core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::SocketAddress = typename PhysicalSocket::SocketAddress
Definition at line 56 of file SocketConnectionFactory.h.
SocketConnection
template<typename PhysicalSocketT , typename ConfigT , typename SocketConnectionT > using core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::SocketConnection = SocketConnectionT protected
Definition at line 42 of file SocketConnectionFactory.h.
Constructor & Destructor Documentation
SocketConnectionFactory() [1/3]
template<typename PhysicalSocketT , typename ConfigT , typename SocketConnectionT > core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::SocketConnectionFactory (const SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT > &) delete
SocketConnectionFactory() [2/3]
template<typename PhysicalSocketT , typename ConfigT , typename SocketConnectionT > core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::SocketConnectionFactory (SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT > &&) delete
SocketConnectionFactory() [3/3]
template<typename PhysicalSocket , typename Config , typename SocketConnection > core::socket::stream::SocketConnectionFactory< PhysicalSocket, Config, SocketConnection >::SocketConnectionFactory (const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect)
Definition at line 30 of file SocketConnectionFactory.hpp.
        : onConnect(onConnect)
        , onConnected(onConnected)
        , onDisconnect(onDisconnect) {
    }
References core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::onConnect, core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::onConnected, and core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::onDisconnect.
Member Function Documentation
create()
template<typename PhysicalSocket , typename Config , typename SocketConnection > bool core::socket::stream::SocketConnectionFactory< PhysicalSocket, Config, SocketConnection >::create (PhysicalSocket & physicalSocket, const std::shared_ptr< Config > & config)
Definition at line 40 of file SocketConnectionFactory.hpp.
{
        SocketConnection* socketConnection = nullptr;
        if (physicalSocket.isValid()) {
            typename SocketAddress::SockAddr localSockAddr;
            typename SocketAddress::SockAddr remoteSockAddr;
            socklen_t localSockAddrLen = sizeof(typename SocketAddress::SockAddr);
            socklen_t remoteSockAddrLen = sizeof(typename SocketAddress::SockAddr);
            if (physicalSocket.getSockname(localSockAddr, localSockAddrLen) == 0 &&
                physicalSocket.getPeername(remoteSockAddr, remoteSockAddrLen) == 0) {
                physicalSocket.setDontClose();
                socketConnection = new SocketConnection(physicalSocket,
                                                        SocketAddress(localSockAddr, localSockAddrLen),
                                                        SocketAddress(remoteSockAddr, remoteSockAddrLen),
                                                        onDisconnect,
                                                        config->getReadTimeout(),
                                                        config->getWriteTimeout(),
                                                        config->getReadBlockSize(),
                                                        config->getWriteBlockSize(),
                                                        config->getTerminateTimeout());
                onConnect(socketConnection);
                onConnected(socketConnection);
            } else {
                PLOG(TRACE) << "getsockname";
            }
        }
        return socketConnection != nullptr;
    }
References core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::onConnect, core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::onConnected, and core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::onDisconnect.
operator=() [1/2]
template<typename PhysicalSocketT , typename ConfigT , typename SocketConnectionT > SocketConnectionFactory & core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::operator= (const SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT > &) delete
operator=() [2/2]
template<typename PhysicalSocketT , typename ConfigT , typename SocketConnectionT > SocketConnectionFactory & core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::operator= (SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT > &&) delete
Member Data Documentation
onConnect
template<typename PhysicalSocketT , typename ConfigT , typename SocketConnectionT > std::function<void(SocketConnection*)> core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::onConnect protected
Definition at line 61 of file SocketConnectionFactory.h.
Referenced by core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::create(), and core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::SocketConnectionFactory().
onConnected
template<typename PhysicalSocketT , typename ConfigT , typename SocketConnectionT > std::function<void(SocketConnection*)> core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::onConnected protected
Definition at line 62 of file SocketConnectionFactory.h.
Referenced by core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::create(), and core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::SocketConnectionFactory().
onDisconnect
template<typename PhysicalSocketT , typename ConfigT , typename SocketConnectionT > std::function<void(SocketConnection*)> core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::onDisconnect protected
Definition at line 63 of file SocketConnectionFactory.h.
Referenced by core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::create(), and core::socket::stream::SocketConnectionFactory< PhysicalSocketT, ConfigT, SocketConnectionT >::SocketConnectionFactory().
The documentation for this class was generated from the following files:
core/socket/stream/SocketConnectionFactory.h
core/socket/stream/SocketConnectionFactory.hpp