SNode.C: iot::mqtt_fast::packets::Pubrel Class Reference
iot::mqtt_fast::packets::Pubrel Class Reference
#include <Pubrel.h>
Public Member Functions
Pubrel (uint16_t packetIdentifier)
Pubrel (iot::mqtt_fast::ControlPacketFactory &controlPacketFactory)
uint16_t getPacketIdentifier () const
Public Member Functions inherited from iot::mqtt_fast::ControlPacket
ControlPacket (uint8_t type, uint8_t reserved=0)
ControlPacket (iot::mqtt_fast::ControlPacketFactory &controlPacketFactory)
ControlPacket (const ControlPacket &)=delete
ControlPacket (ControlPacket &&)=delete
ControlPacket & operator= (const ControlPacket &)=delete
ControlPacket & operator= (ControlPacket &&)=delete
uint8_t getType () const
uint8_t getReserved () const
uint64_t getRemainingLength () const
std::vector< char > getPacket ()
bool isError () const
Private Attributes
uint16_t packetIdentifier
Additional Inherited Members
Protected Member Functions inherited from iot::mqtt_fast::ControlPacket
std::vector< char > & getValue ()
uint8_t getInt8 ()
uint16_t getInt16 ()
uint32_t getInt32 ()
uint64_t getInt64 ()
uint32_t getIntV ()
std::string getString ()
std::string getStringRaw ()
std::list< uint8_t > getUint8ListRaw ()
void putInt8 (uint8_t value)
void putInt16 (uint16_t value)
void putInt32 (uint32_t value)
void putInt64 (uint64_t value)
void putIntV (uint32_t value)
void putString (const std::string &value)
void putStringRaw (const std::string &value)
void putUint8ListRaw (const std::list< uint8_t > &value)
bool isError ()
Protected Attributes inherited from iot::mqtt_fast::ControlPacket
bool error = false
Detailed Description
Definition at line 61 of file Pubrel.h.
Constructor & Destructor Documentation
Pubrel() [1/2]
iot::mqtt_fast::packets::Pubrel::Pubrel (uint16_t packetIdentifier) explicit
Definition at line 50 of file Pubrel.cpp.
        : iot::mqtt_fast::ControlPacket(MQTT_PUBREL, 0x02)
        , packetIdentifier(packetIdentifier) {
        // V-Header
        putInt16(this->packetIdentifier);
        // no Payload
    }
References iot::mqtt_fast::ControlPacket::ControlPacket(), packetIdentifier, and iot::mqtt_fast::ControlPacket::putInt16().
Referenced by iot::mqtt_fast::SocketContext::sendPubrel().
Pubrel() [2/2]
iot::mqtt_fast::packets::Pubrel::Pubrel (iot::mqtt_fast::ControlPacketFactory & controlPacketFactory) explicit
Definition at line 59 of file Pubrel.cpp.
        : iot::mqtt_fast::ControlPacket(controlPacketFactory) {
        // V-Header
        packetIdentifier = getInt16();
        // no Payload
        error = isError();
    }
References iot::mqtt_fast::ControlPacket::ControlPacket(), iot::mqtt_fast::ControlPacket::error, iot::mqtt_fast::ControlPacket::getInt16(), iot::mqtt_fast::ControlPacket::isError(), and packetIdentifier.
Referenced by iot::mqtt_fast::SocketContext::onReceivedFromPeer().
Member Function Documentation
getPacketIdentifier()
uint16_t iot::mqtt_fast::packets::Pubrel::getPacketIdentifier () const
Definition at line 69 of file Pubrel.cpp.
{
        return packetIdentifier;
    }
References packetIdentifier.
Member Data Documentation
packetIdentifier
uint16_t iot::mqtt_fast::packets::Pubrel::packetIdentifier private
Definition at line 69 of file Pubrel.h.
Referenced by getPacketIdentifier(), Pubrel(), and Pubrel().
The documentation for this class was generated from the following files:
iot/mqtt-fast/packets/Pubrel.h
iot/mqtt-fast/packets/Pubrel.cpp