SNode.C: src/utils/CLI11.hpp File Reference
CLI11.hpp File Reference
#include <algorithm>
#include <array>
#include <cctype>
#include <clocale>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <cwchar>
#include <exception>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <limits>
#include <locale>
#include <map>
#include <memory>
#include <numeric>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <tuple>
#include <type_traits>
#include <utility>
#include <vector>
#include <codecvt>
#include <sys/stat.h>
#include <sys/types.h>
Classes
class Error
All errors derive from this one.
class ConstructionError
Construction errors (not in parsing)
class IncorrectConstruction
Thrown when an option is set to conflicting values (non-vector and multi args, for example)
class BadNameString
Thrown on construction of a bad name.
class OptionAlreadyAdded
Thrown when an option already exists.
class ParseError
Anything that can error in Parse.
class Success
This is a successful completion on parsing, supposed to exit.
class CallForHelp
-h or –help on command line
class CallForAllHelp
Usually something like –help-all on command line.
class CallForVersion
-v or –version on command line
class RuntimeError
Does not output a diagnostic in CLI11_PARSE, but allows main() to return with a specific error code.
class FileError
Thrown when parsing an INI file and it is missing.
class ConversionError
Thrown when conversion call back fails, such as when an int fails to coerce to a string.
class ValidationError
Thrown when validation of results fails.
class RequiredError
Thrown when a required option is missing.
class ArgumentMismatch
Thrown when the wrong number of arguments has been received.
class RequiresError
Thrown when a requires option is missing.
class ExcludesError
Thrown when an excludes option is present.
class ExtrasError
Thrown when too many positionals or options are found.
class ConfigError
Thrown when extra values are found in an INI file.
class InvalidError
Thrown when validation fails before parsing.
class HorribleError
class OptionNotFound
Thrown when counting a non-existent option.
struct make_void< Ts >
A copy of std::void_t from C++17 (helper for C++11 and C++14)
struct is_bool< T >
Check to see if something is bool (fail check by default)
struct is_bool< bool >
Check to see if something is bool (true if actually a bool)
struct is_shared_ptr< T >
Check to see if something is a shared pointer.
struct is_shared_ptr< std::shared_ptr< T > >
Check to see if something is a shared pointer (True if really a shared pointer)
struct is_shared_ptr< const std::shared_ptr< T > >
Check to see if something is a shared pointer (True if really a shared pointer)
struct is_copyable_ptr< T >
Check to see if something is copyable pointer.
struct IsMemberType< T >
This can be specialized to override the type deduction for IsMember.
struct IsMemberType< const char * >
The main custom type needed here is const char * should be a string.
struct detail::element_type< T, Enable >
not a pointer
struct detail::element_type< T, typename std::enable_if< is_copyable_ptr< T >::value >::type >
struct detail::element_value_type< T >
struct detail::pair_adaptor< T, _ >
Adaptor for set-like structure: This just wraps a normal container in a few utilities that do almost nothing.
struct detail::pair_adaptor< T, conditional_t< false, void_t< typename T::value_type::first_type, typename T::value_type::second_type >, void > >
class detail::is_direct_constructible< T, C >
class detail::is_ostreamable< T, S >
class detail::is_istreamable< T, S >
Check for input streamability.
class detail::is_complex< T >
Check for complex.
struct detail::is_mutable_container< T, _ >
struct detail::is_mutable_container< T, conditional_t< false, void_t< typename T::value_type, decltype(std::declval< T >().end()), decltype(std::declval< T >().clear()), decltype(std::declval< T >().insert(std::declval< decltype(std::declval< T >().end())>(), std::declval< const typename T::value_type & >()))>, void > >
struct detail::is_readable_container< T, _ >
struct detail::is_readable_container< T, conditional_t< false, void_t< decltype(std::declval< T >().end()), decltype(std::declval< T >().begin())>, void > >
struct detail::is_wrapper< T, _ >
struct detail::is_wrapper< T, conditional_t< false, void_t< typename T::value_type >, void > >
class detail::is_tuple_like< S >
struct detail::wrapped_type< T, def, Enable >
template to get the underlying value type if it exists or use a default
struct detail::wrapped_type< T, def, typename std::enable_if< is_wrapper< T >::value >::type >
Type size for regular object types that do not look like a tuple.
struct detail::type_count_base< T, Enable >
This will only trigger for actual void type.
struct detail::type_count_base< T, typename std::enable_if<!is_tuple_like< T >::value &&!is_mutable_container< T >::value &&!std::is_void< T >::value >::type >
Type size for regular object types that do not look like a tuple.
struct detail::type_count_base< T, typename std::enable_if< is_tuple_like< T >::value &&!is_mutable_container< T >::value >::type >
the base tuple size
struct detail::type_count_base< T, typename std::enable_if< is_mutable_container< T >::value >::type >
Type count base for containers is the type_count_base of the individual element.
struct detail::type_count< T, Enable >
This will only trigger for actual void type.
struct detail::type_count< T, typename std::enable_if<!is_wrapper< T >::value &&!is_tuple_like< T >::value &&!is_complex< T >::value &&!std::is_void< T >::value >::type >
Type size for regular object types that do not look like a tuple.
struct detail::type_count< T, typename std::enable_if< is_complex< T >::value >::type >
Type size for complex since it sometimes looks like a wrapper.
struct detail::type_count< T, typename std::enable_if< is_mutable_container< T >::value >::type >
Type size of types that are wrappers,except complex and tuples(which can also be wrappers sometimes)
struct detail::type_count< T, typename std::enable_if< is_wrapper< T >::value &&!is_complex< T >::value &&!is_tuple_like< T >::value &&!is_mutable_container< T >::value >::type >
Type size of types that are wrappers,except containers complex and tuples(which can also be wrappers sometimes)
struct ConfigItem
Holds values to load into Options.
class Config
This class provides a converter for configuration files.
class ConfigBase
This converter works with INI/TOML files; to write INI files use ConfigINI.
class ConfigINI
ConfigINI generates a "standard" INI compliant output.
class Validator
Some validators that are provided.
class CustomValidator
Class wrapping some of the accessors of Validator.
class detail::ExistingFileValidator
Check for an existing file (returns error message if check fails)
class detail::ExistingDirectoryValidator
Check for an existing directory (returns error message if check fails)
class detail::ExistingPathValidator
Check for an existing path.
class detail::NonexistentPathValidator
Check for an non-existing path.
class detail::IPV4Validator
Validate the given string is a legal ipv4 address.
class TypeValidator< DesiredType >
Validate the input as a particular type.
class FileOnDefaultPath
class Range
Produce a range (factory). Min and max are inclusive.
class Bound
Produce a bounded range (factory). Min and max are inclusive.
struct detail::has_find< C, V >
class IsMember
Verify items are in a set.
class Transformer
Translate named items to other or a value set.
class CheckedTransformer
translate named items to other or a value set
class AsNumberWithUnit
class AsSizeValue
class FormatterBase
class FormatterLambda
This is a specialty override for lambda functions.
class Formatter
class OptionBase< CRTP >
class OptionDefaults
class Option
class App
Creates a command line program, with very few defaults.
class Option_group
Extension of App to better manage groups of options.
struct detail::AppFriend
This class is simply to allow tests access to App's protected functions.
Namespaces
namespace CLI
namespace CLI::detail
namespace CLI::enums
namespace detail
namespace FailureMessage
Macros
#define CLI11_VERSION_MAJOR 2
#define CLI11_VERSION_MINOR 3
#define CLI11_VERSION_PATCH 2
#define CLI11_VERSION "2.3.2"
#define CLI11_DEPRECATED(reason) __attribute__((deprecated(reason)))
#define CLI11_NODISCARD
#define CLI11_USE_STATIC_RTTI 1
#define CLI11_HAS_CODECVT 1
#define CLI11_DIAGNOSTIC_PUSH
#define CLI11_DIAGNOSTIC_POP
#define CLI11_DIAGNOSTIC_IGNORE_DEPRECATED
#define CLI11_INLINE inline
#define CLI11_ERROR_DEF(parent, name)
#define CLI11_ERROR_SIMPLE(name)
#define CLI11_PARSE(app, ...)
Typedefs
template<bool B, class T = void>
using enable_if_t = typename std::enable_if<B, T>::type
template<typename... Ts>
using void_t = typename make_void<Ts...>::type
A copy of std::void_t from C++17 - same reasoning as enable_if_t, it does not hurt to redefine.
template<bool B, class T , class F >
using conditional_t = typename std::conditional<B, T, F>::type
A copy of std::conditional_t from C++14 - same reasoning as enable_if_t, it does not hurt to redefine.
using ConfigTOML = ConfigBase
the default Config is the TOML file format
using results_t = std::vector<std::string>
using callback_t = std::function<bool(const results_t&)>
callback function definition
using Option_p = std::unique_ptr<Option>
using App_p = std::shared_ptr<App>
Enumerations
enum class ExitCodes {
Success = 0 , IncorrectConstruction = 100 , BadNameString , OptionAlreadyAdded ,
FileError , ConversionError , ValidationError , RequiredError ,
RequiresError , ExcludesError , ExtrasError , ConfigError ,
InvalidError , HorribleError , OptionNotFound , ArgumentMismatch ,
BaseClass = 127
}
enum class detail::enabler
Simple empty scoped class.
enum class detail::path_type { detail::nonexistent , detail::file , detail::directory }
CLI enumeration of different file types.
enum class AppFormatMode { Normal , All , Sub }
enum class MultiOptionPolicy : char {
Throw , TakeLast , TakeFirst , Join ,
TakeAll , Sum
}
Enumeration of the multiOption Policy selection.
enum class detail::Classifier {
detail::NONE , detail::POSITIONAL_MARK , detail::SHORT , detail::LONG ,
detail::WINDOWS_STYLE , detail::SUBCOMMAND , detail::SUBCOMMAND_TERMINATOR
}
enum class config_extras_mode : char { error = 0 , ignore , ignore_all , capture }
enumeration of modes of how to deal with extras in config files
Functions
std::string CLI::narrow (const std::wstring &str)
Convert a wide string to a narrow string.
std::string CLI::narrow (const wchar_t *str)
std::string CLI::narrow (const wchar_t *str, std::size_t size)
std::wstring CLI::widen (const std::string &str)
Convert a narrow string to a wide string.
std::wstring CLI::widen (const char *str)
std::wstring CLI::widen (const char *str, std::size_t size)
std::string CLI::detail::narrow_impl (const wchar_t *str, std::size_t str_size)
std::wstring CLI::detail::widen_impl (const char *str, std::size_t str_size)
int CLI::argc ()
argc as passed in to this executable.
const char *const * CLI::argv ()
argv as passed in to this executable, converted to utf-8 on Windows.
const std::vector< const char * > & CLI::detail::args ()
Command-line arguments, as passed in to this executable, converted to utf-8 on Windows.
template<typename T , typename = typename std::enable_if<std::is_enum<T>::value>::type>
std::ostream & CLI::enums::operator<< (std::ostream &in, const T &item)
output streaming for enumerations
std::vector< std::string > CLI::detail::split (const std::string &s, char delim)
Split a string by a delim.
template<typename T >
std::string CLI::detail::join (const T &v, std::string delim=",")
Simple function to join a string.
template<typename T , typename Callable , typename = typename std::enable_if<!std::is_constructible<std::string, Callable>::value>::type>
std::string CLI::detail::join (const T &v, Callable func, std::string delim=",")
Simple function to join a string from processed elements.
template<typename T >
std::string CLI::detail::rjoin (const T &v, std::string delim=",")
Join a string in reverse order.
std::string & CLI::detail::ltrim (std::string &str)
Trim whitespace from left of string.
std::string & CLI::detail::ltrim (std::string &str, const std::string &filter)
Trim anything from left of string.
std::string & CLI::detail::rtrim (std::string &str)
Trim whitespace from right of string.
std::string & CLI::detail::rtrim (std::string &str, const std::string &filter)
Trim anything from right of string.
std::string & CLI::detail::trim (std::string &str)
Trim whitespace from string.
std::string & CLI::detail::trim (std::string &str, const std::string filter)
Trim anything from string.
std::string CLI::detail::trim_copy (const std::string &str)
Make a copy of the string and then trim it.
std::string & CLI::detail::remove_quotes (std::string &str)
remove quotes at the front and back of a string either '"' or '\''
std::string CLI::detail::fix_newlines (const std::string &leader, std::string input)
std::string CLI::detail::trim_copy (const std::string &str, const std::string &filter)
Make a copy of the string and then trim it, any filter string can be used (any char in string is filtered)
std::ostream & CLI::detail::format_help (std::ostream &out, std::string name, const std::string &description, std::size_t wid)
Print a two part "help" string.
std::ostream & CLI::detail::format_aliases (std::ostream &out, const std::vector< std::string > &aliases, std::size_t wid)
Print subcommand aliases.
template<typename T >
bool CLI::detail::valid_first_char (T c)
template<typename T >
bool CLI::detail::valid_later_char (T c)
Verify following characters of an option.
bool CLI::detail::valid_name_string (const std::string &str)
Verify an option/subcommand name.
bool CLI::detail::valid_alias_name_string (const std::string &str)
Verify an app name.
bool CLI::detail::is_separator (const std::string &str)
check if a string is a container segment separator (empty or "%%")
bool CLI::detail::isalpha (const std::string &str)
Verify that str consists of letters only.
std::string CLI::detail::to_lower (std::string str)
Return a lower case version of a string.
std::string CLI::detail::remove_underscore (std::string str)
remove underscores from a string
std::string CLI::detail::find_and_replace (std::string str, std::string from, std::string to)
Find and replace a substring with another substring.
bool CLI::detail::has_default_flag_values (const std::string &flags)
check if the flag definitions has possible false flags
void CLI::detail::remove_default_flag_values (std::string &flags)
std::ptrdiff_t CLI::detail::find_member (std::string name, const std::vector< std::string > names, bool ignore_case=false, bool ignore_underscore=false)
Check if a string is a member of a list of strings and optionally ignore case or ignore underscores.
template<typename Callable >
std::string CLI::detail::find_and_modify (std::string str, std::string trigger, Callable modify)
CLI::detail::trim (str)
CLI::detail::while (!str.empty())
std::size_t CLI::escape_detect (std::string &str, std::size_t offset)
std::string & CLI::add_quotes_if_needed (std::string &str)
template<typename T , enable_if_t< is_istreamable< T >::value, detail::enabler > = detail::dummy>
bool detail::from_stream (const std::string &istring, T &obj)
Templated operation to get a value from a stream.
template<typename T , enable_if_t< std::is_convertible< T, std::string >::value, detail::enabler > = detail::dummy>
auto detail::to_string (T &&value) -> decltype(std::forward< T >(value))
Convert an object to a string (directly forward if this can become a string)
template<typename T , enable_if_t< std::is_constructible< std::string, T >::value &&!std::is_convertible< T, std::string >::value, detail::enabler > = detail::dummy>
std::string detail::to_string (const T &value)
Construct a string from the object.
template<typename T , enable_if_t<!std::is_convertible< std::string, T >::value &&!std::is_constructible< std::string, T >::value &&is_ostreamable< T >::value, detail::enabler > = detail::dummy>
std::string detail::to_string (T &&value)
Convert an object to a string (streaming must be supported for that type)
template<typename T1 , typename T2 , typename T , enable_if_t< std::is_same< T1, T2 >::value, detail::enabler > = detail::dummy>
auto detail::checked_to_string (T &&value) -> decltype(to_string(std::forward< T >(value)))
special template overload
template<typename T1 , typename T2 , typename T , enable_if_t<!std::is_same< T1, T2 >::value, detail::enabler > = detail::dummy>
std::string detail::checked_to_string (T &&)
special template overload
template<typename T , enable_if_t< std::is_arithmetic< T >::value, detail::enabler > = detail::dummy>
std::string detail::value_string (const T &value)
get a string as a convertible value for arithmetic types
template<typename T , enable_if_t<!std::is_enum< T >::value &&!std::is_arithmetic< T >::value, detail::enabler > = detail::dummy>
auto detail::value_string (const T &value) -> decltype(to_string(value))
for other types just use the regular to_string function
template<typename T , std::size_t I>
constexpr std::enable_if< I==type_count_base< T >::value, int >::type detail::tuple_type_size ()
0 if the index > tuple size
template<typename T , std::size_t I>
constexpr std::enable_if< I< type_count_base< T >::value, int >::type tuple_type_size() { return subtype_count< typename std::tuple_element< I, T >::type >::value+tuple_type_size< T, I+1 >();} template< typename T > struct type_count< T, typename std::enable_if< is_tuple_like< T >::value >::type > { static constexpr int value{tuple_type_size< T, 0 >()};};template< typename T > struct subtype_count { static constexpr int value{is_mutable_container< T >::value ? expected_max_vector_size :type_count< T >::value};};template< typename T, typename Enable=void > struct type_count_min { static const int value{0};};template< typename T > struct type_count_min< T, typename std::enable_if<!is_mutable_container< T >::value &&!is_tuple_like< T >::value &&!is_wrapper< T >::value &&!is_complex< T >::value &&!std::is_void< T >::value >::type > { static constexpr int value{type_count< T >::value};};template< typename T > struct type_count_min< T, typename std::enable_if< is_complex< T >::value >::type > { static constexpr int value{1};};template< typename T > struct type_count_min< T, typename std::enable_if< is_wrapper< T >::value &&!is_complex< T >::value &&!is_tuple_like< T >::value >::type > { static constexpr int value{subtype_count_min< typename T::value_type >::value};};template< typename T, std::size_t I > constexpr typename std::enable_if< I==type_count_base< T >::value, int >::type tuple_type_size_min() { return 0;} template< typename T, std::size_t I > constexpr typename std::enable_if< I< type_count_base< T >::value, int >::type tuple_type_size_min() { return subtype_count_min< typename std::tuple_element< I, T >::type >::value+tuple_type_size_min< T, I+1 >();} template< typename T > struct type_count_min< T, typename std::enable_if< is_tuple_like< T >::value >::type > { static constexpr int value{tuple_type_size_min< T, 0 >()};};template< typename T > struct subtype_count_min { static constexpr int value{is_mutable_container< T >::value ?((type_count< T >::value< expected_max_vector_size) ? type_count< T >::value :0) :type_count_min< T >::value};};template< typename T, typename Enable=void > struct expected_count { static const int value{0};};template< typename T > struct expected_count< T, typename std::enable_if<!is_mutable_container< T >::value &&!is_wrapper< T >::value &&!std::is_void< T >::value >::type > { static constexpr int value{1};};template< typename T > struct expected_count< T, typename std::enable_if< is_mutable_container< T >::value >::type > { static constexpr int value{expected_max_vector_size};};template< typename T > struct expected_count< T, typename std::enable_if<!is_mutable_container< T >::value &&is_wrapper< T >::value >::type > { static constexpr int value{expected_count< typename T::value_type >::value};};enum class object_category :int { char_value=1, integral_value=2, unsigned_integral=4, enumeration=6, boolean_value=8, floating_point=10, number_constructible=12, double_constructible=14, integer_constructible=16, string_assignable=23, string_constructible=24, wstring_assignable=25, wstring_constructible=26, other=45, wrapper_value=50, complex_number=60, tuple_value=70, container_value=80, };template< typename T, typename Enable=void > struct classify_object { static constexpr object_category value{object_category::other};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, char >::value &&std::is_signed< T >::value &&!is_bool< T >::value &&!std::is_enum< T >::value >::type > { static constexpr object_category value{object_category::integral_value};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_integral< T >::value &&std::is_unsigned< T >::value &&!std::is_same< T, char >::value &&!is_bool< T >::value >::type > { static constexpr object_category value{object_category::unsigned_integral};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_same< T, char >::value &&!std::is_enum< T >::value >::type > { static constexpr object_category value{object_category::char_value};};template< typename T > struct classify_object< T, typename std::enable_if< is_bool< T >::value >::type > { static constexpr object_category value{object_category::boolean_value};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_floating_point< T >::value >::type > { static constexpr object_category value{object_category::floating_point};};template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value &&std::is_assignable< T &, std::string >::value >::type > { static constexpr object_category value{object_category::string_assignable};};template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value &&!std::is_assignable< T &, std::string >::value &&(type_count< T >::value==1) &&std::is_constructible< T, std::string >::value >::type > { static constexpr object_category value{object_category::string_constructible};};template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value &&!std::is_assignable< T &, std::string >::value &&!std::is_constructible< T, std::string >::value &&std::is_assignable< T &, std::wstring >::value >::type > { static constexpr object_category value{object_category::wstring_assignable};};template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value &&!std::is_assignable< T &, std::string >::value &&!std::is_constructible< T, std::string >::value &&!std::is_assignable< T &, std::wstring >::value &&(type_count< T >::value==1) &&std::is_constructible< T, std::wstring >::value >::type > { static constexpr object_category value{object_category::wstring_constructible};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_enum< T >::value >::type > { static constexpr object_category value{object_category::enumeration};};template< typename T > struct classify_object< T, typename std::enable_if< is_complex< T >::value >::type > { static constexpr object_category value{object_category::complex_number};};template< typename T > struct uncommon_type { using type=typename std::conditional< !std::is_floating_point< T >::value &&!std::is_integral< T >::value &&!std::is_assignable< T &, std::string >::value &&!std::is_constructible< T, std::string >::value &&!std::is_assignable< T &, std::wstring >::value &&!std::is_constructible< T, std::wstring >::value &&!is_complex< T >::value &&!is_mutable_container< T >::value &&!std::is_enum< T >::value, std::true_type, std::false_type >::type;static constexpr bool value=type::value;};template< typename T > struct classify_object< T, typename std::enable_if<(!is_mutable_container< T >::value &&is_wrapper< T >::value &&!is_tuple_like< T >::value &&uncommon_type< T >::value)>::type > { static constexpr object_category value{object_category::wrapper_value};};template< typename T > struct classify_object< T, typename std::enable_if< uncommon_type< T >::value &&type_count< T >::value==1 &&!is_wrapper< T >::value &&is_direct_constructible< T, double >::value &&is_direct_constructible< T, int >::value >::type > { static constexpr object_category value{object_category::number_constructible};};template< typename T > struct classify_object< T, typename std::enable_if< uncommon_type< T >::value &&type_count< T >::value==1 &&!is_wrapper< T >::value &&!is_direct_constructible< T, double >::value &&is_direct_constructible< T, int >::value >::type > { static constexpr object_category value{object_category::integer_constructible};};template< typename T > struct classify_object< T, typename std::enable_if< uncommon_type< T >::value &&type_count< T >::value==1 &&!is_wrapper< T >::value &&is_direct_constructible< T, double >::value &&!is_direct_constructible< T, int >::value >::type > { static constexpr object_category value{object_category::double_constructible};};template< typename T > struct classify_object< T, typename std::enable_if< is_tuple_like< T >::value &&((type_count< T >::value >=2 &&!is_wrapper< T >::value)||(uncommon_type< T >::value &&!is_direct_constructible< T, double >::value &&!is_direct_constructible< T, int >::value)||(uncommon_type< T >::value &&type_count< T >::value >=2))>::type > { static constexpr object_category value{object_category::tuple_value};};template< typename T > struct classify_object< T, typename std::enable_if< is_mutable_container< T >::value >::type > { static constexpr object_category value{object_category::container_value};};template< typename T, enable_if_t< classify_object< T >::value==object_category::char_value, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "CHAR";} template< typename T, enable_if_t< classify_object< T >::value==object_category::integral_value||classify_object< T >::value==object_category::integer_constructible, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "INT";} template< typename T, enable_if_t< classify_object< T >::value==object_category::unsigned_integral, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "UINT";} template< typename T, enable_if_t< classify_object< T >::value==object_category::floating_point||classify_object< T >::value==object_category::number_constructible||classify_object< T >::value==object_category::double_constructible, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "FLOAT";} template< typename T, enable_if_t< classify_object< T >::value==object_category::enumeration, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "ENUM";} template< typename T, enable_if_t< classify_object< T >::value==object_category::boolean_value, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "BOOLEAN";} template< typename T, enable_if_t< classify_object< T >::value==object_category::complex_number, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "COMPLEX";} template< typename T, enable_if_t< classify_object< T >::value >=object_category::string_assignable &&classify_object< T >::value<=object_category::other, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "TEXT";} template< typename T, enable_if_t< classify_object< T >::value==object_category::tuple_value &&type_count_base< T >::value >=2, detail::enabler >=detail::dummy > std::string type_name();template< typename T, enable_if_t< classify_object< T >::value==object_category::container_value||classify_object< T >::value==object_category::wrapper_value, detail::enabler >=detail::dummy > std::string type_name();template< typename T, enable_if_t< classify_object< T >::value==object_category::tuple_value &&type_count_base< T >::value==1, detail::enabler >=detail::dummy > inline std::string type_name() { return type_name< typename std::decay< typename std::tuple_element< 0, T >::type >::type >();} template< typename T, std::size_t I > inline typename std::enable_if< I==type_count_base< T >::value, std::string >::type tuple_name() { return std::string{};} template< typename T, std::size_t I > inline typename std::enable_if<(I< type_count_base< T >::value), std::string >::type tuple_name() { auto str=std::string{type_name< typename std::decay< typename std::tuple_element< I, T >::type >::type >()}+','+tuple_name< T, I+1 >();if(str.back()==',') str.pop_back();return str;} template< typename T, enable_if_t< classify_object< T >::value==object_category::tuple_value &&type_count_base< T >::value >=2, detail::enabler > > inline std::string type_name() { auto tname=std::string(1, '[')+tuple_name< T, 0 >();tname.push_back(']');return tname;} template< typename T, enable_if_t< classify_object< T >::value==object_category::container_value||classify_object< T >::value==object_category::wrapper_value, detail::enabler > > inline std::string type_name() { return type_name< typename T::value_type >();} template< typename T, enable_if_t< std::is_unsigned< T >::value, detail::enabler >=detail::dummy > bool integral_conversion(const std::string &input, T &output) noexcept { if(input.empty()||input.front()=='-') { return false;} char *val=nullptr;errno=0;std::uint64_t const output_ll=std::strtoull(input.c_str(), &val, 0);if(errno==ERANGE) { return false;} output=static_cast< T >(output_ll);if(val==(input.c_str()+input.size()) &&static_cast< std::uint64_t >(output)==output_ll) { return true;} val=nullptr;std::int64_t const output_sll=std::strtoll(input.c_str(), &val, 0);if(val==(input.c_str()+input.size())) { output=(output_sll< 0) ? static_cast< T >(0) :static_cast< T >(output_sll);return(static_cast< std::int64_t >(output)==output_sll);} return false;} template< typename T, enable_if_t< std::is_signed< T >::value, detail::enabler >=detail::dummy > bool detail::integral_conversion (const std::string &input, T &output) noexcept
Recursively generate the tuple type name.
std::int64_t detail::to_flag_value (std::string val)
Convert a flag into an integer value typically binary flags.
template<typename T , enable_if_t< classify_object< T >::value==object_category::integral_value||classify_object< T >::value==object_category::unsigned_integral, detail::enabler > = detail::dummy>
bool detail::lexical_cast (const std::string &input, T &output)
Integer conversion.
template<typename AssignTo , typename ConvertTo , enable_if_t< std::is_same< AssignTo, ConvertTo >::value &&(classify_object< AssignTo >::value==object_category::string_assignable||classify_object< AssignTo >::value==object_category::string_constructible||classify_object< AssignTo >::value==object_category::wstring_assignable||classify_object< AssignTo >::value==object_category::wstring_constructible), detail::enabler > = detail::dummy>
bool detail::lexical_assign (const std::string &input, AssignTo &output)
Assign a value through lexical cast operations.
bool detail::split_short (const std::string &current, std::string &name, std::string &rest)
bool detail::split_long (const std::string &current, std::string &name, std::string &value)
bool detail::split_windows_style (const std::string &current, std::string &name, std::string &value)
std::vector< std::string > detail::split_names (std::string current)
std::vector< std::pair< std::string, std::string > > detail::get_default_flag_values (const std::string &str)
extract default flag values either {def} or starting with a !
std::tuple< std::vector< std::string >, std::vector< std::string >, std::string > detail::get_names (const std::vector< std::string > &input)
Get a vector of short names, one of long names, and a single name.
path_type detail::check_path (const char *file) noexcept
get the type of the path from a file name
template<typename T , enable_if_t< is_copyable_ptr< typename std::remove_reference< T >::type >::value, detail::enabler > = detail::dummy>
auto detail::smart_deref (T value) -> decltype(*value)
template<typename T , enable_if_t<!is_copyable_ptr< typename std::remove_reference< T >::type >::value, detail::enabler > = detail::dummy>
std::remove_reference< T >::type & detail::smart_deref (T &value)
template<typename T >
std::string detail::generate_set (const T &set)
Generate a string representation of a set.
template<typename T >
std::string detail::generate_map (const T &map, bool key_only=false)
Generate a string representation of a map.
template<typename T , typename V , enable_if_t<!has_find< T, V >::value, detail::enabler > = detail::dummy>
auto detail::search (const T &set, const V &val) -> std::pair< bool, decltype(std::begin(detail::smart_deref(set)))>
A search function.
template<typename T , typename V >
auto detail::search (const T &set, const V &val, const std::function< V(V)> &filter_function) -> std::pair< bool, decltype(std::begin(detail::smart_deref(set)))>
A search function with a filter function.
template<typename T >
std::enable_if< std::is_signed< T >::value, T >::type detail::overflowCheck (const T &a, const T &b)
Do a check for overflow on signed numbers.
template<typename T >
std::enable_if<!std::is_signed< T >::value, T >::type detail::overflowCheck (const T &a, const T &b)
Do a check for overflow on unsigned numbers.
template<typename T >
std::enable_if< std::is_integral< T >::value, bool >::type detail::checked_multiply (T &a, T b)
Performs a *= b; if it doesn't cause integer overflow. Returns false otherwise.
template<typename T >
std::enable_if< std::is_floating_point< T >::value, bool >::type detail::checked_multiply (T &a, T b)
Performs a *= b; if it doesn't equal infinity. Returns false otherwise.
std::pair< std::string, std::string > detail::split_program_name (std::string commandline)
std::string FailureMessage::simple (const App *app, const Error &e)
Printout a clean, simple message on error (the default in CLI11 1.5+)
std::string FailureMessage::help (const App *app, const Error &e)
Printout the full help string on error (if this fn is set, the old default for CLI11)
template<typename T , enable_if_t<!std::is_integral< T >::value||(sizeof(T)<=1U), detail::enabler > = detail::dummy>
Option * detail::default_flag_modifiers (Option *opt)
helper functions for adding in appropriate flag modifiers for add_flag
void TriggerOn (App *trigger_app, App *app_to_enable)
Helper function to enable one option group/subcommand when another is used.
void TriggerOn (App *trigger_app, std::vector< App * > apps_to_enable)
Helper function to enable one option group/subcommand when another is used.
void TriggerOff (App *trigger_app, App *app_to_enable)
Helper function to disable one option group/subcommand when another is used.
void TriggerOff (App *trigger_app, std::vector< App * > apps_to_enable)
Helper function to disable one option group/subcommand when another is used.
void deprecate_option (Option *opt, const std::string &replacement="")
Helper function to mark an option as deprecated.
void deprecate_option (App *app, const std::string &option_name, const std::string &replacement="")
Helper function to mark an option as deprecated.
void deprecate_option (App &app, const std::string &option_name, const std::string &replacement="")
Helper function to mark an option as deprecated.
void retire_option (App *app, Option *opt)
Helper function to mark an option as retired.
void retire_option (App &app, Option *opt)
Helper function to mark an option as retired.
void retire_option (App *app, const std::string &option_name)
Helper function to mark an option as retired.
void retire_option (App &app, const std::string &option_name)
Helper function to mark an option as retired.
const char * detail::maybe_narrow (const char *str)
std::string detail::maybe_narrow (const wchar_t *str)
std::string detail::convert_arg_for_ini (const std::string &arg, char stringQuote='"', char characterQuote = '\'')
std::string detail::ini_join (const std::vector< std::string > &args, char sepChar=',', char arrayStart='[', char arrayEnd=']', char stringQuote='"', char characterQuote = '\'')
Comma separated join, adds quotes if needed.
std::vector< std::string > detail::generate_parents (const std::string &section, std::string &name, char parentSeparator)
void detail::checkParentSegments (std::vector< ConfigItem > &output, const std::string &currentSection, char parentSeparator)
assuming non default segments do a check on the close and open of the segments in a configItem structure
Variables
constexpr int CLI::detail::expected_max_vector_size {1 << 29}
auto CLI::detail::find_ws
std::vector< std::string > CLI::detail::output
bool CLI::detail::embeddedQuote = false
char CLI::detail::keyChar = ' '
constexpr enabler detail::dummy = {}
An instance to use in EnableIf.
template<typename T >
using TransformPairs = std::vector<std::pair<std::string, T>>
definition of the default transformation object
const detail::ExistingFileValidator ExistingFile
Check for existing file (returns error message if check fails)
const detail::ExistingDirectoryValidator ExistingDirectory
Check for an existing directory (returns error message if check fails)
const detail::ExistingPathValidator ExistingPath
Check for an existing path.
const detail::NonexistentPathValidator NonexistentPath
Check for an non-existing path.
const detail::IPV4Validator ValidIPV4
Check for an IP4 address.
const TypeValidator< double > Number ("NUMBER")
Check for a number.
const Range NonNegativeNumber ((std::numeric_limits< double >::max)(), "NONNEGATIVE")
Check for a non negative number.
const Range PositiveNumber ((std::numeric_limits< double >::min)(),(std::numeric_limits< double >::max)(), "POSITIVE")
Check for a positive valued number (val>0.0), <double>min here is the smallest positive number.
std::string ignore_case (std::string item)
Helper function to allow ignore_case to be passed to IsMember or Transform.
std::string ignore_underscore (std::string item)
Helper function to allow ignore_underscore to be passed to IsMember or Transform.
std::string ignore_space (std::string item)
Helper function to allow checks to ignore spaces to be passed to IsMember or Transform.
AsNumberWithUnit::Options operator| (const AsNumberWithUnit::Options &a, const AsNumberWithUnit::Options &b)
Macro Definition Documentation
CLI11_DEPRECATED
#define CLI11_DEPRECATED (reason) __attribute__((deprecated(reason)))
Definition at line 101 of file CLI11.hpp.
CLI11_DIAGNOSTIC_IGNORE_DEPRECATED
#define CLI11_DIAGNOSTIC_IGNORE_DEPRECATED
Definition at line 180 of file CLI11.hpp.
CLI11_DIAGNOSTIC_POP
#define CLI11_DIAGNOSTIC_POP
Definition at line 178 of file CLI11.hpp.
CLI11_DIAGNOSTIC_PUSH
#define CLI11_DIAGNOSTIC_PUSH
disable deprecations
Definition at line 177 of file CLI11.hpp.
CLI11_ERROR_DEF
#define CLI11_ERROR_DEF (parent, name)
Value:
protected:                                                                                                                                 \
    name(std::string ename, std::string msg, int exit_code)                                                                                \
        : parent(std::move(ename), std::move(msg), exit_code) {                                                                            \
    }                                                                                                                                      \
    name(std::string ename, std::string msg, ExitCodes exit_code)                                                                          \
        : parent(std::move(ename), std::move(msg), exit_code) {                                                                            \
    }                                                                                                                                      \
                                                                                                                                           \
public:                                                                                                                                    \
    name(std::string msg, ExitCodes exit_code)                                                                                             \
        : parent(#name, std::move(msg), exit_code) {                                                                                       \
    }                                                                                                                                      \
    name(std::string msg, int exit_code)                                                                                                   \
        : parent(#name, std::move(msg), exit_code) {                                                                                       \
    }
Definition at line 1000 of file CLI11.hpp.
#define CLI11_ERROR_DEF(parent, name)                                                                                                      \
protected:                                                                                                                                 \
    name(std::string ename, std::string msg, int exit_code)                                                                                \
        : parent(std::move(ename), std::move(msg), exit_code) {                                                                            \
    }                                                                                                                                      \
    name(std::string ename, std::string msg, ExitCodes exit_code)                                                                          \
        : parent(std::move(ename), std::move(msg), exit_code) {                                                                            \
    }                                                                                                                                      \
                                                                                                                                           \
public:                                                                                                                                    \
    name(std::string msg, ExitCodes exit_code)                                                                                             \
        : parent(#name, std::move(msg), exit_code) {                                                                                       \
    }                                                                                                                                      \
    name(std::string msg, int exit_code)                                                                                                   \
        : parent(#name, std::move(msg), exit_code) {                                                                                       \
    }
CLI11_ERROR_SIMPLE
#define CLI11_ERROR_SIMPLE (name)
Value:
    explicit name(std::string msg)                                                                                                         \
        : name(#name, msg, ExitCodes::name) {                                                                                              \
    }
Definition at line 1018 of file CLI11.hpp.
#define CLI11_ERROR_SIMPLE(name)                                                                                                           \
    explicit name(std::string msg)                                                                                                         \
        : name(#name, msg, ExitCodes::name) {                                                                                              \
    }
CLI11_HAS_CODECVT
#define CLI11_HAS_CODECVT 1
<filesystem> availability <codecvt> availability
Definition at line 159 of file CLI11.hpp.
CLI11_INLINE
#define CLI11_INLINE inline
Inline macro
Definition at line 188 of file CLI11.hpp.
CLI11_NODISCARD
#define CLI11_NODISCARD
Definition at line 106 of file CLI11.hpp.
CLI11_PARSE
#define CLI11_PARSE (app, ...)
Value:
    try {                                                                                                                                  \
        (app).parse(__VA_ARGS__);                                                                                                          \
    } catch (const CLI::ParseError& e) {                                                                                                   \
        return (app).exit(e);                                                                                                              \
    }
Definition at line 6229 of file CLI11.hpp.
#define CLI11_PARSE(app, ...)                                                                                                              \
    try {                                                                                                                                  \
        (app).parse(__VA_ARGS__);                                                                                                          \
    } catch (const CLI::ParseError& e) {                                                                                                   \
        return (app).exit(e);                                                                                                              \
    }
CLI11_USE_STATIC_RTTI
#define CLI11_USE_STATIC_RTTI 1
detection of rtti
Definition at line 124 of file CLI11.hpp.
CLI11_VERSION
#define CLI11_VERSION "2.3.2"
Definition at line 69 of file CLI11.hpp.
CLI11_VERSION_MAJOR
#define CLI11_VERSION_MAJOR 2
Definition at line 66 of file CLI11.hpp.
CLI11_VERSION_MINOR
#define CLI11_VERSION_MINOR 3
Definition at line 67 of file CLI11.hpp.
CLI11_VERSION_PATCH
#define CLI11_VERSION_PATCH 2
Definition at line 68 of file CLI11.hpp.
Typedef Documentation
App_p
using App_p = std::shared_ptr<App>
Definition at line 6256 of file CLI11.hpp.
callback_t
using callback_t = std::function<bool(const results_t&)>
callback function definition
Definition at line 4729 of file CLI11.hpp.
conditional_t
template<bool B, class T , class F > using conditional_t = typename std::conditional<B, T, F>::type
A copy of std::conditional_t from C++14 - same reasoning as enable_if_t, it does not hurt to redefine.
Definition at line 1400 of file CLI11.hpp.
ConfigTOML
using ConfigTOML = ConfigBase
the default Config is the TOML file format
Definition at line 3301 of file CLI11.hpp.
enable_if_t
template<bool B, class T = void> using enable_if_t = typename std::enable_if<B, T>::type
A copy of enable_if_t from C++14, compatible with C++11.
We could check to see if C++14 is being used, but it does not hurt to redefine this (even Google does this: https://github.com/google/skia/blob/main/include/private/SkTLogic.h) It is not in the std namespace anyway, so no harm done.
Definition at line 1386 of file CLI11.hpp.
Option_p
using Option_p = std::unique_ptr<Option>
Definition at line 4734 of file CLI11.hpp.
results_t
using results_t = std::vector<std::string>
Definition at line 4727 of file CLI11.hpp.
TransformPairs
template<typename T > using TransformPairs = std::vector<std::pair<std::string, T>>
definition of the default transformation object
Definition at line 3871 of file CLI11.hpp.
void_t
template<typename... Ts> using void_t = typename make_void<Ts...>::type
A copy of std::void_t from C++17 - same reasoning as enable_if_t, it does not hurt to redefine.
Definition at line 1396 of file CLI11.hpp.
Enumeration Type Documentation
AppFormatMode
enum class AppFormatMode strong
This enum signifies the type of help requested
This is passed in by App; all user classes must accept this as the second argument.
Enumerator
Normal
The normal, detailed help.
All
A fully expanded help.
Sub
Used when printed as part of expanded subcommand.
Definition at line 4561 of file CLI11.hpp.
{
        Normal,
        All,
        Sub,
    };
config_extras_mode
enum class config_extras_mode : char strong
enumeration of modes of how to deal with extras in config files
Enumerator
error
ignore
ignore_all
capture
Definition at line 6252 of file CLI11.hpp.
: char { error = 0, ignore, ignore_all, capture };
ExitCodes
enum class ExitCodes strong
These codes are part of every error in CLI. They can be obtained from e using e.exit_code or as a quick shortcut, int values from e.get_error_code().
Enumerator
Success
IncorrectConstruction
BadNameString
OptionAlreadyAdded
FileError
ConversionError
ValidationError
RequiredError
RequiresError
ExcludesError
ExtrasError
ConfigError
InvalidError
HorribleError
OptionNotFound
ArgumentMismatch
BaseClass
Definition at line 1025 of file CLI11.hpp.
{
        Success = 0,
        IncorrectConstruction = 100,
        BadNameString,
        OptionAlreadyAdded,
        FileError,
        ConversionError,
        ValidationError,
        RequiredError,
        RequiresError,
        ExcludesError,
        ExtrasError,
        ConfigError,
        InvalidError,
        HorribleError,
        OptionNotFound,
        ArgumentMismatch,
        BaseClass = 127
    };
MultiOptionPolicy
enum class MultiOptionPolicy : char strong
Enumeration of the multiOption Policy selection.
Enumerator
Throw
Throw an error if any extra arguments were given.
TakeLast
take only the last Expected number of arguments
TakeFirst
take only the first Expected number of arguments
Join
merge all the arguments together into a single string via the delimiter character default('
')
TakeAll
just get all the passed argument regardless
Sum
sum all the arguments together if numerical or concatenate directly without delimiter
Definition at line 4736 of file CLI11.hpp.
                                 : char {
        Throw,
        TakeLast,
        TakeFirst,
        Join,
        TakeAll,
        Sum
    };
Function Documentation
deprecate_option() [1/3]
void deprecate_option (App & app, const std::string & option_name, const std::string & replacement = "") inline
Helper function to mark an option as deprecated.
Definition at line 7656 of file CLI11.hpp.
{
        auto* opt = app.get_option(option_name);
        deprecate_option(opt, replacement);
    }
References App::get_option().
deprecate_option() [2/3]
void deprecate_option (App * app, const std::string & option_name, const std::string & replacement = "") inline
Helper function to mark an option as deprecated.
Definition at line 7650 of file CLI11.hpp.
{
        auto* opt = app->get_option(option_name);
        deprecate_option(opt, replacement);
    }
References App::get_option().
deprecate_option() [3/3]
void deprecate_option (Option * opt, const std::string & replacement = "") inline
Helper function to mark an option as deprecated.
Definition at line 9817 of file CLI11.hpp.
{
        Validator deprecate_warning{[opt, replacement](std::string&) {
                                        std::cout << opt->get_name() << " is deprecated please use '" << replacement << "' instead\n";
                                        return std::string();
                                    },
                                    "DEPRECATED"};
        deprecate_warning.application_index(0);
        opt->check(deprecate_warning);
        if (!replacement.empty()) {
            opt->description(opt->get_description() + " DEPRECATED: please use '" + replacement + "' instead");
        }
    }
References Validator::application_index(), Option::check(), Option::description(), Option::get_description(), and Option::get_name().
ignore_case()
std::string ignore_case (std::string item) inline
Helper function to allow ignore_case to be passed to IsMember or Transform.
Definition at line 4026 of file CLI11.hpp.
{
        return detail::to_lower(item);
    }
References CLI::detail::to_lower().
ignore_space()
std::string ignore_space (std::string item) inline
Helper function to allow checks to ignore spaces to be passed to IsMember or Transform.
Definition at line 4036 of file CLI11.hpp.
{
        item.erase(std::remove(std::begin(item), std::end(item), ' '), std::end(item));
        item.erase(std::remove(std::begin(item), std::end(item), '\t'), std::end(item));
        return item;
    }
ignore_underscore()
std::string ignore_underscore (std::string item) inline
Helper function to allow ignore_underscore to be passed to IsMember or Transform.
Definition at line 4031 of file CLI11.hpp.
{
        return detail::remove_underscore(item);
    }
References CLI::detail::remove_underscore().
operator|()
AsNumberWithUnit::Options operator| (const AsNumberWithUnit::Options & a, const AsNumberWithUnit::Options & b) inline
Definition at line 4179 of file CLI11.hpp.
{
        return static_cast<AsNumberWithUnit::Options>(static_cast<int>(a) | static_cast<int>(b));
    }
retire_option() [1/4]
void retire_option (App & app, const std::string & option_name) inline
Helper function to mark an option as retired.
Definition at line 9877 of file CLI11.hpp.
{
        retire_option(&app, option_name);
    }
References retire_option().
retire_option() [2/4]
void retire_option (App & app, Option * opt) inline
Helper function to mark an option as retired.
Definition at line 9854 of file CLI11.hpp.
{
        retire_option(&app, opt);
    }
References retire_option().
retire_option() [3/4]
void retire_option (App * app, const std::string & option_name) inline
Helper function to mark an option as retired.
Definition at line 9858 of file CLI11.hpp.
{
        auto* opt = app->get_option_no_throw(option_name);
        if (opt != nullptr) {
            retire_option(app, opt);
            return;
        }
        auto* opt2 = app->add_option(option_name, "option has been retired and has no effect")
                         ->type_name("RETIRED")
                         ->expected(0, 1)
                         ->default_str("RETIRED");
        Validator retired_warning{[opt2](std::string&) {
                                      std::cout << "WARNING " << opt2->get_name() << " is retired and has no effect\n";
                                      return std::string();
                                  },
                                  ""};
        retired_warning.application_index(0);
        opt2->check(retired_warning);
    }
References Validator::application_index(), Option::default_str(), Option::expected(), App::get_option_no_throw(), retire_option(), and Option::type_name().
Referenced by retire_option().
retire_option() [4/4]
void retire_option (App * app, Option * opt) inline
Helper function to mark an option as retired.
Definition at line 9830 of file CLI11.hpp.
{
        App temp;
        auto* option_copy = temp.add_option(opt->get_name(false, true))
                                ->type_size(opt->get_type_size_min(), opt->get_type_size_max())
                                ->expected(opt->get_expected_min(), opt->get_expected_max())
                                ->allow_extra_args(opt->get_allow_extra_args());
        app->remove_option(opt);
        auto* opt2 = app->add_option(option_copy->get_name(false, true), "option has been retired and has no effect")
                         ->type_name("RETIRED")
                         ->default_str("RETIRED")
                         ->type_size(option_copy->get_type_size_min(), option_copy->get_type_size_max())
                         ->expected(option_copy->get_expected_min(), option_copy->get_expected_max())
                         ->allow_extra_args(option_copy->get_allow_extra_args());
        Validator retired_warning{[opt2](std::string&) {
                                      std::cout << "WARNING " << opt2->get_name() << " is retired and has no effect\n";
                                      return std::string();
                                  },
                                  ""};
        retired_warning.application_index(0);
        opt2->check(retired_warning);
    }
References App::add_option(), Option::allow_extra_args(), Validator::application_index(), Option::default_str(), Option::expected(), Option::get_allow_extra_args(), Option::get_expected_max(), Option::get_expected_min(), Option::get_name(), Option::get_type_size_max(), Option::get_type_size_min(), App::remove_option(), Option::type_name(), and Option::type_size().
Referenced by retire_option(), and retire_option().
TriggerOff() [1/2]
void TriggerOff (App * trigger_app, App * app_to_enable) inline
Helper function to disable one option group/subcommand when another is used.
Definition at line 9796 of file CLI11.hpp.
{
        app_to_enable->disabled_by_default(false);
        app_to_enable->enabled_by_default();
        trigger_app->preparse_callback([app_to_enable](std::size_t) {
            app_to_enable->disabled();
        });
    }
References App::disabled(), App::disabled_by_default(), App::enabled_by_default(), and App::preparse_callback().
TriggerOff() [2/2]
void TriggerOff (App * trigger_app, std::vector< App * > apps_to_enable) inline
Helper function to disable one option group/subcommand when another is used.
Definition at line 9804 of file CLI11.hpp.
{
        for (auto& app : apps_to_enable) {
            app->disabled_by_default(false);
            app->enabled_by_default();
        }
        trigger_app->preparse_callback([apps_to_enable](std::size_t) {
            for (const auto& app : apps_to_enable) {
                app->disabled();
            }
        });
    }
References App::preparse_callback().
TriggerOn() [1/2]
void TriggerOn (App * trigger_app, App * app_to_enable) inline
Helper function to enable one option group/subcommand when another is used.
Definition at line 9775 of file CLI11.hpp.
{
        app_to_enable->enabled_by_default(false);
        app_to_enable->disabled_by_default();
        trigger_app->preparse_callback([app_to_enable](std::size_t) {
            app_to_enable->disabled(false);
        });
    }
References App::disabled(), App::disabled_by_default(), App::enabled_by_default(), and App::preparse_callback().
TriggerOn() [2/2]
void TriggerOn (App * trigger_app, std::vector< App * > apps_to_enable) inline
Helper function to enable one option group/subcommand when another is used.
Definition at line 9783 of file CLI11.hpp.
{
        for (auto& app : apps_to_enable) {
            app->enabled_by_default(false);
            app->disabled_by_default();
        }
        trigger_app->preparse_callback([apps_to_enable](std::size_t) {
            for (const auto& app : apps_to_enable) {
                app->disabled(false);
            }
        });
    }
References App::preparse_callback().
Variable Documentation
ExistingDirectory
const detail::ExistingDirectoryValidator ExistingDirectory
Check for an existing directory (returns error message if check fails)
Definition at line 3529 of file CLI11.hpp.
ExistingFile
const detail::ExistingFileValidator ExistingFile
Check for existing file (returns error message if check fails)
Definition at line 3526 of file CLI11.hpp.
ExistingPath
const detail::ExistingPathValidator ExistingPath
Check for an existing path.
Definition at line 3532 of file CLI11.hpp.
NonexistentPath
const detail::NonexistentPathValidator NonexistentPath
Check for an non-existing path.
Definition at line 3535 of file CLI11.hpp.
NonNegativeNumber
const Range NonNegativeNumber((std::numeric_limits< double >::max)(), "NONNEGATIVE") ((std::numeric_limits< double >::max)() , "NONNEGATIVE")
Check for a non negative number.
Number
const TypeValidator< double > Number("NUMBER") ("NUMBER")
Check for a number.
PositiveNumber
const Range PositiveNumber((std::numeric_limits< double >::min)(),(std::numeric_limits< double >::max)(), "POSITIVE") ((std::numeric_limits< double >::min)() , (std::numeric_limits< double >::max)() , "POSITIVE")
Check for a positive valued number (val>0.0), <double>min here is the smallest positive number.
ValidIPV4
const detail::IPV4Validator ValidIPV4
Check for an IP4 address.
Definition at line 3538 of file CLI11.hpp.