SNode.C: apps/http/httplowlevelclient.cpp File Reference
httplowlevelclient.cpp File Reference
#include "core/SNodeC.h"
#include "core/socket/stream/SocketContext.h"
#include "core/socket/stream/SocketContextFactory.h"
#include "net/in/stream/legacy/SocketClient.h"
Classes
class SimpleSocketProtocol
class SimpleSocketProtocolFactory
Namespaces
namespace tls
namespace legacy
Typedefs
using tls::SocketClient = net::in::stream::tls::SocketClient< SimpleSocketProtocolFactory >
using tls::SocketAddress = SocketClient::SocketAddress
using tls::SocketConnection = SocketClient::SocketConnection
using legacy::SocketClient = net::in::stream::legacy::SocketClient< SimpleSocketProtocolFactory >
using legacy::SocketAddress = SocketClient::SocketAddress
using legacy::SocketConnection = SocketClient::SocketConnection
Functions
static web::http::client::ResponseParser * getResponseParser (core::socket::stream::SocketContext *socketContext)
SocketClient tls::getClient ()
SocketClient legacy::getLegacyClient ()
int main (int argc, char *argv[])
Function Documentation
getResponseParser()
static web::http::client::ResponseParser * getResponseParser (core::socket::stream::SocketContext * socketContext) static
Definition at line 50 of file httplowlevelclient.cpp.
{
    web::http::client::ResponseParser* responseParser = new web::http::client::ResponseParser(
        socketContext,
        []() -> void {
        },
        [](const std::string& httpVersion, const std::string& statusCode, const std::string& reason) -> void {
            VLOG(0) << "++ Response: " << httpVersion << " " << statusCode << " " << reason;
        },
        [](const std::map<std::string, std::string>& headers, const std::map<std::string, web::http::CookieOptions>& cookies) -> void {
            VLOG(0) << "++   Headers:";
            for (const auto& [field, value] : headers) {
                VLOG(0) << "++       " << field + " = " + value;
            }
            VLOG(0) << "++   Cookies:";
            for (const auto& [name, cookie] : cookies) {
                VLOG(0) << "++     " + name + " = " + cookie.getValue();
                for (const auto& [option, value] : cookie.getOptions()) {
                    VLOG(0) << "++       " + option + " = " + value;
                }
            }
        },
        [](std::vector<uint8_t> content) -> void {
            content.push_back(0);
            VLOG(0) << "++   OnContent: "; // << content.data();
        },
        [](web::http::client::ResponseParser& parser) -> void {
            VLOG(0) << "++   OnParsed";
            parser.reset();
        },
        [](int status, const std::string& reason) -> void {
            VLOG(0) << "++   OnError: " + std::to_string(status) + " - " + reason;
        });
    return responseParser;
}
References web::http::CookieOptions::getOptions(), web::http::CookieOptions::getValue(), web::http::client::ResponseParser::reset(), and web::http::client::ResponseParser::ResponseParser().
Referenced by SimpleSocketProtocol::SimpleSocketProtocol().
main()
int main (int argc, char * argv[])
Definition at line 340 of file httplowlevelclient.cpp.
{
    core::SNodeC::init(argc, argv);
    {
        const legacy::SocketAddress legacyRemoteAddress("localhost", 8080);
        const legacy::SocketClient legacyClient = legacy::getLegacyClient();
        legacyClient.connect(legacyRemoteAddress,
                             [instanceName = legacyClient.getConfig().getInstanceName()](
                                 const tls::SocketAddress& socketAddress,
                                 const core::socket::State& state) -> void { // example.com:81 simulate connnect timeout
                                 switch (state) {
                                     case core::socket::State::OK:
                                         VLOG(1) << instanceName << ": connected to '" << socketAddress.toString() << "'";
                                         break;
                                     case core::socket::State::DISABLED:
                                         VLOG(1) << instanceName << ": disabled";
                                         break;
                                     case core::socket::State::ERROR:
                                         LOG(ERROR) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                                         break;
                                     case core::socket::State::FATAL:
                                         LOG(FATAL) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                                         break;
                                 }
                             });
        const tls::SocketAddress tlsRemoteAddress = tls::SocketAddress("localhost", 8088);
        const tls::SocketClient tlsClient = tls::getClient();
        tlsClient.connect(tlsRemoteAddress,
                          [instanceName = tlsClient.getConfig().getInstanceName()](
                              const tls::SocketAddress& socketAddress,
                              const core::socket::State& state) -> void { // example.com:81 simulate connnect timeout
                              switch (state) {
                                  case core::socket::State::OK:
                                      VLOG(1) << instanceName << ": connected to '" << socketAddress.toString() << "'";
                                      break;
                                  case core::socket::State::DISABLED:
                                      VLOG(1) << instanceName << ": disabled";
                                      break;
                                  case core::socket::State::ERROR:
                                      LOG(ERROR) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                                      break;
                                  case core::socket::State::FATAL:
                                      LOG(FATAL) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                                      break;
                              }
                          });
    }
    return core::SNodeC::start();
}
References tls::getClient(), legacy::getLegacyClient(), core::SNodeC::init(), and core::SNodeC::start().