@startuml inline_umlgraph_1.svg
!include core/socket/stream/pu/SocketClient.pu
@enduml
@startuml inline_umlgraph_2.svg
!include web/http/server/pu/response_upgrade.pu
@enduml
@startuml inline_umlgraph_3.svg
!include core/socket/stream/pu/SocketClient.pu
@enduml
@startuml inline_umlgraph_4.svg
!include core/socket/stream/pu/SocketClient.pu
@enduml
@startuml inline_umlgraph_5.svg
!include core/socket/stream/pu/SocketClient.pu
@enduml
@startuml inline_umlgraph_6.svg
!include core/socket/stream/pu/SocketClient.pu
@enduml
@startuml inline_umlgraph_7.svg
!include core/socket/stream/pu/SocketClient.pu
@enduml
@startuml inline_umlgraph_8.svg
!include web/http/server/pu/response_upgrade.pu
@enduml
