SNode.C: apps/jsonserver.cpp File Reference
jsonserver.cpp File Reference
#include "express/legacy/in/WebApp.h"
#include "express/middleware/JsonMiddleware.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 56 of file jsonserver.cpp.
{
    using WebApp = express::legacy::in::WebApp;
    WebApp::init(argc, argv);
    using SocketAddress = WebApp::SocketAddress;
    const WebApp legacyApp("legacy-jsonserver");
    legacyApp.use(express::middleware::JsonMiddleware());
    legacyApp.listen(
        8080,
        [instanceName = legacyApp.getConfig().getInstanceName()](const SocketAddress& socketAddress, const core::socket::State& state) {
            switch (state) {
                case core::socket::State::OK:
                    VLOG(1) << instanceName << ": listening on '" << socketAddress.toString() << "'";
                    break;
                case core::socket::State::DISABLED:
                    VLOG(1) << instanceName << ": disabled";
                    break;
                case core::socket::State::ERROR:
                    LOG(ERROR) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                    break;
                case core::socket::State::FATAL:
                    LOG(FATAL) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                    break;
            }
        });
    legacyApp.post("/index.html", [] APPLICATION(req, res) {
        std::string jsonString;
        req->getAttribute<nlohmann::json>(
            [&jsonString](nlohmann::json& json) {
                jsonString = json.dump(4);
                VLOG(1) << "Application received body: " << jsonString;
            },
            [](const std::string& key) {
                VLOG(1) << key << " attribute not found";
            });
        res->send(jsonString);
    });
    legacyApp.post([] APPLICATION(req, res) {
        res->send("Wrong Url");
    });
    return WebApp::start();
}
References core::socket::State::DISABLED, core::socket::State::ERROR, core::socket::State::FATAL, utils::MultibleAttributeInjector::getAttribute(), core::socket::Socket< ConfigT >::getConfig(), net::config::ConfigInstance::getInstanceName(), express::WebApp::init(), net::in::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT, Args >::listen(), core::socket::State::OK, express::Response::send(), express::WebApp::start(), net::in::SocketAddress::toString(), express::WebAppT< ServerT >::WebAppT(), and core::socket::State::what().