SNode.C: apps/jsonclient.cpp File Reference
jsonclient.cpp File Reference
#include "core/SNodeC.h"
#include "web/http/legacy/in/Client.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 53 of file jsonclient.cpp.
{
    core::SNodeC::init(argc, argv);
    using Client = web::http::legacy::in::Client;
    using MasterRequest = Client::MasterRequest;
    using Request = Client::Request;
    using Response = Client::Response;
    using SocketAddress = Client::SocketAddress;
    const Client jsonClient(
        "legacy",
        [](const std::shared_ptr<MasterRequest>& req) {
            VLOG(1) << "-- OnRequest";
            req->method = "POST";
            req->url = "/index.html";
            req->type("application/json");
            req->set("Connection", "close");
            req->send(
                "{\"userId\":1,\"schnitzel\":\"good\",\"hungry\":false}",
                []([[maybe_unused]] const std::shared_ptr<Request>& req, const std::shared_ptr<Response>& res) {
                    VLOG(1) << "-- OnResponse";
                    VLOG(1) << "     Status:";
                    VLOG(1) << "       " << res->httpVersion;
                    VLOG(1) << "       " << res->statusCode;
                    VLOG(1) << "       " << res->reason;
                    VLOG(1) << "     Headers:";
                    for (const auto& [field, value] : res->headers) {
                        VLOG(1) << "       " << field + " = " + value;
                    }
                    VLOG(1) << "     Cookies:";
                    for (const auto& [name, cookie] : res->cookies) {
                        VLOG(1) << "       " + name + " = " + cookie.getValue();
                        for (const auto& [option, value] : cookie.getOptions()) {
                            VLOG(1) << "         " + option + " = " + value;
                        }
                    }
                    res->body.push_back(0);
                    VLOG(1) << "     Body:\n----------- start body -----------" << res->body.data() << "------------ end body ------------";
                },
                [](const std::shared_ptr<Request>&, const std::string& message) {
                    VLOG(1) << "legacy: Request parse error: " << message;
                });
        },
        []([[maybe_unused]] const std::shared_ptr<MasterRequest>& req) {
            LOG(INFO) << " -- OnRequestEnd";
        });
    jsonClient.connect("localhost",
                       8080,
                       [instanceName = jsonClient.getConfig().getInstanceName()](
                           const SocketAddress& socketAddress,
                           const core::socket::State& state) { // example.com:81 simulate connect timeout
                           switch (state) {
                               case core::socket::State::OK:
                                   VLOG(1) << instanceName << ": connected to '" << socketAddress.toString() << "'";
                                   break;
                               case core::socket::State::DISABLED:
                                   VLOG(1) << instanceName << ": disabled";
                                   break;
                               case core::socket::State::ERROR:
                                   LOG(ERROR) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                                   break;
                               case core::socket::State::FATAL:
                                   LOG(FATAL) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                                   break;
                           }
                       });
    /*
        jsonClient.connect("localhost",
                           8080,
                           [instanceName = jsonClient.getConfig().getInstanceName()](
                               const SocketAddress& socketAddress,
                               const core::socket::State& state) { // example.com:81 simulate connnect timeout
                               switch (state) {
                                   case core::socket::State::OK:
                                       VLOG(1) << instanceName << ": connected to '" << socketAddress.toString() << "'";
                                       break;
                                   case core::socket::State::DISABLED:
                                       VLOG(1) << instanceName << ": disabled";
                                       break;
                                   case core::socket::State::ERROR:
                                       LOG(ERROR) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                                       break;
                                   case core::socket::State::FATAL:
                                       LOG(FATAL) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                                       break;
                               }
                           });
    */
    /*
        jsonClient.post("localhost", 8080, "/index.html", "{\"userId\":1,\"schnitzel\":\"good\",\"hungry\":false}", [](int err) {
            if (err != 0) {
                PLOG(ERROR) << "OnError: " << err;
            }
        });
    */
    return core::SNodeC::start();
}
References web::http::client::Response::body, web::http::client::Client< SocketClientT >::Client(), net::in::stream::SocketClient< SocketConnectorT, ConfigSocketClientT, SocketContextFactoryT, Args >::connect(), web::http::client::Response::cookies, core::socket::State::DISABLED, core::socket::State::ERROR, core::socket::State::FATAL, core::socket::Socket< ConfigT >::getConfig(), net::config::ConfigInstance::getInstanceName(), web::http::CookieOptions::getOptions(), web::http::CookieOptions::getValue(), web::http::client::Response::headers, web::http::client::Response::httpVersion, core::SNodeC::init(), web::http::client::Request::method, core::socket::State::OK, web::http::client::Response::reason, web::http::client::MasterRequest::send(), web::http::client::Request::set(), core::SNodeC::start(), web::http::client::Response::statusCode, net::in::SocketAddress::toString(), web::http::client::Request::type(), web::http::client::Request::url, and core::socket::State::what().