SNode.C: web::http Namespace Reference
web::http Namespace Reference
Namespaces
namespace client
namespace decoder
namespace legacy
namespace server
namespace tls
Classes
struct ciLess
class CiStringMap
class ContentDecoder
class CookieOptions
class MimeTypes
class Parser
class SocketContextFactory
class SocketContextUpgrade
class SocketContextUpgradeFactory
class SocketContextUpgradeFactorySelector
class StatusCode
Enumerations
enum ConnectionState { Default , Keep , Close }
enum struct TransferEncoding {
HTTP10 , Identity , Chunked , Compressed ,
GZip , Deflat
}
Functions
bool ciContains (const std::string &str1, const std::string &str2)
bool ciEquals (const std::string &str1, const std::string &str2)
enum Parser::HTTPCompliance operator| (const enum Parser::HTTPCompliance &c1, const enum Parser::HTTPCompliance &c2)
enum Parser::HTTPCompliance operator& (const enum Parser::HTTPCompliance &c1, const enum Parser::HTTPCompliance &c2)
Enumeration Type Documentation
ConnectionState
enum web::http::ConnectionState
Enumerator
Default
Keep
Close
Definition at line 29 of file ConnectionState.h.
{ Default, Keep, Close };
TransferEncoding
enum struct web::http::TransferEncoding strong
Enumerator
HTTP10
Identity
Chunked
Compressed
GZip
Deflat
Definition at line 28 of file TransferEncoding.h.
{ HTTP10, Identity, Chunked, Compressed, GZip, Deflat };
Function Documentation
ciContains()
bool web::http::ciContains (const std::string & str1, const std::string & str2)
Definition at line 31 of file CiStringMap.cpp.
{
        auto it = std::search(str1.begin(), str1.end(), str2.begin(), str2.end(), [](char ch1, char ch2) {
            return std::tolower(ch1) == std::tolower(ch2);
        });
        return (it != str1.end());
    }
Referenced by web::http::client::ResponseParser::analyzeHeader(), web::http::Parser::analyzeHeader(), and web::http::server::RequestParser::analyzeHeader().
ciEquals()
bool web::http::ciEquals (const std::string & str1, const std::string & str2)
Definition at line 39 of file CiStringMap.cpp.
{
        return std::equal(str1.begin(), str1.end(), str2.begin(), str2.end(), [](char ch1, char ch2) {
            return std::tolower(ch1) == std::tolower(ch2);
        });
    }
operator&()
enum Parser::HTTPCompliance web::http::operator& (const enum Parser::HTTPCompliance & c1, const enum Parser::HTTPCompliance & c2)
Definition at line 238 of file Parser.cpp.
{
        return static_cast<enum Parser::HTTPCompliance>(static_cast<unsigned short>(c1) & static_cast<unsigned short>(c2));
    }
operator|()
enum Parser::HTTPCompliance web::http::operator| (const enum Parser::HTTPCompliance & c1, const enum Parser::HTTPCompliance & c2)
Definition at line 234 of file Parser.cpp.
{
        return static_cast<enum Parser::HTTPCompliance>(static_cast<unsigned short>(c1) | static_cast<unsigned short>(c2));
    }