SNode.C: core Namespace Reference
core Namespace Reference
Namespaces
namespace timer
namespace socket
namespace pipe
namespace eventreceiver
namespace file
namespace multiplexer
namespace ssl
namespace system
Classes
class SNodeC
class Descriptor
class DescriptorEventPublisher
class Observer
class DescriptorEventReceiver
class Event
class EventLoop
class EventMultiplexer
class EventReceiver
class DynamicLoader
class TimerEventPublisher
class Timer
class TimerEventReceiver
Enumerations
enum class State { LOADED , INITIALIZED , RUNNING , STOPPING }
enum class TickStatus { SUCCESS , INTERRUPTED , NOOBSERVER , TRACE }
Functions
static std::string getTickCounterAsString (const el::LogMessage *logMessage)
State eventLoopState ()
Enumeration Type Documentation
State
enum class core::State strong
Enumerator
LOADED
INITIALIZED
RUNNING
STOPPING
Definition at line 51 of file State.h.
{ LOADED, INITIALIZED, RUNNING, STOPPING };
TickStatus
enum class core::TickStatus strong
Enumerator
SUCCESS
INTERRUPTED
NOOBSERVER
TRACE
Definition at line 51 of file TickStatus.h.
{ SUCCESS, INTERRUPTED, NOOBSERVER, TRACE };
Function Documentation
eventLoopState()
State core::eventLoopState ()
Definition at line 52 of file State.cpp.
{
        return EventLoop::getEventLoopState();
    }
References core::EventLoop::getEventLoopState().
Referenced by core::TimerEventReceiver::enable(), core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::init(), core::socket::stream::tls::SocketConnector< PhysicalSocketClientT, ConfigT >::init(), core::file::FileReader::onEvent(), core::socket::stream::SocketClient< SocketConnectorT< net::in6::phy::stream::PhysicalSocketClient, ConfigSocketClientT >, SocketContextFactoryT, Args... >::realConnect(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketAcceptor< PhysicalSocketServerT, ConfigT, SocketConnectionT >::SocketAcceptor(), core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector(), and core::socket::stream::SocketConnector< PhysicalSocketClientT, ConfigT, SocketConnectionT >::SocketConnector().
getTickCounterAsString()
std::string core::getTickCounterAsString (const el::LogMessage * logMessage) static
Definition at line 65 of file EventLoop.cpp.
{
        std::string tick = std::to_string(EventLoop::getTickCounter());
        if (tick.length() < 13) {
            tick.insert(0, 13 - tick.length(), '0');
        }
        return tick;
    }
References core::EventLoop::getTickCounter().
Referenced by core::EventLoop::init().