SNode.C: utils Namespace Reference
utils Namespace Reference
Namespaces
namespace config
namespace CallForCommandline
namespace system
Classes
class ConfigRoot
class Config
class AppWithPtr
class SubCommand
class Uuid
class Timeval
class DaemonFailure
class DaemonError
class DaemonSignaled
class Daemon
class PreserveErrno
class Random
struct fixed_string
class AttributeProxy
class SingleAttributeInjector
class MultibleAttributeInjector
class SHA1
Concepts
concept InjectableAttribute
Functions
static std::string bash_backslash_escape_no_whitespace (std::string_view s)
static void createCommandLineOptions (std::stringstream &out, CLI::App *app, utils::CallForCommandline::Mode mode)
static std::string createCommandLineOptions (CLI::App *app, utils::CallForCommandline::Mode mode)
static void createCommandLineTemplate (std::stringstream &out, CLI::App *app, utils::CallForCommandline::Mode mode)
static std::string createCommandLineSubcommands (CLI::App *app, utils::CallForCommandline::Mode mode)
static std::string createCommandLineTemplate (CLI::App *app, utils::CallForCommandline::Mode mode)
static std::string getCommandLine (CLI::App *commandlineTriggerApp)
static std::string getConfig (CLI::App *configTriggeredApp)
static std::string doWriteConfig (utils::SubCommand *subCommand)
static std::string getHelp (utils::SubCommand *subCommand, CLI::App *helpTriggerApp)
std::string hexDump (const std::vector< char > &bytes, int prefixLength, bool prefixAtFirstLine)
std::string hexDump (const std::string &string, int prefixLength, bool prefixAtFirstLine)
std::string hexDump (const char *bytes, uint64_t length, int prefixLength, bool prefixAtFirstLine)
static std::vector< unsigned char > transform_to_binary (const std::string &string)
std::vector< unsigned char > sha1 (const std::string &string)
static std::shared_ptr< CLI::HelpFormatter > makeSectionFormatter ()
std::ostream & operator<< (std::ostream &ostream, const utils::Timeval &timeVal)
Timeval operator* (double mul, const utils::Timeval &timeVal)
template<unsigned N>
fixed_string (char const (&)[N]) -> fixed_string< N - 1 >
Function Documentation
bash_backslash_escape_no_whitespace()
std::string utils::bash_backslash_escape_no_whitespace (std::string_view s) static
Definition at line 81 of file Config.cpp.
{
        static const std::unordered_set<char> special{
            '\\', '\'',                                    // quoting/escape
            '`',  '$',                                     // substitution
            '|',  '&',  ';', '<', '>', '(', ')', '{', '}', // operators
            '*',  '?',  '[', ']', '~', '!', '#', '='       // globbing/history/others
        };
        std::string out;
        out.reserve(s.size() * 3);
        for (const char c : s) {
            if (special.contains(c)) {
                out.push_back('\\');
            }
            out.push_back(c);
        }
        return out;
    }
Referenced by createCommandLineOptions().
createCommandLineOptions() [1/2]
std::string utils::createCommandLineOptions (CLI::App * app, utils::CallForCommandline::Mode mode) static
Definition at line 181 of file Config.cpp.
{
        std::stringstream out;
        createCommandLineOptions(out, app, mode);
        std::string optionString = out.str();
        if (!optionString.empty() && optionString.back() == ' ') {
            optionString.pop_back();
        }
        return optionString;
    }
References createCommandLineOptions().
Referenced by createCommandLineTemplate(), and createCommandLineTemplate().
createCommandLineOptions() [2/2]
void utils::createCommandLineOptions (std::stringstream & out, CLI::App * app, utils::CallForCommandline::Mode mode) static
Definition at line 101 of file Config.cpp.
{
        const CLI::Option* disabledOpt = app->get_option_no_throw("--disabled");
        const bool disabled = disabledOpt != nullptr ? disabledOpt->as<bool>() : false;
        if (!disabled || mode == utils::CallForCommandline::Mode::COMPLETE) {
            for (const CLI::Option* option : app->get_options()) {
                if (option->get_configurable()) {
                    std::string value;
                    switch (mode) {
                        case utils::CallForCommandline::Mode::STANDARD:
                            if (option->count() > 0) {
                                try {
                                    for (const auto& result : option->reduced_results()) {
                                        value += (!result.empty() ? result : "\"\"") + " ";
                                    }
                                    value.pop_back();
                                } catch (CLI::ParseError& e) {
                                    value = std::string{"<["} + Color::Code::FG_RED + e.get_name() + Color::Code::FG_DEFAULT + "] " +
                                            e.what() + ">";
                                }
                            } else if (option->get_required()) {
                                value = "<REQUIRED>";
                            }
                            break;
                        case utils::CallForCommandline::Mode::REQUIRED:
                            if (option->get_required()) {
                                if (option->count() > 0) {
                                    try {
                                        for (const auto& result : option->reduced_results()) {
                                            value += (!result.empty() ? result : "\"\"") + " ";
                                        }
                                        value.pop_back();
                                    } catch (CLI::ParseError& e) {
                                        value = std::string{"<["} + Color::Code::FG_RED + e.get_name() + Color::Code::FG_DEFAULT + "] " +
                                                e.what() + ">";
                                    }
                                } else {
                                    value = "<REQUIRED>";
                                }
                            }
                            break;
                        case utils::CallForCommandline::Mode::ACTIVE:
                        case utils::CallForCommandline::Mode::COMPLETE:
                            if (option->count() > 0) {
                                try {
                                    for (const auto& result : option->reduced_results()) {
                                        value += (!result.empty() ? result : "\"\"") + " ";
                                    }
                                    value.pop_back();
                                } catch (CLI::ParseError& e) {
                                    value = std::string{"<["} + Color::Code::FG_RED + e.get_name() + Color::Code::FG_DEFAULT + "] " +
                                            e.what() + ">";
                                }
                            } else if (!option->get_default_str().empty()) {
                                value = option->get_default_str();
                            } else if (!option->get_required()) {
                                value = "\"\"";
                            } else {
                                value = "<REQUIRED>";
                            }
                            break;
                    }
                    if (!value.empty()) {
                        if (value.starts_with(std::string{"["}) && value.ends_with("]")) {
                            value = value.substr(1, value.size() - 2);
                        }
                        if (value != "<REQUIRED>" && value != "\"\"" && !value.starts_with("<[")) {
                            value = bash_backslash_escape_no_whitespace(value);
                        }
                        out << "--" << option->get_single_name() << ((option->get_items_expected_max() == 0) ? "=" : " ") << value << " ";
                    }
                }
            }
        } else if (disabledOpt->get_default_str() == "false") {
            out << "--disabled=true ";
        }
    }
References utils::CallForCommandline::ACTIVE, bash_backslash_escape_no_whitespace(), utils::CallForCommandline::COMPLETE, Color::FG_DEFAULT, Color::FG_RED, Color::operator+(), utils::CallForCommandline::REQUIRED, and utils::CallForCommandline::STANDARD.
Referenced by createCommandLineOptions().
createCommandLineSubcommands()
std::string utils::createCommandLineSubcommands (CLI::App * app, utils::CallForCommandline::Mode mode) static
Definition at line 196 of file Config.cpp.
{
        std::stringstream out;
        const CLI::Option* disabledOpt = app->get_option_no_throw("--disabled");
        if (disabledOpt == nullptr || !disabledOpt->as<bool>() || mode == utils::CallForCommandline::Mode::COMPLETE) {
            for (CLI::App* subcommand : app->get_subcommands({})) {
                if (!subcommand->get_name().empty()) {
                    createCommandLineTemplate(out, subcommand, mode);
                }
            }
        }
        return out.str();
    }
References utils::CallForCommandline::COMPLETE, and createCommandLineTemplate().
Referenced by createCommandLineTemplate().
createCommandLineTemplate() [1/2]
std::string utils::createCommandLineTemplate (CLI::App * app, utils::CallForCommandline::Mode mode) static
Definition at line 226 of file Config.cpp.
{
        std::stringstream out;
        createCommandLineTemplate(out, app, mode);
        std::string outString = out.str();
        while (app->get_parent() != nullptr) {
            app = app->get_parent();
            std::string parentOptions = createCommandLineOptions(app, mode);
            outString =
                std::string(app->get_name()).append(" ").append(!parentOptions.empty() ? parentOptions.append(" ") : "").append(outString);
        }
        if (outString.empty()) {
            outString = Config::getApplicationName();
        }
        return outString;
    }
References createCommandLineOptions(), createCommandLineTemplate(), and utils::Config::getApplicationName().
Referenced by getCommandLine().
createCommandLineTemplate() [2/2]
void utils::createCommandLineTemplate (std::stringstream & out, CLI::App * app, utils::CallForCommandline::Mode mode) static
Definition at line 211 of file Config.cpp.
{
        std::string outString;
        outString = createCommandLineOptions(app, mode);
        if (!outString.empty()) {
            outString += " ";
        }
        outString += createCommandLineSubcommands(app, mode);
        if (!outString.empty()) {
            out << app->get_name() << " " << outString;
        }
    }
References createCommandLineOptions(), and createCommandLineSubcommands().
Referenced by createCommandLineSubcommands(), and createCommandLineTemplate().
doWriteConfig()
std::string utils::doWriteConfig (utils::SubCommand * subCommand) static
Definition at line 304 of file Config.cpp.
{
        std::stringstream out;
        VLOG(0) << "1: subCommand->getOption(--write-config)->as<std::string>()";
        std::ofstream confFile(subCommand->getOption("--write-config")->as<std::string>());
        if (confFile.is_open()) {
            VLOG(0) << "2: subCommand->getOption(--write-config)->as<std::string>()";
            VLOG(0) << subCommand->configToStr();
            try {
                confFile << subCommand->configToStr();
                confFile.close();
                out << std::string{"["} << Color::Code::FG_GREEN << "SUCCESS" << Color::Code::FG_DEFAULT
                    << "] Writing config file: " + subCommand->getOption("--write-config")->as<std::string>() << std::endl
                    << std::endl;
            } catch (const CLI::ParseError& e) {
                confFile.close();
                out << std::string{"["} << Color::Code::FG_RED << "Error" << Color::Code::FG_DEFAULT
                    << "] Writing config file: " << e.get_name() << " " << e.what() << std::endl;
            }
            confFile.close();
        } else {
            out << std::string{"["} << Color::Code::FG_RED << "Error" << Color::Code::FG_DEFAULT
                << "] Writing config file: " << std::strerror(errno) << std::endl;
        }
        return out.str();
    }
References utils::SubCommand::configToStr(), Color::FG_DEFAULT, Color::FG_GREEN, Color::FG_RED, and utils::SubCommand::getOption().
Referenced by utils::ConfigRoot::parse2().
fixed_string()
template<unsigned N> utils::fixed_string (char const(&)[N]) ->fixed_string< N-1 >
getCommandLine()
std::string utils::getCommandLine (CLI::App * commandlineTriggerApp) static
Definition at line 246 of file Config.cpp.
{
        const std::string modeString = commandlineTriggerApp->get_option("--command-line")->as<std::string>();
        utils::CallForCommandline::Mode mode = utils::CallForCommandline::Mode::STANDARD;
        std::ostringstream out;
        if (modeString == "standard") {
            out << "Below is a command line viewing all non-default and required options:\n"
                   "* Options show their configured value\n"
                   "* Required but not yet configured options show <REQUIRED> as value\n"
                   "* Options marked as <REQUIRED> need to be configured for a successful bootstrap"
                << std::endl;
            mode = utils::CallForCommandline::Mode::STANDARD;
        } else if (modeString == "active") {
            out << "Below is a command line viewing the active set of options with their default or configured values:\n"
                   "* Options show either their configured or default value\n"
                   "* Required but not yet configured options show <REQUIRED> as value\n"
                   "* Options marked as <REQUIRED> need to be configured for a successful bootstrap"
                << std::endl;
            mode = utils::CallForCommandline::Mode::ACTIVE;
        } else if (modeString == "complete") {
            out << "Below is a command line viewing the complete set of options with their default values\n"
                   "* Options show their default value\n"
                   "* Required but not yet configured options show <REQUIRED> as value\n"
                   "* Options marked as <REQUIRED> need to be configured for a successful bootstrap"
                << std::endl;
            mode = utils::CallForCommandline::Mode::COMPLETE;
        } else if (modeString == "required") {
            out << "Below is a command line viewing required options only:\n"
                   "* Options show either their configured or default value\n"
                   "* Required but not yet configured options show <REQUIRED> as value\n"
                   "* Options marked as <REQUIRED> need to be configured for a successful bootstrap"
                << std::endl;
            mode = utils::CallForCommandline::Mode::REQUIRED;
        }
        out << std::endl
            << Color::Code::FG_GREEN << "command@line" << Color::Code::FG_DEFAULT << ":" << Color::Code::FG_BLUE << "~/> "
            << Color::Code::FG_DEFAULT << createCommandLineTemplate(commandlineTriggerApp, mode) << std::endl
            << std::endl;
        return out.str();
    }
References utils::CallForCommandline::ACTIVE, utils::CallForCommandline::COMPLETE, createCommandLineTemplate(), Color::FG_BLUE, Color::FG_DEFAULT, Color::FG_GREEN, utils::CallForCommandline::REQUIRED, and utils::CallForCommandline::STANDARD.
Referenced by utils::ConfigRoot::parse2().
getConfig()
std::string utils::getConfig (CLI::App * configTriggeredApp) static
Definition at line 291 of file Config.cpp.
{
        std::stringstream out;
        try {
            out << configTriggeredApp->config_to_str(true, true);
        } catch (const CLI::ParseError& e) {
            out << std::string{"["} << Color::Code::FG_RED << "Error" << Color::Code::FG_DEFAULT
                << "] Showing current config: " << configTriggeredApp->get_name() << " " << e.get_name() << " " << e.what();
        }
        return out.str();
    }
References Color::FG_DEFAULT, and Color::FG_RED.
Referenced by utils::ConfigRoot::parse2().
getHelp()
std::string utils::getHelp (utils::SubCommand * subCommand, CLI::App * helpTriggerApp) static
Definition at line 333 of file Config.cpp.
{
        std::stringstream out;
        const std::string helpMode =
            (helpTriggerApp != nullptr ? helpTriggerApp->get_option("--help") : subCommand->getOption("--help"))->as<std::string>();
        const CLI::App* helpApp = nullptr;
        CLI::AppFormatMode mode = CLI::AppFormatMode::Normal;
        if (helpMode == "exact") {
            helpApp = helpTriggerApp;
        } else if (helpMode == "expanded") {
            helpApp = helpTriggerApp;
            mode = CLI::AppFormatMode::All;
        }
        try {
            out << subCommand->help(helpApp, mode);
        } catch (CLI::ParseError& e) {
            out << std::string{"["} << Color::Code::FG_RED << "Error" << Color::Code::FG_DEFAULT << "] Show help: " << e.get_name() << " "
                << e.what();
        }
        return out.str();
    }
References Color::FG_DEFAULT, Color::FG_RED, utils::SubCommand::getOption(), and utils::SubCommand::help().
Referenced by utils::ConfigRoot::parse2().
hexDump() [1/3]
std::string utils::hexDump (const char * bytes, uint64_t length, int prefixLength = 0, bool prefixAtFirstLine = false)
Definition at line 66 of file hexdump.cpp.
{
        std::stringstream hexStream;
        if (length > 0) {
            uint8_t buff[17];
            size_t i = 0;
            hexStream << std::hex;
            int currentPrefixLength = prefixAtFirstLine ? prefixLength : 0;
            // Process every byte in the data.
            for (i = 0; i < length; i++) {
                // Multiple of 16 means new line (with line offset).
                if ((i % 16) == 0) {
                    // Just don't print ASCII for the zeroth line.
                    if (i != 0) {
                        hexStream << "  " << buff << std::endl;
                    }
                    // Output the offset.
                    hexStream << Color::Code::FG_BLUE;
                    hexStream << std::setw(currentPrefixLength) << std::setfill(' ') << ""
                              << ": " << std::setw(8) << std::setfill('0') << static_cast<unsigned int>(i);
                    hexStream << Color::Code::FG_DEFAULT << " ";
                }
                // Now the hex code for the specific character.
                hexStream << Color::Code::FG_GREEN;
                hexStream << " " << std::setw(2) << std::setfill('0') << static_cast<unsigned int>(static_cast<unsigned char>(bytes[i]));
                hexStream << Color::Code::FG_DEFAULT;
                // And store a printable ASCII character for later.
                if ((bytes[i] < 0x20) || (bytes[i] > 0x7e)) {
                    buff[i % 16] = '.';
                } else {
                    buff[i % 16] = static_cast<uint8_t>(bytes[i]);
                }
                buff[(i % 16) + 1] = '\0';
                currentPrefixLength = prefixLength;
            }
            hexStream << std::dec;
            // Pad out last line if not exactly 16 characters.
            while ((i % 16) != 0) {
                hexStream << "   ";
                i++;
            }
            // And print the final ASCII bit.
            hexStream << "  " << buff;
        }
        return hexStream.str();
    }
References Color::FG_BLUE, Color::FG_DEFAULT, and Color::FG_GREEN.
Referenced by hexDump(), hexDump(), web::websocket::Receiver::readPayload(), and web::websocket::Transmitter::sendFrame().
hexDump() [2/3]
std::string utils::hexDump (const std::string & string, int prefixLength = 0, bool prefixAtFirstLine = false)
Definition at line 62 of file hexdump.cpp.
{
        return hexDump(string.data(), string.length(), prefixLength, prefixAtFirstLine);
    }
References hexDump().
hexDump() [3/3]
std::string utils::hexDump (const std::vector< char > & bytes, int prefixLength = 0, bool prefixAtFirstLine = false)
Definition at line 58 of file hexdump.cpp.
{
        return hexDump(bytes.data(), bytes.size(), prefixLength, prefixAtFirstLine);
    }
References hexDump().
Referenced by iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onMessageData(), iot::mqtt::Mqtt::toHexString(), httputils::toString(), and httputils::toString().
makeSectionFormatter()
std::shared_ptr< CLI::HelpFormatter > utils::makeSectionFormatter () static
Definition at line 350 of file SubCommand.cpp.
{
        const std::shared_ptr<CLI::HelpFormatter> sectionFormatter = std::make_shared<CLI::HelpFormatter>();
        sectionFormatter->label("SUBCOMMAND", "SECTION");
        sectionFormatter->label("SUBCOMMANDS", "SECTIONS");
        sectionFormatter->label("PERSISTENT", "");
        sectionFormatter->label("Persistent Options", "Options (persistent)");
        sectionFormatter->label("Nonpersistent Options", "Options (nonpersistent)");
        sectionFormatter->label("Usage", "\nUsage");
        sectionFormatter->label("bool:{true,false}", "{true,false}");
        sectionFormatter->label(":{standard,active,complete,required}", "{standard,active,complete,required}");
        sectionFormatter->label(":{standard,exact,expanded}", "{standard,exact,expanded}");
        sectionFormatter->column_width(7);
        return sectionFormatter;
    }
operator*()
Timeval utils::operator* (double mul, const utils::Timeval & timeVal)
Definition at line 223 of file Timeval.cpp.
{
        utils::Timeval help;
        help.timeVal.tv_sec = static_cast<time_t>(static_cast<double>(timeVal.timeVal.tv_sec) * mul);
        help.timeVal.tv_usec = static_cast<suseconds_t>(static_cast<double>(timeVal.timeVal.tv_usec) * mul);
        return help.normalize();
    }
operator<<()
std::ostream & utils::operator<< (std::ostream & ostream, const utils::Timeval & timeVal)
Definition at line 218 of file Timeval.cpp.
{
        return ostream << std::string("{") + std::to_string(timeVal.timeVal.tv_sec) + std::string(":") +
                              std::to_string(timeVal.timeVal.tv_usec) + std::string("}");
    }
sha1()
std::vector< unsigned char > utils::sha1 (const std::string & string)
Definition at line 267 of file sha1.cpp.
{
        SHA1 checksum;
        checksum.update(string);
        return transform_to_binary(checksum.final());
    }
References utils::SHA1::final(), transform_to_binary(), and utils::SHA1::update().
Referenced by base64::serverWebSocketKey().
transform_to_binary()
std::vector< unsigned char > utils::transform_to_binary (const std::string & string) static
Definition at line 251 of file sha1.cpp.
{
        std::vector<unsigned char> buf;
        char hex_byte[3];
        hex_byte[2] = 0;
        for (std::size_t i = 0, j = 0; i < string.size(); i += 2, j += 1) {
            hex_byte[0] = string.at(i);
            hex_byte[1] = string.at(i + 1);
            char* end_ptr = nullptr;
            buf.push_back(static_cast<unsigned char>(strtoul(hex_byte, &end_ptr, 16)));
        }
        return buf;
    }
Referenced by sha1().