SNode.C: utils::system Namespace Reference
utils::system Namespace Reference
Functions
sighandler_t signal (int sig, sighandler_t handler)
std::string sigabbrev_np (int sig)
time_t time (time_t *tloc)
int gettimeofday (struct timeval *tv, struct timezone *tz)
struct tm * gmtime (const time_t *timep)
time_t mktime (struct tm *tm)
Function Documentation
gettimeofday()
int utils::system::gettimeofday (struct timeval * tv, struct timezone * tz)
Definition at line 57 of file time.cpp.
{
        errno = 0;
        return ::gettimeofday(tv, tz);
    }
Referenced by utils::Timeval::currentTime().
gmtime()
struct tm * utils::system::gmtime (const time_t * timep)
Definition at line 62 of file time.cpp.
{
        errno = 0;
        return ::gmtime(timep);
    }
Referenced by web::http::server::Response::clearCookie(), and httputils::to_http_date().
mktime()
time_t utils::system::mktime (struct tm * tm)
Definition at line 67 of file time.cpp.
{
        errno = 0;
        return ::mktime(tm);
    }
sigabbrev_np()
std::string utils::system::sigabbrev_np (int sig)
Definition at line 59 of file signal.cpp.
{
        static std::map<int, std::string> sigMap = {
            {SIGABRT, "ABRT"}, {SIGALRM, "ALRM"},     {SIGBUS, "BUS"},   {SIGCHLD, "CHLD"}, {SIGCONT, "CONT"},  {SIGFPE, "FPE"},
            {SIGHUP, "HUP"},   {SIGILL, "ILL"},       {SIGINT, "INT"},   {SIGKILL, "KILL"}, {SIGPIPE, "PIPE"},  {SIGPOLL, "POLL"},
            {SIGPROF, "PROF"}, {SIGQUIT, "QUIT"},     {SIGSEGV, "SEGV"}, {SIGSTOP, "STOP"}, {SIGSYS, "SYS"},    {SIGTERM, "TERM"},
            {SIGTRAP, "TRAP"}, {SIGTSTP, "TSTP"},     {SIGTTIN, "TTIN"}, {SIGTTOU, "TTOU"}, {SIGUSR1, "USR1"},  {SIGUSR2, "USR2"},
            {SIGURG, "URG"},   {SIGVTALRM, "VTALRM"}, {SIGXCPU, "XCPU"}, {SIGXFSZ, "XFSZ"}, {SIGWINCH, "WINCH"}};
        return sigMap.contains(sig) ? sigMap[sig] : "UNKNOWN";
    }
Referenced by core::EventLoop::free(), apps::websocket::subprotocol::echo::client::Echo::onSignal(), apps::websocket::subprotocol::echo::server::Echo::onSignal(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::onSignal(), iot::mqtt::SubProtocol< WSSubProtocolRoleT >::onSignal(), and core::EventLoop::stoponsig().
signal()
sighandler_t utils::system::signal (int sig, sighandler_t handler)
Definition at line 54 of file signal.cpp.
{
        errno = 0;
        return std::signal(sig, handler);
    }
time()
time_t utils::system::time (time_t * tloc)
Definition at line 52 of file time.cpp.
{
        errno = 0;
        return ::time(tloc);
    }
Referenced by httputils::to_http_date().