SNode.C: web::http::legacy::in Namespace Reference
web::http::legacy::in Namespace Reference
Classes
class EventSource
Typedefs
using Client = web::http::client::Client< net::in::stream::legacy::SocketClient >
using Server = web::http::server::Server< net::in::stream::legacy::SocketServer >
Functions
std::shared_ptr< web::http::client::tools::EventSource > EventSource (const std::string &scheme, const net::in::SocketAddress &socketAddress, const std::string &path)
std::shared_ptr< web::http::client::tools::EventSource > EventSource (const std::string &host, uint16_t port, const std::string &path)
std::shared_ptr< web::http::client::tools::EventSource > EventSource (const std::string &url)
std::shared_ptr< web::http::client::tools::EventSource > EventSource (std::string origin, std::string path)
Typedef Documentation
Client
using web::http::legacy::in::Client = typedef web::http::client::Client<net::in::stream::legacy::SocketClient>
Definition at line 54 of file Client.h.
Server
using web::http::legacy::in::Server = typedef web::http::server::Server<net::in::stream::legacy::SocketServer>
Definition at line 55 of file Server.h.
Function Documentation
EventSource() [1/4]
std::shared_ptr< web::http::client::tools::EventSource > web::http::legacy::in::EventSource (const std::string & host, uint16_t port, const std::string & path) inline
Definition at line 82 of file EventSource.h.
{
        return EventSource("http", net::in::SocketAddress(host, port), path);
    }
References EventSource(), and net::in::SocketAddress::SocketAddress().
EventSource() [2/4]
std::shared_ptr< web::http::client::tools::EventSource > web::http::legacy::in::EventSource (const std::string & scheme, const net::in::SocketAddress & socketAddress, const std::string & path) inline
Definition at line 74 of file EventSource.h.
{
        std::shared_ptr<class EventSource> eventSource = std::make_shared<class EventSource>();
        eventSource->init(scheme, socketAddress, path);
        return eventSource;
    }
References web::http::client::tools::EventSourceT< Client >::init().
Referenced by EventSource(), and EventSource().
EventSource() [3/4]
std::shared_ptr< web::http::client::tools::EventSource > web::http::legacy::in::EventSource (const std::string & url) inline
Definition at line 86 of file EventSource.h.
{
        std::shared_ptr<web::http::client::tools::EventSource> eventSource;
        static const std::regex re(
            R"(^(?:(https?)://)?(?![^/]*@)((?:(?:25[0-5]|2[0-4]\d|1?\d{1,2})\.){3}(?:25[0-5]|2[0-4]\d|1?\d{1,2})|[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*)(?::([0-9]{1,5}))?([^?#]*)(\?[^#]*)?(?:#.*)?$)",
            std::regex::ECMAScript | std::regex::icase);
        std::smatch match;
        if (std::regex_match(url, match, re)) {
            //  [1] scheme    (optional) -> "http" or "https"
            //  [2] host      (required) -> hostname or IPv4 token (no [ ], no :)
            //  [3] port      (optional) -> digits
            //  [4] path      (may be empty)
            //  [5] query     (optional)
            const std::string& scheme = match[1].matched ? match[1].str() : "http";
            const std::string& host = match[2].str();
            const uint16_t port = match[3].matched ? static_cast<uint16_t>(std::stoi(match[3].str())) : static_cast<uint16_t>(80);
            const std::string& path = (match[4].matched ? match[4].str() : "/");
            const std::string& query = (match[5].matched ? match[5].str() : "");
            if (scheme == "http") {
                eventSource = EventSource(scheme, net::in::SocketAddress(host, port), path);
            } else {
                LOG(ERROR) << "Scheme not valid: " << scheme;
            }
        } else {
            LOG(ERROR) << "EventSource url not accepted: " << url;
        }
        return eventSource;
    }
References EventSource(), and net::in::SocketAddress::SocketAddress().
EventSource() [4/4]
std::shared_ptr< web::http::client::tools::EventSource > web::http::legacy::in::EventSource (std::string origin, std::string path) inline
Definition at line 119 of file EventSource.h.
{
        if (!origin.empty() && origin.at(origin.length() - 1) == '/') {
            origin.pop_back();
        }
        if (!path.empty() && path.at(0) != '/') {
            path = "/" + path;
        }
        return EventSource(!origin.empty() ? origin + path : "");
    }