SNode.C: core::system Namespace Reference
core::system Namespace Reference
Functions
void * dlopen (const char *filename, int flags)
int dlclose (void *handle)
void * dlsym (void *handle, const char *symbol)
char * dlerror ()
int epoll_create1 (int flags)
int epoll_wait (int epfd, epoll_event *events, int maxevents, int timeout)
int epoll_pwait (int epfd, struct epoll_event *events, int maxevents, int timeout, const sigset_t *sigMask)
int epoll_ctl (int epfd, int op, int fd, epoll_event *event)
int getaddrinfo (const char *node, const char *service, const struct addrinfo *hints, struct addrinfo **res)
void freeaddrinfo (struct addrinfo *res)
int getnameinfo (const sockaddr *addr, socklen_t addrlen, char *host, socklen_t hostlen, char *serv, socklen_t servlen, int flags)
int poll (pollfd *fds, nfds_t nfds, int timeout)
int ppoll (struct pollfd *fds, nfds_t nfds, const timespec *timeout, const sigset_t *sigMask)
int select (int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout)
int pselect (int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, const struct timespec *timeout, const sigset_t *sigMask)
int socket (int domain, int type, int protocol)
int bind (int sockfd, const sockaddr *addr, socklen_t addrlen)
int listen (int sockfd, int backlog)
int accept (int sockfd, sockaddr *addr, socklen_t *addrlen)
int accept4 (int sockfd, sockaddr *addr, socklen_t *addrlen, int flags)
int connect (int sockfd, const sockaddr *addr, socklen_t addrlen)
int getsockname (int sockfd, sockaddr *addr, socklen_t *addrlen)
int getpeername (int sockfd, sockaddr *addr, socklen_t *addrlen)
ssize_t recv (int sockfd, void *buf, std::size_t len, int flags)
ssize_t send (int sockfd, const void *buf, std::size_t len, int flags)
int getsockopt (int sockfd, int level, int optname, void *optval, socklen_t *optlen)
int setsockopt (int sockfd, int level, int optname, const void *optval, socklen_t optlen)
int shutdown (int sockfd, int how)
int open (const char *pathname, int flags)
ssize_t read (int fd, void *buf, std::size_t count)
ssize_t write (int fd, const void *buf, std::size_t count)
int close (int fd)
int pipe2 (int pipefd[2], int flags)
int pselect (int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, const timespec *timeout, const sigset_t *sigMask)
Function Documentation
accept()
int core::system::accept (int sockfd, sockaddr * addr, socklen_t * addrlen)
Definition at line 44 of file socket.cpp.
{
        errno = 0;
        return ::accept(sockfd, addr, addrlen);
    }
Referenced by net::phy::stream::PhysicalSocketServer< SocketAddressT >::accept().
accept4()
int core::system::accept4 (int sockfd, sockaddr * addr, socklen_t * addrlen, int flags)
Definition at line 49 of file socket.cpp.
{
        errno = 0;
        return ::accept4(sockfd, addr, addrlen, flags);
    }
Referenced by net::phy::stream::PhysicalSocketServer< SocketAddressT >::accept4().
bind()
int core::system::bind (int sockfd, const sockaddr * addr, socklen_t addrlen)
Definition at line 34 of file socket.cpp.
{
        errno = 0;
        return ::bind(sockfd, addr, addrlen);
    }
Referenced by net::phy::PhysicalSocket< SocketAddressT >::bind().
close()
int core::system::close (int fd)
Definition at line 44 of file unistd.cpp.
                      {
        errno = 0;
        return ::close(fd);
    }
Referenced by core::Descriptor::~Descriptor().
connect()
int core::system::connect (int sockfd, const sockaddr * addr, socklen_t addrlen)
Definition at line 53 of file socket.cpp.
{
        errno = 0;
        return ::connect(sockfd, addr, addrlen);
    }
Referenced by net::phy::stream::PhysicalSocketClient< SocketAddressT >::connect().
dlclose()
int core::system::dlclose (void * handle)
Definition at line 34 of file dlfcn.cpp.
{
        errno = 0;
        return ::dlclose(handle);
    }
Referenced by core::DynamicLoader::execDlClose().
dlerror()
char * core::system::dlerror ()
Definition at line 44 of file dlfcn.cpp.
                    {
        errno = 0;
        return ::dlerror();
    }
Referenced by core::DynamicLoader::dlError().
dlopen()
void * core::system::dlopen (const char * filename, int flags)
Definition at line 29 of file dlfcn.cpp.
{
        errno = 0;
        return ::dlopen(filename, flags);
    }
dlsym()
void * core::system::dlsym (void * handle, const char * symbol)
Definition at line 39 of file dlfcn.cpp.
{
        errno = 0;
        return ::dlsym(handle, symbol);
    }
Referenced by core::DynamicLoader::dlSym().
epoll_create1()
int core::system::epoll_create1 (int flags)
Definition at line 29 of file epoll.cpp.
{
        errno = 0;
        return ::epoll_create1(flags);
    }
Referenced by core::epoll::DescriptorEventPublisher::EPollEvents::EPollEvents(), and core::epoll::EventMultiplexer::EventMultiplexer().
epoll_ctl()
int core::system::epoll_ctl (int epfd, int op, int fd, epoll_event * event)
Definition at line 44 of file epoll.cpp.
{
        errno = 0;
        return ::epoll_ctl(epfd, op, fd, event);
    }
Referenced by core::epoll::EventMultiplexer::EventMultiplexer(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxDel(), and core::epoll::DescriptorEventPublisher::EPollEvents::muxMod().
epoll_pwait()
int core::system::epoll_pwait (int epfd, struct epoll_event * events, int maxevents, int timeout, const sigset_t * sigMask)
Definition at line 39 of file epoll.cpp.
{
        errno = 0;
        return ::epoll_pwait(epfd, events, maxevents, timeout, sigMask);
    }
Referenced by core::epoll::EventMultiplexer::monitorDescriptors().
epoll_wait()
int core::system::epoll_wait (int epfd, epoll_event * events, int maxevents, int timeout)
Definition at line 34 of file epoll.cpp.
{
        errno = 0;
        return ::epoll_wait(epfd, events, maxevents, timeout);
    }
Referenced by core::epoll::DescriptorEventPublisher::spanActiveEvents().
freeaddrinfo()
void core::system::freeaddrinfo (struct addrinfo * res)
Definition at line 34 of file netdb.cpp.
{
        errno = 0;
        return ::freeaddrinfo(res);
    }
getaddrinfo()
int core::system::getaddrinfo (const char * node, const char * service, const struct addrinfo * hints, struct addrinfo ** res)
Definition at line 29 of file netdb.cpp.
{
        errno = 0;
        return ::getaddrinfo(node, service, hints, res);
    }
Referenced by net::in::SocketAddrInfo::init(), and net::in6::SocketAddrInfo::init().
getnameinfo()
int core::system::getnameinfo (const sockaddr * addr, socklen_t addrlen, char * host, socklen_t hostlen, char * serv, socklen_t servlen, int flags)
Definition at line 39 of file netdb.cpp.
{
        errno = 0;
        return ::getnameinfo(addr, addrlen, host, hostlen, serv, servlen, flags);
    }
getpeername()
int core::system::getpeername (int sockfd, sockaddr * addr, socklen_t * addrlen)
Definition at line 63 of file socket.cpp.
{
        errno = 0;
        return ::getpeername(sockfd, addr, addrlen);
    }
Referenced by net::phy::PhysicalSocket< SocketAddressT >::getPeername().
getsockname()
int core::system::getsockname (int sockfd, sockaddr * addr, socklen_t * addrlen)
Definition at line 58 of file socket.cpp.
{
        errno = 0;
        return ::getsockname(sockfd, addr, addrlen);
    }
Referenced by net::phy::PhysicalSocket< SocketAddressT >::getSockname().
getsockopt()
int core::system::getsockopt (int sockfd, int level, int optname, void * optval, socklen_t * optlen)
Definition at line 78 of file socket.cpp.
{
        errno = 0;
        return ::getsockopt(sockfd, level, optname, optval, optlen);
    }
Referenced by net::phy::PhysicalSocket< SocketAddressT >::getSockopt().
listen()
int core::system::listen (int sockfd, int backlog)
Definition at line 39 of file socket.cpp.
{
        errno = 0;
        return ::listen(sockfd, backlog);
    }
Referenced by net::phy::stream::PhysicalSocketServer< SocketAddressT >::listen().
open()
int core::system::open (const char * pathname, int flags)
Definition at line 29 of file unistd.cpp.
{
        errno = 0;
        return ::open(pathname, flags);
    }
Referenced by core::file::FileReader::connect().
pipe2()
int core::system::pipe2 (int pipefd[2], int flags)
Definition at line 49 of file unistd.cpp.
{
        errno = 0;
        return ::pipe2(pipefd, flags);
    }
Referenced by core::pipe::Pipe::Pipe().
poll()
int core::system::poll (pollfd * fds, nfds_t nfds, int timeout)
Definition at line 29 of file poll.cpp.
{
        errno = 0;
        return ::poll(fds, nfds, timeout);
    }
ppoll()
int core::system::ppoll (struct pollfd * fds, nfds_t nfds, const timespec * timeout, const sigset_t * sigMask)
Definition at line 34 of file poll.cpp.
{
        errno = 0;
        return ::ppoll(fds, nfds, timeout, sigMask);
    }
pselect() [1/2]
int core::system::pselect (int nfds, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, const struct timespec * timeout, const sigset_t * sigMask)
Definition at line 34 of file select.cpp.
{
        errno = 0;
        return ::pselect(nfds, readfds, writefds, exceptfds, timeout, sigMask);
    }
Referenced by core::select::EventMultiplexer::monitorDescriptors().
pselect() [2/2]
int core::system::pselect (int nfds, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, const timespec * timeout, const sigset_t * sigMask)
read()
ssize_t core::system::read (int fd, void * buf, std::size_t count)
Definition at line 34 of file unistd.cpp.
{
        errno = 0;
        return ::read(fd, buf, count);
    }
Referenced by core::file::FileReader::onEvent(), and core::pipe::PipeSink::readEvent().
recv()
ssize_t core::system::recv (int sockfd, void * buf, std::size_t len, int flags)
Definition at line 68 of file socket.cpp.
{
        errno = 0;
        return ::recv(sockfd, buf, len, flags);
    }
Referenced by core::socket::stream::legacy::SocketReader< PhysicalSocketT >::read().
select()
int core::system::select (int nfds, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, struct timeval * timeout)
Definition at line 29 of file select.cpp.
{
        errno = 0;
        return ::select(nfds, readfds, writefds, exceptfds, timeout);
    }
send()
ssize_t core::system::send (int sockfd, const void * buf, std::size_t len, int flags)
Definition at line 73 of file socket.cpp.
{
        errno = 0;
        return ::send(sockfd, buf, len, flags);
    }
Referenced by core::socket::stream::legacy::SocketWriter< PhysicalSocketT >::write().
setsockopt()
int core::system::setsockopt (int sockfd, int level, int optname, const void * optval, socklen_t optlen)
Definition at line 83 of file socket.cpp.
{
        errno = 0;
        return ::setsockopt(sockfd, level, optname, optval, optlen);
    }
Referenced by net::phy::PhysicalSocket< SocketAddressT >::setSockopt().
shutdown()
int core::system::shutdown (int sockfd, int how)
Definition at line 88 of file socket.cpp.
{
        errno = 0;
        return ::shutdown(sockfd, how);
    }
Referenced by net::phy::stream::PhysicalSocket< SocketAddressT >::shutdown().
socket()
int core::system::socket (int domain, int type, int protocol)
Definition at line 29 of file socket.cpp.
{
        errno = 0;
        return ::socket(domain, type, protocol);
    }
Referenced by net::phy::PhysicalSocket< SocketAddressT >::open().
write()
ssize_t core::system::write (int fd, const void * buf, std::size_t count)
Definition at line 39 of file unistd.cpp.
{
        errno = 0;
        return ::write(fd, buf, count);
    }
Referenced by core::pipe::PipeSource::writeEvent().