SNode.C: detail Namespace Reference
detail Namespace Reference
Classes
struct AppFriend
This class is simply to allow tests access to App's protected functions.
struct element_type
not a pointer
struct element_type< T, typename std::enable_if< is_copyable_ptr< T >::value >::type >
struct element_value_type
class ExistingDirectoryValidator
Check for an existing directory (returns error message if check fails)
class ExistingFileValidator
Check for an existing file (returns error message if check fails)
class ExistingPathValidator
Check for an existing path.
struct has_find
class IPV4Validator
Validate the given string is a legal ipv4 address.
class is_complex
Check for complex.
class is_direct_constructible
class is_istreamable
Check for input streamability.
struct is_mutable_container
struct is_mutable_container< T, conditional_t< false, void_t< typename T::value_type, decltype(std::declval< T >().end()), decltype(std::declval< T >().clear()), decltype(std::declval< T >().insert(std::declval< decltype(std::declval< T >().end())>(), std::declval< const typename T::value_type & >()))>, void > >
class is_ostreamable
struct is_readable_container
struct is_readable_container< T, conditional_t< false, void_t< decltype(std::declval< T >().end()), decltype(std::declval< T >().begin())>, void > >
class is_tuple_like
struct is_wrapper
struct is_wrapper< T, conditional_t< false, void_t< typename T::value_type >, void > >
class NonexistentPathValidator
Check for an non-existing path.
struct pair_adaptor
Adaptor for set-like structure: This just wraps a normal container in a few utilities that do almost nothing.
struct pair_adaptor< T, conditional_t< false, void_t< typename T::value_type::first_type, typename T::value_type::second_type >, void > >
struct subtype_count
Set of overloads to get the type size of an object.
struct subtype_count_min
forward declare the subtype_count_min structure
struct type_count
This will only trigger for actual void type.
struct type_count< T, typename std::enable_if< is_complex< T >::value >::type >
Type size for complex since it sometimes looks like a wrapper.
struct type_count< T, typename std::enable_if< is_mutable_container< T >::value >::type >
Type size of types that are wrappers,except complex and tuples(which can also be wrappers sometimes)
struct type_count< T, typename std::enable_if< is_wrapper< T >::value &&!is_complex< T >::value &&!is_tuple_like< T >::value &&!is_mutable_container< T >::value >::type >
Type size of types that are wrappers,except containers complex and tuples(which can also be wrappers sometimes)
struct type_count< T, typename std::enable_if<!is_wrapper< T >::value &&!is_tuple_like< T >::value &&!is_complex< T >::value &&!std::is_void< T >::value >::type >
Type size for regular object types that do not look like a tuple.
struct type_count_base
This will only trigger for actual void type.
struct type_count_base< T, typename std::enable_if< is_mutable_container< T >::value >::type >
Type count base for containers is the type_count_base of the individual element.
struct type_count_base< T, typename std::enable_if< is_tuple_like< T >::value &&!is_mutable_container< T >::value >::type >
the base tuple size
struct type_count_base< T, typename std::enable_if<!is_tuple_like< T >::value &&!is_mutable_container< T >::value &&!std::is_void< T >::value >::type >
Type size for regular object types that do not look like a tuple.
struct wrapped_type
template to get the underlying value type if it exists or use a default
struct wrapped_type< T, def, typename std::enable_if< is_wrapper< T >::value >::type >
Type size for regular object types that do not look like a tuple.
Enumerations
enum class enabler
Simple empty scoped class.
enum class path_type { nonexistent , file , directory }
CLI enumeration of different file types.
enum class Classifier {
NONE , POSITIONAL_MARK , SHORT , LONG ,
WINDOWS_STYLE , SUBCOMMAND , SUBCOMMAND_TERMINATOR
}
Functions
template<typename T , enable_if_t< is_istreamable< T >::value, detail::enabler > = detail::dummy>
bool from_stream (const std::string &istring, T &obj)
Templated operation to get a value from a stream.
template<typename T , enable_if_t< std::is_convertible< T, std::string >::value, detail::enabler > = detail::dummy>
auto to_string (T &&value) -> decltype(std::forward< T >(value))
Convert an object to a string (directly forward if this can become a string)
template<typename T , enable_if_t< std::is_constructible< std::string, T >::value &&!std::is_convertible< T, std::string >::value, detail::enabler > = detail::dummy>
std::string to_string (const T &value)
Construct a string from the object.
template<typename T , enable_if_t<!std::is_convertible< std::string, T >::value &&!std::is_constructible< std::string, T >::value &&is_ostreamable< T >::value, detail::enabler > = detail::dummy>
std::string to_string (T &&value)
Convert an object to a string (streaming must be supported for that type)
template<typename T1 , typename T2 , typename T , enable_if_t< std::is_same< T1, T2 >::value, detail::enabler > = detail::dummy>
auto checked_to_string (T &&value) -> decltype(to_string(std::forward< T >(value)))
special template overload
template<typename T1 , typename T2 , typename T , enable_if_t<!std::is_same< T1, T2 >::value, detail::enabler > = detail::dummy>
std::string checked_to_string (T &&)
special template overload
template<typename T , enable_if_t< std::is_arithmetic< T >::value, detail::enabler > = detail::dummy>
std::string value_string (const T &value)
get a string as a convertible value for arithmetic types
template<typename T , enable_if_t<!std::is_enum< T >::value &&!std::is_arithmetic< T >::value, detail::enabler > = detail::dummy>
auto value_string (const T &value) -> decltype(to_string(value))
for other types just use the regular to_string function
template<typename T , std::size_t I>
constexpr std::enable_if< I==type_count_base< T >::value, int >::type tuple_type_size ()
0 if the index > tuple size
template<typename T , std::size_t I>
constexpr std::enable_if< I< type_count_base< T >::value, int >::type tuple_type_size() { return subtype_count< typename std::tuple_element< I, T >::type >::value+tuple_type_size< T, I+1 >();} template< typename T > struct type_count< T, typename std::enable_if< is_tuple_like< T >::value >::type > { static constexpr int value{tuple_type_size< T, 0 >()};};template< typename T > struct subtype_count { static constexpr int value{is_mutable_container< T >::value ? expected_max_vector_size :type_count< T >::value};};template< typename T, typename Enable=void > struct type_count_min { static const int value{0};};template< typename T > struct type_count_min< T, typename std::enable_if<!is_mutable_container< T >::value &&!is_tuple_like< T >::value &&!is_wrapper< T >::value &&!is_complex< T >::value &&!std::is_void< T >::value >::type > { static constexpr int value{type_count< T >::value};};template< typename T > struct type_count_min< T, typename std::enable_if< is_complex< T >::value >::type > { static constexpr int value{1};};template< typename T > struct type_count_min< T, typename std::enable_if< is_wrapper< T >::value &&!is_complex< T >::value &&!is_tuple_like< T >::value >::type > { static constexpr int value{subtype_count_min< typename T::value_type >::value};};template< typename T, std::size_t I > constexpr typename std::enable_if< I==type_count_base< T >::value, int >::type tuple_type_size_min() { return 0;} template< typename T, std::size_t I > constexpr typename std::enable_if< I< type_count_base< T >::value, int >::type tuple_type_size_min() { return subtype_count_min< typename std::tuple_element< I, T >::type >::value+tuple_type_size_min< T, I+1 >();} template< typename T > struct type_count_min< T, typename std::enable_if< is_tuple_like< T >::value >::type > { static constexpr int value{tuple_type_size_min< T, 0 >()};};template< typename T > struct subtype_count_min { static constexpr int value{is_mutable_container< T >::value ?((type_count< T >::value< expected_max_vector_size) ? type_count< T >::value :0) :type_count_min< T >::value};};template< typename T, typename Enable=void > struct expected_count { static const int value{0};};template< typename T > struct expected_count< T, typename std::enable_if<!is_mutable_container< T >::value &&!is_wrapper< T >::value &&!std::is_void< T >::value >::type > { static constexpr int value{1};};template< typename T > struct expected_count< T, typename std::enable_if< is_mutable_container< T >::value >::type > { static constexpr int value{expected_max_vector_size};};template< typename T > struct expected_count< T, typename std::enable_if<!is_mutable_container< T >::value &&is_wrapper< T >::value >::type > { static constexpr int value{expected_count< typename T::value_type >::value};};enum class object_category :int { char_value=1, integral_value=2, unsigned_integral=4, enumeration=6, boolean_value=8, floating_point=10, number_constructible=12, double_constructible=14, integer_constructible=16, string_assignable=23, string_constructible=24, wstring_assignable=25, wstring_constructible=26, other=45, wrapper_value=50, complex_number=60, tuple_value=70, container_value=80, };template< typename T, typename Enable=void > struct classify_object { static constexpr object_category value{object_category::other};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, char >::value &&std::is_signed< T >::value &&!is_bool< T >::value &&!std::is_enum< T >::value >::type > { static constexpr object_category value{object_category::integral_value};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_integral< T >::value &&std::is_unsigned< T >::value &&!std::is_same< T, char >::value &&!is_bool< T >::value >::type > { static constexpr object_category value{object_category::unsigned_integral};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_same< T, char >::value &&!std::is_enum< T >::value >::type > { static constexpr object_category value{object_category::char_value};};template< typename T > struct classify_object< T, typename std::enable_if< is_bool< T >::value >::type > { static constexpr object_category value{object_category::boolean_value};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_floating_point< T >::value >::type > { static constexpr object_category value{object_category::floating_point};};template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value &&std::is_assignable< T &, std::string >::value >::type > { static constexpr object_category value{object_category::string_assignable};};template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value &&!std::is_assignable< T &, std::string >::value &&(type_count< T >::value==1) &&std::is_constructible< T, std::string >::value >::type > { static constexpr object_category value{object_category::string_constructible};};template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value &&!std::is_assignable< T &, std::string >::value &&!std::is_constructible< T, std::string >::value &&std::is_assignable< T &, std::wstring >::value >::type > { static constexpr object_category value{object_category::wstring_assignable};};template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value &&!std::is_assignable< T &, std::string >::value &&!std::is_constructible< T, std::string >::value &&!std::is_assignable< T &, std::wstring >::value &&(type_count< T >::value==1) &&std::is_constructible< T, std::wstring >::value >::type > { static constexpr object_category value{object_category::wstring_constructible};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_enum< T >::value >::type > { static constexpr object_category value{object_category::enumeration};};template< typename T > struct classify_object< T, typename std::enable_if< is_complex< T >::value >::type > { static constexpr object_category value{object_category::complex_number};};template< typename T > struct uncommon_type { using type=typename std::conditional< !std::is_floating_point< T >::value &&!std::is_integral< T >::value &&!std::is_assignable< T &, std::string >::value &&!std::is_constructible< T, std::string >::value &&!std::is_assignable< T &, std::wstring >::value &&!std::is_constructible< T, std::wstring >::value &&!is_complex< T >::value &&!is_mutable_container< T >::value &&!std::is_enum< T >::value, std::true_type, std::false_type >::type;static constexpr bool value=type::value;};template< typename T > struct classify_object< T, typename std::enable_if<(!is_mutable_container< T >::value &&is_wrapper< T >::value &&!is_tuple_like< T >::value &&uncommon_type< T >::value)>::type > { static constexpr object_category value{object_category::wrapper_value};};template< typename T > struct classify_object< T, typename std::enable_if< uncommon_type< T >::value &&type_count< T >::value==1 &&!is_wrapper< T >::value &&is_direct_constructible< T, double >::value &&is_direct_constructible< T, int >::value >::type > { static constexpr object_category value{object_category::number_constructible};};template< typename T > struct classify_object< T, typename std::enable_if< uncommon_type< T >::value &&type_count< T >::value==1 &&!is_wrapper< T >::value &&!is_direct_constructible< T, double >::value &&is_direct_constructible< T, int >::value >::type > { static constexpr object_category value{object_category::integer_constructible};};template< typename T > struct classify_object< T, typename std::enable_if< uncommon_type< T >::value &&type_count< T >::value==1 &&!is_wrapper< T >::value &&is_direct_constructible< T, double >::value &&!is_direct_constructible< T, int >::value >::type > { static constexpr object_category value{object_category::double_constructible};};template< typename T > struct classify_object< T, typename std::enable_if< is_tuple_like< T >::value &&((type_count< T >::value >=2 &&!is_wrapper< T >::value)||(uncommon_type< T >::value &&!is_direct_constructible< T, double >::value &&!is_direct_constructible< T, int >::value)||(uncommon_type< T >::value &&type_count< T >::value >=2))>::type > { static constexpr object_category value{object_category::tuple_value};};template< typename T > struct classify_object< T, typename std::enable_if< is_mutable_container< T >::value >::type > { static constexpr object_category value{object_category::container_value};};template< typename T, enable_if_t< classify_object< T >::value==object_category::char_value, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "CHAR";} template< typename T, enable_if_t< classify_object< T >::value==object_category::integral_value||classify_object< T >::value==object_category::integer_constructible, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "INT";} template< typename T, enable_if_t< classify_object< T >::value==object_category::unsigned_integral, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "UINT";} template< typename T, enable_if_t< classify_object< T >::value==object_category::floating_point||classify_object< T >::value==object_category::number_constructible||classify_object< T >::value==object_category::double_constructible, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "FLOAT";} template< typename T, enable_if_t< classify_object< T >::value==object_category::enumeration, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "ENUM";} template< typename T, enable_if_t< classify_object< T >::value==object_category::boolean_value, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "BOOLEAN";} template< typename T, enable_if_t< classify_object< T >::value==object_category::complex_number, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "COMPLEX";} template< typename T, enable_if_t< classify_object< T >::value >=object_category::string_assignable &&classify_object< T >::value<=object_category::other, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "TEXT";} template< typename T, enable_if_t< classify_object< T >::value==object_category::tuple_value &&type_count_base< T >::value >=2, detail::enabler >=detail::dummy > std::string type_name();template< typename T, enable_if_t< classify_object< T >::value==object_category::container_value||classify_object< T >::value==object_category::wrapper_value, detail::enabler >=detail::dummy > std::string type_name();template< typename T, enable_if_t< classify_object< T >::value==object_category::tuple_value &&type_count_base< T >::value==1, detail::enabler >=detail::dummy > inline std::string type_name() { return type_name< typename std::decay< typename std::tuple_element< 0, T >::type >::type >();} template< typename T, std::size_t I > inline typename std::enable_if< I==type_count_base< T >::value, std::string >::type tuple_name() { return std::string{};} template< typename T, std::size_t I > inline typename std::enable_if<(I< type_count_base< T >::value), std::string >::type tuple_name() { auto str=std::string{type_name< typename std::decay< typename std::tuple_element< I, T >::type >::type >()}+','+tuple_name< T, I+1 >();if(str.back()==',') str.pop_back();return str;} template< typename T, enable_if_t< classify_object< T >::value==object_category::tuple_value &&type_count_base< T >::value >=2, detail::enabler > > inline std::string type_name() { auto tname=std::string(1, '[')+tuple_name< T, 0 >();tname.push_back(']');return tname;} template< typename T, enable_if_t< classify_object< T >::value==object_category::container_value||classify_object< T >::value==object_category::wrapper_value, detail::enabler > > inline std::string type_name() { return type_name< typename T::value_type >();} template< typename T, enable_if_t< std::is_unsigned< T >::value, detail::enabler >=detail::dummy > bool integral_conversion(const std::string &input, T &output) noexcept { if(input.empty()||input.front()=='-') { return false;} char *val=nullptr;errno=0;std::uint64_t const output_ll=std::strtoull(input.c_str(), &val, 0);if(errno==ERANGE) { return false;} output=static_cast< T >(output_ll);if(val==(input.c_str()+input.size()) &&static_cast< std::uint64_t >(output)==output_ll) { return true;} val=nullptr;std::int64_t const output_sll=std::strtoll(input.c_str(), &val, 0);if(val==(input.c_str()+input.size())) { output=(output_sll< 0) ? static_cast< T >(0) :static_cast< T >(output_sll);return(static_cast< std::int64_t >(output)==output_sll);} return false;} template< typename T, enable_if_t< std::is_signed< T >::value, detail::enabler >=detail::dummy > bool integral_conversion (const std::string &input, T &output) noexcept
Recursively generate the tuple type name.
std::int64_t to_flag_value (std::string val)
Convert a flag into an integer value typically binary flags.
template<typename T , enable_if_t< classify_object< T >::value==object_category::integral_value||classify_object< T >::value==object_category::unsigned_integral, detail::enabler > = detail::dummy>
bool lexical_cast (const std::string &input, T &output)
Integer conversion.
template<typename AssignTo , typename ConvertTo , enable_if_t< std::is_same< AssignTo, ConvertTo >::value &&(classify_object< AssignTo >::value==object_category::string_assignable||classify_object< AssignTo >::value==object_category::string_constructible||classify_object< AssignTo >::value==object_category::wstring_assignable||classify_object< AssignTo >::value==object_category::wstring_constructible), detail::enabler > = detail::dummy>
bool lexical_assign (const std::string &input, AssignTo &output)
Assign a value through lexical cast operations.
bool split_short (const std::string &current, std::string &name, std::string &rest)
bool split_long (const std::string &current, std::string &name, std::string &value)
bool split_windows_style (const std::string &current, std::string &name, std::string &value)
std::vector< std::string > split_names (std::string current)
std::vector< std::pair< std::string, std::string > > get_default_flag_values (const std::string &str)
extract default flag values either {def} or starting with a !
std::tuple< std::vector< std::string >, std::vector< std::string >, std::string > get_names (const std::vector< std::string > &input)
Get a vector of short names, one of long names, and a single name.
path_type check_path (const char *file) noexcept
get the type of the path from a file name
template<typename T , enable_if_t< is_copyable_ptr< typename std::remove_reference< T >::type >::value, detail::enabler > = detail::dummy>
auto smart_deref (T value) -> decltype(*value)
template<typename T , enable_if_t<!is_copyable_ptr< typename std::remove_reference< T >::type >::value, detail::enabler > = detail::dummy>
std::remove_reference< T >::type & smart_deref (T &value)
template<typename T >
std::string generate_set (const T &set)
Generate a string representation of a set.
template<typename T >
std::string generate_map (const T &map, bool key_only=false)
Generate a string representation of a map.
template<typename T , typename V , enable_if_t<!has_find< T, V >::value, detail::enabler > = detail::dummy>
auto search (const T &set, const V &val) -> std::pair< bool, decltype(std::begin(detail::smart_deref(set)))>
A search function.
template<typename T , typename V >
auto search (const T &set, const V &val, const std::function< V(V)> &filter_function) -> std::pair< bool, decltype(std::begin(detail::smart_deref(set)))>
A search function with a filter function.
template<typename T >
std::enable_if< std::is_signed< T >::value, T >::type overflowCheck (const T &a, const T &b)
Do a check for overflow on signed numbers.
template<typename T >
std::enable_if<!std::is_signed< T >::value, T >::type overflowCheck (const T &a, const T &b)
Do a check for overflow on unsigned numbers.
template<typename T >
std::enable_if< std::is_integral< T >::value, bool >::type checked_multiply (T &a, T b)
Performs a *= b; if it doesn't cause integer overflow. Returns false otherwise.
template<typename T >
std::enable_if< std::is_floating_point< T >::value, bool >::type checked_multiply (T &a, T b)
Performs a *= b; if it doesn't equal infinity. Returns false otherwise.
std::pair< std::string, std::string > split_program_name (std::string commandline)
template<typename T , enable_if_t<!std::is_integral< T >::value||(sizeof(T)<=1U), detail::enabler > = detail::dummy>
Option * default_flag_modifiers (Option *opt)
helper functions for adding in appropriate flag modifiers for add_flag
const char * maybe_narrow (const char *str)
std::string maybe_narrow (const wchar_t *str)
std::string convert_arg_for_ini (const std::string &arg, char stringQuote='"', char characterQuote = '\'')
std::string ini_join (const std::vector< std::string > &args, char sepChar=',', char arrayStart='[', char arrayEnd=']', char stringQuote='"', char characterQuote = '\'')
Comma separated join, adds quotes if needed.
std::vector< std::string > generate_parents (const std::string &section, std::string &name, char parentSeparator)
void checkParentSegments (std::vector< ConfigItem > &output, const std::string &currentSection, char parentSeparator)
assuming non default segments do a check on the close and open of the segments in a configItem structure
Variables
constexpr enabler dummy = {}
An instance to use in EnableIf.
Enumeration Type Documentation
Classifier
enum class detail::Classifier strong
Enumerator
NONE
POSITIONAL_MARK
SHORT
LONG
WINDOWS_STYLE
SUBCOMMAND
SUBCOMMAND_TERMINATOR
Definition at line 6238 of file CLI11.hpp.
{ NONE, POSITIONAL_MARK, SHORT, LONG, WINDOWS_STYLE, SUBCOMMAND, SUBCOMMAND_TERMINATOR };
enabler
enum class detail::enabler strong
Simple empty scoped class.
Definition at line 1374 of file CLI11.hpp.
{};
path_type
enum class detail::path_type strong
CLI enumeration of different file types.
Enumerator
nonexistent
file
directory
Definition at line 3486 of file CLI11.hpp.
{ nonexistent, file, directory };
Function Documentation
check_path()
path_type detail::check_path (const char * file) inline noexcept
get the type of the path from a file name
Definition at line 4353 of file CLI11.hpp.
{
#if defined(_MSC_VER)
            struct __stat64 buffer;
            if (_stat64(file, &buffer) == 0) {
                return ((buffer.st_mode & S_IFDIR) != 0) ? path_type::directory : path_type::file;
            }
#else
            struct stat buffer;
            if (stat(file, &buffer) == 0) {
                return ((buffer.st_mode & S_IFDIR) != 0) ? path_type::directory : path_type::file;
            }
#endif
            return path_type::nonexistent;
        }
References directory, file, and nonexistent.
checked_multiply() [1/2]
template<typename T > std::enable_if< std::is_integral< T >::value, bool >::type detail::checked_multiply (T & a, T b)
Performs a *= b; if it doesn't cause integer overflow. Returns false otherwise.
Definition at line 3766 of file CLI11.hpp.
{
            if (a == 0 || b == 0 || a == 1 || b == 1) {
                a *= b;
                return true;
            }
            if (a == (std::numeric_limits<T>::min)() || b == (std::numeric_limits<T>::min)()) {
                return false;
            }
            if (overflowCheck(a, b)) {
                return false;
            }
            a *= b;
            return true;
        }
checked_multiply() [2/2]
template<typename T > std::enable_if< std::is_floating_point< T >::value, bool >::type detail::checked_multiply (T & a, T b)
Performs a *= b; if it doesn't equal infinity. Returns false otherwise.
Definition at line 3783 of file CLI11.hpp.
{
            T c = a * b;
            if (std::isinf(c) && !std::isinf(a) && !std::isinf(b)) {
                return false;
            }
            a = c;
            return true;
        }
checked_to_string() [1/2]
template<typename T1 , typename T2 , typename T , enable_if_t<!std::is_same< T1, T2 >::value, detail::enabler > = detail::dummy> std::string detail::checked_to_string (T &&)
special template overload
Definition at line 1723 of file CLI11.hpp.
{
            return std::string{};
        }
checked_to_string() [2/2]
template<typename T1 , typename T2 , typename T , enable_if_t< std::is_same< T1, T2 >::value, detail::enabler > = detail::dummy> auto detail::checked_to_string (T && value) -> decltype(to_string(std::forward<T>(value)))
special template overload
Definition at line 1717 of file CLI11.hpp.
{
            return to_string(std::forward<T>(value));
        }
checkParentSegments()
void detail::checkParentSegments (std::vector< ConfigItem > & output, const std::string & currentSection, char parentSeparator) inline
assuming non default segments do a check on the close and open of the segments in a configItem structure
Definition at line 10023 of file CLI11.hpp.
{
            std::string estring;
            auto parents = detail::generate_parents(currentSection, estring, parentSeparator);
            if (!output.empty() && output.back().name == "--") {
                std::size_t const msize = (parents.size() > 1U) ? parents.size() : 2;
                while (output.back().parents.size() >= msize) {
                    output.push_back(output.back());
                    output.back().parents.pop_back();
                }
                if (parents.size() > 1) {
                    std::size_t common = 0;
                    std::size_t const mpair = (std::min)(output.back().parents.size(), parents.size() - 1);
                    for (std::size_t ii = 0; ii < mpair; ++ii) {
                        if (output.back().parents[ii] != parents[ii]) {
                            break;
                        }
                        ++common;
                    }
                    if (common == mpair) {
                        output.pop_back();
                    } else {
                        while (output.back().parents.size() > common + 1) {
                            output.push_back(output.back());
                            output.back().parents.pop_back();
                        }
                    }
                    for (std::size_t ii = common; ii < parents.size() - 1; ++ii) {
                        output.emplace_back();
                        output.back().parents.assign(parents.begin(), parents.begin() + static_cast<std::ptrdiff_t>(ii) + 1);
                        output.back().name = "++";
                    }
                }
            } else if (parents.size() > 1) {
                for (std::size_t ii = 0; ii < parents.size() - 1; ++ii) {
                    output.emplace_back();
                    output.back().parents.assign(parents.begin(), parents.begin() + static_cast<std::ptrdiff_t>(ii) + 1);
                    output.back().name = "++";
                }
            }
            // insert a section end which is just an empty items_buffer
            output.emplace_back();
            output.back().parents = std::move(parents);
            output.back().name = "++";
        }
convert_arg_for_ini()
std::string detail::convert_arg_for_ini (const std::string & arg, char stringQuote = '"', char characterQuote = '\'') inline
Definition at line 9929 of file CLI11.hpp.
{
            if (arg.empty()) {
                return std::string(2, stringQuote);
            }
            // some specifically supported strings
            if (arg == "true" || arg == "false" || arg == "nan" || arg == "inf") {
                return arg;
            }
            // floating point conversion can convert some hex codes, but don't try that here
            if (arg.compare(0, 2, "0x") != 0 && arg.compare(0, 2, "0X") != 0) {
                using CLI::detail::lexical_cast;
                double val = 0.0;
                if (lexical_cast(arg, val)) {
                    return arg;
                }
            }
            // just quote a single non numeric character
            if (arg.size() == 1) {
                return std::string(1, characterQuote) + arg + characterQuote;
            }
            // handle hex, binary or octal arguments
            if (arg.front() == '0') {
                if (arg[1] == 'x') {
                    if (std::all_of(arg.begin() + 2, arg.end(), [](char x) {
                            return (x >= '0' && x <= '9') || (x >= 'A' && x <= 'F') || (x >= 'a' && x <= 'f');
                        })) {
                        return arg;
                    }
                } else if (arg[1] == 'o') {
                    if (std::all_of(arg.begin() + 2, arg.end(), [](char x) {
                            return (x >= '0' && x <= '7');
                        })) {
                        return arg;
                    }
                } else if (arg[1] == 'b') {
                    if (std::all_of(arg.begin() + 2, arg.end(), [](char x) {
                            return (x == '0' || x == '1');
                        })) {
                        return arg;
                    }
                }
            }
            if (arg.find_first_of(stringQuote) == std::string::npos) {
                return std::string(1, stringQuote) + arg + stringQuote;
            }
            return characterQuote + arg + characterQuote;
        }
default_flag_modifiers()
template<typename T , enable_if_t<!std::is_integral< T >::value||(sizeof(T)<=1U), detail::enabler > = detail::dummy> Option * detail::default_flag_modifiers (Option * opt)
helper functions for adding in appropriate flag modifiers for add_flag
summing modifiers
Definition at line 6262 of file CLI11.hpp.
{
            return opt->always_capture_default();
        }
from_stream()
template<typename T , enable_if_t< is_istreamable< T >::value, detail::enabler > = detail::dummy> bool detail::from_stream (const std::string & istring, T & obj)
Templated operation to get a value from a stream.
Definition at line 1595 of file CLI11.hpp.
{
            std::istringstream is;
            is.str(istring);
            is >> obj;
            return !is.fail() && !is.rdbuf()->in_avail();
        }
generate_map()
template<typename T > std::string detail::generate_map (const T & map, bool key_only = false)
Generate a string representation of a map.
Definition at line 3677 of file CLI11.hpp.
{
            using element_t = typename detail::element_type<T>::type;
            using iteration_type_t = typename detail::pair_adaptor<element_t>::value_type; // the type of the object pair
            std::string out(1, '{');
            out.append(detail::join(
                detail::smart_deref(map),
                [key_only](const iteration_type_t& v) {
                    std::string res{detail::to_string(detail::pair_adaptor<element_t>::first(v))};
                    if (!key_only) {
                        res.append("->");
                        res += detail::to_string(detail::pair_adaptor<element_t>::second(v));
                    }
                    return res;
                },
                ","));
            out.push_back('}');
            return out;
        }
generate_parents()
std::vector< std::string > detail::generate_parents (const std::string & section, std::string & name, char parentSeparator) inline
Definition at line 9999 of file CLI11.hpp.
{
            std::vector<std::string> parents;
            if (detail::to_lower(section) != "default") {
                if (section.find(parentSeparator) != std::string::npos) {
                    parents = detail::split(section, parentSeparator);
                } else {
                    parents = {section};
                }
            }
            if (name.find(parentSeparator) != std::string::npos) {
                std::vector<std::string> plist = detail::split(name, parentSeparator);
                name = plist.back();
                detail::remove_quotes(name);
                plist.pop_back();
                parents.insert(parents.end(), plist.begin(), plist.end());
            }
            // clean up quotes on the parents
            for (auto& parent : parents) {
                detail::remove_quotes(parent);
            }
            return parents;
        }
References CLI::detail::remove_quotes(), and CLI::detail::to_lower().
generate_set()
template<typename T > std::string detail::generate_set (const T & set)
Generate a string representation of a set.
Definition at line 3661 of file CLI11.hpp.
{
            using element_t = typename detail::element_type<T>::type;
            using iteration_type_t = typename detail::pair_adaptor<element_t>::value_type; // the type of the object pair
            std::string out(1, '{');
            out.append(detail::join(
                detail::smart_deref(set),
                [](const iteration_type_t& v) {
                    return detail::pair_adaptor<element_t>::first(v);
                },
                ","));
            out.push_back('}');
            return out;
        }
get_default_flag_values()
std::vector< std::pair< std::string, std::string > > detail::get_default_flag_values (const std::string & str) inline
extract default flag values either {def} or starting with a !
Definition at line 3086 of file CLI11.hpp.
{
            std::vector<std::string> flags = split_names(str);
            flags.erase(std::remove_if(
                            flags.begin(),
                            flags.end(),
                            [](const std::string& name) {
                                return ((name.empty()) ||
                                        (!(((name.find_first_of('{') != std::string::npos) && (name.back() == '}')) || (name[0] == '!'))));
                            }),
                        flags.end());
            std::vector<std::pair<std::string, std::string>> output;
            output.reserve(flags.size());
            for (auto& flag : flags) {
                auto def_start = flag.find_first_of('{');
                std::string defval = "false";
                if ((def_start != std::string::npos) && (flag.back() == '}')) {
                    defval = flag.substr(def_start + 1);
                    defval.pop_back();
                    flag.erase(def_start, std::string::npos); // NOLINT(readability-suspicious-call-argument)
                }
                flag.erase(0, flag.find_first_not_of("-!"));
                output.emplace_back(flag, defval);
            }
            return output;
        }
get_names()
std::tuple< std::vector< std::string >, std::vector< std::string >, std::string > detail::get_names (const std::vector< std::string > & input) inline
Get a vector of short names, one of long names, and a single name.
Definition at line 3113 of file CLI11.hpp.
{
            std::vector<std::string> short_names;
            std::vector<std::string> long_names;
            std::string pos_name;
            for (std::string name : input) {
                if (name.length() == 0) {
                    continue;
                }
                if (name.length() > 1 && name[0] == '-' && name[1] != '-') {
                    if (name.length() == 2 && valid_first_char(name[1]))
                        short_names.emplace_back(1, name[1]);
                    else
                        throw BadNameString::OneCharName(name);
                } else if (name.length() > 2 && name.substr(0, 2) == "--") {
                    name = name.substr(2);
                    if (valid_name_string(name))
                        long_names.push_back(name);
                    else
                        throw BadNameString::BadLongName(name);
                } else if (name == "-" || name == "--") {
                    throw BadNameString::DashesOnly(name);
                } else {
                    if (pos_name.length() > 0)
                        throw BadNameString::MultiPositionalNames(name);
                    pos_name = name;
                }
            }
            return std::make_tuple(short_names, long_names, pos_name);
        }
ini_join()
std::string detail::ini_join (const std::vector< std::string > & args, char sepChar = ',', char arrayStart = '[', char arrayEnd = ']', char stringQuote = '"', char characterQuote = '\'') inline
Comma separated join, adds quotes if needed.
Definition at line 9977 of file CLI11.hpp.
{
            std::string joined;
            if (args.size() > 1 && arrayStart != '\0') {
                joined.push_back(arrayStart);
            }
            std::size_t start = 0;
            for (const auto& arg : args) {
                if (start++ > 0) {
                    joined.push_back(sepChar);
                    if (!std::isspace<char>(sepChar, std::locale())) {
                        joined.push_back(' ');
                    }
                }
                joined.append(convert_arg_for_ini(arg, stringQuote, characterQuote));
            }
            if (args.size() > 1 && arrayEnd != '\0') {
                joined.push_back(arrayEnd);
            }
            return joined;
        }
integral_conversion()
template<typename T , std::size_t I> std::enable_if< I< type_count_base< T >::value, int >::type tuple_type_size() { return subtype_count< typename std::tuple_element< I, T >::type >::value+tuple_type_size< T, I+1 >(); } template< typename T > struct type_count< T, typename std::enable_if< is_tuple_like< T >::value >::type > { static constexpr int value{tuple_type_size< T, 0 >()}; }; template< typename T > struct subtype_count { static constexpr int value{is_mutable_container< T >::value ? expected_max_vector_size :type_count< T >::value}; }; template< typename T, typename Enable=void > struct type_count_min { static const int value{0}; }; template< typename T > struct type_count_min< T, typename std::enable_if<!is_mutable_container< T >::value &&!is_tuple_like< T >::value && !is_wrapper< T >::value &&!is_complex< T >::value &&!std::is_void< T >::value >::type > { static constexpr int value{type_count< T >::value}; }; template< typename T > struct type_count_min< T, typename std::enable_if< is_complex< T >::value >::type > { static constexpr int value{1}; }; template< typename T > struct type_count_min< T, typename std::enable_if< is_wrapper< T >::value &&!is_complex< T >::value &&!is_tuple_like< T >::value >::type > { static constexpr int value{subtype_count_min< typename T::value_type >::value}; }; template< typename T, std::size_t I > constexpr typename std::enable_if< I==type_count_base< T >::value, int >::type tuple_type_size_min() { return 0; } template< typename T, std::size_t I > constexpr typename std::enable_if< I< type_count_base< T >::value, int >::type tuple_type_size_min() { return subtype_count_min< typename std::tuple_element< I, T >::type >::value+tuple_type_size_min< T, I+1 >(); } template< typename T > struct type_count_min< T, typename std::enable_if< is_tuple_like< T >::value >::type > { static constexpr int value{tuple_type_size_min< T, 0 >()}; }; template< typename T > struct subtype_count_min { static constexpr int value{is_mutable_container< T >::value ?((type_count< T >::value< expected_max_vector_size) ? type_count< T >::value :0) :type_count_min< T >::value}; }; template< typename T, typename Enable=void > struct expected_count { static const int value{0}; }; template< typename T > struct expected_count< T, typename std::enable_if<!is_mutable_container< T >::value &&!is_wrapper< T >::value &&!std::is_void< T >::value >::type > { static constexpr int value{1}; }; template< typename T > struct expected_count< T, typename std::enable_if< is_mutable_container< T >::value >::type > { static constexpr int value{expected_max_vector_size}; }; template< typename T > struct expected_count< T, typename std::enable_if<!is_mutable_container< T >::value &&is_wrapper< T >::value >::type > { static constexpr int value{expected_count< typename T::value_type >::value}; }; enum class object_category :int { char_value=1, integral_value=2, unsigned_integral=4, enumeration=6, boolean_value=8, floating_point=10, number_constructible=12, double_constructible=14, integer_constructible=16, string_assignable=23, string_constructible=24, wstring_assignable=25, wstring_constructible=26, other=45, wrapper_value=50, complex_number=60, tuple_value=70, container_value=80, }; template< typename T, typename Enable=void > struct classify_object { static constexpr object_category value{object_category::other}; }; template< typename T > struct classify_object< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, char >::value && std::is_signed< T >::value &&!is_bool< T >::value &&!std::is_enum< T >::value >::type > { static constexpr object_category value{object_category::integral_value}; }; template< typename T > struct classify_object< T, typename std::enable_if< std::is_integral< T >::value &&std::is_unsigned< T >::value && !std::is_same< T, char >::value &&!is_bool< T >::value >::type > { static constexpr object_category value{object_category::unsigned_integral}; }; template< typename T > struct classify_object< T, typename std::enable_if< std::is_same< T, char >::value &&!std::is_enum< T >::value >::type > { static constexpr object_category value{object_category::char_value}; }; template< typename T > struct classify_object< T, typename std::enable_if< is_bool< T >::value >::type > { static constexpr object_category value{object_category::boolean_value}; }; template< typename T > struct classify_object< T, typename std::enable_if< std::is_floating_point< T >::value >::type > { static constexpr object_category value{object_category::floating_point}; }; template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value && std::is_assignable< T &, std::string >::value >::type > { static constexpr object_category value{object_category::string_assignable}; }; template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value && !std::is_assignable< T &, std::string >::value &&(type_count< T >::value==1) && std::is_constructible< T, std::string >::value >::type > { static constexpr object_category value{object_category::string_constructible}; }; template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value && !std::is_assignable< T &, std::string >::value &&!std::is_constructible< T, std::string >::value && std::is_assignable< T &, std::wstring >::value >::type > { static constexpr object_category value{object_category::wstring_assignable}; }; template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value && !std::is_assignable< T &, std::string >::value &&!std::is_constructible< T, std::string >::value && !std::is_assignable< T &, std::wstring >::value &&(type_count< T >::value==1) && std::is_constructible< T, std::wstring >::value >::type > { static constexpr object_category value{object_category::wstring_constructible}; }; template< typename T > struct classify_object< T, typename std::enable_if< std::is_enum< T >::value >::type > { static constexpr object_category value{object_category::enumeration}; }; template< typename T > struct classify_object< T, typename std::enable_if< is_complex< T >::value >::type > { static constexpr object_category value{object_category::complex_number}; }; template< typename T > struct uncommon_type { using type=typename std::conditional< !std::is_floating_point< T >::value &&!std::is_integral< T >::value &&!std::is_assignable< T &, std::string >::value && !std::is_constructible< T, std::string >::value &&!std::is_assignable< T &, std::wstring >::value && !std::is_constructible< T, std::wstring >::value &&!is_complex< T >::value &&!is_mutable_container< T >::value && !std::is_enum< T >::value, std::true_type, std::false_type >::type; static constexpr bool value=type::value; }; template< typename T > struct classify_object< T, typename std::enable_if<(!is_mutable_container< T >::value &&is_wrapper< T >::value && !is_tuple_like< T >::value &&uncommon_type< T >::value)>::type > { static constexpr object_category value{object_category::wrapper_value}; }; template< typename T > struct classify_object< T, typename std::enable_if< uncommon_type< T >::value &&type_count< T >::value==1 &&!is_wrapper< T >::value && is_direct_constructible< T, double >::value &&is_direct_constructible< T, int >::value >::type > { static constexpr object_category value{object_category::number_constructible}; }; template< typename T > struct classify_object< T, typename std::enable_if< uncommon_type< T >::value &&type_count< T >::value==1 &&!is_wrapper< T >::value && !is_direct_constructible< T, double >::value &&is_direct_constructible< T, int >::value >::type > { static constexpr object_category value{object_category::integer_constructible}; }; template< typename T > struct classify_object< T, typename std::enable_if< uncommon_type< T >::value &&type_count< T >::value==1 &&!is_wrapper< T >::value && is_direct_constructible< T, double >::value &&!is_direct_constructible< T, int >::value >::type > { static constexpr object_category value{object_category::double_constructible}; }; template< typename T > struct classify_object< T, typename std::enable_if< is_tuple_like< T >::value &&((type_count< T >::value >=2 &&!is_wrapper< T >::value)||(uncommon_type< T >::value &&!is_direct_constructible< T, double >::value && !is_direct_constructible< T, int >::value)||(uncommon_type< T >::value &&type_count< T >::value >=2))>::type > { static constexpr object_category value{object_category::tuple_value}; }; template< typename T > struct classify_object< T, typename std::enable_if< is_mutable_container< T >::value >::type > { static constexpr object_category value{object_category::container_value}; }; template< typename T, enable_if_t< classify_object< T >::value==object_category::char_value, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "CHAR"; } template< typename T, enable_if_t< classify_object< T >::value==object_category::integral_value|| classify_object< T >::value==object_category::integer_constructible, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "INT"; } template< typename T, enable_if_t< classify_object< T >::value==object_category::unsigned_integral, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "UINT"; } template< typename T, enable_if_t< classify_object< T >::value==object_category::floating_point|| classify_object< T >::value==object_category::number_constructible|| classify_object< T >::value==object_category::double_constructible, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "FLOAT"; } template< typename T, enable_if_t< classify_object< T >::value==object_category::enumeration, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "ENUM"; } template< typename T, enable_if_t< classify_object< T >::value==object_category::boolean_value, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "BOOLEAN"; } template< typename T, enable_if_t< classify_object< T >::value==object_category::complex_number, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "COMPLEX"; } template< typename T, enable_if_t< classify_object< T >::value >=object_category::string_assignable && classify_object< T >::value<=object_category::other, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "TEXT"; } template< typename T, enable_if_t< classify_object< T >::value==object_category::tuple_value &&type_count_base< T >::value >=2, detail::enabler >=detail::dummy > std::string type_name(); template< typename T, enable_if_t< classify_object< T >::value==object_category::container_value|| classify_object< T >::value==object_category::wrapper_value, detail::enabler >=detail::dummy > std::string type_name(); template< typename T, enable_if_t< classify_object< T >::value==object_category::tuple_value &&type_count_base< T >::value==1, detail::enabler >=detail::dummy > inline std::string type_name() { return type_name< typename std::decay< typename std::tuple_element< 0, T >::type >::type >(); } template< typename T, std::size_t I > inline typename std::enable_if< I==type_count_base< T >::value, std::string >::type tuple_name() { return std::string{}; } template< typename T, std::size_t I > inline typename std::enable_if<(I< type_count_base< T >::value), std::string >::type tuple_name() { auto str= std::string{type_name< typename std::decay< typename std::tuple_element< I, T >::type >::type >()}+','+tuple_name< T, I+1 >(); if(str.back()==',') str.pop_back(); return str; } template< typename T, enable_if_t< classify_object< T >::value==object_category::tuple_value &&type_count_base< T >::value >=2, detail::enabler > > inline std::string type_name() { auto tname=std::string(1, '[')+tuple_name< T, 0 >(); tname.push_back(']'); return tname; } template< typename T, enable_if_t< classify_object< T >::value==object_category::container_value|| classify_object< T >::value==object_category::wrapper_value, detail::enabler > > inline std::string type_name() { return type_name< typename T::value_type >(); } template< typename T, enable_if_t< std::is_unsigned< T >::value, detail::enabler >=detail::dummy > bool integral_conversion(const std::string &input, T &output) noexcept { if(input.empty()||input.front()=='-') { return false; } char *val=nullptr; errno=0; std::uint64_t const output_ll=std::strtoull(input.c_str(), &val, 0); if(errno==ERANGE) { return false; } output=static_cast< T >(output_ll); if(val==(input.c_str()+input.size()) &&static_cast< std::uint64_t >(output)==output_ll) { return true; } val=nullptr; std::int64_t const output_sll=std::strtoll(input.c_str(), &val, 0); if(val==(input.c_str()+input.size())) { output=(output_sll< 0) ? static_cast< T >(0) :static_cast< T >(output_sll); return(static_cast< std::int64_t >(output)==output_sll); } return false; } template< typename T, enable_if_t< std::is_signed< T >::value, detail::enabler >=detail::dummy > bool detail::integral_conversion (const std::string & input, T & output) constexpr noexcept
Recursively generate the tuple type name.
Definition at line 2254 of file CLI11.hpp.
{
            if (input.empty()) {
                return false;
            }
            char* val = nullptr;
            errno = 0;
            std::int64_t const output_ll = std::strtoll(input.c_str(), &val, 0);
            if (errno == ERANGE) {
                return false;
            }
            output = static_cast<T>(output_ll);
            if (val == (input.c_str() + input.size()) && static_cast<std::int64_t>(output) == output_ll) {
                return true;
            }
            if (input == "true") {
                // this is to deal with a few oddities with flags and wrapper int types
                output = static_cast<T>(1);
                return true;
            }
            return false;
        }
lexical_assign()
template<typename AssignTo , typename ConvertTo , enable_if_t< std::is_same< AssignTo, ConvertTo >::value &&(classify_object< AssignTo >::value==object_category::string_assignable||classify_object< AssignTo >::value==object_category::string_constructible||classify_object< AssignTo >::value==object_category::wstring_assignable||classify_object< AssignTo >::value==object_category::wstring_constructible), detail::enabler > = detail::dummy> bool detail::lexical_assign (const std::string & input, AssignTo & output)
Assign a value through lexical cast operations.
Assign a value from a lexical cast through constructing a value and move assigning it.
Assign a value converted from a string in lexical cast to the output value directly.
Assign a value through lexical cast operations Strings can be empty so we need to do a little different
Assign a value through lexical cast operations for int compatible values mainly for atomic operations on some compilers
Definition at line 2556 of file CLI11.hpp.
{
            return lexical_cast(input, output);
        }
lexical_cast()
template<typename T , enable_if_t< classify_object< T >::value==object_category::integral_value||classify_object< T >::value==object_category::unsigned_integral, detail::enabler > = detail::dummy> bool detail::lexical_cast (const std::string & input, T & output)
Integer conversion.
Non-string parsable by a stream.
Non-string convertible from an int.
Assignable from double.
Assignable from int.
Assignable from double or int.
wrapper types
Enumerations.
Wide strings.
String and similar constructible and copy assignment.
String and similar direct assignment.
complex
Floats.
Boolean values.
char values
Definition at line 2324 of file CLI11.hpp.
{
            return integral_conversion(input, output);
        }
maybe_narrow() [1/2]
const char * detail::maybe_narrow (const char * str) inline
Definition at line 8184 of file CLI11.hpp.
{
            return str;
        }
maybe_narrow() [2/2]
std::string detail::maybe_narrow (const wchar_t * str) inline
Definition at line 8187 of file CLI11.hpp.
{
            return narrow(str);
        }
References CLI::narrow().
overflowCheck() [1/2]
template<typename T > std::enable_if< std::is_signed< T >::value, T >::type detail::overflowCheck (const T & a, const T & b) inline
Do a check for overflow on signed numbers.
Definition at line 3752 of file CLI11.hpp.
{
            if ((a > 0) == (b > 0)) {
                return ((std::numeric_limits<T>::max)() / (std::abs)(a) < (std::abs)(b));
            }
            return ((std::numeric_limits<T>::min)() / (std::abs)(a) > -(std::abs)(b));
        }
overflowCheck() [2/2]
template<typename T > std::enable_if<!std::is_signed< T >::value, T >::type detail::overflowCheck (const T & a, const T & b) inline
Do a check for overflow on unsigned numbers.
Definition at line 3760 of file CLI11.hpp.
{
            return ((std::numeric_limits<T>::max)() / a < b);
        }
search() [1/2]
template<typename T , typename V , enable_if_t<!has_find< T, V >::value, detail::enabler > = detail::dummy> auto detail::search (const T & set, const V & val) -> std::pair<bool, decltype(std::begin(detail::smart_deref(set)))>
A search function.
A search function that uses the built in find function.
Definition at line 3710 of file CLI11.hpp.
{
            using element_t = typename detail::element_type<T>::type;
            auto& setref = detail::smart_deref(set);
            auto it = std::find_if(std::begin(setref), std::end(setref), [&val](decltype(*std::begin(setref)) v) {
                return (detail::pair_adaptor<element_t>::first(v) == val);
            });
            return {(it != std::end(setref)), it};
        }
search() [2/2]
template<typename T , typename V > auto detail::search (const T & set, const V & val, const std::function< V(V)> & filter_function) -> std::pair<bool, decltype(std::begin(detail::smart_deref(set)))>
A search function with a filter function.
Definition at line 3729 of file CLI11.hpp.
{
            using element_t = typename detail::element_type<T>::type;
            // do the potentially faster first search
            auto res = search(set, val);
            if ((res.first) || (!(filter_function))) {
                return res;
            }
            // if we haven't found it do the longer linear search with all the element translations
            auto& setref = detail::smart_deref(set);
            auto it = std::find_if(std::begin(setref), std::end(setref), [&](decltype(*std::begin(setref)) v) {
                V a{detail::pair_adaptor<element_t>::first(v)};
                a = filter_function(a);
                return (a == val);
            });
            return {(it != std::end(setref)), it};
        }
smart_deref() [1/2]
template<typename T , enable_if_t<!is_copyable_ptr< typename std::remove_reference< T >::type >::value, detail::enabler > = detail::dummy> std::remove_reference< T >::type & detail::smart_deref (T & value)
Definition at line 3656 of file CLI11.hpp.
{
            return value;
        }
smart_deref() [2/2]
template<typename T , enable_if_t< is_copyable_ptr< typename std::remove_reference< T >::type >::value, detail::enabler > = detail::dummy> auto detail::smart_deref (T value) -> decltype(*value)
Definition at line 3650 of file CLI11.hpp.
{
            return *value;
        }
split_long()
bool detail::split_long (const std::string & current, std::string & name, std::string & value) inline
Definition at line 3045 of file CLI11.hpp.
{
            if (current.size() > 2 && current.compare(0, 2, "--") == 0 && valid_first_char(current[2])) {
                auto loc = current.find_first_of('=');
                if (loc != std::string::npos) {
                    name = current.substr(2, loc - 2);
                    value = current.substr(loc + 1);
                } else {
                    name = current.substr(2);
                    value = "";
                }
                return true;
            }
            return false;
        }
Referenced by App::_recognize().
split_names()
std::vector< std::string > detail::split_names (std::string current) inline
Definition at line 3075 of file CLI11.hpp.
{
            std::vector<std::string> output;
            std::size_t val = 0;
            while ((val = current.find(',')) != std::string::npos) {
                output.push_back(trim_copy(current.substr(0, val)));
                current = current.substr(val + 1);
            }
            output.push_back(trim_copy(current));
            return output;
        }
split_program_name()
std::pair< std::string, std::string > detail::split_program_name (std::string commandline) inline
Split a string into a program name and command line arguments the string is assumed to contain a file name followed by other arguments the return value contains is a pair with the first argument containing the program name and the second everything else.
Definition at line 4505 of file CLI11.hpp.
{
            // try to determine the programName
            std::pair<std::string, std::string> vals;
            trim(commandline);
            auto esp = commandline.find_first_of(' ', 1);
            while (detail::check_path(commandline.substr(0, esp).c_str()) != path_type::file) {
                esp = commandline.find_first_of(' ', esp + 1);
                if (esp == std::string::npos) {
                    // if we have reached the end and haven't found a valid file just assume the first argument is the
                    // program name
                    if (commandline[0] == '"' || commandline[0] == '\'' || commandline[0] == '`') {
                        bool embeddedQuote = false;
                        auto keyChar = commandline[0];
                        auto end = commandline.find_first_of(keyChar, 1);
                        while ((end != std::string::npos) && (commandline[end - 1] == '\\')) { // deal with escaped quotes
                            end = commandline.find_first_of(keyChar, end + 1);
                            embeddedQuote = true;
                        }
                        if (end != std::string::npos) {
                            vals.first = commandline.substr(1, end - 1);
                            esp = end + 1;
                            if (embeddedQuote) {
                                vals.first = find_and_replace(vals.first, std::string("\\") + keyChar, std::string(1, keyChar));
                            }
                        } else {
                            esp = commandline.find_first_of(' ', 1);
                        }
                    } else {
                        esp = commandline.find_first_of(' ', 1);
                    }
                    break;
                }
            }
            if (vals.first.empty()) {
                vals.first = commandline.substr(0, esp);
                rtrim(vals.first);
            }
            // strip the program name
            vals.second = (esp < commandline.length() - 1) ? commandline.substr(esp + 1) : std::string{};
            ltrim(vals.second);
            return vals;
        }
References CLI::detail::trim().
split_short()
bool detail::split_short (const std::string & current, std::string & name, std::string & rest) inline
Definition at line 3036 of file CLI11.hpp.
{
            if (current.size() > 1 && current[0] == '-' && valid_first_char(current[1])) {
                name = current.substr(1, 1);
                rest = current.substr(2);
                return true;
            }
            return false;
        }
Referenced by App::_parse_arg(), and App::_recognize().
split_windows_style()
bool detail::split_windows_style (const std::string & current, std::string & name, std::string & value) inline
Definition at line 3060 of file CLI11.hpp.
{
            if (current.size() > 1 && current[0] == '/' && valid_first_char(current[1])) {
                auto loc = current.find_first_of(':');
                if (loc != std::string::npos) {
                    name = current.substr(1, loc - 1);
                    value = current.substr(loc + 1);
                } else {
                    name = current.substr(1);
                    value = "";
                }
                return true;
            }
            return false;
        }
Referenced by App::_parse_arg(), and App::_recognize().
to_flag_value()
std::int64_t detail::to_flag_value (std::string val) inline
Convert a flag into an integer value typically binary flags.
Definition at line 2277 of file CLI11.hpp.
{
            static const std::string trueString("true");
            static const std::string falseString("false");
            if (val == trueString) {
                return 1;
            }
            if (val == falseString) {
                return -1;
            }
            val = detail::to_lower(val);
            std::int64_t ret = 0;
            if (val.size() == 1) {
                if (val[0] >= '1' && val[0] <= '9') {
                    return (static_cast<std::int64_t>(val[0]) - '0');
                }
                switch (val[0]) {
                    case '0':
                    case 'f':
                    case 'n':
                    case '-':
                        ret = -1;
                        break;
                    case 't':
                    case 'y':
                    case '+':
                        ret = 1;
                        break;
                    default:
                        throw std::invalid_argument("unrecognized character");
                }
                return ret;
            }
            if (val == trueString || val == "on" || val == "yes" || val == "enable") {
                ret = 1;
            } else if (val == falseString || val == "off" || val == "no" || val == "disable") {
                ret = -1;
            } else {
                ret = std::stoll(val);
            }
            return ret;
        }
References CLI::detail::to_lower().
Referenced by Option::get_flag_value().
to_string() [1/3]
template<typename T , enable_if_t< std::is_constructible< std::string, T >::value &&!std::is_convertible< T, std::string >::value, detail::enabler > = detail::dummy> std::string detail::to_string (const T & value)
Construct a string from the object.
Definition at line 1673 of file CLI11.hpp.
{
            return std::string(value); // NOLINT(google-readability-casting)
        }
to_string() [2/3]
template<typename T , enable_if_t<!std::is_convertible< std::string, T >::value &&!std::is_constructible< std::string, T >::value &&is_ostreamable< T >::value, detail::enabler > = detail::dummy> std::string detail::to_string (T && value)
Convert an object to a string (streaming must be supported for that type)
convert a readable container to a string
If conversion is not supported, return an empty string (streaming is not supported for that type)
Definition at line 1682 of file CLI11.hpp.
{
            std::stringstream stream;
            stream << value;
            return stream.str();
        }
to_string() [3/3]
template<typename T , enable_if_t< std::is_convertible< T, std::string >::value, detail::enabler > = detail::dummy> auto detail::to_string (T && value) -> decltype(std::forward<T>(value))
Convert an object to a string (directly forward if this can become a string)
Definition at line 1665 of file CLI11.hpp.
{
            return std::forward<T>(value);
        }
tuple_type_size()
template<typename T , std::size_t I> std::enable_if< I==type_count_base< T >::value, int >::type detail::tuple_type_size () constexpr
0 if the index > tuple size
Definition at line 1826 of file CLI11.hpp.
{
            return 0;
        }
value_string() [1/2]
template<typename T , enable_if_t< std::is_arithmetic< T >::value, detail::enabler > = detail::dummy> std::string detail::value_string (const T & value)
get a string as a convertible value for arithmetic types
get a string as a convertible value for enumerations
Definition at line 1728 of file CLI11.hpp.
{
            return std::to_string(value);
        }
value_string() [2/2]
template<typename T , enable_if_t<!std::is_enum< T >::value &&!std::is_arithmetic< T >::value, detail::enabler > = detail::dummy> auto detail::value_string (const T & value) -> decltype(to_string(value))
for other types just use the regular to_string function
Definition at line 1738 of file CLI11.hpp.
{
            return to_string(value);
        }
Variable Documentation
dummy
enabler detail::dummy = {} constexpr
An instance to use in EnableIf.
Definition at line 1377 of file CLI11.hpp.
{};