SNode.C: CLI Namespace Reference
CLI Namespace Reference
Namespaces
namespace detail
namespace enums
Classes
class CallForCommandline
class CallForShowConfig
class CallForWriteConfig
class ConfigFormatter
class HelpFormatter
Functions
std::string narrow (const std::wstring &str)
Convert a wide string to a narrow string.
std::string narrow (const wchar_t *str)
std::string narrow (const wchar_t *str, std::size_t size)
std::wstring widen (const std::string &str)
Convert a narrow string to a wide string.
std::wstring widen (const char *str)
std::wstring widen (const char *str, std::size_t size)
int argc ()
argc as passed in to this executable.
const char *const * argv ()
argv as passed in to this executable, converted to utf-8 on Windows.
std::size_t escape_detect (std::string &str, std::size_t offset)
std::string & add_quotes_if_needed (std::string &str)
Function Documentation
add_quotes_if_needed()
std::string & CLI::add_quotes_if_needed (std::string & str) inline
Definition at line 985 of file CLI11.hpp.
{
            if ((str.front() != '"' && str.front() != '\'') || str.front() != str.back()) {
                char const quote = str.find('"') < str.find('\'') ? '\'' : '"';
                if (str.find(' ') != std::string::npos) {
                    str.insert(0, 1, quote);
                    str.append(1, quote);
                }
            }
            return str;
        }
argc()
int CLI::argc () inline
argc as passed in to this executable.
Definition at line 539 of file CLI11.hpp.
{
        return static_cast<int>(detail::args().size());
    }
Referenced by App::parse().
argv()
const char *const * CLI::argv () inline
argv as passed in to this executable, converted to utf-8 on Windows.
Definition at line 536 of file CLI11.hpp.
{
        return detail::args().data();
    }
Referenced by App::parse().
escape_detect()
std::size_t CLI::escape_detect (std::string & str, std::size_t offset) inline
Definition at line 973 of file CLI11.hpp.
{
            auto next = str[offset + 1];
            if ((next == '\"') || (next == '\'') || (next == '`')) {
                auto astart = str.find_last_of("-/ \"\'`", offset - 1);
                if (astart != std::string::npos) {
                    if (str[astart] == ((str[offset] == '=') ? '-' : '/'))
                        str[offset] = ' '; // interpret this as a space so the split_up works properly
                }
            }
            return offset + 1;
        }
Referenced by App::parse().
narrow() [1/3]
std::string CLI::narrow (const std::wstring & str) inline
Convert a wide string to a narrow string.
Definition at line 368 of file CLI11.hpp.
{
        return detail::narrow_impl(str.data(), str.size());
    }
References CLI::detail::narrow_impl().
Referenced by App::parse().
narrow() [2/3]
std::string CLI::narrow (const wchar_t * str) inline
Definition at line 372 of file CLI11.hpp.
{
        return detail::narrow_impl(str, std::wcslen(str));
    }
Referenced by detail::maybe_narrow().
narrow() [3/3]
std::string CLI::narrow (const wchar_t * str, std::size_t size) inline
Definition at line 365 of file CLI11.hpp.
{
        return detail::narrow_impl(str, str_size);
    }
References CLI::detail::narrow_impl().
widen() [1/3]
std::wstring CLI::widen (const char * str) inline
Definition at line 383 of file CLI11.hpp.
{
        return detail::widen_impl(str, std::strlen(str));
    }
widen() [2/3]
std::wstring CLI::widen (const char * str, std::size_t size) inline
Definition at line 376 of file CLI11.hpp.
{
        return detail::widen_impl(str, str_size);
    }
References CLI::detail::widen_impl().
widen() [3/3]
std::wstring CLI::widen (const std::string & str) inline
Convert a narrow string to a wide string.
Definition at line 379 of file CLI11.hpp.
{
        return detail::widen_impl(str.data(), str.size());
    }
References CLI::detail::widen_impl().