SNode.C: httputils Namespace Reference
httputils Namespace Reference
Functions
static int from_hex (int ch)
std::string url_decode (const std::string &text)
std::string url_encode (const std::string &text)
std::string & str_trimm (std::string &text)
std::pair< std::string, std::string > str_split (const std::string &base, char c_middle)
std::pair< std::string, std::string > str_split_last (const std::string &base, char c_middle)
std::string to_http_date (struct tm *tm)
struct tm from_http_date (const std::string &http_date)
std::string file_mod_http_date (const std::string &filePath)
std::string::iterator to_lower (std::string &string)
std::string toString (const std::string &method, const std::string &url, const std::string &version, const web::http::CiStringMap< std::string > &queries, const web::http::CiStringMap< std::string > &header, const web::http::CiStringMap< std::string > &trailer, const web::http::CiStringMap< std::string > &cookies, const std::vector< char > &body)
std::string toString (const std::string &version, const std::string &statusCode, const std::string &reason, const web::http::CiStringMap< std::string > &header, const web::http::CiStringMap< web::http::CookieOptions > &cookies, const std::vector< char > &body)
Function Documentation
file_mod_http_date()
std::string httputils::file_mod_http_date (const std::string & filePath)
Definition at line 166 of file http_utils.cpp.
{
        char buf[100];
        struct stat attrib{};
        stat(filePath.c_str(), &attrib); // TODO: to core::system
        (void) strftime(buf, sizeof buf, "%a, %d %b %Y %H:%M:%S %Z", gmtime(&(attrib.st_mtime))); // TODO: to core::system
        errno = 0; // Errno can be modified by strftime even though there is no error
        return std::string(buf);
    }
Referenced by web::http::client::MasterRequest::executeSendFile(), and web::http::server::Response::sendFile().
from_hex()
static int httputils::from_hex (int ch) static
Definition at line 62 of file http_utils.cpp.
{
        return isdigit(ch) != 0 ? ch - '0' : tolower(ch) - 'a' + 10;
    }
Referenced by url_decode().
from_http_date()
struct tm httputils::from_http_date (const std::string & http_date)
Definition at line 157 of file http_utils.cpp.
{
        struct tm tm{};
        strptime(http_date.c_str(), "%a, %d %b %Y %H:%M:%S", &tm);
        tm.tm_zone = "GMT";
        return tm;
    }
str_split()
std::pair< std::string, std::string > httputils::str_split (const std::string & base, char c_middle)
Definition at line 112 of file http_utils.cpp.
{
        std::pair<std::string, std::string> split;
        const unsigned long middle = base.find_first_of(c_middle);
        split.first = base.substr(0, middle);
        if (middle != std::string::npos) {
            split.second = base.substr(middle + 1);
        }
        return split;
    }
Referenced by web::http::Parser::analyzeHeader(), web::http::client::ResponseParser::analyzeHeader(), web::http::server::RequestParser::analyzeHeader(), express::middleware::BasicAuthentication::BasicAuthentication(), web::websocket::server::SocketContextUpgradeFactory::create(), web::http::client::ResponseParser::parseStartLine(), web::http::server::RequestParser::parseStartLine(), web::http::client::SocketContextUpgradeFactorySelector::select(), web::http::server::SocketContextUpgradeFactorySelector::select(), and web::http::decoder::Fields::splitLine().
str_split_last()
std::pair< std::string, std::string > httputils::str_split_last (const std::string & base, char c_middle)
Definition at line 126 of file http_utils.cpp.
{
        std::pair<std::string, std::string> split;
        const unsigned long middle = base.find_last_of(c_middle);
        split.first = base.substr(0, middle);
        if (middle != std::string::npos) {
            split.second = base.substr(middle + 1);
        }
        return split;
    }
Referenced by express::Request::extend().
str_trimm()
std::string & httputils::str_trimm (std::string & text)
Definition at line 105 of file http_utils.cpp.
{
        text.erase(text.find_last_not_of(" \t") + 1);
        text.erase(0, text.find_first_not_of(" \t"));
        return text;
    }
Referenced by web::http::Parser::analyzeHeader(), web::http::client::ResponseParser::analyzeHeader(), web::http::server::RequestParser::analyzeHeader(), web::websocket::server::SocketContextUpgradeFactory::create(), web::http::client::SocketContextUpgradeFactorySelector::select(), web::http::server::SocketContextUpgradeFactorySelector::select(), and web::http::decoder::Fields::splitLine().
to_http_date()
std::string httputils::to_http_date (struct tm * tm)
Definition at line 140 of file http_utils.cpp.
{
        char buf[100];
        if (tm == nullptr) {
            const time_t now = utils::system::time(nullptr);
            tm = utils::system::gmtime(&now);
        } else {
            const time_t time = utils::system::mktime(tm);
            tm = utils::system::gmtime(&time);
        }
        (void) strftime(buf, sizeof buf, "%a, %d %b %Y %H:%M:%S %Z", tm);
        errno = 0; // Errno can be modified by strftime even though there is no error
        return std::string(buf);
    }
References utils::system::gmtime(), and utils::system::time().
Referenced by web::http::server::Response::clearCookie(), web::http::client::MasterRequest::executeSendHeader(), and web::http::server::Response::sendHeader().
to_lower()
std::string::iterator httputils::to_lower (std::string & string)
Definition at line 178 of file http_utils.cpp.
{
        return std::transform(string.begin(), string.end(), string.begin(), ::tolower);
    }
Referenced by web::http::client::SocketContextUpgradeFactorySelector::select(), web::http::client::SocketContextUpgradeFactorySelector::select(), and web::http::server::SocketContextUpgradeFactorySelector::select().
toString() [1/2]
std::string httputils::toString (const std::string & method, const std::string & url, const std::string & version, const web::http::CiStringMap< std::string > & queries, const web::http::CiStringMap< std::string > & header, const web::http::CiStringMap< std::string > & trailer, const web::http::CiStringMap< std::string > & cookies, const std::vector< char > & body)
Definition at line 182 of file http_utils.cpp.
{
        const int prefixLength = 9;
        int keyLength = 0;
        for (const auto& [key, value] : queries) {
            keyLength = std::max(keyLength, static_cast<int>(key.size()));
        }
        for (const auto& [key, value] : header) {
            keyLength = std::max(keyLength, static_cast<int>(key.size()));
        }
        for (const auto& [key, value] : trailer) {
            keyLength = std::max(keyLength, static_cast<int>(key.size()));
        }
        for (const auto& [key, value] : cookies) {
            keyLength = std::max(keyLength, static_cast<int>(key.size()));
        }
        std::stringstream requestStream;
        requestStream << std::setw(prefixLength) << "Request"
                      << ": " << std::setw(keyLength) << "Method"
                      << " : " << method << "\n";
        requestStream << std::setw(prefixLength) << ""
                      << ": " << std::setw(keyLength) << "Url"
                      << " : " << url << "\n";
        requestStream << std::setw(prefixLength) << ""
                      << ": " << std::setw(keyLength) << "Version"
                      << " : " << version << "\n";
        std::string prefix;
        if (!queries.empty()) {
            prefix = "Queries";
            for (const auto& [query, value] : queries) {
                requestStream << std::setw(prefixLength) << prefix << ": " << std::setw(keyLength) << query << " : " << value << "\n";
                prefix = "";
            }
        }
        if (!header.empty()) {
            prefix = "Header";
            for (const auto& [field, value] : header) {
                requestStream << std::setw(prefixLength) << prefix << ": " << std::setw(keyLength) << field << " : " << value << "\n";
                prefix = "";
            }
        }
        if (!trailer.empty()) {
            prefix = "Trailer";
            for (const auto& [field, value] : trailer) {
                requestStream << std::setw(prefixLength) << prefix << ": " << std::setw(keyLength) << field << " : " << value << "\n";
                prefix = "";
            }
        }
        if (!cookies.empty()) {
            prefix = "Cookies";
            for (const auto& [cookie, value] : cookies) {
                requestStream << std::setw(prefixLength) << prefix << ": " << std::setw(keyLength) << cookie << " : " << value << "\n";
                prefix = "";
            }
        }
        if (!body.empty()) {
            prefix = "Body";
            requestStream << std::setw(prefixLength) << prefix << utils::hexDump(body, prefixLength) << "\n";
        }
        std::string string = requestStream.str();
        if (!string.empty()) {
            string.pop_back();
        }
        return string;
    }
References utils::hexDump().
Referenced by web::http::client::MasterRequest::executeUpgrade(), web::http::client::SocketContext::requestPrepared(), web::http::server::Response::upgrade(), and express::middleware::VerboseRequest::VerboseRequest().
toString() [2/2]
std::string httputils::toString (const std::string & version, const std::string & statusCode, const std::string & reason, const web::http::CiStringMap< std::string > & header, const web::http::CiStringMap< web::http::CookieOptions > & cookies, const std::vector< char > & body)
Definition at line 265 of file http_utils.cpp.
{
        const int prefixLength = 9;
        int keyLength = 0;
        for (const auto& [key, value] : header) {
            keyLength = std::max(keyLength, static_cast<int>(key.size()));
        }
        for (const auto& [key, value] : cookies) {
            keyLength = std::max(keyLength, static_cast<int>(key.size()));
        }
        std::stringstream requestStream;
        requestStream << std::setw(prefixLength) << "Response"
                      << ": " << std::setw(keyLength) << "Version"
                      << " : " << version << "\n";
        requestStream << std::setw(prefixLength) << ""
                      << ": " << std::setw(keyLength) << "Status"
                      << " : " << statusCode << "\n";
        requestStream << std::setw(prefixLength) << ""
                      << ": " << std::setw(keyLength) << "Reason"
                      << " : " << reason << "\n";
        std::string prefix;
        if (!header.empty()) {
            prefix = "Header";
            for (const auto& [field, value] : header) {
                requestStream << std::setw(prefixLength) << prefix << ": " << std::setw(keyLength) << field << " : " << value << "\n";
                prefix = "";
            }
        }
        if (!cookies.empty()) {
            prefix = "Cookies";
            for (const auto& [cookie, options] : cookies) {
                requestStream << std::setw(prefixLength) << prefix << ": " << std::setw(keyLength) << cookie << " : " << options.getValue()
                              << "\n";
                for (const auto& [optionKey, optionValue] : options.getOptions()) {
                    requestStream << std::setw(prefixLength) << ""
                                  << ":" << std::setw(keyLength) << ""
                                  << " : " << optionKey << "=" << optionValue << "\n";
                }
                prefix = "";
            }
        }
        if (!body.empty()) {
            prefix = "Body";
            requestStream << std::setw(prefixLength) << prefix << utils::hexDump(body, prefixLength) << "\n";
        }
        std::string string = requestStream.str();
        if (!string.empty()) {
            string.pop_back();
        }
        return string;
    }
References web::http::CookieOptions::getOptions(), web::http::CookieOptions::getValue(), and utils::hexDump().
Referenced by web::http::server::Response::upgrade(), and web::http::client::MasterRequest::upgrade().
url_decode()
std::string httputils::url_decode (const std::string & text)
Definition at line 66 of file http_utils.cpp.
{
        std::string escaped;
        for (std::string::const_iterator i = text.begin(), n = text.end(); i != n; ++i) {
            const std::string::value_type c = (*i);
            if (c == '%') {
                if ((i[1] != 0) && (i[2] != 0)) {
                    escaped += static_cast<char>(from_hex(i[1]) << 4 | from_hex(i[2]));
                    i += 2;
                }
            } else if (c == '+') {
                escaped += ' ';
            } else {
                escaped += c;
            }
        }
        return escaped;
    }
References from_hex().
Referenced by express::Request::extend().
url_encode()
std::string httputils::url_encode (const std::string & text)
Definition at line 87 of file http_utils.cpp.
{
        std::ostringstream escaped;
        escaped.fill('0'); // cppcheck-suppress ignoredReturnValue
        escaped << std::hex;
        for (const char c : text) {
            if ((isalnum(c) != 0) || c == '-' || c == '_' || c == '.' || c == '~') {
                escaped << c;
            } else {
                escaped << std::uppercase;
                escaped << '%' << std::setw(2) << static_cast<unsigned char>(c);
                escaped << std::nouppercase;
            }
        }
        return escaped.str();
    }
Referenced by web::http::client::MasterRequest::executeSendHeader().