SNode.C: core::socket::stream::tls Namespace Reference
core::socket::stream::tls Namespace Reference
Classes
class SocketAcceptor
class SocketConnection
class SocketConnector
class SocketReader
class SocketWriter
struct SslConfig
class TLSHandshake
class TLSShutdown
Functions
static int password_callback (char *buf, int size, int, void *u)
static int verify_callback (int preverify_ok, X509_STORE_CTX *ctx)
SSL_CTX * ssl_ctx_new (const SslConfig &sslConfig)
SSL_CTX * ssl_ctx_new (const std::shared_ptr< net::config::ConfigTlsServer > &configTls)
SSL_CTX * ssl_ctx_new (const std::shared_ptr< net::config::ConfigTlsClient > &configTls)
SSL_CTX * ssl_ctx_new (const std::map< std::string, std::variant< std::string, bool, ssl_option_t > > &sniCert)
SSL_CTX * ssl_set_ssl_ctx (SSL *ssl, SSL_CTX *sslCtx)
void ssl_ctx_free (SSL_CTX *ctx)
void ssl_set_sni (SSL *ssl, const std::shared_ptr< net::config::ConfigTlsClient > &configTls)
std::set< std::string > ssl_get_sans (SSL_CTX *sslCtx)
std::string ssl_get_servername_from_client_hello (SSL *ssl)
void ssl_log (const std::string &message, int sslErr)
void ssl_log_error (const std::string &message)
void ssl_log_warning (const std::string &message)
void ssl_log_info (const std::string &message)
bool match (const char *first, const char *second)
Function Documentation
match()
bool core::socket::stream::tls::match (const char * first, const char * second)
Definition at line 409 of file ssl_utils.cpp.
{
        // If we reach at the end of both strings, we are done
        if (*first == '\0' && *second == '\0')
            return true;
        // Make sure to eliminate consecutive '*'
        if (*first == '*') {
            while (*(first + 1) == '*')
                first++;
        }
        // Make sure that the characters after '*' are present
        // in second string. This function assumes that the
        // first string will not contain two consecutive '*'
        if (*first == '*' && *(first + 1) != '\0' && *second == '\0')
            return false;
        // If the first string contains '?', or current
        // characters of both strings match
        if (*first == '?' || *first == *second)
            return match(first + 1, second + 1);
        // If there is *, then there are two possibilities
        // a) We consider current character of second string
        // b) We ignore current character of second string.
        if (*first == '*')
            return match(first + 1, second) || match(first, second + 1);
        return false;
    }
References match().
Referenced by core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::getMasterSniCtx(), core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::getPoolSniCtx(), and match().
password_callback()
static int core::socket::stream::tls::password_callback (char * buf, int size, int , void * u) static
Definition at line 51 of file ssl_utils.cpp.
{
        strncpy(buf, static_cast<char*>(u), static_cast<std::size_t>(size));
        buf[size - 1] = '\0';
        memset(u, 0, ::strlen(static_cast<char*>(u))); // garble Password
        free(u);
        return static_cast<int>(::strlen(buf));
    }
Referenced by ssl_ctx_new().
ssl_ctx_free()
void core::socket::stream::tls::ssl_ctx_free (SSL_CTX * ctx)
Definition at line 258 of file ssl_utils.cpp.
{
        if (ctx != nullptr) {
            SSL_CTX_free(ctx);
        }
    }
Referenced by core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::~SocketAcceptor(), and core::socket::stream::tls::SocketConnector< PhysicalSocketClientT, ConfigT >::~SocketConnector().
ssl_ctx_new() [1/4]
SSL_CTX * core::socket::stream::tls::ssl_ctx_new (const SslConfig & sslConfig)
Definition at line 121 of file ssl_utils.cpp.
{
        static int sslSessionCtxId = 1;
        SSL_CTX* ctx = SSL_CTX_new(sslConfig.server ? TLS_server_method() : TLS_client_method());
        if (ctx != nullptr) {
#if OPENSSL_VERSION_NUMBER >= 0x30000000L
            SSL_CTX_set_options(ctx, SSL_OP_IGNORE_UNEXPECTED_EOF);
#endif
            SSL_CTX_set_read_ahead(ctx, 1);
            SSL_CTX_set_mode(ctx, SSL_MODE_ENABLE_PARTIAL_WRITE);
            SSL_CTX_set_mode(ctx, SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER);
            bool sslErr = false;
            if (sslConfig.server) {
                SSL_CTX_set_session_id_context(ctx, reinterpret_cast<const unsigned char*>(&sslSessionCtxId), sizeof(sslSessionCtxId));
                sslSessionCtxId++;
            }
            if (!sslConfig.caFile.empty() || !sslConfig.caDir.empty()) {
                if (SSL_CTX_load_verify_locations(ctx,
                                                  !sslConfig.caFile.empty() ? sslConfig.caFile.c_str() : nullptr,
                                                  !sslConfig.caDir.empty() ? sslConfig.caDir.c_str() : nullptr) == 0) {
                    ssl_log_error("Can not load CA certificate or non default CA directory: ca-cert-file '" + sslConfig.caFile +
                                  "' : ca-cert-dir '" + sslConfig.caDir + "'");
                    sslErr = true;
                } else {
                    LOG(TRACE) << "CA certificate loaded: ca-cert-file '" << sslConfig.caFile << "' : ca-cert-dir '"
                               << sslConfig.caDir + "'";
                }
            } else {
                LOG(TRACE) << "Neither using ca-cert-file nor ca-cert-dir";
            }
            if (!sslErr && sslConfig.useDefaultCaDir) {
                if (SSL_CTX_set_default_verify_paths(ctx) == 0) {
                    ssl_log_error("Can not load default CA directory");
                    sslErr = true;
                } else {
                    ssl_log_info("Using default CA directory");
                }
            } else {
                LOG(TRACE) << "Not using default CA directory";
            }
            if (!sslErr) {
                if (sslConfig.useDefaultCaDir || !sslConfig.caFile.empty() || !sslConfig.caDir.empty()) {
                    SSL_CTX_set_verify_depth(ctx, 5);
                    SSL_CTX_set_verify(ctx, SSL_VERIFY_FLAGS, verify_callback);
                }
                if (!sslConfig.certChain.empty()) {
                    if (SSL_CTX_use_certificate_chain_file(ctx, sslConfig.certChain.c_str()) == 0) {
                        ssl_log_error("Can not load certificate chain: " + sslConfig.certChain);
                        sslErr = true;
                    } else if (!sslConfig.certChainKey.empty()) {
                        if (!sslConfig.password.empty()) {
                            SSL_CTX_set_default_passwd_cb(ctx, password_callback);
                            SSL_CTX_set_default_passwd_cb_userdata(ctx, ::strdup(sslConfig.password.c_str()));
                        }
                        if (SSL_CTX_use_PrivateKey_file(ctx, sslConfig.certChainKey.c_str(), SSL_FILETYPE_PEM) == 0) {
                            ssl_log_error("Can not load private key: " + sslConfig.certChainKey);
                            sslErr = true;
                        } else if (!SSL_CTX_check_private_key(ctx)) {
                            ssl_log_error("Private key not consistent with CA files: " + sslConfig.certChainKey);
                            sslErr = true;
                        } else {
                            LOG(TRACE) << "Private key loaded: " << sslConfig.certChainKey;
                        }
                    }
                    if (!sslErr) {
                        LOG(TRACE) << "Certificate chain loaded: " << sslConfig.certChain;
                    }
                }
            }
            if (!sslErr) {
                if (sslConfig.sslOptions != 0) {
                    SSL_CTX_set_options(ctx, sslConfig.sslOptions);
                }
                if (!sslConfig.cipherList.empty()) {
                    SSL_CTX_set_cipher_list(ctx, sslConfig.cipherList.c_str());
                }
            }
            if (sslErr) {
                SSL_CTX_free(ctx);
                ctx = nullptr;
            }
        } else {
            ssl_log_error("SSL CTX not created");
        }
        return ctx;
    }
References core::socket::stream::tls::SslConfig::caDir, core::socket::stream::tls::SslConfig::caFile, core::socket::stream::tls::SslConfig::certChain, core::socket::stream::tls::SslConfig::certChainKey, core::socket::stream::tls::SslConfig::cipherList, core::socket::stream::tls::SslConfig::password, password_callback(), core::socket::stream::tls::SslConfig::server, ssl_log_error(), ssl_log_info(), core::socket::stream::tls::SslConfig::sslOptions, core::socket::stream::tls::SslConfig::useDefaultCaDir, and verify_callback().
Referenced by ssl_ctx_new(), ssl_ctx_new(), and ssl_ctx_new().
ssl_ctx_new() [2/4]
SSL_CTX * core::socket::stream::tls::ssl_ctx_new (const std::map< std::string, std::variant< std::string, bool, ssl_option_t > > & sniCert)
Definition at line 221 of file ssl_utils.cpp.
{
        SslConfig sslConfig(true);
        for (auto& [key, value] : sniCert) {
            if (key == "CertChain") {
                sslConfig.certChain = std::get<std::string>(value);
            } else if (key == "CertKey") {
                sslConfig.certChainKey = std::get<std::string>(value);
            } else if (key == "CertKeyPassword") {
                sslConfig.password = std::get<std::string>(value);
            } else if (key == "CaCertFile") {
                sslConfig.caFile = std::get<std::string>(value);
            } else if (key == "CaCertDir") {
                sslConfig.caDir = std::get<std::string>(value);
            } else if (key == "UseDefaultCaDir") {
                sslConfig.useDefaultCaDir = std::get<bool>(value);
            } else if (key == "CipherList") {
                sslConfig.cipherList = std::get<std::string>(value);
            } else if (key == "SslOptions") {
                sslConfig.sslOptions = std::get<ssl_option_t>(value);
            }
        }
        return ssl_ctx_new(sslConfig);
    }
References core::socket::stream::tls::SslConfig::caDir, core::socket::stream::tls::SslConfig::caFile, core::socket::stream::tls::SslConfig::certChain, core::socket::stream::tls::SslConfig::certChainKey, core::socket::stream::tls::SslConfig::cipherList, core::socket::stream::tls::SslConfig::password, ssl_ctx_new(), core::socket::stream::tls::SslConfig::SslConfig(), core::socket::stream::tls::SslConfig::sslOptions, and core::socket::stream::tls::SslConfig::useDefaultCaDir.
ssl_ctx_new() [3/4]
SSL_CTX * core::socket::stream::tls::ssl_ctx_new (const std::shared_ptr< net::config::ConfigTlsClient > & configTls)
Definition at line 217 of file ssl_utils.cpp.
{
        return ssl_ctx_new(SslConfig(false, configTls));
    }
References ssl_ctx_new(), and core::socket::stream::tls::SslConfig::SslConfig().
ssl_ctx_new() [4/4]
SSL_CTX * core::socket::stream::tls::ssl_ctx_new (const std::shared_ptr< net::config::ConfigTlsServer > & configTls)
Definition at line 213 of file ssl_utils.cpp.
{
        return ssl_ctx_new(SslConfig(true, configTls));
    }
References ssl_ctx_new(), and core::socket::stream::tls::SslConfig::SslConfig().
ssl_get_sans()
std::set< std::string > core::socket::stream::tls::ssl_get_sans (SSL_CTX * sslCtx)
Definition at line 270 of file ssl_utils.cpp.
{
        std::set<std::string> sans;
        if (sslCtx != nullptr) {
            X509* x509 = SSL_CTX_get0_certificate(sslCtx);
            if (x509 != nullptr) {
                GENERAL_NAMES* subjectAltNames =
                    static_cast<GENERAL_NAMES*>(X509_get_ext_d2i(x509, NID_subject_alt_name, nullptr, nullptr));
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wused-but-marked-unused"
#endif
                int32_t altNameCount = sk_GENERAL_NAME_num(subjectAltNames);
#ifdef __clang__
#pragma clang diagnostic pop
#endif
                for (int32_t i = 0; i < altNameCount; ++i) {
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wused-but-marked-unused"
#endif
                    GENERAL_NAME* generalName = sk_GENERAL_NAME_value(subjectAltNames, i);
#ifdef __clang__
#pragma clang diagnostic pop
#endif
                    if (generalName->type == GEN_DNS || generalName->type == GEN_URI || generalName->type == GEN_EMAIL) {
                        std::string subjectAltName =
                            std::string(reinterpret_cast<const char*>(ASN1_STRING_get0_data(generalName->d.dNSName)),
                                        static_cast<std::size_t>(ASN1_STRING_length(generalName->d.dNSName)));
                        sans.insert(subjectAltName);
                    }
                }
#ifdef __clang__
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wused-but-marked-unused"
#endif
                sk_GENERAL_NAME_pop_free(subjectAltNames, GENERAL_NAME_free);
#ifdef __clang__
#pragma clang diagnostic pop
#endif
            }
        }
        return sans;
    }
Referenced by core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::initAcceptEvent().
ssl_get_servername_from_client_hello()
std::string core::socket::stream::tls::ssl_get_servername_from_client_hello (SSL * ssl)
Definition at line 317 of file ssl_utils.cpp.
{
        const unsigned char* ext;
        size_t ext_len;
        size_t p = 0;
        size_t server_name_list_len;
        size_t server_name_len;
        if (!SSL_client_hello_get0_ext(ssl, TLSEXT_TYPE_server_name, &ext, &ext_len)) {
            return "";
        }
        /* length (2 bytes) + type (1) + length (2) + server name (1+) */
        if (ext_len < 6) {
            return "";
        }
        /* Fetch Server Name list length */
        server_name_list_len = static_cast<size_t>((ext[p] << 8) + ext[p + 1]);
        p += 2;
        if (p + server_name_list_len != ext_len) {
            return "";
        }
        /* Fetch Server Name Type */
        if (ext[p] != TLSEXT_NAMETYPE_host_name) {
            return "";
        }
        p++;
        /* Fetch Server Name Length */
        server_name_len = static_cast<size_t>((ext[p] << 8) + ext[p + 1]);
        p += 2;
        if (p + server_name_len != ext_len) {
            return "";
        }
        /* ext_len >= 6 && p == 5 */
        /* Finally fetch Server Name */
        return std::string(reinterpret_cast<const char*>(ext + p), ext_len - p);
    }
Referenced by core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::clientHelloCallback().
ssl_log()
void core::socket::stream::tls::ssl_log (const std::string & message, int sslErr)
Definition at line 360 of file ssl_utils.cpp.
{
        utils::PreserveErrno preserveErrno;
        switch (sslErr) {
            case SSL_ERROR_NONE:
                [[fallthrough]];
            case SSL_ERROR_ZERO_RETURN:
                ssl_log_info(message);
                break;
            case SSL_ERROR_SYSCALL:
                if (errno != 0) {
                    ssl_log_error(message);
                } else {
                    ssl_log_info(message);
                }
                break;
            default:
                ssl_log_warning(message);
                break;
        }
    }
References ssl_log_error(), ssl_log_info(), and ssl_log_warning().
Referenced by core::socket::stream::tls::SocketConnection< PhysicalSocketT >::doWriteShutdown(), core::socket::stream::tls::SocketReader< PhysicalSocketT >::read(), and core::socket::stream::tls::SocketWriter< PhysicalSocketT >::write().
ssl_log_error()
void core::socket::stream::tls::ssl_log_error (const std::string & message)
Definition at line 382 of file ssl_utils.cpp.
{
        PLOG(TRACE) << message;
        unsigned long errorCode = 0;
        while ((errorCode = ERR_get_error()) != 0) {
            LOG(TRACE) << "|-- with SSL " << ERR_error_string(errorCode, nullptr);
        }
    }
Referenced by ssl_ctx_new(), and ssl_log().
ssl_log_info()
void core::socket::stream::tls::ssl_log_info (const std::string & message)
Definition at line 400 of file ssl_utils.cpp.
{
        PLOG(TRACE) << message;
        unsigned long errorCode = 0;
        while ((errorCode = ERR_get_error()) != 0) {
            LOG(TRACE) << "|-- with SSL " << ERR_error_string(errorCode, nullptr);
        }
    }
Referenced by ssl_ctx_new(), and ssl_log().
ssl_log_warning()
void core::socket::stream::tls::ssl_log_warning (const std::string & message)
Definition at line 391 of file ssl_utils.cpp.
{
        LOG(TRACE) << message;
        unsigned long errorCode = 0;
        while ((errorCode = ERR_get_error()) != 0) {
            LOG(TRACE) << "|-- with SSL " << ERR_error_string(errorCode, nullptr);
        }
    }
Referenced by ssl_log().
ssl_set_sni()
void core::socket::stream::tls::ssl_set_sni (SSL * ssl, const std::shared_ptr< net::config::ConfigTlsClient > & configTls)
Definition at line 264 of file ssl_utils.cpp.
{
        if (!configTls->getSni().empty()) {
            SSL_set_tlsext_host_name(ssl, configTls->getSni().data());
        }
    }
References net::config::ConfigTlsClient::getSni().
ssl_set_ssl_ctx()
SSL_CTX * core::socket::stream::tls::ssl_set_ssl_ctx (SSL * ssl, SSL_CTX * sslCtx)
Definition at line 247 of file ssl_utils.cpp.
{
        SSL_CTX* newSslCtx = SSL_set_SSL_CTX(ssl, sslCtx);
        SSL_clear_options(ssl, 0xFFFFFFFFL);
        SSL_set_options(ssl, SSL_CTX_get_options(sslCtx));
        SSL_set_verify(ssl, SSL_CTX_get_verify_mode(sslCtx), SSL_CTX_get_verify_callback(sslCtx));
        SSL_set_verify_depth(ssl, SSL_CTX_get_verify_depth(sslCtx));
        SSL_set_mode(ssl, SSL_CTX_get_mode(sslCtx));
        return newSslCtx;
    }
Referenced by core::socket::stream::tls::SocketAcceptor< PhysicalSocketServerT, ConfigT >::clientHelloCallback().
verify_callback()
static int core::socket::stream::tls::verify_callback (int preverify_ok, X509_STORE_CTX * ctx) static
Definition at line 61 of file ssl_utils.cpp.
{
        X509* curr_cert = X509_STORE_CTX_get_current_cert(ctx);
        int depth = X509_STORE_CTX_get_error_depth(ctx);
        char buf[256];
        X509_NAME_oneline(X509_get_subject_name(curr_cert), buf, 256);
        if (preverify_ok) {
            LOG(TRACE) << "SSL/TLS verify ok at depth=" << depth << ": " << buf;
        } else {
            int err = X509_STORE_CTX_get_error(ctx);
            LOG(TRACE) << "SSL/TLS verify error at depth=" << depth << ": verifyErr=" << err << ", " << X509_verify_cert_error_string(err);
            /*
             * At this point, err contains the last verification error. We can use
             * it for something special
             */
            switch (err) {
                case X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT:
                    X509_NAME_oneline(X509_get_issuer_name(curr_cert), buf, 256);
                    LOG(TRACE) << "no issuer certificate for issuer= " << buf;
                    break;
                default:
                    break;
            }
        }
        return preverify_ok;
    }
Referenced by ssl_ctx_new().