SNode.C: CLI::detail Namespace Reference
CLI::detail Namespace Reference
Functions
std::string narrow_impl (const wchar_t *str, std::size_t str_size)
std::wstring widen_impl (const char *str, std::size_t str_size)
const std::vector< const char * > & args ()
Command-line arguments, as passed in to this executable, converted to utf-8 on Windows.
std::vector< std::string > split (const std::string &s, char delim)
Split a string by a delim.
template<typename T >
std::string join (const T &v, std::string delim=",")
Simple function to join a string.
template<typename T , typename Callable , typename = typename std::enable_if<!std::is_constructible<std::string, Callable>::value>::type>
std::string join (const T &v, Callable func, std::string delim=",")
Simple function to join a string from processed elements.
template<typename T >
std::string rjoin (const T &v, std::string delim=",")
Join a string in reverse order.
std::string & ltrim (std::string &str)
Trim whitespace from left of string.
std::string & ltrim (std::string &str, const std::string &filter)
Trim anything from left of string.
std::string & rtrim (std::string &str)
Trim whitespace from right of string.
std::string & rtrim (std::string &str, const std::string &filter)
Trim anything from right of string.
std::string & trim (std::string &str)
Trim whitespace from string.
std::string & trim (std::string &str, const std::string filter)
Trim anything from string.
std::string trim_copy (const std::string &str)
Make a copy of the string and then trim it.
std::string & remove_quotes (std::string &str)
remove quotes at the front and back of a string either '"' or '\''
std::string fix_newlines (const std::string &leader, std::string input)
std::string trim_copy (const std::string &str, const std::string &filter)
Make a copy of the string and then trim it, any filter string can be used (any char in string is filtered)
std::ostream & format_help (std::ostream &out, std::string name, const std::string &description, std::size_t wid)
Print a two part "help" string.
std::ostream & format_aliases (std::ostream &out, const std::vector< std::string > &aliases, std::size_t wid)
Print subcommand aliases.
template<typename T >
bool valid_first_char (T c)
template<typename T >
bool valid_later_char (T c)
Verify following characters of an option.
bool valid_name_string (const std::string &str)
Verify an option/subcommand name.
bool valid_alias_name_string (const std::string &str)
Verify an app name.
bool is_separator (const std::string &str)
check if a string is a container segment separator (empty or "%%")
bool isalpha (const std::string &str)
Verify that str consists of letters only.
std::string to_lower (std::string str)
Return a lower case version of a string.
std::string remove_underscore (std::string str)
remove underscores from a string
std::string find_and_replace (std::string str, std::string from, std::string to)
Find and replace a substring with another substring.
bool has_default_flag_values (const std::string &flags)
check if the flag definitions has possible false flags
void remove_default_flag_values (std::string &flags)
std::ptrdiff_t find_member (std::string name, const std::vector< std::string > names, bool ignore_case=false, bool ignore_underscore=false)
Check if a string is a member of a list of strings and optionally ignore case or ignore underscores.
template<typename Callable >
std::string find_and_modify (std::string str, std::string trigger, Callable modify)
trim (str)
while (!str.empty())
Variables
constexpr int expected_max_vector_size {1 << 29}
auto find_ws
std::vector< std::string > output
bool embeddedQuote = false
char keyChar = ' '
Function Documentation
args()
const std::vector< const char * > & CLI::detail::args () inline
Command-line arguments, as passed in to this executable, converted to utf-8 on Windows.
Definition at line 444 of file CLI11.hpp.
{
            // This function uses initialization via lambdas extensively to take advantage of the thread safety of static
            // variable initialization [stmt.dcl.3]
#ifdef _WIN32
            static const std::vector<const char*> static_args = [] {
                static const std::vector<std::string> static_args_as_strings = [] {
                    // On Windows, take arguments from GetCommandLineW and convert them to utf-8.
                    std::vector<std::string> args_as_strings;
                    int argc = 0;
                    auto deleter = [](wchar_t** ptr) {
                        LocalFree(ptr);
                    };
                    // NOLINTBEGIN(*-avoid-c-arrays)
                    auto wargv = std::unique_ptr<wchar_t*[], decltype(deleter)>(CommandLineToArgvW(GetCommandLineW(), &argc), deleter);
                    // NOLINTEND(*-avoid-c-arrays)
                    if (wargv == nullptr) {
                        throw std::runtime_error("CommandLineToArgvW failed with code " + std::to_string(GetLastError()));
                    }
                    args_as_strings.reserve(static_cast<size_t>(argc));
                    for (size_t i = 0; i < static_cast<size_t>(argc); ++i) {
                        args_as_strings.push_back(narrow(wargv[i]));
                    }
                    return args_as_strings;
                }();
                std::vector<const char*> static_args_result;
                static_args_result.reserve(static_args_as_strings.size());
                for (const auto& arg : static_args_as_strings) {
                    static_args_result.push_back(arg.data());
                }
                return static_args_result;
            }();
            return static_args;
#elif defined(__APPLE__)
            return static_args;
#else
            static const std::vector<const char*> static_args = [] {
                static const std::vector<char> static_cmdline = [] {
                    // On posix, retrieve arguments from /proc/self/cmdline, separated by null terminators.
                    std::vector<char> cmdline;
                    auto deleter = [](FILE* f) {
                        std::fclose(f);
                    };
                    std::unique_ptr<FILE, decltype(deleter)> const fp_unique(std::fopen("/proc/self/cmdline", "r"), deleter);
                    FILE* fp = fp_unique.get();
                    if (!fp) {
                        throw std::runtime_error("could not open /proc/self/cmdline for reading"); // LCOV_EXCL_LINE
                    }
                    size_t size = 0;
                    while (std::feof(fp) == 0) {
                        cmdline.resize(size + 128);
                        size += std::fread(cmdline.data() + size, 1, 128, fp);
                        if (std::ferror(fp) != 0) {
                            throw std::runtime_error("error during reading /proc/self/cmdline"); // LCOV_EXCL_LINE
                        }
                    }
                    cmdline.resize(size);
                    return cmdline;
                }();
                std::size_t const argc = static_cast<std::size_t>(std::count(static_cmdline.begin(), static_cmdline.end(), '\0'));
                std::vector<const char*> static_args_result;
                static_args_result.reserve(argc);
                for (auto it = static_cmdline.begin(); it != static_cmdline.end(); it = std::find(it, static_cmdline.end(), '\0') + 1) {
                    static_args_result.push_back(static_cmdline.data() + (it - static_cmdline.begin()));
                }
                return static_args_result;
            }();
            return static_args;
#endif
        }
find_and_modify()
template<typename Callable > std::string CLI::detail::find_and_modify (std::string str, std::string trigger, Callable modify) inline
Find a trigger string and call a modify callable function that takes the current string and starting position of the trigger and returns the position in the string to search for the next trigger string
Definition at line 732 of file CLI11.hpp.
{
            std::size_t start_pos = 0;
            while ((start_pos = str.find(trigger, start_pos)) != std::string::npos) {
                start_pos = modify(str, start_pos);
            }
            return str;
        }
find_and_replace()
std::string CLI::detail::find_and_replace (std::string str, std::string from, std::string to) inline
Find and replace a substring with another substring.
Referenced by CLI::HelpFormatter::make_expanded(), and Formatter::make_expanded().
find_member()
std::ptrdiff_t CLI::detail::find_member (std::string name, const std::vector< std::string > names, bool ignore_case = false, bool ignore_underscore = false) inline
Check if a string is a member of a list of strings and optionally ignore case or ignore underscores.
fix_newlines()
std::string CLI::detail::fix_newlines (const std::string & leader, std::string input) inline
Add a leader to the beginning of all new lines (nothing is added at the start of the first line). "; " would be for ini files
Can't use Regex, or this would be a subs.
Referenced by CLI::ConfigFormatter::to_config(), and ConfigBase::to_config().
format_aliases()
std::ostream & CLI::detail::format_aliases (std::ostream & out, const std::vector< std::string > & aliases, std::size_t wid) inline
Print subcommand aliases.
format_help()
std::ostream & CLI::detail::format_help (std::ostream & out, std::string name, const std::string & description, std::size_t wid) inline
Print a two part "help" string.
Referenced by Formatter::make_option(), CLI::HelpFormatter::make_subcommand(), and Formatter::make_subcommand().
has_default_flag_values()
bool CLI::detail::has_default_flag_values (const std::string & flags) inline
check if the flag definitions has possible false flags
Definition at line 719 of file CLI11.hpp.
{
            return (flags.find_first_of("{!") != std::string::npos);
        }
Referenced by App::_add_flag_internal().
is_separator()
bool CLI::detail::is_separator (const std::string & str) inline
check if a string is a container segment separator (empty or "%%")
Definition at line 689 of file CLI11.hpp.
{
            static const std::string sep("%%");
            return (str.empty() || str == sep);
        }
isalpha()
bool CLI::detail::isalpha (const std::string & str) inline
Verify that str consists of letters only.
Definition at line 695 of file CLI11.hpp.
{
            return std::all_of(str.begin(), str.end(), [](char c) {
                return std::isalpha(c, std::locale());
            });
        }
join() [1/2]
template<typename T , typename Callable , typename = typename std::enable_if<!std::is_constructible<std::string, Callable>::value>::type> std::string CLI::detail::join (const T & v, Callable func, std::string delim = ",")
Simple function to join a string from processed elements.
Definition at line 585 of file CLI11.hpp.
{
            std::ostringstream s;
            auto beg = std::begin(v);
            auto end = std::end(v);
            auto loc = s.tellp();
            while (beg != end) {
                auto nloc = s.tellp();
                if (nloc > loc) {
                    s << delim;
                    loc = nloc;
                }
                s << func(*beg++);
            }
            return s.str();
        }
join() [2/2]
template<typename T > std::string CLI::detail::join (const T & v, std::string delim = ",")
Simple function to join a string.
Definition at line 569 of file CLI11.hpp.
{
            std::ostringstream s;
            auto beg = std::begin(v);
            auto end = std::end(v);
            if (beg != end)
                s << *beg++;
            while (beg != end) {
                s << delim << *beg++;
            }
            return s.str();
        }
ltrim() [1/2]
std::string & CLI::detail::ltrim (std::string & str) inline
Trim whitespace from left of string.
Referenced by trim().
ltrim() [2/2]
std::string & CLI::detail::ltrim (std::string & str, const std::string & filter) inline
Trim anything from left of string.
Referenced by trim().
narrow_impl()
std::string CLI::detail::narrow_impl (const wchar_t * str, std::size_t str_size) inline
Definition at line 297 of file CLI11.hpp.
{
#if CLI11_HAS_CODECVT
#ifdef _WIN32
            return std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>>().to_bytes(str, str + str_size);
#else
            return std::wstring_convert<std::codecvt_utf8<wchar_t>>().to_bytes(str, str + str_size);
#endif // _WIN32
#else  // CLI11_HAS_CODECVT
            (void) str_size;
            std::mbstate_t state = std::mbstate_t();
            const wchar_t* it = str;
            std::string old_locale = std::setlocale(LC_ALL, nullptr);
            auto sg = scope_guard([&] {
                std::setlocale(LC_ALL, old_locale.c_str());
            });
            set_unicode_locale();
            std::size_t new_size = std::wcsrtombs(nullptr, &it, 0, &state);
            if (new_size == static_cast<std::size_t>(-1)) {
                throw std::runtime_error("CLI::narrow: conversion error in std::wcsrtombs at offset " + std::to_string(it - str));
            }
            std::string result(new_size, '\0');
            std::wcsrtombs(const_cast<char*>(result.data()), &str, new_size, &state);
            return result;
#endif // CLI11_HAS_CODECVT
        }
Referenced by CLI::narrow(), and CLI::narrow().
remove_default_flag_values()
void CLI::detail::remove_default_flag_values (std::string & flags) inline
Referenced by App::_add_flag_internal().
remove_quotes()
std::string & CLI::detail::remove_quotes (std::string & str) inline
remove quotes at the front and back of a string either '"' or '\''
Referenced by ConfigBase::from_config(), and detail::generate_parents().
remove_underscore()
std::string CLI::detail::remove_underscore (std::string str) inline
remove underscores from a string
Definition at line 710 of file CLI11.hpp.
{
            str.erase(std::remove(std::begin(str), std::end(str), '_'), std::end(str));
            return str;
        }
Referenced by App::check_name(), Option::check_name(), and ignore_underscore().
rjoin()
template<typename T > std::string CLI::detail::rjoin (const T & v, std::string delim = ",")
Join a string in reverse order.
Definition at line 603 of file CLI11.hpp.
{
            std::ostringstream s;
            for (std::size_t start = 0; start < v.size(); start++) {
                if (start > 0)
                    s << delim;
                s << v[v.size() - start - 1];
            }
            return s.str();
        }
rtrim() [1/2]
std::string & CLI::detail::rtrim (std::string & str) inline
Trim whitespace from right of string.
Referenced by trim().
rtrim() [2/2]
std::string & CLI::detail::rtrim (std::string & str, const std::string & filter) inline
Trim anything from right of string.
Referenced by trim().
split()
std::vector< std::string > CLI::detail::split (const std::string & s, char delim) inline
Split a string by a delim.
to_lower()
std::string CLI::detail::to_lower (std::string str) inline
Return a lower case version of a string.
Definition at line 702 of file CLI11.hpp.
{
            std::transform(std::begin(str), std::end(str), std::begin(str), [](const std::string::value_type& x) {
                return std::tolower(x, std::locale());
            });
            return str;
        }
Referenced by App::check_name(), Option::check_name(), ConfigBase::from_config(), detail::generate_parents(), ignore_case(), and detail::to_flag_value().
trim() [1/3]
std::string & CLI::detail::trim (std::string & str) inline
Trim whitespace from string.
Definition at line 628 of file CLI11.hpp.
{
            return ltrim(rtrim(str));
        }
References ltrim(), and rtrim().
Referenced by ConfigBase::from_config(), App::parse(), detail::split_program_name(), trim_copy(), and while().
trim() [2/3]
std::string & CLI::detail::trim (std::string & str, const std::string filter) inline
Trim anything from string.
Definition at line 633 of file CLI11.hpp.
{
            return ltrim(rtrim(str, filter), filter);
        }
References ltrim(), and rtrim().
Referenced by trim_copy().
trim() [3/3]
CLI::detail::trim (str)
trim_copy() [1/2]
std::string CLI::detail::trim_copy (const std::string & str) inline
Make a copy of the string and then trim it.
Definition at line 638 of file CLI11.hpp.
{
            std::string s = str;
            return trim(s);
        }
References trim().
Referenced by ConfigBase::from_config().
trim_copy() [2/2]
std::string CLI::detail::trim_copy (const std::string & str, const std::string & filter) inline
Make a copy of the string and then trim it, any filter string can be used (any char in string is filtered)
Definition at line 653 of file CLI11.hpp.
{
            std::string s = str;
            return trim(s, filter);
        }
References trim().
valid_alias_name_string()
bool CLI::detail::valid_alias_name_string (const std::string & str) inline
Verify an app name.
Definition at line 683 of file CLI11.hpp.
{
            static const std::string badChars(std::string("\n") + '\0');
            return (str.find_first_of(badChars) == std::string::npos);
        }
Referenced by App::add_option_group(), App::alias(), and OptionBase< CRTP >::group().
valid_first_char()
template<typename T > bool CLI::detail::valid_first_char (T c)
Verify the first character of an option
is a trigger character, ! has special meaning and new lines would just be annoying to deal with
Definition at line 666 of file CLI11.hpp.
{
            return ((c != '-') && (c != '!') && (c != ' ') && c != '\n');
        }
valid_later_char()
template<typename T > bool CLI::detail::valid_later_char (T c)
Verify following characters of an option.
Definition at line 672 of file CLI11.hpp.
{
            // = and : are value separators, { has special meaning for option defaults,
            // and \n would just be annoying to deal with in many places allowing space here has too much potential for
            // inadvertent entry errors and bugs
            return ((c != '=') && (c != ':') && (c != '{') && (c != ' ') && c != '\n');
        }
valid_name_string()
bool CLI::detail::valid_name_string (const std::string & str) inline
Verify an option/subcommand name.
Referenced by App::add_subcommand().
while()
CLI::detail::while (!str. empty())
Definition at line 932 of file CLI11.hpp.
{
                if (delims.find_first_of(str[0]) != std::string::npos) {
                    keyChar = str[0];
                    auto end = str.find_first_of(keyChar, 1);
                    while ((end != std::string::npos) && (str[end - 1] == '\\')) { // deal with escaped quotes
                        end = str.find_first_of(keyChar, end + 1);
                        embeddedQuote = true;
                    }
                    if (end != std::string::npos) {
                        output.push_back(str.substr(1, end - 1));
                        if (end + 2 < str.size()) {
                            str = str.substr(end + 2);
                        } else {
                            str.clear();
                        }
                    } else {
                        output.push_back(str.substr(1));
                        str = "";
                    }
                } else {
                    auto it = std::find_if(std::begin(str), std::end(str), find_ws);
                    if (it != std::end(str)) {
                        std::string const value = std::string(str.begin(), it);
                        output.push_back(value);
                        str = std::string(it + 1, str.end());
                    } else {
                        output.push_back(str);
                        str = "";
                    }
                }
                // transform any embedded quotes into the regular character
                if (embeddedQuote) {
                    output.back() = find_and_replace(output.back(), std::string("\\") + keyChar, std::string(1, keyChar));
                    embeddedQuote = false;
                }
                trim(str);
            }
References embeddedQuote, find_ws, keyChar, and trim().
widen_impl()
std::wstring CLI::detail::widen_impl (const char * str, std::size_t str_size) inline
Definition at line 329 of file CLI11.hpp.
{
#if CLI11_HAS_CODECVT
#ifdef _WIN32
            return std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>>().from_bytes(str, str + str_size);
#else
            return std::wstring_convert<std::codecvt_utf8<wchar_t>>().from_bytes(str, str + str_size);
#endif // _WIN32
#else  // CLI11_HAS_CODECVT
            (void) str_size;
            std::mbstate_t state = std::mbstate_t();
            const char* it = str;
            std::string old_locale = std::setlocale(LC_ALL, nullptr);
            auto sg = scope_guard([&] {
                std::setlocale(LC_ALL, old_locale.c_str());
            });
            set_unicode_locale();
            std::size_t new_size = std::mbsrtowcs(nullptr, &it, 0, &state);
            if (new_size == static_cast<std::size_t>(-1)) {
                throw std::runtime_error("CLI::widen: conversion error in std::mbsrtowcs at offset " + std::to_string(it - str));
            }
            std::wstring result(new_size, L'\0');
            std::mbsrtowcs(const_cast<wchar_t*>(result.data()), &str, new_size, &state);
            return result;
#endif // CLI11_HAS_CODECVT
        }
Referenced by CLI::widen(), and CLI::widen().
Variable Documentation
embeddedQuote
bool CLI::detail::embeddedQuote = false
Definition at line 930 of file CLI11.hpp.
Referenced by while().
expected_max_vector_size
int CLI::detail::expected_max_vector_size {1 << 29} constexpr
a constant defining an expected max vector size defined to be a big number that could be multiplied by 4 and not produce overflow for some expected uses
Definition at line 562 of file CLI11.hpp.
{1 << 29};
Referenced by Option::expected(), Option::expected(), Option::get_items_expected_max(), CLI::HelpFormatter::make_option_opts(), Formatter::make_option_opts(), Formatter::make_option_usage(), Option::type_size(), and Option::type_size().
find_ws
auto CLI::detail::find_ws
Initial value:
= [delimiter](char ch) {
                return (delimiter == '\0') ? std::isspace<char>(ch, std::locale()) : (ch == delimiter);
            }
Split a string '"one two" "three"' into 'one two', 'three' Quote characters can be ‘ ’ or " inline std::vector<std::string> split_up(std::string str, char delimiter = '\0'); / This function detects an equal or colon followed by an escaped quote after an argument / then modifies the string to replace the equality with a space. This is needed / to allow the split up function to work properly and is intended to be used with the find_and_modify function / the return value is the offset+1 which is required by the find_and_modify function. inline std::size_t escape_detect(std::string& str, std::size_t offset); / Add quotes if the string contains spaces inline std::string& add_quotes_if_needed(std::string& str); } // namespace detail namespace detail { inline std::vector<std::string> split(const std::string& s, char delim) { std::vector<std::string> elems; Check to see if empty string, give consistent result if (s.empty()) { elems.emplace_back(); } else { std::stringstream ss; ss.str(s); std::string item; while (std::getline(ss, item, delim)) { elems.push_back(item); } } return elems; } inline std::string& ltrim(std::string& str) { auto it = std::find_if(str.begin(), str.end(), [](char ch) { return !std::isspace<char>(ch, std::locale()); }); str.erase(str.begin(), it); return str; } inline std::string& ltrim(std::string& str, const std::string& filter) { auto it = std::find_if(str.begin(), str.end(), [&filter](char ch) { return filter.find(ch) == std::string::npos; }); str.erase(str.begin(), it); return str; } inline std::string& rtrim(std::string& str) { auto it = std::find_if(str.rbegin(), str.rend(), [](char ch) { return !std::isspace<char>(ch, std::locale()); }); str.erase(it.base(), str.end()); return str; } inline std::string& rtrim(std::string& str, const std::string& filter) { auto it = std::find_if(str.rbegin(), str.rend(), [&filter](char ch) { return filter.find(ch) == std::string::npos; }); str.erase(it.base(), str.end()); return str; } inline std::string& remove_quotes(std::string& str) { if (str.length() > 1 && (str.front() == '"' || str.front() == '\'')) { if (str.front() == str.back()) { str.pop_back(); str.erase(str.begin(), str.begin() + 1); } } return str; }
inline std::string fix_newlines(const std::string& leader, std::string input) { std::string::size_type n = 0; while (n != std::string::npos && n < input.size()) { n = input.find('
', n); if (n != std::string::npos) { input = input.substr(0, n + 1) + leader + input.substr(n + 1); n += leader.size(); } } return input; }
inline std::ostream& format_help(std::ostream& out, std::string name, const std::string& description, std::size_t wid) { name = " " + name; out << std::setw(static_cast<int>(wid)) << std::left << name; if (!description.empty()) { if (name.length() >= wid) out << "\n" << std::setw(static_cast<int>(wid)) << ""; for (const char c : description) { out.put(c); if (c == '
') { out << std::setw(static_cast<int>(wid)) << ""; } } } out << "\n"; return out; }
inline std::ostream& format_aliases(std::ostream& out, const std::vector<std::string>& aliases, std::size_t wid) { if (!aliases.empty()) { out << std::setw(static_cast<int>(wid)) << " aliases: "; bool front = true; for (const auto& alias : aliases) { if (!front) { out << ", "; } else { front = false; } out << detail::fix_newlines(" ", alias); } out << "\n"; } return out; }
inline bool valid_name_string(const std::string& str) { if (str.empty() || !valid_first_char(str[0])) { return false; } auto e = str.end(); for (auto c = str.begin() + 1; c != e; ++c) if (!valid_later_char(*c)) return false; return true; }
inline std::string find_and_replace(std::string str, std::string from, std::string to) { std::size_t start_pos = 0;
while ((start_pos = str.find(from, start_pos)) != std::string::npos) { str.replace(start_pos, from.length(), to); start_pos += to.length(); }
return str; }
inline void remove_default_flag_values(std::string& flags) { auto loc = flags.find_first_of('{', 2); while (loc != std::string::npos) { auto finish = flags.find_first_of("},", loc + 1); if ((finish != std::string::npos) && (flags[finish] == '}')) { flags.erase(flags.begin() + static_cast<std::ptrdiff_t>(loc), flags.begin() + static_cast<std::ptrdiff_t>(finish) + 1); } loc = flags.find_first_of('{', loc + 1); } flags.erase(std::remove(flags.begin(), flags.end(), '!'), flags.end()); }
inline std::ptrdiff_t find_member(std::string name, const std::vector<std::string> names, bool ignore_case, bool ignore_underscore) { auto it = std::end(names); if (ignore_case) { if (ignore_underscore) { name = detail::to_lower(detail::remove_underscore(name)); it = std::find_if(std::begin(names), std::end(names), [&name](std::string local_name) { return detail::to_lower(detail::remove_underscore(local_name)) == name; }); } else { name = detail::to_lower(name); it = std::find_if(std::begin(names), std::end(names), [&name](std::string local_name) { return detail::to_lower(local_name) == name; }); }
} else if (ignore_underscore) { name = detail::remove_underscore(name); it = std::find_if(std::begin(names), std::end(names), [&name](std::string local_name) { return detail::remove_underscore(local_name) == name; }); } else { it = std::find(std::begin(names), std::end(names), name); }
return (it != std::end(names)) ? (it - std::begin(names)) : (-1); }
inline std::vector<std::string> split_up(std::string str, char delimiter) { const std::string delims("\'\"`");
Definition at line 924 of file CLI11.hpp.
{
                return (delimiter == '\0') ? std::isspace<char>(ch, std::locale()) : (ch == delimiter);
            };
Referenced by while().
keyChar
char CLI::detail::keyChar = ' '
Definition at line 931 of file CLI11.hpp.
Referenced by while().
output
return CLI::detail::output
Definition at line 929 of file CLI11.hpp.