SNode.C: web::websocket::client Namespace Reference
web::websocket::client Namespace Reference
Classes
class SocketContextUpgrade
class SocketContextUpgradeFactory
class SubProtocol
class SubProtocolFactorySelector
Functions
int getentropy (void *buf, size_t buflen)
web::http::client::SocketContextUpgradeFactory * websocketClientSocketContextUpgradeFactory ()
Function Documentation
getentropy()
int web::websocket::client::getentropy (void * buf, size_t buflen)
Definition at line 70 of file SocketContextUpgradeFactory.cpp.
{
#ifdef SYS_GETRANDOM
        const ssize_t ret = syscall(SYS_getrandom, buf, buflen, 0);
#else
        // Fallback to /dev/urandom if necessary
        const int fd = open("/dev/urandom", O_RDONLY);
        if (fd == -1) {
            return -1;
        }
        const ssize_t ret = read(fd, buf, buflen);
        close(fd);
#endif
        return (ret == static_cast<ssize_t>(buflen)) ? 0 : -1;
    }
Referenced by web::websocket::client::SocketContextUpgradeFactory::prepare().
websocketClientSocketContextUpgradeFactory()
web::http::client::SocketContextUpgradeFactory * web::websocket::client::websocketClientSocketContextUpgradeFactory ()
Definition at line 130 of file SocketContextUpgradeFactory.cpp.
{
        return new SocketContextUpgradeFactory();
    }
References web::websocket::client::SocketContextUpgradeFactory::SocketContextUpgradeFactory().
Referenced by web::websocket::client::SocketContextUpgradeFactory::link().