SNode.C: web::http::legacy::rc Namespace Reference
web::http::legacy::rc Namespace Reference
Classes
class EventSource
Typedefs
using Client = web::http::client::Client< net::rc::stream::legacy::SocketClient >
using Server = web::http::server::Server< net::rc::stream::legacy::SocketServer >
Functions
std::shared_ptr< web::http::client::tools::EventSource > EventSource (const std::string &scheme, const net::rc::SocketAddress &socketAddress, const std::string &path)
std::shared_ptr< web::http::client::tools::EventSource > EventSource (const std::string &host, uint8_t channel, const std::string &path)
std::shared_ptr< web::http::client::tools::EventSource > EventSource (const std::string &url)
std::shared_ptr< web::http::client::tools::EventSource > EventSource (std::string origin, std::string path)
Typedef Documentation
Client
using web::http::legacy::rc::Client = typedef web::http::client::Client<net::rc::stream::legacy::SocketClient>
Definition at line 54 of file Client.h.
Server
using web::http::legacy::rc::Server = typedef web::http::server::Server<net::rc::stream::legacy::SocketServer>
Definition at line 55 of file Server.h.
Function Documentation
EventSource() [1/4]
std::shared_ptr< web::http::client::tools::EventSource > web::http::legacy::rc::EventSource (const std::string & host, uint8_t channel, const std::string & path) inline
Definition at line 80 of file EventSource.h.
{
        return EventSource("http", net::rc::SocketAddress(host, channel), path);
    }
References EventSource(), and net::rc::SocketAddress::SocketAddress().
EventSource() [2/4]
std::shared_ptr< web::http::client::tools::EventSource > web::http::legacy::rc::EventSource (const std::string & scheme, const net::rc::SocketAddress & socketAddress, const std::string & path) inline
Definition at line 72 of file EventSource.h.
{
        std::shared_ptr<class EventSource> eventSource = std::make_shared<class EventSource>();
        eventSource->init(scheme, socketAddress, path);
        return eventSource;
    }
Referenced by EventSource().
EventSource() [3/4]
std::shared_ptr< web::http::client::tools::EventSource > web::http::legacy::rc::EventSource (const std::string & url) inline
Definition at line 85 of file EventSource.h.
{
        std::shared_ptr<web::http::client::tools::EventSource> eventSource;
        static const std::regex re(
            R"(^(?:rfcomm://)(?![^/]*@)((?:[0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}|[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*)"
            R"(?::([1-9]|[12]\d|30))?([^?#]*)(\?[^#]*)?(?:#.*)?$)",
            std::regex::ECMAScript | std::regex::icase);
        std::smatch match;
        if (std::regex_match(url, match, re)) {
            // rfcomm://<mac-or-host>[:<channel>][/path][?query][#fragment]
            //  [1] addr   -> MAC "01:23:45:67:89:AB" OR hostname
            //  [2] chan   -> RFCOMM channel 1..30 (optional; default 1)
            //  [3] path   -> may be empty; default "/"
            //  [4] query  -> optional
            const std::string scheme = "rfcomm";     // fixed
            const std::string addr = match[1].str(); // MAC or hostname
            const uint8_t chan = match[2].matched ? static_cast<uint8_t>(std::stoi(match[2].str())) : static_cast<uint16_t>(1);
            const std::string path = match[3].matched ? match[3].str() : "/";
            const std::string query = match[4].matched ? match[4].str() : "";
            eventSource = std::make_shared<class EventSource>(scheme, net::rc::SocketAddress(addr, chan), path + query);
        } else {
            LOG(ERROR) << "EventSource RFCOMM url not accepted: " << url;
        }
        return eventSource;
    }
References net::rc::SocketAddress::SocketAddress().
EventSource() [4/4]
std::shared_ptr< web::http::client::tools::EventSource > web::http::legacy::rc::EventSource (std::string origin, std::string path) inline
Definition at line 115 of file EventSource.h.
{
        if (!origin.empty() && origin.at(origin.length() - 1) == '/') {
            origin.pop_back();
        }
        if (!path.empty() && path.at(0) != '/') {
            path = "/" + path;
        }
        return EventSource(!origin.empty() ? origin + path : "");
    }