SNode.C: legacy Namespace Reference
legacy Namespace Reference
Typedefs
using SocketClient = net::in::stream::legacy::SocketClient<apps::http::SimpleSocketProtocolFactory>
using SocketAddress = SocketClient::SocketAddress
using SocketConnection = SocketClient::SocketConnection
Functions
SocketClient getLegacyClient ()
Typedef Documentation
SocketAddress
using legacy::SocketAddress = SocketClient::SocketAddress
Definition at line 254 of file httplowlevelclient.cpp.
SocketClient
typedef net::in::stream::legacy::SocketClient< apps::http::SimpleSocketProtocolFactory > legacy::SocketClient = net::in::stream::legacy::SocketClient<apps::http::SimpleSocketProtocolFactory>
Definition at line 253 of file httplowlevelclient.cpp.
SocketConnection
using legacy::SocketConnection = SocketClient::SocketConnection
Definition at line 255 of file httplowlevelclient.cpp.
Function Documentation
getLegacyClient()
SocketClient legacy::getLegacyClient ()
Definition at line 257 of file httplowlevelclient.cpp.
{
        SocketClient legacyClient(
            "legacy",
            [](SocketConnection* socketConnection) { // OnConnect
                VLOG(1) << "OnConnect";
                VLOG(1) << "\tServer: " << socketConnection->getRemoteAddress().toString();
                VLOG(1) << "\tClient: " << socketConnection->getLocalAddress().toString();
            },
            [](SocketConnection* socketConnection) { // onConnected
                VLOG(1) << "OnConnected";
                socketConnection->sendToPeer("GET /index.html HTTP/1.1\r\nConnection: close\r\n\r\n"); // Connection: close\r\n\r\n");
            },
            [](SocketConnection* socketConnection) { // onDisconnect
                VLOG(1) << "OnDisconnect";
                VLOG(1) << "\tServer: " << socketConnection->getRemoteAddress().toString();
                VLOG(1) << "\tClient: " << socketConnection->getLocalAddress().toString();
            });
        SocketAddress remoteAddress("localhost", 8080);
        remoteAddress.init();
        VLOG(1) << "###############': " << remoteAddress.getCanonName();
        VLOG(1) << "###############': " << remoteAddress.toString();
        legacyClient.connect(remoteAddress,
                             [instanceName = legacyClient.getConfig().getInstanceName()](
                                 const tls::SocketAddress& socketAddress,
                                 const core::socket::State& state) { // example.com:81 simulate connnect timeout
                                 switch (state) {
                                     case core::socket::State::OK:
                                         VLOG(1) << instanceName << ": connected to '" << socketAddress.toString() << "'";
                                         break;
                                     case core::socket::State::DISABLED:
                                         VLOG(1) << instanceName << ": disabled";
                                         break;
                                     case core::socket::State::ERROR:
                                         LOG(ERROR) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                                         break;
                                     case core::socket::State::FATAL:
                                         LOG(FATAL) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                                         break;
                                 }
                             });
        return legacyClient;
    }
References core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::connect(), core::socket::State::DISABLED, core::socket::State::ERROR, core::socket::State::FATAL, net::in::SocketAddress::getCanonName(), core::socket::Socket< ConfigT >::getConfig(), net::config::ConfigInstance::getInstanceName(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::getLocalAddress(), core::socket::stream::SocketConnectionT< PhysicalSocketT, SocketReaderT, SocketWriterT, ConfigT >::getRemoteAddress(), net::in::SocketAddress::init(), core::socket::State::OK, core::socket::stream::SocketConnection::sendToPeer(), net::in::SocketAddress::SocketAddress(), net::in::SocketAddress::toString(), and core::socket::State::what().
Referenced by main().