SNode.C: express::tls::un Namespace Reference
express::tls::un Namespace Reference
Typedefs
using WebApp = WebAppT< web::http::tls::un::Server >
Functions
WebApp Server (const std::string &instanceName, const express::Router &router, const std::function< void(const std::string &, WebApp::SocketAddress, const core::socket::State &)> &reportState, const std::function< void(typename WebApp::Config &)> &configurator)
WebApp Server (const std::string &instanceName, const Router &router, const std::function< void(WebApp::Config &)> &configurator)
WebApp Server (const std::string &instanceName, const express::Router &router, const std::function< void(typename WebApp::Config &)> &configurator)
Typedef Documentation
WebApp
using express::tls::un::WebApp = typedef WebAppT<web::http::tls::un::Server>
Definition at line 54 of file WebApp.h.
Function Documentation
Server() [1/3]
WebApp express::tls::un::Server (const std::string & instanceName, const express::Router & router, const std::function< void(const std::string &, WebApp::SocketAddress, const core::socket::State &)> & reportState = nullptr, const std::function< void(typename WebApp::Config &)> & configurator = nullptr)
Definition at line 55 of file Server.cpp.
{
        using SocketAddress = typename WebApp::SocketAddress;
        const WebApp webApp(instanceName, router);
        if (configurator != nullptr) {
            configurator(webApp.getConfig());
        }
        webApp.listen([instanceName, reportState](const SocketAddress& socketAddress, const core::socket::State& state) {
            if (reportState != nullptr) {
                reportState(instanceName, socketAddress, state);
            } else {
                switch (state) {
                    case core::socket::State::OK:
                        VLOG(1) << instanceName << ": listening on '" << socketAddress.toString() << "'";
                        break;
                    case core::socket::State::DISABLED:
                        VLOG(1) << instanceName << ": disabled";
                        break;
                    case core::socket::State::ERROR:
                        VLOG(1) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                        break;
                    case core::socket::State::FATAL:
                        VLOG(1) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                        break;
                }
            }
        });
        VLOG(1) << "Instance: " << instanceName;
        for (std::string& route : webApp.getRoutes()) {
            route.erase(std::remove(route.begin(), route.end(), '$'), route.end());
            VLOG(1) << "  " << route;
        }
        return webApp;
    }
References core::socket::State::DISABLED, core::socket::State::ERROR, core::socket::State::FATAL, core::socket::Socket< ConfigT >::getConfig(), express::Router::getRoutes(), core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::listen(), core::socket::State::OK, net::un::SocketAddress::toString(), express::WebAppT< ServerT >::WebAppT(), and core::socket::State::what().
Referenced by Server().
Server() [2/3]
WebApp express::tls::un::Server (const std::string & instanceName, const express::Router & router, const std::function< void(typename WebApp::Config &)> & configurator)
Server() [3/3]
WebApp express::tls::un::Server (const std::string & instanceName, const Router & router, const std::function< void(WebApp::Config &)> & configurator)
Definition at line 98 of file Server.cpp.
{
        return Server(instanceName, router, nullptr, configurator);
    }
References Server().