SNode.C: core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Context Struct Reference
core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Context Struct Reference
Public Member Functions
Context (const std::shared_ptr< SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect)
Public Attributes
std::shared_ptr< SocketContextFactory > socketContextFactory
std::function< void(SocketConnection *)> onConnect
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
std::function< void(core::eventreceiver::AcceptEventReceiver *)> onInitState
std::function< void(const std::shared_ptr< AutoConnectControl > &)> onAutoConnectControl
std::shared_ptr< AutoConnectControl > autoConnectControl
Detailed Description
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args>
struct core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Context
Definition at line 82 of file SocketServer.h.
Constructor & Destructor Documentation
Context()
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Context::Context (const std::shared_ptr< SocketContextFactory > & socketContextFactory, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect) inline
Definition at line 83 of file SocketServer.h.
                : socketContextFactory(socketContextFactory)
                , onConnect(onConnect)
                , onConnected(onConnected)
                , onDisconnect(onDisconnect)
                , onInitState([]([[maybe_unused]] core::eventreceiver::AcceptEventReceiver* descriptorEventReceiver) {
                })
                , onAutoConnectControl([]([[maybe_unused]] const std::shared_ptr<AutoConnectControl>& onAutoConnectControl) {
                }) {
            }
References onConnect, onConnected, onDisconnect, onInitState, and socketContextFactory.
Member Data Documentation
autoConnectControl
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::shared_ptr<AutoConnectControl> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Context::autoConnectControl
Definition at line 105 of file SocketServer.h.
onAutoConnectControl
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::function<void(const std::shared_ptr<AutoConnectControl>&)> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Context::onAutoConnectControl
Definition at line 104 of file SocketServer.h.
onConnect
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::function<void(SocketConnection*)> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Context::onConnect
Definition at line 99 of file SocketServer.h.
Referenced by Context().
onConnected
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::function<void(SocketConnection*)> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Context::onConnected
Definition at line 100 of file SocketServer.h.
Referenced by Context().
onDisconnect
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::function<void(SocketConnection*)> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Context::onDisconnect
Definition at line 101 of file SocketServer.h.
Referenced by Context().
onInitState
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::function<void(core::eventreceiver::AcceptEventReceiver*)> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Context::onInitState
Definition at line 102 of file SocketServer.h.
Referenced by Context().
socketContextFactory
template<typename SocketAcceptorT, typename SocketContextFactoryT, typename... Args> std::shared_ptr<SocketContextFactory> core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::Context::socketContextFactory
Definition at line 97 of file SocketServer.h.
Referenced by Context().
The documentation for this struct was generated from the following file:
core/socket/stream/SocketServer.h