SNode.C: core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::Context Struct Reference
core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::Context Struct Reference
Public Member Functions
Context (const std::shared_ptr< SocketContextFactory > &socketContextFactory, std::function< void(SocketConnection *)> onConnect, std::function< void(SocketConnection *)> onConnected, std::function< void(SocketConnection *)> onDisconnect)
Public Attributes
std::shared_ptr< SocketContextFactory > socketContextFactory
std::function< void(SocketConnection *)> onConnect
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
Detailed Description
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args>
struct core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::Context
Definition at line 319 of file SocketClient.h.
Constructor & Destructor Documentation
Context()
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::Context::Context (const std::shared_ptr< SocketContextFactory > & socketContextFactory, std::function< void(SocketConnection *)> onConnect, std::function< void(SocketConnection *)> onConnected, std::function< void(SocketConnection *)> onDisconnect) inline
Definition at line 320 of file SocketClient.h.
                : socketContextFactory(socketContextFactory)
                , onConnect(onConnect)
                , onConnected(onConnected)
                , onDisconnect(onDisconnect) {
            }
References onConnect, onConnected, onDisconnect, and socketContextFactory.
Member Data Documentation
onConnect
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> std::function<void(SocketConnection*)> core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::Context::onConnect
Definition at line 331 of file SocketClient.h.
Referenced by Context().
onConnected
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> std::function<void(SocketConnection*)> core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::Context::onConnected
Definition at line 332 of file SocketClient.h.
Referenced by Context().
onDisconnect
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> std::function<void(SocketConnection*)> core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::Context::onDisconnect
Definition at line 333 of file SocketClient.h.
Referenced by Context().
socketContextFactory
template<typename SocketConnectorT, typename SocketContextFactoryT, typename... Args> std::shared_ptr<SocketContextFactory> core::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT, Args >::Context::socketContextFactory
Definition at line 329 of file SocketClient.h.
Referenced by Context().
The documentation for this struct was generated from the following file:
core/socket/stream/SocketClient.h