SNode.C: apps/testpost.cpp File Reference
testpost.cpp File Reference
#include "express/legacy/in/WebApp.h"
#include "express/middleware/VerboseRequest.h"
#include "express/tls/in/WebApp.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 54 of file testpost.cpp.
{
    express::WebApp::init(argc, argv);
    using LegacyWebApp = express::legacy::in::WebApp;
    using LegacySocketAddress = LegacyWebApp::SocketAddress;
    const LegacyWebApp legacyApp("legacy");
    legacyApp.getConfig().setReuseAddress();
    legacyApp.use(express::middleware::VerboseRequest());
    legacyApp.get("/", [] APPLICATION(req, res) {
        res->send("<html>"
                  "    <head>"
                  "        <style>"
                  "            main {"
                  "                min-height: 30em;"
                  "                padding: 3em;"
                  "                background-image: repeating-radial-gradient( circle at 0 0, #fff, #ddd 50px);"
                  "            }"
                  "            input[type=\"file\"] {"
                  "                display: block;"
                  "                margin: 2em;"
                  "                padding: 2em;"
                  "                border: 1px dotted;"
                  "            }"
                  "        </style>"
                  "    </head>"
                  "    <body>"
                  "        <h1>File-Upload with input type=\"file\"</h1>"
                  "        <main>"
                  "            <h2>Send us something fancy!</h2>"
                  "            <form method=\"post\" enctype=\"multipart/form-data\">"
                  "                <label> Select a text file (*.txt, *.html etc.) from your computer."
                  "                    <input name=\"datei\" type=\"file\" size=\"50\" accept=\"text/*\">"
                  "                </label>"
                  "                <button>… and off we go!</button>"
                  "            </form>"
                  "        </main>"
                  "    </body>"
                  "</html>");
    });
    legacyApp.post("/", [] APPLICATION(req, res) {
        res->send("<html>\n"
                  "    <body>\n"
                  "        <h1>Thank you, we received your file!</h1>\n"
                  "        <h2>Content:</h2>\n"
                  "        <pre>\n" +
                  std::string(req->body.begin(), req->body.end()) +
                  "        </pre>\n"
                  "    </body>\n"
                  "</html>\n");
    });
    legacyApp.listen(8080, [](const LegacySocketAddress& socketAddress, const core::socket::State& state) {
        switch (state) {
            case core::socket::State::OK:
                VLOG(1) << "legacyApp: listening on '" << socketAddress.toString() << "'";
                break;
            case core::socket::State::DISABLED:
                VLOG(1) << "legacyApp: disabled";
                break;
            case core::socket::State::ERROR:
                VLOG(1) << "legacyApp: error occurred";
                break;
            case core::socket::State::FATAL:
                VLOG(1) << "legacyApp: fatal error occurred";
                break;
        }
    });
    using TLSWebApp = express::tls::in::WebApp;
    using TLSSocketAddress = TLSWebApp::SocketAddress;
    const TLSWebApp tlsApp("tls");
    tlsApp.getConfig().setReuseAddress();
    tlsApp.getConfig()
        .setCert("/home/voc/projects/snodec/snode.c/certs/wildcard.home.vchrist.at_-_snode.c_-_server.pem")
        .setCertKey("/home/voc/projects/snodec/snode.c/certs/Volker_Christian_-_Web_-_snode.c_-_server.key.encrypted.pem")
        .setCertKeyPassword("snode.c");
    tlsApp.use(legacyApp);
    tlsApp.listen("localhost", 8088, [](const TLSSocketAddress& socketAddress, const core::socket::State& state) {
        switch (state) {
            case core::socket::State::OK:
                VLOG(1) << "tlsApp: listening on '" << socketAddress.toString() << "'";
                break;
            case core::socket::State::DISABLED:
                VLOG(1) << "tlsApp: disabled";
                break;
            case core::socket::State::ERROR:
                VLOG(1) << "tlsApp: error occurred";
                break;
            case core::socket::State::FATAL:
                VLOG(1) << "tlsApp: fatal error occurred";
                break;
        }
    });
    return express::WebApp::start();
}
References express::Request::body, core::socket::State::DISABLED, core::socket::State::ERROR, core::socket::State::FATAL, core::socket::Socket< ConfigT >::getConfig(), express::WebApp::init(), net::in::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT, Args >::listen(), net::in::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT, Args >::listen(), core::socket::State::OK, express::Response::send(), net::config::ConfigTls::setCert(), net::config::ConfigTls::setCertKey(), net::config::ConfigTls::setCertKeyPassword(), net::in::stream::config::ConfigSocketServer::setReuseAddress(), express::WebApp::start(), net::in::SocketAddress::toString(), and express::WebAppT< ServerT >::WebAppT().