SNode.C: apps/vhostserver.cpp File Reference
vhostserver.cpp File Reference
#include "express/legacy/in6/WebApp.h"
#include "express/middleware/StaticMiddleware.h"
#include "express/middleware/VHost.h"
#include "express/tls/in6/WebApp.h"
#include "utils/Config.h"
Functions
Router getRouter (const std::string &webRoot)
int main (int argc, char *argv[])
Function Documentation
getRouter()
Router getRouter (const std::string & webRoot)
Definition at line 58 of file vhostserver.cpp.
{
    const Router router;
    router.use(middleware::StaticMiddleware(webRoot));
    return router;
}
main()
int main (int argc, char * argv[])
Definition at line 66 of file vhostserver.cpp.
{
    utils::Config::addStringOption("--web-root", "Root directory of the web site", "[path]");
    WebApp::init(argc, argv);
    {
        const legacy::in6::WebApp legacyApp("legacy");
        const Router& vh1 = middleware::VHost("localhost:8080");
        vh1.use(middleware::StaticMiddleware(utils::Config::getStringOptionValue("--web-root")));
        legacyApp.use(vh1);
        const Router& vh2 = middleware::VHost("jupiter.home.vchrist.at");
        vh2.get("/",
                [] MIDDLEWARE(req, res, next) {
                    if (req->query("how").empty()) {
                        next();
                    } else if (req->query("how") == "route") {
                        next("route");
                    } else if (req->query("how") == "router") {
                        next("router");
                    }
                })
            .get([] APPLICATION(req, res) {
                res->send("Hello! I am VHOST jupiter.home.vchrist.at.");
            });
        legacyApp.use(vh2);
        const Router& vh3 = middleware::VHost("atlas.home.vchrist.at:8080");
        vh3.get("/",
                [] MIDDLEWARE(req, res, next) {
                    if (req->query("how").empty()) {
                        next();
                    } else if (req->query("how") == "route") {
                        next("route");
                    } else if (req->query("how") == "router") {
                        next("router");
                    }
                })
            .get([] APPLICATION(req, res) {
                res->send("Hello! I am VHOST atlas.home.vchrist.at.");
            });
        vh3.get("/", [] APPLICATION(req, res) {
            res->send("Hello, next route on atlas.home.vchrist.at");
        });
        vh3.get("/test", [] APPLICATION(req, res) {
            res->send("Test Route on VHOST atlas.home.vchrist.at.");
        });
        legacyApp.use(vh3);
        legacyApp.use([] APPLICATION(req, res) {
            res->status(404).send("The requested resource is not found.");
        });
        legacyApp.listen(8080,
                         [instanceName = legacyApp.getConfig().getInstanceName()](const legacy::in6::WebApp::SocketAddress& socketAddress,
                                                                                  const core::socket::State& state) {
                             switch (state) {
                                 case core::socket::State::OK:
                                     VLOG(1) << instanceName << " listening on '" << socketAddress.toString() << "'";
                                     break;
                                 case core::socket::State::DISABLED:
                                     VLOG(1) << instanceName << " disabled";
                                     break;
                                 case core::socket::State::ERROR:
                                     LOG(ERROR) << instanceName << " " << socketAddress.toString() << ": " << state.what();
                                     break;
                                 case core::socket::State::FATAL:
                                     LOG(FATAL) << instanceName << " " << socketAddress.toString() << ": " << state.what();
                                     break;
                             }
                         });
    }
    {
        const express::tls::in6::WebApp tlsApp("tls");
        const Router& vh1 = middleware::VHost("localhost:8088");
        vh1.use(middleware::StaticMiddleware(utils::Config::getStringOptionValue("--web-root")));
        tlsApp.use(vh1);
        const Router& vh2 = middleware::VHost("atlas.home.vchrist.at:8088");
        vh2.get("/",
                [] MIDDLEWARE(req, res, next) {
                    if (req->query("how").empty()) {
                        next();
                    } else if (req->query("how") == "route") {
                        next("route");
                    } else if (req->query("how") == "router") {
                        next("router");
                    }
                })
            .get([] APPLICATION(req, res) {
                res->send("Hello! I am VHOST atlas.home.vchrist.at.");
            });
        tlsApp.use(vh2);
        const Router& vh3 = middleware::VHost("ceres.home.vchrist.at:8088");
        vh3.get("/",
                [] MIDDLEWARE(req, res, next) {
                    if (req->query("how").empty()) {
                        next();
                    } else if (req->query("how") == "route") {
                        next("route");
                    } else if (req->query("how") == "router") {
                        next("router");
                    }
                })
            .get([] APPLICATION(req, res) {
                res->send("Hello! I am VHOST ceres.home.vchrist.at.");
            });
        vh3.get("/", [] APPLICATION(req, res) {
            res->send("Hello, next route on ceres.home.vchrist.at");
        });
        vh3.get("/test", [] APPLICATION(req, res) {
            res->send("Test Route on VHOST ceres.home.vchrist.at.");
        });
        tlsApp.use(vh3);
        tlsApp.use([] APPLICATION(req, res) {
            res->status(404).send("The requested resource is not found.");
        });
        tlsApp.listen(8088,
                      [instanceName = tlsApp.getConfig().getInstanceName()](const legacy::in6::WebApp::SocketAddress& socketAddress,
                                                                            const core::socket::State& state) {
                          switch (state) {
                              case core::socket::State::OK:
                                  VLOG(1) << instanceName << " listening on '" << socketAddress.toString() << "'";
                                  break;
                              case core::socket::State::DISABLED:
                                  VLOG(1) << instanceName << " disabled";
                                  break;
                              case core::socket::State::ERROR:
                                  LOG(ERROR) << instanceName << " " << socketAddress.toString() << ": " << state.what();
                                  break;
                              case core::socket::State::FATAL:
                                  LOG(FATAL) << instanceName << " " << socketAddress.toString() << ": " << state.what();
                                  break;
                          }
                      });
        tlsApp.getConfig().setCert("/home/voc/projects/snodec/snode.c/certs/wildcard.home.vchrist.at_-_snode.c_-_server.pem");
        tlsApp.getConfig().setCertKey(
            "/home/voc/projects/snodec/snode.c/certs/Volker_Christian_-_Web_-_snode.c_-_server.key.encrypted.pem");
        tlsApp.getConfig().setCertKeyPassword("snode.c");
    }
    WebApp::start();
}
References core::socket::State::DISABLED, core::socket::State::ERROR, core::socket::State::FATAL, core::socket::Socket< ConfigT >::getConfig(), net::config::ConfigInstance::getInstanceName(), express::WebApp::init(), net::in6::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT, Args >::listen(), core::socket::State::OK, express::Next::operator()(), express::Request::query(), express::Response::send(), net::config::ConfigTls::setCert(), net::config::ConfigTls::setCertKey(), net::config::ConfigTls::setCertKeyPassword(), express::WebApp::start(), express::Response::status(), net::in6::SocketAddress::toString(), express::WebAppT< ServerT >::WebAppT(), and core::socket::State::what().