SNode.C: apps/warema-jalousien.cpp File Reference
warema-jalousien.cpp File Reference
#include "express/legacy/in/WebApp.h"
Functions
int main (int argc, char *argv[])
Variables
static std::map< std::string, std::string > jalousien
static std::map< std::string, std::string > actions = {{"open", "up"}, {"close", "down"}, {"stop", "stop"}}
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 67 of file warema-jalousien.cpp.
{
    WebApp::init(argc, argv);
    legacy::in::WebApp webApp("werema");
    //    tls::WebApp wa;
    webApp.get("/jalousien/:id", [] APPLICATION(req, res) {
        VLOG(1) << "Param: " << req->param("id");
        VLOG(1) << "Qurey: " << req->query("action");
        std::string arguments = "aircontrol -t " + jalousien[req->param("id")] + "_" + actions[req->query("action")];
        int ret = system(arguments.c_str());
        ret = (ret >> 8) & 0xFF;
        /* ret:
               Bits 15-8 = Exit code.
               Bit     7 = 1 if a core dump was produced.
               Bits  6-0 = Signal number that killed the process.
        */
        switch (ret) {
            case 0:
                res->status(200).send("OK: " + arguments);
                break;
            case 127:
                res->status(404).send("ERROR not found: " + arguments);
                break;
        }
    });
    webApp.use([] APPLICATION(req, res) {
        res->status(404).send("No Jalousie specified");
    });
    webApp.listen(8080,
                  [instanceName = webApp.getConfig().getInstanceName()](const legacy::in::WebApp::SocketAddress& socketAddress,
                                                                        const core::socket::State& state) {
                      switch (state) {
                          case core::socket::State::OK:
                              VLOG(1) << instanceName << ": listening on '" << socketAddress.toString() << "'";
                              break;
                          case core::socket::State::DISABLED:
                              VLOG(1) << instanceName << ": disabled";
                              break;
                          case core::socket::State::ERROR:
                              LOG(ERROR) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                              break;
                          case core::socket::State::FATAL:
                              LOG(FATAL) << instanceName << ": " << socketAddress.toString() << ": " << state.what();
                              break;
                      }
                  });
    return WebApp::start();
}
References actions, core::socket::State::DISABLED, core::socket::State::ERROR, core::socket::State::FATAL, core::socket::Socket< ConfigT >::getConfig(), net::config::ConfigInstance::getInstanceName(), express::WebApp::init(), jalousien, net::in::stream::SocketServer< SocketAcceptorT, ConfigSocketServerT, SocketContextFactoryT, Args >::listen(), core::socket::State::OK, express::Request::param(), express::Request::query(), express::Response::send(), express::WebApp::start(), express::Response::status(), net::in::SocketAddress::toString(), express::WebAppT< ServerT >::WebAppT(), and core::socket::State::what().
Variable Documentation
actions
std::map< std::string, std::string > actions = {{"open", "up"}, {"close", "down"}, {"stop", "stop"}} static
Definition at line 65 of file warema-jalousien.cpp.
{{"open", "up"}, {"close", "down"}, {"stop", "stop"}};
Referenced by main().
jalousien
std::map< std::string, std::string > jalousien static
Initial value:
= {{"kueche", "kueche"},
                                                       {"strasse", "strasse"},
                                                       {"esstisch", "esstisch"},
                                                       {"balkon", "balkon"},
                                                       {"schlafzimmer", "schlafzimmer"},
                                                       {"arbeitszimmer", "arbeitszimmer"},
                                                       {"comfort", "komfort"},
                                                       {"all", "alle"}}
Definition at line 56 of file warema-jalousien.cpp.
                                                {{"kueche", "kueche"},
                                                       {"strasse", "strasse"},
                                                       {"esstisch", "esstisch"},
                                                       {"balkon", "balkon"},
                                                       {"schlafzimmer", "schlafzimmer"},
                                                       {"arbeitszimmer", "arbeitszimmer"},
                                                       {"comfort", "komfort"},
                                                       {"all", "alle"}};
Referenced by main().