SNode.C: apps/websocket/echoserver.cpp File Reference
echoserver.cpp File Reference
#include "express/legacy/in/WebApp.h"
#include "express/middleware/VerboseRequest.h"
#include "express/tls/in/WebApp.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 59 of file echoserver.cpp.
{
    express::WebApp::init(argc, argv);
    using LegacyWebApp = express::legacy::in::WebApp;
    using Request = LegacyWebApp::Request;
    using Response = LegacyWebApp::Response;
    using SocketAddress = LegacyWebApp::SocketAddress;
    const LegacyWebApp legacyApp("legacy");
    legacyApp.use(express::middleware::VerboseRequest());
    legacyApp.get("/ws", [](const std::shared_ptr<Request>& req, const std::shared_ptr<Response>& res) {
        const std::string connectionName = res->getSocketContext()->getSocketConnection()->getConnectionName();
        res->upgrade(req, [req, res, connectionName](const std::string& name) {
            if (!name.empty()) {
                VLOG(1) << connectionName << ": Successful upgrade:";
                VLOG(1) << connectionName << ":   Requested: " << req->get("upgrade");
                VLOG(1) << connectionName << ":    Selected: " << name;
                res->end();
            } else {
                VLOG(1) << connectionName << ": Can not upgrade to any of '" << req->get("upgrade") << "'";
                res->sendStatus(404);
            }
        });
    });
    legacyApp.get("/", [] APPLICATION(req, res) {
        VLOG(1) << "HTTP GET on "
                << "/";
        if (req->url == "/" || req->url == "/index.html") {
            req->url = "/wstest.html";
        }
        VLOG(1) << CMAKE_CURRENT_SOURCE_DIR "/html" + req->url;
        res->sendFile(CMAKE_CURRENT_SOURCE_DIR "/html" + req->url, [req, res](int errnum) {
            if (errnum == 0) {
                VLOG(1) << req->url;
            } else {
                VLOG(1) << "HTTP response send file failed: " << std::strerror(errnum);
                res->sendStatus(404);
            }
        });
    });
    legacyApp.listen(
        [instanceName = legacyApp.getConfig().getInstanceName()](const SocketAddress& socketAddress, const core::socket::State& state) {
            switch (state) {
                case core::socket::State::OK:
                    VLOG(1) << instanceName << " listening on '" << socketAddress.toString() << "'";
                    break;
                case core::socket::State::DISABLED:
                    VLOG(1) << instanceName << " disabled";
                    break;
                case core::socket::State::ERROR:
                    VLOG(1) << instanceName << " " << socketAddress.toString() << ": " << state.what();
                    break;
                case core::socket::State::FATAL:
                    VLOG(1) << instanceName << " " << socketAddress.toString() << ": " << state.what();
                    break;
            }
        });
    VLOG(1) << "Legacy Routes:";
    for (std::string& route : legacyApp.getRoutes()) {
        route.erase(std::remove(route.begin(), route.end(), '$'), route.end());
        VLOG(1) << "  " << route;
    }
    {
        using TlsWebApp = express::tls::in::WebApp;
        using Request = TlsWebApp::Request;
        using Response = TlsWebApp::Response;
        using SocketAddress = TlsWebApp::SocketAddress;
        const TlsWebApp tlsApp("tls");
        tlsApp.use(express::middleware::VerboseRequest());
        tlsApp.get("/ws", [](const std::shared_ptr<Request>& req, const std::shared_ptr<Response>& res) {
            const std::string connectionName = res->getSocketContext()->getSocketConnection()->getConnectionName();
            res->upgrade(req, [req, res, connectionName](const std::string& name) {
                if (!name.empty()) {
                    VLOG(1) << connectionName << ": Upgrade success:";
                    VLOG(1) << connectionName << ":   Requested: " << req->get("upgrade");
                    VLOG(1) << connectionName << ":    Selected: " << name;
                    res->end();
                } else {
                    VLOG(1) << connectionName << ": Can not upgrade to any of '" << req->get("upgrade") << "'";
                    res->sendStatus(404);
                }
            });
        });
        tlsApp.get("/", [] APPLICATION(req, res) {
            if (req->url == "/" || req->url == "/index.html") {
                req->url = "/wstest.html";
            }
            VLOG(1) << CMAKE_CURRENT_SOURCE_DIR "/html" + req->url;
            res->sendFile(CMAKE_CURRENT_SOURCE_DIR "/html" + req->url, [req, res](int errnum) {
                if (errnum == 0) {
                    VLOG(1) << req->url;
                } else {
                    VLOG(1) << "HTTP response send file failed: " << std::strerror(errnum);
                    res->sendStatus(404);
                }
            });
        });
        tlsApp.listen(
            [instanceName = tlsApp.getConfig().getInstanceName()](const SocketAddress& socketAddress, const core::socket::State& state) {
                switch (state) {
                    case core::socket::State::OK:
                        VLOG(1) << instanceName << " listening on '" << socketAddress.toString() << "'";
                        break;
                    case core::socket::State::DISABLED:
                        VLOG(1) << instanceName << " disabled";
                        break;
                    case core::socket::State::ERROR:
                        VLOG(1) << instanceName << " " << socketAddress.toString() << ": " << state.what();
                        break;
                    case core::socket::State::FATAL:
                        VLOG(1) << instanceName << " " << socketAddress.toString() << ": " << state.what();
                        break;
                }
            });
        VLOG(1) << "Tls Routes:";
        for (std::string& route : legacyApp.getRoutes()) {
            route.erase(std::remove(route.begin(), route.end(), '$'), route.end());
            VLOG(1) << "  " << route;
        }
    }
    return express::WebApp::start();
}
References core::socket::State::DISABLED, express::Response::end(), core::socket::State::ERROR, core::socket::State::FATAL, express::Request::get(), core::socket::Socket< ConfigT >::getConfig(), core::socket::stream::SocketConnection::getConnectionName(), net::config::ConfigInstance::getInstanceName(), express::Router::getRoutes(), core::socket::stream::SocketContext::getSocketConnection(), express::Response::getSocketContext(), express::WebApp::init(), core::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT, Args >::listen(), core::socket::State::OK, express::Response::sendStatus(), express::WebApp::start(), net::in::SocketAddress::toString(), express::Response::upgrade(), express::Request::url, express::WebAppT< ServerT >::WebAppT(), and core::socket::State::what().